E2E: add connect to Portfolio
MetaMask/metamask-mobile pull request #10015
Opened 2024-06-17 04:33 UTC by chrisleewilcox

## **Description**
Automate scenario for connecting wallet to Portfolio by tapping on Portfolio button on Wallet view.

## **Related issues**

Related: https://github.com/MetaMask/mobile-planning/issues/1728

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-17 22:21 UTC, sethkfman commented on e2e/specs/wallet/portfolio-connect-account.spec.js
> +      //   await TabBarComponent.tapBrowser();
Remove commented code

2024-06-27 21:00 UTC, SamuelSalas commented
Regression test run: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/30a5abc2-fb48-4e25-937c-cccc647e018a
Smoke test run: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/c5e4593a-4174-4bdd-870d-75bd1c8c1e53

2024-06-27 21:07 UTC, SamuelSalas commented on e2e/specs/wallet/portfolio-connect-account.spec.js
> +      //   await TabBarComponent.tapBrowser();
Done

2024-06-27 21:46 UTC, cortisiko requested changes

2024-06-27 21:46 UTC, cortisiko commented on app/components/UI/Tokens/index.tsx
> +          testID={PORTFOLIO_BUTTON}
can we put this in a selector object?

2024-06-27 22:19 UTC, SamuelSalas commented on app/components/UI/Tokens/index.tsx
> +          testID={PORTFOLIO_BUTTON}
Done

2024-06-28 23:58 UTC, cortisiko approved these changes
🌮 🌮 🌮

2024-06-29 01:50 UTC, chrisleewilcox commented
@SamuelSalas looks good!

2024-06-29 12:39 UTC, merged