feat: new receive flow
MetaMask/metamask-mobile pull request #10061
Opened 2024-06-21 11:54 UTC by jonybur

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-26 23:12 UTC, jonybur commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +    navigation.navigate('QRTabSwitcher', {});
Make sure this redirects OK

2024-06-26 23:12 UTC, jonybur commented on app/components/UI/DrawerView/index.js
> +    this.props.navigation.navigate('QRTabSwitcher', {});
Make sure this redirects OK

2024-06-26 23:12 UTC, jonybur commented on app/components/UI/Navbar/index.js
> +    navigation.navigate('QRTabSwitcher', {});
Make sure this redirects OK

2024-06-26 23:13 UTC, jonybur commented on app/components/Views/ImportPrivateKey/index.tsx
> +    navigation.navigate('QRTabSwitcher', {});
Make sure this redirects OK

2024-06-26 23:14 UTC, jonybur commented on app/components/Views/QRScanner/index.tsx
> +      {/* <RNCamera
Uncomment this

2024-06-26 23:14 UTC, jonybur commented on app/components/Views/QRScanner/index.tsx
> +    <SafeAreaView style={styles.container}>
Can we swith this for a View?

2024-06-26 23:14 UTC, jonybur commented on app/components/Views/QRScanner/styles.ts
> +      backgroundColor: 'red',
Remove this

2024-06-26 23:14 UTC, jonybur commented on app/components/Views/QRScanner/styles.ts
> +      fontFamily: 'EuclidCircularB-Regular',
Remove this

2024-06-27 09:08 UTC, hesterbruikman commented
@yanrong-chen This is ready for your review. Please note that the QR got is not using dots as in the design. That would require a larger change.

2024-06-27 09:18 UTC, hesterbruikman commented
@plasmacorral This PR updates QR code scanning and makes it part of a shared 'Receive' and 'Scan' flow. Could we kindly ask for your support to test this update against key import scanning, keystone use, etc.?

2024-07-01 13:30 UTC, jonybur commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +    navigation.navigate('QRTabSwitcher', {});
Done

2024-07-01 13:31 UTC, jonybur commented on app/components/UI/DrawerView/index.js
> +    this.props.navigation.navigate('QRTabSwitcher', {});
Done

2024-07-16 21:53 UTC, jonybur commented on app/components/Views/QRTabSwitcher/styles.ts
> +  const navbarTop = height * 0.05 + 20;
This is the position of the navbar. This works on devices with the dynamic island and with devices without it (e.g. iPhone SE). Not sure if this is the correct way to implement this though, would like to get a second opinion.

2024-07-18 09:00 UTC, sahar-fehri commented on app/components/Views/QRAccountDisplay/index.tsx
> +      marginVertical: 32, // TODO: remove this when the component is no longer used in a modal
Does this still need to be removed?

2024-07-18 09:02 UTC, sahar-fehri commented on app/components/Views/QRTabSwitcher/index.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-explicit-any
Noticed there are few other TODO's relates to replacing "any" type in the code,

2024-07-18 09:32 UTC, salimtb commented on app/components/Views/QRAccountDisplay/index.tsx
> +const QRAccountDisplay = (props: { accountAddress: string }) => {
we should create a storybook for this new component

2024-07-18 09:35 UTC, salimtb commented on app/components/Views/QRTabSwitcher/index.test.tsx
> +  //   it('switch to ReceiveRequest screen when tab is clicked', () => {
i guess we should uncomment the tests here

2024-07-18 09:37 UTC, sahar-fehri commented
I've tested this component looks great 🎉

2024-07-18 09:38 UTC, salimtb commented on app/components/Views/QRAccountDisplay/index.tsx
> +  await ClipboardManager.setString(address);
for security purpose i think we should handle the case of promise rejected here , and send a appropriate error

2024-07-18 09:39 UTC, salimtb commented on app/components/Views/QRAccountDisplay/index.test.tsx
> +  });
can we add the test scenario of handle copy button

2024-07-18 09:45 UTC, salimtb commented on app/components/Views/QRAccountDisplay/index.tsx
> +  StyleSheet.create({
can we move the style to a separate file ?

2024-07-18 10:17 UTC, salimtb commented
getting the error below for a physical device ( iphone 14 ) 

https://github.com/user-attachments/assets/7175762a-2769-463b-9f36-19f39d5f4ec8

2024-07-18 10:17 UTC, salimtb commented
can we add an e2e test for this feature ?

2024-07-19 08:20 UTC, andreahaku reviewed
a few minor comments. thanks

2024-07-19 08:20 UTC, andreahaku commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +    navigation.navigate('QRTabSwitcher', {
please use `Routes.QR_TAB_SWITCHER` instead of the string

2024-07-19 08:20 UTC, andreahaku commented on app/components/UI/DrawerView/index.js
> +    this.props.navigation.navigate('QRTabSwitcher', {
please use `Routes.QR_TAB_SWITCHER` instead of the string

2024-07-19 08:20 UTC, andreahaku commented on app/components/UI/Navbar/index.js
> +    navigation.navigate('QRTabSwitcher', {
please use `Routes.QR_TAB_SWITCHER` instead of the string

2024-07-19 08:20 UTC, andreahaku commented on app/components/Views/ImportPrivateKey/index.tsx
> +    navigation.navigate('QRTabSwitcher', {
please use `Routes.QR_TAB_SWITCHER` instead of the string

2024-07-19 08:20 UTC, andreahaku commented on app/components/Views/WalletActions/WalletActions.tsx
> +      navigate('QRTabSwitcher', {
please use `Routes.QR_TAB_SWITCHER` instead of the string

2024-07-19 08:20 UTC, andreahaku commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +          navigation.navigate('QRTabSwitcher', {
please use `Routes.QR_TAB_SWITCHER` instead of the string

2024-07-19 08:20 UTC, andreahaku commented on app/components/UI/ReceiveRequest/index.js
> +  const { height: windowHeight } = Dimensions.get('window');
you can define the const outside of the style and use the width it for the QRCode size as well (line 231)

2024-07-19 08:20 UTC, andreahaku commented on app/components/Views/QRAccountDisplay/index.tsx
> +      <>
not needed

2024-07-19 08:20 UTC, andreahaku commented on app/components/Views/QRAccountDisplay/index.tsx
> +      <>
not needed

2024-07-23 12:27 UTC, jonybur commented on app/components/Views/QRAccountDisplay/index.tsx
> +  // TODO: handle warnings about seed phrase not backed up?
Removed

2024-07-24 08:40 UTC, mirceanis submitted a review, later dismissed
I spotted a few spots that cause build failures or warnings and I added a suggestion to adopt a component from the component library.
Please take a look

2024-07-24 08:40 UTC, mirceanis commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +import Routes from '../../constants/navigation/Routes.js';
This import is causing a build failure on Android. Removing the .js specifier fixes it.

```suggestion
import Routes from '../../constants/navigation/Routes';
```

2024-07-25 23:35 UTC, jonybur commented on app/components/Views/QRTabSwitcher/index.tsx
> +import Icon from 'react-native-vector-icons/Ionicons';
Done, please retest

2024-08-23 07:50 UTC, salimtb commented on app/components/Views/QRAccountDisplay/index.tsx
> +'use strict';
It would be more consistent with our other components if we name this file QRAccountDisplay.tsx instead of index.tsx. The same applies to the Storybook and style files.

2024-08-23 07:51 UTC, salimtb commented on app/components/Views/QRTabSwitcher/index.tsx
> +const QRTabSwitcher = () => {
same here regarding the name file

2024-08-23 09:53 UTC, EtherWizard33 commented on app/components/Views/QRAccountDisplay/index.tsx
> +'use strict';
yea, its expected to have a named folder, with the named component inside, and a barrel (index.ts) that exports it, with styles also having the name as well as type files, this came originally from @tommasini so tagging him here just in case he wants to chime in

 I include a screenshot of what seems to be the expected file naming convention
 
![2024-08-23 12 06 25](https://github.com/user-attachments/assets/531a601a-2f18-4a2e-aad7-305dd85324cb)

2024-08-23 09:53 UTC, EtherWizard33 commented on app/components/Views/QRAccountDisplay/index.tsx
> +  const styles = createStyles(theme);
I believe for performance since it memoizes the styles (useMemo) it is expected that new components should use useStyle from import { useStyles } from '../../../component-library/hooks'; there are examples in the app,

2024-08-23 09:53 UTC, EtherWizard33 commented on app/components/Views/QRAccountDisplay/index.tsx
> +
the video in the description was on Android or iOS, currently on iOS 

- from the receive flow, it closes when I click to scan (on first attempt was prompt for camera and have allowed it), but on subsequent it closes automatically, is this expected on iOS simulator?
- also on iOS simulator, from the icon on top right of the nav bar, the bottom sheet doesn't open, but bounces, is it expected?
<img width="350" alt="Screenshot 2024-04-18 at 3 56 43 PM" src="https://github.com/user-attachments/assets/36a58fd2-ff40-443d-937a-7ced48ebf98c">

2024-08-23 13:32 UTC, jpuri submitted a review, later dismissed
Changes in files owned by confirmations team look good 👍

2024-08-23 13:55 UTC, jonybur commented on app/components/Views/QRAccountDisplay/index.tsx
> +
@EtherWizard33 the camera won't open if you are using the simulator

2024-08-27 15:58 UTC, NicolasMassart reviewed
Some comments on the tests, but other parts seems good to me.

2024-08-27 15:58 UTC, NicolasMassart commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.test.tsx
> +  it('renders correctly', () => {
```suggestion
  it('render matches snapshot', () => {
```

2024-08-27 15:58 UTC, NicolasMassart commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.test.tsx
> +    expect(copyButton).toBeTruthy();
C: this only tests that the button is visible on the screen, not that the content was correctly copied in clipboard.

2024-08-27 15:58 UTC, NicolasMassart commented on app/components/Views/QRTabSwitcher/QRTabSwitcher.test.tsx
> +  it('not render tabber when disableTabber is true', () => {
```suggestion
  it('does not render tabber when disableTabber is true', () => {
```

2024-08-29 01:12 UTC, chrisleewilcox commented
@jonybur tested on my physical iOS device in dark mode and I am not able to see the unselected tab in the new Receive view and I can barely see the selected tab.  The close icon (x) is also barely visible.  At minimum can you make the unselected tab more visible?  

https://github.com/user-attachments/assets/866d0e8b-7e1f-4bab-8441-167f4a3739f8

This will also need to be verified on android devices.

2024-09-05 00:49 UTC, jonybur commented
@chrisleewilcox Please check out the latest commit; it adds dark mode support. I updated the images on the description of this PR. The X button does not support any color that is not black, so I increased its size. @mmragkandala please confirm if this would be OK.

2024-09-05 13:05 UTC, NicolasMassart submitted a review, later dismissed
Look good to me on the code side.
Haven't manually tested though, so requires QA.

2024-09-05 16:37 UTC, brianacnguyen commented on app/components/Views/QRTabSwitcher/styles.ts
> +        theme.themeAppearance === AppThemeKey.dark
Please use themed colors.background.alternative

2024-09-05 16:37 UTC, brianacnguyen commented on app/components/Views/QRTabSwitcher/styles.ts
> +          : theme.brandColors.white,
Please use themed colors.background.default

2024-09-06 15:31 UTC, tommasini commented on app/components/Views/QRTabSwitcher/QRTabSwitcher.test.tsx
> +    withNavigation: (obj: any) => obj,
We should aim to find solutions for this typescript issues and not use "any"

2024-09-06 15:32 UTC, tommasini commented on app/components/Views/QRTabSwitcher/QRTabSwitcher.tsx
> +            // @ts-expect-error proptypes issue
By this comment I'm not understanding the problem or the solution and why we are ignoring it, if the solution is out of scope, could you elaborate on it on the expect error description?

2024-09-06 15:33 UTC, tommasini commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.tsx
> +/* eslint @typescript-eslint/no-require-imports: "off" */
This two eslint rules doens't seem to need to be disabled anymore
```suggestion
```

2024-09-06 15:35 UTC, EtherWizard33 reviewed
currently a few checks are failing, lint, tags, smoke e2e needs to be re-ran, when I submit a PR for review I make sure all CI checks are green and the branch up to date

2024-09-06 15:36 UTC, tommasini commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.tsx
> +const copyAddressToClipboard = async (address: string) => {
Wondering if this could be a util function, I believe this is used on many places around the app! That seems an awesome improvement

2024-09-06 15:37 UTC, tommasini commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.tsx
> +const copyAddressToClipboard = async (address: string) => {
![image](https://github.com/user-attachments/assets/f9ddc108-40a7-427e-8f2f-72822d5484b1)
It seems we have multiple places using it indeed!
And the `showAlert` is an action of redux so it needs to be dispatched

2024-09-06 15:47 UTC, jonybur commented on app/components/Views/QRTabSwitcher/QRTabSwitcher.tsx
> +            // @ts-expect-error proptypes issue
NavbarTitle is a JS Proptypes component - because of this, until we refactor it into TS, we will have to ts-expect-error it

2024-09-06 15:58 UTC, jonybur commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.tsx
> +const copyAddressToClipboard = async (address: string) => {
https://github.com/user-attachments/assets/87fa1704-7646-43c3-83cc-b0caa7265b26

The functionality is currently working fine as per testing - both alert and copy. Are you sure this change is needed?

2024-09-06 16:00 UTC, jonybur commented on app/components/Views/QRTabSwitcher/QRTabSwitcher.test.tsx
> +    withNavigation: (obj: any) => obj,
Updated the type for this test

2024-09-09 11:13 UTC, NicolasMassart approved these changes, later dismissed
Looks good to me.

2024-09-09 13:36 UTC, EtherWizard33 commented on app/components/Nav/App/index.js
>  } from 'react-native';
on ios simulator after giving access to the camera, the modal either closes on expectedly and for the top right header button doesnt open, maybe specific to simulator?

<img width="350" alt="Screenshot 2024-04-18 at 3 56 43 PM" src="https://github.com/user-attachments/assets/a7d65a4e-9701-476a-8cdc-8d02d17bebe6">

2024-09-09 13:36 UTC, EtherWizard33 commented on app/components/UI/ReceiveRequest/index.js
> -                    this.props.metrics.trackEvent(
any chance this MetaMetricsEvents.RECEIVE_OPTIONS_QR_CODE needs to exist somewhere else in the new code? If not maybe it should be cleaned from the app/core/Analytics/MetaMetrics.events.ts file

2024-09-09 13:36 UTC, EtherWizard33 commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.tsx
> +'use strict';
looks like the status indicator, vertical alignment, the green dot is not aligned like in figma
<img width="350" alt="Screenshot 2024-04-18 at 3 56 43 PM" src="https://github.com/user-attachments/assets/9764f5ce-fa2a-4437-8a3e-fa0504669aad">

2024-09-09 13:39 UTC, jonybur commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.tsx
> +'use strict';
This is normal behaviour for the simulator

2024-09-09 13:39 UTC, jonybur commented on app/components/Nav/App/index.js
>  } from 'react-native';
This is normal behaviour on the simulator

2024-09-09 13:41 UTC, jonybur commented on app/components/UI/ReceiveRequest/index.js
> -                    this.props.metrics.trackEvent(
It is used in `ReceiveRequest/index.js`, line `236`

2024-09-09 14:07 UTC, EtherWizard33 commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.tsx
> +'use strict';
updated the screenshot to show the status indicator

2024-09-09 14:39 UTC, jonybur commented on app/components/UI/ReceiveRequest/index.js
> -                    this.props.metrics.trackEvent(
I removed it because this modal does not exist anymore. I can rewire `RECEIVE_OPTIONS_QR_CODE` to trigger whenever the ReceiveRequest (which contains the QR Code) is rendered.

2024-09-09 14:47 UTC, jonybur commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.tsx
> +'use strict';
This is out of scope for this ticket; that component `NavbarTitle` has been unchanged by this PR.

2024-09-09 16:40 UTC, tommasini commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.test.tsx
> +import initialBackgroundState from '../../../util/test/initial-background-state.json';
```suggestion
import backgroundState from '../../../util/test/initial-root-state';
```

Not sure if the path is correct, but it would be awesome if we remove the `ts-expect-error` at this test file. And now for a better typing experience we are importing the backgroundState from the `initial-root-state`

2024-09-09 16:50 UTC, tommasini commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.tsx
> +const copyAddressToClipboard = async (address: string) => {
On the part converting this function to a util function is a good to have on my eyes.

On the part that we need to dispatch the `showAlert` function I'm sure we need to dispatch it instead of leaving it this way. [Dispatching](https://redux.js.org/tutorials/fundamentals/part-2-concepts-data-flow#dispatch) is the correct way to update the state of redux when we need to trigger an event!

Most likely if you want to refactor this you can take a look on how Redux Toolkit is used on our app and create a slice for the alerts (This is also a good to have, but not a blocker)

2024-09-09 16:52 UTC, tommasini commented on app/components/Views/QRScanner/index.test.tsx
> +      // @ts-expect-error props are not passed to QrScanner
Through this comment I'm not understanding why the type couldn't be fixed, could you elaborate?

2024-09-09 16:57 UTC, tommasini commented on app/components/Views/QRScanner/styles.ts
> +      backgroundColor: colors.overlay,
We do not need to import colors at the styles file, since they are passed on the theme object
```suggestion
      backgroundColor: theme.colors.background,
```

2024-09-09 16:58 UTC, tommasini commented on app/components/Views/QRTabSwitcher/QRTabSwitcher.test.tsx
> +    // @ts-expect-error useRoute doesn't have mockReturnValue
If doens't have, can we add it instead of ignoring the error?

2024-09-09 17:03 UTC, tommasini commented on app/styles/common.ts
> +  overlay: 'rgba(242, 244, 246, 0.33)',
We do not need the `overlay` as mentioned above we have it on the `theme` object!

I can't find the overlayText, could you check with @brianacnguyen if we are missing from where we should import it?

2024-09-09 17:49 UTC, jonybur commented on app/components/Views/QRTabSwitcher/QRTabSwitcher.test.tsx
> +    // @ts-expect-error useRoute doesn't have mockReturnValue
I'd rather not go out of the scope for this ticket

2024-09-09 17:51 UTC, jonybur commented on app/components/Views/QRScanner/index.test.tsx
> +      // @ts-expect-error props are not passed to QrScanner
The way QrScanner needs to be passed to renderScreen throws a ts error since it doesn't allow for props passing to happen

2024-09-09 17:56 UTC, jonybur commented on app/styles/common.ts
> +  overlay: 'rgba(242, 244, 246, 0.33)',
Unused, removing

2024-09-09 18:07 UTC, jonybur commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.test.tsx
> +import initialBackgroundState from '../../../util/test/initial-background-state.json';
I agree it would be awesome, let's do it in a later interation

2024-09-09 18:08 UTC, jonybur commented on app/components/Views/QRScanner/styles.ts
> +      backgroundColor: colors.overlay,
We actually do, since these colors are not theme-constrained

2024-09-09 18:25 UTC, NicolasMassart commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.test.tsx
> +import initialBackgroundState from '../../../util/test/initial-background-state.json';
I think using backgroundState from initial-root-state is in the scope as this is the new way to test with state.

2024-09-09 18:32 UTC, NicolasMassart commented on app/components/Views/QRScanner/styles.ts
> +      backgroundColor: colors.overlay,
Should we modify the theme?

2024-09-09 18:32 UTC, NicolasMassart commented on app/components/Views/QRScanner/index.test.tsx
> +      // @ts-expect-error props are not passed to QrScanner
So you may use renderWithProvider instead?

2024-09-09 18:32 UTC, NicolasMassart commented on app/components/Views/QRTabSwitcher/QRTabSwitcher.test.tsx
> +    // @ts-expect-error useRoute doesn't have mockReturnValue
It's in the scope, it's just tweaking your test mock.

2024-09-09 19:50 UTC, jonybur commented on app/components/Views/QRTabSwitcher/QRTabSwitcher.test.tsx
> +    // @ts-expect-error useRoute doesn't have mockReturnValue
useRoute was not implemented by this ticket, and the ts-expect-error was introduced as part of the `lint:tsc` step. I don't think that modifying useRoute/typing it should be part of this PR.

2024-09-09 19:50 UTC, jonybur commented on app/components/Views/QRScanner/styles.ts
> +      backgroundColor: colors.overlay,
Isn't the theme constrained by dark/light modes?

2024-09-09 19:56 UTC, jonybur commented on app/components/Views/QRScanner/index.test.tsx
> +      // @ts-expect-error props are not passed to QrScanner
Updated

2024-09-09 19:59 UTC, jonybur commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.test.tsx
> +import initialBackgroundState from '../../../util/test/initial-background-state.json';
Just implemented it

2024-09-10 12:14 UTC, EtherWizard33 submitted a review, later dismissed
This PR looks good to me! One tiny suggestion I have is regarding the network status indicator's vertical alignment. If we don't tackle it in this PR, it might be a good idea to open a UI/UX issue to ensure we get it just right.

Other than that, nice job!

2024-09-11 01:26 UTC, jonybur commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.tsx
> +const copyAddressToClipboard = async (address: string) => {
This is working as-is, therefore the action is being dispatched somehow; otherwise the demo I sent earlier wouldn't be working. This might be due to some configuration on the sagas or the thunk.

2024-09-11 01:34 UTC, jonybur commented on app/components/UI/ReceiveRequest/index.js
> -                    this.props.metrics.trackEvent(
I discussed with Hester and we decided to do this after merging this PR

2024-09-11 01:46 UTC, jonybur commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.tsx
> +const copyAddressToClipboard = async (address: string) => {
Actually the reason why this is working is because the alert that is not being dispatched shouldnt be dispatched at all, we shouldn't have that alert. It is a remanent of old code; I removed it.

2024-09-11 15:21 UTC, jonybur commented on app/components/Views/QRTabSwitcher/QRTabSwitcher.tsx
> +export enum Screens {
@tommasini, I’ve made the change you requested, but I think it’s worth noting that blocking this feature further over minor details isn’t ideal. If there are more nits you consider to be necessary and blocking, could we get them all out at once? It would make things smoother and avoid dragging out the process.

From a process perspective, holding up a feature over small issue doesn’t seem productive. As you know, the repo itself has a lot of instability—flaky tests, CI problems, and things like the `audit` issue we just dealt with. Delaying the feature means more frequent rebasing (sometimes with conflicts), which only adds to the instability since I have to continuously keep rebuilding and retesting the feature.

That aside, some of the feedback seems out of scope, like fixing unrelated components, tests, or config files that aren't tied to this specific feature. Those things are better tackled in separate tasks or PRs.

2024-09-11 15:25 UTC, EtherWizard33 approved these changes, later dismissed

2024-09-11 15:35 UTC, jonybur commented on app/components/Views/QRTabSwitcher/QRTabSwitcher.test.tsx
> +    // @ts-expect-error useRoute doesn't have mockReturnValue
The issue being thrown is:
```
Property 'mockReturnValue' does not exist on type '<T extends RouteProp<ParamListBase, string>>() => T'.ts(2339)
```
I have casted this to jest.Mock to fix this ts-lint issue.

2024-09-11 15:39 UTC, jonybur commented
@tommasini, I’ve made the change you requested, but I think it’s worth noting that blocking this feature further over minor details isn’t ideal. If there are more nits you consider to be necessary and blocking, could we get them all out at once? It would make things smoother and avoid dragging out the process.

From a process perspective, holding up a feature over a small issue (such as renaming a variable, renaming a test, modifying a comment) doesn’t seem productive. As you know, the repo itself has a lot of instability—flaky tests, CI problems, and things like the audit issue we just dealt with. Delaying the feature means more frequent rebasing (sometimes with conflicts), which only adds to the instability since I have to continuously keep rebuilding and retesting the feature.

That aside, some of the feedback seems out of scope, like fixing unrelated components, tests, or config files that aren't tied to this specific feature. Those things are better tackled in separate tasks or PRs.

2024-09-11 16:17 UTC, brianacnguyen approved these changes, later dismissed
Approved changes regarding close svg update

2024-09-11 17:22 UTC, tommasini commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.test.tsx
> +      // @ts-expect-error initialBackgroundState throws error
NIT: (feel free to solve this conversation and address this issue on a separate PR)

Accordingly to typescript docs guidelines: https://github.com/MetaMask/contributor-docs/blob/main/docs/typescript.md

"@ts-expect-error usage should generally be reserved to situations where an error is the intended or expected result of an operation, not to silence errors when the correct typing solution is difficult to find."

I didn't checkout this branch, but I believe this issue is because we are importing initialBackgroundState from the json file and not from [initial-root-state file](https://github.com/MetaMask/metamask-mobile/blob/b5fa36242919e03f7820434b0534783dd86e1aa1/app/util/test/initial-root-state.ts#L14) like for example [here](https://github.com/MetaMask/metamask-mobile/blob/72339d1045c4a2ad4c107710ec0be73991ee1e03/app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.test.tsx#L13)

2024-09-12 08:40 UTC, EtherWizard33 submitted a review, later dismissed
re-approving for my previous approval that seem to have been reset by [b5763ff](https://github.com/MetaMask/metamask-mobile/commit/b5763ff8be8687b7b969a3dd9d4879cea4359e3e)

2024-09-16 09:25 UTC, NicolasMassart commented on app/components/Views/QRScanner/index.test.tsx
>    it('should render correctly', () => {
```suggestion
  it('render matches snapshot', () => {
```

2024-09-16 09:26 UTC, NicolasMassart submitted a review, later dismissed
Looks good to me.
I fixed an committed a test name before approval not to block you.

2024-09-16 10:00 UTC, Jonathansoufer requested changes
Left some comments/doubts.

2024-09-16 10:00 UTC, Jonathansoufer commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.tsx
> +  const handleCopyButton = async () => {
This is more into the UX of the app. In all the other places we copy address, we use a specific UI for feedback. Why are you using toast here, instead?

![Screenshot 2024-09-16 at 10 56 48](https://github.com/user-attachments/assets/16e8aaad-dfc4-4649-b266-f0fb161b2ed2)
![Screenshot 2024-09-16 at 10 57 00](https://github.com/user-attachments/assets/ac180bb3-16eb-4785-a28f-d0a1fd306a58)

2024-09-16 10:16 UTC, jonybur commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.tsx
> +  const handleCopyButton = async () => {
Hi @Jonathansoufer, this is as per the design. Perhaps @mmragkandala can answer this better.

2024-09-16 14:10 UTC, jonybur commented on app/core/RPCMethods/RPCMethodMiddleware.ts
>              // TODO: Replace "any" with type
This TODO seems to have been set by a different developer several months ago, do we want to include this as part of the work of this PR?

2024-09-16 14:14 UTC, jonybur commented on app/components/Views/QRAccountDisplay/QRAccountDisplay.tsx
> +  const handleCopyButton = async () => {
Please refer to: https://www.figma.com/design/7FrkC3HDPP9K4NYZ8oOi5J/Scan-%2F-Show-QR-code?node-id=0-1&node-type=canvas&t=2yM5RQTA9nD6WU2w-0

2024-09-16 15:25 UTC, EtherWizard33 approved these changes, later dismissed
re-approving my previous approval that had been reset

2024-09-16 16:10 UTC, EtherWizard33 submitted a review, later dismissed

2024-09-17 07:24 UTC, NicolasMassart approved these changes, later dismissed
Looks good to me.

2024-09-17 10:59 UTC, Jonathansoufer submitted a review, later dismissed
LGTM!

2024-09-17 11:22 UTC, Jonathansoufer submitted a review, later dismissed
Re-approving due 577a5903fa7d462234f714674dc7f01503ba488b

2024-09-17 14:49 UTC, brianacnguyen submitted a review, later dismissed

2024-09-18 10:14 UTC, chrisleewilcox approved these changes
QA Passed

2024-09-18 11:57 UTC, EtherWizard33 approved these changes

2024-09-18 13:58 UTC, merged

2024-09-23 20:40 UTC, wachunei commented on app/components/UI/ReceiveRequest/index.js
>    onBuy = async () => {
@jonybur  Line 334 was removed, it had the button that invoked this method, this method is now unreachable. It should be removed.