feat: add dApp spam screen
MetaMask/metamask-mobile pull request #10082
Opened 2024-06-24 12:50 UTC by OGPoyraz

## **Description**

This PR aims to add dApp spam screen to app. 

Notes:
- Data will not be persisted after close & reopening app
- If there is 30 seconds between user rejections, it's not considered as spam by default.
- Every 3 rejection will make modal appear as decided

## **Related issues**

Fixes: https://github.com/MetaMask/MetaMask-planning/issues/1822 

## **Manual testing steps**

1. Go to test-dapp
2. Trigger 3x sign/transaction
3. See modal appear
4. Click "continue" to ignore this modal and behaviour
5. Trigger 3x sign/transaction
6. Click "block dapp" & "got it"
7. Try sign/transaction - they will be blocked without error since they are considered & marked as "spam" by user
8. Wait 1 minute to trigger or reset the situation

## **Screenshots/Recordings**

https://github.com/MetaMask/metamask-mobile/assets/7644512/b2528e12-eef9-4ec8-9d56-64f6af19aba9

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-24 13:00 UTC, OGPoyraz commented on app/components/Views/DappSpamModal/DappSpamModal.test.tsx
> +  '../../../component-library/components/BottomSheets/BottomSheet',
`BottomSheet` component causes different issues in the rendering with `SafeAreaProvider`. This is the simplest fix that I found in order to avoid proving `SafeAreaProvider` and others.

2024-06-24 15:42 UTC, sleepytanya commented
Tested on physical device:
Bitrise build https://app.bitrise.io/build/088916f8-1921-44eb-b6fd-fa82780127bb?tab=artifacts
Samsung S24+
Android 14

https://github.com/MetaMask/metamask-mobile/assets/104780023/2fdb474f-1d4c-4cda-b549-6f487dbeb0e3

2024-06-25 13:53 UTC, matthewwalsh0 commented on app/components/Views/DappSpamModal/DappSpamModal.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(DappSpamModal);
I understood the `connect` and `mapStateToProps` functions to be deprecated in favour of `useSelector` and `useDispatch` since this is a functional component.

2024-06-25 13:53 UTC, matthewwalsh0 commented on app/components/Views/DappSpamModal/DappSpamModal.tsx
> +  handleCloseModal,
Since these are properties, is the standard to be `onX` rather than `handleX`?

2024-06-25 13:53 UTC, matthewwalsh0 commented on locales/languages/en.json
> +    "description": "The site has sent you multiple requests. It might be a scam site trying to steal your assets by sending multiple requests. Do you want to disconnect from the site?",
Does this also need to make the user aware they are blocking the site also?

Are we disconnecting the origin, or just preventing new requests?

2024-06-25 13:53 UTC, matthewwalsh0 commented on locales/languages/en.json
> +    "site_blocked_description": "Site is blocked for 1 minute for sending requests.",
```suggestion
    "site_blocked_description": "Site is blocked from sending requests for 1 minute.",
```

2024-06-25 13:53 UTC, matthewwalsh0 commented on app/core/redux/slices/dappSpamFilter/index.ts
In the long run, all of this blocking state and logic could be folded into the `ApprovalController` to avoid duplication in both clients, but this seems like a logical MVP.

2024-06-25 13:53 UTC, matthewwalsh0 commented on app/core/redux/slices/dappSpamFilter/index.ts
> +        currentTime - currentState.lastRejection <
Minor, but could this instead be in the form:

```
const isUnderThreshold = ...

newRejections = isUnderThreshold ? newRejections + 1 : 1;
```

2024-06-25 13:53 UTC, matthewwalsh0 commented on app/core/redux/slices/dappSpamFilter/index.ts
> +        newSpamPrompt = true;
Rather than deriving this in the reducer, is it cleaner to provide a selector such as `selectOriginAtSpamThreshold` so the UI or middleware can ask the state and make its own decision?

2024-06-25 13:53 UTC, matthewwalsh0 commented on app/core/redux/slices/dappSpamFilter/index.ts
> +    resetDappSpamState: (
Minor, but line breaks?

2024-06-25 13:53 UTC, matthewwalsh0 commented on app/core/RPCMethods/utils.ts
> +export const BLOCKABLE_SPAM_RPC_METHODS = new Set([
For modularity sake, should we put all this new logic and constants into a separate file such as `spam.ts`?

2024-06-25 13:53 UTC, matthewwalsh0 commented on app/core/RPCMethods/RPCMethodMiddleware.test.ts
Given the impact here, should we have a unit test to verify the new logic?

2024-06-25 13:53 UTC, matthewwalsh0 commented on app/core/redux/slices/dappSpamFilter/index.ts
Probably personal preference, but in a technical sense, would this be more explicit called something like `originThrottling` or `dappThrottling`?

2024-06-26 08:44 UTC, OGPoyraz commented on locales/languages/en.json
> +    "description": "The site has sent you multiple requests. It might be a scam site trying to steal your assets by sending multiple requests. Do you want to disconnect from the site?",
Good call, I've implemented as it just prevent new requests, I will double check this with Barbara.

But regardless of that, copies are subject to change, still waiting for confirmation.

2024-06-26 08:45 UTC, OGPoyraz commented on app/components/Views/DappSpamModal/DappSpamModal.tsx
> +  handleCloseModal,
Done in https://github.com/MetaMask/metamask-mobile/pull/10082/commits/4a866a5073e247d480bf6082ade4befdacd09aef

2024-06-26 08:55 UTC, OGPoyraz commented on app/components/Views/DappSpamModal/DappSpamModal.tsx
> +export default connect(mapStateToProps, mapDispatchToProps)(DappSpamModal);
Done in https://github.com/MetaMask/metamask-mobile/pull/10082/commits/72f6006cfbad7259792a73eaa174967f7accebb4

2024-06-26 08:56 UTC, OGPoyraz commented on locales/languages/en.json
> +    "site_blocked_description": "Site is blocked for 1 minute for sending requests.",
Applied this

2024-06-26 09:01 UTC, OGPoyraz commented on app/core/redux/slices/dappSpamFilter/index.ts
That's right. 

In such implementation would you rather to have this state in the `ApprovalController` or it's own controller?

2024-06-26 09:04 UTC, OGPoyraz commented on app/core/redux/slices/dappSpamFilter/index.ts
> +        currentTime - currentState.lastRejection <
Done in https://github.com/MetaMask/metamask-mobile/pull/10082/commits/c214a1cb9d38bd295113e4ff08549bcb4767569c

2024-06-26 09:40 UTC, OGPoyraz commented on app/core/redux/slices/dappSpamFilter/index.ts
> +        newSpamPrompt = true;
Removed this in https://github.com/MetaMask/metamask-mobile/pull/10082/commits/7cdd476592586a194bda426fe5b0be22770d7694

2024-06-26 09:44 UTC, OGPoyraz commented on app/core/RPCMethods/utils.ts
> +export function validateDappRequestAgainstSpam({
Done in https://github.com/MetaMask/metamask-mobile/pull/10082/commits/5dd6d010fec554b86f5fd3d2571a48e6623e68e9

2024-06-26 09:44 UTC, OGPoyraz commented on app/core/RPCMethods/utils.ts
> +export function processDappSpamRejection({
Done in https://github.com/MetaMask/metamask-mobile/pull/10082/commits/5dd6d010fec554b86f5fd3d2571a48e6623e68e9

2024-06-26 09:46 UTC, OGPoyraz commented on app/core/redux/slices/dappSpamFilter/index.ts
> +    resetDappSpamState: (
Done in https://github.com/MetaMask/metamask-mobile/pull/10082/commits/5dd6d010fec554b86f5fd3d2571a48e6623e68e9

2024-06-26 09:50 UTC, OGPoyraz commented on app/core/RPCMethods/utils.ts
> +export const BLOCKABLE_SPAM_RPC_METHODS = new Set([
Done in https://github.com/MetaMask/metamask-mobile/pull/10082/commits/d766d807a3b4cb787ef578b593341b5d33e24350

2024-06-26 09:54 UTC, OGPoyraz commented on app/core/RPCMethods/utils.ts
> +  if (
Done in https://github.com/MetaMask/metamask-mobile/pull/10082/commits/f42740ec8c9d1e88887d1b21a2a23e84be777132

2024-06-26 10:20 UTC, OGPoyraz commented on app/core/redux/slices/dappSpamFilter/index.ts
Done in https://github.com/MetaMask/metamask-mobile/pull/10082/commits/89255c0f23b41c605ec769facbfb174f7c7c67de

Renamed this to `originThrottling` and all `domain` references to `origin`

2024-06-26 10:34 UTC, OGPoyraz commented on app/core/RPCMethods/utils.ts
> +        'Request blocked as the user identified it as spam.',
I think we can introduce a new error code in future here https://github.com/MetaMask/rpc-errors/blob/main/src/error-constants.ts

For now I am going to throw an custom `unauthorized` error as suggested in https://github.com/MetaMask/rpc-errors

2024-06-26 10:34 UTC, OGPoyraz commented on app/core/RPCMethods/utils.ts
> +      const error = new Error('Request blocked due to active spam modal.');
https://github.com/MetaMask/metamask-mobile/pull/10082/files/aaca51b3a2d0d63fec868541f148fe61f26f7803#r1654561022

2024-06-26 12:00 UTC, OGPoyraz commented on app/core/RPCMethods/RPCMethodMiddleware.test.ts
Added basic tests in https://github.com/MetaMask/metamask-mobile/pull/10082/commits/6e4c3377cc4886a0e7ba16fbc7997936d8369e75

2024-06-26 23:24 UTC, OGPoyraz commented on locales/languages/en.json
> +    "description": "The site has sent you multiple requests. It might be a scam site trying to steal your assets by sending multiple requests. Do you want to disconnect from the site?",
As Barbara mentioned, we are not disconnecting user from dApp, just prevent incoming RPC requests.

2024-07-10 21:22 UTC, sleepytanya commented
@OGPoyraz 
Bitrise build https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/2444e26c-326d-4463-9405-5fe5d3fa58de?tab=artifacts

I see different modal (Android):



https://github.com/MetaMask/metamask-mobile/assets/104780023/f4a189c5-7424-48b3-9820-047e158a1e8c



![Screenshot_20240710_171213_MetaMask-QA](https://github.com/MetaMask/metamask-mobile/assets/104780023/6819f38c-baea-4622-aa41-91ebd3caf0a0)

2024-07-10 21:32 UTC, OGPoyraz commented
Sorry for the confusion @sleepytanya 
That is actually the correct modal, the content of the modal changed a bit since I opened the PR. 

But it looks like title of modal doesnt seem to shown properly on small devices. I will take care of that soon.

2024-07-11 04:47 UTC, jpuri submitted a review, later dismissed
🚀

2024-07-11 06:58 UTC, matthewwalsh0 submitted a review, later dismissed

2024-07-11 06:58 UTC, matthewwalsh0 commented on app/core/RPCMethods/spam.ts
> +    if (selectOriginAtSpamThreshold(store.getState(), req.origin)) {
Minor, but can we use two early returns here to avoid the nesting?

2024-07-11 06:58 UTC, matthewwalsh0 commented on app/core/redux/slices/originThrottling/index.ts
> +export const isDappBlockedForRPCRequests = (
Minor, but ideally all selectors start with `selectX` even the boolean ones?

2024-07-11 06:58 UTC, matthewwalsh0 commented on app/core/redux/slices/originThrottling/index.ts
> +const ONE_MINUTE_IN_MS = 60000;
Minor, but should we call this `BLOCKING_THRESHOLD_IN_MS` for clarity?

2024-07-11 07:36 UTC, OGPoyraz commented
@sleepytanya I addressed the not wrapping text on your device. Here is the screenshot of it
PS: I just make that string longer to replicate issue, not a real one

![Screenshot 2024-07-11 at 09 32 46](https://github.com/MetaMask/metamask-mobile/assets/7644512/0146434d-9193-4b68-9b33-da248ea18afa)

2024-07-11 07:36 UTC, OGPoyraz commented on app/core/RPCMethods/spam.ts
> +    if (selectOriginAtSpamThreshold(store.getState(), req.origin)) {
Done

2024-07-11 07:36 UTC, OGPoyraz commented on app/core/redux/slices/originThrottling/index.ts
> +export const isDappBlockedForRPCRequests = (
Done

2024-07-11 07:36 UTC, OGPoyraz commented on app/core/redux/slices/originThrottling/index.ts
> +const ONE_MINUTE_IN_MS = 60000;
Done

2024-07-11 11:35 UTC, OGPoyraz commented on app/core/redux/slices/originThrottling/index.ts
> -export const selectOriginAtSpamThreshold = (
Essentially this was doing the same thing with `selectOriginBlockedForRPCRequests` hence I removed this.

2024-07-11 11:38 UTC, OGPoyraz commented on app/core/RPCMethods/spam.ts
> -  const hasActiveSpamPrompt = selectOriginAtSpamThreshold(appState, req.origin);
This case was not possible to reach out because `isDappBlocked` will always be `true`.
Since it's useless for spammer origin to determine either it's "user blocked" or "active spam modal", I removed this and make generic `SPAM_FILTER_ACTIVATED` error.

2024-07-11 12:24 UTC, matthewwalsh0 submitted a review, later dismissed

2024-07-11 15:58 UTC, digiwand requested changes
Nice feature and implementation!

one thing, wanted to double-check validateOriginThrottling will not break the app if it throws

2024-07-11 15:58 UTC, digiwand commented on app/core/redux/slices/originThrottling/index.ts
> +export const selectOriginBlockedForRPCRequests = (
[minor nit] what if we renamed this to `selectIsOriginBlockedForRPCRequests`? this would help indicate that the method returns a boolean

2024-07-11 15:58 UTC, digiwand commented on app/core/redux/slices/originThrottling/index.ts
> +  const isWithinOneMinute =
[nit] this is susceptible to being stale if BLOCKING_THRESHOLD_IN_MS is updated. Possibly we could update this to `isWithinBlockingThreshold`, or rename `BLOCKING_THRESHOLD_IN_MS` to `MINUTE_IN_MS`. We could also use `isWithinBlockingThreshold` for this suggestion

2024-07-11 15:58 UTC, digiwand commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +    validateOriginThrottling({ req, store });
did we want to move this into the try block?

2024-07-11 16:02 UTC, OGPoyraz commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +    validateOriginThrottling({ req, store });
We don't want to catch any error here, that's the whole point of rejecting validating/throwing error in the middleware.

2024-07-11 16:04 UTC, OGPoyraz commented on app/core/redux/slices/originThrottling/index.ts
> +  const isWithinOneMinute =
This is recently changed to the `BLOCKING_THRESHOLD_IN_MS`. 
https://github.com/MetaMask/metamask-mobile/pull/10082#discussion_r1673505654

2024-07-11 16:16 UTC, sleepytanya commented
@OGPoyraz 

Not sure if the Sign Typed Data is expected not to be blocked by the spam modal. Also Sign Typed Data does not trigger the spam modal no matter how many times you initiate the signature.

Bitrise build: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/0863dcb0-6a87-4499-9f55-7eb08a773671?tab=artifacts


https://github.com/MetaMask/metamask-mobile/assets/104780023/ad2d537e-02ba-4d4f-b69e-f1c17e393ec2

2024-07-11 16:16 UTC, digiwand commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +    validateOriginThrottling({ req, store });
I see now. right. I also see we throw the error again in the catch statement too. Thanks for the explanation!

2024-07-11 16:17 UTC, digiwand submitted a review, later dismissed
Lgtm! Could be good to merge after addressing the Sign Typed concern above

2024-07-11 16:21 UTC, OGPoyraz commented on app/core/redux/slices/originThrottling/index.ts
> +export const selectOriginBlockedForRPCRequests = (
Good call, I never underestimate any nit that contributes to readability 
Done in https://github.com/MetaMask/metamask-mobile/pull/10082/commits/33182e1912afab4c8b3845bae5b90db6b211ccde

2024-07-11 16:51 UTC, digiwand submitted a review, later dismissed

2024-07-11 16:53 UTC, digiwand commented on app/core/redux/slices/originThrottling/index.ts
> +  const isWithinOneMinute =
oh I see. conflicting opinions. possibly it makes sense to update `isWithinOneMinute` → `isWithinBlockingThreshold` for the reason mentioned above

2024-07-11 17:32 UTC, sleepytanya commented
Bitrise build: https://app.bitrise.io/build/12ba9420-efb0-4e6b-9e49-61f4276eb3fa?tab=artifacts

Works great!
All types of transactions, including approvals, signatures when spammed successfully trigger the spam modal and all type of transactions successfully blocked for 1 minute.


https://github.com/MetaMask/metamask-mobile/assets/104780023/18f3399a-4999-403e-97b5-d4c12cf902bb

2024-07-12 15:27 UTC, matthewwalsh0 approved these changes, later dismissed

2024-07-17 11:46 UTC, OGPoyraz commented on app/core/RPCMethods/spam.ts
> +  if (selectIsOriginBlockedForRPCRequests(store.getState(), req.origin)) {
I am not sure what do you mean @Cal-L 
The dispatch above sets some state and selector is checking if the certains are in place. 
What do you mean `it's extremely rare for dispatch to fail.`?

2024-07-18 15:46 UTC, Cal-L commented on app/core/RPCMethods/spam.ts
> +  if (selectIsOriginBlockedForRPCRequests(store.getState(), req.origin)) {
My question was referring to if line 85 is checking that line 83 succeeds. For example, line 83 would update redux and it seems that line 85 is grabbing that same set of data from redux?

2024-07-19 12:51 UTC, OGPoyraz commented on app/core/RPCMethods/spam.ts
> +  if (selectIsOriginBlockedForRPCRequests(store.getState(), req.origin)) {
@Cal-L thanks for the clarification, you're right, 83 updates some states and 85 checks certain conditions are met after that update on same state part. So this is why I directly used `store` reference in that condition.

2024-07-19 12:54 UTC, OGPoyraz commented on app/core/RPCMethods/spam.ts
> +  if (selectIsOriginBlockedForRPCRequests(store.getState(), req.origin)) {
We didn't want to check this condition in the `onRPCRequestRejectedByUser ` because it's purely updating part, and middleware can decide later what to do. In this case, it navigates a new page.

2024-07-23 16:45 UTC, Cal-L commented on app/core/RPCMethods/spam.ts
> +  if (selectIsOriginBlockedForRPCRequests(store.getState(), req.origin)) {
We don't need to check since we can assume that the redux update succeeds. We can remove the check condition and just navigate since that's always the expected behavior right?

2024-07-24 08:29 UTC, OGPoyraz commented on app/core/RPCMethods/spam.ts
> +  if (selectIsOriginBlockedForRPCRequests(store.getState(), req.origin)) {
Sorry for the confusion @Cal-L ,
Navigating to spam modal is not always expected, `selectIsOriginBlockedForRPCRequests` is checking if it's rejected 3 times and within 1 minute window, please see it's implementation. So this condition should be in place here.

2024-07-25 16:49 UTC, Cal-L approved these changes
LGTM

2024-07-25 16:49 UTC, Cal-L commented on app/core/RPCMethods/spam.ts
> +  if (selectIsOriginBlockedForRPCRequests(store.getState(), req.origin)) {
Ahh ok, thanks for clarifying. This makes sense

2024-07-26 08:34 UTC, merged