feat: add increase decrease token percentage
MetaMask/metamask-mobile pull request #10144
Opened 2024-06-27 14:14 UTC by salimtb

## **Description**

This pull request introduces a new feature to the MetaMask mobile that enhances user experience by displaying the percentage increase or decrease for each token directly within the UI. This update aims to provide users with immediate visual feedback on the performance of their tokens, helping them make more informed decisions based on recent market trends.

core PR: https://github.com/MetaMask/core/pull/4206
figma: https://www.figma.com/design/aMYisczaJyEsYl1TYdcPUL/Wallet-Assets?node-id=1620-23897&t=EJSzfKoFvTJ5LuK0-0

## **Related issues**

Fixes: #9635 

## **Manual testing steps**

1. Go to the wallet view
2. You should see the percentage of increase/decrease

## **Screenshots/Recordings**

### **Before**

<img width="487" alt="Screenshot 2024-05-15 at 16 54 25" src="https://github.com/MetaMask/metamask-mobile/assets/26223211/5b165737-4150-4ca7-83a3-3cb667b6f4a6">

### **After**
![Screenshot 2024-05-15 at 16 39 31](https://github.com/MetaMask/metamask-mobile/assets/26223211/3792f1d2-6300-4cad-ad5a-6c49e1697773)

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-07-01 13:25 UTC, tommasini submitted a review, later dismissed
LGTM! This is awesome!

2024-07-01 13:58 UTC, EtherWizard33 commented
Nice feature, the description says 'percentage increase or decrease'.

The following may be obvious for power users already... it's just a thought.
When we talked about this feature together I believe we confirmed it's the daily increase in value, yet I was curious to know if the user has a way to find this information by himself, and when does a day start and end, is it a 24h rolling window, or does it reset at midnight utc?

2024-07-01 14:48 UTC, EtherWizard33 commented on app/component-library/components-temp/Price/AggregatedPercentage/AggregatedPercentage.tsx
> +  const styles = createStyles(colors);
might interesting to use useStyle, because of it's useMemo that memoizes the depenencies the styles may have on theme and color

2024-07-01 14:50 UTC, EtherWizard33 commented on app/component-library/components-temp/Price/AggregatedPercentage/AggregatedPercentage.tsx
> +const createStyles = (colors: Colors) =>
I believe platform wishes to promote to keep files in a style file, with a name pattern like AggregatePercentage.style.ts

2024-07-01 15:11 UTC, EtherWizard33 approved these changes, later dismissed
LGTM, I left some comments for small refactorings just in case some other changes are required then maybe these could also be bundled with them.

2024-07-01 21:11 UTC, salimtb commented
hey @cortisiko , you can find below the requested test

Uploading Screen Recording 2024-07-01 at 23.09.50.mov…

2024-07-02 10:34 UTC, salimtb commented
hey @cortisiko , you can find below the requested test


https://github.com/MetaMask/metamask-mobile/assets/26223211/652025b0-717c-4a8d-9a3d-6e5a2ae731f8

2024-07-02 11:48 UTC, EtherWizard33 approved these changes, later dismissed
re-approving to follow up on my previous approval

2024-07-02 15:40 UTC, brianacnguyen commented on app/component-library/components-temp/Price/AggregatedPercentage/AggregatedPercentage.tsx
> +  });
can you separate the styles out to a different file?

2024-07-02 15:41 UTC, brianacnguyen commented on app/component-library/components-temp/Price/AggregatedPercentage/AggregatedPercentage.stories.tsx
> +const mockInitialState = {
can you post a video of the stories?

2024-07-02 15:42 UTC, brianacnguyen reviewed
Can you provide screencap of the new component. Also can you split the styles file out?

2024-07-02 15:43 UTC, brianacnguyen requested changes
Can you provide screencap of the new component. Also can you split the styles file out?

2024-07-02 16:37 UTC, salimtb commented on app/component-library/components-temp/Price/AggregatedPercentage/AggregatedPercentage.tsx
> +  });
done

2024-07-02 16:37 UTC, salimtb commented
@brianacnguyen you can find below the Storybook video

https://github.com/MetaMask/metamask-mobile/assets/26223211/299a57b6-75e2-4c8e-8302-6db42fe0510d

2024-07-02 17:44 UTC, brianacnguyen commented on app/component-library/components-temp/Price/AggregatedPercentage/AggregatedPercentage.styles.ts
> +      ...fontStyles.normal,
can you use the TextVariant and TextColor from the Text component instead?
https://github.com/MetaMask/metamask-mobile/blob/main/app/component-library/components/Texts/Text/Text.types.ts

2024-07-02 17:47 UTC, brianacnguyen commented on app/component-library/components-temp/Price/AggregatedPercentage/AggregatedPercentage.styles.ts
> +      ...fontStyles.normal,
![Screenshot 2024-07-02 at 10 45 34 AM](https://github.com/MetaMask/metamask-mobile/assets/14355083/162207e1-9e1a-436d-8bc7-730a84b2b635)
TextVariant should be TextVariant.BodyMDMedium
TextColor should be TextColor.Default, TextColor.Success, and TextColor.Error

2024-07-02 17:48 UTC, brianacnguyen commented on app/component-library/components-temp/Price/AggregatedPercentage/AggregatedPercentage.styles.ts
> +      ...fontStyles.normal,
![Screenshot 2024-07-02 at 10 47 29 AM](https://github.com/MetaMask/metamask-mobile/assets/14355083/2051e8c8-1db8-4d22-8fa4-2093c22ca8ba)
btw you can see this by Pressing `Command` then click on the element on the figma file. The critical information should be on the right

2024-07-02 17:48 UTC, brianacnguyen requested changes
another small change regarding the styles

2024-07-02 19:31 UTC, salimtb commented on app/component-library/components-temp/Price/AggregatedPercentage/AggregatedPercentage.styles.ts
> +      ...fontStyles.normal,
done :)

2024-07-02 19:42 UTC, brianacnguyen submitted a review, later dismissed

2024-07-02 21:01 UTC, cortisiko submitted a review, later dismissed
🌮 🌮 🌮

2024-07-02 21:14 UTC, cortisiko submitted a review, later dismissed
🎬 🌮 🌮

2024-07-02 21:41 UTC, brianacnguyen approved these changes

2024-07-03 09:15 UTC, tommasini approved these changes

2024-07-03 09:16 UTC, merged