chore: add Sentry snapshot with masked data
MetaMask/metamask-mobile pull request #10241
Opened 2024-07-03 18:19 UTC by tommasini

## **Description**

This PR introduces snapshot with masked data for metamask mobile.
Here is an example of masked data on sentry

```
{"accounts": {"reloadAccounts": false}, "alert": {"autodismiss": null, "content": null, "data": null, "isVisible": false}, "bookmarks": [], "browser": {"activeTab": null, "favicons": [], "history": [], "tabs": [], "visitedDappsByHostname": {}, "whitelist": []}, "collectibles": {"favorites": {}, "isNftFetchingProgress": false}, "engine": {"backgroundState": {"AccountTrackerController": [Object], "AccountsController": [Object], "AddressBookController": [Object], "ApprovalController": [Object], "AssetsContractController": [Object], "CurrencyRateController": [Object], "GasFeeController": [Object], "KeyringController": [Object], "LoggingController": [Object], "NetworkController": [Object], "NftController": [Object], "NftDetectionController": "object", "PPOMController": [Object], "PermissionController": [Object], "PhishingController": [Object], "PreferencesController": [Object], "SmartTransactionsController": [Object], "SnapController": [Object], "SubjectMetadataController": [Object], "SwapsController": [Object], "TokenBalancesController": "object", "TokenDetectionController": [Object], "TokenListController": [Object], "TokenRatesController": [Object], "TokensController": [Object], "TransactionController": [Object]}}, "experimentalSettings": {"securityAlertsEnabled": true}, "fiatOrders": "object", "infuraAvailability": {"isBlocked": false}, "inpageProvider": {"networkId": "1"}, "legalNotices": {"newPrivacyPolicyToastClickedOrClosed": true, "newPrivacyPolicyToastShownDate": null}, "modals": {"collectibleContractModalVisible": false, "dappTransactionModalVisible": false, "networkModalVisible": false, "receiveAsset": undefined, "receiveModalVisible": false, "shouldNetworkSwitchPopToWallet": true, "signMessageModalVisible": true}, "navigation": {"currentBottomNavRoute": "Wallet", "currentRoute": "Login"}, "networkOnboarded": {"networkOnboardedState": {}, "networkState": {"nativeToken": "", "networkType": "", "networkUrl": "", "showNetworkOnboarding": false}, "switchedNetwork": {"networkStatus": false, "networkUrl": ""}}, "notification": {"notification": {"notificationsSettings": [Object]}, "notifications": []}, "onboarding": {"events": []}, "privacy": {"approvedHosts": {}, "revealSRPTimestamps": []}, "rpcEvents": {"signingEvent": {"eventStage": "idle", "rpcName": ""}}, "sdk": {"approvedHosts": {}, "connections": {}, "dappConnections": {}, "wc2Metadata": undefined}, "security": {"allowLoginWithRememberMe": false, "automaticSecurityChecksEnabled": false, "dataCollectionForMarketing": null, "hasUserSelectedAutomaticSecurityCheckOption": false, "isAutomaticSecurityChecksModalOpen": false, "isNFTAutoDetectionModalViewed": false}, "settings": {"basicFunctionalityEnabled": true, "hideZeroBalanceTokens": false, "lockTime": 30000, "primaryCurrency": "ETH", "searchEngine": "DuckDuckGo", "useBlockieIcon": true}, "signatureRequest": "object", "smartTransactions": {"optInModalAppVersionSeen": null}, "swaps": "object", "transaction": "object", "transactionMetrics": "object", "user": {"ambiguousAddressEntries": "object", "appTheme": "os", "backUpSeedphraseVisible": false, "gasEducationCarouselSeen": false, "initialScreen": "", "isAuthChecked": false, "loadingMsg": "", "loadingSet": false, "passwordSet": true, "protectWalletModalVisible": false, "seedphraseBackedUp": true, "userLoggedIn": true}, "wizard": {"step": 1}}
```

![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/1010f09a-4c56-477f-b526-f93c17870c5f)

## **Related issues**

Fixes: https://github.com/MetaMask/mobile-planning/issues/1843

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-07-04 10:06 UTC, tommasini commented
The failed quality gate do not seem accurate `maskKey === undefined` it's needed and not redundant!

2024-07-04 11:48 UTC, NicolasMassart commented
> The failed quality gate do not seem accurate `maskKey === undefined` it's needed and not redundant!

The `maskKey === undefined` check might not be necessary if you want to handle it in the same way as `false`. So if you use `maskKey == false` both `false` and `undefined` values will be covered. At least that's my understanding.

2024-07-04 23:55 UTC, tommasini commented
That would mean that `maskKey == false` would cover for both? It's not what it seems, but most likely `!maskKey` would cover for both, but since there is an else scenario, Im not sure if we should do that, we are not accounting for key that are `null` or empty strings or 0, those values would fall into the else and throw an error!

![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/2347d62e-edbd-48d7-b6d3-907ef572c39a)

I bring that method from [extension](https://github.com/MetaMask/metamask-extension/blob/8e00507f9c98ad18294448f3fdedcf92b19a00b3/shared/modules/object.utils.js#L23)

2024-07-05 11:46 UTC, NicolasMassart commented on app/util/sentry/utils.js
> +    }
```suggestion
    if (appState) {
      const maskedState = maskObject(appState, SENTRY_STATE);
      report.contexts.appState = maskedState || {};
    }
```

2024-07-05 11:46 UTC, NicolasMassart commented on app/util/sentry/utils.js
> +  if (!object) return {};
S: could you test the mask param too? Or maybe have a default value for this function mask param?

2024-07-05 11:46 UTC, NicolasMassart commented on app/util/sentry/utils.js
> +  }
Q: could you explain what this part is for exactly? Some code comment?

2024-07-05 11:46 UTC, NicolasMassart commented on app/util/sentry/utils.js
> +      AssetsContractController: {},
Q: what will the mask be for this with {} ?

2024-07-05 11:46 UTC, NicolasMassart commented on app/util/sentry/utils.js
> +        versionInfo: [],
Q: what will the mask be for this with [] ?

2024-07-05 11:46 UTC, NicolasMassart commented on app/util/sentry/utils.test.ts
> +    it('mask our fixture of intial root state', () => {
S: Could you test a state with actual values that would cover the specific cases you test in the util function? See how "accounts" for instance masks with a real value. I feel the fixture root state is too empty to provide an accurate masking test. You have to at least test it of course, but adding a more realistic one would help.

Also, just some naming:
```suggestion
    it('masks initial root state fixture', () => {
```

2024-07-05 11:46 UTC, NicolasMassart commented on app/util/sentry/utils.test.ts
> +      });
S: as the output you are testing is a big generated JSON, and it's not really useful to have it visible in the test itself (you just copy/pasted the initial return and no one reads each value and removing it would make the test more readable), that's a good use case for using snapshots. Snapshots allow to compare a json, it's not necessarily just for UIs. This seems a good use case for it to me here.

```suggestion
      expect(maskedState).toMatchSnapshot();
```

2024-07-05 12:46 UTC, tommasini commented on app/util/sentry/utils.js
> +        versionInfo: [],
I don't replicated that on the test examples, but yes , I will be adding unit tests to proof this!
![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/cdf16a61-f18c-40ae-b487-77690ab49a22)

2024-07-05 16:49 UTC, tommasini commented on app/util/sentry/utils.test.ts
> +      });
Yeah you are totally right! Addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/10241/commits/26ba148811d8c108dfe5ebb850e4a5fe17d9a232)

2024-07-05 16:49 UTC, tommasini commented on app/util/sentry/utils.js
> +    }
Refactored on this commit: https://github.com/MetaMask/metamask-mobile/pull/10241/commits/26ba148811d8c108dfe5ebb850e4a5fe17d9a232

2024-07-05 16:49 UTC, tommasini commented on app/util/sentry/utils.test.ts
> +    it('mask our fixture of intial root state', () => {
Refactored on this commit: https://github.com/MetaMask/metamask-mobile/pull/10241/commits/26ba148811d8c108dfe5ebb850e4a5fe17d9a232

2024-07-05 16:49 UTC, tommasini commented on app/util/sentry/utils.js
> +  if (!object) return {};
Addressed on this commit: https://github.com/MetaMask/metamask-mobile/pull/10241/commits/26ba148811d8c108dfe5ebb850e4a5fe17d9a232

2024-07-05 16:57 UTC, tommasini commented on app/util/sentry/utils.js
> +  }
>  if (Object.keys(mask).includes(AllProperties)) {

This is looking if the keys on the mask object contains the Symbol '*'

> if (Object.keys(mask).length > 1) {
If the it includes the Symbol '*' and includes more than one key, the iteration that happens after only support one key being '*' as we can see here when we are accessing the object on mask
```
    const maskKey = maskAllProperties ? mask[AllProperties] : mask[key];
```

If the value on the mask is true we can sho the values of the state (we do not obfuscate them)

>     } else if (maskKey && typeof maskKey === 'object') {
If it's an object, it calls function again since it's goes deeper on the object tree

>  } else if (maskKey === undefined || maskKey === false) {
If it's undefined or false we pass the type of the object to that property, obfuscating their real value

2024-07-05 16:59 UTC, tommasini commented on app/util/sentry/utils.js
> +      AssetsContractController: {},
If it an object what will happen is:

Will enter the maskObject function, will fall into the second condition: `else if (maskKey && typeof maskKey === 'object')` then it will fall into the first condition : `if (maskKey === true) {` and show an empty object on sentry

2024-07-05 16:59 UTC, tommasini commented on app/util/sentry/utils.js
> +        versionInfo: [],
Same [here](https://github.com/MetaMask/metamask-mobile/pull/10241#discussion_r1666999564)

2024-07-05 17:06 UTC, tommasini commented on app/util/sentry/utils.js
> +      AssetsContractController: {},
Taking the example of assetsContracController we can see that it do not appear on Sentry 
![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/4cd326ed-e3d6-4d2a-8500-9f64e912dc7c)

2024-07-05 19:53 UTC, NicolasMassart commented on app/util/sentry/utils.js
> +export const SENTRY_STATE = {
S: Now that I read this a bit more I feel it could be called `sentryStateMask` for more clarity (and also avoid uppercase const names, that's not in guidelines and usually more for env vars.)
```suggestion
export const sentryStateMask = {
```

2024-07-05 19:53 UTC, NicolasMassart commented on app/util/sentry/utils.test.ts
> +    const rootState = {
Q: how to make sure this will be in sync with our real state? it will have to be updated each time the real rootState will be updated in the app.
Should we move this to TS to be able to implement RootState from app/reducer and ensure a link between both forcing des to update this mask test too?

2024-07-09 10:09 UTC, tommasini commented on app/util/sentry/utils.test.ts
> +    const rootState = {
Not sure if I understood this part "Should we move this to TS to be able to implement RootState"
But rootState it's meant to be a default state, default state doesn't have data, we want here to see if the mask is working as expected and we need to mock data for that to happen!

2024-07-09 22:28 UTC, jpcloureiro requested changes

2024-07-09 22:28 UTC, jpcloureiro commented on app/util/sentry/utils.js
> +export const sentryStateMask = {
We can remove the keys with `false`, making the mask object smaller and easier to maintain

2024-07-09 22:28 UTC, jpcloureiro commented on app/util/sentry/utils.js
> +export function maskObject(object, mask = true) {
We could also improve the naming of the `object` parameter.

2024-07-09 22:28 UTC, jpcloureiro commented on app/util/sentry/utils.js
> +      throw new Error(`Unsupported mask entry: ${maskKey}`);
Can't we just ignore unsupported mask entries?

2024-07-09 22:28 UTC, jpcloureiro commented on app/util/sentry/utils.js
> +    if (maskKey === true) {
Lets give names to these conditions.

Example
```
const shouldPrintValue = maskKey === true
const shouldIterateSubMask = Boolean(maskKey) && typeof maskKey === 'object'
const shouldPrintType = maskKey === undefined || maskKey === false
```

2024-07-09 22:30 UTC, jpcloureiro commented on app/util/sentry/utils.test.ts
> +    });
have a submask with 

```
{
  [AllProperties]: false,
  enabled: true
}
```

2024-07-10 11:04 UTC, jpcloureiro commented on app/util/sentry/utils.js
> +  }
Something along these lines would help better understand the code

```js
// This function applies a mask to an object, returning a new object where the properties
// are either copied from the original object, replaced with their type, or recursively masked.
function maskObject(object, mask = true) {
  // If the input object is null or undefined, return null.
  if (!object) return null;

  // Flag to indicate if all properties should be masked.
  let maskAllProperties = false;

  // Check if the mask contains the special AllProperties key.
  if (Object.keys(mask).includes(AllProperties)) {
    // If AllProperties key exists alongside other keys, throw an error.
    if (Object.keys(mask).length > 1) {
      throw new Error('AllProperties mask key does not support sibling keys');
    }
    // Set flag to true to mask all properties.
    maskAllProperties = true;
  }

  // Reduce the object's keys to a new masked state.
  return Object.keys(object).reduce((state, key) => {
    // Determine the mask for the current key.
    const maskKey = maskAllProperties ? mask[AllProperties] : mask[key];
    
    if (maskKey === true) {
      // If the mask is true, copy the property from the original object.
      state[key] = object[key];
    } else if (maskKey && typeof maskKey === 'object') {
      // If the mask is an object, recursively apply maskObject to the property.
      state[key] = maskObject(object[key], maskKey);
    } else if (maskKey === undefined || maskKey === false) {
      // If the mask is undefined or false, replace the property with its type.
      state[key] = typeof object[key];
    } else {
      // If the mask has an unsupported value, throw an error.
      throw new Error(`Unsupported mask entry: ${maskKey}`);
    }

    // Return the accumulated state.
    return state;
  }, {});
}


```

2024-07-10 19:27 UTC, tommasini commented on app/util/sentry/utils.js
> +export const sentryStateMask = {
We need to keep it, because keeping it shows the type, and since we can't look at the data at least we try to understand if it's corrupted by the type
By removing it we will not log anything on that entry

2024-07-10 19:30 UTC, tommasini commented on app/util/sentry/utils.js
> +    if (maskKey === true) {
Thanks for the review!!! Addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/10241/commits/38fd89d0add8f15464854fb84e967b492c45b0f0)

2024-07-10 19:30 UTC, tommasini commented on app/util/sentry/utils.js
> +      throw new Error(`Unsupported mask entry: ${maskKey}`);
Thanks for the review!!! Addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/10241/commits/38fd89d0add8f15464854fb84e967b492c45b0f0)

2024-07-10 19:30 UTC, tommasini commented on app/util/sentry/utils.js
> +  if (!object) return null;
Thanks for the review!!! Addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/10241/commits/38fd89d0add8f15464854fb84e967b492c45b0f0)

2024-07-10 19:30 UTC, tommasini commented on app/util/sentry/utils.js
> + * @param {{[key: string]: object | boolean}} mask - The mask to apply to the object
Thanks for the review!!! Addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/10241/commits/38fd89d0add8f15464854fb84e967b492c45b0f0)

2024-07-10 19:30 UTC, tommasini commented on app/util/sentry/utils.test.ts
> +    });
Thanks for the review!!! Addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/10241/commits/38fd89d0add8f15464854fb84e967b492c45b0f0)

2024-07-10 19:30 UTC, tommasini commented on app/util/sentry/utils.js
> +export function maskObject(object, mask = true) {
Thanks for the review!!! Addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/10241/commits/38fd89d0add8f15464854fb84e967b492c45b0f0)

2024-07-10 19:34 UTC, tommasini commented on app/util/sentry/utils.js
> +  return Object.keys(object).reduce((state, key) => {
Thanks for the review!! Addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/10241/commits/ac2e0396566a0acccbba58676edb4e6f7f72fdad)

2024-07-10 19:35 UTC, tommasini commented
@jpcloureiro Thanks for the review!!!! I believe I addressed/answered everything!

2024-07-11 11:08 UTC, jpcloureiro commented on app/util/sentry/utils.js
> +export const sentryStateMask = {
Should log the type of keys not defined in the mask

```js
const shouldPrintType = maskKey === undefined || maskKey === false;

if (shouldPrintType) {
  maskedObject[key] = typeof objectToMask[key];
}
```

2024-07-11 11:16 UTC, jpcloureiro commented on app/util/sentry/utils.js
> +export const sentryStateMask = {
For the sub-masks that only have keys with `false`, we could use the `[AllProperties]: false`

For the ones that have siblings as `true`, it is safe to remove the keys with `false`

This could be refactored with an enum to cover more cases. I'll leave it up to the author to decide if it is worth the effort.

2024-07-11 14:27 UTC, tommasini commented on app/util/sentry/utils.js
> +export const sentryStateMask = {
You are right! Thank you so much, is much better now, addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/10241/commits/6ecf7433bd9e195454d4c9ce977b728e0fedf111)

2024-07-11 15:56 UTC, jpcloureiro submitted a review, later dismissed
lgtm

2024-07-12 16:36 UTC, NicolasMassart approved these changes, later dismissed
Looks good to me.

2024-07-12 17:05 UTC, NicolasMassart approved these changes
Looks good to me.

2024-07-15 22:14 UTC, merged