feat: add utility function to get supported chains from the Security Alerts API
MetaMask/metamask-mobile pull request #10267
Opened 2024-07-09 13:00 UTC by vinistevam

## **Description**

This PR aims to include a new utility function to get supported chains from the Security Alerts API when enabled.

#### Related Repository
Refer to the [Security Alerts API repository](https://github.com/consensys-vertical-apps/va-mmcx-security-alerts-api) for more details.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Test blockaid regression

2. add the envs 
```shell
export SECURITY_ALERTS_API_URL='https://security-alerts.dev-api.cx.metamask.io'
export SECURITY_ALERTS_API_ENABLED='true'
```
- Go to test dapp and trigger on of the malicious signatures
- To verify in chrome go to dev tools > network. Search for `security-alerts` and find the call to the API service.

Existing PPOM logic should function as before, even with the above environment variables added, due to the fallback to the controller in the event of an error.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-07-10 13:56 UTC, pedronfigueiredo submitted a review, later dismissed

2024-07-10 15:52 UTC, jpuri commented
There is usage of `BLOCKAID_SUPPORTED_CHAIN_IDS` here also: https://github.com/MetaMask/metamask-mobile/blob/f7d8e61c4b4caab2623b208ad33a4db492700ad7/app/util/blockaid/index.ts#L20

2024-07-10 20:44 UTC, matthewwalsh0 requested changes

2024-07-10 20:44 UTC, matthewwalsh0 commented on app/lib/ppom/security-alerts-api.ts
> +  return response.json();
Can we remove the duplication and create a `request` function for example that accepts the method and some extra properties?

2024-07-10 20:44 UTC, matthewwalsh0 commented on app/lib/ppom/security-alerts-api.ts
> +export async function getSupportedChains(): Promise<Hex[]> {
Maybe `getSecurityAlertsAPISupportedChainIds` to be explicit?

2024-07-10 20:44 UTC, matthewwalsh0 commented on app/lib/ppom/ppom-util.ts
> +    return supportedChains.includes(chainId);
Minor, but could we remove some duplication with something like:

```
let supportedChainIds = BLOCKAID_SUPPORTED_CHAIN_IDS;

try {
    if(isSecurityAlertsAPIEnabled()) {
        supportedChainIds = getSupportedChainds();
    }
} catch (e) {
    Logger.log(
      `Error fetching supported chains from security alerts API: ${e}`,
    );
}

return supportedChainIds.includes(chainId);
```

2024-07-10 20:44 UTC, matthewwalsh0 commented on app/lib/ppom/ppom-util.test.ts
> +      jest
Minor, but could we create a persistent variable for this such as `getSupportedChainsMock` like we do for `isSecurityAlertsEnabledMock`?

2024-07-11 09:06 UTC, vinistevam commented on app/lib/ppom/security-alerts-api.ts
> +  return response.json();
Great suggestions, I created the `request` function with the same options supported by fetch.

2024-07-11 09:07 UTC, vinistevam commented on app/lib/ppom/ppom-util.ts
> +    return supportedChains.includes(chainId);
Nice! Pushed the suggestion. https://github.com/MetaMask/metamask-mobile/pull/10267/commits/ad145f490243d499ea835d9731af623d39b0b7ff

2024-07-11 09:07 UTC, vinistevam commented on app/lib/ppom/ppom-util.test.ts
> +      jest
Done. https://github.com/MetaMask/metamask-mobile/pull/10267/commits/ad145f490243d499ea835d9731af623d39b0b7ff

2024-07-12 15:46 UTC, matthewwalsh0 approved these changes, later dismissed

2024-07-12 15:46 UTC, matthewwalsh0 commented on app/lib/ppom/ppom-util.ts
> +export async function isChainSupported(chainId: Hex): Promise<boolean> {
Does this need to be exported as it's just part of the validate implementation?

Ideally we wouldn't expose but test indirectly?

2024-07-16 10:21 UTC, vinistevam commented on app/lib/ppom/ppom-util.ts
> +export async function isChainSupported(chainId: Hex): Promise<boolean> {
Removed the `export` https://github.com/MetaMask/metamask-mobile/pull/10267/commits/b5b8db1ec62aa5914175a6ee7230e6b2c3ed11bd

2024-07-17 09:27 UTC, matthewwalsh0 approved these changes, later dismissed

2024-07-22 10:08 UTC, OGPoyraz approved these changes

2024-07-29 10:03 UTC, matthewwalsh0 approved these changes

2024-08-01 09:55 UTC, vinistevam commented
> There is usage of `BLOCKAID_SUPPORTED_CHAIN_IDS` here also:
> 
> https://github.com/MetaMask/metamask-mobile/blob/f7d8e61c4b4caab2623b208ad33a4db492700ad7/app/util/blockaid/index.ts#L20

I will open a ticket and the refactor will be handled in this [PR](https://github.com/MetaMask/metamask-mobile/pull/10518), cause it was getting too big.

2024-08-01 10:24 UTC, merged