fix: skip blockaid validations for users internal accounts
MetaMask/metamask-mobile pull request #10264
Opened 2024-07-08 06:40 UTC by jpuri

## **Description**

Skip blockaid validation for users internal accounts

## **Related issues**

Fixes: https://github.com/MetaMask/MetaMask-planning/issues/2633

## **Manual testing steps**

1. Make a send transaction to user's own account
2. Check that blockaid validation is not done

## **Screenshots/Recordings**
NA

## **Pre-merge author checklist**

- [X] I've followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Extension Coding Standards](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-extension/blob/develop/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-07-11 08:49 UTC, matthewwalsh0 approved these changes, later dismissed

2024-07-11 08:49 UTC, matthewwalsh0 commented on app/lib/ppom/ppom-util.ts
> +  if (req.method === 'eth_sendTransaction') {
Would it add clarity to add a small local function such as `isInternalAccount(req)`?

2024-07-11 16:08 UTC, digiwand requested changes
requesting minor update to test before merge

2024-07-11 16:08 UTC, digiwand commented on app/lib/ppom/ppom-util.test.ts
> +        false;
```suggestion
        true;
```

I think this would be more effective if the setting were turned on which could call the validation, else we do not expect validate to run

2024-07-11 16:08 UTC, digiwand commented on app/lib/ppom/ppom-util.ts
> +    AccountsController,
[nit] could move to the top to preserve alphabetical order

2024-07-12 07:32 UTC, jpuri commented on app/lib/ppom/ppom-util.test.ts
> +        false;
Its `true` for all other tests, this particular test is check that validation is not done if its `false`.

2024-07-12 07:32 UTC, jpuri commented on app/lib/ppom/ppom-util.test.ts
> +        false;
https://github.com/MetaMask/metamask-mobile/blob/f31edcacf86dba7c35664c96afbbd9b09664cb41/app/lib/ppom/ppom-util.test.ts#L25

2024-07-12 12:11 UTC, tommasini commented on app/lib/ppom/ppom-util.test.ts
> +        // eslint-disable-next-line @typescript-eslint/no-explicit-any
We shouldn't use any anymore, could you change it and type it correctly?

2024-07-12 14:49 UTC, jpuri commented on app/lib/ppom/ppom-util.test.ts
> +        // eslint-disable-next-line @typescript-eslint/no-explicit-any
I fixed it

2024-07-12 14:52 UTC, matthewwalsh0 submitted a review, later dismissed

2024-07-12 15:37 UTC, tommasini submitted a review, later dismissed

2024-07-12 15:57 UTC, matthewwalsh0 submitted a review, later dismissed

2024-07-12 16:58 UTC, digiwand commented on app/lib/ppom/ppom-util.test.ts
> +        false;
```suggestion
```

2024-07-12 17:01 UTC, digiwand commented on app/lib/ppom/ppom-util.test.ts
> +        false;
in this case, I think we can remove the line then. See suggestion https://github.com/MetaMask/metamask-mobile/pull/10264/files#r1676204298

It looks like the test above checks the validation is not done when this value is false `should not validate if preference securityAlertsEnabled is false`

I think in this test, `should not validate if request is send to users own account`, we want the feature to be enabled to properly check the feature does not run for internal accounts

2024-07-12 17:15 UTC, jpuri commented on app/lib/ppom/ppom-util.test.ts
> +        false;
I am setting value to true here: https://github.com/MetaMask/metamask-mobile/blob/f31edcacf86dba7c35664c96afbbd9b09664cb41/app/lib/ppom/ppom-util.test.ts#L25

2024-07-12 17:19 UTC, digiwand approved these changes

2024-07-12 17:41 UTC, tommasini approved these changes

2024-07-12 23:46 UTC, merged