feat: New nft details page
MetaMask/metamask-mobile pull request #10277
Opened 2024-07-10 12:49 UTC by sahar-fehri

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-07-23 05:12 UTC, brianacnguyen requested changes
The changes to badge is not needed. You can conditionally set the offset positions wherever youre using the BadgeWrapper by passing it to the badgePosition prop
<img width="457" alt="Screenshot 2024-07-22 at 10 12 13 PM" src="https://github.com/user-attachments/assets/f0d1fb0b-a2f9-450b-8460-53b1f4a85569">
<img width="352" alt="Screenshot 2024-07-22 at 10 12 16 PM" src="https://github.com/user-attachments/assets/1e07a9c0-7555-4439-8e3f-7c15f46827e3">

2024-07-23 05:13 UTC, brianacnguyen commented on app/component-library/components/Icons/Icon/assets/back.svg
This is not needed. Use ARROW_LEFT

2024-07-23 05:14 UTC, brianacnguyen commented on app/component-library/components/Icons/Icon/assets/close-2.svg
This is not needed. Use close

2024-07-23 05:14 UTC, brianacnguyen commented on app/component-library/components/Icons/Icon/assets/vertical-dots.svg
this is not needed. use more-vertical

2024-07-23 05:15 UTC, brianacnguyen requested changes
All DS changes in here are not needed

2024-07-23 18:40 UTC, sahar-fehri commented
> All DS changes in here are not needed

Thank you @brianacnguyen 🙏 

Icons updated  [425aff2](https://github.com/MetaMask/metamask-mobile/pull/10277/commits/425aff297de486bb3a7f589b399ecdb61b102f9d)



<img width="433" alt="Screenshot 2024-07-23 at 20 39 09" src="https://github.com/user-attachments/assets/5c56bd53-8afc-4bd5-beb8-f8c62e11d3ca">


<img width="413" alt="Screenshot 2024-07-23 at 20 39 01" src="https://github.com/user-attachments/assets/218862bf-3494-4460-a0bd-18575a962f10">

2024-07-23 19:09 UTC, bergeron commented on app/components/Views/NftOptions/NftOptions.tsx
> +  const removeNft = () => {
I merged 2 NFT metrics in https://github.com/MetaMask/metamask-mobile/pull/9469 yesterday, could you check that they still emit in this new UI?

2024-07-23 23:22 UTC, cortisiko requested changes
left some small feedback for you @sahar-fehri, thanks for adding e2e test coverage for this new feature btw

2024-07-24 04:48 UTC, brianacnguyen commented on app/component-library/components/Badges/BadgeWrapper/BadgeWrapper.styles.ts
> +  const {
can you remove these changes are use badgePosition instead? let me know if you need help with this

2024-07-24 05:06 UTC, brianacnguyen reviewed
Can you remove the BadgeWrapper changes and use the BadgePosition object instead? LMK if you need help with this

2024-07-24 10:34 UTC, sahar-fehri commented on app/component-library/components/Badges/BadgeWrapper/BadgeWrapper.styles.ts
> +  const {
Hi @brianacnguyen ! Removing all changes to this file makes tha badge icon looking like this 
<img width="326" alt="Screenshot 2024-07-24 at 12 29 55" src="https://github.com/user-attachments/assets/31fb39ea-dc7b-4169-bfbe-5094f58e31c1">

I am already passing the badge position `badgePosition={DEFAULT_BADGEWRAPPER_BADGEPOSITION}`
here:https://github.com/MetaMask/metamask-mobile/pull/10277/files/0bf29a067b8b7db87ec51f457821783a877f5247#diff-a78d4aae7fcc002ba295de7ac42c733134d60ed085982abd0ccab79dff0fb7d8R189

2024-07-24 13:10 UTC, sahar-fehri commented on app/component-library/components/Badges/BadgeWrapper/BadgeWrapper.styles.ts
> +  const {
Hey @brianacnguyen ! , Removing all changes to this file and relying on the default configuration of the customBadge 
```
    default:
      positionObj = badgePosition;
      isCustomPosition = true;
      xOffset = 0;
      yOffset = 0;
```
Is not enough to make the badge look like the designs;
I tried passing 
```
badgePosition = {
  top: 8,
  right: 8
}
```
But that did not work..

2024-07-24 17:13 UTC, brianacnguyen commented on app/components/Base/RemoteImage/index.js
> +      position: 'absolute',
this style is no longer used, can you remove it?

2024-07-24 17:13 UTC, brianacnguyen approved these changes, later dismissed
Approved with some minor non-blocking comments/suggestions

2024-07-24 17:53 UTC, sahar-fehri commented on app/components/Base/RemoteImage/index.js
> +      position: 'absolute',
Removed!

2024-07-24 17:53 UTC, sahar-fehri commented on app/components/Base/RemoteImage/index.js
> +    },
Updated!

2024-07-25 15:37 UTC, brianacnguyen approved these changes, later dismissed

2024-07-29 13:58 UTC, cortisiko approved these changes, later dismissed
PR looks good from a Quality Perspective. Thank you for adding E2E coverage.

2024-07-29 21:56 UTC, bergeron commented
A minor bug is that the nft opens twice if you click fast enough.

https://github.com/user-attachments/assets/9f0c5027-ccfd-4876-96a9-e8853c667583

2024-07-29 21:59 UTC, bergeron commented on app/component-library/components/Icons/Icon/assets/arrow-down.svg
Why are these SVG icons changed?

2024-07-29 22:47 UTC, sahar-fehri commented on app/component-library/components/Icons/Icon/assets/arrow-down.svg
DS team provided me with these [icons](https://consensys.slack.com/archives/C0354T27M5M/p1721748419142219?thread_ts=1721743082.474289&cid=C0354T27M5M) to update them in mobile as part of my PR 🙏

2024-07-30 03:32 UTC, bergeron commented on app/components/Views/Asset/index.js
> +          /*         <Text>sqjkbdjksqdjsqn</Text> */
```suggestion
```

delete me

2024-07-30 03:36 UTC, bergeron approved these changes, later dismissed

2024-07-30 09:41 UTC, sahar-fehri commented
> 75d1b32

Should be fixed here [75d1b32](https://github.com/MetaMask/metamask-mobile/pull/10277/commits/75d1b32635a15dd51344552032851f11a555f78c)

> A minor bug is that the nft opens twice if you click fast enough.
> 
>  Screen.Recording.2024-07-29.at.2.55.04.PM.mov

Should be fixed: [75d1b32](https://github.com/MetaMask/metamask-mobile/pull/10277/commits/75d1b32635a15dd51344552032851f11a555f78c)

2024-07-30 10:54 UTC, brianacnguyen approved these changes, later dismissed

2024-07-30 16:37 UTC, bergeron approved these changes, later dismissed

2024-07-31 10:34 UTC, tommasini reviewed
This work is awesome, left some questions!

2024-07-31 10:34 UTC, tommasini commented on app/components/Views/NftDetails/nftDetails.utils.ts
> +export const formatTimestampToYYYYMMDD = (timestamp: number): string => {
It would be good to have tests for this util function, and also if we think we will use it on more places I would argue that we should move it to the utils folder, but will defer that decision to you

2024-07-31 10:34 UTC, tommasini commented on app/util/url/index.ts
> +export function getValidUrl(urlString: string): URL | null {
I see that we use a library to do that [here](https://github.com/MetaMask/metamask-mobile/blob/a9522c9f5fd8ae6b9fa0f6833294fa3c5a22fe0c/app/core/RPCMethods/wallet_addEthereumChain.js#L2)

Instead of duplicate, I would say that we can decide if to use the library or use this version, I think we shouldn't have both! Would be better if we have a consistent way to validate the url, wdyt?

2024-07-31 10:34 UTC, tommasini commented on patches/@metamask+assets-controllers+30.0.0.patch
> ++        const collections = apiNfts.reduce((acc, currValue) => {
The assets-controllers maintenance is being handed off to the assets team, I'm hoping that we can get rid of this patch as soon as possible

2024-07-31 10:34 UTC, tommasini commented on app/util/url/index.ts
> +export function getValidUrl(urlString: string): URL | null {
I also Think we should have tests for this function if we decide to keep it!

2024-07-31 10:34 UTC, tommasini commented on app/util/url/index.ts
> +export function addUrlProtocolPrefix(urlString: string) {
I believe we have this function with the same intention, should we improve it instead?
https://github.com/MetaMask/metamask-mobile/blob/253449c5d066d772337af6d38b923a37b2f01c54/app/util/browser/index.ts#L13

2024-07-31 10:34 UTC, tommasini commented on app/util/url/index.ts
>  }
Can we add TSDoc to the new util functions?

2024-07-31 13:41 UTC, sahar-fehri commented on app/util/url/index.ts
> +export function getValidUrl(urlString: string): URL | null {
I removed this fct and using prefixUrlWithProtocol instead

2024-07-31 13:41 UTC, sahar-fehri commented on app/util/url/index.ts
> +export function addUrlProtocolPrefix(urlString: string) {
Removed in favor of prefixUrlWithProtocol

2024-07-31 13:41 UTC, sahar-fehri commented on app/util/url/index.ts
>  }
removed my new utils fct eventually 🙏

2024-07-31 13:42 UTC, sahar-fehri commented on patches/@metamask+assets-controllers+30.0.0.patch
> ++        const collections = apiNfts.reduce((acc, currValue) => {
Yes we have a ticket to cleanup this patch after merging this one 🙏

2024-07-31 14:12 UTC, tommasini approved these changes
LGTM! Let's re run the E2E and only merge when they are all green!

2024-08-01 14:29 UTC, bergeron approved these changes

2024-08-01 14:47 UTC, cortisiko approved these changes

2024-08-01 15:56 UTC, Prithpal-Sooriya approved these changes

2024-08-01 15:59 UTC, sahar-fehri commented on app/components/Views/NftOptions/NftOptions.tsx
> +  const removeNft = () => {
Yup, this is added 🙏

2024-08-01 16:00 UTC, merged