SRP reveal quiz test setup
MetaMask/metamask-mobile pull request #10273
Opened 2024-07-09 22:10 UTC by plasmacorral

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-07-17 21:18 UTC, chrisleewilcox commented
@plasmacorral you can look at swaps use of fixtures and see it that works for your tests.

./e2e/specs/swaps/swap-action-smoke.spec.js

2024-07-18 21:25 UTC, cortisiko requested changes
Good work on this 👏,  I have left some feedback

2024-07-19 01:31 UTC, plasmacorral commented on e2e/pages/Settings/SecurityAndPrivacy/RevealSecretRecoveryPhrase.js
> +  async tapGetStarted() {
They were different, one was the `get` other was the `tap...`  Both will be removed from this file. TY!

2024-07-19 01:31 UTC, plasmacorral commented on e2e/pages/Settings/SecurityAndPrivacy/RevealSecretRecoveryPhrase.js
> +  async tapTryAgainTwo() {
removing from this file. TY!

2024-07-19 01:31 UTC, plasmacorral commented on e2e/pages/Settings/SecurityAndPrivacy/RevealSecretRecoveryPhrase.js
> +  async tapTouchableBox() {
Removed from this file. TY!

2024-07-19 01:33 UTC, plasmacorral commented on e2e/pages/Settings/SecurityAndPrivacy/RevealSecretRecoveryPhrase.js
> +  async tapRevealRecoveryPhrase() {
Removed from this file.  TY!

2024-07-19 01:33 UTC, plasmacorral commented on e2e/selectors/Settings/SecurityAndPrivacy/RevealSeedView.selectors.js
> +  SECRET_RECOVERY_PHRASE_QUIZ_GET_STARTED_BUTTON_ID: 'get-started-button',
Done.  TY!

2024-07-19 01:34 UTC, plasmacorral commented on e2e/specs/accounts/secret_recovery_phrase_quiz.spec.js
> +        await TestHelpers.checkIfVisible(
Done.  TY!

2024-07-19 01:35 UTC, plasmacorral commented on e2e/specs/accounts/secret_recovery_phrase_quiz.spec.js
> +        await TestHelpers.checkIfVisible(
Done.  TY!

2024-07-19 01:35 UTC, plasmacorral commented on e2e/specs/accounts/secret_recovery_phrase_quiz.spec.js
> +        await TestHelpers.checkIfVisible(
Done.  TY!

2024-07-19 01:35 UTC, plasmacorral commented on e2e/specs/accounts/secret_recovery_phrase_quiz.spec.js
> +        await TestHelpers.checkIfVisible(
Done.  TY!

2024-07-19 04:31 UTC, plasmacorral commented on e2e/specs/accounts/secret_recovery_phrase_quiz.spec.js
> +  it('completes successfully after correcting wrong answers', async () => {
Changed the wording a little, hopefully it is more clear?

2024-07-19 04:32 UTC, plasmacorral commented on e2e/pages/Settings/SecurityAndPrivacy/RevealSecretRecoveryPhrase.js
> +  get getStarted() {
Restored this file to its previous state

2024-07-19 04:32 UTC, plasmacorral commented on e2e/specs/accounts/secret_recovery_phrase_quiz.spec.js
> +        await TestHelpers.checkIfVisible(
Removed this for now.

2024-07-19 15:19 UTC, cortisiko approved these changes
LGTM ✅

2024-07-19 15:23 UTC, gantunesr approved these changes

2024-07-19 15:26 UTC, merged