chore: Fix some TS errors in component library
MetaMask/metamask-mobile pull request #10307
Opened 2024-07-15 18:23 UTC by kylanhurt

## **Description**

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/10200

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-07-17 19:47 UTC, kylanhurt commented on package.json
> -    "react-native-reanimated": "3.1.0",
@tommasini Any special consideration I need for upgrading an npm module like this?

2024-07-18 22:44 UTC, brianacnguyen commented on app/component-library/components-temp/Contracts/ContractBoxBase/ContractBoxBase.tsx
> -              textVariant={TextVariant.HeadingMD}
Can you remove these changes? These settings are important and I will update the Button component to accept this prop again to make sure the settings are properly set on the Button side

2024-07-18 22:45 UTC, brianacnguyen commented on app/component-library/components-temp/Price/AggregatedPercentage/AggregatedPercentage.stories.tsx
> +}
is it possible to extract this out into a props file so the main file can share this prop with the story?

2024-07-18 22:47 UTC, brianacnguyen commented on app/component-library/components/Avatars/Avatar/variants/AvatarNetwork/AvatarNetwork.types.ts
> +  backgroundColor?: string;
why were these added?

2024-07-18 22:48 UTC, brianacnguyen commented on app/component-library/components/Badges/Badge/Badge.tsx
> +          iconName={IconName.Info}
why was this added?

2024-07-18 22:48 UTC, brianacnguyen commented on app/component-library/components/RadioButton/index.ts
> -export { default } from './Checkbox';
why was this deleted?

2024-07-18 22:49 UTC, brianacnguyen commented on app/component-library/components/Select/SelectValue/foundation/index.ts
> -export { default } from './SelectButtonBase';
why was this deleted

2024-07-18 22:49 UTC, brianacnguyen requested changes
Some of the changes did not make sense. Can you provide context into each of them?

2024-07-19 18:27 UTC, kylanhurt commented on app/component-library/components/Select/SelectValue/foundation/index.ts
> -export { default } from './SelectButtonBase';
Because the file it references does not exist
[app/component-library/components/Select/SelectValue/foundation/index.ts](https://github.com/MetaMask/metamask-mobile/pull/10307/files/4808b29d2740462b3a740627c63f5e58bf7102e8#diff-27c0365c4c8d1100054ff5cef035d0f9bb8a99ee2319cc41fcbf034e620931f8)

2024-07-19 18:29 UTC, kylanhurt commented on app/component-library/components/RadioButton/index.ts
> -export { default } from './Checkbox';
Another reference to a non-existent file

<img width="1409" alt="image" src="https://github.com/user-attachments/assets/2485ab05-0598-41a7-80e1-dd99db6690a2">

2024-07-19 20:41 UTC, kylanhurt commented on app/component-library/components/Badges/Badge/Badge.tsx
> +          iconName={IconName.Info}
The `BadgeNotifications` component requires an `iconName` property which eventually passes through to the `Icon` component but then it says in the file that "This props it's for testing purposes" so it's a bit confusing

BadgeNotifications file:
app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.tsx
Icon file:
app/component-library/components/Icons/Icon/Icon.tsx
```
    <SVG
      color={iconColor}
      style={styles.icon}
      width={sizeAsNum}
      height={sizeAsNum}
      // This prop it's for testing purposes
      name={name}
      {...props}
    />
 ````

<img width="1900" alt="image" src="https://github.com/user-attachments/assets/68fb71f5-668a-4897-bbd0-81453357c4e0">

2024-07-23 04:38 UTC, brianacnguyen approved these changes, later dismissed

2024-07-24 15:48 UTC, brianacnguyen submitted a review, later dismissed

2024-07-24 21:34 UTC, tommasini approved these changes
LGTM! Could we add just a recording to the PR of android and ios? I see reanimated library was updated, that could be a good proof of testing + history of testing!

Also I re-ran the E2E, let's only merged it if passes

2024-07-30 15:55 UTC, tommasini requested changes
Can we add to the PR description why reanimated version update was needed?

2024-07-31 03:39 UTC, brianacnguyen submitted a review, later dismissed

2024-08-02 14:39 UTC, tommasini commented on yarn.lock
> +"@babel/helper-plugin-utils@^7.0.0", "@babel/helper-plugin-utils@^7.10.4", "@babel/helper-plugin-utils@^7.12.13", "@babel/helper-plugin-utils@^7.14.5", "@babel/helper-plugin-utils@^7.18.6", "@babel/h
Since this changes are not expected can we revert these?

2024-08-12 15:58 UTC, tommasini approved these changes

2024-08-12 21:37 UTC, merged