Add confirmation UI adjustments
MetaMask/metamask-mobile pull request #10348
Opened 2024-07-19 12:40 UTC by OGPoyraz

## **Description**

This PR aims to adjust couple design tweaks reported in the ticket https://github.com/MetaMask/MetaMask-planning/issues/2750

## **Related issues**

Fixes:

## **Manual testing steps**

## **Screenshots/Recordings**

### **Before**

![old1](https://github.com/user-attachments/assets/87606e80-1a2d-4408-8cb3-2314db19e1ba)
![old2](https://github.com/user-attachments/assets/3cb4df63-0970-4982-95c8-3e164627f8eb)
![old3](https://github.com/user-attachments/assets/4a7f347f-926d-409b-bc96-c27f220580cb)

### **After**

![new1](https://github.com/user-attachments/assets/3dcc43ff-4e15-4370-9a55-b9bd151e1a74)
![new2](https://github.com/user-attachments/assets/bdddd00d-3508-4ea7-ad61-6eb653cdaf3f)
![new3](https://github.com/user-attachments/assets/d94f6e40-37a9-4086-8068-977086ee2303)

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-07-23 16:30 UTC, matthewwalsh0 requested changes

2024-07-23 16:30 UTC, matthewwalsh0 commented on app/components/UI/ApprovalTagUrl/ApprovalTagUrl.tsx
> +const ApprovalTagUrl = ({
For audit sake, can I confirm why we've moved this from `ApproveTransactionHeader.tsx`?

Is it absolutely necessary for this PR as it's already a big one so ideally want to do the minimum refactor possible.

2024-07-23 16:30 UTC, matthewwalsh0 commented on app/components/UI/ApprovalTagUrl/ApprovalTagUrl.tsx
Assuming this is still related to the original `ApproveTransactionHeader`, should this also go in: `app/components/Views/confirmations/components` ?

2024-07-23 16:30 UTC, matthewwalsh0 commented on app/components/UI/AccountFromToInfoCard/AddressFrom.tsx
Same for these two components, I love the modularity, but it just introduces additional risk so want to clarify the intent?

2024-07-24 08:42 UTC, OGPoyraz commented on app/components/UI/ApprovalTagUrl/ApprovalTagUrl.tsx
> +const ApprovalTagUrl = ({
I need to separate the logic in of `ApprovalTagUrl` from `ApproveTransactionHeader.tsx` otherwise I need to duplicate this logic into new component. 
The reasoning behind this is the order of the components are changed and `ApprovalTagUrl` is need individually, not tied to `ApproveTransactionHeader`.

2024-07-24 08:52 UTC, OGPoyraz commented on app/components/UI/ApprovalTagUrl/ApprovalTagUrl.tsx
Not only `ApproveTransactionHeader` also `TransactionReview`.
But regardless, this change seems logical since this is only used in confirmations.
Done in https://github.com/MetaMask/metamask-mobile/pull/10348/commits/fedd1a4a0c7f65187dc3190ad177cb69ea7d53e1

2024-07-24 09:03 UTC, OGPoyraz commented on app/components/UI/AccountFromToInfoCard/AddressFrom.tsx
Please note that this component is actually new and very identical to component that `ApproveTransactionHeader` render with few changes. So I am trying to keep it minimal on the changes already.

2024-09-11 12:39 UTC, matthewwalsh0 approved these changes, later dismissed

2024-09-11 12:43 UTC, pedronfigueiredo commented on locales/languages/en.json
> +    "estimated_fee": "Estimated fee",
We recently changed to "Network fee" on extension, is it not worth making the same change here for consistency?

2024-09-11 12:46 UTC, vinistevam commented on app/components/UI/ApprovalTagUrl/ApprovalTagUrl.tsx
> +      title = '';
Am I missing something, or is this redundant as it's assigned on line 52?

2024-09-11 12:46 UTC, vinistevam approved these changes, later dismissed

2024-09-11 12:48 UTC, vinistevam commented on locales/languages/en.json
> +    "estimated_fee": "Estimated fee",
Good point we have a ticket for it https://github.com/MetaMask/MetaMask-planning/issues/3064 .

2024-09-11 12:51 UTC, OGPoyraz commented on app/components/UI/ApprovalTagUrl/ApprovalTagUrl.tsx
> +      title = '';
You're right, I added this part recently because of conflicts. I didnt check the whole.

2024-09-11 12:55 UTC, OGPoyraz commented on locales/languages/en.json
> +    "estimated_fee": "Estimated fee",
Good call, it's added in to this PR now.

2024-09-11 12:57 UTC, pedronfigueiredo approved these changes

2024-09-11 13:30 UTC, merged