add test
MetaMask/metamask-mobile pull request #10380
Opened 2024-07-24 02:29 UTC by plasmacorral

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-07-25 15:07 UTC, cortisiko requested changes
I left a few comments.

2024-07-25 15:07 UTC, cortisiko commented on e2e/specs/accounts/imported-account-remove-and-import.spec.js
> +  SmokeAccounts('removes and reimports an account using a private key'),
Should this be a regression test instead of a smoke test?

2024-07-25 15:07 UTC, cortisiko commented on e2e/specs/accounts/imported-account-remove-and-import.spec.js
> +async function verifyImportedAccountPresence() {
why create seperate methods when these test actions could live within the `it` block?

2024-07-25 15:07 UTC, cortisiko commented on e2e/pages/AccountListView.js
> +    const expectation = element(
Does expectation mean the element in this case the account element?

2024-07-25 15:07 UTC, cortisiko commented on e2e/specs/accounts/imported-account-remove-and-import.spec.js
> +const IMPORTED_LABEL = 'Imported';
this text is probably in the locales folder. Use the string there intead of hard coding it.

2024-07-25 15:07 UTC, cortisiko commented on e2e/specs/accounts/imported-account-remove-and-import.spec.js
> +const accountListView = new AccountListView();
we don't initalize the page object classes but instead we import the class direction. Any reason why you opted to go this way?

2024-07-25 15:15 UTC, cortisiko commented on e2e/selectors/AccountListView.selectors.js
> +  ACCOUNT_TYPE_LABEL_TEXT: 'account-type',
This is a bit confusing. IDs go into the ID selector object and strings go into the string selector object. Perhaps remove 'TEXT' or rename it so it does not include 'TEXT'
```
  ACCOUNT_TYPE_LABEL_TEXT: 'account-type',
```

2024-07-25 15:37 UTC, brianacnguyen approved these changes, later dismissed

2024-07-25 19:16 UTC, plasmacorral commented on e2e/specs/accounts/imported-account-remove-and-import.spec.js
> +  SmokeAccounts('removes and reimports an account using a private key'),
Yes, thank you.  Will update.

2024-07-25 19:17 UTC, plasmacorral commented on e2e/pages/AccountListView.js
> +    const expectation = element(
Yes, will rename to `expectedAccountElement`

2024-07-25 20:57 UTC, plasmacorral commented on e2e/selectors/AccountListView.selectors.js
> +  ACCOUNT_TYPE_LABEL_TEXT: 'account-type',
Good call, updated.  Ty!

2024-07-25 21:00 UTC, plasmacorral commented on e2e/specs/accounts/imported-account-remove-and-import.spec.js
> +const accountListView = new AccountListView();
Was having an issue asserting on the account label.  Once I updated the getter to be static async I was able to remove this line.

2024-07-25 21:00 UTC, plasmacorral commented on e2e/specs/accounts/imported-account-remove-and-import.spec.js
> +const IMPORTED_LABEL = 'Imported';
Updated. TY!

2024-07-25 21:01 UTC, plasmacorral commented on e2e/specs/accounts/imported-account-remove-and-import.spec.js
> +async function verifyImportedAccountPresence() {
Was done initially to try and help with readability and maintainability, but adjusted this to happen within the it block.

2024-07-25 21:41 UTC, owencraston commented on e2e/selectors/AccountListView.selectors.js
> +  ACCOUNT_NAME: 'account-name',
I dont see ACCOUNT_NAME being used.

2024-07-25 21:41 UTC, owencraston approved these changes, later dismissed

2024-07-25 21:53 UTC, plasmacorral commented on e2e/selectors/AccountListView.selectors.js
> +  ACCOUNT_NAME: 'account-name',
removed, ty!

2024-07-25 21:56 UTC, owencraston approved these changes, later dismissed

2024-07-26 19:57 UTC, owencraston approved these changes

2024-07-26 20:49 UTC, cortisiko approved these changes

2024-07-26 21:32 UTC, merged