fix: no insufficient funds warning
MetaMask/metamask-mobile pull request #10385
Opened 2024-07-24 12:38 UTC by OGPoyraz

## **Description**

We should display an insufficient funds for gas warning on mobile confirmations when the user doesn't have enough funds to pay for gas. This fix brings back the warning.

## **Related issues**

Fixes: https://github.com/MetaMask/MetaMask-planning/issues/2564

## **Manual testing steps**

1. Have 0 native asset balance
2. Start a send transaction for an erc20 token (if you don't have balance for it, input 0 as the amount being sent)
3. Notice insufficient funds warning is displayed on the confirmation screen

## **Screenshots/Recordings**

### **Before**

<img width="564" alt="Screenshot 2024-07-24 at 14 33 12" src="https://github.com/user-attachments/assets/a50e2b1b-7d58-4472-901d-1c5d80cc437f">

### **After**

<img width="564" alt="Screenshot 2024-07-24 at 14 31 41" src="https://github.com/user-attachments/assets/c7021452-2221-4f09-aed3-58f05a4f9156">

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-07-25 16:04 UTC, matthewwalsh0 requested changes

2024-07-25 16:04 UTC, matthewwalsh0 commented on app/components/Views/confirmations/SendFlow/Confirm/index.js
> +      return validateEthOrTokenTransaction(
If this just validates the balance and nothing else, could we just call it directly here for clarity?

2024-07-29 11:00 UTC, OGPoyraz commented on app/components/Views/confirmations/SendFlow/Confirm/index.js
> +        prevState.EIP1559GasTransaction.totalMaxHex
:) Done in the latest commit

2024-08-19 09:07 UTC, vinistevam submitted a review, later dismissed

2024-08-19 09:10 UTC, vinistevam commented on app/components/Views/confirmations/SendFlow/Confirm/validation.ts
> +  const [, , amount] = decodeTransferData('transfer', transaction.data);
It may be outside the scope of this ticket, but I see it would be good to change `decodeTransferData` to use `transactionType` and refactor wherever it is being used.

2024-09-03 15:57 UTC, jpuri approved these changes
LGTM

2024-09-04 00:07 UTC, sleepytanya commented
Bitrise builds: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/fc5c1be3-9fca-46d5-8d38-4644002a7bb0?tab=artifacts


Android:


https://github.com/user-attachments/assets/f1d3a92d-bf44-44b1-9467-bd5538fed0f6


iOS:


https://github.com/user-attachments/assets/3ce8a37a-8a8f-45bd-a28c-1698906bd8ee

2024-09-04 08:19 UTC, matthewwalsh0 approved these changes

2024-09-04 08:23 UTC, merged