chore: add details screen/ui elements
MetaMask/metamask-mobile pull request #10451
Opened 2024-07-27 17:33 UTC by Jonathansoufer

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-07-30 13:33 UTC, Prithpal-Sooriya commented on package.json
> +    "react-native-render-html": "^6.3.4",
New package is strictly for allowing us to correctly render feature announcements correctly.

The announcement is created through a WYSIWYG which generates html. But we then need to convert this HTML into React Native compatible components.

2024-07-30 13:34 UTC, Prithpal-Sooriya approved these changes, later dismissed

2024-07-30 18:57 UTC, tommasini commented on app/components/Views/Notifications/Details/styles.ts
> +/* eslint-disable import/prefer-default-export */
I believe this can be removed
```suggestion

```

2024-07-30 18:57 UTC, tommasini commented on app/components/Views/Notifications/Details/index.tsx
> +  };
We could remove this eslint-disable-next-line by creating components for headerLeft and header right I believe, something like this:

I also believe the headerLeft could be memoized because it shouldn't change notification to notification, I will defer the decision of the headerTitle to you, since you have more context on if it changes a lot or not



```suggestion
const HeaderLeft = useCallback(() => (
    <TouchableOpacity onPress={() => navigation.goBack()}>
      <Icon
        name={IconName.ArrowLeft}
        size={IconSize.Md}
        style={styles.backIcon}
      />
    </TouchableOpacity>
  ), [navigation]);

// Only use useCallback here if the state.title is most likely always the same, if not, it is unnecessary to memoize it
  const HeaderTitle = useCallback(() => (
    <Header
      title={state.title}
      subtitle={formatIsoDateString(state.createdAt)}
    />
  ), [state.title, state.createdAt]);
  
    return {
    headerLeft: HeaderLeft,
    headerTitle: HeaderTitle,
  };
```

2024-07-30 18:57 UTC, tommasini commented on app/components/Views/Notifications/Details/Fields/AddressField.tsx
> +import React from 'react';
All the components inside fields should be snapshot tested! So we know easily if for mistake they were changed on the future or not

2024-07-30 18:57 UTC, tommasini commented on app/components/Views/Notifications/Details/Footers/AnnouncementCtaFooter.tsx
> +import React from 'react';
All this Footers components should be snapshot tested so we easily identify unintentional changes on the future

2024-07-30 18:57 UTC, tommasini commented on app/components/Views/Notifications/Details/Headers/AnnouncementImageHeader.tsx
> +import React from 'react';
All this Headers components should be snapshot tested so we easily identify unintentional changes on the future

2024-07-31 08:51 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/Fields/AddressField.tsx
> +import React from 'react';
we're covering these comp on a macro level w/ tests.

2024-07-31 08:51 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/Headers/AnnouncementImageHeader.tsx
> +import React from 'react';
we're covering these comp on a macro level w/ tests.

2024-07-31 08:51 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/Footers/AnnouncementCtaFooter.tsx
> +import React from 'react';
we're covering these comp on a macro level w/ tests.

2024-07-31 09:13 UTC, tommasini commented on app/components/Views/Notifications/Details/Fields/AddressField.tsx
> +import React from 'react';
Yeah, it would be cool to have do those independently as well, since they exist to be re-used, but not a blocker

2024-07-31 09:15 UTC, tommasini approved these changes
LGTM!

2024-07-31 09:15 UTC, tommasini commented on app/components/Views/Notifications/Details/index.tsx
> +  // Only use useCallback here if the state.title is most likely always the same, if not, it is unnecessary to memoize it
I believe we do not need this comment here, it was just a message that I was trying to say for we memoize if the title didn't change on every notification details

2024-07-31 09:16 UTC, tommasini requested changes
Ah, actually the unit tests are failing, let's address that as well

2024-07-31 09:36 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/index.tsx
> +  // Only use useCallback here if the state.title is most likely always the same, if not, it is unnecessary to memoize it
removed.

2024-07-31 16:31 UTC, Prithpal-Sooriya approved these changes

2024-07-31 16:37 UTC, tommasini approved these changes

2024-07-31 16:37 UTC, tommasini approved these changes

2024-07-31 16:46 UTC, merged