chore: Notifications Settings Polishing
MetaMask/metamask-mobile pull request #10457
Opened 2024-07-29 11:08 UTC by Jonathansoufer

## **Description**

This PR are part of a series of PRs to implement the new notifications feature on MetaMask. This brings UI elements together to present our users:

- Notification SETTINGS Screen

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this Settings screen, open the new Notifications option and enable it.

## **Screenshots/Recordings**

https://github.com/MetaMask/metamask-mobile/assets/44679989/80029408-ea8d-424e-9f1d-735423d5ff02

### **Before**

### **After**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-07-29 18:11 UTC, Cal-L reviewed
Left some comments

2024-07-29 18:11 UTC, Cal-L commented on app/components/Views/Settings/NotificationsSettings/index.tsx
> +  const styles = createStyles(colors);
use `useStyles` instead, which will automatically expose theme in the style sheet function

2024-07-29 18:11 UTC, Cal-L commented on app/components/Views/Settings/NotificationsSettings/index.tsx
> +import { useAccountSettingsProps } from '../../../../util/notifications/hooks/useSwitchNotifications';
I may have missed it but where is the file `useSwitchNotifications` in this PR?

2024-07-29 18:11 UTC, Cal-L commented on locales/languages/en.json
> +      "metamask_swap_completed": "Swapped {{symbolIn}} for {{symbolOut}}",
Where is the change in the PR that utilizes this change?

2024-07-29 18:11 UTC, Cal-L commented on locales/languages/en.json
> +      "title_swapped": "Swapped {{symbolIn}} to {{symbolOut}}",
Where is the change in the PR that utilizes this change?

2024-07-30 03:50 UTC, Jonathansoufer commented on app/components/Views/Settings/NotificationsSettings/sectionHeader.tsx
> +/* eslint-disable import/prefer-default-export */
Adjusted.

2024-07-30 04:00 UTC, Jonathansoufer commented on app/components/Views/Settings/NotificationsSettings/index.tsx
> +  const styles = createStyles(colors);
adjusted

2024-07-30 04:01 UTC, Jonathansoufer commented on app/components/Views/Settings/NotificationsSettings/index.tsx
> +import { useAccountSettingsProps } from '../../../../util/notifications/hooks/useSwitchNotifications';
It was introduced [here](https://github.com/MetaMask/metamask-mobile/issues/10340) as part of the break down effort PRs.

2024-07-30 04:02 UTC, Jonathansoufer commented on locales/languages/en.json
> +      "metamask_swap_completed": "Swapped {{symbolIn}} for {{symbolOut}}",
[Here](https://github.com/MetaMask/metamask-mobile/blob/5a892bbfa91a0850c39f0a9225a993598eaef1a3/app/util/notifications/notification-states/swap-completed/swap-completed.tsx)

2024-07-30 04:03 UTC, Jonathansoufer commented on locales/languages/en.json
> +      "title_swapped": "Swapped {{symbolIn}} to {{symbolOut}}",
[Here](https://github.com/MetaMask/metamask-mobile/blob/5a892bbfa91a0850c39f0a9225a993598eaef1a3/app/util/notifications/notification-states/swap-completed/swap-completed.tsx)

2024-07-30 13:35 UTC, Prithpal-Sooriya submitted a review, later dismissed

2024-07-30 19:03 UTC, tommasini commented
@Jonathansoufer I can see that this PR have multiple E2E failures, let's address those first

2024-07-30 19:18 UTC, Cal-L commented
Let's fix the CI checks

2024-07-31 11:22 UTC, Prithpal-Sooriya submitted a review, later dismissed

2024-08-13 15:48 UTC, Prithpal-Sooriya submitted a review, later dismissed

2024-08-13 23:15 UTC, tommasini commented on app/components/Views/Settings/NotificationsSettings/NotificationOptionToggle/index.tsx
> +          name={icon as IconName}
Instead of casting here as IconName we could type it [here](https://github.com/MetaMask/metamask-mobile/blob/72339d1045c4a2ad4c107710ec0be73991ee1e03/app/components/Views/Settings/NotificationsSettings/NotificationOptionToggle/index.tsx#L25) wdyt?

2024-08-13 23:15 UTC, tommasini commented on app/components/Views/Settings/NotificationsSettings/NotificationOptionToggle/index.tsx
> +          type={icon as AvatarAccountType}
Hmm I see why my comment above could not make sense

2024-08-13 23:19 UTC, tommasini commented
When opening the network bottom sheed on the notification is intended to the button of the "View on block explorer" keep being visible? 
Recording time: 0.50 second
<img width="504" alt="image" src="https://github.com/user-attachments/assets/b05c5941-15f2-4e85-ae33-25f05893cb4e">

2024-08-13 23:21 UTC, tommasini commented
Curious question: Why the swap doesn't have the button to see at the "View Block Explorer" ?
Recording time: 1:27 min
<img width="546" alt="image" src="https://github.com/user-attachments/assets/c6c84d7f-2a65-42d5-b456-5ce8908dafec">

2024-08-14 06:46 UTC, Jonathansoufer commented on app/components/Views/Settings/NotificationsSettings/NotificationOptionToggle/index.tsx
> +          name={icon as IconName}
This was based on another suggestions coming from a review which led to `icon?: AvatarAccountType | IconName;`. when we avoid the usage of `any`.

2024-08-14 06:47 UTC, Jonathansoufer commented on app/components/Views/Settings/NotificationsSettings/NotificationOptionToggle/index.tsx
> +          type={icon as AvatarAccountType}
yep. answered above already.

2024-08-14 06:50 UTC, Jonathansoufer commented
> Curious question: Why the swap doesn't have the button to see at the "View Block Explorer" ? Recording time: 1:27 min <img alt="image" width="546" src="https://private-user-images.githubusercontent.com/46944231/357609742-c6c84d7f-2a65-42d5-b456-5ce8908dafec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MTgxNDUsIm5iZiI6MTcyMzYxNzg0NSwicGF0aCI6Ii80Njk0NDIzMS8zNTc2MDk3NDItYzZjODRkN2YtMmE2NS00MmQ1LWI0NTYtNWNlODkwOGRhZmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDA2NDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YjQzNGM3OGUzMzk3YWNkZWE2Yzc5MGQ4N2Y4ZGVmMDdjMmFkYTM4OGExZGNhMTE5YjM0OGY2MTllNzY5ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZPftZ3J9zy8p6QUF32wUa77uNUymN3KV1DJiJ3FBKEw">

Good catch. Fixed.

2024-08-14 13:26 UTC, tommasini commented on app/components/Views/Settings/NotificationsSettings/index.tsx
> +  }, [accountSettingsProps]);
I wonder for we not need to use the  `// eslint-disable-next-line react-hooks/exhaustive-deps` we could refactor to refetchAccountSettings outside, since we do not want this to re render when the accounts coming from `useAccounts` change, we do not need it to add it to the dependency that way. 

```suggestion
    const refetchAccountSettings = async () => {
    await accountSettingsProps.update(accountAddresses);
  };

  const renderAccounts = useCallback(() => {
    return accounts.map((account) => (
      <NotificationOptionToggle
        type={NotificationsToggleTypes.ACCOUNT}
        icon={accountAvatarType}
        key={account.address}
        title={account.name}
        address={account.address}
        disabledSwitch={accountSettingsProps.initialLoading}
        isLoading={accountSettingsProps.accountsBeingUpdated.includes(
          account.address,
        )}
        isEnabled={
          accountSettingsProps.data?.[account.address.toLowerCase()] ?? false
        }
        refetchAccountSettings={refetchAccountSettings}
      />
    ));
  }, [
    accounts,
    accountAvatarType,
    accountSettingsProps.initialLoading,
    accountSettingsProps.accountsBeingUpdated,
    accountSettingsProps.data,
    refetchAccountSettings,
  ]);
```

I'm assuming that this was done to avoid a infinite loop, but I do not see why that would cause it, is the `useAccounts` hook always returning a different accounts object? If yes, more likely we should create an issue to try to see where the problem lives, wdyt?

2024-08-14 13:26 UTC, tommasini requested changes
The PR LGTM! Just left a comment that we would want to address!

2024-08-14 13:27 UTC, tommasini approved these changes, later dismissed

2024-08-14 14:41 UTC, Prithpal-Sooriya approved these changes

2024-08-14 14:44 UTC, tommasini approved these changes

2024-08-14 14:45 UTC, merged