chore: Capture custom rpc url in `trackEvent`
MetaMask/metamask-mobile pull request #10468
Opened 2024-07-30 06:00 UTC by gambinish

## **Description**

Custom `rpcUrls` were not being emitted to MetaMetrics, only `chainId`. Task was to emit a `NETWORK_ADDED` event whenever a custom RPC url was added in settings. As a privacy step, we are hashing the `rpcUrl` when it gets sent, and emitted the event with `trackAnonymousEvent`

Additionally, I noticed that custom RPCs were being tracked from `source: 'Popular network list'` rather than `Custom network form`. This event should probably also be emitted on "Add Network" action, rather than "Switching Networks" action, since switching networks technically is not required in order to "Add Network".

I have a question: rather than hardcoding, I would like to import `popularNetworkIds` from `app/util/networks/customNetworks.tsx` but am running into compilation issues. Any idea why? Is this a core package change that needs to be published externally and then installed locally into the repo?

## **Related issues**

Fixes: MMASSETS-298

## **Manual testing steps**

1. Go to Settings view
2. Add Popular network, validate that event gets emitted by with `source: "Popular network list"`
3. Add Custom network, validate that event gets emitted by with `source: "Custom network form"`

## **Screenshots/Recordings**

Popular Network:

https://github.com/user-attachments/assets/1b3bc09b-fbcc-4505-bea6-36151c5f5694

Custom Network

https://github.com/user-attachments/assets/e23fb2df-a174-4eba-8ef9-e75a0f42ccc8

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-07-30 16:09 UTC, bergeron commented on app/components/UI/NetworkModal/index.tsx
> +    if (!popularNetworkIds.includes(chainId)) {
I don't think this is determinable based on chain id.  A network being on the popular list does not prevent you from adding it via the custom form.

2024-07-30 20:09 UTC, gambinish commented on app/components/UI/NetworkModal/index.tsx
> +    if (!popularNetworkIds.includes(chainId)) {
Refactored to use `showPopularNetworksModal` boolean here: https://github.com/MetaMask/metamask-mobile/pull/10468/commits/52320079f715e9cedd639dfcce09b7da5ada09de

2024-07-30 23:06 UTC, legobeat requested changes
Has analysis been done on the resistance of this scheme against rainbow-table attacks?
 
https://github.com/MetaMask/metamask-mobile/pull/10468/files#r1697698617

2024-07-30 23:46 UTC, gambinish commented on app/components/UI/NetworkModal/index.tsx
> +        rpcUrl: ethers.utils.sha256(ethers.utils.toUtf8Bytes(rpcUrl)),
Thanks for pointing this out. I am going to link the companion PR on extensions so that this issue can be tracked together: https://github.com/MetaMask/metamask-extension/pull/26203/files#diff-8e09bedbf5f945a64e22a83416aeb4c5f890318acfa999b5ebedd7ff102b58a3R973

2024-08-23 19:33 UTC, gambinish commented
> From PR description:
> 
> > As a privacy step, we are hashing the rpcUrl when it gets sent, and emitted the event with trackAnonymousEvent
> 
> Where is this happening?

These are no longer being hashed, since we are only sending over chains that are popular and in the `safeChains` list. Follows the same strategy as the extensions PR that got merged, which is effectively this same implementation.

I can update the description.

2024-08-23 19:51 UTC, gambinish commented on app/components/UI/NetworkModal/index.tsx
> +    if (!showPopularNetworkModal && safeChains) {
In the `useSafeChains` hook, `safeChains` is undefined before they get fetched.

2024-08-30 10:51 UTC, NicolasMassart reviewed
Only questions is if you evaluated privacy risk and if so, is there's any need for anonymous event.
Otherwise looks good!

2024-08-30 10:51 UTC, NicolasMassart commented on app/components/UI/NetworkModal/index.tsx
> +      });
Q: is there any privacy risk by associating these infos with the user metrics ID?
If so, you should make it an anonymous event for instance like the following:
```ts
      trackEvent(MetaMetricsEvents.NETWORK_ADDED, {
        propertie: {
          source: 'Custom Network Added',
        }
        sensitiveProperties: {
          chain_id: toHex(safeChain.chainId),
          symbol: safeChain.nativeCurrency.symbol,
          rpcUrl: safeRPCUrl,
        },
      });
```
In this example only the source is not an anonymous value and will be sent with both anonymous (with anonymous ID) and non-anonymous (with actual user unique ID) events.
The sensitiveProperties will only be sent with the anonymous (with anonymous ID) event.

2024-08-30 10:51 UTC, NicolasMassart commented on app/components/UI/NetworkModal/index.tsx
> +      trackEvent(MetaMetricsEvents.NETWORK_ADDED, {
Q: same question here about anonymous event

2024-09-03 17:24 UTC, gambinish commented on app/components/UI/NetworkModal/index.tsx
> +      });
Good call! There is a slightly different pattern on Extension so I was a bit unsure. I'll go ahead and make this change.

2024-09-03 17:35 UTC, gambinish commented on app/components/UI/NetworkModal/index.tsx
> +      trackEvent(MetaMetricsEvents.NETWORK_ADDED, {
We were already emitting this event non-anonymously previously as chainId isn't/shouldn't necessarily be personally identifiable like a custom rpc url is (ie a dev running a local eth node). Changes in this PR are to add telemetry for custom rpcs

So, similar to how we are doing in this [PR](https://github.com/MetaMask/metamask-extension/pull/26266) on extension, we only want to capture the rpc url as a sensitive property.

2024-09-03 17:49 UTC, gambinish commented on app/components/UI/NetworkModal/index.tsx
> +    if (!showPopularNetworkModal && safeChains) {
Would you say that this change is strictly necessary for this PR to get merged? I suppose we could do a reverse lookup on `NETWORKS_CHAIN_ID` but I'm not sure how much value that would add to this from a privacy perspective (if any) since the chainId and ticker that get evaluated here only ever get sent from our popular network list anyway?

If I'm missing something here please lmk. Might need to spell this out a bit more if I'm not seeing a big blindspot.

2024-09-06 22:25 UTC, NicolasMassart approved these changes, later dismissed
Looks good to me.

2024-09-08 21:38 UTC, legobeat commented on app/components/UI/NetworkModal/index.tsx
> +    if (!showPopularNetworkModal && safeChains) {
> since the chainId and ticker that get evaluated here only ever get sent from our popular network list anyway?

> [(they are being evaluated from the hardcoded popular networks list in the source code, rather than API response)](https://github.com/MetaMask/metamask-mobile/pull/10468/files#r1742443707)

It may be me who's missing something, because it looks like this will trigger also for user-added custom networks, where `chainId`, `rpcUrl`, and `ticker` will e free-form user-defined values. Your comments indicate that this is not the case. Could you help by pointing mere to how this is limited only to networks on the popular-networks list?

2024-09-09 17:01 UTC, gambinish commented on app/components/UI/NetworkModal/index.tsx
> +    if (!showPopularNetworkModal && safeChains) {
Can you message me directly in Slack plz? Would like to get this resolved so that we can move on, rather than going back and forth here.

2024-09-10 04:35 UTC, legobeat commented on app/components/UI/NetworkModal/index.tsx
> +      Logger.log('Unable to capture custom network');
```suggestion
      Logger.log('MetaMetrics - Unable to capture custom network');
```

2024-09-10 04:37 UTC, legobeat commented on app/components/UI/NetworkModal/index.tsx
>      const validUrl = validateRpcUrl(rpcUrl);
```suggestion
    const isValidUrl = validateRpcUrl(rpcUrl);
```

2024-09-10 04:38 UTC, legobeat commented on app/components/UI/NetworkModal/index.tsx
>      setNetworkAdded(validUrl);
```suggestion
    setNetworkAdded(isValidUrl);
```

2024-09-10 04:38 UTC, legobeat commented on app/components/UI/NetworkModal/index.tsx
> +    } else if (!showPopularNetworkModal && safeChains) {
```suggestion
    } else if (safeChains) {
```

2024-09-10 04:53 UTC, legobeat approved these changes
LGTM!

2024-09-10 08:09 UTC, NicolasMassart approved these changes
Looks good to me.

2024-09-10 13:48 UTC, merged