Fix: Refacor blockaid metrics methods to async
MetaMask/metamask-mobile pull request #10518
Opened 2024-08-01 09:53 UTC by vinistevam

## **Description**
After this [PR](https://github.com/MetaMask/metamask-mobile/pull/10267) to use the Security alert API to get the supported chains via `isChainSupported` which now it's an async function and we saw that is used across the blockaid metrics in the mobile client. So this PR aims to refactor every place that used it to support asynchronously.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-08-13 16:37 UTC, pedronfigueiredo approved these changes, later dismissed

2024-08-14 09:02 UTC, matthewwalsh0 submitted a review, later dismissed

2024-08-19 08:31 UTC, pedronfigueiredo submitted a review, later dismissed

2024-08-19 10:12 UTC, jpuri requested changes
If a confirmation has `securityAlertResponse` we can add metrics for it. We do validation only after checking if blockaid is enabled. Check before getting metrics params again looks redundant.

2024-08-20 08:47 UTC, vinistevam commented
> If a confirmation has `securityAlertResponse` we can add metrics for it. We do validation only after checking if blockaid is enabled. Check before getting metrics params again looks redundant.

Reverted changes in `getBlockaidMetricsParams` and `getBlockaidTransactionMetricsParams`.

2024-09-02 08:01 UTC, matthewwalsh0 approved these changes, later dismissed

2024-09-03 14:05 UTC, jpuri commented on app/components/Views/confirmations/SendFlow/Confirm/index.js
> -          {isBlockaidFeatureEnabled() && this.state.transactionMeta?.id && (
We can even avoid `isBlockaidFeatureEnabled` below as `TransactionBlockaidBanner` render only is there is a `securityAlertResponse`.

2024-09-03 14:06 UTC, jpuri commented on app/components/Views/confirmations/SendFlow/Confirm/index.js
> +    if (isBlockaidEnabled) {
We can avoid this check here as `ppomUtil.validateRequest(reqObject, id);` will work only if blockaid is enabled.

2024-09-03 14:07 UTC, jpuri commented on app/lib/ppom/ppom-util.ts
> +    !isBlockaidFeatEnabled ||
👍

2024-09-03 14:08 UTC, jpuri reviewed
Changes look great, I left some small feedbacks to be addressed.

2024-09-06 08:25 UTC, vinistevam commented on app/components/Views/confirmations/SendFlow/Confirm/index.js
> +    if (isBlockaidEnabled) {
done [here](https://github.com/MetaMask/metamask-mobile/pull/10518/commits/8ee73b8a2d0ffac98af2a7bbcf5401cb88f10d39)

2024-09-06 12:10 UTC, jpuri approved these changes

2024-09-06 12:41 UTC, matthewwalsh0 approved these changes

2024-09-06 13:38 UTC, merged