Feat/parse tx logs to update nft state
MetaMask/metamask-mobile pull request #10529
Opened 2024-08-01 19:30 UTC by sahar-fehri

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-08-26 11:44 UTC, salimtb commented on app/components/UI/Navbar/index.js
> +              testID="more"
can we call this test-id "more-button" instead ?

2024-08-26 11:44 UTC, salimtb commented on app/components/Views/NftDetails/NftDetails.test.tsx
> +import * as allSelectors from '../../../../app/reducers/collectibles/index.js';
Suggestion: instead of using global import then use spyOn , it's better to mock the whole module using `jest.mock`.
using jest mock have some advantage like avoid leaking mock btw tests, better readable tests and improve performence, here is an example:

```

// Mock the selectors directly
jest.mock('../../../../app/reducers/collectibles/index.js', () => ({
  collectiblesSelector: mockedCollectiblesSelector,
  collectibleContractsOwnedSelector: mockedCollectibleContractsOwnedSelector,
}));

// use it inside specific test
    mockedCollectibleContractsOwnedSelector.mockReturnValue(data);

```
link to the documentation: https://jestjs.io/docs/jest-object#jestmockmodulename-factory-options

2024-08-26 11:44 UTC, salimtb commented on app/components/Views/NftDetails/NftDetails.test.tsx
> +    spyOnContracts.mockRestore();
i'm seeing the use of mockRestore after several tests , this can be common by using afterEach:
```
  afterEach(() => {
    cleanup();
    jest.restoreAllMocks(); // This will restore all mocked functions after each test
  });
  ```

2024-10-18 20:59 UTC, gambinish commented on app/core/Engine.ts
> +    }
This makes me a bit nervous. Not sure what the downstream effects of this would be. There might be some CI or testing environment flags that we aren't aware of?

I'm noticing that we had spys implemented previously. Were they not spying previously? Could you help understand why this is necessary now?

If changing the unit tests is way too hard, I wonder if this might be safer 

```
  import { DEVELOPMENT } from "./AppConstants"
   if (process.env.NODE_ENV !== DEVELOPMENT) {
      Object.freeze(instance);
    }
```

What do you think?

2024-10-18 21:01 UTC, gambinish commented on app/core/Engine.ts
> +            // ignore
Did you meant to log the caught err here?

2024-10-18 21:05 UTC, gambinish requested changes
Leaving a couple questions here. Also, if theses are dev accounts that you are using, could we share the accounts that you used in your recording? Will make testing easier on my end 🙇

2025-01-23 22:33 UTC, closed without merging