fix: replaced incorrect icons on wallet bottom sheet with correct icons
MetaMask/metamask-mobile pull request #10532
Opened 2024-08-01 23:05 UTC by vinnyhoward

## **Description**
Replaced incorrect icons with correct icons raised from this [issue](https://github.com/MetaMask/metamask-mobile/issues/8053) icon assets pulled from [Figma](https://www.figma.com/file/MlBUrNnIXlftX4TSjqiUYg/Core-Components?type=design&node-id=1213-7938&mode=design&t=jTWqDkNHlaMh3yiO-0)

There is a slight deviation from the design where `minus` was not shown in the Figma so I just increased the stroke of the current minus to be the same weight as the icons

## **Related issues**

Fixes: N/A

## **Manual testing steps**

1. Click on action tab
2. Compare action tab from Figma to this build
3. Compare action tab from previous build to this build or just look at my screenshots

## **Screenshots/Recordings**

| Before  | After  |
|:---:|:---:|
| ![Screenshot 2024-08-01 at 4 02 59 PM](https://github.com/user-attachments/assets/03a113e5-8b78-4c58-b4ed-ebcb2c7821ff) | ![Screenshot 2024-08-01 at 4 40 13 PM](https://github.com/user-attachments/assets/23cf1052-3007-418a-8909-05dcec9b99b4) | 

### **Before**
N/A

### **After**
N/A

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-08-02 03:01 UTC, vinnyhoward commented
I have read the CLA Document and I hereby sign the CLA

2024-08-02 09:36 UTC, mirceanis submitted a review, later dismissed
Looks good

2024-08-02 13:35 UTC, EtherWizard33 approved these changes, later dismissed
LGTM

2024-08-02 13:40 UTC, EtherWizard33 commented
about the label check that is failing, i suspect it could be because of something seen last month, when someone added a job or action that automatically adds the team label provided based on the PR author name, it's possible that you will need to add your name to the repo or ask someone who has the rights to do so:

I believe that someone in this thread had the same issue https://consensys.slack.com/archives/C02U025CVU4/p1719431165050949

2024-08-06 00:11 UTC, brianacnguyen requested changes
Request change with new icon files that I sent

2024-08-12 18:37 UTC, brianacnguyen commented on app/component-library/components/Icons/Icon/assets/swap-vertical.svg
Can you update this svg with the ones i sent?

2024-08-12 18:38 UTC, brianacnguyen requested changes
Requesting SVG changes

2024-08-12 18:38 UTC, brianacnguyen commented on app/components/Views/WalletActions/WalletActions.tsx
> +            iconName={IconName.MinusBold}
Can you provide a screenshot/screencap for this change?

2024-08-12 19:08 UTC, vinnyhoward commented on app/components/Views/WalletActions/WalletActions.tsx
> +            iconName={IconName.MinusBold}
The PR screenshots should be updated with them now

2024-08-12 19:15 UTC, brianacnguyen approved these changes

2024-08-12 21:22 UTC, merged