Fix/notifications first round of tests
MetaMask/metamask-mobile pull request #10668
Opened 2024-08-15 20:17 UTC by Jonathansoufer

## **Description**

This PR introduces smalls fixes on Notifications feature after the first round of tests.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-08-15 20:21 UTC, Prithpal-Sooriya submitted a review, later dismissed

2024-08-15 20:34 UTC, tommasini commented
Unit tests are failing!

Can you update the description with what the issues that were discovered and what the PR is aiming to fix? It will help the reviews

2024-08-15 21:00 UTC, tommasini submitted a review, later dismissed
LGTM!

2024-08-15 21:12 UTC, Prithpal-Sooriya submitted a review, later dismissed

2024-08-16 12:41 UTC, Prithpal-Sooriya approved these changes, later dismissed

2024-08-16 13:34 UTC, tommasini submitted a review, later dismissed

2024-08-16 13:56 UTC, FrederikBolding requested changes

2024-08-16 13:56 UTC, FrederikBolding commented on app/lib/snaps/SnapsExecutionWebView.tsx
> +              uri: SNAPS_EE_URL,
We can't do this as-is because it would mean that the WebView is loaded when the app loads even if the user has the "basic functionality" toggle.

2024-08-16 14:12 UTC, Jonathansoufer commented on app/lib/snaps/SnapsExecutionWebView.tsx
> +              uri: SNAPS_EE_URL,
Added flag on it.

2024-08-16 16:07 UTC, Prithpal-Sooriya approved these changes

2024-08-16 16:15 UTC, tommasini approved these changes

2024-08-16 17:14 UTC, FrederikBolding approved these changes

2024-08-16 17:42 UTC, merged