chore: updates needed to support swaps-controller v10 (WIP)
MetaMask/metamask-mobile pull request #10743
Opened 2024-08-22 11:49 UTC by nikoferro

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-04 21:00 UTC, infiniteflower commented
Need to delete the patch introduced in https://github.com/MetaMask/metamask-mobile/pull/10960

SwapsController v10 will have this: https://github.com/MetaMask/swaps-controller/pull/312

2024-09-27 07:48 UTC, nikoferro commented
> Need to delete the patch introduced in #10960
> 
> SwapsController v10 will have this: [MetaMask/swaps-controller#312](https://github.com/MetaMask/swaps-controller/pull/312)

Just updated the PR and removed this.

2024-09-30 12:37 UTC, martahj approved these changes, later dismissed
Have not QA'd it but code lgtm!

2024-10-02 13:44 UTC, martahj submitted a review, later dismissed

2024-10-04 07:09 UTC, legobeat commented on app/core/Engine.ts
> +        fetchGasFeeEstimates: () => gasFeeController.fetchGasFeeEstimates(),
Is this already done?


(`@metamask/gas-fee-controller@15.1.2`)

https://github.com/MetaMask/core/blob/d30f7df58f403cc9c68e4fe0652abf7320dbd852/packages/gas-fee-controller/src/GasFeeController.ts#L230

Or is this refering to something else?

2024-10-06 16:58 UTC, nikoferro commented on app/core/Engine.ts
> +        fetchGasFeeEstimates: () => gasFeeController.fetchGasFeeEstimates(),
Its quite similar... the one you are proposing is the action to get the state, but not the one that triggers fetching the estimates on GasFeeController. 

I do see that the GasFeeController has a polling mechanism, but would need to dig deeper if getting the latest state of the controller is enough without manually triggering the fetch first (worth mentioning that the fetch function does return the new values, so we are not consuming this from the GasFeeController state directly)

If this is the case, i would keep it as a quick TODO for the next iteration, since changing this now, involves a new SwapsController release also. So i would prefer to merge v10.0.0 first, and then we can update (if this is the case), the controller with reading directly from the GasFeeController state from within the SwapsController on the next major

2024-10-16 09:42 UTC, Daniel-Cross requested changes
This looks good but there's little to no checks or tests ran against these new changes.

At the very least, please run `E2E smoke tests` on the PR. I already added the label, you may need to remove and add again to get it to run.

I would also like to see some test coverage on the changes. At the moment I just have to trust this doesn't break anything.

2024-11-20 00:17 UTC, infiniteflower commented
Tested

2024-11-20 14:15 UTC, Daniel-Cross approved these changes
Looks good!

2024-11-20 19:09 UTC, jclancy93 approved these changes
Tested locally and everything LGTM!

2024-11-20 19:14 UTC, bergeron approved these changes

2024-11-20 19:32 UTC, merged