chore: Enable typescript coverage for all the files
MetaMask/metamask-mobile pull request #10745
Opened 2024-08-22 15:20 UTC by tommasini

## **Description**

This PR enables the TS coverage for the mobile app. From now on all the TS issues will be spotted.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-08-26 23:31 UTC, gambinish commented on app/components/UI/AssetOverview/TokenDetails/TokenDetails.tsx
> +  fullyDiluted: string | null;
👍

2024-08-26 23:31 UTC, gambinish submitted a review, later dismissed
LGTM thanks for the heads up ✅

2024-08-26 23:33 UTC, Cal-L approved these changes, later dismissed
LGTM

2024-08-26 23:36 UTC, gambinish submitted a review, later dismissed

2024-08-27 15:03 UTC, brianacnguyen requested changes
Question regarding the AvatarGroup change

2024-08-27 15:23 UTC, tommasini commented on app/component-library/components/Avatars/AvatarGroup/AvatarGroup.types.ts
> +   * Token Name.
Because it was not cleaned from where it was being used: https://github.com/MetaMask/metamask-mobile/blob/72339d1045c4a2ad4c107710ec0be73991ee1e03/app/components/hooks/useAccounts/useAccounts.types.ts#L5

2024-08-27 15:28 UTC, brianacnguyen commented on app/component-library/components/Avatars/AvatarGroup/AvatarGroup.types.ts
> +   * Token Name.
The previous implementation only allows a group of tokens. That PR updated it so all kinds of avatars can be used, so if you need a group of avatar tokens, you can just pass the same object in the `avatarPropsList`
What you have in your PR essentially is the prop for `AvatarToken` https://github.com/MetaMask/metamask-mobile/blob/main/app/component-library/components/Avatars/Avatar/variants/AvatarToken/AvatarToken.types.ts

2024-08-27 15:32 UTC, tommasini commented on app/component-library/components/Avatars/AvatarGroup/AvatarGroup.types.ts
> +   * Token Name.
Thank you!
Pushed on this commit : https://github.com/MetaMask/metamask-mobile/pull/10745/commits/39723fd64df2604c06f1a1dc59b88d9ccb08dde0

2024-08-27 15:33 UTC, brianacnguyen commented on app/component-library/components/Avatars/AvatarGroup/AvatarGroup.types.ts
> +   * Token Name.
`import { AvatarTokenProps } from '../../../component-library/components/Avatars/Avatar/variants/AvatarToken/AvatarToken.types.ts'; `
`tokens?: AvatarTokenProps[];`
would be my recommendation

2024-08-27 15:35 UTC, tommasini commented on app/component-library/components/Avatars/AvatarGroup/AvatarGroup.types.ts
> +   * Token Name.
Thanks! Done [here](https://github.com/MetaMask/metamask-mobile/pull/10745/commits/af640d59ddf31131fd0868a62e8ece9c7730e687)

2024-08-27 15:38 UTC, brianacnguyen approved these changes, later dismissed

2024-08-27 17:50 UTC, Cal-L submitted a review, later dismissed
LGTM

2024-08-27 19:04 UTC, Cal-L approved these changes
LGTM

2024-08-27 19:22 UTC, merged