chore: update eslint v^8.44
MetaMask/metamask-mobile pull request #10865
Opened 2024-08-28 15:06 UTC by tommasini

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-08-28 16:09 UTC, tommasini commented on storybook/decorators/withSafeArea.tsx
> -/* eslint-disable import/prefer-default-export */
revert this change

2024-08-29 16:12 UTC, tommasini commented on package.json
> -    "@metamask/eslint-config": "^9.0.0",
This was not being used, instead of removing it should we apply it?

2024-08-29 16:27 UTC, tommasini commented on package.json
> -    "@metamask/eslint-config": "^9.0.0",
By apply it, I mean create a new all effort to address the issues that appear by applying it
10248 problems (10219 errors, 29 warnings)

2024-08-30 16:38 UTC, leotm commented
@SocketSecurity ignore npm/string.prototype.repeat@1.0.0
New Author: nicolo-ribaudo, Previous Author: mathias

2024-09-03 13:31 UTC, wachunei submitted a review, later dismissed
Ramp changes LGTM

2024-09-03 14:40 UTC, NicolasMassart commented on app/core/MobilePortStream.js
> +  _write = function (msg, enconding, cb) {
You introduced a typo here...

2024-09-03 14:40 UTC, NicolasMassart commented on app/selectors/accountTrackerControllerReRenders.test.tsx
> +
Q: why all these empty lines?

2024-09-03 14:40 UTC, NicolasMassart commented on e2e/pages/Settings/AesCryptoTestForm.js
It has types in it! We may have to convert it before just changing the extension.

2024-09-03 14:40 UTC, NicolasMassart commented on patches/@metamask+eslint-config-typescript+9.0.1.patch
Can you add the usual patch comment to explain the reason for it please?

2024-09-03 15:03 UTC, brianacnguyen requested changes
Icon changes look good. For safety, can you attach a screenshot of an Icon from either the app or storybook to make sure theyre still functioning as expected?

2024-09-06 10:49 UTC, tommasini commented on app/selectors/accountTrackerControllerReRenders.test.tsx
> +
It seems prettier didn't cover this file :o

2024-09-06 11:07 UTC, tommasini commented on app/selectors/accountTrackerControllerReRenders.test.tsx
> +
Addressed [here](https://github.com/MetaMask/metamask-mobile/pull/10865/commits/be044bd2e2fbac632ce2cedfc058fe648d041d63)

2024-09-06 11:08 UTC, tommasini commented on app/core/MobilePortStream.js
> +  _write = function (msg, enconding, cb) {
Amazing catch! Yeah it is an unused variable :( I deleted but then reverted because going that route would be a super big PR, addressed here: https://github.com/MetaMask/metamask-mobile/pull/10865/commits/be044bd2e2fbac632ce2cedfc058fe648d041d63

2024-09-06 11:08 UTC, tommasini commented on e2e/pages/Settings/AesCryptoTestForm.js
Interesting, now it's fixed let's re run the e2e

2024-09-06 11:08 UTC, tommasini commented on patches/@metamask+eslint-config-typescript+9.0.1.patch
Added [here](https://github.com/MetaMask/metamask-mobile/pull/10865/commits/be044bd2e2fbac632ce2cedfc058fe648d041d63)

2024-09-06 11:09 UTC, tommasini commented
@brianacnguyen Video added! Thanks for bringing it up!

2024-09-06 15:10 UTC, brianacnguyen approved these changes
Approved icon changes

2024-09-08 09:09 UTC, abretonc7s approved these changes

2024-09-09 09:38 UTC, jpuri approved these changes

2024-09-09 09:49 UTC, NicolasMassart approved these changes
Looks good to me.

2024-09-09 10:07 UTC, merged