Test/private-key-reveal
MetaMask/metamask-mobile pull request #10879
Opened 2024-08-29 00:57 UTC by plasmacorral

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-08-29 15:28 UTC, cortisiko requested changes, later dismissed
left some small feedback.

2024-08-29 15:28 UTC, cortisiko commented on e2e/selectors/Modals/SrpQuizModal.selectors.js
> +  IDs: {
Mind updating the selectors to following our best practices guide? https://github.com/MetaMask/contributor-docs/blob/main/docs/e2e/mobile-e2e-guidelines.md#test-ids

2024-08-29 15:28 UTC, cortisiko commented on e2e/pages/modals/SrpQuizModal.js
> +  async tapGetStartedDismiss() {
this name is a bit vague. Is it tapping on the dismiss button or is it tapping on get started?

2024-08-29 17:42 UTC, plasmacorral commented on e2e/pages/modals/SrpQuizModal.js
> +  async tapGetStartedDismiss() {
Nice catch, thank you. This is dismissing the get started screen.  I renamed this to `tapGetStartedScreenDismiss`

2024-08-29 17:47 UTC, plasmacorral commented on e2e/selectors/Modals/SrpQuizModal.selectors.js
> +  IDs: {
This PR was based on the in-flight work to reveal SRP.  I addressed this suggestion on PR [10754](https://github.com/MetaMask/metamask-mobile/pull/10754) and rebased this PR.  Once I get SRP reveal merged I will rebase on main and take this PR out of draft.  Thank you for taking the time to provide feedback!

2024-08-29 21:24 UTC, cortisiko commented on e2e/specs/accounts/reveal-private-key.spec.js
> +  async function handleIncorrectPassword(password) {
There is no need to have a function for assertions in the test file itself. Any test action needs to live in the page object itself. The assertions should live within the test.

2024-08-30 02:43 UTC, owencraston submitted a review, later dismissed

2024-08-30 03:03 UTC, plasmacorral commented on e2e/specs/accounts/reveal-private-key.spec.js
> +  async function handleIncorrectPassword(password) {
removed, thanks!

2024-08-30 03:35 UTC, owencraston approved these changes

2024-08-30 03:43 UTC, merged