chore: Chore/detect pod diffs
MetaMask/metamask-mobile pull request #10880
Opened 2024-08-29 01:05 UTC by Cal-L

## **Description**

This PR does two things:
1. Moves Gemfile into iOS directory, which is where it belongs since it only relates to iOS. We also updated everywhere that calls bundle install or exec so it's calling it in the ios directory
2. Run pod install in CI for detecting diffs in Podfile.lock

## **Related issues**

Fixes:

## **Manual testing steps**

- Running `yarn setup` still works normally when run locally
- CI passes when run
- CI fails when Podfile.lock is changed when pod install runs in the CI

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-05 01:15 UTC, legobeat requested changes, later dismissed

2024-09-05 01:15 UTC, legobeat commented on scripts/setup.mjs
> +  prepareDependenciesTask,
`setupIosTask` [depends](https://github.com/MetaMask/metamask-mobile/actions/runs/10710006807/job/29695856882?pr=10880) on patch done in `patchPackages`, and can therefore not be run concurrently with `prepareDependenciesTask`.

(the same might hold in the future if any of the other steps start relying on package patches in any way).

2024-09-05 04:12 UTC, legobeat commented on scripts/setup.mjs
> +  prepareDependenciesTask,
- 11052

2024-09-18 17:01 UTC, Cal-L commented on .depcheckrc.yml
> +  - 'patch-package'
No longer used in package.json scripts

2024-09-18 17:01 UTC, Cal-L commented on .github/workflows/ci.yml
> +      - uses: ruby/setup-ruby@a6e6f86333f0a2523ece813039b8b4be04560854 #v1
Specify Ruby config

2024-09-18 17:01 UTC, Cal-L commented on .github/workflows/ci.yml
> +        check-diff,
Rename to be more accurate

2024-09-18 17:02 UTC, Cal-L commented on ios/Podfile
> -  pod 'OpenSSL-Universal', :modular_headers => true, :configurations => ['Release']
Remove redundant OpenSSL dep

2024-09-18 17:03 UTC, Cal-L commented on package.json
> -    "setup:node": "yarn allow-scripts && yarn patch-package",
No longer needed since we use `yarn setup` with args

2024-09-18 17:04 UTC, Cal-L commented on scripts/setup.mjs
These changes reorganizes the steps to run all deps in sequence and standalone ones concurrently

2024-09-18 17:05 UTC, Cal-L reviewed
Added notes

2024-09-18 23:41 UTC, legobeat commented on scripts/setup.mjs
> +    case '--skip-pods':
Do I get it right if `--skip-pods` on macOS is basically the inverse of `--build-ios` on other platforms? Feels like this is approaching the point where more complete cli parsing would be nice (so we could use something like `--build-ios=false` on macOS)?

In any case, could this case be changed to `BUILD_IOS = false` - at least the internal `SKIP_PODS` variable seems redundant, considering that bundler and ruby gems are only used together with cocoapods?

Separately, could also be nice to unify the naming of the two cli flags ... `--no-skip-pods`? `--no-build-ios`?

2024-09-18 23:42 UTC, legobeat commented
Looks great! Just one thought I had on simplifying the `setup.mjs` refactor somewhat.

2024-09-18 23:43 UTC, legobeat commented on .github/workflows/ci.yml
> +    runs-on: macos-14
Why `macos-14` and not `macos-latest`?

2024-09-19 07:01 UTC, legobeat commented on scripts/setup.mjs
> +}
How about this?
```suggestion
let BUILD_IOS = IS_OSX;
let IS_NODE = false;
const args = process.argv.slice(2) || [];
for (const arg of args) {
  switch (arg) {
    case '--build-ios':
      console.warn(`${arg} is deprecated and has been renamed to --install-pods`);
    case '--install-pods':
      BUILD_IOS = true;
      continue;
    case '--no-install-pods':
      SKIP_PODS = true;
      continue;
    case '--node':
      IS_NODE = true;
      continue;
    default:
      throw new Error(`Unrecognized CLI arg ${arg}`);
  }
}
```

2024-09-20 00:41 UTC, owencraston approved these changes, later dismissed

2024-09-20 18:11 UTC, Cal-L commented on scripts/setup.mjs
> +    case '--skip-pods':
Great point. Will remove skip pods and just consolidate iOS instead - https://github.com/MetaMask/metamask-mobile/pull/10880/commits/d2d77cf20d76d42f4d32b48c1a40d1365e0372d5

2024-09-20 18:11 UTC, Cal-L commented on scripts/setup.mjs
> +}
Just consolidated iOS instead - https://github.com/MetaMask/metamask-mobile/pull/10880/commits/d2d77cf20d76d42f4d32b48c1a40d1365e0372d5

2024-09-20 18:12 UTC, Cal-L commented on .github/workflows/ci.yml
> +    runs-on: macos-14
Updated to use macos-latest - https://github.com/MetaMask/metamask-mobile/pull/10880/commits/c5b1391d76c5ac9b63fdacc9332c718b943e7590

2024-09-20 18:14 UTC, Cal-L commented on scripts/setup.mjs
> +  prepareDependenciesTask,
Fixed to run ios and ppom afterwards

2024-09-23 22:58 UTC, legobeat approved these changes, later dismissed

2024-09-23 23:01 UTC, legobeat commented on scripts/setup.mjs
> +    case '--skip-ios':
```suggestion
    case '--no-build-ios':
```
Minor but I still think it could be nice with a generic `no-` prefix, which could be reused for any other future negatable options for a coherent CLI API :)

2024-09-24 00:48 UTC, legobeat approved these changes

2024-09-24 01:14 UTC, merged