test: Fix Swap e2e test failure
MetaMask/metamask-mobile pull request #10897
Opened 2024-08-29 14:31 UTC by davibroc

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-08-29 15:21 UTC, cortisiko requested changes, later dismissed

2024-08-29 15:21 UTC, cortisiko commented on e2e/pages/swaps/SwapView.js
> +    await TestHelpers.checkIfElementWithTextIsVisible('New quotes in 0:10');
Use the assertion class to perform this assertion. `checkIfTextIsDisplayed` seems like it might suffice

2024-08-30 08:20 UTC, davibroc commented on e2e/pages/swaps/SwapView.js
> +    await TestHelpers.checkIfElementWithTextIsVisible('New quotes in 0:10');
I have tried to use Assertion but it doesn't work in this case. The purpose of this line of code is not to assert but rather wait for the counter to go from 0:30 to 0:10 and then perform the swipe. Reason for that are explained in the PR description

2024-08-30 08:37 UTC, Andepande approved these changes
LGTM

2024-08-30 08:44 UTC, merged