chore: Add a new transaction event
MetaMask/metamask-mobile pull request #10950
Opened 2024-08-30 14:17 UTC by dan437

## **Description**
Add a minimal version of the "Transaction Finalized" event, triggered at the same time as in the extension. This PR also fixes metrics passed from the STX controller.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Submit a Send transaction on a Sepolia testnet
2. You will see the `Transaction Finalized` event in console if you are running the mobile app locally and it will have an additional payload if it's a smart transaction

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-03 13:18 UTC, dbrans commented on app/util/smart-transactions/index.ts
> +export const getSmartTransactionMetricsProperties = async (
Nice work on this function! I think you could streamline it by 

1. extracting the polling:

   ```typescript
    
    const POLL_INTERVAL = 100; // ms
    const MAX_POLL_TIME = 2000; // ms

   const pollForSmartTransaction = async (getSmartTransaction) => {
     const startTime = Date.now();

      while (Date.now() - startTime < MAX_POLL_TIME) {
        const smartTransaction = getSmartTransaction();
        if (smartTransaction?.statusMetadata) {
          return smartTransaction;
        }
        await new Promise(resolve => setTimeout(resolve, POLL_INTERVAL));
      }
    
      return null
   };

   ```

2. having a closure like `getSmartTransaction` that you pass to the polling function.

  ```typescript
    export const getSmartTransactionMetricsProperties = async (
      smartTransactionsController,
      transactionMeta,
      waitForSmartTransaction,
    ): Promise<Record<string, boolean>> => {
      if (!transactionMeta?.hash) {
        return {};
      }
    
      const getSmartTransaction = () =>
        smartTransactionsController.getSmartTransactionByMinedTxHash(transactionMeta.hash);
    
      let smartTransaction = getSmartTransaction();
    
      if (waitForSmartTransaction && !smartTransaction?.statusMetadata) {
        smartTransaction = await pollForSmartTransaction(getSmartTransaction);
      }
      if (!smartTransaction) {
        return {};
      }

      const { duplicated, timedOut, proxied } = statusMetadata;
      //...
  };

  ```
  
  These changes should make the code more modular and easier to maintain. Happy to discuss further!

2024-09-18 12:23 UTC, dan437 commented on app/core/Engine.ts
> +  _handleTransactionFailed = async (transactionEventPayload: any) => {
Good catch, it should be `TransactionMeta`, as it's done for other 2 handlers.

2024-09-18 12:59 UTC, dan437 commented on app/util/smart-transactions/index.ts
> +export const getSmartTransactionMetricsProperties = async (
Thanks for the suggestion. I wasn't too happy with the polling approach, so I've changed it to listen to a new event from the STX controller instead, which I believe is cleaner. I need to update the STX controller with it and publish it on npm and then I can use it here.

2024-10-02 14:26 UTC, dbrans commented on app/util/smart-transactions/index.ts
> +  if (waitForSmartTransaction && !smartTransaction?.statusMetadata && controllerMessenger) {
can we clarify what this boolean expression is checking? Maybe we could break it down with some temporary variables to make it clearer?

2024-10-02 14:26 UTC, dbrans commented on app/core/Engine.ts
> +  _handleTransactionFinalizedEvent = async ( transactionEventPayload: TransactionEventPayload, properties: object ) => {
Could we add comments and tests to this function?

2024-10-02 14:26 UTC, dbrans commented on app/util/smart-transactions/index.ts
> +const waitForSmartTransactionConfirmationDone = (
Do we need a test for this function?

2024-10-02 14:26 UTC, dbrans commented on app/util/smart-transactions/index.ts
> +    }, 10000);
Do you think it makes sense to make this configurable? If not, maybe we could add a const at the top with a quick comment explaining the timeout and why we chose it. What do you think?

2024-10-02 14:50 UTC, dan437 commented on app/util/smart-transactions/index.ts
> +    }, 10000);
I don't think we need to configure this externally, since 10s is a very long time already and if it's not resolved within this timeframe, we don't want to wait anymore. Constant is fine.

2024-10-02 15:18 UTC, dan437 commented on app/util/smart-transactions/index.ts
> +const waitForSmartTransactionConfirmationDone = (
Not exactly for this one, but for the exported `getSmartTransactionMetricsProperties` function, which will indirectly test this unexported function.

2024-10-15 12:29 UTC, leotm commented
> Add a minimal version of the "Transaction Finalized" event, triggered at the same time as in the extension.

could you link where in our metamask-extension codebase? for reference

2024-10-15 12:42 UTC, leotm commented on package.json
> +    "@metamask/smart-transactions-controller": "^13.1.0",
nb: [13.2.0](https://github.com/MetaMask/smart-transactions-controller/releases/tag/v13.2.0) released last week, but can be bumped in future since 13.1.0 includes the change we need (`smartTransactionConfirmationDone`)

2024-10-15 12:44 UTC, leotm submitted a review, later dismissed

2024-10-21 10:56 UTC, tommasini commented on app/core/Engine.ts
> +    this.transactionController.clearUnapprovedTransactions();
This PR is also clearing unapproved transactions from the state, since it was not on the description, I'm making this comment to make sure isn't something we left here by mistake and we really want to do it

2024-10-21 10:57 UTC, tommasini submitted a review, later dismissed
The code LGTM! Can we have some recordings of the event being triggered on the PR for history and testing purposes?

2024-10-21 11:20 UTC, NicolasMassart requested changes
The trackEvent signature used here and manually building the event object are deprecated.
Use MetricsEventBuilder and non-deprecated trackEvent instead

2024-10-21 11:20 UTC, NicolasMassart commented on app/core/Engine.ts
>          },
Use of this trackEvent signature and manually building the event object is deprecated.
Use MetricsEventBuilder and non-deprecated trackEvent instead

2024-10-21 11:20 UTC, NicolasMassart commented on app/core/Engine.ts
> +      );
Use of this trackEvent signature and manually building the event object is deprecated.
Use MetricsEventBuilder and non-deprecated trackEvent instead

2024-10-21 11:20 UTC, NicolasMassart commented on app/core/Engine.ts
> +    );
Use of this trackEvent signature and manually building the event object is deprecated.
Use MetricsEventBuilder and non-deprecated trackEvent instead

2024-10-28 11:00 UTC, NicolasMassart reviewed
Nice work!
Some suggestions about [guidelines](https://github.com/MetaMask/contributor-docs/blob/main/docs/testing/unit-testing.md#use-it-to-specify-the-desired-behavior-for-the-code-under-test) compliance.

2024-10-28 11:00 UTC, NicolasMassart commented on app/core/Engine.test.ts
> +    it('should track event with basic properties when smart transactions are disabled', async () => {
```suggestion
    it('tracks event with basic properties when smart transactions are disabled', async () => {
```

2024-10-28 11:00 UTC, NicolasMassart commented on app/core/Engine.test.ts
> +    it('should not process smart transaction metrics if transactionMeta is missing', async () => {
```suggestion
    it('does not process smart transaction metrics if transactionMeta is missing', async () => {
```

2024-10-28 11:00 UTC, NicolasMassart commented on app/core/Engine.test.ts
> +    it('should handle dropped transactions', async () => {
```suggestion
    it('tracks dropped transactions', async () => {
```

2024-10-28 11:00 UTC, NicolasMassart commented on app/core/Engine.test.ts
> +    it('should handle confirmed transactions', async () => {
```suggestion
    it('tracks confirmed transactions', async () => {
```

2024-10-28 11:00 UTC, NicolasMassart commented on app/core/Engine.test.ts
> +    it('should handle failed transactions', async () => {
```suggestion
    it('tracks failed transactions', async () => {
```

2024-10-28 11:00 UTC, NicolasMassart commented on app/core/Engine.test.ts
> +    it('should subscribe to transaction events', () => {
```suggestion
    it('subscribes to transaction events', () => {
```

2024-10-28 12:31 UTC, NicolasMassart approved these changes
Looks good to me.

2024-10-28 12:47 UTC, merged