[Draft] test: initial ramps tests
MetaMask/metamask-mobile pull request #11086
Opened 2024-09-06 15:57 UTC by bkirb

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-17 14:21 UTC, davibroc approved these changes, later dismissed
LGTM

2024-09-17 15:58 UTC, cortisiko requested changes

2024-09-17 15:58 UTC, cortisiko commented on e2e/specs/ramps/onramp.spec.js
> +describe(SmokeRamps('Buy Crypto'), () => {
Can you tag SmokeAssets instead? This is mainly because there is only one test, and creating a separate CI workflow for just one test does not make sense. Once that is done, can you trigger the smoke pipeline and ensure that the test runs on CI and passes.

2024-09-26 10:30 UTC, chrisleewilcox commented on e2e/specs/ramps/onramp.spec.js
> +  it('should select Region and Payment Method to see the Build Quote screen', async () => {
May make sense to break this down to show more scenarios tested like....

- should select Region
- should select Payment Method
- should show Build Quote screen

2024-10-01 02:16 UTC, bkirb commented on e2e/specs/ramps/onramp.spec.js
> +describe(SmokeRamps('Buy Crypto'), () => {
Done ✅

2024-10-02 15:00 UTC, bkirb commented on e2e/specs/ramps/onramp.spec.js
> +  it('should select Region and Payment Method to see the Build Quote screen', async () => {
Discussed with Javier and we decided to stick to longer user flows instead of granular tests

2024-10-02 17:34 UTC, cortisiko reviewed
quick feedback

2024-10-02 17:34 UTC, cortisiko commented on e2e/pages/Ramps/BuildQuoteView.js
> +    await Assertions.checkIfVisible(this.amountToBuyLabel);
We tend to put the assertions within the testfile itself not the page objects

2024-10-02 17:34 UTC, cortisiko commented on e2e/pages/Ramps/BuildQuoteView.js
> +    await Assertions.checkIfVisible(this.getQuotesButton);
same as above!

2024-10-03 02:10 UTC, bkirb commented on e2e/pages/Ramps/BuildQuoteView.js
> +    await Assertions.checkIfVisible(this.amountToBuyLabel);
Fixed ✅

2024-10-03 02:10 UTC, bkirb commented on e2e/pages/Ramps/BuildQuoteView.js
> +    await Assertions.checkIfVisible(this.getQuotesButton);
Fixed ✅

2024-10-03 02:11 UTC, bkirb commented
@cortisiko I moved the assertions to the test file, and the test still passes ✅

```
 PASS  e2e/specs/ramps/onramp.spec.js (137.591 s)
  smokeAssets Buy Crypto
    ✓ should select Region and Payment Method to see the Build Quote screen (15111 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
```

2024-10-03 18:55 UTC, cortisiko approved these changes
PR is ✅

2024-10-04 05:26 UTC, merged