fix: update token details monetization button
MetaMask/metamask-mobile pull request #11112
Opened 2024-09-09 14:52 UTC by salimtb

## **Description**

This PR aims to align the monetization buttons in the mobile application with those in the extension. The following buttons have been added or updated: Send, Receive, Bridge, Swap, and Buy. This effort is part of a broader initiative to provide a consistent user experience across platforms.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to token details page
2. Check the buttons send, receive, bridge ...

## **Screenshots/Recordings**

### **Before**

![Screenshot 2024-09-09 at 16 49 39](https://github.com/user-attachments/assets/466f2ec8-dd58-4f34-8b14-cfb743b262f0)

### **After**
![Screenshot 2024-09-09 at 16 50 11](https://github.com/user-attachments/assets/b38a1e46-d46e-4072-8895-716846e9d2d3)

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-10 12:33 UTC, sahar-fehri commented
I saw that in the designs it shows "your balance" after the buttons; which is not the case in screenshot in the description, was this intentional?

<img width="309" alt="Screenshot 2024-09-10 at 14 32 35" src="https://github.com/user-attachments/assets/5c0822f6-8c6a-4f1a-818c-b5eabf2384f2">

2024-09-12 18:03 UTC, gambinish commented
@salimtb https://github.com/MetaMask/metamask-mobile/pull/11049 just got merged, so you should be able to get those balance updates here.

Do you want me to address the conflicts here? More than happy to.

2024-09-12 19:52 UTC, salimtb commented
> @salimtb #11049 just got merged, so you should be able to get those `Your balance` updates here.
> 
> Do you want me to address the conflicts here? More than happy to.

@gambinish feel free to resolve conflicts on my PR , planing to do it tmrw morning , but if you're free the rest of the day you can do it

2024-09-13 02:11 UTC, gambinish commented on app/components/UI/AssetOverview/AssetOverview.tsx
>            </View>
How would you feel about this being it's own component? Maybe like `WalletActions.tsx` or something along those lines?

2024-09-13 02:17 UTC, gambinish requested changes
I went ahead and merged `main`, and addressed our conflicts like we talked about. I also went ahead and made a couple of css tweaks, feel free to revert if you don't feel that they are necessary.

I felt like the Icons looked a bit better as `AvatarSize.Lg` (a bit bigger)...do you agree? I also opted to `justify-content: space-evenly` for things with 4 `WalletActions`. Though this may need to get design approval from @amandaye0h 

Also noticing that the Icons on Dark Mode are still white, when the designs show that they should match the background (be black). Is there an easy way to fix this through the design system?

Anyway, here is a screenshot of where I'm leaving things off:

<img width="460" alt="Screenshot 2024-09-12 at 7 15 57 PM" src="https://github.com/user-attachments/assets/4730b585-13a2-4fd0-af4b-1ac595c95463">

2024-09-13 08:09 UTC, salimtb commented on app/components/UI/AssetOverview/AssetOverview.tsx
>            </View>
that's a good idea , i'll extract this as a new component

2024-09-13 13:33 UTC, amandaye0h commented
Thanks for sharing this — these buttons look so much better :face_holding_back_tears::face_holding_back_tears::face_holding_back_tears:. The look like how they were originally meant to. Am aligned with using `space-evenly`.

Re:  `icons on Dark Mode are still white`:

What you have in the codebase is right. We most recently [updated](https://consensys.slack.com/archives/C0354T27M5M/p1725572568339679) the button icons back to white. My bad for not explicitly communicating in the specs 🥲

2024-09-13 15:44 UTC, gambinish commented on index.js
> +// );
Are these changes intended?

2024-09-13 16:20 UTC, gambinish commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +    navigation.navigate(...createBuyNavigationDetails());
```suggestion
    const [route, params] = createBuyNavigationDetails();
    navigation.navigate(route, params || {});
```

Will this allow us to avoid `@ts-ignore` here?

2024-09-13 16:26 UTC, gambinish commented on app/components/UI/AssetOverview/AssetOverview.test.tsx
> +      } as any,
```suggestion
      } as const,
```
I think this will work too

2024-09-13 16:40 UTC, gambinish commented on app/components/Views/AssetDetails/AssetDetailsActions/AssetDetailsActions.styles.ts
> +      justifyContent: 'center',
```suggestion
      justifyContent: 'space-between',
```
I'm confirming with @amandaye0h but I think we may want to change this as well

2024-09-13 16:43 UTC, gambinish requested changes
This looks great. Thanks for breaking out `AssetDetailsActions` into it's own component ✨ 

I left a few TS suggestions, and one final css thing to double check but once we do that I'm ready to ✅

2024-09-13 17:28 UTC, salimtb commented on app/components/UI/AssetOverview/AssetOverview.test.tsx
> +      } as any,
done

2024-09-13 17:29 UTC, amandaye0h commented on app/components/Views/AssetDetails/AssetDetailsActions/AssetDetailsActions.styles.ts
> +      justifyContent: 'center',
`space-evenly` looks the best!

2024-09-13 18:28 UTC, gambinish approved these changes, later dismissed

2024-09-16 09:17 UTC, tommasini approved these changes
LGTM!

2024-09-16 09:18 UTC, merged