chore(deps): Bump `@metamask/approval-controller` from `^7.0.1` to `^7.0.3`
MetaMask/metamask-mobile pull request #11116
Opened 2024-09-09 16:49 UTC by MajorLift

## **Description**

```md
### Changed

- Bump `@metamask/approval-controller` from `^7.0.1` to `^7.0.3`
```
## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-10 14:05 UTC, mikesposito approved these changes, later dismissed

2024-09-10 14:26 UTC, cryptodev-2s approved these changes

2024-09-10 14:48 UTC, cryptodev-2s requested changes
can we remove also `patches/@metamask+approval-controller+7.0.2.patch` or at least we maintain the patch

2024-10-23 18:28 UTC, mcmire reviewed
Looks good overall but there are some conflicts now it seems.

2024-10-23 19:07 UTC, cryptodev-2s commented
closed as completed in https://github.com/MetaMask/metamask-mobile/pull/11911

2024-10-23 19:07 UTC, closed without merging