feat: Add performance tracing infrastructure
MetaMask/metamask-mobile pull request #11132
Opened 2024-09-10 10:47 UTC by OGPoyraz

## **Description**

#### **Additions**
- Add initial tracing and performance metrics infrastructure.
Add the `trace`, `endTrace` method, to be used anywhere in the mobile code to generate a Sentry traces. Implementation is almost same as we have in the extension.
- Add developer options to settings (similar settings [added in extension](https://github.com/MetaMask/metamask-extension/blob/e858167bb1fee33d4d0be1ab2f8e1ce2b11c7945/ui/pages/settings/developer-options-tab/developer-options-tab.tsx#L50) ) 
This adds an easily accessible development actions which devs wants to test locally. Specifically this PR adds generating nested traces in Sentry. 
- New environment variables:
`MM_ENABLE_SETTINGS_PAGE_DEV_OPTIONS` : Needs to be set to `true` in order to show `Developer Options` in the settings page
`MM_SENTRY_DSN_DEV` : This is explicitly set for `test-metamask` project and the expected value is in the `.js.env.example`

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to settings page tab `Developer Options`
2. Tab `Generate Trace Test`
3. Open `https://metamask.sentry.io/traces/?project=273496&statsPeriod=15m`, in this link you will be able to see traces that have been send to `test-metamask` in last 15 minutes
4. See `Developer Test` trace is triggered

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [X] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [X] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-10 13:29 UTC, matthewwalsh0 submitted a review, later dismissed

2024-09-10 13:29 UTC, matthewwalsh0 commented on app/components/Views/Settings/DeveloperOptions/SentryTest.tsx
This is great to have in mobile and useful for testing the trace support, but would it break up the code review to have it in its own PR?

2024-09-10 13:29 UTC, matthewwalsh0 commented on app/components/Nav/Main/MainNavigator.js
> +    {process.env.MM_ENABLE_SETTINGS_PAGE_DEV_OPTIONS === 'true' && (
Is there any kind of config abstraction in mobile, so a single place to reference and parse any environment variables?

2024-09-10 13:29 UTC, matthewwalsh0 commented on app/util/sentry/trace.ts
I appreciate the `sentry` directory already existed, but part of the benefit of these utility functions was to abstract and encapsulate any usage of Sentry for these to minimise coupling through the codebase.

2024-09-10 13:29 UTC, matthewwalsh0 commented on app/util/sentry/trace.ts
> +const tracesByKey: Map<string, PendingTrace> = new Map();
This is perhaps less of a problem in the extension since the browser is more likely to be closed, especially in the case of the popup.

But since mobile may have a longer typical lifecycle, is it worth a `setTimeout` when adding to this to delete them after 5 minutes for example to minimise memory usage?

2024-09-10 13:29 UTC, matthewwalsh0 commented on app/util/sentry/trace.ts
> +interface PendingTrace {
Is `interface` encouraged in mobile rather than `type`?

2024-09-10 13:29 UTC, matthewwalsh0 commented on app/util/sentry/trace.ts
> +    Logger.log('Starting trace', name, request);
I'm a big fan of `debug` and `createModuleLogger` for the colour coding and prefix support.

Something worth aligning across both clients and core I think.

2024-09-10 13:29 UTC, matthewwalsh0 commented on app/util/sentry/utils.js
> +      tracesSampleRate: __DEV__ ? 1.0 : 0.04,
Worth nothing that mobile are uses `0.04` while extension uses `0.01`.

I assume a side effect of less traffic generated from mobile?

2024-09-10 13:29 UTC, matthewwalsh0 commented on app/components/Views/Settings/DeveloperOptions/SentryTest.tsx
> +      new Promise((resolve) => setTimeout(resolve, ms));
This must be the most duplicated logic in every repository.

Is this a util already or should we bite the bullet and make one?

2024-09-11 05:58 UTC, Cal-L reviewed
Left some comments

2024-09-11 05:58 UTC, Cal-L commented on .js.env.example
> +# export MM_SENTRY_DSN_DEV=https://f59f3dd640d2429d9d0e2445a87ea8e1@sentry.io/273496
Let's replace the value with an empty string in this file

2024-09-11 05:58 UTC, Cal-L commented on app/components/Nav/Main/MainNavigator.js
> +        name="DeveloperOptions"
Define name in route file

2024-09-11 05:58 UTC, Cal-L commented on app/components/Views/Settings/DeveloperOptions/DeveloperOptions.types.ts
> +export interface Props {
Instead of defining the props navigation and route here, you can remove the props and use `useNavigation` hook in the component instead

2024-09-11 05:58 UTC, Cal-L commented on app/components/Views/Settings/DeveloperOptions/SentryTest.tsx
> +  const styles = createStyles(colors);
replace with `useStyles` instead, which already provides theme under the hood

2024-09-11 05:58 UTC, Cal-L commented on app/components/Views/Settings/DeveloperOptions/SentryTest.tsx
> +  const styles = createStyles(colors);
Replace with `useStyles` instead

2024-09-11 05:58 UTC, Cal-L commented on app/components/Views/Settings/DeveloperOptions/SentryTest.tsx
> +        Sentry
```suggestion
        {'Sentry'}
```

This gives better formatting in IDE

2024-09-11 05:58 UTC, Cal-L commented on app/components/Views/Settings/DeveloperOptions/SentryTest.tsx
> +      {<GenerateTrace />}
```suggestion
      <GenerateTrace />
```

2024-09-11 05:58 UTC, Cal-L commented on app/components/Views/Settings/DeveloperOptions/index.test.tsx
> +      <Provider store={store}>
Use `renderScreen` instead, which already wraps with Providers

2024-09-11 05:58 UTC, Cal-L commented on app/components/Views/Settings/DeveloperOptions/index.tsx
> +  const styles = createStyles(colors);
Use `useStyles` instead

2024-09-11 05:58 UTC, Cal-L commented on app/util/sentry/utils.js
> +    const dsn = __DEV__ ? MM_SENTRY_DSN_DEV : MM_SENTRY_DSN;
Cleaner to handle this in the build.sh script instead

2024-09-11 06:34 UTC, OGPoyraz commented on app/components/Nav/Main/MainNavigator.js
> +    {process.env.MM_ENABLE_SETTINGS_PAGE_DEV_OPTIONS === 'true' && (
Unfortunately I couldn't find a place to add a utility function for this. If you search `process.env.` these branches are everywhere, we can start one but it wont get notice by other devs. I think it should be handled at once to centralise it.

2024-09-11 06:37 UTC, OGPoyraz commented on app/components/Views/Settings/DeveloperOptions/SentryTest.tsx
I don't think it's adding too much complexity to this PR. Also `SentryTest` is the first content of `DeveloperOptions` shall we keep this one for now?

2024-09-11 06:41 UTC, OGPoyraz commented on app/util/sentry/trace.ts
Moved up in `app/util` directory and leave the name as is.

2024-09-11 07:21 UTC, OGPoyraz commented on app/util/sentry/trace.ts
> +const tracesByKey: Map<string, PendingTrace> = new Map();
Added in https://github.com/MetaMask/metamask-mobile/pull/11132/commits/f4ce466260d239fccb02a9ea319a55739b55cf8b

2024-09-11 07:28 UTC, OGPoyraz commented on app/util/sentry/trace.ts
> +interface PendingTrace {
Fixed in https://github.com/MetaMask/metamask-mobile/pull/11132/commits/e0026992f4db086977fb61bb3e9cb7f26f0d23d7

2024-09-11 07:36 UTC, OGPoyraz commented on app/util/sentry/trace.ts
> +    Logger.log('Starting trace', name, request);
Done in https://github.com/MetaMask/metamask-mobile/pull/11132/commits/308f2e6497196e5a99b93c148b93c8aa3503294f

2024-09-11 07:40 UTC, OGPoyraz commented on app/util/sentry/utils.js
> +      tracesSampleRate: __DEV__ ? 1.0 : 0.04,
It's probably that but not sure why is this 1/4 ratio.

2024-09-11 07:44 UTC, OGPoyraz commented on app/components/Views/Settings/DeveloperOptions/SentryTest.tsx
> +      new Promise((resolve) => setTimeout(resolve, ms));
Relocated this into very empty `app/util/testUtils` 😄 https://github.com/MetaMask/metamask-mobile/pull/11132/commits/9ed584db2ec6f77b61baa9b6dd4f375a24eeb5a4

2024-09-11 07:45 UTC, OGPoyraz commented on .js.env.example
> +# export MM_SENTRY_DSN_DEV=https://f59f3dd640d2429d9d0e2445a87ea8e1@sentry.io/273496
Is there any downside/reason leaving as is? Because we already show this value in extension example environments as well

2024-09-11 08:14 UTC, OGPoyraz commented on app/components/Views/Settings/DeveloperOptions/index.tsx
> +  const styles = createStyles(colors);
Done

2024-09-11 08:14 UTC, OGPoyraz commented on app/components/Views/Settings/DeveloperOptions/index.test.tsx
> +      <Provider store={store}>
Done

2024-09-11 08:14 UTC, OGPoyraz commented on app/components/Views/Settings/DeveloperOptions/SentryTest.tsx
> +      {<GenerateTrace />}
Done

2024-09-11 08:14 UTC, OGPoyraz commented on app/components/Views/Settings/DeveloperOptions/SentryTest.tsx
> +  const styles = createStyles(colors);
Done

2024-09-11 08:14 UTC, OGPoyraz commented on app/components/Views/Settings/DeveloperOptions/SentryTest.tsx
> +  const styles = createStyles(colors);
Done

2024-09-11 08:14 UTC, OGPoyraz commented on app/components/Views/Settings/DeveloperOptions/DeveloperOptions.types.ts
> +export interface Props {
Done

2024-09-11 08:14 UTC, OGPoyraz commented on app/components/Nav/Main/MainNavigator.js
> +        name="DeveloperOptions"
Done

2024-09-11 08:16 UTC, OGPoyraz commented on app/util/sentry/utils.js
> +    const dsn = __DEV__ ? MM_SENTRY_DSN_DEV : MM_SENTRY_DSN;
Do you mean setting single `SENTRY_DSN `? Please also note that `MM_SENTRY_DSN_DEV` is needed in this context because I believe `isTest` is not working as intended.

2024-09-11 15:02 UTC, Cal-L commented on .js.env.example
> +# export MM_SENTRY_DSN_DEV=https://f59f3dd640d2429d9d0e2445a87ea8e1@sentry.io/273496
Since this is a mm dev is environment, we wouldn't want non mm contributors reporting to the same DSN. They should be using their own

2024-09-11 15:33 UTC, Cal-L commented on app/util/sentry/utils.js
> +    const dsn = __DEV__ ? MM_SENTRY_DSN_DEV : MM_SENTRY_DSN;
Yep, we can conditionally map the sentry dsn to the dev one in debug mode from the build.sh file. You might not need to couple it with isTest since that's used for e2e.

2024-09-12 06:46 UTC, OGPoyraz commented on .js.env.example
> +# export MM_SENTRY_DSN_DEV=https://f59f3dd640d2429d9d0e2445a87ea8e1@sentry.io/273496
Regardless of this PR it's already in public in extension, that's what I mean. I don't mind removing it for sure.

2024-09-12 06:46 UTC, OGPoyraz commented on .js.env.example
> +# export MM_SENTRY_DSN_DEV=https://f59f3dd640d2429d9d0e2445a87ea8e1@sentry.io/273496
https://github.com/MetaMask/metamask-mobile/pull/11132/commits/3481ff35b23881fc5d23ea13ac1c5091082e411b

2024-09-12 07:04 UTC, OGPoyraz commented on app/util/sentry/utils.js
> +    const dsn = __DEV__ ? MM_SENTRY_DSN_DEV : MM_SENTRY_DSN;
Well that's the issue, `isTest` is returning `true` in dev environments unless we don't set `METAMASK_ENVIRONMENT=production`. 

I'm cautious about conditionally modifying `process.env` values, especially outside of test environments. This approach can lead to unpredictable behavior and make it harder to debug issues. Unless there's a specific requirement or a well-established convention, I think it's best to avoid dynamically changing environment variables. In our case, I believe it's more maintainable and predictable to keep the Sentry DSN configuration separate from the build process. If we need to switch between dev and prod DSNs, we can achieve this through other means, such as using separate configuration files or environment-specific settings.

2024-09-12 15:15 UTC, Cal-L commented on app/util/sentry/utils.js
> +    const dsn = __DEV__ ? MM_SENTRY_DSN_DEV : MM_SENTRY_DSN;
I'm not sure about the issue with the `isTest` but let's keep it simple and just consider the debug environment for now. We can handle E2E conditions in another PR, preferably when the `isTest` is fixed. I see what you mean on how it could be harder to debug when the mechanism that handles setting the env vars is abstracted from the main code. Although the build.sh script may introduce complexities, the project was set up in a way to be reliant on it. At the same time, by using the intended script commands, the build.sh is also intended to produce predictable behavior. For example, one would expect that running `yarn start:ios:qa` would start a build using QA environment setup. There are definitely alternatives to setting up these environments such as creating multiple variants. However as it's set up today, the non-documented approach is to map the variables within each variant in `buildIos` in the build.sh script. For your changes, it would mean mapping the env vars in `buildIosSimulator` by adding a mapping function. You can reference `buildIosFlaskRelease` as a point of reference. The end result is: provided that you have the dev sentry DSN defined in your .js.env, running `yarn start:ios` should pick up the dev value.

2024-09-13 06:56 UTC, OGPoyraz commented on app/util/sentry/utils.js
> +    const dsn = __DEV__ ? MM_SENTRY_DSN_DEV : MM_SENTRY_DSN;
@Cal-L I appreciate your clarification. While I'm not entirely opposed to this approach, I do worry that the growing number of small differences between our mobile and extension repositories is making life harder for developers. I understand that these are two distinct clients with varying requirements, but I also believe that we should strive for common conventions wherever possible, in that case it's not. 

As you pointed out that this won't be the first example done in mobile, I'll implement the changes as you've suggested.

https://github.com/MetaMask/metamask-mobile/pull/11132/commits/3cc85dc17eb387fa4e77da1d60883fc5b99679f3

2024-09-13 20:43 UTC, Cal-L submitted a review, later dismissed
Nice, LGTM. Feel free to reach out for another approval once the conflicts are fixed.

2024-09-14 20:13 UTC, matthewwalsh0 requested changes

2024-09-14 20:13 UTC, matthewwalsh0 commented on app/util/trace.ts
> +export function cleanupTraces() {
Is this called anywhere yet or just available?

My assumption was we could handle this automatically by triggering an individual `setTimeout` for each one within `startTrace` and then store the timeout inside `PendingTrace` so we can call `clearTimeout` within `endTrace`?

2024-09-14 20:13 UTC, matthewwalsh0 commented on app/util/trace.ts
> +export const tracesByKey: Map<string, PendingTrace> = new Map();
It's difficult, but I'm a big fan of avoiding exporting variables purely for the sake of tests.

Ideally, any unit tests would just verify the side effects such as `end` being called on the `span` or a `clearTimeout` being called?

2024-09-16 09:36 UTC, OGPoyraz commented on app/util/trace.ts
> +export function cleanupTraces() {
Changed the approach here: https://github.com/MetaMask/metamask-mobile/pull/11132/commits/69aa635b6986eb32c026e7e72d27680095a82b4a

2024-09-16 09:37 UTC, OGPoyraz commented on app/util/trace.ts
> +export const tracesByKey: Map<string, PendingTrace> = new Map();
That make sense, I've changed the tests to not use `tracesByKey`

2024-09-18 06:57 UTC, matthewwalsh0 approved these changes

2024-09-18 09:21 UTC, vinistevam approved these changes

2024-09-18 18:02 UTC, leotm approved these changes
lgtm

<img width="1856" alt="Screenshot 2024-09-18 at 6 52 31 PM" src="https://github.com/user-attachments/assets/4a8809d5-f822-49a0-b667-95f07bc88645">

perhaps like https://github.com/MetaMask/metamask-extension/blob/develop/development/README.md#sentry

we should add a Sentry section here https://github.com/MetaMask/metamask-mobile/blob/main/docs/readme/testing.md

with heading e.g. `Generating a trace test` that mentions our new env vars, with the odd screenshot or two if it helps

2024-09-18 18:44 UTC, merged