fix: Reuse mmkv instance once created
MetaMask/metamask-mobile pull request #11139
Opened 2024-09-10 14:13 UTC by tommasini

## **Description**
We should reuse MMKV instance instead of creating a new one each time we want to access storage.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-10 18:43 UTC, tommasini commented on app/store/storage-wrapper.js
> +export default StorageWrapper.instance || new StorageWrapper();
Thanks Nico for the meeting and helping get more perfect towards a Singleton pattern design!

2024-10-09 09:52 UTC, NicolasMassart requested changes

2024-10-09 09:52 UTC, NicolasMassart commented on app/store/storage-wrapper.test.ts
> +jest.unmock('./storage-wrapper');
S: you could add a small comment here to explain why you unmock.
```suggestion
// Unmocking storage-wrapper as it's mocked in testSetup directly
// to allow easy testing of other parts of the app
// but here we want to actually test storage-wrapper
jest.unmock('./storage-wrapper');
```

2024-10-09 09:52 UTC, NicolasMassart commented on app/store/storage-wrapper.test.ts
> +    expect(result).toBe('test-value');
C: not sure this one actually tests anything except mockResolvedValue...

2024-10-09 09:52 UTC, NicolasMassart commented on app/store/storage-wrapper.test.ts
> +  it('throw an error when setItem do not receives a string', async () => {
```suggestion
  it('throws when setItem value param is not a string', async () => {
```

2024-10-09 09:52 UTC, NicolasMassart commented on app/store/storage-wrapper.test.ts
> +  it('remove value from the store', async () => {
```suggestion
  it('removes value from the store', async () => {
```

2024-10-09 09:52 UTC, NicolasMassart commented on app/store/storage-wrapper.test.ts
> +    expect(resultBeforeRemove).toBe('test-value');
S: Add some empty line to make test steps separated and more readable
```suggestion
    expect(resultBeforeRemove).toBe('test-value');

```

2024-10-09 09:52 UTC, NicolasMassart commented on app/store/storage-wrapper.test.ts
> +    expect(removeItemSpy).toHaveBeenCalledWith('test-key');
S: Add some empty line to make test steps separated and more readable
```suggestion
    expect(removeItemSpy).toHaveBeenCalledWith('test-key');

```

2024-10-09 09:52 UTC, NicolasMassart commented on app/store/storage-wrapper.test.ts
> +  it('remove all values from the store', async () => {
```suggestion
  it('removes all values from the store', async () => {
```

2024-10-09 09:52 UTC, NicolasMassart commented on app/store/storage-wrapper.test.ts
> +  it('StorageWrapper instance is defined', () => {
S: The suite already is called "StorageWrapper", no need to repeat.
```suggestion
  it('singleton instance is defined', () => {
```
Then your test will appear as "StorageWrapper singleton instance is defined"

2024-10-09 09:52 UTC, NicolasMassart commented on app/store/storage-wrapper.ts
> +  async getItem(key: string) {
S: add some TSDoc to make IDE display it when we code.
Don't hesitate to add an `@example` section

2024-10-09 09:52 UTC, NicolasMassart commented on app/store/storage-wrapper.ts
> +  async setItem(key: string, value: string) {
S: add some TSDoc to make IDE display it when we code.
Don't hesitate to add an `@example` section

2024-10-09 09:52 UTC, NicolasMassart commented on app/store/storage-wrapper.ts
> +  async removeItem(key: string) {
S: add some TSDoc to make IDE display it when we code.
Don't hesitate to add an `@example` section

2024-10-09 09:52 UTC, NicolasMassart commented on app/store/storage-wrapper.ts
>    async clearAll() {
S: add some TSDoc to make IDE display it when we code.
Don't hesitate to add an `@example` section

2024-10-09 09:52 UTC, NicolasMassart commented on app/store/storage-wrapper.ts
> +  static getInstance() {
S: add some TSDoc to make IDE display it when we code.
Don't hesitate to add an `@example` section

2024-10-09 09:55 UTC, tommasini commented on app/store/storage-wrapper.test.ts
> +jest.unmock('./storage-wrapper');
Thanks Nico! Yeah sounds great to explain why that was needed!

2024-10-09 09:55 UTC, tommasini commented on app/store/storage-wrapper.test.ts
> +    expect(result).toBe('test-value');
Yeah, I will remove the mock resolved value, is not needed indeed!

2024-10-09 12:58 UTC, NicolasMassart approved these changes

2024-10-09 14:46 UTC, merged