First mocking test final branch
MetaMask/metamask-mobile pull request #11144
Opened 2024-09-10 23:04 UTC by Andepande

Merged all mocking research into this branch

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-13 15:39 UTC, cortisiko requested changes
Good work on this @Andepande and @SamuelSalas. I left comments

2024-09-13 15:39 UTC, cortisiko commented on e2e/pages/AccountListView.js
> +    await Assertions.checkIfNotVisible(this.title);
is this needed? Assertions should live in the test file not the page object

2024-09-13 15:39 UTC, cortisiko commented on e2e/specs/wallet/suggestedGasApi.mock.spec.js
> +  afterAll(async () => {
it is good practice to put the hooks together (before hook followed by after all hook

2024-09-13 15:39 UTC, cortisiko commented on e2e/specs/wallet/suggestedGasApi.mock.spec.js
> +      mockUrl: 'https://gas.api.cx.metamask.io/networks/1/suggestedGasFees',
perhaps have some data structure to store endpoints and then access the data in the test.

2024-09-13 15:39 UTC, cortisiko commented on e2e/pages/Send/TransactionConfirmView.js
> +    if (index === 0) {
Mind explaining the conditional?

2024-09-13 17:47 UTC, SamuelSalas commented on e2e/pages/Send/TransactionConfirmView.js
> +    if (index === 0) {
This is because some issues we're having some issues with Detox on the transaction screen with the existing test and this new mock test. So i added this conditional so it work for both tests.

2024-09-13 17:49 UTC, SamuelSalas commented on e2e/pages/AccountListView.js
> +    await Assertions.checkIfNotVisible(this.title);
Right now is no longer needed because we added a conditional to check if the platform is ios or android. We're having some issues with Android trying to tap the Actions button before the Accounts modal was closed.

2024-09-17 13:30 UTC, NicolasMassart reviewed
I like this mock!
Added some suggestions and questions.

2024-09-17 13:30 UTC, NicolasMassart commented on shim.js
> +      Platform.OS === 'ios' ? 'localhost' : '10.0.2.2' // l
Suggestions:
- the `eslint-disable-next-line no-undef` to prevent global `Platform` to raise error may be replaced by a file level `/* global Platform */`
- remove or fix comment `// l`

2024-09-17 13:30 UTC, NicolasMassart commented on shim.js
> +      // small healthcheck
Not useful comment. Small gives no real information and the path `/health-check` already says what it is.
```suggestion
```

2024-09-17 13:30 UTC, NicolasMassart commented on e2e/specs/wallet/suggestedGasApi.mock.spec.js
> +        await TestHelpers.delay(20000);
Why 20s pause?

2024-09-17 13:30 UTC, NicolasMassart commented on e2e/mockserver/mockserver.js
> +  port = 8000,
S: export a `const defaultPort=8000` to use here as default of the func and in shim.js too.

2024-09-17 13:30 UTC, NicolasMassart commented on e2e/mockserver/mockserver.js
> +export const startMockServer = async ({
Q: should we also handle response headers? I guess we have some request with headers in the response.
We can default to no headers `{}`.

2024-09-17 13:30 UTC, NicolasMassart commented on shim.js
> +    global.fetch = async (url, options) =>
Q: what about requests not using fetch? Is this mocking in case of Axios is used?

2024-09-17 15:34 UTC, SamuelSalas commented on e2e/specs/wallet/suggestedGasApi.mock.spec.js
> +        await TestHelpers.delay(20000);
The main reason is that we encounter an error with Detox when the app change the legacy suggested gas fee modal to the new  EIP1559 modal. So the pause is just to give the app enough time to change modals and continue with the testing.

2024-09-17 15:45 UTC, SamuelSalas commented on e2e/mockserver/mockserver.js
> +export const startMockServer = async ({
We could handle the response headers, but in this case the main objective of the pr was to push a POC for how the mockserver would be implemented on the detox test. So we just wanted to show one scenario were the behavior of the app changed by mocking one response. We didn't want to add more than needed.

2024-09-17 17:08 UTC, Andepande commented on shim.js
> +    global.fetch = async (url, options) =>
A: We experimented with several methods for rerouting network traffic and found that this approach is a lightweight solution that effectively routes most requests to the mock server for our use case. However, if we encounter situations where axios or other custom request methods are not intercepted, we can modify the code to better handle these cases or introduce conditional logic to accommodate different types of requests.

2024-09-17 17:44 UTC, NicolasMassart commented on e2e/specs/wallet/suggestedGasApi.mock.spec.js
> +        await TestHelpers.delay(20000);
Could we await something instead of having a fixed 20s pause?

2024-09-17 17:47 UTC, NicolasMassart commented on shim.js
> +    const defaultMockPort = 8000;
C: my point was to reuse port const from e2e/mockserver/mockserver.js here too

2024-09-18 11:39 UTC, NicolasMassart commented on e2e/specs/wallet/suggestedGasApi.mock.spec.js
> +        await TestHelpers.delay(20000);
Timeout is better. Thanks!

2024-09-18 11:39 UTC, NicolasMassart approved these changes, later dismissed
Looks good to me. Great work!

2024-09-18 21:38 UTC, cortisiko approved these changes

2024-09-18 21:44 UTC, SamuelSalas approved these changes

2024-09-18 22:02 UTC, merged