addressed lint issues
MetaMask/metamask-mobile pull request #11194
Opened 2024-09-13 12:04 UTC by Daniel-Cross

## **Description**

A PR that addresses all 50 current linting issues found in the repo when running `yarn lint`

## **Related issues**

Fixes:

1. Run `yarn lint` and see there are no linting issues remaining.
2. Run `yarn test:unit` and see all tests pass.

## **Screenshots/Recordings**

### **Before**
<img width="514" alt="Screenshot 2024-09-13 at 14 03 28" src="https://github.com/user-attachments/assets/afb5a55c-94ce-44ad-808f-2f051c559e76">
### **After**
<img width="274" alt="Screenshot 2024-09-13 at 14 01 40" src="https://github.com/user-attachments/assets/58417fc7-5647-4028-9702-d1a79e4f550a">
<img width="365" alt="Screenshot 2024-09-13 at 14 02 28" src="https://github.com/user-attachments/assets/33c894a8-c83d-41bc-90a7-52c512915e4e">

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-17 15:02 UTC, brianacnguyen approved these changes, later dismissed

2024-09-17 17:16 UTC, tommasini commented on app/components/UI/EditGasFee1559/index.js
> +  const RenderInfoIcon = useCallback(
NIT: Is this PascalCase intentionally?

2024-09-17 17:17 UTC, tommasini commented on app/components/UI/EditGasFee1559/__snapshots__/index.test.tsx.snap
> +                        <Unknown
Interesting that the changes on `RenderInfoIcon` make the snapshot update to use `Unknown`

2024-09-17 17:21 UTC, tommasini commented on ios/MetaMask.xcodeproj/project.pbxproj
> +		BD4D3EFD86C6275688BF457A /* libPods-MetaMask-QA.a in Frameworks */ = {isa = PBXBuildFile; fileRef = C70E98D3DE4855533F66851F /* libPods-MetaMask-QA.a */; };
Were these changes intentional?  They seem unrelated to the PR

2024-09-18 07:43 UTC, Daniel-Cross commented on app/components/UI/EditGasFee1559/index.js
> +  const RenderInfoIcon = useCallback(
Yeah, I thought it would make more sense as a component instead of a function, but I'm happy to change it if we prefer to it to be a function instead of it's own component.

2024-09-18 07:44 UTC, Daniel-Cross commented on app/components/UI/EditGasFee1559/__snapshots__/index.test.tsx.snap
> +                        <Unknown
Yeah that is weird? Not entirely sure why. I can take a look

2024-09-18 07:45 UTC, Daniel-Cross commented on ios/MetaMask.xcodeproj/project.pbxproj
> +		BD4D3EFD86C6275688BF457A /* libPods-MetaMask-QA.a in Frameworks */ = {isa = PBXBuildFile; fileRef = C70E98D3DE4855533F66851F /* libPods-MetaMask-QA.a */; };
Probably not, I'll revert these

2024-09-30 10:58 UTC, tommasini commented on app/core/SDKConnect/handlers/handleConnectionReady.test.ts
> -import handleConnectionReady from './handleConnectionReady';
This file seems to be testing `handleConnectionReady`, was this intentional?

2024-09-30 11:50 UTC, Daniel-Cross commented on .vscode/settings.json
> +  "javascript.preferences.importModuleSpecifier": "relative",
Yeah this was intentional. At the moment the linter auto imports files with the path of `app/src/components/etc` but this causes errors because the workflow linters only accept relative paths such as `.../.../.../components/etc`. This is fine if you're using something like Intellisense and have custom lint rules, but if you're using VSCode, it will default to the repo linting rules.

2024-09-30 11:51 UTC, Daniel-Cross commented on app/core/SDKConnect/handlers/handleConnectionReady.test.ts
> -import handleConnectionReady from './handleConnectionReady';
Let me double check this. Not sure why it's been removed.

2024-09-30 12:45 UTC, tommasini commented on .vscode/settings.json
> +  "javascript.preferences.importModuleSpecifier": "relative",
Love it! Thanks!

2024-09-30 14:16 UTC, sahar-fehri commented
Tested NFT and token detection, LGTM 🙏

2024-09-30 14:16 UTC, sahar-fehri approved these changes, later dismissed

2024-10-03 16:42 UTC, tommasini commented on app/components/Nav/App/index.js
> +  const DetectedTokensFlow = useCallback(
Regarding what was being said on this [thread](https://consensys.slack.com/archives/C04GLB755TK/p1727967564680889), what do you think of instead of adding this useCallbacks we isolate this flow in separate files/folders and actually turn this nav/app component more readable?

2024-10-08 08:20 UTC, Daniel-Cross commented on app/components/Nav/App/index.js
> +  const DetectedTokensFlow = useCallback(
Yes! We should definitely look into making some changes to this file to make it easier to manage and deal with the useCallbacks

2024-10-11 12:18 UTC, tommasini commented on .eslintrc.js
> +    'react/no-unstable-nested-components': 'off',
Sorry, I missed, was decided to silent the warning instead of address it?

2024-10-11 12:31 UTC, tommasini requested changes, later dismissed
Let's discuss turning off this rule internally

2024-10-14 16:10 UTC, Daniel-Cross commented on .eslintrc.js
> +    'react/no-unstable-nested-components': 'off',
Addressed this and removed the rule override.

2024-10-17 16:59 UTC, sethkfman approved these changes, later dismissed
LGTM

2024-10-18 13:34 UTC, tommasini commented on app/components/Nav/App/index.js
> +      // eslint-disable-next-line react/prop-types
Is this disable needed since we are ignoring the rule on props [here](https://github.com/MetaMask/metamask-mobile/pull/11194/files#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5R57)
```suggestion

```

2024-10-18 13:36 UTC, tommasini commented on app/components/Nav/Main/MainNavigator.js
> +      // eslint-disable-next-line react/no-unstable-nested-components
Is the disable still needed since we are adding the rule [here](https://github.com/MetaMask/metamask-mobile/pull/11194/files#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5R57)?
```suggestion

```

2024-10-18 13:39 UTC, tommasini commented on app/components/UI/AssetOverview/PriceChart/PriceChart.tsx
> +/* eslint-disable react/no-unstable-nested-components */
Are we disabling the rule at this component for any reason?

2024-10-18 13:39 UTC, tommasini commented on app/components/Views/confirmations/components/EditGasFee1559Update/index.tsx
> +/* eslint-disable react/no-unstable-nested-components */
Are we disabling the rule at this component for any reason?

2024-10-18 20:11 UTC, Daniel-Cross commented on app/components/UI/AssetOverview/PriceChart/PriceChart.tsx
> +/* eslint-disable react/no-unstable-nested-components */
The component from this package called `<Tooltip />` has props passed into it by default from the parent, however they're not declared so I can't change the component to be a function or something instead. The way we're doing it in this file is also how they recommend doing it in the docs, so for this file it would seem to make sense to skip the check.

2024-10-18 20:12 UTC, Daniel-Cross commented on app/components/Views/confirmations/components/EditGasFee1559Update/index.tsx
> +/* eslint-disable react/no-unstable-nested-components */
This file needs completely re-writing, it has lots of issues. The second you touch something nothing things stop working, sonar cloud has issues and e2e have issues. I would suggest we come back and address this one some other time.

2024-10-21 17:58 UTC, infiniteflower approved these changes

2024-10-21 21:14 UTC, owencraston commented on .eslintrc.js
> +            allowAsProps: true,
What is the consequence of this? how much of a lift would it be to remove these instances?

2024-10-21 21:26 UTC, vinnyhoward approved these changes

2024-10-21 21:39 UTC, Daniel-Cross commented on .eslintrc.js
> +            allowAsProps: true,
This is just for false positives such as this:
```
navigation.setParams({
        headerLeft: () => <View />,
     });
```
It only affects a couple of files that do this when they want to hide the back button while a password reset or something similar is ongoing.

2024-10-21 22:27 UTC, brianacnguyen approved these changes

2024-10-21 22:32 UTC, sahar-fehri approved these changes

2024-10-22 01:02 UTC, abretonc7s approved these changes

2024-10-22 04:26 UTC, jpuri approved these changes
Changes in files owned by confirmations team look good.

2024-10-22 07:52 UTC, andreahaku approved these changes
LGTM

2024-10-22 11:26 UTC, NicolasMassart approved these changes

2024-10-22 12:24 UTC, ccharly approved these changes
LGTM for `core/Encryptor` test changes, thanks!

2024-10-22 12:38 UTC, merged