add Transaction trace implementation
MetaMask/metamask-mobile pull request #11191
Opened 2024-09-13 09:48 UTC by OGPoyraz

## **Description**

- Adding `createTracingMiddleware` to start tracing for defined type of messages.
- Adding `trace` callback to `TransactionController`.
- End `Notification Display` trace after confirmation landed on users screen. (We don't name `Notification` for user confirmations in mobile, but the since the trace name is `Notification Display` in controller, we will leave it for now and refactor naming later)

## **Related issues**

Fixes: https://github.com/MetaMask/mobile-planning/issues/1876

## **Manual testing steps**

1. Set `MM_SENTRY_DSN_DEV` to developer Sentry dsn, see the value here https://github.com/MetaMask/metamask-extension/blob/develop/.metamaskrc.dist
2. Go test-dapp in app, trigger and accept test transaction
3. If you used the mentioned dsn above, your `Transaction` trace will appear on this link: https://metamask.sentry.io/traces/?project=273496&query=transaction%3ATransaction&source=traces&statsPeriod=1h

## **Screenshots/Recordings**

Example trace: https://metamask.sentry.io/performance/trace/1c4b2cfbe13640448ff5ac33feb13692/?node=txn-a3464e9139ad47c5bed4adbcfc756920&pageEnd&pageStart&project=273496&query=transaction%3ATransaction&source=traces&statsPeriod=1h&timestamp=1726219598.426

### **Before**

### **After**

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [X] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [X] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-13 10:04 UTC, OGPoyraz commented on app/components/Views/confirmations/components/TransactionReview/index.js
> +    endTrace({ name: TraceName.NotificationDisplay, id: transaction.id });
We don't name Notification for user confirmations in mobile, but the since the trace name is Notification Display in controller, we will leave it for now and refactor naming later

2024-09-13 20:51 UTC, Cal-L reviewed
left some comments

2024-09-13 20:51 UTC, Cal-L commented on app/core/createTracingMiddleware.test.ts
Let's place this and the original file in a folder named `createTracingMiddleware`

2024-09-13 20:51 UTC, Cal-L commented on app/core/createTracingMiddleware.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Let's remove the TS ignore and type the req and res. You can reference `eth_sendTransaction` on what that looks like

2024-09-13 20:51 UTC, Cal-L commented on app/core/RPCMethods/eth_sendTransaction.ts
> +    traceContext?: unknown;
Does Sentry provide a type for this?

2024-09-13 20:51 UTC, Cal-L commented on app/core/createTracingMiddleware.test.ts
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Let's type this file if we can

2024-09-14 20:31 UTC, matthewwalsh0 requested changes

2024-09-14 20:31 UTC, matthewwalsh0 commented on app/components/Views/confirmations/components/TransactionReview/index.js
> +    endTrace({ name: TraceName.NotificationDisplay, id: transaction.id });
Should we do this at the start of the function as there is some `await` calls before this point that may delay the timing?

2024-09-14 20:31 UTC, matthewwalsh0 commented on app/core/RPCMethods/eth_sendTransaction.ts
> +    traceContext?: unknown;
Technically it does, but part of the goal of the `trace` utility functions is to abstract the use of `Sentry` to reduce coupling.

But while there should be no need to manipulate or inspect the value itself, we do still define a `TraceContext` type equal to `unknown` within `trace.ts`, in case we update the type in future.

2024-09-14 20:31 UTC, matthewwalsh0 commented on app/core/RPCMethods/eth_sendTransaction.ts
> +    actionId: req.id as string,
Is this related to this PR? Why do we need to add action ID support here?

2024-09-14 20:31 UTC, matthewwalsh0 commented on app/core/createTracingMiddleware.ts
> +      await trace({
Do these two need `await` since they are just starting traces which should be synchronous?

2025-01-01 10:34 UTC, closed without merging