feat(NOTIFY-1096): add account syncing
MetaMask/metamask-mobile pull request #11190
Opened 2024-09-13 08:30 UTC by mathieuartu

## **Description**

⚠️ DO NOT MERGE yet since this PR contains preview packages.

This PR adds [account syncing](https://www.figma.com/board/sx26FtZcQc0zs0z5hpdqBh/Account-Syncing-Solution?t=5Oy00gbHLnoPqyYP-0) to MetaMask.
As part of profile syncing, with this new feature, users will be able to synchronize all of their accounts and accounts' names across all of their devices.

## **Related issues**

Fixes:

[NOTIFY-1096](https://consensyssoftware.atlassian.net/jira/software/projects/NOTIFY/boards/616?assignee=712020%3A5843b7e2-a7fe-4c45-9fbd-e1f2b2eb58c2&selectedIssue=NOTIFY-1096)

## **Manual testing steps**

1. Log in with SRP
2. Activate profile syncing in preferences
3. Add new accounts and rename others
4. Using another browser, log in with SRP
5. Activate profile syncing in preferences
6. Watch the magic happen!

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-13 08:30 UTC, mathieuartu commented
I have read the CLA Document and I hereby sign the CLA

2024-10-16 07:59 UTC, Prithpal-Sooriya submitted a review, later dismissed

2024-10-16 07:59 UTC, Prithpal-Sooriya commented on app/components/Views/Wallet/index.tsx
> +        dispatchAccountSyncing();
This is fine.

I am still paranoid about mobile performance.
I think we are okay, so let's leave as is

2024-10-16 07:59 UTC, Prithpal-Sooriya commented on app/core/Engine.ts
> +import { NotificationParameters } from '@metamask/snaps-rpc-methods/dist/restricted/notify.cjs';
Just making sure. Is this change intentional?

2024-10-16 08:35 UTC, Jonathansoufer approved these changes, later dismissed
LGTM!

2024-10-16 08:49 UTC, Daniel-Cross submitted a review, later dismissed
Just one small listing issue fix and you're good to go!

2024-10-16 08:55 UTC, Daniel-Cross submitted a review, later dismissed
GTG!

2024-10-16 08:55 UTC, NicolasMassart requested changes

2024-10-16 08:55 UTC, NicolasMassart commented on app/util/notifications/hooks/useProfileSyncing.ts
This file name should match the hook name: useAccountSyncing

2024-10-16 08:55 UTC, NicolasMassart commented on app/components/Views/Wallet/index.tsx
> +        dispatchAccountSyncing();
Q: Can we test this effect in the unit tests?

2024-10-16 09:27 UTC, mathieuartu commented on app/util/notifications/hooks/useProfileSyncing.ts
Updated the PR to move account sync related hooks & tests to their own files named accordingly!

2024-10-16 09:30 UTC, mathieuartu commented on app/components/Views/Wallet/index.tsx
> +        dispatchAccountSyncing();
It's a pain to locally test using jest for `app/components/Views/Wallet/index.test.tsx`, do you have a trick in mind so I can bypass this error?

Happy to explore that for both `listNotifications` and  `dispatchAccountSyncing` in a subsequent PR as well. LMK

![Capture d’écran 2024-10-16 à 11 29 24](https://github.com/user-attachments/assets/fcf6c251-22e2-4665-a5b9-1133353e5d09)

2024-10-16 11:31 UTC, NicolasMassart requested changes

2024-10-16 11:31 UTC, NicolasMassart commented on app/core/Engine.ts
> +                profile_id: profileId,
C: trackEvent called with legacy way has been deprecated recently. You will find out how to use the new `MetricsEventBuilder` in the code documentation

2024-10-17 11:19 UTC, NicolasMassart requested changes

2024-10-17 11:19 UTC, NicolasMassart commented on app/components/Views/Wallet/index.test.tsx
> +    const handleAppStateChange = addEventListener.mock.calls[0][1];
C: Not fond of this as if we add another listener in the code, this will break this test even if the feature works.
```suggestion
    expect(addEventListener).toHaveBeenCalledWith('change', expect.any(Function));

    const handleAppStateChange = (addEventListener as jest.Mock).mock.calls.find(
      ([event]) => event === 'change'
    )[1];
```

2024-10-18 09:10 UTC, NicolasMassart submitted a review, later dismissed
Looks good to me.
Thanks for your work that makes this codebase better!

2024-10-23 15:16 UTC, NicolasMassart commented
Did I delete this branch and thus closed this PR by mistake?
I'm not sure what happened here...
I'm very sorry if I did.
I restored the branch and reopened the PR.
🙇🙇🙇🙇🙇🙇🙇

2024-10-25 12:08 UTC, mathieuartu commented on e2e/mockServer/mockServer.js
> +  });
I've been fiddling around in this file, eventually coming back to the original implementation. But Prettier wanted a better indentation 😀

2024-10-25 12:09 UTC, mathieuartu commented on e2e/specs/notifications/utils/user-storage/userStorageMockttpController.js
> +// TODO: Export user storage schema from @metamask/profile-sync-controller
I'm thinking this will eventually end up in our shared package. Keeping it here for now since Yande will introduces changes to the mock system soon.

2024-10-25 12:10 UTC, mathieuartu commented on e2e/specs/notifications/utils/user-storage/userStorageMockttpController.js
> +// TODO: Export user storage schema from @metamask/profile-sync-controller
PS: We have the same controller on extension, hence maybe sharing this in our package. Keeping it here for rapid changes if needed, will move it once everything is stable.

2024-10-28 12:11 UTC, Prithpal-Sooriya commented on app/core/Engine.ts
> +        isAccountSyncingEnabled: Boolean(process.env.IS_TEST),
OK nice, so we will merge this PR with account syncing in test env only?

2024-10-28 12:11 UTC, mathieuartu commented on app/core/Engine.ts
> +        isAccountSyncingEnabled: Boolean(process.env.IS_TEST),
Yes that's the plan @Prithpal-Sooriya  !

Slack convo about this is here: 

https://consensys.slack.com/archives/C02U025CVU4/p1729868322146649

2024-10-28 12:15 UTC, Prithpal-Sooriya commented on e2e/specs/notifications/account-syncing/sync-after-adding-custom-name-account.spec.js
> +        return JSON.parse(decryptedAccountName).n;
This is fine. We've discussed this and can make this easier to work with in the future.

2024-10-28 12:15 UTC, Prithpal-Sooriya commented on e2e/specs/notifications/account-syncing/sync-after-adding-custom-name-account.spec.js
> +    await WalletView.tapIdenticon();
This is good enough as a framework for @cmd-ob to pick up and use a Page Object Model / clean up these tests.

2024-10-28 12:16 UTC, Prithpal-Sooriya commented on e2e/specs/notifications/utils/constants.js
> +  'leisure swallow trip elbow prison wait rely keep supply hole general mountain';
To emphasise, this SRP does not have any funds and is only used for testing purposes.

2024-10-28 12:19 UTC, Prithpal-Sooriya commented on e2e/specs/notifications/utils/mocks.js
> +      const url = getDecodedProxiedURL(request.url);
To keep this PR unblocked, lets keep as is, but I am not convinced on this proxy pattern and it should be removed - or removed at least for our mocks.

2024-10-28 12:20 UTC, Prithpal-Sooriya commented on e2e/specs/notifications/utils/user-storage/userStorageMockttpController.js
> +export class UserStorageMockttpController {
Really nice work with this mockttp controller, once we are satisfied with this, it would be cool to decouple and have a shareable version with extension and mobile.

2024-10-28 12:21 UTC, Prithpal-Sooriya commented on e2e/specs/notifications/utils/user-storage/userStorageMockttpController.test.js
Wow testing your test utils 😄 

No complaints, and glad that you are being thorough.

2024-10-28 12:22 UTC, Prithpal-Sooriya commented on e2e/viewHelper.js
> +    seedPhrase ?? validAccount.seedPhrase,
Nice test override optionality!

2024-10-28 12:22 UTC, Prithpal-Sooriya submitted a review, later dismissed

2024-10-28 14:20 UTC, Prithpal-Sooriya submitted a review, later dismissed

2024-10-28 18:15 UTC, cortisiko requested changes
Left some comments, good work on writing these e2e tests.

2024-10-28 18:22 UTC, cortisiko commented on bitrise.yml
> +      - run_tag_smoke_notifications_ios: {}
Great job adding workflows for these tests! Given our focus on optimizing CI resource usage, I suggest we avoid creating separate workflows for now. Instead, let’s integrate these tests into the existing accounts workflow, as they align with the responsibilities in that area. You can label the new tests as SmokeAccounts.

2024-10-28 21:07 UTC, mathieuartu commented on bitrise.yml
> +      - run_tag_smoke_notifications_ios: {}
Thanks for the thorough review @cortisiko ! Appreciate it :) 

I'll add the requested changes tomorrow morning!

About the above comment specifically, I feel like we could still gain in the long run by having a separate notifications flow on Bitrise.
The reason is, our features depend heavily on the use of encryption / decryption, and a lot of our test cases will need to boot the application several times in a row in the same test statement to verify syncing.
Because of all that, our tests are likely to be longer than others (time wise) and I feel we could benefit from the parallelization. WDYT? Happy to discuss!!

2024-10-28 22:30 UTC, cortisiko commented on bitrise.yml
> +      - run_tag_smoke_notifications_ios: {}
okay fair points. For now we can keep but keep in the soon to near future we are going to do some optimizations where we are aiming to run our tests by lanes instead of by individual teams!

2024-10-31 19:08 UTC, mathieuartu commented on e2e/specs/notifications/utils/mocks.js
> +      const url = getDecodedProxiedURL(request.url);
Let's discuss this with Yande next week, we can work something out :)

2024-10-31 19:10 UTC, mathieuartu commented on e2e/specs/notifications/account-syncing/sync-after-onboarding.spec.js
> +        element(by.text(accountName).and(by.id('cellbase-avatar-title'))),
Turns out it actually was in `AccountActionsModal` 😛 Fixed!

2024-10-31 22:53 UTC, cortisiko approved these changes
🌮 🌮 🌮

2024-11-01 08:15 UTC, merged