feat: update text of swaps gas tooltip
MetaMask/metamask-mobile pull request #11269
Opened 2024-09-17 21:01 UTC by martahj

## **Description**

Updates the swap gas tooltip text

## **Manual testing steps**

1. Enter info for a swap
2. Proceed to the review screen
3. Click on the tooltip
4. Confirm that the tooltip has been updated to say, "MetaMask doesn't make money from gas fees. These fees are estimates and can change based on how busy the network is and how complex a transaction is. Learn more here."  [“here” is a hyperlinkl that should link to help center FAQs on gas fees: [Gas fees | MetaMask Help Center 🦊♥️](https://support.metamask.io/transactions-and-gas/gas-fees/) ]

## **Screenshots/Recordings**

### **Before**

<img width="296" alt="Screenshot 2024-09-17 at 9 10 45 AM" src="https://github.com/user-attachments/assets/001577cd-90f9-4ad8-a3ff-64f4458a8360">

### **After**

<img width="287" alt="Screenshot 2024-09-17 at 1 42 11 PM" src="https://github.com/user-attachments/assets/365b93ba-6965-4723-9e9f-c14aa90bdc93">

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-18 13:34 UTC, martahj commented
I have read the CLA Document and I hereby sign the CLA

2024-09-18 13:36 UTC, martahj commented
Failing CI due to team label (nb: there is a PR open to add team label)

2024-09-19 20:12 UTC, infiniteflower approved these changes
Tested, looks good

2024-09-20 21:48 UTC, ejwessel approved these changes

2024-10-15 18:48 UTC, NicolasMassart commented
The tooltip text is gray:
<img width="320" alt="Screenshot 2024-10-15 at 20 46 31" src="https://github.com/user-attachments/assets/37283a5f-1f3c-4da2-971f-4a3cd2bb0b38">

When the other tooltip for the MEtamask fees is black:
<img width="345" alt="Screenshot 2024-10-15 at 20 46 49" src="https://github.com/user-attachments/assets/7b8794dc-df6e-4505-890d-6a38676adb95">

2024-10-15 18:49 UTC, NicolasMassart requested changes
- Text color difference between tooltips on the same screen
- no unit tests for this new code

2025-01-20 20:31 UTC, closed without merging