feat: added KeyValueRow to component-library/components-temp
MetaMask/metamask-mobile pull request #11294
Opened 2024-09-18 17:07 UTC by Matt561

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-19 13:05 UTC, brianacnguyen requested changes
Can you provide a Figma link in the comment?

2024-09-19 13:21 UTC, Matt561 commented
> Can you provide a Figma link in the comment?

Sure thing! Here's what I used. I don't think it's part of DS yet though. 

https://www.figma.com/design/1c0Y9jDJe6p0j82jydJDcs/Mobile-Staking?node-id=2187-96037&t=kOEnlk3CXZ727Qjb-1

2024-09-19 14:12 UTC, brianacnguyen commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.types.ts
> +
the name of these interfaces might be too generic, and since the props only apply for this component at the moment, can you add some specificities to the naming?

2024-09-19 14:12 UTC, brianacnguyen commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.types.ts
> +}
adding descriptions and defaults as comments would be helpful

2024-09-19 14:13 UTC, brianacnguyen commented on storybook/decorators/withNavigation.tsx
> +
can you attach a video to show that storybook still functions properly with this change?

2024-09-19 14:13 UTC, Matt561 commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.types.ts
> +
Yes I'll change this. I actually started with specific names but shortened them in the last commit or two.

2024-09-19 14:14 UTC, brianacnguyen commented on storybook/storyLoader.js
> +  require('../app/component-library/components-temp/TagColored/TagColored.stories');
you can probably remove these changes

2024-09-19 14:14 UTC, brianacnguyen commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.types.ts
> +  tooltip?: Tooltip;
probably better to extend from text props

2024-09-19 14:16 UTC, brianacnguyen commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.types.ts
> +
also our current TextField refers to inputs, so might want to change it to something different

2024-09-19 14:18 UTC, brianacnguyen commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.types.ts
> +
Have you tried using the ListItem component or extends from it. It has all of these props as well

2024-09-19 14:19 UTC, brianacnguyen commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.tsx
> +import { useStyles } from '../../hooks';
This is a rather large file with 3 components inside (section, row, and label). The section can at least be separated into its own component.

2024-09-19 14:20 UTC, brianacnguyen commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.tsx
> +          accessibilityLabel={`${tooltip.title}} tooltip`}
nice

2024-09-19 14:21 UTC, brianacnguyen commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.tsx
> +            <AvatarToken
the name shouldRenderKeyTextPrimaryIcon implies that it should render any icon/avatar, but it seems like only avatar token is rendered. Other icons like network icons or ui icons wont be able to be rendered with this

2024-09-19 14:24 UTC, brianacnguyen commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.stories.tsx
> +  decorators: [withNavigation],
can you move the Navigation decorator to the .storybook/ folder? Also can you upload a quick video walkthrough to make sure storybook is still working with this change?

2024-09-19 14:25 UTC, brianacnguyen requested changes
Requesting a few changes

2024-09-19 17:53 UTC, Matt561 commented on storybook/storyLoader.js
> +  require('../app/component-library/components-temp/TagColored/TagColored.stories');
I think these changes are auto-generated from the storybook scripts.

2024-09-19 17:59 UTC, Matt561 commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.types.ts
> +  tooltip?: Tooltip;
Good call out! I'll extend the TextProps if that's okay.

2024-09-19 22:04 UTC, Matt561 commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.tsx
> +            <AvatarToken
I've refactored the component to prioritize using our Icons out of the box.

2024-09-20 01:20 UTC, Matt561 commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.types.ts
> +
I wasn't aware of this component when I create the KeyValueRow. I've since refactored KeyValueRow to be simpler and more intuitive (at least I think so 😄).

2024-09-20 01:41 UTC, Matt561 commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.tsx
> +import { useStyles } from '../../hooks';
I've broken the subcomponents into their own directories.

2024-09-20 01:44 UTC, Matt561 commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.stories.tsx
> +  decorators: [withNavigation],
I added the storybook screen recording to the description. I'll also attach it here to save you a moment.


https://github.com/user-attachments/assets/a6ff29d4-56c7-4cf7-a7a9-8b4f0e41840a

2024-09-24 16:28 UTC, brianacnguyen approved these changes

2024-09-24 21:56 UTC, merged