feat: attribution id parameter in deeplinks
MetaMask/metamask-mobile pull request #11318
Opened 2024-09-19 13:21 UTC by abretonc7s

## **Description**

When a user is redirected to MetaMask Mobile app thanks to a deep link, including an attributionId parameter:

metamask://open.browser/website_url?attributionId=xyz
(deep link above is just a placeholder)

Then MM Mobile app should attach attributionId as a property to an event emitted right after Mobile app opens.
Given Mobile app would open and directly redirect the user to the in-app browser, the "App Opened" event might be a good candidate.

## **Related issues**

[Fixes: ](https://id.atlassian.com/login?continue=https%3A%2F%2Fid.atlassian.com%2Fjoin%2Fuser-access%3Fresource%3Dari%253Acloud%253Ajira%253A%253Asite%252F8831f492-a12c-460e-ac1b-400f1b09e935%26continue%3Dhttps%253A%252F%252Fconsensyssoftware.atlassian.net%252Fbrowse%252FSDK-18%253FatlOrigin%253DeyJpIjoiNzI2OWEwNTczYTZmNGEyZjgxYmFjYjkxMzJlZmE4MTYiLCJwIjoiaiJ9&application=jira)

## **Manual testing steps**

1. Open deeplink container url and check event on segment

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-19 13:44 UTC, gauthierpetetin commented on app/core/DeeplinkManager/ParseManager/parseDeeplink.ts
> +    }
I see `App Opened` event is emitted in `parseDeeplink` function.
This means it will only be emitted when App is opened through deep link, right?

If so, we might want to update the location of it, because we want it to be emitted every time the App is opened (via deep link but also without deep link). More detail in @Cal-L 's [comment](https://consensys.slack.com/archives/C07EJHAT6JX/p1726259653287669) on Slack.

2024-09-19 13:55 UTC, abretonc7s commented on app/core/DeeplinkManager/ParseManager/parseDeeplink.ts
> +    }
but everything goes threw parseDeeplinks, even the qrcode scanning

2024-09-19 13:58 UTC, gauthierpetetin commented on app/core/DeeplinkManager/ParseManager/parseDeeplink.ts
> +    }
If I presse the app icon on my phone and the app opens, will it also go through `parseDeeplink` function?

2024-09-19 13:58 UTC, abretonc7s commented on app/core/DeeplinkManager/ParseManager/parseDeeplink.ts
> +    }
this works on hot or cold start.

2024-09-20 08:00 UTC, gauthierpetetin commented
Adding release-7.32.0 on this PR to make sure we cherry-pick it. cc @Cal-L @sethkfman for visibility

2024-09-20 10:49 UTC, NicolasMassart requested changes
The new class could benefit from being split in a way that matches the actual process more semantically.
Understanding what this does is not easy and I see a risk of this becoming a "catch-all" place under the synonym "manager" name.
Refactoring into a more modular code now, given it's still fairly simple, could prevent many issues later and make this part more readable.

2024-09-20 10:49 UTC, NicolasMassart commented on app/core/Analytics/MetaMetrics.events.ts
> +  APP_OPENED = 'App Opened',
Q: would this be different from DAPP_VIEWED ?

2024-09-20 10:49 UTC, NicolasMassart commented on app/core/AppStateManager.test.ts
> +  it('should subscribe to AppState changes on instantiation', () => {
```suggestion
  it('subscribes to AppState changes on instantiation', () => {
```

2024-09-20 10:49 UTC, NicolasMassart commented on app/core/AppStateManager.test.ts
> +  it('should track event when app becomes active and conditions are met', () => {
Q: what conditions exactly?
```suggestion
  it('tracks event when app becomes active and [THE ACTUAL CONDITIONS]', () => {
```

2024-09-20 10:49 UTC, NicolasMassart commented on app/core/AppStateManager.test.ts
> +  it('should not track event when data collection is disabled', () => {
Q: what are you testing exactly here?
The assert shows the track event is called.
If you are testing that no actual event is sent to the SDK when metrics are not optin, this is already done on the metametrics test level, no need to repeat it here.

2024-09-20 10:49 UTC, NicolasMassart commented on app/core/AppStateManager.test.ts
> +  it('should not track event when there is no deeplink', () => {
Q: what does not tracking mean here? I can read the assert toHaveBeenCalledWith so it means trackEvent is called.

Also naming guidelines:
```suggestion
  it('does not track event when there is no deeplink', () => {
```

2024-09-20 10:49 UTC, NicolasMassart commented on app/core/AppStateManager.test.ts
> +  it('should handle errors gracefully', () => {
```suggestion
  it('handles app state change errors', () => {
```

2024-09-20 10:49 UTC, NicolasMassart commented on app/core/AppStateManager.test.ts
> +  it('should clean up the AppState listener on cleanup', () => {
```suggestion
  it('cleans up the AppState listener', () => {
```

2024-09-20 10:49 UTC, NicolasMassart commented on app/core/AppStateManager.test.ts
> +  it('should not process app state change when app is not becoming active', () => {
```suggestion
  it('does not process app state change when app is backgrounded', () => {
```

2024-09-20 10:49 UTC, NicolasMassart commented on app/core/AppStateManager.test.ts
> +  it('should not process app state change when app state has not changed', () => {
```suggestion
  it('does not process app state change when app state is the same', () => {
```
Q: Does this also work for other states?

2024-09-20 10:49 UTC, NicolasMassart commented on app/core/AppStateManager.ts
> +class AppStateManager {
C: I'm not fond of the name "manager". It tells not much about what this class does exactly, it's mostly synonym to "does things". Could you find a more precise term? Maybe there's a term used in the design patterns that could match?

Maybe try something like "AppStateChangeListener"?

Also the only public method on this class is setCurrentDeeplink(), and all the state part is private. Maybe the class name should be about deeplink or the class does to many different things that you had to find a generic term like "manager".
See also my next comment about extracting attribution code. This may help clarifying the scope of this class.

2024-09-20 10:49 UTC, NicolasMassart commented on app/core/AppStateManager.ts
> +  public setCurrentDeeplink(deeplink: string | null) {
Q: why the deeplink could be null? If the method is called, should it be when the deeplink exists?

2024-09-20 10:49 UTC, NicolasMassart commented on app/core/AppStateManager.ts
> +    }
S: Make nit modular. This attribution specific code could be extracted to a separate file to make the state management class scope restricted to managing states but not the consequences of state change.
You then link a specific process to happen on state change, here the attribution based on deeplink, and this is this part that will have the setCurrentDeeplink(), not the state change one.

2024-09-20 10:59 UTC, deeeed commented on app/core/Analytics/MetaMetrics.events.ts
> +  APP_OPENED = 'App Opened',
yes, DAPP_VIEWED is for in-app browser events. this is general to metamask app.

2024-09-20 11:00 UTC, deeeed commented on app/core/AppStateManager.test.ts
> +  it('should not process app state change when app state has not changed', () => {
we dont want to send the same event twice

2024-09-20 11:11 UTC, NicolasMassart commented on app/core/AppStateManager.test.ts
> +  it('should not process app state change when app state has not changed', () => {
I get it. Does this test also work if the state goes from background to background? Here we only test active.

2024-09-20 11:11 UTC, NicolasMassart commented on app/core/AppStateManager.test.ts
> +  it('tracks event when app becomes active and conditions are met', () => {
S: could this name be more specific than "conditions are met". What conditions exactly?

2024-09-20 11:11 UTC, NicolasMassart commented on app/core/AppStateManager.test.ts
> +  it('does not track event when data collection is disabled', () => {
Q: is this redundant with the test already existing in metametrics to check if trackEvent is done when opt-out?

2024-09-20 11:11 UTC, NicolasMassart commented on app/core/AppStateManager.test.ts
> +      { attributionId: undefined },
Q: should we send nothing at all instead of an undefined?

2024-09-20 11:11 UTC, NicolasMassart commented on app/core/AppStateManager.test.ts
> +  it('handles errors gracefully', () => {
```suggestion
  it('handles app state change processing errors', () => {
```

2024-09-20 13:05 UTC, NicolasMassart commented on app/core/processAttribution.tsx
> +    return params.attributionId;
C: if undefined, the return value from extractURLParams will be an empty string. Maybe you should align with your policy to return undefined.

2024-09-20 13:08 UTC, abretonc7s commented on app/core/AppStateEventListener.ts
>          { attributionId },
this is the same thing...

2024-09-20 13:12 UTC, abretonc7s commented on app/core/processAttribution.tsx
> +    return params.attributionId;
it('returns undefined when deeplink is undefined', () => {
    (store.getState as jest.Mock).mockReturnValue({
      security: { dataCollectionForMarketing: true },
    });

    const result = processAttribution(null);
    expect(result).toBeUndefined();
  });

2024-09-20 13:35 UTC, abretonc7s commented on app/core/AppStateEventListener.ts
>          { attributionId },
also you can't spread a string

2024-09-20 14:06 UTC, NicolasMassart approved these changes, later dismissed
Looks good to me.
Thanks for the very interesting discussion and for your care about the codebase!

2024-09-20 14:18 UTC, NicolasMassart submitted a review, later dismissed
Looks good to me.
Thanks for these last changes.

2024-09-20 15:29 UTC, Cal-L reviewed
left a comment

2024-09-21 01:50 UTC, deeeed commented on app/components/Nav/App/index.js
Initializing with the store definitely makes sense, but then there is also dependency to metametrics. I did play around initializing separately but then it also required changes on deeplink manager which was becoming a 
"complex" change for a small feature and went with this version.

2024-09-21 01:54 UTC, deeeed commented on app/components/Nav/App/index.js
I can adjust on Monday.

2024-09-23 09:56 UTC, abretonc7s commented on app/components/Nav/App/index.js
@Cal-L please take a look again

2024-09-23 15:35 UTC, Cal-L commented on app/components/Nav/App/index.js
Nice, that's looking clean

2024-09-23 15:36 UTC, Cal-L approved these changes
LGTM

2024-09-23 16:07 UTC, merged

2024-10-03 19:19 UTC, gauthierpetetin commented
Fixes https://github.com/MetaMask/mobile-planning/issues/1522