feat: disable wallet buttons for accounts that cannot sign transactions
MetaMask/metamask-mobile pull request #11330
Opened 2024-09-19 20:55 UTC by k-g-j

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-24 16:13 UTC, gantunesr reviewed
looks good overall, left some minor comments

2024-09-24 16:13 UTC, gantunesr commented on app/components/UI/WalletAction/WalletAction.types.ts
> +> = {
I suggest a different naming for these types instead of using the word `string`

```suggestion
export interface WalletActionDetail {
  title: string;
  description: string;
  disabledDescription: string;
}

export const walletActionDetails: Record<
  WalletActionType,
  WalletActionDetail
> = {
```

2024-09-24 16:13 UTC, gantunesr commented on app/components/UI/WalletAction/WalletAction.types.ts
> +    disabledDescription: strings('wallet.disabled_button.buy'),
Would it be better for these strings to also be inside `asset_overview` like the title and description?

2024-09-24 16:13 UTC, gantunesr commented on app/components/Views/WalletActions/WalletActions.test.tsx
> +  it('should disable buttons when the account cannot sign transactions', () => {
nit: I know the rest of the file is using the previous convention but that shouldn't stop us of using the new one

```suggestion
  it('disables action buttons when the account cannot sign transactions', () => {
```

2024-09-24 16:55 UTC, k-g-j commented on app/components/UI/WalletAction/WalletAction.types.ts
> +> = {
renamed here [20e79f9](https://github.com/MetaMask/metamask-mobile/pull/11330/commits/20e79f9f6747da06cc98ca81fd14d49cf471c11a)

2024-09-24 17:04 UTC, k-g-j commented on app/components/UI/WalletAction/WalletAction.types.ts
> +    disabledDescription: strings('wallet.disabled_button.buy'),
good idea! [845c66f](https://github.com/MetaMask/metamask-mobile/pull/11330/commits/845c66f17a2a2c164d0a942319d3f7995675b0c2)

2024-09-24 19:26 UTC, owencraston commented on app/components/UI/WalletAction/WalletAction.types.ts
> +  actionType?: WalletActionType;
why would this be optional if we are using it to derive the key information?

2024-09-24 19:30 UTC, owencraston commented on app/components/Views/WalletActions/WalletActions.tsx
> +  const canSignTransactions = selectedAccount?.methods?.includes(
lets memoize this value with React.useMemo: https://react.dev/reference/react/useMemo

2024-09-24 19:31 UTC, owencraston commented on app/components/UI/WalletAction/WalletAction.types.ts
> +export const walletActionDetails: Record<WalletActionType, WalletActionDetail> =
I like this a lot better.

2024-09-24 19:33 UTC, owencraston commented on app/components/Views/WalletActions/WalletActions.test.tsx
> +      ...mockInitialState,
Are all of these spreads necessary? Why cant you just modify the AccountsController section?

2024-09-24 19:35 UTC, owencraston commented on locales/languages/en.json
> +    "disabled_button": {
@AlexJupiter @eriknson what do you think of this copy?

2024-09-24 19:37 UTC, k-g-j commented on app/components/UI/WalletAction/WalletAction.types.ts
> +  actionType?: WalletActionType;
It is currently optional in the implementation on the main branch [here](https://github.com/MetaMask/metamask-mobile/blob/main/app/components/UI/WalletAction/WalletAction.types.ts#L6) and making it non-optional would break [AssetDetailsActions](https://github.com/MetaMask/metamask-mobile/blob/main/app/components/Views/AssetDetails/AssetDetailsActions/AssetDetailsActions.tsx)

2024-09-24 19:57 UTC, k-g-j commented on app/components/Views/WalletActions/WalletActions.tsx
> +  const canSignTransactions = selectedAccount?.methods?.includes(
smart thinking! [f5e18fb](https://github.com/MetaMask/metamask-mobile/pull/11330/commits/f5e18fb493d7eb6311063ef787dbc0182ffa9d26)

2024-09-24 20:35 UTC, k-g-j commented on app/components/Views/WalletActions/WalletActions.test.tsx
> +      ...mockInitialState,
We do need to spread the whole state unfortunately, because the buttons such as the Buy and Swap buttons need to know the context of the Chain ID and other configurations [see this test](https://github.com/MetaMask/metamask-mobile/blob/main/app/components/Views/WalletActions/WalletActions.test.tsx#L101) for an example why

2024-09-24 22:20 UTC, owencraston commented on app/components/UI/WalletAction/WalletAction.types.ts
> +  actionType?: WalletActionType;
true but now we are using this to derive the description which was previously a prop. I personally see no reason to make this optional. Do you?

2024-09-26 16:17 UTC, k-g-j commented on app/components/UI/WalletAction/WalletAction.types.ts
> +  actionType?: WalletActionType;
Agreed, we should make it non-optional 
done here [8c2b833](https://github.com/MetaMask/metamask-mobile/pull/11330/commits/8c2b833cb918dc60e8991e3f2c8e8544aefebd9e)

2024-09-26 20:59 UTC, owencraston commented on app/components/UI/WalletAction/WalletAction.tsx
> +          style={[
passing inline styles like this mean that on every render a new array instance will be passed as a prop. because of this the virtual dom will not memoize the props for this component. can you try and extract these out so they are not computed inline? The same should be done for the rest of the files.

2024-09-27 15:05 UTC, k-g-j commented on app/components/UI/WalletAction/WalletAction.tsx
> +          style={[
I believe I have made some improvement here in this commit [a9909ce](https://github.com/MetaMask/metamask-mobile/pull/11330/commits/a9909ce0e9d22affaa69ed60173d8f326df456ef)

2024-09-27 16:44 UTC, k-g-j commented on app/components/Views/AssetDetails/AssetDetailsActions/AssetDetailsActions.tsx
> +        renderWalletAction(
removed! [88690e1](https://github.com/MetaMask/metamask-mobile/pull/11330/commits/88690e1c50dc3996f419ac8125e25d878a85b0f9)

2024-09-27 16:45 UTC, owencraston approved these changes, later dismissed

2024-10-09 14:31 UTC, plasmacorral commented
Can confirm that observation 2 above can be reproduced on a flask build of main commit 9e3d2684acfaf193cc1781680beaf7ea29f5edb8.

2024-10-09 19:16 UTC, owencraston approved these changes, later dismissed

2024-10-09 21:32 UTC, plasmacorral commented
Observation 1 resolved in commit 91cb7d310b775b6d3f57875c713244fa1666f8f4
<div style="display: inline-block"><img width="140" src="https://github.com/user-attachments/assets/1d132425-b98e-47bd-936b-b454f2d1e202"><img width="140" src="https://github.com/user-attachments/assets/4ca7e5c5-819d-459b-aa8f-6a0cdb3f7af5"><img width="137" src="https://github.com/user-attachments/assets/8fe34cc4-13b3-4780-9957-ee126b06f766"><img width="133" src="https://github.com/user-attachments/assets/57cd3199-1f99-4453-985e-4dce9574948c"></div>

Observation 2 is beyond the scope of this PR and was not introduced here.  Now tracked as [633](https://github.com/MetaMask/accounts-planning/issues/633).

Observation 3 can be addressed later once we are in production with the ability to disable the actions

2024-10-09 22:56 UTC, plasmacorral commented
Maybe only wallet view is in scope here?  These action buttons are presented and usable from the asset details pages, even for an account that does not support signing and has actions disabled from wallet view.

https://www.loom.com/share/68348eda25db4e2187a21c047a2eb32a

Is this something that should also be addressed within this PR, or do we take this incremental improvement and follow it with a subsequent PR to address asset detail pages?

2024-10-11 01:47 UTC, plasmacorral commented
I now see that action buttons are disabled on the asset details pages. However, there is no feedback when a user clicks on these muted buttons, which can create the impression that the mobile app is unresponsive.

Although the [recording](https://www.loom.com/share/000203123b90425b92255ba96a50baf9?sid=aab86031-f120-41e2-9d82-2ea0746a3503) doesn't show it well, repeatedly clicking these muted buttons provides no feedback, which can be frustrating for users.

I'm not sure if we have an established pattern for this on mobile; it might be a good question for our DS teammates.

In the Chrome extension with Flask, the cursor changes to a barred circle, and a tooltip appears without requiring a click, explicitly stating "Not supported on this account."

While we may not be able to fully replicate the extension behavior, we have an opportunity to make the user experience more explicit on the asset details page and avoid the app feeling unresponsive.
<img width="246" alt="Screenshot 2024-10-10 at 9 37 36 PM" src="https://github.com/user-attachments/assets/05696877-609e-410a-ad15-2e88b9ffeacf">

2024-10-11 19:09 UTC, k-g-j commented
> I'm not sure if we have an established pattern for this on mobile; it might be a good question for our DS teammates.

cc: @eriknson and @AlexJupiter what are your thoughts?

2024-10-18 22:06 UTC, plasmacorral commented
Having an issue with local builds of flask on this branch in commit ab171e4b881505a2abdc6611a3eb397394be6854

```
ERROR  Error: createSelector expects all input-selectors to be functions, but received the following types: [undefined, function memoized(), function memoized()], js engine: hermes
 ERROR  TypeError: Cannot read property 'store' of undefined, js engine: hermes
 ERROR  Error: createSelector expects all input-selectors to be functions, but received the following types: [undefined, function memoized(), function memoized()], js engine: hermes
 ERROR  TypeError: Cannot read property 'store' of undefined, js engine: hermes
```
![Screenshot_20241018-174745](https://github.com/user-attachments/assets/8a9d3603-6e93-46fd-90c5-d97e4cd355cb)

2024-10-23 14:45 UTC, brianacnguyen commented on app/components/UI/WalletAction/WalletAction.tsx
> +
These style changes are not needed (and also does not follow our disabled pattern. Instead, you can just update the container style to have  `opacity: 0.5`

2024-10-23 14:46 UTC, brianacnguyen requested changes
1 small request

2024-10-24 19:46 UTC, k-g-j commented on app/components/UI/WalletAction/WalletAction.tsx
> +
okay! thanks for letting me me know :) 
I adjusted the styles to only use `opacity: 0.5` in this commit [153c801](https://github.com/MetaMask/metamask-mobile/pull/11330/commits/153c801904870d58708663be384383abbbd098f0)

2024-10-24 20:05 UTC, owencraston reviewed
Looking very good and very nice 😁 ! The code looks good I just had a few comments/questions about all the memoization of props.

2024-10-24 20:05 UTC, owencraston commented on app/components/Views/AssetDetails/AssetDetailsActions/AssetDetailsActions.tsx
> +            {...walletActionProps}
I THINK the spread operator here defeats the purpose of the memoization since spreading the object will create a new reference anyway. [See this stackoverflow thread](https://stackoverflow.com/questions/52959059/does-spread-operator-return-new-object-after-operation). I am not certain about this so please correct me if I am wrong.

2024-10-24 20:05 UTC, owencraston commented on app/components/Views/AssetDetails/AssetDetailsActions/AssetDetailsActions.tsx
> +            {...walletActionProps}
the same goes for the rest of the file.

2024-10-24 20:05 UTC, owencraston commented on app/components/Views/WalletActions/WalletActions.tsx
> +            {...walletActionBaseProps}
same question about spreading the memoized props.

2024-10-24 20:07 UTC, owencraston commented
you will need to run `yarn jest -u pp/components/UI/AssetOverview/AssetOverview.test.tsx` to update the snapshot and get your unit tests passing.

2024-10-24 20:19 UTC, k-g-j commented on app/components/UI/WalletAction/WalletAction.tsx
> +      style={[styles.base, containerStyle, disabled && styles.disabled]}
[5946bfb](https://github.com/MetaMask/metamask-mobile/pull/11330/commits/5946bfb50a54bf9003b4ef85e56d2c47227203c4)

2024-10-24 20:28 UTC, k-g-j commented on app/components/Views/AssetDetails/AssetDetailsActions/AssetDetailsActions.tsx
> +            {...walletActionProps}
I THINK you are right

I updated the code in this commit [37077bf](https://github.com/MetaMask/metamask-mobile/pull/11330/commits/37077bfc24ac5a8022b1e5d05f833d3ec17bff89) so we're not creating new object references unnecessarily, which was defeating the purpose of memoization. It also makes the code more explicit about which props are being passed to each `WalletAction` component.

2024-10-24 20:31 UTC, k-g-j commented on app/components/Views/WalletActions/WalletActions.tsx
> +            {...walletActionBaseProps}
Same logic as your above comment and my point about creating new object references unnecessarily 
addressed here [37077bf](https://github.com/MetaMask/metamask-mobile/pull/11330/commits/37077bfc24ac5a8022b1e5d05f833d3ec17bff89)

2024-10-29 01:21 UTC, plasmacorral commented
Tested on Pixel 5a with Android 14 with commit [f714dd1d56a1b22e79b6b53cc8a5668294a22eca](https://github.com/MetaMask/metamask-mobile/pull/11330/commits/f714dd1d56a1b22e79b6b53cc8a5668294a22eca). Buttons were enabled in the wallet view bottom bar and asset view when signing was enabled on the snap account, and disabled when signing permission was removed. Re-enabling signing restored the buttons. Checked on Eth mainnet, Sepolia, Base, and Arbitrum. No impact on button display or function for HD, imported, QR, and Ledger accounts.

2024-10-29 16:34 UTC, brianacnguyen commented on app/components/UI/WalletAction/WalletAction.tsx
> +      backgroundColor: disabled ? colors.primary.muted : colors.primary.default,
this disabled change is not needed since the opacity would take care of color change

2024-10-29 16:34 UTC, brianacnguyen requested changes
1 small request regarding avatar disabled

2024-11-05 01:54 UTC, owencraston commented
Do to difficulty rebasing this PR I am continuing the work over [here](https://github.com/MetaMask/metamask-mobile/pull/12145).

2024-11-05 01:54 UTC, closed without merging