refactor(1702-3): batch account balance component
MetaMask/metamask-mobile pull request #11368
Opened 2024-09-21 22:32 UTC by vinnyhoward

## **Description**

WIP

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

NA

### **After**

NA

## **Pre-merge author checklist**

- [ x I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-26 00:55 UTC, cortisiko commented
Smoke and [Regression](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/91019cad-cefa-4aed-8d51-cddaeff64200) runs are passing on this PR.

2024-09-27 06:17 UTC, brianacnguyen requested changes, later dismissed
Can you add a story for easy viewing?

2024-09-27 06:17 UTC, brianacnguyen commented on app/components/Views/Settings/BatchAccountBalanceSettings/index.tsx
> +// Third party dependencies
if you can can you add a story for these components?

2024-10-03 17:20 UTC, andreahaku reviewed
just a few minor comments :)

2024-10-03 17:20 UTC, andreahaku commented on app/components/Views/Settings/BatchAccountBalanceSettings/index.tsx
> +  const toggleIsMultiAccountBalancesEnabled = (
maybe you can memoize this by using `useCallback`

2024-10-03 17:20 UTC, andreahaku commented on app/components/Views/Settings/BatchAccountBalanceSettings/index.tsx
> +    const { PreferencesController } = Engine.context;
you can take the destructuring out of the function and check if `PreferencesController` exists in the following line

2024-10-03 17:26 UTC, EtherWizard33 approved these changes, later dismissed
Looks good to me, approved.

 I liked the readability of the description, all info was useful and I could understand it event before getting into the code, and the code was very readyable too, nice.

Small nit, in the gif, the hidden balance was showing only at the end of the animation and I had to ninja screencapture the last half second to see it :)

and i had to zoom out to fit the mobile screenshot on my laptop, just in case you need to set sizes, this is what i use <img width="350" alt="alt text" src="...path...">

2024-10-03 18:03 UTC, gambinish commented on app/components/Views/Settings/BatchAccountBalanceSettings/index.tsx
> +} from './index.constants';
I like how you organized these imports, but can we remove the code comments and extra whitespace?

If we ever need to add in things like codefencing for mmi, the comments might get in the way and as we use this component, automatic imports won't have context about them, which could make them confusing/out of date

2024-10-03 18:04 UTC, gambinish commented on app/components/Views/Settings/SecuritySettings/SecuritySettings.tsx
> +        <BatchAccountBalanceSettings />
Much prefer this pattern vs the callback pattern 👍

2024-10-03 18:07 UTC, gambinish submitted a review, later dismissed
Couple nits but LGTM ✅

2024-10-03 18:18 UTC, vinnyhoward commented on app/components/Views/Settings/SecuritySettings/SecuritySettings.tsx
> +        <BatchAccountBalanceSettings />
Saaame here!

2024-10-03 18:21 UTC, vinnyhoward commented on app/components/Views/Settings/BatchAccountBalanceSettings/index.tsx
> +} from './index.constants';
That is a good point. I think going forward I'll stop adding in the comments and white space because of the points made. But for now I'm going to leave it in favor of merging this in quickly. Its been open for awhile. I hope you don't mind

2024-10-03 18:32 UTC, EtherWizard33 approved these changes, later dismissed

2024-10-04 07:30 UTC, andreahaku approved these changes
LGTM

2024-10-04 13:48 UTC, EtherWizard33 approved these changes

2024-10-04 14:32 UTC, merged