feat(1702-4): ipfs gateway settings and display nft media settings components
MetaMask/metamask-mobile pull request #11381
Opened 2024-09-23 17:43 UTC by vinnyhoward

## **Description**

WIP

This PR is part of a series that breaks down the original [large PR #11127](https://github.com/MetaMask/metamask-mobile/pull/11127) into smaller, more manageable chunks. 

The `IPFSGateway` functionality and `DisplayNFtMedia` functionality are valuable beyond its original implementation. By converting it into a reusable component, we can:
1. Improve code maintainability
2. Reduce duplication
3. Enhance consistency across the application and ease of use

### Changes
- Extracted `IPFSGateway` and `DisplayNFTMedia` logic from its original location of `SecuritySettings` into separate component files
- Included new tests
- Updated the original screen to use the new components

### Impact
This refactored component will be used in:
- Its current original screen of `SecuritySettings`
- New screens coming from the enhanced onboarding settings [#1702](https://github.com/MetaMask/mobile-planning/issues/1702) that is currently under progress

## **Related issues**

Feature: [#1702](https://github.com/MetaMask/mobile-planning/issues/1702) 

## **Manual testing steps**

1. 
## **Screenshots/Recordings**

### **Before**

NA

### **After**

NA

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-27 06:20 UTC, brianacnguyen requested changes, later dismissed
a few minor comments + adding stories

2024-09-27 06:20 UTC, brianacnguyen commented on app/components/Views/Settings/DisplayNFTMediaSettings/index.tsx
> +// Third party dependencies
Can you add a story for each of these components as well?

2024-09-27 06:20 UTC, brianacnguyen commented on app/components/Views/Settings/IPFSGatewaySettings/index.types.ts
> +  label: string;
is it possible to provide some descriptions for these?

2024-10-03 17:19 UTC, andreahaku reviewed
just a few minor comments :)

2024-10-03 17:19 UTC, andreahaku commented on app/components/Views/Settings/IPFSGatewaySettings/index.tsx
> +    const { PreferencesController } = Engine.context;
take this destructure out of the function so that you can reuse it

2024-10-03 17:19 UTC, andreahaku commented on app/components/Views/Settings/IPFSGatewaySettings/index.tsx
> +        return { ...gateway, available };
you can simply do `return { ...gateway, available: false };`

2024-10-03 18:50 UTC, gambinish commented on app/components/Views/Settings/DisplayNFTMediaSettings/index.test.tsx
> +import { NFT_DISPLAY_MEDIA_MODE_SECTION } from './index.constants';
Same thing [here](https://github.com/MetaMask/metamask-mobile/pull/11368#discussion_r1786651543) do you think we can remove the code comment and extra whitespace here?

2024-10-04 07:31 UTC, andreahaku submitted a review, later dismissed
LGTM

2024-10-04 13:47 UTC, EtherWizard33 approved these changes, later dismissed

2024-10-04 15:44 UTC, andreahaku approved these changes
LGTM

2024-10-04 17:44 UTC, merged