feat: Add signature tracing
MetaMask/metamask-mobile pull request #11453
Opened 2024-09-26 08:11 UTC by OGPoyraz

## **Description**

- Adding `createTracingMiddleware` to start tracing for defined type of messages.
- Adding `trace` callback to `SignatureController`.
- End `Notification Display` trace after signature confirmation landed on users screen.

## **Related issues**

Fixes: https://github.com/MetaMask/mobile-planning/issues/1883

## **Manual testing steps**

1. Set `MM_SENTRY_DSN_DEV` to developer Sentry dsn, see the value here https://github.com/MetaMask/metamask-extension/blob/develop/.metamaskrc.dist
2. Go test-dapp in app, trigger and personal signature
3. If you used the mentioned dsn above, your `Signature` trace will appear on this link: https://metamask.sentry.io/traces/?project=273496&query=signature%3ATransaction&source=traces&statsPeriod=1h

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [X] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [X] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-09-26 09:30 UTC, pedronfigueiredo submitted a review, later dismissed

2024-09-26 09:39 UTC, vinistevam approved these changes, later dismissed

2024-09-26 11:47 UTC, jpuri approved these changes, later dismissed

2024-09-26 19:22 UTC, matthewwalsh0 requested changes

2024-09-26 19:22 UTC, matthewwalsh0 commented on app/components/Approvals/SignatureApproval/SignatureApproval.tsx
> +  useAsyncResult(async () => await endTrace({
Why do we need `useAsyncResult` here as `endTrace` isn't asynchronous?

2024-09-26 19:22 UTC, matthewwalsh0 commented on app/components/Approvals/SignatureApproval/SignatureApproval.tsx
> +    }), [approvalRequest?.requestData?.requestId]);
Is it worth defining a local variable such as `signatureRequestId`?

2024-09-26 19:22 UTC, matthewwalsh0 commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +        trace(
Maybe not in this PR, but I wonder if we'd avoid a lot of duplication by using a generic function for all the signing methods?

2024-09-30 10:09 UTC, OGPoyraz commented on app/components/Approvals/SignatureApproval/SignatureApproval.tsx
> +  useAsyncResult(async () => await endTrace({
That's right, fixed

2024-09-30 10:09 UTC, OGPoyraz commented on app/components/Approvals/SignatureApproval/SignatureApproval.tsx
> +    }), [approvalRequest?.requestData?.requestId]);
Done

2024-09-30 10:12 UTC, OGPoyraz commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +        trace(
I tried that in the beginning but it was looking load of changes so didn't proceed. I definitely agree that it's worth doing some cleaning up on these rpc methods.

2024-09-30 11:07 UTC, matthewwalsh0 approved these changes

2024-10-07 09:44 UTC, andreahaku reviewed
some optimisations suggested

2024-10-07 09:44 UTC, andreahaku commented on app/core/createTracingMiddleware/index.ts
> +
you can validate `id`and do an early return in case it's not valid:
```
if (typeof id !== 'string') {
      return next();
    }

2024-10-07 09:44 UTC, andreahaku commented on app/core/createTracingMiddleware/index.ts
> +
same thing for `traceName`:
```
if (!traceName) {
      return next();
    }

2024-10-07 09:44 UTC, andreahaku commented on app/core/createTracingMiddleware/index.ts
> +    if (traceName) {
you can parallelize trace calls as they are indipendent so to optimise response time:

```
const [traceContext] = await Promise.all([
      trace({
        name: traceName,
        id,
      }),
      trace({
        name: TraceName.Middleware,
        id,
        parentContext: req.traceContext,
      })
    ]);

    req.traceContext = traceContext;

2024-10-07 09:49 UTC, OGPoyraz commented on app/core/createTracingMiddleware/index.ts
> +
We still want this `trace` action to be called even if the `id` is not defined here.

2024-10-07 09:50 UTC, OGPoyraz commented on app/core/createTracingMiddleware/index.ts
> +    if (traceName) {
Unfortunately this doesn't work as we want, because subsequent `trace` call (second one) needs parent context to be settled.

2024-10-07 09:54 UTC, OGPoyraz commented on app/core/createTracingMiddleware/index.ts
> +
I like early returns but doing this will add duplication of `next` call. 

```
if(!traceName) {
  return next();
}

/// actions

next();
```

2024-10-07 10:07 UTC, andreahaku approved these changes
LGTM

2024-10-08 09:33 UTC, tommasini approved these changes

2024-10-08 09:47 UTC, merged