chore: Reorganize `PortfolioBalance`
MetaMask/metamask-mobile pull request #11520
Opened 2024-10-01 04:38 UTC by gambinish

## **Description**

Step 2 of token sorting is to move `PortfolioBalance` above the `TabView`. This PR introduces this UI change, since it can happen separately from the Token sorting task in order to keep PRs small and easy to review / get past CI.

## **Related issues**

Design: https://www.figma.com/design/aMYiscz

## **Manual testing steps**

## **Screenshots/Recordings**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-04 05:16 UTC, gambinish commented
Leaving a comment here to remember to address the following comments left on the origin PR here as a follow up:

https://github.com/MetaMask/metamask-mobile/pull/11471#discussion_r1784009013
https://github.com/MetaMask/metamask-mobile/pull/11471#discussion_r1784015687

2024-10-09 18:06 UTC, vinnyhoward commented on app/components/UI/Tokens/TokenList/PortfolioBalance/index.test.tsx
> +import React from 'react';
Adding new testes for portfolio, love it👍

2024-10-09 18:07 UTC, vinnyhoward approved these changes, later dismissed
LGTM✅

2024-10-11 08:11 UTC, salimtb approved these changes, later dismissed

2024-10-11 08:12 UTC, salimtb commented
LGTM ✅ great job !

2024-10-15 15:39 UTC, vinnyhoward approved these changes, later dismissed

2024-10-15 19:28 UTC, vinnyhoward submitted a review, later dismissed

2024-10-16 10:29 UTC, Daniel-Cross approved these changes, later dismissed
Looks good!

2024-10-16 16:03 UTC, salimtb submitted a review, later dismissed

2024-10-16 16:06 UTC, NicolasMassart requested changes

2024-10-16 16:06 UTC, NicolasMassart commented on app/components/Views/Wallet/__snapshots__/index.test.tsx.snap
Be careful this snapshot is actually rendering the error screen and not the expected feature!

2024-10-16 19:08 UTC, gambinish commented on app/components/Views/Wallet/__snapshots__/index.test.tsx.snap
Thanks for flagging this. I resolved this by only rendering `PortfolioBalance` when the `accountBalanceByChainId` resolves. Lmk if this works for you?

This looks like a very old unit test suite. `should render correctly` seems a bit generic, and also like the outdated unit testing naming convention, which isn't super specific. Should I create an issue to update this suite?

2024-10-17 20:56 UTC, NicolasMassart approved these changes

2024-10-17 21:50 UTC, salimtb approved these changes

2024-10-17 22:04 UTC, merged