fix: fix approve flow on swap
MetaMask/metamask-mobile pull request #11532
Opened 2024-10-01 13:19 UTC by sahar-fehri

## **Description**

PR to fix the approve flow when users swap tokens.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/10834

## **Manual testing steps**

1. Switch to base network
2. Swap WETH against any other token, exp USDC
3. See approval screen; it should have the buttons enabled and you should be able to see token icon and spending cap

## **Screenshots/Recordings**

### **Before**

https://github.com/user-attachments/assets/d8be6306-be74-4c6c-8463-567f35ee891e

### **After**

https://github.com/user-attachments/assets/8382cc83-e4e7-42ce-b913-fcac7e906d4b

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-01 13:21 UTC, sahar-fehri commented on app/components/Views/confirmations/components/ApproveTransactionReview/index.js
> +    const contract = tokenList[to];
The reason why this error was triggered with WETH initially is because the address of Weth is `0x4200000000000000000000000000000000000006` and its the same address when you apply `safeToChecksumAddress`;
For any other token; exp DAI; the contract would be `undefined` even though it exists in `tokenList` and the code would go into if(!contract) and fetch details.

2024-10-01 14:38 UTC, sahar-fehri commented on app/components/Views/confirmations/components/ApproveTransactionReview/index.js
> +    const contract = tokenList[to];
Maybe we can do sth like this too
`const contract = tokenList[to] || tokenList[safeToChecksumAddress (to)]`
Still not sure what was the case of adding safeToChecksumAddress in the first place

2024-10-07 13:21 UTC, pedronfigueiredo approved these changes, later dismissed

2024-10-07 14:24 UTC, andreahaku submitted a review, later dismissed
LGTM

2024-10-07 14:46 UTC, tommasini commented on app/components/Views/confirmations/components/ApproveTransactionReview/index.js
> +    const contract = tokenList[to];
This maybe was something that was missed when migrating the token list endpoint, what is not making super sense to me because I believe the change was only to no target the coin gecko endpoint directly. Can we check with the api team if there was any change around this?
I will approve it!

2024-10-07 14:46 UTC, tommasini approved these changes, later dismissed

2024-10-09 13:00 UTC, andreahaku submitted a review, later dismissed
LGTM

2024-10-09 13:17 UTC, NicolasMassart requested changes
Tests are missing

2024-10-09 13:42 UTC, pedronfigueiredo submitted a review, later dismissed

2024-10-09 18:54 UTC, davibroc submitted a review, later dismissed
I tested it and it works now

2024-10-10 13:25 UTC, NicolasMassart commented on app/components/Views/confirmations/components/ApproveTransactionReview/index.test.tsx
> +  it('render matches snapshot when tokenList is defined', () => {
```suggestion
  it('"Approve" button enabled when tokenList is defined', () => {
```

2024-10-10 13:25 UTC, NicolasMassart commented on app/components/Views/confirmations/components/ApproveTransactionReview/index.test.tsx
> +  it('render matches snapshot when tokenList is defined', () => {
S: Add another similar test but to check approve is disabled when no tokens in list. and call it `"Approve" button is disabled when no tokenList`

2024-10-10 14:57 UTC, sahar-fehri commented on app/components/Views/confirmations/components/ApproveTransactionReview/index.test.tsx
> +  it('render matches snapshot when tokenList is defined', () => {
updated the tests 🙏

2024-10-10 15:12 UTC, NicolasMassart reviewed
Only one comment on the second test, make sure you are not adding useless actions or missing testing them

2024-10-10 15:15 UTC, sahar-fehri commented on app/components/Views/confirmations/components/ApproveTransactionReview/index.test.tsx
> +    fireEvent.press(getByTestId('Confirm'));
Oh i ve already removed it in here [3cb2d4d](https://github.com/MetaMask/metamask-mobile/pull/11532/commits/3cb2d4daa9dfcb5e3d5e8e23d69d1cdcece19a1a) before checking your comment ^^"

2024-10-10 15:31 UTC, NicolasMassart approved these changes
Looks good to me.
Thanks for all the changes you made and you patience!

2024-10-10 16:04 UTC, merged