fix: Migrate Login view to use design system components (and fix blur error)
MetaMask/metamask-mobile pull request #11551
Opened 2024-10-01 18:13 UTC by kylanhurt

## **Description**

The purpose of this task is to fix an error that keeps occurring where a `TextField` ref is `null` when the `blur` method on it is executed. 

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/10805

## **Manual testing steps**

The best way to make sure this bug is fixed will be to check the error logs in Sentry.

## **Screenshots/Recordings**

n/a

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-04 05:16 UTC, brianacnguyen submitted a review, later dismissed

2024-10-04 05:16 UTC, brianacnguyen commented
Can you provide a screenshot?

2024-10-07 23:48 UTC, chrisleewilcox requested changes
The keypad is now being displayed by default on the Login view.  This is causing a failure with spec `./e2e/specs/settings/delete-wallet.spec.js` trying to tap 'Reset Wallet' button link but it's now blocked by the keypad.

Can we adjust the changes on Login view to not show the keypad by default when navigating/loading Login view?  I have no clue what the exact change that is causing this.
[
![Screenshot_1728340706](https://github.com/user-attachments/assets/abbd717b-73c3-4601-8f79-8b852c0b4558)
](url)

2024-10-08 16:06 UTC, brianacnguyen submitted a review, later dismissed

2024-10-08 17:21 UTC, wachunei commented on app/component-library/components/Form/TextField/foundation/Input/Input.tsx
> +  autoFocus = true,
I have a concern with `true` being the default value: what is the behavior when there are more than 1 `Input` components with `autoFocus`?

2024-10-08 17:22 UTC, kylanhurt commented on app/component-library/components/Form/TextField/foundation/Input/Input.tsx
> +  autoFocus = true,
That is a fair point. Thoughts, @brianacnguyen

2024-10-08 17:31 UTC, kylanhurt commented on app/component-library/components/Form/TextField/foundation/Input/Input.tsx
> +  autoFocus = true,
@wachunei Now that I think of it, they were already autofocusing before so technically that shouldn't change any behavior

2024-10-08 17:33 UTC, wachunei commented on app/component-library/components/Form/TextField/foundation/Input/Input.tsx
> +  autoFocus = true,
I'm seeing that in `TextField` the default is `false`, so the default `true` would only apply for `Input` components being directly used. https://github.com/MetaMask/metamask-mobile/blob/253449c5d066d772337af6d38b923a37b2f01c54/app/component-library/components/Form/TextField/TextField.tsx#L30

2024-10-08 17:34 UTC, wachunei commented on app/components/Views/Login/index.js
> +                  autoFocus={false}
This is not needed since the default is false already https://github.com/MetaMask/metamask-mobile/blob/253449c5d066d772337af6d38b923a37b2f01c54/app/component-library/components/Form/TextField/TextField.tsx#L30

2024-10-09 22:23 UTC, wachunei commented on app/component-library/components/Form/TextField/foundation/Input/Input.tsx
> +  autoFocus = true,
> they were already autofocusing
oh right, the prop is set to true 😅

2024-10-10 00:54 UTC, kylanhurt commented on app/components/Views/Login/index.js
> +                  autoFocus={false}
Removed!

2024-10-10 01:39 UTC, kylanhurt commented
> Can you provide a screenshot?

Side by side comparison (before on left, after on right)
![image](https://github.com/user-attachments/assets/d1ff4244-c2a6-4d89-beb0-f7198fa02d01)

2024-10-10 18:46 UTC, chrisleewilcox approved these changes
LGTM

2024-10-11 06:04 UTC, brianacnguyen approved these changes
LGTM. Thank you for this!

2024-10-18 17:34 UTC, Daniel-Cross approved these changes

2024-10-18 18:54 UTC, darkwing approved these changes
Looks good!  Nice work!

2024-10-18 19:07 UTC, merged