fix: ledger sign message screen, legacy account with legacy path will push balance information outside the border of screen.
MetaMask/metamask-mobile pull request #11550
Opened 2024-10-01 18:11 UTC by dawnseeker8

## **Description**
When import a ledger legacy account in Metamask, and user go to click `Personal Sign` . sometimes the balance is out of border of the personal sign screen, please see the attached screen image for detail.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Install MM
2. Recover from SRP
3. Add Ledger hardware wallet and connect Ledger 2x account
4. Launch MM test dapp
5. Connect Ledger legacy account on test dapp
6. Sign Permit with account

## **Screenshots/Recordings**

### **Before**
![image](https://github.com/user-attachments/assets/1c4173e4-52ad-4304-8306-a0f54bf42ad4)

### **After**
![image](https://github.com/user-attachments/assets/84f41566-74ee-4026-83bc-c80f028c7cb8)

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-08 16:04 UTC, brianacnguyen requested changes
Do you have a figma link for this? the margin change may not be approved by design

2024-10-11 08:38 UTC, dawnseeker8 commented
> Do you have a figma link for this? the margin change may not be approved by design

I am waiting for @eriknson to approve on the layout change.

2024-10-14 13:47 UTC, SayaGT commented
LGTM! We can go ahead with these changes as they leverage an existing pattern. These designs will soon be replaced with the new confirmation designs. You can find the [relevant Figma here](https://www.figma.com/design/mnEDOgCGH6Jyqh49pncIvh/Consentful-experience-for-token-allowances-(mobile)?node-id=1903-6483&t=KImR58H4nY9Eli8W-1).

2024-10-15 15:44 UTC, brianacnguyen approved these changes

2024-10-16 08:49 UTC, merged