feat: STAKE-824: [FE] build staking input confirmation screen
MetaMask/metamask-mobile pull request #11605
Opened 2024-10-03 15:23 UTC by Matt561

## **Description**

This PR adds the staking confirmation screen with some mock data being used temporarily. 

### Change List
- Add staking confirmation screen.
- Connect existing `<StakeInputView />` to staking confirmation screen when user enters valid amount to stake.

## **Related issues**
Ticket: [FE] Build staking input confirmation screen - ([link](https://consensyssoftware.atlassian.net/browse/STAKE-824))
Figma Designs - [link](https://www.figma.com/design/1c0Y9jDJe6p0j82jydJDcs/Mobile-Staking?node-id=2979-22435&m=dev)

## **Manual testing steps**

1. Add `export MM_POOLED_STAKING_UI_ENABLED=true` to your `.js.env` file.
2. Click on Ethereum In the token list page
3. Scroll down a bit and click "Stake more". This should open the stake input view (not related to this PR)
4. Enter a valid amount to stake and click "Confirm"
5. You should be redirected to a staking confirmation screen. The screen should display the amount to stake in `wETH` and Fiat.

## **Screenshots/Recordings**

### **Before**

Nothing would happen after clicking "Confirm" on the stake input view. This screen is new.

### **After**

https://github.com/user-attachments/assets/84ea4c52-50c5-48c3-8077-2c2e8a92bf21

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-03 16:08 UTC, Matt561 commented
The `Interacting with` row on the confirmation screen has been updated as per this morning's design updates

### Screenshot

<img width="306" alt="image" src="https://github.com/user-attachments/assets/c756401a-740e-4b2b-ba60-ccaf4e02f59b">

2024-10-04 21:01 UTC, amitabh94 reviewed
Left some comments and suggestions . There might be some open questions related to how we are displaying gas fee values. They may not be in scope for this PR but raising them for awareness. 

Overall it looks clean and good . I was wondering if we can separate out the KeyValue changes in a separate PR if you want but I am okay either way . 

Good work on separating out components and tests.Looks like great test coverage on the PR.

2024-10-07 17:27 UTC, Matt561 commented on app/component-library/components-temp/KeyValueRow/KeyValueRow.types.ts
> +  text: string | ReactNode;
I renamed this to `content` the changes are in the KeyValueRow PR [here](https://github.com/MetaMask/metamask-mobile/pull/11660).

2024-10-07 17:28 UTC, Matt561 commented on locales/languages/en.json
> +    "estimated_annual_reward": "Est. annual Rewards",
I prefer this too. I was matching what was seen in the designs here.

2024-10-07 17:30 UTC, Matt561 commented on app/components/UI/Stake/components/StakingConfirmation/AccountTag/AccountTag.types.ts
> +  address: string;
Sure 😄 I originally did this but thought that it would be implied with the component name.

E.g. 
`<AccountTag address="0x1" name="Account 1" />`

2024-10-07 21:44 UTC, Matt561 commented on app/components/UI/Stake/Views/StakeConfirmationView/StakeConfirmationMockData.ts
Sure. I was following the pattern I setup earlier of placing the mock data in a separate file. I'll place it back in the view file and delete this mock data file.

2024-10-07 21:48 UTC, Matt561 commented on app/components/UI/Stake/Views/StakeConfirmationView/StakeConfirmationMockData.ts
> +export const MOCK_STAKING_REVIEW_DATA = {
Nice! Thank you

2024-10-07 21:54 UTC, Matt561 commented on app/components/UI/Stake/components/StakingConfirmation/AmountHeader/AmountHeader.types.ts
> +  wei: string;
Do you have some examples in mind? My aim with this component was to have a generic way to display an amount of ETH and fiat. 

A name too specific like `weiToStake` would make this more confusing when it's used in the unstake and claim screens.

2024-10-07 22:04 UTC, Matt561 commented
> Left some comments and suggestions . There might be some open questions related to how we are displaying gas fee values. They may not be in scope for this PR but raising them for awareness.
> 
> Overall it looks clean and good . I was wondering if we can separate out the KeyValue changes in a separate PR if you want but I am okay either way .
> 
> Good work on separating out components and tests.Looks like great test coverage on the PR.

The KeyValueRow changes have been broken out into a separate PR - https://github.com/MetaMask/metamask-mobile/pull/11660 👍

2024-10-07 22:30 UTC, amitabh94 commented on app/components/UI/Stake/components/StakingConfirmation/AmountHeader/AmountHeader.types.ts
> +  wei: string;
just `amountWei`

2024-10-08 16:08 UTC, brianacnguyen requested changes
Can you attach the figma link to the description? I want to double check the implementation against design

2024-10-08 16:30 UTC, Matt561 commented
> Can you attach the figma link to the description? I want to double check the implementation against design

Here's the [link](https://www.figma.com/design/1c0Y9jDJe6p0j82jydJDcs/Mobile-Staking?node-id=2979-22435&m=dev). I've also added it to the PR description.

2024-10-09 15:34 UTC, brianacnguyen commented on app/components/UI/Stake/components/StakingConfirmation/AmountHeader/AmountHeader.tsx
> +      <BadgeWrapper
is it possible for you to use the Header component to build this?

2024-10-09 15:35 UTC, brianacnguyen commented on app/components/UI/Stake/Views/StakeConfirmationView/StakeConfirmationView.styles.ts
> +      paddingTop: 8,
was there a reason why the padding got split between this main container and the header?

2024-10-09 15:36 UTC, brianacnguyen commented on app/components/UI/Stake/Views/StakeConfirmationView/StakeConfirmationView.styles.ts
> +      height: '100%',
percentage is kinda dangerous to use with mobile. is it possible to use Dimension instead?

2024-10-09 15:37 UTC, brianacnguyen commented on app/components/UI/Stake/Views/StakeConfirmationView/StakeConfirmationView.tsx
> +};
were these mock data intentionally kept in for the pr?

2024-10-09 15:38 UTC, brianacnguyen commented on app/components/UI/Stake/components/StakingConfirmation/AccountHeaderCard/AccountHeaderCard.styles.ts
> +      borderBottomLeftRadius: 8,
are these resets needed?

2024-10-09 15:42 UTC, brianacnguyen requested changes
A few changes requested

2024-10-09 16:02 UTC, Matt561 commented on app/components/UI/Stake/Views/StakeConfirmationView/StakeConfirmationView.tsx
> +};
Yes

2024-10-09 16:03 UTC, Matt561 commented on app/components/UI/Stake/components/StakingConfirmation/AccountHeaderCard/AccountHeaderCard.styles.ts
> +      borderBottomLeftRadius: 8,
Yes

2024-10-15 16:16 UTC, Matt561 commented on app/components/UI/Stake/Views/StakeConfirmationView/StakeConfirmationView.styles.ts
> +      height: '100%',
I was able to replace this is `flex: 1`.

2024-10-15 16:22 UTC, Matt561 commented on app/components/UI/Stake/Views/StakeConfirmationView/StakeConfirmationView.styles.ts
> +      paddingTop: 8,
By header do you mean the navbar of the `<AmountHeader />`? I'm not sure I understand.

1. For Navbar, I don't see any padding being set.
2. For the `<AmountHeader />` it has its own default padding so that it can be reused in other confirmation screens and look consistent.

2024-10-15 16:33 UTC, Matt561 commented on app/components/UI/Stake/components/StakingConfirmation/AmountHeader/AmountHeader.tsx
> +      <BadgeWrapper
Do you mean the `<HeaderBase>` component? I don't see a component-library component called `<Header />`. If you're talking about `<HeaderBase>` I can't use it directly as is without basically recreating the styles I already have which wouldn't be a productive use of time.

2024-10-15 18:31 UTC, amitabh94 submitted a review, later dismissed
LGTM!

2024-10-15 19:05 UTC, brianacnguyen commented on app/components/UI/Stake/components/StakingConfirmation/AmountHeader/AmountHeader.tsx
> +      <BadgeWrapper
The `HeaderBase` already built in the styles needed for all Headers (alignment, text styles, etc.), so you wouldnt need to recreate the styles. You only need to pass in the BadgeWrapper and and title string.
And it would be a productive use of time, since this header aligns with design's header, so if the header's design changes in the future, this would be changed on the systematic level.
It's similar to styling a raw react native button vs using design system button. It may seem like not a productive use of time to refactor styled raw react native button to design system button, but it helps with scalability. the moment that the design system button changes (like for brand evolution for example), the styled raw react native button will become out of date with the rest of the application

2024-10-15 19:07 UTC, brianacnguyen commented on app/components/UI/Stake/Views/StakeConfirmationView/StakeConfirmationView.styles.ts
> +      paddingTop: 8,
can you show me the `AmountHeader` in other confirmation screens with the 8px paddings?

2024-10-15 19:11 UTC, brianacnguyen commented on app/components/UI/Stake/components/StakingConfirmation/AmountHeader/AmountHeader.tsx
> +      <BadgeWrapper
Actually upon looking at the design and back at your code, I realized that you named the `AmountConfirmation` as `Header`. In the design, we would consider Stake/Unstake/Claim to be the Header, not the `AmountConfirmation`. You can definitely keep the styling as is, but can you update the naming to not be `Header` to reduce confusions?

2024-10-15 19:11 UTC, brianacnguyen requested changes
Change `AmountHeader` to another name to reduce confusions

2024-10-15 21:07 UTC, amitabh94 approved these changes

2024-10-15 22:48 UTC, brianacnguyen approved these changes

2024-10-15 22:48 UTC, brianacnguyen commented
Approved, though I'd suggest to update the AccountHeaderCard to not include Header

2024-10-16 00:20 UTC, merged