DO NOT MERGE - feat: STAKE-841 build unstake review confirmation screen
MetaMask/metamask-mobile pull request #11611
Opened 2024-10-03 20:21 UTC by Matt561

## DO NOT MERGE - Depends on prerequisite [PR](https://github.com/MetaMask/metamask-mobile/pull/11605)

## **Description**
Adds the unstaking confirmation screen. The screen is temporarily using mock data for certain elements.

## **Related issues**

- STAKE-841: [FE] Build unstake review confirmation screen - ([link](https://consensyssoftware.atlassian.net/browse/STAKE-841))

## **Manual testing steps**

1. Add `export MM_POOLED_STAKING_UI_ENABLED=true` to your `.js.env` file.
2. Click on Ethereum In the token list page
3. Click on "Staked Ethereum" Balance row
4. The Unstaking Confirmation screen should appear.

**Note:** Attaching the unstaking confirmation screen to the "Staked Ethereum" asset row is temporary in order to view the screen. The unstaking confirmation screen will be added to the unstaking flow when it's dependent screen(s) have been completed.

## **Screenshots/Recordings**

### **Before**

N/A - This is a new screen

### **After**

https://github.com/user-attachments/assets/bd1919d3-dcc6-4443-b08c-7944e183914c

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-21 16:38 UTC, Matt561 commented
> ## **Description**
> Adds the unstaking confirmation screen. The screen is temporarily using mock data for certain elements.
> 
> ## **Related issues**
> * STAKE-841: [FE] Build unstake review confirmation screen - ([link](https://consensyssoftware.atlassian.net/browse/STAKE-841))
> 
> ## **Manual testing steps**
> 1. Add `export MM_POOLED_STAKING_UI_ENABLED=true` to your `.js.env` file.
> 2. Click on Ethereum In the token list page
> 3. Click on "Staked Ethereum" Balance row
> 4. The Unstaking Confirmation screen should appear.
> 
> **Note:** Attaching the unstaking confirmation screen to the "Staked Ethereum" asset row is temporary in order to view the screen. The unstaking confirmation screen will be added to the unstaking flow when it's dependent screen(s) have been completed.
> 
> ## **Screenshots/Recordings**
> ### **Before**
> N/A - This is a new screen
> 
> ### **After**
>  stake-841-build-unstake-review-confirmation-screen-after.mov 
> ## **Pre-merge author checklist**
> * [ ]  I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
> * [ ]  I've completed the PR template to the best of my ability
> * [ ]  I’ve included tests if applicable
> * [ ]  I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
> * [ ]  I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
> 
> ## **Pre-merge reviewer checklist**
> * [ ]  I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
> * [ ]  I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

I've removed the "Gas fee" card from the review screen

<img width="360" alt="image" src="https://github.com/user-attachments/assets/4d1d5b14-4804-4b0a-a7b9-2752577b0f50">

2024-10-21 16:50 UTC, amitabh94 requested changes
Some minor changes required due to updated components and hooks .

2024-10-21 16:50 UTC, amitabh94 commented on app/components/UI/Stake/Views/InputView/StakeInputView.tsx
> +import styleSheet from './StakeInputView.styles';
Seeing error here for import path.

2024-10-21 16:50 UTC, amitabh94 commented on app/components/UI/Stake/Views/InputView/StakeInputView.tsx
> +import { getStakeInputNavbar } from '../../../Navbar';
Seeing error here for import paths.

2024-10-21 16:50 UTC, amitabh94 commented on app/components/UI/Stake/components/Confirmation/EstimatedGasFeeTooltipContent/EstimatedGasFeeTooltipContent.test.tsx
Do we need gas components for confirmation screens now ?

2024-10-21 16:50 UTC, amitabh94 commented on app/components/UI/Stake/Views/InputView/StakeInputView.tsx
> +  const { balance, balanceBN, balanceFiatNumber } = useBalance();
Need to fix error on renamed properties from the hook .

2024-10-22 16:52 UTC, Matt561 commented on app/components/UI/Stake/components/Confirmation/EstimatedGasFeeTooltipContent/EstimatedGasFeeTooltipContent.test.tsx
No we don't. I was leaving this in in case we wanted to use it later but I can delete it.

2024-10-23 14:50 UTC, brianacnguyen commented
can you provide the design link for this? The bottom sheet spacing after clicking on the info icon next to estimated changes seems HUGE

2024-10-23 14:51 UTC, brianacnguyen reviewed
can you provide the design link for this? The bottom sheet spacing after clicking on the info icon next to estimated changes seems HUGE

2024-10-23 15:07 UTC, brianacnguyen submitted a review, later dismissed

2024-10-23 17:03 UTC, amitabh94 reviewed
Nice work! Very minor nitpicks but otherwise LGTM!

2024-10-23 17:03 UTC, amitabh94 submitted a review, later dismissed

2024-10-23 17:16 UTC, amitabh94 approved these changes

2024-10-23 17:42 UTC, merged