Feat/stake 799
MetaMask/metamask-mobile pull request #11668
Opened 2024-10-07 20:50 UTC by siibars

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-08 15:58 UTC, siibars commented on app/core/redux/slices/stake/index.ts
> +     * Updates the local accounts state based on external notifications source.
fix : incorrect description

2024-10-08 17:20 UTC, Matt561 commented on app/components/UI/Stake/Views/InputView/StakeInputView.tsx
> +    setAmountBN,
Subjective: adding the denomination to the name might make it easier to understand and work with. I say this because in this codebase the variable `balance` is sometimes formatted in different ways. I've seen `balance` formatted like

- `25000000000000000` (wei string)
- `0.025` (ETH string)
- `0.025 ETH` (formatted ETH string with suffix)

```suggestion
    amountEth,
    setAmountEth,
    amountWei,
    setAmountWei,
```

2024-10-08 17:20 UTC, Matt561 commented on app/components/UI/Stake/Views/InputView/StakeInputView.tsx
> +      });
Thank you for adding this example!

2024-10-08 17:20 UTC, Matt561 commented on app/components/UI/Stake/sdk/index.tsx
> +  // setCurrency: (currency: string) => void;
Let's remove this commented code if it's not being used.

2024-10-08 17:20 UTC, Matt561 commented on app/components/UI/Stake/sdk/index.tsx
> +    <STAKEContext.Provider value={stakeContextValue}>
Is using all uppercase letters for the context name a common convention? Should we rename this to `StakeContext`?

2024-10-08 17:20 UTC, Matt561 commented on app/reducers/stake/index.ts
> +export const selectedAddressSelector: (
Do we need `selectedAddressSelector` if it's directly calling `selectSelectedInternalAccountChecksummedAddress`? 

As far as I can tell, we aren't doing anything extra in this selector.

2024-10-09 16:37 UTC, amitabh94 requested changes
This PR needs some more work in terms of accessing SDK methods and state management. 
Since we already have the package imported, it should be fairly simple to just call those methods by instantiating the sdk without adding a lot of context to it . 

I would recommend breaking the analytics part out of this PR and adding tests for those in a separate PR which we can use.

@jclancy93 It might be good for you to have a look at this PR as well and see if I might be missing anything or if there is a gap in my understanding.

2024-10-09 16:37 UTC, amitabh94 commented on app/components/UI/Stake/sdk/index.tsx
> +export const StakeSDKProvider: FC<PropsWithChildren<StakeProviderProps>> = ({
Why do we have local states combined with SDK ? Is the expectation to keep on adding all local states in this file?

I would keep these state along with components that are using them and have a separate hook like useStakingInput to be used in components.

2024-10-09 16:37 UTC, amitabh94 commented on app/components/UI/Stake/sdk/index.tsx
> +  const setAmountCallback = useCallback(
Same comment as above  as to why do we think that we need to have them in redux and dispatch actions to update them ?

There are many posts that talk about when to use local states vs redux states. I found [this](https://stackoverflow.com/questions/41584647/when-do-i-choose-react-state-vs-redux-store) on a simple google search but there maybe more exhaustive resources that can explain this better.

2024-10-09 16:37 UTC, amitabh94 commented on app/components/UI/Tokens/index.test.tsx
> +    expect(trackEvent).toHaveBeenNthCalledWith(
Thank you for adding test for the already added event. It would be good to add tests for the new staking events that you have added as well in this PR.

2024-10-09 16:37 UTC, amitabh94 commented on app/core/redux/slices/stake/index.ts
> +export interface StakeState {
We don't need these as initial states. 

[This](https://github.com/consensys-vertical-apps/metamask-portfolio/blob/66ac071705a1c8c87124e95a45f6eb09f460e644/src/experiences/stake/slices/index.ts#L107) might be the only initial state we need .

2024-10-10 13:01 UTC, siibars commented on app/core/redux/slices/stake/index.ts
> +     * Updates the local accounts state based on external notifications source.
done

2024-10-10 13:05 UTC, siibars commented on app/components/UI/Stake/Views/InputView/StakeInputView.tsx
> +    balanceFiatNumber,
yes for this useBalance.balanceWei would be used

2024-10-10 13:06 UTC, siibars commented on app/components/UI/Stake/Views/InputView/StakeInputView.tsx
> +    setAmountBN,
done

2024-10-10 13:08 UTC, siibars commented on app/reducers/stake/index.ts
> +export const selectedAddressSelector: (
yup removed done

2024-10-10 13:08 UTC, siibars commented on app/components/UI/Stake/sdk/index.tsx
> +  // setCurrency: (currency: string) => void;
yup done

2024-10-10 13:09 UTC, siibars commented on app/components/UI/Stake/Views/InputView/StakeInputView.tsx
> +      });
in the end I moved all the analytics stuff in a dedicated pr https://github.com/MetaMask/metamask-mobile/pull/11732

2024-10-11 07:57 UTC, siibars commented on app/components/UI/Stake/Views/InputView/StakeInputView.tsx
> +    balanceBN,
yes done

2024-10-11 08:15 UTC, siibars commented on app/components/UI/Stake/Views/InputView/StakeInputView.tsx
> +        selected_provider: 'consensys',
I have moved the analytic stuff in a dedicated pr so lets continue the convo there.
To answer your question, it's likely that we will use the staking-event [segment staking library](https://github.com/Consensys/segment-schema/blob/0638df24dd62ad35a1898656e1c6e3613d130de9/libraries/events/metamask-staking/stake-input-clicked.yaml#L15) in mm mobile and it's a required property atm.
cheers

2024-10-11 08:16 UTC, siibars commented on app/components/UI/Tokens/index.test.tsx
> +    expect(trackEvent).toHaveBeenNthCalledWith(
I have moved the analytic stuff in a separate pr.

2024-10-11 14:04 UTC, siibars commented on app/components/UI/Stake/Views/InputView/StakeInputView.tsx
> +    currentCurrency,
hi if we contextualize those state variables in the stakeContext (which is available in all components under a stakeProvider). This allows us to share data between (StakeInputView, UnStakeInputView or any upcoming component) avoid duplication make sense for (balances, conversionRate, estimatedAnnualRewards)  but less for amounts since stake/unstake amounts are differents.

2024-10-11 14:50 UTC, siibars commented on app/actions/stake/index.ts
ok done

2024-10-11 14:52 UTC, siibars commented on app/components/UI/Stake/sdk/index.tsx
> +export const StakeSDKProvider: FC<PropsWithChildren<StakeProviderProps>> = ({
hi @amitabh94  pretty important comment & answer imo,
I have removed all those state variables, I shared more details [here](https://github.com/MetaMask/metamask-mobile/pull/11668#discussion_r1797009755) on why we may want to contextualize some of them, have a peek and let me know what you think.
cheers

2024-10-11 14:52 UTC, siibars commented on app/components/UI/Stake/sdk/index.tsx
> +  const setAmountCallback = useCallback(
redux removed done

2024-10-11 14:53 UTC, siibars commented on app/core/redux/slices/stake/index.ts
> +export interface StakeState {
removed done

2024-10-11 14:54 UTC, siibars commented on app/components/UI/Stake/Views/InputView/StakeInputView.tsx
> +    currentCurrency,
@Matt561 closing this comment as I removed them but would love to continue the discussion on contextualizing some state variable in the stake context.

2024-10-11 14:54 UTC, siibars commented on app/components/UI/Stake/sdk/index.tsx
> +export const StakeSDKProvider: FC<PropsWithChildren<StakeProviderProps>> = ({
closing but lets continue the discussion off gh

2024-10-11 14:56 UTC, siibars commented on app/actions/stake/index.ts
removed done

2024-10-15 13:31 UTC, amitabh94 requested changes
Requesting some changes due to changes in sdk package and some other minor comments.

2024-10-15 13:31 UTC, amitabh94 commented on app/components/UI/Stake/sdk/index.tsx
> +import { PooledService, ProtocolType, StakeSdk } from '@metamask/stake-sdk';
Need to update the names based on latest changes in the SDK.

2024-10-15 15:59 UTC, siibars commented on app/core/Analytics/MetaMetrics.events.ts
good catch yes

2024-10-15 15:59 UTC, siibars commented on app/components/UI/Stake/sdk/index.tsx
> +export const SDK = StakeSdk.create();
yes done

2024-10-15 16:00 UTC, siibars commented on app/components/UI/Stake/sdk/index.tsx
> +  stakeCurrency?: string;
yes indeed done

2024-10-15 16:00 UTC, siibars commented on app/components/UI/Stake/sdk/index.tsx
> +import { PooledService, ProtocolType, StakeSdk } from '@metamask/stake-sdk';
done

2024-10-17 07:44 UTC, siibars commented on app/components/UI/Stake/sdk/index.tsx
test added done

2024-10-17 08:45 UTC, siibars commented
I have read the CLA Document and I hereby sign the CLA

2024-10-17 14:45 UTC, amitabh94 reviewed
Some minor comments but otherwise LGTM.

2024-10-17 14:45 UTC, amitabh94 commented on app/core/Analytics/MetaMetrics.events.ts
> +  // Stake
This probably should be in the other analytics PR.

2024-10-17 14:45 UTC, amitabh94 commented on app/components/UI/Stake/hooks/useStakeContext.ts
can we rename this file to useStakeSdkContext?

2024-10-17 14:45 UTC, amitabh94 commented on app/components/UI/Stake/sdk/UseSdkProvider.test.tsx
Can we rename this file to stakeSdkProvider.test.tsx to match the main file ?

2024-10-17 14:45 UTC, amitabh94 commented on package.json
> +    "@metamask/stake-sdk": "^0.2.11",
can we use the latest 0.2.12?

2024-10-17 15:18 UTC, siibars commented on app/core/Analytics/MetaMetrics.events.ts
> +  // Stake
it's ok atm

2024-10-17 15:20 UTC, siibars commented on package.json
> +    "@metamask/stake-sdk": "^0.2.11",
Unfortunately lot of types export changes. can help to do that once merge, one type export from the stake so lets that when its done

2024-10-17 15:24 UTC, siibars commented on app/components/UI/Stake/sdk/UseSdkProvider.test.tsx
feel free to rename any file the intial name are poorly chosen  I admit

2024-10-17 15:24 UTC, amitabh94 submitted a review, later dismissed

2024-10-17 15:25 UTC, Matt561 submitted a review, later dismissed

2024-10-17 16:16 UTC, tommasini commented on app/components/UI/Stake/Views/StakeInputView/StakeInputView.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
I'm not sure a navigation needs to be wrapped on a useCallback, since it's not an high resources computational function, we could remove the useCallback, and also the disable of eslint

2024-10-17 16:18 UTC, tommasini commented on app/components/UI/Stake/sdk/stakeSdkProvider.tsx
> +  // from react state
NIT: I think this comment was forgotten, is yes can we remove it?

2024-10-17 16:18 UTC, siibars commented on app/components/UI/Stake/Views/StakeInputView/StakeInputView.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
hi, the eslint react-hooks/exhaustive-deps exclude comment is only about the sdkService being added in the dependency list and not used yet, but will as soon as this pr is merged

2024-10-17 16:19 UTC, tommasini commented on app/components/UI/Stake/sdk/UseSdkProvider.test.tsx
> +import {
NIT: This file is testing the hook `useSdkProvider`, but it's Pascal Case, can we re write it in camel?

2024-10-17 16:20 UTC, siibars commented on app/components/UI/Stake/sdk/stakeSdkProvider.tsx
> +  // from react state
good catch removed

2024-10-17 20:00 UTC, siibars commented on app/components/UI/Stake/sdk/UseSdkProvider.test.tsx
> +import {
yes good catch done

2024-10-17 23:12 UTC, cortisiko approved these changes
✅ ✅

2024-10-17 23:40 UTC, Matt561 approved these changes

2024-10-18 08:07 UTC, merged