test: Refactor e2e Swap test to use Tenderly Virtual TestNets
MetaMask/metamask-mobile pull request #11670
Opened 2024-10-07 21:39 UTC by davibroc

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-09 08:40 UTC, Andepande submitted a review, later dismissed
LGTM

2024-10-09 21:55 UTC, cortisiko requested changes
Great work @davibroc ! I Left a few comments. You should also blacklist all requests made to tenderly virtual testnet (This regex would suffice that: `.*rpc.vnet.tenderly.co/.*`) as detox will wait until the requests are resolved before continuing test execution. I say this because, in some instances, this introduced performance issues for our tests.

2024-10-09 21:55 UTC, cortisiko commented on e2e/specs/swaps/swap-action-regression.spec.js
> +    await Tenderly.addFunds( CustomNetworks.Tenderly.Mainnet.providerConfig.rpcUrl, wallet.address);
Can we fund the wallet used in the test instead of funding a private key and going through the import flow before the test starts? https://github.com/MetaMask/metamask-mobile/blob/main/e2e/fixtures/fixture-builder.js#L138 << is the wallet address in case you need it

2024-10-09 21:55 UTC, cortisiko commented on e2e/specs/swaps/swap-action-regression.spec.js
> +    await Tenderly.addFunds( CustomNetworks.Tenderly.Mainnet.providerConfig.rpcUrl, wallet.address);
Also this step can be in the beforeAll hook

2024-10-09 21:55 UTC, cortisiko commented on e2e/specs/swaps/swap-action-smoke.spec.js
> +    ${'native'}$     |${'.1 '}  | ${'ETH'}          | ${'USDC'}       | ${CustomNetworks.Tenderly.Optimism}
How about switching the order here? Put the mainnet swaps together? How about using Linea here instead of Optimism. You can use optimism for the regression tests

2024-10-09 21:55 UTC, cortisiko commented on e2e/specs/swaps/swap-action-smoke.spec.js
> +      //Select source token, if native tiken can skip because already selected
typo here. Token instead of tiken

2024-10-09 21:55 UTC, cortisiko commented on e2e/fixtures/fixture-builder.js
> +    const NetworkController =
camel case this

2024-10-09 21:55 UTC, cortisiko commented on e2e/fixtures/fixture-builder.js
> +    (NetworkController.selectedNetworkClientId = network.id),
camel case this

2024-10-09 21:55 UTC, cortisiko commented on e2e/resources/networks.e2e.js
> +    Mainnet: {
you can lower case this.

2024-10-09 21:55 UTC, cortisiko commented on e2e/resources/networks.e2e.js
> +    Polygon: {
you can lower case this.

2024-10-09 21:55 UTC, cortisiko commented on e2e/resources/networks.e2e.js
> +    Optimism: {
you can lower case this.

2024-10-16 03:59 UTC, davibroc commented on e2e/specs/swaps/swap-action-smoke.spec.js
> +      //Select source token, if native tiken can skip because already selected
done

2024-10-16 04:15 UTC, davibroc commented on e2e/resources/networks.e2e.js
> +    Polygon: {
Actually in the file networks.e2e.js the network names are all uppercase so that would look strange

2024-10-16 04:16 UTC, davibroc commented on e2e/resources/networks.e2e.js
> +    Optimism: {
Actually in the file networks.e2e.js the network names are all uppercase so that would look strange

2024-10-16 04:16 UTC, davibroc commented on e2e/resources/networks.e2e.js
> +    Mainnet: {
Actually in the file networks.e2e.js the network names are all uppercase so that would look strange

2024-10-16 04:19 UTC, davibroc commented on e2e/fixtures/fixture-builder.js
> +    const NetworkController =
done

2024-10-16 04:19 UTC, davibroc commented on e2e/fixtures/fixture-builder.js
> +    (NetworkController.selectedNetworkClientId = network.id),
done

2024-10-16 04:37 UTC, davibroc commented on e2e/specs/swaps/swap-action-smoke.spec.js
> +    ${'native'}$     |${'.1 '}  | ${'ETH'}          | ${'USDC'}       | ${CustomNetworks.Tenderly.Optimism}
Swtiched the order but can't use Linea at the moment as having issues on Mobile and it's low volume for us. The Swap team wants Optimism because we have some special code for that network that needs to be tested. Optimism has been having issues recently and it wasn't avaible on Mobile so this test will make sure Optimism doesn't regrees

2024-10-28 18:43 UTC, cortisiko requested changes

2024-10-28 18:43 UTC, cortisiko commented on e2e/specs/swaps/swap-action-smoke.spec.js
> +    ${'native'}$     |${'.4'}   | ${'ETH'}          | ${'WETH'}       | ${CustomNetworks.Tenderly.Mainnet}
Thinking out loud here: we should have a test for ERC20<>ERC20 or Native <> ERC20 to prevent this [regression](https://github.com/MetaMask/metamask-mobile/issues/9677)

2025-01-14 23:34 UTC, cortisiko requested changes
a few comments

2025-01-15 00:45 UTC, cortisiko approved these changes, later dismissed
Great work @davibroc 🚀 🥇

2025-01-15 20:32 UTC, cortisiko approved these changes

2025-01-15 20:47 UTC, merged