feat: add tracking for receive action
MetaMask/metamask-mobile pull request #11695
Opened 2024-10-09 01:30 UTC by jonybur

## **Description**

This PR adds metrics tracking to the interactions with the "Receive" and "Request" features. 

## **Related issues**

Fixes: https://github.com/MetaMask/MetaMask-planning/issues/3260

## **Manual testing steps**

Click on top QR for scanner, onReceive being ran should trigger a trackingEvent
Same thing for action button on lower menu
Same thing for asset in asset list

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-09 08:25 UTC, naugtur reviewed
There's nothing interesting going on here supply-chain wise.
I'm surprised seeing arbitrary human readable strings assigned to a field called origin, but I'm likely missing context here.

2024-10-09 11:06 UTC, EtherWizard33 approved these changes, later dismissed
LGTM

2024-10-09 11:16 UTC, andreahaku approved these changes
LGTM

2024-10-10 15:09 UTC, salimtb commented on package.json
> +    "@metamask/smart-transactions-controller": "^13.2.0",
can you explain pls why this upgrade is needed ?

2024-10-10 15:11 UTC, sahar-fehri commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +      origin: 'Token details',
Nit: origin is sometimes defined as part of AppConstants; definitely not a blocker

2024-10-10 15:13 UTC, sahar-fehri submitted a review, later dismissed

2024-10-14 12:10 UTC, jonybur commented on package.json
> +    "@metamask/smart-transactions-controller": "^13.2.0",
We need to import the new definitions from `MetaMetricsEventCategory` and `MetaMetricsEventName`, which are available on 13.2.0

2024-12-02 14:40 UTC, sahar-fehri submitted a review, later dismissed

2024-12-02 14:40 UTC, EtherWizard33 submitted a review, later dismissed
re-approving

2024-12-02 14:54 UTC, NicolasMassart requested changes
Same comment as others on origin that could be a constant (or enum) but more importantly, your track event is using old way that is not valid anymore but undetected because your file is JS instead of TS.
You have an example of the valid way just a few lines bellow.

2024-12-02 14:54 UTC, NicolasMassart commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +      origin: 'Token details',
I think it is unless it's typed value.
So please make use of constants or enums here

2024-12-02 14:54 UTC, NicolasMassart commented on app/components/UI/Navbar/index.js
> +      origin: 'QR code scanner icon',
can you use a constant or enum instead of string?

2024-12-02 14:54 UTC, NicolasMassart commented on app/components/UI/ReceiveRequest/index.js
> +    });
this has to use `createEventBuilder`

2024-12-02 14:54 UTC, NicolasMassart commented on app/components/Views/WalletActions/WalletActions.tsx
> +        origin: 'Action menu',
use constant or enum

2024-12-02 15:03 UTC, EtherWizard33 submitted a review, later dismissed

2024-12-02 15:08 UTC, NicolasMassart submitted a review, later dismissed
LGTM, thanks for your changes!

2024-12-02 15:16 UTC, sahar-fehri approved these changes, later dismissed

2024-12-03 14:43 UTC, NicolasMassart requested changes

2024-12-03 14:43 UTC, NicolasMassart commented on app/components/UI/AssetOverview/AssetOverview.test.tsx
> +  it('should handle receive button press', async () => {
```suggestion
  it('navigates to "Your QR code" screen on receive button press', async () => {
```

2024-12-03 14:43 UTC, NicolasMassart commented on app/components/UI/AssetOverview/AssetOverview.test.tsx
>    it('should handle send button press', async () => {
```suggestion
  it('navigates to send screen on send button press', async () => {
```

2024-12-03 14:43 UTC, NicolasMassart commented on app/components/UI/ReceiveRequest/index.test.tsx
> +  it('should track metrics when onReceive is called', () => {
```suggestion
  it('tracks metrics when onReceive is called', () => {
```

2024-12-03 14:43 UTC, NicolasMassart commented on app/components/UI/ReceiveRequest/index.test.tsx
> +    expect(mockTrackEvent).toHaveBeenCalledTimes(2);
S: you can test the trackEvent is called with an object created by event builder without mocking the builder, it's just a builder without side effects.
You just have to create a new event  with createEventBuilder, similar to the expected one, and expect trackEvent to have been called with it.

2025-03-10 16:36 UTC, closed without merging