fix: relax network symbol length validation #24872
MetaMask/metamask-mobile pull request #11693
Opened 2024-10-08 21:52 UTC by bergeron

## **Description**

When adding a network with wallet_addEthereumChain, MetaMask was requiring the chain's symbol to be minimum of 2 characters. But there are networks with single character symbols. 

## **Related issues**

- Equivalent PR on extension: https://github.com/MetaMask/metamask-extension/pull/24872

## **Manual testing steps**

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-11 16:56 UTC, salimtb approved these changes, later dismissed

2024-10-11 17:06 UTC, sahar-fehri approved these changes, later dismissed

2024-11-06 19:04 UTC, gambinish approved these changes

2024-11-07 15:40 UTC, joaoloureirop approved these changes

2024-11-07 15:48 UTC, NicolasMassart requested changes
Can you provide a unit test for this please?

2024-11-07 15:50 UTC, kylanhurt approved these changes
LGTM

2024-11-07 15:55 UTC, merged