feat: Header Update
MetaMask/metamask-mobile pull request #11763
Opened 2024-10-11 17:51 UTC by vinnyhoward

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-18 22:24 UTC, gambinish commented on app/components/hooks/useAccountName.ts
> +      '',
In which situation would `isDefaultAccountName(defaultName) && ensName ? ensName : defaultName` not return a value? I think the `|| ''` might be redundant here.

2024-10-18 22:25 UTC, gambinish commented on app/components/hooks/useAccountName.ts
> +      '',
```suggestion
      isDefaultAccountName(defaultName) && ensName ? ensName : defaultName)
```
☝️ not tested

2024-10-18 22:28 UTC, gambinish commented on app/components/UI/Navbar/index.js
> +        {/* <ButtonIcon
We may want to delete this unless there is a reason for keeping the code commented out

2024-10-18 22:50 UTC, gambinish requested changes

2024-10-18 22:50 UTC, gambinish commented on app/component-library/components/Pickers/PickerNetwork/PickerNetwork.test.tsx
> +  });
Should we also add a test for when `hideNetworkName` is true? Or, is this sufficiently captured in the snapshot on line 17?

Admittedly, I'm not the biggest fan of snapshot tests, and usually prefer to target testIDs directly like you are doing here.

2024-10-18 22:50 UTC, gambinish commented on app/component-library/components/Pickers/PickerNetwork/PickerNetwork.test.tsx
> +// External dependencies.
Nit: Are we missing whitespace after the import?

2024-10-22 18:37 UTC, vinnyhoward commented on app/component-library/components/Pickers/PickerNetwork/PickerNetwork.test.tsx
> +// External dependencies.
Fixed

2024-10-22 18:38 UTC, vinnyhoward commented on app/component-library/components/Pickers/PickerNetwork/PickerNetwork.test.tsx
> +  });
Added the new. Thanks for the idea

2024-10-22 18:38 UTC, vinnyhoward commented on app/components/hooks/useAccountName.ts
> +      '',
Added new tests for this hook

2024-10-23 14:52 UTC, brianacnguyen approved these changes, later dismissed

2024-10-24 18:15 UTC, gambinish commented on app/components/UI/Navbar/index.js
> + * @returns {Object} An object containing the navbar options for the wallet screen
Are all of these params being passed into `getWalletNavbarOptions`? I see 7 params being passed, but lmk if I'm missing something.

2024-10-24 18:19 UTC, vinnyhoward commented on app/components/UI/Navbar/index.js
> + * @returns {Object} An object containing the navbar options for the wallet screen
Good catch, I need to update that

2024-10-24 18:28 UTC, gambinish submitted a review, later dismissed
Approved, just one question about some JSdoc stuff

2024-10-24 19:53 UTC, vinnyhoward commented on app/components/UI/Navbar/index.js
> + * @returns {Object} An object containing the navbar options for the wallet screen
Fixed

2024-10-24 19:55 UTC, gambinish submitted a review, later dismissed

2024-10-28 18:57 UTC, gambinish approved these changes, later dismissed

2024-10-29 15:35 UTC, gambinish submitted a review, later dismissed

2024-10-30 01:22 UTC, darkwing approved these changes, later dismissed

2024-10-30 03:05 UTC, gambinish submitted a review, later dismissed

2024-10-30 17:04 UTC, frankvonhoven commented on app/component-library/components/Pickers/PickerAccount/PickerAccount.styles.ts
> +      borderWidth: 0,
does these need to be explicitly set to `0`?

2024-10-30 17:04 UTC, frankvonhoven commented on app/component-library/components/Pickers/PickerAccount/PickerAccount.styles.ts
> +      flexDirection: 'column',
column is default, you can remove 👍

2024-10-30 17:04 UTC, frankvonhoven commented on app/component-library/components/Pickers/PickerAccount/PickerAccount.styles.ts
> +      flexDirection: 'column',
again, default

2024-10-30 17:12 UTC, cortisiko submitted a review, later dismissed
Trigger the Regression E2E tests, once it passes feel free to post the link on the PR. I will approve once we have ✅ for regression

2024-10-30 17:45 UTC, vinnyhoward commented on app/component-library/components/Pickers/PickerAccount/PickerAccount.styles.ts
> +      borderWidth: 0,
Yeah it as to do with the PickerBase component in the component library. This is what it looks like without it
![Screenshot 2024-10-30 at 11 45 05 AM](https://github.com/user-attachments/assets/0f061140-8ef7-433a-8e2e-9c8da554043d)

2024-10-30 17:45 UTC, vinnyhoward commented on app/component-library/components/Pickers/PickerAccount/PickerAccount.styles.ts
> +      flexDirection: 'column',
Fixed

2024-10-30 17:45 UTC, vinnyhoward commented on app/component-library/components/Pickers/PickerAccount/PickerAccount.styles.ts
> +      flexDirection: 'column',
Fixed

2024-10-31 20:05 UTC, AxelGes submitted a review, later dismissed

2024-11-06 16:01 UTC, brianacnguyen requested changes
Can you link the design to the show caret being moved to the account selector list?

2024-11-06 23:05 UTC, chrisleewilcox approved these changes
LGTM

2024-11-07 16:24 UTC, brianacnguyen submitted a review, later dismissed

2024-11-07 16:24 UTC, brianacnguyen commented
non-blocking. This PR could be split into smaller PRs. just a small note

2024-11-07 16:36 UTC, gambinish approved these changes, later dismissed

2024-11-07 16:42 UTC, AxelGes approved these changes, later dismissed

2024-11-07 17:13 UTC, frankvonhoven approved these changes, later dismissed

2024-11-07 20:22 UTC, chrisleewilcox requested changes
Will run regression tests as well for this.

2024-11-07 23:33 UTC, chrisleewilcox commented
> Will run regression tests as well for this.

Regression passed: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/e7468f64-538c-4308-8c63-17b6d59905c1?tab=workflows

2024-11-07 23:33 UTC, chrisleewilcox approved these changes, later dismissed
LGTM

2024-11-08 17:57 UTC, EtherWizard33 commented on app/component-library/components-temp/ListItemMultiSelectButton/ListItemMultiSelectButton.tsx
> -
nit: I kind of like having an empty line before the return statement, but no need to change it just for this :)

but, I since it was the only change in the component library, I believe it could have spared you an extra codeowner approval from the DS team

2024-11-08 17:57 UTC, EtherWizard33 commented on app/components/UI/AccountSelectorList/AccountSelectorList.tsx
> +      if (!isMultiSelect) {
nit: I see these styles were already defined in the component, and it's not new to this PR, but I would think they should go in the styles file AccountSelectorList.styles.ts, and receive params.vars like isLoading and isMultiselect, for example how it's done in AvatarBase.styles.ts 

so far I like the PR, all very clear to understand and clean, with accessibilty and test ids, types, nice work :)

2024-11-08 17:57 UTC, EtherWizard33 commented on app/components/Views/AccountActions/AccountActions.test.tsx
> +      message: '0xC4966c0D659D99699BFD7EB54D8fafEE40e4a756',
looks like the expected address was not checksummed before, and is checksummed now, is this to be expected?

2024-11-08 20:34 UTC, vinnyhoward commented on app/components/Views/AccountActions/AccountActions.test.tsx
> +      message: '0xC4966c0D659D99699BFD7EB54D8fafEE40e4a756',
Yeah this one is expected it was just changed in the initial test to be checksummed. I had used the same address from above in line 34 and 41

2024-11-08 20:37 UTC, gambinish approved these changes

2024-11-08 20:53 UTC, AxelGes approved these changes

2024-11-08 20:58 UTC, EtherWizard33 approved these changes
looks good to me, good work!

2024-11-08 21:03 UTC, frankvonhoven approved these changes

2024-11-08 21:18 UTC, chrisleewilcox approved these changes
LGTM

2024-11-08 21:58 UTC, brianacnguyen approved these changes

2024-11-08 22:40 UTC, merged