test: Refining E2E Testing with API Mocking
MetaMask/metamask-mobile pull request #11797
Opened 2024-10-15 14:13 UTC by Andepande

## **Description**
This change enhances the mock functionality to enable multiple dynamic events to be passed through. This will evolve over time with how people use it. A corresponding document has been created in the contributors' repository.

## **Related issues**

Fixes:
https://github.com/orgs/MetaMask/projects/60/views/3?pane=issue&itemId=81125053&issue=MetaMask%7Cmobile-planning%7C1944

## **Screenshots/Recordings**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-25 16:00 UTC, SamuelSalas approved these changes, later dismissed
LGTM

2024-10-25 23:28 UTC, cortisiko requested changes
Just some small feedback; otherwise, things are looking good.

2024-10-25 23:28 UTC, cortisiko commented on e2e/mockServer/mock-server.js
> +/* eslint-disable no-console */
You have the file and directory names inverted. The file name should be `mockServer.js` and the name of the directory should be` mock-server`

2024-10-25 23:28 UTC, cortisiko commented on e2e/specs/mock-specs/suggestedGasApi.mock.spec.js
> +  SmokeCore(
This test seems like a good candidate for regression not smoke

2024-10-25 23:28 UTC, cortisiko commented on e2e/mockServer/mock-responses/mock-responses.json
> +{
We should create individual JSONs for the mock endpoints; therefore, the names of the response data should match those. In this case, the name of this file should be `gas-api-responses.json`. The name we currently have implies that we are going to have an exhaustive JSON file for all the mock responses.

2024-10-28 17:14 UTC, cortisiko commented on e2e/api-mocking/mock-config/mock-events.js
> +
Can you add JSDocs here as well?

2024-10-29 16:31 UTC, cortisiko commented on e2e/api-mocking/mock-config/mockUrlCollection.json
> +  "defaultMockPort": 8000
Okay so you defined The mock server port two places, here and then again here: https://github.com/MetaMask/metamask-mobile/pull/11797/files#diff-03b7a8cfcc1c4512beea1ccb712a7c6570c734f7e2e359ade57c65c5ffeb17a4R6 

I do not see a need for having it defined two places. If it is used in the shims you can just import the default port from the mock server file

2024-10-30 18:28 UTC, cortisiko approved these changes

2024-10-30 19:11 UTC, merged