chore: upgrade assets controllers v33.0.0
MetaMask/metamask-mobile pull request #11800
Opened 2024-10-15 17:06 UTC by sahar-fehri

## **Description**
PR to upgrade assets-controllers to v33.0.0

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-16 09:21 UTC, Daniel-Cross commented
Hi @sahar-fehri 

When I checkout the branch and cold boot the app I get stuck on a loading screen, see attached:

https://github.com/user-attachments/assets/af4f9abc-0550-44c3-b6e2-a1413a1609e2

2024-10-16 09:22 UTC, Daniel-Cross requested changes
App gets stuck on loading screen on cold boot.

2024-10-16 09:29 UTC, Daniel-Cross commented
> Hi @sahar-fehri
> 
> When I checkout the branch and cold boot the app I get stuck on a loading screen, see attached:
> 
>  Simulator.Screen.Recording.-.iPhone.16.Pro.-.2024-10-16.at.11.21.07.mp4

This is addressed with a clean build of the app so I'll approve.

2024-10-16 09:30 UTC, Daniel-Cross approved these changes
Looks good!

2024-10-16 14:33 UTC, sahar-fehri commented
Thanks @Daniel-Cross  for pulling the branch locally and testing it 🙏

2024-10-17 20:44 UTC, bergeron commented on app/selectors/accountsController.ts
> +export const selectSelectedInternalAccountAddress = createSelector(
Is this here as an alternative to `selectSelectedInternalAccountChecksummedAddress` that is not checksummed?

2024-10-17 21:42 UTC, bergeron approved these changes
Looked okay to me. Tested the usual features of token/nft detection, importing, removing, prices.

2024-10-18 04:16 UTC, sahar-fehri commented on app/selectors/accountsController.ts
> +export const selectSelectedInternalAccountAddress = createSelector(
Correct this selector is returning the non checksummed address for the selected account and used to fetch collectibles now because NftController now gets the selected address from `AccountsController:getAccount` which is not a checksum address

2024-10-18 05:00 UTC, merged