feat: adds GoogleService.plist creation during build process
MetaMask/metamask-mobile pull request #11863
Opened 2024-10-18 10:28 UTC by Jonathansoufer

## **Description**

This PR address a need for creating GoogleServices-info.plist file at build process thus avoiding leaving project details exposed. Although this isn't an issue as stated [here](https://firebase.google.com/docs/projects/api-keys) and [here](https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public), we're just trying to minimize risk even when they're very low already.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

![Screenshot 2024-10-18 at 11 27 28](https://github.com/user-attachments/assets/a083aab0-6641-4e78-a79b-567e5c78fe71)

### **After**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-23 17:46 UTC, legobeat commented on README.md
> +Before running the app, keep in mind that MetaMask uses FCM (Firebase Cloud Message) to empower communications. Based on this, as an external contributor you would preferably need to provide your own
could we also add instructions for devs that do not have access to Google services? Ie how to build and run the app without valid Firebase credentials.

2024-10-23 17:54 UTC, legobeat commented on README.md
> +base64 -i ./ios/GoogleServices/GoogleService-Info-example.plist
Why not the same approach to iOS and Android varieties?

2024-10-23 17:55 UTC, legobeat commented on README.md
> +Copy the result to your clipboard and paste it in the `GOOGLE_SERVICES_B64_ANDROID` or `GOOGLE_SERVICES_B64_IOS` variable in the `.env` file you are running the app.
Copying to clipboard is not good security advice. See the existing Android example (which should prob be amended).

2024-10-23 17:58 UTC, legobeat commented on README.md
> +You can make usage of a mock file at `android/app/google-services-example.json` or `ios/GoogleServices/GoogleService-Info-example.plist`, following the same steps above from the root of the project.
Maybe this entire paragraph can be removed and merged into the one at line 46, as they mostly say the same thing.

2024-10-23 18:02 UTC, legobeat commented on README.md
> +> In case you don't provide your own Firebase project config file, you will face the error `No matching client found for package name 'io.metamask'`.
This should be fixed as of #11758, at least for Android - could a similar approach work for iOS as well?

2024-10-23 21:16 UTC, Jonathansoufer commented on README.md
> +Before running the app, keep in mind that MetaMask uses FCM (Firebase Cloud Message) to empower communications. Based on this, as an external contributor you would preferably need to provide your own
Good point. Fixed.

2024-10-23 21:16 UTC, Jonathansoufer commented on README.md
> +base64 -i ./ios/GoogleServices/GoogleService-Info-example.plist
adjusted

2024-10-23 21:16 UTC, Jonathansoufer commented on README.md
> +Copy the result to your clipboard and paste it in the `GOOGLE_SERVICES_B64_ANDROID` or `GOOGLE_SERVICES_B64_IOS` variable in the `.env` file you are running the app.
adjusted

2024-10-23 21:17 UTC, Jonathansoufer commented on README.md
> +You can make usage of a mock file at `android/app/google-services-example.json` or `ios/GoogleServices/GoogleService-Info-example.plist`, following the same steps above from the root of the project.
Agreed. Removed

2024-10-23 21:18 UTC, Jonathansoufer commented on README.md
> +> In case you don't provide your own Firebase project config file, you will face the error `No matching client found for package name 'io.metamask'`.
iOS doesn't trigger such error while building, so no need to handle in that sense.

2024-10-23 23:40 UTC, owencraston commented on ios/GoogleService-Info.plist
> +	<string>mock-api-key-1234</string>
Is this file used or is it an example?

2024-10-23 23:41 UTC, owencraston approved these changes, later dismissed
I ran the commands listed in the readme and they all worked. Building the app on Android worked as well.

2024-10-24 13:47 UTC, Jonathansoufer commented on ios/GoogleService-Info.plist
> +	<string>mock-api-key-1234</string>
is an example one.

2024-10-25 01:46 UTC, legobeat requested changes
[This seems to be causing build failure in Bitrise?]( https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/6d6b8153-3499-46e7-8a49-7fc640227443)

2024-10-25 12:43 UTC, closed without merging