fix: Resolve secp256k1 package
MetaMask/metamask-mobile pull request #11929
Opened 2024-10-21 21:43 UTC by NEllusion

## **Description**

This pull request resolves the secp256k1 to the latest version as a precaution. 

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-21 21:49 UTC, legobeat requested changes
https://github.com/MetaMask/metamask-mobile/actions/runs/11449136476/job/31854080852?pr=11929

2024-10-21 22:33 UTC, tommasini approved these changes, later dismissed

2024-10-21 22:55 UTC, legobeat commented on package.json
> +    "ethereumjs-util/**/secp256k1": "3.8.1",
When looking closer, this is only here because of a pinning to an ancient `ethereumjs-util@6.1.0`. I propose we start with just lifting that pin and then look at upgrading.

2024-10-21 22:59 UTC, legobeat approved these changes, later dismissed

2024-10-21 23:31 UTC, legobeat commented on package.json
> +    "ethereumjs-util/**/secp256k1": "3.8.1",
I tried just bumping to `ethereumjs-util@^6.2.0` here but that uncovered a type error in the build about what looks like existing mismatching major versions of `bn.js`.
Follow-up:
- #11930

2024-10-22 08:52 UTC, salimtb approved these changes

2024-10-22 10:25 UTC, legobeat approved these changes

2024-10-22 11:07 UTC, merged