test: Refactor Advanced Gas fees test to utilize mocks
MetaMask/metamask-mobile pull request #11927
Opened 2024-10-21 18:59 UTC by SamuelSalas

## **Description**
The advanced gas fees tests are becoming a bit unstable within the smoke pipeline mainly because we are relying on real funds (Sepolia ETH) to submit the transaction. With the recent addition of mocking, we should refactor the advanced gas fees tests to:

- use ganache
- mock the gas api to return expected values

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-21 19:53 UTC, cortisiko requested changes
nice stuff! small feedback

2024-10-21 19:53 UTC, cortisiko commented on e2e/pages/Send/AmountView.js
> -  get currencySwitch() {
I recall we had a specific use case for this. Unfortunately, the test that used this test step was deleted https://github.com/MetaMask/metamask-mobile/blob/3635e729262bf8db08983e79f80bba7d67f5df99/e2e/specs/confirmations/send-eth-flow.spec.js#L58 . We can work to add it back. Do not remove.

2024-10-21 19:53 UTC, cortisiko commented on e2e/pages/Send/AmountView.js
> -  async tapCurrencySwitch() {
I recall we had a specific use case for this. Unfortunately, the test that used this test step was deleted https://github.com/MetaMask/metamask-mobile/blob/3635e729262bf8db08983e79f80bba7d67f5df99/e2e/specs/confirmations/send-eth-flow.spec.js#L58 . We can work to add it back. Do not remove.

2024-10-21 22:25 UTC, SamuelSalas commented on e2e/pages/Send/AmountView.js
> -  get currencySwitch() {
Done

2024-10-21 22:25 UTC, SamuelSalas commented on e2e/pages/Send/AmountView.js
> -  async tapCurrencySwitch() {
Done

2024-10-22 22:03 UTC, cortisiko approved these changes

2024-10-22 22:21 UTC, merged