test: Refactor SendLinkView.js & TokenOverview.js files to follow page object model
MetaMask/metamask-mobile pull request #11986
Opened 2024-10-23 21:14 UTC by SamuelSalas

## **Description**

We are aiming to refactor the page objects in the modal folder so that they strictly follow the page object model pattern. This would aide in providing more readable and help standardize the way we create our tests. Because of the amount of files remaining, this issue will focus on working on three files to refactor, as well as their respective testIDS.

Files inside the scope for this batch:

- SendLinkView.js
- TokenOverview.js

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-24 15:13 UTC, cortisiko requested changes
small feedback

2024-10-24 15:13 UTC, cortisiko commented on e2e/pages/SendLinkView.js
> +  get qrCloseButton() {
we probably should create a seperate page object for the qr modal.

2024-10-24 19:09 UTC, cortisiko approved these changes

2024-10-25 15:55 UTC, bergeron approved these changes

2024-10-25 16:15 UTC, merged