[WIP] feat: Simulation re-trigger
MetaMask/metamask-mobile pull request #12073
Opened 2024-10-29 11:58 UTC by OGPoyraz

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-10-29 12:28 UTC, OGPoyraz commented on app/components/Views/confirmations/Approval/index.test.tsx
> +    const wrapper = renderScreen(
More meaningful snapshot is added here.

2024-10-29 12:29 UTC, OGPoyraz commented on app/components/Views/confirmations/Approval/index.js
> +    if (isUpdatedAfterSecurityCheck) {
This is not unit tested - lacking some infra to test modals and their children.
I am open for any suggestions here.

2024-10-29 13:55 UTC, matthewwalsh0 requested changes

2024-10-29 13:55 UTC, matthewwalsh0 commented on app/components/Views/ChangeInSimulationModal/ChangeInSimulationModal.tsx
> +    <BottomSheet ref={sheetRef}>
Way out of scope, but I'm surprised there isn't a generic `MessageModal` or something handle all of this infrastructure.

2024-10-29 13:55 UTC, matthewwalsh0 commented on app/components/Views/confirmations/Approval/index.js
> +      navigation.navigate(Routes.MODAL.ROOT_MODAL_FLOW, {
Since we use `SimulationDetails` in approval, approve, and send, do we need to centralise this in a util and use it inside `TransactionReview` (hopefully handles Approval and Approve) and `Send` also?

2024-10-29 14:31 UTC, NicolasMassart commented on app/components/Views/ChangeInSimulationModal/ChangeInSimulationModal.test.tsx
> +  it('renders content', () => {
```suggestion
  it('render matches snapshot', () => {
```

2024-10-30 11:39 UTC, OGPoyraz commented on app/components/Views/confirmations/Approval/index.js
> +      navigation.navigate(Routes.MODAL.ROOT_MODAL_FLOW, {
This was unfortunately not possible due since we cannot manage the visibility of main confirmation modal inside child - `TransactionReview`.
So it's duplicated and put `Approve` and `Send/Confirm` now.

2024-10-30 16:22 UTC, matthewwalsh0 approved these changes

2024-10-30 16:54 UTC, sethkfman commented
Considering the manual test evidence. I am okay moving forward with an override. I would like to see an issue created to support modal unit testing for these scenarios. @OGPoyraz

2024-10-30 17:01 UTC, merged

2024-10-30 17:46 UTC, sleepytanya commented
Bitrise builds:

https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/4469c953-368c-49aa-b322-850019994581?tab=workflows

https://app.bitrise.io/build/4a80f97e-7cee-49ba-b0c0-d3b0e150ce5c?tab=log

The fix has been implemented successfully. However, we experienced a challenge with the iOS build on Bitrise, which prevented testing the functionality on a physical device. Despite this, the local iOS build operates as anticipated.

https://cloud.githubusercontent.com/assets/104780023//5d59a555-6a87-4596-8220-7b2bc340f0c3.mp4




https://github.com/user-attachments/assets/30c5b6e0-734c-49c7-b244-e7d3f3ae55d3



In iOS Bitrise build all transaction action are disabled and other errors not related to the current PR are present as well, for example the error you get when trying to access networks modal:


![IMG_0256](https://github.com/user-attachments/assets/898e0842-1a69-43be-9d17-f27e4c9451c6)