Integrate NFT api to display names for nfts within simulations includ…
MetaMask/metamask-mobile pull request #12160
Opened 2024-11-04 13:39 UTC by OGPoyraz

## **Description**

This PR integrates NFT api to display name and image of collection for nfts within simulations include `ERC721` nfts.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to Opensea, try buying https://opensea.io/assets/ethereum/0xd4307e0acd12cf46fd6cf93bc264f5d5d1598792/41757 (you don't need to buy) - this is `ERC721`
2. See collection name and image in simulations 

## **Screenshots/Recordings**

### **Before**

![1](https://github.com/user-attachments/assets/21c1c4b1-ff6c-438e-98bf-0c658fb43185)

### **After**

![2](https://github.com/user-attachments/assets/2285d896-e5a0-4284-9927-13399e30e954)

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-11-08 11:15 UTC, pedronfigueiredo submitted a review, later dismissed

2024-11-13 12:56 UTC, matthewwalsh0 requested changes

2024-11-13 12:56 UTC, matthewwalsh0 commented on app/components/hooks/DisplayName/useDisplayName.ts
> +    const isNotSpam = nftCollectionProperties?.isSpam === false;
As we do with the other fallbacks and in the extension, can we create a dedicated hook such as `useNftName` to abstract all this logic?

In mobile, they are separate files but same directory.

2024-11-13 12:56 UTC, matthewwalsh0 commented on app/components/UI/Name/Name.tsx
> +        <Image source={{ uri: image }} style={styles.image} />
I've done something similar in my pending global network PR, would it be worth getting that in first to simplify this one?

https://github.com/MetaMask/metamask-mobile/pull/12257

2024-11-13 12:56 UTC, matthewwalsh0 commented on app/components/hooks/DisplayName/useNftCollectionsMetadata.ts
> +export interface UseNftCollectionsMetadataRequest {
Can we re-use the original `UseDisplayNameRequest` here and support the variation as we now do in the extension?

2024-11-13 13:31 UTC, jpuri approved these changes, later dismissed

2024-11-19 10:11 UTC, OGPoyraz commented on app/components/hooks/DisplayName/useDisplayName.ts
> +    const isNotSpam = nftCollectionProperties?.isSpam === false;
Done

2024-11-19 10:11 UTC, OGPoyraz commented on app/components/hooks/DisplayName/useNftCollectionsMetadata.ts
> +export interface UseNftCollectionsMetadataRequest {
Done

2024-11-19 17:31 UTC, matthewwalsh0 requested changes

2024-11-19 17:31 UTC, matthewwalsh0 commented on app/components/hooks/DisplayName/useNftCollectionsMetadata.ts
> +  const chainId = requests?.[0]?.variation;
We shouldn't really assume they all have the same chain ID since they are distinct requests.

I refactored the same hook in the extension to support alternate chains in the requests, can we copy and paste here?

2024-11-19 17:31 UTC, matthewwalsh0 commented on app/components/hooks/DisplayName/useNftName.ts
> +    const nftCollectionProperties = nftCollections[value.toLowerCase()];
Can we add the standard `type` check to return `undefined` if it's not an Ethereum address?

2024-11-19 17:31 UTC, matthewwalsh0 commented on app/components/hooks/DisplayName/useNftName.ts
> +    const isNotSpam = nftCollectionProperties?.isSpam === false;
Minor, could we also just early return if it is spam?

2024-11-19 17:31 UTC, matthewwalsh0 commented on app/components/hooks/DisplayName/useNftName.ts
> +export interface UseNFTNameResponse {
Minor, `type` rather than `interface`?

2024-11-19 17:31 UTC, matthewwalsh0 commented on app/components/hooks/DisplayName/useNftName.ts
> +  nftCollectionName: string | undefined;
Minor, in this context is `name` and `image` sufficient as the rest is implied?

2024-11-20 09:16 UTC, OGPoyraz commented on app/components/hooks/DisplayName/useNftName.ts
> +  nftCollectionName: string | undefined;
Done

2024-11-20 09:16 UTC, OGPoyraz commented on app/components/hooks/DisplayName/useNftName.ts
> +export interface UseNFTNameResponse {
Done

2024-11-20 09:16 UTC, OGPoyraz commented on app/components/hooks/DisplayName/useNftName.ts
> +    const nftCollectionProperties = nftCollections[value.toLowerCase()];
Done

2024-11-20 09:16 UTC, OGPoyraz commented on app/components/hooks/DisplayName/useNftCollectionsMetadata.ts
> +  const chainId = requests?.[0]?.variation;
Done

2024-11-20 21:36 UTC, matthewwalsh0 approved these changes

2024-11-20 21:51 UTC, merged