fix: 10967 User able to add Ledger account with existing account name
MetaMask/metamask-mobile pull request #12199
Opened 2024-11-06 04:47 UTC by dawnseeker8

## **Description**

This PR fix #10967 User able to add Ledger account with existing account name.
Now the ledger Select accounts screen will display `Account Ledger 1 already exists`

## **Related issues**

Fixes: #10967 

## **Manual testing steps**

1. Install MM
2. Recover from SRP
3. Rename 'Account 1' to 'Ledger 1'
4. Connect Ledger device
5. Add 1 Ledger account
6. `Account Ledger 1 already exists` error should be displayed

## **Screenshots/Recordings**

### **Before**
https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmVqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1518b952ff8565cc8a07ece6fc4e18261e572a22/image.png?_gl=1*sdljcu*_gcl_au*MTQ0MDIzNTU3NC4xNzI4ODc2NDg3

### **After**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-11-07 11:23 UTC, vivek-consensys commented
Bitrise [build](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/21fa0d1a-d26c-4923-8529-a411668521cb?tab=workflows) 

Tested on iPhone 13 / iOS 18.1

[Fix](https://github.com/MetaMask/metamask-mobile/issues/10967) 


https://github.com/user-attachments/assets/690205ad-ddb2-4f14-8afb-86815a20fc66

2024-11-13 10:47 UTC, vivek-consensys commented
Tested using the latest ledger library [upgrade](https://github.com/MetaMask/metamask-mobile/pull/11836) on bitrise [build](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/957add45-66f2-4d8e-b79a-df93bba4f358?tab=artifacts) and working as expected.

2024-12-02 11:07 UTC, joaoloureirop requested changes
code lgtm.

Can we have wallet ux confirmation that we want to block users from importing Ledger wallets until they manually rename the existing non-ledger wallet?

I'm concerned this friction might upset users.
We could offer a wallet rename at this point.

2024-12-02 11:07 UTC, joaoloureirop commented on app/core/Ledger/Ledger.ts
> +      throw new Error(`Account ${accountName} already exists`);
Should add error message to translation file `locales/languages/en.json`

2024-12-02 11:37 UTC, dawnseeker8 commented on app/core/Ledger/Ledger.ts
> +      throw new Error(`Account ${accountName} already exists`);
have make the change to add translation key into en.json file.

2024-12-02 14:55 UTC, joaoloureirop approved these changes

2024-12-03 08:04 UTC, merged