feat: custom names for snap accounts
MetaMask/metamask-mobile pull request #12198
Opened 2024-11-06 04:16 UTC by owencraston

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-11-14 14:29 UTC, Daniel-Cross commented on app/components/Approvals/SnapAccountCustomNameApproval/SnapAccountCustomNameApproval.tsx
> +  );
We've been having a discussion recently on the Mobile Team regarding the usage of useCallback and useMemo as there is generally an overuse of these hooks in an attempt to make the code more efficient. However this is not really the case, and every time we use these, we're asking the device to allocate system memory to watch the dependencies in case they change. In essence, we're introducing memory leaks into our code in the name of improvements when we haven't had any performance issues around these functions to begin with. In this instance, we're asking the useCallback to watch a boolean. This could be re-rendered thousands of times and it wouldn't impact performance in anyway.

Thats a long winded way of basically saying, can you please remove the usage of useCallback on these functions as it's overkill and not needed.

I recently wrote some docs on this if you're interested in knowing more: https://www.notion.so/metamask-consensys/React-Native-Contributor-Guidelines-127f86d67d6880adb3f4e9ec784c0d36

2024-11-14 14:31 UTC, Daniel-Cross commented on app/components/Approvals/SnapAccountCustomNameApproval/SnapAccountCustomNameApproval.tsx
> +  }, [approvalRequest, internalAccounts, checkIfNameTaken]);
Can we pull some of the logic out of this `useEffect` and into normal functions to make it easier to test and to ensure there aren't unwanted re-renders?

2024-11-14 14:32 UTC, Daniel-Cross requested changes
Just a couple of comments around the usage of some optimisation hooks and an intense `useEffect`. Looking good though!

2024-11-14 21:56 UTC, owencraston commented on app/components/Approvals/SnapAccountCustomNameApproval/SnapAccountCustomNameApproval.tsx
> +  );
I very much agree with your assessment/doc however the linter complains when using these non memoized functions in a useEffect. Do you suggest I disable this with eslint-disable?
<img width="1095" alt="Screenshot 2024-11-14 at 1 48 38 PM" src="https://github.com/user-attachments/assets/f5a0fc4d-dc6d-4e1c-98d0-1c91dfcfde9b">

2024-11-14 23:02 UTC, owencraston commented on app/components/Approvals/SnapAccountCustomNameApproval/SnapAccountCustomNameApproval.tsx
> +  }, [approvalRequest, internalAccounts, checkIfNameTaken]);
I have extracted the methods out of this useEffect into helper functions. Eslint wanted me to keep them wrapped in useCallbacks so I left them there but if you feel strongly about removing the useCallbacks I can disable this eslint rule.

2024-11-15 12:28 UTC, gantunesr reviewed
Looks good! Left some minor comments

2024-11-15 12:28 UTC, gantunesr commented on app/core/SnapKeyring/SnapKeyring.ts
> +export async function showAccountNameSuggestionDialog(
What do you think about moving this to another file?

2024-11-15 12:28 UTC, gantunesr commented on app/core/SnapKeyring/SnapKeyring.ts
> +        _displayConfirmation = false,
Is this still needed? I see it was only used for logging purposes and now is not even used

2024-11-15 12:28 UTC, gantunesr commented on app/core/SnapKeyring/SnapKeyring.ts
> +            throw new Error('User denied account creation');
Is it right to throw an error if the user has intentionally refused to create the account?

2024-11-15 14:57 UTC, Daniel-Cross commented on app/components/Approvals/SnapAccountCustomNameApproval/SnapAccountCustomNameApproval.tsx
> +  );
Yeah sorry, this is what we're currently discussing at the moment. Really it doesn't need the `useCallback` and can be re-rendered multiple times without issue. For now though, I think it's best to move these back inside the `useEffect` to negate the need of additional `useCallback` hooks.

Something like this maybe?

```
  useEffect(() => {
    const suggestedName = approvalRequest?.requestData.snapSuggestedAccountName;
    const initialName = suggestedName
      ? generateUniqueNameWithSuffix(suggestedName)
      : Engine.context.AccountsController.getNextAvailableAccountName(
          KeyringTypes.snap,
        );
    setAccountName(initialName);

    function generateUniqueNameWithSuffix(baseName) {
      let suffix = 1;
      let candidateName = baseName;
      while (
        internalAccounts.some(
          (account) => account.metadata.name === candidateName,
        )
      ) {
        suffix += 1;
        candidateName = `${baseName} ${suffix}`;
      }
      return candidateName;
    }
  }, [approvalRequest, internalAccounts]);
  ```

2024-11-15 20:53 UTC, owencraston commented on app/core/SnapKeyring/SnapKeyring.ts
> +        _displayConfirmation = false,
No I can remove it. I left it because the rpc method signature has this param in its signature but we are not using it now.

2024-11-15 20:55 UTC, owencraston commented on app/core/SnapKeyring/SnapKeyring.ts
> +            throw new Error('User denied account creation');
This matches the behaviour on [the extension](https://github.com/MetaMask/metamask-mobile/blob/d8d5093e662b9dec7803c7902111054a5c1d3d85/app/core/SnapKeyring/SnapKeyring.ts#L104). This error is used for the snap to know wether the account creation was successful or not.

2024-11-15 21:20 UTC, owencraston commented on app/components/Approvals/SnapAccountCustomNameApproval/SnapAccountCustomNameApproval.tsx
> +  );
good suggestion. I made this change in my latest commit.

2024-11-15 23:41 UTC, owencraston commented
confirmed it is working on the latest commit. 

https://github.com/user-attachments/assets/3920496a-4743-45cd-b74a-109fbd124f86

2024-11-19 12:03 UTC, gantunesr reviewed
one last observation

2024-11-19 13:05 UTC, Daniel-Cross approved these changes

2024-11-19 18:44 UTC, owencraston commented on app/components/Approvals/SnapAccountCustomNameApproval/SnapAccountCustomNameApproval.tsx
> +      return candidateName;
if we define the function outside then we will need to use `useCallback` which is the main issue that @Daniel-Cross had with the code.

2024-11-19 21:14 UTC, merged