fix: Jest timer error in unit test
MetaMask/metamask-mobile pull request #12230
Opened 2024-11-07 17:23 UTC by NicolasMassart

## **Description**

Fixes the following error message when runnning `app/components/Views/QRTabSwitcher/QRTabSwitcher.test.tsx` test:
```
ReferenceError: You are trying to access a property or method of the Jest environment after it has been torn down. From app/components/Views/QRTabSwitcher/QRTabSwitcher.test.tsx.

      at Timeout.now [as _onTimeout] (node_modules/react-native/jest/setup.js:28:41)
```

## **Related issues**

Fixes: N/A

## **Manual testing steps**

N/A

## **Screenshots/Recordings**

N/A

### **Before**

N/A

### **After**

N/A

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-12-04 16:53 UTC, jonybur requested changes

2024-12-04 16:53 UTC, jonybur commented on app/components/Views/QRTabSwitcher/QRTabSwitcher.test.tsx
> +jest.useFakeTimers();
Please reset the timer after the test is done, you can do this with `jest.useRealTimers()` or `jest.clearAllTimers()`

2024-12-05 11:48 UTC, jonybur approved these changes

2024-12-06 16:18 UTC, NicolasMassart commented
Added the no e2e smoke needed as the change is only touching a unit test and it would only run smoke for nothing.

2024-12-06 16:40 UTC, Gudahtt approved these changes
LGTM!

2024-12-06 16:55 UTC, merged

2024-12-06 17:01 UTC, frankvonhoven approved these changes