fix: Disable confirm button if `transactionMeta` is undefined
MetaMask/metamask-mobile pull request #12273
Opened 2024-11-13 12:38 UTC by OGPoyraz

## **Description**

This PR adds disabled button condition when `transactionMeta` is undefined.

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/11537

## **Manual testing steps**

N/A

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [X] I’ve included tests if applicable
- [X] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [X] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-11-13 13:17 UTC, matthewwalsh0 requested changes

2024-11-14 09:38 UTC, OGPoyraz commented on app/components/Views/confirmations/SendFlow/Confirm/index.js
> +      Logger.error(error, 'error while adding transaction (Confirm)');
True, added navigation back to recent screen on error.

2024-11-20 22:03 UTC, matthewwalsh0 submitted a review, later dismissed

2024-11-21 13:10 UTC, matthewwalsh0 approved these changes

2024-11-21 13:25 UTC, merged