Feat/bitcoin wallet overview
MetaMask/metamask-mobile pull request #12294
Opened 2024-11-14 20:22 UTC by owencraston

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-11-21 09:41 UTC, ccharly commented on app/core/MultiChain/test/utils.test.ts
> +    it('should return true for EOA accounts', () => {
We can probably get rid of the `should` in every tests here, see:
- https://github.com/MetaMask/contributor-docs/blob/00ca767852af400b3d9fd346df0b99ffa5b92b7d/docs/testing/unit-testing.md#use-it-to-specify-the-desired-behavior-for-the-code-under-test

2024-11-21 09:41 UTC, ccharly commented on app/core/MultiChain/test/utils.test.ts
> +
You might want to add other non-EVM addresses as well here, like in this PR:
- https://github.com/MetaMask/metamask-extension/pull/27690

Just to make sure we are future-proofing those address validation helpers.

2024-11-21 09:41 UTC, ccharly commented on app/lib/snaps/preinstalled-snaps.ts
> +  BitcoinSnap as unknown as PreinstalledSnap,
Should probably be code-fenced for flask?

2024-11-21 09:41 UTC, ccharly commented on app/selectors/accountsController.test.ts
> +
Instead of computing this here, we could use the `.id` from `btc*Account`?

2024-11-21 09:41 UTC, ccharly commented on app/selectors/accountsController.test.ts
> +      } as RootState;
Slight refactor proposal, what about having a function for this like:

```ts
function getStateWithAccount(account: InternalAccount) {
  return {
        engine: {
          backgroundState: {
            AccountsController: {
              internalAccounts: {
                accounts: {
                  [account.id]: account,
                },
                selectedAccount: account.id,
              },
            },
            KeyringController: MOCK_KEYRING_CONTROLLER,
          },
        },
      } as RootState;
}
```

This would be more DRY:

```suggestion
      const state = getStateWithAccount(btcMainnetAccount);
```

WDYT?

2024-11-21 09:41 UTC, ccharly commented on app/selectors/accountsController.ts
> +  ///: BEGIN:ONLY_INCLUDE_IF(keyring-snaps)
Should we use the `flask` feature here?

2024-11-21 09:41 UTC, ccharly commented on app/selectors/accountsController.ts
> +///: BEGIN:ONLY_INCLUDE_IF(keyring-snaps)
Should we use the `flask` feature here?

2024-11-21 09:41 UTC, ccharly commented on app/selectors/accountsController.ts
> +    return undefined;
We could also use the new helper here like:

```suggestion
    // We check for `account` here too, to make sure it will be defined
    // when calling `getFormattedAddressFromAccount`
    return account && account?.address
      ? getFormattedAddressFromAccount(account)
      : undefined;
```

2024-11-21 09:41 UTC, ccharly commented on app/util/address/index.ts
> +    : address;
Here we would need another helper IMO, maybe `toFormattedAddress` in this case? IMO that's better to have a helper rather than a ternary here (and we kinda have this pattern in several places)

2024-11-21 09:41 UTC, ccharly commented on app/util/address/index.ts
> +  }
Same here, we could use the `toFormattedAddress` helper

2024-11-21 09:41 UTC, ccharly commented on app/util/address/index.ts
> +    : address;
Same here

2024-11-21 09:41 UTC, ccharly commented on app/util/address/index.test.ts
> +  describe('non-EVM addresses', () => {
Cosmetic:
```suggestion

  describe('non-EVM addresses', () => {
```

2024-11-21 09:41 UTC, ccharly commented on app/util/address/index.test.ts
> +    it('should not checksum address and maintain original format', () => {
We could probably get rid of the `should` here too (in the entire file)

2024-11-21 09:41 UTC, ccharly commented on app/util/address/index.test.ts
> +      expect(formatAddress(mockBtcAddress, 'full')).toBe(mockBtcAddress);
Cosmetic: Just to match the same "pattern" than for the EVM block:

```suggestion
      const expectedValue = 'bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh';
      expect(formatAddress(mockBtcAddress, 'full')).toBe(expectedValue);
```

2024-11-21 22:26 UTC, owencraston commented on app/components/Views/EditAccountName/__snapshots__/EditAccountName.test.tsx.snap
> +            placeholder="0x0...0x0"
I need to look into this. I removed the address validation so id you pass an invalid address we still parse it in the format you specified. This should not matter in prod since all of our addresses come from the accounts controller and should be valid but the tests will need updating.

2024-11-21 22:26 UTC, owencraston commented on app/components/Views/Wallet/index.tsx
> +        selectedInternalAccount || '',
True, let me come up with something that makes more sense.

2024-11-21 22:51 UTC, owencraston commented on app/components/Views/Wallet/index.tsx
> +        selectedInternalAccount || '',
I added a null check for this property. In practice this should never be undefined but the return type of the selector is undefined if we cannot find the selected account id in the accounts list. This occurred a few times in the past so the core team wanted us to handle this case without crashing the app. I have no seen this be an issue in recent weeks though.

2024-11-21 23:17 UTC, owencraston commented on app/components/hooks/useAccounts/useAccounts.ts
> +          : address;
Love it. I implemented this in the latest commit.

2024-11-21 23:19 UTC, owencraston commented on app/components/hooks/useAccounts/useAccounts.ts
> +          .toHexString();
This will need to be done when in a later change when we integrate the BalanceController on mobile. I will add a comment here.

2024-11-21 23:34 UTC, owencraston commented on app/core/SnapKeyring/constants.ts
> +export enum MultichainNetworks {
yeah good call. I created that before I created core/MultiChain but this is a better place for it.

2024-11-22 00:02 UTC, owencraston commented on app/core/MultiChain/utils.ts
> +  return !isEthAddress(address) && !isBtcMainnetAddress(address);
thanks for pointing this out. I have made these changes in the latest commit.

2024-11-22 00:02 UTC, owencraston commented on app/core/MultiChain/test/utils.test.ts
> +    it('should return true for EOA accounts', () => {
👍

2024-11-22 00:12 UTC, owencraston commented on app/core/MultiChain/test/utils.test.ts
> +
I added a test for SOL and it seems to work.

2024-11-22 00:13 UTC, owencraston commented on app/lib/snaps/preinstalled-snaps.ts
> +  BitcoinSnap as unknown as PreinstalledSnap,
Likely yes, I need to see if this is needed since all of snaps is code fenced and the npm package is still included un the package.json.

2024-11-22 00:38 UTC, owencraston commented on app/util/address/index.ts
> +    : address;
agreed

2024-11-22 00:50 UTC, owencraston commented on app/selectors/accountsController.ts
> +///: BEGIN:ONLY_INCLUDE_IF(keyring-snaps)
we are not using the flask build type but instead the keyring-snaps feature flag which we can then move into the flask build later on.

2024-11-22 00:50 UTC, owencraston commented on app/selectors/accountsController.ts
> +  ///: BEGIN:ONLY_INCLUDE_IF(keyring-snaps)
we are not using the flask build type but instead the keyring-snaps feature flag which we can then move into the flask build later on.

2024-11-22 00:51 UTC, owencraston commented on app/components/UI/Navbar/index.js
> +///: BEGIN:ONLY_INCLUDE_IF(keyring-snaps)
we are not using the flask build type but instead the keyring-snaps feature flag which is included in the flask build. We can then move into the main build later on.

2024-11-22 00:54 UTC, owencraston commented on app/selectors/accountsController.test.ts
> +
very true, I should have seen that.

2024-11-22 00:55 UTC, owencraston commented on app/selectors/accountsController.test.ts
> +      } as RootState;
Love it. the above tests are using a pre defined mock so it was not as needed for them but in this case it makes perfect sense. I have made this change in the latest commit.

2024-11-22 01:23 UTC, owencraston commented on app/lib/snaps/preinstalled-snaps.ts
> +  BitcoinSnap as unknown as PreinstalledSnap,
Okay I code fenced it in the latest commit

2024-11-22 02:39 UTC, owencraston commented on app/components/Views/ConnectQRHardware/index.test.tsx
> +    shortenedAddress: '0x4x67...1210',
Previously this would pass because these were technically invalid addresses so when we ran it through the following function..

```ts
type FormatAddressType = 'short' | 'mid' | 'full';
export const formatAddress = (rawAddress: string, type: FormatAddressType) => {
  let formattedAddress = rawAddress;

  if (!isValidAddress(rawAddress)) {
    return rawAddress;
  }

  if (type && type === 'short') {
    formattedAddress = renderShortAddress(rawAddress);
  } else if (type && type === 'mid') {
    formattedAddress = renderSlightlyLongAddress(rawAddress);
  } else {
    formattedAddress = renderFullAddress(rawAddress);
  }

  return formattedAddress;
};
```

... it would return the entire address but in practice these values are always rendered in the shortened form. Here is a screenshot from production...

![IMG_1592](https://github.com/user-attachments/assets/4cf84bd6-016c-4c1c-b075-8d888f64e1b2)

All this to say that this test was not really very accurate before.

2024-11-26 04:26 UTC, owencraston commented on app/reducers/multichain/index.ts
> +  bitcoinSupportEnabled: false,
Change these values to enable this feature. These are added because ...
1. BTC will likely live under a feature flag when it is ready for release the same way that it does on extension. We can reuse all of this code when we are ready to add the toggle to the UX.
2. To hide this feature. Even those this feature is hidden behind flask, we want to be extra safe with this feature and since we are merging code that is not fully functional I believe it should be hidden by default.

2024-11-26 04:27 UTC, owencraston commented on app/store/persistConfig.ts
> +  blacklist: ['onboarding', 'rpcEvents', 'accounts', 'multichainSettings'],
By not persisting these settings we as developers are able to easily change thee values in this state for testing purposes.

2024-11-26 14:19 UTC, Daniel-Cross approved these changes, later dismissed
Looks good, and ready to merge once the other comments are addressed!

2024-11-26 20:45 UTC, boneskull reviewed
cc @naugtur

2024-11-26 20:45 UTC, boneskull commented on package.json
> +    "bitcoin-address-validation": "^2.2.3",
Can this be pinned?  Can its transitive deps also be pinned (via resolutions or w/e)?

There doesn't seem to be too many protections here against this package or its dependencies shipping malicious code.  Why doesn't Socket mention this package?

Above, it's mentioned that this package is temporary.  Can we get away with a) _not_ shipping using this package, and b) deferring whatever feature uses it until later?

2024-11-26 21:34 UTC, georgewrmarshall approved these changes, later dismissed
Approved on behalf of @MetaMask/design-system-engineers 
- Checked updates to `PickerNetwork` ✅ 

Only approving for component-library code owners please also get reviews from relevant teams 🙏

2024-11-26 21:52 UTC, owencraston commented on package.json
> +    "bitcoin-address-validation": "^2.2.3",
Thank you @boneskull for the review. I have pinned these versions in [this commit here](https://github.com/MetaMask/metamask-mobile/pull/12294/commits/74c833ed4f73664d16dad294976a190f1e962912). This package is not temporary and is already used [in the extension](https://github.com/MetaMask/metamask-extension/pull/27690). More information on why this was added [here](https://github.com/MetaMask/metamask-mobile/pull/12294#discussion_r1851619279). As far as the security concerns I am not sure what to say. Are there any steps you recommend to alleviate your concerns? Looking at the [snyc advisor](https://snyk.io/advisor/npm-package/bitcoin-address-validation) I dont see any major red flags.

2024-11-27 12:34 UTC, gantunesr reviewed
Good job. Some notes beyond the comments,

1. Can you rename the directory `MultiChain` to `Multichain`?
2.

2024-11-27 12:34 UTC, gantunesr commented on app/util/address/index.ts
> +  return strings('transactions.tx_details_not_available');
I know you didn't write this method but I don't understand the reasoning here. It either returns the formatted address or the copy `Not available` which is not clear from the identifier `transactions.tx_details_not_available`. No action needed since this was here before but just pointing that out in case the original author sees it

2024-11-27 12:34 UTC, gantunesr commented on app/util/address/index.test.ts
> +    it('should return 0xC4955 before ellipsis and 4D272 after the ellipsis', () => {
nit

```suggestion
    it('returns 0xC4955 before ellipsis and 4D272 after the ellipsis', () => {
```

2024-11-27 12:34 UTC, gantunesr commented on app/store/persistConfig.ts
> +  blacklist: ['onboarding', 'rpcEvents', 'accounts', 'multichainSettings'],
Can you remind me about this? I don't fully remember what is the `blacklist`

2024-11-27 12:34 UTC, gantunesr commented on app/util/test/accountsControllerTestUtils.ts
> +  accountType: BtcAccountType | EthAccountType = EthAccountType.Eoa,
Do you think there's a way of making this more generic? Imagine support more chains beyond Bitcoin and Solana

2024-11-27 12:34 UTC, gantunesr commented on locales/languages/en.json
> +    "add_bitcoin_account_mainnet": "Add a new Bitcoin Account (Beta)"
I know this is how it's in extension too but I just noticed that the words `Beta` and `Testnet` are in parentheses. Should it be `Add a new Bitcoin Testnet Account`? cc @eriknson

2024-11-27 12:34 UTC, gantunesr commented on app/selectors/accountsController.ts
> + * A selector that returns whether the the user has already created a Bitcoin mainnet account
nit
```suggestion
 * A selector that returns whether the user has already created a Bitcoin mainnet account
```

2024-11-27 12:34 UTC, gantunesr commented on app/selectors/accountsController.ts
> + * A selector that returns whether the the user has already created a Bitcoin testnet account
nit
```suggestion
 * A selector that returns whether the user has already created a Bitcoin testnet account
```

2024-11-27 12:34 UTC, gantunesr commented on app/core/MultiChain/utils.ts
> +import { toChecksumHexAddress } from '@metamask/controller-utils';
I see that this file has duplicated code from other codebases, we should have this in a shared module to be consumed by different clients

2024-11-27 12:34 UTC, gantunesr commented on app/components/Views/EditAccountName/__snapshots__/EditAccountName.test.tsx.snap
> +            placeholder="0x0...0x0"
I agree that this seems like an odd change during the snapshots update, do you know what is the exact cause?

2024-11-27 14:25 UTC, wachunei submitted a review, later dismissed
Ramp changes LGTM

2024-11-27 16:24 UTC, brianacnguyen approved these changes, later dismissed

2024-11-27 22:54 UTC, boneskull commented on package.json
> +    "bitcoin-address-validation": "^2.2.3",
Currently, there's nothing about the code that is a red flag, but that's not the problem.

Even though extension uses this package, extension has more protections against supply-chain attacks than mobile (and AFAIK, we're working on improving that situation).

That leads me to think adding _any_ production dep that is not wholly controlled by MM to this project is a significant risk (though @naugtur may disagree) and must be weighed carefully against the value it provides.

Socket's enabled in this project, but we're leaning on it pretty heavily. While the Socket team does great work, it just hasn't been around long enough for me to feel comfortable about that.

Ensuring that a new version of this package (and its transitive deps) won't creep into the build artifacts is probably good enough for now.  Besides, that's why we have @MetaMask/supply-chain reviewing the dependency manifest.  😄

2024-11-28 02:30 UTC, owencraston commented on app/store/persistConfig.ts
> +  blacklist: ['onboarding', 'rpcEvents', 'accounts', 'multichainSettings'],
All items in this blacklist will not be persisted. The persistence is managed by redux-persist and automatically saves all items in state. The reason we want this blacklisted (for now) is so that as a developer you can easily switch these values from false to true and vice versa. If these values get persisted then they will be saved as false and you wont be able to turn on this feature on without uninstalling and re installing.

2024-11-28 02:33 UTC, owencraston commented on locales/languages/en.json
> +    "add_bitcoin_account_mainnet": "Add a new Bitcoin Account (Beta)"
I'll this up to Erik since this content matches the current extension copy.

2024-11-28 02:53 UTC, owencraston commented on app/core/MultiChain/utils.ts
> +import { toChecksumHexAddress } from '@metamask/controller-utils';
great idea. I have a made an issue to track this work: https://github.com/MetaMask/accounts-planning/issues/735

2024-11-28 02:57 UTC, owencraston commented on app/util/address/index.ts
> +  return strings('transactions.tx_details_not_available');
yeah I thought this was weird when I was looking at it but did not want to change it since I was worried it would have side effects.

2024-11-28 02:59 UTC, owencraston commented on app/util/address/index.test.ts
> +    it('should return 5 characters before ellipsis and 4 final characters of the address after the ellipsis', () => {
addressed in [this](https://github.com/MetaMask/metamask-mobile/pull/12294/commits/6af53412493d5f67e7918b59ed0e6291ae1258c1) commit.

2024-11-28 02:59 UTC, owencraston commented on app/util/address/index.test.ts
> +    it('should return 0xC4955 before ellipsis and 4D272 after the ellipsis', () => {
addressed in [this](https://github.com/MetaMask/metamask-mobile/pull/12294/commits/6af53412493d5f67e7918b59ed0e6291ae1258c1) commit.

2024-11-28 03:00 UTC, owencraston commented on app/selectors/accountsController.ts
> + * A selector that returns whether the the user has already created a Bitcoin mainnet account
addressed in [this](https://github.com/MetaMask/metamask-mobile/pull/12294/commits/6af53412493d5f67e7918b59ed0e6291ae1258c1) commit.

2024-11-28 03:00 UTC, owencraston commented on app/selectors/accountsController.ts
> + * A selector that returns whether the the user has already created a Bitcoin testnet account
addressed in [this](https://github.com/MetaMask/metamask-mobile/pull/12294/commits/6af53412493d5f67e7918b59ed0e6291ae1258c1) commit.

2024-11-28 03:36 UTC, owencraston commented on app/components/Views/EditAccountName/__snapshots__/EditAccountName.test.tsx.snap
> +            placeholder="0x0...0x0"
I have figured out the root cause. This component calls `formatAddress`. I modified this function to remove address validation. Previously there was a block of code with the following logic..

```ts
 if (!isValidAddress(rawAddress)) {
    return rawAddress;
  }
```

Since the mock address passed into this test was invalid an address (0x0), it used to simply return the original address (0x0). I have modified this test to use a real address to better reflect the real world.

2024-11-28 03:45 UTC, owencraston commented on app/components/Views/EditAccountName/__snapshots__/EditAccountName.test.tsx.snap
> +            placeholder="0x0...0x0"
For reference this is what this component looks like in production. As you can see the input field is rendering most of the address with some concatenation. This matches what we would expect from calling `formatAddress(selectedAccount?.address, 'mid')`

<img src="https://github.com/user-attachments/assets/65c78d11-b542-437a-ab79-550ff510bc7c" width="300" width="500" />

2024-11-28 04:30 UTC, owencraston commented
@SocketSecurity ignore npm/@metamask/bitcoin-wallet-snap@0.8.2

2024-11-28 13:53 UTC, Daniel-Cross approved these changes, later dismissed
Looks good!

2024-11-29 09:12 UTC, Daniel-Cross approved these changes, later dismissed
Looks good!

2024-11-29 19:09 UTC, wachunei approved these changes, later dismissed

2024-12-02 00:04 UTC, gantunesr approved these changes, later dismissed

2024-12-02 13:49 UTC, GuillaumeRx approved these changes, later dismissed

2024-12-02 16:42 UTC, brianacnguyen commented on app/component-library/components/Pickers/PickerNetwork/PickerNetwork.types.ts
> +  disabled?: boolean;
can you change this to `isDisabled` to align with best practices?

2024-12-02 16:42 UTC, brianacnguyen requested changes
1 small change requested that I didnt catch last time (my apologies)

2024-12-02 17:28 UTC, GuillaumeRx submitted a review, later dismissed

2024-12-02 17:28 UTC, brianacnguyen submitted a review, later dismissed

2024-12-02 17:32 UTC, gantunesr approved these changes, later dismissed

2024-12-02 17:51 UTC, wachunei approved these changes, later dismissed

2024-12-02 17:54 UTC, owencraston commented on package.json
> +    "bitcoin-address-validation": "^2.2.3",
Thank you for looking.

2024-12-02 18:08 UTC, Daniel-Cross submitted a review, later dismissed

2024-12-02 18:33 UTC, amitabh94 approved these changes, later dismissed
LGTM on behalf of staking team!

2024-12-02 18:37 UTC, gambinish commented on app/components/UI/Stake/hooks/useBalance.ts
> +      ),
nit: This seems like an odd formatting diff

2024-12-02 18:38 UTC, owencraston commented on app/components/UI/Stake/hooks/useBalance.ts
> +      ),
this was auto changed when I ran the format command.

2024-12-02 18:45 UTC, georgewrmarshall approved these changes

2024-12-02 18:45 UTC, wachunei approved these changes

2024-12-02 18:47 UTC, gantunesr approved these changes

2024-12-02 18:52 UTC, amitabh94 approved these changes

2024-12-02 18:53 UTC, GuillaumeRx approved these changes

2024-12-02 18:54 UTC, gambinish approved these changes
Approving from Assets. Only thing that gives me pause is that there might be some overlap/conflicts with https://github.com/MetaMask/metamask-mobile/pull/12431

I synced with the UX team as well here, will leave it to them to flag anything. It might be worth it to check out that branch as well to see if there's anything that might break or need these new functions.

2024-12-02 19:03 UTC, vinnyhoward approved these changes

2024-12-02 19:12 UTC, ejwessel approved these changes

2024-12-02 19:29 UTC, brianacnguyen approved these changes

2024-12-02 19:56 UTC, owencraston commented
@gambinish Great call out. I am going to meet with @vinnyhoward to discuss how are two teams can divide and concur on this project.

2024-12-02 19:56 UTC, Daniel-Cross approved these changes

2024-12-02 19:58 UTC, owencraston commented
The confirmations e2e suite is failing but it is not related to this PR and is also failing on main.

2024-12-02 20:05 UTC, matthewwalsh0 approved these changes

2024-12-02 20:21 UTC, merged