fix: updated failing test for multichain on feature flag removal
MetaMask/metamask-mobile pull request #12397
Opened 2024-11-22 16:05 UTC by NidhiKJha

This PR is to update the failing e2e on removal of multichain feature flag

Note: This PR is based on failing e2e reports on bitrise https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/79a0b587-b4c9-4b3b-a642-8917724ed36f?tab=tests

## **Related issues**

Fixes:

## **Manual testing steps**

1. Create the test build
2. Run the test using `yarn test:e2e:ios:debug:run e2e/specs/permission-systems/permission-system-revoke-single-account.spec.js`

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-11-22 17:52 UTC, EtherWizard33 commented on app/util/networks/index.js
> +export const isMultichainVersion1Enabled = true;
this went from a === check to an assignment, hardcoding them and bypassing the feature flag system, 
since those flags are hardcoded it also explains why it ran on bitrise

setting them temporarily in the bitrise.yml file can be used as a way to run e2e tests with a specific value
as mentioned, if using the bitrise.yml file, it should not be pushed to main, if a pr is to be merged to main the bitrise file should not be part of the pr (should remain unchanged at time of merge)

2024-11-23 00:41 UTC, cortisiko requested changes
Thanks for updating the test!
I noticed that the connected account notification lags a bit on android compared to iOS. I recommend putting a `await TestHelpers.delay(2000);` [here](https://github.com/MetaMask/metamask-mobile/blob/multichain-e2e/e2e/pages/Browser/ConnectedAccountsModal.js#L65) which allows the tests to wait for a bit until the toast disappears before continuing. 

 I recommend you run all the e2e tests in the permissions-system folder for iOS and Android locally. The test steps may also need to be updated since you are changing the page object.  IF they both pass, feel free to kick off the tests on bitrise. Both smoke and regression ( pr_regression_pipeline)

2024-11-23 00:41 UTC, cortisiko commented on e2e/pages/Browser/ConnectedAccountsModal.js
> +  get managePermissionsButton() {
Select elements by ID instead of text. It would be best if you created a new testID selector for this and store it in the TestID selector object for [connectedAccounts](https://github.com/MetaMask/metamask-mobile/blob/multichain-e2e/e2e/selectors/Browser/ConnectedAccountModal.selectors.js#L13). 

You can read more here on testIDs here: https://github.com/MetaMask/contributor-docs/blob/main/docs/testing/e2e/mobile-e2e-guidelines.md#test-ids

2024-11-23 00:41 UTC, cortisiko commented on e2e/pages/Browser/ConnectedAccountsModal.js
> +  get disconnectButton() {
Same as below/above. IDs over Text

2024-11-23 00:41 UTC, cortisiko commented on e2e/pages/Browser/ConnectedAccountsModal.js
> +  get disconnectAllAccountsAndNetworksButton() {
So a couple of things: 
1. A getter was already created to disconnect all accounts from a dapp: https://github.com/MetaMask/metamask-mobile/blob/multichain-e2e/e2e/pages/Browser/ConnectedAccountsModal.js#L21, you can reuse it but you will need to update the selector strategy. That is select the elementByID instead of Text and use the already existing selector string: https://github.com/MetaMask/metamask-mobile/blob/multichain-e2e/e2e/selectors/Browser/ConnectedAccountModal.selectors.js#L16

2, All that is needed is setting the testID property to the [button component.](https://github.com/MetaMask/metamask-mobile/blob/multichain-e2e/app/components/UI/PermissionsSummary/PermissionsSummary.tsx#L435 )

2024-11-23 00:41 UTC, cortisiko commented on e2e/pages/Browser/ConnectedAccountsModal.js
> +  get disconnectButton() {
Steps: 
Create a testID selector and store it in the TestID selector object for [connectedAccounts](https://github.com/MetaMask/metamask-mobile/blob/multichain-e2e/e2e/selectors/Browser/ConnectedAccountModal.selectors.js#L13).
Set the button component with the testID property and use your created selector

2024-11-23 00:41 UTC, cortisiko commented on e2e/pages/Browser/ConnectedAccountsModal.js
> +  async tapDisconnectAllAccountsAndNetworksButton() {
There is already a `tapDisconnectAllButton()`. You don't need to create a new method for this.

2024-11-25 15:22 UTC, NidhiKJha commented on e2e/pages/Browser/ConnectedAccountsModal.js
> +  async tapDisconnectAllAccountsAndNetworksButton() {
It's using `disconnect_all_accounts` as the key which is not the copy on button. Hence, I created a new one. If we are going to use ID, then we can update it

2025-03-02 15:31 UTC, closed without merging