feat: snaps dynamic UI
MetaMask/metamask-mobile pull request #12429
Opened 2024-11-26 14:19 UTC by Daniel-Cross

## **Description**

This PR integrates the Snaps Dynamic UI controller and components to allow different dialog prompts to show on the screen.

## **Related issues**

Fixes: https://github.com/MetaMask/accounts-planning/issues/738

## **Manual testing steps**

1. Make a Flask build
2. Go to: https://metamask.github.io/snaps/test-snaps/latest/ in the in app browser
3. Connect the Snaps Dialog snap
4. Try to launch the different snaps prompts.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-12-05 17:13 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapInterfaceContext.tsx
> +  const updateStateDebounced = debounce(
We can remove all of the debouncing and throttling logic, we discovered it wasn't necessary in the extension at least.

2024-12-19 12:11 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapInterfaceContext.tsx
We should sync this file with https://github.com/MetaMask/metamask-extension/blob/a1b41c4e49497805f437011b643e99cf1680ebb2/ui/contexts/snaps/snap-interface.tsx

There has been a bunch of changes since this was committed originally

2024-12-19 12:15 UTC, FrederikBolding commented on app/core/Snaps/SnapsMethodMiddleware.ts
> +    getInterfaceState: (...args: any) =>
Missing `getInterfaceContext`

2024-12-19 12:15 UTC, FrederikBolding commented on package.json
> -    "@metamask/swaps-controller": "^11.0.0",
?

2024-12-19 12:16 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/file-input.ts
> +export const fileInput: UIComponentFactory<FileInputElement> = ({
It's unclear to me how many of these components actually work? I would prefer we only add the ones that do and write up a list of remaining components

2024-12-19 12:17 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +      case SnapDialogTypes.CUSTOM:
Custom dialogs can define their own buttons. We will need to support that instead of hardcoding their text and the logic to confirm/cancel

2024-12-19 12:19 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapInterfaceContext.tsx
> +type StateType = Record<
Can't we just use `InterfaceState` from `snaps-sdk`?

2024-12-19 12:21 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/utils.ts
> +      return element;
Do we not need to unescape HTML entities here to allow usage of `&bull` etc?

2024-12-19 12:22 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/utils.ts
> +export enum TextWrap {
Do these not exist as DS values in mobile? Why are we defining them here?

2024-12-19 12:23 UTC, FrederikBolding commented on app/components/UI/Snaps/SnapUIInput/Index.tsx
> +      (inputRef.current.children[0] as HTMLInputElement).focus();
This was bugged and is fixed on the extension

2024-12-19 12:23 UTC, FrederikBolding commented on app/core/Engine/Engine.ts
> +      AssetsContractController,
I don't follow the changes here that are unrelated to Snaps?

2024-12-19 14:12 UTC, Daniel-Cross commented on app/core/Snaps/SnapsMethodMiddleware.ts
> +    getInterfaceState: (...args: any) =>
Added

2024-12-19 14:21 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/components/file-input.ts
> +export const fileInput: UIComponentFactory<FileInputElement> = ({
Removed a bunch that aren't used in the snaps dialogs

2024-12-19 14:22 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +      case SnapDialogTypes.CUSTOM:
Is there a Type for the expected data on these custom buttons? I took a look at the extension code but it's much different to how we implement on Mobile so it's hard to make sense of what data should be expected for the custom buttons. Also, it doesn't seem to have any custom data coming from the snaps when I search for the button content.

2024-12-19 14:31 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/utils.ts
> +      return element;
I removed it as we don't seem to have this package installed on mobile, and it isn't relevant for React Native, just React.js. If we want to handle HTML in RN we would need a package such as this:

https://www.npmjs.com/package/react-native-render-html

2024-12-19 14:32 UTC, Daniel-Cross commented on app/core/Engine/Engine.ts
> +      AssetsContractController,
Cleaned up

2024-12-19 15:21 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/utils.ts
> +      return element;
Certain Snaps rely on being able to use encoded HTML entities. 

E.g. a Snap passing `foo &copy; bar &ne; baz &#x1D306; qux` should display `foo © bar ≠ baz 𝌆 qux'``

2024-12-19 15:25 UTC, FrederikBolding commented on app/components/UI/FormTextField/index.tsx
> +export const FormTextField = ({
Did this not exist on mobile? Is there an alternative we should be using instead?

2024-12-19 15:27 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapUIRenderer.tsx
> +const SnapUIRendererComponent = ({
We should make sure that all of the CSS rules from the extension are applied to the renderer content: https://github.com/MetaMask/metamask-extension/blob/main/ui/components/app/snaps/snap-ui-renderer/index.scss

2024-12-19 15:30 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +      case SnapDialogTypes.CUSTOM:
The buttons should be extracted from `Container -> Footer`.
https://github.com/MetaMask/snaps/blob/main/packages/snaps-sdk/src/jsx/components/Container.ts
https://github.com/MetaMask/snaps/blob/main/packages/snaps-sdk/src/jsx/components/Footer.ts

On the extension we have some fallback buttons if the Snap doesn't define some, the logic is somewhat complicated, but can be found here: https://github.com/MetaMask/metamask-extension/blob/main/ui/components/app/snaps/snap-ui-renderer/components/footer.ts

2024-12-21 15:21 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapInterfaceContext.tsx
Updated to reflect this file

2024-12-21 15:37 UTC, Daniel-Cross commented on app/components/UI/Snaps/SnapUIInput/Index.tsx
> +      (inputRef.current.children[0] as HTMLInputElement).focus();
Updated based on the extension code

2025-01-07 14:21 UTC, Daniel-Cross commented on app/components/UI/FormTextField/index.tsx
> +export const FormTextField = ({
We don't really handle 'forms' on mobile. It's just basic text inputs that need to be wrapped in `divs` so they can be styled.

2025-01-07 14:23 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapUIRenderer.tsx
> +const SnapUIRendererComponent = ({
Not really sure how to implement this but we can discuss it.

2025-01-16 17:21 UTC, brianacnguyen requested changes
The change to the ButtonPrimary would effectively remove startIconName and  endIconName into being passed down, which is not correct. What was your intention behind the change?

2025-01-17 09:27 UTC, FrederikBolding commented on app/component-library/components/Buttons/Button/variants/ButtonPrimary/ButtonPrimary.tsx
> +  startIconName,
As @brianacnguyen pointed out, what is the goal of this change?

2025-01-17 09:27 UTC, FrederikBolding commented on app/component-library/components/Buttons/Button/variants/ButtonPrimary/__snapshots__/ButtonPrimary.test.tsx.snap
>  >
?

2025-01-17 09:32 UTC, FrederikBolding commented on app/core/Engine/Engine.ts
> +          'PhishingController:maybeUpdateState',
There's a bunch of missing actions here that would cause the controller to throw for certain operations and inputs
https://github.com/MetaMask/metamask-extension/blob/main/app/scripts/metamask-controller.js#L1557-L1559

2025-01-17 09:33 UTC, FrederikBolding commented on app/core/Permissions/specifications.js
> +  'snap_getInterfaceContext',
```suggestion
  'snap_getInterfaceContext',
  'snap_resolveInterface',
```

2025-01-17 09:34 UTC, FrederikBolding commented on app/core/Snaps/SnapsMethodMiddleware.ts
> +      ).state,
```suggestion
      ).state,
       resolveInterface: controllerMessenger.call.bind(
      controllerMessenger,
      'SnapInterfaceController:resolveInterface',
      origin,
    ),
```

2025-01-17 09:34 UTC, FrederikBolding commented on app/selectors/snaps/interfaceController.ts
> +const getInterfaces = (state: any) =>
Is there not a type for the root state?

2025-01-17 09:35 UTC, FrederikBolding commented on package.json
> +    "html-entities": "^2.5.2",
What's the reasoning for using a different package than we use on the extension?

2025-01-17 09:43 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/value.ts
> +export const value: UIComponentFactory<ValueElement> = ({ element: e }) => ({
This doesn't exist on mobile as far as I can tell

2025-01-17 09:44 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/types.ts
> +  promptLegacyProps?: {
IMO we don't need to spend too much time supporting these

2025-01-17 09:45 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/text.ts
> +  props: element.props as ExtendedTextProps,
This doesn't seem safe, we do a lot of remapping of these props on the extension-side

2025-01-17 09:46 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/row.ts
> +  element: 'Row',
This component doesn't exist on mobile

2025-01-17 09:48 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/input.ts
> +export const input: UIComponentFactory<InputElement> = ({
Would be great to update this to the latest logic from the extension

2025-01-17 09:49 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/icon.ts
> +    name: element.props.name,
We should consider the name being invalid here, same applies to sizing and color, we have remapping of these values on the extension for that reason

2025-01-17 09:49 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/heading.ts
> +    title: e.props.children,
We should add support for sizing here

2025-01-17 09:53 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/container.ts
> +      element: child as JSXElement,
Seems like a bunch of params aren't being passed down to the children here

2025-01-17 09:54 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapInterfaceContext.tsx
> +  const handleFileChange: HandleFileChange = (name, file, form) => {
Since we don't have the file input we can remove this and `uploadFile` for now

2025-01-17 09:58 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapUIRenderer.tsx
> +const SnapUIRendererComponent = ({
Unresolving this as it doesn't seem resolved, we use the CSS file to standardize the spacing between the components and implement more complicated layout rules. We need to figure out a path to do something similar on mobile

2025-01-17 09:58 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapUIRenderer.tsx
> +    // oldState {"content": {"key": null, "props": {"children": [Array]}, "type": "Box"}, "context": null, "snapId": "npm:@metamask/dialog-example-snap", "state": {}} newState undefined
```suggestion
```

2025-01-17 10:02 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/bold.ts
> +    ...(element.props as ExtendedTextProps),
What additional props are we trying to pass here?

2025-01-17 10:04 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/address.ts
> +  props: element.props as ExtendedAddressProps,
Looks like none of the props that Snaps are passing are supported in the address component

We also will need to support CAIP-10 addresses in addition to ethereum addresses

Maybe worth omitting the address component for now?

2025-01-17 10:05 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/SnapInterfaceContext.test.tsx
This file seems like it should be in the folder above it

2025-01-17 10:05 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/Heading.test.ts
Can we name the test files the same as the file they are testing?

2025-01-17 10:05 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/Icon.test.ts
Can we name the test files the same as the file they are testing?

2025-01-17 10:08 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/utils.ts
> +// const colors = Theme.colors;
```suggestion
```

Do we need to keep this?

2025-01-17 10:10 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/utils.ts
> +  if (!(type in COMPONENT_MAPPING)) {
```suggestion
  if (!hasProperty(COMPONENT_MAPPING, type)) {
```

2025-01-17 10:10 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/utils.ts
> +  if (typeof mappingFunction !== 'function') {
When would this be the case?

2025-01-17 10:13 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/utils.ts
> +export enum TextWrap {
I'm still super confused by this, we don't seem to be using all of this. What does mobile use for defining standardized styles like this then?

2025-01-17 10:14 UTC, FrederikBolding commented on app/components/Approvals/Snaps/helpers/constants/index.ts
> +export const getDelineatorTitle = (type: DelineatorType) => {
As far as I can tell this isn't used anywhere

2025-01-17 10:18 UTC, FrederikBolding commented on app/components/UI/Snaps/SnapUIInput/Index.tsx
Is the preferred pattern on mobile to have `Index` files for every component?

Seems harder to find things then, but maybe I'm missing something

2025-01-17 10:18 UTC, FrederikBolding commented on app/components/UI/Snaps/SnapUILink/index.tsx
> +export const SnapUILink: React.FC<SnapUILinkProps> = ({ href, children }) => (
We should make a note that this component should show a modal for links when not using preinstalled Snaps

2025-01-17 10:23 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/box.ts
> +    ...(element.props as ViewProps),
What additional props are we trying to support here?

2025-01-17 10:25 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/button.ts
> +  return {
We'll need to map over the children and remap props here

2025-01-17 10:25 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/card.ts
> +  element: 'Card',
You've added `SnapUICard` but this seems to use another component?

2025-01-17 10:26 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUICard/index.tsx
> +        <Image
This should probably be `SnapUIImage`

2025-01-17 10:28 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/footer.ts
> +      element: 'SnapUIFooterButton',
Seems like we haven't implemented this component

2025-01-17 10:43 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +      case SnapDialogTypes.CUSTOM:
This has also not been addressed yet, unresolving.

2025-01-17 12:15 UTC, Daniel-Cross commented on app/selectors/snaps/interfaceController.ts
> +const getInterfaces = (state: any) =>
Not sure, probably. I'll take a look

2025-01-17 12:16 UTC, Daniel-Cross commented on package.json
> +    "html-entities": "^2.5.2",
I'm not sure the one you use on extension is React Native friendly. We can try it but it specifically supports only React.

2025-01-17 12:24 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/components/value.ts
> +  element: 'ConfirmInfoRowValueDouble',
Could be called `infoValue` or something similar

2025-01-17 12:28 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/components/text.ts
Check extension code to implement the `Text` file from there

2025-01-17 12:30 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/components/row.ts
> +  element: 'Row',
`Row` doesn't exist on mobile

2025-01-17 12:31 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/components/row.ts
> +  element: 'Row',
Called something different on mobile possibly?

2025-01-17 12:36 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/components/icon.ts
> +    name: element.props.name,
Defaults values needed for fallback

2025-01-17 12:38 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/components/container.ts
> +      element: child as JSXElement,
Add to `templateChildren`:

```
  useFooter,
  onCancel,
  promptLegacyProps,
  t,
  ```

2025-01-17 12:40 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/components/address.ts
> +  props: element.props as ExtendedAddressProps,
Update based on extension file but omit this file for now

2025-01-17 12:52 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/components/button.ts
> +  return {
Check extension file and compare

2025-01-17 12:53 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/components/card.ts
> +  element: 'Card',
Two possible Card files `SnapUICard` and `Card`. `Card` currently called possibly by mistake.

2025-02-04 14:31 UTC, GuillaumeRx requested changes

2025-02-04 14:31 UTC, GuillaumeRx commented on app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.types.ts
> +  type?: ButtonType;
I'm not sure this should use `ButtonType` from `snaps-sdk`

2025-02-04 14:31 UTC, GuillaumeRx commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +}
This could be replaced with https://github.com/MetaMask/snaps/blob/2bf545271ab74a2f9e4fa6ece7ec33f197ea593a/packages/snaps-rpc-methods/src/restricted/dialog.ts#L38-L43

2025-02-04 14:31 UTC, GuillaumeRx commented on app/components/Approvals/Snaps/SnapUIFooterButton/SnapUIFooterButton.tsx
> +  };
I don't understand why this exists, what if a snap calls it's buttons `cancel` and `confirm` ? If these are buttons defined by the snap we shouldn't call `onCancel` or `onConfirm`

2025-02-04 14:31 UTC, GuillaumeRx commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapUIRenderer.tsx
> +  const useFooter = content?.props?.children?.[1]?.type === 'Footer';
This should not be used like this, `useFooter` should come from the props and should be set to true only if the dialog is a custom dialog, we don't allow footers in other dialog types

2025-02-04 14:31 UTC, GuillaumeRx commented on app/components/UI/Snaps/SnapUILink/index.tsx
> +export const SnapUILink: React.FC<SnapUILinkProps> = ({ href, children }) => (
Unresolving since it still doesn't have a modal

2025-02-05 16:55 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +}
Changed this

2025-02-06 08:54 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIFooterButton/SnapUIFooterButton.tsx
> +  const hideSnapBranding = true;
This is a flag on the state in `SnapController.snaps`

2025-02-06 08:55 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapInterfaceContext.tsx
> +  const [focusedInput, setFocusedInput] = useState<string | null>(null);
We are intentionally not using state for this in the extension because it causes a ton of unnecessary re-renders. Why was this changed?

2025-02-06 08:56 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapUIRenderer.tsx
> +const SnapUIRendererComponent = ({
This is still not resolved, if we cannot resolve it as part of this PR we should create a ticket to look into it. The Snaps UI system cannot go into production without matching the designs

2025-02-06 08:56 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapUIRenderer.tsx
> +  const useFooter = content?.props?.children?.[1]?.type === 'Footer';
Agreed. This should be a prop.

2025-02-06 08:56 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapUIRenderer.tsx
I'm writing some base level tests for this component here: https://github.com/MetaMask/metamask-extension/blob/debbc76244709b6e83ac6fea7f6f489c943d1f89/ui/components/app/snaps/snap-ui-renderer/snap-ui-renderer.test.js

It would be great to test this implementation against them

2025-02-06 08:59 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/bold.ts
> +    color: TextColor.Default,
Should inherit the color and use overflow wrap

2025-02-06 09:00 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/address.ts
> +  element: 'AddressElement',
Looks like all of these props aren't available in mobile. We can wait with implementing this component fully, but would recommend deleting the mapper then

2025-02-06 09:00 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/box.ts
> +    alignItems: element.props.center || AlignItems.center,
```suggestion
    alignItems: element.props.center && AlignItems.center,
```

2025-02-06 09:01 UTC, FrederikBolding commented on app/core/Engine/Engine.ts
> +          'PhishingController:maybeUpdateState',
Still the case https://github.com/MetaMask/metamask-extension/blob/main/app/scripts/metamask-controller.js#L1513-L1517

2025-02-06 09:02 UTC, FrederikBolding commented on app/components/UI/Snaps/SnapUILink/index.tsx
> +export const SnapUILink: React.FC<SnapUILinkProps> = ({ href, children }) => (
IMO fine to not address for now, but we should have a ticket to address it

2025-02-06 09:03 UTC, FrederikBolding commented on app/components/UI/Snaps/SnapUIInput/Index.tsx
> +      inputRef.current.focus();
I'm assuming this won't work unless we directly target the input inside the FormTextField?

2025-02-06 09:04 UTC, FrederikBolding commented on app/components/UI/Box/index.tsx
> +const styles = StyleSheet.create({
Is this used?

2025-02-06 09:05 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/utils.ts
> +export enum AlignItems {
Again, are all of these necessary? Are there no existing definitions for these in mobile? At the very least they should be defined at a DS/component level and not for the SnapsUIRenderer

2025-02-06 09:06 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/row.ts
> +  element: 'Row',
This is still unresolved

2025-02-06 09:09 UTC, FrederikBolding commented on app/component-library/components/Buttons/Button/Button.tsx
> +  const capitalizedVariant = variant.charAt(0).toUpperCase() + variant.slice(1);
We should not be modifying DS components to accept our props, that is what the mapping functions are for

2025-02-06 09:10 UTC, FrederikBolding commented on app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.types.ts
> +  type?: ButtonType;
Definitely not. The Snaps button type is used to determine the onClick handler behavior:
https://github.com/MetaMask/metamask-extension/blob/e7e84889a4f27fb6dcd6d8c5cc80ca3cbf7b2efa/ui/components/app/snaps/snap-ui-button/snap-ui-button.tsx#L43-L52

2025-02-06 09:10 UTC, FrederikBolding commented on app/component-library/components/Avatars/Avatar/variants/AvatarFavicon/AvatarFavicon.types.ts
> +  name?: string;
I don't follow the changes here, where are these required?

2025-02-06 09:11 UTC, FrederikBolding commented on app/component-library/components/Avatars/Avatar/variants/AvatarFavicon/AvatarFavicon.tsx
> +      size={size.toLowerCase() as AvatarSize}
We should not be modifying DS components to accept our props, that is what the mapping functions are for

2025-02-06 09:13 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/row.ts
> +    ...(element.props as ViewProps),
We want to be explicit about the props we are passing instead of spreading

2025-02-06 09:14 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/text.ts
> +      textAlign: element.props.alignment || 'left',
As far as I can tell this prop isn't currently supported, maybe remove and we can revisit?

2025-02-06 09:16 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIFooterButton/SnapUIFooterButton.tsx
> +  onConfirm,
`onConfirm` doesn't need to exist, the Snap handles this by listening for the button clicks

2025-02-06 09:18 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/button.ts
> +        element.props.size === 'sm' ? TextVariant.BodySM : TextVariant.BodyMD,
```suggestion
      type: element.type,
      form: element.props.form,
      variant: element.props.variant,
      name: element.props.name,
      disabled: element.props.disabled,
      loading: element.props.loading ?? false,
      textVariant:
        element.props.size === 'sm' ? TextVariant.BodySM : TextVariant.BodyMD,
```

2025-02-06 09:18 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/button.ts
> +      label: element.props.children,
```suggestion
```

2025-02-06 09:18 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/Icon.test.ts
These are still named wrong

2025-02-06 09:18 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/Heading.test.ts
These are still named wrong

2025-02-06 09:20 UTC, FrederikBolding commented on app/components/UI/Snaps/SnapUILink/index.tsx
Can we please rename these to not all be `index.tsx`? This includes all of the components in this PR

2025-02-06 09:20 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/box.types.ts
> +import React from 'react';
Can we move all of these types to the actual box component?

2025-02-06 09:21 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/container.ts
> +    element: 'View',
Box?

2025-02-06 09:21 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/container.ts
> +      element: '',
```suggestion
      element: 'Box',
```

2025-02-06 09:29 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapUIRenderer.tsx
> +  onConfirm: () => void;
```suggestion
```

2025-02-06 09:35 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +
We should be calling `SnapInterfaceController.deleteInterface(approvalRequest.id)` when confirming and cancelling an approval

2025-02-06 09:37 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +      case DIALOG_APPROVAL_TYPES.confirmation:
Each dialog type needs different handling for the return values of the approval.

Alert: Should return null when the one button is hit
Confirmation: Should return true if accepted, otherwise false (currently returns null)
Prompt: Should return the string from the input if accepted, otherwise null (currently does not return the string)

2025-02-06 13:26 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapInterfaceContext.tsx
> +  const [focusedInput, setFocusedInput] = useState<string | null>(null);
Changed this back to a `ref`, it was changed to `useState` to pass a test I think.

2025-02-06 13:31 UTC, Daniel-Cross commented on app/component-library/components/Buttons/Button/Button.tsx
> +  const capitalizedVariant = variant.charAt(0).toUpperCase() + variant.slice(1);
Will move this to the parent component where we map the rest of the data.

2025-02-06 13:49 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/components/container.ts
> +    element: 'View',
Good catch!

2025-02-06 13:57 UTC, Daniel-Cross commented on app/components/UI/Snaps/SnapUILink/index.tsx
> +export const SnapUILink: React.FC<SnapUILinkProps> = ({ href, children }) => (
I will resolve this comment for now and we can address this once this PR has been merged.

2025-02-06 14:00 UTC, FrederikBolding commented on app/components/UI/Snaps/SnapUILink/index.tsx
> +export const SnapUILink: React.FC<SnapUILinkProps> = ({ href, children }) => (
Could you please create a ticket or make a note of this somewhere?

2025-02-06 14:01 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapUIRenderer/components/heading.ts
> +    numberOfLines: 0,
Ah! That does seem like what we want! Ignore my comment!

2025-02-06 14:34 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +
How does that work in this case when we're returning the `inputState.state['custom-input'] as unknown as Record<string, Json>` back to the user? Seeing as deleteInterface only seems to accept the request id and not any other parameters.

2025-02-06 14:36 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +
```
  const inputState =
      await Engine.context.SnapInterfaceController.getInterface(
        approvalRequest?.origin as SnapId,
        approvalRequest.requestData.id,
      );
    await Engine.acceptPendingApproval(
      approvalRequest.id,
      inputState.state['custom-input'] as unknown as Record<string, Json>,
    );
```
Here we get the current input state and return back to the user `onConfirm`. The input state is then displayed in the grey field on the Snaps dialog screen:

<img width="363" alt="Screenshot 2025-02-06 at 15 36 12" src="https://github.com/user-attachments/assets/7b532bae-2c72-4e40-a84e-1c2d1b2a1361" />

2025-02-06 14:38 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +
We should continue to resolve the pending approval, we just need to clean up and delete the interface afterwards!

2025-02-06 14:42 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +
I suspect this hasn't been configured correctly in the `Engine.ts` file so I'm going to dig into the implementation on extension first.

2025-02-06 14:44 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +
We do the same on extension, see here for example: https://github.com/MetaMask/metamask-extension/blob/fb/snap-ui-renderer-tests/ui/pages/confirmations/confirmation/templates/snaps/snap-confirmation/snap-confirmation.js#L10

2025-02-06 14:46 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +
So the extension implementation is different of course, but does this look correct to you? This is the `acceptApproval` function:

```
async acceptPendingApproval(
    id: string,
    requestData?: Record<string, Json>,
    opts: AcceptOptions & { handleErrors?: boolean } = {
      waitForResult: false,
      deleteAfterResult: false,
      handleErrors: true,
    },
  ) {
    const { ApprovalController } = this.context;

    try {
      return await ApprovalController.accept(id, requestData, {
        waitForResult: opts.waitForResult,
        deleteAfterResult: opts.deleteAfterResult,
      });
    } catch (err) {
      if (opts.handleErrors === false) {
        throw err;
      }
    }
  }
```

Hard to tell, but it feels kind of close to the `deleteInterface` function.

2025-02-06 14:50 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +
That looks fine, my only point is that we should also do something like this afterwards:
```suggestion
Engine.context.SnapInterfaceController.deleteInterface(
  approvalRequest.requestData.id,
)
```

2025-02-06 14:58 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +
Had a look at the `ApprovalController` types and it seems `accept` deletes the approval, which I'm assuming `deleteInterface` also does? Also pasting `reject` here so you can see the difference between them.

```
accept(id: string, value?: unknown, options?: AcceptOptions): Promise<AcceptResult>;
    /**
     * Rejects the promise of the approval with the given id, and deletes the
     * approval. Throws an error if no such approval exists.
     *
     * @param id - The id of the approval request.
     * @param error - The error to reject the approval promise with.
     */
    reject(id: string, error: unknown): void;
    /**
     * Rejects and deletes all approval requests.
     *
     * @param rejectionError - The JsonRpcError to reject the approval
     * requests with.
     */
```

2025-02-06 14:59 UTC, FrederikBolding commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +
Yep! The Snap interface is stored separately from the approval, so we need to clean up both.

E.g. the approval simply stores an identifier for which interface to show.

2025-02-06 15:34 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +      case DIALOG_APPROVAL_TYPES.confirmation:
I just tested these again and it seems that they return the values that you said they should here in this message, except for the `prompt` dialog, but for some reason that doesn't render a text input. When I look at the received data I don't see any input either like I do on the `custom` dialog:

```
interfaceState {
  "snapId": "npm:@metamask/dialog-example-snap",
  "content": {
    "type": "Box",
    "props": {
      "children": [
        {
          "type": "Heading",
          "props": {
            "children": "Prompt Dialog"
          },
          "key": null
        },
        {
          "type": "Text",
          "props": {
            "children": "This is a prompt dialog. In addition to the &quot;OK&quot; and &quot;Cancel&quot; buttons, it has a text input field."
          },
          "key": null
        }
      ]
    },
    "key": null
  },
  "state": {},
  "context": null,
  "contentType": null
}
```

2025-02-06 15:53 UTC, brianacnguyen requested changes
Please remove unnecessary changes to design system

2025-02-06 16:29 UTC, Daniel-Cross commented on app/component-library/components/Avatars/Avatar/variants/AvatarFavicon/AvatarFavicon.types.ts
> +  name?: string;
I've tried to reuse components that already exist in the mobile repo but it seems they're quite different from the extension components. I'm going to double check all the prop changes I made to accommodate the snaps functionality and possibly write new snap specific components where needed.

2025-02-07 12:19 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +      case DIALOG_APPROVAL_TYPES.confirmation:
Add onCancel for `custom` dialog. Custom is the only snap that receives a function via Snaps. The rest are hardcoded.

2025-02-07 12:38 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapUIRenderer.tsx
> +const SnapUIRendererComponent = ({
Currently no way to implement the style sheet that works for extension. All the styles in this `scss` file will crash the app or are not relevant. Also, `className` isn't a relevant field on mobile. Something along the line of styled-components would be a better fit.

2025-02-07 12:39 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/SnapUIRenderer.tsx
> +const SnapUIRendererComponent = ({
Ticket needed for this issue.

2025-02-07 12:59 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/utils.ts
> +export enum AlignItems {
Move types from `utils.ts` into `box.types.ts` where they are referenced. Move `box.types.ts` to be with `box.ts`.

2025-02-07 13:04 UTC, Daniel-Cross commented on app/components/Approvals/Snaps/SnapUIRenderer/components/button.ts
> +    element: 'Button',
`handleSnapInteraction` function needed in this component

2025-02-07 18:59 UTC, owencraston commented
All of the use cases seem to be working as expected. Great work! The only concern I have is the modification of the metamask base components. Are we able to achieve what we want without those modifications?
https://github.com/user-attachments/assets/6cd91cf9-09f0-449b-bcee-02279332bd17

2025-02-08 08:04 UTC, Daniel-Cross commented on package.json
> +    "html-entities": "^2.5.2",
Added the same package as the one used on extension `he`

2025-02-13 14:44 UTC, Daniel-Cross commented on app/core/Engine/Engine.ts
> +          'PhishingController:maybeUpdateState',
So I found in the extension that there are the following actions:
```
 const snapKeyringBuildMessenger = this.controllerMessenger.getRestricted({
      name: 'SnapKeyring',
      allowedActions: [
        'ApprovalController:addRequest',
        'ApprovalController:acceptRequest',
        'ApprovalController:rejectRequest',
        'ApprovalController:startFlow',
        'ApprovalController:endFlow',
        'ApprovalController:showSuccess',
        'ApprovalController:showError',
        'PhishingController:test',
        'PhishingController:maybeUpdateState',
        'KeyringController:getAccounts',
        'AccountsController:setSelectedAccount',
        'AccountsController:getAccountByAddress',
        'AccountsController:setAccountName',
        'SnapController:handleRequest',
        'SnapController:get',
      ],
    });
```

But they are found under the `SnapKeyring` and not under the `SnapInterfaceController`. On mobile we have both of these are the same actions are found in both `allowedActions` array. 

Is this correct? Should both of these look the same as the `SnapKeyring` above?

2025-02-13 22:29 UTC, owencraston commented
Everything is looking good except for the prompt dialog. The prompt is missing the text input. 

https://github.com/user-attachments/assets/a171c6c9-2f37-4831-b77f-0d4b0df89f7e

2025-02-13 22:31 UTC, owencraston commented on app/component-library/components/Avatars/Avatar/variants/AvatarFavicon/AvatarFavicon.types.ts
> +  imageSource?: ImageSourcePropType;
This seems like it should be mandatory for this component? In what case would we show an avatar without an image source?

2025-02-13 22:31 UTC, owencraston commented on app/component-library/components/Avatars/Avatar/variants/AvatarFavicon/AvatarFavicon.tsx
> +      {error ? renderFallbackFavicon() : renderFavicon()}
can you explain the reasoning behind this change?

2025-02-13 22:33 UTC, owencraston commented on app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.types.ts
> +  textProps?: StyleProp<TextStyle>;
Is a change to the base components here needed (I am going to ask this on every component lib change, sorry)? If so, should we call this textStyles instead since it seems that is actually what it is doing?

2025-02-13 22:33 UTC, owencraston commented on app/component-library/components/Buttons/Button/variants/ButtonPrimary/ButtonPrimary.tsx
> +  startIconName,
^

2025-02-13 22:35 UTC, owencraston commented on app/component-library/components/Icons/Icon/Icon.types.ts
> +  Inherit = 'Inherit',
when would we use this vs specifying a size?

2025-02-13 22:43 UTC, owencraston commented on app/components/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +      null as unknown as Record<string, Json>,
I am confused how we go form null to a `Record<string, Json>`. Is there a more accurate param we can pass in?

2025-02-13 22:54 UTC, owencraston commented on app/components/Snaps/SnapUICard/SnapUICard.props.ts
> +  image?: ImageSourcePropType;
why are these all nullable?

2025-02-13 22:54 UTC, owencraston commented on app/components/Snaps/SnapUICard/SnapUICard.props.ts
> +export interface SnapUICardProps {
Nit: should this file be called SnapUICard.types.ts

2025-02-13 23:12 UTC, owencraston commented on app/components/Snaps/SnapUIRenderer/SnapUIRenderer.tsx
> +const styles = StyleSheet.create({
these should be moved to a .styles.ts component

2025-02-13 23:14 UTC, owencraston commented on app/components/Snaps/SnapUIRenderer/components/Heading.test.ts
> +  it('should transform HeadingElement into Text format with default size', () => {
Nit pick. remove the should from each it block. This is the pattern we are using across the app. For example...
`transforms HeadingElement into Text format with default size`

2025-02-13 23:14 UTC, owencraston commented on app/components/Snaps/SnapUIRenderer/components/Icon.test.ts
> +  it('should create correct element configuration with valid props', () => {
same comment about the should in the it block. This applies to all tests.

2025-02-13 23:30 UTC, owencraston commented on app/components/Snaps/SnapUIRenderer/components/link.ts
> +/* eslint-disable @typescript-eslint/no-shadow */
is this meant to be there?

2025-02-13 23:30 UTC, owencraston commented on app/components/Snaps/SnapUIRenderer/components/row.ts
> +/* eslint-disable @typescript-eslint/no-shadow */
again, is this still needed?

2025-02-13 23:31 UTC, owencraston commented on app/components/Snaps/SnapUIRenderer/components/row.ts
> +// TODO: Row is not a valid component on mobile. Check InfoRow.tsx for the mobile implementation against extension. Possible new component needed.
will this work as of right now?

2025-02-13 23:34 UTC, owencraston commented on app/components/UI/FormTextField/form-text-field.types.ts
> +  extends Omit<TextFieldStyleUtilityProps, 'size' | 'type'> {
Nit pick: This file should probably be called FormTextField.types.ts

2025-02-13 23:38 UTC, owencraston commented on app/components/UI/TemplateRenderer/TemplateRenderer.tsx
> +  if (!component || !isValidElementName(component)) {
why did this change to an or clause?

2025-02-13 23:49 UTC, owencraston commented on app/core/Engine/Engine.ts
> +    const snapInterfaceController = new SnapInterfaceController({
There is a new pattern for adding controllers to the engine. We are using a factory that creates the instance for us. This helps reduce some of the code inside this main file. Look at the `createAccountsController` inside `app/core/Engine/controllers/AccountsController/utils.ts`. All of the messenger events should be constants. If the component has not yet been migrated to the new pattern then the raw string is fine but we already have the `SnapControllerGetSnapAction` created in `app/core/Engine/controllers/SnapController/constants.ts`.

2025-02-13 23:50 UTC, owencraston commented on app/core/Engine/constants.ts
> +  'SnapInterfaceController:stateChange',
Once you create the factory function to create the `SnapInterfaceController`. Lets use a constant for this event. You can see we did this with the SnapControllerStateChangeEvent already.

2025-02-13 23:54 UTC, owencraston commented on app/core/Snaps/SnapsMethodMiddleware.ts
> +    ),
I'm noticing that not all of the callbacks that you implemented in this file were added in the Engine.ts. This is a really bad pattern that requires us to duplicate these callbacks in two places. Lets work on changing this in another PR but in the meantime, I think you need to add updateInterfaceState, resolveInterface and  getInterfaceContext to the Engine file.

2025-02-13 23:55 UTC, owencraston commented on app/core/Snaps/SnapsMethodMiddleware.ts
> +    ),
Also, these events should all be constants. as I discussed in this [comment](https://github.com/MetaMask/metamask-mobile/pull/12429/files#r1955361506).

2025-02-13 23:55 UTC, owencraston commented on app/selectors/snaps/interfaceController.ts
> +const getInterfaces = (state: any) =>
Most likely its RootState.

2025-02-13 23:56 UTC, owencraston commented on app/selectors/snaps/interfaceController.ts
> +export const getInterface = createSelector(
any reason this one is not memoized?

2025-02-14 00:01 UTC, owencraston reviewed
In general, all of the files in `app/components/Snaps/` and `app/components/UI` look good to me. I left a bunch of small nitpicks. Lastly, the prompt is not showing the text input. This is really great work and I will be ready to approve once these small issues are resolved.

2025-02-14 00:46 UTC, FrederikBolding commented on app/components/UI/TemplateRenderer/TemplateRenderer.tsx
> +  if (!component || !isValidElementName(component)) {
I changed this when I wrote the initial version of this PR. The template renderer would not fail correctly if a component was not in the safe list.

2025-02-14 09:54 UTC, GuillaumeRx commented on app/components/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +  };
We have different return values depending on the type of dialog, was it decided that we would return only `true`, `false` or `null` ?

2025-02-14 10:15 UTC, GuillaumeRx requested changes

2025-02-14 10:15 UTC, GuillaumeRx commented on app/components/Snaps/SnapUIFooterButton/SnapUIFooterButton.tsx
Looking at @owencraston's video the buttons are the wrong color, they should not be blue :thinking:

2025-02-14 10:15 UTC, GuillaumeRx commented on app/components/Snaps/SnapUIRenderer/components/button.ts
> +    form: e.props.form,
What do you mean by this ? `form` should be use to trigger the good event

2025-02-14 10:15 UTC, GuillaumeRx commented on app/components/Snaps/SnapUIRenderer/components/container.ts
> +      element: 'FormTextField',
Do you guys have `FormTextField` ?

2025-02-14 11:44 UTC, Daniel-Cross commented on app/component-library/components/Avatars/Avatar/variants/AvatarFavicon/AvatarFavicon.types.ts
> +  imageSource?: ImageSourcePropType;
Reverted this. Thanks

2025-02-14 11:46 UTC, Daniel-Cross commented on app/component-library/components/Avatars/Avatar/variants/AvatarFavicon/AvatarFavicon.tsx
> +      {error ? renderFallbackFavicon() : renderFavicon()}
Reverted this also. Thanks

2025-02-14 11:47 UTC, Daniel-Cross commented on app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.types.ts
> +  textProps?: StyleProp<TextStyle>;
Reverted this also. Thanks

2025-02-14 11:49 UTC, Daniel-Cross commented on app/component-library/components/Icons/Icon/Icon.types.ts
> +  Inherit = 'Inherit',
This is apparently what is sent in the custom dialog snap, so in that case we don't define a size, the snap will define a size of it's own instead.

2025-02-14 11:49 UTC, Daniel-Cross commented on app/component-library/components/Icons/Icon/Icon.types.ts
> +  Inherit = 'Inherit',
I can always just add this to the component where it's necessary instead of changing this file.

2025-02-14 11:52 UTC, Daniel-Cross commented on app/components/Snaps/SnapUICard/SnapUICard.props.ts
> +export interface SnapUICardProps {
Yep!

2025-02-14 11:57 UTC, Daniel-Cross commented on app/components/Snaps/SnapUICard/SnapUICard.props.ts
> +  image?: ImageSourcePropType;
Changed the ones that are required props.

2025-02-14 11:59 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIRenderer/components/link.ts
> +/* eslint-disable @typescript-eslint/no-shadow */
Probably not!

2025-02-14 13:04 UTC, FrederikBolding commented on app/components/Snaps/SnapIcon/SnapIcon.tsx
> +  const fallbackIcon = getAvatarFallbackLetter(snapName ?? 'M');
```suggestion
  const fallbackIcon = getAvatarFallbackLetter(snapName ?? '?');
```

2025-02-14 13:05 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/utils.ts
> +export const getAvatarFallbackLetter = (subjectName: string) =>
```suggestion
export const getAvatarFallbackLetter = (subjectName?: string) =>
```

2025-02-14 13:05 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/utils.ts
> +export enum IconColor {
This should live somewhere else

2025-02-14 13:05 UTC, FrederikBolding commented on app/components/UI/ApprovalTagUrl/__snapshots__/ApprovalTagUrl.test.tsx.snap
> -    <Image
Revert?

2025-02-14 13:06 UTC, FrederikBolding commented on app/components/UI/Box/index.tsx
Can we rename this to `Box.tsx`

2025-02-14 13:08 UTC, FrederikBolding commented on app/core/Engine/Engine.ts
> +      AssetsContractController,
Not sure where `AssetsContractController` is coming from here

2025-02-14 13:08 UTC, FrederikBolding commented on app/selectors/snaps/snapController.ts
> +      Record<string, { name: string; description: string; iconUrl?: string }>
```suggestion
      Record<string, { name: string; description: string }>
```

2025-02-14 13:11 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/components/row.ts
> +// TODO: Row is not a valid component on mobile. Check InfoRow.tsx for the mobile implementation against extension. Possible new component needed.
```suggestion
```

2025-02-14 13:13 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/components/box.types.ts
This should live next to the box component, not the mapper

2025-02-14 13:20 UTC, GuillaumeRx commented on app/components/Snaps/SnapUIFooterButton/SnapUIFooterButton.tsx
unresolving, the primary buttons on extension are not black, we make them black because they are used by snaps in custom dialogs. @eriknson can you expand on this ?

2025-02-14 13:22 UTC, FrederikBolding commented on app/components/Snaps/SnapUIButton/SnapUIButton.tsx
> +  handlePress,
Why was the button handling removed? It was working as intended before with the `handleEvent` logic?
```
  const handlePress = () => {
    handleEvent({
      event: UserInputEventType.ButtonClickEvent,
      name,
    });
  };

```

2025-02-14 13:55 UTC, FrederikBolding commented on app/components/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +  };
As far as I can tell we return the proper values with the exception of `prompt` which doesn't show a prompt

2025-02-14 13:58 UTC, FrederikBolding commented on app/components/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +      null as unknown as Record<string, Json>,
I think the upstream type is too strict here, maybe worth changing it to `Json` and removing the casts here

2025-02-14 14:00 UTC, FrederikBolding commented on app/components/UI/Snaps/SnapUIInput/SnapUIInput.tsx
> +      inputRef.current.focus();
Does this actually work without somehow targeting the "inner" input? Since the ref is attached to `FormTextField`

2025-02-14 14:01 UTC, FrederikBolding commented on app/components/UI/Snaps/SnapUIInput/index.test.tsx
Rename this file to match the component

2025-02-14 14:19 UTC, Daniel-Cross commented on app/components/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +  };
Do we want to add a prompt now? I remember someone saying that was legacy or not needed for the Solana/Bitcoin work so it didn't matter at the moment?

2025-02-14 14:21 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIFooterButton/SnapUIFooterButton.tsx
@GuillaumeRx Is this relevant?

https://consensys.slack.com/archives/C05V3JXAYLW/p1726737398125959?thread_ts=1726500769.338779&cid=C05V3JXAYLW

2025-02-14 14:24 UTC, Daniel-Cross commented
> Everything is looking good except for the prompt dialog. The prompt is missing the text input.
> 
>  Screen.Recording.2025-02-13.at.3.26.46.PM.mov

Can we please get some clarity on this? 

Do we want to include the input on the prompt dialog right now? Is it going to be used or should it wait?

@FrederikBolding @GuillaumeRx

2025-02-14 14:28 UTC, Daniel-Cross commented on app/components/UI/Snaps/SnapUIInput/SnapUIInput.tsx
> +      inputRef.current.focus();
Regarding this from the extension:
´´´
 useEffect(() => {
    if (inputRef.current && name === focusedInput) {
      (inputRef.current.querySelector('input') as HTMLInputElement).focus();
    }
  }, [inputRef]);
  ´´´
`inputRef.current.querySelector` is a DOM API method that exists in web browsers but not in React Native. 

`TextInput` components have their own `focus()` method that can be called directly on the ref.

2025-02-14 14:32 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIRenderer/components/box.types.ts
While I agree, the `Box.tsx` component lives in the following file path: `app/components/UI/ramp/components` with 20+ other components, none of which have types alongside them. I have no problem moving it but it will be the only type file in the directory.

2025-02-14 14:39 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIButton/SnapUIButton.tsx
> +  handlePress,
The `SnapUIButton` is rendered via the `SnapUIFooterButton`, and we call this function there and pass it down into the `SnapUIButton` so it seemed redundant to call this in both places.

We don't render the `SnapUIButton` anywhere else, but if you think it would be better served having this function called in this component instead of the parent I can move it.

2025-02-14 14:56 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIRenderer/SnapUIRenderer.tsx
> +const styles = StyleSheet.create({
Added `SnapUIRenderer.styles.ts`

2025-02-14 14:59 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIRenderer/components/Heading.test.ts
> +  it('should transform HeadingElement into Text format with default size', () => {
Will remove `should` from all tests

2025-02-14 14:59 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIRenderer/components/Icon.test.ts
> +  it('should create correct element configuration with valid props', () => {
`should` has now been removed

2025-02-14 15:00 UTC, Daniel-Cross commented on app/components/UI/FormTextField/form-text-field.types.ts
> +  extends Omit<TextFieldStyleUtilityProps, 'size' | 'type'> {
Changed name.

2025-02-14 15:00 UTC, Daniel-Cross commented on app/components/UI/TemplateRenderer/TemplateRenderer.tsx
> +  if (!component || !isValidElementName(component)) {
I will leave this as it is then?

2025-02-14 15:04 UTC, Daniel-Cross commented on app/selectors/snaps/interfaceController.ts
> +export const getInterface = createSelector(
No particular reason, I think I just copied it from the original POC branch that Frederik started implementing.

2025-02-14 15:04 UTC, FrederikBolding commented on app/components/UI/Snaps/SnapUIInput/SnapUIInput.tsx
> +      inputRef.current.focus();
> TextInput components have their own focus() method that can be called directly on the ref.

Cool, but `inputRef.current` refers to the the container of `TextInput` as far as I can tell. Does it not?

2025-02-14 15:05 UTC, FrederikBolding commented
> > Everything is looking good except for the prompt dialog. The prompt is missing the text input.
> > Screen.Recording.2025-02-13.at.3.26.46.PM.mov
> 
> Can we please get some clarity on this?
> 
> Do we want to include the input on the prompt dialog right now? Is it going to be used or should it wait?
> 
> @FrederikBolding @GuillaumeRx

Fine to skip IMO, I would just remove references to it so it fails more obviously if someone tries to use it.

2025-02-14 15:07 UTC, FrederikBolding commented on app/components/Snaps/SnapUIButton/SnapUIButton.tsx
> +  handlePress,
`SnapUIButton` may be rendered by the Snap outside of the footer too. For example if the Snap creates a form with a button: 
![image](https://github.com/user-attachments/assets/a5dcf0fc-8afb-4654-8229-220e659303b4)

2025-02-14 15:08 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/components/box.types.ts
Where do the types for those components live then? My preference is just to not complicate the Snaps directories with more files than necessary

2025-02-14 15:09 UTC, FrederikBolding commented on app/components/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +  };
We sorta half support it now, I would just remove references to it so it is clear that it doesn't work

2025-02-14 15:10 UTC, FrederikBolding commented on app/core/Snaps/SnapsMethodMiddleware.ts
> +    ),
@owencraston Can you elaborate on what is a bad pattern here? Is there an established pattern for sharing hooks in multiple middlewares?

2025-02-14 15:11 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIRenderer/components/button.ts
> +    form: e.props.form,
React Native doesn't have the native HTML form element that is found on web. We have to handle forms differently. We can have a discussion around how that will look or work but it mainly involves saving everything in state.

2025-02-14 15:12 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIRenderer/components/container.ts
> +      element: 'FormTextField',
We have this component: `app/UI/components/FormTextField/index.tsx`

2025-02-14 15:17 UTC, Daniel-Cross commented on app/core/Engine/Engine.ts
> +      AssetsContractController,
This seems to have been added 6 years ago. I'm not really sure what to do about it to be honest. Any recommendations?

2025-02-14 15:18 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIButton/SnapUIButton.tsx
> +  handlePress,
Okay, in that case I will move the handle function into the button and remove it from the parent.

2025-02-14 15:24 UTC, FrederikBolding commented on app/core/Engine/Engine.ts
> +      AssetsContractController,
As far as I can tell it isn't there in main, so I don't think this PR needs to add it?

2025-02-14 16:01 UTC, Daniel-Cross commented on app/components/UI/Snaps/SnapUIInput/SnapUIInput.tsx
> +      inputRef.current.focus();
Yeah, it references the `TextInput` which is wrapped by a `FormTextField`.

So it would probably look something like this:

```
<FormTextField ref={inputRef}>
  <Input />
</FormTextField>
```

Thats what makes up the `<TextInput />` component in RN.

2025-02-14 16:02 UTC, Daniel-Cross commented on app/components/UI/Snaps/SnapUIInput/index.test.tsx
Done, renamed.

2025-02-14 16:03 UTC, Daniel-Cross commented
> > > Everything is looking good except for the prompt dialog. The prompt is missing the text input.
> > > Screen.Recording.2025-02-13.at.3.26.46.PM.mov
> > 
> > 
> > Can we please get some clarity on this?
> > Do we want to include the input on the prompt dialog right now? Is it going to be used or should it wait?
> > @FrederikBolding @GuillaumeRx
> 
> Fine to skip IMO, I would just remove references to it so it fails more obviously if someone tries to use it.

So what would that look like? Total removal of the prompt dialog or changing the text to not include the mention of the input? Or just not showing the text at all?

2025-02-14 16:04 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIButton/SnapUIButton.tsx
> +  handlePress,
Moved this function into the button itself instead of the parent wrapper (now removed from there).

2025-02-14 16:06 UTC, Daniel-Cross commented on app/core/Engine/Engine.ts
> +      AssetsContractController,
<img width="1054" alt="Screenshot 2025-02-14 at 17 05 47" src="https://github.com/user-attachments/assets/e08a519c-a940-4f2d-8a08-aa23e5cbb080" />
Weird man! I'll remove it.

2025-02-16 16:14 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIRenderer/utils.ts
> +export enum IconColor {
Moved to `Icon.types.ts`

2025-02-16 16:15 UTC, Daniel-Cross commented on app/components/UI/ApprovalTagUrl/__snapshots__/ApprovalTagUrl.test.tsx.snap
> -    <Image
Ran the tests again after updating the test files and making suggested changes. This should be correct now?

2025-02-16 16:17 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIRenderer/components/box.types.ts
Moved this into a `Box` folder

2025-02-17 18:17 UTC, eriknson commented on app/components/Snaps/SnapUIFooterButton/SnapUIFooterButton.tsx
So to summarize;
- Snaps 3rd party actions / buttons in the footer are (for now) using the `icon/default` background color to differentiate them from native actions
- Pre-installed snaps are de-facto native and override this background color to use the `primary/blue` just like other native actions

2025-02-18 09:42 UTC, FrederikBolding commented on app/component-library/components/Avatars/Avatar/variants/AvatarFavicon/AvatarFavicon.types.ts
> -// External dependencies.
Revert

2025-02-18 09:42 UTC, FrederikBolding commented on app/component-library/components/Buttons/Button/variants/ButtonPrimary/ButtonPrimary.tsx
> +  startIconName,
Revert

2025-02-18 09:43 UTC, FrederikBolding commented on app/components/Snaps/SnapIcon/SnapIcon.tsx
> +  const fallbackIcon = getAvatarFallbackLetter(snapName ?? undefined);
```suggestion
  const fallbackIcon = getAvatarFallbackLetter(snapName);
```
Do we need this?

2025-02-18 09:45 UTC, FrederikBolding commented on app/components/Snaps/SnapUIFooterButton/SnapUIFooterButton.tsx
> +            imageSource={snapMetadata.icon}
```suggestion
```

2025-02-18 09:47 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/components/button.ts
> +    form: e.props.form,
We are already saving everything in state, we just need to hook it up correctly to submit the proper event. Should not be a problem. Please keep track of the fact that we haven't done this yet via a ticket

2025-02-18 09:49 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/components/box.types.ts
Delete in favor of `UI/Box/box.types.ts`

2025-02-18 09:52 UTC, FrederikBolding commented on app/components/UI/Snaps/SnapUIInput/index.test.tsx
Change the filename to match the component

2025-02-18 09:54 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/components/SnapInterfaceContext.test.tsx
Why is this file not placed next to the component it is testing?

2025-02-18 09:54 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/components/Icon.test.ts
Fix casing on these tests please

2025-02-18 09:54 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/components/Heading.test.ts
Fix casing on these tests please

2025-02-18 10:01 UTC, FrederikBolding commented on app/components/Snaps/SnapIcon/SnapIcon.tsx
> +} & AvatarFaviconProps;
Probably too broad of a type, we don't need callers to pass `imageSource` for instance

2025-02-18 10:26 UTC, FrederikBolding commented
> > > > Everything is looking good except for the prompt dialog. The prompt is missing the text input.
> > > > Screen.Recording.2025-02-13.at.3.26.46.PM.mov
> > > 
> > > 
> > > Can we please get some clarity on this?
> > > Do we want to include the input on the prompt dialog right now? Is it going to be used or should it wait?
> > > @FrederikBolding @GuillaumeRx
> > 
> > 
> > Fine to skip IMO, I would just remove references to it so it fails more obviously if someone tries to use it.
> 
> So what would that look like? Total removal of the prompt dialog or changing the text to not include the mention of the input? Or just not showing the text at all?

I would just throw if we get a request to display a prompt tbh

2025-02-18 10:28 UTC, FrederikBolding commented on app/core/Engine/Engine.ts
> +    const snapInterfaceController = new SnapInterfaceController({
In the interest of not having this PR go stale I think this is something that can be done in a follow-up

2025-02-18 13:07 UTC, Daniel-Cross commented on app/components/UI/Snaps/SnapUIInput/SnapUIInput.tsx
> +      inputRef.current.focus();
The focus should correctly apply to the input contained within the container wrapper. We can test it in a real use case perhaps and see if there are any issues? Something to be mindful of if we notice any strange behaviour around the inputs.

2025-02-18 13:08 UTC, Daniel-Cross commented on app/components/Snaps/SnapIcon/SnapIcon.tsx
> +  const fallbackIcon = getAvatarFallbackLetter(snapName ?? undefined);
The linter won't pass without some kind of fallback passed into this function or on the `snapName` variable. 
<img width="1183" alt="Screenshot 2025-02-18 at 14 08 43" src="https://github.com/user-attachments/assets/11daed51-bfe9-4e02-99ed-4aec4a4c707b" />

2025-02-18 14:34 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/utils.ts
> +export const getAvatarFallbackLetter = (subjectName?: string) =>
```suggestion
export const getAvatarFallbackLetter = (subjectName?: string | null) =>
```

2025-02-18 14:34 UTC, FrederikBolding commented on app/components/Snaps/SnapIcon/SnapIcon.tsx
> +  const fallbackIcon = getAvatarFallbackLetter(snapName ?? undefined);
Alternative approach: https://github.com/MetaMask/metamask-mobile/pull/12429/files#r1959876956

2025-02-18 15:04 UTC, Daniel-Cross commented on app/core/Engine/Engine.ts
> +    const snapInterfaceController = new SnapInterfaceController({
Spoke to Owen. We will look at implementing this change in the refactor once this has been merged.

2025-02-18 15:04 UTC, Daniel-Cross commented on app/core/Snaps/SnapsMethodMiddleware.ts
> +    ),
@owencraston sent me a rough example here: https://github.com/MetaMask/metamask-mobile/pull/13567/files

We can look into changing in the refactor PR.

2025-02-18 15:04 UTC, Daniel-Cross commented on app/selectors/snaps/interfaceController.ts
> +const getInterfaces = (state: any) =>
Updated to use `RootState`

2025-02-18 15:04 UTC, Daniel-Cross commented on app/selectors/snaps/interfaceController.ts
> +export const getInterface = createSelector(
I will kick this down the road to the next refactor PR after this has been merged.

2025-02-18 15:23 UTC, FrederikBolding commented on app/components/Snaps/SnapUIButton/SnapUIButton.tsx
> +const SnapUIButton = ({
Sorry for not realizing this mistake sooner, the `SnapUIButton` is meant to be a `ButtonLink`, e.g. inline clickable text with a color: https://www.figma.com/design/gHWl7G8ih3YXesly2XaA0R/Snaps-DS?node-id=621-17256&p=f&t=dGepyMDW1LiMbXn2-0

The SnapUIFooterButton is the only component that should use the regular `Button` component.

Perhaps we scrap `SnapUIButton` in this PR and add it properly in a follow-up PR? We'll need to move some of the logic to the footer button regardless

2025-02-18 15:26 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/components/Icon.test.ts
https://github.com/MetaMask/metamask-mobile/pull/12429#discussion_r1959942890

2025-02-18 16:31 UTC, brianacnguyen commented on app/component-library/components/Buttons/Button/variants/ButtonPrimary/ButtonPrimary.tsx
> +  endIconName,
can you remove this unnecessary change?

2025-02-18 16:32 UTC, brianacnguyen commented on app/component-library/components/ConfirmInfoRowValueDouble/ConfirmInfoRowValueDouble.tsx
> +export const ConfirmInfoRowValueDouble = ({
this should go into components-temp since it's not an official ds component

2025-02-18 16:32 UTC, brianacnguyen commented on app/component-library/components/Icons/Icon/Icon.types.ts
> +}
please revert these

2025-02-18 16:33 UTC, brianacnguyen commented on app/component-library/components/Texts/Text/Text.types.ts
> +  Bold = 'bold',
This wont simply wont simply work like this. please revert or reach out to me and I can walk you through implementations

2025-02-18 16:33 UTC, brianacnguyen submitted a review, later dismissed
Please revert unnecessary ds changes

2025-02-19 10:15 UTC, FrederikBolding commented on app/components/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +  };
We could just crash if we try to render a prompt tbh

2025-02-19 14:18 UTC, Daniel-Cross commented on app/component-library/components/ConfirmInfoRowValueDouble/ConfirmInfoRowValueDouble.tsx
> +export const ConfirmInfoRowValueDouble = ({
Moved to `components-temp`

2025-02-19 14:19 UTC, FrederikBolding commented on app/component-library/components/Icons/Icon/Icon.types.ts
> +}
Looks like we already have a enum for this: https://github.com/MetaMask/metamask-mobile/blob/main/app/component-library/components/Icons/Icon/Icon.types.ts#L10

2025-02-19 14:26 UTC, Daniel-Cross commented on app/components/Snaps/SnapIcon/SnapIcon.tsx
> +  const fallbackIcon = getAvatarFallbackLetter(snapName ?? undefined);
Approved @FrederikBolding's suggestion

2025-02-19 14:27 UTC, FrederikBolding commented on app/component-library/components/Buttons/Button/variants/ButtonPrimary/__snapshots__/ButtonPrimary.test.tsx.snap
> -  <SvgMock
Probably needs to rerun tests to regen this file

2025-02-19 14:29 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIRenderer/components/Icon.test.ts
Removed the ability to call the `prompt` dialog. The button won't return anything when pressed.

2025-02-19 14:29 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIRenderer/utils.ts
> +export const getAvatarFallbackLetter = (subjectName?: string) =>
Added this.

2025-02-19 16:52 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIRenderer/components/Heading.test.ts
Updated this now finally

2025-02-19 16:55 UTC, Daniel-Cross commented on app/component-library/components/Texts/Text/Text.types.ts
> +  Bold = 'bold',
Reverted this for now

2025-02-19 17:50 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIRenderer/components/button.ts
> +    form: e.props.form,
Ticket made: https://github.com/orgs/MetaMask/projects/149/views/1?pane=issue&itemId=98599953&issue=MetaMask%7Csnaps%7C3134

2025-02-20 10:02 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/components/text.ts
> +type TextProps = JSXElement & {
This should be importable from `@metamask/snaps-sdk/jsx`

2025-02-20 10:18 UTC, FrederikBolding commented on app/components/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +      case DIALOG_APPROVAL_TYPES.confirmation:
I think we removed too much here, we want `confirmation` to still work

2025-02-20 10:21 UTC, Daniel-Cross commented on app/components/Snaps/SnapUIRenderer/components/text.ts
> +type TextProps = JSXElement & {
Resolved via call with @FrederikBolding

2025-02-20 10:23 UTC, Daniel-Cross commented on app/components/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +      case DIALOG_APPROVAL_TYPES.confirmation:
Reverted

2025-02-20 11:11 UTC, FrederikBolding commented on app/components/Approvals/ApprovalModal/ApprovalModal.test.tsx
> +        <Text>test</Text>
Revert

2025-02-20 11:40 UTC, FrederikBolding commented on app/components/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +        approvalRequest?.type === DIALOG_APPROVAL_TYPES.prompt ||
```suggestion
```

2025-02-20 11:40 UTC, FrederikBolding commented on app/components/Snaps/SnapUIFooterButton/SnapUIFooterButton.tsx
Let's create a ticket to follow up on the design of the footer buttons

2025-02-20 11:43 UTC, FrederikBolding commented on app/components/Snaps/SnapDialogApproval/SnapsDialogApproval.tsx
> +      null as unknown as Record<string, Json>,
@Daniel-Cross Can we change the type of `acceptPendingApproval` to take a `Json` type instead?

2025-02-20 11:44 UTC, FrederikBolding commented on app/components/Snaps/SnapUIFooterButton/SnapUIFooterButton.tsx
> +    } else if (isSnapAction && !hideSnapBranding && !loading) {
```suggestion
    } else if (isSnapAction && !hideSnapBranding) {
```

2025-02-20 12:56 UTC, FrederikBolding submitted a review, later dismissed

2025-02-21 11:28 UTC, FrederikBolding commented
@SocketSecurity ignore npm/@metamask/solana-wallet-snap@1.7.0

Trusted authors :)

2025-02-21 15:03 UTC, tommasini commented on app/components/Snaps/SnapUIRenderer/SnapUIRenderer.test.tsx
> +      PERF_DEBUG
Would it make sense to replace the PER_DEBUG variable to use the [METAMASK_ENVIRONMENT](https://github.com/MetaMask/metamask-mobile/blob/0e2e04452ad50529e2ad7a96cba9645e4fd66ae6/.js.env.example#L56) that already exists for that purpose?

2025-02-21 15:09 UTC, tommasini commented on app/components/Snaps/SnapUIRenderer/components/footer.test.ts
> +    expect((result.children as any[])[0]).toEqual({
NIT: I see some patterns of these children that we consistently cast as any, we probably can type this no? (Just adding this notes since we may want to do it, but not commenting as a blocker )

2025-02-21 15:14 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/components/footer.test.ts
> +    expect((result.children as any[])[0]).toEqual({
https://github.com/MetaMask/metamask-mobile/blob/b6c0b6af137a1bb7eb402d490106f985cb41a87b/app/components/Snaps/SnapUIRenderer/SnapUIRenderer.test.tsx is how we want to write tests for these mappers, we can likely remove some of these additional tests in the near future

2025-02-21 15:24 UTC, tommasini commented on app/components/Snaps/SnapUIRenderer/utils.ts
> +      sha256(
We should aim to have this as a native implementation! Could we use [react-native-quick-crypto](https://github.com/margelo/react-native-quick-crypto?tab=readme-ov-file#usage) instead?

2025-02-21 15:27 UTC, GuillaumeRx approved these changes

2025-02-21 15:28 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/utils.ts
> +      sha256(
Good point, I'll make a note to look into this. We haven't done a perf pass on this yet because we need more components first

2025-02-21 15:28 UTC, tommasini commented on app/components/Snaps/SnapUIRenderer/utils.ts
> +export const mapToTemplate = (params: MapToTemplateParams): UIComponent => {
NIT & question: Does this function map the UI components to the snap UI right? Can we add a TSDoc to it?

2025-02-21 15:29 UTC, FrederikBolding commented on app/components/Snaps/SnapUIRenderer/utils.ts
> +export const mapToTemplate = (params: MapToTemplateParams): UIComponent => {
Yep, this maps from Snaps UI to MetaMask components!

2025-02-21 15:32 UTC, tommasini commented on app/components/UI/FormTextField/index.tsx
> +  helpText,
NIT: We can reduce the number of properties of this form by having the `helpText` as a property of `helpTextProps`. The same applies for label and labelProps.

2025-02-21 15:32 UTC, tommasini commented on app/components/UI/FormTextField/index.tsx
> +        isDisabled || disabled ? styles.disabled : undefined,
I'm most likely lacking context, but why do you have two disable properties?

2025-02-21 15:34 UTC, tommasini commented on app/components/UI/FormTextField/index.tsx
> +  helpText,
I see, that this because the snaps already contain this diff properties. If is this ignore this comment

2025-02-21 15:34 UTC, tommasini commented on app/components/UI/FormTextField/index.tsx
> +        isDisabled || disabled ? styles.disabled : undefined,
Ah I see why, it's because snaps can have both of this properties!

2025-02-21 15:38 UTC, FrederikBolding commented on app/components/UI/FormTextField/index.tsx
> +        isDisabled || disabled ? styles.disabled : undefined,
I agree that this should be cleaned up. There's a couple of other things like that in this PR, I'm working on follow-up PRs to this PR that'll be smaller in scope and easier to review. This PR has gotten out of hand

2025-02-21 15:38 UTC, tommasini commented on app/core/Engine/Engine.ts
> +    const snapInterfaceController = new SnapInterfaceController({
Just to add that now tehre is a completely new pattern that it was introduced yesterday: https://github.com/MetaMask/metamask-mobile/pull/13065 

Just referencing, this can totally be in a refactor PR so we can have the changes in sooner and can keep working towards the goals.

2025-02-21 15:39 UTC, FrederikBolding commented on app/core/Engine/Engine.ts
> +    const snapInterfaceController = new SnapInterfaceController({
We should refactor all the Snaps controller init like we just did on the extension, out of scope IMO

2025-02-21 15:42 UTC, FrederikBolding commented on app/components/UI/FormTextField/index.tsx
> +        isDisabled || disabled ? styles.disabled : undefined,
https://github.com/MetaMask/snaps/issues/3145

2025-02-21 15:45 UTC, tommasini commented on app/components/Snaps/SnapUIRenderer/utils.ts
> +      sha256(
Sounds great! Let's keep an eye on this then!

2025-02-21 16:18 UTC, ffmcgee725 approved these changes

2025-02-21 16:22 UTC, tommasini approved these changes
LGTM! After talking with @FrederikBolding there is the decision of addressing some of the highlighted stuff like the criptography in another PRs to keep it easier for reviews!

2025-02-21 16:40 UTC, merged