feat: feature-flag-controller
MetaMask/metamask-mobile pull request #12427
Opened 2024-11-26 09:52 UTC by joaoloureirop

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-11-26 18:24 UTC, joaoloureirop commented on app/core/Engine.ts
> +        allowedEvents: ['PreferencesController:stateChange'],
might not be needed

2024-11-26 19:32 UTC, joaoloureirop commented on app/core/Engine.ts
> +        allowedEvents: ['PreferencesController:stateChange'],
addressed https://github.com/MetaMask/metamask-mobile/pull/12427/commits/27b32a3bf00c8c429c1532cf063a441eb82e9074

2024-11-26 19:48 UTC, joaoloureirop commented on metro.config.js
> +
To be removed once controller has been published to NPM

Will revert 00a3bd164f163a714d4e15e921dbb300b1fc70fb

2024-11-26 19:49 UTC, joaoloureirop commented on yarn.lock
>  "@metamask/rpc-errors@7.0.1", "@metamask/rpc-errors@^6.0.0", "@metamask/rpc-errors@^6.2.1", "@metamask/rpc-errors@^6.3.1", "@metamask/rpc-errors@^7.0.0", "@metamask/rpc-errors@^7.0.1":
update once controller has been published to NPM

2024-11-26 21:21 UTC, Cal-L commented on app/selectors/featureFlagController/index.ts
Let's bucket these new selectors into `selectors/platform` directory, which the platform team will own. It probably isn't necessary to create another directory for `minimumAppVersion` as well since it's just part of the featureFlagController. The structure that could scale nicely may look like this:

`selectors/platform/featureFlagController`
This folder would then hold files 
`index.ts` - selectors
`index.test.ts` - tests for selectors
`constants.ts` - constants (your mocked values are also constants, which can go here)
`types.ts` - types

This pattern can scale as we add more controllers and could apply to other teams well

2024-11-26 22:11 UTC, joaoloureirop commented on app/selectors/featureFlagController/index.ts
What are you trying to achieve with directories with team names?

If the concern is feature flags ownership, then the `CODEOWNERS` file should be used instead.

2024-11-27 10:57 UTC, joaoloureirop commented on app/selectors/featureFlagController/index.ts
The directory naming based on team names is concerning due to the high chance of tech debt increase.
Internal team names can change without product or code changes. Directory names and their imports will easily become meaningless and confusing. It will become one more refactor necessity to minimize code rot.

[A feature flag can be a boolean, string, number, or a JSON object.](https://docs.launchdarkly.com/sdk/concepts/flag-types#understanding-flag-types)  Having multiple feature flags in a single place might be tempting to avoid multiple file creation but, will quickly turn into a big ball of mud with their unique fallbacks, selectors, mocks, tests all mixed up.

Would love some more insights and feedback on having a structure like that, because I see drawbacks with no benefit.

2024-11-27 14:53 UTC, joaoloureirop commented on app/core/Engine/Engine.ts
> +        disableSnaps: !isBasicFunctionalityEnabled,
Great catch, thank you!

addressed 559c26fe7e792c843daeb018351a25009a81e725

2024-11-27 15:09 UTC, joaoloureirop commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +    expect(androidMinimumAPIVersion).toBe(1026);
TODO:
- Test feature flag state selectors separate
- replace hardcoded numbers with mocked values.

2024-11-27 15:10 UTC, joaoloureirop commented on app/core/Engine/controllers/RemoteFeatureFlagController/index.ts
> +const init = ({
TODO:
- add remote feature flag controller unit tests

2024-11-27 15:11 UTC, joaoloureirop commented on app/reducers/index.ts
> -  featureFlags: FeatureFlagsState;
TODO:
- create migration to remove featureFlags state

2024-11-27 17:36 UTC, Cal-L commented on app/selectors/featureFlagController/index.ts
Completely agree with the concern here and your point makes sense. The org has been moving towards codeowner based structures for a while now so there will be other opinions on this as well. we'll bring up this topic in the MCOP/engineering sync to get more thoughts. We can the codeowner based folder structure out for now.

2024-11-27 17:58 UTC, NicolasMassart reviewed
First pass of review

2024-11-27 17:58 UTC, NicolasMassart commented on app/components/hooks/MinimumVersions/useMinimumVersions.tsx
> +  const appMinimumBuild = useSelector((state: RootState) => selectAppMinimumBuild(state));
Q: not sure if this change makes the mock in the test obsolete and how this test doesn't need any changes.

2024-11-27 17:58 UTC, NicolasMassart commented on app/core/Engine/controllers/RemoteFeatureFlagController/index.ts
> +const init = ({
is this a TODO?

2024-11-27 18:17 UTC, joaoloureirop commented on .github/CODEOWNERS
> +app/selectors/featureFlagController/index.ts                @MetaMask/mobile-platform
We want  `app/selectors/featureFlagController/<featureFlagName>` to be owned by other teams

I'll update the `CODEOWNERS` syntax to match files like `featureFlagController/index.ts` but no further nested files

2024-11-27 18:19 UTC, joaoloureirop commented on app/reducers/index.ts
> -  featureFlags: FeatureFlagsState;
addressed on d7d384c00dc19b00e4e16b619216dca186625c20

2024-11-27 18:23 UTC, joaoloureirop commented on .github/CODEOWNERS
> +app/selectors/featureFlagController/index.ts                @MetaMask/mobile-platform
addressed on b784e89e226916a201d204ee80cdb52bc0fe7292

2024-11-27 18:37 UTC, NicolasMassart reviewed
Thanks for this awesome work @joaoloureirop!
Added some guideline suggestions and a few questions on some code parts I'm not sure to fully understand.

2024-11-27 18:37 UTC, NicolasMassart commented on app/core/Engine/Engine.ts
> +    const getBasicFunctionalityToggleState = () =>
S: should we use a selector here?

2024-11-27 18:37 UTC, NicolasMassart commented on app/core/Engine/Engine.ts
> +      disabled: getBasicFunctionalityToggleState() === false
Q: why testing the exact boolean false equality here?
If the value is true, it's true.
If the value is false, it's true.
If the value eis anything like undefined or null, it will be true because of the getBasicFunctionalityToggleState default.
So if we have a false here, it's necessarily a real false as a value in the state. So the following would be enough:
```suggestion
      disabled: !getBasicFunctionalityToggleState()
```
and same on line 949

2024-11-27 18:37 UTC, NicolasMassart commented on app/core/Engine/controllers/RemoteFeatureFlagController/index.ts
> +const init = ({
Thanks. Yes unit tests please!

2024-11-27 18:37 UTC, NicolasMassart commented on app/selectors/featureFlagController/index.test.ts
> +  it('should return feature flag initial state', () => {
```suggestion
  it('returns feature flag initial state', () => {
```

2024-11-27 18:37 UTC, NicolasMassart commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +  it('should return feature flag object', () => {
```suggestion
  it('returns feature flag object', () => {
```

2024-11-27 18:37 UTC, NicolasMassart commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +  it('should return fallback values', () => {
```suggestion
  it('returns fallback values', () => {
```

2024-11-27 18:37 UTC, NicolasMassart commented on app/selectors/featureFlagController/minimumAppVersion/index.ts
> +    androidMinimumAPIVersion: 21,
S: should we have this in a constants file?

2024-11-27 18:37 UTC, NicolasMassart commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +  it('should return fallback values', () => {
Q: we only have this test that tests the fallback values. How do we test the normal values? Could we have a mocked test for this?

2024-11-27 18:37 UTC, NicolasMassart commented on app/store/migrations/061.test.ts
> +    it(`should capture exception if ${scenario}`, async () => {
```suggestion
    it(`captures exception if ${scenario}`, async () => {
```

2024-11-27 18:37 UTC, NicolasMassart commented on app/store/migrations/061.test.ts
> +  it('remove featureFlags property from redux state', async () => {
```suggestion
  it('removes featureFlags property from redux state', async () => {
```

2024-11-27 18:39 UTC, NicolasMassart commented on app/components/hooks/MinimumVersions/useMinimumVersions.tsx
> +  const appMinimumBuild = useSelector((state: RootState) => selectAppMinimumBuild(state));
I'm surprised the test is passing given the changes in the hook... so maybe rewrite the test in a more robust way. A change like this should make it fail otherwise it probably means it's not testing anything but the mocks...

2024-11-27 21:14 UTC, Cal-L reviewed
Left some comments

2024-11-27 21:14 UTC, Cal-L commented on app/core/Engine/controllers/RemoteFeatureFlagController/index.ts
In this case, it's debatable whether or not we should just put all of the functions in index or utils file. IMO, creating the utils file and re-exporting via index allows us to be more flexible in the future, where index can export other things such as constants, etc.

2024-11-27 21:14 UTC, Cal-L commented on app/store/index.ts
> -    // Fetch feature flags only if basic functionality is enabled
Let's confirm that the code above this is also no longer needed. Rehydration should automatically populate it already

2024-11-27 21:14 UTC, Cal-L commented on app/store/migrations/061.ts
> +  return state;
Let's update this migration to include the default state for `RemoteFeatureFlagController` to be safe

2024-11-28 17:22 UTC, joaoloureirop commented on app/store/index.ts
> -    // Fetch feature flags only if basic functionality is enabled
Let's address that in a separate PR as it is out of scope

2024-11-28 18:33 UTC, joaoloureirop commented on app/store/migrations/061.ts
> +  return state;
default state is `undefined`, as with a clean redux store

2024-11-28 20:05 UTC, DDDDDanica commented on app/selectors/featureFlagController/index.ts
> +export const selectRemoteFeatureFlagsCacheTimestamp = createSelector(
Just a question: under which circumstance will we use this selector?

2024-11-28 20:40 UTC, joaoloureirop commented on app/selectors/featureFlagController/index.ts
> +export const selectRemoteFeatureFlagsCacheTimestamp = createSelector(
Probably none, I might remove it.

2024-11-28 20:44 UTC, joaoloureirop commented on app/selectors/featureFlagController/index.ts
> +export const selectRemoteFeatureFlagsCacheTimestamp = createSelector(
removed on 7bdcc819ac62606992b2bdecde4d2eb6209f7ab2

2024-11-28 20:46 UTC, joaoloureirop commented on app/core/Engine/controllers/RemoteFeatureFlagController/types.ts
> +  controllerMessenger: ControllerMessenger,
addressed on [f5b754f](https://github.com/MetaMask/metamask-mobile/pull/12427/commits/f5b754ffb535100874030e58c3def43858e36dca)

2024-11-28 20:46 UTC, joaoloureirop commented on app/core/Engine/controllers/RemoteFeatureFlagController/types.ts
> +  initialState: Partial<EngineState>;
addressed on [f5b754f](https://github.com/MetaMask/metamask-mobile/pull/12427/commits/f5b754ffb535100874030e58c3def43858e36dca)

2024-11-28 20:46 UTC, joaoloureirop commented on app/core/Engine/controllers/RemoteFeatureFlagController/index.ts
> +    messenger: controllerMessenger.getRestricted({
addressed on [f5b754f](https://github.com/MetaMask/metamask-mobile/pull/12427/commits/f5b754ffb535100874030e58c3def43858e36dca)

2024-11-28 20:46 UTC, joaoloureirop commented on app/core/Engine/controllers/RemoteFeatureFlagController/index.ts
> +      ...initialState.RemoteFeatureFlagController
addressed on [f5b754f](https://github.com/MetaMask/metamask-mobile/pull/12427/commits/f5b754ffb535100874030e58c3def43858e36dca)

2024-11-28 20:46 UTC, joaoloureirop commented on app/core/Engine/controllers/RemoteFeatureFlagController/index.ts
> +const init = ({
addressed on [f5b754f](https://github.com/MetaMask/metamask-mobile/pull/12427/commits/f5b754ffb535100874030e58c3def43858e36dca)

2024-11-28 20:46 UTC, joaoloureirop commented on app/core/Engine/controllers/RemoteFeatureFlagController/index.ts
addressed on [f5b754f](https://github.com/MetaMask/metamask-mobile/pull/12427/commits/f5b754ffb535100874030e58c3def43858e36dca)

2024-11-28 21:02 UTC, DDDDDanica commented on app/selectors/featureFlagController/index.ts
> +export const selectRemoteFeatureFlags = createSelector(
I was thinking our daily use case. A dev/team working on a feature behind a flag, might not care about the whole dataset, but just the one team is working on. How about we narrow down the selector to selectRemoteFeatureFlagByName, while we can pass in a name string and only return the value of that key when requested? what's your insight on this one?

2024-11-28 22:26 UTC, DDDDDanica commented on app/selectors/featureFlagController/index.ts
> +export const selectRemoteFeatureFlags = createSelector(
discussed with Dan and keep a general fetch for all feature flags is simplier [here](https://github.com/MetaMask/metamask-extension/pull/28684#discussion_r1862725486). resolved the thread now 🙌🏻

2024-11-28 22:38 UTC, tommasini commented on app/core/Engine/types.ts
> +} from '@metamask/remote-feature-flag-controller';
It seems that we will need to add this to the declarations file for now

2024-11-29 00:34 UTC, Gudahtt commented on app/core/Engine/controllers/RemoteFeatureFlagController/index.ts
Nit: Maybe better to name this directory `platform` instead to preserve the team grouping, so that we can include other controllers here too in the future

2024-11-29 00:37 UTC, Gudahtt commented on app/core/Engine/controllers/RemoteFeatureFlagController/utils.ts
> +  try {
The controller should not be constructed in a `try` block, it's not fallible. It can't throw. If it does throw we would want the app to crash, because it would be an urgent problem that we wouldn't want buried in the log for us to discover too late.

2024-11-29 00:38 UTC, Gudahtt commented on app/core/Engine/types.ts
> +} from '@metamask/remote-feature-flag-controller';
No need, it is published, we can use the real package with real types now

2024-11-29 00:40 UTC, Gudahtt commented on app/selectors/featureFlagController/minimumAppVersion/index.ts
> +    return featureFlagValues as FeatureFlagType;
Why are we casting here? By doing this we're declaring this value to be a number, but we haven't validated that. This makes the type inaccurate.

2024-11-29 09:58 UTC, joaoloureirop commented on metro.config.js
> +
resolved e54d05d551d5522926bd7309df34670be4a84736

2024-11-29 09:58 UTC, joaoloureirop commented on metro.config.js
> +      unstable_enableSymlinks: true,
resolved e54d05d551d5522926bd7309df34670be4a84736

2024-11-29 09:58 UTC, joaoloureirop commented on yarn.lock
>  "@metamask/rpc-errors@7.0.1", "@metamask/rpc-errors@^6.0.0", "@metamask/rpc-errors@^6.2.1", "@metamask/rpc-errors@^6.3.1", "@metamask/rpc-errors@^7.0.0", "@metamask/rpc-errors@^7.0.1":
resolved e54d05d551d5522926bd7309df34670be4a84736

2024-11-29 12:22 UTC, joaoloureirop commented on app/selectors/featureFlagController/minimumAppVersion/index.ts
> +    return featureFlagValues as FeatureFlagType;
I've changed the types on the selector to improve type inference

resolved on b003b6aae56aecf877222b38e0c11e855406b06a

2024-11-29 12:32 UTC, joaoloureirop commented on app/core/Engine/controllers/RemoteFeatureFlagController/utils.ts
> +  try {
resolved 6f709eb4ad9fa2186b4b74a84ed251644663545e

2024-11-29 12:37 UTC, joaoloureirop commented on app/core/Engine/controllers/RemoteFeatureFlagController/index.ts
I'm concerned about the potential tech debt we add when the team's name-based namings enter the codebase.

[See another discussion around this topic.](https://github.com/MetaMask/metamask-mobile/pull/12427#discussion_r1860452762)

2024-11-29 12:43 UTC, joaoloureirop commented on app/core/Engine/types.ts
> +} from '@metamask/remote-feature-flag-controller';
resolved b4fb8662a16640e71490eff858bacd64899560f2

2024-11-29 16:28 UTC, joaoloureirop commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +    expect(androidMinimumAPIVersion).toBe(1026);
resolved 96ca13b364a7de2d3004d2033ea1e7462eb38bde

2024-11-29 16:40 UTC, Gudahtt commented on app/core/Engine/controllers/RemoteFeatureFlagController/index.ts
Well, we could think of it as "feature areas" instead perhaps, which roughly correlate to teams but are more long-lasting.

The purpose (as I understood it) of moving controller-related code to dedicated files was that it allowed us to assign more appropriate code owners (i.e. teams) and reduce code review burden and regression risk that comes from modifying core modules like `Engine.ts`.

But the problem is that there are very few changes that affect _just_ a controller. If we co-located multiple controllers owned by the same team, it would be more effective in minimizing cross-team impact/reviews for changes to how controllers interact with each other. If each controller is separate, then their interactions would be via `Engine.ts` still so we don't get that benefit.

2024-11-29 17:02 UTC, joaoloureirop commented on app/core/Engine/Engine.ts
> +    const getBasicFunctionalityToggleState = () =>
Yes, that would be more appropriate.

2024-11-29 17:02 UTC, joaoloureirop commented on app/core/Engine/Engine.ts
> +    const getBasicFunctionalityToggleState = () =>
addressed 50795f03f5cda3c5a4ad2eb42ffe680fa7c59e98

2024-11-29 17:04 UTC, joaoloureirop commented on app/core/Engine/Engine.ts
> +      disabled: getBasicFunctionalityToggleState() === false
Good point Nico. Although false equality stands out to the eyes more than negation, I agree with you about simplifying this expression.

2024-11-29 17:04 UTC, joaoloureirop commented on app/core/Engine/Engine.ts
> +      disabled: getBasicFunctionalityToggleState() === false
addressed 50795f03f5cda3c5a4ad2eb42ffe680fa7c59e98

2024-11-29 17:05 UTC, joaoloureirop commented on app/selectors/featureFlagController/index.test.ts
> +  it('should return feature flag initial state', () => {
addressed 96ca13b364a7de2d3004d2033ea1e7462eb38bde

2024-11-29 17:06 UTC, joaoloureirop commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +  it('should return fallback values', () => {
addressed 96ca13b364a7de2d3004d2033ea1e7462eb38bde

2024-11-29 17:06 UTC, joaoloureirop commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +  it('should return fallback values', () => {
addressed 96ca13b364a7de2d3004d2033ea1e7462eb38bde

2024-11-29 17:12 UTC, joaoloureirop commented on app/store/migrations/061.test.ts
> +    it(`should capture exception if ${scenario}`, async () => {
addressed 01261192e1cf576d31e7c6131f24d2ae78bb63c9

2024-11-29 17:12 UTC, joaoloureirop commented on app/store/migrations/061.test.ts
> +  it('remove featureFlags property from redux state', async () => {
addressed 01261192e1cf576d31e7c6131f24d2ae78bb63c9

2024-11-29 17:13 UTC, joaoloureirop commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +  it('should return feature flag object', () => {
addressed 96ca13b364a7de2d3004d2033ea1e7462eb38bde

2024-11-29 19:43 UTC, joaoloureirop commented on app/core/Engine/controllers/RemoteFeatureFlagController/index.ts
I recognize the benefits of organizing the codebase in a feature-based structure. It helps with ownership and better outlines the relationship between components.

Namings that carry meaning for the codebase / product are long-lasting and do not need to be revisited if there's any maintainer's restructuring.

I'll leave it as is for now and follow up with an update when there's a decision on feature area names.

2024-12-02 10:17 UTC, NicolasMassart commented on app/core/Engine/controllers/RemoteFeatureFlagController/index.ts
Just a note on the feature scope source folders naming: I totally agree with the pros, making things easier and faster to review, but do not forget about the cons:
- feature is then tied to a group/team and moving responsibility requires changing the app folders structure,
- siloing features mean less need for review from other team, so less knowledge sharing
- isolating features also tends to make code practices diverge. We see that for metametrics where we have already 3 kind of wrappers. So we will have to do even bigger efforts in standardizing and work with guidelines.

2024-12-02 10:44 UTC, NicolasMassart requested changes
update tests please

2024-12-02 10:44 UTC, NicolasMassart commented on app/core/Engine/controllers/RemoteFeatureFlagController/utils.test.ts
> +    it('should create controller with correct config when enabled', () => {
Can we, once and for all, agree that we have to name tests according to our guidelines and not according to whatever AI outputs?
```suggestion
    it('creates controller with correct config when enabled', () => {
```

2024-12-02 10:44 UTC, NicolasMassart commented on app/core/Engine/controllers/RemoteFeatureFlagController/utils.test.ts
> +    it('should handle initial state correctly', () => {
Try to avoir the use of terms like handle or correctly.
Handle means do something with... so just say waht we do exactly. Here we want to check the controller actually uses the initial state to set its internal state.
Also correctly means whatever you put in it. What is correct to you may not be correct for someone else. So be more specific, what is a correct handling?
Here a correct handling, for what I can read in the test, seems to me when the controler internal exactly state matches the initial state.
So let's be it. Name it:
```suggestion
    it('internal state matches initial state', () => {
```

2024-12-02 10:44 UTC, NicolasMassart commented on app/core/Engine/controllers/RemoteFeatureFlagController/utils.test.ts
> +    it('should call updateRemoteFeatureFlags when enabled', () => {
```suggestion
    it('calls updateRemoteFeatureFlags when enabled', () => {
```

2024-12-02 10:44 UTC, NicolasMassart commented on app/core/Engine/controllers/RemoteFeatureFlagController/utils.test.ts
> +    it('should not throw when receive corrupted data', () => {
```suggestion
    it('does not throw when initial state is corrupted', () => {
```
Also as a dev looking at this code for the first time, I would love to have this test tell me more about why this is considered corrupted data, why the controller can receive corrupted data and why we don't type data with an interface or type to prevent this corruption.

2024-12-02 10:44 UTC, NicolasMassart commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +  it('empty feature flag state: returns default value', () => {
update naming

2024-12-02 10:44 UTC, NicolasMassart commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +  it('undefined RemoteFeatureFlagController state: returns default value', () => {
update naming

2024-12-02 10:44 UTC, NicolasMassart commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +  it('empty feature flag state: returns default value', () => {
update naming

2024-12-02 10:44 UTC, NicolasMassart commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +  it('empty feature flag state: returns default value', () => {
update naming

2024-12-02 10:44 UTC, NicolasMassart commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +  it('undefined RemoteFeatureFlagController state: returns default value', () => {
update naming

2024-12-02 10:44 UTC, NicolasMassart commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +  it('empty feature flag state: returns default value', () => {
update naming

2024-12-02 16:18 UTC, joaoloureirop commented
I've revisited the controller initialisation testing. 
- unit test that can't be validated without mocking the feature flag service were removed.
- unit tests names were improved.

For the selector, the unit test names were updated

2024-12-02 16:18 UTC, joaoloureirop commented
I've revisited the controller initialisation testing. 
- unit test that can't be validated without mocking the feature flag service were removed.
- unit tests names were improved.

For the selector, the unit test names were updated

Thanks for your review @NicolasMassart

2024-12-02 16:38 UTC, NicolasMassart reviewed
allowing myself to fix some typos and missing 'when' directly

2024-12-02 16:38 UTC, NicolasMassart commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +  it('returns default value empty feature flag state', () => {
```suggestion
  it('returns default value when empty feature flag state', () => {
```

2024-12-02 16:38 UTC, NicolasMassart commented on app/selectors/featureFlagController/minimumAppVersion/index.test.ts
> +  it('returns default value empty feature flag state', () => {
```suggestion
  it('returns default value when empty feature flag state', () => {
```

2024-12-02 16:58 UTC, NicolasMassart approved these changes
Looks good to me on the code side.

2024-12-02 18:34 UTC, merged