feat: multi chain asset list
MetaMask/metamask-mobile pull request #12431
Opened 2024-11-26 15:11 UTC by vinnyhoward

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

NA

### **Before**

NA

### **After**

NA

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-11-27 22:11 UTC, gambinish commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +        );
Maybe we can `.catch` any errors here to stop execution, in the edge case that this fails.

2024-11-27 23:13 UTC, vinnyhoward commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +        );
Yeah great idea, similar to what is being done for extension

2024-11-27 23:37 UTC, gambinish commented on app/components/UI/Tokens/TokensBottomSheet/TokenFilterBottomSheet.tsx
> +  );
It looks like the changes to this bottom sheet might be able to be separated into it's own PR?

One benefit that we saw in extension, was that breaking out a small, low risk piece like this, allowed us to also break out a lot of the fixture mocks needed for e2e. Made the final PR much smaller.

2024-11-28 21:24 UTC, vinnyhoward commented on app/components/UI/Ramp/Views/BuildQuote/__snapshots__/BuildQuote.test.tsx.snap
> +                      "alignItems": "center",
Yeah I have two pending PRs and have some others in mind that can be broken up that will make this smaller and can be merged independently from PR
https://github.com/MetaMask/metamask-mobile/pull/12405
https://github.com/MetaMask/metamask-mobile/pull/12293

2024-12-04 13:49 UTC, jonybur requested changes, later dismissed

2024-12-04 13:49 UTC, jonybur commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +    // eslint-disable-next-line @typescript-eslint/no-explicit-any
Not blocker: We should get this TODO either fixed or linked to a ticket

2024-12-04 13:49 UTC, jonybur commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +      navigation.navigate('Swaps', {
Seems like we are repeating this block:
```
        navigation.navigate('Swaps', {
          screen: 'SwapsAmountView',
          params: {
            sourceToken: asset.address ?? swapsUtils.NATIVE_SWAPS_TOKEN_ADDRESS,
            sourcePage: 'MainView',
            chainId: asset.chainId,
          },
        });
```
There's probably a way to alter the logic so that we dont have repeated blocks like that

2024-12-04 13:49 UTC, jonybur commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +    secondaryBalance = asset.balanceFiat;
Same here, seems like our code is repeating blocks of logic across several components

2024-12-04 13:49 UTC, jonybur commented on app/components/UI/Stake/hooks/useStakingChain.ts
> +  // const chainId = useSelector(selectChainId); // Removed the useSelector hook
Remove this line?

2024-12-04 13:49 UTC, jonybur commented on app/selectors/multichain.ts
> +        // TODO: Check if this is correct for native tokens
Is this TODO still necessary?

2024-12-04 13:49 UTC, jonybur commented on app/selectors/multichain.ts
> +            // TODO: Some exchange rates for some tokens don't exist? Is this expected?
TODO?

2024-12-04 13:49 UTC, jonybur commented on app/selectors/tokensController.ts
> +// TODO: Double check this make sure this allTokens change plays nice with original view
TODO here, could be covered with a test

2024-12-04 20:15 UTC, vinnyhoward commented on app/selectors/tokensController.ts
> +// TODO: Double check this make sure this allTokens change plays nice with original view
Tests have recently been udpated

2024-12-04 20:16 UTC, vinnyhoward commented on app/selectors/multichain.ts
> +            // TODO: Some exchange rates for some tokens don't exist? Is this expected?
Old comment and no longer an issue. I'll remove TODO

2024-12-04 20:16 UTC, vinnyhoward commented on app/selectors/multichain.ts
> +        // TODO: Check if this is correct for native tokens
No its no longer needed. I'll remove

2024-12-04 20:19 UTC, vinnyhoward commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +    // eslint-disable-next-line @typescript-eslint/no-explicit-any
It was updated with a type 2 weeks ago but the comment wasn't removed. I'll remove now

2024-12-04 23:55 UTC, vinnyhoward commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +    secondaryBalance = asset.balanceFiat;
This is because of some feature flag logic. This will be simplified once the feature flag is removed

2024-12-09 21:48 UTC, Matt561 commented on app/components/UI/Stake/components/StakingBalance/StakingBalance.test.tsx
> +  (isPortfolioViewEnabled() ? it.skip : it)('render matches snapshot', () => {
Is this temporary while another feature is in progress? Ideally we wouldn't want to conditionally run tests.

2024-12-09 21:50 UTC, Matt561 reviewed
I left a comment related to running a staking snapshot test conditionally. Otherwise, staking-owned files look good to me!

2024-12-09 22:38 UTC, vinnyhoward commented on app/components/UI/Stake/components/StakingBalance/StakingBalance.test.tsx
> +  (isPortfolioViewEnabled() ? it.skip : it)('render matches snapshot', () => {
Noted! I'll fix this now

2024-12-09 23:01 UTC, darkwing approved these changes, later dismissed

2024-12-10 00:14 UTC, vinnyhoward commented on app/components/UI/Stake/components/StakingBalance/StakingBalance.test.tsx
> +  (isPortfolioViewEnabled() ? it.skip : it)('render matches snapshot', () => {
Just updated it. It now doesn't conditionally  skip but runs a separate test specifically for the feature flag snapshot

2024-12-10 10:04 UTC, tommasini commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +    selectNativeCurrencyByChainId(state, asset.chainId as Hex),
Is there the possibility to fix the type instead of cast here?

2024-12-10 10:18 UTC, tommasini commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +    currentAddress = asset.address as Hex;
Same here

2024-12-10 10:18 UTC, tommasini commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +      : (asset.address as Hex);
Same here

2024-12-10 10:18 UTC, tommasini commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +        await NetworkController.setActiveNetwork(networkClientId as string);
For thr networkCkientId as well

2024-12-10 10:18 UTC, tommasini commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +        chainId as Hex
chainId should be hex already no? I wonder why typescript complains about it

2024-12-10 10:18 UTC, tommasini commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +    secondaryBalance = exchangeRate ? asset.balanceFiat : '';
This fallbackk changed, flagging this line to understand what happens if secondaryBalance is an empty string

2024-12-10 10:52 UTC, sahar-fehri commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +    secondaryBalance = exchangeRate ? asset.balanceFiat : '';
Hi @tommasini if this is empty then it wont be displayed in the UI; I think the logic has slightly changed this is why the fallback also have changed

2024-12-10 10:57 UTC, sahar-fehri commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +        chainId as Hex
Yes i think we could remove the cast on this one;
Thank you @tommasini  for your feedback 🙏  We have plans to do a follow up PR to refactor; and  we will address your ts comments on a followup PR.

Unless its a major thing that we should address; i think we can followup on this PR 🙏

2024-12-10 11:14 UTC, tommasini commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +      trackEvent(
Does it make sense to move the trackEvent to `handleSwapNavigation` since we want to track the navigation from the TokenDetails to swap I think it's still accurate if we change it to there

2024-12-10 11:14 UTC, tommasini commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +        chainId as Hex
Sounds great!

2024-12-10 11:15 UTC, tommasini commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +    secondaryBalance = exchangeRate ? asset.balanceFiat : '';
Thank you for the explanation!

2024-12-10 11:19 UTC, tommasini commented on app/components/UI/AssetOverview/TokenDetails/TokenDetails.tsx
> +    selectTokenMarketDataByChainId(state, asset.chainId as Hex),
Flagging this cast

2024-12-10 11:19 UTC, tommasini commented on app/components/UI/AssetOverview/TokenDetails/TokenDetails.tsx
> +    selectNativeCurrencyByChainId(state, asset.chainId as Hex),
flagging this cast

2024-12-10 11:21 UTC, tommasini commented on app/components/UI/AssetOverview/TokenDetails/TokenDetails.tsx
> +    marketData = tokenExchangeRates?.[tokenContractAddress as Hex];
This cast is new, most likely because the logic behind the portfolio view could be better typed or we have a new fallback to handle?

2024-12-10 11:25 UTC, tommasini commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +    ? (asset.chainId as Hex)
Flagging this cast

2024-12-10 11:26 UTC, tommasini commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +    ? multiChainTokenBalance?.[selectedInternalAccountAddress as Hex]?.[
flagging this cast

2024-12-10 11:26 UTC, tommasini commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +        chainId as Hex
Flagging this cast

2024-12-10 11:26 UTC, tommasini commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +    networkConfigurations?.[chainId as Hex]?.nativeCurrency;
flagging this cast

2024-12-10 11:28 UTC, tommasini commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +      exchangeRates || {},
It seems that any of this fallbacks is harmless, although, If we are doing a follow up PR to fix typing, can we please fix this anys: https://github.com/MetaMask/metamask-mobile/blob/b2f9eecdd24008b0338a0f3fb5bb6a134dec2040/app/components/UI/Tokens/util/deriveBalanceFromAssetMarketDetails.ts#L12

2024-12-10 11:34 UTC, tommasini commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +      currentCurrency || '',
Just confirming that we want to show no current currency if this fallsback to an empty string
https://github.com/MetaMask/metamask-mobile/blob/8229dbcc07de3506ab3e0d1082502c2618ea1cc9/app/util/number/index.js#L525

If so we should fix it on `deriveBalanceFromAssetMarketDetails ` instead of where it's called right?
Since it's used in [Tokens](https://github.com/MetaMask/metamask-mobile/blob/eefb4280e5e4c2834b3383e2fbaae2e6e9a158c5/app/components/UI/Tokens/index.tsx#L131) and [TokenListItem](https://github.com/MetaMask/metamask-mobile/blob/b2f9eecdd24008b0338a0f3fb5bb6a134dec2040/app/components/UI/Tokens/TokenList/TokenListItem/index.tsx#L93) this will help have parity while the function itself handles the fallbacks.

2024-12-10 11:35 UTC, sahar-fehri commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +      exchangeRates || {},
I see that the "any" in the `deriveBalanceFromAssetMarketDetails` fct were not introduced specifically in this PR but i agree that we need to address it; can we follow up on this one too 🙏

2024-12-10 11:36 UTC, tommasini commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +      ? multiChainMarketData?.[chainId as Hex]?.[asset.address as Hex]
flag cast

2024-12-10 11:36 UTC, tommasini commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +      ? multiChainMarketData?.[chainId as Hex]?.[zeroAddress() as Hex]
flag cast

2024-12-10 11:36 UTC, tommasini commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +      ? exchangeRates?.[itemAddress as Hex]?.pricePercentChange1d
flag cast

2024-12-10 11:36 UTC, tommasini commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +      : exchangeRates?.[zeroAddress() as Hex]?.pricePercentChange1d;
flag cast

2024-12-10 11:37 UTC, tommasini commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +      const defaultNetwork = getDefaultNetworkByChainId(currentChainId) as any;
We should never use any

2024-12-10 11:38 UTC, tommasini commented on app/components/UI/Tokens/index.tsx
> +      ).flat() as TokenI[];
Flagging cast

2024-12-10 11:38 UTC, tommasini commented on app/components/UI/Tokens/index.tsx
> +                tokenExchangeRates || {},
Check here: https://github.com/MetaMask/metamask-mobile/pull/12431/files#r1877933307

2024-12-10 11:56 UTC, sahar-fehri commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +      const defaultNetwork = getDefaultNetworkByChainId(currentChainId) as any;
I think any was used here because `getDefaultNetworkByChainId` was not typed; 
Exp of another usage on main: https://github.com/MetaMask/metamask-mobile/blob/9d63e3407607e32e7fadc2b33c2d776193d930a3/app/util/networks/index.js#L405

2024-12-10 12:02 UTC, tommasini commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +          chainId={chainId as Hex}
Flag cast

2024-12-10 12:12 UTC, tommasini commented on app/components/UI/Tokens/util/filterAssets.ts
> +const filterCallbacks: FilterCallbacksT = {
Can we add a TSDoc explanation here?

2024-12-10 12:12 UTC, tommasini commented on app/components/UI/Tokens/util/filterAssets.ts
> +export function filterAssets<T>(assets: T[], criteria: FilterCriteria[]): T[] {
And here it would be good to have a TSDoc as well

2024-12-10 12:40 UTC, tommasini commented on app/components/Views/AssetOptions/AssetOptions.tsx
> +                  chainIdToUse as Hex,
Flagging cast

2024-12-10 12:45 UTC, salimtb commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +      currentCurrency || '',
If I understand correctly, you're suggesting that we set default values directly in the `deriveBalanceFromAssetMarketDetails` function instead of implementing the fallback in this way. We prefer to make these changes in a separate PR when the feature flag is set to `true`. We don’t believe this approach will cause any issues if we leave it as is for now.

2024-12-10 12:47 UTC, salimtb commented on app/components/UI/Tokens/index.tsx
> +                tokenExchangeRates || {},
answer on the flagged message

2024-12-10 12:48 UTC, tommasini commented on app/components/Views/Wallet/index.tsx
> +            return AccountTrackerController.refresh(networkClientId);
Curious question, is there any plan to optimise this[ refresh function](https://github.com/MetaMask/core/blob/f5ad522451002eb2b56fdac78d2b11ad26ac471a/packages/assets-controllers/src/AccountTrackerController.ts#L356), since we use mutex, I believe this will only be called once, I wonder if we could architect a `refreshAll` function to accept multiple networkClientIds, I believe that way we could be able to improve the performance of this! Food for thoughts!

2024-12-10 12:49 UTC, tommasini commented on app/components/Views/Wallet/index.tsx
> +            return AccountTrackerController.refresh(networkClientId);
We are calling all this promises at once, which makes me doubt if the mutex under the hood really works for all of them or just for the first or just ignore some of the `networkClietId` that receives while the other is still running

2024-12-10 12:50 UTC, salimtb commented on app/components/UI/Tokens/TokenList/TokenListItem/index.tsx
> +          ticker={asset.ticker || ''}
this is a small nit , we will address this on a separated follow up PR

2024-12-10 12:56 UTC, tommasini commented on app/reducers/swaps/index.js
> +const swapsControllerAndUserTokensMultichain = createSelector(
Could we add TSDdoc and unit tests for this selector?

2024-12-10 12:59 UTC, tommasini commented on app/selectors/currencyRateController.ts
> +    currencyRateControllerState?.currencyRates,
What happens if this is undefined? It would be good for we to start handle this scenarios directly on the selector to type the way the consumers components use the data

2024-12-10 13:04 UTC, tommasini commented on locales/languages/en.json
> +    "switch_network_to_view_transactions": "Please switch network to view transactions",
We can't merge this and cut it directly to the release, will not include the translations for this copy

2024-12-10 13:06 UTC, tommasini commented on patches/@metamask+assets-controllers+45.1.1.patch
> ++  // TODO: Either fix this lint violation or explain why it's necessary to ignore.
Flagging a todo

2024-12-10 13:07 UTC, tommasini commented on patches/@metamask+assets-controllers+45.1.1.patch
> ++      const { networkConfigurationsByChainId } = this.messagingSystem.call('NetworkController:getState');
Can we have a comment explaining the change patched and if possible the PR or issue where the patch will be addressed?

2024-12-10 13:10 UTC, sahar-fehri commented on locales/languages/en.json
> +    "switch_network_to_view_transactions": "Please switch network to view transactions",
I think we can ship this separately to no block this one 🙏

2024-12-10 13:20 UTC, salimtb commented on patches/@metamask+assets-controllers+45.1.1.patch
> ++      const { networkConfigurationsByChainId } = this.messagingSystem.call('NetworkController:getState');
related to this: https://github.com/MetaMask/core/pull/4967

2024-12-10 13:21 UTC, sahar-fehri commented on app/components/Views/Wallet/index.tsx
> +            return AccountTrackerController.refresh(networkClientId);
We updated this code and removed the promise.all; thnx for flagging this 🙏

2024-12-10 13:23 UTC, sahar-fehri commented
Thanks @tommasini again 🙏  we will address your TS feedback on a followup PR 🙏

2024-12-10 14:12 UTC, matthewwalsh0 approved these changes

2024-12-10 15:33 UTC, tommasini approved these changes
LGTM! can we add the follow up steps at the PR description?

2024-12-10 16:03 UTC, Matt561 approved these changes
Approved on behalf of the staking team!

2024-12-10 16:14 UTC, darkwing approved these changes

2024-12-10 17:33 UTC, merged