test: e2e scenario where the user connects an in app browser dapp by granting permissions to one account and one chain
MetaMask/metamask-mobile pull request #12488
Opened 2024-11-28 21:53 UTC by EtherWizard33

## **Description**
Covers with e2e the scenario where the user connects an in app browser dapp by granting permissions to one account and one chain

## **Related issues**

Contributes to solve issue: https://github.com/MetaMask/MetaMask-planning/issues/2796

## **Manual testing steps**

I have added screenshot below to see how it looks.

1. `yarn watch:clean` `yarn test:e2e:ios:debug:build`
2. `yarn test:e2e:ios:debug:run e2e/specs/multichain/permission-system-initial-permissions-grant-one-account-and-one-chain.spec.js`

## **Screenshots/Recordings**

![2024-11-28 16 47 48](https://github.com/user-attachments/assets/f9dca549-42fe-4fc2-b2f1-6a8339dcba72)

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-12-02 18:59 UTC, cortisiko commented on e2e/specs/multichain/permission-system-connect-to-non-permitted-chain.spec.js
> +describe(Regression('Connect to a Test Network'), () => {
Tag smoke core to avoid this failing during the regression run. Remember regression has the feature flag disabled.

2024-12-02 21:17 UTC, EtherWizard33 commented on e2e/specs/multichain/permission-system-connect-to-non-permitted-chain.spec.js
> +describe(Regression('Connect to a Test Network'), () => {
thanks, yes, updated in my last commit, that also split the test in 3 smaller ones, hope all this is to you liking :)

2024-12-05 17:04 UTC, cortisiko requested changes
small comments. Other than that PR looks good

2024-12-05 17:04 UTC, cortisiko commented on e2e/selectors/Network/NetworkNonPemittedBottomSheet.selectors.js
> +  ETHEREUM_MAIN_NET_NETWORK_NAME: 'Ethereum Main Network',
You can grab the networknames from the networks.e2e file. No need to create specific string selectors for them.

2024-12-05 17:04 UTC, cortisiko commented on e2e/specs/multichain/permission-system-connect-to-non-permitted-chain.spec.js
> +            .withChainPermission(['0x1', '0xaa36a7'])
Can we use the chainID in the networks.e2e file instead of hard coding?

2024-12-05 21:21 UTC, EtherWizard33 commented on e2e/selectors/Network/NetworkNonPemittedBottomSheet.selectors.js
> +  ETHEREUM_MAIN_NET_NETWORK_NAME: 'Ethereum Main Network',
was able to find Sepolia but not Ethereum Main Network
would you be ok using Ethereum Main Network one as it is now?

2024-12-05 21:24 UTC, EtherWizard33 commented on e2e/specs/multichain/permission-system-connect-to-non-permitted-chain.spec.js
> +            .withChainPermission(['0x1', '0xaa36a7'])
was able to find the chain id for Sepolia in that file, but the mainnet one would be for main net with custom rpc, which is probably intended as a different main net, would you be ok using 0x1 for now?

2024-12-05 21:50 UTC, cortisiko commented on e2e/specs/multichain/permission-system-connect-to-non-permitted-chain.spec.js
> +            .withChainPermission(['0x1', '0xaa36a7'])
hmmm yeah leaving 0x1 makes sense to me

2024-12-05 21:50 UTC, cortisiko commented on e2e/selectors/Network/NetworkNonPemittedBottomSheet.selectors.js
> +  ETHEREUM_MAIN_NET_NETWORK_NAME: 'Ethereum Main Network',
Yeah sure thing!

2024-12-06 16:02 UTC, cortisiko approved these changes
✅ ✅ ✅ ✅

2024-12-06 16:18 UTC, merged