feat: Support gas fee flows in swaps
MetaMask/metamask-mobile pull request #12495
Opened 2024-11-29 12:39 UTC by OGPoyraz

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-12-03 12:16 UTC, matthewwalsh0 requested changes

2024-12-03 12:16 UTC, matthewwalsh0 commented on app/components/UI/Swaps/QuotesView.js
> +        if (isEIP1559Network) {
Minor, is it worth encapsulating all this logic in the existing `getTransactionPropertiesFromGasEstimates` but also passing the `quote` argument?

2024-12-03 12:16 UTC, matthewwalsh0 commented on app/components/UI/Swaps/QuotesView.js
> +        if (isEIP1559Network) {
If we expanded `getTransactionPropertiesFromGasEstimates`, could we just call again here but with the approval transaction or quote instead?

2024-12-03 12:16 UTC, matthewwalsh0 commented on app/components/UI/Swaps/utils/gas.ts
> +  const transactionGasFeeResponse = await TransactionController.estimateGasFee({
Should we use the transaction controller utils file here instead?

2024-12-03 12:16 UTC, matthewwalsh0 commented on app/selectors/networkController.ts
> +export const selectIsEIP1559Network = createSelector(
We could also determine this from the gas fee estimate type, but this is better as it reduces coupling on the gas fee controller ❤️

2024-12-03 12:16 UTC, matthewwalsh0 commented on app/selectors/networkController.test.ts
> +describe('NetworkController Selectors', () => {
Minor, but Redux discourage testing unit selectors in favour of mocking state in all component and hook tests so they get covered there.

2024-12-03 12:16 UTC, matthewwalsh0 commented on app/components/UI/Swaps/utils/gas.ts
> +  const baseAndPriorityFeePerGas = maxPriorityFeePerGas
Is this needed in mobile since we add this return straight to the transaction params? And `estimatedBaseFeeGwei` also?

2024-12-03 19:14 UTC, infiniteflower commented
Tested and seems to be working

2024-12-04 10:10 UTC, OGPoyraz commented on app/selectors/networkController.test.ts
> +describe('NetworkController Selectors', () => {
Not gonna lie, I was trying to trick quality gate 😅

2024-12-04 10:29 UTC, OGPoyraz commented on app/components/UI/Swaps/QuotesView.js
> +        if (isEIP1559Network) {
Done

2024-12-04 10:29 UTC, OGPoyraz commented on app/components/UI/Swaps/QuotesView.js
> +        if (isEIP1559Network) {
Done, passing transactions to that function now

2024-12-04 10:30 UTC, OGPoyraz commented on app/components/UI/Swaps/utils/gas.ts
> +  const transactionGasFeeResponse = await TransactionController.estimateGasFee({
I always forgot this, done now. Maybe we could have small linter while doing the refactors

2024-12-04 10:31 UTC, OGPoyraz commented on app/components/UI/Swaps/utils/gas.ts
> +  const baseAndPriorityFeePerGas = maxPriorityFeePerGas
Right, removed unnecessary things here

2024-12-04 10:32 UTC, OGPoyraz commented
> Tested and seems to be working

Thanks for looking at it @infiniteflower

2024-12-04 14:27 UTC, matthewwalsh0 approved these changes

2024-12-04 16:21 UTC, infiniteflower approved these changes

2024-12-04 16:35 UTC, merged