chore: bump `@metamask/preferences-controller` to `15.0.1`
MetaMask/metamask-mobile pull request #12579
Opened 2024-12-05 17:41 UTC by cryptodev-2s

## **Description**

This PR bumps `@metamask/preferences-controller` to `15.0.1`

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/12382

## **Manual testing steps**

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-12-05 17:50 UTC, tommasini approved these changes

2024-12-05 17:51 UTC, tommasini requested changes
Actually, should we merge keyring controller to v19 first?
https://github.com/MetaMask/metamask-mobile/blob/93c382350ed199650f02e03e31ca3d008ac1a168/package.json#L169

changelog: https://github.com/MetaMask/core/blob/%40metamask/preferences-controller%4015.0.1/packages/preferences-controller/CHANGELOG.md

2024-12-05 18:03 UTC, cryptodev-2s commented
> Actually, should we merge keyring controller to v19 first?
> 
> https://github.com/MetaMask/metamask-mobile/blob/93c382350ed199650f02e03e31ca3d008ac1a168/package.json#L169
> 
> changelog: https://github.com/MetaMask/core/blob/%40metamask/preferences-controller%4015.0.1/packages/preferences-controller/CHANGELOG.md
> 
> It seems almost ready: #12555

@tommasini We are using @metamask/keyring-controller within @metamask/preferences-controller at this location: [PreferencesController.ts#L9](https://github.com/MetaMask/core/blob/main/packages/preferences-controller/src/PreferencesController.ts#L9). In this context, we only listen to keyring state changes. Reviewing the CHANGELOG for @metamask/keyring-controller from version 18 to 19, there are no state changes or updates that would affect this version bump.

But I have no problem waiting for the other one to be merged first.

2024-12-06 15:26 UTC, cryptodev-2s commented on package.json
> +    "@metamask/assets-controllers": "45.0.0",
Updating to the exact version to avoid it resolving to 45.1.x, which appears to include some UI changes (Ref: [MetaMask/metamask-extension#28584](https://github.com/MetaMask/metamask-extension/pull/28584)).

2024-12-06 16:38 UTC, Gudahtt commented on package.json
> +    "@metamask/assets-controllers": "45.0.0",
Hmm, it looks like 45.1.0 adds a new method that was used for UI changes, but none would be expected just from updating

2024-12-06 16:40 UTC, Gudahtt commented on package.json
> +    "@metamask/assets-controllers": "45.0.0",
We can leave it for a later PR if you'd prefer though, that's no problem. The E2E tests have already run.

2024-12-06 16:43 UTC, Gudahtt submitted a review, later dismissed
LGTM!

2024-12-06 17:31 UTC, tommasini approved these changes, later dismissed

2024-12-06 22:49 UTC, Gudahtt commented on patches/@metamask+assets-controllers+45.1.1.patch
> --        const { ignoredTokens, detectedTokens, tokens } = this.state;
I am guessing the changes in this patch are included in the version we're updating to?

2024-12-06 22:50 UTC, cryptodev-2s commented on patches/@metamask+assets-controllers+45.1.1.patch
> --        const { ignoredTokens, detectedTokens, tokens } = this.state;
Yes exactly

2024-12-06 22:53 UTC, Gudahtt approved these changes
LGTM!

2024-12-06 22:57 UTC, salimtb approved these changes

2024-12-09 12:36 UTC, tommasini approved these changes

2024-12-09 12:52 UTC, merged