feat: MultichainBalanceController
MetaMask/metamask-mobile pull request #12599
Opened 2024-12-06 22:12 UTC by owencraston

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2025-01-17 20:31 UTC, owencraston commented on app/reducers/multichain/index.ts
> +  bitcoinSupportEnabled: true,
set back to false before merging

2025-01-21 00:53 UTC, Gedoxa approved these changes

2025-01-22 17:33 UTC, gambinish commented on app/components/hooks/usePortfolioBalance/usePortfolioBalance.ts
> +        PreferencesController.setPrivacyMode(value),
For `privacyMode` and `togglePrivacyMode` my preference would be to keep these as props getting passed into the React component, rather than abstracting them into a hook.

Toggling/reading `privacyMode` is unrelated to differentiating between evm and non-evm balances (which it seems like this hook is meant to do). Imo having this adds unnecessary scope and complexity to this hook. Having this broken out separately will make this more straightforward to control and troubleshoot.

2025-01-22 17:41 UTC, gambinish commented on app/hooks/usePortfolioBalance/index.ts
> +export const usePortfolioBalance = (): {
Is this a duplicate hook? It is very similar to `app/components/hooks/usePortfolioBalance`

What are the key differences between these? If we need both pieces of code, I wonder if we should change some of the naming conventions to make it easier to understand which hook needs to be used in which scenarios.

2025-01-22 17:43 UTC, gambinish requested changes
Thanks again for reminding me about this!

I mostly reviewed the logic in the `usePortfolioBalance` hooks, and left a few comments. Overall I think the approach makes sense. I do see a couple places where we might be able to simplify the business logic a bit, and also a question about some potential duplication of code.

2025-01-22 20:28 UTC, owencraston commented on app/hooks/usePortfolioBalance/index.ts
> +export const usePortfolioBalance = (): {
Oops, I initially created this hook in this folder but moved it into `app/components/hooks/usePortfolioBalance` but forgot to delete the old version.

2025-01-22 20:59 UTC, owencraston commented on app/components/hooks/usePortfolioBalance/usePortfolioBalance.ts
> +        PreferencesController.setPrivacyMode(value),
fair point, I removed both actions (privacy mode and the opening of the portfolio from the hook in favour of having it inline in the component.

2025-01-22 22:38 UTC, owencraston commented on app/components/hooks/usePortfolioBalance/usePortfolioBalance.ts
> +      isTestNetwork: isTestNet(chainId),
Initially I thought adding these would simplify the view but I realize this is adding too many concerns into this hook that should really remain balance focused. I have removed them now.

2025-01-22 22:41 UTC, owencraston commented on app/core/Engine/controllers/RatesController/utils.ts
> +      includeUsdRate: true,
I have now setup a subscription for whenever the selected fiat currency in is changed in the `CurrencyRateController`. You can find this logic in `app/core/Engine/controllers/RatesController/subscriptions.ts`. This will work for most "normal" currencies but there are a few supported currencies (like TokenList) that will not work with the new rates controller. Since this is a flask only feature for now I think this is alright.

2025-01-27 16:14 UTC, brianacnguyen requested changes
Can you attach a screenshot/screencap of the AggregatedPercentage story?

2025-01-27 23:10 UTC, gambinish commented on app/components/UI/NonEvmTokens/index.tsx
> +  };
Is this function doing anything? Seems like it should it be calling a controller of some sort.

2025-01-27 23:12 UTC, gambinish commented on app/components/UI/NonEvmTokens/index.tsx
> +  }, []);
Are these placeholders? Maybe we can pass these callbacks in as `null` instead and use the nullish value to conditionally render the buttons/links that call these callbacks in the component.

2025-01-27 23:14 UTC, gambinish commented on app/components/UI/Tokens/TokenList/PortfolioBalance/index.tsx
> +  const { data } = useMultichainBalances();
Nit: Might make sense/be more readable to reassign data to something more descriptive.

`const { data: multchainBalances } = useMultichainBalances();`

2025-01-27 23:26 UTC, gambinish commented on app/components/UI/Tokens/index.tsx
> +
Note to remove

2025-01-27 23:26 UTC, owencraston commented on app/components/Views/Wallet/index.tsx
> -          {accountBalanceByChainId && <PortfolioBalance />}
@gambinish are there any side effects or removing this check here? We are fetching the balances inside the useMultichainBalances hook so I see no reason we should conditionally render this component here.

2025-01-27 23:27 UTC, gambinish commented on app/components/Views/Wallet/index.tsx
> +          // @ts-expect-error tabLabel prop is used by ScrollableTabView parent
Is there any way that we can remove this expect-error?

2025-01-27 23:28 UTC, gambinish commented on app/components/hooks/useMultichainBalances/useMultichainBalances.ts
> +      isPortfolioEnabled: isPortfolioViewEnabled(),
Can't wait until we can simply remove this feature flag entirely 🥲

2025-01-27 23:28 UTC, gambinish commented on app/components/hooks/useMultichainBalances/useMultichainBalances.ts
> +      isPortfolioEnabled: isPortfolioViewEnabled(),
In the meantime, can we pass this along as `isPortfolioVieEnabled` rather than `isPortfolioEnabled` so that we can have an easier time when it does come down to removing this?

2025-01-27 23:30 UTC, gambinish commented on app/selectors/multichain/multichainNonEvm.ts
> +      // TODO: Adapt this for other non-EVM networks
Is this TODO still relevant?

2025-01-27 23:32 UTC, gambinish commented on app/selectors/multichain/multichainNonEvm.ts
> +      return 0;
Nit: Is `0` what we would expect the balance to be if account is not found? It could be, I'm just curious if `undefined` or something along those lines could also work.

2025-01-28 05:10 UTC, owencraston commented on app/components/UI/NonEvmTokens/index.tsx
> +  };
Good point. I modified it to call `MultichainBalancesController.updateBalances()`

2025-01-28 05:10 UTC, owencraston commented on app/components/UI/NonEvmTokens/index.tsx
> +  }, []);
I need to play with the types so that they accept null as an option.

2025-01-28 05:12 UTC, owencraston commented on app/components/UI/Tokens/TokenList/PortfolioBalance/index.tsx
> +  const { data } = useMultichainBalances();
I like this. I have made this change in my latest commit.

2025-01-28 05:13 UTC, owencraston commented on app/components/UI/Tokens/index.tsx
> +
Removed!

2025-01-29 04:54 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +      return 0;
I would prefer to return 0 so that we can handle this case gracefully instead of crashing the app or not rendering anything.

2025-01-29 04:56 UTC, owencraston commented on app/components/Views/Wallet/index.tsx
> +          // @ts-expect-error tabLabel prop is used by ScrollableTabView parent
yeah good call.

2025-01-29 04:57 UTC, owencraston commented on app/components/hooks/useMultichainBalances/useMultichainBalances.ts
> +      isPortfolioEnabled: isPortfolioViewEnabled(),
I prefer this name. I will make this change.

2025-01-29 04:58 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +      // TODO: Adapt this for other non-EVM networks
I believe it is since we are still hardcoding some EVM logic in there.

2025-01-29 15:24 UTC, ccharly commented on app/core/Engine/Engine.ts
> +          'SnapController:handleRequest',
What about creating a `app/core/Engine/controllers/SnapController/constants.ts` for this one?

We will need other actions later on when updating the `SnapKeyring` to the latest version (which relies on "actions" rather than a instance to the `SnapController`)

2025-01-29 15:24 UTC, ccharly commented on app/components/UI/Tokens/TokenList/PortfolioBalance/index.tsx
> +  const ismultchainBalancesCollectionForMarketingEnabled = useSelector(
Same typo here: 

```suggestion
  const isMultichainBalancesCollectionForMarketingEnabled = useSelector(
```

2025-01-29 19:12 UTC, owencraston commented on app/components/hooks/useMultichainBalances/useMultichainBalances.ts
> +    multchainBalances: {
oops 😢

2025-01-29 19:19 UTC, owencraston commented on app/components/hooks/useMultichainBalances/useMultichainBalances.ts
> +    multchainBalances: {
serves me right for making changes at midnight.

2025-01-29 19:24 UTC, owencraston commented on app/components/hooks/useMultichainBalances/useMultichainBalances.test.ts
> +    });
I like it.

2025-01-29 19:24 UTC, owencraston commented on app/components/hooks/useMultichainBalances/useMultichainBalances.test.ts
> +    });
Great Nit

2025-01-29 19:33 UTC, owencraston commented on app/core/Engine/controllers/RatesController/subscriptions.ts
> +    `${CurrencyRateController.name}:stateChange`,
Great idea.

2025-01-29 20:50 UTC, owencraston commented on app/core/Engine/Engine.ts
> +          'SnapController:handleRequest',
Okay. I went ahead and made that change (as well as extracted the remaining SnapController, RatesController and MultichainBalances type into constants files). I did not fully migrate these controller to the factory pattern in order to try and keep the changes minimal.

2025-01-30 16:57 UTC, tommasini commented on app/components/UI/NonEvmTokens/index.test.tsx
> +const renderComponent = (state: any = {}) =>
Can we use `RootState` instead?

2025-01-30 23:07 UTC, brianacnguyen approved these changes, later dismissed

2025-02-03 14:35 UTC, wachunei commented on app/components/UI/NonEvmTokens/index.tsx
> +      decimals: network.chainId === MultichainNetworks.Solana ? 9 : 6, // SOL uses 9 decimals, BTC uses 6
is this decimals value the actual minimal unit or a format representation for the UI? Because BTC hast 8 decimals (satoshi is 10e-8 btc)

either way, these probably should be constants,

2025-02-03 14:40 UTC, wachunei commented on app/components/Views/AddAccountActions/AddAccountActions.tsx
> +                await createBitcoinAccount(MultichainNetworks.Bitcoin);
Is there a reason why `createSolanaAccount` and `createBitcoinAccount` need te receive the chain ID as param? is it just kept as is because of legacy code?

`await createSolanaAccount(MultichainNetworks.Bitcoin);` would not make sense

2025-02-03 14:40 UTC, wachunei commented on app/components/Views/AddAccountActions/AddAccountActions.tsx
> +                await createBitcoinAccount(MultichainNetworks.Bitcoin);
aah I saw `createBitcoinAccount` can receive the testnet chain id as scope. nevermind, resolve these comments :)

2025-02-03 18:17 UTC, tommasini commented on app/selectors/multichain/multichainEvm.ts
>  import {
Let's sync on this, it seems like this file is only balances related, would make sense to rename it to `multichainEvmBalances?` Let me know your thoughts

2025-02-03 18:19 UTC, tommasini commented on app/selectors/multichain/multichainNonEvm.ts
> +///: BEGIN:ONLY_INCLUDE_IF(keyring-snaps)
It seems that this selectors are not nonEvm specific! Since we are both working on this, let's sync to understand if they are all being used, and compare some similar behaviours that we have, to only have one source of truth like the `solanaEnabled`!

2025-02-03 18:23 UTC, tommasini commented on app/core/Multichain/utils.ts
> +export function isSolanaAddress(address: string): boolean {
Out of curiosity, you created an util function to use across the codebase around one util function because it's from a third party repo?
I liked it a lot, if we want to shift from the library it would be much easier! Cool!

2025-02-03 18:25 UTC, tommasini commented on app/selectors/multichain/multichainNonEvm.ts
> +  return state.multichainSettings.solanaSupportEnabled;
Not sure if we want to store this data in the user device, any strong thoughts on it? I think it would be okay to use a environment variable instead, wdyt?

2025-02-03 19:41 UTC, owencraston commented on app/components/Views/AddAccountActions/AddAccountActions.tsx
> +                await createBitcoinAccount(MultichainNetworks.Bitcoin);
Yeah the reason is so we can support testnet accounts. Solana does not have test net accounts yet but we can easily enable it in the future.

2025-02-03 20:24 UTC, owencraston commented on app/components/UI/NonEvmTokens/index.tsx
> +      decimals: network.chainId === MultichainNetworks.Solana ? 9 : 6, // SOL uses 9 decimals, BTC uses 6
good idea, I have added it as part of the network config response.

2025-02-03 20:34 UTC, owencraston commented on app/core/Multichain/constants.ts
> +  [MultichainNetworks.Bitcoin]: BTC,
Are you sure? I do not see the same data available in the keyring API? Even if it did, this type is easier to work with since it is the natural response from the assets controller.

2025-02-03 20:37 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +  return state.multichainSettings.solanaSupportEnabled;
It wont be persisted since I put this selector state in the [persistConfig blacklist](https://github.com/MetaMask/metamask-mobile/blob/dd957381894c94faf073b3a3d5a105a212052a1e/app/store/persistConfig.ts#L111).

2025-02-03 21:05 UTC, owencraston commented on app/selectors/multichain/multichainEvm.ts
>  import {
fair point, There will likely be more "types" of selectors added to this file in the future so I kept it generic.

2025-02-03 21:07 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +///: BEGIN:ONLY_INCLUDE_IF(keyring-snaps)
yeah I explicitly broke them up for now to try and not step on other peoples toes but you are right, eventually we will want t migrate all selectors to the multichain version.

2025-02-04 00:20 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +      return 0;
On the other hand I think returning 0 could lead users to panic so it would be better to return undefined and show a loading indicator.

2025-02-04 00:21 UTC, owencraston commented on app/selectors/multichain/multichainEvm.ts
>  import {
this file was also originally not mine. I simply migrated the multichain.ts file to the new name multihainEvm.ts.

2025-02-04 00:59 UTC, owencraston commented on app/components/UI/NonEvmTokens/index.tsx
> +  }, []);
for now I think passing in an empty function works and keeps the changes minimal? what do you think?

2025-02-04 00:59 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +      return 0;
I made the change to return undefined here.

2025-02-05 14:27 UTC, Prithpal-Sooriya commented
@owencraston is there any additional environment variables I need?

I am unable to fetch Solana and Bitcoin assets, and the app crashes if I try clicking into these assets. See loom recording
https://www.loom.com/share/4093ad17a61c45d79b9b33ab243b3324?sid=3b113a73-1096-481a-aa7a-2a9dbc336f19

2025-02-05 17:30 UTC, owencraston commented
@Prithpal-Sooriya as long as you set the `METAMASK_BUILD_TYPE` to flask inside the .js.env you should be good to create and pull the balances. Make sure the server is running. as far as the other errors go, I will look into those.

2025-02-05 18:19 UTC, gambinish commented
Noticing the following issue on the Account Picker component:

<img width="402" alt="Screenshot 2025-02-05 at 10 18 07 AM" src="https://github.com/user-attachments/assets/2872ecf7-0bac-48d7-bae8-e0b26751a4c7" />

The amount showed suggests that my Bitcoin Account should have a balance of ETH, should this be BTC? It's also not reflecting my BTC balance in my Testnet account I created:

<img width="398" alt="Screenshot 2025-02-05 at 10 19 11 AM" src="https://github.com/user-attachments/assets/f540ff0f-166b-42bf-bdf4-bcab0eb25c97" />

2025-02-05 18:23 UTC, gambinish commented
Also, we may want to considering piping in the balance from the token list item into the token detail page:

<img width="403" alt="Screenshot 2025-02-05 at 10 22 28 AM" src="https://github.com/user-attachments/assets/1546c1e2-82d9-47d0-a845-42766501af0f" />

However, I'm not sure if this token details view is in scope, since it seems that we are still missing market data related to BTC token. Maybe we should consider deactivating the navigation on non-EVM assets. Has product weighed in at all here?

2025-02-05 18:27 UTC, gambinish requested changes
Code is looking good. I was able to pull down this branch and get it setup with iOS. I verified the testing steps you outlined, and was able to add a Testnet bitcoin account, and funded it from a faucet.

The balance updated on the token list page ✅ 
However I noticed a few places in the UI where I saw some unexpected values ♻️ 

Not sure what the scope of this feature is, we may want to pull in product to weigh in here.

2025-02-05 19:48 UTC, gantunesr reviewed
I still need to review 10 files

2025-02-05 19:51 UTC, gantunesr commented
> Also, we may want to considering piping in the balance from the token list item into the token detail `page:`
> However, I'm not sure if this token details view is in scope, since it seems that we are still missing market data related to BTC token. Maybe we should consider deactivating the navigation on non-EVM assets. Has product weighed in at all here? 
> Sidenote that on the token details page, I'm still seeing the ETH mainnet network logo

This should be out of scope, in extension the navigation to the details view is deactivate

2025-02-06 05:37 UTC, owencraston commented
@Prithpal-Sooriya I am not experiencing the same issues as you (see video below). Try and pull the latest and see if you can get it to work?

https://github.com/user-attachments/assets/83571c29-d066-461e-8428-0ceed42f20e0

2025-02-06 06:29 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +  (multichainCurrerntNetwork) => multichainCurrerntNetwork.network,
good catch.

2025-02-06 06:36 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
yeah I know. I am no sure how to reconcile this because the previous multichain.ts file was quite large and I did not want to edit it in order to better isolate these changes. This file could be thought of working across Evm AND Non evm where as the multichainEvm file only handles evm. I think eventually we would want to migrate all of our key selectors to the non evm. What would you suggest as the best path forward at this moment?

2025-02-06 06:37 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +      return isTestNet ? shouldShowFiatOnTestnets : true; // Is it safe to assume that we default show fiat for mainnet?
Yeah I cannot think of a good reason either but I noticed that we had an existing setting to display fiat balance in test nets so in the spirit of backwards compatibility I added it. do you think I should remove it?

2025-02-06 06:38 UTC, owencraston commented on app/core/Multichain/constants.ts
> +    },
This is how it was done on the [extesnion](https://github.com/MetaMask/metamask-extension/blob/be2b439924773a9dc5995c21ac33b446572a86e4/shared/constants/multichain/networks.ts#L79).

2025-02-06 06:40 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +      console.warn('Could not find selected internal account');
We added them in the [extension selectors](https://github.com/MetaMask/metamask-extension/blob/01c9fbd76ca73d1012f30376cc6cfff8b4769b03/ui/selectors/multichain.ts#L391) so I added them here. I can remove them if you think that is better?

2025-02-06 06:43 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +      ? providerConfig?.ticker ?? 'ETH'
I was following this [extension selector](https://github.com/MetaMask/metamask-extension/blob/01c9fbd76ca73d1012f30376cc6cfff8b4769b03/ui/selectors/multichain.ts#L313). I can try and find a better way.

2025-02-06 06:46 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +  (isEvm, token) => !isEvm && token.symbol === 'BTC',
I will use the ticker defined in our network config. 

```ts
export const selectMultichainIsBitcoin = createDeepEqualSelector(
  selectMultichainIsEvm,
  selectMultichainDefaultToken,
  (isEvm, token) =>
    !isEvm &&
    token.symbol ===
      MULTICHAIN_PROVIDER_CONFIGS[MultichainNetworks.Bitcoin].ticker,
);
```

2025-02-06 06:51 UTC, owencraston commented on app/components/Views/Wallet/index.tsx
> +    return evmTokenContent;
which part? In the production case, this function will only ever return `evmTokenContent`

2025-02-06 11:55 UTC, gantunesr commented on app/core/Multichain/constants.ts
> +    },
damn, ok

2025-02-06 11:58 UTC, gantunesr commented on app/selectors/multichain/multichainNonEvm.ts
> +      console.warn('Could not find selected internal account');
My personal preference is to remove logs since they make overall devex a bit more noisy for the rest. Again, this is a personal preference, not sure what is the norm here

2025-02-06 13:45 UTC, gantunesr commented on app/selectors/multichain/multichainNonEvm.ts
Maybe calling this one `multichain` and the other just `evm`? Not sure if this would be better, looking at the file path it would make more sense for evm at least (`multichain/evm.ts`) while the other would be redundant (`multichain/multichain.ts`).

2025-02-06 13:52 UTC, gantunesr commented on app/components/Views/Wallet/index.tsx
> +    return evmTokenContent;
Is just the fact that you'll have an unreachable `return` in a version of the code, what do you think about making it more explicit just for the sake of removing the comment? Something like,

```ts
// ...

///: BEGIN:ONLY_INCLUDE_IF(keyring-snaps)
if (!isEvm) {
  return <>...</>
}
///: END:ONLY_INCLUDE_IF

return evmTokenContent;

```

2025-02-06 15:49 UTC, brianacnguyen submitted a review, later dismissed

2025-02-06 20:20 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +    }
fair point. I'll make that change.

2025-02-06 20:23 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
I like this better. I have made this change in my latest commit.

2025-02-06 20:39 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +      console.warn('Could not find selected internal account');
I removed all of the console.warn logs from this file.

2025-02-06 20:42 UTC, owencraston commented on app/components/Views/Wallet/index.tsx
> +    return evmTokenContent;
yeah this is much better actually. I have made the change in my latest commit and removed the constant.

2025-02-06 20:52 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +      ? providerConfig?.ticker ?? 'ETH'
I realized that this ternary isnt even needed since the default response from the `selectProviderConfig` will always return ETH as the ticker.

2025-02-06 20:54 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +      ? providerConfig?.ticker ?? 'ETH'
the new code is much simpler and more robust since it relies on existing network selctors.

```ts
export const selectMultichainDefaultToken = createDeepEqualSelector(
  selectMultichainIsEvm,
  selectEvmProviderConfig,
  selectMultichainProviderConfig,
  (isEvm, evmProviderConfig, multichainProviderConfig) => {
    const symbol = isEvm
      ? evmProviderConfig.ticker
      : multichainProviderConfig.ticker;
    return { symbol };
  },
);
```

2025-02-06 20:57 UTC, owencraston commented
> Noticing the following issue on the Account Picker component:
> 
> <img alt="Screenshot 2025-02-05 at 10 18 07 AM" width="402" src="https://private-user-images.githubusercontent.com/35090461/410123172-2872ecf7-0bac-48d7-bae8-e0b26751a4c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg4NjgyNjEsIm5iZiI6MTczODg2Nzk2MSwicGF0aCI6Ii8zNTA5MDQ2MS80MTAxMjMxNzItMjg3MmVjZjctMGJhYy00OGQ3LWJhZTgtZTBiMjY3NTFhNGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA2VDE4NTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YmRmYjc1YTM4ODJjYThkNjBhZjllODEwNWFkMzNlZWE4MWJmMWI4MmNlNjJhMmFiMWJmZWY3Mzc1ZGYwZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F55TSuLCr9cnxO0X1MJpa7veSvJ066OYXvlxbpOm6es">
> The amount showed suggests that my Bitcoin Account should have a balance of ETH, should this be BTC? It's also not reflecting my BTC balance that I see on the token list for my Testnet account I created:
> 
> <img alt="Screenshot 2025-02-05 at 10 19 11 AM" width="398" src="https://private-user-images.githubusercontent.com/35090461/410123552-f540ff0f-166b-42bf-bdf4-bcab0eb25c97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg4NjgyNjEsIm5iZiI6MTczODg2Nzk2MSwicGF0aCI6Ii8zNTA5MDQ2MS80MTAxMjM1NTItZjU0MGZmMGYtMTY2Yi00MmJmLWJkZjQtYmNhYjBlYjI1Yzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA2VDE4NTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYmI0NTRiNGVjNDYxOGMyOTkxYzBjOGFiNjBjODJhMjExNmVjYWZmZWRkMWI5Y2U1YWMxMGQ0NTE2NDJhZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xxHQqZP3jwe2X6JQ8D0AwJliveOc9E8CoQq9bkuoUus">


@gambinish  This change is out of scope for this PR. [The next issue](https://github.com/MetaMask/accounts-planning/issues/697) that I tackle will solve this problem as it will piggy back on the changes made in this PR. I am not doing this now since the changes for this PR are already massive and this is a flask only feature so none of this flawed Ux will make it into production.

2025-02-06 21:01 UTC, owencraston commented
> Also, we may want to considering piping in the balance from the token list item into the token detail page:
> 
> <img alt="Screenshot 2025-02-05 at 10 22 28 AM" width="403" src="https://private-user-images.githubusercontent.com/35090461/410124662-1546c1e2-82d9-47d0-a845-42766501af0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg4NjgyNjEsIm5iZiI6MTczODg2Nzk2MSwicGF0aCI6Ii8zNTA5MDQ2MS80MTAxMjQ2NjItMTU0NmMxZTItODJkOS00N2QwLWE4NDUtNDI3NjY1MDFhZjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA2VDE4NTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNWFiZTBkMjI1ODM4M2JmM2JlNDg3ZDMwNjcxN2Y3ODVlYjU3OTI3ZjkyYmQ4MGZlZjQ0YmJmZWExZjZkNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UY0ZSjIprRRhIGW8jLJg-D7YdNBRyb03yjdpJAT-6WE">
> However, I'm not sure if this token details view is in scope, since it seems that we are still missing market data related to BTC token. Maybe we should consider deactivating the navigation on non-EVM assets. Has product weighed in at all here?
> 
> Sidenote that on the token details page, I'm still seeing the ETH mainnet network logo

@gambinish I would prefer to handle this in a separate PR in order to keep the changes minimal (or at least not let them grow beyond where they have now).  This is a flask only feature so it will never make it into production, therefore I feel comfortable shipping this as it. The token details page handles this lack of data fairly gracefully already so the UX is not that bad IMO but I will defer to @gantunesr.

2025-02-06 21:18 UTC, gambinish approved these changes

2025-02-06 21:18 UTC, gantunesr commented on app/selectors/multichain/multichainNonEvm.ts
> +      return isTestNet ? shouldShowFiatOnTestnets : true; // Is it safe to assume that we default show fiat for mainnet?
hmm sounds like a product decision

2025-02-06 21:48 UTC, owencraston commented on app/selectors/multichain/multichainNonEvm.ts
> +      return isTestNet ? shouldShowFiatOnTestnets : true; // Is it safe to assume that we default show fiat for mainnet?
discussed with @Montoya on slack and we decided to keep it as is since the pattern already exists. We also agreed this is a very weird feature that should not be used.

2025-02-06 22:12 UTC, brianacnguyen approved these changes

2025-02-07 02:50 UTC, gantunesr approved these changes

2025-02-07 11:13 UTC, FrederikBolding approved these changes

2025-02-07 15:52 UTC, tommasini approved these changes

2025-02-07 16:08 UTC, merged