chore: Additional e2e test to support `PortfolioView`
MetaMask/metamask-mobile pull request #12602
Opened 2024-12-07 00:11 UTC by gambinish

## **Description**

Additional e2e tests to support `PortfolioView`. This is an initial pass to cover the basic happy path use cases. Should be expanded further to handle edge cases.

## **Related issues**

Fixes:

## **Manual testing steps**

1. `yarn setup`
2. `yarn test:e2e:ios:debug:build`
3. `yarn watch:clean`
4. `yarn test:e2e:ios:debug:run /e2e/specs/multichain/asset-list.spec.js`

## **Screenshots/Recordings**

Current state of things:
```
PASS  e2e/specs/multichain/asset-list.spec.js (58.1 s)
  SmokeMultiChain Import Tokens
    ✓ should display tokens across networks when all networks filter is toggled on (9755 ms)
    ✓ should display tokens across networks when current networks filter is toggled on (23606 ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        58.153 s
```

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-12-11 13:44 UTC, sahar-fehri approved these changes, later dismissed

2024-12-11 16:26 UTC, cortisiko requested changes

2024-12-12 22:03 UTC, cortisiko approved these changes
🐳 ✅ 🐳 ✅

2024-12-12 22:05 UTC, salimtb approved these changes

2024-12-12 22:21 UTC, merged