feat: Create Permit Simulation
MetaMask/metamask-mobile pull request #12606
Opened 2024-12-09 08:20 UTC by digiwand

## **Description**

Creates Permit Simulation UI to be shown on V3 and V4 signTypedData confirmations. Signature Decoding logic to be added following this PR.

### Add
- create ButtonPill component
- create PermitSimulation component
  - add to TypedSignV3V4 component
- create constants/signatures.ts file
- create hooks/useGetTokenStandardAndDetails files
- create hooks/useTrackERC20WithoutDecimalInformation.ts
 file
- create utils/signature.ts file
- create utils/token.ts file

### Update
- add style param to UI/Name component 
- add noBorder param to Box component
- add TokenStandard enum
- add handleCloseOnBackdropClick param to confirmation BottomModal component
- add skipCharacterInEnd param to shortenString common util. This mimics the same logic in extension

### Designs
Simulations MVP https://www.figma.com/design/8DrinrQI4hs76Grm2F34xK/Simulations-MVP?node-id=1283-18713&node-type=canvas&t=FbRsIUjxMDxC3Get-0

Confirmations Redesign V5 https://www.figma.com/design/wcXUl6AH5KNFwKdAIv49kh/Confirmation-redesign-V5?node-id=4157-7776&node-type=canvas&m=dev

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/12432
Related: https://github.com/MetaMask/metamask-mobile/pull/12994 (Signature Decoding Simulation - follow-up PR)

###: Follow-up
- Related: https://github.com/MetaMask/metamask-mobile/issues/12910 (Create storybook page + unit tests for ButtonPill)
- Related: https://github.com/MetaMask/metamask-mobile/issues/13013  (Do not use Ramp/Box. Use View instead)
- Related: https://github.com/MetaMask/metamask-mobile/issues/13016 (Move shortenString helper location)

## **Manual testing steps**

1. Test Permit test-dapp button

## **Screenshots/Recordings**

### **Before**

### **After**

<img width="320" src="https://github.com/user-attachments/assets/a7a478b0-6b05-47a6-b68c-c691af82c5ee"> 

![CleanShot 2025-01-15 at 12 41 45](https://github.com/user-attachments/assets/76549a51-7254-41b1-8ab9-44cceedaefd7)

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2025-01-07 16:29 UTC, brianacnguyen requested changes, later dismissed
Since the ButtonPill is not an official DS component, can you move it to components-temp?
Also can you attach the design for this to the PR

2025-01-07 16:30 UTC, brianacnguyen commented on app/component-library/components/Buttons/ButtonPill/ButtonPill.styles.ts
> +  pressed: boolean;
this should be isPressed

2025-01-07 16:37 UTC, digiwand commented on app/component-library/components/Buttons/ButtonPill/ButtonPill.styles.ts
> +  pressed: boolean;
good callout! I copied this from the existing ButtonIcon component and forgot to update here. Thanks! updated d53035f74b4d8445283c4a99d7d913d51545d7f5

ButtonIcon remains the same since it's out of scope

2025-01-07 16:37 UTC, digiwand commented on app/component-library/components/Buttons/ButtonPill/ButtonPill.styles.ts
> +  pressed: boolean;
good callout! I copied this from the existing ButtonIcon component and forgot to update here. Thanks @brianacnguyen! updated d53035f74b4d8445283c4a99d7d913d51545d7f5

ButtonIcon remains the same since it's out of scope

2025-01-07 16:42 UTC, digiwand commented
got it, thanks @brianacnguyen! moved [2bdb950](https://github.com/MetaMask/metamask-mobile/pull/12606/commits/2bdb950c0059659539423f52a52a768b0f94db35)

copied designs from the related issue to this ticket

2025-01-08 06:31 UTC, jpuri commented on app/component-library/components-temp/Buttons/ButtonPill/ButtonPill.styles.ts
> +export default styleSheet;
It will be nicer to create separate PR for this component and also possibly addd storybook.

2025-01-08 07:22 UTC, jpuri commented on app/util/notifications/methods/common.ts
> +    skipCharacterInEnd: false,
NIT: unit test coverage for new added condition.

2025-01-08 07:24 UTC, jpuri commented on app/components/Views/confirmations/utils/signature.ts
> +import { ApprovalRequest } from '@metamask/approval-controller';
Unit test coverage for new util methods will be very useful.

2025-01-08 07:27 UTC, jpuri commented on app/components/Views/confirmations/components/UI/BottomModal/BottomModal.tsx
> + * TODO replace BottomModal instances with BottomSheet
Will be nice to also create a task for this TODO so we do not miss this change.

2025-01-08 22:57 UTC, digiwand commented on app/component-library/components-temp/Buttons/ButtonPill/ButtonPill.styles.ts
> +export default styleSheet;
thanks for the review @jpuri!

yeah, I agree. In retrospect, having a tree trunk branch for this feature would have been nice since it requires much more than I anticipated initially. This PR is my first mobile feat PR, so I didn't expect to need all of these dependencies 

good idea to add a storybook page. I created a separate issue ticket for this + related unit tests
https://github.com/MetaMask/metamask-mobile/issues/12910

2025-01-08 22:58 UTC, digiwand commented on app/component-library/components-temp/Buttons/ButtonPill/__snapshots__/ButtonPill.test.tsx.snap
> +`;
I was mimicing the exiting DS ButtonIcon component. It isn't too bad at this lower level component, as opposed to a parent component to have the snapshot.

I created a separate issue to handle this suggestion https://github.com/MetaMask/metamask-mobile/issues/12910

2025-01-09 05:59 UTC, digiwand commented on app/components/Views/confirmations/utils/signature.ts
> +import { ApprovalRequest } from '@metamask/approval-controller';
agreed. added [1ffe22e](https://github.com/MetaMask/metamask-mobile/pull/12606/commits/1ffe22ea0fd14f4bfe9ed1de2b44875f4de308d2). I mirrored what was in extension. We will want to add tests for the relevant extension test. I'll create a PR in parallel for this

2025-01-09 06:07 UTC, digiwand commented on app/components/Views/confirmations/utils/signature.ts
> +import { ApprovalRequest } from '@metamask/approval-controller';
updated [1ffe22e](https://github.com/MetaMask/metamask-mobile/pull/12606/commits/1ffe22ea0fd14f4bfe9ed1de2b44875f4de308d2)

2025-01-09 06:08 UTC, digiwand commented on app/components/Views/confirmations/utils/signature.ts
> +import { ApprovalRequest } from '@metamask/approval-controller';
also updating relevant methods in extension in a parallel PR

2025-01-09 06:49 UTC, digiwand commented on app/util/notifications/methods/common.ts
> +    skipCharacterInEnd: false,
updated https://github.com/MetaMask/metamask-mobile/pull/12606/commits/5852d8717b5da4a451560b8f04a75dd4ccf82203

2025-01-09 06:49 UTC, digiwand commented on app/util/notifications/methods/common.ts
> +    skipCharacterInEnd: false,
added tests for shortenString with new param https://github.com/MetaMask/metamask-mobile/pull/12606/commits/5852d8717b5da4a451560b8f04a75dd4ccf82203

2025-01-13 07:29 UTC, digiwand commented
hello @jpuri and @brianacnguyen, thanks for the reviews! may I get a rereview here please? added additional tests and update some paths related to the simulation files

2025-01-13 13:18 UTC, matthewwalsh0 requested changes

2025-01-13 13:18 UTC, matthewwalsh0 commented on app/components/Views/confirmations/components/UI/BottomModal/BottomModal.tsx
> +  canCloseOnBackdropClick?: boolean;
Minor, should this be `closeOnBackdropPress` to be explicit?

2025-01-13 13:18 UTC, matthewwalsh0 commented on app/components/Views/confirmations/hooks/useGetTokenStandardAndDetails.ts
> +      return (await memoizedGetTokenStandardAndDetails(
How are we determining the chain for the address? Or is it relying on the global provider?

2025-01-14 05:25 UTC, digiwand commented on app/components/Views/confirmations/components/Confirm/Simulation/TypedSignPermit/TypedSignPermit.tsx
> +  const chainId = useSelector(selectChainId);
unsure why at this moment, but on my build useSignatureRequest is not working. I've ran yarn setup before running the updated build 

```
export function useSignatureRequest() {
  const { approvalRequest } = useApprovalRequest();

  const signatureRequest = useSelector((state: RootState) =>
    selectSignatureRequestById(state, approvalRequest?.id as string),
  );

  console.log('signatureRequest', signatureRequest);
  console.log('approvalRequest?.type', approvalRequest?.type);
  console.log('SIGNATURE_APPROVAL_TYPES.includes(approvalRequest?.type as ApprovalType)', SIGNATURE_APPROVAL_TYPES.includes(approvalRequest?.type as ApprovalType));

  if (
    !SIGNATURE_APPROVAL_TYPES.includes(approvalRequest?.type as ApprovalType) ||
    !signatureRequest
  ) {
    return undefined;
  }

    return signatureRequest;
}

```

![CleanShot 2025-01-13 at 21 24 42@2x](https://github.com/user-attachments/assets/66f09dce-a71b-4ccb-82eb-9e702c6ee02f)

2025-01-14 05:28 UTC, digiwand commented on app/component-library/components-temp/Buttons/ButtonPill/ButtonPill.tsx
@jpuri  inquired about this as well. It would be preferred, though I needed to merge that in first. In retrospect, I think having a trunk branch for all of this work would have been helpful, but I didn't realize how many dependencies we'd need for this feature.

2025-01-14 06:22 UTC, digiwand commented on app/components/Views/confirmations/components/Confirm/Simulation/components/ValueDisplay/ValueDisplay.tsx
> +    function onPressTokenValue() {
thanks! updated [f99a239](https://github.com/MetaMask/metamask-mobile/pull/12606/commits/f99a239880d2e91c01c45157eaf50c8fa1008701)

2025-01-14 06:22 UTC, digiwand commented on app/components/Views/confirmations/components/Confirm/Simulation/TypedSignPermit/TypedSignPermit.tsx
> +  const chainId = useSelector(selectChainId);
awesomee, ty! updated [2e75fb1](https://github.com/MetaMask/metamask-mobile/pull/12606/commits/2e75fb1551869bbeecf6fa1d310e1766b906d4e8)

2025-01-14 06:32 UTC, digiwand commented on app/components/Views/confirmations/components/UI/BottomModal/BottomModal.tsx
> +  canCloseOnBackdropClick?: boolean;
I went with prefixing `can` to follow naming conventions

 [TypeScript ESLint](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/naming-convention.md#enforce-that-boolean-variables-are-prefixed-with-an-allowed-verb)
 "prefix": ["is", "should", "has", "can", "did", "will"]

https://github.com/MetaMask/contributor-docs/blob/main/docs/javascript.md#use-a-verb-phrase-for-boolean-variable-names-that-do-not-involve-secondary-objects

2025-01-14 06:33 UTC, digiwand commented on app/components/Views/confirmations/components/Confirm/Simulation/components/ValueDisplay/ValueDisplay.styles.ts
> +      marginStart: 4,
Agreed, nice suggestion 

updated [72ba710](https://github.com/MetaMask/metamask-mobile/pull/12606/commits/72ba710462ac210ffdcaf62db4e4860a408b3a3e)

2025-01-14 07:04 UTC, digiwand commented on app/components/Views/confirmations/hooks/useGetTokenStandardAndDetails.ts
> +      return (await memoizedGetTokenStandardAndDetails(
good question. Updated to use the network client id found by the signature chain id 

[ddfbfb0](https://github.com/MetaMask/metamask-mobile/pull/12606/commits/ddfbfb0867e455b6bf51ca3d4f4ae98b52380e07)
https://github.com/MetaMask/metamask-mobile/pull/12606/commits/e89622c0ff65b1a068681d086de32c66a44c1e1c

2025-01-14 07:10 UTC, digiwand commented on app/components/Views/confirmations/components/Confirm/Simulation/components/ValueDisplay/ValueDisplay.tsx
> +      <Box style={styles.wrapper}>
actually, this was something I was thinking about as well. It seems that we have two different existences of similar UI. We a maintaining separate UI styles for transaction and signature simulation. 

created a PR to investigate abstracting presentation components in the future
https://github.com/MetaMask/metamask-mobile/issues/12974

2025-01-15 12:12 UTC, matthewwalsh0 approved these changes

2025-01-15 19:26 UTC, jpuri commented on app/components/Views/confirmations/Confirm/Confirm.tsx
> +    <BottomModal canCloseOnBackdropClick={false}>
Component does not support this prop `canCloseOnBackdropClick`

2025-01-15 19:26 UTC, jpuri approved these changes

2025-01-15 19:29 UTC, jpuri approved these changes

2025-01-15 19:49 UTC, wachunei commented
Why did we have to add a `noBorder` prop to `Box` component, which is a Ramp component, and the changes of this feature are not related to Ramp code? is the `Box` component being used outside of Ramp code domain?

2025-01-15 19:54 UTC, digiwand commented
@wachunei good question. This is my first mobile feat PR. Used Box as it had familiar naming to the DS Box in extension. 

I can update these instances to use the View component instead. Mind if I do it in a follow-up PR to not block this PR? 
Created an issue to address this: https://github.com/MetaMask/metamask-mobile/issues/13013

2025-01-15 20:07 UTC, wachunei commented
Since it is a visual change and changes on the Ramp code (beside `Box` itself) are only snapshot changes I'm OK with a follow up PR for the same release. I will update that issue with the places the Box component must be replaced.

2025-01-15 20:08 UTC, wachunei approved these changes

2025-01-15 20:08 UTC, digiwand commented
thanks @wachunei! I actually just updated them in this follow-up PR 
https://github.com/MetaMask/metamask-mobile/pull/12994

2025-01-15 20:13 UTC, brianacnguyen requested changes
Please include a story for ButtonPill and record a video of the story

2025-01-15 20:15 UTC, digiwand commented
Hey @brianacnguyen, apologies, I think I may have missed communicating this in our thread. I moved ButtonPill to the temp folder and created an issue to handle the storybook page + more refined unit tests in a subsequent PR. I will create a recording and add it here in the meantime 

follow-up PR https://github.com/MetaMask/metamask-mobile/issues/12910

2025-01-15 20:24 UTC, digiwand commented
hi @MetaMask/notifications team, may I get a review here please?  

I created a follow-up ticket to move shortenString outside of the notifications domain. Sorry I didn't move it earlier but will move asap in a subsequent PR. It also seems shortenString was not being used anymore before this PR. This PR brings back its usecase 

New Issue: https://github.com/MetaMask/metamask-mobile/issues/13016

2025-01-15 20:46 UTC, brianacnguyen approved these changes

2025-01-15 21:14 UTC, Prithpal-Sooriya approved these changes

2025-01-15 22:10 UTC, merged