chore: Convert browser tab to typescript
MetaMask/metamask-mobile pull request #12740
Opened 2024-12-17 20:45 UTC by tommasini

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2025-01-08 16:20 UTC, brianacnguyen commented on app/component-library/components/Icons/Icon/Icon.assets.ts
> +import blankSVG from './assets/blank.svg';
@tommasini why was this needed?

2025-01-08 16:20 UTC, brianacnguyen requested changes
a comment

2025-01-09 15:20 UTC, tommasini commented on app/component-library/components/Icons/Icon/Icon.assets.ts
> +import blankSVG from './assets/blank.svg';
This was added by @Cal-L on this [commit ](https://github.com/MetaMask/metamask-mobile/pull/12740/commits/14796932b38da816b6f3daa39503e1be4b6b85ff)

2025-01-15 20:34 UTC, Cal-L commented on app/component-library/components/Icons/Icon/Icon.assets.ts
> +import blankSVG from './assets/blank.svg';
It was used to hide the connection type icon in the address bar. Not needed anymore, so removed, thanks!

2025-01-20 10:41 UTC, EtherWizard33 approved these changes, later dismissed
approved for wallet-ux on the two following files codeownered:
app/components/UI/OnboardingWizard/index.tsx
app/components/Views/Settings/SecuritySettings/SecuritySettings.tsx

2025-01-20 13:32 UTC, sahar-fehri approved these changes, later dismissed

2025-01-20 23:08 UTC, abretonc7s approved these changes, later dismissed

2025-01-21 22:47 UTC, adonesky1 submitted a review, later dismissed
RPCMethodMiddleware changes look good to me!

2025-01-21 23:33 UTC, brianacnguyen submitted a review, later dismissed

2025-01-22 16:32 UTC, Cal-L approved these changes
Lgtm!

2025-01-23 15:08 UTC, EtherWizard33 approved these changes
re-approve after prev was reset

2025-01-23 15:41 UTC, tommasini commented on app/actions/browser/index.js
> +    metricsEnabled,
Yes just for simplicity let me cover it in another PR!

2025-01-23 15:51 UTC, adonesky1 approved these changes

2025-01-23 15:55 UTC, sahar-fehri approved these changes

2025-01-23 16:17 UTC, christopherferreira9 approved these changes
re-approve from @abretonc7s 's

2025-01-23 16:30 UTC, brianacnguyen approved these changes

2025-01-23 18:24 UTC, merged