feat: add Network URL non-ascii -> punycode warning
MetaMask/metamask-mobile pull request #12813
Opened 2024-12-20 16:15 UTC by digiwand

## **Description**

Similar to the extension, we want to warn the user if the URL has non-ASCII characters. Inline alerts are not supported on mobile, so we display the new alert as a banner.

## **Related issues**

Fixes: https://github.com/MetaMask/MetaMask-planning/issues/2365

## **Manual testing steps**

Test switching to a custom network

## **Screenshots/Recordings**

### **Before**

![CleanShot 2024-12-20 at 19 22 05@2x](https://github.com/user-attachments/assets/51c455ab-4f2e-4663-8bd1-305cfab6f3dd)

### **After**

![CleanShot 2024-12-20 at 22 19 39@2x](https://github.com/user-attachments/assets/8df714b1-6f9e-4915-8b6c-a5944c2d43c0)

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2025-01-07 10:11 UTC, jpuri commented on app/util/url/index.ts
> +};
@digiwand : why is the check for valid ASCII includes only the host part of the URL ?

2025-01-07 16:24 UTC, digiwand commented on app/util/url/index.ts
> +};
hey @jpuri, good question. I copied this method verbatim from the metamask-extension code. I think you created the one in the metamask-extension. 

will double-check this method with consideration of @NicholasEllul's comment above https://github.com/MetaMask/metamask-mobile/pull/12813/files#r1905686031

2025-01-07 23:43 UTC, digiwand commented on app/util/url/index.ts
> +    return urlString?.includes(punycode.toASCII(new URL(urlString).host));
hey @NicholasEllul and @jpuri, thanks for flagging this! This helper method was copied over from the extension. I updated the extension code and the code in this PR to include the path in its check. can I get another look at this please? 

related extension PR: https://github.com/MetaMask/metamask-extension/pull/29490

2025-01-07 23:43 UTC, digiwand commented on app/util/url/index.ts
> +};
please see https://github.com/MetaMask/metamask-mobile/pull/12813#discussion_r1906162676

2025-01-08 06:01 UTC, jpuri submitted a review, later dismissed
Nice work

2025-01-08 16:59 UTC, matthewwalsh0 requested changes

2025-01-08 16:59 UTC, matthewwalsh0 commented on app/util/url/index.ts
> +    console.error(exp);
Minor, does this warrant an error log if it's handled?

And if we still want a log, should we add some context for clarity such as:

`console.log('URL contains non-ASCII characters', urlString, urlPunycodeString)`

2025-01-08 16:59 UTC, matthewwalsh0 commented on app/util/url/index.ts
> +    return `${protocol}//${punycodeHostname}${port}${pathname}${search}${hash}`;
Why do we need to build this manually and only convert the hostname to ASCII?

Could we pass the entire `href` in one go as we do in `isValidASCIIURL`?

2025-01-08 19:26 UTC, NEllusion reviewed
I notice the following notice in the punycode README: https://github.com/mathiasbynens/punycode.js?tab=readme-ov-file#installation

> ⚠️ Note that userland modules don't hide core modules. For example, require('punycode') still imports the deprecated core module even if you executed npm install punycode. Use require('punycode/') to import userland modules rather than core modules.


We should double check to ensure we are using the punycode built into node which is soft-deprecated. I notice other files like this one import punycode as the following: https://github.com/MetaMask/metamask-mobile/blob/e0864ad83afcaf74c535efa4006e773564e31f1c/app/util/address/index.ts#L9

2025-01-08 19:26 UTC, digiwand commented on app/util/url/index.ts
> +    return `${protocol}//${punycodeHostname}${port}${pathname}${search}${hash}`;
oh I originally proposed href then took it out to handle the pathname === '/' logic. Taking a second look at this we can keep the href and reword the logic. Thanks for the callout! updated [4c48863](https://github.com/MetaMask/metamask-mobile/pull/12813/commits/4c4886389c3a8bc8ada30f48b6baa74e621f6682)

2025-01-08 20:42 UTC, digiwand commented on app/util/url/index.ts
> +    return urlPunycodeString?.includes(urlString);
@NicholasEllul

yeah, the react-native runtime URL library didn't seem to support the punycode encoding

---

> E.g if the url string in this case is https://opensea.io/language=français, the toASCII function will incorrectly turn it into https://example.xn--com/lang=franais-opb.

This is the reason why I was told we are displaying the given input rather than the punycode version. We show the punycode different in the warning. If only we could mimic the behavior of the browser search bar. An attempt at this would be out-of-scope

2025-01-10 20:04 UTC, digiwand commented on app/util/url/index.ts
> +    return urlPunycodeString?.includes(urlString);
@NicholasEllul I like this idea. Will update. When we do render the punycode version in the warning, we will continue to do so on the entire URL, including the path.

2025-01-10 20:16 UTC, digiwand commented on app/util/url/index.ts
> +    return urlPunycodeString?.includes(urlString);
@NicholasEllul 

ran into a test blocker. Because URL does apply punycode encoding in the node.js tests, the checks don't test what is represented in react-native and it fails to detect the differences. We want to check the original hostname of urlString. We could add a regex to check this non-punycode encoded hostname 🤔

2025-01-10 22:32 UTC, digiwand commented on app/util/url/index.ts
> +    return urlPunycodeString?.includes(urlString);
updated using a regex @NicholasEllul [c880f36](https://github.com/MetaMask/metamask-mobile/pull/12813/commits/c880f3614c3276557f899d33c4c635f6d0e67b52). Thanks for the suggestion!

2025-01-13 18:49 UTC, NEllusion approved these changes
Nice workaround 👍

2025-01-14 16:14 UTC, matthewwalsh0 approved these changes

2025-01-14 18:21 UTC, merged