Link to support URLs using default browser
MetaMask/metamask-mobile pull request #1303
Opened 2020-01-28 17:03 UTC by rickycodes

re: #1295 

Alternatively we could check what platform is being used and only adjust this functionality in Android? @dpazdan also mentioned wanting to change the general google form so we're funnelling everything through zendesk. However it appears we're sending a lot of pertinent data in that form so I am not entirely sure what that would look like.

2020-01-28 22:27 UTC, estebanmino requested changes
i'd like to fix the issue inside the app rather than sending the user to other app and fix it later. WDYT?

2020-01-29 14:44 UTC, rickycodes commented
I added the platform check so the two support links only promp user for default browser on Android.

2020-01-29 16:17 UTC, rickycodes commented on app/components/UI/DrawerView/index.js
> +const USE_EXTERNAL_LINKS = (Platform.OS === 'android') | false;
I need to change this to `||`

2020-01-29 19:18 UTC, brunobar79 approved these changes
LGTM

2020-02-04 15:47 UTC, estebanmino approved these changes

2020-02-04 21:45 UTC, ibrahimtaveras00 approved these changes
Looks good, QA Passed 👍

2020-02-05 19:48 UTC, merged