[WIP] Improvement: send flow
MetaMask/metamask-mobile pull request #1327
Opened 2020-02-05 22:36 UTC by estebanmino

**Description**

Improvements based on @cjeria doc

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2020-02-17 12:51 UTC, danjm commented on app/components/Views/Settings/Contacts/ContactForm/index.js
> +									onBlur={this.onBlur}
Is `this.onBlur` defined?

2020-02-17 12:57 UTC, danjm commented on app/components/UI/Navbar/index.js
> +			<TouchableOpacity onPress={navigationPop} style={styles.backButton}>
Minor: We could pass `navigation.pop` directly to `onPress` to avoid creating the extra function.

2020-02-17 12:58 UTC, danjm requested changes
Left a couple comments. The only important one is the question about `this.onBlur` in `ContactForm/index.js`

2020-02-18 14:25 UTC, estebanmino commented on app/components/Views/Settings/Contacts/ContactForm/index.js
> +									onBlur={this.onBlur}
not defined, I can remove it

2020-02-18 14:37 UTC, estebanmino commented on app/components/UI/Navbar/index.js
> +			<TouchableOpacity onPress={navigationPop} style={styles.backButton}>
it doesn't work that way

2020-02-18 18:33 UTC, rickycodes commented on app/components/UI/Navbar/index.js
> +			<TouchableOpacity onPress={navigationPop} style={styles.backButton}>
It could just be `onPress={e => navigation.pop()}`. I think having a separate function is fine though.

2020-02-19 16:06 UTC, rickycodes commented on app/components/UI/Navbar/index.js
> +			<TouchableOpacity onPress={navigationPop} style={styles.backButton}>
I see why it's a separate function now... doing what I proposed above results in a warning: `JSX props should not use arrow functions eslint(react/jsx-no-bind)`

2020-02-20 01:00 UTC, ibrahimtaveras00 commented
Some QA issues I saw from the mobile address book design QA doc:

**From 1.2 in doc**

When switching the account in the "From" field on the "send to" view, it doesn't detect the update 
For example, in this screencast Account 1 does have a balance greater than 0 ETH while Account 4 has 0 ETH, I correctly see the message displayed when FROM = Account 4, however, when I switch to Account 1, the message is still displayed

Seen here = https://recordit.co/rB9WamXrfk

![image](https://user-images.githubusercontent.com/41752922/74890067-eb656000-5350-11ea-8263-014e53d8cbdc.png)

Steps to reproduce:
This can be reproduced in 2 ways:
1) Start on an account that has 0 ETH then switch to an account that has some ETH
2) Start on an account that has ETH, then switch to an account that has 0 ETH

**From 3 in doc**

This issue is still happening "The last account used to send does not show up in my “Recents” list"

**From 6.1 in doc**

I do see the green check mark aligned next to the address when no name is present, however, when there is a name present, or has an ENS name, the green check mark is now in the middle, is this intended/how it should be? 

![image](https://user-images.githubusercontent.com/41752922/74890255-8a8a5780-5351-11ea-98b5-5fb67e051245.png)


**From 7 in doc**

I do not see any updates from 7.1 to 7.5 
Are we ignoring this for now, or was this over looked? 

**From 8.1 in doc**

When you already have at least 1 contact, then add another contact, and then attempt to delete that newly added contact, the list does not update unless you leave the Contacts view by going back to settings and then coming back to the Contacts view

seen here = https://recordit.co/tZlryP2SeJ

**Other Issue**

I'm not sure which to associate this issue with in the doc, but nonetheless it is noticeable.

When I have an ENS name in my Recents list that's not saved yet in my contacts, and I tap on it to populate the To field, I do not see the option to add to my address book.

On the other hand, if I manually type the same exact ENS name, I do see the option.

Seen here = http://recordit.co/sEI6SxDyCJ

2020-02-20 16:25 UTC, estebanmino commented on app/components/UI/Navbar/index.js
> +			<TouchableOpacity onPress={navigationPop} style={styles.backButton}>
is a separate function because it literally doesn't work, if I changed that the user couldn't go back

2020-02-20 16:52 UTC, estebanmino commented
@ibrahimtaveras00  Issue 7 is https://github.com/MetaMask/metamask-mobile/issues/1334

2020-02-21 19:07 UTC, danjm commented on app/components/Views/Settings/Contacts/ContactForm/index.js
> +		// Workaround https://github.com/facebook/react-native/issues/9958
Interesting workaround. I guess we should check back on that react-native issue and remove the workaround once the underlying problem is resolved

2020-02-21 19:10 UTC, danjm approved these changes
All the code changes look good to me

2020-02-26 02:27 UTC, ibrahimtaveras00 commented
All fixes look good 👍 

Last issue I found is more of a question; do we want to have an ellipsis here @estebanmino @cjeria?

![Screen Shot 2020-02-25 at 9 24 32 PM](https://user-images.githubusercontent.com/41752922/75305907-6dec9480-5815-11ea-8f8e-3621a8b5c602.png)

Same as on the send view as well

![Screen Shot 2020-02-25 at 9 27 31 PM](https://user-images.githubusercontent.com/41752922/75305968-a7250480-5815-11ea-8ccc-2e2d7acb2c8b.png)

2020-02-26 18:18 UTC, cjeria commented
> Last issue I found is more of a question; do we want to have an ellipsis here @estebanmino @cjeria?
Yes to ellipsis. Let's try to make it wide as possible.

2020-02-26 18:23 UTC, omnat commented
QA: Recent addresses only the ones from address book, not the ones not saved. This logic needs changing. @danjm

2020-02-26 20:04 UTC, ibrahimtaveras00 commented
Ellipsis fix looks good 👍 

<img width="825" alt="Screen Shot 2020-02-26 at 3 00 36 PM" src="https://user-images.githubusercontent.com/41752922/75382791-2e6f8800-58a9-11ea-9d06-b26587dee38f.png">

2020-02-26 21:04 UTC, ibrahimtaveras00 approved these changes
Changes look good on both OS's QA Passed 👍

2020-02-26 21:33 UTC, cjeria commented
Looking good! One additional change I'd like to suggest is to remove the text "No contacts in your address book" or at least use a grey color since I thought it looked like a text link, although I'm more in favor of just removing it altogether. 

![image](https://user-images.githubusercontent.com/597770/75390018-8ad8a480-58b5-11ea-8ab5-b7dfb0f8abdf.png)

2020-02-27 15:57 UTC, merged