Adjust padding
MetaMask/metamask-mobile pull request #1390
Opened 2020-02-28 20:12 UTC by rickycodes

**Description**

re: https://github.com/MetaMask/metamask-mobile/issues/1330

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable (not applicable)
* [x] Any added code is fully documented (not applicable)
* [x] Use 24px padding (or as low as 22px for smaller screen) to the left and right of the screen.
* [x] This includes address bar and large cancel/approve buttons.
* [ ] The modal window looks like it goes over 24px. 
* [ ] Remove confirm page.

**Issue**

Resolves #1330

2020-03-02 20:25 UTC, cjeria approved these changes
LGTM

2020-03-03 15:35 UTC, estebanmino commented on app/components/UI/ActionModal/index.js
> +		width: '100%',
this component is used in other places of the app not only here, is this working everywhere?

2020-03-03 15:35 UTC, estebanmino commented on app/components/UI/ActionView/index.js
> +		paddingHorizontal: 24
same here, component re used in other places

2020-03-03 15:38 UTC, estebanmino commented on app/components/UI/TransactionEdit/index.js
> +		left: 24,
this component is not related to approve screen, there are other updates as well?

2020-03-03 15:39 UTC, estebanmino commented on app/components/Views/PaymentChannel/PaymentChannelDeposit/index.js
> +		paddingLeft: 24
same here, not approve

2020-03-03 15:40 UTC, estebanmino reviewed
looks good, my only doubt is I see changes in other places that aren't related to approve screen

2020-03-03 15:40 UTC, rickycodes commented on app/components/UI/ActionModal/index.js
> +		width: '100%',
yep, it's working as expected everywhere. I actually tested it via the `Send Feedback` link as well (since that's easier to get to).

2020-03-03 15:53 UTC, rickycodes commented on app/components/UI/ActionView/index.js
> +		paddingHorizontal: 24
we still want the same padding regardless of where it's used

2020-03-03 15:54 UTC, rickycodes commented on app/components/Views/PaymentChannel/PaymentChannelDeposit/index.js
> +		paddingLeft: 24
the from graphic is in the screens and needed to be moved over slightly to fall into the same grid.

2020-03-03 15:56 UTC, rickycodes commented on app/components/UI/TransactionEdit/index.js
> +		left: 24,
you're right that this one is not the in screens included in the PR, but the spacing on these still needed to be adjusted to match

2020-03-03 15:57 UTC, rickycodes commented
I've addressed your feedback. there are a couple spacing changes that are unrelated to the approve screen, but this spacing should be the same throughout the application.

2020-03-04 20:42 UTC, ibrahimtaveras00 commented
I checked on various screen sizes on both OS's and the only issues I could fine are the following: 

Happening on a smaller screen (iPhone SE) but looks fine on the small screen on Nexus S

![Screen Shot 2020-03-04 at 3 09 04 PM](https://user-images.githubusercontent.com/41752922/75920938-49ed0c80-5e2e-11ea-9113-4887b2d54344.png)

The blue check mark on smaller screens:

Here's iPhone SE:

![Screen Shot 2020-03-04 at 3 30 08 PM](https://user-images.githubusercontent.com/41752922/75921029-6d17bc00-5e2e-11ea-9613-cbef0023fa24.png)

Here's Nexus S:

![Screen Shot 2020-03-04 at 3 37 38 PM](https://user-images.githubusercontent.com/41752922/75921051-76a12400-5e2e-11ea-980b-11fd2cdfa111.png)


And the "E" for "AVERAGE" on this view:

![Screen Shot 2020-03-04 at 3 36 10 PM](https://user-images.githubusercontent.com/41752922/75921131-97697980-5e2e-11ea-84c2-cb0f0dc7ebda.png)

which is happening on both iPhone SE and Nexus S

steps to get to this view:
- go to browser
- switch to ropsten network
- go to https://faucet.metamask.io/
- after connecting attempt to donate some ETH 
- on confirm view, tap on Edit on the top left

2020-03-04 21:03 UTC, cjeria commented
good catch @ibrahimtaveras00 !  I'll have a look at this asap!

2020-03-05 02:31 UTC, cjeria commented
Here are suggested solutions to all of the above UI bugs and link to figma file below. Let me know if there are any questions! cc @rickycodes 
![image](https://user-images.githubusercontent.com/597770/75941981-2abaa300-5e5f-11ea-8791-e178ad80eaec.png)

Figma file
https://www.figma.com/file/1aRs60GBYLLlBkReWg3XSA/Gas-selection-button-group?node-id=1%3A281

2020-03-06 18:28 UTC, estebanmino requested changes
From yesterday's conversations, for this PR we have to address https://github.com/MetaMask/metamask-mobile/pull/1390#issuecomment-594825281 and apply @cjeria design in a separate PR

2020-03-11 15:59 UTC, rickycodes commented
Closing this and will open a new PR with this work as well as the new work suggested in https://github.com/MetaMask/metamask-mobile/pull/1390#issuecomment-594996341

2020-03-11 15:59 UTC, closed without merging