Feature: analytics v2
MetaMask/metamask-mobile pull request #1453
Opened 2020-03-23 21:57 UTC by estebanmino

**Description**

Several updates to the events we're tracking based on https://docs.google.com/spreadsheets/d/1XYj78KAUytJQCKk1fD8pERxXsZRZ6aQhcMP5GJS5X8k/edit#gid=1878986372

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #1350

2020-04-07 00:57 UTC, ibrahimtaveras00 commented
**Issue 1:**

Tapping on Instapay shows as Nacigation Drawer > Logout (row 34 in spreadsheet) 

**Issue 2:**

Metrics Opt Out doesn’t seem to be triggered (row 7 in spreadsheet)

**Issue 3:** 

Taps on account icon and Taps on network isn't working (rows 97 and 98 in spreadsheet)

**Issue 4:**

Send Flow "confirm send" (“User taps ‘Send’ on review screen”) doesn’t seem to get triggered
Instead, this is the one that’s triggered = Adds Amount (row 288 in spreadsheet)

**Issue 5:**

Approve Request View tx details User taps ‘View details’ isn't working (row 34 in spreadsheet)

2020-04-09 21:15 UTC, estebanmino commented
@ibrahimtaveras00 everything was fixed but `Issue 3`, talked with @omnat and these are already implemented under other events

2020-04-10 00:16 UTC, ibrahimtaveras00 approved these changes
All fixes look good, QA Passed 👍

2020-04-16 16:44 UTC, danjm requested changes
Everything looks good. I made some minor suggestions, and ask a couple of questions on things I was uncertain about.

Another thought, that does not need to be addressed in this PR, we can probably create a utility method for calls of type:
```
InteractionManager.runAfterInteractions(() => {			 
    Analytics.trackEvent(ANALYTICS_EVENT_OPTS.ONBOARDING_SELECTED_NO_THANKS);
});
```
That's an improvement to be made in another issue though.

2020-04-16 16:44 UTC, danjm commented on app/components/UI/OnboardingWizard/index.js
> +const stepDescription = {
Perhaps these should be included in `metamask-mobile/app/util/analytics.js`

2020-04-16 16:44 UTC, danjm commented on app/components/UI/OnboardingWizard/index.js
> +					View: stepDescription[step]
There seems to be a convention of using a `this.getTrackingParams` method with `trackEventWithParameters`. Should we follow that same convention here?

2020-04-16 16:44 UTC, danjm commented on app/components/UI/OptinMetrics/index.js
> -		Analytics.enable();
Why is `Analytics.enable();` no longer needed?

2020-04-16 16:44 UTC, danjm commented on app/components/Views/SendFlow/Confirm/index.js
> +					network: providerType
Should we follow the `this.getTrackingParameters` convention here? (I asked a similar question above)

2020-04-16 16:46 UTC, danjm commented
Also, have we anywhere documented all the params/properties we are sending to mixpanel?

2020-04-16 20:58 UTC, estebanmino commented on app/components/UI/OnboardingWizard/index.js
> +					View: stepDescription[step]
because I added it on `componentDidMount`

2020-04-16 21:01 UTC, estebanmino commented on app/components/Views/SendFlow/Confirm/index.js
> +					network: providerType
I only added `getTrackingParameters` on places where I used it more than one time, if we do it here it seems like boilerplate code for me

2020-04-16 21:03 UTC, estebanmino commented on app/components/UI/OptinMetrics/index.js
> -		Analytics.enable();
because I added it on componentDidMount

2020-04-16 21:04 UTC, estebanmino commented on app/components/UI/OnboardingWizard/index.js
> +					View: stepDescription[step]
replied the same in another comment, if we use it just one time I don't think is a need for cleaner code, WDYT?

2020-04-16 21:05 UTC, estebanmino commented on app/components/UI/OnboardingWizard/index.js
> +const stepDescription = {
I can do that

2020-04-16 21:26 UTC, estebanmino commented
@danjm left comments on yours and added an object to the utils file
- `Also, have we anywhere documented all the params/properties we are sending to mixpanel?`: yes, I left the link on the description of this pr

2020-04-22 19:49 UTC, danjm commented on app/components/UI/OnboardingWizard/index.js
> +					View: stepDescription[step]
yeah, that's fine

2020-04-22 19:49 UTC, danjm commented on app/components/UI/OptinMetrics/index.js
> -		Analytics.enable();
:ok_hand:

2020-04-22 19:50 UTC, danjm approved these changes

2020-04-23 19:25 UTC, merged