Handle icon parsing without faviconkit
MetaMask/metamask-mobile pull request #1464
Opened 2020-03-31 02:30 UTC by rickycodes

**Description**

Relying on a 3rd party to handle our icons has proven unreliable; this can be seen in #1261 and #1335. There's also some additional details here: https://github.com/MetaMask/metamask-mobile/issues/1261#issuecomment-575782124. This adds a single dep and parses favicons directly in the client.

**Issue**

Resolves #1261

2020-04-16 17:01 UTC, danjm requested changes
Nice solution to the problem. I've suggested a couple changes to make.

2020-04-16 17:02 UTC, danjm commented
@ibrahimtaveras00 The code changes needed here are pretty minimal, so this is good for QA. Aims to resolve #1261

2020-04-17 17:39 UTC, ibrahimtaveras00 approved these changes
Fixes look good on both OS's, QA passed 👍

2020-04-17 23:55 UTC, rickycodes commented on app/components/UI/WebsiteIcon/index.js
> +			return sizes || (/icon/.test(rel) && el);
ya that probably doesn't need to be there.

2020-04-18 00:46 UTC, rickycodes commented on app/components/UI/WebsiteIcon/index.js
> +		if (!icon) {
yes that, but also the case where a website _only_ has a `favicon.ico`. the rest of this tries to get icons from `<links>` eg: 
```
  <link href="images/favicon.png" rel="shortcut icon" type="image/x-icon">
  <link href="images/webclip.png" rel="apple-touch-icon">
```
but these aren't always set. in that case we would need something to turn that `.ico` file into something we can render. I was thinking about covering this case maybe with something like https://github.com/LinusU/ico-to-png or something similar? There might even be a simple way to do it with File api I'm not sure. But it certainly seems feasible to do it in the client? It was at this point where I thought maybe doing all this lifting to get icons off a favicon service might not be worth it? wdy think?

2020-05-07 21:08 UTC, rickycodes commented
this still needs some work so I am converting it to draft status

2020-06-06 14:36 UTC, rickycodes commented
I've updated this a bit and did some additional testing. I'm confident we can merge this now.

2020-06-11 14:52 UTC, danjm approved these changes
LGTM

2020-06-22 18:23 UTC, omnat commented
@ibrahimtaveras00 @rickycodes @danjm 
Can we merge this one?

2020-07-28 01:37 UTC, rickycodes commented
I'm just going to close this for now to get it out the way... there's some good stuff in here, but this work needs to be redone in the mobile provider and in dapps

2020-07-28 01:37 UTC, closed without merging