WIP: Make send flows consistent
MetaMask/metamask-mobile pull request #1465
Opened 2020-04-01 18:48 UTC by rickycodes

**Description**

Reuse components from the new send flow in certain areas to make things consistent

**Before:**

<img width=400 src=https://user-images.githubusercontent.com/675259/78174696-a8a2a780-7427-11ea-845a-b7fda144824c.png />

**After:**

<img width=400 src=https://user-images.githubusercontent.com/675259/78174713-b2c4a600-7427-11ea-9841-fd8682876d48.png />

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2020-04-01 21:28 UTC, cjeria commented
Looking good Ricky! So @omnat and I took a look together and wanted to point out a few things for this screen. See the screenshot for notes. Let us know if you have any questions @rickycodes 

![image](https://user-images.githubusercontent.com/597770/78188376-1c4faf00-743e-11ea-8acf-62cd1eef496e.png)

2020-04-15 17:10 UTC, danjm commented
@cjeria Here are updated designs. Let me know what you think of the disabling of the accounts that have insufficient funds: https://streamable.com/35d8vo

2020-04-15 17:52 UTC, danjm commented
New designs now working for payment request as well: https://streamable.com/dskued

2020-04-15 17:53 UTC, danjm commented
However, those designs do not allow the user to edit as many fields as the existing payment request screen. Will discuss live with Christian.

2020-04-22 16:17 UTC, danjm commented
Demo video of new designs applied to instapay txes: https://streamable.com/6qzdpa

2020-04-27 15:57 UTC, estebanmino reviewed
LGTM in terms of code,  left some important concerns tho

2020-04-27 15:57 UTC, estebanmino commented on app/components/Views/SendFlow/Confirm/index.js
> +		};
can we move all of this to `componentDidMount` (or `didUpdate`checking for changes on state if needed)? My concern with this way is performance, all of this is going to be executed when state changes, so many times for  data that is not going to change

2020-04-27 15:57 UTC, estebanmino commented on app/components/Views/SendFlow/Confirm/index.js
> +import { newTransaction } from '../../../../actions/transaction';
I've seen this in other files too, I don't feel safe using to sets of `reducers` and `actions` for the same transaction. The idea before this PR of having a new `actions/newTransaction` was to keep using the old flow for app / deeplink txs in its own state, now that we're unifying these we should use the same redux state to handle all txs, wdyt?

2020-04-27 15:57 UTC, estebanmino commented on app/components/Views/SendFlow/Amount/index.js
> +	return {
added a comment below about this, we have too many state updates coming from redux this could impact performance

2020-04-27 15:57 UTC, estebanmino commented on app/components/Views/SendFlow/Amount/index.js
> +import { setTransactionObject } from '../../../../actions/transaction';
Added a comment in `/confirm/index.js` about this

2020-04-30 16:47 UTC, danjm commented on app/components/Views/SendFlow/Confirm/index.js
> +import { newTransaction } from '../../../../actions/transaction';
Is this what you had in mind: https://github.com/MetaMask/metamask-mobile/pull/new/consistent-send-flow-tx-state-refactor

A couple bugs to work out, but wanted to share what I've done so far to make sure it matches what you were thinking

2020-04-30 16:48 UTC, danjm commented on app/components/Views/SendFlow/Amount/index.js
> +	return {
This goes away with this refactor: https://github.com/MetaMask/metamask-mobile/pull/new/consistent-send-flow-tx-state-refactor

2020-04-30 16:48 UTC, danjm commented on app/components/Views/SendFlow/Confirm/index.js
> +		};
This goes away with this refactor: https://github.com/MetaMask/metamask-mobile/pull/new/consistent-send-flow-tx-state-refactor

2020-04-30 16:50 UTC, danjm commented on app/components/Views/SendFlow/Amount/index.js
> +import { setTransactionObject } from '../../../../actions/transaction';
Addressed in https://github.com/MetaMask/metamask-mobile/compare/consistent-send-flow...consistent-send-flow-tx-state-refactor?expand=1

2020-05-01 10:11 UTC, danjm commented on app/components/Views/SendFlow/Confirm/index.js
> +		};
With the latest commit 1216a2369682e0913b802388921b150f2faf5917, this is now all handled before the transaction is dispatched to redux.

2020-05-01 10:12 UTC, danjm commented on app/components/Views/SendFlow/Confirm/index.js
> +import { newTransaction } from '../../../../actions/transaction';
The two reducers are combined in 1216a2369682e0913b802388921b150f2faf5917,

2020-05-01 11:35 UTC, danjm commented on app/components/Views/SendFlow/Amount/index.js
> +	return {
With the latest commit 08b4a49, this is now all handled before the transaction is dispatched to redux.

2020-05-01 11:36 UTC, danjm commented on app/components/Views/SendFlow/Amount/index.js
> +import { setTransactionObject } from '../../../../actions/transaction';
The two reducers are combined in 08b4a49,

2020-05-06 17:06 UTC, estebanmino commented on app/store/index.js
> +	2: state => {
I don't think this is needed, this state is only used when sending txs if that flow finishes the state should be erased

2020-05-06 17:15 UTC, estebanmino commented on app/components/Views/SendFlow/SendTo/index.js
> +		: state.transaction.selectedAsset,
was this intended?

2020-05-06 17:50 UTC, danjm commented on app/components/Views/SendFlow/SendTo/index.js
> +		: state.transaction.selectedAsset,
lol, no the ternary statement is no longer needed and it can just be `selectedAsset: state.transaction.selectedAsset`

2020-05-06 17:52 UTC, danjm commented on app/store/index.js
> +	2: state => {
In that case we only need a migration to delete the `newTransaction` property from state... an error is thrown otherwise

2020-05-06 21:16 UTC, ibrahimtaveras00 commented
**Issue 1:**

It's a little confusing at first how to edit the txn fee if you don't pay attention right away to the wording, but making it blue to stand out should be easier and more identifiable 
cc: @cjeria 

![image](https://user-images.githubusercontent.com/41752922/81229144-5a9c3900-8fbd-11ea-8ec2-825ad96577fa.png)

2020-05-06 22:55 UTC, omnat commented
**Issue 1:**
Yes, per the designs this was meant to be blue. Let's make it blue. 

**Issue 2:**
Account shouldn't be switchable when user is initiating the Send flow **only** when a payment request link/QR is opened (that lands on confirm screen)

cc @cjeria

2020-05-06 23:13 UTC, ibrahimtaveras00 commented
**Issue 3:**

I am unable to transact on dapps 

- https://faucet.metamask.io/

Here I attempted to donate ETH on Ropsten 

Seen here = https://recordit.co/KaE6gOic9A

- https://metamask.github.io/test-dapp/

I can't really perform any txn on this site

Seen here = https://recordit.co/0gPWKlFzLx

- https://uniswap.exchange on mainnet 

Similar to above issue, I can't complete my txn

seen here = https://recordit.co/PF81D9n3IP

2020-05-06 23:53 UTC, ibrahimtaveras00 requested changes
Found issues 1-4

2020-05-07 00:27 UTC, omnat commented
Issue 3 is the most critical and a definite blocker.

2020-05-07 16:20 UTC, danjm commented
Fixed issues 1-4
----
Issue #1 fixed in 593ad00028c6d43491af818daa585b7bd3e7781c

<details>
<summary>Screenshot of issue 1 fix:</summary>
![Screenshot from 2020-05-07 13-42-45](https://user-images.githubusercontent.com/7499938/81318482-e4551080-9068-11ea-8f56-f55478b92722.png)
</details>
----
Issue #2 fixed in b0bc9deec2737472c2c63f351bdd27e9b3d6d7b7

<details>
<summary>Screenshot of issue 2
![Screenshot from 2020-05-07 13-20-59](https://user-images.githubusercontent.com/7499938/81318586-123a5500-9069-11ea-95d9-e9e09e6f3a2d.png)
 fix:</summary>

</details>
Also, video of still being able to select account payment request txes: https://streamable.com/ejwnle
----
Issue #3 fixed in c0dcb9283e8f74bd59e7e0b065509539c92108a7

Video of confirming tx from faucet: https://streamable.com/44857d
Video of confirming tx from uniswap: https://streamable.com/0q67ut
Video of confirming tx from test-dapp: https://streamable.com/qbd7er
----
Issue #4 fixed in 46eff4e7ba0b8d0af0e128d4c1aa5ced8a25efef

Video of correct balance validation for payment channel txes: https://streamable.com/scenqr

2020-05-07 20:43 UTC, ibrahimtaveras00 commented
**Issue 1:* = Fixed 👍 

**Issue 2:* = Initial issue was fixed, however, as @omnat stated above should the account be switchable **only** when coming from a payment request?  Currently that's not the case.
cc: @cjeria 

seen here = https://recordit.co/TI0H3550Zy

![image](https://user-images.githubusercontent.com/41752922/81338904-60585400-907b-11ea-93e1-855c52fc5977.png)

**Issue 3:* = Is fixed, however, it's exactly the same as the old flow; seen here = https://recordit.co/zV81j2nWlc

![Screen Shot 2020-05-07 at 4 07 56 PM](https://user-images.githubusercontent.com/41752922/81339928-f345be00-907c-11ea-985c-7ba8adf734ad.png)

![Screen Shot 2020-05-07 at 4 08 28 PM](https://user-images.githubusercontent.com/41752922/81339962-0193da00-907d-11ea-8b14-45181dc53b99.png)

I was under the impression that we should not be seeing this old view and should be consistent with the new send flow view? cc: @omnat @cjeria 

**Issue 4:** = Fixed 👍 


While re-testing there were some issues I noticed in the payment request flow:

**Issue 5A:** 

When coming from a payment request link or QR code I am immediately sent to this view, however, it doesn't say Confirm as it does in regular send flow.  To keep it consistent it should say confirm right? 

![image](https://user-images.githubusercontent.com/41752922/81341890-52f19880-9080-11ea-99f3-773c5cf48ffc.png)

Also, notice in the screenshot one says "Back" and another says "Edit"

**Issue 5B:**

Following up on Issue 5A, when you do end up tapping edit, there are two cancel buttons 

![image](https://user-images.githubusercontent.com/41752922/81342019-86ccbe00-9080-11ea-8dc0-8e1bb9cf3ca6.png)

**Issue 5C:**

And finally, when you do initiate the payment request flow either by deeplink or by scanning QR code, if you do not change the amount, then you get this txn error:
seen here = http://recordit.co/ILnDSjNMaA

![image](https://user-images.githubusercontent.com/41752922/81342152-bbd91080-9080-11ea-8fa7-c70d4b15eb8c.png)

I'm going to continue sanity checking to see if any other issues arise...

2020-05-07 21:18 UTC, cjeria commented
Issue 2: yes, only switchable from a payment request
Issue 3: Yes, the old confirm screen is being used. It should be the **new confirm screen**. 
Issue 5A: Let's make both say **Confirm**. From payment request the difference in the top bar links is correct.  
Issue 5B: There should be only one cancel button on the right side of the top bar.
Issue 5C: Yep, that seems like a bug!

2020-05-07 21:21 UTC, ibrahimtaveras00 commented
**Issue 6:**

Forgot to check instapay deeplink, looks like it's still triggering the old flow

seen here = https://recordit.co/fY1juDUioW

2020-05-08 05:53 UTC, danjm commented
**Issue 2**
From dropdown now switchable for both link and QR code payment requests: https://streamable.com/9wfy0o 

**Issue 3**
Not an issue, as discussed here: https://consensys.slack.com/archives/GT64EQCV6/p1588890847103400

**Issue 5a and 5b**
Headers for payment requests now look like:
![Screenshot from 2020-05-08 02-57-08](https://user-images.githubusercontent.com/7499938/81373888-5fa1db00-90d8-11ea-8ad8-03992686510e.png)
-
![Screenshot from 2020-05-08 02-57-14](https://user-images.githubusercontent.com/7499938/81373894-63356200-90d8-11ea-8066-8b69b9893490.png)

**Issue 5c**
Payment request works without edit: https://streamable.com/gplqrs

**Issue 6 and 7**
All payment request types working as QR codes: https://streamable.com/og76jn
All payment request types working as links: https://streamable.com/c3ob85

And for regression testing, eth and token sends from the wallet: https://streamable.com/tja58i

All of the above fixes were done in commit 6812589f

2020-05-08 21:15 UTC, ibrahimtaveras00 commented
**Issue 2** fixed 👍 

One thing to keep in mind @omnat @cjeria, that since we do still allow the switching of accounts **ONLY** on payment requests, there is still a chance of a user switching to an account that doesn't hold an ERC20 Token that the requester is requesting  and they can proceed with the txn.  See the flow here = http://recordit.co/cqoppARTwW
- Basically the requester is requesting 1 MANA  
- I am on Account 1 which does have MANA
- Once on Confirm view, I then switch to Account 4 which doesn't have MANA
- I then proceed with the txn

**Issue 5A:** Fixed 👍 

**Issue 5B:** Fixed although the position of the Cancel relative to the normal send flow is flopped 

Seen here:
![image](https://user-images.githubusercontent.com/41752922/81438052-200bdb00-913a-11ea-9486-a4983ee4a359.png)

**Issue 5C:** Fixed 👍  

**Issue 6:** Fixed 👍 

**Issue 7:** Fixed 👍 

**Issue 8:** 
While testing the fix, I did find an issue with InstaPay where I can only send whole number values and not anything with a decimal after 1; seen here = https://recordit.co/9PGPeI4umS

**Issue 9:**

Approval of token isn't working
Seen here:
Rinkeby = http://recordit.co/UvCCUJSNZH
Mainnet = http://recordit.co/CoiORWKd7B

**Issue 10:** 
This one is weird, it seems like all the transaction history dates are wrong (showing a future date)

Mainnet example:
![image](https://user-images.githubusercontent.com/41752922/81449923-56078a00-914f-11ea-8690-04683a194803.png)

Rinkeby example:
![image](https://user-images.githubusercontent.com/41752922/81449986-79323980-914f-11ea-9516-f74fa33a535d.png)

2020-05-08 21:45 UTC, omnat commented
Issue 2: We should do another check against the balance of the chosen account (same as we'd do for the default account that opens the payment request too). And if there's insufficient amount, we should throw the error 'insufficient funds' (and show the requested asset balance in From field), and disable Send button.

2020-05-11 15:45 UTC, danjm commented
Issue 8 fixed in ce3b3b69
Issue 9 fixed in 6c9d7def
Issue 10 fixed in a separate PR as it is also on develop: https://github.com/MetaMask/metamask-mobile/pull/1557

2020-05-11 15:47 UTC, danjm commented
I think the best improvement for the outstanding concern of issue 2 would be prevent switching to accounts with 0 tokens. However, that will require a non-trivial update to a gaba controller, so I would recommend we create a separate task for that improvement.

2020-05-11 19:59 UTC, ibrahimtaveras00 commented
**Issues 8 and 9** have been fixed 👍 

While re-testing instapay, I also decided to retest the other two deeplinks to make sure all is still well.  I found that now, tapping on and/or scanning the QR code for payment request for ETH Payment isn't working.  Note: ERC20 token transfer deeplink still works though.

Tapping link = https://recordit.co/TMTMym4odQ
Scanning code = https://recordit.co/sXsyokEdOx

Also I see **issue 2** is still outstanding as well as the button placement of **issue 5B**

2020-05-11 21:27 UTC, danjm commented
90890cf6 implements @omnat's suggestion for Issue 2 (https://github.com/MetaMask/metamask-mobile/pull/1465#issuecomment-626034631)

2020-05-11 22:56 UTC, ibrahimtaveras00 commented
In regards to Issue 2, I'm still able to switch to an account that doesn't hold that ERC20 token and tap send and continue

seen here = http://recordit.co/7U8Gt5Wy6l

In txn history I end up seeing Not Available Undefined 

![Screen Shot 2020-05-11 at 6 56 20 PM](https://user-images.githubusercontent.com/41752922/81620118-1f34ac80-93b9-11ea-8918-26f3451d67a8.png)

2020-05-11 23:29 UTC, danjm commented
Addressed navbar button position issue 5b in 218a2ca7

https://streamable.com/8wmscl

2020-05-11 23:45 UTC, danjm commented
Okay, issue 2 should be fixed for real with c47dccc4

2020-05-12 02:41 UTC, ibrahimtaveras00 commented
@danjm all fixes look good now 👍 

I did another regression on txn's just to make sure nothing else broke.  There was only 1 issue I found through my regression.

When going to instaPay via drawer, and then attempting to send a value below 1, results in the following error:

![Screen Shot 2020-05-11 at 10 40 29 PM](https://user-images.githubusercontent.com/41752922/81632514-7c8c2600-93d8-11ea-9f29-8251f48fc01d.png)

flow seen here = https://recordit.co/nR7RdRNiQG

All other flows looked good.

2020-05-12 03:01 UTC, estebanmino commented on app/components/Nav/Main/index.js
> +				logo: 'dai.svg',
I think we should use `sai.svg` for https://github.com/MetaMask/eth-contract-metadata/blob/master/images/sai.svg

2020-05-12 03:03 UTC, estebanmino commented on app/components/Nav/Main/index.js
> +		PaymentChannelsClient.hub.on('state::change', this.onPaymentChannelStateChange);
what is this for?

2020-05-12 03:07 UTC, estebanmino commented on app/components/Views/PaymentChannel/index.js
>  			logo: 'dai.svg',
hu I see the old logo here, not sure which one to use now

2020-05-12 10:04 UTC, danjm commented
Fix the issue with sending DAI and SAI < 1 via instapay in 393e251a

2020-05-12 14:21 UTC, danjm commented on app/components/Views/PaymentChannel/index.js
>  			logo: 'dai.svg',
Probably 'sai.svg'. It probably should have been changed here: https://github.com/MetaMask/metamask-mobile/pull/1198/files#diff-5fcafd423a73d3bea2411bdfac37267dL470

2020-05-12 14:32 UTC, danjm commented on app/components/Nav/Main/index.js
> +		PaymentChannelsClient.hub.on('state::change', this.onPaymentChannelStateChange);
When we get a `'payment::request'` event (below), we end up calling `this.initiatePaymentChannelRequest`.

`this.initiatePaymentChannelRequest` calls `setTransactionObject` to set the transaction state of the payment channel request, and then navigates to the confirm screen. To ensure the balance of the payment channel is available when we get to the confirm screen, we pass it as the `assetBalance` property.

This listener gets that balance when it becomes available on the first state event from the `PaymentChannelsClient`.

2020-05-12 17:16 UTC, estebanmino commented on app/components/Nav/Main/index.js
> +		PaymentChannelsClient.hub.on('state::change', this.onPaymentChannelStateChange);
cool I think it makes sense, `PaymentChannelsClient` is polling every 5 seconds I believe, emitting `state::change`, so I'm worried about performance

2020-05-12 17:43 UTC, danjm reviewed
@estebanmino I've made some comments that explain the reason for the various code changes. I hope it all makes sense, and please ask any questions. Please do let me know if you think any of it was unnecessary or could have been done in a simpler way.

2020-05-12 17:43 UTC, danjm commented on app/actions/transaction/index.js
> +
Code changes here, except for the function added at very bottom, are just copy and pastes of the code that was in `app/actions/newTransaction/index.js`

This was done to combined the `transaction` and `newTransaction` states, as suggested in [this comment](https://github.com/MetaMask/metamask-mobile/pull/1465#discussion_r415935541)

2020-05-12 17:43 UTC, danjm commented on app/actions/transaction/index.js
> + */
This is not used and can be removed.

2020-05-12 17:43 UTC, danjm commented on app/components/Nav/Main/index.js
>  		/**
The majority of changes in this file are needed to properly handling payment channel requests and direct them to the existing confirm screen.

2020-05-12 17:43 UTC, danjm commented on app/components/Nav/Main/index.js
> +					{!forceReload ? (
These changes allow us to customize the navbar if we are handling payment channel transactions or editing payment requests.

2020-05-12 17:43 UTC, danjm commented on app/components/UI/AccountList/AccountElement/index.js
>  		paddingVertical: 20,
The changes in this file give the user additional information when attempting to switch accounts on the confirm screen, which is an addition that is new with this PR, possible when editing deep link / QR code transactions. Same for the `AccountList` component.

2020-05-12 17:43 UTC, danjm commented on app/components/UI/TransactionEditor/index.js
> +	transaction: getNormalizedTxState(state)
`getNormalizedTxState` is needed so that we can use what was previously called the `newTransaction` state (renamed to just `transaction` in this PR because we combined the two parts of state) without making too many changes to state handling within the components. `getNormalizedTxState` copies the properties of `newTransaction.transaction` to be root properties as well. This allows us to reference, for example, both `this.props.transaction.value` and `this.props.transaction.transaction.value`.

Eventually we will want to standardize how all components use their `transaction` props, but this is an intermediary step to reduce the amount of refactoring in this PR.

2020-05-12 17:43 UTC, danjm commented on app/actions/transaction/index.js
> +
Along with a similar combination of the reducer files, these changes cause file and property remaining throughout the PR.

2020-05-12 17:43 UTC, danjm commented on app/reducers/transaction/index.js
>  import { REHYDRATE } from 'redux-persist';
Code changes here are just copy and pastes of the reducers that were in in `app/reducers/newTransaction/index.js` and not in this file.

This was done to combined the `transaction` and `newTransaction` states, as suggested in this comment

Along with a similar combination of the action files, these changes cause file and property remaining throughout the PR.

2020-05-12 17:43 UTC, danjm commented on app/components/Views/Send/index.js
> +		const { addressBook, network, identities, selectedAddress } = this.props;
The changes in this `handleNewTxMeta` method are needed to properly set state of deep link transactions for the `Confirm` screen, that is coupled to the object schema that used to be called `newTransaction`.

2020-05-12 17:43 UTC, danjm commented on app/components/Views/Send/index.js
> +		if (this.state.mode === EDIT) {
The changes in this method and the render method allow us to use the existing `Amount` and `Confirm` views for deeplink / QR code transactions.

2020-05-12 17:43 UTC, danjm commented on app/components/Views/SendFlow/Amount/index.js
>  } from 'react-native';
The changes in this file allow us to use the existing `Amount` view component to edit the amounts of payment channel and payment request transactions.

2020-05-12 17:43 UTC, danjm commented on app/components/Views/SendFlow/Confirm/index.js
> +		const {
These `componentDidUpdate` changes are need to show proper error messages when changing accounts (a new feature added for payment request transactions in this PR).

2020-05-12 17:43 UTC, danjm commented on app/components/Views/SendFlow/Confirm/index.js
>  			transactionState: {
`parseTransactionData` has been updated to handle payment channel transactions, and to ensure that the balance / amount is validated on component mount and update.

2020-05-12 17:43 UTC, danjm commented on app/components/Views/SendFlow/Confirm/index.js
> +		const {
Validation of amount is now needed on this screen because editing of tx from can now be done from this screen (now that it supports payment requests).

2020-05-12 17:43 UTC, danjm commented on app/components/Views/SendFlow/Confirm/index.js
> +		this.setState({ transactionConfirmed: true });
This send method is needed for payment channel transactions.

2020-05-12 17:43 UTC, danjm commented on app/components/Views/SendFlow/Confirm/index.js
>  		const {
This and other methods added below but before render support the account switching functionality.

2020-05-12 17:43 UTC, danjm commented on app/components/Views/SendFlow/SendTo/index.js
>  import { isValidAddress, toChecksumAddress } from 'ethereumjs-util';
Changes in this file allow the first screen of the standard send flow to be used for payment channel transactions created within metamask-mobile

2020-05-12 17:43 UTC, danjm commented on app/components/Views/TransactionSummary/index.js
>  import React, { PureComponent } from 'react';
Changes here accomodate the design changes shown in this comment https://github.com/MetaMask/metamask-mobile/pull/1465#issuecomment-607499051

2020-05-12 17:57 UTC, danjm commented on app/components/Nav/Main/index.js
> +		PaymentChannelsClient.hub.on('state::change', this.onPaymentChannelStateChange);
The `setState` call in `this.onPaymentChannelStateChange` is only called once because of the `paymentChannelReady` state property. So I don't think there will a performance impact.

2020-05-12 18:58 UTC, ibrahimtaveras00 approved these changes
All fixes look good on both OS's, QA Passed 👍

2020-05-12 20:57 UTC, merged