Transaction Header Component
MetaMask/metamask-mobile pull request #1487
Opened 2020-04-11 05:57 UTC by EtDu

**Description**

Break out `renderPageContent` inside of `SignatureRequest` and create it's own component, `TransactionHeader`

**Checklist**

- [ ] Remove `renderPageContent`
- [ ] Create `TransactionHeader` component
- [ ] Show lock or warning icon based on protocol (`http` vs `https`)
- [ ] Show network status circle, color green if network is active, red if not
- [ ] Add function name, appears if it exists, otherwise not

**Issue**

fixes #1484

2020-04-11 06:01 UTC, EtDu commented
Does anyone know where I can find the `function` as per the design? I.E. `Confirm: Eth to Token Swap`

2020-04-14 01:01 UTC, danjm requested changes
Overall this looks really good. Made a few nitpick comments on small improvements that can be made to code structure, but otherwise this looks good for QA.

2020-04-14 01:01 UTC, danjm commented on app/components/UI/TransactionHeader/index.js
> +		const network = this.getTrackingParams().network;
I think I would say the same for the `secureIcon` logic and image component.

2020-04-14 02:30 UTC, danjm approved these changes

2020-04-14 17:40 UTC, estebanmino requested changes
Left some comments on the issue tracking this PR, related to the icons added here for @cjeria

2020-04-14 17:40 UTC, estebanmino commented on app/components/UI/TransactionHeader/index.js
> +		const network = this.getTrackingParams().network;
I'd use `network` coming directly from `props`. On this component you're calling `getTrackingParams` three times and creating an object that's already coming from 'props', any particular reason for doing this?

2020-04-14 17:40 UTC, estebanmino commented on app/components/UI/TransactionHeader/index.js
> +		const networkStatusIndicatorColor = this.getTrackingParams().status[network] === 'ok' ? 'green' : 'red';
I'd use`status` coming directly from props

2020-04-14 17:40 UTC, estebanmino commented on app/components/UI/TransactionHeader/index.js
> +					<Text style={styles.network}>{this.getTrackingParams().network}</Text>
I'd use`networkType` coming directly from props

2020-04-14 22:16 UTC, estebanmino commented
@EtDu  https://github.com/MetaMask/metamask-mobile/issues/1484#issuecomment-613681782

2020-04-15 05:07 UTC, EtDu commented on app/components/UI/TransactionHeader/index.js
> +					<Text style={styles.network}>{this.getTrackingParams().network}</Text>
`getTrackingParams()` already existed in `SignatureRequest`, so I kept it just in case that was there for a special reason. 

Removed in updated commit.

2020-04-15 05:19 UTC, EtDu commented
@estebanmino 
Removed getTrackingParams and updated the icons

2020-04-15 05:33 UTC, EtDu commented
<img width="177" alt="Screen Shot 2020-04-15 at 1 32 37 PM" src="https://user-images.githubusercontent.com/26778340/79302023-a8250900-7f1d-11ea-8f0c-e50244a159e8.png">
<img width="160" alt="Screen Shot 2020-04-15 at 1 29 45 PM" src="https://user-images.githubusercontent.com/26778340/79302027-a9eecc80-7f1d-11ea-8309-63404f85857d.png">

Screenshots for reference

2020-04-15 15:05 UTC, cjeria commented
@EtDu Regarding network names, the suggestion was to use the name of the network e.g. Ethereum, Ropsten, Rinkeby, etc. I notice in your screenshot above you have "Mainnet". I don't believe this is descriptive enough. I'd suggest using the names. @omnat @rachelcope WDYT?

2020-04-15 20:34 UTC, estebanmino commented
@EtDu `getTrackingParams` are used for analytics, I can imagine this is not breaking that right?

2020-04-16 00:08 UTC, EtDu commented
> @EtDu `getTrackingParams` are used for analytics, I can imagine this is not breaking that right?

I don't think so, I left it alone where it was originally created in `SignatureRequest/index`

2020-04-16 01:55 UTC, EtDu commented
> @EtDu Regarding network names, the suggestion was to use the name of the network e.g. **Ethereum**, **Ropsten**, **Rinkeby**, etc. I notice in your screenshot above you have "Mainnet". I don't believe this is descriptive enough. I'd suggest using network names instead. @omnat @rachelcope WDYT?

<img width="174" alt="Screen Shot 2020-04-16 at 9 53 54 AM" src="https://user-images.githubusercontent.com/26778340/79405984-6a30ef00-7fc8-11ea-971b-1bdcb0ef880f.png">

@cjeria Updated!

2020-04-16 20:56 UTC, estebanmino requested changes

2020-04-16 20:56 UTC, estebanmino commented on app/components/UI/TransactionHeader/index.js
> +					<Text style={styles.network}>{networkType === 'mainnet' ? 'Ethereum' : networkType}</Text>
I'd use https://github.com/MetaMask/metamask-mobile/blob/develop/app/util/networks.js
You can add a new entry there for each network as `shortName` for example
```
ropsten: {
		name: 'Ropsten Test Network',
        shortName: 'Ropsten',
		networkId: 3,
		chainId: 3,
		color: '#ff4a8d'
	},
```
and then do something like 
`Networks[networkType].shortName` to not hardcode the name here, including rpc networks

2020-04-17 01:41 UTC, EtDu commented on app/components/UI/TransactionHeader/index.js
> +					<Text style={styles.network}>{networkType === 'mainnet' ? 'Ethereum' : networkType}</Text>
Done!

2020-04-22 18:37 UTC, estebanmino approved these changes
LGTM! now we need QA @ibrahimtaveras00

2020-04-29 22:26 UTC, ibrahimtaveras00 approved these changes
Looks good on both OS's, QA Passed 👍

2020-05-05 21:57 UTC, merged