Sig request design fixed
MetaMask/metamask-mobile pull request #1493
Opened 2020-04-16 15:07 UTC by EtDu

**Description**

Implement new signature request screen designs

**Checklist**

- [x] Create `AccountInfoCard` component
- [x] SignatureRequest: use AccountInfoCard
- [x] SignatureRequest: remove scrollview
- [x] ActionView: remove scrollview if rendered by message, typed or personal sign components (isSigning = true)
- [x] TypedSign (V1, V3, V4): Ensure message content fits within the box (no overflow)
- [x] MessageSign: Ensure message content fits within the box (no overflow)
- [x] PersonalSign: Ensure message content fits within the box (no overflow)
- [x] Ensure arrow icon only renders if content is clipped
- [x] SignatureRequest: tap on children (message box) to expand and reveal the full message
- [x] SignatureRequest: tap on the top left arrow to go back (collapsing full message)
- [x] MessageSign: add new warning message 

**Issue**

Resolves #1488

2020-04-16 15:15 UTC, EtDu commented
<img width="351" alt="Screen Shot 2020-04-16 at 11 12 34 PM" src="https://user-images.githubusercontent.com/26778340/79473663-09d99600-8038-11ea-9daf-705e420e44d4.png">

@cjeria What do you think? This is with typed data signing.

2020-04-16 21:00 UTC, cjeria commented
@EtDu Does the style of the data change per the data type (string vs type data)? For instance, if the message is a string (like the cryptokitties example below), does the style of the message font change?

If so, I'm inclined to suggest styling `type data` messages like code blocks and strings like the example below.

<img src="https://user-images.githubusercontent.com/597770/79506015-4b038300-8003-11ea-89b0-27a47626e68d.png" width="450">

Also, note that the arrow symbol ">" (indicating the message can be expanded) is only intended for very long messages that don't fit inside the container.

2020-04-17 13:50 UTC, EtDu commented
<img width="351" alt="Screen Shot 2020-04-17 at 9 48 03 PM" src="https://user-images.githubusercontent.com/26778340/79576067-4919ec80-80f5-11ea-87a8-22352000b610.png">

CryptoKitties example with a regular message

2020-04-20 12:50 UTC, EtDu commented
<img width="392" alt="Screen Shot 2020-04-20 at 8 45 51 PM" src="https://user-images.githubusercontent.com/26778340/79753398-727e8680-8348-11ea-927a-055461c75d3e.png">
eth_sign message sign

2020-04-21 09:36 UTC, danjm requested changes
Nice work. Left some minor comments and questions.

2020-04-21 09:36 UTC, danjm commented on app/components/UI/StyledButton/styledButtonStyles.js
> +		backgroundColor: colors.blue,
The changes in this file will affect 'normal' type buttons across the app. Was this requested by design?

2020-04-21 09:36 UTC, danjm commented on app/components/UI/ActionView/index.js
> +			{isSigning ? (
Nit: a variable name that is more general than `isSigning` would more accurately reflect the general purpose use of `ActionView`.

`noScroll` would be an option

2020-04-21 09:36 UTC, danjm commented on app/components/UI/ActionView/index.js
> +	/**
See above comment on suggested variable name change. The comment here could then be more generalized as well.

2020-04-21 09:36 UTC, danjm commented on app/components/UI/MessageSign/index.js
> -export default class MessageSign extends PureComponent {
Why the change from `PureComponent` to `React.Component`?

2020-04-21 09:38 UTC, danjm commented
I'll do final review once unit tests are passing and we get design approval. I'll also do a QA pass as Ibrahim is mostly out this week.

2020-04-22 02:06 UTC, EtDu commented on app/components/UI/StyledButton/styledButtonStyles.js
> +		backgroundColor: colors.blue,
Hmm I made the assumption. Perhaps I shouldn't have.

2020-04-22 02:42 UTC, EtDu commented on app/components/UI/ActionView/index.js
> +	/**
This one was there already

2020-04-22 02:42 UTC, EtDu commented on app/components/UI/MessageSign/index.js
> -export default class MessageSign extends PureComponent {
Now the signing components have state

2020-04-22 16:48 UTC, danjm commented on app/components/UI/MessageSign/index.js
> -export default class MessageSign extends PureComponent {
oh, right

2020-04-22 18:41 UTC, estebanmino commented on app/components/UI/AccountInfoCard/index.js
> +						{strings('signature_request.balance_title')} ${dollarBalance} ({balance} {strings('unit.eth')})
my guess is that here we're not using the proper format for fiat balance, we have a method to handle that called `weiToFiat`

2020-04-22 18:43 UTC, estebanmino commented on app/components/UI/ActionView/index.js
> +	keyboardShouldPersistTaps = 'never',
what's the purpose of this? I remember being debugging some problems for `ActionView`s that are using this in order to work

2020-04-22 18:46 UTC, estebanmino commented on app/components/UI/MessageSign/index.js
> -export default class MessageSign extends PureComponent {
you can have `PureComponents` with state (in fact all of our components with state are PureComponents), this is a performance improvement we did while ago, could you change it back?

2020-04-22 18:48 UTC, estebanmino commented on app/components/UI/PersonalSign/index.js
> +export default class PersonalSign extends React.Component {
same about `PureComponent`

2020-04-22 18:50 UTC, estebanmino commented on app/components/UI/PersonalSign/index.js
> +		return this.renderRootView();
why don't just add that method content on `render`

2020-04-22 18:54 UTC, estebanmino commented on app/components/UI/SignatureRequest/index.js
> +		const arrowIcon = shouldRenderArrow ? this.renderArrowIcon() : null;
am I missing the definition of `renderArrowIcon` ?

2020-04-22 18:56 UTC, estebanmino commented on app/components/UI/SignatureRequest/index.js
> +					noScroll
seems like this is removing the ability to scroll? we have to keep in mind that there are smaller devices that needs this to see the whole view

2020-04-22 18:56 UTC, estebanmino commented on app/components/UI/TypedSign/index.js
> +export default class TypedSign extends React.Component {
same about `PureComponent`

2020-04-22 18:58 UTC, estebanmino commented on app/components/UI/ActionView/index.js
> +	noScroll
what's the purpose to block the abiolity to scroll? we have to support smaller devices that without this could not be able to display all the information we may need to

2020-04-22 19:00 UTC, estebanmino requested changes
left some comments. @danjm I'd wait for @ibrahimtaveras00 to do QA he can build the app on both IOS and Android devices

2020-04-22 19:01 UTC, estebanmino commented
I'm also worried about the task `SignatureRequest: remove scrollview` I believe we need that for smaller devices but @ibrahimtaveras00 can take a look that

2020-04-23 00:32 UTC, EtDu commented on app/components/UI/ActionView/index.js
> +	keyboardShouldPersistTaps = 'never',
I don't know why this is showing up in the diff, this wasn't my work so I'm not sure

2020-04-23 00:34 UTC, EtDu commented on app/components/UI/MessageSign/index.js
> -export default class MessageSign extends PureComponent {
You're right, misunderstanding on my part, I'll change it back

2020-04-23 01:35 UTC, EtDu commented on app/components/UI/AccountInfoCard/index.js
> +						{strings('signature_request.balance_title')} ${dollarBalance} ({balance} {strings('unit.eth')})
Noted!

2020-04-23 01:37 UTC, EtDu commented on app/components/UI/PersonalSign/index.js
> +		return this.renderRootView();
Okay, makes sense

2020-04-23 01:44 UTC, EtDu commented on app/components/UI/SignatureRequest/index.js
> +		const arrowIcon = shouldRenderArrow ? this.renderArrowIcon() : null;
It is directly below `renderActionViewChildren`

2020-04-23 01:47 UTC, EtDu commented
> I'm also worried about the task `SignatureRequest: remove scrollview` I believe we need that for smaller devices but @ibrahimtaveras00 can take a look that

@estebanmino  The reasoning for this was because of the new design. Instead of scrolling on the signature request screen, the user would tap the message to expand it, where they can scroll there if necessary

2020-04-23 01:48 UTC, EtDu commented on app/components/UI/ActionView/index.js
> +	noScroll
below comment

2020-04-23 01:48 UTC, EtDu commented on app/components/UI/TypedSign/index.js
> +export default class TypedSign extends React.Component {
resolved

2020-04-23 01:48 UTC, EtDu commented on app/components/UI/SignatureRequest/index.js
> +					noScroll
below comment

2020-04-24 05:10 UTC, EtDu commented
<img width="399" alt="Screen Shot 2020-04-24 at 11 35 35 AM" src="https://user-images.githubusercontent.com/26778340/80177007-f1b3d900-862c-11ea-9aaf-c9f9bce334d2.png">
@cjeria

2020-04-27 04:47 UTC, EtDu commented
<img width="395" alt="Screen Shot 2020-04-27 at 12 46 30 PM" src="https://user-images.githubusercontent.com/26778340/80334899-2f12a380-8885-11ea-965b-36b21d5aaeaf.png">

with `AccountInfoCard` ontop

2020-04-27 22:59 UTC, estebanmino approved these changes
LGTM!

2020-04-29 23:29 UTC, ibrahimtaveras00 commented
There are quite a few screen sizes that don't play well with the new design: 

![image](https://user-images.githubusercontent.com/41752922/80656643-aeec6980-8a4f-11ea-962b-466ade456ba2.png)

2020-04-30 02:58 UTC, EtDu commented
@ibrahimtaveras00 Thank you for the feedback, I'll get it fixed

2020-05-05 12:47 UTC, EtDu commented
@ibrahimtaveras00 Fixed all of the above! Also, Android native back button takes you back to "Sign this message"

2020-05-05 22:25 UTC, estebanmino requested changes

2020-05-05 22:25 UTC, estebanmino commented on app/components/UI/AccountInfoCard/index.js
> +							{strings('unit.eth')})
users can change the ticker of networks so can we use https://github.com/MetaMask/metamask-mobile/blob/develop/app/components/UI/AccountSelect/index.js#L179 ?

2020-05-05 22:25 UTC, estebanmino commented on app/components/UI/PersonalSign/index.js
> +		marginBottom: 5
I'm almost sure 5 is not a number we use for margins and borders, are we sure about it?

2020-05-05 22:25 UTC, estebanmino commented on app/components/UI/SignatureRequest/index.js
> +		} else if (type === 'ethSign' && Device.getDeviceHeight() >= 736) {
where is 736 coming from? we have an util file that can help you with this https://github.com/MetaMask/metamask-mobile/blob/develop/app/util/Device.js

2020-05-05 22:25 UTC, estebanmino commented on app/components/UI/StyledButton/styledButtonStyles.js
> +		color: colors.blue
this is changing all the cancel buttons we have in the app... is that the purpose of this?

2020-05-05 22:25 UTC, estebanmino commented on app/components/Nav/Main/index.js
> +				onBackButtonPress={showExpandedMessage ? this.toggleExpandedMessage : this.onSignAction}
this feels strange to me, having a state variable from /Main to change stuff inside a component. Did you try to use https://reactnative.dev/docs/backhandler to handle the back button on these modals?

2020-05-06 04:55 UTC, ibrahimtaveras00 commented
Issues 1 and 2 have been fixed!

**Issue 3:**

However, I'm noticing that we no longer show the balance in the accountInfoCard how it appears in the design mockups; is that intentional?  I wasn't sure if we should only show it for sign message v2, but currently it's not showing for any sign type.  

![Screen Shot 2020-05-06 at 12 34 06 AM](https://user-images.githubusercontent.com/41752922/81139543-1ca70280-8f34-11ea-8d7c-2eed561ad366.png)

![Screen Shot 2020-05-06 at 12 52 27 AM](https://user-images.githubusercontent.com/41752922/81139548-216bb680-8f34-11ea-8b22-b1ce616b7f7c.png)


**Issue 4:**

For some reason, I'm unable to bring up the sign modal for sign typed data v4 on the bottom of this page https://danfinlay.github.io/js-eth-personal-sign-examples/ 

seen here = https://recordit.co/AyTlC6gYdL

![Screen Shot 2020-05-06 at 12 48 08 AM](https://user-images.githubusercontent.com/41752922/81139538-157ff480-8f34-11ea-9a99-0cd05a6d0cec.png)

2020-05-06 09:05 UTC, EtDu commented on app/components/Nav/Main/index.js
> +				onBackButtonPress={showExpandedMessage ? this.toggleExpandedMessage : this.onSignAction}
Yes, but when a Modal is open `BackHandler` doesn't publish any events. Modal has the `onRequestClose` prop for this very purpose. Since we're using a wrapped version of the native `Modal`, it's `onBackButtonPress`.  Since the Modal is at the top of the view hierarchy for signing operations, I wasn't sure how else to implement this.

2020-05-06 09:42 UTC, EtDu commented on app/components/UI/AccountInfoCard/index.js
> +							{strings('unit.eth')})
done

2020-05-06 09:42 UTC, EtDu commented on app/components/UI/PersonalSign/index.js
> +		marginBottom: 5
changed to 4

2020-05-06 09:43 UTC, EtDu commented on app/components/UI/SignatureRequest/index.js
> +		} else if (type === 'ethSign' && Device.getDeviceHeight() >= 736) {
736 is the height of iPhone 8+/7+. Added new helper to `Device`

2020-05-06 11:22 UTC, EtDu commented on app/components/UI/StyledButton/styledButtonStyles.js
> +		color: colors.blue
Not sure, so just made a new button type for signing components

2020-05-06 12:10 UTC, EtDu commented
@ibrahimtaveras00 Issue #3 is intentional as of recently, but only for the signing components. Issue #4 doesn't appear to be related to this PR (also present on `develop`). I've opened #1551 to address it. 

To anyone: In the case I'm missing something and this is intentional, please close the issue

2020-05-06 16:45 UTC, ibrahimtaveras00 approved these changes
Fixes look good on both OS's, QA passed 👍

2020-05-06 17:51 UTC, estebanmino commented on app/components/UI/StyledButton/styledButtonStyles.js
> +		color: colors.blue
we need to change it, can you create a new style? This is changing all the cancel button styles

2020-05-06 18:02 UTC, estebanmino commented on app/components/UI/StyledButton/styledButtonStyles.js
> +		color: colors.blue
you can use `info` style https://github.com/MetaMask/metamask-mobile/pull/1493/files/c4b8407d87ddb76adb061c24d4a1cc4ac0ac2b54#diff-ff2e6a58d18583289e9404b4a668ecc5R149 for that button and make `cancelText` with color `grey400` again

2020-05-06 20:05 UTC, estebanmino commented on app/components/UI/StyledButton/styledButtonStyles.js
> +		color: colors.blue
@EtDu I talked with @cjeria about this, we're going with grey400 as the color for cancel buttons so we need to update it

2020-05-06 20:07 UTC, estebanmino commented on app/components/UI/StyledButton/styledButtonStyles.js
> +		color: colors.blue
this is the button style we should use https://github.com/MetaMask/metamask-mobile/blob/develop/app/components/UI/StyledButton/styledButtonStyles.js#L121

2020-05-07 03:36 UTC, EtDu commented on app/components/UI/StyledButton/styledButtonStyles.js
> +		color: colors.blue
I already created a new style `signingCancel` is that ok?

2020-05-07 13:01 UTC, EtDu commented
Okay I've rebased and switched the compare branch to `develop`. Anything else before merge?

2020-05-07 16:24 UTC, estebanmino approved these changes

2020-05-07 16:46 UTC, danjm approved these changes
LGTM

2020-05-07 16:49 UTC, merged