Feature/block screenshots
MetaMask/metamask-mobile pull request #1495
Opened 2020-04-17 23:33 UTC by estebanmino

**Description**

The only thing left is to add the methods where we want to block screenshots

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #

2020-04-23 14:51 UTC, andrepimenta requested changes
If this is not implemented on iOS, then the respective NativeModule is not available right? This should be checked, otherwise will crash on iOS.

Also, it seems that there is no prevention for other apps to record screen, for example. Is it not possible?

Otherwise, looking good! 👍

2020-04-23 14:51 UTC, andrepimenta commented on app/components/Views/ImportPrivateKeySuccess/index.js
> +	componentWillUnmount = async () => {
`async` should not be necessary?

2020-04-23 14:51 UTC, andrepimenta commented on app/components/Views/Wallet/index.js
> +	componentDidMount = async () => {
`async` should not be necessary?

2020-04-23 14:51 UTC, andrepimenta commented on app/components/Views/RevealPrivateCredential/index.js
> +	componentWillUnmount = async () => {
`async` should not be necessary?

2020-04-23 22:05 UTC, estebanmino commented
@andrepimenta  good call on iOS 👌

2020-04-27 19:16 UTC, estebanmino commented
@andrepimenta all good now, added a check for iOS. Regarding the screen recording, I added the `FLAG_SECURE` flag that blocks screenshots and recording ([related link](https://developer.android.com/reference/android/view/Display?authuser=2#FLAG_SECURE))

2020-04-28 16:24 UTC, ibrahimtaveras00 commented
**This works on Android on the following views:**
- import seed phrase
- security & privacy > "SHOW PRIVATE KEY"
- security & privacy > "REVEAL SEED PHRASE"

showing this message on my pixel 2 
![image](https://user-images.githubusercontent.com/41752922/80512057-f6d59880-894a-11ea-913d-9c20ca603772.png)

**Few places where this doesn't work:**
- on the "secure your wallet" flow after creating your password and then navigating to the "Your seed phrase" view 
- on the import account view when adding the private key

2020-04-29 14:37 UTC, andrepimenta commented
@estebanmino We should consider creating a service or helper called, for example, `PreventScreenshot` that implements empty functions for iOS, so that we don't have to duplicate code like this:
`const PreventScreenshot = Platform.OS === 'android' ? NativeModules.PreventScreenshot : null;` and `PreventScreenshot && PreventScreenshot.forbid();`

A possible implementation could be
PreventScreenshot.js
`
import { NativeModules } from react-native

const isAndroid = Platform.OS === 'android' 
export default {
forbid: isAndroid ? () => NativeModules.PreventScreenshot.forbid() : () => {},
allow: isAndroid ? () => NativeModules.PreventScreenshot.allow() : () => {}
}
`

What do you think?

2020-04-30 15:02 UTC, estebanmino commented
@andrepimenta @ibrahimtaveras00 issues addressed 👌

2020-04-30 15:45 UTC, andrepimenta approved these changes
Great! Looks good to me 👌

2020-05-05 21:10 UTC, ibrahimtaveras00 approved these changes
Fixes look good on Android, QA Passed 👍

2020-05-05 22:30 UTC, merged

2020-05-07 17:42 UTC, omnat commented
In the latest, on iOS, I could still take screenshots on these flows:
- reveal seedphrase
- during the backup flow

From my understanding, we can not prevent the user on iOS on taking a screenshot (unlike on Android), but we can show them a "taking a screenshot is not safe to do.."