Transaction components
MetaMask/metamask-mobile pull request #1512
Opened 2020-04-27 03:47 UTC by EtDu

**Description**

Create components for transactions created from dApps redesign. #1501 

**Checklist**

- [ ] Create `TransactionReviewFeeCard` component
- [ ] `Confirm`: Use `TransactionReviewFeeCard`
- [ ] Create new data modal
- [ ] `Approve`: Use the data modal
- [ ] `CustomGas`: implement custom gas modal redesign

**Issue**

Resolves #1497
Resolves #1499 
Resolves #1500

2020-04-27 04:01 UTC, EtDu commented
<img width="322" alt="Screen Shot 2020-04-27 at 11 59 56 AM" src="https://user-images.githubusercontent.com/26778340/80332869-b4468a00-887e-11ea-983b-5576d6b6757d.png">
primaryCurrency = FIAT

<img width="321" alt="Screen Shot 2020-04-27 at 11 59 25 AM" src="https://user-images.githubusercontent.com/26778340/80332900-cb857780-887e-11ea-99dc-fbd6116f3e94.png">
primaryCurrency = ETH

@cjeria is this what you had in mind?

2020-04-29 05:59 UTC, EtDu commented
<img width="393" alt="Screen Shot 2020-04-29 at 1 52 53 PM" src="https://user-images.githubusercontent.com/26778340/80564812-746bd800-8a21-11ea-9e44-065390cc58bc.png">

Basic network fee selection

2020-05-11 18:47 UTC, estebanmino commented on app/components/Views/SendFlow/CustomGas/index.js
> +	radio: {}
I think you can remove this

2020-05-11 18:49 UTC, estebanmino commented on app/components/Views/SendFlow/CustomGas/index.js
> +		if ((warningGasLimit && warningGasPrice) || warningGasPrice) {
isn't this equivalent to `if (warningGasPrice)` ?

2020-05-11 18:51 UTC, estebanmino commented on app/components/Views/SendFlow/CustomGas/index.js
> +				<View style={[styles.warningTextWrapper, !gasError ? styles.invisible : null]}>
what about not returning any component if there's no error? I don't know if this is using space on the view even though is rendering nothing

2020-05-11 18:52 UTC, estebanmino reviewed
added small comments, looks good!

2020-05-13 09:20 UTC, EtDu commented on app/components/Views/SendFlow/CustomGas/index.js
> +	radio: {}
missed that, I wonder if the linter could pick up on empty styles

2020-05-13 09:22 UTC, EtDu commented on app/components/Views/SendFlow/CustomGas/index.js
> +		if ((warningGasLimit && warningGasPrice) || warningGasPrice) {
Yes, double logic at its finest

2020-05-13 09:25 UTC, EtDu commented on app/components/Views/SendFlow/CustomGas/index.js
> +				<View style={[styles.warningTextWrapper, !gasError ? styles.invisible : null]}>
It is using space on the view on purpose, that's why I hide and show it with `opacity: 0`. If it doesn't initially take space, then when the error appears it will push everything else upward- which doesn't look good. 

Let me know however if this is the desired effect

2020-05-26 20:29 UTC, estebanmino commented on app/components/Views/SendFlow/Confirm/index.js
> +			<Modal
I wonder why you didn't use `ActionModal` here, you can disable the cancel button if you want and add a style prop there to put it on the bottom of the screen. In terms of reusability of components, now if we change the color of these models, we'll have to change this one separately from the others.
Same comment for https://github.com/MetaMask/metamask-mobile/pull/1512/files#diff-1d09ed350c73498ec258583166d70e87R461

2020-05-26 20:29 UTC, estebanmino commented on app/components/Views/SendFlow/Confirm/index.js
> +			<Modal
I mean is working and already approved, but I think we can reuse things here

2020-05-28 11:05 UTC, EtDu commented on app/components/Views/SendFlow/Confirm/index.js
> +			<Modal
Cool, resolved

2020-06-05 02:25 UTC, ibrahimtaveras00 requested changes
Overall this looks and feels pretty solid across both OS's and multiple screen sizes! 

Only noticed two issues:

**Issue 1:**

When I edit network fee and go to advanced, I'm still able to tap save when I do not have anything entered in the gas limit input field

seen here = https://recordit.co/3sK3vd9Jt5

![Screen Shot 2020-06-04 at 10 16 37 PM](https://user-images.githubusercontent.com/41752922/83829537-1762e200-a6b1-11ea-9466-b81a9c10e105.png)

When I tap send, I then get the error

![Screen Shot 2020-06-04 at 10 18 00 PM](https://user-images.githubusercontent.com/41752922/83829629-49744400-a6b1-11ea-903f-1aac3713faa8.png)

**Issue 2:** 

Continuing from issue one, when I get into this state and click Edit again and attempt to change to either slow/average/fast and tap save, the advanced section doesn't update thus I still have a network fee of $0.00.  Is the value supposed to update after saving gas speed? 

Seen here = https://recordit.co/c2F2d2tvA4

I'm sure the fix for one will ultimately fix issue 2 as they're related.

2020-06-05 21:22 UTC, ibrahimtaveras00 approved these changes
Fix looks good on both OS's, QA Passed 👍

2020-06-09 03:58 UTC, estebanmino approved these changes
🚀

2020-06-09 05:25 UTC, merged