[WIP] Bugfix/choose password lockout
MetaMask/metamask-mobile pull request #1550
Opened 2020-05-05 19:47 UTC by estebanmino

**Description**

I couldn't reproduce the issue directly but I can imagine how it was failing

When users call `login` from the view on the issue we're calling https://github.com/MetaMask/metamask-mobile/blob/develop/app/components/Views/Onboarding/index.js#L108 that's asking for a variable set on state, `passwordSet`

This variable is being set when a password is set or not, in this case we were doing it here https://github.com/MetaMask/metamask-mobile/compare/bugfix/choose-password-lockout?expand=1#diff-05500d00f4a6959745b57a220987a4b6L269 way after we really set the password on the keyring to create a new vault https://github.com/MetaMask/metamask-mobile/compare/bugfix/choose-password-lockout?expand=1#diff-05500d00f4a6959745b57a220987a4b6L244 or https://github.com/MetaMask/metamask-mobile/compare/bugfix/choose-password-lockout?expand=1#diff-05500d00f4a6959745b57a220987a4b6L255 so if something failed between that we could reach a state when the password is set on the keyring but the app wouldn't know because `passwordSet` would be still false.

The fix sets that var to true before anything happens here https://github.com/MetaMask/metamask-mobile/compare/bugfix/choose-password-lockout?expand=1#diff-05500d00f4a6959745b57a220987a4b6R216 and then sets it to false if something failed we recreate the same vault again with no password

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves https://github.com/MetaMask/metamask-mobile/issues/1532

2020-05-08 10:54 UTC, andrepimenta requested changes
The logic makes sense to me!

Could you just remove the console.logs? 🙏

2020-05-08 19:11 UTC, danjm approved these changes
There are some console.logs in here that can probably be removed. But this looks like a good solution to the problem, as explained in the PR description.

2020-05-26 23:18 UTC, ibrahimtaveras00 approved these changes
QA Passed 👍

2020-05-27 17:44 UTC, andrepimenta approved these changes

2020-05-27 19:25 UTC, merged