Complete redesigns for approval flow
MetaMask/metamask-mobile pull request #1558
Opened 2020-05-11 19:51 UTC by rickycodes

**Description**

re: #1503

opening this as a draft PR for now, going to clean things up after I get back from my afternoon walk :)

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #1503

2020-05-26 16:01 UTC, danjm commented on app/components/Views/ApproveView/Approve/index.js
> +										<StyledButton
As we discussed on a call, these buttons, as well as the `TransactionHeader` should be part of a reusable component that all the new confirmation modals can use. It's okay with me if that is done as a future task as it affects multiple flows, including some that are still in PR at this time.

2020-05-26 16:02 UTC, danjm commented on app/util/transactions.js
> +const capitalize = str => str.charAt(0).toUpperCase() + str.slice(1);
When building for the web we can do this with css. Does that work on mobile?

2020-05-26 16:05 UTC, danjm requested changes
Left two comments. The code looks fine overall. All good for me if QA passes.

2020-05-27 17:34 UTC, rickycodes commented on app/components/Views/ApproveView/Approve/index.js
> +										<StyledButton
yea, my thinking is that we should have another type of Modal component to simplify and DRY out some of this type of thing: https://github.com/MetaMask/metamask-mobile/blob/develop/app/components/Views/BrowserTab/index.js#L1722-L1733. I already have some ideas. I think a `DefaultModal` with preferred transition props etc should be created and then maybe another one that updates/replaces the existing `ActionModal` functionality? happy to do that in a separate PR

2020-06-03 15:38 UTC, rickycodes commented
Leaving some screenshots here for design QA:

Initial Approve Token Screen:

![image](https://user-images.githubusercontent.com/675259/83656274-55ff7c00-a58d-11ea-833d-fe9220bf0d36.png)

Edit Permissions:

![image](https://user-images.githubusercontent.com/675259/83656350-6d3e6980-a58d-11ea-8c17-f52f244f5c24.png)

Transaction Details:

![image](https://user-images.githubusercontent.com/675259/83656936-2c932000-a58e-11ea-8081-60603f636e7c.png)

Transaction Details (View Data Expanded):

![image](https://user-images.githubusercontent.com/675259/83657004-446aa400-a58e-11ea-811e-d4e3cf9eaceb.png)

A couple things:

Transaction details is currently missing a row for name as the contract for token approval doesn't have one. name isn't always available. After discussion with @estebanmino he suggested we leave it out for now. The past icon is still what we were using previously vs the new clipboard treatment that's in the new screens, I wasn't sure if we wanted to change that everywhere? Again, that's something we can look at adding in a separate PR.

2020-06-17 02:28 UTC, danjm approved these changes

2020-06-17 16:14 UTC, ibrahimtaveras00 requested changes
**Issue 1:**

When you choose fiat as your primary currency, the fee is not displayed in fiat but rather in native (ETH).  On current production, we do display fiat first with ETH below it.  Do we want to keep it this way?  Also, @cjeria I noticed there is nothing indicating what form of currency the fee is (there is no USD or ETH to the right of it) 

![image](https://user-images.githubusercontent.com/41752922/84921665-c5e42b00-b092-11ea-9092-62d4b77108b7.png)

**Issue 2:**

When keyboard is expanded on iOS when editing permission to be custom spend limit I can’t see the digits I’m entering = http://recordit.co/uOScHm2nbW

**Issue 3:** 

For some reason it takes quite a lot of taps to bring up the edit network fee on android but works instantly on iOS.  Are you seeing this happen to you as well @rickycodes? 

**Issue 4:**

The transitioning when opening network fee is different compared to how it currently opens on production and develop.  On that flow it comes from the bottom of the app upwards, while on this branch there’s a brief flash with a spinner then shows the edit network fee; seen here = http://recordit.co/L8Okta2laE (prod on right)

![Screen Shot 2020-06-17 at 6 10 32 PM](https://user-images.githubusercontent.com/41752922/84955801-e679a880-b0c5-11ea-9974-2d9bf9750e37.png)

**Issue 5:**

There is no way to save the updated network fee, all I see is the approve button and when I go back the network fee value is not updated; seen here = http://recordit.co/VGWIPkM67Z 

![image](https://user-images.githubusercontent.com/41752922/84922161-781bf280-b093-11ea-9cd0-d2206acf9416.png)

**Issue 6:** 

When editing permission there is no set button and is a bit confusing in comparison to our current prod flow; seen here = http://recordit.co/s7sP003Z6B (prod on right) 
Was this intentional perhaps @cjeria although I still see it in figma?

![image](https://user-images.githubusercontent.com/41752922/84922645-22941580-b094-11ea-9f2d-3a33ec726c7c.png)

Nonetheless it does seem like the value is being remembered

**Issue 7:**

I don't think this icon is updating properly (it should show as a secured lock just as in the connect component)

![image](https://user-images.githubusercontent.com/41752922/84924002-fa0d1b00-b095-11ea-8d19-0583e8781fa3.png)

**Issue 8:**

On smaller screens the view is getting cut off

Nexus_S_API_27
<img width="432" alt="Screen Shot 2020-06-17 at 12 41 53 PM" src="https://user-images.githubusercontent.com/41752922/84925588-1f9b2400-b098-11ea-8d9a-c2bf8f460ba0.png">

iPhone SE:
![Screen Shot 2020-06-17 at 2 01 38 PM](https://user-images.githubusercontent.com/41752922/84932961-1a8fa200-b0a3-11ea-892a-ad401f4de535.png)

**Suggestion** 

I noticed that on Android when I go a level deeper (editing permission or network fee) tapping the device back button closes the modal.  I was wondering if maybe we just want to take users back one level?  Nonetheless that's how it is currently implemented now, so maybe it's fine as is.

2020-06-17 20:01 UTC, cjeria commented
Issue 1:
The fee should be represented in whichever currency the user has set their global default and we should show it in the standard format $00.10 or 0.01234 ETH.

Issue 2:
Was it you @estebanmino that was working on getting a fix for this overlapping issue?
![image](https://user-images.githubusercontent.com/597770/84940799-368c4700-b095-11ea-9d4f-73b26cddd9f4.png)


Issue 3:

2020-06-17 22:01 UTC, cjeria commented
**Issue 1:**
The fee should be represented in whichever currency the user has set their global default and we should show it in the standard format $00.10 or 0.01234 ETH.

**Issue 2:**
It looks like this issue was remedied by auto-scrolling to the input field so it's visible when the keyboard is opened. It could be a little tricky to interact with especially if you scroll too far down. I also had difficulty dismissing the keyboard without closing the modal. If it could behave more like Android that would be ideal. Otherwise, I'd be happy to mockup an alternative pattern for these inputs. @omnat does it seem feasible given our timeline? 

<img src="https://user-images.githubusercontent.com/597770/84944736-152e5980-b09b-11ea-8d9a-f5d2e61cd6c5.png" width="200">

**Issue 4:**
I would expect the transitions to be the same except for the last screen in your gif https://recordit.co/L8Okta2laE. That screen will eventually be updated. The current implementation is ok for now.

**Issue 5:**
Somewhat related to **Issue 2**
The main action button in Edit network fee should say "save" not "Approve".

**Issue 8:**
Let's revisit how we could address this problem. I had suggested we proportionally scale down the font and UI elements for smaller screens.

2020-06-22 18:24 UTC, omnat commented
@rickycodes Is this one ready to be QA'd again?

2020-06-23 02:24 UTC, rickycodes commented
> Issue 1:
The fee should be represented in whichever currency the user has set their global default and we should show it in the standard format $00.10 or 0.01234 ETH.

Are we okay doing what we had before for currency eg: `00.10 USD`? The problem with using `$` is that the symbol is different for other currencies and I'm not sure if we want to add symbols for each supported one.

2020-06-23 22:49 UTC, ibrahimtaveras00 commented
All fixes look good 👍 

The only issue/suggestion I have is for Network fee, when in fiat mode do we want to stay consistent with other designs and only show up to 2 decimal points? 

![image](https://user-images.githubusercontent.com/41752922/85474059-2804ca80-b582-11ea-9628-d1b690e63829.png)

2020-06-23 23:37 UTC, rickycodes commented
> The only issue/suggestion I have is for Network fee, when in fiat mode do we want to stay consistent with other designs and only show up to 2 decimal points?

This should be good now as well :)

2020-06-23 23:46 UTC, estebanmino commented on app/components/Views/ApproveView/Approve/index.js
> +	activeTabUrl: state.browser.tabs.find(({ id }) => id === state.browser.activeTab).url
this view works on deeplinks right? does this work when no tabs are opened and we get a deeplink request?

2020-06-24 01:04 UTC, ibrahimtaveras00 commented on app/components/Views/ApproveView/Approve/index.js
> +	activeTabUrl: state.browser.tabs.find(({ id }) => id === state.browser.activeTab).url
I see what you mean @estebanmino that doesn't seem to be working = http://recordit.co/VSmyLayJty (this branch on left/ prod on right)

2020-06-24 01:04 UTC, ibrahimtaveras00 commented on app/components/Views/ApproveView/Approve/index.js
> +	activeTabUrl: state.browser.tabs.find(({ id }) => id === state.browser.activeTab).url
Although it looks like prod crashed on me upon confirming 👀

2020-06-24 17:07 UTC, rickycodes commented on app/components/Views/ApproveView/Approve/index.js
> +	activeTabUrl: state.browser.tabs.find(({ id }) => id === state.browser.activeTab).url
I've added a fallback here just in case: https://github.com/MetaMask/metamask-mobile/pull/1558/commits/8ff0d932ba7026ffaa0dd35e5b5e59f0f240a24f

2020-06-24 17:13 UTC, estebanmino approved these changes
LGTM!

2020-06-24 17:14 UTC, ibrahimtaveras00 approved these changes
All fixes look good on both OS's, QA Passed 👍

2020-06-24 17:46 UTC, merged