Fix validating of amount when sending a collectible
MetaMask/metamask-mobile pull request #1565
Opened 2020-05-12 22:48 UTC by danjm

Fixes an error with sending collectibles.

https://streamable.com/f4pbdw

2020-05-12 22:53 UTC, rickycodes approved these changes

2020-05-12 22:53 UTC, rickycodes commented on app/components/Views/SendFlow/Confirm/index.js
> +			} else if (selectedAsset.isETH || selectedAsset.tokenId) {
should we be checking for either or, or both?

or should we just be checking for `selectedAsset.tokenId`?

2020-05-12 22:53 UTC, rickycodes commented
left a comment, but I still approved since this lgtm

2020-05-12 23:03 UTC, danjm commented on app/components/Views/SendFlow/Confirm/index.js
> +			} else if (selectedAsset.isETH || selectedAsset.tokenId) {
I think checking both is okay. When sending a collectible, we only need to validate that the user's balance exceeds the total gas, which is what `weiInput` will equal in the case of a collectible.

2020-05-12 23:46 UTC, estebanmino commented on app/components/Views/SendFlow/Confirm/index.js
> +			} else if (selectedAsset.isETH || selectedAsset.tokenId) {
could you use something like https://github.com/MetaMask/metamask-mobile/blob/develop/app/components/UI/TransactionEditor/index.js#L331 ?

2020-05-12 23:47 UTC, estebanmino requested changes
Added a comment about https://github.com/MetaMask/metamask-mobile/pull/1565#discussion_r424096125 would be nice to have since users can send collectibles from dapps that we're not aware of

2020-05-12 23:49 UTC, estebanmino reviewed
that doesn't need to be a blocker TBH  I think it wasn't on this flow

2020-05-13 00:03 UTC, danjm commented on app/components/Views/SendFlow/Confirm/index.js
> +			} else if (selectedAsset.isETH || selectedAsset.tokenId) {
@estebanmino added in 0951e548

2020-05-13 00:04 UTC, danjm commented
I have added commit 26e8f1ac to address an issue found by @omnat:

> Next button not working issue... It happened when I went back to collectible screen from the review screen. Wouldn’t go next from there

This now works: https://streamable.com/uukqza

2020-05-13 16:14 UTC, ibrahimtaveras00 commented
@danjm was part of the fix an update to txn history as well?

I'm seeing a no fee when there is a fee

![image](https://user-images.githubusercontent.com/41752922/81836786-f411a080-9511-11ea-93fe-a0e86760a1b0.png)

This is different in relation to how iOS shows sent collectible 

![Screen Shot 2020-05-13 at 12 14 29 PM](https://user-images.githubusercontent.com/41752922/81837832-54551200-9513-11ea-9776-a7993a8fdf25.png)

2020-05-13 16:37 UTC, danjm commented
@ibrahimtaveras00 I don't think any change in this PR could cause that "No fee" message

I just did a send of a collectible and it didn't happen.

![Screenshot from 2020-05-13 14-02-06](https://user-images.githubusercontent.com/7499938/81840104-11029f80-9523-11ea-9e7d-c38d0f70040a.png)

2020-05-13 16:39 UTC, danjm commented
However, it could be an unintended consequence / bug introduced by this PR. I investigating what could cause that and how we might make consistent reproduction steps.

2020-05-13 17:49 UTC, ibrahimtaveras00 commented
Interesting, I couldn't reproduce the last two attempts 

1st attempt:
![Screen Shot 2020-05-13 at 1 39 28 PM](https://user-images.githubusercontent.com/41752922/81846653-6ee1b800-9520-11ea-88e9-d73b89c612c8.png)

2nd attempt: 
http://recordit.co/Nbw9CecFYc

Bug fixes for both issues look good on both OS's 👍 , QA Passed

2020-05-13 17:49 UTC, ibrahimtaveras00 approved these changes

2020-05-13 17:51 UTC, estebanmino commented
I think that could come from https://github.com/MetaMask/metamask-mobile/pull/1465/files#diff-9bf1465668b5085c8f828241d9dd6bbcR96 @danjm WDYT?

2020-05-13 19:16 UTC, danjm commented
@estebanmino yeah, that's where the `undefined` fee is affecting the UI

The question is why is the fee undefined? I have not been able to track that down yet. Getting closer... I at least have a transaction with the fee undefined in state now, so I can inspect it.

2020-05-13 20:46 UTC, danjm commented
@ibrahimtaveras00 Those last two examples you shared, the "Amount" is actually the collectible id number. Is that what the design is supposed to be?

2020-05-13 21:07 UTC, ibrahimtaveras00 commented
That's how the current implementation is on playstore and testflight versions and how it's been for quite some time.  I created https://github.com/MetaMask/metamask-mobile/issues/1563 to address this, but it's not something new from this release as it's been around.

CC: @cjeria

2020-05-13 21:30 UTC, danjm commented
@ibrahimtaveras00 @estebanmino I figured out why sometimes we are seeing "No fee" and sometimes not. Different collectibles have different transfer methods. We encode some of these specifically in `/metamask-mobile/app/util/collectibles-transfer.json`. The data we attach to the transaction details is currently a little different depending on whether the collectible contract uses a  `transfer` or `transferFrom` method.

The fix is to ensure the fee data is included in both types of transaction data. This issue is separate from this PR. So I will create another PR for it.

2020-05-13 21:47 UTC, estebanmino approved these changes

2020-05-13 22:14 UTC, merged