Payment channel opt in
MetaMask/metamask-mobile pull request #1573
Opened 2020-05-13 21:40 UTC by estebanmino

**Description**

This PR will hide the option for turning on payment channel if no funds on the channel for current `selectedAddress` and `provider.type`

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2020-05-13 22:54 UTC, danjm commented on app/components/Views/Settings/ExperimentalSettings/index.js
> +		this.setState({ paymentChannelHasBalance: true });
I think line 84 can be deleted

2020-05-13 22:54 UTC, danjm commented on app/core/PaymentChannelsClient.js
> +		if (client) return true;
Is it possible for a client to have been initialized but no balance sent to the address?

2020-05-14 20:57 UTC, estebanmino commented on app/core/PaymentChannelsClient.js
> +		if (client) return true;
yes, just enabling the experimental setting with the channel just opened

2020-07-02 00:41 UTC, ibrahimtaveras00 requested changes
**Issue 1**

I am unable to enable payment channels on an account that has a balance

steps:
- I started in a state where instapay was already enabled on the app (came from develop branch) 
- built this branch and saw instapay was still enabled with the correct balance
- I then toggled off/disabled state channels on that account 
- switched to another account that didn't have any instapay balance
- killed the app and relaunched 
- switched back to the account that DOES have an instapay balance
- however, when I attempted to enable payment channels, I didn't have the option to do so 

**Issue 2** 

I don't see the option to enable payment channels when importing via seed phrase 

- started app in fresh state 
- imported my wallet via seed phrase
- once I got to the wallet view I went to settings > experimental 
- I did not see the option to enable payment channels even though my Account 1 does indeed have instapay funds

2020-07-08 16:44 UTC, ibrahimtaveras00 approved these changes
Issues have been resolved on both OS's, QA Passed 👍

2020-07-08 16:55 UTC, merged