React native upgrade 0.62.1 rebased
MetaMask/metamask-mobile pull request #1586
Opened 2020-05-18 15:42 UTC by andrepimenta

**Description**

This PR addresses the upgrade from React Native 0.59.10 to 0.62.1. Although there were lots of changes necessary, an effort was made in order to keep as much as possible the version of the libraries that were already being used (**no unnecessary library upgrades were made**), and also to keep as much of the code as intact as possible (**no unnecessary code changes were made**). This makes it easier to track any possible problems to the React Native upgrade itself. The upgrading of libraries to a newer current version is a step 2 outside of this PR context.

**Note**: To run this PR, don't forget to check the changes on the README. More specifically installing the pods:
`brew install cocoapods`
And on the root of the project
`cd ios && pod install && cd ..`

To open the project on Xcode, the file **MetaMask.xcworkspace** should be used instead of MetaMask.xcodeproj.

`yarn clean` also installs the pods now.

## General file changes
The first part of the upgrade was making all the file changes needed in order to integrate the new React Native version. Those changes can be followed on this [upgrade-helper](https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.62.1).

## Library changes
One of the biggest changes in React 0.60+ is the integration by default of the [pods system](https://reactnative.dev/blog/2019/07/03/version-60#cocoapods-by-default). This means every library needed to be unlinked. This is because with the new system, every library is [automatically linked](https://reactnative.dev/blog/2019/07/03/version-60#native-modules-are-now-autolinked). More specifically, the **libraries that were unlinked** were:
- react-native-sensors
- react-native-reanimated
- react-native-webview
- @react-native-community/netinfo
- react-native-view-shot
- lottie-react-native
- @react-native-community/async-storage
- react-native-push-notification
- react-native-background-timer
- react-native-device-info
- react-native-svg
- react-native-gesture-handler
- react-native-screens
- react-native-branch
- react-native-camera
- react-native-fs
- react-native-i18n
- react-native-keychain
- react-native-share
- react-native-randombytes
- react-native-vector-icons

### Libraries that did not support auto-linking
Some libraries couldn't be unlinked because they did not support auto-linking. Furthermore, in order for some of them to work, changes needed to be made on each library.

More specifically on iOS:
- react-native-aes-crypto. [See changes here.](https://github.com/MetaMask/react-native-aes/commit/b73625d7e1ce711ed3c2fbd795eea2bda5a5e9ad)
- react-native-os. [See  changes here.](https://github.com/MetaMask/react-native-os/commit/67cbc5787295f36575c64442e7f74b803b3de8dd)
- react-native-search-api. [See changes here.](https://github.com/MetaMask/react-native-search-api/commit/270512b6641bfaba155ca8b31aa2e1d8b5cf0ec6)
- react-native-tcp [See changes here.](https://github.com/MetaMask/react-native-tcp/commit/961328b678b01427b0d2cd7ddb506f620a5418e1)
- react-native-scrollable-tab-view. The fix for this library was actually **bumping the version**, since the new version supported auto-linking and it seemed to already integrate our custom changes. Version bumped from [our custom version](https://github.com/estebanmino/react-native-scrollable-tab-view/commit/f954274c6260a07c956e2185c611aed24b2f1526) to [original v1.0.0](https://github.com/ptomasroos/react-native-scrollable-tab-view/tree/v1.0.0)

and on Android:
- lottie-react-native
- react-native-gesture-handler

### Patches removed
- `react-native+0.59.10.patch`. Since a new version of React Native was installed, this patch did not make sense anymore. No patch for the new version was necessary, at least for successfully compiling and running the app.

### Removed assets
- Removed fonts: Because of the auto-linking features, all the fonts that were manually added to Xcode from `react-native-vector-icons` were removed. The auto-linking should add those fonts automatically now.

## Errors fixed
After the app compiled successfully, there were some errors encountered when running the app. More specifically:
- App crashed on Android on any screen with our `WebView`. After some research, [the fix was modifying our custom WebView.](https://github.com/MetaMask/react-native-webview/commit/408df176e6fe7c00aa05c2fddb4054968330e8a1)
- App crashed when closing the side nav drawer on iOS release. The fix was adding `import 'react-native-gesture-handler';` to the` index.js file`. See [here](https://github.com/MetaMask/metamask-mobile/compare/react-native-upgrade-0.62.1-wip#diff-168726dbe96b3ce427e7fedce31bb0bcR3).
- Metro bundler did not work with the new React Native version. The metro version needed to be upgraded from 0.55.0 to 0.59.0.

## Warnings fixed

- `Animated: 'useNativeDriver' was not specified. This is a required 'option and must be explicitly set to true or false`. This warning was fixed by **upgrading** `react-native-modal` from 9.0.0 to 11.5.6.
- `Animated.event now requires a second argument for options`. This warning was fixed by **upgrading** `react-native-modal` from 9.0.0 to 11.5.6.
- `Calling getNode() on the ref of an Animated component is no longer necessary`. Since a lot of libraries were causing this warning like `react-native-scrollable-tab-view`, `react-native-keyboard-aware-scroll-view` and `react-native-tab-view`, **this warning was added to the ignore list**. We should address this by upgrading the libraries mentioned.
- `componentWillUpdate deprecated`. Since this appears on a lot of our components, **this warning was added to the ignore list**. Check [this](https://reactjs.org/docs/react-component.html#unsafe_componentwillupdate) for possible fix.
- `componentWillReceiveProps deprecated`. Since this appears on a lot of our components, **this warning was added to the ignore list**. Check [this](https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops) for possible fix.

## Lint

The lint plugin we used called `eslint-config-react-native` no longer worked correctly with the new React Native version. The reccommended plugin now is `@react-native-community/eslint-config`. An effort was made so that our current rules remained the same. Because of this, there were lots of rules added so a new file called `.eslintrc.js` was created to accommodate all the rules. It's possible that this new config is more strict, so we may still change the config file to our liking.

**Issue**

Resolves #1201

2020-05-18 18:36 UTC, estebanmino commented on .gitignore
> +/ios/Pods/
I see a lot of `No new line ...` warnings

2020-05-18 18:37 UTC, estebanmino commented on android/app/build.gradle
> +            keyPassword 'android'
are we adding new keys?

2020-05-18 18:38 UTC, estebanmino commented on android/app/build.gradle
> +            keyPassword 'android'
do we need keys for debug?

2020-05-18 18:41 UTC, estebanmino commented on android/app/src/main/AndroidManifest.xml
> +			android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
cool

2020-05-18 18:41 UTC, andrepimenta commented on .gitignore
> +/ios/Pods/
Thanks I will fix that!

2020-05-18 18:42 UTC, andrepimenta commented on android/app/build.gradle
> +            keyPassword 'android'
Yes if you start a new RN project those are there now. Take a look at this:
https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.62.1

2020-05-18 18:44 UTC, estebanmino commented on android/keystores/debug.keystore.properties
> -key.alias.password=android
I made a comment before about this, so you passed these vars to that file?

2020-05-18 18:46 UTC, andrepimenta commented on android/keystores/debug.keystore.properties
> -key.alias.password=android
I followed this:
https://react-native-community.github.io/upgrade-helper/?from=0.59.10&to=0.62.1

So, new RN projects now are like that

2020-05-18 18:46 UTC, estebanmino commented on index.js
> +	'getNode()'
I saw your comment about this on the PR description. I tried to find where we were using these on our side as you said and I couldn't... this seems to come from our deps right?

2020-05-18 18:48 UTC, andrepimenta commented on index.js
> +	'getNode()'
The componentWillUpdate and componentWillReceiveProps are from our code (and probably from libs). We need to use hooks. The other ones are from libs yes.

2020-05-18 18:50 UTC, estebanmino commented on index.js
> +	'getNode()'
hm strange I'm searching on vscode on the project and I can't find these. But anyways I agree about hooks

2020-05-18 18:52 UTC, andrepimenta commented on index.js
> +	'getNode()'
Oh you are right! I thought we were using those, because the project started before they were deprecated. Nevermind then, they are from libs!

2020-05-19 22:08 UTC, omnat commented
![](https://github.trello.services/images/mini-trello-icon.png) [React Native upgrade #2](https://trello.com/c/JAVWAOdX/70-react-native-upgrade-2)

2020-05-21 08:20 UTC, ibrahimtaveras00 requested changes
Following issues are happening only on **Android**

**Issue 1:**

Detox e2e isn't able to run on debug mode, nor release mode 

**Issue 2:**

Assets are not showing up on wallet view; nor the option to add tokens and/or collectibles

![Screen Shot 2020-05-20 at 4 19 22 PM](https://user-images.githubusercontent.com/41752922/82538352-a1d80d00-9b19-11ea-9cb0-60072b72a133.png)

**Issue 3:** 

Similar to issue 2, when you are on a dapp and initiate a txn, the confirm view is missing both details and data

You can reproduce by going to https://metamask.github.io/test-dap and tapping on deploy contract after connecting

**Issue 4:**

Upon going to drawer > settings > Security & Privacy and then scrolling down to both SHOW PRIVATE KEY and REVEAL SEED PHRASE; once tapping those buttons and entering password, you're unable to see anything be displayed.

2020-05-21 16:14 UTC, andrepimenta commented
@ibrahimtaveras00 Those issues should be fixed now!

2020-05-21 20:30 UTC, ibrahimtaveras00 approved these changes
Fixes look good, QA Passed 👍

2020-05-21 20:54 UTC, estebanmino approved these changes
approving now, waiting for your decision on https://github.com/MetaMask/metamask-mobile/pull/1586/commits/d111f27a3b068e6099440ab574cc9948a08d9d58

2020-05-23 15:19 UTC, merged