Android performance improvements: use of asyncstorage on login
MetaMask/metamask-mobile pull request #1593
Opened 2020-05-20 19:27 UTC by danjm

This PR explicitly aims at improve the time it takes to go from submission of password on the login page to rendering content to the user.

The focus is on removing the `AsyncStorage` calls to get `onboardingWizard` and `metricsOptIn ` variables in the `onLogin` method of the Login view.

When testing under conditions of system resource constraint, I found that these calls could take more than 1 second each. This is consistent with performance measurement of `AsyncStorage` (https://medium.com/@Sendbird/extreme-optimization-of-asyncstorage-in-react-native-b2a1e0107b34)

My moving the data under redux and redux-persist, it is retrieved as part of the batch of all data, and we avoid the performance cost on these individual calls. Can save close to 2 seconds on slow systems.

2020-06-05 22:19 UTC, ibrahimtaveras00 requested changes
Few issues I noticed here:

**Issue 1:** 

If I have a wallet that already has a password, and I log out, or restart app, I am prompted with a warning.  FYI, this is on a real device.  Not seeing the same on emulator.

Restarting app; seen here = https://recordit.co/RalpfqV6eD

![Screen Shot 2020-06-05 at 5 35 24 PM](https://user-images.githubusercontent.com/41752922/83926458-dd005000-a757-11ea-9f8b-b054e577019d.png)

**Issue 2:** 

When creating a new wallet, or when restarting app that already has a wallet (fingerprint enabled) I am repeatedly shown metametrics opt-in (even though I already agreed) along with onboarding wizard (even though I dismissed it already).

creating a new wallet = https://recordit.co/zP3N7rmNIB
wallet with password/fingerprint = https://recordit.co/E8tlamPy7c

2020-06-22 18:45 UTC, omnat commented
@danjm Is this ready to be QA'd again?

2020-07-02 16:49 UTC, danjm commented
@ibrahimtaveras00 I have just pushed a fix that I believe resolves both your issues. At least, I can no longer recreate them.

2020-07-03 00:17 UTC, ibrahimtaveras00 commented
@danjm I'm still seeing issue 2 happening 

here goes a side by side comparison with this branch (on left) compared to playstore (on right) = http://recordit.co/xrI8dDXjeS

As you can see when you create a new wallet and agree to MetaMetrics and then dismiss the tutorial, you should no longer see the MetaMetrics opt-in nor the tutorial again, however, on this branch I still see it when I shouldn't.

steps to reproduce:
- create a new wallet
- agree to MetaMetrics opt-in
- dismiss onboarding wizard tutorial 
- relaunch app

Also same thing happens when I import via seed phrase; seen here = http://recordit.co/oMbgg9svTK

Issue 1 seems fixed 👍

2020-07-06 23:38 UTC, ibrahimtaveras00 requested changes
So creation of the new wallet and killing/relaunching of App issue is fixed along with showing the on-boarding wizard repeatedly 👍 

However, upon creating a new wallet and setting a password (by sending yourself funds), upon killing and relaunching app, I'm still seeing the MetaMetrics Opt-In screen even though I already agreed; seen here = http://recordit.co/R39U3VsGMJ

When I choose "Remember Me", interestingly I don't get this issue = http://recordit.co/eyJeFcFCCW
But if I logout, then log back in, I do get the issue again = http://recordit.co/Q87MjK7cYi

Another issue (similar to above) when syncing with extension, then logging out and logging back in I get the same issue where it shows MetaMetrics view again even though I agreed already (so I assume related to the action of logging out and logging back in)

2020-07-14 17:59 UTC, danjm commented
I don't think this effects enough users often enough to be a blocker. I don't want to risk wasting another 1 or 2 QA cycles on this. When I fix this again, I want to make sure I take the time to get it right so Ibrahim need not find any more bugs. Let's close and reopen after V1

2020-07-14 17:59 UTC, closed without merging