Use @metamask/controllers
MetaMask/metamask-mobile pull request #1598
Opened 2020-05-26 18:22 UTC by rickycodes

remove `gaba` and use `@metamask/controllers`

2020-05-26 18:36 UTC, whymarrh requested changes

2020-05-26 18:36 UTC, whymarrh commented on app/components/UI/Transactions/index.js
> +import { hexToBN } from '@metamask/controllers/dist/util';
Can we not dig into the directory structure of the package?

There is a named `util` export: https://github.com/MetaMask/controllers/blob/v2.0.0/src/index.ts#L2

2020-05-26 18:36 UTC, whymarrh commented on app/components/UI/TxNotification/index.js
> +import { hexToBN } from '@metamask/controllers/dist/util';
Can we not dig into the directory structure of the package?

There is a named `util` export: https://github.com/MetaMask/controllers/blob/v2.0.0/src/index.ts#L2

2020-05-27 04:47 UTC, rickycodes commented
@whymarrh this should be good now

2020-05-27 15:22 UTC, whymarrh approved these changes
LGTM!

2020-05-27 16:01 UTC, merged