Feature/incoming token transactions
MetaMask/metamask-mobile pull request #1613
Opened 2020-06-02 22:40 UTC by estebanmino

**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2020-06-05 21:59 UTC, rickycodes approved these changes
Mostly looks good to me, just a few small notes.

2020-06-05 21:59 UTC, rickycodes commented on app/util/transactions.js
> +		return strings('transactions.received_unit', { unit: tx.transferInformation.symbol });
Maybe we can simplify this slightly? Something like:
```suggestion
		return strings(selfSent ? 'transactions.self_sent_unit' : 'transactions.received_unit', { unit: tx.transferInformation.symbol });
		
```
If that's not clear enough maybe:
```suggestion
		const translationKey = selfSent ? 'transactions.self_sent_unit' : 'transactions.received_unit';
		return strings(translationKey, { unit: tx.transferInformation.symbol });
		
```

2020-06-05 21:59 UTC, rickycodes commented on app/components/UI/TransactionElement/utils.js
> +
I think using let and if/else conditionals makes sense if there's greater than two possibilities, but for cases like this we can use a ternary and `const`:

(I've also added some destructuring for the `TRANSACTION_TYPES`, but that can likely go at the `import`)

```suggestion
	const { SENT_TOKEN, RECEIVED_TOKEN } = TRANSACTION_TYPES
	const transactionType = (renderFullAddress(from) === selectedAddress)
		? SENT_TOKEN
		: RECEIVED_TOKEN
```

2020-06-05 21:59 UTC, rickycodes commented on app/components/UI/TransactionElement/utils.js
> +	else transactionType = TRANSACTION_TYPES.RECEIVED_TOKEN;
same as above :point_up:

2020-06-05 21:59 UTC, rickycodes commented on app/components/UI/TransactionElement/utils.js
> +
same as above :point_up:

2020-07-09 22:07 UTC, ibrahimtaveras00 requested changes
**Issue 1:** 

The txn history updates roughly every 15 seconds or so = http://recordit.co/iH31hzRKLQ 
If you are viewing txn details and have the modal open, this action will automatically close the modal = http://recordit.co/HnTwgPoYj1

**Issue 2:**

I wanted to test canceling a txn, but found that I can't send any ETH on Rinkeby or Ropsten, this was the error I got on Rinkeby

![image](https://user-images.githubusercontent.com/41752922/87095502-d6f60700-c20e-11ea-8d61-79aa0505c757.png)

Followed by this:
![Screen Shot 2020-07-08 at 8 04 26 PM](https://user-images.githubusercontent.com/41752922/87095560-effeb800-c20e-11ea-8962-dc3c4311f18b.png)

**Issue 3:**

Padding is a bit off on the icon's on Android; seen here on a pixel 2 device

![image](https://user-images.githubusercontent.com/41752922/87095625-0efd4a00-c20f-11ea-87bf-6993fd174372.png)

2020-07-10 22:44 UTC, estebanmino commented
Issue 1 fixed with https://github.com/MetaMask/controllers/pull/247/commits/0db69d911300276eb216dc57f6ff27527ee0e7ee
The other two on this PR

2020-07-15 00:49 UTC, ibrahimtaveras00 requested changes
Issues 1 -3 have been resolved 👍 

**Issue 4:**

Something weird with SAI is occurring where I sent SAI to an account, but it's appearing as received DAI; seen here = https://recordit.co/q5S2nZ0Hj5

![image](https://user-images.githubusercontent.com/41752922/87490327-6c303b80-c613-11ea-8c13-895e871ef5bf.png)

2020-07-16 15:55 UTC, ibrahimtaveras00 approved these changes
Fix looks good, QA Passed 👍

2020-07-16 17:07 UTC, merged