Dapp confirmation designs transitions
MetaMask/metamask-mobile pull request #1620
Opened 2020-06-05 08:23 UTC by EtDu

**Description**

Implement screen transitions for `dapp-confirmation-designs`

**Checklist**

- [ ] Implement transitions

2020-06-23 23:26 UTC, estebanmino commented on app/components/UI/CustomGas/index.js
> +		width: PropTypes.number,
any reason for getting this through props instead of calling Dimensions.get('window')?

2020-06-23 23:26 UTC, estebanmino commented on app/components/UI/CustomGas/index.js
> +		customGasHeight: PropTypes.number,
same question for this, seems like a style passed through props?

2020-06-23 23:31 UTC, estebanmino commented on app/components/UI/CustomGas/index.js
> +		!this.state.gasInputHeight && this.setState({ gasInputHeight: event.nativeEvent.layout.height });
hm this could be the answer to my questions before?

2020-06-23 23:34 UTC, estebanmino commented on app/components/UI/TransactionEditor/index.js
> +		else if (xTranslationName === 'reviewToData') xTranslationValue = reviewToDataValue;
I see many constants here, maybe could be a good idea to put these on the top of the file

2020-06-23 23:35 UTC, estebanmino commented on app/components/UI/TransactionEditor/index.js
> +					hideData: true
seems like https://github.com/MetaMask/metamask-mobile/pull/1620/files#diff-fc12bc5d7b49a26e971be23e01a8c79cR626 is the same code but the boolean than here ... can we put that in a method?

2020-06-23 23:37 UTC, estebanmino commented on app/components/UI/TransactionEditor/index.js
> +								Device.isIphoneX() ? rootHeight - customGasHeight : rootHeight - customGasHeight + 24,
I beleieve I saw this 3 times on this file, can we use a method?

2020-06-24 07:17 UTC, EtDu commented on app/components/UI/CustomGas/index.js
> +		width: PropTypes.number,
Thought since I computed the width once I could just just pass it through. Is it better to call Dimensions.get('window') or Device.getDeviceWidth()?

2020-06-24 07:20 UTC, EtDu commented on app/components/UI/CustomGas/index.js
> +		customGasHeight: PropTypes.number,
This value is created via the `onLayout` function on the root `CustomGas` view. It is needed to compute the proper transforms for the animations. 

It's needed inside of `TransactionEditor` as well which is why I didn't just compute it and leave it in `CustomGas`

2020-06-24 07:21 UTC, EtDu commented on app/components/UI/CustomGas/index.js
> +		!this.state.gasInputHeight && this.setState({ gasInputHeight: event.nativeEvent.layout.height });
Yep, `saveCustomGasHeight` called by `onLayout` from the root `CustomGas` view

2020-06-24 07:33 UTC, EtDu commented on app/components/UI/TransactionEditor/index.js
> +		else if (xTranslationName === 'reviewToData') xTranslationValue = reviewToDataValue;
Made an object that maps the strings to the state vars and put it at the top of component

2020-06-24 10:26 UTC, EtDu commented on app/components/UI/TransactionEditor/index.js
> +					hideData: true
Done

2020-06-24 10:42 UTC, EtDu commented on app/components/UI/TransactionEditor/index.js
> +								Device.isIphoneX() ? rootHeight - customGasHeight : rootHeight - customGasHeight + 24,
Done

2020-06-24 20:40 UTC, estebanmino commented on app/components/UI/CustomGas/index.js
> +		width: PropTypes.number,
for these two... I'm thinking if we use it somewhere else in the future is gonna be coupled to whichever parent it uses. I'd say Device.getDeviceWidth() since we have a util for it

2020-06-25 15:51 UTC, EtDu commented on app/components/UI/CustomGas/index.js
> +		width: PropTypes.number,
done

2020-07-01 22:04 UTC, ibrahimtaveras00 commented
**Issue 1 from https://github.com/MetaMask/metamask-mobile/pull/1559:** 

I now see that android is having issues with the keyboard blocking the text input field; seen here = http://recordit.co/FNMCosZIMK

Also in the above screencast notice how the padding is off on both OS's

![Screen Shot 2020-07-01 at 3 57 28 PM](https://user-images.githubusercontent.com/41752922/86293459-a126a200-bbc0-11ea-881b-be704ce7f2c7.png)

![Screen Shot 2020-07-01 at 5 30 55 PM](https://user-images.githubusercontent.com/41752922/86293468-a552bf80-bbc0-11ea-8c3c-7023f0ceb717.png)

I'm not sure if this is related to this fix/change, but on normal send flow, when I tap the Edit button to the right of Network fee nothing happens 

![Screen Shot 2020-07-01 at 5 46 56 PM](https://user-images.githubusercontent.com/41752922/86294655-ffed1b00-bbc2-11ea-9f10-d2c933aebdae.png)

**Issue 2 from https://github.com/MetaMask/metamask-mobile/pull/1559** seems resolved here 👍 

**Issue 4 from https://github.com/MetaMask/metamask-mobile/pull/1559** seems resolved here 👍 

**Other Issues on this PR**

- I'm noticing the padding is off when I tap on View Data button

![Screen Shot 2020-07-01 at 3 54 10 PM](https://user-images.githubusercontent.com/41752922/86295255-295a7680-bbc4-11ea-893a-1a921751ca8f.png)

I also tried to check if approve shows the hex data but I see the old approve still (assuming develop needs to be merged into this PR and I see a conflict above) 

![Screen Shot 2020-07-01 at 5 44 15 PM](https://user-images.githubusercontent.com/41752922/86295385-79393d80-bbc4-11ea-8778-cd4c417c80f2.png)

2020-07-01 22:05 UTC, ibrahimtaveras00 requested changes
few issues reported

2020-07-07 02:20 UTC, ibrahimtaveras00 approved these changes
Fixes look good on both OS's, QA Passed 👍

2020-07-07 04:11 UTC, merged