Fix env vars
MetaMask/metamask-mobile pull request #1645
Opened 2020-06-18 16:52 UTC by estebanmino

**Description**

Env vars haven't been working on debug mode for a while now, this PR fixes that so we can use all the features on debug mode.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2020-06-25 00:20 UTC, ibrahimtaveras00 approved these changes
Fixes look good, QA Passed 👍

2020-06-25 17:39 UTC, rickycodes requested changes

2020-06-25 17:39 UTC, rickycodes commented on app/core/Analytics.js
> +			Logger.log(`Analytics 'trackEventWithValueAndParameters' - `, event, value, info, params);
maybe this could be a method? looks like we're dong the same thing 6x

2020-06-25 19:33 UTC, andrepimenta approved these changes
The only recommendation I have is to put code like this:
```
if (!__DEV__) {
  RCTAnalytics.trackEvent(event);
} else {
  Logger.log(`Analytics 'trackEvent' - `, event);
}
```

On a function outside on a service or helper that would look like:
```
const trackEvent = event => {
  if (!__DEV__) {
    RCTAnalytics.trackEvent(event);
  } else {
    Logger.log(`Analytics 'trackEvent' - `, event);
  }
}
```

And then you could call `trackEvent(event)` everywhere so we don't repeat code. This is especially important if we need to use that function more times in the future.

And the same for `!__DEV__ && RCTAnalytics.optIn(this.enabled);`

Otherwise looks good to me!!

2020-06-25 19:39 UTC, estebanmino commented
@rickycodes @andrepimenta it totally makes sense, it was that way before so I didn't question it 🤦

2020-06-26 18:23 UTC, rickycodes approved these changes

2020-06-26 18:25 UTC, merged