Fiat on Ramp: Payments
MetaMask/metamask-mobile pull request #1666
Opened 2020-07-01 21:20 UTC by wachunei

**Description**

This PR includes Fiat on Ramp feature using different providers such as Wyre (Apple Pay integration) and Transak.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2020-07-10 22:50 UTC, estebanmino commented on .gitignore
> +.env
I think this is not needed anymore

2020-07-10 22:51 UTC, estebanmino commented on app/components/Base/Text.js
> +	style: PropTypes.oneOfType([PropTypes.object, PropTypes.array])
can you add docs for these properties please?

2020-07-10 22:52 UTC, estebanmino commented on app/components/Base/Title.js
> +		marginBottom: 3,
I saw this in other file as well, you could also do `marginVertical` and `paddingVertical` but is not very important

2020-07-10 22:52 UTC, estebanmino commented on app/components/Base/Title.js
> +	style: PropTypes.oneOfType([PropTypes.object, PropTypes.array])
same for these props

2020-07-10 22:53 UTC, estebanmino commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +		paddingHorizontal: 8,
ah here it is

2020-07-10 22:54 UTC, estebanmino commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +		fontFamily: 'Roboto',
we're removing roboto from our fonts, is this needed?

2020-07-10 22:54 UTC, estebanmino commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +		opacity: 0.6
is not the same than `applePayButtonTextDisabled`?

2020-07-10 22:55 UTC, estebanmino commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +		fontFamily: 'Roboto-Light',
same for the font here, we're moving from roboto

2020-07-10 22:55 UTC, estebanmino commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +				// TODO: throw error for feedback?
are we doing this?

2020-07-10 22:56 UTC, estebanmino commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +		setLockTime(-1);
reminder for @ibrahimtaveras00 to qa closing the app while a tx is happening and other cases like that

2020-07-10 22:57 UTC, wachunei commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +		fontFamily: 'Roboto',
I'm using Roboto according to the designs :O

2020-07-10 22:57 UTC, wachunei commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +		fontFamily: 'Roboto-Light',
What would be the replacement?

2020-07-10 22:58 UTC, estebanmino commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +									`$${rates.USD.toFixed(2)} ≈ 1 ETH`
not sure if this was intentional `$$`

2020-07-10 22:58 UTC, wachunei commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +				// TODO: throw error for feedback?
Not right now, we just ignore input that would result in a bad formed amount.

2020-07-10 22:58 UTC, estebanmino commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +									`$${rates.USD.toFixed(2)} ≈ 1 ETH`
oh yes it was

2020-07-10 22:59 UTC, wachunei commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +									`$${rates.USD.toFixed(2)} ≈ 1 ETH`
yes, that yields "$XXX.XX ≈ 1 ETH"

2020-07-10 23:00 UTC, estebanmino commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +	addOrder: PropTypes.func.isRequired
could you please add descriptions here?

2020-07-10 23:02 UTC, estebanmino commented on app/components/UI/FiatOrders/components/PaymentMethod/index.js
> +export default PaymentMethod;
👌

2020-07-10 23:04 UTC, estebanmino commented on app/components/UI/FiatOrders/index.js
> +export const allowedToBuy = network => network === '1' || (network === '42' && Device.isIos());
how are handling this? we're not showing the option to buy fiat or you can see it and it won't work

2020-07-10 23:04 UTC, estebanmino commented on app/components/UI/FiatOrders/index.js
> +				<Text onPress={onPressAdd}>Add</Text> <Text onPress={clearOrders}>Clear</Text>{' '}
could you add these texts to locales file?

2020-07-10 23:05 UTC, estebanmino commented on app/components/UI/FiatOrders/index.js
> +	createFakeOrder: (address, network) =>
do we need this for production?

2020-07-10 23:06 UTC, estebanmino commented on app/components/UI/FiatOrders/orderProcessor/wyreApplePay.js
> +			label: 'Fee'
could you add these to locales file as well?

2020-07-10 23:09 UTC, estebanmino commented on app/components/UI/ReceiveRequest/index.js
> +				// 	} }
could you remove this?

2020-07-10 23:11 UTC, estebanmino commented on app/components/UI/ReceiveRequest/ReceiveRequestAction/index.js
> -import { connect } from 'react-redux';
why was this file deleted?

2020-07-10 23:12 UTC, wachunei commented on app/components/UI/FiatOrders/index.js
> +export const allowedToBuy = network => network === '1' || (network === '42' && Device.isIos());
We are not showing the option when this is false.

2020-07-10 23:13 UTC, wachunei commented on app/components/UI/FiatOrders/index.js
> +				<Text onPress={onPressAdd}>Add</Text> <Text onPress={clearOrders}>Clear</Text>{' '}
I'll remove this, not needed in prod it was only used for debugging.

2020-07-10 23:13 UTC, estebanmino commented on app/components/UI/Tokens/index.js
> +		const ethBalance = eth && eth.balance !== '0';
hu never thought about this. Does it work for all cases? What we do it take the balance in wei from the controllers like `accounts: state.engine.backgroundState.AccountTrackerController.accounts,` then pass it through props

2020-07-10 23:13 UTC, wachunei commented on app/components/UI/FiatOrders/index.js
> +	createFakeOrder: (address, network) =>
Nope, will remove.

2020-07-10 23:15 UTC, estebanmino commented on package.json
> +    "query-string": "^6.12.1",
what is this for?

2020-07-10 23:15 UTC, estebanmino reviewed
kudos on this @wachunei, massive PR. Added some small comments 🚀

2020-07-10 23:20 UTC, wachunei commented on app/components/UI/ReceiveRequest/ReceiveRequestAction/index.js
> -import { connect } from 'react-redux';
These were the boxes from the old receive drawer 
<img width="261" alt="Screen Shot 2020-07-10 at 19 20 30" src="https://user-images.githubusercontent.com/1024246/87210120-6d472d00-c2e2-11ea-8dba-537613c25ad8.png">

2020-07-10 23:22 UTC, wachunei commented on package.json
> +    "query-string": "^6.12.1",
This is the recommended package from transak to format/parse query params used in the URL for the webview and the redirect callback we are grabbing the order from.

2020-07-10 23:49 UTC, wachunei commented on app/components/Base/Text.js
> +	style: PropTypes.oneOfType([PropTypes.object, PropTypes.array])
Added

2020-07-10 23:49 UTC, wachunei commented on app/components/Base/Title.js
> +	style: PropTypes.oneOfType([PropTypes.object, PropTypes.array])
Added

2020-07-10 23:54 UTC, wachunei commented on app/components/UI/Tokens/index.js
> +		const ethBalance = eth && eth.balance !== '0';
It works because of this, where `balance` is the result of `renderFromWei` already. `assets` is passed as the `tokens` prop to `Tokens`. 

https://github.com/MetaMask/metamask-mobile/blob/4a4c14b832fa7353b498027cdc1fb4da0f0f8c32/app/components/Views/Wallet/index.js#L182-L195

2020-07-10 23:55 UTC, wachunei commented on app/components/Base/Title.js
> +		marginBottom: 3,
Fixed

2020-07-10 23:55 UTC, wachunei commented on .gitignore
> +.env
Removed

2020-07-10 23:56 UTC, wachunei commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +		opacity: 0.6
Merged styles for both button text and logo

2020-07-10 23:58 UTC, wachunei commented on app/components/UI/FiatOrders/PaymentMethodApplePay/index.js
> +	addOrder: PropTypes.func.isRequired
Added

2020-07-10 23:59 UTC, wachunei commented on app/components/UI/FiatOrders/orderProcessor/wyreApplePay.js
> +			label: 'Fee'
Added

2020-07-10 23:59 UTC, wachunei commented on app/components/UI/ReceiveRequest/index.js
> +				// 	} }
Removed

2020-07-11 00:06 UTC, wachunei commented on app/components/UI/ReceiveRequest/ReceiveRequestAction/index.js
> -import { connect } from 'react-redux';
this is the new one 

<img alt="Simulator Screen Shot - iPhone 11 Pro - 2020-07-10 at 20 04 48" src="https://user-images.githubusercontent.com/1024246/87211691-ada9a980-c2e8-11ea-9c4d-ab82141716cf.png" width="300" />

2020-07-11 00:42 UTC, wachunei commented
For everyone involved in this PR, please read this about the behavior of the payment processors.

### Wyre - Apple Pay

- Available for iOS only in Mainnet and Kovan.
- **Depends on the network**: if you open the flow when Mainnet is selected and purchase ETH you will get charged and receive actual ETH. Otherwise you will not be charged and you will receive Kovan ETH.
- Does not work on iOS Simulator.

### Transak
- Available for iOS and Android in Mainnet only (it won't be shown when opening the flow in iOS/Kovan).
- **Depends on the environment**: if you open the flow from a development environment you'll use the [Sandbox Environment](https://integrate.transak.com/Sandbox-Environment-7b2c567382bb4c8b95db608eb3804e68) (Rinkeby ETH), use this for testing purposes (see below).
- **Testing**: The code is meant for production, so "Buy ETH" button and Transak Payment Method button will be available in Mainnet only, **change this to make it available in Rinkeby**
  - in `app/components/UI/FiatOrders/index.js` set `allowedToBuy` to `network => true`.
  - for iOS: in `app/components/UI/FiatOrders/PaymentMethodSelector/index.ios.js` remove network check in `{network === '1' && <TransakPaymentMethod onPress={onPressTransak} />}` .

### Order Tracking
- Order tracking depends on current selected address and network, if you switch either netowrk/address the order will remain pending until you switch back to the combination it was created from.

2020-07-20 21:40 UTC, wachunei commented
## Additional comments about this PR

### Code
- This PR has preferences of the use of Functional Components + Hooks over class components.
  Example: The component that polls and updates the state of the fiat orders is a renderless functional component with a `useInterval` hook.
https://github.com/wachunei/metamask-mobile/blob/feature/rn-payments/app/components/UI/FiatOrders/index.js#L75-L94

- This PR introduces a new `fiatOrders` reducer:
https://github.com/wachunei/metamask-mobile/blob/feature/rn-payments/app/reducers/fiatOrders/index.js

- This PR **does not** include any interaction with the in-app notifications, since the implementation would required deeper changes in order to support a generic onPress action.

### UI
This PR introduces new Base components in order of the to be reused, and also extracts existing components to a the Base level folder for the same purpose.

- **Base/Text.js**: This is the Base Text component, it is used in every new written code in this PR, avoiding rewriting style objects over and over again.

- **Base/Title.js**: A Title Text component used in the Payment Method Selector view

- **Base/ModalHandler.js**: Utility component to handle modals inline. Example: https://github.com/wachunei/metamask-mobile/blob/feature/rn-payments/app/components/Views/FiatOrdersView/index.js#L34-L57

- **Base/ListItem.js**: A component to render an item of a list, used for transactions and also orders. 
  <img width="394" alt="Screen Shot 2020-07-20 at 17 06 27" src="https://user-images.githubusercontent.com/1024246/87986655-6c18bb80-caab-11ea-9596-79db09dedb45.png"> <img width="391" alt="Screen Shot 2020-07-20 at 17 06 36" src="https://user-images.githubusercontent.com/1024246/87986675-70dd6f80-caab-11ea-8083-5e7e1a91a13e.png">

- **Base/DetailsModal.js**: Details component shown in the modal when clicking a Transaction or an Order
  <img width="396" alt="Screen Shot 2020-07-20 at 17 10 02" src="https://user-images.githubusercontent.com/1024246/87986987-e3e6e600-caab-11ea-97c7-2a546eccde6a.png"> <img width="387" alt="Screen Shot 2020-07-20 at 17 10 11" src="https://user-images.githubusercontent.com/1024246/87986997-e6494000-caab-11ea-8048-7fb384f565ec.png">

- **Base/StatusText.js**: Green/orange/red text shown in `ListItem` and also `DetailsModal` to display transaction or order status.

- **Base/Summary.js**: Summary box for amount/fee/total/value breakdown. Used in both Transactions and Orders and also in the Send View 
  <img width="322" alt="Screen Shot 2020-07-20 at 17 15 52" src="https://user-images.githubusercontent.com/1024246/87987581-dd0ca300-caac-11ea-8592-e48f834c8411.png">
  <img width="395" alt="Screen Shot 2020-07-20 at 17 16 23" src="https://user-images.githubusercontent.com/1024246/87987597-e3028400-caac-11ea-8625-52da1556547a.png">

## To consider in the future

<img width="500" alt="Screen Shot 2020-07-20 at 17 31 23" src="https://user-images.githubusercontent.com/1024246/87988756-d7b05800-caae-11ea-9bf1-8886e66f653e.png">

With this PR we introduce a lot more of cases where Fiat amounts are being displayed. Currently, as seen in the screenshot above, fiat amounts are not formatted and they are shown as is they were crypto amounts. 

<img width="324" alt="Screen Shot 2020-07-20 at 17 33 03" src="https://user-images.githubusercontent.com/1024246/87988896-12b28b80-caaf-11ea-949c-a96f4d75ac21.png">

In this PR I'm introducing the usage of `toLocaleString()` (as seen above) which also helps when dealing with floating point situations. For example: 
<img width="217" alt="Screen Shot 2020-07-20 at 17 35 09" src="https://user-images.githubusercontent.com/1024246/87989051-5c9b7180-caaf-11ea-9596-023695b1d7e4.png">

I propose the team to discuss the use of this method or the use of [Intl / Intl.NumberFormat API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat), considering this might need polyfilling in some JSC implementations.

2020-08-06 22:25 UTC, estebanmino commented on .circleci/config.yml
> +                - feature/rn-payments
reminder to fix this when merge

2020-08-13 16:18 UTC, ibrahimtaveras00 commented
**Suggestion/Potential issue 1:**

If you have many tokens, you don't automatically notice the Buy ETH CTA at the bottom of the screen. 

![Screen Shot 2020-08-12 at 7 27 40 PM](https://user-images.githubusercontent.com/41752922/90158258-c6303800-dd5c-11ea-83ea-c65a01dc8494.png)

Once you scroll all the way down and tap the Buy ETH CTA and actually do purchase ETH, you're taken back to the wallet view at the bottom of the screen and the alert doesn't stay, it disappears and you can't see whats going on with your ETH and aren't really given any indication of what's going on till you navigate to txn history (but not sure if users would intuitively go here right away)

Seen here = https://recordit.co/fI0vUI3ypy (after about 5 seconds alert disappears and user may be unsure what's going on) 

Maybe make the Buy ETH cta sticky at the bottom, and after a user purchases ETH once sending back to wallet view, move them back to the top of the screen so ETH is viewable?

**Issue 2:**

I am unable to buy ETH using Kovan 

![image](https://user-images.githubusercontent.com/41752922/90159464-6aff4500-dd5e-11ea-864a-4fc777167515.png)

**Issue 3:**

If user attempts to create new account while on the "Amount to buy" view, you get a white screen; seen here = https://recordit.co/xAULKiL1cw

If you attempt to import you also get a whit screen followed by this alert (even though the account does get added after restarting the app)

![Screen Shot 2020-08-12 at 9 37 35 PM](https://user-images.githubusercontent.com/41752922/90158779-7140f180-dd5d-11ea-8a42-dc2605894d04.png)

**Issue 4:**

In addition to what @omnat mentioned here = https://consensys.slack.com/archives/G018FR294E9/p1596841526003000 on smaller devices the list get's cut off since the modal is not scrollable 

![image](https://user-images.githubusercontent.com/41752922/90159265-25db1300-dd5e-11ea-874c-7698964a8705.png)

**Issue 5:**

Also on a smaller device the Buy with applepay CTA is cut off

![image](https://user-images.githubusercontent.com/41752922/90159375-4dca7680-dd5e-11ea-815e-e40f28831278.png)

**Issue 6:**

Also on a smaller device, the Transak card text overlaps (iPhone SE)

![Screen Shot 2020-08-12 at 8 05 41 PM](https://user-images.githubusercontent.com/41752922/90159551-8f5b2180-dd5e-11ea-8913-307308a6fa12.png)

**Issue 7:** 

On dapp modal I am unable to scroll thus I can't tap the View Data link on this view

![Screen Shot 2020-08-13 at 12 58 19 AM](https://user-images.githubusercontent.com/41752922/90159640-b580c180-dd5e-11ea-83a9-efcde4182ff4.png)

This is on an iPhone X navigating to https://metamask.github.io/test-dapp/ (after connecting tap on Deploy Contract

**Issue 8:** 

Attempting a txn on dapps on normal send flow causes a txn error (I am on Rinkeby and attempted the deploy contract mentioned in above issue and also normal send flow) 

Same thing happens on Mainnet

![Screen Shot 2020-08-13 at 1 01 30 AM](https://user-images.githubusercontent.com/41752922/90159917-0db7c380-dd5f-11ea-90d9-7672735e9a42.png)

![Screen Shot 2020-08-13 at 1 02 53 AM](https://user-images.githubusercontent.com/41752922/90159924-114b4a80-dd5f-11ea-99d0-778d971197eb.png)

2020-08-13 16:19 UTC, ibrahimtaveras00 requested changes
So far above reported issues, but still continuing my QA 

All this is testing on testflight 0.2.20(512)

2020-08-13 18:37 UTC, wachunei commented
I've Fixed QA Issues 3, 4, 5 and 6
<img width="500" alt="Screen Shot 2020-08-13 at 14 21 25" src="https://user-images.githubusercontent.com/1024246/90173404-6775b900-dd72-11ea-8d4c-e1c49f9a544d.png">
<img width="250" alt="Screen Shot 2020-08-13 at 14 33 35" src="https://user-images.githubusercontent.com/1024246/90173406-6775b900-dd72-11ea-9862-b265c79cdecb.png">

2020-08-13 18:44 UTC, omnat commented
For **issue 1**, we had a little chat, and it could indeed be a bit nerve wrecking if it is not intuitive for user to see that their purchase is in progress.

Design team's suggestion:
Make this alert (in screenshot) sticky. If user taps it, they get redirected to the Purchases tab of Transaction history. If they want to close it, they can close with the 'X' on top right. 

![image](https://user-images.githubusercontent.com/44038140/90170387-d7754680-dd54-11ea-99b7-82728e67b859.png)

2020-08-13 18:48 UTC, wachunei commented
We discarded any interaction with the notification beyond clicking on the X because right now the in-app notifications can't handle that event.

2020-08-13 20:50 UTC, omnat commented
@wachunei @ibrahimtaveras00 I synced with @estebanmino on this, who shared the challenge with updating the interaction with the alert, and the behavior of making it sticky. 

So, let us leave it for v1. We'll improve it after release. 

In short, issue 1 is non-release blocker - no action / resolution needed

2020-08-18 17:35 UTC, ibrahimtaveras00 approved these changes
QA Passed 👍

2020-08-18 21:37 UTC, merged