Improvement/migrate aes crypto lib
MetaMask/metamask-mobile pull request #1755
Opened 2020-08-06 20:23 UTC by andrepimenta

**Description**

Migration to the new aes-crypto lib from the forked one.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2020-08-06 21:01 UTC, estebanmino commented on app/core/Vault.js
> +export const recreateVault = async (password = '', selectedAddress) => {
is this taking imported accounts or it's going to be deleted?

2020-08-07 21:21 UTC, ibrahimtaveras00 approved these changes
looks good, QA Passed 👍

2020-08-10 20:00 UTC, ibrahimtaveras00 requested changes
Still fails on imported accounts as mentioned in https://github.com/MetaMask/metamask-mobile/pull/1756

2020-08-11 19:34 UTC, estebanmino commented on app/core/Vault.js
> +	let importedAccounts = [];
seems like is the same code right? https://github.com/MetaMask/metamask-mobile/pull/1756/files#diff-05500d00f4a6959745b57a220987a4b6R359 
would be nice to have `Logger` here to know what's going on and remove duplicated code, but we can do the last after releasing

2020-08-11 21:34 UTC, ibrahimtaveras00 commented
Imported accounts are not lost on login 👍 

I did notice that we show a different error message on android with empty password or wrong password rather than how in iOS we show Invalid password

seen here = https://recordit.co/K8r7qnxUl8

![Screen Shot 2020-08-11 at 5 30 04 PM](https://user-images.githubusercontent.com/41752922/89950798-54d77480-dbf8-11ea-8531-cb5cc47372c8.png)

Again this is only on android.  To reproduce:
- either sync with extension/import via seed phrase/ or create a new wallet
- after arriving on wallet view, open drawer and log out 
- now on login screen simply tap log in or input an invalid password

2020-08-12 15:24 UTC, andrepimenta commented
@ibrahimtaveras00 just fixed the error message on Android 👍  You can take a look again

2020-08-12 17:15 UTC, ibrahimtaveras00 approved these changes
QA Passed 👍

2020-08-12 17:34 UTC, merged