Fix recreate vault import accounts
MetaMask/metamask-mobile pull request #1756
Opened 2020-08-07 18:41 UTC by andrepimenta

**Description**

This fixes import accounts getting deleted when the vault is recreated 

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2020-08-07 18:46 UTC, Gudahtt commented on app/components/Views/ChoosePassword/index.js
> +		if (KeyringController.state.keyrings.length === 2) {
On the extension we have one keyring for each imported account - I am guessing mobile is the same? So this should handle all keyrings from index 1 onwards.

2020-08-07 22:54 UTC, ibrahimtaveras00 requested changes
Few issues

**Issue 1:**   Wallet with 1 imported account produces an error "Error: Invalid password"

**Issue 2:** Wallet with 2 imported accounts does allow you create password, however, the imported accounts are lost

Here goes my set up/steps:

1.  I built v0.2.19 

![Screen Shot 2020-08-07 at 6 31 59 PM](https://user-images.githubusercontent.com/41752922/89694199-a6bd8900-d8de-11ea-95ac-d18ed917d0e5.png)

2.  I then created 3 wallets (no password set/nor no back up)
wallet 1 = 1 account with 1 imported account
wallet 2 = 1 account with 2 imported accounts 
wallet 3 = 3 accounts with 1 imported account

![image](https://user-images.githubusercontent.com/41752922/89694490-d076b000-d8de-11ea-8283-d92142dc379e.png)

3.   I then switched to this branch and ran yarn clean, yarn watch:clean, and yarn start:android

4.  Upon building this branch, after being prompted to create a password these are the results; seen here = https://recordit.co/189ncJf7qX

wallet 1 = upon attempting to create a password it gave me the "Invalid password" error
wallet 2 = it did allow me to create password, however, my imported accounts are no longer there
wallet 3 = same error as wallet 1

![Screen Shot 2020-08-07 at 6 52 19 PM](https://user-images.githubusercontent.com/41752922/89694592-23506780-d8df-11ea-88a1-74403ebb3d85.png)

2020-08-09 18:29 UTC, rickycodes commented
> Issue 2: Wallet with 2 imported accounts does allow you create password, however, the imported accounts are lost

I believe this is due to what @Gudahtt mentioned here: https://github.com/MetaMask/metamask-mobile/pull/1756#discussion_r467210676

2020-08-10 15:06 UTC, andrepimenta commented on app/components/Views/ChoosePassword/index.js
> +		if (KeyringController.state.keyrings.length === 2) {
You are right! Thanks, fixing this now.

2020-08-10 15:45 UTC, andrepimenta commented on app/components/Views/ChoosePassword/index.js
> +		if (KeyringController.state.keyrings.length === 2) {
Should be fixed now 👍

2020-08-10 19:59 UTC, ibrahimtaveras00 requested changes
**Issue 1** has been fixed 👍  in regards to no longer showing the error on password creation
**Issue 2** still happens to both wallets with 1 imported account and wallets with 2 or more imported accounts

2020-08-11 18:45 UTC, ibrahimtaveras00 approved these changes
Fixes look good, QA Passed 👍

2020-08-11 19:29 UTC, estebanmino commented on app/components/Views/ChoosePassword/index.js
> +			console.warn(e);
what if we use the logger here to get the errors in sentry?

2020-08-12 17:22 UTC, merged