Add option to use Jazz Icon
MetaMask/metamask-mobile pull request #1757
Opened 2020-08-08 01:07 UTC by rickycodes

This gives us a new option to enable jazz icons instead of identicons:

![image](https://user-images.githubusercontent.com/675259/89698909-c8743b80-d8f1-11ea-83fe-8a04fb5b5ad2.png)

Which in turn changes the Identicon usage:

![image](https://user-images.githubusercontent.com/675259/89698935-e8a3fa80-d8f1-11ea-931b-327a1814d23f.png)

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #232

2020-08-08 07:09 UTC, EtDu commented on app/actions/settings/index.js
> +export function setUseBlockieIcon(useBlockieIcon) {
Nit: I would say `toggleUseBlockieIcon` to be more specific

2020-08-08 07:35 UTC, EtDu requested changes
Nice, just a couple nitpicks

2020-08-08 07:35 UTC, EtDu commented on app/actions/settings/index.js
> +export function setUseBlockieIcon(useBlockieIcon) {
Nit: I would say toggleUseBlockieIcon to be more specific

2020-08-08 07:35 UTC, EtDu commented on app/components/Views/Settings/AdvancedSettings/index.js
> +	toggleUseBlockieIcon = useuseBlockieIcon => {
`useBlockieIcon`

2020-08-08 07:35 UTC, EtDu commented on app/components/Views/Settings/AdvancedSettings/index.js
> +									trackColor={Device.isIos() ? { true: colors.blue, false: colors.grey000 } : null}
binary operator:
`Device.isIos() && {......}`

2020-08-08 07:35 UTC, EtDu commented on app/components/Views/Settings/AdvancedSettings/index.js
> +	setShowHexData: showHexData => dispatch(setShowHexData(showHexData)),
I know this wasn't your commit, but could also change to `toggleShowHexData`

2020-08-08 07:38 UTC, rickycodes commented on app/components/Views/Settings/AdvancedSettings/index.js
> +	setShowHexData: showHexData => dispatch(setShowHexData(showHexData)),
actually, I think that might have been added by me idk? but yea i guess if we're toggling (true/false) we should be calling them toggle

2020-08-08 07:44 UTC, rickycodes commented on app/actions/settings/index.js
> +export function setUseBlockieIcon(useBlockieIcon) {
this is where it gets tricky imo, I am kinda just following convention in the repo... so idk if I want to change thses two to toggle... would you suggest also changing the `type` here? to maybe be something like 

```
'TOGGLE_BLOCKIE_ICON'
```

as well?

2020-08-08 07:53 UTC, EtDu commented on app/actions/settings/index.js
> +export function setUseBlockieIcon(useBlockieIcon) {
Yeah, if you decide to change I would also change it there

2020-08-08 07:57 UTC, EtDu commented on app/components/Views/Settings/AdvancedSettings/index.js
> +	setShowHexData: showHexData => dispatch(setShowHexData(showHexData)),
I suppose just leave it for now since it would be inconsistent compared to the existing convention

2020-08-08 08:03 UTC, EtDu approved these changes

2020-08-10 02:31 UTC, rickycodes commented on app/components/UI/Identicon/__snapshots__/index.test.js.snap
> -exports[`Identicon should render correctly 1`] = `""`;
this is interesting. I'm not sure why this was empty before? the new snapshot I think makes sense, but maybe this is normal for components created with `.memo`? maybe the test just wasn't correct?

2020-09-01 21:43 UTC, ibrahimtaveras00 requested changes
**Issue 1:** 

When I switch to use Blockies Identicon I get this warning:

![Screen Shot 2020-09-01 at 5 25 56 PM](https://user-images.githubusercontent.com/41752922/91908822-24747a80-ec7a-11ea-93e1-563c49d9935a.png)

followed by nothing showing up in it's place

![Screen Shot 2020-09-01 at 5 26 30 PM](https://user-images.githubusercontent.com/41752922/91908863-35bd8700-ec7a-11ea-89b2-0f13c1b9b069.png)

![Screen Shot 2020-09-01 at 5 40 29 PM](https://user-images.githubusercontent.com/41752922/91908902-479f2a00-ec7a-11ea-8c59-9f4f47b8dfe1.png)

**Issue 2:**

The padding of the Jazz Icons on account info seems off compared to blockies

![image](https://user-images.githubusercontent.com/41752922/91909112-9d73d200-ec7a-11ea-9e9a-0c03f99c23fb.png)

2020-09-02 17:34 UTC, rickycodes commented
@ibrahimtaveras00 good catches on these! should be good now :)

2020-09-08 21:17 UTC, ibrahimtaveras00 approved these changes
Fixes look good on both OS's, QA Passed 👍

2020-09-09 00:37 UTC, merged