Bugfix/payment request and wallet connect origin on tx
MetaMask/metamask-mobile pull request #1790
Opened 2020-08-20 21:48 UTC by estebanmino

**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2020-08-21 00:58 UTC, ibrahimtaveras00 requested changes
All is fixed in this PR 👍 

However, one thing I noticed about Wallet Connect; when testing with uniswap on safari and coming to MM app I noticed the dapp name said wallect-connect-origin instead of the uniswap dapp name

seen here = http://recordit.co/pUjUFLZMx6

![image](https://user-images.githubusercontent.com/41752922/90840381-da110680-e327-11ea-8555-dbf4c9d2615e.png)

2020-08-21 00:59 UTC, ibrahimtaveras00 commented
This will be fixed with https://github.com/MetaMask/metamask-mobile/pull/1790

2020-08-21 16:43 UTC, rickycodes approved these changes

2020-08-21 16:46 UTC, ibrahimtaveras00 approved these changes
QA Passed 👍

2020-08-21 17:28 UTC, merged

2020-09-07 03:01 UTC, miranda76 approved these changes

2020-09-07 03:02 UTC, miranda76 approved these changes