Feature/hide seedphrase on import
MetaMask/metamask-mobile pull request #1794
Opened 2020-08-25 16:44 UTC by rickycodes

**Description**

Similar to https://github.com/MetaMask/metamask-extension/pull/8730 this makes it so the seedphrase is hidden by default on import so the user can paste it in without showing it on device:

![image](https://user-images.githubusercontent.com/675259/91202988-92e09800-e6d0-11ea-8236-b670c3163130.png)

If the user absolute needs to see their seedphrase on screen they can show it with the "eye":

![image](https://user-images.githubusercontent.com/675259/91203085-b3a8ed80-e6d0-11ea-9c9b-403fd151bc7b.png)

We may want to change the placeholder text (similar to what we did on the extension) as well.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2020-08-26 02:47 UTC, EtDu approved these changes
+++

2020-09-09 22:20 UTC, ibrahimtaveras00 approved these changes
QA Passed 👍

2020-09-22 23:06 UTC, ibrahimtaveras00 requested changes
For iOS, I'm unable to type or paste into the seedphrase text input field.  The only way to get it to work is to tap Show to expand the field.  Android works as expected.

2020-09-23 20:32 UTC, ibrahimtaveras00 approved these changes
QA Passed 👍

2020-09-23 20:39 UTC, merged