Bugfix/post v1 aug 2020
MetaMask/metamask-mobile pull request #1797
Opened 2020-08-26 17:01 UTC by rickycodes

**Description**

This is a grouping of PRs to clean things up a bit and make review/QA a bit easier on @ibrahimtaveras00.
this PR includes the following work:

#1781 (this has been approved, this is just a code change, no functionality changed)
#1759 (this is a bugfix and needs QA)
#1728 (just some code cleanup, no functionality changed)
#1787 (add missing currencies, in particular SAI and INR)

2020-08-26 20:11 UTC, estebanmino commented on app/components/Views/AccountBackupStep1/index.js
> +					<OnboardingProgress steps={steps} currentStep={1} />
is this component used in other places? if not maybe we could put the steps cont in the component itself

2020-08-26 20:11 UTC, estebanmino commented on app/components/Views/AccountBackupStep1B/index.js
> +		strings('choose_password.confirm')
I see the same steps than before here

2020-08-26 20:12 UTC, estebanmino commented on app/components/Views/ImportWallet/index.js
> +			await AsyncStorage.removeItem(NEXT_MAKER_REMINDER);
I believe we don't need this item anymore, I erased the code for the reminder alert while ago

2020-08-26 21:37 UTC, rickycodes commented on app/components/Views/AccountBackupStep1/index.js
> +					<OnboardingProgress steps={steps} currentStep={1} />
it's used in other places, but I've de-duplicated things a bit by moving the steps variables into a new `/constants` file now

2020-08-26 21:38 UTC, rickycodes commented on app/components/Views/AccountBackupStep1B/index.js
> +		strings('choose_password.confirm')
https://github.com/MetaMask/metamask-mobile/pull/1797#discussion_r477604140

2020-08-26 21:44 UTC, rickycodes commented on app/components/Views/ImportWallet/index.js
> +			await AsyncStorage.removeItem(NEXT_MAKER_REMINDER);
It's still all over `develop` from what I am seeing :eyes: https://github.com/MetaMask/metamask-mobile/blob/master/app/components/Views/CreateWallet/index.js#L121

If you think we can delete all the `nextMakerReminder` AsyncStorage calls we probably should. I suggest we make sure and then possible do the redaction in a second pull request?

I did find one place where I missed a constant (from pedro's changes). I'm going to add that one.

2020-09-01 20:01 UTC, estebanmino approved these changes

2020-09-08 22:40 UTC, ibrahimtaveras00 requested changes
Few issues mentioned to @rickycodes

2020-09-10 04:22 UTC, rickycodes commented
@ibrahimtaveras00 this one should be good-to-go again!

2020-09-11 20:09 UTC, ibrahimtaveras00 approved these changes
Fixes look good, QA Passed 👍

2020-09-11 20:26 UTC, merged