Add safety to toLowerCase calls
MetaMask/metamask-mobile pull request #1854
Opened 2020-09-26 22:08 UTC by rickycodes

**Description**

We're using `toLowerCase()` in quite a few places in the codebase without actually checking what the value of the item is.

eg:
```
> undefined.toLowerCase()
Thrown:
TypeError: Cannot read property 'toLowerCase' of undefined
```

While we should ensure that things are indeed being set in predictable ways, we can add some guardrails by verifying the value is set before calling `toLowerCase()`

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

This resolves at least two problems that I am seeing on Sentry

2020-09-26 22:13 UTC, rickycodes commented on app/components/UI/DrawerView/index.js
> +										const { name = undefined } = item;
use option chaining for and default values so we're not calling `toLowerCase()` on undefined values

there's a bug here from the `item.name.toLowerCase()` where `name` is `undefined` on sentry: https://sentry.io/organizations/metamask/issues/1903751096/?project=2299799&query=is%3Aunresolved+toLowerCase&statsPeriod=14d

2020-09-26 22:15 UTC, rickycodes commented on app/components/Views/ChoosePassword/index.js
> +			});
check if biometryType is not null or undefined before calling `.toLowerCase()` and fallback to null

2020-09-26 22:16 UTC, rickycodes commented on app/components/Views/ChoosePassword/index.js
> +						<Text style={styles.biometryLabel}>{strings(`biometrics.enable_${biometryType}`)}</Text>
we don't need to call `.toLowerCase()` in the `render()` method any more because it's being called when it's set in state

2020-09-26 22:17 UTC, rickycodes commented on app/components/Views/ImportFromSeed/index.js
> +			});
same as https://github.com/MetaMask/metamask-mobile/pull/1854/files#r495500874

2020-09-26 22:18 UTC, rickycodes commented on app/components/Views/ImportFromSeed/index.js
> +					<Text style={styles.biometryLabel}>{strings(`biometrics.enable_${this.state.biometryType}`)}</Text>
same as https://github.com/MetaMask/metamask-mobile/pull/1854/files#r495500931

2020-09-26 22:18 UTC, rickycodes commented on app/components/Views/Login/index.js
> +					biometryType: (biometryType && biometryType.toLowerCase()) || null,
same as https://github.com/MetaMask/metamask-mobile/pull/1854/files#r495500944

2020-09-26 22:19 UTC, rickycodes commented on app/components/Views/Login/index.js
> +					<Text style={styles.biometryLabel}>{strings(`biometrics.enable_${biometryType}`)}</Text>
same as https://github.com/MetaMask/metamask-mobile/pull/1854/files#r495501005

2020-09-26 22:23 UTC, rickycodes commented on app/components/Views/Settings/SecuritySettings/index.js
> +			biometryType: (biometryType && biometryType.toLowerCase()) || null,
same as https://github.com/MetaMask/metamask-mobile/pull/1854/files#r495501044

2020-09-26 22:23 UTC, rickycodes commented on app/components/Views/Settings/SecuritySettings/index.js
> +							<Text style={styles.title}>{strings(`biometrics.enable_${this.state.biometryType}`)}</Text>
same as https://github.com/MetaMask/metamask-mobile/pull/1854/files#r495501100

2020-09-28 05:11 UTC, rickycodes commented on app/components/UI/DrawerView/index.js
> +										const { name = undefined } = item;
after thinking about this we should probably sort out why `name` isn't set in the first place :thinking:

2020-10-13 14:44 UTC, andrepimenta requested changes
I made some comments, the same comments apply to the other similar situations

2020-10-13 14:44 UTC, andrepimenta commented on app/components/Views/ChoosePassword/index.js
> +			});
Here I think we are already checking if biometryType is not null or undefined on line 247 right?

2020-10-13 14:44 UTC, andrepimenta commented on app/components/Views/ChoosePassword/index.js
> +						<Text style={styles.biometryLabel}>{strings(`biometrics.enable_${biometryType}`)}</Text>
I don't know if we want to set the lower case value on the state because we are using the state here for example: 				`await AsyncStorage.setItem(BIOMETRY_CHOICE, this.state.biometryType);`. And probably we need the normal (not lower case) value to be set?

2020-10-13 14:44 UTC, andrepimenta commented on app/components/Views/Login/index.js
> +					biometryType: (biometryType && biometryType.toLowerCase()) || null,
Here I think we are also checking for the biometryType before on line 157

2020-10-13 14:44 UTC, andrepimenta commented on app/components/UI/DrawerView/index.js
> +										const { name = undefined } = item;
This makes sense

2020-10-19 16:18 UTC, rickycodes commented
closing for now

2020-10-19 16:18 UTC, closed without merging