Unify Custom Gas Components
MetaMask/metamask-mobile pull request #1860
Opened 2020-09-29 10:28 UTC by EtDu

**Description**

This refactor aims to combine the `CustomGas` components inside `UI` & `SendFlow` to enable better code maintenance and error resolution surrounding gas errors.

**Checklist**

- [ ] Remove redundant `TransactionEdit` component
- [ ] Create a middle component to handle screen transitions/animations
- [ ] Unify `CustomGas` components

https://trello.com/c/TyjdNnRN/228-unify-customgas-components-for-dapp-wallet-txs

2020-10-12 15:22 UTC, EtDu commented
@ibrahimtaveras00 QA notes:
- Test the Approve and dApp transaction modals
- Test the wallet send flow

General review notes:
- One diff contains all the animation/transition logic. This can be ignored, as it was simply moved from one location to another.
- Animations for custom gas now work for Approve, dApp transactions and wallet send flow. There are some animations that still need to be implemented at some point for Approve.

2020-10-13 20:23 UTC, estebanmino commented on app/components/UI/AnimatedTransactionModal/index.js
> +		editToAdvancedValue: new Animated.Value(0),
any specific reason these are on state? I think this could be done under a component variable, there's no need to update this on state

2020-10-13 20:23 UTC, estebanmino commented on app/components/UI/AnimatedTransactionModal/index.js
> +		editToAdvancedValue: new Animated.Value(0),
`reviewToEditValue`,`reviewToDataValue` and `editToAdvancedValue`

2020-10-13 20:27 UTC, estebanmino commented on app/components/UI/AnimatedTransactionModal/index.js
> +						{React.cloneElement(components[1], {
I see you checked for components length to define some properties, us this always defined?

2020-10-13 20:32 UTC, estebanmino commented on app/components/UI/CustomGas/index.js
> +		if (hexToBN(fromAccount.balance).lt(gas.mul(gasPrice).add(toBN(value))))
I think if checksummedFrom is '' this is going to crash

2020-10-13 20:41 UTC, estebanmino commented on app/components/UI/AnimatedTransactionModal/index.js
> +class AnimatedTransactionModal extends PureComponent {
I'm a bit confused about this component's utility. This only handles animations right?

2020-10-13 20:41 UTC, estebanmino commented on app/components/UI/AnimatedTransactionModal/index.js
> +						{React.cloneElement(customGasComponent, {
I think there's an opportunity to deduplicate code from https://github.com/MetaMask/metamask-mobile/pull/1860/files#diff-35ecbe8bc085d0b73e845cb41c95ce841926077dd9a17254b10d1e54e419c2d0R208

2020-10-14 03:57 UTC, EtDu commented on app/components/UI/AnimatedTransactionModal/index.js
> +		editToAdvancedValue: new Animated.Value(0),
Cool, updated

2020-10-14 04:01 UTC, EtDu commented on app/components/UI/AnimatedTransactionModal/index.js
> +						{React.cloneElement(components[1], {
That's a good point, if you don't pass down children it will be undefined. I've added some optional chaining to fix this

2020-10-14 04:05 UTC, EtDu commented on app/components/UI/CustomGas/index.js
> +		if (hexToBN(fromAccount.balance).lt(gas.mul(gasPrice).add(toBN(value))))
I don't know why that's there, removed

2020-10-14 04:06 UTC, EtDu commented on app/components/UI/AnimatedTransactionModal/index.js
> +class AnimatedTransactionModal extends PureComponent {
Yeah, the idea is to contain all the animation logic in this component to keep it clean and aintainable, instead of having it scattered throughout other components

2020-10-14 04:55 UTC, EtDu commented on app/components/UI/AnimatedTransactionModal/index.js
> +						{React.cloneElement(customGasComponent, {
Good point, done

2020-10-22 18:46 UTC, estebanmino approved these changes

2020-10-23 20:47 UTC, ibrahimtaveras00 requested changes
**Issue 1:**

In send flow, when I change from slow/average/fast and return to the modal it always defaults to average (this works in dapp gas modal) seen here = https://recordit.co/cP8kdpTdYx

**Issue 2:**

On android, I cannot save when editing advanced gas on neither send flow, nor dapp flow; seen here = https://recordit.co/qmCV4qqjCa

2020-10-26 14:35 UTC, EtDu commented
Issue 1 is fixed.
For issue 2, I couldn't figure out why the button is disabled.

2020-11-09 21:50 UTC, ibrahimtaveras00 approved these changes
QA Passed 👍

2020-11-09 22:14 UTC, merged