Bugfix/deeplink, request modals and wallet connect
MetaMask/metamask-mobile pull request #1877
Opened 2020-10-07 00:08 UTC by estebanmino

**Description**

This PR include

1. refactor of the `Entry` and  `Main` components to hooks. The problem with these component was the state handling, it was messy so we were having problems with all the modals on  `Main`.

2. WalletConnect version update and added a way to handle wallet connect requests when the app is locked.

3. Deeplinks are being erased if the app is closed, to not get the request when the app is opened again without context.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves https://github.com/MetaMask/metamask-mobile/issues/1798
Resolves https://github.com/MetaMask/metamask-mobile/issues/1804

2020-10-07 23:46 UTC, ibrahimtaveras00 requested changes
Android doesn't progress pass splash screen 
iOS I'm unable to get any deeplinks to work 

built with METAMASK_ENVIRONMENT='production' yarn build:ios:release and detox build -c android.emu.release && detox test -c android.emu.release

2020-10-08 06:30 UTC, rickycodes requested changes
left a few comments/question. admittedly, I need to brush up on react hooks... most of where we used them previously i was able to understand, but there's a lot of changes here. I may need to take another look at this tomorrow with a fresh set of eyes.

2020-10-08 06:30 UTC, rickycodes commented on app/core/WalletConnect.js
> +	while (!KeyringController.isUnlocked()) {
does the `KeyringController` not have an unlock event we can listen for? checking every second for a whole minute seems _not_ ideal :thinking:

i see on the extension `KeyringController` extends `EventEmitter` which seems like a better pattern.

2020-10-08 06:30 UTC, rickycodes commented on app/components/Nav/Main/index.js
> +					(value === '0x0' || !value) &&
rather than doing all the magic directly in an if condition what if instead we outline what the constraints are separately? I think that will make things a bit easier to understand.

something like:

```js
const valueIsEmpty = value === '0x0' || !value;
const dataIsNotEmpty = data && data !== '0x';
...

if (valueIsEmpty && dataIsNotEmpty && ...)
```

2020-10-08 06:30 UTC, rickycodes commented on app/components/Nav/Main/index.js
> +				transactionMeta.transaction.data &&
does `transactionMeta` always have a `transaction` key? what happens if it doesn't? you could use optional chaining here to be safe

2020-10-08 06:30 UTC, rickycodes commented on app/components/Nav/Main/index.js
> +		// Force unmount the webview to avoid caching problems
Why do we have to do this?

2020-10-08 12:01 UTC, estebanmino commented on app/components/Nav/Main/index.js
> +					(value === '0x0' || !value) &&
this is payment channel stuff which we're deprecating, I think we shouldn't spend time on this (in fact I was deleting it https://github.com/MetaMask/metamask-mobile/pull/1877/commits/acd5d434635f62397f0500efded0e22d4c8a02dc)

2020-10-08 12:01 UTC, estebanmino commented on app/components/Nav/Main/index.js
> +				transactionMeta.transaction.data &&
payment channel stuff

2020-10-08 12:02 UTC, estebanmino commented on app/components/Nav/Main/index.js
> +		// Force unmount the webview to avoid caching problems
is to mount `MainNavigator` on language change

2020-10-08 12:03 UTC, estebanmino commented on app/core/WalletConnect.js
> +	while (!KeyringController.isUnlocked()) {
we don't have that on `controllers` KeyringController

2020-10-09 00:21 UTC, ibrahimtaveras00 commented
After retesting, here are the following issues:

**Issue 1:**

Android still isn't moving past the splash screen

**Issue 2:** 

I'm unable to open deeplinks/Wallet Connect when the app is either in the background and locked, or completely in a killed state

also too, as a side not, I'm in a broken state when I attempt to do this, seen here = http://recordit.co/Flpx8M1fyG 
the app stays with a white loading screen on browser, and none of my account information is displayed

![Screen Shot 2020-10-08 at 8 08 37 PM](https://user-images.githubusercontent.com/41752922/95525560-3e545c00-09a2-11eb-9756-a0efa9d062f0.png)

![Screen Shot 2020-10-08 at 8 08 51 PM](https://user-images.githubusercontent.com/41752922/95525598-414f4c80-09a2-11eb-8471-5230cb7dd988.png)

This currently works on iOS build 525 seen here = http://recordit.co/67bKuGHqLF

 **Issue 3:**

When you are going via Wallet connect (in this scenario I had uniswap.exchange open on Safari and came to MM via wallet connect), it shows the wrong title URL on the approve modal.  Furthermore, when I kill the app and relaunch, I'm no longer able to see the ERC-20 token I want to swap to; seen here = https://recordit.co/zPi5Z8hxOo

<img width="411" alt="Screen Shot 2020-10-08 at 8 19 44 PM" src="https://user-images.githubusercontent.com/41752922/95527589-af484380-09a3-11eb-9d9e-fa2546470d28.png">

You can also follow [this thread](https://consensys.slack.com/archives/GBW7S9FSN/p1601335976059900) for more information

2020-10-15 17:05 UTC, andrepimenta approved these changes
LGTM! 👍

2020-10-19 20:57 UTC, ibrahimtaveras00 requested changes
Real iOS device used on testflight build 1.0.5 (532) = iPhone X OS 13.7
Android apk = Pixel 2

**Issue 1:**  Fixed 

**Issue 2:**
The broken state part is fixed, however, I'm still unable to open any deep link on iOS when the app is in background/locked/or killed state.

On android it only works if the app is completely killed.

Killed state = https://recordit.co/y6Tld4TStU
Locked state = https://recordit.co/037QPM1Hq8
app in background and not locked =https://recordit.co/wKcCQSAHkM

**Issue 3:** 

I couldn't retest this as it still doesn't work on iOS (as above) nor on android; seen here = http://recordit.co/8uCB8rmVwI

New issues...

**Issue 4:** 

This happens when I sync with extension or when I search tokens on wallet > add tokens

![Screen Shot 2020-10-16 at 4 25 35 PM](https://user-images.githubusercontent.com/41752922/96510934-49be4780-122c-11eb-86c5-e9bde099bf37.png)

**Issue 5:** 

Now android is asking for my fingerprint twice when just launching the app normally

2020-10-22 00:41 UTC, ibrahimtaveras00 requested changes
**Issue 2:** 
Still an issue according to the following:

on iOS:
- can't open deeplink in locked state
- can't open deeplink in killed state 

on android:
- can't open deeplink in locked state

**Issue 3**
Fixed, however, when I relaunch app, iOS doesn't show me the modal which is correct, but on Android, I still see the modal in a broken state

**Issue 4** = fixed

**Issue 5** = fixed on both OS's

2020-10-23 23:14 UTC, ibrahimtaveras00 requested changes
Issue 2 and Issue 3 still exist

**For issue 2**

Both OS's pass for background state 👍 

However the following scenarios are still failing.

- killed state on iOS 

URL example = https://recordit.co/1WSPanYeib
to reproduce this, kill app and open this deeplink = https://metamask.app.link/dapp/uniswap.eth

WC example = https://recordit.co/q2UtgNXrlt
to reproduce this kill app, and try to connect to wallet connect while in safari https://example.walletconnect.org/ 

Approve example = http://recordit.co/7kCSQqMkfB
I created this deeplink by going to https://brunobar79.github.io/eip681-link-generator/# with the following ethereum:0x1d7a9cd8c67e3c74a84bb76cbc1b606e2e460db5@4/approve?address=0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6&uint256=1

Payment request example = http://recordit.co/o29lXfczlb
To reproduce this kill app and click on this deeplink = https://metamask.app.link/send/0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6@4?value=1e15

- Locked state on both OS's are failing 

URL example seen here = https://recordit.co/7R0E753mkM
to reproduce this go to settings > security & privacy and change your Auto-lock to immediately and then go to chrome/safari web browser or click on this link https://metamask.app.link/dapp/uniswap.eth

Wallet connect example = seen here = http://recordit.co/yJvRicB2bu
to reproduce this go to settings > security & privacy and change your Auto-lock to immediately and then go to chrome/safari web browser and go to wallet connect and attempt to connect while MM is locked

Approve seen here = http://recordit.co/4nVly5RGq3
Attempt to open the deeplink while MM app is locked
I created this deeplink by going to https://brunobar79.github.io/eip681-link-generator/# with the following ethereum:0x1d7a9cd8c67e3c74a84bb76cbc1b606e2e460db5@4/approve?address=0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6&uint256=1

Payment request example seen here = http://recordit.co/1jeSYnwcFx
to reproduce this go to settings > security & privacy and change your Auto-lock to immediately and then go to chrome/safari web browser to create a deeplink or just click on this link = https://metamask.app.link/send/0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6@4?value=1e15

**For Issue 3**
This works on iOS now, however, still fails on Android; seen here = http://recordit.co/ynZBE9znLK

I created this deeplink by going to https://brunobar79.github.io/eip681-link-generator/# with the following ethereum:0x1d7a9cd8c67e3c74a84bb76cbc1b606e2e460db5@4/approve?address=0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6&uint256=1
Now open this deeplink in MM browser, and once the approve modal is displayed kill the app and relaunch

**Issue 6:**

Not sure if this was newly introduced here, or exists on develop or not but when I QA'd https://github.com/MetaMask/metamask-mobile/pull/1847 when I had the MM wallet open and tapped on the QR code scanner and scanned the following QR code the approve modal would pop up, however, now it doesn't and just takes me to Send flow

![image](https://user-images.githubusercontent.com/41752922/97061166-e0a83e00-1563-11eb-9e81-576c2368271b.png)

seen here = http://recordit.co/SLsQrYvaK5

2020-10-30 18:18 UTC, ibrahimtaveras00 requested changes
All issues have been resolved on Android 

With iOS, the only outstanding issue is that in a killed, or locked state deeplinks will not work on a device that has biometrics enabled (FaceID or TouchID)

similar to https://github.com/MetaMask/metamask-mobile/issues/1798

2020-11-02 21:05 UTC, ibrahimtaveras00 requested changes
Only 1 scenario fails on both OS's:

When you have the app in a locked state and you're not on the wallet view
 
ios = http://recordit.co/8sEuCj1qyp
Android = https://recordit.co/LnIdgLJavd

This nonetheless works if you have a device without biometrics and use your password to log in

2020-11-03 23:33 UTC, ibrahimtaveras00 requested changes
Wallet connect is now fixed on both OS's 👍 

However, there are now 2 places of failure on both OS's

1) Payment request isn’t working when app is in a locked state (set to immediately)

Seen here = http://recordit.co/uyQfcwuGXF

As you can see it opens to the correct view then immediately closes the view

2) Scanning a public address is not working as it should
Ever since https://github.com/MetaMask/metamask-mobile/pull/1859 when a user scans a public address QR code, they should be sent to the send to view

Seen here = http://recordit.co/JmRNIYrhl8

2020-11-05 00:10 UTC, ibrahimtaveras00 approved these changes
fixes look good on both OS's, QA Passed 👍

2020-11-05 00:27 UTC, merged