Add protect reminder section to settings
MetaMask/metamask-mobile pull request #1892
Opened 2020-10-15 14:40 UTC by rickycodes

**Description**

WIP: https://github.com/MetaMask/mobile-planning/issues/15

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2020-10-26 05:19 UTC, rickycodes commented on app/components/Views/ChoosePassword/index.js
> +		const previousScreen = this.props.navigation.getParam(PREVIOUS_SCREEN);
this has been wrong for _a while_...

`PREVIOUS_SCREEN` is no longer in `AppConstants` :woman_facepalming:

2020-10-26 05:21 UTC, rickycodes commented on app/components/Views/ManualBackupStep3/index.js
> +import { ONBOARDING_WIZARD, METRICS_OPT_IN, SEED_PHRASE_HINTS } from '../../../constants/storage';
made this into a constants... it's a shame we broke our convention of `@MetaMask:*` for this key... we should try not to do this in the future.

2020-10-28 23:48 UTC, ibrahimtaveras00 requested changes
**Issue 1:**

<strike>As soon as I install the app, and create a wallet, and skip backup, then go to settings > security & privacy, I get this warning 

![image](https://user-images.githubusercontent.com/41752922/97507960-c64fd500-1954-11eb-9766-ae01079274fb.png)</strike>


**Issue 2:**

When I'm in the above state, (I install the app, and create a wallet, and skip backup, then go to settings > security & privacy) and tap back up now CTA android immediately asks me for my password, however, iOS doesn't ask me for my password

seen here = http://recordit.co/IRyQlm8pcT

Something weird though, when I have a real device with biometrics enabled (FaceID) I do see it ask me to scan my face; seen here = http://recordit.co/MX1VgM3ykH

Also, when you do end up actually backing up your seedphrase, and then tap on back up again, it does indeed ask for password on all scenarios (biometrics or no biometrics) seen here = http://recordit.co/XqoR5unIk1


**Issue 2A:**

<strike>In addition, the left title is overlapping with the METAMASK title on iOS

![image](https://user-images.githubusercontent.com/41752922/97508341-be446500-1955-11eb-8a99-e2dcd5bd6be7.png)</strike>


**Issue 3:**

When attempting to change password, the first view asks to enter current password, however, on devices I have biometrics enabled I don’t see the option to use biometrics to pass this step, is that intended? 

seen here = http://recordit.co/PPPrnECo8k

**Issue 4:**

I don’t see the alert that my password was updated on Android 

Seen here = http://recordit.co/DayEQ6m35F

**Issue 5:**

<strike>Once backing up again and going through the flow, the hint shows up as empty, but when going back to settings after completing flow, the hint is still there 

Seen here = http://recordit.co/U24uQ01XWG</strike>

**Issue 6:**

<strike>So if I have a fresh install of the app and import my wallet, I don't see the congratulations confetti screen, however, if I already have a wallet installed, log out, and then go to import via this flow, it does work.

Seen here = http://recordit.co/uMDqWOT1Xw</strike>

2020-10-29 20:48 UTC, ibrahimtaveras00 commented
**Issue 7:**

Change password should be secondary button outline 

**Issue 8:**

If we could use smaller font and center align the copy here (to match font sizes of next screen: cc @cjeria)

![Screen Shot 2020-10-29 at 4 45 55 PM](https://user-images.githubusercontent.com/41752922/97630643-441fe900-1a06-11eb-9145-bb2f63b8cdca.png)

Also we're repeating the change password text on this screen

![Screen Shot 2020-10-29 at 4 47 03 PM](https://user-images.githubusercontent.com/41752922/97630773-67e32f00-1a06-11eb-9429-58cf264e3f3e.png)

2020-10-30 01:05 UTC, swornov commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 70.85pt 70.85pt 70.85pt;}
div.WordSection1
	{page:WordSection1;}
-->Thx alot my friend you did an awsome job  😉 you are the best   Verzonden vanuit Mail voor Windows 10 Van: Ibrahim TaverasVerzonden: donderdag 29 oktober 2020 21:48Aan: MetaMask/metamask-mobileCC: SubscribedOnderwerp: Re: [MetaMask/metamask-mobile] Reminder to backup seed phrase (#1892) Issue 7:Change password should be secondary button outlineIssue 8:If we could use smaller font and center align the copy here (to match font sizes of next screen: cc @cjeria)Also we're repeating the change password text on this screen—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. 

2020-11-02 17:48 UTC, rickycodes commented
I don't think we should be addressing any design related issues in this PR. Like centring the text for the password confirmation screen... I am merely reusing components as they appear in the application today... if those components need to be tweaked or redesigned they should be addressed in a separate PR. there's already a bunch of changes in here that are outside the scope of the original task.

2020-11-02 18:18 UTC, cjeria commented
@rickycodes totally understand, however, the original task/design suggests specific UI patterns that do fit into the scope. Also, we're not suggesting we change the original components since they work in other parts of the app so those should likely not be changed, rather we might need to add variations of those components so that they work in different contexts. 

>  those components need to be tweaked or redesigned they should be addressed in a separate PR.
Sounds good. I'd suggest we make these tweaks next so we don't forget about them. cc @omnat WDYT?

2020-11-02 20:22 UTC, ibrahimtaveras00 approved these changes
👍

2020-11-03 04:31 UTC, rickycodes commented on app/components/UI/StyledButton/styledButtonStyles.js
> +		...fontStyles.bold
`...fontStyles.bolder` doesn't exist

2020-11-03 13:25 UTC, andrepimenta requested changes
Just added small comments/questions. But overall looks good! 👌

2020-11-03 13:25 UTC, andrepimenta commented on android/build.gradle
> +		classpath('com.android.tools.build:gradle:4.1.0')
Could you explain more this change? Is it because of a lib?

2020-11-03 13:25 UTC, andrepimenta commented on app/components/UI/BackupAlert/index.js
> +		onDismiss: PropTypes.func
Could you add a small description to follow convention?

2020-11-03 13:25 UTC, andrepimenta commented on app/components/Views/ManualBackupStep3/index.js
> +		this.steps = props.navigation.getParam('steps') || undefined;
Here I think you can use` props.navigation.getParam(value, defaultValue)`. So `props.navigation.getParam('steps', undefined);`

2020-11-03 13:25 UTC, andrepimenta commented on app/components/Views/ResetPassword/index.js
> +import React, { PureComponent } from 'react';
For new components would be nice to start using functional components (I saw you did this in other components which is nice!). I guess the reason for this one not to be a functional component is because it is very similar to other components that already implemented authentication logic no?

2020-11-03 13:25 UTC, andrepimenta commented on app/components/Views/Settings/SecuritySettings/index.js
> +		seedphraseBackedUp: PropTypes.bool
Could you add a comment to follow convention?

2020-11-03 15:57 UTC, rickycodes commented on android/build.gradle
> +		classpath('com.android.tools.build:gradle:4.1.0')
this was just studio asking me to update Gradle. it doesn't really need to be included in this PR, but I figured why not?

2020-11-03 15:59 UTC, rickycodes commented on app/components/Views/ResetPassword/index.js
> +import React, { PureComponent } from 'react';
Yea, exactly. `ResetPassword` is almost a direct copy of `CreatePassword` with just some small modifications. Ideally it would have been nice to break things up a bit more and reuse some logic and _not_ have another class component, but it was easier to just copy/paste.

2020-11-03 16:11 UTC, andrepimenta commented on android/build.gradle
> +		classpath('com.android.tools.build:gradle:4.1.0')
Do you know if this is safe to do? I am not sure now

2020-11-03 16:22 UTC, rickycodes commented on android/build.gradle
> +		classpath('com.android.tools.build:gradle:4.1.0')
I've done it in the past: https://github.com/MetaMask/metamask-mobile/pull/1801, but if it makes sense I can take it out and do it in another PR

2020-11-03 16:38 UTC, andrepimenta approved these changes

2020-11-03 19:42 UTC, merged