Fix KeyboardAvoidingView behavior on android
MetaMask/metamask-mobile pull request #1903
Opened 2020-10-20 17:47 UTC by rickycodes

**Description**

This fixes an issue I noticed with the `KeyboardAvoidingView` affecting smaller android devices:

before:

![before](https://user-images.githubusercontent.com/675259/96624445-bf80ec80-12da-11eb-88fa-44d4229d97b9.gif)

after:

![after](https://user-images.githubusercontent.com/675259/96624471-c7409100-12da-11eb-85fc-2c47b4752b7b.gif)

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2020-10-29 00:28 UTC, ibrahimtaveras00 approved these changes
QA Passed 👍

2020-10-29 17:25 UTC, andrepimenta approved these changes

2020-11-04 04:17 UTC, ibrahimtaveras00 requested changes
amount view looks a bit off = http://recordit.co/aN4SOb6t20 (a bit smaller wiggle room compared to live version)

live version = http://recordit.co/IgHpR7jxR1

2021-01-08 03:28 UTC, rickycodes commented
closing this one for now

2021-01-08 03:28 UTC, closed without merging