Add missing env keys for OPENSEA and INFURA
MetaMask/metamask-mobile pull request #1908
Opened 2020-10-23 16:37 UTC by rickycodes

**Description**

Just adding some missing env keys

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2020-10-26 16:57 UTC, andrepimenta requested changes

2020-10-26 16:57 UTC, andrepimenta commented on .android.env.example
> +export MM_FABRIC_API_KEY=
We should add this to iOS env as well right?

2020-10-26 18:21 UTC, estebanmino commented on .android.env.example
> +export MM_FABRIC_API_KEY=
we're not using this key anywhere I believe

2020-10-30 15:45 UTC, andrepimenta approved these changes

2020-11-03 16:14 UTC, merged