Fix QR send
MetaMask/metamask-mobile pull request #1916
Opened 2020-10-27 18:51 UTC by andrepimenta

**Description**

PR that fixes QR code send flow.

2020-10-28 00:25 UTC, rickycodes commented on app/core/DeeplinkManager.js
> +				onHandled && onHandled();
maybe we could consolodate these into a single method? eg:

```
const handle = () => onHandled && onHandled();
```
and then just call that?

2020-10-30 00:09 UTC, ibrahimtaveras00 commented
All scenarios look good to me 👍 

There's just 2 instances where I noticed we don't provide any feedback and just keep you on the send to screen:
1) when you're on the send to view and you scan a private key QR code
2) when you're on the send to view and you scan a seed phrase QR code

Do we want to do anything in this regard @andrepimenta @omnat @cjeria 

This is what we currently do if a user is on the wallet screen and they scan such things:
- Private Key

![Screen Shot 2020-10-29 at 7 59 00 PM](https://user-images.githubusercontent.com/41752922/97645160-88b97d80-1a22-11eb-96c5-eabcd9741709.png)

-  Seed phrase

![Screen Shot 2020-10-29 at 7 59 15 PM](https://user-images.githubusercontent.com/41752922/97645170-8ce59b00-1a22-11eb-83cc-4014edd974e8.png)

Perhaps we send them to wallet with this messaging and continue from there?

2020-10-30 00:10 UTC, ibrahimtaveras00 approved these changes

2020-11-03 05:08 UTC, rickycodes requested changes

2020-11-03 05:08 UTC, rickycodes commented on locales/en.json
> +		"continueError": "I understand the risks, continue"
`es.json`?

2020-11-04 18:19 UTC, omnat commented
@andrepimenta @cjeria based off of our discussion in team standup, could we remove the warning when user enters just a contract address (which isn't a token address)?
It's totally my bad for not considering the case where people are actually intending to send tokens to smart contract accounts. I agree with Dan that the user error/mistakes are most of the times when sending to token addresses.

2020-11-04 21:13 UTC, andrepimenta commented on locales/en.json
> +		"continueError": "I understand the risks, continue"
Added!

2020-11-04 21:14 UTC, rickycodes commented on app/core/DeeplinkManager.js
> +		const handled = () => onHandled?.();
:heart_eyes:

2020-11-04 21:14 UTC, rickycodes approved these changes
:+1:

2020-11-04 21:20 UTC, andrepimenta commented
> @andrepimenta @cjeria based off of our discussion in team standup, could we remove the warning when user enters just a contract address (which isn't a token address)?
> It's totally my bad for not considering the case where people are actually intending to send tokens to smart contract accounts. I agree with Dan that the user error/mistakes are most of the times when sending to token addresses.

Done it will show a warning:
![Simulator Screen Shot - iPhone 11 Pro - 2020-11-04 at 20 32 15](https://user-images.githubusercontent.com/4960833/98169092-8a33eb80-1ee3-11eb-91fe-b412f2f21f07.png)

2020-11-05 00:35 UTC, ibrahimtaveras00 approved these changes
Update looks good on both OS's 👍

2020-11-06 00:47 UTC, ibrahimtaveras00 approved these changes
Latest fixes look good 👍

2020-11-06 00:49 UTC, merged