Replace public config with rpc
MetaMask/metamask-mobile pull request #1987
Opened 2020-11-12 11:45 UTC by andrepimenta

**Description**

This PR replaces public config with rpc. Introduces `unlockStateChanged` and `chainChanged` notifications and `wallet_getProviderState` rpc method.

2020-11-20 19:33 UTC, ibrahimtaveras00 approved these changes
QA Passed 👍

2020-11-25 01:12 UTC, rekmarks requested changes
This implementation LGTM! However, before merging this, https://github.com/MetaMask/mobile-provider/pull/41 must be merged, and `mobile-provider` must be updated with `@metamask/inpage-provider@7.0.0`, once that's published. Then `mobile-provider` needs to be updated here as well, probably in this PR.

2020-11-25 01:12 UTC, rekmarks commented on app/components/Views/BrowserTab/index.js
> +	 * Disabling iframes for now´
Stray back-tick:
```suggestion
	 * Disabling iframes for now
```

2021-01-14 01:00 UTC, rekmarks commented
#2114 needs to be merged into this first.

2021-01-15 22:15 UTC, rekmarks commented
Since QA passed, we now need to publish `mobile-provider@2.0.0` and add it to this PR, then this can be merged.

2021-01-18 20:53 UTC, rekmarks commented on app/components/Views/BrowserTab/index.js
> +				metamask_getProviderState: async () => {
```suggestion
				/**
				 * This method is used by the inpage provider to get its state on
				 * initialization.
				 */
				metamask_getProviderState: async () => {
```

2021-01-18 20:55 UTC, rekmarks approved these changes
LGTM!

2021-01-18 20:59 UTC, merged