Feature: Initial Swaps amount view
MetaMask/metamask-mobile pull request #1994
Opened 2020-11-16 16:46 UTC by wachunei

**Description**

This PR adds the initial swaps amount view. For now slippage is fixed at 1%.

**Draft Checklist** 

* [x] Upgrade swaps controller to working cache 

**Checklist**

* [ ] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #???

2020-11-18 07:14 UTC, zech564 approved these changes

2020-11-18 07:15 UTC, zech564 approved these changes

2020-12-04 15:07 UTC, estebanmino approved these changes

2020-12-07 23:08 UTC, ibrahimtaveras00 requested changes
Only padding issue I saw was on Android Nexus S (4 inch screen) 

![Screen Shot 2020-12-07 at 6 06 06 PM](https://user-images.githubusercontent.com/41752922/101416001-e8733600-38b6-11eb-8a5c-79a1d844d8a3.png)

Nonetheless, you can scroll on this view so it's not too big of a problem

Another issue I saw was that the title Convert to or Convert from is cut off on smaller Android devices when keyboard is expanded when searching token list 

In this example, this is a pixel (5 inch screen) on left compared to iPhone SE 2nd generation

![Screen Shot 2020-12-07 at 6 08 13 PM](https://user-images.githubusercontent.com/41752922/101416148-36883980-38b7-11eb-8828-37fdd5884148.png)

2020-12-09 02:17 UTC, wachunei commented
I pushed an updated code with conditional height for the list depending wether the keyboard is open and the device size in order to keep the UI contained in the viewport at all times.

<img width="1674" alt="Screen Shot 2020-12-08 at 23 14 15" src="https://user-images.githubusercontent.com/1024246/101565216-5e58c980-39ab-11eb-8881-34dac8c894e3.png">
<img width="1673" alt="Screen Shot 2020-12-08 at 23 14 40" src="https://user-images.githubusercontent.com/1024246/101565225-63b61400-39ab-11eb-9ff0-ac9956acf42d.png">

2020-12-10 03:14 UTC, ibrahimtaveras00 approved these changes

2020-12-10 14:25 UTC, merged