Remove sync with extension from settings
MetaMask/metamask-mobile pull request #2044
Opened 2020-12-04 01:46 UTC by rickycodes

**Description**

Remove sync and update QR scan feedback as per bellow:

**Checklist**

* [x] Remove "Sync with extension" option from Settings
* [ ] Error handling when user scans the Sync with mobile QR code from extension wallet

Copy suggestion: “In order to Sync your MetaMask mobile wallet with your extension wallet, please re-install the app and choose the 'Import your extension wallet' option at onboarding.
Make sure your have your current wallet seed phrase safely backed up before uninstalling. Backup now (button that redirects to Settings > Security & Privacy)

* [ ] Also remove the ability to replace wallet (remove "Go back" button when user logs out)
    Consider adding copy somewhere to let user know that if they want to create/import new wallet, they need to re-install the app. 

**Issue**

Resolves #1950

2020-12-10 18:02 UTC, estebanmino commented on app/components/Views/Login/index.js
> +	isDev: process.env?.NODE_ENV === DEVELOPMENT
I think this could be moved as constant outside the component?

2020-12-10 18:49 UTC, estebanmino approved these changes
👌

2020-12-10 21:41 UTC, ibrahimtaveras00 requested changes
@cjeria @omnat Possible re-design on the removal of "Go Back"
cc @rickycodes

2020-12-10 21:42 UTC, ibrahimtaveras00 commented
Also bump security up in the settings list

2020-12-10 21:53 UTC, omnat commented
@cjeria syncing with Ibrahim on this one. We are talking how this direction might still make sense and doesn't require re-design. Happy to sync on it.

2020-12-10 22:04 UTC, cjeria commented
Here is a suggested design that mirrors what the extension does today
https://www.figma.com/proto/lcodxIQfO9j0nJwTBvPAYz/Forgot-Password?node-id=52%3A507&viewport=1059%2C657%2C1.0626369714736938&scaling=min-zoom

2020-12-14 19:34 UTC, cjeria commented
Here's another idea for removing the ability to restore from login and instead include direction for what do to if the user is locked out cc @omnat 
![image](https://user-images.githubusercontent.com/597770/102125834-1b5d8280-3dff-11eb-8669-ae87c5ad64b7.png)

2021-01-12 22:49 UTC, ibrahimtaveras00 approved these changes
QA Passed 👍🏽

2021-01-12 23:00 UTC, merged