Add Slippage Slider Component
MetaMask/metamask-mobile pull request #2068
Opened 2020-12-14 21:33 UTC by flamingYawn

**Description**

This pull request introduces a `SlippageSlider` component. Although it was designed for the amount of allowable slippage in a swap (1-5%), it has been created to be somewhat customizable to facilitate future cases of reusability:

* Custom ranges
* Custom tick increments
* A function to format the text/content in the tooltip

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves Issue #2026

2020-12-17 03:28 UTC, wachunei requested changes, later dismissed
It looks good 👍, I'd suggest these changes:

- safe range/step numbers as mentioned in the other comment (this is mostly a dev experience improvement)
- add a boolean prop to have `onChange` called when the slider snaps in place (we are most likely responding to a snap change in the ui than upon release)

2020-12-17 03:28 UTC, wachunei commented on app/components/UI/SlippageSlider/index.js
> +					{new Array(fullRange / increment + 1).fill(0).map((unused, i) => (
In the case is set an increment that is not a divisor of the range this would not be an integer and throws an exception. I would default to a sane case and throw a warning instead perhaps.

2020-12-23 23:41 UTC, wachunei commented
Refactor includes:
- Slider does not depend on device dimensions anymore
- Slider does not need to be centered in the screen
- Slider calls onChange when changing slider position (although it can be called only when gesture is finished by setting `changeOnRelease` prop to true
- All the position/layout was redone so changing paddings and diameters wont affect the positing
- Slider reacts to changed value from the props and sets the position correctly
- Gradient image was updated and stretches correctly, the rounded tips are overflows and not part of the image.
- When range is not divisible by increment the component won't crash
- PanHandlers are memoized (they were recreated every render)

2021-01-04 17:28 UTC, estebanmino commented on app/components/UI/SlippageSlider/index.js
> +// }).start();
do we need this?

2021-01-04 17:36 UTC, estebanmino commented on app/components/UI/SlippageSlider/index.js
> +				style={[styles.slider, { left: sliderPosition }, { backgroundColor: sliderColor }]}
```suggestion
				style={[styles.slider, { left: sliderPosition, backgroundColor: sliderColor }]}
```

2021-01-04 17:37 UTC, estebanmino commented on app/components/UI/Swaps/components/SlippageModal.js
> +							{slippage >= 5 && (
shouldn't this check be in the view above?

2021-01-04 17:41 UTC, wachunei commented on app/components/UI/Swaps/components/SlippageModal.js
> +							{slippage >= 5 && (
This is the modal itself (not the slider). I think the check and range values belong here instead of the amount view.


<img width="580" alt="Screen Shot 2021-01-04 at 14 39 34" src="https://user-images.githubusercontent.com/1024246/103562958-bdbad400-4e9a-11eb-80c0-5c25770bbe99.png">

2021-01-04 17:43 UTC, wachunei commented on app/components/UI/SlippageSlider/index.js
> +// }).start();
Removed 👌

2021-01-04 17:43 UTC, wachunei commented on app/components/UI/SlippageSlider/index.js
> +				style={[styles.slider, { left: sliderPosition }, { backgroundColor: sliderColor }]}
Fixed 👍

2021-01-05 00:42 UTC, merged