Feature/make insufficient fee descriptive
MetaMask/metamask-mobile pull request #2076
Opened 2020-12-16 04:51 UTC by rickycodes

**Description**

Make 'Insufficient fee' error descriptive & add link to Buy ETH

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2020-12-19 20:04 UTC, rickycodes commented on app/components/UI/TransactionReview/TransactionReviewInformation/index.js
> +import { withNavigation } from 'react-navigation';
rather than passing navigation through props, maybe we should adopt this pattern everywhere everywhere?

2020-12-21 21:07 UTC, rickycodes commented on app/components/Nav/Main/index.js
> +				navigation={props.navigation}
this is unrelated, but `Approval` was missing `navigation` prop. it needs it for this: https://github.com/MetaMask/metamask-mobile/blob/develop/app/components/Views/Approval/index.js#L92-L96. I've made the prop `isRequired` on it now so we don't do this

2020-12-21 21:12 UTC, rickycodes commented on app/components/UI/TransactionReview/TransactionReviewInformation/index.js
> +		navigation.navigate('PaymentMethodSelector');
it would be nice to be able to leave the transaction up and be able to get the user to buy eth and come back to the aforementioned transaction but it's not really possible here. I think for this rejecting is fine and the user can just go through the trouble of setting up the transaction again

2021-01-05 02:13 UTC, ibrahimtaveras00 requested changes
**Issue 1:**

I'm unable to scroll to see any of the messaging in this approve modal

![Screen Shot 2021-01-04 at 8 59 15 PM](https://user-images.githubusercontent.com/41752922/103598088-bbbf3800-4ecf-11eb-8ee1-97500270b8dd.png)

I got this view by using this deeplink:

https://metamask.app.link/approve/0x1d7a9cd8c67e3c74a84bb76cbc1b606e2e460db5@1/approve?address=0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6&uint256=1

**Issue 2:**

I do see it on the Dapp confirm modal and contract deployment modal, however, I'm wondering, should we still show the option to buy ETH on testnets not supported? 

For instance there's no option to buy ETH on Ropsten however, I see the link to buy ETH still

![Screen Shot 2021-01-04 at 9 03 34 PM](https://user-images.githubusercontent.com/41752922/103598396-7f400c00-4ed0-11eb-9212-2abf6c267396.png)

this is from https://metamask.github.io/test-dapp

**Issue 3:** 

I'm not seeing this option when I come from a request, am I supposed to?
cc: @cjeria 

![Screen Shot 2021-01-04 at 9 13 08 PM](https://user-images.githubusercontent.com/41752922/103598858-a945fe00-4ed1-11eb-96ea-5c1d13b6c3ad.png)

I got here by using this deeplink:

https://metamask.app.link/send/0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6@4?value=1e15

2021-01-05 04:01 UTC, rickycodes commented
> I'm not seeing this option when I come from a request, am I supposed to?

Ah good catch. yes we should also make this work for deep links (I can add that).

> For instance there's no option to buy ETH on Ropsten however, I see the link to buy ETH still

Maybe in those cases we should have links to the faucets instead?

2021-01-05 17:52 UTC, estebanmino commented on app/components/Nav/Main/index.js
> +				navigation={props.navigation}
👌

2021-01-05 18:01 UTC, estebanmino approved these changes
lgtm

2021-01-11 22:26 UTC, ibrahimtaveras00 approved these changes
Fixes look good, QA Passed 👍🏽

2021-01-11 22:30 UTC, merged