bugfix/erc20 allowance ui
MetaMask/metamask-mobile pull request #2103
Opened 2021-01-07 20:22 UTC by estebanmino

**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #2017

2021-01-14 16:18 UTC, rickycodes approved these changes

2021-01-21 20:08 UTC, ibrahimtaveras00 requested changes
~~Issue 1 from https://github.com/MetaMask/metamask-mobile/issues/1914 is fixed, however issue 2 still remains~~

~~Here I am requesting 1003 HOT and when I end up on the confirm view, I see < 0.00001 HOT instead~~

2021-01-21 20:10 UTC, ibrahimtaveras00 commented
sorry meant for this comment to be for https://github.com/MetaMask/metamask-mobile/pull/2104

2021-01-21 21:01 UTC, ibrahimtaveras00 approved these changes
Allowance now displays correct value, QA Passed 👍🏽

2021-01-21 22:10 UTC, merged