Feature/warn when replacing
MetaMask/metamask-mobile pull request #2176
Opened 2021-01-28 01:06 UTC by rickycodes

**Description**

Adequately warn user when resting:

https://user-images.githubusercontent.com/675259/106075100-fbe29680-60da-11eb-8836-7ff74d8e9e35.mp4

**Checklist**

* [x] There is a related GitHub issue

**Issue**

Resolves #2115

2021-01-29 23:21 UTC, ibrahimtaveras00 requested changes
- **Issue 1:** 
<strike>The wording seems a little bit incomplete where we say "setup new"

![image](https://user-images.githubusercontent.com/41752922/106332202-4e938e00-6254-11eb-82b5-0d1e4cf0d088.png)

Maybe "and setup a new wallet" or "and setup a new one" 
cc: @cjeria @omnat </strike>

- **Issue 2:** 
<strike>Mispelling 

![image](https://user-images.githubusercontent.com/41752922/106332326-94e8ed00-6254-11eb-8c9f-575f8bf5c6cf.png)

Should be "permanently"</strike>

- **Issue 3:** 
<strike>On a smaller screen the modal is stretched out (example iPhone 5s)

![Screen Shot 2021-01-29 at 6 04 31 PM](https://user-images.githubusercontent.com/41752922/106336258-869ecf00-625c-11eb-9ace-2d79dbb1b687.png)</strike>

- **Issue 4:** 
Delete confirmation doesn't pop up on iOS; seen here = http://recordit.co/A0w226up6u

- **Issue 5:** 
<strike>In the figma mock up, it states to re-use the 'Creating wallet' loading screen from onboarding flow, and then it says not to allow going back on the onboarding carousel from here.  Also I didn't see the notification that my wallet was erased.  All 3 are not implemented; seen here = http://recordit.co/DeEz3hGhIh</strike>

![Screen Shot 2021-01-29 at 6 17 43 PM](https://user-images.githubusercontent.com/41752922/106337164-830c4780-625e-11eb-9361-e3f061499b75.png)

2021-02-02 22:16 UTC, cjeria commented
Issue 1: Let's go with "Can’t log in? You can ERASE your current wallet and **set up a new one**".

Issue 3: Let's try reducing the left and right margins of the modal so all sides have equal spacing (the area around the modal showing the background). Experiment with 8px, 16px or 24px to see what looks best.
![image](https://user-images.githubusercontent.com/597770/106669803-308e9c00-657a-11eb-9b41-c8cf6fcac1fb.png)

2021-02-10 04:24 UTC, rickycodes commented on app/components/Views/ManualBackupStep3/index.js
> -		});
this is just me undoing a previous silly thing i did.

2021-02-10 15:58 UTC, estebanmino commented on app/components/Views/Onboarding/index.js
> +		const notificationStatus = 'success';
can you move this to locales?

2021-02-10 16:16 UTC, rickycodes commented on app/components/Views/Onboarding/index.js
> +		const notificationStatus = 'success';
good catch

2021-02-10 18:36 UTC, estebanmino approved these changes
👌

2021-02-11 16:27 UTC, estebanmino approved these changes
lgtm

2021-02-11 19:52 UTC, ibrahimtaveras00 approved these changes
QA Passed 👍🏽

2021-02-11 19:54 UTC, merged