Feature/high gas warn
MetaMask/metamask-mobile pull request #2306
Opened 2021-02-26 16:36 UTC by sethkfman

**Description**

This feature will warn users if they have entered a gas price that is higher than the recommend "Fast" price during the entire transaction flow. 

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2021-03-03 18:26 UTC, estebanmino commented on app/components/UI/TransactionReview/TransactionReviewFeeCard/index.js
> -					{this.renderIfGasEstimationReady(
we need to render this `Text` inside this method to display a loader when the gases are being calculated

2021-03-03 18:30 UTC, estebanmino commented on app/components/Views/SendFlow/Confirm/index.js
> +			: this.setState({ warningGasPriceHigh: undefined });
you could do 
```suggestion
			this.setState({ warningGasPriceHigh });
```

since warningGasPriceHigh could be undefined ?

2021-03-03 18:32 UTC, estebanmino commented on app/components/Views/SendFlow/Confirm/index.js
> +								<Text style={styles.error}>{!errorMessage ? warningGasPriceHigh : errorMessage}</Text>
```suggestion
								<Text style={styles.error}>{errorMessage || warningGasPriceHigh}</Text>
```

2021-03-03 18:33 UTC, estebanmino commented on app/reducers/transaction/index.js
> +			return transactionNew;
what is this change for?

2021-03-03 22:04 UTC, sethkfman commented on app/components/UI/TransactionReview/TransactionReviewFeeCard/index.js
> -					{this.renderIfGasEstimationReady(
Typo. Added back in.

2021-03-03 22:05 UTC, sethkfman commented on app/components/Views/SendFlow/Confirm/index.js
> +			: this.setState({ warningGasPriceHigh: undefined });
Updated

2021-03-03 22:05 UTC, sethkfman commented on app/reducers/transaction/index.js
> +			return transactionNew;
Used for logging purposes. Set back to previous.

2021-03-03 22:07 UTC, sethkfman commented on app/components/Views/SendFlow/Confirm/index.js
> +								<Text style={styles.error}>{!errorMessage ? warningGasPriceHigh : errorMessage}</Text>
Broke this out into a separate view since I didn't want the onPress={errorPress} to apply to this warning.

2021-03-11 19:34 UTC, estebanmino commented on app/components/UI/TransactionReview/TransactionReviewInformation/index.js
> +			transaction: { gas, gasPrice, warningGasPriceHigh },
this is still in the `transaction` object? I see you modified the object in the reducer

2021-03-11 19:45 UTC, sethkfman commented on app/components/UI/TransactionReview/TransactionReviewInformation/index.js
> +			transaction: { gas, gasPrice, warningGasPriceHigh },
That property is coming from base object within that reducer. I moved it out of the nested transaction object in the reducer. It is a little confusing because of the prop name. Below is a console print out of the object.

{
	"assetType": "ETH",
	"data": "0x7ff36ab500000000000000000000000000000000000000000000000000000552978361ee0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000223367c61c38facbdd0b92de5aa7b742e1e5a19a00000000000000000000000000000000000000000000000000000000604a770f0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c778417e063141139fce010982780140aa0cd5ab000000000000000000000000ad6d458402f60fd3bd25163575031acdce07538d",
	"ensRecipient": undefined,
	"from": "0x223367c61c38facbdd0b92de5aa7b742e1e5a19a",
	"gas": "22285",
	"gasPrice": "17bfac7c00",
	"id": "df271c80-82a1-11eb-9114-f32d13faeaae",
	"origin": "app.uniswap.org",
	"paymentChannelTransaction": undefined,
	"paymentRequest": undefined,
	"readableValue": "0.00000001",
	"selectedAsset": {
		"isETH": true,
		"symbol": "ETH"
	},
	"symbol": "ETH",
	"to": "0x7a250d5630b4cf539739df2c5dacb4c659f2488d",
	"transaction": {
		"data": "0x7ff36ab500000000000000000000000000000000000000000000000000000552978361ee0000000000000000000000000000000000000000000000000000000000000080000000000000000000000000223367c61c38facbdd0b92de5aa7b742e1e5a19a00000000000000000000000000000000000000000000000000000000604a770f0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c778417e063141139fce010982780140aa0cd5ab000000000000000000000000ad6d458402f60fd3bd25163575031acdce07538d",
		"from": "0x223367c61c38facbdd0b92de5aa7b742e1e5a19a",
		"gas": "22285",
		"gasPrice": "17bfac7c00",
		"to": "0x7a250d5630b4cf539739df2c5dacb4c659f2488d",
		"value": "2540be400"
	},
	"transactionFromName": "Account 1",
	"transactionTo": "0x0942890c603273059a11A298f81Cb137bE9cF70F",
	"transactionToName": undefined,
	"transactionValue": undefined,
	"type": "ETHER_TRANSACTION",
	"value": "2540be400",
	_"warningGasPriceHigh": undefined_
}

2021-03-16 18:17 UTC, estebanmino commented on app/components/UI/TransactionReview/TransactionReviewInformation/index.js
> +			transaction: { gas, gasPrice, warningGasPriceHigh },
👌

2021-03-17 14:13 UTC, estebanmino approved these changes
LGTM!

2021-03-18 00:37 UTC, ibrahimtaveras00 requested changes
**Issue 1:**

There is an extra `m` in amount 

![image](https://user-images.githubusercontent.com/41752922/111555230-50f76c00-875e-11eb-863b-a6b0dfedabf4.png)

**Issue 2:**

Figma shows the are you sure modal, however, I do not see this upon confirming/sending the txn 

seen here (on send)= https://recordit.co/4yvZv0hvGp
seen here (on confirm/dapp) = https://recordit.co/8hxpQpN4yv

**Issue 3: or Question**

Not really an issue per se, however, I did notice that after changing the gas price to be higher than fast, saving, then coming back I don't see the warning anymore.  Nonetheless, when I do tap back into the text input field and change the value, I do correctly see the warning

seen here = https://recordit.co/F34gI0T4TM

Non-blocker IMO just wanted to bring it up

**Issue 4:**

I do correctly see the warning on the approve modal in advanced mode on editing the gas price, however, when I save and before I tap Approve button, I don't see the warning, nor is the network fee value in red text

seen here = http://recordit.co/eINVmGcpyR

![image](https://user-images.githubusercontent.com/41752922/111555759-733db980-875f-11eb-8192-3b3be7f406bf.png)

Easiest way to get the approve modal to show is to tap this deep link (open this PR on a browser, then tap link to deeplink to MM app)

https://metamask.app.link/approve/0x1d7a9cd8c67e3c74a84bb76cbc1b606e2e460db5@4/approve?address=0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6&uint256=1

**Issue 5: or Question**

Similar to issue 3 I'd say this is a non blocker, but still wanted to bring it up.

When I'm on a dapp txn, and I have high gas, below the warning there is a "View Data" button that gets cut off.  Nonetheless, I'm able to tap it and see the next view.
cc: @jakehaugen 

seen here = https://recordit.co/wuXckXFpIz

![image](https://user-images.githubusercontent.com/41752922/111556114-2efee900-8760-11eb-81e3-6e0519c840c0.png)

**Issue 6:**

Similar to issue 4 with Approve, when I'm on a swap and I have high gas fee, I correctly see the warning in advanced gas mode, however, when I come back to complete the swap, I do not see the warning anywhere, should I? (nor is the network fee value in red text)

cc: @jakehaugen / @wachunei  / @estebanmino 

seen here = https://recordit.co/OXu10aQEzU

![image](https://user-images.githubusercontent.com/41752922/111556284-8d2bcc00-8760-11eb-8628-32e05b76323e.png)

2021-03-19 22:11 UTC, omnat commented
Are we showing the warning if the user chooses 1.5 times the 'Fast' gas setting? 
Was discussed async [here](https://consensys.slack.com/archives/GTQAGKY5V/p1614798338271300?thread_ts=1614627758.173800&cid=GTQAGKY5V), but unsure if was visible enough.

2021-03-22 18:31 UTC, sethkfman commented
@omnat We are showing the warning if it is anything over the "Fast" value. Does it need to be changed to 1.5x? 
CC: @jakehaugen & @ibrahimtaveras00

2021-03-23 14:28 UTC, estebanmino commented on app/components/UI/Swaps/QuotesView.js
> +				{!!warningGasPriceHigh && (
could you move this to this line https://github.com/MetaMask/metamask-mobile/pull/2306/files#diff-025ac7b6441b0f42a655967d0c0d48698910f51d40ebd8cdf41aa964ae73753dR1017 ?

2021-03-23 14:31 UTC, estebanmino commented on app/components/UI/Swaps/QuotesView.js
> +				{!!warningGasPriceHigh && (
then only show this warning if `!(!hasEnoughTokenBalance || !hasEnoughEthBalance)`

I can see the case when the swap is not gonna be possible to do either because not enough token nor ETH to do the swap but anyways we could be displaying it.

also just to have all warnings together

2021-03-23 16:12 UTC, sethkfman commented on app/components/UI/Swaps/QuotesView.js
> +				{!!warningGasPriceHigh && (
Updated code and added the 1.5x validation in the custom gas to have feature parody with the extension. CC: @omnat & @ibrahimtaveras00

2021-03-23 16:24 UTC, estebanmino approved these changes
lgtm!

2021-03-25 17:18 UTC, ibrahimtaveras00 approved these changes
Fixes look good, QA Passed 👍🏽

2021-03-31 15:47 UTC, merged