Add custom network rpc API
MetaMask/metamask-mobile pull request #2318
Opened 2021-03-01 17:21 UTC by andrepimenta

**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2021-03-11 19:41 UTC, estebanmino commented on app/components/Views/BrowserTab/index.js
> +			addCustomNetworkRequest.current.reject(new Error('User rejected the request.'));
can we move theese messages to a common file? I see they're being used below too

2021-03-11 19:43 UTC, estebanmino commented on app/core/RPCMethods/wallet_addEthereumChain.js
> +	const { PreferencesController, CurrencyRateController, NetworkController } = Engine.context;
I see you're using the `PreferencesController` directly here, but the `frequentRpcList` is still passed trough the browser, together with `networkProvider`, instead of doing `PreferencesController.state.frequentRpcList`. Any reason for that?

2021-03-11 19:44 UTC, estebanmino commented on app/core/RPCMethods/wallet_addEthereumChain.js
> +	const extraKeys = Object.keys(params).filter(key => !allowedKeys[key]);
any option of having `params` undefined?

2021-03-11 19:49 UTC, estebanmino commented on app/core/RPCMethods/wallet_addEthereumChain.js
> +	NetworkController.setRpcTarget(firstValidBlockExplorerUrl, chainIdDecimal, ticker, _chainName);
`firstValidRPCUrl` instead? seems like you're passing the block explorer as rpc url

2021-03-11 19:53 UTC, estebanmino commented
As a general comment and since this is a complete new feature, we could use the `Text` component we have (not the one from react-native) just to start adding it through the app

2021-03-22 13:59 UTC, andrepimenta commented on app/components/Views/BrowserTab/index.js
> +			addCustomNetworkRequest.current.reject(new Error('User rejected the request.'));
The default message was actually already "User rejected the request." so no need for this Error! Thanks!

2021-03-22 13:59 UTC, andrepimenta commented on app/core/RPCMethods/wallet_addEthereumChain.js
> +	const { PreferencesController, CurrencyRateController, NetworkController } = Engine.context;
Makes sense! Going to get the variables directly from the controller!

2021-03-22 14:00 UTC, andrepimenta commented on app/core/RPCMethods/wallet_addEthereumChain.js
> +	const extraKeys = Object.keys(params).filter(key => !allowedKeys[key]);
No problem there, the params are checked for undefined before this line.

2021-03-22 14:00 UTC, andrepimenta commented on app/core/RPCMethods/wallet_addEthereumChain.js
> +	NetworkController.setRpcTarget(firstValidBlockExplorerUrl, chainIdDecimal, ticker, _chainName);
Good catch, thanks!!

2021-03-22 20:14 UTC, andrepimenta commented
> As a general comment and since this is a complete new feature, we could use the `Text` component we have (not the one from react-native) just to start adding it through the app

@estebanmino This should be done now, thanks for bringing this up!

2021-03-23 19:58 UTC, estebanmino approved these changes
lgtm 
👌

2021-03-30 22:17 UTC, ibrahimtaveras00 requested changes
The only outstanding issue here is that the RPC URL causes the text to appear outside the warning on Android (works on iOS)

![image](https://user-images.githubusercontent.com/41752922/113063981-2e187f00-9184-11eb-83c1-95e38362efcb.png)

Device Emulator info:
![Screen Shot 2021-03-30 at 5 21 03 PM](https://user-images.githubusercontent.com/41752922/113063991-3375c980-9184-11eb-998d-a023f430eada.png)

2021-03-31 15:36 UTC, ibrahimtaveras00 approved these changes
![Screen Shot 2021-03-31 at 11 35 18 AM](https://user-images.githubusercontent.com/41752922/113171239-44225000-9215-11eb-9e8a-422737de2cc3.png)

Fix looks good, QA Passed 👍🏽

2021-03-31 16:51 UTC, merged