Feature/custom nonce
MetaMask/metamask-mobile pull request #2371
Opened 2021-03-11 16:31 UTC by rickycodes

**Description**

Opening this as a Draft as it relies on https://github.com/MetaMask/controllers/pull/381

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #2126

2021-03-11 16:49 UTC, wachunei commented on app/components/Views/SendFlow/Confirm/index.js
> +								<Text bold blue>
Thanks for adding blue 👌, however to keep things semantically correct I'd use `bold link` here, what do you think?

2021-03-11 19:43 UTC, rickycodes commented on app/components/Views/SendFlow/Confirm/index.js
> +								<Text bold blue>
oh jeez! I didn't see that. thanks for the heads up. I'll change that.

2021-03-17 18:45 UTC, cjeria commented
For the warning copy, instead of repeating what is already mentioned in the default copy, I'm now thinking we should mention what _could_ happen if they continue with the higher than suggested nonce. 

How about something like this instead? cc @rickycodes @omnat @jakehaugen 
![image](https://user-images.githubusercontent.com/597770/111521252-2c77a180-8716-11eb-8632-1b2a0c5aa48e.png)

2021-03-23 21:35 UTC, Gudahtt commented on package.json
> +    "@metamask/controllers": "file:./metamask-controllers-v6.1.2.tgz",
This feature has been published in v9.2.0 of the controllers repo, so this can be updated now to reference the published version

2021-03-29 16:20 UTC, estebanmino commented on app/core/Engine.js
> +import { /* TransactionController ,*/ SwapsController } from '@estebanmino/controllers';
this is not needed anymore `/* TransactionController ,*/`

2021-03-29 16:24 UTC, estebanmino commented on app/util/transactions.js
> +
rather than taking this from the transactions list I'd try to query the blockchain instead with [getTransactionCount](https://infura.io/docs/ethereum/json-rpc/eth-getTransactionCount). We can miss transactions that didn't happen from the app, specially for custom networks added by users.

We can do it directly with `query(this.ethQuery, 'getTransactionCount', [from, 'pending']))` from the app.

WDYT?

2021-03-29 17:01 UTC, rickycodes commented on app/util/transactions.js
> +
personally, I like the simplicity of this approach (one less blockchain query)... but maybe it makes sense to _also_ get the nonce from the network and then use that _if_ it's different from the local one?

2021-03-29 17:15 UTC, estebanmino commented on app/util/transactions.js
> +
I can imagine txs in custom networks that aren't on the app, if they want to use this feature it won't work for them

2021-03-29 17:16 UTC, estebanmino commented on app/util/transactions.js
> +
this is also important for users with 3rd party apis turned off, it will make this feature fail if txs happened somewhere else

2021-03-29 17:16 UTC, estebanmino commented on app/util/transactions.js
> +
WDYT?

2021-03-29 17:28 UTC, Gudahtt commented on app/util/transactions.js
> +
We rely upon just the transaction list in the extension, but we're in a different situation. We get our list of confirmed transactions directly from the network (not Etherscan), and we update it every single block (whereas mobile seems to get an updated transaction list according to certain UI actions - not sure which).

Barring some major change to how the `@metamask/controllers` transaction controller works, we'll need to use `getTransactionCount` here I think.

2021-04-05 20:55 UTC, ibrahimtaveras00 requested changes
**Issue 1:**

So far this is only implemented on send flow, but also needs to be implemented on dapp transactions which is currently not the case

refer to = https://consensys.slack.com/archives/GBW7S9FSN/p1617653913259200?thread_ts=1617652943.258500&cid=GBW7S9FSN

**Issue 2:**

Some text changes compared to mock up

![image](https://user-images.githubusercontent.com/41752922/113626013-9dccb500-962f-11eb-992e-65c301c3ab40.png)

2021-04-08 17:12 UTC, rickycodes commented
I've gone ahead and removed the design qa label since I've gone over this with Christian and he's okay'd it all. re: https://github.com/MetaMask/metamask-mobile/pull/2371#pullrequestreview-628156144 I've addressed all QA feedback except for issue 3 as discussed. this is ready for qa again.

2021-04-08 17:15 UTC, estebanmino commented on app/components/UI/CustomNonceModal/index.js
> +	const saveAndClose = value => {
just personal preference, maybe it would be cleaner to use the nonce from state here directly rather than calling the method with the value from render https://github.com/MetaMask/metamask-mobile/pull/2371/files#diff-7358361397d4cbafe60eca2a1bae2ed5226b676ef85d91995e272bdac2159682R205

2021-04-08 17:16 UTC, estebanmino commented on app/components/UI/TransactionReview/TransactionReviewInformation/index.js
> +				close={() => this.toggleNonceModal()}
```suggestion
				close={this.toggleNonceModal}
```

2021-04-08 17:18 UTC, estebanmino commented on app/util/networks.js
> +	return parseInt(networkNonce, 16);
nice and clean 👌

2021-04-08 17:32 UTC, estebanmino approved these changes
lgtm!

2021-04-14 18:56 UTC, ibrahimtaveras00 approved these changes
All issues resolved, QA Passed 👍🏽

2021-04-14 19:22 UTC, merged