Add `toFixed(2)`
MetaMask/metamask-mobile pull request #2381
Opened 2021-03-15 15:22 UTC by rickycodes

**Description**

I noticed we're not rounding fiat correctly in some instances:

**Before:**

<img src=https://user-images.githubusercontent.com/675259/111176622-e12b8a80-857f-11eb-82b7-9102e4114d38.png width=300 /><img src=https://user-images.githubusercontent.com/675259/111176664-eab4f280-857f-11eb-9459-86bf3fd86537.png width=300 />

**After:**

![image](https://user-images.githubusercontent.com/675259/111177273-73339300-8580-11eb-8d90-8b2738e74769.png)

This likely needs more work since I don't think adding `toFixed(2)` is an adequate enough solution. We could probably look at adding `Intl.NumberFormat` in the future.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2021-03-21 23:24 UTC, rickycodes commented
this is probably fine to merge as we're doing the same thing in other places (it only fixes the issue for USD)

2021-04-12 16:18 UTC, andrepimenta requested changes

2021-04-12 16:18 UTC, andrepimenta commented on app/core/Engine.js
> +			ethFiat = weiToFiatNumber(accounts[selectedAddress].balance, conversionRate, decimalsToShow);
I think if `decimalsToShow = false` (which will happen if `currentCurrencty !== 'usd'`), then it will send false to weiToFiatNumber and then it will fail no? Since it's expecting a number?

2021-04-12 17:20 UTC, rickycodes commented on app/core/Engine.js
> +			ethFiat = weiToFiatNumber(accounts[selectedAddress].balance, conversionRate, decimalsToShow);
if that's the case we may have another bug here? https://github.com/MetaMask/metamask-mobile/blob/develop/app/util/number.js#L351 I just copied and pasted this logic from there.

2021-04-12 17:32 UTC, rickycodes commented on app/core/Engine.js
> +			ethFiat = weiToFiatNumber(accounts[selectedAddress].balance, conversionRate, decimalsToShow);
ah! good catch. I've added a `|| undefined` for both cases.

2021-04-12 17:34 UTC, andrepimenta approved these changes
LGTM!

2021-04-12 17:48 UTC, merged