Feature/tx local state logs
MetaMask/metamask-mobile pull request #2460
Opened 2021-03-30 18:57 UTC by sethkfman

**Description**

This is a feature to track the times that a user adds/creates/imports an account on the mobile app which then is used to display added/import time and local transaction history.

**Checklist**

* [ ] There is a related GitHub issue
* [X] Tests are included if applicable
* [X] Any added code is fully documented

**Issue**

Resolves #???

2021-04-07 19:10 UTC, estebanmino commented on app/components/UI/TransactionElement/index.js
> +						<ListItem.Date>{toDateFormat(identities[selectedAddress].importTime)}</ListItem.Date>
what happens with current users that don't have this time set? I think if the tx has the `insertImportTime` property this could crash?

2021-04-07 19:14 UTC, estebanmino commented on app/components/UI/Transactions/index.js
> +				tx.insertImportTime = false;
do we need to have `insertImportTime` defined or we could just find the one that makes this true and return 2 lines above? I'm wondering that if i have 100 or more txs and I just imported 1 tx ago, I'll be doing the loop check 99 + times every time this component is rendered

2021-04-07 21:02 UTC, sethkfman commented on app/components/UI/Transactions/index.js
> +				tx.insertImportTime = false;
I completely agree with the performance hit. My original concern was if it was bad practice to have objects have inconsistent properties. See my corrections.

2021-04-07 21:03 UTC, sethkfman commented on app/components/UI/TransactionElement/index.js
> +						<ListItem.Date>{toDateFormat(identities[selectedAddress].importTime)}</ListItem.Date>
Good catch I add the `import` time to the check before rendering the view.

2021-04-12 15:52 UTC, andrepimenta commented on app/components/UI/TransactionElement/index.js
> +		}
Maybe newer versions of React Native don't complain but I think it would be a good practice for this function to return null (in case it doesn't get into the if statement)

2021-04-12 16:06 UTC, andrepimenta requested changes

2021-04-12 16:06 UTC, andrepimenta commented on app/components/UI/Transactions/index.js
> +	processTransactions = transactions => {
Couldn't this be done on the item render function. Return null if it `tx.time <= time`, otherwise render it?

2021-04-12 16:06 UTC, andrepimenta commented on app/components/UI/Transactions/index.js
> +	processTransactions = transactions => {
If the render approach described on the comment above doesn't work:
There is also a view above this one called TransactionView `app/components/Views/TransactionsView/index.js` that already processes transactions on the function called `filterTransactions`. Maybe you can use it?

2021-04-15 19:32 UTC, sethkfman commented on app/components/UI/Transactions/index.js
> +	processTransactions = transactions => {
@andrepimenta I moved it up to the `TransactionView/index.js` let me know what you think.

2021-04-15 20:11 UTC, andrepimenta commented on app/components/Views/TransactionsView/index.js
> +		addImportTimeFlagToTransactions(allTransactions);
We already have a loop on all the transactions on the filter above. What do you think about using this function (without the loop) inside the filter function? Would make it more performant

2021-04-15 21:16 UTC, sethkfman commented on app/components/Views/TransactionsView/index.js
> +		addImportTimeFlagToTransactions(allTransactions);
@andrepimenta very much so! I refactored and added it to the filter as well as renamed some values to better represent what is displayed on the UI.

2021-04-16 09:58 UTC, andrepimenta approved these changes
LGTM! 👍

2021-04-16 17:57 UTC, ibrahimtaveras00 approved these changes
QA Passed 👍🏽

2021-04-16 18:11 UTC, merged