Feature/confusables
MetaMask/metamask-mobile pull request #2464
Opened 2021-03-31 20:30 UTC by rickycodes

**Description**

re: #2067 

![image](https://user-images.githubusercontent.com/675259/113206587-a3945600-923d-11eb-8dc5-6ea538c9a72e.png)
![image](https://user-images.githubusercontent.com/675259/113206599-a8590a00-923d-11eb-834a-59267a60cf26.png)

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #2067

2021-04-06 14:23 UTC, rickycodes commented on app/components/Views/SendFlow/SendTo/index.js
> +										<Icon size={16} color={colors.red} name="exclamation-triangle" />
there's lots of instances where we don't use a `style` for these like https://github.com/MetaMask/metamask-mobile/blob/develop/app/components/UI/GlobalAlert/index.js#L89 and https://github.com/MetaMask/metamask-mobile/blob/master/app/components/UI/Tokens/index.js#L160. In this case I don't think I adding a `style` prop would make much a difference.

2021-04-06 16:24 UTC, sethkfman commented on app/components/Views/SendFlow/SendTo/index.js
> +										<Icon size={16} color={colors.red} name="exclamation-triangle" />
Sounds good. Is the general rule to use a style when it is repeated throughout the file?

2021-04-07 23:28 UTC, omnat commented
jfyi @rickycodes - extension found this bug on their confusables error implementation https://github.com/MetaMask/metamask-extension/issues/10691

2021-04-08 03:30 UTC, rickycodes commented
@omnat doesn't look like we have any such issue in our case that address resolves fine:
![image](https://user-images.githubusercontent.com/675259/113964289-33677080-97f9-11eb-971e-3284aaa6614b.png)

2021-04-08 17:10 UTC, estebanmino commented on app/components/Views/SendFlow/AddressInputs/index.js
> +		const Texts = toAddressName.split('').map((char, index) => {
`T`exts instead of `t`exts was on purpose?

2021-04-08 17:11 UTC, estebanmino commented on app/components/Views/SendFlow/Confirm/index.js
> +		paymentChannelReady: false,
we can remove these two now, instapay was deprecated

2021-04-08 17:40 UTC, rickycodes commented on app/components/Views/SendFlow/AddressInputs/index.js
> +		const Texts = toAddressName.split('').map((char, index) => {
updated to `texts`

2021-04-08 17:40 UTC, rickycodes commented on app/components/Views/SendFlow/Confirm/index.js
> +		paymentChannelReady: false,
updated.

2021-04-09 15:08 UTC, estebanmino approved these changes
👌

2021-04-14 20:09 UTC, ibrahimtaveras00 commented
My normal ENS name for my test account, ibrahimtester.eth, is getting flagged as a confusable 

Are we fine with showing this warning on normal ENS names? 

Saw it on a few other ones as well:

![Screen Shot 2021-04-14 at 4 08 18 PM](https://user-images.githubusercontent.com/41752922/114772385-bb8ad000-9d3b-11eb-9979-0ffdb629f4b5.png)

2021-04-14 20:23 UTC, cjeria commented
@ibrahimtaveras00 looks like it's flagging the letter "m" from your screenshots. @rickycodes does this seem like a bug to you?

2021-04-14 20:27 UTC, rickycodes commented
it's not a bug. looking at the json I see a pairing ` "m": "rn",`... i guess `m` is similar to `rn` so i gets flagged.

2021-04-14 20:35 UTC, cjeria commented
@rickycodes ah, I see. Should either of those be in the json though? There are English words that use that pair - "morning.eth",  "burning.eth". I wouldn't want to alarm the user in those cases. Can that be omitted from the JSON?

2021-04-14 20:50 UTC, rickycodes commented
@cjeria the `.json` that I am referring to is part of the library we're using. that said, they could be omitted if we wanted to filter them out on our end. alternatively, we could look at flagging the more obvious ones (ens names that container zero width white space or unicode chars).

2021-04-14 21:06 UTC, ibrahimtaveras00 requested changes
![image](https://user-images.githubusercontent.com/41752922/114779150-c0538200-9d43-11eb-95f6-23dc2e4cd23d.png)

2021-04-15 09:57 UTC, andrepimenta commented
![image.png](https://images.zenhubusercontent.com/5f99d46607474d60b64035d5/a80b0c12-e6f7-4d73-8926-e2e8c4d987a6)

It flags it on extension too it seems.

2021-04-29 21:01 UTC, ibrahimtaveras00 approved these changes
Fixes look good, QA Passed 👍🏽

2021-04-29 23:45 UTC, merged