added new bitrise yml file
MetaMask/metamask-mobile pull request #2531
Opened 2021-04-14 14:39 UTC by sethkfman

**Description**

Adding new Bitrise yml file for new CI/CD pipelines

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2021-04-17 01:33 UTC, rickycodes requested changes

2021-04-17 01:33 UTC, rickycodes commented on bitrise.yml
> +            ./scripts/yarn-audit.sh
rather than putting shell scripting into config there should be a way to run the shell script directly? For example, all the `set -e` and `set -x` here could just as easily be placed in `./scripts/yarn-audit.sh` directly. This also means if we add tooling (thinking something like [shellcheck](https://github.com/koalaman/shellcheck)) then we can use that to analyze shell scripts without having to extract anything from a yaml file. mixing code and config like this is confusing.

2021-04-17 01:33 UTC, rickycodes commented on bitrise.yml
> +            ./scripts/yarn-audit.sh
actually, now that i look closer there's already some `set`'s in the `./scripts/yarn-audit.sh`

2021-04-19 16:55 UTC, sethkfman commented on bitrise.yml
> +            ./scripts/yarn-audit.sh
Will update. Thanks

2021-05-20 21:58 UTC, closed without merging