Fix/respect custom spend limit on dapp approve modal
MetaMask/metamask-mobile pull request #2556
Opened 2021-04-20 21:00 UTC by rickycodes

**Description**

This gets the custom spend limit working for dapp approve again:

https://user-images.githubusercontent.com/675259/115463410-c80a9f00-a1f9-11eb-9168-094bd049b810.mp4

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #2380

2021-04-26 15:31 UTC, sethkfman commented on app/components/UI/ApproveTransactionReview/index.js
> +			//
Should we log something in Sentry?

2021-04-26 17:37 UTC, wachunei commented on app/components/UI/ApproveTransactionReview/index.js
> +			//
If I recall correctly this would catch issues with a specific case regarding the number being used to create the approval transaction. I'd say we should log something to keep track of the number of times it happens, thoughts @rickycodes ?

2021-04-29 13:30 UTC, andrepimenta requested changes

2021-04-29 13:30 UTC, andrepimenta commented on app/components/UI/ApproveTransactionReview/EditPermission/index.js
> +	}));
I think here you can simplify?
`useState({spendLimitUnlimitedSelected, spendLimitCustomValue})`

2021-04-29 13:30 UTC, andrepimenta commented on app/components/UI/ApproveTransactionReview/EditPermission/index.js
>  		() => !spendLimitUnlimitedSelected && minimumSpendLimit > spendLimitCustomValue,
`minimumSpendLimit` seems to be a string? Any problem doing this comparison?

2021-04-29 13:30 UTC, andrepimenta commented on app/components/UI/ApproveTransactionReview/index.js
> +import EditPermission, { MINIMUM_VALUE } from './EditPermission';
Should MINIMUM_VALUE be on the constants util?

2021-04-29 17:34 UTC, rickycodes commented on app/components/UI/ApproveTransactionReview/index.js
> +import EditPermission, { MINIMUM_VALUE } from './EditPermission';
It's only used for `EditPermission` so I think this is fine?

2021-04-29 17:36 UTC, rickycodes commented on app/components/UI/ApproveTransactionReview/EditPermission/index.js
>  		() => !spendLimitUnlimitedSelected && minimumSpendLimit > spendLimitCustomValue,
should be fine:
```
> '2' > '1'
true
> '2' < '1'
false
```

2021-04-30 20:13 UTC, ibrahimtaveras00 commented
I tested Rinkeby uniswap.exchange and Ropsten https://ropsten.kyber.network and they both don't behave how our swaps behave, although I'm not sure if that's from the dapp side, and I can't confirm on prod as spend limit isn't respected.

Our swaps behavior: 
If you have 4 UNI and you approve 2, then swap 2, the next time you want to swap more UNI you will have to approve again

Dapps behavior:
just need to approve once, no matter what the custom spend limit is

2021-05-03 17:16 UTC, ibrahimtaveras00 approved these changes
👍🏽

2021-05-04 13:34 UTC, andrepimenta approved these changes
Only have one more thing: https://github.com/MetaMask/metamask-mobile/pull/2556/files#diff-07d844893596c7056d106bff7269585b347aaeea01f22e4ca5e3d57625974be3R111
Otherwise, looks good to me!

2021-05-04 14:13 UTC, merged