Collectibles under wallet
MetaMask/metamask-mobile pull request #2602
Opened 2021-04-27 23:40 UTC by estebanmino

**Description**

![aaa](https://user-images.githubusercontent.com/12115171/116325490-4c2bcc00-a790-11eb-8782-54cc2385e573.gif)

cc @cjeria 
**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #2591

2021-04-29 13:50 UTC, andrepimenta requested changes

2021-04-29 13:50 UTC, andrepimenta commented on app/components/UI/CollectibleContractElement/index.js
> +		width: (DEVICE_WIDTH - 30 - 16) / 3,
Should this be a constant above since it's used multiple times? `(DEVICE_WIDTH - 30 - 16) / 3`

2021-04-29 13:50 UTC, andrepimenta commented on app/components/UI/CollectibleContractElement/index.js
> +								index - (1 % 3) === 0 ? styles.collectibleInTheMiddle : styles.collectibleIcon
Maybe I am not doing the math correctly, but isn't (1 % 3) always the same number (1)? 
So `index - (1 % 3) === 0` will only be true when index = 1?

Also one more suggestion (although this is more a personal choice maybe), is instead of declaring two different styles, you could declare just one style as a function which takes a parameter for example:
```
collectibleIcon: (middle) => {
		width: (DEVICE_WIDTH - 30 - 16) / 3,
		height: (DEVICE_WIDTH - 30 - 16) / 3,
		marginHorizontal: middle ? 8 : 0
	}
```
then you would do `containerStyle={styles.collectibleIcon(index - (1 % 3) === 0)}`

2021-04-30 20:09 UTC, estebanmino commented on app/components/UI/CollectibleContractElement/index.js
> +		width: (DEVICE_WIDTH - 30 - 16) / 3,
👌

2021-04-30 20:21 UTC, estebanmino commented on app/components/UI/CollectibleContractElement/index.js
> +								index - (1 % 3) === 0 ? styles.collectibleInTheMiddle : styles.collectibleIcon
I had no idea what happened there

2021-04-30 20:23 UTC, estebanmino commented on app/components/UI/CollectibleContractElement/index.js
> +								index - (1 % 3) === 0 ? styles.collectibleInTheMiddle : styles.collectibleIcon
good catch

2021-04-30 20:27 UTC, estebanmino commented
also added @cjeria recommendation to only have the first collectible contract open by default

2021-05-03 15:39 UTC, andrepimenta approved these changes
LGTM! 👍

2021-05-03 15:52 UTC, merged

2021-05-03 16:12 UTC, mobularay commented
Adding "needs-qa" label, however for NFTs, @ibrahimtaveras00 needs to wait for other NFT cards to be completed before proper QA can be done