Educate gas fees
MetaMask/metamask-mobile pull request #2611
Opened 2021-04-30 16:10 UTC by andrepimenta

**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2021-05-13 20:12 UTC, sethkfman commented on app/components/UI/FiatOrders/PaymentMethodSelector/index.android.js
> +		const goToTransakFlow = () =>
Could you pull out the onPressTransak and onPressWyreApplePay to a common area to reduce duplicate code?

2021-05-17 22:36 UTC, sethkfman approved these changes

2021-05-29 01:15 UTC, ibrahimtaveras00 requested changes
**Issue 1:**

On a smaller device (iPhone SE) there's no indication that there are multiple pages to scroll through 

![image](https://user-images.githubusercontent.com/41752922/120053597-04030200-bff9-11eb-81cf-0c9acc54b0b5.png)

**Issue 2:**

Warning pops up when changing gas fee

seen here = https://recordit.co/jh6h8ki2rE

![Screen Shot 2021-05-28 at 7 11 44 PM](https://user-images.githubusercontent.com/41752922/120053618-2eed5600-bff9-11eb-979e-7a25a0ac6529.png)

**Issue 3:** 

Not sure if this was changed, but I noticed the URL is different from figma

![image](https://user-images.githubusercontent.com/41752922/120053652-63f9a880-bff9-11eb-85e4-877af057dd14.png)

**Issue 4:**

I don't see tooltip nor link format for approve txn type

![Screen Shot 2021-05-28 at 8 36 26 PM](https://user-images.githubusercontent.com/41752922/120053664-7bd12c80-bff9-11eb-8075-6cd4627289e0.png)

If you want an easy way to get approve to pop up tap this deeplink in safari/chrome to open MM app

https://metamask.app.link/approve/0x1d7a9cd8c67e3c74a84bb76cbc1b606e2e460db5@1/approve?address=0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6&uint256=1

**Issue 5:**

The gas fee on Swaps is different than the mock up in figma

![image](https://user-images.githubusercontent.com/41752922/120053700-c2268b80-bff9-11eb-80d0-dc174da9944b.png)

2021-06-01 18:51 UTC, mobularay commented
From today's mid-sprint sync: @jakehaugen and @wachunei will respond to Ibrahim's QA questions, and complete this ticket hopefully while Andre is away.

2021-06-02 20:54 UTC, wachunei commented
- **Issue 1**: Added custom styling for small screens 
- **Issue 2**: Fixed 
- **Issue 3**: @jakehaugen can you confirm what is the right url?
- **Issue 4**: Added it!
- **Issue 5**: It seems we are not implementing this because of dotted underline does not exists, @jakehaugen please confirm 🙏

2021-06-03 19:48 UTC, jakehaugen commented
Issue 3: The MetaMask link is correct
Issue 5: We decided to go with an underline (not dotted) for the edit link not on swaps, right? If so, let's be consistent and go with the underline. 

For 5, this is what is shown in the mocks: https://www.figma.com/file/J8Gg2fYEY9iB0Mmi0DWk5E/Gas-Education?node-id=72%3A127

2021-06-03 20:26 UTC, wachunei commented
**Issue 5**: Fixed

2021-06-04 19:21 UTC, ibrahimtaveras00 approved these changes
All issues have been resolved 👍🏽

2021-06-04 20:05 UTC, merged