On-Ramp: Refactor and Wyre countries
MetaMask/metamask-mobile pull request #2617
Opened 2021-05-03 23:17 UTC by wachunei

2021-05-17 18:51 UTC, estebanmino commented on app/reducers/fiatOrders/index.js
> +const networkSelector = state => state.engine.backgroundState.NetworkController.network;
can we have this dependant on chainId instead of network?

2021-05-17 18:54 UTC, estebanmino commented on app/components/UI/FiatOrders/index.js
> +					dispatch(updateFiatOrder(updatedOrder));
hm there's any reason to dispatch from the component rather than doing mapDispatchToProps? just to maintain the same structure

2021-05-17 18:56 UTC, estebanmino commented on app/components/UI/FiatOrders/components/PaymentMethod/index.js
> +		marginHorizontal: Device.isIphone5() ? 15 : 25,
is this for only iPhone5 or all smaller devices? i believe there's a isSmallDevice method too

2021-05-17 18:58 UTC, estebanmino commented on app/components/UI/FiatOrders/components/CountrySelectorModal.js
> +		height: Device.isSmallDevice() ? 130 : 250,
ah you're using it (I commented this below, I'm reviewing from bottom to top)

2021-05-17 19:03 UTC, estebanmino commented on app/components/UI/FiatOrders/PaymentMethodSelector/transak.js
> +						<View style={styles.countryList}>
is this the same list than https://github.com/MetaMask/metamask-mobile/pull/2617/files?file-filters%5B%5D=.js&file-filters%5B%5D=.snap#diff-c4abe94ba2fc59ac406bb0e39c608aca28757ae56470d8ea275dead83345ffe5R94 ?
Maybe it would make sense to have another component?

2021-05-17 19:04 UTC, estebanmino commented on app/components/Base/Text.js
> +		lineHeight: 16 * 1.4
22.4?

2021-05-17 20:01 UTC, wachunei commented on app/components/UI/FiatOrders/PaymentMethodSelector/transak.js
> +						<View style={styles.countryList}>
No, is not the same

2021-05-17 20:03 UTC, wachunei commented on app/components/UI/FiatOrders/components/PaymentMethod/index.js
> +		marginHorizontal: Device.isIphone5() ? 15 : 25,
Yeah, this is more related to the width and the `isSmallDevice` to the height

2021-05-17 20:04 UTC, wachunei commented on app/reducers/fiatOrders/index.js
> +const networkSelector = state => state.engine.backgroundState.NetworkController.network;
Fixed 👌

2021-05-17 20:04 UTC, wachunei commented on app/components/UI/FiatOrders/index.js
> +					dispatch(updateFiatOrder(updatedOrder));
Moved it to `mapDispatchToProps` 👌

2021-05-17 20:04 UTC, wachunei commented on app/components/Base/Text.js
> +		lineHeight: 16 * 1.4
👌

2021-05-19 15:50 UTC, estebanmino commented
@wachunei @ibrahimtaveras00 just pushed a build to testflight to QA this PR. we need to revert this https://github.com/MetaMask/metamask-mobile/pull/2617/commits/4a60af557de04771ec3ae569dd90c659b01f69d5 before merging

2021-06-01 18:49 UTC, mobularay commented
Currently in limited user testing stage: 

- Andre (Portugal): passed successfully in Portugal
- Omna (Canada): currently working through some issues with Pedro
- Gabriel (Canada): still need to test. ETA eod June 1st. 
- Peter (UK): to be added to Testflight's internal testing group?
- Chantal (Singapore): to be added to Testflight's internal testing group?


If the above testings go well, then once Ibrahim is back this Thursday, he can do minimal feature testing and then move quickly into regression testing stage.

2021-06-03 16:20 UTC, mobularay commented
Update on user testing progress:

* Andre: pass
* Peter: pass
* Omna: stuck
* Gabriel: stuck
* Chantal: ???

2021-06-03 16:22 UTC, wachunei commented
Just to clarify: Omna and Gabriel are stuck because of Apple Pay restriction, this restriction is also present before the support of multiple countries.

2021-06-03 19:06 UTC, mobularay commented
- stuck error by Omna and Gabriel is not "terrible"
- It’ll just prevent them from using Apple Pay
- Transak will still work, or is available at least
- this error doesn't hit Wyre; stays at card level
- need to give heads-up to Customer Success

Removing Omna and Gabriel's stuck issue as blocker; will check with Chantal

2021-06-04 00:02 UTC, ibrahimtaveras00 requested changes
I added my QA results in slack with @wachunei and @jakehaugen, but posting here as well:
- Double check if $10K is accurate for yearly
- Not seeing Lithuania as a supported country 
- US and NON-US limits questions 
- Did we want to change the notification to match figma?
- In addition, do we want to change the quick buttons to match max of $400 US and $800 non-US?

2021-06-04 06:06 UTC, mobularay commented
Other than encountering a minor(?) UI issue, Chantal seems to have successfully completed the purchase - @wachunei to confirm!

2021-06-04 16:29 UTC, mobularay commented
Latest update: https://consensys.slack.com/archives/G018FR294E9/p1622818729047100

TBD on go/no-go status to be included into v2.5 release

2021-06-04 19:36 UTC, wachunei commented
> * Double check if $10K is accurate for yearly
> * Not seeing Lithuania as a supported country
> * US and NON-US limits questions
> * Did we want to change the notification to match figma?
> * In addition, do we want to change the quick buttons to match max of $400 US and $800 non-US?

All of these are fixed 🆗

2021-06-04 21:06 UTC, ibrahimtaveras00 approved these changes
I will have to check Issue 4 during regression testing as I can't do the full flow on debug mode and will need testflight instead.

Everything else looks good, QA Passed 👍🏽

2021-06-04 21:58 UTC, merged