Remove autoDismiss prop to always display close button on notification
MetaMask/metamask-mobile pull request #2619
Opened 2021-05-04 16:42 UTC by rickycodes

**Description**

This makes it so the close button is always displayed on notifications when an `onHide` is provided. The hope here is people can still dismiss this notification when it gets stuck.

![image](https://user-images.githubusercontent.com/675259/117038849-1af25500-acd6-11eb-9b97-cfff0f34591b.png)

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #2494

2021-05-04 17:06 UTC, sethkfman approved these changes
LGTM

2021-05-04 19:29 UTC, mobularay commented
@ibrahimtaveras00  tagging you to this ticket - can you prioritize this ticket to QA, pls? :slightly_smiling_face:

2021-05-04 20:54 UTC, ibrahimtaveras00 requested changes
I can't send txn's on this branch to test the notifications 

![image](https://user-images.githubusercontent.com/41752922/117068307-1db27180-acf9-11eb-9b2f-4ddba87ff56f.png)

![Screen Shot 2021-05-04 at 4 52 47 PM](https://user-images.githubusercontent.com/41752922/117068347-2c008d80-acf9-11eb-95de-e0b9414d82fe.png)

Also when I try and navigate to metamask.github.io/test-dapp in the browser I get this error:

![Screen Shot 2021-05-04 at 4 53 54 PM](https://user-images.githubusercontent.com/41752922/117068506-5d795900-acf9-11eb-9798-26fbd7c618df.png)

I was able to get a notification to show when deleting my current wallet, but I did not see the X there to dismiss, should I?

![image](https://user-images.githubusercontent.com/41752922/117068572-741fb000-acf9-11eb-9885-539e00ff101b.png)

2021-05-05 06:55 UTC, eddfr commented
There seems to be a related issue where buttons are not pressable ("next" button and other buttons don't respond) when the notification is stuck. 
Can anyone guess or know what the cause might be for this issue?

2021-05-05 20:09 UTC, rickycodes commented
closing for now until we can get more details/steps to reproduce

2021-05-05 20:09 UTC, closed without merging