Swaps: Add custom token flow
MetaMask/metamask-mobile pull request #2729
Opened 2021-05-28 00:03 UTC by wachunei

**Description**

This PR allows a user to enter a custom token address and use it to Swap

**Issue**

Resolves #2641

2021-06-01 21:15 UTC, sethkfman commented on app/components/UI/Swaps/utils/useFetchTokenMetadata.js
> +function useFetchTokenMetadata(address, chainId) {
Is this something that we will eventually move into a common Token Controller?

2021-06-01 21:17 UTC, wachunei commented on app/components/UI/Swaps/utils/useFetchTokenMetadata.js
> +function useFetchTokenMetadata(address, chainId) {
Good Question, at least I know is going to move to an API with a single endpoint with params `address, chainId` in the near future, that's why I left it there.

That endpoint could be exposed in a controller too, not planned so far tho.

2021-06-01 21:22 UTC, sethkfman commented on app/components/UI/Swaps/utils/useFetchTokenMetadata.js
> +function useFetchTokenMetadata(address, chainId) {
That makes sense. I guess if this utility starts to grow with more functionality we should check-in with Mark and the extension team to see if it would makes sense to convert it to a controller.

2021-06-01 21:49 UTC, sethkfman commented on app/components/UI/Swaps/components/TokenImportModal.js
> +function TokenImportModal({ isVisible, dismiss, token, onPressImport }) {
Is there any risk that `token` could be undefined?

2021-06-02 00:17 UTC, wachunei commented on app/components/UI/Swaps/components/TokenImportModal.js
> +function TokenImportModal({ isVisible, dismiss, token, onPressImport }) {
No, This in only rendered with valid metadata https://github.com/MetaMask/metamask-mobile/pull/2729/files/0aac78f607623c019b480d0f8e2bfa61494859a1#diff-8bdf03ea62d01afd27f35a8881d23e3175b5a9797c43372a7e14f117612bb133R348

2021-06-03 16:57 UTC, sethkfman approved these changes
LGTM

2021-06-23 05:51 UTC, mobularay commented
@jakehaugen: I just added the "design-qa" label

2021-07-26 22:05 UTC, ibrahimtaveras00 requested changes
**Issue 1:** 

it’s a bit tight to scroll on small device to see the full “can’t find a token” message box
http://recordit.co/Qd3Qsgce0D

**Issue 2:**

when you tap on the bscscan link it takes you to a 403 = http://recordit.co/zb2ZWCDbKK

I searched this token = 0x170dca460d661e834ff91bf6011afa8aa1a00b05

2021-07-27 16:23 UTC, jakehaugen commented
> **Issue 1:**
> 
> it’s a bit tight to scroll on small device to see the full “can’t find a token” message box
> http://recordit.co/Qd3Qsgce0D

No idea why this would cause a scrolling issue. Are design changes needed?

2021-07-27 16:27 UTC, wachunei commented
@jakehaugen I fixed it, no design changes needed. The issue happened because the footer was a regular view that did not capture the scrolling gesture. I changed it to a Touchable (without feedback) and behaves correctly now.

2021-07-27 17:33 UTC, ibrahimtaveras00 approved these changes
Fixes look good, QA Passed 👍🏽

2021-07-27 17:45 UTC, merged