Improvement/react navigation upgrade 5
MetaMask/metamask-mobile pull request #2731
Opened 2021-05-28 18:18 UTC by andrepimenta

**Description**

Updates navigation packages to react-navigation 5:
`"@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/compat": "^5.3.15",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "react-native-screens": "^3.3.0",

`
Reference on how to upgrade from 4: https://reactnavigation.org/docs/upgrading-from-4.x

Thinks to look out for @ibrahimtaveras00 :
- Navigation to another screen not working
- Headers not looking the same, for example, missing the back button or with incorrect titles 
- Inputs not pre-filled or information missing when navigating to a new screen. Since we are passing information using screen parameters and the way this is done has changed, there is now a probability that this does not work as expected for some screens.
- Warnings and errors that are thrown that were not there before.
- In general anything that is not working. Due to some screens relying on parameters that are sent to them, and since the way this is done has changed, there is now a probability that some things may not work as expected.

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #2077

2021-06-09 18:52 UTC, wachunei commented on app/components/Nav/App/index.js
> +// Is this necessary?
I have no idea about this 🤔

2021-06-09 19:09 UTC, wachunei commented on app/components/UI/DrawerView/index.js
> +		this.props.navigation.navigate('SetPasswordFlow', this.props.passwordSet && { screen: 'AccountBackupStep1' });
```ts
this.props.passwordSet && { screen: 'AccountBackupStep1' }
```

^ if `this.props.passwordSet` is `false`, navigate will be called as `navigate('SetPasswordFlow', false)`, according to docs the second argument must be a params object, I would not rely on passing a boolean, it better be undefined, wdyt?

2021-06-09 19:29 UTC, wachunei commented on app/components/UI/NavbarBrowserTitle/index.js
>  	};
I've seen this pattern a few times, I propose we change it.

`??` operator returns right side value only when left side value is nullish (`null` or `undefined`), which is the same condition `?.` operator uses.

In this case I suggest we change this for:

```ts
this.props.route.params?.showUrlModal?.({ urlInput: this.props.url })
```
Instead of creating noop functions

2021-06-09 19:46 UTC, wachunei commented on app/components/UI/Notification/index.js
> +		const routes = navigation.dangerouslyGetState().routes;
since this is already a functional component we should use
`const routes = useNavigationState(state => state.routes)` at top level instead of `dangerouslyGetState()`

2021-06-09 19:51 UTC, wachunei commented on app/components/UI/WhatsNewModal/index.js
> +			const route = findRouteNameFromNavigatorState(props.navigation.dangerouslyGetState());
We should refactor `findRouteNameFromNavigatorState` to receive `routes` directly.
And in places we can obtain `routes` by using
```ts
const routes = useNavigationState(state => state.routes);
```

2021-06-09 20:02 UTC, wachunei commented on app/components/Views/SendFlow/SendTo/index.js
> +		const targetAddress = (route.params?.txMeta ?? null)?.target_address;
Refactor as `route.params?.txMeta?.target_address`

2021-06-09 20:06 UTC, wachunei commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +		const network = route.params?.network ?? undefined;
I've seen this a few times too: `value ?? undefined`, I think we should remove `?? undefined` unless that case is we want to explicitly set a `null` as `undefined` (`null ?? undefined`)

2021-06-09 20:08 UTC, wachunei commented on app/components/Views/SimpleWebview/index.js
>  		if (uri) {
This is a similar case, we should remove nullish coalescing operator from `value ?? null`, unless we wan to explicitly convert `undefined` to `null`

2021-06-09 20:21 UTC, rickycodes commented on app/components/UI/NavbarBrowserTitle/index.js
>  	};
I agree with this :100:

2021-06-10 10:17 UTC, andrepimenta commented on app/components/Nav/App/index.js
> +// Is this necessary?
@estebanmino do you know?

2021-06-10 10:17 UTC, andrepimenta commented on app/components/UI/DrawerView/index.js
> +		this.props.navigation.navigate('SetPasswordFlow', this.props.passwordSet && { screen: 'AccountBackupStep1' });
Fixed thanks!

2021-06-10 10:22 UTC, andrepimenta commented on app/components/UI/NavbarBrowserTitle/index.js
>  	};
Yeah I basically blindly replaced every instance of `navigation.getParam('ABC', DEFAULT)` with `route.params?.ABC ?? DEFAULT` as they mention in the documentation. See https://reactnavigation.org/docs/upgrading-from-4.x#no-more-getparam

I did this to be faster because I didn't know how much more changes I still had to do to make this work, and also to make sure everything behaved the same (say something expecting null instead of undefined for some reason).

But yeah I think this is a good step to do now since everything else is working! Just changed this, thanks!!

2021-06-10 10:23 UTC, andrepimenta commented on app/components/Views/SendFlow/SendTo/index.js
> +		const targetAddress = (route.params?.txMeta ?? null)?.target_address;
My related comment: https://github.com/MetaMask/metamask-mobile/pull/2731#discussion_r649053478

Fixed!!

2021-06-10 10:23 UTC, andrepimenta commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +		const network = route.params?.network ?? undefined;
My related comment: #2731 (comment)

Fixed!!

2021-06-10 10:23 UTC, andrepimenta commented on app/components/Views/SimpleWebview/index.js
>  		if (uri) {
My related comment: #2731 (comment)

Fixed!!

2021-06-10 10:24 UTC, andrepimenta commented on app/components/UI/Notification/index.js
> +		const routes = navigation.dangerouslyGetState().routes;
Do you wanna do this part?

2021-06-10 10:24 UTC, andrepimenta commented on app/components/UI/WhatsNewModal/index.js
> +			const route = findRouteNameFromNavigatorState(props.navigation.dangerouslyGetState());
Do you wanna do this part?

2021-06-10 10:56 UTC, wachunei commented on app/components/UI/WhatsNewModal/index.js
> +			const route = findRouteNameFromNavigatorState(props.navigation.dangerouslyGetState());
I'll take care of this today

2021-06-23 20:27 UTC, ibrahimtaveras00 commented
**Issue 1:**

On onboarding wizard when attempting to explore the browser doesn't work; seen here = https://recordit.co/0e8vcow8rv (start at 37 sec mark) 

![Screen Shot 2021-06-23 at 3 57 47 PM](https://user-images.githubusercontent.com/41752922/123162520-b1bdd100-d43e-11eb-9472-02667f30ada8.png)

**Issue 2:** 

When tapping on "Learn more about gas fees" on the educate gas fee
![image](https://user-images.githubusercontent.com/41752922/123163508-c9498980-d43f-11eb-9909-2e1d25d44184.png)

I end up getting the following errors:

![Screen Shot 2021-06-23 at 4 13 48 PM](https://user-images.githubusercontent.com/41752922/123163539-d36b8800-d43f-11eb-8395-a214543d20fc.png)

![Screen Shot 2021-06-23 at 4 13 32 PM](https://user-images.githubusercontent.com/41752922/123163564-db2b2c80-d43f-11eb-8559-962e2e8260ff.png)

2021-06-24 23:02 UTC, ibrahimtaveras00 requested changes
Above issues have been resolved!

Other issues:

**Issue 4:**

tap on a txn and then tap on the view on etherscan, then tap X and tap back and go back to wallet and you will see this error:

![Screen Shot 2021-06-24 at 3 01 20 PM](https://user-images.githubusercontent.com/41752922/123341661-59f59780-d51c-11eb-8b90-8f5a9e6f36ac.png)

seen here = https://recordit.co/nZpQ7uIgr0

**Issue 5:**

I'm not seeing the seed recovery phrase video in onboarding flow, nor on settings > Security & Privacy 

seen here = https://recordit.co/tItYEecCF0

![Screen Shot 2021-06-24 at 6 23 57 PM](https://user-images.githubusercontent.com/41752922/123342234-60d0da00-d51d-11eb-87b7-f3699746d0ca.png)

**Issue 6:**

If I tap learn more in the sign message warning box, I get the following exception 

![Screen Shot 2021-06-24 at 6 14 28 PM](https://user-images.githubusercontent.com/41752922/123342338-92e23c00-d51d-11eb-97a2-14f285d98b99.png)

seen here = https://recordit.co/Jqcv4Ekyvh

steps:
- go to https://metamask.github.io/test-dapp
- connect wallet
- scroll down and tap on on "Sig" under ETH Sign category 
- tap on the learn more link in the warning box

**Issue 7:** 

Remind me later on the secure your wallet flow not behaving as expected 

seen here = https://recordit.co/O6RtMbNIyT

steps:
- create a new wallet
- on the "Secure your wallet" page, tap on remind me later
- tap inside the check box and tap Skip
- agree or disagree to metametrics
- tap no thanks on the onboarding tutorial
- on the protect your wallet sticky tap on protect wallet (notice how the sticky doesn't go away) and covers the Start CTA from being tapped 
- next tap remind me later to get rid of the sticky 
- now tap on the Remind me later button above the (Not recommended) text 
- notice how you're stuck on this page and you can no longer go back to wallet

**Issue 8:**

I get the following exception when tapping on the "Continue to purchase ETH" button on the gas education flow

![Screen Shot 2021-06-24 at 6 47 38 PM](https://user-images.githubusercontent.com/41752922/123342943-ae9a1200-d51e-11eb-8b0c-c49d119992bc.png)

seen here = https://recordit.co/u7kfPQcH03

**Issue 9:**

The title to view seed phrase is different than current prod 

![image](https://user-images.githubusercontent.com/41752922/123343048-f9b42500-d51e-11eb-8d46-98c3bc8767bb.png)

**Issue 10:**

The title to view private key is different than current prod 

![Screen Shot 2021-06-24 at 7 08 37 PM](https://user-images.githubusercontent.com/41752922/123343358-9bd40d00-d51f-11eb-8a8b-591e0e455371.png)

**Issue 11:**

On android, if I tap the device back button on metametrics screen it doesn't prevent me from going back nor show the alert box anymore compared to prod

<img src="https://user-images.githubusercontent.com/41752922/123344089-1e110100-d521-11eb-9a57-65fe4a1d025e.png" width=50% height=50%>

**Issue 12:**

When attempting to open a deeplink, I am taken to the browser, however, the URL does not load and I am just on the browser homepage.

seen here = http://recordit.co/wtTJ5pivh1

To reproduce, you can open this page on chrome and tap this link:
https://metamask.app.link/dapp/metamask.github.io/test-dapp/ 

**Issue 13:**

If I import a private key by scanning the QR directly from wallet view, I get the following error:

![Screen Shot 2021-06-24 at 7 46 55 PM](https://user-images.githubusercontent.com/41752922/123345829-f2901580-d524-11eb-8f74-93a98b51ee49.png)

steps:
- start on wallet view
- tap on QR scanner on top right
- scan a QR code for a private key

**Issue 14:**

I cannot scroll on the NFT modal on Android devices 

![image](https://user-images.githubusercontent.com/41752922/123346431-44856b00-d526-11eb-8486-150f76094383.png)

**Issue 15:**

When I relaunch Android, and log in, I notice the following on the bottom for a quick second, but then goes away:

![image](https://user-images.githubusercontent.com/41752922/123350495-1e14ff00-d529-11eb-9276-e925e0f60b74.png)

2021-06-28 17:57 UTC, ibrahimtaveras00 commented
**Issue 17:**

Reset wallet flow not working as expected.  on iOS, it seemed like it imported an account even though I didn't select anything, while on Android, I couldn't even get the modal to pop up to type "delete" 

seen here = http://recordit.co/esIXuDY7Ot

**Issue 18:**

Sync with extension navigation issues:
on iOS it immediately takes me to the login page after successfully
on Android it works, but opens up the QR scanner again when it shouldn’t

2021-06-29 16:20 UTC, ibrahimtaveras00 commented
Issues 1 - 6 = Resolved 👍🏽 
**Issue 7** = still happens https://recordit.co/MvR0ygtB8Y
Issues 8 - 13 = Resolved 👍🏽 
**Issue 14** = still happens
Issues 15 - 18 = Resolved 👍🏽

2021-06-29 22:06 UTC, ibrahimtaveras00 commented
Latest Outstanding Issues:

- **Issue 14**
I cannot scroll on the NFT modal on Android devices

![image](https://user-images.githubusercontent.com/41752922/123873483-8a667880-d904-11eb-847b-00484a8c316f.png)

- **Issue 21**
delete/reset wallet flow no longer keeps user on "Wallet setup page" and doesn't show delete wallet notification seen here = http://recordit.co/RTogvGfObY

all other issues have been resolved 👍🏽

2021-07-02 02:12 UTC, ibrahimtaveras00 approved these changes
All fixes look good, QA Passed 👍🏽

2021-07-02 15:09 UTC, merged