Feature/video subtitles
MetaMask/metamask-mobile pull request #2813
Opened 2021-06-16 15:17 UTC by sethkfman

**Description**

Subtitle work for translations

**Checklist**

* [X ] There is a related GitHub issue
* [X] Tests are included if applicable
* [X] Any added code is fully documented

**Issue**

Resolves #2665

2021-06-18 20:50 UTC, wachunei commented on app/components/Views/MediaPlayer/index.js
> +	};
Is there a reason for this change? 🤔

2021-06-18 20:53 UTC, sethkfman commented on app/components/Views/MediaPlayer/index.js
> +	};
Ah, no...lingering debugging. I will remove.

2021-06-18 20:55 UTC, rickycodes approved these changes

2021-08-05 21:34 UTC, ibrahimtaveras00 requested changes
In the issue, it states, "Add subtitles file to the video in all the languages we support (including English, and the 10 other languages we support)"

However, I'm only seeing the subtitles in English

In this example I have my language set to Spanish:

<img width="435" alt="Screen Shot 2021-08-05 at 5 30 51 PM" src="https://user-images.githubusercontent.com/41752922/128424293-06a6631f-7750-458e-9694-978d27ec6a4e.png">

2021-08-06 01:16 UTC, sethkfman commented
@ibrahimtaveras00 Made a small tweak you should be good to test it now.

2021-08-10 23:12 UTC, ibrahimtaveras00 approved these changes
Fix looks good; when OS system language = MM app language all works well 👍🏽 

The only exception is we do not have the Chinese language translations.

2021-08-11 16:42 UTC, merged