Feature/improve warning eth sign
MetaMask/metamask-mobile pull request #2852
Opened 2021-06-23 18:41 UTC by sethkfman

**Description**

Copy text change for eth_sign modal

**Checklist**

* [X] There is a related GitHub issue
* [X] Tests are included if applicable
* [X] Any added code is fully documented

**Issue**

Resolves #2820

2021-06-23 21:16 UTC, rickycodes submitted a review, later dismissed

2021-06-23 21:16 UTC, rickycodes commented on app/components/Views/SendFlow/WarningMessage/index.js
> +export default function WarningMessage({ styleType, warningMessage }) {
rather than adding a prop `styleType` I think the signature for this component should be:
```js
<WarningMessage type={'error'} message={this.renderWarning()} />
```
thoughts?

2021-07-13 15:10 UTC, mobularay commented
@cjeria would you have time to do the design QA for this work, pls? CC @sethkfman 

Thanks! :-)

2021-08-12 12:30 UTC, andrepimenta requested changes, later dismissed

2021-08-12 12:30 UTC, andrepimenta commented on locales/languages/hi-in.json
> -	"swaps": {
Are we removing these translations?

2021-08-18 22:27 UTC, sethkfman commented on locales/languages/hi-in.json
> -	"swaps": {
My branch was outdated with develop. It has been synced. We are not removing the swaps translations

2021-08-31 18:51 UTC, Cal-L approved these changes
LGTM!

2021-09-01 23:50 UTC, cortisiko approved these changes
looks good 👍

2021-09-02 18:35 UTC, merged