[2847] bug in token correct balance
MetaMask/metamask-mobile pull request #2866
Opened 2021-07-05 16:30 UTC by gantunesr

Bug related to a case sensitive match between the keys (address) associated with the token balance.

`0x514910771bf9ca656af840dff83e8264ecf123nm != 0x514910771BF9Ca656af840dff83E8264EcF123NM`

Fix: Case insensitive key match.

2021-07-05 16:32 UTC, andrepimenta approved these changes
LGTM! 👍

2021-08-10 16:56 UTC, cortisiko commented
**Issue 1**

If I were to remove a token from my wallet then re-add it, the token value shows as “0”
see on [android](http://recordit.co/MsRZBiIpKa)
see on [iOS](http://recordit.co/F5MnQIruhu)

to reproduce:

- delete a saved token from your wallet (i deleted chainlink by long pressing the token then tapping delete)
- from the browser, go to coingecko.com
- search for chainlink
- scroll down a little and then tap on “more information”
- tap on the fox logo.
- notice a modal appears with the coin name. notice the coin value is incorrect.

2021-08-10 17:03 UTC, cortisiko requested changes
sending this guy back. found an issue

2021-08-31 17:30 UTC, cortisiko approved these changes
🎉 🎉 🎉 🎉

2021-09-02 17:54 UTC, sethkfman approved these changes
Updates LGTM

2021-09-02 22:13 UTC, Cal-L requested changes
@gantunesr  Left some comments.

2021-09-02 22:13 UTC, Cal-L commented on app/components/hooks/useTokenBalance.tsx
> + * @returns {Handlers} Handlers `[balance, loading, error]`
Since this is TypeScript, we could remove the types from the TSDocs. 
Ref: https://github.com/microsoft/tsdoc/tree/master/tsdoc

For returns, I wasn't really sure what `Handlers` meant in this context. We could do something like:
`@returns Array that consists of [balance, loading, error]` to be more explicit.

2021-09-07 13:18 UTC, gantunesr commented on app/components/UI/WatchAssetRequest/index.js
> +WatchAssetRequest.propTypes = {
@Cal-L I'll open another PR for the next release to convert this component to TS, for the moment I would merged as it is.

2021-09-07 13:22 UTC, gantunesr commented on app/components/UI/WatchAssetRequest/index.js
> +	const address = Object.keys(contractBalances).find(key => toLowerCaseEquals(key, asset.address));
Agreed, I was thinking to pass the balance value of `contractBalances` to the hook and only fetch the new balance if the value was `undefined` but in a second thought, maybe is better to remove `contractBalances` as a dependence.

2021-09-07 13:22 UTC, gantunesr commented on app/components/hooks/useTokenBalance.tsx
> + * @returns {Handlers} Handlers `[balance, loading, error]`
Fixed, thanks for the reference

2021-09-07 17:25 UTC, Cal-L requested changes
cc: @gantunesr

2021-09-07 17:25 UTC, Cal-L commented on app/components/UI/WatchAssetRequest/index.js
> +		balance = renderFromTokenMinimalUnit(balance, asset.decimals);
Let's move this try catch logic into the `renderFromTokenMinimalUnit` function and have it return a fallback balance of 0.

cc: @gantunesr

2021-09-07 18:20 UTC, Cal-L approved these changes
@gantunesr LGTM

2021-09-07 18:34 UTC, merged