[2783] Change default account name for ENS reversed-resolved name
MetaMask/metamask-mobile pull request #2878
Opened 2021-07-09 04:25 UTC by gantunesr

## Description

If a user has not changed their account nickname (it is not \Account $[0-9]+), and an ENS reverse-resolved name is available for that account, then show the reverse-resolved name.

## To Do

- [x] Default-ENS change in account overview
- [x] Default-ENS change in accounts list
- [x] Remove ENS from account overview ethereum address
- [ ] Update testing

2021-07-09 14:14 UTC, wachunei commented on app/components/UI/AccountList/AccountElement/index.js
>  		const { disabled, updatedBalanceFromStore } = this.props;
`ticker` is destructured again on line 123, I suggest adding it on this line

```suggestion
		const { disabled, updatedBalanceFromStore, ticker } = this.props;
```

2021-07-09 14:14 UTC, wachunei commented on app/components/UI/AccountList/AccountElement/index.js
>  		const { ticker } = this.props;
```suggestion
```

2021-07-09 14:19 UTC, wachunei commented on app/components/UI/AccountList/index.js
> +				});
Fix: `setState` takes a function with `state, props` as arguments ([reference](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous))
```suggestion
				this.setState(state => {
					accountsENS: {
						...state.accountsENS,
						[account.address]: ens
					}
				});
```

2021-07-09 17:06 UTC, rickycodes commented on app/components/UI/AccountList/AccountElement/index.js
> +		const regExp = /Account \d*$/;
i notice we have this same regExp in two spots, maybe we should add another utility method something like `isAccountName` or similar to the existing ens utils and then that way this regEx and logic can live in one place and be easily tested from there as well.

2021-07-09 17:07 UTC, rickycodes requested changes
one small suggestion re: DRY (don't repeat yourself)

2021-07-09 18:26 UTC, gantunesr commented on app/components/UI/AccountList/AccountElement/index.js
>  		const { disabled, updatedBalanceFromStore } = this.props;
Done 👍

2021-07-09 18:26 UTC, gantunesr commented on app/components/UI/AccountList/AccountElement/index.js
>  		const { ticker } = this.props;
Done 👍

2021-07-09 18:27 UTC, gantunesr commented on app/components/UI/AccountList/index.js
> +				});
Fixed!

2021-07-09 18:28 UTC, gantunesr commented on app/components/UI/AccountList/AccountElement/index.js
> +		const regExp = /Account \d*$/;
Fixed! It's only pending the test to check the logic

2021-07-13 03:04 UTC, rickycodes commented
looks like a number of snapshot tests are now failing. you can _usually_ update these via `yarn test:unit:update`

2021-07-13 17:17 UTC, rickycodes approved these changes
code LGTM now
thanks for adding the tests!

2021-08-16 18:26 UTC, cortisiko requested changes
Found an issue:

I notice when you tap on the burger menu the ENS name is missing. 
see [iOS](https://www.screencast.com/t/PxM4lpR0S0 ) and [android](https://www.screencast.com/t/aMX4mbk5ze) 

to reproduce:
log in using your ENS wallet
tap on the burger menu
notice the wallet address appears instead of your ENS name.

2021-08-20 16:45 UTC, cortisiko approved these changes
🚀

2021-08-24 17:02 UTC, merged