Replace safe area view for send flow. Wrap send flow input focus in i…
MetaMask/metamask-mobile pull request #2907
Opened 2021-07-15 23:29 UTC by Cal-L

…nteraction block.

**Description**

- Quick fix for removing extra top padding on send flow.
- Pages include SendTo, Amount, and Confirm
- This also fixes failed keyboard avoiding view on Amount page when auto focusing input. We are now wrapping the input logic in run after interactions.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???
Convo: https://consensys.slack.com/archives/C025ENGEX60/p1626385383041800

2021-07-16 02:02 UTC, rickycodes approved these changes

2021-07-16 02:04 UTC, rickycodes commented on app/components/Views/SendFlow/Amount/index.js
> +			() => this.amountInput && this.amountInput.current && this.amountInput.current.focus()
instead of this you could use optional chaining:

```js
this.amountInput?.current?.focus?.()
```

2021-07-16 13:52 UTC, rickycodes commented
@Cal-L looks like you'll want to update snapshots as well: `yarn test:unit:update`

2021-07-17 01:45 UTC, Cal-L commented
> @Cal-L looks like you'll want to update snapshots as well: `yarn test:unit:update`

Pushed up new snapshots

2021-08-03 23:55 UTC, ibrahimtaveras00 requested changes
Only 1 issue I can see here that only effects iPhone (not smaller devices but devices with a notch; I tried on iPhone 11 Pro)

Seen here = https://recordit.co/XQ3NIAornv 

![Screen Shot 2021-08-03 at 7 33 28 PM](https://user-images.githubusercontent.com/41752922/128100599-d8e82123-63c2-48df-846a-4123d3cd3dff.png)

Steps to reproduce: 

I was only able to reproduce this via a deeplink while the app is already open/unlocked

- have the app open 
- on safari open this PR and tap on this deeplink:
https://metamask.app.link/send/0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6@4?value=1e13
- once you're directed to the app you will be on confirm view with the padding off

2021-08-04 23:16 UTC, Cal-L commented
@ibrahimtaveras00 Pushed up fix for padding on deep link
![image](https://user-images.githubusercontent.com/10508597/128267446-fd7c4f60-ec49-4f87-98df-5d69cd415b90.png)

2021-08-05 18:41 UTC, ibrahimtaveras00 approved these changes
Fix looks good, QA Passed 👍🏽

2021-08-06 00:49 UTC, merged