Add support for wallet_switchEthereumChain
MetaMask/metamask-mobile pull request #3023
Opened 2021-08-16 12:23 UTC by andrepimenta

**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2021-08-30 21:01 UTC, ibrahimtaveras00 requested changes
Works as expected.  
However, there is one case I'm curious about:
- go to https://andrepimenta.github.io/wallet_switchEthereumChain.html
- don't add xDai chain yet, but tap on "Switch xDai chain" 

This error shows up = https://recordit.co/aqfCj5bPOa
![Screen Shot 2021-08-30 at 5 01 19 PM](https://user-images.githubusercontent.com/41752922/131405010-984b36b1-6954-4400-ad8d-65a16224da78.png)

Should we see some type of message appear in this case?

2021-09-01 20:56 UTC, ibrahimtaveras00 approved these changes
We're all good here, 👍🏽

2021-09-01 20:59 UTC, sethkfman commented on app/core/RPCMethods/wallet_switchEthereumChain.js
> +const wallet_addEthereumChain = async ({
@rickycodes I would think this should be `wallet_switchEthereumChain`? WDYT

2021-09-02 15:43 UTC, rickycodes commented on app/core/RPCMethods/wallet_switchEthereumChain.js
> +	const params = req.params[0];
```suggestion
	const params = req.params?.[0];

	if (!params || typeof params !== 'object') {
		throw ethErrors.rpc.invalidParams({
			message: `Expected single, object parameter. Received:\n${JSON.stringify(params)}`
		});
	}
```

2021-09-02 16:02 UTC, rickycodes commented on app/core/RPCMethods/wallet_switchEthereumChain.js
> +	const params = req.params[0];
you'll have to verify, but I think this is functionality equivalent.

2021-09-02 17:31 UTC, rickycodes approved these changes
LGTM

2021-09-02 17:39 UTC, merged