Feature/update recents
MetaMask/metamask-mobile pull request #3028
Opened 2021-08-17 03:25 UTC by rickycodes

**Description**

render recents based on items stored in redux instead of from `transactions`

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #2912

2021-08-17 14:17 UTC, rickycodes commented on app/components/Views/Login/index.js
> +							{strings('login.type_delete', { [DELETE]: DELETE })}
unrelated to this, but I wanted to re-utilise this `const` to ensure the `key` is always the string `'delete'`

2021-08-17 14:17 UTC, rickycodes commented on app/components/Views/SendFlow/AddressElement/index.js
> +				onLongPress={() => onAccountLongPress(address)}
no idea why these were disabled

2021-08-17 14:40 UTC, gantunesr approved these changes
lgtm

2021-08-19 23:21 UTC, ibrahimtaveras00 requested changes
Fix states = "In the ‘recent addresses’ list of Send flow, ONLY show the addresses that were previously added & sent to in the “recipient address field”."

I sent SAI to to an address and I am not seeing the same address I added in the recipient address field

seen here = https://recordit.co/bgKck6zJlh

![image](https://user-images.githubusercontent.com/41752922/130156350-37e2ec12-4b32-4ce8-9291-e82614e33c4a.png)

![image](https://user-images.githubusercontent.com/41752922/130156376-302b77ad-21a2-499d-8e6a-bd4a1804cbb7.png)

2021-08-19 23:40 UTC, ibrahimtaveras00 commented
It does work with normal ETH send = http://recordit.co/VrnXby1E6Q

![image](https://user-images.githubusercontent.com/41752922/130157643-ae223f2e-3340-4f91-a02f-cc8578d1f415.png)

2021-08-24 20:17 UTC, ibrahimtaveras00 approved these changes
Fixes look good, QA Passed 👍🏽

2021-08-26 15:03 UTC, merged