[FEATURE] Transaction state
MetaMask/metamask-mobile pull request #3099
Opened 2021-09-07 15:45 UTC by gantunesr

Improvement on how we process transaction state by updating the Transaction Controller. The extension currently has a Transaction State Controller to handle user scenarios, something we lack.

2021-09-07 23:19 UTC, cortisiko approved these changes
didn't notice nothing out of the ordinary here. 💯

2021-09-09 16:50 UTC, rickycodes approved these changes

2021-09-09 16:53 UTC, rickycodes commented on app/components/UI/TransactionElement/utils.js
> +	if (gasUsedBN && isBN(gasUsedBN) && isBN(gasPriceBN)) {
looks like you have the same thing twice here?

2021-09-09 16:54 UTC, rickycodes requested changes
just one small thing

2021-09-09 16:55 UTC, rickycodes approved these changes

2021-09-09 16:58 UTC, merged