Refactor RPC Methods logic (Fix network change)
MetaMask/metamask-mobile pull request #3341
Opened 2021-10-26 12:17 UTC by andrepimenta

**Description**

- Moves the RPC Methods logic from the browser tab to its own file.
- No more dependency on the Browser Tab props.
- No more need for reloading after changing networks.

@cortisiko How to test:
- Test changing networks on https://metamask.github.io/test-dapp/ and on https://ropsten.kyber.network/transfer/eth
- Test the browser in general with dapps signing, transactions, etc.

2021-11-02 23:28 UTC, cortisiko requested changes
found a couple issues:

**Issue 1**
My eth balance does not update correctly when I switch networks. 

For example:

I have eth in my wallet on main net and on ropsten. If I were to connect to uniswap dapp while on main net my eth balance looks correct.
 
If I were to switch my network from main net to ropsten my eth balance does not reflect what I currently have in my wallet on ropsten. Instead my balance reflects my main net balance. 

See [here](http://recordit.co/DJ4PBuFUJz)
Notice this does not happen in prod on [v3.4.1](http://recordit.co/svOWelP9c7)

To reproduce:
With a wallet that has eth on both main net and ropsten open the browser and go to app.uniswap.org
Connect your wallet.
Pay attention to your current ETH. Switch networks to ropsten
Wait 3-4 seconds. Notice your wallet balance does not update correctly.

**Issue 2**

I get a couple errors when I connect to a dapp:

(A) 
`ERROR: header not found. `
And 
(B)
`{"originalError": [Object]}, "message": "undefined is not an object (evaluating '_.default.wallet_switchEthereumChain')"}`

To reproduce:
With a wallet that has eth on both main net and ropsten open the browser and go to app.uniswap.org notice (A)
Connect your wallet. 
 Switch networks from main net  to ropsten
Notice (B) 

AND

Go to the test dapp: https://metamask.github.io/test-dapp/
And try tapping on “ADD XDAI CHAIN”
Notice (B)

2021-11-03 10:56 UTC, andrepimenta commented on app/core/RPCMethods/RPCMethodMiddleware.js
> +export const getRpcMethodMiddleware = ({
This should be done! Thank you!

2021-11-24 22:51 UTC, cortisiko commented
@andrepimenta this ticket is mainly good but I encountered a couple of errors while testing. Not sure if they are anything to worry about so feel free to dismiss them. 

1. 
It is not the end of the world but time to time when I attempt to sign eth on the test dapp: https://metamask.github.io/test-dapp/


 I get: `[MetaMask DEBUG]: [Error: undefined is not an object (evaluating '_messageParams$meta.title')] `

It is not really consistent enough for me to record it. 

To reproduce:
Go here:  https://metamask.github.io/test-dapp/
Connect your wallet 
Scroll to the bottom of the page and tap on “sign ETH”
The error should appear


2.
 this guy is still happening:  `Error: [ethjs-rpc] rpc error with payload {"id":968630319409,"jsonrpc":"2.0","params":[{"to":"0x","data":"0x691f3431c7db9ae18f13a98c6f23dbad809949c7b232f627f38d8e0b0cf809d65f1cb206"},"latest"],"method":"eth_call"}`

See the first instance of when this was reported [here](https://consensys.slack.com/archives/C029D95J3K8/p1635195551008000 ) in slack. 

To reproduce:

switch from a custom network( avalanche or polygon) to main net and vice versa.

2021-12-06 20:08 UTC, rickycodes commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +				let version = appVersion;
you already have `let version` in root scope. was this intended to simply be `version = appVersion;`?

2021-12-06 20:12 UTC, rickycodes commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +				res.result = `MetaMask/${version}/Beta/Mobile`;
could this instead be?
I don't think you need a new variable?
```suggestion
				if (!appVersion) {
					appVersion = await getVersion();
				}
				res.result = `MetaMask/${version}/Beta/Mobile`;
```

2021-12-07 01:08 UTC, gantunesr commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +				res.result = `MetaMask/${version}/Beta/Mobile`;
Should this `MetaMask/${version}/Beta/Mobile;` also be changed?

2022-01-14 18:21 UTC, andrepimenta commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +				res.result = `MetaMask/${version}/Beta/Mobile`;
I have updated to use Ricky code. Regarding Beta/Mobile I think we could change it but no right now because I am not sure if devs are using this specific string to check if it's the mobile app using their dapp.

2022-01-18 20:20 UTC, sethkfman approved these changes
Not blockers but I have a number of suggestions as things progress in this area.

2022-01-18 20:20 UTC, sethkfman commented on app/core/RPCMethods/utils.ts
> +export const polyfillGasPrice = async (method: string, params: any[] = []) => {
Would there be value in testing this?

2022-01-18 20:20 UTC, sethkfman commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +				res.result = `MetaMask/${appVersion}/Beta/Mobile`;
Is this still in Beta?

2022-01-18 20:20 UTC, sethkfman commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +		const rpcMethods: any = {
I don't think this needs to be done for this PR but I think there would be value into creating separate utility files that encapsulate and test a related group of RPC methods (e.g. all the `eth_`, all the `wallet_`, & all the `metamask_` methods) similar to what was done with `polyfillGasPrice`

2022-01-18 22:20 UTC, Cal-L reviewed
I pushed a temp fix for TS errors and left some comments.

2022-01-18 22:20 UTC, Cal-L commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +import { store } from '../../store';
Just a thought: Feels more consistent if we moved all redux action creators + selectors to the `BrowserTab.js` file and pass callbacks the same way we do with most of the `getRpcMethodMiddleware` params.

2022-01-18 22:20 UTC, Cal-L commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +					if (showApprovalDialog) return;
Regarding `return` statement. Do we need to set `res` or throw here? I suspect webview will resolve the request automatically, but probably better to explicitly resolve ourselves.

2022-01-18 22:20 UTC, Cal-L commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +					accounts: await getAccounts(),
I think I'm just not familiar with this order. Will JS wait for the accounts before setting the `res.result` or does it return with accounts being a [Promise]?

2022-01-19 09:51 UTC, andrepimenta commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +				res.result = `MetaMask/${appVersion}/Beta/Mobile`;
Fixed

2022-01-19 09:52 UTC, andrepimenta commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +				res.result = `MetaMask/${version}/Beta/Mobile`;
I updated Beta/Mobile to just Mobile. I just saw that the text changed with {version} so devs should be expecting it to change always.

2022-01-19 09:54 UTC, andrepimenta commented on app/core/RPCMethods/utils.ts
> +export const polyfillGasPrice = async (method: string, params: any[] = []) => {
I will be refactoring this file for the SDK epic and will include more test, so I will do that work there if it's ok

2022-01-19 09:54 UTC, andrepimenta commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +		const rpcMethods: any = {
I will be refactoring this file for the SDK epic and will include more test, so I will do that work there if it's ok. I have it in my todos :)

2022-01-19 09:57 UTC, andrepimenta commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +import { store } from '../../store';
The objective was that this file was as independent as possible from components that call it. For the SDK work, I will even move all the UI events out of the Browser tab, so we will need to pass very few variables to this. I think it's much more manageable once we have multiple parts of the app calling this file. Wdyt?

2022-01-19 10:00 UTC, andrepimenta commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +					accounts: await getAccounts(),
Yeah it will wait, accounts will be the result of `await getAccounts()` resolved

2022-01-19 10:17 UTC, andrepimenta commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +					if (showApprovalDialog) return;
Good question, I have tested and this returns undefined. I think this always worked like this so I am bit hesitant in changing this, not sure if dapps are now expecting an undefined. I am actually refactoring some parts of this for the SDK so I could take a closer look then.

2022-01-20 18:28 UTC, Cal-L commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +import { store } from '../../store';
Ah got it. Makes sense, we can discuss architecture when we get there!

2022-01-26 21:34 UTC, cortisiko approved these changes
🌮 🌮 🌮

2022-01-27 09:23 UTC, merged