Add lavamoat
MetaMask/metamask-mobile pull request #3367
Opened 2021-11-02 19:49 UTC by rickycodes

**Description**

This adds lavamoat to the build

2021-11-02 20:05 UTC, sethkfman commented on .github/workflows/ci.yml
> +      - run: yarn setup
What about `bitrise.yml`? Do you think since it always is being run on branches we don't need to have the `yarn setup` in Bitrise?

2021-11-02 20:27 UTC, rickycodes commented on .github/workflows/ci.yml
> +      - run: yarn setup
ah! good point. added!

2021-11-03 15:49 UTC, rickycodes commented on package.json
> +    "clean:node": "rm -rf node_modules && yarn --frozen-lockfile --network-timeout 300000 --network-concurrency 1",
works for me.

2021-11-03 20:43 UTC, sethkfman approved these changes
LGTM

2021-11-03 20:44 UTC, sethkfman requested changes
We should add some instructions in our readMe

2021-11-04 15:32 UTC, sethkfman approved these changes
lgtm

2021-11-08 18:12 UTC, merged