Consume split TokenDetectionsController and CollectibleDetectionController (previously AssetDetectionController)
MetaMask/metamask-mobile pull request #3380
Opened 2021-11-04 18:21 UTC by adonesky1

This PR makes required changes to consume the split TokenDetectionsController and CollectibleDetectionController (previously AssetDetectionController) in v19.0.0 of @metamask/controllers.

2021-11-04 18:28 UTC, adonesky1 commented
No idea why CLA is failing here... I've opened and merged PRs into this repo before? The logs in the action don't really provide much clarity?
`Error: Waiting on additional CLA signatures.`

2021-11-04 18:36 UTC, Gudahtt commented
The CLA bot is a relatively recent addition.

2021-11-04 19:19 UTC, gantunesr commented
Yes, as Mark points out, it's a recent addition. You have to make your organization visibility public or comment the following statement: _I have read the CLA Document and I hereby sign the CLA_

2021-11-04 19:22 UTC, gantunesr submitted a review, later dismissed
LGTM

2021-11-04 19:24 UTC, adonesky1 commented
I have read the CLA Document and I hereby sign the CLA

2021-11-12 13:43 UTC, gantunesr commented
@Cal-L spotted some things that should be updated before merging this PR

2021-11-15 18:18 UTC, cortisiko requested changes
found an issue: 

My ERC-20 tokens (chainlink & compound)  does not appear after I import my wallet: http://recordit.co/7H7AIeh4b3

Compared to prod: http://recordit.co/x311rIyDT0 

To reproduce:
Launch the app
Import a wallet with eth and ERC-20 tokens

2021-11-16 22:38 UTC, adonesky1 commented
@cortisiko @gantunesr having alot of of trouble with my mobile environment, could you test again and see if you are still seeing [this issue](https://github.com/MetaMask/metamask-mobile/pull/3380#pullrequestreview-806405016)

2021-11-18 00:46 UTC, gantunesr requested changes

2021-11-18 00:46 UTC, gantunesr commented on app/core/Engine.js
>  					getBalancesInSingleCall:
Looks like `getBalancesInSingleCall` is from `TokenDetectionController`

2021-11-18 12:44 UTC, gantunesr reviewed
@adonesky1 The changes I pointed out helps to solve the bug that Curtis got, I also got the same bug but after the changes it was resolved

2021-11-18 15:09 UTC, adonesky1 commented on app/core/Engine.js
>  			KeyringController,
Whoops yeah that'll do it 😅 Thanks!

2021-11-18 15:14 UTC, adonesky1 commented on app/core/Engine.js
>  					getBalancesInSingleCall:
Oh you mean it should be passed to the TokenDetectionController not the CollectibleDetectionController. Yes you're right.

2021-11-18 15:20 UTC, gantunesr approved these changes
LGTM

2021-11-23 17:29 UTC, cortisiko commented
🌮 🌮 🌮 🌮

2021-11-23 20:17 UTC, cortisiko approved these changes

2021-11-23 20:30 UTC, merged