[FIX] Backwards compatibility CollectiblesController
MetaMask/metamask-mobile pull request #3386
Opened 2021-11-08 13:46 UTC by gantunesr

# Description

With version 18.0.0 of the controllers, there was on the data type of the property `tokenId` (`Number -> String`), this update ensures that the app works properly with both data types.

## ⚠️  Blockers 

- PR #3379

# Tasks

- [x] Remove previous fix.
- [x] Add controllers update
- [x] Update snapshots (if necessary) 

# References

- [MM Controllers PR](https://github.com/MetaMask/controllers/pull/630)

2021-11-11 21:29 UTC, Cal-L requested changes

2021-11-11 21:29 UTC, Cal-L commented on app/core/Engine.js
>  					getBalancesInSingleCall:
I believe `getBalancesInSingleCall` belongs under `TokenDetectionController`

2021-11-11 21:45 UTC, Cal-L commented on app/core/Engine.js
> -			AssetsDetectionController,
I'm pretty sure both `TokenDetectionController` and `CollectibleDetectionController` is needed here for the engine  reducer to recognize the state if these controllers. Here's how the reducer is accessing the Engine.state: `newState.backgroundState[action.key] = Engine.state[action.key];`

2021-11-12 13:41 UTC, gantunesr commented on app/core/Engine.js
> -			AssetsDetectionController,
You're right! This change is from this PR https://github.com/MetaMask/metamask-mobile/pull/3380 which is a blocker to this one

2021-11-12 13:42 UTC, gantunesr commented on app/core/Engine.js
>  					getBalancesInSingleCall:
Thats true! This should be update on PR #3380 which is blocking this one

2021-11-12 13:42 UTC, gantunesr commented on app/core/Engine.js
>  					getBalancesInSingleCall:
Thats true! This should be update on PR #3380 which is blocking this one

2021-11-12 13:42 UTC, gantunesr commented on app/core/Engine.js
> -			AssetsDetectionController,
You're right, this should be fixed in #3380 which is blocking this PR

2021-12-03 16:44 UTC, gantunesr commented
This PR is no longer necessary

2021-12-03 16:44 UTC, closed without merging