[UPGRADE] Android SDK and dependencies to support SDK 30
MetaMask/metamask-mobile pull request #3412
Opened 2021-11-12 16:41 UTC by sethkfman

**Description**

Bump Android SDK version to compile and target 30. Also, updated dependencies required for this bump. 

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2021-11-12 18:37 UTC, rickycodes requested changes
this looks good to me and no longer crashes woot

just a few small things. awesome stuff.

2021-11-12 18:37 UTC, rickycodes commented on android/app/build.gradle
> +    implementation "com.squareup.okhttp3:logging-interceptor:4.9.1"
tabbing is inconsistent here

2021-11-12 18:37 UTC, rickycodes commented on app/components/Views/Entry/index.js
> +	console.log('Hermes Enabled', !!global.HermesInternal);
you'll want to take this out.

2021-11-16 17:52 UTC, rickycodes approved these changes
LGTM

2021-11-16 20:09 UTC, cortisiko approved these changes
🌮 🌮 🌮 🌮

2021-11-16 22:19 UTC, merged