[FIX] Fixes text field frame got cut off
MetaMask/metamask-mobile pull request #3548
Opened 2022-01-08 04:05 UTC by blackdevelopa

**Description**

On two different screens, the text field frame cuts off the bottom part of the text. This PR fixes both bugs.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #3542

2022-01-10 12:10 UTC, blackdevelopa commented
I have read the CLA Document and I hereby sign the CLA

2022-01-10 19:59 UTC, gantunesr commented on package.json
> +    "react-native-responsive-fontsize": "^0.5.1",
Can you explain why adding this dependency is necessary?

2022-01-11 06:12 UTC, blackdevelopa commented on package.json
> +    "react-native-responsive-fontsize": "^0.5.1",
I introduced this package to minimize using fixed values (px) instead of responsive values that scale across different devices.

2022-01-27 08:23 UTC, Cal-L requested changes
Left a comment and made a PR for suggested changes:
https://github.com/MetaMask/metamask-mobile/pull/3652

2022-01-28 10:58 UTC, blackdevelopa commented on app/components/Views/BrowserTab/index.js
> +		fontSize: Device.isAndroid() ? 16 : RFValue(13),
Absolutely valid point. I have updated this PR and removed the library. Thank you.

2022-02-07 17:24 UTC, Cal-L approved these changes
LGTM

2022-02-15 13:24 UTC, merged