[FIX] branch multiple subscribers
MetaMask/metamask-mobile pull request #3570
Opened 2022-01-13 21:53 UTC by sethkfman

**Description**

There was a bug that allowed the creation of multiple Branch subscribers which would trigger multiple WalletConnect & Deep Link sessions. 

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2022-01-13 23:15 UTC, gantunesr approved these changes
LGTM

2022-01-17 20:59 UTC, Fatxx commented
LGTM

2022-01-17 21:05 UTC, gantunesr approved these changes
![Alt Text](https://media.giphy.com/media/3o6gE2LfcxozwGwTbq/giphy.gif)

2022-01-26 14:17 UTC, atifbuttgss approved these changes

2022-02-01 16:47 UTC, rickycodes commented on android/app/src/main/AndroidManifest.xml
> +				<data android:scheme="https" />
this looks like a mistake? you're missing `android:host` for these. if it's intentional you probably only need the one tag?

2022-02-01 16:49 UTC, rickycodes commented on app/components/Nav/App/index.js
> +const isIos = Platform.OS === 'ios';
I'm seeing this a fair bit, there's actually a utility for this already in `util/device`: https://github.com/MetaMask/metamask-mobile/blob/develop/app/util/device/index.js#L15

2022-02-01 16:49 UTC, rickycodes requested changes
a few small suggestions

2022-02-01 16:56 UTC, andreahaku commented on app/components/Nav/App/index.js
> +const isIos = Platform.OS === 'ios';
awesome! thanks. Will use it.

2022-02-01 17:04 UTC, rickycodes approved these changes

2022-02-02 19:26 UTC, merged