code optimization, extract common code hooks usePrevious
MetaMask/metamask-mobile pull request #3573
Opened 2022-01-14 14:44 UTC by nuoyz

**Description**

code optimization: usePrevious code implementations exist in multiple files;

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2022-01-14 14:45 UTC, nuoyz commented
I have read the CLA Document and I hereby sign the CLA

2022-01-14 15:30 UTC, gantunesr requested changes
Good catch! Can you refactor the hook code to TypeScript?

2022-01-14 15:41 UTC, nuoyz commented
ok

2022-01-14 16:18 UTC, gantunesr commented on app/components/hooks/usePrevious.js
> +}
The JS file should be deleted

2022-01-14 16:37 UTC, gantunesr requested changes

2022-01-14 16:37 UTC, gantunesr commented on app/components/UI/Notification/index.js
> +import usePrevious from "../../hooks/usePrevious";
```suggestion
import usePrevious from '../../hooks/usePrevious';
```

2022-01-14 17:10 UTC, nuoyz commented
what do i need to do next?

2022-01-14 18:55 UTC, rickycodes commented
@nuoyz I've taken the liberty of squashing your commits (and properly attributing them). you're PR should be good to merge now :)

2022-02-07 18:49 UTC, gantunesr approved these changes

2022-02-07 18:59 UTC, merged