Line height is distributed unevenly when lineHeight <= fontSize
MetaMask/metamask-mobile pull request #3593
Opened 2022-01-18 12:58 UTC by nuoyz

**Description**

When lineHeight is less than the fontSize, Text shrinks the line's bounding box only by removing space from above the text, rather than distributing the space evenly above and below, as is done with extra line height.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???
![image](https://user-images.githubusercontent.com/11713023/149941558-9f583d71-9194-4bce-b892-93149c9c8d8a.png)
![image](https://user-images.githubusercontent.com/11713023/149941593-da59530e-6b2d-4400-9bc4-2b42c0912616.png)

2022-01-18 12:59 UTC, nuoyz commented
@rickycodes done

2022-01-18 13:17 UTC, gantunesr commented on ios/Podfile.lock
> +  DoubleConversion: cde416483dac037923206447da6e1454df403714
here

2022-01-18 13:17 UTC, gantunesr commented on ios/Podfile.lock
> +  glog: 40a13f7840415b9a77023fbcae0f1e6f43192af3
here

2022-01-18 13:17 UTC, gantunesr requested changes
LGTM. But remove the Podfile changes

2022-01-18 13:55 UTC, nuoyz commented on ios/Podfile.lock
> +  DoubleConversion: cde416483dac037923206447da6e1454df403714
https://github.com/MetaMask/metamask-mobile/commit/c2a294a4214fa94d7deb872a413d1035369969a4#diff-b7d85c35701918f25c9b2c418249f9b66fd9b067676e295a9eff493b73ee1752;  this commit  ios/Podfile.lock file changed

2022-01-18 18:56 UTC, gantunesr reviewed
Hey @nuoyz, looks like the tests are failing, can you ran this command to update the snapshots?

`yarn test:unit:update`

2022-01-19 07:23 UTC, nuoyz commented
> Hey @nuoyz, looks like the tests are failing, can you ran this command to update the snapshots?
> 
> `yarn test:unit:update`

![image](https://user-images.githubusercontent.com/11713023/150083363-e18bd398-9c20-4ae3-95eb-d03512df39fb.png)

2022-02-07 18:48 UTC, gantunesr approved these changes

2022-02-07 18:48 UTC, merged