[WIP]Integrate Keystone - connect Keystone Wallet
MetaMask/metamask-mobile pull request #3647
Opened 2022-01-26 11:12 UTC by soralit

**Description**
This PR adds basic support for connect Keystone Wallet and get extended public key from Keystone Wallet.

**Changes**
1. Add `ConnectQRHardware` view for the whole `connect qr hardware` flow, it has 3 components `Instruction`, `AnimatedQRScanner` and `SelectQRAccounts` and was displayed by conditions. 
2. Add entry of `ConnectQRHardware` on `AccountList`

**Dependencies**
1. `@keystonehq/metamask-airgapped-keyring`: our QR wallet keyring that supports sync xpub, sign txs and data.
2. `@keystonehq/ur-decoder`: our helper lib to decode QR code based on UR type. 

**Others**
This PR is not workable because some changes in `@metamask/controllers` is required. I will raise another PR in `@metamask/controllers` ASAP.

2022-01-27 01:42 UTC, soralit commented
I have read the CLA Document and I hereby sign the CLA

2022-01-27 20:59 UTC, gantunesr requested changes
Hey Sora! This is looking great, I left some comments, let me know what you think

2022-01-27 20:59 UTC, gantunesr commented on app/components/Views/ConnectQRHardware/index.tsx
> +	}, [KeyringController]);
I think having the KeyringController (or any controller) in a dependency array can create performance issues, since it is always getting updated in the background.

2022-01-27 20:59 UTC, gantunesr commented on app/components/Views/ConnectQRHardware/Instruction/index.tsx
> +				source={require('../../../../images/connect-qr-hardware.png')}
This `require` can be moved to a variable

2022-01-28 07:41 UTC, soralit commented on app/components/UI/AccountList/index.js
> +		height: Device.isIphoneX() ? 200 : 170,
This change is for that we add a new option of `connect hardware` below `import account` in AccountList component but the footer's height is not enough to contain 3 items. So I increased it.

2022-01-28 07:45 UTC, soralit commented on app/components/UI/AccountList/index.js
> +		// });
I think extension is not tracking QR hardware event currently.

2022-01-28 07:46 UTC, soralit commented on app/components/Views/ConnectQRHardware/SelectQRAccounts/index.tsx
> +	accounts: { address: string; index: number; checked: boolean; exist: boolean }[];
Cool

2022-01-28 07:52 UTC, soralit commented on app/components/Views/ConnectQRHardware/index.tsx
> +				</TouchableOpacity>
Cool

2022-01-28 09:47 UTC, soralit commented on app/components/Views/ConnectQRHardware/SelectQRAccounts/index.tsx
> +};
Cool

2022-01-28 09:54 UTC, soralit commented on app/components/Views/ConnectQRHardware/index.tsx
> +	}, [KeyringController]);
I think it can be resolved by 'fix' the KeyringController by a `useMemo` hook.
```
const KeyringController = useMemo(() => {const {keyring} = Engine.context as any; return keyring;}, []);
```

2022-01-28 09:59 UTC, soralit commented on app/components/Views/ConnectQRHardware/Instruction/index.tsx
> +			</TouchableOpacity>
Modified the style to fix that.

2022-01-28 14:48 UTC, gantunesr commented on app/components/UI/AccountList/index.js
> +		// });
Aah ok, we can add the event in another PR, I'll check with Omna how this event should be tracked

2022-02-03 13:42 UTC, gantunesr commented on app/components/Views/ConnectQRHardware/index.tsx
> +				};
Here you're modifying the account object with the attribute `exist` that is not defined in the interface (line 52). Which is the same interface (`IAccount`) in the component `SelectQRAccounts`. Do you think it's better to move that interface to a new file and import it here and in `SelectQRAccounts`?

You can also define this interface in the controllers, but either way would work for this case.

2022-02-17 07:52 UTC, soralit commented on app/components/Views/ConnectQRHardware/AnimatedQRScanner/index.tsx
> +	}, [purpose]);
I think you are correct, actually the `purpose` was not expected to be changed in one connecting or signing process.

2022-02-17 17:24 UTC, merged