Network Specific Asset Education
MetaMask/metamask-mobile pull request #3648
Opened 2022-01-26 13:30 UTC by blackdevelopa

**Description**

This PR updates a user when they toggle to a different network and have no token/funds present.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #

2022-02-02 16:21 UTC, blackdevelopa commented on app/components/UI/NetworkList/index.js
> +		this.props.onNetworkSelected(type, 'ETH');
Updated

2022-02-08 23:44 UTC, sethkfman commented on app/components/UI/NetworkInfo/index.tsx
> +const learnMoreUrl = 'https://metamask.zendesk.com/hc/en-us/articles/4404424659995';
Suggest pulling this from strings in the even we have other translations.

2022-02-08 23:49 UTC, sethkfman commented on app/components/UI/NetworkInfo/index.tsx
> +const UnknownAsset = () => (
We typically embed the smaller components inside as render functions that uses the useEffect hook to reduce renders. If you want to keep `UnknownAsset` & `Description` as a separate component move them to another file.

2022-02-08 23:54 UTC, sethkfman commented on app/reducers/networkSelector/index.js
> +export const onboardNetworkAction = (data) => ({
We typically have separate files for the actions. Move this action to the `app/actions`

2022-02-08 23:55 UTC, sethkfman commented on app/util/custom-gas/index.js
> +export const PRIVATENETWORK = 'PRIVATENETWORK';
Consider moving this to the `app/constants/network.js`

2022-02-08 23:56 UTC, sethkfman reviewed
A few minor comments around coding style/project arch. Overall looks good.

2022-02-09 04:49 UTC, blackdevelopa commented on app/util/custom-gas/index.js
> +export const PRIVATENETWORK = 'PRIVATENETWORK';
Updated. Thank you

2022-02-09 18:07 UTC, sethkfman approved these changes
LGTM

2022-02-10 18:47 UTC, sethkfman approved these changes
LGTM

2022-02-10 18:48 UTC, sethkfman commented on app/components/UI/NetworkInfo/index.tsx
> +const UnknownAsset = () => (
Completed

2022-02-10 18:48 UTC, sethkfman commented on app/components/UI/NetworkInfo/index.tsx
> +const learnMoreUrl = 'https://metamask.zendesk.com/hc/en-us/articles/4404424659995';
Completed

2022-02-15 20:43 UTC, cortisiko requested changes
Issue 1
when I:
go to chainlist.org
add a network (I used avalanche)
I am taken back to the wallet view and I do not see [the educational modal ](http://recordit.co/xOnL57mjTi)

Issue 2
[After importing a network manually the education modal does not appear.](http://recordit.co/r9uXmiWO7A)

to reproduce:
open the drawer
go to the networks page and tap on "add a network"
Input these into the empty fields: Network name: xDai, RPC url: https://dai.poa.network/, Symbol: xDai, Chain ID: 100 
tap on Add token
notice the network is added, you are on the wallet view but the education modal does not appear.

2022-03-18 10:50 UTC, blackdevelopa commented
Closing this PR and updating this #3910

2022-03-18 10:50 UTC, closed without merging