adds support for 'twitter://' scheme by the internal browser
MetaMask/metamask-mobile pull request #3664
Opened 2022-01-31 12:49 UTC by andreahaku

### **Description**
Twitter is attempting to reliably link back to the Twitter mobile app from MetaMask and is not able to do this on iOS.

Confirmed flow: 
User selected Choose NFT -> Deep link: https://metamask.app.link/dapp/https://ton.twitter.com/ -> Dapp browser and triggers App Request for Wallet Connections -> On success -> twitter:// called -> return to Twitter

### **Technical Details**
-   To support this link back functionality `twitter://` needs to be added the URL scheme

### **Acceptance Criteria**
-   Install Twitter on iOS test device
-   Create a link that can be loaded on the browser `twitter://test`
-   The link above should be open the Twitter app

### **References**
-   https://medium.com/wolox/ios-deep-linking-url-scheme-vs-universal-links-50abd3802f97

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2022-01-31 20:03 UTC, rickycodes commented on app/core/DeeplinkManager.js
> +		const urlObj = new URL(url.replace('http://', '').replace('http://', ''));
same replace call twice?

2022-01-31 20:04 UTC, rickycodes requested changes
noticed one small thing

2022-01-31 20:14 UTC, andreahaku commented on app/core/DeeplinkManager.js
> +		const urlObj = new URL(url.replace('http://', '').replace('http://', ''));
You’re right :) thanks a lot!

2022-02-02 01:38 UTC, cortisiko requested changes
@andreahaku  sending this back your way. Deep links appears to be broken.

to reproduce:
attempt to deep link using: https://metamask.app.link/dapp/uniswap.eth


see android: http://recordit.co/uWHM733AZ5 
see iOS: http://recordit.co/f0ge8PFe2S 


In terms of testing what this actually does, I attempt to deep link using  twitter://test  and it successfully launches the twitter app. Should I do anything extra or the twitter app launching is sufficient?

2022-02-03 13:59 UTC, andreahaku commented
> @andreahaku sending this back your way. Deep links appears to be broken.
> 
> to reproduce: attempt to deep link using: https://metamask.app.link/dapp/uniswap.eth
> 
> see android: http://recordit.co/uWHM733AZ5 see iOS: http://recordit.co/f0ge8PFe2S
> 
> In terms of testing what this actually does, I attempt to deep link using twitter://test and it successfully launches the twitter app. Should I do anything extra or the twitter app launching is sufficient?

Deeplinks should be fixed now. Yes it should open Twitter when using "twitter://" scheme from the browser and you can also test it using the deeplink that is the description. Thanks :)

2022-02-03 18:29 UTC, cortisiko approved these changes
This is QA passed!

2022-02-04 15:25 UTC, rickycodes approved these changes

2022-02-04 20:30 UTC, merged