Feature/onramp critical path UI
MetaMask/metamask-mobile pull request #3689
Opened 2022-02-03 14:27 UTC by alaahd

**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2022-02-03 19:15 UTC, wachunei requested changes
There are some other little details that will be

2022-02-03 19:15 UTC, wachunei commented on app/components/Nav/Main/MainNavigator.js
> +				})}
Let's follow MMM convention and move this to `GetStarted.navigationOptions` and the content to `app/components/UI/Navbar/index.js`, including `styles` definition.

I don't think all the components share the exact same header, so declare the options per Screen instead of the Navigator. The pattern is to use `screenOptions` at the navigator level for options that are global instead of defaults to be overridden

2022-02-03 19:15 UTC, wachunei commented on locales/languages/en.json
> +	},
MMM team convention is to have properties that represent the content of the string instead of the role they have in the view.

2022-02-03 19:15 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/GetStarted.js
> +			<StyledButton type={'confirm'} onPress={() => navigation.navigate('PaymentMethod')} style={styles.button}>
When using `onPress` use `const handleOnPress = useCallback(() => ...` to avoid recreating the function on every render. (there are other files that have this same pattern)

2022-02-07 13:17 UTC, alaahd commented on app/components/Nav/Main/MainNavigator.js
> +				})}
I agree with the idea that we need to move the code and styling into `app/components/UI/Navbar/index.js` but I still don't understand why we have to define navigationOptions for each screen assuming 5 or 6 screens will have same header navigation elements, looking into figma screens I can see that most of screens they have `cancel` button on top right to abort the journey and back button on top left to go to previous screen. I am totally Ok to follow the convention but I just need to understand what we lose if we have create defaults navigation elements then keep it optional to override

2022-02-07 13:34 UTC, wachunei commented on app/components/Nav/Main/MainNavigator.js
> +				})}
We can define a reusable component in Navbar above our functions for now. This feedback is great and should definitely be considered when refactoring nav headers.

2022-02-07 13:46 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/GetStarted.js
> +			<StyledButton type={'confirm'} onPress={() => navigation.navigate('PaymentMethod')} style={styles.button}>
Fixed.

2022-02-07 13:54 UTC, alaahd commented on locales/languages/en.json
> +	},
fixed

2022-02-09 22:37 UTC, wachunei requested changes
A few new comments about the styling in the stories to avoid disabling rules

2022-02-09 22:37 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/components/ScreenRegion.tsx
> +		alignItems: 'center',
According to the design the header margin is smaller (16)

```suggestion
	header: {
		marginVertical: 16,
		alignItems: 'center',
```

2022-02-09 22:37 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/components/ScreenRegion.stories.js
> +							</ScreenRegion.Content>
in the style object another key for the content could be added to make it full width instead of styling the button (background just for reference)

<img width="400" alt="Screen Shot 2022-02-09 at 19 36 20" src="https://user-images.githubusercontent.com/1024246/153302075-f47db4ca-4e39-4be3-9616-3ad178f2db3c.png">

2022-02-10 13:13 UTC, wachunei requested changes
One small comment, everything else looks good to me. 
PS: remember to sign the CLA by commenting the sentence given by the bot in the comment above

2022-02-11 15:25 UTC, alaahd commented
I have read the CLA Document and I hereby sign the CLA

2022-02-11 15:45 UTC, merged