Show the contract receiving token allowances on the allowance screen
MetaMask/metamask-mobile pull request #3692
Opened 2022-02-04 16:23 UTC by blackdevelopa

**Description**

Contract address naming

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2022-02-15 16:12 UTC, sethkfman commented on app/components/UI/ApproveTransactionReview/index.js
> +						<Text>Contract: </Text>
Move this string to locals so it can be translated.

2022-02-15 16:12 UTC, sethkfman commented on app/components/UI/ApproveTransactionReview/index.js
> +						{this.props.nicknameExists ? 'Edit' : 'Add'} nickname
Move strings to locales for translation.

2022-02-15 16:22 UTC, sethkfman reviewed
Minor updates required to use locales

2022-02-15 20:11 UTC, cortisiko requested changes
**Issue 1**
I get this warning:  `ERROR  Warning: Failed prop type: Invalid prop protectWalletModalVisible of type function supplied to ApproveTransactionReview, expected boolean.`

[When I attempted to approve a token
](http://recordit.co/BOdVyp8Ujp)

to reproduce:
go [here](https://metamask.app.link/dapp/metamask.github.io/test-dapp/) while on a test net (because you do not want to use real funds)  
connect your wallet 
scroll down on the page and tap on create token
after your txn was confirmed tap on “approve token”
notice the confirmation modal appears with the error


**Issue 2**
after saving the contract address to my contacts I get: `Cannot update during an existing state transition (such as within render). Render methods should be a pure function of props and state`

 see [here](http://recordit.co/QF8tDB1kRv )

to reproduce:
go [here](https://metamask.app.link/dapp/metamask.github.io/test-dapp/) while on a test net (because you do not want to use real funds)  
connect your wallet 
scroll down on the page and tap on create token
after your txn was confirmed tap on “approve token”
notice the confirmation modal appears. Now tap on “Add nickname” 
input a nick name then hit save

notice the error appears 

**Issue 3**
On the edit nick name view I am unable to share my address. Tapping on the share icon does nothing.  On the other hand tapping on the address does not copy it to my clipboard. I need to carefully tap on the copy icon in order to copy. Even when i do copy my address i see a toast message “shell was pasted from your clipboard”. Maybe it should be “address was copied to your clipboard” ? 

see [here](http://recordit.co/VL5k3u4aBb )

**Issue 4**
[the contract i added to my contacts should not appear in recents
](http://recordit.co/gT5KQDeQN6 )
to reproduce:
go [here](https://metamask.app.link/dapp/metamask.github.io/test-dapp/) while on a test net (because you do not want to use real funds)  
connect your wallet 
scroll down on the page and tap on create token
after your txn was confirmed tap on “approve token”
notice the confirmation modal appears. Now tap on “Add nickname” 
input a nick name then hit save
return to the wallet view then go through the send flow
notice the contract address appears

2022-02-23 18:24 UTC, blackdevelopa commented
> **Issue 1** I get this warning: `ERROR Warning: Failed prop type: Invalid prop protectWalletModalVisible of type function supplied to ApproveTransactionReview, expected boolean.`
> 
> [When I attempted to approve a token ](http://recordit.co/BOdVyp8Ujp)
> 
> to reproduce: go [here](https://metamask.app.link/dapp/metamask.github.io/test-dapp/) while on a test net (because you do not want to use real funds) connect your wallet scroll down on the page and tap on create token after your txn was confirmed tap on “approve token” notice the confirmation modal appears with the error
> 

Thank you for catching this, QA issue 1 is now fixed.

> **Issue 2** after saving the contract address to my contacts I get: `Cannot update during an existing state transition (such as within render). Render methods should be a pure function of props and state`
> 
> see [here](http://recordit.co/QF8tDB1kRv)
> 
> to reproduce: go [here](https://metamask.app.link/dapp/metamask.github.io/test-dapp/) while on a test net (because you do not want to use real funds) connect your wallet scroll down on the page and tap on create token after your txn was confirmed tap on “approve token” notice the confirmation modal appears. Now tap on “Add nickname” input a nick name then hit save
> 
> notice the error appears
> 

Thank you for catching this, QA issue 2 is now fixed.

> **Issue 3** On the edit nick name view I am unable to share my address. Tapping on the share icon does nothing. On the other hand tapping on the address does not copy it to my clipboard. I need to carefully tap on the copy icon in order to copy. Even when i do copy my address i see a toast message “shell was pasted from your clipboard”. Maybe it should be “address was copied to your clipboard” ?
> 
> see [here](http://recordit.co/VL5k3u4aBb)
> 

Thank you for catching this, QA issue 3 is now fixed. We've got approval from Design on the `share` icon

> **Issue 4** [the contract i added to my contacts should not appear in recents ](http://recordit.co/gT5KQDeQN6) to reproduce: go [here](https://metamask.app.link/dapp/metamask.github.io/test-dapp/) while on a test net (because you do not want to use real funds) connect your wallet scroll down on the page and tap on create token after your txn was confirmed tap on “approve token” notice the confirmation modal appears. Now tap on “Add nickname” input a nick name then hit save return to the wallet view then go through the send flow notice the contract address appears

Thank you for catching this, QA issue 4 might take a little longer as it will require an update on the AddressController file to complete this.

2022-03-03 16:26 UTC, sethkfman commented on app/components/Views/ApproveView/Approve/index.js
> +		// backgroundColor: '#fff',
remove comment

2022-03-03 16:27 UTC, sethkfman commented on app/components/Views/ApproveView/Approve/index.js
> +		for (const [key, value] of Object.entries(addressBook)) {
consider breaking this out to a util function and testing it

2022-03-03 16:29 UTC, sethkfman commented on app/components/UI/ApproveTransactionReview/index.js
> +		setTimeout(() => this.props.protectWalletModalVisible(), 2000);
Can we avoid this setTimeout?

2022-03-04 22:05 UTC, cortisiko commented
@blackdevelopa sending this back your way:


**Issue 1**

I get this error: `[TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[3], "ethjs-util").stripHexPrefix(address).toLowerCase')]` when:

I go to https://uniswap.exchange/
Connect your wallet
Toggle from Swap to Charts.
Upon doing so I get that error 

See here: http://recordit.co/ZjZJ4L4h7M  
See main: http://recordit.co/flwnspWKMP 

**Maybe updating your branch would fix this?** 


**Issue 2**
I added a nick name to a contract then:

 went to the contacts view 
 tried editing the nickname.
 After saving my edit I am taken back to a blank contacts view. 

See here: http://recordit.co/QKAIXuRhLx 

**Issue 2B**

Similar to the above, If you were to:
add a nick name to a contract 
Go to the wallet view
Tap on send. Verify the contract address does not appear
Now go to the contacts view 
Notice the saved contract address is not visible. 

See here: http://recordit.co/MawUyJKiAh

2022-03-07 18:01 UTC, sethkfman reviewed
Architecture comments

2022-03-07 21:33 UTC, sethkfman approved these changes
LGTM

2022-03-08 18:45 UTC, owencraston commented on app/components/UI/ApproveTransactionReview/AddNickNameHeader/index.tsx
> +	const { onUpdateContractNickname, nicknameExists, headerWrapperStyle, headerTextStyle, iconStyle } = props;
NIT PICK (Not important): you could just destructure these values in the function declaration.
```
const Header = ({onUpdateContractNickname, nicknameExists, headerWrapperStyle, headerTextStyle, iconStyle}: HeaderProps) => {
```

2022-03-08 19:37 UTC, owencraston commented on app/components/UI/ApproveTransactionReview/ShowBlockExplorer/index.tsx
> +interface ShowBlockExplorerProps {
I can see that this is a very common pattern so we can discuss this with the team but I am really not a fan of putting the logic in the the index.ts/js. I reason for this is because when you are working with many files, all of the files that you open look the same, making it super difficult to navigate. 

I know the reason for this is so you can get default imports but what I prefer is to create the folder `ShowBlockExplorder` and the have the logic inside a file `ShowBlockExplorder.tsx` and add an `index.ts` file in the folder that consist of ...
```
// index.ts
import {ShowBlockExplorder} from './ShowBlockExplorder';

export default ShowBlockExplorder;
```

2022-03-08 19:39 UTC, owencraston commented on app/components/UI/ApproveTransactionReview/ShowBlockExplorer/index.tsx
> +export default ShowBlockExplorer;
This component can be wrapped in `React.memo(...)`
https://reactjs.org/docs/react-api.html#reactmemo

Pretty much every component should be wrapped in this unless its a component that lives very high in the tree (wraps a lot of views/components)

2022-03-08 19:47 UTC, owencraston commented on app/components/UI/ApproveTransactionReview/index.js
> +		marginVertical: 8,
Not that we need to do this now but we should definitely create  file that has our constant style baselines. Having each stylesheet inline the values leads to inconsistency and becomes super hard to change if the designers decide we need to overall all of the spacing.

what I envision is ...
a file called `StyleConstants.ts` (or something like that)
```
// StyleConstants.ts`
const baseMarginVertical = 4;
```

and then in your stylesheet you can do ...
`marginVertical: 2*baseMarginVertical,`
another option would be to turn the style units into a function so we can have something like this
```
const baseMarginVertical = 4;
const spaces = (multiplier: number) => baseMarginVertical *  multiplier;
```
and then in the styles we would do...
`marginVertical: spaces(2)`

2022-03-08 19:48 UTC, owencraston commented on app/components/UI/ApproveTransactionReview/index.js
> +		borderRadius: 40,
as you can see keeping track of all these raw numbers can get super tedious and could lead to inconsistent styles. Not to mention it adds an extra burden on the developer to know what the standard values for certain properties are, if these were all constants/functions, we would all just rely on them and the burden would be lifted.

2022-03-08 19:52 UTC, owencraston commented on app/components/UI/ApproveTransactionReview/index.js
> +		marginVertical: 8,
I talked to @Cal-L and he said something like this is in the words on the redesign team.

2022-03-08 20:01 UTC, owencraston commented on app/components/Views/ApproveView/Approve/index.js
> +		network: PropTypes.string,
I'm unfamiliar with this library. why not just use typescript primitive types?

2022-03-09 22:03 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/AddNickname/index.tsx
> +const styles = StyleSheet.create({
I also agree with you on this, but at this time the team's practice is to have the styles where it is - at the top. We can always review this for future updates.

2022-03-09 22:05 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/index.js
> +		marginVertical: 8,
I actually like this idea and I am all for it. We can sync with the rest of the team and adopt this approach.

2022-03-09 22:07 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/index.js
> +		borderRadius: 40,
On the same page with you on this. We should definitely sync up on this.

2022-03-10 18:02 UTC, cortisiko approved these changes
🌮 🌮 🌮

2022-03-14 15:41 UTC, merged