Fix formatting of gas price for all conversion currencies
MetaMask/metamask-mobile pull request #3731
Opened 2022-02-10 17:16 UTC by Fatxx

**Description**

Fix formatting of gas price for all types of conversion currencies. 
Removed unnecessary external library for currency formatting since it is now natively supported by ECMAScript Internationalization API.

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #3498

2022-02-11 09:46 UTC, andreahaku approved these changes
LGTM

2022-02-15 23:08 UTC, cortisiko requested changes
[Android specific] If i were to go:

change my fiat currency from USD to BNT
go to uniswap 
attempt to swap, the app crashes: http://recordit.co/knzyiMM8nw 

I see this in the logs: 

```
 ERROR  ReferenceError: Can't find variable: Intl

This error is located at:
    in TransactionReviewInformation (created by Connect(TransactionReviewInformation))
    in Connect(TransactionReviewInformation) (at TransactionReview/index.js:376)
    in RCTView (at View.js:32)
    in View (at TransactionReview/index.js:372)
    in TouchableWithoutFeedback (at ActionView/index.js:54)
    in RCTView (at View.js:32)
    in View (at ScrollView.js:1674)
    in RCTScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at KeyboardAwareHOC.js:537)
    in KeyboardAwareScrollView (at ActionView/index.js:49)
    in RCTView (at View.js:32)
    in View (at ActionView/index.js:48)
    in ActionView (at TransactionReview/index.js:364)
    in RCTView (at View.js:32)
    in View (at TransactionReview/index.js:363)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at TransactionReview/index.js:353)
    in TransactionReview (created by Connect(TransactionReview))
    in Connect(TransactionReview) (at TransactionEditor/index.js:809)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at AnimatedTransactionModal/index.js:225)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at AnimatedTransactionModal/index.js:216)
    in AnimatedTransactionModal (at TransactionEditor/index.js:808)
    in RCTView (at View.js:32)
    in View (at ScrollView.js:1674)
    in RCTScrollView (at ScrollView.js:1792)
    in ScrollView (at ScrollView.js:1818)
    in ScrollView (at KeyboardAwareHOC.js:537)
    in KeyboardAwareScrollView (at TransactionEditor/index.js:807)
    in TransactionEditor (created by Connect(TransactionEditor))
    in Connect(TransactionEditor) (at Approval/index.js:361)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at createAnimatableComponent.js:599)
    in withAnimatable(View) (created by ReactNativeModal)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at Modal.js:242)
    in RCTView (at View.js:32)
    in View (at Modal.js:270)
    in VirtualizedListContextResetter (at Modal.js:268)
    in RCTModalHostView (at Modal.js:248)
    in Modal (created by ReactNativeModal)
    in ReactNativeModal (at Approval/index.js:347)
    in Approval (created by Connect(Approval))
    in Connect(Approval) (at Main/index.js:547)
    in Main (created by Connect(Main))
    in Connect(Main) (at SceneView.tsx:122)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:32)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:32)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:32)
    in View (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:573)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at Card.tsx:544)
    in RCTView (at View.js:32)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RNSScreen (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at src/index.native.tsx:147)
    in Screen (at Screens.tsx:74)
    in MaybeScreen (at CardStack.tsx:616)
    in RNSScreenContainer (at src/index.native.tsx:186)
    in ScreenContainer (at Screens.tsx:50)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:32)
    in View (at GestureHandlerRootView.android.tsx:21)
    in GestureHandlerRootView (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at Main/index.js:809)
    in MainFlow (at SceneView.tsx:122)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:32)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:32)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:32)
    in View (at CardSheet.tsx:33)
    in CardSheet (at Card.tsx:573)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:32)
    in View (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at Card.tsx:544)
    in RCTView (at View.js:32)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:623)
    in RNSScreen (at createAnimatedComponent.js:242)
    in AnimatedComponent (at createAnimatedComponent.js:295)
    in AnimatedComponentWrapper (at src/index.native.tsx:147)
    in Screen (at Screens.tsx:74)
    in MaybeScreen (at CardStack.tsx:616)
    in RNSScreenContainer (at src/index.native.tsx:186)
    in ScreenContainer (at Screens.tsx:50)
    in MaybeScreenContainer (at CardStack.tsx:498)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:76)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in GestureHandlerRootView (at GestureHandlerRootView.android.tsx:26)
    in GestureHandlerRootView (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at App/index.js:277)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in BaseNavigationContainer (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in NavigationContainer (at App/index.js:266)
    in RCTView (at View.js:32)
    in View (at App/index.js:265)
    in App (created by Connect(App))
    in Connect(App) (at Root/index.js:44)
    in ErrorBoundary (at Root/index.js:43)
    in PersistGate (at Root/index.js:42)
    in Provider (at Root/index.js:41)
    in Root (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in MetaMask(RootComponent) (at renderApplication.js:60)
```

2022-02-16 12:10 UTC, andreahaku commented on app/util/confirm-tx.js
> +	const formatedCurrency = new Intl.NumberFormat(I18n.locale, {
to support `Intl` on Android you should modify `build.gradle` like that:
``` /**
   * Use the international variant of JavaScriptCore
   * This variant includes the ICU i18n library to make APIs like `Date.toLocaleString`
   * and `String.localeCompare` work when using with locales other than en-US.
   * Note that this variant is about 6MiB larger per architecture than the default.
   */
-  def useIntlJsc = false
+  def useIntlJsc = true
```

2022-02-16 17:37 UTC, Fatxx commented on app/util/confirm-tx.js
> +	const formatedCurrency = new Intl.NumberFormat(I18n.locale, {
Thanks @andreahaku

2022-02-21 17:22 UTC, Fatxx commented
@cortisiko just fixed you can QA again if you like

2022-03-23 20:54 UTC, cortisiko approved these changes
🌮 🌮 🌮 🌮

2022-03-25 17:06 UTC, merged