Added payment options for On-Ramp
MetaMask/metamask-mobile pull request #3732
Opened 2022-02-10 17:30 UTC by VikChawla

Added Payment option screens.

Checkout the PaymentOptions.stories.js to see component examples and change nobs to see different prop options.

2022-02-10 17:35 UTC, VikChawla commented
I have read the CLA Document and I hereby sign the CLA

2022-02-11 10:39 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/components/PaymentOption.tsx
> +						<FontAwesome name="square" size={50} color="#F0F0F2" />
you can use color variables instead of hex colors.

2022-02-11 10:40 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/components/PaymentOption.tsx
> +	if (paymentIcon === 'apple') {
It is more contextual to say `paymentType` instead of `paymentIcon`

2022-02-11 10:42 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/components/PaymentOption.tsx
> +const Text = CustomText as any;
Add the comment `// TODO: Convert into typescript and correctly type optionals
`

2022-02-11 10:43 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/components/PaymentOption.tsx
> +								<>
remove react fragment, it is not needed when you return a single node.

2022-02-11 10:50 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/components/PaymentOption.tsx
> +	cardImage,
instead of having `cardImage` as boolean prop and to avoid static binding of card types, we can pass an array of supported networks, so for Apple pay paymentOption we can pass `networks=['visa', 'mastercard'] so this would make the rendering fully dynamic.

2022-02-16 13:44 UTC, wachunei requested changes
There are some additional styles that even though it makes it match the design, we should remove and stick to the components we already have.

2022-02-16 13:44 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/components/PaymentOption.stories.js
> +/* eslint-disable react-native/no-color-literals */
This should be removed

2022-02-16 13:44 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/components/PaymentOption.tsx
> +		backgroundColor: '#F0F0F2',
Would you add a TODO comment mentioning we need to remove this hard coded color later? I think there's a similar one in our Keypad component.

2022-02-16 13:44 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/components/PaymentOption.tsx
> +		color: colors.black,
use `<Text big primary bold>` instead and remove this style.

2022-02-16 13:44 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/components/PaymentOption.tsx
> +	},
use `<Text small grey>` and remove this style

2022-02-16 14:17 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/components/PaymentOption.tsx
> +
Remove top eslint disable and disable the block only where it is used.

```suggestion
/* eslint-disable import/no-commonjs, @typescript-eslint/no-var-requires, @typescript-eslint/no-require-imports */
const visa = require('./images/visa.png');
const sepa = require('./images/sepa.png');
const mastercard = require('./images/mastercard.png');
/* eslint-enable import/no-commonjs, @typescript-eslint/no-var-requires, @typescript-eslint/no-require-imports */

```

2022-02-16 16:36 UTC, merged