Transaction reseted and NFT deleted only when transaction confirmed
MetaMask/metamask-mobile pull request #3753
Opened 2022-02-15 13:06 UTC by tommasini

**Description**

Now the collectible it's removed only when the transaction it's confirmed! 

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**https://github.com/MetaMask/metamask-mobile/issues/2784#issuecomment-1038345711**

Solves #2784

2022-02-15 13:07 UTC, tommasini commented
The NFT is deleted after the transaction is confirmed.

It's needed to change the UI.
I propose that the NFT that was transacted stays disabled in the Wallet view, for the user can't send it again while the transaction is happening.

2022-02-15 22:53 UTC, gantunesr commented
@tommasini Another scenario to consider is if an user tries to send again the same NFT to a different address with a higher gas fee to overwrite the first transaction. Do you this case is worth taking in consideration?

2022-02-15 22:54 UTC, gantunesr requested changes
LGTM But the linter is failing

```
/home/runner/work/metamask-mobile/metamask-mobile/app/components/UI/Transactions/index.test.tsx
Warning:   4:26  warning  Parse errors in imported module '.': ')' expected. ([17](https://github.com/MetaMask/metamask-mobile/runs/5208332772?check_suite_focus=true#step:9:17)0:24)  import/no-named-as-default-member

/home/runner/work/metamask-mobile/metamask-mobile/app/components/Views/SendFlow/Confirm/index.js
Error:   743:10  error    Replace `⏎↹↹↹chainId,⏎↹↹` with `·chainId·`  prettier/prettier
Error:   850:60  error    Delete `⏎↹↹↹↹`                              prettier/prettier
Warning:   851:1   warning  Trailing spaces not allowed                 no-trailing-spaces
```

2022-02-16 18:44 UTC, tommasini commented
> Another scenario to consider is if an user tries to send again the same NFT to a different address with a higher gas fee to overwrite the first transaction. Do you think this case is worth taking in consideration?

I think if the transaction is being overwritten that's not a problem because the user will have the information of a bigger gas fee in the confirmation screen.

2022-02-16 19:39 UTC, gantunesr commented
@tommasini I was referring to this comment

> It's needed to change the UI.
> I propose that the NFT that was transacted stays disabled in the Wallet view, for the user can't send it again while the transaction is happening.

Because the user might want to send the NFT again using the same nonce and a higher gas fee

2022-02-16 20:13 UTC, tommasini commented
> @tommasini I was referring to this comment
> 
> > It's needed to change the UI.
> > I propose that the NFT that was transacted stays disabled in the Wallet view, for the user can't send it again while the transaction is happening.
> 
> Because the user might want to send the NFT again using the same nonce and a higher gas fee

Yes, you are right, We can't disable it because the user might want to overwrite the transaction. When I purpose that I was thinking that the user could not overwrite it.
The only thing that I noticed and I can purpose for the UI It's that could exist in the NFT one label saying the NFT is being transacted (Since one transaction can take some time, like more than 10 minutes). What do you think?

2022-02-17 01:25 UTC, gantunesr commented
That's an interesting proposition, we can get some feedback from our designers

2022-02-17 15:42 UTC, tommasini commented
> That's an interesting proposition, we can get some feedback from our designers

Thank you! I'm glad to hear that!

2022-04-01 12:30 UTC, tommasini commented
This PR will only works when we have the controllers updated with this [PR](https://github.com/MetaMask/controllers/pull/762)

I will leave here a small demo of the expected behavior of these changes in the UI, please let me know what could be improved here

https://user-images.githubusercontent.com/46944231/161263555-cf9d4865-5759-4165-afe9-c42354137c22.mp4

2022-04-06 15:18 UTC, tommasini commented on app/components/UI/CollectibleModal/index.js
> +						isTransacting={collectibleUpdated ? !!collectibleUpdated.transactionId : false}
!!collectibleUpdated?.transactionId

2022-04-12 05:37 UTC, chrisleewilcox commented
Not able to git pull/checkout branch.....

![image](https://user-images.githubusercontent.com/6626407/162888343-195c17dc-93c2-494d-b987-d9c7499d5a49.png)

2022-04-12 15:41 UTC, tommasini commented
Closing this PR and creating a new one from the metamask remote repo, check [here](https://github.com/MetaMask/metamask-mobile/pull/4091)

2022-04-12 15:41 UTC, closed without merging