[IMPROVEMENT] Authentication Refactor
MetaMask/metamask-mobile pull request #3755
Opened 2022-02-15 16:05 UTC by sethkfman

**Description**

The goal of this refactor was to be able to remove logic from our UI components that handle authentication(login, logout, update password, update biometric) and centralize them in a single service. 

This work is preparation to make it easier for additional refactors and improvements. There is still more opportunity to refactor vault creation but that will be completed in future work. 

**Checklist**

* [ ] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #???

2022-02-22 22:35 UTC, sethkfman commented on app/components/Nav/App/index.js
> +				if (existingUser && !userLoggedIn && !locked.current && selectedAddress) {
Like allowing the user to retry?

2022-02-22 22:36 UTC, sethkfman commented on app/components/Nav/App/index.js
> +				console.log('APP AUTH', existingUser, !userLoggedIn, !locked.current);
I will go through the PR and remove all console logs

2022-02-22 23:16 UTC, sethkfman commented on app/components/Nav/App/index.js
> +	});
That state dependency was added as a temporary patch. I reverted all of the temporary patches

2022-02-25 22:20 UTC, sethkfman commented on app/components/Views/Settings/SecuritySettings/index.js
> +				credentials = await AuthenticationService.getPassword();
Good call. Updated and converted strings to constants

2022-02-25 22:27 UTC, sethkfman commented on app/core/AuthenticationService.ts
> +		if (encryptionLib !== ORIGINAL && existingUser) {
Good catch, I added a throw error that is caught in the public methods for this class.

2022-03-08 18:21 UTC, sethkfman commented on app/components/Nav/App/index.js
> +				if (existingUser && !userLoggedIn && !locked.current && selectedAddress) {
When this fails the setAuthCancelled state will trigger the loading screen. Could you elaborate on what you are thinking about the action?

2022-03-10 18:13 UTC, owencraston commented on app/__mocks__/@react-native-community/async-storage.js
> +export default from '@react-native-community/async-storage/jest/async-storage-mock';
👏

2022-03-10 18:24 UTC, owencraston commented on app/components/Nav/App/index.js
> +			animationName?.current?.play();
why do we need both of these?

2022-03-10 18:37 UTC, owencraston commented on app/components/Views/ChoosePassword/index.js
>  const styles = StyleSheet.create({
Nit Pick: I think its cleaner for the styles to be left at the bottom of the file. That way when you open the file you can quickly see the logic. This is especially helpful when the style are very large like this.

2022-03-10 19:00 UTC, owencraston commented on app/core/AuthenticationService.ts
> +class AuthenticationService {
Nitpick but I feel that the term `Service` isn't really applicable here as it doesn't run any long standing operations. A dev coming from a more traditional background might infer this as a classic [android service](https://developer.android.com/guide/components/services) which will run in the background. Not important though so not a blocker. I think just `Authentication` would suffice.

2022-03-10 19:16 UTC, owencraston commented on app/core/AuthenticationService.ts
> +export enum AuthenticationType {
I also might suggest making this file `typescript` since it will only be harder to convert it later when everyone is using it.

2022-03-10 19:16 UTC, owencraston commented on app/core/AuthenticationService.ts
> +	_newWalletVaultAndRestore = async (password: string, parsedSeed: string, clearEngine: boolean) => {
if this class was `TS` we could have [real private methods/values](https://www.typescriptlang.org/docs/handbook/2/classes.html#private)

2022-03-10 19:17 UTC, owencraston commented on app/core/AuthenticationService.ts
> +	_newWalletVaultAndRestore = async (password: string, parsedSeed: string, clearEngine: boolean) => {
I think in typescript you can make these methods [private](https://www.typescriptlang.org/docs/handbook/2/classes.html#private)

I assume thats what you are going for here with the `_`

2022-03-10 19:18 UTC, owencraston commented on app/core/AuthenticationService.ts
> +		const { KeyringController }: any = Engine.context;
is this `any` because the engine is pure `js`? If not then I think we should avoid any at all cost.

2022-03-10 19:22 UTC, owencraston commented on app/core/AuthenticationService.ts
> +let instance: AuthenticationService;
why is this let?

2022-03-10 19:23 UTC, owencraston commented on app/core/AuthenticationService.ts
> +	store: any;
why is this any?

2022-03-10 19:27 UTC, owencraston commented on app/core/AuthenticationService.ts
> +		this.store?.dispatch(logOut());
if we instead allowed the consumer of this class to pass in a dispatch (or something like an `onAction` callback) then we would not need to null check the properties on the store. Since the store is typed any we lose a lot of type safety but the dispatch should be easier to pass in as a type since its just a callback function. Another pro of this is that we are not married to redux state management if we decide to use something else in the future.

2022-03-10 19:33 UTC, owencraston commented on app/core/AuthenticationService.ts
> +	componentAuthenticationType = async (biometryChoice: boolean, rememberMe: boolean) => {
what is this returning?

2022-03-10 19:35 UTC, owencraston commented on app/core/AuthenticationService.ts
> +	store: any;
also how do these properties get set without a constructor?

2022-03-10 19:39 UTC, owencraston commented on app/core/AuthenticationService.ts
> +		} catch (e: any) {
It would be super bonus if we could have a custom AuthError. I think it would make catching bugs or crashes easier. It would be especially useful for something this crucial. Thinking something like [this](https://ashsmith.io/handling-custom-error-classes-in-typescript)

2022-03-10 19:41 UTC, owencraston commented on app/core/AuthenticationService.ts
> +			instance.store = store;
I see, you are manually accessing the property (since its public) and setting this. I if you enforce this property being part of the arguments to the constructor we will get cleaner code and less chance of misusing the property access.

2022-03-10 19:48 UTC, owencraston commented on app/core/AuthenticationService.ts
> +	userEntryAuth: async (password: string, authType: AuthData, selectedAddress: string) =>
why do we have so much extra logic in the singleton? Ideally the class would have all of this logic in the "original" class and this singleton simple handle the instantiating.

2022-03-10 19:49 UTC, owencraston commented on package.json
> +    "react-native": "0.66.4",
are we sure this upgrade will have no issues? what is the need for it? I am also very pro regular updates I am just wondering if you needed some key functionality.

2022-03-11 07:11 UTC, blackdevelopa commented on app/components/Nav/App/index.js
> +				if (existingUser && !userLoggedIn && !locked.current && selectedAddress) {
Okay. Got it now. Thank you.

2022-03-22 15:40 UTC, sethkfman commented on package.json
> +    "react-native": "0.66.4",
I had upgraded it to resolve some `yarn audit` issues

2022-03-22 19:25 UTC, rickycodes commented on app/components/Views/ImportFromSeed/index.js
> +			});
instead of using `authType.type` why not destructure here?
```suggestion
		const { type } = await Authentication.getType();
		const previouslyDisabled = await AsyncStorage.getItem(BIOMETRY_CHOICE_DISABLED);
		const passcodePreviouslyDisabled = await AsyncStorage.getItem(PASSCODE_DISABLED);
		if (type === AUTHENTICATION_TYPE.BIOMETRIC)
			this.setState({
				biometryType: type,
				biometryChoice: !(previouslyDisabled && previouslyDisabled === TRUE),
			});
		else if (type === AUTHENTICATION_TYPE.PASSCODE)
			this.setState({
				biometryType: Device.isIos() ? type + '_ios' : type + '_android',
				biometryChoice: !(passcodePreviouslyDisabled && passcodePreviouslyDisabled === TRUE),
			});
```

2022-03-23 14:29 UTC, owencraston commented on app/core/Authentication/Authentication.ts
> +	checkAuthenticationMethod = async (credentials: any) => {
is there a better way we could represent this data? What type of credentials are we expecting?

2022-03-23 14:30 UTC, owencraston commented on app/core/Authentication/Authentication.ts
> +		const { KeyringController }: any = Engine.context;
I am trying to think of a way we can store this as a property on the class so we do not need to keep accessing it directly.

2022-03-23 14:56 UTC, sethkfman commented on app/core/Authentication/Authentication.ts
> +		const { KeyringController }: any = Engine.context;
If you are referring to the `KeyringController` the challenge is that this state continues to update and we need the current state before interacting with it. We may be able to update the AuthService property by adding a middleware  in the Engine redux store.

2022-03-23 20:58 UTC, owencraston approved these changes
I did some user testing with the basic log in and wallet creation as well as testing putting the app in the background and it all worked for me. The code also looks good to me but I was a contributor so we should probably get another review.

2022-03-23 21:05 UTC, sethkfman commented
@owencraston and myself paired and dev tested on this PR. We are feeling pretty good about the update but need review from other devs. Thx

2022-04-25 02:52 UTC, gantunesr reviewed
Just finished reviewing the refactor, left some minor observations and questions.

I also have the following point to discuss,
- We could standardize the Authentication related log and error messages so its easier to filter in Sentry

Let me know if you want to sync about the review.

2022-04-25 02:52 UTC, gantunesr commented on app/core/Authentication/Authentication.ts
> +	 */
Nit: Add proper comments

2022-05-02 17:53 UTC, sethkfman commented on app/components/Views/Login/index.js
> +	selectedAddress: state.engine.backgroundState?.PreferencesController?.selectedAddress,
I don't know if it makes sense to add this check on the `Root/index.js`. WDYT?

2022-05-10 02:19 UTC, cortisiko requested changes
@sethkfman sending this back your way

**Issue 1**

When i kill the app and relaunch it i get these warnings:

 `[TypeError: (0, _auth.default) is not a function. (In '(0, _auth.default)(type)', '(0, _auth.default)' is undefined)] ` & 

`[Error: KeyringController - password is not a string]
`
to reproduce:
create your wallet with “unlock with biometrics” on
kill the app
relaunch the app
notice the errors

see recording: http://recordit.co/BrKdPb957L 

**Issue 1B**
With “unlock with biometrics” enabled if I were to:

 create a new wallet 
 kill the app and relaunch it 
I have to authenticate two times before unlocking the app. Meaning I unlock the app with my biometrics then I am taken to the log in view where I need to use my biometrics to unlock the app again
See recording here: http://recordit.co/SXOEJ5gxVA 

Furthermore, if i were to kill the app one more time then relaunch it. After i log in with biometrics the wallet view has an endless spinner: http://recordit.co/XywSMuaKQf 

**Issue 2**
I am unable to toggle on “unlock with biometrics” on the privacy and security view

to reproduce:
create your wallet with “unlock with biometrics” toggled off
go to the settings view then privacy and security 
toggle “unlock with biometrics” on
notice the view refreshes but  “unlock with biometrics” is still toggled off

Good news is if i were to kill the app and relaunch it i am prompted to unlock my device with biometrics. 
see recording here: http://recordit.co/MZegGgBilT 

**Issue 3**
I am unable to change my password. When i try changing my password i am taken back to the onboarding flow. 

to reproduce:
create a new wallet or import wallet
go  to the settings view then privacy and security 
tap change password
change your password
notice you are taken back to the onboarding view. 

see here: http://recordit.co/EkiUQ6UxAD 

**Issue 4** 

I get `Error:Error:error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT` when I:
create/import a wallet with “remember me” toggled off
kill the app
relaunch it
log in with an incorrect password. 
notice the error. 

see recording here: http://recordit.co/6cUGb90zjE  

**Issue 5**
If i were to:
import/create my wallet with “unlock with biometrics” toggle on
kill the app
wait until the biometrics authentication times out (wait until the log in view appears)
Do not try to authenticate with biometrics 
enter in an invalid password
ensure you get an error message letting you know your password was incorrect
now tap on the biometrics button in the password input box
authenticate with biometrics. 
notice the log in view appears a second time.

furthermore I see this error: [TypeError: null is not an object (evaluating 'input.blur')]  
see here: http://recordit.co/4afTxPa37v  


Quicker way you can reproduce by:
creating your wallet with remember me/ unlock with biometrics toggled off
kill the app
relaunch it
enter an invalid password
enter the correct password
notice the log in view appears a second time.

**Issue 6**
As a user who creates a new wallet when I create a new account, the first account name appears twice
see here: http://recordit.co/fNvRKSvSUZ 

to reproduce:
creating your wallet with remember me/ unlock with biometrics toggled off 
open the account lists
tap on “create account” 
notice that account 1 is duplicated. 

**Issue 6B**
When I import my wallet then try to create an account  I appear to be going through biometrics authentication  

see here: http://recordit.co/6NvU85xWNa (where-ever you see the blank screen that is when I need to verify my biometrics) 

To reproduce:
import your wallet with “unlock with biometrics” on
open the account lists
tap on “create account” 
notice you are asked to use your biometrics.

2022-05-10 02:19 UTC, cortisiko commented
I am 35% done with testing.

2022-05-10 20:21 UTC, sethkfman commented on app/components/Views/Login/index.js
> +	selectedAddress: state.engine.backgroundState?.PreferencesController?.selectedAddress,
Removed optionals in login. Required before navigation to login occurs.

2022-05-10 20:26 UTC, sethkfman commented on app/components/Views/Settings/SecuritySettings/index.js
>  	TRUE,
These strings are different values

2022-05-10 20:50 UTC, gantunesr approved these changes
LGTM

2022-05-11 00:09 UTC, cortisiko commented
**Issue 8**

When i tried importing an account I am prompted to log in with faceID biometrics. It seems as if faceID biometrics is stuck in a loop for a brief moment then i am taken back to the onboarding view:

To reproduce:
import your wallet with “unlock with biometrics” on
open the account lists
tap on “import account”
enter your private key
notice after you import the account, you are asked to use your biometrics again and again until you are finally kicked back to the onboarding view.


I also see this error `undefined is not an object (evaluating address.toLowerCase)`
see here: http://recordit.co/1cgeuKBpVn
  
**Issue 9**
While going through the backup SRP flow I am prompted to enter my password and when i do enter my password I get an error `Couldn’t unlock your account. Please try again”`

to reproduce:
creating your wallet with remember me/ unlock with biometrics toggled on
land on the wallet view then kill the app
relaunch the app
now while on the wallet view, tap on the text “Protect wallet” in the back up alert
notice you are taken to step 1 of the backup SRP page. 
proceed to step 2 “Secure wallet”. 
Here you would be asked to enter your password.  If your device has biometrics enabled deny it. That way you can enter your password to proceed. 
enter your password. 
Notice the error `Couldn’t unlock your account. Please try again`
see here: http://recordit.co/p8f1UpzA0A 

**Issue 10**
This one is sometimes-ish meaning it is not a consistent bug to reproduce. When I attempt to deep link to polygon send flow i get:  `[TypeError: undefined is not an object (evaluating 'identities[selectedAddress].name')]`

to reproduce:
add polygon to your list of networks
kill the app
tap on https://metamask.app.link/send/0x0000000000000000000000000000000000001010@137/transfer?address=0xC5b2b5ae370876c0122910F92a13bef85A133E56&uint256=3e18

the error should appear. 


**Update on Issue 1B**

I am still have to authenticate two times before unlocking the app.
 see here http://recordit.co/grrcMhTtaJ 

**Update on Issue 2:**
I am unable to disabled biometrics. The app logs me out, tries to authenticate using FaceID then prompts me with an error alert “invalid password” 

see here: http://recordit.co/x6S1FYX1Nl

2022-05-11 00:10 UTC, cortisiko commented
I am 75% done with testing

2022-05-12 16:02 UTC, owencraston commented on app/components/Nav/App/index.js
> +      const existingUser = await AsyncStorage.getItem(EXISTING_USER);
thoughts on moving this into the Authentication class?

2022-05-13 15:51 UTC, owencraston commented on .iyarc
> +GHSA-gff7-g5r8-mg8m
?

2022-05-13 15:56 UTC, owencraston commented on app/core/Authentication/Authentication.ts
> +  checkAuthenticationMethod = async (): Promise<AuthData> => {
If this is truly only for previous logins,we should probably centralize that logic around verifying there was a previous login inside this class.

2022-05-13 23:14 UTC, sethkfman commented
@cortisiko I made progress on most of the items but still have to reply to @owencraston feedback. I think this will need to wait until May 24th. Unless @owencraston ends up with some free time.
- Outstanding issues:
  -  Issue 2 
- New issue 11: If you lock the wallet (biometrics enabled), kill the app, then start the app, in the login view the biometric button on the password window appears but doesn't work (it should be hidden)

2022-05-18 17:15 UTC, owencraston commented on app/util/testSetup.js
> +  BIOMETRY_TYPE: {
Once [this PR merges](https://github.com/MetaMask/metamask-mobile/pull/4305) we will need to remove this

2022-05-20 23:06 UTC, cortisiko commented
Hey @sethkfman I tested the fixes on your latest commit. Most of the issues are fixed.

 Issue 9 is fixed but we have a cosmetic issue. The color of the masked password differs from that of prod. On [your PR ](http://recordit.co/1XvSf7OZIt ) the color is black while in [prod](http://recordit.co/ljPDPninVE) it is white. 

I do have another issue to report. Call this one **Issue 12**.

**Issue 12**

As a new user when I declined to authenticate using FaceID ([here](https://www.screencast.com/t/BPX8Tk41Bogs ) visual representation of what I mean)  I get into a broken state. Meaning I am stuck on the _Create your wallet_ view. 


To reproduce:
Create a new wallet
You should be prompted with an alert message asking you to Allow or disallow Face ID ([this](https://www.screencast.com/t/BPX8Tk41Bogs) is what I mean.) 
Tap on “don’t allow”
Notice you are in a broken state. 

See [here](http://recordit.co/19LhwkAk2t )

I will be OOO until June 3rd. If you are not too swamped @plasmacorral can you keep things rolling on this? Thanks!

2022-08-02 17:19 UTC, owencraston commented on app/core/Authentication/Authentication.ts
> +    } else if (await SecureKeychain.getGenericPassword()) {
should we validate this password works before we return here?

2022-12-09 20:54 UTC, owencraston commented on app/core/Authentication/Authentication.ts
> +  private loginVaultCreation = async (
Look into # as an alternative to private

2023-01-30 13:58 UTC, sethkfman commented
Close PR due to inactivity

2023-01-30 13:58 UTC, closed without merging