Prioritise specified transaction gas to further fix gasless network transactions
MetaMask/metamask-mobile pull request #3756
Opened 2022-02-15 17:43 UTC by Fatxx

**Description**

On extension the gas fee specified in the transaction is prioritise over the average gas price. This PR implements also that logic in order to enable gasless transactions.

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #3305

2022-02-16 12:03 UTC, andreahaku commented on app/components/UI/TransactionEditor/index.js
> +		const totalGasValue = gasPrice ? hexToBN(gasPrice) : hexToBN(totalGas);
what about:
`const totalGasValue = hexToBN(gasPrice || totalGas);`

2022-02-16 17:23 UTC, andreahaku approved these changes

2022-02-24 19:12 UTC, andrepimenta requested changes

2022-02-24 19:12 UTC, andrepimenta commented on app/components/UI/TransactionEditor/index.js
> +		const totalGasValue = hexToBN(gasPrice || totalGas);
The gasPrice should not be get prioritized when compared to totalGas. totalGas comes from our API that is much better at predicting prices than what comes from gasPrice. But, for custom networks where our API does not work, we should already be using the gasPrice. So this shouldn't be necessary, there is a bug somewhere on our gas controller probably.

2022-02-25 14:53 UTC, andrepimenta approved these changes
LGTM!

2022-03-10 21:01 UTC, cortisiko approved these changes
I synced with @gantunesr  and @Fatxx  on this. We are 🌮

2022-03-10 21:22 UTC, merged