[FIX] "Speed up" and "Cancel" buttons showing up the receiver side
MetaMask/metamask-mobile pull request #3790
Opened 2022-02-21 19:07 UTC by gantunesr

**Description**

The speed up and cancel CTA’s appear on the receiver (the person who received the funds) end.

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #3222

2022-02-23 11:24 UTC, andreahaku approved these changes
LGTM

2022-02-23 11:24 UTC, andreahaku commented on app/util/activity/index.ts
> +			return !!tokens.find(({ address }) => toLowerCaseEquals(address, transferInformation.contractAddress));
I'd prefer a ternary here. Something like:
`return isTransfer ? !!tokens.find(({ address }) => toLowerCaseEquals(address, transferInformation.contractAddress)) : true;`

2022-02-25 00:36 UTC, plasmacorral requested changes
Still seeing the issue present in android 11, testing with Moto G play (2021) running December 2021 security updates.

I am able to see the pending transaction from the receiving address side in transaction history.

Device logs:
[bugreport-guamna_t-RZAS31.Q2-146-14-5-2022-02-24-17-58-15.zip](https://github.com/MetaMask/metamask-mobile/files/8137469/bugreport-guamna_t-RZAS31.Q2-146-14-5-2022-02-24-17-58-15.zip)

State Logs:
[PR3790_MetaMask State logs -  v4.1-3.0 (816).zip](https://github.com/MetaMask/metamask-mobile/files/8137474/PR3790_MetaMask.State.logs.-.v4.1-3.0.816.zip)

2022-02-25 02:24 UTC, plasmacorral commented
To Reproduce

    1. Go through the send flow to send some eth to one of your accounts (on rinkeby)
    2. Before submitting your txn tap the estimated gas fee
    3. Tap Advanced options.  
    4. Take a few gwei off Max Priority Fee until red network conditions warnings pop 
    5. Do the same with Max Fee, until red network conditions warnings pop
    6. Tap save
    7. Tap Send to submit txn
    8. Tap Back to wallet view
    9. Change to receiving address 
    10. Tap asset (Eth) to see transactions
    11. Note that incoming transaction shows as "Submitted" with speed up and cancel buttons on receiving side in advance of being accepted on chain.

Expected behavior
The receiver transaction overview should not contain any transaction that requires him/her to speed up the transaction.

2022-02-25 14:59 UTC, gantunesr commented on app/util/activity/index.ts
> +			return !!tokens.find(({ address }) => toLowerCaseEquals(address, transferInformation.contractAddress));
Done in [a8d4751](https://github.com/MetaMask/metamask-mobile/pull/3790/commits/a8d475160d80deaf77750438e7673248efc47b9d)

2022-02-27 15:51 UTC, gantunesr commented
Fixed in [b924dcc](https://github.com/MetaMask/metamask-mobile/pull/3790/commits/b924dccdfb847f44e3326601260b193657e05e40) and [ccf6d5f](https://github.com/MetaMask/metamask-mobile/pull/3790/commits/ccf6d5fc8010d37679ae622d66a9c75efe6a5e8a)

cc @plasmacorral

2022-03-09 01:05 UTC, cortisiko requested changes
@gantunesr sending this back your way:  The sender’s pending transaction does not appear in the activity view but appears on asset overview. Meaning Once I send a transaction between my wallet address with a low gas fee, the pending transaction does not appear in the activity view (formerly transaction history). 
 See recording [here](http://recordit.co/ChwunZ5nRS) 

_**The transaction appeared after it was confirmed.**_ 

to reproduce:

Go through the send flow to send some eth to one of your accounts
Before submitting your txn change the gas fee to low
Submit txn
go to the activity view ( formerly transaction history) 
notice the pending transaction is missing.

2022-03-09 04:07 UTC, gantunesr commented
@cortisiko fixed in [ad4b9eb](https://github.com/MetaMask/metamask-mobile/pull/3790/commits/ad4b9eb81fd3bc3e0f4eb4d0013ed2aa7e7d4efb)

2022-03-09 15:24 UTC, cortisiko approved these changes
I tested:
sending ETH and speeding up the transaction
                                  -  between wallet addresses
                                  - between different wallets

sending ERC-20 tokens and speeding up the transaction
                                  -  between wallet addresses
                                  - between different wallets

sending an NFT and speeding up the transaction:
                                  -  between wallet addresses
                                  - between different wallets

I verified that the asset overview and transaction activity on both the sender and receiver showed the correct state. I also verified that the receiver of the transaction did not see duplicate transactions and the pending transaction did not show up on the receivers end. 

@gantunesr this guy is 🌮  🌮 🌮

2022-03-09 17:51 UTC, plasmacorral approved these changes
Approving changes based on cortisiko's testing

2022-03-09 17:52 UTC, merged