Upgrade WebView to 11.17.0
MetaMask/metamask-mobile pull request #3905
Opened 2022-03-16 21:13 UTC by gantunesr

**Description**

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2022-03-17 18:10 UTC, Fatxx approved these changes
LGTM

2022-03-24 20:43 UTC, sethkfman commented on package.json
> +    "react-native-webview": "11.17.2",
Make sure the patch applies

2022-03-24 20:46 UTC, sethkfman requested changes
Suggest checking for the android system webview version to be equal or greater than 83.0.4103.106. 
- if false `prompt and direct user to upgrade version`
  - if reject upgrade then keep `setSupportMultipleWindows = true`
- else ` setSupportMultipleWindows = false`

2022-04-11 03:32 UTC, gantunesr commented on app/util/general/index.js
> +export const versionGreaterOrEqualThan = (vOne, vTwo) => {
Add errors if:

- One or both values are empty strings
- One or both are not `String`

2022-04-18 03:46 UTC, gantunesr commented
Converting this PR to draft since design is required

2022-04-18 14:45 UTC, gantunesr commented on app/components/Views/BrowserTab/index.js
> +				);
Use library `compare-versions`

2022-05-05 17:02 UTC, gantunesr commented on app/components/Views/BrowserTab/index.js
> +        {!safeAndroidWebviewVersion && <Text>Not a safe version</Text>}
Update styles

2022-05-23 07:06 UTC, gantunesr commented
Solution update:

1. Check Android WebView System version
2. If version is equal or greater than `83.0.4103.106`
  - User uses Browser as usual
3. Else
  - Prompt system alert to warn user about outdated version and security risk

2022-06-03 06:57 UTC, Fatxx commented on app/components/Views/BrowserTab/index.js
> +        {!safeAndroidWebviewVersion && <Text>Not a safe version</Text>}
Design: https://www.figma.com/file/BVcxQCC87m22iqI2lCFDj8/Forced-Upgrades?node-id=6%3A11

2022-06-04 10:31 UTC, Fatxx commented
Separated Toast Component PR: https://github.com/MetaMask/metamask-mobile/pull/4450

2022-06-14 22:55 UTC, sethkfman commented on app/components/Views/BrowserTab/index.js
> +                'https://play.google.com/store/apps/details?id=com.google.android.webview',
Move to the `constants/url`

2022-06-22 22:14 UTC, Fatxx commented on patches/react-native-webview+11.17.2.patch
> --      RNCWebView reactWebView = (RNCWebView) webView;
I believe that was not removed but changed to another line since this new version added new lines of code to the file

2022-07-07 16:41 UTC, cortisiko requested changes
I am still experiencing the browser reload bug: http://recordit.co/fEk3zsqm2c


To reproduce:

- use a device with the webview version < 84. If you do not have a physical device readily available feel free to use browser stack. The google pixel 3 running android 9 is the device you want to use. The build name is webview_905.apk 

- open https://www.hawku.com/ in the browser

- notice the constant reloading.

2022-07-21 14:54 UTC, mobularay commented
Checked in with @Fatxx on latest status - this needs more work as upgrading the Webview doesnt fix the underlying issue of constantly refreshing

2022-09-21 12:35 UTC, gantunesr commented
After some discussions it was concluded that this fix won't the issue anymore. I'll close this PR for a new development.

2022-09-21 12:35 UTC, closed without merging