Network Specific Asset Education - Updated
MetaMask/metamask-mobile pull request #3910
Opened 2022-03-17 18:25 UTC by blackdevelopa

**Description**

This PR updates a user when they toggle to a different network and have no token/funds present.
https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/metamask/mobile-planning/149

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #3648

2022-03-18 14:27 UTC, owencraston commented on app/actions/onboardNetwork/index.js
> + */
New files should be typescript

2022-03-18 14:33 UTC, owencraston commented on app/actions/onboardNetwork/index.js
> +	type: 'SHOW_NETWORK_ONBOARDING',
when you make this typescript you can define these are real types so they can be type checked in calling functions

2022-03-18 14:34 UTC, owencraston commented on app/components/Base/LineDivide.tsx
> +export default LineDivide;
this should be wrapped in a `React.memo`

2022-03-18 14:35 UTC, owencraston commented on app/components/Base/LineDivide.tsx
> +function LineDivide(): JSX.Element {
`Jsx.element` is unnecessary here

2022-03-18 14:41 UTC, owencraston commented on app/components/Nav/Main/RootRPCMethodsUI.js
>  	const onSwitchCustomNetworkConfirm = () => {
All of these functions should be wrapped in `useCallback`

2022-03-18 14:43 UTC, owencraston commented on app/components/UI/DrawerView/index.js
> +	onInfoNetworksModalClose = async (manualClose) => {
They should also be wrapped in `useCallback`

2022-03-18 14:43 UTC, owencraston commented on app/components/UI/DrawerView/index.js
> +	onNetworkSelected = (type, currency, url) => {
same as above

2022-03-18 14:44 UTC, owencraston commented on app/components/UI/DrawerView/index.js
> +		const checkIfCustomNetworkExists = networkOnboardedState.filter(
this value should be memoized to avoid unnecessary re calculations. This can be done with [useMemo](https://reactjs.org/docs/hooks-reference.html#usememo)

2022-03-18 14:56 UTC, owencraston commented on app/components/UI/NetworkInfo/InfoDescription/index.tsx
> +const Description = (props: DescriptionProps) => {
What do you think about naming this file `InfoDescription.tsx` instead of index.tsx?

2022-03-18 14:56 UTC, owencraston commented on app/components/UI/NetworkInfo/InfoDescription/index.tsx
> +export default Description;
React.memo

2022-03-18 15:02 UTC, owencraston commented on app/components/UI/NetworkInfo/index.test.tsx
> +
I like to put my test files inside a `test` folder within the components folder

2022-03-18 15:04 UTC, owencraston commented on app/components/UI/NetworkInfo/index.test.tsx
> +const initialState = {
Have you confirmed if this actually does anything. When I was messing around with the tests used `const store = mockStore({});` and it didn't change anything. I verified this by logging the initial state inside the component.

2022-03-18 15:04 UTC, owencraston commented on app/components/UI/NetworkInfo/InfoDescription/index.tsx
> +							{' '}
what is this empty text for?

2022-03-18 15:05 UTC, owencraston commented on app/components/UI/NetworkInfo/index.test.tsx
> +	it('should render correctly', () => {
Are there no other test cases you can check? what about the logic around `clickableText`?

2022-03-18 15:08 UTC, owencraston commented on app/components/UI/NetworkInfo/index.tsx
> +		onClose,
These can be destructured in the line 95. Its not a huge difference but imo its cleaner.

2022-03-18 15:09 UTC, owencraston commented on app/components/UI/NetworkInfo/index.tsx
> +const NetworkInfo = (props: NetworkInfoProps): JSX.Element => {
`JSX.Element` is redundant.

2022-03-18 15:14 UTC, owencraston commented on app/components/UI/NetworkInfo/index.tsx
> +	networkProvider: {
Maybe this should be defined as a separate interface instead of inline?

2022-03-18 15:21 UTC, owencraston commented on app/components/UI/NetworkInfo/index.tsx
> +								? strings('network_information.first_description', { ticker })
just echoing what I said above, this logic is so difficult to follow when its all in one file like this.

2022-03-18 15:22 UTC, owencraston commented on app/components/UI/NetworkInfo/index.tsx
> +export default connect(mapStateToProps)(NetworkInfo);
I've never seen this. what is going on here?

2022-03-18 15:23 UTC, owencraston commented on app/components/UI/NetworkInfo/index.test.tsx
> +	it('should render correctly', () => {
This file is massive and has a lot of branching statements. I'd encourage you to think of more test cases.

2022-03-18 15:34 UTC, owencraston commented on app/constants/network.js
> +export const PRIVATENETWORK = 'PRIVATENETWORK';
i'd suggest converting this file into typescript. Then we can have real types defined that can be used for type safety in the future.

2022-03-18 15:35 UTC, owencraston commented on app/reducers/index.js
> +	networkOnboarded: networkOnboardReducer,
I think this file could easily be converted to typescript.

2022-03-18 15:41 UTC, owencraston commented on app/reducers/networkSelector/index.js
> +/**
Again, I think this new  file should be typescript. Its going to be hard enough to convert the old files into TS so we shouldn't make the job harder by adding new vanilla js files.

2022-03-18 15:43 UTC, owencraston commented on app/util/santizeUrl.tsx
> +const santizeUrl = (url: string) => url.replace(/\/$/, '');
I am not sure if this makes a big difference but I dont think this is a `.tsx` file. Instead it should be just `.ts` I thought the compiler would say something if you dont have `jsx` in a .`tsx` file but if not we should still probably try and follow that pattern.

2022-03-18 15:44 UTC, owencraston commented on app/util/santizeUrl.tsx
> +const santizeUrl = (url: string) => url.replace(/\/$/, '');
I feel that with utility functions we should have a minimum of 1 unit test since they are fairly critical and will get consumed all over the place. luckily they are super easy to test. We can pair on some testing if you want.

2022-03-18 15:46 UTC, owencraston commented on e2e/pages/modals/NetworkEducationModal.js
> +export default class NetworkEducationModal {
why use a class ?

2022-03-18 15:46 UTC, owencraston commented on ios/Podfile.lock
> -COCOAPODS: 1.11.2
Is this intentional ?

2022-03-18 15:47 UTC, owencraston requested changes
Very good stuff. I had a few comments mostly regarding code cleanliness, typescript and testing. Please let me know if you need further clarification or want to pair on any issues.

2022-03-21 20:34 UTC, owencraston commented on app/components/UI/NetworkInfo/index.test.tsx
> +const initialState = {
Confirmed you do need this

2022-03-21 20:36 UTC, owencraston commented on app/util/sanitizeUrl.ts
> +const sanitizeUrl = (url: string) => url.replace(/\/$/, '');
I think adding some tests to this function would be nice

2022-03-21 21:33 UTC, owencraston approved these changes
Code looks good to me. I didn't run the code on my device though.

2022-03-24 01:00 UTC, cortisiko requested changes
Issue 1
(android specific google pixel 3XL to be exact) 
If i were to add BSC mainnet to my list of networks 
Switch to BSC mainnet 
the network education modal appears and the text  “binance smart chain mainnet” is misaligned https://www.screencast.com/t/NHCvsvxq 

Issue 2
As a returning user with funds across custom networks, If i were to:
add a custom network
switch to that custom 
the education modal appears. 

see here: http://recordit.co/sPw1sWvKGc

Issue 3
In the education modal if i were to:
tap on “click here to manually add the tokens”  the import token view appears fine but the education modal does not disappear. 
http://recordit.co/i2Rmb3WKio

Issue 4
(android specific google pixel 3XL to be exact) 
In the educational modal on line item #2 if i were to tap on “learn more” I get “oops something went wrong there was an error loading the network information …” 

to reproduce: 
trigger the education modal on a custom network (i used fantom opera)
tap on the “learn more” link in line item #2 
http://recordit.co/aFZj0lqOKi

2022-03-25 17:04 UTC, cortisiko approved these changes
🌮 🌮 🌮

2022-03-28 11:42 UTC, merged