Feature/quotes-refresh
MetaMask/metamask-mobile pull request #3926
Opened 2022-03-21 14:37 UTC by alaahd

**Description**

* [ ] Adding data polling for fetching new quotes using time interval. 

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2022-03-28 16:47 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/sdk/index.tsx
> +			}
How frequent does this case happens? Should we log this?

2022-04-12 17:49 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/GetQuotes.js
> +const POLLING_CYCLES = 2;
Can you move this to the AppContants, read them on the SDKProvider from AppContants and provide them through the provider object (along with `sdk` and selected state)?

This in the future might be a setting coming from the SDK/Server

2022-04-12 17:52 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/GetQuotes.js
> +										!error && !errorCode && amountIn && amountOut
Why is `error` not enough?

2022-04-13 18:19 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/sdk/index.tsx
> +			}
It is very intermittent. it happens mostly with a fresh start of the application.

2022-04-13 18:21 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/GetQuotes.js
> +										!error && !errorCode && amountIn && amountOut
it is enough, but this is a more religious check!

2022-04-13 18:23 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/sdk/index.tsx
> +			}
We will remove this provider from the app startup (splitting orders/buy flow), however we should definitely keep an eye on this when the buy flow is mounted.

2022-04-13 18:28 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/sdk/index.tsx
> +			}
Indeed but we are going to point to another provider which could still need a reference to another sdk instance required for order management!

2022-04-13 18:30 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/GetQuotes.js
> +										!error && !errorCode && amountIn && amountOut
Let's just use error please 🙏

2022-04-20 22:42 UTC, wachunei requested changes

2022-04-20 22:42 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/GetQuotes.js
> +		backgroundColor: colors.grey000,
use colors from theme, search for `createStyles` in the codebase for reference

2022-04-21 13:11 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/GetQuotes.js
> +		backgroundColor: colors.grey000,
we are already using colors from theme

2022-04-21 13:44 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/GetQuotes.js
> +		},
These colors are not present in the design tokens, I think it should be `success` and `error` I'm not sure, please reach out to design team 🙏 https://github.com/MetaMask/design-tokens/blob/main/src/colors/index.ts

2022-04-21 13:56 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/GetQuotes.js
> +		backgroundColor: colors.grey000,
Fixed

2022-04-21 14:32 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/GetQuotes.js
> +		backgroundColor: colors.grey000,
Fixed.

2022-04-21 14:33 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/GetQuotes.js
> +		},
Fixed

2022-04-21 15:34 UTC, wachunei approved these changes

2022-04-21 15:43 UTC, merged