Fix/watch asset rpc call
MetaMask/metamask-mobile pull request #3942
Opened 2022-03-23 15:04 UTC by jpcloureiro

**Description**

_Fix payload when adding a custom token (wallet_watchAsset rpc call). Also use the token logo if provided._

[wallet_watchAsset rpc method spec](https://eips.ethereum.org/EIPS/eip-747#wallet_watchasset)

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #3722

2022-03-23 15:23 UTC, jpcloureiro commented
I have read the CLA Document and I hereby sign the CLA

2022-03-23 15:48 UTC, jpcloureiro commented
I have read the CLA Document and I hereby sign the CLA

2022-03-24 11:26 UTC, jpcloureiro commented
I have read the CLA Document and I hereby sign the CLA

2022-03-25 01:12 UTC, gantunesr requested changes
Good work @jpcloureiro! Left some comments

2022-03-25 01:12 UTC, gantunesr commented on app/components/UI/AssetOverview/index.js
> +import TokenImage from '../../UI/TokenImage';
Can you explain why this change is necessary?

2022-03-25 11:06 UTC, jpcloureiro commented on app/components/UI/TokenImage/index.js
> +	const assetImage = isUrl(asset.image) ? asset.image : null;
Good catch. Somehow I assumed asset prop was declared as `isRequired`

We should also use optional when passing `asset.address` to the `<Identicon />` component (line 28)

2022-03-25 11:06 UTC, jpcloureiro commented on app/components/UI/AssetOverview/index.js
> +import TokenImage from '../../UI/TokenImage';
`TokenImage` component already implements this logic

```jsx
const iconUrl = tokenList[address]?.iconUrl || tokenList[address?.toLowerCase()]?.iconUrl || '';
return iconUrl ? <AssetIcon logo={iconUrl} /> : <Identicon address={address} />;
```

It is better to reuse that component and remove the unused imports

2022-03-28 11:59 UTC, jpcloureiro commented on app/components/UI/TokenImage/index.js
> +	const assetImage = isUrl(asset.image) ? asset.image : null;
addressed at https://github.com/MetaMask/metamask-mobile/pull/3942/commits/4bfbfc93ab8656ee2d440c1da7b7af93cc71e318

2022-03-28 13:24 UTC, gantunesr approved these changes
LGTM

2022-04-11 15:35 UTC, chrisleewilcox commented
Getting the following error when running `yarn setup`...
**ERROR** Failed to apply patch for package @metamask/design-tokens at path
  
    node_modules/@metamask/design-tokens

  This error was caused because @metamask/design-tokens has changed since you
  made the patch file for it. This introduced conflicts with your patch,
  just like a merge conflict in Git when separate incompatible changes are
  made to the same piece of code.

  Maybe this means your patch file is no longer necessary, in which case
  hooray! Just delete it!

  Otherwise, you need to generate a new patch file.

  To generate a new one, just repeat the steps you made to generate the first
  one.

  i.e. manually make the appropriate file changes, then run 

    patch-package @metamask/design-tokens

  Info:
    Patch file: patches/@metamask+design-tokens+1.4.2.patch
    Patch was made for version: 1.4.2
    Installed version: 1.5.1

---
patch-package finished with 1 warning(s), 1 error(s).
4. Create xcconfig files...
5. Init git submodules

2022-04-11 15:38 UTC, wachunei commented
@chrisleewilcox this was fixed here https://github.com/MetaMask/metamask-mobile/commit/b9d3f4b1b33c377508eaefab9e371bb2e62195cb, updating this branch with main will fix it.

2022-04-14 18:54 UTC, chrisleewilcox approved these changes
Here is a recording of the test.  Data is shown as expected and token icon is shown.

https://recordit.co/pjMnCIaTr4


LGTM

2022-04-25 15:50 UTC, merged