Fix/2830 enter many names
MetaMask/metamask-mobile pull request #3967
Opened 2022-03-29 09:55 UTC by tommasini

**Description**

The input text is not longer transformed in a formatted text with was impossible to keep writing.
Now it is a text input with a check icon that tell us that the address it is valid.

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Resolves #2830 
Resolves the fact that we could not write many names like "evan.ethereum.ether" and now we can access that addresses too with this solution.

Small demo with the final result

https://user-images.githubusercontent.com/46944231/160585472-64d17744-04c8-47ed-93d6-d1ed27c8c660.mp4

2022-03-30 13:15 UTC, gantunesr requested changes
Hey @tommasini, this is looking good. Left a few comments and also we have a provider that takes care of the translations, so you only need to add the english text and they take care of the rest, so you can revert those changes.

2022-03-30 13:15 UTC, gantunesr commented on app/components/Views/SendFlow/AddressInputs/index.js
> +					{!toSelectedAddress?.length > 0 ? (
Can you move this condition to a variable with a clear name so its easier to read and understand the logic?

2022-03-30 13:15 UTC, gantunesr commented on app/util/address/index.js
>  }
Can you add unit testing to this method?

2022-03-30 13:15 UTC, gantunesr commented on app/components/Views/SendFlow/SendTo/index.js
> +				toAddressName = toAddressName === undefined ? toSelectedAddress : toAddressName;
Would this work too?

```suggestion
				toAddressName = toAddressName || toSelectedAddress;
```

2022-03-30 16:57 UTC, tommasini commented on app/components/Views/SendFlow/AddressInputs/index.js
> +					{!toSelectedAddress?.length > 0 ? (
Yes of course! Thank you!

2022-03-30 16:58 UTC, tommasini commented on app/util/address/index.js
>  }
Of course! Done it! Thank you!

2022-03-30 16:58 UTC, tommasini commented on app/components/Views/SendFlow/SendTo/index.js
> +				toAddressName = toAddressName === undefined ? toSelectedAddress : toAddressName;
Yes, tested and implemented! Thank you!

2022-04-06 09:34 UTC, tommasini commented
With @jpcloureiro, we solve the [issue](https://github.com/MetaMask/metamask-mobile/issues/4005) , upgrading the "to" input performance in the last commit of this branch

2022-04-12 04:06 UTC, chrisleewilcox commented
Not able to checkout/pull branch.  Getting an invalid error....
![image](https://user-images.githubusercontent.com/6626407/162878299-c70db02e-de2b-47e0-9540-623ba598a2a2.png)

2022-04-12 14:47 UTC, tommasini commented
Closing this PR and opening a new one from the remote metamask mobile app repo, can access [here](https://github.com/MetaMask/metamask-mobile/pull/4089)

2022-04-12 14:47 UTC, closed without merging