Info and region alert
MetaMask/metamask-mobile pull request #3982
Opened 2022-03-30 12:52 UTC by VikChawla

**Description**

Added provider info modal, and integrated region alert with dark mode. 

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #???

2022-03-31 20:40 UTC, wachunei requested changes
Left a few comments with small changes

2022-03-31 20:40 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/GetQuotes.js
> +		setShowInfo(!showInfo);
This is not needed, whenever you want to toogle `setState` value you can do `setState(value => !value)`

2022-03-31 20:40 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/GetQuotes.js
> +				dismiss={() => setShowInfo(!showInfo)}
Set it to `false` explicitly

2022-03-31 20:40 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/GetQuotes.js
> +										showInfo={() => renderInfo()}
Set it to `true` explicitly

2022-03-31 20:40 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/Region.js
> +		setRememberRegion(!rememberRegion);
Undo this change.

2022-03-31 20:40 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/Region.js
> +				dismiss={() => setShowAlert(!showAlert)}
Set it to `false` explicitly

2022-03-31 20:40 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/Region.js
> +						</TouchableOpacity>
Why the TouchableOpacity now does not wrap the Checkbox + Text?

2022-03-31 20:40 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/components/RegionAlert.tsx
> +		},
This font size is 2 points bigger than `<Text big>`, can you reach out to design team about the possibility of turning this into a reusable font size (eg: `<Text bigger>`)?

2022-03-31 20:40 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/components/RegionModal.tsx
> +			backgroundColor: colors.background.alternative,
Do you have a graphic reference about this change?

2022-03-31 20:40 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/components/RegionModal.tsx
> +							dismiss={() => setShowAlert(!showAlert)}
Set it to `false` explicitly

2022-04-04 14:01 UTC, VikChawla commented on app/components/UI/FiatOnRampAggregator/Views/Region.js
> +						</TouchableOpacity>
It was causing errors before. The touchable opacity and the checkbox were becoming un-synced. Do you want me to try finding another workaround?

2022-04-04 14:33 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/components/RegionModal.tsx
> +			backgroundColor: colors.background.alternative,
Yes, change it back. Semantically the separator is should corresponde to a `border.muted` color, we can ask a design review later once we code frees.

2022-04-04 14:42 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/Region.js
> +						</TouchableOpacity>
Make the checkbox a controlled component, remove the `onValueChange` prop and let the wrapper capture the press event.:

example:
```tsx
	<TouchableOpacity onPress={handleChangeRememberRegion} style={styles.checkboxView}>
		<CheckBox
			value={rememberRegion}
			boxType="square"
			animationDuration={0.2}
			onAnimationType="fill"
			offAnimationType="fill"
			onFillColor={colors.primary}
			onCheckColor={colors.background.default}
			style={styles.checkbox}
		/>
		<Text black style={styles.checkboxMargin}>
			{strings('fiat_on_ramp_aggregator.region.remember_region')}
		</Text>
	</TouchableOpacity>
```

Also, if you are going to dismiss the opacity effect with `activeOpacity={1}`, consider using `<Pressable>` instead.

2022-04-04 17:16 UTC, CryptoGodfatherVA23 approved these changes

2022-04-07 13:55 UTC, wachunei approved these changes

2022-04-20 17:06 UTC, closed without merging