Use converted input value if internal currency is FIAT
MetaMask/metamask-mobile pull request #3989
Opened 2022-03-30 19:42 UTC by Fatxx

**Description**

Use converted input value if FIAT is selected as an internal currency. 

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Resolves #3983

2022-03-31 14:26 UTC, jpcloureiro commented on app/components/Views/SendFlow/Amount/index.js
> +			inputValue = inputValueConversion;
I suggest creating a new variable instead of mutating the function parameter `inputValue`

2022-04-04 01:47 UTC, CryptoGodfatherVA4 approved these changes

2022-04-04 01:47 UTC, CryptoGodfatherVA4 approved these changes

2022-04-05 07:15 UTC, JessePinkman48 approved these changes

2022-04-12 15:56 UTC, chrisleewilcox commented
This branch is a draft.  Please update PR to show green open icon.  Makes it easy to determine if a PR is ready for QA.

2022-05-11 17:02 UTC, Fatxx reviewed
What do to when we don't have conversion rate available? 

- Force the user to switch to crypto as native currency?

@jakehaugen @yanrong-chen

2022-05-11 22:49 UTC, jakehaugen commented
> What do to when we don't have conversion rate available?
> 
> * Force the user to switch to crypto as native currency?

Discussed with @Fatxx, will work on some mocks and follow up.

2022-06-07 14:21 UTC, Fatxx commented
Figma: https://www.figma.com/file/ad2Higmy1dBMonznFEV4hZ/Fiat-converssions-not-available?node-id=5%3A102

2022-07-13 20:08 UTC, Fatxx commented on app/components/Views/SendFlow/Amount/index.js
> +    }
If it's crypto it uses the same logic that we have before

2022-07-26 11:48 UTC, gantunesr approved these changes
LGTM

Also verifies the correct functionality of sending ERC721 tokens and the same use cases as before in Ethereum Mainnet.

2022-10-15 01:09 UTC, chrisleewilcox commented
@Fatxx can you resolve the merge conflict?

2022-12-16 15:24 UTC, cortisiko commented
@Fatxx can you merge in main and solve these merge conflicts? I will remove needs QA for now. cc @sethkfman

2022-12-29 00:10 UTC, cortisiko requested changes
@Fatxx swinging this back your way:

**Issue 1**
is [this](https://www.screencast.com/t/eq4dBRn4GGT) expected? Happens when I attempt to send an NFT. 

**Issue 2**
if my primary currency is set to Fiat and I send funds, when I view the transaction activity, [the default seems to be Native and not Fiat](https://www.screencast.com/t/4Qm1tzltyB).

**Issue 3**
My primary currency is set to Fiat, when I view the detected tokens in my wallet, [the default currency is native and not Fiat. ](https://www.screencast.com/t/x8EmWJ20h)

**Issue 4**
if I were to scan a payment request QR code, when I land on the transaction confirmation view, the fiat conversion is set to 0. See [recording](https://recordit.co/MFv5VheCHm)

To reproduce:
on device A, request funds (go through the receive flow) then open up the QR code for the payment request
on device B scan device A QR code. Notice the fiat value is set to 0 

**Issue 5**
With Fiat as my default currency, when i tap on the send button on the transaction confirmation screen, the screen does not disappear. See [recording](http://recordit.co/nvue2E2eE7).



To reproduce:
add then switch to BSC
change your default currency from Native to Fiat
attempt to send funds, notice after you tap on “send” the transaction confirmation view does not disappear.

2022-12-29 15:46 UTC, Fatxx commented
@cortisiko 

I fixed **Issue 1** since it's related to the Amount Screen, which was the initial screen that needed to be set in this PR.

I'll look at **4** and **5** since they are related to the overall transaction flow.

Issues **2** and **3** are out of scope and should be developed in separate issues.

2022-12-29 20:00 UTC, Fatxx commented
@cortisiko 

Regarding **issue 4**:
The problem here is that the sender doesn't have the token currently on the token list and the controllers fetch the exchange rates from this token list, so when you open the confirm screen from the QR code the conversion rate is not available.

What I did to fix this is to add the respective erc20 token to the token list, since there is no way to get this exchange rate directly from the controllers. cc @sethkfman 

Recording with the fix:
https://recordit.co/vK5sfaVBoc

2022-12-29 20:04 UTC, Fatxx commented
@cortisiko 

Regarding **issue 5**, I'm not able to reproduce it.

https://recordit.co/pXeQTh8SUY

2023-01-13 18:30 UTC, sethkfman commented
Test case
- User receiving payment request
   - User has 0 token balance (temporarily add during send flow, don't show token)
   - User has more than 0 token balance but it doesn't display in wallet (add token and display)

2023-01-17 19:53 UTC, Fatxx commented
@cortisiko 

**Issue 4** fixed

2023-02-09 23:49 UTC, cortisiko commented
When I send funds, I get `[TypeError: undefined is not an object (evaluating 'weiBalance.isZero')`


to reproduce:
send funds to an address
notice the error. 

@Fatxx sending this back your way.

2023-02-17 01:00 UTC, cortisiko approved these changes
ticket looks good to me 🌮 🌮 🌮

2023-02-17 10:35 UTC, closed without merging