Download attachments in browser on iOS
MetaMask/metamask-mobile pull request #4052
Opened 2022-04-06 19:15 UTC by owencraston

**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Progresses #???

2022-04-19 16:38 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> +const HOMEPAGE_HOST = 'localhost:3000';
This must be deleted before merging and is required for testing since we block the popup of the autocomplete modal if the source is not the `HOMEPAGE_HOST` so to test the new version of the dapp I needed to modify this to support local host.

2022-04-19 19:30 UTC, owencraston commented on app/core/AppConstants.js
> +	HOMEPAGE_URL: 'http://localhost:3000/',
This must be removed before merging. This is needed for the same reason as [this](https://github.com/MetaMask/metamask-mobile/pull/4052/files#diff-72ccae71561c6917c635e5f6e2e93d9149271e8422e3ea4f8f211d73f9ae0ba7R55) so that we are able to test the autocomplete locally. If not for this we would be forbidden from triggering the url modal from the search bar in the dapp.

2022-04-19 19:39 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> -	const [autocompleteValue, setAutocompleteValue] = useState('');
we are no longer handling the state of the modal inside this component which makes it much easier to read. The autocomplete, showUrlModal and inputRef are all handled by the new BrowserUrlModal component

2022-04-19 19:40 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> -	const toggleUrlModal = useCallback(
This was simply moved to [here](https://github.com/MetaMask/metamask-mobile/pull/4052/files#diff-72ccae71561c6917c635e5f6e2e93d9149271e8422e3ea4f8f211d73f9ae0ba7R847) as this function became dependant on some other functions that were defined later in the file. It resulted in less changes to move this downward than to bring everything up above this line.

2022-04-19 19:42 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> -	const initializeBackgroundBridge = (urlBridge, isMainFrame) => {
This was also simply moved down to [here](https://github.com/MetaMask/metamask-mobile/pull/4052/files#diff-72ccae71561c6917c635e5f6e2e93d9149271e8422e3ea4f8f211d73f9ae0ba7R856) as it became dependant on `toggleURlModal` and needed to be defined after.

2022-04-19 19:44 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> -	useEffect(() => {
This was moved to [here](https://github.com/MetaMask/metamask-mobile/pull/4052/files#diff-72ccae71561c6917c635e5f6e2e93d9149271e8422e3ea4f8f211d73f9ae0ba7R918) since it needed to be defined after `initializeBackgroundBridge` which was moved due to its dependancy on toggleUrl modal

2022-04-19 19:45 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> -	const onLoadStart = async ({ nativeEvent }) => {
This was moved to [here](https://github.com/MetaMask/metamask-mobile/pull/4052/files#diff-72ccae71561c6917c635e5f6e2e93d9149271e8422e3ea4f8f211d73f9ae0ba7R888) since it needed to be defined after `initializeBackgroundBridge` which had moved due to its dependancy on `toggleUrlModal`

2022-04-19 19:46 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> -	const renderProgressBar = () => (
moved to [here](https://github.com/MetaMask/metamask-mobile/pull/4052/files#diff-72ccae71561c6917c635e5f6e2e93d9149271e8422e3ea4f8f211d73f9ae0ba7R933)

2022-04-19 19:46 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> -	const onURLChange = (inputValue) => {
this is no longer needed since the BrowserUrlModal handles its own input state

2022-04-19 19:47 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> -	const clearSearchInput = () => {
This is no longer needed since the BrowserUrlModal handles this now

2022-04-19 19:48 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> -	const renderUrlModal = () => {
🔥 (no longer needed)

2022-04-19 19:49 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> +	const handleOnFileDownload = async (downloadUrl) => {
This is our callback that wraps our `downloadFile` and finishes the request when the file is downloaded

2022-04-19 19:49 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> +							onFileDownload={({ nativeEvent: { downloadUrl } }) => handleOnFileDownload(downloadUrl)}
here is where we hook up the logic to download attachments

2022-04-19 19:51 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> +			props.navigation.navigate('BrowserUrlModal', { url: urlToShow, onUrlInputSubmit });
Triggers a navigation to the modal screen but the screen will appear as an overlay

2022-04-19 19:52 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> +			props.navigation.navigate('BrowserUrlModal', { url: urlToShow, onUrlInputSubmit });
we did not want exhaustive deps here since it would be dependant on props which would get changed when we make this call causing an infinite re render

2022-04-19 19:52 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> -				{isTabActive() && renderUrlModal()}
In the future we can move the rest of our modals to use this pattern and really clean up this file.

2022-04-19 19:54 UTC, owencraston commented on locales/languages/en.json
> +		"title": "Save file",
these strings are up for debate.

2022-04-19 22:58 UTC, sethkfman reviewed
A few minor comments

2022-04-19 22:58 UTC, sethkfman commented on app/util/browser/downloadFile.ts
> +				message: 'unknown error occurred',
Add to local strings

2022-04-19 22:58 UTC, sethkfman commented on package.json
> +    "react-native-share": "7.3.7",
This is a big bump. We should make sure we test the other share features.

2022-04-19 22:58 UTC, sethkfman commented on app/components/Views/BrowserUrlModal/BrowserUrlModal.tsx
> +const BrowserUrlModal = (props: Props) => {
I would add a snapshot test case here

2022-04-20 13:40 UTC, andreahaku commented on app/core/AppConstants.js
> +	HOMEPAGE_URL: 'http://localhost:3000/',
same as above.

2022-04-20 14:16 UTC, blackdevelopa commented on app/components/Views/BrowserUrlModal/BrowserUrlModal.tsx
> +			<View style={styles.urlModalContent} testID={'url-modal'}>
nitpick: Can we have `'url-modal'` as a constant. `..app/constants/test-ids`

2022-04-20 14:22 UTC, blackdevelopa commented on ios/MetaMask.xcodeproj/project.pbxproj
> -				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64;
I don't think this file change should be committed.

2022-04-20 17:50 UTC, owencraston commented on app/core/AppConstants.js
> +	HOMEPAGE_URL: 'http://localhost:3000/',
@andreahaku I am going to remove this very soon since I am going to ship [this change](https://github.com/MetaMask/dapps/pull/121) to production. You are probably right though.

2022-04-20 17:55 UTC, owencraston commented on ios/MetaMask.xcodeproj/project.pbxproj
> -				"EXCLUDED_ARCHS[sdk=iphonesimulator*]" = arm64;
true, this was needed for testing

2022-04-21 19:54 UTC, tommasini commented on app/components/UI/NavbarBrowserTitle/index.js
> +		this.props.route.params?.showUrlModal?.();
I'm curious, why do we need the '?' in this case?

2022-04-21 20:15 UTC, owencraston commented on app/components/Views/BrowserUrlModal/BrowserUrlModal.tsx
> +const BrowserUrlModal = (props: Props) => {
New snapshot and test file has been added

2022-04-21 20:17 UTC, owencraston commented on app/components/UI/NavbarBrowserTitle/index.js
> +		this.props.route.params?.showUrlModal?.();
Since the props may not exist we need to null check them first. This is partly due to the fact that this is a `js` file. This is called [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).

2022-04-21 20:42 UTC, tommasini commented on app/components/UI/NavbarBrowserTitle/index.js
> +		this.props.route.params?.showUrlModal?.();
I was wondering because I was thinking that prop would came always because that's the onPress action of the touchable opacity component and because of that would never came null!
Thank you so much for the answer 🍀🚀

2022-04-21 20:55 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> +const HOMEPAGE_HOST = 'localhost:3000';
added it as a comment

2022-04-25 18:04 UTC, owencraston commented
@sethkfman I tested the other use of share in the browser and it works as expected with the upgrade. I read the documentation and there doesn't seem to be any breaking changes. I couldn't figure out where the other uses of share are in the app to test them but this example seems to indicate that it's working. 

https://user-images.githubusercontent.com/22918444/165147617-aae5982c-de9a-458b-8d30-f95846c25909.MOV

2022-04-25 18:08 UTC, owencraston commented
I also confirmed that for file downloads, the title and message are not needed so I removed them from my helper function and en.json

https://user-images.githubusercontent.com/22918444/165148192-1e2aa714-0829-477a-b8f3-02732d9c22a6.MOV

2022-04-25 19:16 UTC, sethkfman approved these changes
LGTM

2022-04-26 13:38 UTC, owencraston commented on package.json
> +    "react-native-share": "7.3.7",
I did a test of the other use case of share in the browser and it seems to be working as expected.

2022-04-26 22:24 UTC, cortisiko requested changes
@owencraston sending this back your way! 


**Issue 1** 
the keyboard does not open on android: http://recordit.co/gsmKjCvmEf 

To reproduce:
launch the app on android
go to the browser
attempt to enter a URL
notice the keyboard does not appear.  

**Issue 2** 
deep linking to a dapp is broken: http://recordit.co/uQgPcG0wup

To reproduce:
deep link here: https://metamask.app.link/dapp/app.olympusdao.finance/#/bonds 
notice the browser open
but the dapp does not open

2022-04-29 17:31 UTC, owencraston commented
@cortisiko By adding a new name to the BrowserTabHome screen in the stack navigator I was able to fix the deep linking issue

https://user-images.githubusercontent.com/22918444/165994220-f7e01425-2a4a-4bde-9a89-6523f23309a2.MP4

2022-04-29 17:48 UTC, owencraston commented
### Some more test deep links
- https://metamask.app.link/dapp/app.uniswap.org
- https://metamask.app.link/approve/0x1d7a9cd8c67e3c74a84bb76cbc1b606e2e460db5@3/approve?address=0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6&uint256=3e18
- https://metamask.app.link/send/0xB8B4EE5B1b693971eB60bDa15211570df2dB228A@56?value=1e14
- https://metamask.app.link/dapp/metamask.github.io/test-dapp/
- https://metamask.app.link/send/0x3dD3DfaAdA4d6765Ae19b8964E2BAC0139eeCb40@4/approve?address=0x178e3e6c9f547A00E33150F7104427ea02cfc747&uint256=5e8

2022-05-02 14:46 UTC, andreahaku approved these changes
LGTM!

2022-05-02 17:21 UTC, owencraston commented on app/components/Views/BrowserUrlModal/BrowserUrlModal.tsx
> +	const triggerClose = () => dismissModal();
I meant to wrap this in a useCallback. I made these changes in the latest commit

2022-05-03 00:10 UTC, cortisiko commented
@owencraston Issue 1 was fixed. [The android keyboard appears](http://recordit.co/9h42J16mlz) when I tap on the input url. 

However issue 2 was partially fixed. 

- When I attempt to deep link with the app in the background the browser opens and the dapp loads. ✅ 

- When I attempt to deep link to a dapp with the app closed, the browser page opens but the dapp does not load. See [here](http://recordit.co/BR0yb23L8e )

to reproduce:
- with the app closed, attempt to deep link here: https://metamask.app.link/dapp/metamask.github.io/test-dapp/
- notice the app launches to the browser but the dapp does not load.

2022-05-04 22:07 UTC, owencraston commented
@cortisiko I managed to get the deeplinks working when the app is in the background as well as closed. 
https://user-images.githubusercontent.com/22918444/166833420-0e5e15dc-e8fb-4613-952a-177cd48d6fce.MP4

2022-05-05 23:09 UTC, cortisiko requested changes
@owencraston Okay so the deep linking issues as well as the android keyboard issue is fixed. I did however run into a couple more issues. See below:

{ios specific}
1.
From the browser homepage when i tap on the search input box above the favorites tap, the input modal appears. Fine. If i were to tap on the “cancel” button, the modal does not disappear: http://recordit.co/3u6AiVN20G

2.
after i download an attachment I am taken back to the browser homepage. Now on that home page I can’t tap on the “take tutorial button” at the bottom of the page

furthermore, when i tap on the top nav in the browser the metamask homepage url (https://home.metamask.io/) does not appear

If i were to open a new browser tab I can tap on the “take tutorial button” at the bottom of the page and when i tap on the top nav in the browser the metamask homepage url appears. 

This does not happen on android.  
see recording here http://recordit.co/Q2vVPAfgVE

to reproduce:
open the browser and paste https://storage.opensea.io/files/7c2a3bf635a404d6ad0cdbea5a643d6f.glb
download the attachment
notice you are still on the browser home page
scroll to the bottom of the page and tap on the take tutorial button
notice nothing happens
go ahead and tap on the input box in the top nav. 
notice the home page url is missing

3. (this affects both iOS and Android) 
From a dapp I am unable to add a token to my wallet aka asset watch is broken

For example on uniswap after i swap from native to ERC-20, The Add {token_name} to Metamask button does not work: http://recordit.co/3wIKK6QXUh

to reproduce (the long way):
ensure you have testnet funds then switch to rinkeby
go to https://app.uniswap.org
swap ETH to UNI
notice a modal appears with a “Add UNI to Metamask” button
tap on it. Notice nothing happens. 

to reproduce (the short way):
follow the steps to reproduce here: https://github.com/MetaMask/metamask-mobile/issues/3722

4.
Can we make expanding the url input box behavior consistent on ios and android? Right now android highlights the url and iOS does not. see here: http://recordit.co/DHBZPyR2sJ (left device is android & the right device is iOS)

to reproduce:
on ios go to the browser
tap on the browser input in the top nav
notice the url is not highlighted

5.
Something wonky is happening with dapp interactions on ios. Meaning i would open the test dapp in the ios browser then:
tap create token
I submit the transaction to create the token
the transaction goes through successfully but the buttons for all the other token interactions are not working correctly.

on android this is not the case. I can repeat the above on android and everything works as expected.

see here:
 http://recordit.co/cG1431IrXO (left device is android & the right device is iOS)

2022-05-06 17:48 UTC, owencraston commented
Link to staging site for metamask home: https://62606731634cc3230534a7f5--metamask-dapps.netlify.app/
^ meant to test the latest dapp features

2022-05-10 21:50 UTC, cortisiko commented
Update:  Issue 2 & 3 was fixed. I can no longer reproduce Issue 5. The only outstanding item is issue 4.

2022-05-11 19:02 UTC, owencraston commented on app/components/Views/BrowserTab/index.js
> -      Engine.context.TokensController.hub.removeAllListeners();
After talking with @andrepimenta we decided this was not needed since the listeners are instantiated/removed in the RootRPCMethodsUI component. This was causing some issues with asset watch.

2022-05-11 21:47 UTC, cortisiko approved these changes
Good work @owencraston, we are QA pass! 🌮 🌮

2022-05-12 00:14 UTC, merged