when tx is submitted we do not cancel anymore
MetaMask/metamask-mobile pull request #4060
Opened 2022-04-08 18:03 UTC by tommasini

**Description**
When tx is submitted, and the app goes to the background, we were trying to cancel it.

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Progresses #https://github.com/MetaMask/metamask-mobile/issues/3927

2022-04-13 18:10 UTC, gantunesr requested changes

2022-04-13 18:10 UTC, gantunesr commented on app/components/Views/Approval/index.js
> +					currentTransaction.status !== TX_SUBMITTED &&
`Reject`, `Cancelled`, `Failed` and `Confirmed` are final states. You should exclude them too

2022-04-18 14:42 UTC, gantunesr approved these changes
LGTM

2022-04-20 09:56 UTC, tommasini commented
Test case 1:
 - Go to browser and go to https://metamask.github.io/test-dapp/
 - Create a token
 - Put the mobile app in the background state
 - Watch the result of the notification
Test case 2:
 - Go to browser and go to https://metamask.github.io/test-dapp/
 - Create a token
 - Put the mobile app in the background state
 - Reopen the mobile app
 - Watch the result of the notification
 Test case 3:
 - Go to browser and go to https://metamask.github.io/test-dapp/
 - Create a token
 - Watch the result of the notification

2022-05-08 16:05 UTC, Jens05 commented
Any progress on this? If this issue is resolved i can continue with my Dapp :)

2022-06-08 23:08 UTC, cortisiko approved these changes
This ticket is QA passed. Scenarios I tested:

Send transaction 
Swap transaction
dapps transactions. 

I no longer see the `ooops something went wrong` alert message when the app was in the background. I also did not see that alert message when I killed and relaunched the app. Finally with push notifications turned on I did not receive a `ooops something went wrong` notification. Good work @tommasini 🌮 🌮

2022-06-09 08:39 UTC, merged