[FIX] [IMPROVEMENT] keep nft when transaction fail
MetaMask/metamask-mobile pull request #4091
Opened 2022-04-12 15:40 UTC by tommasini

**Description**
The problem was the collectible was removed when the transaction started.

**Proposed Solution**
The solution proposed was that the collectible was only removed when the transaction was confirmed.
Also, it's proposed here when the transaction it's submitted and we are waiting for feedback from the blockchain, the collectible details will change the _Send_ button for a _View Transactions_ button, which will redirect the user to the Activity View option on the left menu, where he can see the collectible transaction and cancel it or speed it up.

Also sorted the collectible by it's name inside of the collection.

**Code Impact**
Medium, changes the collectible details component and the way that collectibles have in the wallet.

**Screenshots/Recordings**
Small demo of the solution:
UPDATE:  https://recordit.co/6b8oh8xWLG
**Test Cases**
Case1:
 - Import collectible
 - Transact collectible to another account
 - Press the collectible to see the collectible details
 - Click on View Transaction Button, will redirect to Activity View
 - Cancel the collectible transaction 
 - Go to wallet
 - Verify if can send the collectible again
Case2:
 - Import collectible
 - Transact collectible to another account
 - Press the collectible to see the collectible details
 - Wait for the transaction ends and touch the modal to the button update

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**https://github.com/MetaMask/metamask-mobile/issues/2784#issuecomment-1038345711**

Solves #2784

2022-04-14 02:26 UTC, chrisleewilcox commented
I don't see the NFT in my receiving account that I had sent to.  Does the NFT need still need to be imported into the receiving account?

2022-04-14 09:15 UTC, tommasini commented
@chrisleewilcox , yes you will need to add in the receiving account too, you can also check in the open sea for test networks if you are using one [here](https://testnets.opensea.io/account)

2022-04-14 14:50 UTC, chrisleewilcox approved these changes
LGTM

2022-04-25 03:38 UTC, gantunesr reviewed
Left some minor comments

2022-04-25 03:38 UTC, gantunesr commented on app/components/Views/SendFlow/Confirm/index.js
> +			if (assetType === 'ERC721') {
Lets move `'ERC721'` to a constant file and update and the occurrences in the codebase along side `'ERC1155'`

2022-04-25 03:38 UTC, gantunesr commented on app/components/UI/CollectibleOverview/index.js
> +	 * When the collectible is being transacted, this func will navigate to Transactions View
Nit

```suggestion
	 * When the collectible is being transacted, this method will navigate to Transactions View
```

2022-04-25 03:38 UTC, gantunesr commented on app/components/UI/CollectibleOverview/index.js
> +	 * Returns if the collectible is being transacted or not
Nit

```suggestion
	 * Indicates if the collectible is being transacted or not
```

2022-04-25 03:43 UTC, gantunesr requested changes
This PR is blocked by a controllers release

https://github.com/MetaMask/controllers/pull/762

2022-04-27 13:10 UTC, tommasini commented on app/components/Views/SendFlow/Confirm/index.js
> +			if (assetType === 'ERC721') {
Done! 
Created at util/tokens constant file

2022-08-23 13:29 UTC, gantunesr reviewed
Some small comments

2022-08-23 13:29 UTC, gantunesr commented on app/components/UI/CollectibleContracts/index.js
> +      navigation.navigate('CollectiblesDetails', {
Move this constant to the Routes file

2022-08-23 13:29 UTC, gantunesr commented on app/components/UI/CollectibleModal/index.js
> +    navigation.navigate('TransactionsHome');
Move this constant to the Routes file

2022-08-23 13:29 UTC, gantunesr commented on app/components/UI/CollectibleModal/index.js
> +            isTransacting={!!collectibleUpdated?.transactionId}
Could to move this small logic to a method with a name that indicates the purpose?

2022-08-23 13:29 UTC, gantunesr commented on app/components/UI/Transactions/index.js
> +        message: `resetCollectibleTransactionStatusByTransactionId failed `,
Should it be?
```suggestion
        message: 'resetCollectibleTransactionStatusByTransactionId failed',
```

2022-11-08 01:03 UTC, gantunesr reviewed
I think there's room for improvement on this PR. I left some small comments, the rest LGTM in the meanwhile

2022-11-08 01:03 UTC, gantunesr approved these changes

2022-11-08 13:22 UTC, tommasini commented on app/components/Views/SendFlow/Confirm/index.js
> +      Logger.error(error, 'error while trying to send transaction (Confirm)');
It was not wise from me to do that, don't knew why I was doing that log!

2022-11-08 13:24 UTC, tommasini commented on app/util/tokens/index.ts
> +export const ERC721 = 'ERC721';
Moved!

2023-03-02 02:11 UTC, tommasini commented
Closing this PR since it's outdated

2023-03-02 02:11 UTC, closed without merging