skeleton views for region, payment method and amount to buy screens
MetaMask/metamask-mobile pull request #4152
Opened 2022-04-25 19:09 UTC by VikChawla

**Description**

Added skeleton components for region, payment method and amount to buy screens

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Progresses #???

2022-04-25 20:18 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/Region.js
> +				<ScreenLayout.Body>
It would be better if we can offload styling and Skelton elements to standalone components, so you only import a single component when content is loading! this approach will help us to avoid polluting the code.

2022-04-25 20:19 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/PaymentMethod.js
> +const SkeletonPaymentOption = () => (
offload all Skelton related components and styling into standalone component.

2022-04-25 20:23 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/AmountToBuy.js
> +				<ScreenLayout.Body>
Offload all Skelton related styling and JSX into standalone component, example would be: `SkeltonAmountToBuy.jsx`

2022-04-25 20:57 UTC, wachunei requested changes
I agree with Alaa, but don't create ad-hoc components as files, just extract and componentize the skeleton views.
Some key indicators of acceptance criteria:
- ⚠️ No extra styling should be added or removed from a View because they're using a Skeleton component
- Take advantage of props! Imagine `<SkeletonText short|medium|long|longer small|tall>`, the same for the Icon/Amount Label/Pill
- Avoid styling as "lineOne", "lineTwo", etc. These components should be used for general purpose and should just be dropped in. Random example (notice no custom layout/styling):

```jsx
<Box>
  <ListItem.Content>
      <ListItem.Icon><SkeletonIcon large /></ListItem.Icon>
      <ListItem.Body><SkeletonText tall long /></ListItem.Body>
      <ListItem.Amounts><SkeletonText short /></ListItem.Amounts>
  </ListItem.Content>
  <ListItem.Actions><SkeletonPill medium /> <SkeletonPill medium /></ListItem.Actions>
</Box>
```

2022-04-26 13:10 UTC, alaahd commented
I feel we can still create ad-hoc components to ease reusability of these components and have the lowest amount of code pollution in main views, In Atomic Design Methodology, `SkeletonIcon` `SkeletonText` `SkeletonPill` will act as **atoms** and the components I am advocating for will act as **molecules** which group different atoms to form a more complex/reusable Skelton view.

2022-04-26 13:26 UTC, wachunei commented
<img width="537" alt="Screen Shot 2022-04-26 at 08 25 21" src="https://user-images.githubusercontent.com/1024246/165310105-01790d5f-4626-4d6a-aac2-8d74621e14ff.png">

That composition of components must explicitly be declared in these "is loading" rendering section and not in other files, since they are just composed atoms without any behavior or interaction.

2022-04-26 13:34 UTC, alaahd commented
So imagine you have 20 views with the same shape or same skelton! are you going to compose 20 times ? what if that Skelton need to be changed later due to UI changes ?

2022-04-26 13:57 UTC, alaahd commented
Ok perfect!

2022-05-03 20:10 UTC, wachunei commented
Superseded by https://github.com/MetaMask/metamask-mobile/pull/4207

2022-05-03 20:10 UTC, closed without merging