Fix favourites not showing when home button is pressed in browser tab menu
MetaMask/metamask-mobile pull request #4175
Opened 2022-04-28 15:46 UTC by Fatxx

**Description**

Fix no favourites shown when "home" is pressed in the browser, scripts are now guaranteed to be present when the website is loaded.

This is blocked by https://github.com/MetaMask/dapps/pull/122 and should be tested and merged together.

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [x] Any added code is fully documented

**Issue**

Progresses #3331

2022-04-28 17:25 UTC, andrepimenta requested changes
We probably need to check if the user is on the homepage before we inject the favourites otherwise we will inject them into all websites.

2022-04-28 17:54 UTC, Fatxx commented
It should only inject on the "metamask dapps web app" since the event is triggered from there. 

Maybe not I just used the RpcMethod logic because we were already using it for other events but we can create a custom event for that.

2022-04-28 18:04 UTC, andrepimenta requested changes

2022-04-28 18:04 UTC, andrepimenta commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +			metamask_onAppMounted: async () => {
The issue would be if a malicious dapp calls this rpc method, it would get the favourites from the user

2022-04-28 18:16 UTC, andrepimenta requested changes

2022-04-28 18:16 UTC, andrepimenta commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +			metamask_onAppMounted: async () => {
If this rpc method is needed, then we should check if it's the homepage
`isHomepage()`

2022-04-29 08:39 UTC, Fatxx commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +			metamask_onAppMounted: async () => {
Done

2022-04-29 12:09 UTC, andrepimenta approved these changes
LGTM!

2022-05-12 17:29 UTC, chrisleewilcox approved these changes
iOS 15.0 Simulator = Pass
iOS 15.5 iPhone 12 = Pass
Android 10 Pixel 3 Simulator = Pass
Android 12 Samsung A42 = Pass

Browser Favorites
Tap Home button shows Favorites = Pass
New Browser Tab show Favorites = Pass
Delete Favorites = Pass

2022-05-13 10:14 UTC, merged