The app does not crash anymore when the transaction funds warning is pressed
MetaMask/metamask-mobile pull request #4178
Opened 2022-04-28 18:37 UTC by tommasini

**Description**

The app does not crash anymore when the transaction funds warning is pressed

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Progresses #4177

2022-04-28 19:28 UTC, gantunesr approved these changes
lgtm

2022-04-28 20:35 UTC, cortisiko requested changes
Some custom networks have the ability to onramp. for example BSC, Polygon, Avalanche.
With that being said if i were to be on any of those custom networks (in my case i was on polygon) & i tap the warning message I am taken the [faucet page](http://recordit.co/6aaVOnVq9g)

To reproduce:
- with an account with no funds add a custom network (for example BSC, Polygon, Avalanche.)
- go to https://metamask.github.io/test-dapp/
- connect your wallet
- tap on deploy contract, or create token
- now tap on the warning message
- notice the error

2022-04-29 16:34 UTC, tommasini commented on app/components/Views/SendFlow/Confirm/index.js
> +		const errorPress = is_test_net
Need to think more about this, and do a deeper look into the navigation stack
Please feel free to comment another idea to navigate to the faucet if it is a testnet in the send flow confirm screen

2022-04-29 16:35 UTC, tommasini commented on app/util/networks/index.js
> +	[BSC]: {
This hexChainId are wrong, they need to be fixed

2022-05-02 17:21 UTC, tommasini commented
* Replaced all the places where transaction needs to be confirmed 
* The message is according to the coin that you are trying to transact
* New coins added, BSC, Polygon, Avalanche, Celo and Fantom

https://images.zenhubusercontent.com/141427485/57f78fe9-f2e6-4858-9eee-d690f317477d/simulator_screen_recording___iphone_11_pro___2022_05_02_at_18_15_01.mp4

2022-05-11 17:32 UTC, tommasini commented on locales/languages/en.json
>  {
Done

2022-05-11 17:35 UTC, tommasini commented on app/components/Views/SendFlow/Confirm/index.js
>    gotoFaucet = () => {
Done

2022-05-11 17:41 UTC, tommasini commented on app/components/UI/TransactionReview/TransactionReviewInformation/index.js
> +    const is_test_net = isTestNet(network);
done

2022-05-11 17:46 UTC, tommasini commented on app/constants/network.js
> +export const fantom = 'fantom';
Done

2022-05-12 18:43 UTC, cortisiko approved these changes
🌮 🌮 🌮 🌮

2022-05-24 14:08 UTC, Fatxx requested changes

2022-05-24 14:08 UTC, Fatxx commented on app/util/networks/index.js
> +  if (
We can do instead `return networkName === ROPSTEN ||
    networkName === GOERLI ||
    networkName === KOVAN ||
    networkName === RINKEBY`

2022-05-26 09:13 UTC, Fatxx approved these changes
LGTM

2022-05-26 10:00 UTC, merged