adding error view component
MetaMask/metamask-mobile pull request #4246
Opened 2022-05-06 11:02 UTC by alaahd

- [x] Create ErrorView component 
- [x] Integration and handling of errors within all screens interacting with OnRamp SDK methods

**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Progresses #???

2022-05-06 16:01 UTC, wachunei requested changes
Besides the `useSDKMethod` errors there is an error handler at SDK level (not the methods) that we should also handle.

Most likely that kind of error is critical and the cta should be dismiss the flow, what do you think? 
In that case it should be the first check in the render and display the error page with CTA to dismiss.

https://github.com/MetaMask/metamask-mobile/blob/252e3967facc2312c0df45d99b3671a16c4921f9/app/components/UI/FiatOnRampAggregator/sdk/index.tsx#L89

2022-05-06 18:05 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/components/ErrorView.js
> +        </View>
Fixed

2022-05-06 18:05 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/components/ScreenLayout.tsx
> +        <Text style={[descriptionStyle, styles.description]} centered grey>
Fixed

2022-05-06 18:06 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/GetQuotes.js
> +        description={'Try to increase or reduce the amount you want to buy!'}
Fixed

2022-05-06 18:06 UTC, alaahd commented
> Besides the `useSDKMethod` errors there is an error handler at SDK level (not the methods) that we should also handle.
> 
> Most likely that kind of error is critical and the cta should be dismiss the flow, what do you think? In that case it should be the first check in the render and display the error page with CTA to dismiss.
> 
> https://github.com/MetaMask/metamask-mobile/blob/252e3967facc2312c0df45d99b3671a16c4921f9/app/components/UI/FiatOnRampAggregator/sdk/index.tsx#L89

I have added global error handling to all screens.

2022-05-06 18:09 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/AmountToBuy.js
> +      setRetryMethod(() => queryGetCountries);
No It doesn't allow you to do that! You have to set anonymous function.

2022-05-06 18:11 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/sdk/index.tsx
>        }
Revert this change and:
- Pass `sdkError` to  `ErrorViewWithReporting`: `<ErrorViewWithReporting error={sdkError} />`
- Get the error message inside `ErrorViewWithReporting` and add default:  `<ErrorView description={error?.message || "default message"} {/* other props */} /> `

In case we add reporter we need the whole Error object and not only the message.

2022-05-06 18:16 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/AmountToBuy.js
> +      setRetryMethod(() => queryGetCountries);
Interesting, so if React does not allow to store functions in the state we must not do it, we should use a callback.

```tsx
const retryMethod = useCallback(() => {
  if (!errorInAmountToBuy) {
    return null;
  }

  if (errorSdkCryptoCurrencies) {
    return queryGetCryptoCurrencies;
  } else if (errorCurrentPaymentMethod) {
    return queryGetPaymentMethod;
  } else if (errorPaymentMethods) {
    return queryGetPaymentMethods;
  } else if (errorFiatCurrencies) {
    return queryGetFiatCurrencies;
  } else if (errorDefaultFiatCurrency) {
    return queryDefaultFiatCurrency;
  } else if (errorCountries) {
    return queryGetCountries;
  }
}, [
  errorInAmountToBuy,
  errorCountries,
  errorCurrentPaymentMethod,
  errorDefaultFiatCurrency,
  errorFiatCurrencies,
  errorPaymentMethods,
  errorSdkCryptoCurrencies,
  queryDefaultFiatCurrency,
  queryGetCountries,
  queryGetCryptoCurrencies,
  queryGetFiatCurrencies,
  queryGetPaymentMethod,
  queryGetPaymentMethods,
]);
```

2022-05-06 18:17 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/AmountToBuy.js
> +      setRetryMethod(() => queryGetCountries);
Added the check for 
``` 
if(!errorInAmountToBuy) {
  setRetryMethod(null);
  return;
}
```

2022-05-06 18:34 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/sdk/index.tsx
>        }
Fixed

2022-05-06 18:35 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/components/ErrorView.js
> +            style={[styles.errorIcon]}
Fixed

2022-05-06 18:35 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/components/ErrorView.js
> +        <View style={[styles.ctaContainer]}>
Fixed

2022-05-06 19:37 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/AmountToBuy.js
> +  }, [errorInAmountToBuy]);
`errorInAmountToBuy` is redundant, we can just use the error variable.
In the useEffect you can create a variable to store the error if you think is better.
```suggestion
  const retryMethod = useCallback(() => {
    if (!error) {
      return null;
    }

    if (errorSdkCryptoCurrencies) {
      return queryGetCryptoCurrencies();
    } else if (errorCurrentPaymentMethod) {
      return queryGetPaymentMethod();
    } else if (errorPaymentMethods) {
      return queryGetPaymentMethods();
    } else if (errorFiatCurrencies) {
      return queryGetFiatCurrencies();
    } else if (errorDefaultFiatCurrency) {
      return queryDefaultFiatCurrency();
    } else if (errorCountries) {
      return queryGetCountries();
    }
  }, [
    errorCountries,
    errorCurrentPaymentMethod,
    errorDefaultFiatCurrency,
    errorFiatCurrencies,
    error,
    errorPaymentMethods,
    errorSdkCryptoCurrencies,
    queryDefaultFiatCurrency,
    queryGetCountries,
    queryGetCryptoCurrencies,
    queryGetFiatCurrencies,
    queryGetPaymentMethod,
    queryGetPaymentMethods,
  ]);

  useEffect(() => {
      setError(errorSdkCryptoCurrencies ||
      errorCurrentPaymentMethod ||
      errorPaymentMethods ||
      errorFiatCurrencies ||
      errorDefaultFiatCurrency ||
      errorCountries ?? null);
  }, [
      errorCountries,
      errorCurrentPaymentMethod,
      errorDefaultFiatCurrency,
      errorFiatCurrencies,
      errorPaymentMethods,
      errorSdkCryptoCurrencies,
  ]);
```

2022-05-09 14:39 UTC, wachunei approved these changes

2022-05-09 15:14 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/AmountToBuy.js
> +  }, [errorInAmountToBuy]);
Fixed.

2022-05-09 16:12 UTC, merged