Feature/improve dapp connection
MetaMask/metamask-mobile pull request #4286
Opened 2022-05-12 15:23 UTC by andreahaku

**Description**

Improves connection between dapps and MM mobile app

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Progresses #???

2022-05-12 17:50 UTC, andrepimenta approved these changes

2022-08-18 19:02 UTC, andrepimenta commented on app/core/SDKConnect.ts
> +    /*AsyncStorage.setItem('sdkConnections', JSON.stringify({}));
Remove this

2022-08-19 14:35 UTC, gantunesr requested changes
Left some minor comments and there are tests failing

2022-08-19 14:35 UTC, gantunesr commented on android/app/build.gradle
> +		versionName "5.5.99"
Revert before merging

2022-08-19 14:35 UTC, gantunesr commented on app/components/Views/Settings/ExperimentalSettings/index.tsx
> +            {'Clear all MetaMask SDK connections'}
Add to strings file

2022-08-19 14:35 UTC, gantunesr commented on app/components/Views/Settings/ExperimentalSettings/index.tsx
> +          <Text style={styles.title}>{'MetaMask SDK Connections'}</Text>
Add to strings file

2022-08-19 14:35 UTC, gantunesr commented on app/components/Views/Settings/ExperimentalSettings/index.tsx
> +            {'Clear MetaMask SDK connections'}
Add to strings file

2022-08-19 14:35 UTC, gantunesr commented on app/core/SDKConnect.ts
> +  if (source === 'unity') return 'unity';
A good improvement would be to add this values to a `Enum`

2022-08-19 14:35 UTC, gantunesr commented on ios/MetaMask.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 951;
Revert before merge

2022-08-19 14:35 UTC, gantunesr commented on ios/MetaMask.xcodeproj/project.pbxproj
> +				MARKETING_VERSION = 5.5.99;
Revert before merge

2022-08-19 14:35 UTC, gantunesr commented on ios/MetaMask.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 951;
Revert before merge

2022-08-19 14:35 UTC, gantunesr commented on ios/MetaMask.xcodeproj/project.pbxproj
> +				MARKETING_VERSION = 5.5.99;
Revert before merge

2022-08-19 14:35 UTC, gantunesr commented on locales/languages/en.json
> +    "clear_sdk_connections_text": "All connections will be cleared and dapps will need to request connection again"
dapps, Dapps, or dApps? 🤔

2022-08-19 14:59 UTC, sethkfman commented on app/components/UI/ApproveTransactionReview/index.js
> +          ? 'MetaMask-SDK-Remote-Conn'
Should these be stored as constants?

2022-08-22 14:44 UTC, sethkfman commented on app/components/Views/Settings/ExperimentalSettings/index.tsx
> +    await AsyncStorage.setItem('sdkConnections', JSON.stringify({}));
Should be converted to constants

2022-08-22 14:44 UTC, sethkfman commented on app/components/Views/Settings/ExperimentalSettings/index.tsx
> +    await AsyncStorage.setItem('sdkApprovedHosts', JSON.stringify({}));
Should be converted to constants

2022-08-22 14:54 UTC, sethkfman commented on app/core/SDKConnect.ts
> +        }, 20000);
Consider making this a constant that describe the reason for the timeout

2022-08-22 15:34 UTC, sethkfman approved these changes
LGTM

2023-06-21 15:32 UTC, closed without merging