Transaction of Matic submitted in polygon network goes to the activity view
MetaMask/metamask-mobile pull request #4329
Opened 2022-05-16 13:22 UTC by tommasini

**Description**

When the transaction is submitted on the polygon network, it appears in the activity view, we can now cancel or speed up that transaction.

Feature: Be able to see all the submitted activities in the activity view to be possible to cancel them or speed up.
 Scenario: User does a transaction
  GIVEN any user does a transaction
  WHEN the activity view is empty or not
  THEN must appear the transaction submitted and be possible cancel it or speed up

Demo:
 Uploading Simulator Screen Recording - iPhone 11 Pro - 2022-05-16 at 14.11.03.mp4…

Test cases:
- Go to settings -> Advanced
- Press reset account (to have no transaction on activity view)
- Go to polygon network
- transfer 0.001 matic
- go to activity view and verify if it's there
(Did the same for rinkeby network)

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Screenshots/Recordings**

_If applicable, add screenshots or recordings to visualize the changes_

**Issue**

Progresses #3820

2022-06-23 19:31 UTC, gantunesr requested changes
Let's remove all the changes caused by tabs/spaces

2022-06-23 19:31 UTC, gantunesr commented on app/components/Views/TransactionsView/index.js
> +  const network = Engine.context.NetworkController.state.network;
Use hook `useSelector`

2022-06-24 18:59 UTC, gantunesr approved these changes
LGTM

2022-06-24 19:09 UTC, tommasini commented on app/components/Views/TransactionsView/index.js
> +  const network = Engine.context.NetworkController.state.network;
Implemented in this [commit](https://github.com/MetaMask/metamask-mobile/pull/4329/commits/23a62176a133ff274e8cc7f249625bea6c1ef394)

2022-07-06 21:56 UTC, chrisleewilcox commented
LGTM!

2022-07-06 21:57 UTC, chrisleewilcox approved these changes
LGTM

2022-07-26 16:19 UTC, merged