Proper error handling for no crypto currencies available on certain region
MetaMask/metamask-mobile pull request #4360
Opened 2022-05-17 18:15 UTC by alaahd

**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Screenshots/Recordings**

_If applicable, add screenshots or recordings to visualize the changes_

**Issue**

Progresses #???

2022-05-17 19:31 UTC, rickycodes commented on app/components/UI/FiatOnRampAggregator/Views/AmountToBuy.tsx
> +    }
```suggestion
    setIsFetching(isFetchingData)
```

2022-05-17 19:31 UTC, rickycodes commented on app/components/UI/FiatOnRampAggregator/Views/AmountToBuy.tsx
> +            }}
```suggestion
            ctaOnPress={toggleRegionModal}
```

2022-05-17 19:59 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/AmountToBuy.tsx
> +            }}
If I do this change typescript will complain "Type 'Function' is not assignable to type '() => void'" I have changed it to 
```suggestion
            ctaOnPress={() => toggleRegionModal()}
```

2022-05-17 20:00 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/AmountToBuy.tsx
> +    }
Fixed

2022-05-17 20:13 UTC, Cal-L approved these changes
LGTM

2022-05-18 07:59 UTC, alaahd commented
I have pushed on more commit for improvement suggested by @wachunei appreciate if we can review again.

2022-05-18 13:35 UTC, wachunei requested changes

2022-05-18 13:35 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/Views/AmountToBuy.tsx
> +  const [isFetching, setIsFetching] = useState(true);
We probably don't need this new state since we can directly derive it from the others. Please revert (along with the useEffect) and make sure error screen does not show up early.

2022-05-18 13:35 UTC, wachunei commented on app/components/UI/FiatOnRampAggregator/components/ErrorView.tsx
> +  ctaOnPress?: () => void; // The optional callback to be invoked when pressing the CTA button (Optional)
Revert this change, onPress could be `any` return

2022-05-18 14:48 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/AmountToBuy.tsx
> +  const [isFetching, setIsFetching] = useState(true);
Fixed

2022-05-18 14:49 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/Views/AmountToBuy.tsx
> +            ctaOnPress={() => toggleRegionModal()}
Fixed

2022-05-18 14:49 UTC, alaahd commented on app/components/UI/FiatOnRampAggregator/components/ErrorView.tsx
> +  ctaOnPress?: () => void; // The optional callback to be invoked when pressing the CTA button (Optional)
Reverted

2022-05-18 20:08 UTC, wachunei approved these changes

2022-05-19 18:31 UTC, wachunei approved these changes

2022-05-23 22:04 UTC, merged