[5.2.0][FIX] M3 - Warning on legit address
MetaMask/metamask-mobile pull request #4376
Opened 2022-05-20 16:49 UTC by tommasini

**Description**
The warning of invalid address was showing before the address was verified but if it was on the address book was already verified.

**Proposed solution**
 Now the address that is on the address book will not be verified again, that way we will not have the delay of verifying the address again.

**Code Impact**
Low, the code will only affect how the SendTo screen works, it's the first screen of the send flow.

**Test Cases**
Case 1:
* In wallet view, press the send button
* In the Address to complete with (in mainnet):
  * ENS name
  * address
  * address from the address book
  * recents
  * from user accounts
* Press next and insert one amount
* In rinkeby network completed the transaction when the address was from
  *  insert normal address
  *  recent 
  *  address from the address book
Case 2:
 * Complete with an unknown address
 * Add the address to the Address book
Case 3:
 * Select the address from the address book
 * Clear address 
Case 4:
 * Select unkown address from recents (will appear the warning because needs to be verified)
 * Clear address
Case 5:
 * Write an unkown address  (will appear the warning because needs to be verified)
 * Clear address
Case 6:
* Write an ens name  (will appear the warning because needs to be verified)
* Clear ens name
Case 7:
* Scan address with QR code
* Clear address
* Scan again and do a transaction

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Screenshots/Recordings**
Solution without the orange warning:
https://recordit.co/FCljUjFoxQ

**Issue**

Progresses #https://github.com/MetaMask/mobile-planning/issues/278

2022-05-23 05:28 UTC, gantunesr requested changes

2022-05-23 05:28 UTC, gantunesr commented on app/components/Views/SendFlow/SendTo/index.js
> +   * @param {*} toSelectedAddress - Represents the value of what user writes on toAddress input
Is `toSelectedAddress` a `string`? Add the correct data type.

```suggestion
   * @param {String} toSelectedAddress - Represents the value of what user writes on toAddress input
```

2022-05-23 05:28 UTC, gantunesr commented on app/components/Views/SendFlow/SendTo/index.js
> +   * @returns
What's this method returning? `string | null`?

2022-05-23 05:28 UTC, gantunesr commented on app/components/Views/SendFlow/SendTo/index.js
> +    const checksummedToSelectedAddress = toChecksumAddress(toSelectedAddress);
Improve variable name
```suggestion
    const checksummedAddress = toChecksumAddress(toSelectedAddress);
```

2022-05-23 05:28 UTC, gantunesr commented on app/components/Views/SendFlow/SendTo/index.js
> +    return null;
I see there's some unnecessary validations in this method. For example, if `networkAddressBook[checksummedToSelectedAddress]` is falsy, you're going to evaluate it again in

```js
networkAddressBook[checksummedToSelectedAddress] && 
  networkAddressBook[checksummedToSelectedAddress].name) ||
```

Which is unnecessary since you already know that the value will be falsy. I recommend using a ternary operator to handle this logic in a more effective way. I think it would be something like this,

```js
return networkAddressBook[checksummedToSelectedAddress] ?
  networkAddressBook[checksummedToSelectedAddress].name :
  identities[checksummedToSelectedAddress] ?
    identities[checksummedToSelectedAddress].name :
    null
```

2022-05-23 05:28 UTC, gantunesr commented on app/components/Views/SendFlow/SendTo/index.js
> +     */
Are you a 100% sure of this statement?

2022-05-23 12:54 UTC, tommasini commented on app/components/Views/SendFlow/SendTo/index.js
> +    const checksummedToSelectedAddress = toChecksumAddress(toSelectedAddress);
Thank you, much better!

2022-05-23 16:26 UTC, gantunesr reviewed
Some minor nits

2022-05-23 16:26 UTC, gantunesr commented on app/components/Views/SendFlow/SendTo/index.js
>          // If not in address book nor user accounts
```suggestion
        // If not in the addressBook nor user accounts
```

2022-05-23 16:26 UTC, gantunesr commented on app/components/Views/SendFlow/SendTo/index.js
> +       * we are setting the state here synchronously, so it does not block the UI
```suggestion
       * Because validateAddressOrENSFromInput is an asynchronous function
       * we are setting the state here synchronously, so it does not block the UI
```

2022-05-23 21:39 UTC, merged

2022-05-24 18:48 UTC, plasmacorral commented
https://github.com/MetaMask/mobile-planning/issues/278#issuecomment-1136134528