[FIX] Add margin and check to AssetActionButton text
MetaMask/metamask-mobile pull request #4381
Opened 2022-05-23 06:22 UTC by gantunesr

**Description**

The `AssetActionButton` component wasn't handling long string. This PR add a margin and a 10 character max check to the component to avoid UI issues

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Screenshots/Recordings**

| BUG | FIX |
|-----|-----|
| ![Bug](https://user-images.githubusercontent.com/17601467/169755943-60ab86ba-24cc-4655-bfc5-f671f78cb787.png) | ![Fix](https://user-images.githubusercontent.com/17601467/169755890-8bb2383a-09ae-4d13-86fb-35ea624e0291.png) |

**Issue**

Progresses #???

2022-05-23 15:54 UTC, Fatxx reviewed
Shouldn't this be pointing to `release/5.2`?

2022-05-23 15:54 UTC, Fatxx commented on app/components/UI/AssetActionButton/index.js
> +          ? `${label[(0, maxStringLength - 3)]}...`
Didn't you want to `.substring()` the value instead?

2022-05-23 21:30 UTC, gantunesr commented
@Fatxx I need this in main for another development, I'll cherry pick it to the release branch

2022-05-23 21:33 UTC, gantunesr commented on app/components/UI/AssetActionButton/index.js
> +          ? `${label[(0, maxStringLength - 3)]}...`
Updated in [4b934bd](https://github.com/MetaMask/metamask-mobile/pull/4381/commits/4b934bdcbdda600f7cc06bb2c5d7b0619d95cf4c)

2022-05-23 22:29 UTC, Fatxx reviewed
LGTM

2022-05-23 22:29 UTC, Fatxx approved these changes

2022-05-24 07:56 UTC, Fatxx requested changes

2022-05-24 07:56 UTC, Fatxx commented on app/components/UI/AssetActionButton/__snapshots__/index.test.tsx.snap
> +    receive receive
Didn't seem to work, uhm?

2022-05-24 07:56 UTC, Fatxx commented on app/components/UI/AssetActionButton/index.js
> +        {label.size > maxStringLength
It's `label.length` instead I suppose

2022-05-24 12:14 UTC, gantunesr commented on app/components/UI/AssetActionButton/__snapshots__/index.test.tsx.snap
> +    receive receive
[95f3990](https://github.com/MetaMask/metamask-mobile/pull/4381/commits/95f399064be7804d9a725c97f265079659213763)

2022-05-24 12:15 UTC, Fatxx approved these changes

2022-05-24 22:44 UTC, chrisleewilcox approved these changes
LGTM!

2022-05-24 23:21 UTC, merged