Fixed ERC20 token transfer from Dapps
MetaMask/metamask-mobile pull request #4404
Opened 2022-05-25 22:48 UTC by tommasini

**Description**
The issue was that was not possible to do a erc20 transfer from a dapp without specify the gas price.

**Proposed Solution**
When the Modal mount, if it's not given from dapp any gas price, we estimate with the method estimateGas of TransactionController.

**Code Impact**
Low, will just impact the transaction modal of dapp transfers.

**Test Cases**
Case1:
* Clone test-dapp from metamask github 
* Open test-dapp with your editor
* Follow the read me instructions to run the dapp in localhost
* Remove line 576 to 578 of src/index.js
* Open metamask mobile app
* Browse http://localhost:9011/
* Press Create token
* Press Transfer tokens without gas 
* Modal will open and everything will be okay (no warning with "Invalid value" )

**Screenshots/Recordings**
| Bug | Solution |
|-----|-----|
| ![Bug](https://user-images.githubusercontent.com/46944231/170381733-c151264a-92df-4311-9ca8-bb98364d91eb.jpeg) | ![Solution](https://user-images.githubusercontent.com/46944231/170381889-e531f71e-08d1-4a26-96d2-2526838a74eb.png) |

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Issue**

Progresses #3999

2022-07-04 14:48 UTC, andreahaku approved these changes
small suggestion to have a more concise code. Up to you if you want to use it or not :) The rest LGTM ;)

2022-07-04 14:48 UTC, andreahaku commented on app/components/UI/TransactionEditor/index.js
> +    if (!hasGasPrice && !hasGasLimit) {
Probably you can do the same thing in a more compact way:
```
const transactionObject = {
  ...(!hasGasPrice && { gasPrice: hexToBN(gasPrice) }),
  ...(!(!hasGasPrice && hasGasLimit) && { gas: hexToBN(gas) }),
};

this.props.setTransactionObject(transactionObject);
```

2022-07-04 18:09 UTC, tommasini commented on app/components/UI/TransactionEditor/index.js
> +    if (!hasGasPrice && !hasGasLimit) {
Yeah true, thank you so much!! 
I believe this will cover all possibilities
1- when don't have gasPrice
2- when don't have gasLimit
3- when don't have both

`const transactionObject = {
  ...(!hasGasPrice && { gasPrice: hexToBN(gasPrice) }),
  ...(!hasGasLimit && { gas: hexToBN(gas) }),
};

this.props.setTransactionObject(transactionObject);`

Do you agree?

2022-07-05 11:06 UTC, andreahaku commented on app/components/UI/TransactionEditor/index.js
> +    if (!hasGasPrice && !hasGasLimit) {
Initially I went this way and I agree with you. But that was not respecting the original set of if statements, that's why I've added the additional condition (`!(!hasGasPrice && hasGasLimit)`). But if your logic is correct than go for it as it makes totally sense. Probably the original if statements where not fully correct.

2022-07-11 17:52 UTC, andrepimenta approved these changes
LGTM!

2022-07-13 16:21 UTC, andreahaku approved these changes
LGTM

2022-09-05 02:20 UTC, gantunesr requested changes
I'm aware that this PR is under 'QA in progress', and in that sense, my comments shouldn't affect the overall logic of this code.

It would be good to,
- Have some basic unit testing around the file `app/util/dappTransactions.ts`
- Add return types to each method to make it easier to read and to make it more predictable

2022-09-06 13:48 UTC, gantunesr approved these changes
Looks better. Thanks for doing some refactor and adding tests

2022-09-06 13:48 UTC, gantunesr commented on app/util/dappTransactions/index.ts
> +};
This method should always return a `boolean` and if it returns `false` you can set the proper error message.

2022-09-16 19:49 UTC, cwagner22 commented
Any estimated time when this will be merged? Thanks.

2022-09-22 23:01 UTC, cortisiko requested changes
@tommasini Sending this back your way! See below.


**Issue 1**

When I attempt to buy drip tokens I get` [TypeError: setTransactionObject is not a function. (In 'setTransactionObject(transactionObject)', 'setTransactionObject' is undefined)]`

see recording: http://recordit.co/Bl8uT35wnf 

To reproduce:
make sure you are on BSC
go to drip.community
connect your wallet
attempt to buy some DRIP
notice the error


**Potential Issue 2**
This might be out of the scope of this ticket but when I try using WalletConnect eth_SendTransaction function while on Polygon network I get `Transaction error internal JSON-RPC error`

see recording: https://recordit.co/8dtg5zENVJ

2022-09-23 22:15 UTC, cortisiko commented
We are getting there @tommasini ! Your fix for issue 1 looks good. I did however uncover another bug. A regression bug with [gasless transactions](https://github.com/MetaMask/metamask-mobile/pull/3756). Basically, whenever I try to submit a gasless transaction, I get: [TypeError: undefined is not an object (evaluating 'inputBn.toString')] See screen capture [here](https://www.screencast.com/t/QBAZxCYgy)

2022-09-26 18:38 UTC, cortisiko approved these changes
I tested the various dapp transactions listed in the PR as well as:

Keystone transactions
Swap Native to ERC-20 and vise versa 
I tested gasless transactions
Regular send transactions
Speeding up and cancelling transactions


I verified the transaction data that we display is what I see on chain. 

With that being said, this PR is QA passed @tommasini  🌮 🌮 🌮

2022-09-26 18:41 UTC, merged