Add browser cookies support on Android
MetaMask/metamask-mobile pull request #4407
Opened 2022-05-26 11:17 UTC by Fatxx

**Description**

At the moment users are not able to use cookies on Android since the HTTP client (OkHttp) is [rejecting cookies by default](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-cookie-jar/), this PR implements an interface that saves and loads cookies accordingly.

This PR also fixes clearing cookies on iOS and improves the "Clear Cookies" section structure.

**Test Cases**

Case 1 (Android):
 - Access a website that has cookies or session cookies (please @ me, I can provide a test website)
 - You should be able to access those cookies

Cases 2 (iOS):
 - Access a website that has cookies or login into one that has session cookies (please @ me, I can provide a test website)
 - Go to Settings -> Security & Privacy -> Clear Browser Cookies
 - Clear cookies button should be disabled
 - Navigate to the browser you should have no cookies

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Screenshots/Recordings**

_If applicable, add screenshots or recordings to visualize the changes_

**Issue**

Progresses #4245

2022-05-26 12:41 UTC, gantunesr requested changes
Some nits in the js part of the PR. @sethkfman can provide a better review on the Java part

2022-05-26 12:41 UTC, gantunesr commented on app/components/Views/Settings/SecuritySettings/Sections/ClearCookiesSection.tsx
> +      if (Platform.OS === 'android') {
Use the `Device` module from `utils`

2022-05-26 12:41 UTC, gantunesr commented on app/components/Views/Settings/SecuritySettings/Sections/ClearCookiesSection.tsx
> +      if (Platform.OS === 'ios') {
Same here. Use the `Device` module from `utils`

2022-05-26 12:41 UTC, gantunesr commented on app/components/Views/Settings/SecuritySettings/Sections/ClearCookiesSection.tsx
> +    if (Platform.OS === 'ios') {
Same here. Use the `Device` module from `utils`

2022-05-26 12:41 UTC, gantunesr commented on app/components/Views/Settings/SecuritySettings/Sections/ClearCookiesSection.tsx
> +      <View style={styles.setting} testID={'clear-cookies-section'}>
Lets move this constant to the `test-ids` file

2022-05-26 12:41 UTC, gantunesr commented on app/components/Views/Settings/SecuritySettings/index.js
> +          <ClearCookiesSection />
Nice

2022-05-26 15:46 UTC, gantunesr commented
The `priority` and `severity` labels should be used in issues and not PRs

2022-06-14 17:25 UTC, tommasini commented on patches/react-native-webview+11.13.0.patch
> ++  private static final boolean USES_LEGACY_STORE = Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP;
Check if legacy support is needed

2022-06-14 17:25 UTC, tommasini commented on patches/react-native-webview+11.13.0.patch
> ++  public CustomCookieJar (WebView webView) {
Should move logic to the outside of web view file

2022-06-14 17:25 UTC, tommasini commented on app/components/Views/Settings/SecuritySettings/Sections/ClearCookiesSection.tsx
> +        // CookieManager.getAll() is not supported on Android
Remove the comment

2022-06-14 22:15 UTC, sethkfman commented
Reviewed during meeting. Once the comments are addressed the PR looks good.

2022-06-16 14:37 UTC, chrisleewilcox commented
Please resolve conversations, changes and conflicts.  Once resolved please removed `needs-dev-review` label.

2022-07-05 16:52 UTC, Fatxx commented
Add as draft in favour of merging https://github.com/MetaMask/metamask-mobile/pull/3905

2022-07-07 18:01 UTC, gantunesr approved these changes
LGTM

2022-07-07 21:41 UTC, cortisiko commented
@Fatxx A couple of things:

1.
 I am using the URL mentioned in [this](https://github.com/MetaMask/metamask-mobile/issues/4245#issuecomment-1125049113) comment to test and I can still reproduce the issue. that is, I switch to polygon  > open https://matic.art/  > tap connect > connect my wallet > I am taken back to the dapp home screen and my wallet is still not connected.
see here: http://recordit.co/nxXZBUUsqc

2.
this link doesn't work: https://notareal.club/shop 
I am taken to a blank page. 

3.

I am unable to log into a WordPress site

2022-08-03 23:48 UTC, cortisiko requested changes
@Fatxx sending this back your way:


**Issue 1**
I am experiencing a crash on android when I try to sign in using Github on [[gitcoin.co](http://gitcoin.co/)](http://gitcoin.co/)
As soon as I tap on sign up the app crashes. I tried to view the logs but i didn’t find anything useful. Unfortunately, I can’t continuously reproduce because of Recaptcha. Can you try to reproduce on your end as well?
**The device used**: xaomi redmi note 8 running android 11
See recording [here](http://recordit.co/wQdTgyibMu )

**Issue 2**
I am having an issue logging into [[wordpress.org](http://wordpress.org/)](http://wordpress.org/) on android. Everything works as expected on ios

to see screen recording view our slack chat [here](https://consensys.slack.com/archives/C035KHUJLHG/p1659397318187869?thread_ts=1659397284.705659&cid=C035KHUJLHG)

**Issue 3**
On any android device, I can’t add items to my cart when I go to this woocomerce website:  https://porterandyork.com/product-category/buy-beef-online/
see [android](http://recordit.co/3qEotCy7oO)
it works on [ios](http://recordit.co/NckwugI15G)

2022-08-23 02:36 UTC, cortisiko commented
@Fatxx The issues I reported [here](https://github.com/MetaMask/metamask-mobile/pull/4407#pullrequestreview-1061122450) were fixed…. BUT I noticed you merged 3905 into your PR. This prompted me to test the sites listed in this issue: https://github.com/MetaMask/metamask-mobile/issues/3857

My findings are both Android-specific:

**1/**
Using this WebSocket website: https://www.hawku.com/ 
I am unable to get to the connect wallet view. I am stuck on the Recaptcha page. It seems as if the page keeps on refreshing even though I completed the Recaptcha. 

see here: http://recordit.co/qdztA4bc1Z 

**2/**
Using this WebSocket website: https://fly.io/launch/livebook

 I am prompted with an oops something went wrong view after signing up making the browser feel a bit unstable. 

See here: http://recordit.co/Rm28GuxA4I

2022-08-23 14:32 UTC, cortisiko approved these changes
@Fatxx This guy is QA passed 🌮 🌮 🌮 

Outside of the scenarios listed in the ticket description I also tested the following:

- https://github.com/MetaMask/metamask-mobile/issues/1931

- https://github.com/MetaMask/metamask-mobile/issues/1956


- Ensure that you can interact with https://matic.art/

- With https://porterandyork.com/product-category/buy-beef-online/ or any other woo-commerce you can:
        Add items to your cart
        log in/create an account 
       And get to the check-out page

- You should be able to log into WordPress 
- You can go to http://gitcoin.co/ and proceed to log in/sign up with GitHub

2022-08-23 14:33 UTC, merged