[IMPROVEMENT] Address Verification
MetaMask/metamask-mobile pull request #4418
Opened 2022-05-30 05:04 UTC by gantunesr

**Description**

Improve address verification in SendFlow,

1. Allow user to input an address with all lower or upper case characters.
2. If the user inputs a mixed case address, it should be the correct checksum.  Else, the address should be flagged as invalid and not auto-checksum the address.
  - Example of incorrect checksum: `0x87187657b35f461d0ceEc338d9B8e944A193afe2`
  - Example of correct checksum: `0x87187657b35F461D0Ceec338d9b8E944a193aFE2`

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

**Screenshots/Recordings**

| Bug | Fix |
|-------|-------------|
|![](https://user-images.githubusercontent.com/17601467/170919712-87e9f850-fa40-49e8-863c-fa1a199b76c0.png)|![](https://user-images.githubusercontent.com/17601467/170919674-2271054c-cb10-46fa-91d3-859894809d77.png)|

**Issue**

Progresses https://github.com/MetaMask/mobile-planning/issues/288

2022-05-31 12:25 UTC, Fatxx requested changes
Should we also add the same validation in `Views/Send/index.js` screen?

2022-06-01 02:27 UTC, gantunesr commented
@Fatxx I don't see any validation logic in `Views/Send/index.js` and we should stop using it in favor of `SendFlow`

2022-06-01 17:11 UTC, Fatxx approved these changes

2022-06-09 21:37 UTC, cortisiko approved these changes
I tested these Incorrect check sum addressed:

`0xa54D3c09E34aC96807c1CC397404bF2B98DC4eFb`
`0x87187657b35f461d0ceEc338d9B8e944A193afe2`

on the send flow and also on the add contact view. I also generated QR codes for the above addresses and tested with them. See QR codes [here](https://www.screencast.com/t/cdvWwa9f8) and [here](https://www.screencast.com/t/dxjZXdVNsoa8). I tested upper cased addresses and lower cased addresses. 


I tested scanning a keystone address QR code and I was able to successfully send to that address. 


Finally I did sanity checks on:
scanning a request QR code. The correct address received the funds
Scanning an extension QR code for a couple of my accounts. I had no issues 

QA passed! 🌮 🌮

2022-06-09 21:55 UTC, merged