backup vault
MetaMask/metamask-mobile pull request #4421
Opened 2022-05-30 16:30 UTC by owencraston

**Description**

_Write a short description of the changes included in this pull request._

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Screenshots/Recordings**

_If applicable, add screenshots or recordings to visualize the changes_

**Issue**

Progresses #???

2022-05-30 18:30 UTC, owencraston commented on app/store/index.js
> +const TIMEOUT = 1;
This is for testing purposes

2022-12-20 23:26 UTC, sethkfman commented on app/components/Views/Login/index.js
> +        } else {
Any thoughts on how to remove these repeated setState? Maybe return before the catch and remove the final else but keep the setState.

2022-12-20 23:26 UTC, sethkfman commented on app/components/Views/RestoreWallet/WalletRestored.tsx
> +  const backupSRPURL =
Move to URL constants

2022-12-20 23:26 UTC, sethkfman commented on app/core/backupVault.ts
> +export const backupVault = async (keyringState: KeyringState) => {
Can you add comments to each of these functions? It would be good to understand how they relate the keychain integration

2022-12-20 23:26 UTC, sethkfman commented on app/store/index.js
> +    // throw new Error('Failed async storage storage fetch.');
Remove if not needed

2022-12-20 23:31 UTC, owencraston commented on app/components/Views/RestoreWallet/WalletRestored.tsx
> +  const backupSRPURL =
This is temporary. I am still working with @jakehaugen on the intended behaviour. He wants to navigate to the BackupSRP page which is only possible if we have a successful login.

2022-12-21 12:21 UTC, gantunesr commented on app/components/Views/RestoreWallet/WalletResetNeeded.tsx
> +      );
Remove before merge

2022-12-21 12:21 UTC, gantunesr commented on app/components/Views/RestoreWallet/WalletResetNeeded.tsx
> +      );
Remove before merge

2022-12-21 12:21 UTC, gantunesr commented on app/components/Views/RestoreWallet/WalletResetNeeded.tsx
> +      setCreateNewWalletLoading(false);
Can you explain the situation here, I want to understand better the problem that you're pointing out in the comments

2022-12-21 12:21 UTC, gantunesr commented on app/components/Views/Login/index.js
> +    console.log('vault/ vault error thrown: ', error);
Remove before merge

2022-12-21 12:21 UTC, gantunesr commented on app/components/Views/Login/index.js
> +          );
Why is it necessary to get the mnemonic here?

2022-12-21 12:51 UTC, gantunesr commented on app/components/Views/Login/index.js
> +          );
Would the method `KeyringController.validatePassword` also work here? That way you can validate the password without the need to decrypt the mnemonic

2022-12-21 21:40 UTC, owencraston commented on app/components/Views/Login/index.js
> +        } else {
we could create a passwordCheck function and abstract it in there?

2022-12-21 21:59 UTC, owencraston commented on app/components/Views/RestoreWallet/WalletResetNeeded.tsx
> +      setCreateNewWalletLoading(false);
We are still deciding what the best options are here and if we should have more than these two options...maybe a try again button? see [discussion on slack](https://consensys.slack.com/archives/C03BAF1DXCL/p1671567198279629) for more context.

2022-12-21 22:01 UTC, owencraston commented on app/components/Views/Login/index.js
> +          );
we could maybe use this in place of the parsedVault function call here. The only snag is that will be using the old KeyringController that is corrupt since the engine has not been reiniatliazed yet. The benefit of parseVaultValue is that it lets us pass in our backup as a param so we can validate the backup.

2022-12-21 22:03 UTC, owencraston commented on app/components/Views/Login/index.js
> +          );
the reason we are calling `componentAuthenticationType` ( and why I don't think we can replace it with `KeyringController.validatePassword`) is because its possible for a user to change their auth type before they enter the vault corruption flow. `componentAuthenticationType` will return to us what the desired auth type is based on priority and the given state values and then we can persist it in the call to storePassword below.

2023-01-31 23:46 UTC, owencraston commented on app/components/Views/RestoreWallet/WalletRestored.tsx
> +  const backupSRPURL =
After some investigation I realized it is impossible to navigate to the backup flow from here since the user is logged out. I think there is value in having some call to action here. Is there a better resource that I can link to? cc @sethkfman @gantunesr @AlexJupiter

2023-01-31 23:46 UTC, owencraston commented on app/components/Views/RestoreWallet/WalletRestored.tsx
> +  const backupSRPURL =
also should we have an analytics event for this?

2023-01-31 23:47 UTC, owencraston commented on app/components/Views/RestoreWallet/WalletResetNeeded.tsx
> +      MetaMetricsEvents.VAULT_CORRUPTION_WALLET_RESET_NEEDED_TRY_AGAIN_BUTTON_PRESSED,
@gantunesr should we add some way to determine if the user is going back to the restore screen from the try again button? that way we can tell if this try again button does anything at all. If so do you have suggestions on how to implement this?

2023-02-01 21:34 UTC, gantunesr reviewed
Left a lot of minor comments, the logic made sense according to previous discussion about this solution. Some observations,

- The file `app/core/backupVault.ts` is not tested, this is not a blocker for this PR and lets open a ticket to address it during this Q
- Feel free to add more comments explaining the logic and reasoning behind some methods, in a year from here other devs might wonder why it was necessary

2023-02-01 21:34 UTC, gantunesr commented on app/components/Views/RestoreWallet/WalletResetNeeded.tsx
> +      MetaMetricsEvents.VAULT_CORRUPTION_WALLET_RESET_NEEDED_TRY_AGAIN_BUTTON_PRESSED,
I think with this events it should be enough, from the logic I can see that the user will navigate to the `VAULT_RECOVERY.RESTORE_WALLET`, and for this case you can also take a particular user and see an event pattern of this type,

```
Vault Corruption Wallet Reset Needed Try Again Button Pressed
Vault Corruption Restore Wallet Screen Viewed
Vault Corruption Restore Wallet Button Pressed
```

From that you can tell that the user previously pressed `Try Again` and ended up in the Restore View (multiple times if you see this pattern repeated). But if you want to improve it, I think the solution would be to persist an flag, set it to true when `Try Again` is pressed for the first time, and then use it as an argument in the event `Vault Corruption Restore Wallet Screen Viewed`. An alternative would be a counter for the times `Try Again` is pressed.

2023-02-01 21:34 UTC, gantunesr commented on app/components/Views/RestoreWallet/WalletRestored.tsx
> +import StyledButton from '../../UI/StyledButton';
Same here,

> _Any reason on using StyledButton over the DS Button?_

2023-02-01 21:34 UTC, gantunesr commented on app/components/Views/RestoreWallet/WalletRestored.tsx
> +  const finishWalletRestore = useCallback(async () => {
nit
```suggestion
  const finishWalletRestore = useCallback(async (): Promise<void> => {
```

2023-02-01 21:34 UTC, gantunesr commented on app/components/Views/RestoreWallet/WalletRestored.tsx
> +  const backupSRPURL =
I think you can use the `SRP_GUIDE_URL` in the `constants/urls.ts` file. And I don't think an event here will add value.

2023-02-01 21:34 UTC, gantunesr commented on app/components/Views/RestoreWallet/WalletRestored.tsx
> +  const onPressBackupSRP = useCallback(async () => {
nit
```suggestion
  const onPressBackupSRP = useCallback(async (): void => {
```

2023-02-01 21:34 UTC, gantunesr commented on app/components/Views/RestoreWallet/WalletRestored.tsx
> +  const handleOnNext = useCallback(async () => {
nit
```suggestion
  const handleOnNext = useCallback(async (): void => {
```

2023-02-01 21:34 UTC, gantunesr commented on app/core/EngineService.ts
> +const NO_VAULT_IN_BACKUP_ERROR = 'No vault in backup';
Move to error constants file (`constants/error.ts`)

2023-02-01 21:34 UTC, gantunesr commented on app/core/EngineService.ts
> +   */
Specify the return object in the commentary

2023-02-01 21:34 UTC, gantunesr commented on app/core/EngineService.ts
> +   */
For example,

```ts
  /**
   * METHOD DESCRIPTION
   *
   * @returns RETURN OBJECT DESCRIPTION
   */
```

2023-02-01 21:34 UTC, gantunesr commented on app/core/backupVault.ts
> +
Add proper commentary to describe the methods in this file

2023-02-01 21:34 UTC, gantunesr commented on app/core/backupVault.ts
> +export const resetVaultBackup = async () => {
nit
```suggestion
export const resetVaultBackup = async (): Promise<void> => {
```

2023-02-01 21:34 UTC, gantunesr commented on app/core/backupVault.ts
> +    Logger.log(VAULT_BACKUP_KEY, 'Vault successfully backed up');
We could remove this log since we're expecting this to be the happy path

2023-02-01 21:34 UTC, gantunesr commented on app/core/backupVault.ts
> +  Logger.log(VAULT_BACKUP_KEY, 'getVaultFromBackup');
We can also remove this one and add it before the last return to indicate that there was an error

2023-02-01 21:34 UTC, gantunesr commented on app/core/backupVault.ts
> +  Logger.log(VAULT_BACKUP_KEY, 'resetting vault backup');
We can also remove this one too

2023-02-01 23:56 UTC, owencraston commented on app/components/Views/RestoreWallet/RestoreWallet.tsx
> +import StyledButton from '../../UI/StyledButton';
The reason for this is that the DS Button (ButtonPrimary) does not take children or support a loading state. It can only render a label which comes in as string. The styled button allows me to conditionally render a loading indicator.

2023-02-02 22:47 UTC, owencraston commented on app/components/Views/RestoreWallet/WalletRestored.tsx
> +import StyledButton from '../../UI/StyledButton';
ds does not support loading state. More into in the above comments.

2023-02-27 12:47 UTC, gantunesr requested changes
An observation,

- I'm pointing out again that `app/core/backupVault.ts` has is un-tested, that's also the case for the `EngineService`. Maybe I missed this in the previous PR, but if you're going to modify this core files, it's always a good practice to add testing.

2023-02-27 12:47 UTC, gantunesr commented on app/components/Views/Login/index.js
> +            await Authentication.storePassword(
Break out this nested try-catch

2023-02-27 12:47 UTC, gantunesr commented on app/constants/error.ts
> +//backupVault
nit

```suggestion
// backupVault
```

2023-02-27 12:47 UTC, gantunesr commented on app/core/backupVault.ts
> + */
The return type is already specified in the code, you can just explain what it's returning on simple terms

2023-02-27 12:47 UTC, gantunesr commented on app/core/backupVault.ts
> +    vault?: string;
Same here,

> _The return type is already specified in the code, you can just explain what it's returning on simple terms_

2023-02-27 12:47 UTC, gantunesr commented on app/core/backupVault.ts
> + * @returns Promise<Void>
No need here since you're not returning a value inside the `Promise`

```suggestion
```

2023-02-27 12:47 UTC, gantunesr commented on app/core/EngineService.ts
> +      }
Same here,

> _The return type is already specified in the code, you can just explain what it's returning on simple terms_

2023-02-28 00:07 UTC, owencraston commented on app/core/backupVault.ts
> + */
I noticed that when I removed the interface the intenseness was not as descriptive which is why I added it. 

**With** the interface commented
<img width="669" alt="Screenshot 2023-02-27 at 4 05 45 PM" src="https://user-images.githubusercontent.com/22918444/221717626-dd41c0ca-5987-4577-9d69-622497fabdff.png">

**Without** the interface commented
<img width="651" alt="Screenshot 2023-02-27 at 4 04 05 PM" src="https://user-images.githubusercontent.com/22918444/221717379-69f7781b-ac6e-4d82-9c64-95b0f763a915.png">

2023-02-28 06:35 UTC, owencraston commented on app/core/EngineService.ts
> +      }
By adding this description we get better inline code documentation. This is from the file that is calling this method and we can see the exact response object.
<img width="753" alt="Screenshot 2023-02-27 at 10 33 24 PM" src="https://user-images.githubusercontent.com/22918444/221773175-06510110-223d-45e8-833a-443955d275f5.png">

2023-02-28 23:52 UTC, owencraston commented
@gantunesr I gave it a very good try on the unit testing but  I was unable to make any progress. I documented the need for testing in [this issue ](https://github.com/MetaMask/metamask-extension/issues/17938)as well as some of the issues I encountered. I hope that we can move this into QA without doing the tests today and that we can come back to this in the future.

2023-03-01 00:14 UTC, gantunesr requested changes
LGTM. I'm flagging this PR as `request changes` for the piece of UI used to develop and test.

2023-03-01 00:48 UTC, owencraston commented on app/components/Views/Login/index.js
> +      } else if (containsErrorMessage(error, VAULT_ERROR)) {
I modified this from a strict equal to contains for two reasons...
1. Since the [Authentication Refactor](https://github.com/MetaMask/metamask-mobile/pull/5374) was merged our errors have become more nested. This shouldn't be a problem since I made sure to throw the original errors in the Authentication class but this adds an extra layer of protection in case things change within the Authentication logic in the future.
2. In order to help future proof this catch in the case that the authentication logic becomes more nested than it already is. A strict equal would fail if the error message was `'Error: Error: Cannot unlock without a previous vault.'` but this contains function would not. This extra error message is happens all the time when functions eagerly throw an error from another method.

2023-03-01 22:29 UTC, owencraston commented on app/components/Views/Login/index.js
> -        const vaultCorruptionError = new Error('Vault Corruption Error');
Moved this log into the `handleVaultCorruption` function.

2023-03-01 22:30 UTC, owencraston commented on app/components/Views/Login/index.js
> +        } catch (e) {
We also want to log the error and display the vault corruption error in the case that the our `handleVaultCorruption` has an uncaught error.

2023-03-01 22:32 UTC, owencraston commented on app/components/Views/Login/index.js
> +  NEVER_MERGE_tempBreakTheVault = async () => {
this needs to be deleted before merging, this method is exactly the same as the onLogin function with the exception that it makes a call to `await Authentication.NEVER_MERGE_BROKEN_userEntryAuth();` which eagerly throws an error. This is because the vault corruption error will come from the auth class so to best simulate how this recovery flow will work in prod I opted for this test method.

2023-03-01 22:33 UTC, owencraston commented on app/components/Views/Login/index.js
> +      } else if (containsErrorMessage(error, VAULT_ERROR)) {
This block needs to match 1/1 the catch block in onLogin before we merge.

2023-03-01 22:33 UTC, owencraston commented on app/core/Authentication/Authentication.ts
> +  NEVER_MERGE_BROKEN_userEntryAuth = async (): Promise<void> => {
Needs to be removed before merging

2023-03-01 22:34 UTC, owencraston commented on app/core/Authentication/AuthenticationError.ts
> +  constructor(message: string, customErrorMessage: string, authData: AuthData) {
This is small and isn't 100% needed however in order to match the properties that exist in the standard Error class I changed this to `message`

2023-03-06 20:46 UTC, olenapankina requested changes
**Tested on**
iPhone Xr iOS 16.1.1
Samsung Galaxy M21 Android 12, One UI Core version 4.1

**Issue_01:** User can swipe through vault recovery screens
- Restore needed-> Continue to wallet [4421_Issue_01_success flow.mov](https://user-images.githubusercontent.com/116747263/223225372-73843ed6-df58-4213-8ec6-31e7c1df89c5.mov)
- Restore needed-> New wallet needed [4421_Issue_01_failed flow.mp4](https://user-images.githubusercontent.com/116747263/223225544-cc88f7c1-375a-4668-8b9e-fc3db37cd606.mp4)

iOS - use gestures. Android - use native back button
**Expected result:** user should not be able to navigate between vault recovery screens. Android: user should not be able to navigate to the lock page using back button from vault recovery flow

**Issue_02:** password field is not cleared after restoring wallet
**Steps to reproduce:**
1. Set up password as auth
2. Force quit and relaunch the application
3. Enter password - click dev button
4. Finish success flow, enter the wallet
5. Put application in the background, wait for auto-lock time to pass (tested with 30s and immediate lock)
6. Open MetaMask
7. Observe password present in password entry field
8. Tap login button

**Actual result:** password present is password entry field, user is able to login with it [4421_Issue_02.mov](https://user-images.githubusercontent.com/116747263/223225687-195ff794-d91d-4546-b0d8-ae68eef8c9e2.mov)
**Expected result:** password should not be present in password entry after user successfully logged in
**Not able to reproduce on:** prod, auth refactor builds, after ordinary flow without vault recovery on vault recovery builds

**Issue_03:** User ends up on Lock page after tapping on 'Create a new wallet' at 'New wallet needed' screen
**Steps to reproduce:**
1. Launch the app
2. Enter vault recovery failed flow
3. At 'New wallet needed' screen tap at 'Create a new wallet' button
4. Tap 'Cancel' or observe screen in the background

**Actual result:** user ends up on Lock screen [4421_Issue_03.mp4](https://user-images.githubusercontent.com/116747263/223225821-f0d7f096-36a4-45ad-8dbf-82af997c7fb7.mp4)
**Expected result:** TBD, but I would expect user to stay in 'New wallet needed' screen

**Issue_04:** Android: New wallet needed flow: lock screen flashes in the background [4421_Issue_04.mov](https://user-images.githubusercontent.com/116747263/223225888-c146b3c0-eb92-43dc-a37f-a6a3b1e11e1c.mov)

2023-03-07 16:58 UTC, owencraston commented on app/components/Views/Login/index.js
> +      } else if (containsErrorMessage(error, VAULT_ERROR)) {
Before I c lean this up it matched 100%
<img width="1208" alt="Screenshot 2023-03-07 at 8 56 24 AM" src="https://user-images.githubusercontent.com/22918444/223493852-2f4f09ef-80a3-484b-8ae2-c57e18eca266.png">

2023-03-07 18:55 UTC, owencraston commented on app/component-library/components/Icons/Icon/Icon.types.ts
> +  // TODO finalize Icon size in Design system
I did this based on @brianacnguyen instructions.

2023-03-08 19:39 UTC, gantunesr approved these changes
LGTM

2023-03-08 19:39 UTC, gantunesr commented on app/components/Views/Login/index.js
> +const VAULT_ERROR = 'Cannot unlock without a previous vault.';
A note for the future,

We should import this error from the KeyringController. Having the hardcoded string can create a new bug

2023-03-10 17:38 UTC, olenapankina commented
**Issue_05**: Translations for vault recovery screens are not presented.

2023-03-10 17:57 UTC, owencraston commented
I pulled in the available translations from [here](https://github.com/MetaMask/metamask-mobile/pull/4262/files)

2023-03-13 18:37 UTC, olenapankina approved these changes
**Tested on** 
iPhone Xr iOS 16.1.1
Samsung Galaxy M21 Android 12, One UI Core version 4.1
commit e2713133

Issue 01-05 confirmed fixed.

[4421_Android_successful backup.mov](https://user-images.githubusercontent.com/116747263/224792936-55f12eee-3db5-4d1d-84bf-3aa7b7362aad.mov)
[4421_iOS_successful backup.mp4](https://user-images.githubusercontent.com/116747263/224793153-8a18b136-145e-4de4-a7d2-1801f519f4db.mp4)
[4421_Android_failed backup.mov](https://user-images.githubusercontent.com/116747263/224793379-55cd0556-8d76-43d3-9d07-cad00bab0537.mov)
[4421_iOS_failed backup.mp4](https://user-images.githubusercontent.com/116747263/224793460-1b936530-4487-42a6-801a-991627868e4a.mp4)

QA Passed :white_check_mark:

2023-03-13 18:48 UTC, owencraston commented on app/components/Views/Login/index.js
> +  NEVER_MERGE_tempBreakTheVault = async () => {
deleted

2023-03-13 19:33 UTC, merged