[5.5] Keystone: fix 2 bugs
MetaMask/metamask-mobile pull request #4430
Opened 2022-06-01 09:02 UTC by soralit

**Description**

This PR fixed 2 bugs with Keystone:
1. keystone accounts will disappear when reset password.
2. keystone accounts page will increase 1 when scanning wrong wallet sync qrcode.

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

**Screenshots/Recordings**

_If applicable, add screenshots or recordings to visualize the changes_

**Issue**

Progresses https://github.com/MetaMask/qr-hardware-wallets/issues/7
Progresses https://github.com/MetaMask/qr-hardware-wallets/issues/6

2022-06-02 08:48 UTC, gantunesr reviewed
Thanks @soralit! I'm leaving some questions for the moment

2022-06-02 08:48 UTC, gantunesr commented on app/components/Views/ConnectQRHardware/index.tsx
> +    [hideScanner, KeyringController],
Having the KeyringController in the dependency array provides any improve on the render cycles and/or performance?

2022-07-05 17:28 UTC, cortisiko requested changes
@soralit I am unable to log in after a password change. Basically, when I attempt to change my password with **_biometrics log-in disabled_** I get an error “invalid password”. 

To reproduce:

import your wallet
go to the privacy and security page
tap on the “change password” button
 enter your current password to proceed
now you should be taken to the create password screen
enter a new password
before creating the new password toggle off “log in with biometrics”
proceed and create that new password
After the password change was successful 
kill the app
relaunch the app
login with your new password. Notice the error



I reproduced without binding my keystone device: http://recordit.co/jt2b4IjCxm

And after I bind my keystone device: http://recordit.co/iKkwuYgxpP

2022-07-28 14:26 UTC, AlexJupiter commented
Hey @soralit any update on this at all? :)

2022-09-20 19:56 UTC, gantunesr approved these changes
LGTM

2022-09-20 20:04 UTC, cortisiko approved these changes
This PR is 🌮 🌮

2022-09-20 20:12 UTC, merged