Account nickname will never be empty
MetaMask/metamask-mobile pull request #4684
Opened 2022-07-18 17:55 UTC by tommasini

**Description**
The issue is that when the nickname of the account would be empty, it would be non editable.

**Proposed Solution**
The proposed solution it is, when the name it's empty we will assume that the name of the account will be the last name of it.
Example: 
If it was "Account 2" after confirm the empty string on the account name, it will come back to be "Account 2"

**Code Impact**
Low

**Test Cases**
Case1:
* Notice the account nickname
* Long press the account nickname
* Edit the name to an empty string
* Will came back to the last account nickname

**Screenshots/Recordings**

https://user-images.githubusercontent.com/46944231/179572818-7b5589f9-b820-48a9-bc10-692f2213229b.mp4

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #4308 

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-07-18 18:02 UTC, jakehaugen commented
Looks great to me!

2022-07-21 10:05 UTC, gantunesr reviewed
LGTM. Good work, just a small comment

2022-07-21 10:05 UTC, gantunesr commented on app/components/UI/AccountOverview/index.js
> +    }
I think the code is self-explanatory, you can remove the comment

2022-07-21 10:13 UTC, tommasini commented on app/components/UI/AccountOverview/index.js
> +    }
Okok! Doing it

2022-08-11 12:11 UTC, gantunesr approved these changes

2022-08-11 16:44 UTC, cortisiko requested changes
@tommasini I found a fun edge case:

If I were to:
- long press to edit my account nickname
- remove the current name
- tap on the space bar to set ' ' as my account nickname
- upon doing so, I still experience the bug where I am unable to edit my account nickname after setting it to ' '

see [recording](http://recordit.co/2Ngj9SyMVH)

2022-08-11 19:11 UTC, tommasini commented
@cortisiko Really well catched, I was not considering the blank spaces!! Thank you Curtis! Awesome!!!

@gantunesr Could you give me another review please?

2022-08-12 02:04 UTC, gantunesr approved these changes

2022-08-12 15:14 UTC, cortisiko approved these changes
🌮 🌮 looks good @tommasini

2022-08-12 15:14 UTC, merged