Component/4226 bottom sheet
MetaMask/metamask-mobile pull request #4718
Opened 2022-07-21 20:25 UTC by Cal-L

**Description**

#4226 
<img width="601" alt="image" src="https://user-images.githubusercontent.com/10508597/180308673-37f53787-a83a-4434-be31-b07b587d0cf1.png">

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-08-01 23:43 UTC, brianacnguyen requested changes
Left quite a few comments

2022-08-01 23:43 UTC, brianacnguyen commented on app/component-library/components/BottomSheet/BottomSheet.tsx
> +      onActive: (event, ctx) => {
should these calculation logic be extracted into a util function to be reused in the future for similar gestures?

2022-08-01 23:43 UTC, brianacnguyen commented on app/component-library/components/BottomSheet/BottomSheet.tsx
> +
should we add a show?

2022-08-05 17:56 UTC, Cal-L commented on app/component-library/components/BottomSheet/BottomSheet.tsx
> +      onActive: (event, ctx) => {
May abstract if logic is needed in other components. For example Modal

2022-08-05 17:57 UTC, brianacnguyen approved these changes

2022-08-05 19:02 UTC, owencraston approved these changes
This code is so clean it cleansed my soul 👏  🧼

2022-08-05 19:52 UTC, merged