Add entry point in mobile app to labs dapp
MetaMask/metamask-mobile pull request #4808
Opened 2022-08-04 23:08 UTC by meppsilon

**Description**

This PR is about adding the entry point button that will link users to the Metalabs dapp in the Metamask Mobile browser.

There were a couple important decisions that I made:

I placed the button in both the Tokens tab and the CollectibleContracts tab. Initially, the button is supposed to sit below the list of tabs in the Wallet component and above the content within the tabs but I couldn't find a way to fit a UI element between the tabs list and the tabs content so I ended up placing the button in both of the components for the tab contents. That would allow it to show up for both tabs but it creates a weird behavior for the user because as they click through the tabs, all of the contents within the tabs will change but the entry buttons will remain the same, even though they slide in and out and they are technically different buttons.
I hardcoded metalabs.consensys.net as an approvedHost. The functionality we want is for the user to click the link and for the browser to open up on the metalabs page with the selected address already approved. This is the same functionality that we will be receiving from the extension. The solution of hardcoding the metalabs url as an approved host allowed for the accounts rpc requests from the metalabs dapp to automatically go through successfully. I considered another solution where I would check separately if the hostname was the same as the metalabs dapp url but I thought that solution was even more hardcoded than the previous and I didn't want to introduce more logic for approving an eth_accounts request that could possibly add confusing and overhead in the future. So I chose to add on top of the existing logic instead.

**Screenshots/Recordings**

https://www.figma.com/file/gi92L28Nr4PdUaLsTRhmkK/User-Flows---Master?node-id=106%3A14700

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-08-05 16:40 UTC, gantunesr reviewed
Hi @meppsilon, the PR looks good, I left some small comments. Can you add a recording of the feature for our QA team in the PR description? Thanks!

2022-08-05 16:40 UTC, gantunesr commented on .js.env.example
> +export METALABS_URL="https://metalabs.consensys.net"
We need to add this variable to our CI/CD workflow

2022-08-05 16:40 UTC, gantunesr commented on locales/languages/en.json
> +    "goToPortfolio": "Go to portfolio",
```suggestion
    "go_to_portfolio": "Go to portfolio",
```

2022-08-05 16:40 UTC, gantunesr commented on app/components/UI/CollectibleContracts/index.js
> +            {strings('wallet.goToPortfolio')}
```suggestion
            {strings('wallet.go_to_portfolio')}
```

2022-08-05 16:40 UTC, gantunesr commented on app/components/UI/Tokens/index.js
> +              {strings('wallet.goToPortfolio')}
```suggestion
              {strings('wallet. go_to_portfolio')}
```

2022-08-05 16:40 UTC, gantunesr commented on app/components/UI/CollectibleContracts/index.js
> +      color: colors.blue,
I think it's better to use the colors of our DS to make this feature Dark Mode compatible

2022-08-05 16:40 UTC, gantunesr commented on app/components/UI/Tokens/index.js
> +      textAlign: 'center',
Same

> I think it's better to use the colors of our DS to make this feature Dark Mode compatible

2022-08-08 22:07 UTC, meppsilon commented on app/components/UI/CollectibleContracts/index.js
> +      color: colors.blue,
how do I use the colors from the DS?

2022-08-08 22:46 UTC, meppsilon commented on .js.env.example
> +export METALABS_URL="https://metalabs.consensys.net"
Let me know if you'd like me to set this up.

2022-08-09 16:09 UTC, gantunesr reviewed
LGTM. I'll send this to our QA team

2022-08-09 18:29 UTC, meppsilon commented
@gantunesr One more thing, there is some push back on the designs of this feature so I might need to make some minor updates to the UI before we can merge. Functionality will remain the same.

2022-08-11 23:26 UTC, cortisiko requested changes
hey @meppsilon ! A couple of things I noticed:


- I noticed when I tap on the portfolio link on the wallet view, the browser page [opens to the metamask homepage and nothing else](http://recordit.co/vPPO3G5EIE). Yes, I did add the `METALABS_URL` to my js.env file. 


- While on the tokens tab, [there is a missing translation for the link text ](https://www.screencast.com/t/gqXCXWAH9N )


- When I try to access the portfolio dapp while on the NFT’s tab I get: `TypeError: undefined is not an object (evaluating '_this.props.navigation')` See [recording](http://recordit.co/RB3iEPLm0i)

2022-10-04 20:22 UTC, sethkfman commented
@meppsilon Do you know the status of this ticket?

2022-10-06 01:53 UTC, meppsilon commented
@sethkfman It still under design review. I'm going to go ahead and close this PR for now because I think it is going to take some time before we release this feature.

2022-10-06 01:53 UTC, closed without merging