Sent transaction icon changes incorrectly when the language changes
MetaMask/metamask-mobile pull request #4832
Opened 2022-08-10 15:31 UTC by tommasini

**Description**
The issue was when we change language the icon of a transaction was not consistent, a sent icon was changed for one swipe icon.

**Proposed Solution**
Comparing the action key with lower case and the translation with lower case to have consistent results.
 [Technical] - When we compare we lower the case of the strings, because the string.include() is case sensitive.

**Screenshots/Recordings**
https://recordit.co/eQPcABRTaA

**Issue**
https://github.com/MetaMask/metamask-mobile/issues/4814
Progresses #4184 

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-08-11 15:58 UTC, blackdevelopa commented on app/components/UI/TransactionElement/utils.js
> +  if (actionKeyLowerCase === strings('transactions.approve').toLowerCase())
Can we have `transactions.approve` in lowercase instead?

2022-08-11 18:38 UTC, blackdevelopa submitted a review, later dismissed

2022-08-11 22:02 UTC, cortisiko requested changes
@tommasini it seems the issue still persists. I was able to reproduce by:

- heading to BSC
- performing a swap
- then I sent some BEP-20 tokens
- upon doing so, I viewed the transactions activity and notice the swaps logo is next to the send transaction

See transaction activity [here](https://www.screencast.com/t/rlsGYvwr0)
asset overview [here](https://www.screencast.com/t/Hw48DYiOhe)

2023-07-06 09:53 UTC, tommasini commented
I'm closing this PR since it's too old

2023-07-06 09:53 UTC, closed without merging