Change skip to payment method in on-ramp flow
MetaMask/metamask-mobile pull request #4860
Opened 2022-08-15 17:04 UTC by wachunei

**Description**

This screen changes the behavior of skipping screen after the Fiat On Ramp flow has started. 
- Previous behavior was to skip directly to Amount to Buy screen
- New behavior is to skip to Payment Methods screen.

**Screenshots/Recordings**
Before:

https://user-images.githubusercontent.com/1024246/184681297-9efb9b9a-4da0-4475-be62-8cd596104350.mp4

After: 

https://user-images.githubusercontent.com/1024246/184681314-465609c9-8f33-43e9-b07d-3f338b4599f6.mp4

2022-08-17 15:22 UTC, alaahd requested changes
LGTM, left a small comment!

2022-08-17 15:22 UTC, alaahd commented on app/constants/navigation/Routes.ts
>      AMOUNT_TO_BUY_HAS_STARTED: 'AmountToBuyHasStarted',
Since we are updating the entry point for returning users, do we need to drop `AMOUNT_TO_BUY_HAS_STARTED` if it not being used any where?

2022-08-17 15:26 UTC, wachunei commented on app/constants/navigation/Routes.ts
>      AMOUNT_TO_BUY_HAS_STARTED: 'AmountToBuyHasStarted',
Yes, I'll remove it

2022-08-17 15:27 UTC, wachunei commented on app/constants/navigation/Routes.ts
>      AMOUNT_TO_BUY_HAS_STARTED: 'AmountToBuyHasStarted',
Addressed in e91039fb7

2022-08-17 17:33 UTC, alaahd approved these changes

2022-08-23 14:42 UTC, gantunesr approved these changes

2022-08-23 15:33 UTC, merged