Refactor ApproveTransaction Component
MetaMask/metamask-mobile pull request #4868
Opened 2022-08-16 13:51 UTC by blackdevelopa

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-09-13 23:03 UTC, sethkfman commented on app/components/UI/TransactionReview/TransactionReviewEIP1559Update/index.tsx
> +    onlyGas: !!onlyGas,
Is there a risk this could be undefined?

2022-09-13 23:04 UTC, sethkfman commented on app/components/Views/ApproveView/Approve/index.js
> +import EditGasFee1559Update from '../../../UI/EditGasFee1559Update';
Lets make sure to reset the value after the EditGasFee1559 refactor is complete

2022-09-13 23:06 UTC, sethkfman commented on app/components/Views/ApproveView/Approve/index.js
>      LegacyGasData: {},
Are these objects needed? I would think the GasPolling util would be providing these as well.

2022-09-26 15:20 UTC, blackdevelopa commented on app/components/Views/ApproveView/Approve/index.js
>      LegacyGasData: {},
Yes. That's why it's removed

2022-09-26 15:21 UTC, blackdevelopa commented on app/components/UI/TransactionReview/TransactionReviewEIP1559Update/index.tsx
> +    onlyGas: !!onlyGas,
Some transaction type (Send flow) uses `onlyGas: undefined`

2022-09-27 14:43 UTC, sethkfman commented on app/components/UI/TransactionReview/TransactionReviewEIP1559Update/index.tsx
> +    onlyGas: !!onlyGas,
This is a way to make it more explicit to use gas provided or not

2022-09-27 14:44 UTC, sethkfman approved these changes
LGTM

2022-10-15 00:08 UTC, chrisleewilcox commented
Goerli, Fuji, Mumbai testnets all look good.  I am having issues testing this with BNB testnet.  Getting JSON-RPC error....
https://recordit.co/zn0ab4MQ4Y

2022-10-17 16:06 UTC, chrisleewilcox requested changes
Goerli, Fuji, Mumbai testnets all look good.  I am having issues testing this with BNB testnet.  Getting JSON-RPC error....
https://recordit.co/zn0ab4MQ4Y

2022-10-25 08:45 UTC, blackdevelopa commented
> Goerli, Fuji, Mumbai testnets all look good. I am having issues testing this with BNB testnet. Getting JSON-RPC error.... https://recordit.co/zn0ab4MQ4Y

Hey Chris, thanks for this. Updated now

2022-10-27 20:08 UTC, chrisleewilcox approved these changes

2022-10-27 20:23 UTC, merged