New Crowdin translations by Github Action
MetaMask/metamask-mobile pull request #4881
Opened 2022-08-17 19:49 UTC by sethkfman

**Description**

Working PR for translations and UX bugs related to new translations

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-08-17 19:51 UTC, sethkfman commented
@sethkfman @rickycodes 

Using Filipino as my default language:


- [The password strength text is too long](https://www.screencast.com/t/l6YLDdv6p5)

- When I go through the onramps flow the translated “cancel” button [is misaligned](https://www.screencast.com/t/rWFmkt36Ol ) 
 
- Same as above: [when I am on the select payment page](https://www.screencast.com/t/DJ6afqgo)


- [Add networks view is misaligned](https://www.screencast.com/t/Wg6raJgipwaY)


- [misalignment issue on the security and privacy page](https://www.screencast.com/t/Dv9jHBidGw)


- [Skip tutorial is misaligned](https://www.screencast.com/t/PET5F4yo0)


- [The Add funds button is misaligned ](https://www.screencast.com/t/lZRrXf9p)


### The issues below was tested on a iPhone SE and Filipino as my default language:

- [The text on the onramps view runs off the screen](https://www.screencast.com/t/Rb9YYTLZ). 
 
- [The “Done” CTA on the  wallet import success screen is misaligned](http://recordit.co/k5HCLIMFmS)

to reproduce:
import your wallet
notice the wallet success view appears

- [The text in the advanced options on the transactions modal is misaligned](https://www.screencast.com/t/Yetlf08b7uFe) 


- [the close button in the “what are gas fees” modal needs padding](https://www.screencast.com/t/TKF1nFqp94E)

2022-09-08 15:00 UTC, Fatxx commented
![](https://files.slack.com/files-pri/T02P98BKE-F041HEG1PUM/screen_shot_2022-09-08_at_15.59.10.png)

2022-09-09 15:54 UTC, Fatxx commented
@sethkfman @cortisiko This is ready for review, I don't think we're using the modal from this point [the close button in the “what are gas fees” modal needs padding](https://www.screencast.com/t/TKF1nFqp94E) anymore. Please tell me if I'm wrong.

2022-09-09 19:58 UTC, sethkfman commented on app/components/UI/NavbarTitle/index.js
> +          <Text numberOfLines={1} style={styles.realTitle}>
I may be missing something but I don't see this style.

2022-09-09 19:59 UTC, sethkfman reviewed
Minor comment

2022-09-15 22:42 UTC, sethkfman commented
I opened the PR so I can't approve. I have reviewed @Fatxx updates and he can approve.

2022-09-16 21:45 UTC, cortisiko requested changes
@Fatxx found a couple more issues:


> - [ ] [The password strength text is too long](https://www.screencast.com/t/l6YLDdv6p5)

still exists: https://www.screencast.com/t/8ELS4W1n3 

[Furthermore, on a bigger screen device (see image on the right. It was a pixel 3XL)](https://www.screencast.com/t/LFmw3b0ViCEx) The password strength text is not visible. It appears to be running off the screen 

---

> - [ ] When I go through the onramps flow the translated “cancel” button [is misaligned](https://www.screencast.com/t/rWFmkt36Ol)

 the cancel button appears to be misaligned. [The misalignment is prominent on bigger screen devices (device on the right in the screenshot)](https://www.screencast.com/t/btGi0ZFabX9) 

---
> - [x] [The Add funds button is misaligned](https://www.screencast.com/t/lZRrXf9p)

On the pixel 3XL [The receive button needs a little more padding](https://www.screencast.com/t/UcWFRLnGUxi)

2022-12-26 19:56 UTC, tommasini commented
> [The password strength text is too long](https://www.screencast.com/t/l6YLDdv6p5)

Fixed:
https://recordit.co/swMb44v0U2

> When I go through the onramps flow the translated “cancel” button is misaligned

<img width="250" alt="image" src="https://user-images.githubusercontent.com/46944231/209578370-871a57c3-43f0-43bf-9c69-a6f0a15a7381.png">

> The Add funds button is misaligned

<img width="250" alt="image" src="https://user-images.githubusercontent.com/46944231/209578694-e2f46b7e-465f-4072-9d04-2df9e6dfba21.png">

2023-01-10 20:47 UTC, owencraston commented on package.json
> +    "react-native-size-matters": "^0.4.0",
Nitpick. we should probably pin the specific version of the package we are using so that everyone gets the exact same version. therefore it would be `"react-native-size-matters": "0.4.0",`

2023-01-10 20:48 UTC, owencraston approved these changes
I didn't run the app but the code looks good. Great job for finally pushing this over the edge!

2023-01-14 00:24 UTC, cortisiko approved these changes
@tommasini good stuff, this is 🌮 🌮

2023-01-14 00:25 UTC, merged