Fix/4876 missing token detection event properties
MetaMask/metamask-mobile pull request #4882
Opened 2022-08-17 23:00 UTC by Cal-L

**Description**

#4876

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-08-17 23:02 UTC, Cal-L commented on bitrise.yml
> +          VERSION_NAME: 5.5.2
Revert version number before merging

2022-08-17 23:02 UTC, Cal-L commented on bitrise.yml
> +          VERSION_NUMBER: 949
Revert build number before merging

2022-08-23 14:39 UTC, gantunesr requested changes
LGTM. But it required to revert the version and build number before merge

2022-08-23 14:39 UTC, gantunesr commented on android/app/build.gradle
> +		versionName "5.5.2"
Revert before merge

2022-08-23 14:39 UTC, gantunesr commented on app/util/analyticsV2.js
> +        ) {
Are you sure this is not breaking any other event?

2022-08-23 21:07 UTC, Cal-L commented on app/util/analyticsV2.js
> +        ) {
Yep. We don't have any events where we're sending a list format, so this logic wouldn't apply to any post change analytics events. However, this was added to support list format for mix panel.

2022-08-23 21:10 UTC, gantunesr approved these changes

2022-08-23 22:01 UTC, merged