Implement warning for deprecated test networks, kovan, ropsten and rinkeby
MetaMask/metamask-mobile pull request #4885
Opened 2022-08-18 17:40 UTC by tommasini

**Description**
Kovan, Ropsten and Rinkeby are 3 test networks that will be deprecated soon with the merge of ethereum.

**Proposed Solution**
A warning with the information when the user change for one of this three networks.

**Screenshots/Recordings**
https://recordit.co/WeoxoIWOoo

**Issue**

Progresses #4697 

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-08-18 18:04 UTC, bschorchit commented
This looks great! Thank you, @tommasini

2022-08-18 20:50 UTC, sethkfman commented on app/components/Nav/App/index.js
> +        <View style={styles.alertContainer}>
What do you think about moving this out to a separate component?

2022-08-18 20:51 UTC, sethkfman commented on app/components/Nav/App/index.js
> +      'https://blog.ethereum.org/2022/06/21/testnet-deprecation/',
Suggest adding this to the constants/url.js

2022-08-23 15:08 UTC, sethkfman approved these changes
LGTM

2022-08-23 15:14 UTC, cortisiko requested changes
@tommasini found a couple 🐛 

In dark mode: there is a dark artifact in the warning alert https://www.screencast.com/t/42EScJP1ofhd 

In light mode: I cannot read the text in the warning alert:
https://www.screencast.com/t/VuL2JAB0A


Usability issue:
If I create a new wallet and I switch to a deprecated test net I see two warning alerts: The protect your wallet and network deprecation. Which one takes precedence? https://www.screencast.com/t/hbGAhZHyRS

Furthermore, If I were to open the burger menu I am unable to see the menu options to scroll through: http://recordit.co/ot71GMZndf

2022-08-23 22:01 UTC, cortisiko approved these changes
🌮 🌮 🌮

2022-08-24 13:19 UTC, merged

2022-08-25 19:22 UTC, omnat commented
Is this shown just once per user or everytime they switch to one of the 3 networks @tommasini ?

2022-08-25 19:37 UTC, tommasini commented
The behaviour is:
 * Everytime they switch the network to one of the three the warning will prompt
 * If they close the alert it will only appear when they kill the app and re open it