[ENHANCEMENT] SRP Reveal Timestamp
MetaMask/metamask-mobile pull request #4997
Opened 2022-09-15 14:17 UTC by gantunesr

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards]()
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_

To help our CS team to provide a better assistance to our user it's useful to have a log of the timestamp when a SRP was revealed.

_2. What is the improvement/solution?_

Update the state logs of the app to store an array of the timestamps the user SRP was revealed

**Screenshots/Recordings**

In the following string there's a example of a part of the logs an user should be able to download and see their SRP reveal timestamps.

```
"privacy":{"privacyMode":true,"thirdPartyApiMode":true,"revealSRPTimestamps":["Wed Sep 14 2022 18:10:46 GMT-0300 (-03)","Wed Sep 14 2022 18:10:58 GMT-0300 (-03)"],"approvedHosts":{}}
```

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-09-15 14:51 UTC, owencraston commented on app/components/Views/Settings/AdvancedSettings/index.js
> -      Engine.context.KeyringController.state.keyrings;
why did you delete this?

2022-09-15 14:59 UTC, gantunesr commented on app/components/Views/Settings/AdvancedSettings/index.js
> -      Engine.context.KeyringController.state.keyrings;
I didn't, its in an utils file now

2022-09-15 15:08 UTC, owencraston commented on app/util/logs/index.ts
> +  delete fullState.engine.backgroundState.AssetsContractController;
never mind I see that you moved the deletes into here.

2022-09-15 15:10 UTC, owencraston commented on app/util/logs/index.ts
> +  return JSON.stringify(newState);
why not just pass in the a timestamp into this object through a plane old JavaScript Date.getTime()?

2022-09-15 15:51 UTC, owencraston approved these changes
After talking on slack we discussed some of the choices here and I am all for it. 🏁

2022-09-16 19:43 UTC, cortisiko requested changes
I am unable to download state logs on android. See [here](http://recordit.co/6eiB6EDwet) vs [main](http://recordit.co/lV1hQYxRnt)

I receive `{"error": "bad base-64"}`

2022-09-21 01:51 UTC, cortisiko approved these changes
@gantunesr Fix looks good. I tested on a samsung, Google pixel and a xaomi ✅ 


Testing:
This PR is binary. Either it works or doesn't. i.e. after you reveal your SRP > download the state logs > the reveal SRP timestamp object has data in it or it does not have the data in.

2022-09-21 01:51 UTC, merged