E2E Appium - Initial setup, onboarding and import seed flow
MetaMask/metamask-mobile pull request #5108
Opened 2022-10-06 13:11 UTC by Fatxx

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

Implement new Appium, WebDriver.io and Cucumber e2e testing solution.
Adds initial test for "Create onboarding wizard flow"
Adds "Import wallet flow"

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-10-09 21:28 UTC, cortisiko requested changes
Hey @Fatxx I left some  feedback comments, lmk if you have any questions!

2022-10-09 21:28 UTC, cortisiko commented on wdio/features/screen-objects/WalletSetupScreen.js
> +class WalletSetupScreen {
> You should define your locator-id/test-id as a getter function then you perform the assertion on the element.

```
get walletScreenTitle() {
    return $(`~${WALLET_SETUP_SCREEN_TITLE_ID}`);
}

get walletScreenDescriptionText() {
    return $(`~${WALLET_SETUP_SCREEN_DESCRIPTION_ID}`);
}

  get importWalletButton() {
    return $(`~${WALLET_SETUP_SCREEN_IMPORT_FROM_SEED_BUTTON_ID}`);
  }

 get createWalletButton() {
    return $(`~${WALLET_SETUP_CREATE_NEW_WALLET_BUTTON_ID}`);
  }


async verifyScreenTitle(){
await expect(this.walletScreenTitle).toBeDisplayed();
}


async verifyImportWalletButton(){
await expect(this.importWalletButton).toBeDisplayed();

}

async verifyCreateNewWalletButton(){
await expect(this.createWalletButton).toBeDisplayed();

}


```

2022-10-09 21:28 UTC, cortisiko commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +  async typeSecretRecoveryPhrase(phrase) {
Same. re: utilizing gesture methods in the gestures.js file. it should be

```suggestion
 async typeSecretRecoveryPhrase(phrase) {
    await Gestures.typeText(IMPORT_FROM_SEED_SCREEN_SEED_PHRASE_INPUT_ID, phrase);
  }

```

2022-10-09 21:28 UTC, cortisiko commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +  async typeNewPassword(newPassword) {
Same. re: utilizing gesture methods in the gestures.js file. it should be

```suggestion
 async enterPassword(newPassword)  {
    await Gestures.typeText(IMPORT_FROM_SEED_SCREEN_NEW_PASSWORD_INPUT_ID, newPassword);
  }

```

2022-10-09 21:28 UTC, cortisiko commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +  async typeConfirmPassword(confirmPassword) {
Same. re: utilizing gesture methods in the gestures.js file. it should be

```suggestion
 async reEnterPassword(confirmPassword)  {
    await Gestures.typeText(IMPORT_FROM_SEED_SCREEN_CONFIRM_PASSWORD_INPUT_ID, confirmPassword);
  }

```

2022-10-09 21:28 UTC, cortisiko commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +  async typeConfirmPassword(confirmPassword) {
For some reason on android, the keyboard remains expanded so you would need to collapse the keyboard. Tapping on any element outside the input box should work.

2022-10-10 13:47 UTC, Fatxx commented on wdio/features/screen-objects/OptinMetricsScreen.js
> +    const elem = await $(`~${OPTIN_METRICS_I_AGREE_BUTTON_ID}`)
Here I'm waiting for the button to disappear, not to appear before click

2022-10-10 13:51 UTC, Fatxx commented on wdio/features/screen-objects/WalletMainScreen.js
> +class WalletMainScreen {
This is the actual Wallet Main Screen after you complete the onboarding

2022-10-11 18:58 UTC, closed without merging