Sqashed commits and a few amendments
MetaMask/metamask-mobile pull request #5124
Opened 2022-10-14 21:28 UTC by Andepande

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

As part of our migration from Detox to appium, This small PR will merge into e2e-appium/import-wallet-and-create-wallet

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

2022-10-14 22:00 UTC, chrisleewilcox requested changes

2022-10-14 22:00 UTC, chrisleewilcox commented on wdio/features/newWallet.feature
> +Feature: New wallet flow
Let's refer to the feature how it is express in the app....
Feature: Create new wallet

2022-10-14 22:00 UTC, chrisleewilcox commented on wdio/features/newWallet.feature
> +    And I input a new password and create account
Anytime you have a step that contains 'and' is likely you should split in two statements.

And I input a new password 
And click create wallet (this is creating a wallet, not create account)

2022-10-14 22:00 UTC, chrisleewilcox commented on wdio/features/newWallet.feature
> +    Then I select remind me later on secure wallet screen and proceed to accountP
Anytime you have a step that contains 'and' is likely you should split in two statements.

2022-10-14 22:03 UTC, cortisiko requested changes

2022-10-14 23:59 UTC, chrisleewilcox commented on wdio/features/screen-objects/WalletSetupScreen.js
> +export const createNewPassword = '123454321';
This is test data mixed in with page object data.  I think we should refactor this data to the feature file.

2022-10-17 11:04 UTC, Andepande commented on wdio/features/newWallet.feature
> +Feature: New wallet flow
Renamed

2022-10-17 12:58 UTC, Andepande commented on wdio/features/testIDs/Screens/WalletSetupScreen.testIds.js
> +  export const SKIP_BACKUP_BUTTON =
Yes changed

2022-10-17 13:03 UTC, Andepande commented on app/components/Views/ImportFromSeed/index.js
> +                // {...generateTestId(
Needs to  be rectified with Fatia on his branch when merged as this apart was affecting Detox tests

2022-10-17 13:03 UTC, Andepande commented on app/components/UI/SkipAccountSecurityModal/index.js
> +            //testID={'skip-backup-text'}
Removed

2022-10-17 13:05 UTC, Andepande commented on app/components/UI/SkipAccountSecurityModal/index.js
> +            // {...generateTestId(Platform, 'skip-backup-check')}
I think this may need looking at, currently using skip-back-up text selector to select check-box, but when this is enabled we're unable to select the checkbox

2022-10-17 13:10 UTC, Andepande commented on app/components/UI/SkipAccountSecurityModal/index.js
> +      confirmTestID={'Skip-button'}
On 'Secure Wallet' page, user selects Remind me later, I was able to select the skip button on ios with appium however was not able to do so with android. Creating new objects like so enabled us to define the test-id better and also enables Appium to see the selectors on Android.

2022-10-17 13:10 UTC, Andepande commented on app/components/UI/SkipAccountSecurityModal/index.js
> +      cancelTestID={'Cancel-Skip'}
On 'Secure Wallet' page, user selects Remind me later, I was able to select the skip button on ios with appium however was not able to do so with android. Creating new objects like so enabled us to define the test-id better and also enables Appium to see the selectors on Android.

2022-10-17 13:10 UTC, Andepande commented on wdio/features/screen-objects/WalletSetupScreen.js
> + async createNewAccountPassword() {
Done

2022-10-17 13:10 UTC, Andepande commented on wdio/features/screen-objects/WalletSetupScreen.js
> +async assertSkipSecurityModal(){
done

2022-10-17 13:11 UTC, Andepande commented on wdio/features/screen-objects/WalletSetupScreen.js
> + async assertNewAccountScreenFields(){
Yeah that makes sense, its just I was asserting all the expected fields on the one screen, but yeah one assertion can do the trick

2022-10-17 13:14 UTC, Andepande commented on wdio/features/screen-objects/WalletSetupScreen.js
> + async assertNewAccountScreenFields(){
Having thought about it, sometimes we may have instances where a screen may have some fields present and others not. But in this case we are asserting a screen so maybe may not be necessary to assert each field.

2022-10-17 13:15 UTC, Andepande commented on wdio/features/newWallet.feature
> +    Then I select remind me later on secure wallet screen and proceed to accountP
Makes sense in this instance, Changed

2022-10-17 15:06 UTC, chrisleewilcox commented on wdio/features/screen-objects/WalletSetupScreen.js
> +export const createNewPassword = '123454321';
At this point or in the near future I don't see a reason to have test data in the page objects.

2022-10-18 10:24 UTC, cortisiko commented on app/components/UI/SkipAccountSecurityModal/index.js
> +            // {...generateTestId(Platform, 'skip-backup-check')}
got it! Perhaps creating a variable for the selector instead of passing in the text itself.

2022-10-18 14:44 UTC, chrisleewilcox approved these changes
LGTM

2022-10-18 15:26 UTC, merged