Import wallet srp password validation
MetaMask/metamask-mobile pull request #5138
Opened 2022-10-22 17:22 UTC by chrisleewilcox

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

These changes do not include the ./app/components/Views/ImportFromSeed/index.js changes needed to avoid breaking detox. 

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-10-23 15:48 UTC, cortisiko requested changes
see comments

2022-10-23 15:48 UTC, cortisiko commented on wdio/features/step-definitions/onboarding.js
> +  const msg = await driver.getAlertText();
line 106 to line 109 should be an assertion method that lives in the ImportWallet page object.

2022-10-23 15:48 UTC, cortisiko commented on wdio/features/step-definitions/onboarding.js
> +      // await driver.pause(10000);
lets not leave comments in the code unless absolutely necessary.

2022-10-23 15:48 UTC, cortisiko commented on app/components/Views/ImportFromSeed/index.js
> +                //testID={'create-password-first-input-field'}
let's not leave comments in the code

2022-10-23 15:48 UTC, cortisiko commented on wdio/features/screen-objects/WalletMainScreen.js
> +    await expect(elem).toBeDisplayed();
Create a getter for the object then assert that the object is visible. Something like:


```suggestion

  get onBoardingWizard() {
    return Selectors.getElementByPlatform(ONBOARDING_WIZARD_STEP_1_CONTAINER_ID);
  }

  async isOnboardingWizardVisible() {
    await expect(this.onBoardingWizard).toBeDisplayed();
  }
```

2022-10-23 15:48 UTC, cortisiko commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +    console.log(`## Password strength is: ${strength}`);
Was this for debugging purposes? Do not keep console log messages in the code.

2022-10-23 15:48 UTC, cortisiko commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +    const elem = await this.passwordStrength;
this method seems like it is doing a lot. You are creating a variable for the password element then creating another variable to get the string of the password element. Why not do:

`const passwordStrengthText = await this.passwordStrength.getText();`

2022-10-23 15:48 UTC, cortisiko commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +    assert.strictEqual(strength, text);
any reason why we are not using webdriverio built-in assertions?

2022-10-24 14:03 UTC, chrisleewilcox commented on app/components/Views/ImportFromSeed/index.js
> +                //testID={'create-password-first-input-field'}
This is a detox id that is commented out.  Are you sure you want this removed?

2022-10-24 14:05 UTC, chrisleewilcox commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +    const elem = await this.passwordStrength;
Done.

2022-10-24 14:48 UTC, chrisleewilcox commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +    console.log(`## Password strength is: ${strength}`);
Removed.

2022-10-24 14:49 UTC, chrisleewilcox commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +    assert.strictEqual(strength, text);
Any reason why we want to only use webdriverio assertions?  No need for us to be limited with assertion capabilities.

2022-10-24 14:53 UTC, chrisleewilcox commented on wdio/features/screen-objects/WalletMainScreen.js
> +    await expect(elem).toBeDisplayed();
This file was implemented by either Yande or Fatia.  I just made a simple fix by adding await in the return.  I would actually like this file to be renamed to "TakeATourComponent.js" or something like that and probably best to do maintenance work on another PR.

2022-10-24 15:04 UTC, chrisleewilcox commented on wdio/features/step-definitions/onboarding.js
> +      // await driver.pause(10000);
Removed.

2022-10-24 15:34 UTC, chrisleewilcox commented on wdio/features/step-definitions/onboarding.js
> +  const msg = await driver.getAlertText();
Done.

2022-10-24 17:31 UTC, cortisiko commented on app/components/Views/ImportFromSeed/index.js
> +                //testID={'create-password-first-input-field'}
Is there a reason why you commented it out?

2022-10-24 17:32 UTC, cortisiko commented on wdio/features/screen-objects/WalletMainScreen.js
> +    await expect(elem).toBeDisplayed();
That is fair.

2022-10-24 17:34 UTC, cortisiko commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +    const elem = await this.passwordStrength;
mmmm okay! Your function still does a lot for an assertion. 

how about splitting that function into two? One that gets the password strength text and the other for the assertion.

2022-10-24 17:36 UTC, cortisiko commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +    const elem = await this.passwordStrength;
```
async PasswordStrengthText(){     
    const passwordStrengthTextElement = await this.passwordStrength;     
    const strength = await passwordStrengthTextElement.getText();      
    return strength;   
  }  
```

```
  async assertPasswordStrength(text){     
    assert.strictEqual(await this.PasswordStrengthText(), text);       
    }
```

The assertion function does what it is set to do.

2022-10-24 17:37 UTC, cortisiko commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +  async assertDeviceAlert(text){
This function should be split up into two. The action "tapping(accepting)" the alert should be in its function.

2022-10-24 17:41 UTC, cortisiko commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +    assert.strictEqual(strength, text);
I recommend using wdio assertions. In this case [toHaveText](https://webdriver.io/docs/api/expect-webdriverio/#tohavetext). I do agree with not being limited by assertions but I also believe it is important to have consistency. The question would be: when to use assert vs wdio assertions.

2022-10-24 18:00 UTC, chrisleewilcox commented on app/components/Views/ImportFromSeed/index.js
> +                //testID={'create-password-first-input-field'}
If I recall I think it was commented out when I created the branch.  I uncommented and doesn't look like that causes any issue.  Done.

2022-10-24 18:30 UTC, chrisleewilcox commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +    assert.strictEqual(strength, text);
This ended up being just a oneliner change that inherently getText() and compares so I didn't have to break that out into multiple functions.  

`await expect(this.passwordStrengthLabel).toHaveText(text);`

I like this approach.  Done.

2022-10-24 18:45 UTC, chrisleewilcox commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +  async assertDeviceAlert(text){
Do we want to have a separate class like `/helpers/Device.js` and put device control functions there?  Can we discuss and address in another PR?

2022-10-24 19:21 UTC, chrisleewilcox commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +    const elem = await this.passwordStrength;
Done.  Related to below change.

2022-10-24 19:59 UTC, cortisiko commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +  async assertDeviceAlert(text){
Yeah but you do so in this PR. This way, we lay a good foundation to deal with alert boxes when writing test cases in the future. It is as simple as creating a new class that has a function that taps "Ok" in the alert message.

2022-10-24 20:32 UTC, chrisleewilcox commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +  async assertDeviceAlert(text){
So I went down the route of trying to click "OK" on an alert and it didn't work out.  Doesn't look like there is a way to get an element for a device alert.  I then resorted to using webdriverio support for device alerts which is limited to...
[dismissAlert](https://webdriver.io/docs/api/jsonwp/#dismissalert)
[acceptAlert](https://webdriver.io/docs/api/jsonwp/#acceptalert)
[getAlertText](https://webdriver.io/docs/api/jsonwp/#getalerttext)
[sendAlertText](https://webdriver.io/docs/api/jsonwp/#sendalerttext)

Sounds like we need a class for device alert support for all our test.  There will also need to be some thought put into how we bundle up buttons on a device for acceptAlert(Yes, OK, Agree, Allow, etc...) and dismissAlert(No, Cancel, Close, etc...).  With all these considerations and others, I think this is separate work.  I feel more comfortable if there are no further changes necessary at this point related to SRP and password strength to merge this PR in before adding device support.  We should be mindful of not letting code reviews force PR's to drag on and take on other work that may be better suited in a separate PR.  Adding device support to this PR is essentially code creep for automation.  I agree we need it but think it's best suited in another PR so we can move on from this one.
Let me know how you want to proceed.

2022-10-24 20:43 UTC, cortisiko commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +  async assertDeviceAlert(text){
Thank you for doing the necessary research. The purpose of the code review is to ensure we are making the code as clean and readable as possible not necessarily dragging on the PR.

2022-10-24 20:43 UTC, cortisiko commented on wdio/features/screen-objects/ImportFromSeedScreen.js
> +  async assertDeviceAlert(text){
I will ask Fatia or Yande to handle. Thanks!

2022-10-24 20:45 UTC, cortisiko approved these changes
Much better. Feel free to merge whenever @chrisleewilcox

2022-10-24 22:35 UTC, merged