Appium: Lock and Reset wallet scenarios
MetaMask/metamask-mobile pull request #5174
Opened 2022-10-29 19:23 UTC by chrisleewilcox

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-10-30 13:56 UTC, cortisiko requested changes

2022-10-30 13:56 UTC, cortisiko commented on wdio/features/screen-objects/WalletMainScreen.js
>    get WalletScreenContainer(){
put all the `getters` together.

2022-10-30 13:56 UTC, cortisiko commented on wdio/features/screen-objects/LoginScreen.js
> +    async typedelete(deleteText){
this should be camel case. Also, can you rename it to something more explicit? `typeDeleteText` or `typeDeleteTextInModal`

2022-10-30 13:56 UTC, cortisiko commented on wdio/features/screen-objects/LoginScreen.js
> +    get deleteMyWallet(){
I assume this is the delete button in the delete wallet modal? If so you should be a bit more descriptive.

2022-10-30 13:56 UTC, cortisiko commented on wdio/features/screen-objects/LoginScreen.js
> +    get understandContinue(){
create a new page object for the delete wallet modal. You are mixing the delete wallet modal elements and the login view elements. So `deleteInput`, `deleteMyWallet`,`tapIUnderstandContinue`,`typedelete` should be in the delete modal class. 

also rename the function from `understandContinue` to `iUnderstandContinueButton`

2022-10-30 13:56 UTC, cortisiko commented on wdio/features/helpers/Gestures.js
> +const Actions = {
🌮 🌮 🌮 🌮

2022-10-30 13:56 UTC, cortisiko commented on wdio/features/screen-objects/WalletMainScreen.js
> +  async validateOnboardingWizard() {
```suggestion
  async isOnboardingWizardVisible() {
```

2022-10-30 13:56 UTC, cortisiko commented on wdio.conf.js
> +    require: ['./wdio/features/step-definitions/*.js'],
smart call!

2022-10-30 13:56 UTC, cortisiko commented on app/components/UI/DrawerView/index.js
> +                            // accessible={item.accessible}
you should remove these comments.

2022-10-30 13:56 UTC, cortisiko commented on wdio/features/step-definitions/login-view.js
> +import { Given, When, Then } from '@wdio/cucumber-framework';
nice, so this would be the format for naming feature files? `login-view` or `wallet-view` or `settings-view`

2022-10-30 13:56 UTC, cortisiko commented on wdio/features/screen-objects/LoginScreen.js
> +    async tapResetWallet(){
```suggestion
    async tapResetWalletButton(){
```

2022-10-30 13:56 UTC, cortisiko commented on wdio/features/screen-objects/LoginScreen.js
> +    get resetWallet(){
```suggestion
    get resetWalletButton(){
```

2022-10-31 04:25 UTC, chrisleewilcox commented on wdio/features/screen-objects/WalletMainScreen.js
>    get WalletScreenContainer(){
Done.

2022-10-31 04:28 UTC, chrisleewilcox commented on wdio/features/screen-objects/LoginScreen.js
> +    async typedelete(deleteText){
Doned

2022-10-31 04:32 UTC, chrisleewilcox commented on wdio/features/screen-objects/LoginScreen.js
> +    get deleteMyWallet(){
You mean like deleteMyWalletButton()?

2022-10-31 04:45 UTC, chrisleewilcox commented on wdio/features/step-definitions/login-view.js
> +import { Given, When, Then } from '@wdio/cucumber-framework';
You mean naming format for step files?  Yeah I think we can follow this for step files.

2022-10-31 04:49 UTC, chrisleewilcox commented on app/components/UI/DrawerView/index.js
> +                            // accessible={item.accessible}
Done

2022-10-31 04:52 UTC, chrisleewilcox commented on wdio/features/screen-objects/LoginScreen.js
> +    async tapResetWallet(){
Done.

2022-10-31 04:53 UTC, chrisleewilcox commented on wdio/features/screen-objects/LoginScreen.js
> +    get resetWallet(){
Done

2022-10-31 20:44 UTC, chrisleewilcox commented on wdio/features/screen-objects/LoginScreen.js
> +    get understandContinue(){
Done

2022-10-31 20:49 UTC, chrisleewilcox commented on app/components/UI/DeleteWalletModal/index.tsx
> +          cancelTestID={'delete-my-wallet-button-on-permanetly-delete-modal'}
Yeah we can but I was wondering if we can change the property name?  cancelTestiD doesn't seem to match the button to click on like 'I understand, continue'.  I would like to see if we can update the properties to reflect the element.

2022-10-31 22:59 UTC, cortisiko approved these changes
good work Chris!

2022-10-31 23:16 UTC, chrisleewilcox commented on wdio/features/screen-objects/WalletMainScreen.js
> +  async validateOnboardingWizard() {
Done

2022-11-01 18:55 UTC, merged