Networks-flow appium feature file
MetaMask/metamask-mobile pull request #5188
Opened 2022-11-01 19:35 UTC by Andepande

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
Implemented Networks feature test file testing a number of scenarios

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [ ] Any added code is fully documented

2022-11-01 20:50 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And I tap on the navbar network title button
When I tap on the navbar network title button

2022-11-01 20:51 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +             When I tap on the Add a Network button
And I tap on the Add a Network button

2022-11-01 20:51 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And I select approve
When I select approve

2022-11-01 20:52 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And I should see the added network name "Palm" in the top navigation bar
Then I should see the added network name "Palm" in the top navigation bar

2022-11-01 20:56 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +             Then the networks page opens with two tab views: Popular networks and Custom network
Then the networks page opens with two tab views
And tab "Popular" network is displayed
And tab "Custom" network is displayed

2022-11-01 20:57 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And "Palm" is not visible in the Popular Networks section
Then "Palm" is not visible in the Popular Networks section

2022-11-01 21:00 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +             When I tap on the Add Network button the networks page opens
And I tap on the Add Network button

2022-11-01 21:02 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And the Network name input box is visible and I type "xDai "
Then I type "xDai"

2022-11-01 21:04 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And the RPC URL input box is visible and I type "https://rpc.gnosischain.com"
And I type "https://rpc.gnosischain.com" in RPC URL input

2022-11-01 21:28 UTC, chrisleewilcox requested changes
Please review comments....

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And the Chain ID input box is visible and I type "100"
And I type "100" in Chain ID input

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And the Network Symbol input box is visible and I type "xDai"
And I type "xDai" in Network Symbol input

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And I should see the added network name "xDai" in the top navigation bar
Then...

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And I tap on the Add Network button the networks page opens
And I tap on the Add Network button

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +             When the network approval modal has two options Switch network and close
Then...

Anytime you have 'and' in a step that most likely means its better to break off that 'and' into 'And' for a separate step.

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And I should see the added network name "Palm" in the top navigation bar
Then....

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +             When I tap and hold network "Palm"
And....

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +             When I tap on the Add Network button the networks page opens
And...

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And Add button is disabled
Then...

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And the Network name input box is visible and I type "xDai "
And I type "xDai"

No need to check if an element is visible if the next step is you are going to interact with it.

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And the RPC URL input box is visible and I type "https://rpc.gnosischain.com"
And I type "https://rpc.gnosischain.com"

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And the Chain ID input box is visible and I type "100"
And I type "100" in the Chain ID input

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And the Network Symbol input box is visible and I type "xDai"
And I type "xDai" in Network Symbol input

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And I should see the added network name "xDai" in the top navigation bar
Then....

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And a "Delete" button should be visible
Then..

But do you really need to check if it's visible if you are going to interact with it?

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +            #  Then "xDai" should not be visible
Remove comments.

2022-11-01 21:28 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And I tap on the navbar network title button
When...

2022-11-02 00:55 UTC, cortisiko requested changes, later dismissed

2022-11-02 00:55 UTC, cortisiko commented on app/components/UI/Navbar/index.js
> +        {...generateTestId(Platform, 'hamburger-menu-button-wallet')}
Add a constant for this elementID

2022-11-02 00:55 UTC, cortisiko commented on app/components/UI/NavbarTitle/index.js
> +            accessibilityLabel={'navbar-title-network'}
Add a constant for this elementID

2022-11-02 00:55 UTC, cortisiko commented on app/components/UI/OnboardingWizard/Step4/index.js
> +            {...generateTestId(Platform, 'hamburger-menu-button-wallet-fake')}
Add a constant for this elementID

2022-11-02 00:55 UTC, cortisiko commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +              {...generateTestId(Platform, 'input-chain-id')}
Add a constant for this elementID

2022-11-02 00:55 UTC, cortisiko commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +              {...generateTestId(Platform, 'input-rpc-url')}
Add a constant for this elementID

2022-11-02 00:55 UTC, cortisiko commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +              {...generateTestId(Platform, 'input-network-symbol')}
Add a constant for this elementID

2022-11-02 00:55 UTC, cortisiko commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +              //testID={'input-network-symbol'}
probably remove this comment after you verify that detox does not fail because of the missing testID property

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/Modals/AddNetworksModal.js
> +        return Selectors.getElementByPlatform('add-network-button', true);
Add a constant for this elementID then import it into this view. Also, the "true" flag is only for iOS. Whenever the elements are nested that's when you pass the true flag.

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/Modals/NetworkApprovalModal.js
> +        return Selectors.getElementByPlatform('approve-network-modal', true);
Add a constant for this elementID then import it into this view. Also, the "true" flag is only for iOS. Whenever the elements are nested that's when you pass the true flag.

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/Modals/NetworkApprovalModal.js
> +        return Selectors.getElementByPlatform('approve-network-approve-button', true);
See above comment

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/Modals/NetworkApprovalModal.js
> +        return Selectors.getElementByPlatform('close-network-button', true);
see above comment

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/Modals/NetworkApprovalModal.js
> +        return Selectors.getElementByPlatform('switch-to-network-button', true);
see above comment

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/Modals/NetworkRemovalModal.js
> +  return Selectors.getElementByPlatform('network-education-modal-close-button');
Add a constant for this elementID then import it into this view.

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/NetworksScreen.js
> +        return Selectors.getElementByPlatform('POPULAR');
Add a constant for this `elementID` then import it into this view.

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/NetworksScreen.js
> +        return Selectors.getElementByPlatform('CUSTOM NETWORKS');
see above

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/NetworksScreen.js
> +        return Selectors.getElementByPlatform('add-network-button');
see above

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/NetworksScreen.js
> +        return Selectors.getElementByPlatform('input-network-name');
see above

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/NetworksScreen.js
> +        return Selectors.getElementByPlatform('input-rpc-url');
see above

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/NetworksScreen.js
> +        return Selectors.getElementByPlatform('input-chain-id');
see above

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/NetworksScreen.js
> +        return Selectors.getElementByPlatform(' add-network-button');
see above

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/NetworksScreen.js
> +        return Selectors.getElementByPlatform('remove-network-button');
see above

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/NetworksScreen.js
> +        return Selectors.getElementByPlatform('block-explorer');
see above

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/NetworksScreen.js
> +        return Selectors.getElementByPlatform('input-network-symbol');
see above

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/WalletMainScreen.js
> +    return Selectors.getElementByPlatform('hamburger-menu-button-wallet');
Add a constant for this elementID then import it into this view.

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/screen-objects/WalletMainScreen.js
> +    return Selectors.getElementByPlatform('drawer-settings');
see above

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/step-definitions/network-flow.js
> +  await expect($(`//android.widget.TextView[@text='${network}']`)).not.toBeDisplayed();
keep assertions within the page object. Create a method for this assertion

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/step-definitions/network-flow.js
> +  expect(await $(`//android.widget.TextView[@text='${text}']`)).toBeDisplayed();
keep assertions within the page object. Create a method for this assertion

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/step-definitions/network-flow.js
> +  await $(`//android.widget.TextView[@text='${text}']`).click();
keep actions within the page object. Create a method for this action. Furthermore, if you can import the tap action from the gesture class that would be great. Perhaps create a new method in the gestures class called `tapByXPath` 

something like this in the gestures class
```
async tapByXPath(text){
(await $(`//android.widget.TextView[@text='${text}']`)).touchAction(Actions.TAP);
}
```
then in the page object you use the method like

```
async tapRemoveNetwork(text){
        await Gestures.tapByXPath(text)
    }
```

I know you will come up with a different solution!

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/step-definitions/network-flow.js
> +  expect(await $(`//android.widget.TextView[@text='${network}']`)).not.toBeDisplayed();
keep assertions within the page object. Create a method for this assertion

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/step-definitions/network-flow.js
> +  await $(`//android.widget.TextView[@text='${network}']`).touchAction('tap');
Re

> keep actions within the page object. Create a method for this action. Furthermore, if you can import the tap action from the gesture class that would be great. Perhaps create a new method in the gestures class called tapByXPath

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/step-definitions/network-flow.js
> +  await expect($(`//android.widget.TextView[@text='${network}']`)).toBeDisplayed();
keep assertions within the page object. Create a method for this assertion

2022-11-02 00:55 UTC, cortisiko commented on wdio/features/step-definitions/network-flow.js
> +  await $(`//android.widget.TextView[@text='${option}']`).click();
Re

> keep actions within the page object. Create a method for this action. Furthermore, if you can import the tap action from the gesture class that would be great. Perhaps create a new method in the gestures class called tapByXPath

2022-11-06 19:09 UTC, Andepande commented on app/components/UI/NavbarTitle/index.js
> +            accessibilityLabel={'navbar-title-network'}
Adding constant causing issues for some reason, this seems to work best for now

2022-11-06 19:10 UTC, Andepande commented on app/components/UI/OnboardingWizard/Step4/index.js
> +            {...generateTestId(Platform, 'hamburger-menu-button-wallet-fake')}
Removed constant as not used

2022-11-07 11:34 UTC, Fatxx commented on app/components/UI/NetworkInfo/index.tsx
> +          testID={NETWORK_EDUCATION_MODAL_CLOSE_BUTTON}
We should not need both `testID` and `generateTestId` in the same component

2022-11-07 11:34 UTC, Fatxx commented on app/components/UI/OnboardingWizard/Step4/index.js
> +import generateTestId from '../../../../../wdio/utils/generateTestId';
Remove undefined variables

2022-11-07 11:34 UTC, Fatxx commented on app/components/UI/NetworkModal/index.tsx
> +                testID={APPROVE_NETWORK_APPROVE_BUTTON}
Same here

2022-11-07 11:34 UTC, Fatxx commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
>                testID={INPUT_NETWORK_NAME}
Same here

2022-11-07 11:34 UTC, Fatxx commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +              testID={INPUT_RPC_URL_FIELD}
Same here

2022-11-07 11:34 UTC, Fatxx commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
>                      testID={ADD_CUSTOM_RPC_NETWORK_BUTTON_ID}
Same here

2022-11-07 11:34 UTC, Fatxx commented on app/components/Views/Wallet/index.tsx
> +  Platform,
Remove undefined variables

2022-11-07 11:34 UTC, Fatxx commented on index.js
> +LogBox.ignoreAllLogs();
Don't commit to this change, this should be only for development porpuses

2022-11-07 11:34 UTC, Fatxx commented on app/components/Views/Settings/NetworksSettings/index.js
> +          testID={'remove'}
Use constant? Why hardcoded?

2022-11-07 11:34 UTC, Fatxx commented on app/components/Views/Settings/index.js
> +          testID={'test'}
Remove this? Seems that it was forgotten.

2022-11-07 11:34 UTC, Fatxx commented on wdio/features/helpers/Selectors.js
> +  static async getXpathElementByText(text){
Why are we using Xpath? Can we keep using ids instead?

2022-11-07 11:34 UTC, Fatxx commented on wdio/features/testIDs/Components/NetworksModal.testIds.js
> +// eslint-disable-next-line import/prefer-default-export
Can we remove this file? It's empty

2022-11-07 14:12 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And a "Delete" button should be visible
Redundant, remove.

2022-11-07 14:20 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And I tap on the Add Network button the networks page opens
Still kind of a confusing step.....

And I tap on the Add Network button

2022-11-07 14:20 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And the Network Symbol input box is visible
Redundant, remove.

2022-11-07 14:33 UTC, chrisleewilcox requested changes
Left a few more comments but in general I think we can trim down the amount of steps you have in your feature file.  There is also a lint error with one of your changes.  Please address.

2022-11-07 15:29 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And I type "100" into the Chain ID field
You should have a separate parameter for the network modal inputs...
name
rpcURL
symbol
blockexplorer

2022-11-07 16:24 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +              And I tap No thanks on the onboarding welcome tutorial
I like this.  Can be used for other scenarios.

2022-11-08 01:01 UTC, chrisleewilcox approved these changes
LGTM

2022-11-09 10:18 UTC, Fatxx commented on app/components/UI/DrawerView/index.js
> +          testID: 'drawer-settings',
Use constant instead

2022-11-09 10:18 UTC, Fatxx commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +                    {...generateTestId(Platform, REMOVE_NETWORK_BUTTON)}
This is a `StyledButton` so as we talked before it should use the `testID`

2022-11-09 10:18 UTC, Fatxx commented on index.js
> -
Add this line back pls

2022-11-09 15:46 UTC, sethkfman commented on wdio/features/screen-objects/NetworksScreen.js
> +       await (await Selectors.getXpathElementByContentDecscription('burger-menu-title-back-arrow-button')).touchAction('tap');
consider using a constant for button string

2022-11-09 15:48 UTC, sethkfman commented on wdio/features/step-definitions/network-flow.js
> +  await driver.pause(10000);
consider converting the number to constant

2022-11-09 17:31 UTC, sethkfman approved these changes
LGTM

2022-11-09 17:32 UTC, merged