[DRAFT] Update Controllers to version 32.0.2 (will be to 32.0.3)
MetaMask/metamask-mobile pull request #5200
Opened 2022-11-04 11:26 UTC by tommasini

**Description**
*Waiting for the release on controllers*
Updating the controllers to version 32.0.2, will update the way Network Controller works

**Test Cases**
Case1:
* Tested swaps on mainnet (uniswap) and custom network (Binance Smart Chain) (pancakeswap)
Case2:
* Tested transfer of collectible to myself on Mainnet
Case3:
* Tested token detection and nft Detection
Case4:
* Tested transfers between accounts, and the gas fee seems to be working and well defined
Case 5:
* Tested deep link with network changing
Case 6:
* Tested the activity view in different networks
Case 7:
* Tested switching accounts and verifying the balance on them (Also switching networks)

Would be good to do an overall test of the app.

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-11-04 21:03 UTC, sethkfman commented on app/core/BackgroundBridge/BackgroundBridge.js
> +      `NetworkController:stateChange`,
Maybe we can create a const and reference throughout the codebase. I see this in a few locations

2022-11-04 21:33 UTC, tommasini commented on app/core/BackgroundBridge/BackgroundBridge.js
> +      `NetworkController:stateChange`,
Completely agree 💯

2022-11-08 17:42 UTC, sethkfman commented on app/core/BackgroundBridge/BackgroundBridge.js
> +      `NetworkController:stateChange`,
Missed one

2022-11-08 17:42 UTC, sethkfman commented on app/core/BackgroundBridge/BackgroundBridge.js
> +      `NetworkController:stateChange`,
Missed one

2022-11-08 17:42 UTC, sethkfman commented on app/core/EngineService.ts
> +          'NetworkController:stateChange',
Missed one

2022-11-08 22:01 UTC, Gudahtt commented
I have created a PR to account for the PhishingController breaking changes included in the v31 and v32 controllers releases: #5215

2022-11-08 22:26 UTC, Gudahtt reviewed
The NetworkController changes all look good to me!

2022-11-08 22:26 UTC, Gudahtt commented on app/core/Engine.js
> +          ],
Nit: I don't think any allowed events are needed here. It should automatically have permission to use any events or actions under its own namespace

```suggestion
          allowedEvents: [],
```

2022-11-08 22:26 UTC, Gudahtt commented on app/core/Engine.js
> -      network.refreshNetwork();
Interesting - even in the older version of the controllers package, this was a private method. It seems that setting `providerConfig` has basically the same effect as calling this, so I agree that it is not needed.

2022-11-09 17:19 UTC, tommasini commented on app/core/Engine.js
> +          ],
Confirmed

2022-11-09 20:46 UTC, sethkfman commented
@SocketSecurity ignore @ethereumjs/rlp@4.0.0 rlp@2.2.6 rlp@3.0.0

2022-11-09 20:49 UTC, sethkfman approved these changes
LGTM

2022-11-09 20:57 UTC, Gudahtt commented
This PR still needs to be merged into this: https://github.com/MetaMask/metamask-mobile/pull/5215

Otherwise the phishing configuration will never be updated

2022-11-10 21:39 UTC, Gudahtt commented on app/store/migrations.js
>  export const version = 11;
Oops, I think I missed this!
```suggestion
export const version = 12;
```

2022-11-10 23:34 UTC, tommasini commented on app/store/migrations.js
>  export const version = 11;
Oops, escaped me as well! Thanks for backing here!

2022-11-22 16:42 UTC, Gudahtt commented
I'm seeing this warning during the `setup` step in CI:

```
Warning: patch-package detected a patch file version mismatch

  Don't worry! This is probably fine. The patch was still applied
  successfully. Here's the deets:

  Patch file created for

    @metamask/controllers@30.3.0

  applied to

    @metamask/controllers@33.0.0
  
  At path
  
    node_modules/@metamask/controllers

  This warning is just to give you a heads-up. There is a small chance of
  breakage even though the patch was applied successfully. Make sure the package
  still behaves like you expect (you wrote tests, right?) and then run

    patch-package @metamask/controllers

  to update the version in the patch file name and make this warning go away.

```

Seems like that patch file needs an update

2022-11-22 23:47 UTC, Gudahtt approved these changes

2022-12-09 23:56 UTC, chrisleewilcox commented
Swaps:
Polygon
  MATIC => WMATIC => Edit gas fee to Market: PASS
  MATIC => UNI: PASS
  USDT => LINK: PASS
  UNI => DAI: PASS
  Cancel transaction: having problems cancelling.  Getting console warning on cancel: https://recordit.co/9xDj8XntwW

2022-12-12 15:50 UTC, chrisleewilcox commented
NFTs

Autodetect NFTs:
- ETH Mainnet: PASS

2022-12-12 16:08 UTC, chrisleewilcox commented
Wallet view:

Token fiat balance for asset is incorrect.  See [here](![image](https://user-images.githubusercontent.com/6626407/207095098-bd35c373-76d4-4e47-8d19-dfdf44388275.png)).

2022-12-12 16:17 UTC, chrisleewilcox requested changes
Please review comments.

2022-12-12 16:23 UTC, chrisleewilcox commented
Send Tokens:

ETH QRC:
ETH Deeplink:
Polygon QRC:
Polygon Deeplink:
BNB QRC:
BNB Deeplink:
AVAX QRC:
AVAX Deeplink:
Arbitrum QRC:
Arbitrum Deeplink:
Optimism QRC:
Optimism Deeplink:

2022-12-12 16:41 UTC, Gudahtt commented
Are these errors reproducible on `main`? Also, when these errors were encountered, did you recently switch networks?

It's hard to see how these changes would cause cancellation failures, edit limit failures, balance failures, etc. unless maybe there's a bug related to network switching. The code changes barely touch the transaction controller or asset management parts at all.

2022-12-12 19:02 UTC, chrisleewilcox commented
dApps

Uniswap:

- swaps:

Sushiswap swap:

- swaps:

pancake swap:

- swaps:

1inch:

- swaps:

2022-12-14 01:28 UTC, chrisleewilcox approved these changes
LGTM

2022-12-14 01:28 UTC, merged