Improve deeplinks experience
MetaMask/metamask-mobile pull request #5218
Opened 2022-11-09 14:45 UTC by jpcloureiro

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses [#460](/https://github.com/MetaMask/mobile-planning/issues/460)

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-11-09 15:08 UTC, NicholasEllul reviewed
I love this approach of intercepting the request! Are we able to add any tests to catch regressions in this behaviour?

2022-11-09 15:08 UTC, NicholasEllul commented on app/components/Views/BrowserTab/index.js
> +    const protocol = key.startsWith('http')
Do we know if theres a case that `http` could have any upper cases (ex: `hTTp://google.com`, or does that get normalized somewhere?

2022-11-09 15:08 UTC, NicholasEllul commented on app/components/Views/BrowserTab/index.js
> +    return true;
In the event a protocol comes in such as `foobar://` this if-statement will evaluate false as there is no alert message, and as a result the `verifyKnownProtocols` function and the `onShouldLoadWithRequest` will return true. This will lead to us proceeding with the execution of unknown protocols. Can we also have a generic alert to protect users in that case?

2022-11-09 16:00 UTC, sethkfman commented on app/components/Views/BrowserTab/index.js
> +          text: 'Ignore',
Check to see if there is something already available in our locales for translations.

2022-11-09 16:58 UTC, andreahaku commented
@jpcloureiro did you check how this change behaves with the app specific schemas like `metamask://`, `dapp://`, 'wc://' or 'ethereum://'?

2022-11-15 15:50 UTC, jpcloureiro commented
> @jpcloureiro did you check how this change behaves with the app specific schemas like `metamask://`, `dapp://`, `wc://` or `ethereum://`?

@andreahaku opening any of these schemas inside the webview will open the alert dialog. If the user presses allow, it will execute as before.

2022-11-15 15:50 UTC, jpcloureiro commented on app/components/Views/BrowserTab/index.js
> +    return true;
I've modified the code so any non whitelisted protocol will trigger an alert dialog with a generic message

2022-11-15 23:36 UTC, sethkfman commented on app/components/Views/BrowserTab/index.js
> +  const protocolWhitelist = ['about:', 'http:', 'https:'];
If any these are not impacting state, could they be moved out to a `ults` class that is TSX and can be tested?

2022-12-14 20:54 UTC, sethkfman approved these changes
One minor comment for a method rename but other than that it looks good.

2022-12-14 20:54 UTC, sethkfman commented on app/util/browser/index.test.ts
> +describe('Browser utils :: sanitizeUrl', () => {
Nice work on these test cases

2022-12-14 20:54 UTC, sethkfman commented on app/util/browser/index.ts
> +export const sanitizeUrl = (url: string, defaultProtocol = 'https://') => {
I like the effort to refactor to type script.

2022-12-14 20:54 UTC, sethkfman commented on app/components/Views/BrowserTab/index.js
> +    if (protocolWhitelist.includes(protocol)) return true;
Could we call change this to `protocolAllowlist()`?

2022-12-15 16:15 UTC, jpcloureiro commented on app/components/Views/BrowserTab/index.js
> +    if (protocolWhitelist.includes(protocol)) return true;
Yes, changing `protocolWhitelist` to `protocolAllowList`

2022-12-15 17:56 UTC, sethkfman approved these changes
LGTM

2022-12-20 21:07 UTC, NicholasEllul commented on app/util/browser/index.ts
> +        searchUrl = 'https://duckduckgo.com/?q=' + escape(input);
Escape is now [deprecated](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape) and instead its recommended that we use [encodeUriComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent)

2022-12-21 19:43 UTC, jpcloureiro commented on app/util/browser/index.ts
> +};
Agree, `prefixUrlWithProtocol` is better suited for what the function does.

2022-12-21 20:35 UTC, sethkfman commented
@jpcloureiro Can you add the scenarios you tested and update the lint errors?

2022-12-27 21:49 UTC, cortisiko requested changes
@jpcloureiro sending this back your way!

**Issue** 

On the webview error screen, when I tap the "return to home page" button I get:`[TypeError: Invalid URL: home.metamask.io]`. Furthermore, I am not taken back to the mm home page.  
see [recording](http://recordit.co/RncotziS6t)

To reproduce:
- open the browser
- enter an invalid URL. For example https://asfasfo.aox
- When the error screen appears
- tap on "return to home page". Notice the error.

2023-01-28 00:01 UTC, jpcloureiro commented
> @jpcloureiro sending this back your way!
> 
> **Issue**
> 
> On the webview error screen, when I tap the "return to home page" button I get:`[TypeError: Invalid URL: home.metamask.io]`. Furthermore, I am not taken back to the mm home page. see [recording](http://recordit.co/RncotziS6t)
> 
> To reproduce:
> 
> * open the browser
> * enter an invalid URL. For example https://asfasfo.aox
> * When the error screen appears
> * tap on "return to home page". Notice the error.

@cortisiko pushed a fix. It should go back to mm home page now.

2023-02-02 23:46 UTC, cortisiko approved these changes
Fix looks good @jpcloureiro, This is QA passed! 🌮 🌮

2023-02-02 23:46 UTC, merged