Add WebdriverIO test reports
MetaMask/metamask-mobile pull request #5226
Opened 2022-11-10 15:13 UTC by Fatxx

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

Enables generation of test reports for cucumber e2e tests, these reports are created as HTML pages under `wdio/reports`.

TODO: Where should we host these reports?

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-11-10 15:44 UTC, sethkfman approved these changes
LGTM

2022-12-19 18:30 UTC, cortisiko requested changes

2022-12-19 18:30 UTC, cortisiko commented on app/components/Views/AccountBackupStep1/index.js
> +// import SeedPhraseVideo from '../../UI/SeedPhraseVideo';
Is this disabling for QA builds as well as our regular builds?

2022-12-19 18:30 UTC, cortisiko commented on app/components/Views/AccountBackupStep1/index.js
> +  // <SeedPhraseVideo onClose={skip} />
relating to the above

2022-12-19 18:30 UTC, cortisiko commented on index.js
> +const IGNORE_LOGS_DEVELOPMENT = process.env.IGNORE_LOGS_DEVELOPMENT;
this is specifically for QA builds or regular builds? I see a benefit in having the logs during testing. Helps identify potential errors that can pollute sentry.

2022-12-19 18:30 UTC, cortisiko commented on wdio/features/screen-objects/Onboarding/ImportFromSeedScreen.js
> +    var msg = await driver.getAlertText();
Following ES6 variable declaration: the variable should be either a `const` or `let`.

2022-12-19 18:30 UTC, cortisiko commented on wdio/features/screen-objects/Onboarding/OnboardingCarousel.js
> +    // await elem.waitForDisplayed({ reverse: true });
any need for this?

2022-12-19 18:34 UTC, Fatxx commented on index.js
> +const IGNORE_LOGS_DEVELOPMENT = process.env.IGNORE_LOGS_DEVELOPMENT;
That's a variable that you can set in the .js.env to hide the boxes, it's disabled by default

2022-12-19 18:35 UTC, Fatxx commented on app/components/Views/AccountBackupStep1/index.js
> +// import SeedPhraseVideo from '../../UI/SeedPhraseVideo';
This was for testing, I will put it back

2022-12-19 19:13 UTC, cortisiko commented on index.js
> +const IGNORE_LOGS_DEVELOPMENT = process.env.IGNORE_LOGS_DEVELOPMENT;
okay got it. Left another comment down below!

2022-12-19 19:13 UTC, cortisiko commented on index.js
> +if (IGNORE_LOGS_DEVELOPMENT === 'true') {
okay so I see code is added here to ignore logs. Was this intentional?

2022-12-19 21:57 UTC, Fatxx commented on index.js
> +if (IGNORE_LOGS_DEVELOPMENT === 'true') {
Yes, it's a condition that checks if that variable is set it hides the log boxes.

2022-12-19 21:57 UTC, Fatxx commented on wdio/features/screen-objects/Onboarding/ImportFromSeedScreen.js
> +    var msg = await driver.getAlertText();
This is from the @chrisleewilcox PR. I merged his PR in to this one.

2022-12-19 22:13 UTC, chrisleewilcox commented on wdio/features/screen-objects/Onboarding/ImportFromSeedScreen.js
> +    var msg = await driver.getAlertText();
My bad.  Been awhile.  Changed to `let`.

2022-12-23 15:42 UTC, Fatxx commented
Closing in favor of #5433

2023-01-12 20:00 UTC, closed without merging