Improve browser experience
MetaMask/metamask-mobile pull request #5238
Opened 2022-11-14 14:51 UTC by blackdevelopa

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses [#458](https://github.com/MetaMask/mobile-planning/issues/458)

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-11-16 03:25 UTC, Cal-L reviewed
Left some comments. You can ignore the areas where I commented that I tagged. It's just a way for me to identify the areas of code that changed. Btw, it looks like there are a bunch of changes that you didn't actually touch. If you have the chance, I'd recommend reapplying the changes that you made and then re-patching to see if you still get all of the diffs.

2022-11-16 03:25 UTC, Cal-L commented on patches/react-native-webview+11.13.0.patch
> ++        ArrayList<String> requestedAndroidPermissions = new ArrayList<>();
Doesn't look like this is being used.

2022-11-16 03:25 UTC, Cal-L commented on patches/react-native-webview+11.13.0.patch
> ++        ArrayList<String> grantedPermissions = new ArrayList<>();
Doesn't look like this is being used.

2022-11-16 03:25 UTC, Cal-L commented on patches/react-native-webview+11.13.0.patch
> -+      String visibleUrl = webView.getUrl();
This shouldn't be removed. Can you verify your merge from main to confirm that you have the latest changes?

2022-11-16 03:25 UTC, Cal-L commented on patches/react-native-webview+11.13.0.patch
> ++        String requestPermissionIdentifier = null;
Just tagging this line as actual code that changed

2022-11-16 03:25 UTC, Cal-L commented on patches/react-native-webview+11.13.0.patch
> ++        AlertDialog.Builder builder = new AlertDialog.Builder(mReactContext);
Just tagging this line as actual code that changed

2022-11-16 11:25 UTC, blackdevelopa commented on patches/react-native-webview+11.13.0.patch
> -+      String visibleUrl = webView.getUrl();
Crossed checked against main and reverted.

2022-11-17 21:16 UTC, Cal-L approved these changes
LGTM!

2022-11-24 00:48 UTC, cortisiko requested changes
@Cal-L @blackdevelopa @NicholasEllul This PR does what it was set out to do. I went ahead and did the browser regression and reported my findings [here](https://github.com/MetaMask/mobile-planning/issues/458#issuecomment-1325810589).

2022-11-24 08:57 UTC, blackdevelopa commented
@cortisiko I have now updated the cirt app description [here](https://github.com/MetaMask/mobile-planning/issues/458#issuecomment-1326138612)

2022-11-29 18:09 UTC, cortisiko approved these changes
After discussing the above with @blackdevelopa @NicholasEllul we decided that the above is not a blocker for this PR. We will follow up in a different PR. You can track the progress [here](https://github.com/MetaMask/mobile-planning/issues/494)

2022-11-29 18:09 UTC, merged