[DRAFT][IMPLEMENT] Use Terms Modal
MetaMask/metamask-mobile pull request #5242
Opened 2022-11-15 12:51 UTC by tommasini

**THIS IS A DRAFT AND IT'S WAITING FOR DESIGN FEEDBACK AND THE TRANSLATIONS TO BE READY**

**Description**
Implementation of the new User Terms logic.
* The new user will not be able to create a new wallet or import an existing one while the new user while do not accept the Terms and Conditions
* The existing user will not be able to do anything if do not accept the Terms and Conditions

**Screenshots/Recordings**
Iphone 11 pro and Iphone 12 mini 
https://recordit.co/7o6OLITJFG

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-11-15 22:03 UTC, sethkfman commented on app/components/UI/ModalUseTerms/ModalUseTerms.tsx
> +const ModalUseTerms = ({ onDismiss }: ModalUseTermsI) => {
Could we make this modal component more generic? Maybe title it `ModalRequireAccept` and then pass in props for the text?

I am thinking this could be something we may reuse.

2022-11-15 23:18 UTC, tommasini commented on app/components/UI/ModalUseTerms/ModalUseTerms.tsx
> +const ModalUseTerms = ({ onDismiss }: ModalUseTermsI) => {
Yes of course!! Thank you!

2022-11-17 17:33 UTC, tommasini commented on app/components/UI/ModalUseTerms/ModalUseTerms.tsx
> +const ModalUseTerms = ({ onDismiss }: ModalUseTermsI) => {
Done it

2023-01-06 19:16 UTC, Cal-L reviewed
Left some comments.

2023-01-06 19:16 UTC, Cal-L commented on app/components/Nav/Main/index.js
> +          <ModalUseTerms onDismiss={() => setShowUseTermsModal(false)} />
Cleaner to move the `ModalUseTerms` over to the `RootModalFlow` in `Nav/App/index.js`. Reference how `ModalConfirmation` is setup.

2023-01-06 19:16 UTC, Cal-L commented on app/components/Views/Onboarding/index.js
> +            onDismiss={() => this.setState({ showUseTermsModal: false })}
Cleaner to move the `ModalUseTerms` over to the `RootModalFlow` in `Nav/App/index.js`. Reference how `ModalConfirmation` is setup.

2023-01-06 19:16 UTC, Cal-L commented on app/components/UI/ModalUseTerms/ModalUseTerms.tsx
> +    <ModalMandatory
Based on the UI and places where this page is used, we can probably consolidate this file into `ModalMandatory` and make it more agnostic + expose callback for analytics triggers to satisfy the different use cases.

2023-01-06 19:16 UTC, Cal-L commented on app/component-library/components/Modals/ModalMandatory/ModalMandatory.tsx
> +const ModalMandatory = ({
Left a comment below mentioning that we can keep this and remove `ModalUseTerms` since the UI is basically the same in all places where this is used, so no need to create another layer.

2023-01-06 19:16 UTC, Cal-L commented on app/component-library/components/Modals/ModalMandatory/ModalMandatory.tsx
> +    <ElevatedView style={styles.screen}>
In a comment below, I mentioned that it's probably cleaner to use this component as part of the navigation stack instead of being inline within a component. To achieve that, you can reference how `ModalConfirmation` is currently setup since it's setup exactly that way. Part of that means that you can remove `ElevatedView` (Android specific) and wrap with `ReusableModal` instead.

2023-01-06 19:37 UTC, Cal-L commented
It also looks like the implemented UI is slightly different than what is presented in the Finalized section in Figma.
- The checkbox isn't aligned relative to the agreement description
- The circle with the down caret doesn't exist in the implementation

I left a few comments in Figma asking for clarification on some pieces. Will keep an eye out for a response. @tommasini Who should we reach out to as the designer for this UI?
Figma for reference - https://www.figma.com/file/j3T1H0Xiuke9NhFJ3yOxBU/Updated-Terms-of-Use?node-id=0%3A1&t=VX7fTz82hEXlbNiO-0

2023-01-10 18:08 UTC, tommasini commented on app/component-library/components/Modals/ModalMandatory/ModalMandatory.tsx
> +    <ElevatedView style={styles.screen}>
Thanks for the review!
We can't use the Reusable Modal here because the webview doesn't render inside the PanGestureHandler according to the [comment](https://github.com/software-mansion/react-native-gesture-handler/issues/648#issuecomment-1084485256) on this issue

2023-01-16 17:13 UTC, Cal-L approved these changes
Lgtm

2023-02-15 20:27 UTC, sethkfman commented on locales/languages/en.json
> +  "title": "Our Terms of Use have updated",
"Our Terms of Use have been updated"

2023-02-15 20:31 UTC, tommasini commented on locales/languages/en.json
> +  "title": "Our Terms of Use have updated",
Done! Thanks Seth for the review!

2023-02-15 20:33 UTC, sethkfman approved these changes
LGTM

2023-02-17 03:19 UTC, chrisleewilcox commented
After install app launch shows "An error occured" screen with a number of console warning/errors.

https://recordit.co/GG1zxTg37F

Also, is 'occured' misspelled?  Should be 'occurred'??

2023-02-17 03:22 UTC, chrisleewilcox requested changes
Please review app launch issue.

@Cal-L @tommasini

2023-02-17 03:53 UTC, chrisleewilcox commented
Case 3:
Case 2 with translations.

2023-02-18 16:23 UTC, chrisleewilcox commented
I am finding issues that are not meeting the acceptance criteria in the issue.  Please make sure all acceptance criteria in the issue has been met.  This is not ready for QA.  Please do not move this to QA Review until we have reviewed together the acceptance criteria.

2023-02-18 17:06 UTC, chrisleewilcox commented
I think we should have two PR's for the ToU to better manage the implementation.....

- Modify this PR to reflect ToU for new installs
- Add another PR to reflect ToU for upgrading app

2023-02-19 21:08 UTC, tommasini commented
>  I can easily bypass the ToU without accepting terms

Thanks for testing, can you record how you bypass the modal? Thank you!

2023-02-21 16:17 UTC, chrisleewilcox requested changes
@tommasini can you provide a recording of ToU for upgrading app?  I am curious how we are testing that for iOS and Android.  Are you using TestFlight?  How are you confirming this for Android upgrade?

2023-02-21 16:39 UTC, tommasini commented
@chrisleewilcox I'm using the simulator on IOS and with android, I'm running debug on my physical device, when you say android upgrade I'm not sure if I'm understanding the question

2023-02-23 00:57 UTC, Cal-L approved these changes
LGTM

2023-03-01 21:55 UTC, chrisleewilcox commented
### Issue 1: Accessibility icon changes ToU content on iOS
iPhone 11 iOS 15.2
Is there a way to disable and not display the accessibility icon on the ToU?  A user can change the content of the ToU and agree to the different content and not ToU.
https://recordit.co/Nd12AdXXjk
Expected: ToU content cannot be changed and user must accept/agree to the correct ToU content.

2023-03-01 22:06 UTC, chrisleewilcox commented
### Issue 2: Terms of Use main slow loading
The main content inside the ToU modal take awhile to load and display.

2023-03-01 23:28 UTC, tommasini commented
Issue1:
* It's fixed, we can't remove the accessibility floating button, but I prevent the navigation on the webview now to another website
Issue2:
* Hmm do you think it would be better to have a loader? It will not open quickly but it will give some feedback to the user that the page is loading

2023-03-02 18:02 UTC, chrisleewilcox commented
Issue 2 is not high priority and we can defer for now and address in later PR if necessary.

2023-03-10 17:41 UTC, chrisleewilcox commented
Hi all.  Tomas had looped me in on this thread because I am testing the ToU and I have concerns about the accessibility icon at it's current position on the ToU content in mobile app.  Currently the accessibility icon is too close to the agree to terms checkbox and if a user mistaps on the accessibility icon they can get confused with the different accessibility content being displayed and have a hard time agreeing to terms.
Can we move the accessibility icon?  I'm thinking to the upper right of the ToU content.  If so I think this would have to be done on the website side.

2023-03-13 21:47 UTC, chrisleewilcox commented
@tommasini I am unable to see the ToU events.  I can see other events for mobile app but not ToU events.  Can you take a look?
https://recordit.co/5fDI0enmj3

2023-03-14 17:48 UTC, tommasini commented
@chrisleewilcox It's fixed, the ToU modal was moved to before importing the SRP or create a new wallet screens and right after the Metrics agreed screen, this way news users, if they agree to participate on the metrics, the mix panel events should appear

2023-03-14 23:41 UTC, Cal-L approved these changes
LGTM

2023-03-15 00:15 UTC, tommasini commented
They are addressed on this PR, the reason why they were not appearing it was that it was a new user and still did not accept to participate in the metrics

2023-03-16 13:51 UTC, SamuelSalas commented
Webdriver.IO Browserstack test results:
/wdio/features/Accounts/CreatingWalletAccount.feature

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/521d7390f4c43a28130de11107f32ed6e3e0dbf3?auth_token=60b1b6a1021fde7802e00eb31d6661ce751543e08f10ccd54179e78d4b1e7f96

/wdio/features/Accounts/ImportingAccount.feature

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/0538249f59ed6e471203e5fe6dc6374cfc756a63?auth_token=08f7b5c143a11dac3e620766ad1a7b9ae8453ff098e0586fc4dbbeaf6416b5d7

/wdio/features/Onboarding/CreateNewWallet.feature

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/94d198ecd44e786cbebca558bdceb6fc664b1e8f?auth_token=79b49c5ed157b59418bc8552c2aa1ac70245791b02a65a3a16240c7c699b8178

/wdio/features/Onboarding/ImportWallet.feature

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/f11b33be46545b268bda4ef17fafdd9564a7fe97?auth_token=6225c8675703479047c579bc2247ec0538291aaa37e162030c51b27018497a1a

/wdio/features/Onboarding/ImportWalletRegression.feature

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/c505a6675f2ed1cee046e0a07d8b856b109f66b1?auth_token=074accdd04692188d52c7827ef2f8b24ab85f13edc2d22e81b44233dcf36f53b

/wdio/features/Onboarding/TermsOfUse.feature

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/983f14e98a39a833d93081dc78256c64caee0a56?auth_token=0db9e909a06dea0bb1f1ecb359120fbe24e8404570562a85fc9042ad734e22d7

/wdio/features/Performance/AppLaunchTime.feature

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/bd21a47bd0d37590b1d7a86dccf8272df9e284b3?auth_token=b56a04ef64aa0f4b9a5e9789ea63f49e59e64cb68cb085c11a2049d389d2d96f

/wdio/features/AddressFlow.feature -FAILED

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/dab2b9214e3a086d22693cb1d491cbabe6a7a9c4?auth_token=e307fc8ab0f4d18518404bcde4880cf8ec77a1c55b427302a1b07caf0ecf923a

/wdio/features/ExploringWizard.feature

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/82c6107fc9010e5edb2228ebe3c49c1521fa2bd9?auth_token=5d64907aeef8250126fe209b90b1ad858bbfde11ce21642b6f2326ca4eab091f

/wdio/features/LockResetWallet.feature

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/cad6bbb66e42f768de7de0e5b2153556d50b4f87?auth_token=c82d1299a0c53345edcf17bc24e5960b4e59b364d71699c66c08b40fae12502f

/wdio/features/ImportCustomToken.feature - FAILED

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/dff5cc6163cb422e5e29574749341db528e513c7?auth_token=b9d8253686a519b8a72cfaeec70f479854ea28ee82f8f3d90959984295d72de1

/wdio/features/NetworkFlow.feature

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/55375aa04ef4df19ce81b923559e40dfa27e3827?auth_token=ea4acf3f6b62566e9b139115b923a75958173eacb4b65cd5ced4364673cdd6cf

/wdio/features/RequestTokenFlow.feature -  FAILED

 https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/f8a137cd9a02ba2193eda3b83979c4b2834244a4?auth_token=7b0959e392fc12b47c39c6712c646ca4ce88019771126bd3fa5355919333c88c

/wdio/features/SecurityPrivacyRememberMe.feature

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/0a3f6b8a0d732e514589a839cd89d4fa84c34414?auth_token=69da264a969521f146005f481532e08e63a2d5f2d7b3c5e4aa205692614116e2

/wdio/features/SendToken.feature

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/b40047a26355496f1faa64e0f3920eefeb80a5c2?auth_token=be1b837cc2d560066000120cd29c2ff50a91cfb2cc3fb42d42ed32152069ad5a

/wdio/features/Onboarding/OnboardingCarousel.feature 

https://app-automate.browserstack.com/builds/8921ccc14ac9135ca38531b8fc30448c28a5e573/sessions/c1283403ff6c2c0ad81e7652c8b3f1292831311a?auth_token=5f5275f58e2601d72999b3e66a3f62e6837c32e70a1b5b0cb6c1a154cb807aa9

2023-03-16 13:53 UTC, SamuelSalas commented
Detox test results:
Test Suites: 4 failed, 9 passed, 13 total
Tests:       16 failed, 120 passed, 136 total

Failed:
e2e/specs/confirmations/send-eth-flow.spec.js
e2e/specs/confirmations/advanced-gas-fees.spec.js
e2e/specs/wallet-tests.spec.js
e2e/specs/deeplinks.spec.js

2023-03-17 20:27 UTC, chrisleewilcox approved these changes
LGTM

2023-03-17 20:27 UTC, merged