add e2e start exploring flow
MetaMask/metamask-mobile pull request #5293
Opened 2022-11-24 16:53 UTC by SamuelSalas

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-11-29 18:49 UTC, cortisiko requested changes
@SamuelSalas I left a few comments. Outside of that everything looks good in my opinion.

2022-11-29 18:49 UTC, cortisiko commented on wdio/features/step-definitions/start-exploring.js
> +  await ImportFromSeedScreen.typeSecretRecoveryPhrase('fold media south add since false relax immense pause cloth just raven');
you should avoid passing in data in the test itself. In the helpers folder, there is an `accounts.js` file that contains the SRP.

2022-11-29 18:49 UTC, cortisiko commented on wdio/features/step-definitions/start-exploring.js
> +  await ImportFromSeedScreen.typeNewPassword('metapass1');
Same as above. You can import the password from the accounts.js file

> you should avoid passing in data in the test itself. In the helpers folder, there is an accounts.js file that contains the SRP.

2022-11-29 18:49 UTC, cortisiko commented on wdio/features/step-definitions/start-exploring.js
> +  await ImportFromSeedScreen.typeConfirmPassword('metapass1');
Same as above. You can import the password from the accounts.js file

> you should avoid passing in data in the test itself. In the helpers folder, there is an accounts.js file that contains the SRP.

2022-11-29 20:15 UTC, SamuelSalas commented on wdio/features/step-definitions/start-exploring.js
> +  await ImportFromSeedScreen.typeSecretRecoveryPhrase('fold media south add since false relax immense pause cloth just raven');
Of course, i just made the propers changes.

2022-11-29 22:10 UTC, cortisiko approved these changes
This looks good to me!

2022-11-29 23:46 UTC, chrisleewilcox requested changes
Please review comments

2022-11-29 23:46 UTC, chrisleewilcox commented on wdio/features/step-definitions/start-exploring.js
> +  await ImportFromSeedScreen.clickImportButton();
I think it would be much clearer if it is...

Given I have imported my wallet

2022-11-29 23:46 UTC, chrisleewilcox commented on wdio/features/step-definitions/start-exploring.js
> +  await OnboardingWizardModal.isVisible();
And I am on wallet view

But look for the wallet view screen title or something significant on the wallet view.

2022-11-29 23:46 UTC, chrisleewilcox commented on wdio/features/helpers/Gestures.js
> +  }
Not sure if this considered a gesture.  Seems like this is duplicating what the framework already does when we call elem.getText().  How are you using this in the test?

2022-11-29 23:46 UTC, chrisleewilcox commented on wdio/features/StartExploring.feature
> +    When I enter "Big Bank"
When I enter "Big Bank" for account name

2022-11-29 23:46 UTC, chrisleewilcox commented on wdio/features/screen-objects/Modals/OnboardingWizardModal.js
> +  async clickBackButton() {
tapBackButton

2022-11-29 23:46 UTC, chrisleewilcox commented on wdio/features/screen-objects/Modals/OnboardingWizardModal.js
> +  async clickNextButton() {
tapNextButton

2022-11-29 23:46 UTC, chrisleewilcox commented on wdio/features/step-definitions/start-exploring.js
> +      await OnboardingWizardModal.clickSkipTutorialButton();
replace click with tap

2022-11-30 02:12 UTC, SamuelSalas commented on wdio/features/helpers/Gestures.js
> +  }
Yes, this might be a little bit redundant. Pretty much just getting the text from the element to make the respective assertion. I'll remove it.

2022-11-30 09:47 UTC, Andepande approved these changes

2022-11-30 12:50 UTC, SamuelSalas commented on wdio/features/step-definitions/start-exploring.js
> +  await OnboardingWizardModal.isVisible();
When inspecting the screen using appium inspector, the wallet view elements are not available to be inspected when the onboarding modal is displayed.

2022-11-30 16:32 UTC, chrisleewilcox approved these changes
LGTM

2022-11-30 17:07 UTC, merged