[REFACTOR] Screen ImportFromSeed
MetaMask/metamask-mobile pull request #5299
Opened 2022-11-28 04:30 UTC by gantunesr

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_

Refactor

_2. What is the improvement/solution?_

This is a simple refactor over the component `ImportFromSeed` based on some issues detect during the QA of https://github.com/MetaMask/metamask-mobile/pull/4670, this refactor include,

1.  Refactor component from Class Component to Functional Component.
2. Code re-location.

**Screenshots/Recordings**

<img src="https://user-images.githubusercontent.com/17601467/204194315-63288143-9aab-43d2-86c7-a7e525a7b97e.PNG" width="300" />

**Issue**

Progresses https://github.com/MetaMask/mobile-planning/issues/227

**Checklist**

* [x] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-12-01 13:56 UTC, Fatxx commented on app/components/Views/ImportFromSeed/index.js
> +                  {strings('import_from_seed.new_password')}
Since we don't have any new translations on this PR, I wonder why this changed.

2022-12-01 13:56 UTC, Fatxx commented on app/components/Views/ImportFromSeed/index.js
> +ImportFromSeed.propTypes = {
Shouldn't we also refactor components to TypeScrypt?

2022-12-01 14:06 UTC, andreahaku reviewed
some minor comments

2022-12-01 14:06 UTC, andreahaku commented on app/components/Views/ImportFromSeed/index.js
> +    <SafeAreaView style={styles.mainWrapper}>
personally, I don't like those huge rendering trees. I'd make some pieces as internal components. Also some of them seems to be repeated and this componentization would be beneficial. wdyt?

2022-12-02 01:40 UTC, gantunesr commented on app/components/Views/ImportFromSeed/index.js
> +ImportFromSeed.propTypes = {
Ideally, but I have left that for a next iteration since it requires the definition of some interfaces to use across multiple components

2022-12-02 01:44 UTC, gantunesr commented on app/components/Views/ImportFromSeed/index.js
> +                  {strings('import_from_seed.new_password')}
I haven't, it's comparing two different parts of this component. The one you're seeing here is the one at line 626 before the changes

2022-12-02 01:46 UTC, gantunesr commented on app/components/Views/ImportFromSeed/index.js
> +    <SafeAreaView style={styles.mainWrapper}>
I strongly agree with you but because of time I was not able to do a major refactor on this component. I assume the responsibility of breaking down this components in the next iteration

2022-12-02 01:47 UTC, gantunesr commented on app/components/Views/ImportFromSeed/index.js
> +          navigation.replace('ManualBackupStep3');
Yes, update in [d201b86](https://github.com/MetaMask/metamask-mobile/pull/5299/commits/d201b86549665c5600f75198939b57f2e02e6a26)

2022-12-02 01:52 UTC, gantunesr commented on app/components/Views/ImportFromSeed/index.js
> +        setBiometryType(Device.isAndroid() ? 'biometrics' : biometryType);
There's actually a bug during the recover flow when the user disables biometrics, I didn't changed this logic because my intention is to fix it in a separate PR

2022-12-02 08:53 UTC, andreahaku commented on app/components/Views/ImportFromSeed/index.js
> +    <SafeAreaView style={styles.mainWrapper}>
ok thanks

2022-12-02 08:54 UTC, andreahaku approved these changes
LGTM

2022-12-06 17:48 UTC, olenapankina commented
**Tested on**
iPhone Xr iOS 16.1.1, Bitrise build 5193
Samsung Galaxy M21 Android 12, One UI Core version 4.1, Bitrise build 5194

**Issue_01:** SPR is revealed after scanning QR code
**Steps to reproduce:**
1. Launch the app
2. Select 'Import using Secret Recovery Phrase'
3. Scan QR code
4. Observe

**Actual result:** QR code scanned, 'Secret Recovery Phrase' field is showing SPR
[5299_Issue_01.mp4](https://user-images.githubusercontent.com/116747263/205982065-3d46e749-b1f0-4e6d-93f4-10bc46032e16.mp4)
**Expected result:** QR code scanned, 'Secret Recovery Phrase' field is hidden

**Issue_02:** After scanning QR code with SPR field unhidden - 'Secret Recovery Phrase' field is shown as empty 
**Steps to reproduce:**
1. Launch the app
2. Select 'Import using Secret Recovery Phrase'
3. Tap Show near the 'Secret Recovery Phrase' field
3. Scan QR code
4. Observe
6. Tap 'Show'
7. Observe

**Actual result:** Step 5 - SRP field is shown as empty
Step 7 - SPR field is filed with the SPR
[5299_Issue_02.mp4](https://user-images.githubusercontent.com/116747263/205981091-ceec1ad9-28c9-4a71-b343-f436510fb91e.mp4)
**Expected result:** Step 5 - QR code scanned, 'Secret Recovery Phrase' field is showing SPR

2022-12-08 13:20 UTC, olenapankina requested changes
**Tested on**
iPhone Xr iOS 16.1.1, Bitrise build 5193
Samsung Galaxy M21 Android 12, One UI Core version 4.1, Bitrise build 5194

**Issue_01:** SPR is revealed after scanning QR code
**Steps to reproduce:**
1. Launch the app
2. Select 'Import using Secret Recovery Phrase'
3. Scan QR code
4. Observe

**Actual result:** QR code scanned, 'Secret Recovery Phrase' field is showing SPR
[5299_Issue_01.mp4](https://user-images.githubusercontent.com/116747263/205982065-3d46e749-b1f0-4e6d-93f4-10bc46032e16.mp4)
**Expected result:** QR code scanned, 'Secret Recovery Phrase' field is hidden

**Issue_02:** After scanning QR code with SPR field unhidden - 'Secret Recovery Phrase' field is shown as empty 
**Steps to reproduce:**
1. Launch the app
2. Select 'Import using Secret Recovery Phrase'
3. Tap Show near the 'Secret Recovery Phrase' field
3. Scan QR code
4. Observe
6. Tap 'Show'
7. Observe

**Actual result:** Step 5 - SRP field is shown as empty
Step 7 - SPR field is filed with the SPR
[5299_Issue_02.mp4](https://user-images.githubusercontent.com/116747263/205981091-ceec1ad9-28c9-4a71-b343-f436510fb91e.mp4)
**Expected result:** Step 5 - QR code scanned, 'Secret Recovery Phrase' field is showing SPR

2022-12-08 15:54 UTC, gantunesr commented
@olenapankina issue_01 and issue_02 are fixed in https://github.com/MetaMask/metamask-mobile/pull/5299/commits/fe6437da38e162c7cac386329a02569e76d73f0b.

The step 5 on issue_02 is fixed in https://github.com/MetaMask/metamask-mobile/pull/5299/commits/2f08ebd7c4702ed841fcfa5977e787de15f91f30

2022-12-14 13:10 UTC, olenapankina approved these changes
Tested on
iPhone Xr iOS 16.1.1, Bitrise build 5227
Samsung Galaxy M21 Android 12, One UI Core version 4.1, Bitrise build 5226

Issue_01 and Issue_02 confirmed fixed.

2022-12-14 17:22 UTC, merged