[REFACTOR] Screen ManualBackupStep2
MetaMask/metamask-mobile pull request #5300
Opened 2022-11-28 04:41 UTC by gantunesr

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_

Refactor

_2. What is the improvement/solution?_

This is a simple refactor over the component ManualBackupStep2 based on some issues detected during the QA of https://github.com/MetaMask/metamask-mobile/pull/4670, this refactor includes,

1. Refactor component from Class Component to Functional Component.
2. Code re-location.
3. Unit tests

**Screenshots/Recordings**

<img src="https://user-images.githubusercontent.com/17601467/204195279-6c8513cd-7156-4107-af3c-a7be0269c26f.PNG" width="300" />

**Issue**

Progresses https://github.com/MetaMask/mobile-planning/issues/227

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

2022-11-29 13:38 UTC, tommasini commented on app/components/Views/ManualBackupStep2/index.js
> +  const validateWords = useCallback(() => {
Since this return a value, should be used `useMemo` instead?

2022-11-30 10:26 UTC, blackdevelopa commented on app/components/Views/ManualBackupStep2/index.js
> +        confirmTestID={'manual-backup-step-2-continue-button'}
nitpick: Can testID be some constant?

2022-12-01 13:43 UTC, gantunesr commented on app/components/Views/ManualBackupStep2/index.js
> +  const validateWords = useCallback(() => {
[2778e34](https://github.com/MetaMask/metamask-mobile/pull/5300/commits/2778e34b6bb521922e788f69c92f3700bfcb9274)

2022-12-01 13:43 UTC, gantunesr commented on app/components/Views/ManualBackupStep2/index.js
> +        confirmTestID={'manual-backup-step-2-continue-button'}
[c07e0d9](https://github.com/MetaMask/metamask-mobile/pull/5300/commits/c07e0d94b3930929db24013c1bb6bc16d61df6d3)

2022-12-01 13:52 UTC, andreahaku approved these changes
LGTM

2022-12-01 13:55 UTC, blackdevelopa approved these changes

2022-12-01 13:58 UTC, Fatxx commented on app/components/Views/ManualBackupStep2/index.js
> +ManualBackupStep2.propTypes = {
Shouldn't we be refactoring also to TypeScrypt?

2022-12-01 15:41 UTC, gantunesr commented on app/components/Views/ManualBackupStep2/index.js
> +ManualBackupStep2.propTypes = {
Ideally, but I have left that a next iteration since it requires the definition of some interfaces to use across multiple components

2022-12-05 20:45 UTC, olenapankina commented
**Tested on** 
iPhone Xr iOS 16.1.1
Samsung Galaxy M21 Android 12, One UI Core version 4.1
refactor/manual-backup-step-2 commit d54aaa195caae2b5f3b3b45c86651da232b04f61

**Issue_01:** Unable to confirm SPR
**Steps to reproduce:**
1. Launch freshly installed application
2. Go through 'Create a new wallet' journey 
3. Land on 'Confirm Secret Recovery Phrase' page
4. Observe

**Actual result:** error page, `View: Root. TypeError: F is not a function. (In 'F(), 'F' is false)`
**Note:** reproducible from SPR reminder as well
[5300_Issue_01.mov](https://user-images.githubusercontent.com/116747263/205736873-756a796d-9fa1-4dba-8eaa-3588b562f5a7.mov)
![5300_Issue_01](https://user-images.githubusercontent.com/116747263/205736865-dd80a39e-5c6d-4dc9-9d62-b4dbf58b0060.PNG)

2022-12-08 03:56 UTC, gantunesr commented
@olenapankina Fixed in https://github.com/MetaMask/metamask-mobile/pull/5300/commits/4422a1ad68e7eaab9b0fd6401a254c97b3e24ddd

2022-12-08 13:24 UTC, olenapankina requested changes
**Tested on** 
iPhone Xr iOS 16.1.1
Samsung Galaxy M21 Android 12, One UI Core version 4.1
refactor/manual-backup-step-2 commit d54aaa195caae2b5f3b3b45c86651da232b04f61

**Issue_01:** Unable to confirm SPR
**Steps to reproduce:**
1. Launch freshly installed application
2. Go through 'Create a new wallet' journey 
3. Land on 'Confirm Secret Recovery Phrase' page
4. Observe

**Actual result:** error page, `View: Root. TypeError: F is not a function. (In 'F(), 'F' is false)`
**Note:** reproducible from SPR reminder as well
[5300_Issue_01.mov](https://user-images.githubusercontent.com/116747263/205736873-756a796d-9fa1-4dba-8eaa-3588b562f5a7.mov)
![5300_Issue_01](https://user-images.githubusercontent.com/116747263/205736865-dd80a39e-5c6d-4dc9-9d62-b4dbf58b0060.PNG)

2022-12-12 17:49 UTC, olenapankina approved these changes
Tested on
iPhone Xr iOS 16.1.1, Bitrise build 5235
Samsung Galaxy M21 Android 12, One UI Core version 4.1, Bitrise build 5234

Issue_01 confirmed fixed

2022-12-12 18:12 UTC, merged