Initial iPad adjustments
MetaMask/metamask-mobile pull request #5312
Opened 2022-11-28 23:43 UTC by wachunei

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

This PR is a refreshed version of #3512.
This PR adds the minimum adjustments for the UI to work on iPad, allowing a better browser experience.
Main Fixes: 
- Onboarding carousel rendering
- NFT dimension rendering
- Receive modal rendering
- Fullscreen browsing on iPad
- Better tabs display on iPad

**Screenshots/Recordings**

- [Current version without adjustments on iPad](https://imgur.com/a/7m8I96v)
- [Version with adjustments on iPad](https://imgur.com/a/1F7OQgv)

**Issue**

Progresses #4574 

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

2022-11-30 01:52 UTC, gantunesr reviewed
From a first review this LGTM. Here are some notes to take into account,

- The component `OnboardingCarousel` was refactored.
- The component `AddressQRCode` was refactored.
- The component `TabThumbnail` was refactored.

2022-11-30 01:52 UTC, gantunesr commented on app/components/Views/AddressQRCode/index.js
> +        style={[styles.closeIcon, { width: contentStyle.size + 36 * 2 }]}
Can you explain the reason of ` + 36 * 2`?

2022-11-30 02:55 UTC, wachunei commented on app/components/UI/Tabs/index.js
> +            key={`${tab.id}-${index}`}
Yes, there was a duplication if I recall correctly.

2022-11-30 03:09 UTC, wachunei commented on app/components/Views/AddressQRCode/index.js
> +        style={[styles.closeIcon, { width: contentStyle.size + 36 * 2 }]}
`36 * 2` is making it full width and match the View below, so the icon sits at the end of the QR code view vertically (see screenshots [1](https://user-images.githubusercontent.com/1024246/204698290-8a25334b-b307-42ed-acbd-33dd251a5ebf.png), [2](https://user-images.githubusercontent.com/1024246/204698298-5abca639-9eb0-42b8-a7da-2293bbe57fbe.png))

Because:
```jsx
      <View style={styles.qrCodeContainer}> {/* this has padding 28 */}
        <View style={styles.qrCode}> {/* this has padding 8 */}
          <QRCode
            value={`ethereum:${selectedAddress}`}
            size={contentStyle.size} // this is contentStyle.size
          />
        </View>
      </View>
```

So a full width is `28 + 8 + contentStyle.size + 8 + 28` = `36 + contentStyle.size + 36`

2022-11-30 03:12 UTC, wachunei commented on app/components/Views/AddressQRCode/index.js
> +        style={[styles.closeIcon, { width: contentStyle.size + 36 * 2 }]}
I changed it to: 
```tsx
      <TouchableOpacity
        style={[
          styles.closeIcon,
          {
            width:
              contentStyle.size +
              (styles.qrCode.padding + styles.qrCodeContainer.padding) * 2,
          },
        ]}
        onPress={closeModal}
        testID={'close-qr-modal'}
      >
```

2022-11-30 15:29 UTC, gantunesr commented on app/components/Views/AddressQRCode/index.js
> +        style={[styles.closeIcon, { width: contentStyle.size + 36 * 2 }]}
Nice

2022-12-16 23:03 UTC, cortisiko requested changes
@wachunei sending this back your way. 

The device used: iPad Air 5th Gen

Landscape mode issues:
1. On the wallet view, [the touch area for “tokens” is too small/off](http://recordit.co/OsBH2NMz7Q) 
2. [I am unable to tap on the burger menu](http://recordit.co/QzUDupajBa)  
3. When I get to the token details view, I am unable to tap on the back button
4. [When I open the import NFT view I am unable to enter the address and ID, Furthermore, I am unable to tap on the back button](http://recordit.co/QzUDupajBa). The same thing happens when I try to import tokens or search for tokens
 
 **_Not sure if these need design confirmation but below is layout issues in landscape mode:_**

5. There is some extra spacing on the [onboarding tutorial modal](https://www.screencast.com/t/5dOGqEsHXldD) 
6. modals as well as CTA’s looks a bit stretched out. See [here](https://www.screencast.com/t/Q7EshGFsuyE)

2023-01-10 20:33 UTC, sethkfman commented
@wachunei What do you think about removing the requirement for landscape on iPad and only allow portrait. Then when we have more capacity we can have a story for landscape.

2023-01-10 23:36 UTC, wachunei commented
I think we should fix the behavior of the overlay once for all, even if the rotation is disabled there are multitasking features in both OS that make the app width change. Foldable phones too.

--
Pedro Pablo Aste Kompen
On 10 Jan 2023 17:34 -0300, sethkfman ***@***.***>, wrote:
> @wachunei What do you think about removing the requirement for landscape on iPad and only allow portrait. Then when we have more capacity we can have a story for landscape.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-04-07 07:01 UTC, edsonayllon commented
> I think we should fix the behavior of the overlay once for all, even if the rotation is disabled there are multitasking features in both OS that make the app width change. Foldable phones too.
> […](#)
> -- Pedro Pablo Aste Kompen
> On 10 Jan 2023 17:34 -0300, sethkfman ***@***.***>, wrote: @wachunei What do you think about removing the requirement for landscape on iPad and only allow portrait. Then when we have more capacity we can have a story for landscape. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

I thought the scope of this was iPad.

I'd prefer a better iPad experience now than the current version. And wouldn't mind landscape being disabled.

2023-10-09 20:31 UTC, closed without merging

2024-03-13 04:29 UTC, edsonayllon commented
Any update on this?