Verify Contract Details
MetaMask/metamask-mobile pull request #5327
Opened 2022-12-01 07:14 UTC by blackdevelopa

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
https://github.com/MetaMask/MetaMask-planning/issues/179

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-12-14 23:53 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/VerifyContractDetails/VerifyContractDetails.tsx
> +  const learnMore = () => Linking.openURL('');
Todo: Replace the empty string with the right link

2022-12-14 23:53 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/VerifyContractDetails/VerifyContractDetails.tsx
> +  const imageUtil = (symbol: string) => {
Todo: Rewrite this to account for the different tokens

2022-12-14 23:53 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/VerifyContractDetails/VerifyContractDetails.tsx
> +            type: 'Token',
Todo: `Token` should be either ERC20 or 721

2022-12-14 23:53 UTC, blackdevelopa commented on app/component-library/components-temp/Contracts/ContractBoxBase/ContractBoxBase.tsx
> +          <Identicon address={contractAddress} diameter={40} />
In hindsight, this component may not need to have image passed into it. Confirm again.

2022-12-15 09:55 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/VerifyContractDetails/VerifyContractDetails.tsx
> +  const imageUtil = (symbol: string) => {
Also, should there be a default image for unknown token?

2022-12-15 17:07 UTC, blackdevelopa commented on app/component-library/components-temp/Contracts/ContractBoxBase/ContractBoxBase.tsx
> +          <Identicon address={contractAddress} diameter={40} />
The response to this is a yes at this time.

2022-12-15 19:16 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/VerifyContractDetails/VerifyContractDetails.tsx
> +  const learnMore = () => Linking.openURL('');
Removed for now

2022-12-16 20:21 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/VerifyContractDetails/VerifyContractDetails.tsx
> +  const imageUtil = (symbol: string) => {
Done

2023-01-13 11:53 UTC, jpuri commented on app/component-library/components-temp/Contracts/ContractBox/ContractBox.constants.ts
> +export const TOKEN_SYMBOL = 'D';
constant names already look quite explanatory

2023-01-13 11:55 UTC, jpuri commented on app/component-library/components-temp/Contracts/ContractBoxBase/ContractBoxBase.tsx
> +        </View>
Nested ternary is avoidable.

2023-01-13 11:56 UTC, jpuri commented on app/component-library/components-temp/Contracts/ContractBoxBase/ContractBoxBase.types.ts
> +  contractLocalImage?: ImageSourcePropType | null;
Both `null` and `?` are I guess not needed.

2023-01-13 11:57 UTC, jpuri commented on app/components/UI/ApproveTransactionReview/AddNickNameHeader/index.tsx
> +  const handlePress = () => closeModal();
reason for not writing it inline `() => closeModal()`

2023-01-13 12:02 UTC, jpuri commented on app/components/UI/ApproveTransactionReview/VerifyContractDetails/VerifyContractDetails.tsx
> +        </Text>{' '}
Is nested text needed ? Also `{' '} ` can be removed.

2023-01-16 11:56 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/VerifyContractDetails/VerifyContractDetails.tsx
> +        </Text>{' '}
Removed. https://github.com/MetaMask/metamask-mobile/pull/5327/commits/6a1feeaded183e0ce53049b8c8be34dbd758f470

2023-01-16 11:56 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/AddNickNameHeader/index.tsx
> +  const handlePress = () => closeModal();
Removed. https://github.com/MetaMask/metamask-mobile/pull/5327/commits/6a1feeaded183e0ce53049b8c8be34dbd758f470

2023-01-16 11:56 UTC, blackdevelopa commented on app/component-library/components-temp/Contracts/ContractBoxBase/ContractBoxBase.types.ts
> +  contractLocalImage?: ImageSourcePropType | null;
Cleaned up. https://github.com/MetaMask/metamask-mobile/pull/5327/commits/6a1feeaded183e0ce53049b8c8be34dbd758f470

2023-01-16 11:57 UTC, blackdevelopa commented on app/component-library/components-temp/Contracts/ContractBoxBase/ContractBoxBase.tsx
> +        </View>
https://github.com/MetaMask/metamask-mobile/pull/5327/commits/6a1feeaded183e0ce53049b8c8be34dbd758f470

2023-02-07 11:54 UTC, tommasini reviewed
Hey, @blackdevelopa great job here!

Left some questions/suggestions.

2023-02-07 11:54 UTC, tommasini commented on app/components/UI/ApproveTransactionReview/VerifyContractDetails/VerifyContractDetails.tsx
> +  const filterTokensByTokenSymbol = tokens.filter(
Would make sense turn this to an useMemo?

2023-02-07 11:54 UTC, tommasini commented on app/components/UI/ApproveTransactionReview/VerifyContractDetails/VerifyContractDetails.tsx
> +  const showBlockExplorerIcon = () => {
Make sense to use useCallback here?

2023-02-07 11:54 UTC, tommasini commented on app/components/UI/ApproveTransactionReview/VerifyContractDetails/VerifyContractDetails.tsx
> +            hasBlockExplorer={Boolean(hasBlockExplorer)}
The intention is this to be false only if `findBlockExplorerForRpc` returns undefined?

2023-02-07 13:02 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/AddNickname/index.tsx
> +                onPress={copyaddress}
Good catch. https://github.com/MetaMask/metamask-mobile/pull/5327/commits/b3c58d06fe3f54b920af46ee07f9ebb0dcd4e596

2023-02-07 13:02 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/VerifyContractDetails/VerifyContractDetails.tsx
> +  const filterTokensByTokenSymbol = tokens.filter(
https://github.com/MetaMask/metamask-mobile/pull/5327/commits/b3c58d06fe3f54b920af46ee07f9ebb0dcd4e596

2023-02-07 13:03 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/VerifyContractDetails/VerifyContractDetails.tsx
> +  const showBlockExplorerIcon = () => {
https://github.com/MetaMask/metamask-mobile/pull/5327/commits/b3c58d06fe3f54b920af46ee07f9ebb0dcd4e596

2023-02-07 13:04 UTC, blackdevelopa commented on app/components/Views/ApproveView/Approve/index.js
> +    const filteredSavedContactList = savedContactListToArray.filter(
Valid thought, but I don't think it's the best solution at this time

2023-02-07 13:41 UTC, tommasini approved these changes
Thanks! LGTM!

2023-02-15 08:38 UTC, jpuri commented on app/component-library/components-temp/Contracts/ContractBox/ContractBox.constants.ts
> +export const TOKEN_SYMBOL = 'D';
`TOKEN_SYMBOL` is for only storybook. It will be nice to add a prefix to indicate that, or move it to story component.

`TOKEN_SYMBOL = 'D';` does not seems to be useful at other places.

2023-02-15 08:43 UTC, jpuri commented on app/constants/address.ts
> +export default '0x2990079bcdEe240329a520d2444386FC119da21a';
Hey, is above really needed to be a re-usable constant value ?

2023-02-15 08:47 UTC, jpuri approved these changes
I added some NIT feedbacks.

PR is huge and touches important part of code. Thus QA is very important.

For complex changes smaller PRs with test coverage help a lot.

2023-02-15 09:19 UTC, blackdevelopa commented on app/constants/address.ts
> +export default '0x2990079bcdEe240329a520d2444386FC119da21a';
Yeah, about this. This address is used in a couple places in the codebase. I think they can all be extracted away to this constant. Wydt?

2023-02-15 09:20 UTC, blackdevelopa commented on app/component-library/components-temp/Contracts/ContractBox/ContractBox.constants.ts
> +export const TOKEN_SYMBOL = 'D';
They are used only for storybook.

2023-02-15 09:46 UTC, jpuri commented on app/constants/address.ts
> +export default '0x2990079bcdEe240329a520d2444386FC119da21a';
I see its used for testing only. It will be useful to indicate that in filename or variable name.

May be create a constant file just for all test related variables.

2023-02-15 10:05 UTC, blackdevelopa commented on app/constants/address.ts
> +export default '0x2990079bcdEe240329a520d2444386FC119da21a';
Updated. https://github.com/MetaMask/metamask-mobile/pull/5327/commits/9a57539a3c3fc3b2cd2a490df614ea57c8debe3a

2023-02-21 12:38 UTC, seaona commented
Some QA findings for clarification:

1. When I am using a network without any BlockExplorer set, if I click on the Transaction Details, I can still see the icons for going to BlockExplorer. I believe they should be hidden in this case

https://user-images.githubusercontent.com/54408225/220340849-18f71d69-7106-47b3-9d91-1f6db1050e09.mp4

2. When I click on Copy icon for an address of the Verify Contract Details screen, I can see 2 messages. One indicating the address has been copied to the clipboard, but another one indicating `Shell pasted from your clipboard`. I believe this last one should not be displayed

https://user-images.githubusercontent.com/54408225/220341392-a8483441-478d-4de8-8d06-d4530400fd59.mp4

3. When I click on Copy on the Tx Details from the Approval screen, the address is not copied anymore and I get a Warning (not sure if it's related)

https://user-images.githubusercontent.com/54408225/220342302-73bd3ffc-2fef-4965-8583-fbd28f89f114.mp4

4. When I try to Approve a token that I have on my Wallet, I can see that only the first letter is displayed and the alignment is not correct. See  [UNI token](https://goerli.etherscan.io/address/0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984#writeContract), or [DAI](https://etherscan.io/token/0x6b175474e89094c44da98b954eedeac495271d0f#writeContract):

![image](https://user-images.githubusercontent.com/54408225/220345933-a29ace76-041f-4018-8eee-e3c3aea12aa5.png)

![image](https://user-images.githubusercontent.com/54408225/220344908-d84a71e4-bacf-48f8-856f-ff0c53795419.png)

5. About the text: `Contract requesting spending cap` could we have something more generic? On Approve transaction, we can approve both to EOA and Contract addresses. Should we double-check this? (I kind of re-call that the same happens in Extension) @bschorchit 

https://user-images.githubusercontent.com/54408225/220343354-86d2c985-4fcc-47ad-bd2e-8a71b8dba337.mp4

2023-03-01 10:58 UTC, seaona commented
QAd after the changes, some comments on the issues mentioned above:
1. I can see that the icons for BlockExplorer are now hidden, when I am using a network without any BlockExplorer set
2. @blackdevelopa clarified this is a specific setting from the device. You can turn it on or off. See more [here](https://nerdschalk.com/android-12-how-to-turn-off-clipboard-access-warnings-pasted-from-your-clipboard-pop-ups/)
3. I can see this working
5. I can see this fixed
6. This might be treated separately (if needed)

The only one I still see some things to clarify is point number 4. Now I've observed the following:

- When I am approving an ERC20 Token, which **I have in my wallet**
   - I can see the token logo - which is correct
   - I don't see the token symbol (i.e. DAI) - I think we should display the symbol, according to the specs (see pic below)

https://user-images.githubusercontent.com/54408225/222119452-9602ba00-5865-46a6-a767-ff5e949dd5ba.mp4

![image](https://user-images.githubusercontent.com/54408225/222118928-c25a1e27-8bff-4e24-9ce2-fe6fa5c6534a.png)


- When I am approving an ERC20 Token, which **I don't have in my wallet** 
   - I can see there is no logo -- I think we should display an identicon here
   - I can see a letter T (the initial of the token symbol) -- I think we should not display any initial?

https://user-images.githubusercontent.com/54408225/222118298-3bbb8b9e-035b-4fc1-bfa6-030387252462.mp4

- When I am approving an ERC20 Token, which **I have in my wallet, but does not have a logo**
   - I can see a question mark on the logo placeholder -- I think here we should display an identicon 

https://user-images.githubusercontent.com/54408225/222119686-c796fde6-1f26-4b7b-898d-df0c475f6b1d.mp4


cc @bschorchit @blackdevelopa

2023-03-01 18:44 UTC, bschorchit commented
> When I am approving an ERC20 Token, which I have in my wallet
> I can see the token logo - which is correct
> I don't see the token symbol (i.e. DAI)

I agree the token symbol should be displayed as nickname. This was part of the specs [here](https://github.com/MetaMask/MetaMask-planning/issues/179)

> Scenario: Arrive on the Verify contract details modal
> 
> GIVEN a user is on the Token Allowance confirmation screen
> WHEN user taps to view contract details
> THEN the Verify contract details modal is displayed
> AND correct token icon is displayed for token contract
> AND **correct token symbol is displayed for token contract**

2023-03-01 18:46 UTC, bschorchit commented
> When I am approving an ERC20 Token, which I don't have in my wallet
> I can see there is no logo -- I think we should display an identicon here
> I can see a letter T (the initial of the token symbol) -- I think we should not display any initial?

I agree that identicon for the address without any initial should be the fallback here for unknown tokens.

2023-03-01 18:49 UTC, bschorchit commented
> When I am approving an ERC20 Token, which I have in my wallet, but does not have a logo
> I can see a question mark on the logo placeholder -- I think here we should display an identicon

I think in this case the icon should be the same that we currently display in wallet view for consistency - is it a question mark or the token initial?

2023-03-03 10:34 UTC, seaona commented
After last changes, I can see that if I click to Verify Contract details MM crashes, with the error `undefined is not an object (evaluating networkProvider.rpcTarget)`.

It's pointing to line 12 of `VerifyContractDetails.tsx`

https://user-images.githubusercontent.com/54408225/222698064-b4b25d4a-5e49-44fc-b3ab-a1367cb9a999.mp4

2023-03-06 14:01 UTC, seaona commented
The issue above is fixed. Few things:

- This PR needs to go over the dev review process again before being merged, so I've added the `needs-red-review` label
- This PR cannot be introduced in the 6.2 release, as we need to fix the pending issues (the different tickets that @bschorchit created)
- Once all issues are fixed, all the corresponding PRs should target the same release and we can add the release label

Let me know if this sounds good @bschorchit @blackdevelopa

2023-03-09 05:39 UTC, bschorchit commented
> The issue above is fixed. Few things:
> 
> * This PR needs to go over the dev review process again before being merged, so I've added the `needs-red-review` label

Would you mind giving this a final re-review once you have a chance, @jpuri ? Once this is re-reviewed, we'll merge this PR and address the non-blocking issues found during QA as part of different the tickets tagged above. 🧡

2023-03-09 15:46 UTC, jpuri commented on app/constants/address.ts
> +export default TEST_ADDRESS;
Will be better to have a constants file dedicated to tests.

2023-03-09 15:51 UTC, jpuri commented
Looks good for merge 👍 

cc @bschorchit , @blackdevelopa

2023-03-09 15:51 UTC, jpuri commented
Plz ignore PR closing, that was accidental.

2023-03-10 14:11 UTC, bschorchit commented
We're now following the practice of 2 reviews for confirmations mobile PRs, would you mind also giving this a re-review to check the latest changes @tommasini? Thank you 🧡

2023-03-10 15:37 UTC, tommasini requested changes

2023-03-10 15:37 UTC, tommasini commented on app/components/UI/ApproveTransactionReview/index.js
> +    await ClipboardManager.setString(address || transaction.to);
Is there any reason for this callback to `transaction.to`?

From what I can see this function `copyContractAddress` is passed by props to the `TransactionReviewDetailsCard` component and `VerifyContractDetails ` component.

On `VerifyContractDetails` that prop is not optional so I conclude that it would always be defined
On `TransactionReviewDetailsCard` it shouldn't be defined either if I'm not missing something

I think we do not need the fallback to `transaction.to`, let me know your thoughts here

2023-03-10 15:37 UTC, tommasini commented on app/components/UI/ApproveTransactionReview/index.js
> +        address={address || to}
We only render the blockExplorer when the state variable `showBlockExplorerModal ` is true and we set that variable to true at the same time we set the state variable `address` with the `tokenAddress`  prop value of`VerifyContractDetails`. I think there is no necessity for a callback to  `to` here 

Let me know your thoughts

2023-03-10 15:38 UTC, tommasini commented
Thanks for the tag @bschorchit!
Let me know your thoughts @blackdevelopa 🙌

2023-03-10 17:14 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/index.js
> +        address={address || to}
Good catch. The `transaction.to` isn't also necessary here as well. [47b18cc](https://github.com/MetaMask/metamask-mobile/pull/5327/commits/47b18ccb727aea4875076a2f234ffdfafecd0210)

2023-03-10 17:15 UTC, blackdevelopa commented
Thank you @tommasini. Good catch.

2023-03-10 17:31 UTC, tommasini approved these changes
Thanks! LGTM! Awesome work! 🚀

2023-03-13 10:14 UTC, seaona commented
Looks good! I merge the PR.
Notice, for SetApprovalForAll and Revoke custom screens, we should also add the Verify Contract Details. At the moment, we don't have custom screens for these cases on Mobile, but whenever we add them, we should take this into account.

![image](https://user-images.githubusercontent.com/54408225/224672096-06e63f3d-09d8-4be5-9470-2a534293ee18.png)

cc @bschorchit @blackdevelopa

2023-03-13 10:14 UTC, merged