Add Custom Network during on boarding
MetaMask/metamask-mobile pull request #5334
Opened 2022-12-01 23:51 UTC by tommasini

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
Now it's possible to add a custom network during onboarding, that enables the user to choose not to use a infura rpc url.

**Screenshots/Recordings**
https://recordit.co/PIQjzWnaue

**Test Cases**
Case1:
* Fresh install the app
* Press settings on meta metrics screen
* add another rpc url for ethereum
* finish on boarding (create a new wallet and importing an existing one) 
* go to settings -> networks
* check active network and active network rpc url

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-12-02 17:41 UTC, cortisiko commented
this is not ready for QA since it did not go through dev review. Once we pass dev review. Feel free to add back the "needs-qa" label.

2022-12-02 19:12 UTC, sethkfman commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +        nickname = DEFAULT_MAINNET_NAME;
I think we should add a DEFAULT_MAINNET_CUSTOM_NAME = Ethereum Main Custom. Using the existing name could cause confusion

2022-12-02 19:14 UTC, sethkfman commented on app/constants/network.js
> +export const DEFAULT_MAINNET_NAME = 'Default Main Network';
Consider updating per comment where value is used.

2022-12-03 00:14 UTC, sethkfman approved these changes
LGTM

2022-12-06 00:55 UTC, cortisiko requested changes
@Cal-L I am done with testing. Below are my findings:

**issue 1**
from the MetaMetrics view if i were to open the custom RPC form:
enter an RPC url
hit save/confirm/set. basically, tapping the CTA confirms the RPC url.
i am taken back to the MetaMetrics view.
if i were to return back to the custom RPC url form, the saved RPC URL does not appear: http://recordit.co/lEz0ONEIZa

**Issue 2**
Custom RPC for mainnet edit the RPC after wallet creation and confirm you are not seeing duplicate networks. See recording: http://recordit.co/owxMG7DvX6

**Issue 3**
This one is sort of sensitive. [Here is the slack chat](https://consensys.slack.com/archives/C04E6UR5WEM/p1670277127391459?thread_ts=1670271057.998489&cid=C04E6UR5WEM) with the bug description.

2022-12-07 17:53 UTC, Cal-L commented
Closing and moved to #5362

2022-12-07 17:53 UTC, closed without merging