Align buttons with Figma
MetaMask/metamask-mobile pull request #5343
Opened 2022-12-02 17:41 UTC by brianacnguyen

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-01-10 11:50 UTC, Fatxx commented
Hey @brianacnguyen,

Can you please provide more details about what's being done here? Also if applicable add screenshots or screen recordings of the respective changes.

2023-01-10 11:51 UTC, Fatxx requested changes, later dismissed
Please provide more details

2023-01-26 21:30 UTC, brianacnguyen commented
> Please provide more details

done

2023-01-26 21:31 UTC, brianacnguyen commented
> Please provide more details

done

2023-02-03 22:49 UTC, brianacnguyen commented
@Fatxx Hey can you review this PR?

2023-02-04 00:22 UTC, Cal-L approved these changes
Left some comments. Can merge after fix.

2023-02-04 00:22 UTC, Cal-L commented on app/component-library/components/Buttons/Button/variants/ButtonLink/ButtonLink.tsx
> +  size = ButtonSize.Md,
Put into consts

2023-02-04 00:22 UTC, Cal-L commented on app/component-library/components/Buttons/Button/variants/ButtonLink/ButtonLink.tsx
>    onPress,
Do not need to deconstruct

2023-02-04 00:22 UTC, Cal-L commented on app/component-library/components/Buttons/Button/variants/ButtonLink/ButtonLink.styles.ts
> +    base: Object.assign({ backgroundColor: 'transparent' }, style) as ViewStyle,
Use colors from util

2023-02-04 00:22 UTC, Cal-L commented on app/component-library/components/Buttons/Button/variants/ButtonLink/ButtonLink.tsx
> +  const labelColor = useMemo(() => {
Make sure label color is also applied to `Text`

2023-02-04 00:22 UTC, Cal-L commented on app/component-library/components/Buttons/Button/variants/ButtonLink/ButtonLink.tsx
> +          style={styles.base}
Use .baseText

2023-02-04 00:22 UTC, Cal-L commented on app/component-library/components/Buttons/Button/foundation/ButtonBase/README.md
> +### `isDanger`
Update usage with `width` and `isDanger`

2023-02-04 00:22 UTC, Cal-L commented on app/component-library/components/Buttons/Button/foundation/ButtonBase/ButtonBase.tsx
> +  width = ButtonWidthTypes.Auto,
Put into const

2023-02-04 22:16 UTC, brianacnguyen commented on app/component-library/components/Buttons/Button/variants/ButtonSecondary/ButtonSecondary.stories.tsx
> +    ButtonWidthTypes,
It's possible but can be misleading. Since the fixed/number option is meant to be for a fallback, I think it's okay to omit this from storybook for now

2023-02-05 01:43 UTC, merged