E2e appium address book-Send flow tests
MetaMask/metamask-mobile pull request #5373
Opened 2022-12-08 22:45 UTC by Andepande

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

- Increasing Appium test automation coverage
- Added tests related to the Address Book and Send flow

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [x] Tests are included if applicable
* [ ] Any added code is fully documented

2022-12-08 23:16 UTC, cortisiko requested changes
looks good to me but left a few comments

2022-12-08 23:16 UTC, cortisiko commented on wdio/features/screen-objects/SendScreen.js
> +    async tapOnText(text){
small tings but why is it called tapOnText? Is there a specific text that you are tapping on?

2022-12-08 23:16 UTC, cortisiko commented on wdio/features/screen-objects/Contacts.js
> +    async tapOnText(text){
but why call it tapOnText? Is there a specific text that you are tapping on?

2022-12-08 23:16 UTC, cortisiko commented on wdio/features/screen-objects/WalletMainScreen.js
> +    return Selectors.getElementByPlatform(NAVBAR_TITLE_NETWORKS2);
why the name change?

2022-12-09 02:49 UTC, chrisleewilcox requested changes
Please review comments.

2022-12-09 02:49 UTC, chrisleewilcox commented on wdio/features/AddressFlow.feature
> +    And I enter a contract address "0xdac17f958d2ee523a2206206994597c13d831ec7" in the sender's input box
When

2022-12-09 02:49 UTC, chrisleewilcox commented on wdio/features/AddressFlow.feature
> +    And I tap the 'Save' button
When

2022-12-09 02:49 UTC, chrisleewilcox commented on wdio/features/AddressFlow.feature
> +    When I tap the 'Edit Contact' button which is enabled to confirm the change
consistency with "" for passing in values.

2022-12-09 02:49 UTC, chrisleewilcox commented on wdio/features/AddressFlow.feature
> +    And I tap on 'Edit' button to edit Saved contact details
""

2022-12-09 02:49 UTC, chrisleewilcox commented on wdio/features/AddressFlow.feature
> +    Then I should see the edited name "Gusto" contact under 'Recents' on the send screen
"" or remove quotes.

2022-12-09 02:49 UTC, chrisleewilcox commented on wdio/features/AddressFlow.feature
> +    And I navigate back to main wallet screen
When

2022-12-09 05:08 UTC, Fatxx requested changes
Please check my comment that is a lot of code that is not tests related

2022-12-09 05:08 UTC, Fatxx commented on app/components/UI/AssetSearch/AssetOverview/index.js
> +import AssetActionButton from '../../AssetActionButton';
Why do you have all this code changes from the implementation side? Seems strange to me that you need to change all this code. Did you branch out from something that is not on main yet?

2022-12-09 11:01 UTC, Andepande commented on app/components/UI/AssetSearch/AssetOverview/index.js
> +import AssetActionButton from '../../AssetActionButton';
I think they are just eslint changes, no changes were made to those on my part.

2022-12-09 17:57 UTC, chrisleewilcox requested changes
Please see comments

2022-12-09 17:57 UTC, chrisleewilcox commented on wdio/features/screen-objects/SendScreen.js
> +     async isContinueTextVisivle(){
....Visible()

2022-12-09 17:57 UTC, chrisleewilcox commented on wdio/features/screen-objects/SendScreen.js
> +    async tapAddAddressButton(){
Want to get in the habit of not being too specific of the actual element.  Is there anything else on this view that is call "Add Address"?  No need to say Button.  Just tapAddAddress().

2022-12-09 17:57 UTC, chrisleewilcox commented on wdio/features/screen-objects/SendScreen.js
> +     async tapCancelButton(){
tapCancel() is probably better.

2022-12-09 17:57 UTC, chrisleewilcox commented on wdio/features/screen-objects/WalletMainScreen.js
> +  async tapBurgerButton() {
Is this a duplicate?  I already added the ability to tap on the Burger Icon.  What's the difference?

2022-12-09 17:57 UTC, chrisleewilcox commented on wdio/features/screen-objects/WalletMainScreen.js
> +  async tapBurgerButtonByXpath() {
Why have multiple ways of taping the burger icon?

2022-12-09 17:57 UTC, chrisleewilcox commented on wdio/features/step-definitions/network-flow.js
> +  await driver.pause(wait);
Why have two separate lines to do this?

2022-12-09 17:57 UTC, chrisleewilcox commented on wdio/features/step-definitions/network-flow.js
>    await driver.pause(wait);
Why have two separate lines to do this?

2022-12-09 17:57 UTC, chrisleewilcox commented on wdio/features/testIDs/Screens/WalletView.testIds.js
> +  'hamburger-menu-button-wallet';
Two burger ids, why?

2022-12-10 01:59 UTC, Andepande commented on wdio/features/screen-objects/SendScreen.js
> +    async tapOnText(text){
So there were instances where instead of creating a function for just one button, re-using functions and passing the specific button text from cucumber made more sense, especially when navigating through the application to get to the specific test screen.

2022-12-10 02:00 UTC, Andepande commented on wdio/features/screen-objects/Contacts.js
> +    async tapOnText(text){
So there were instances where instead of creating a function for just one button, re-using functions and passing the specific button text from cucumber made more sense, especially when navigating through the application to get to the specific test screen.

2022-12-10 02:02 UTC, Andepande commented on wdio/features/screen-objects/WalletMainScreen.js
> +    return Selectors.getElementByPlatform(NAVBAR_TITLE_NETWORKS2);
We had duplicate ID names, to avoid confusion I renamed them slightly.

2022-12-10 02:03 UTC, Andepande commented on wdio/features/AddressFlow.feature
> +    Then I should see a warning message "This address is a token contract address. If you send tokens to this address, you will lose them."
May become too long and un-readable, easier to read when split

2022-12-10 02:07 UTC, Andepande commented on wdio/features/helpers/Gestures.js
> +    await elem.isDisplayed();
Kept this during when I trying figure out cause of intermittent failures, but like you said framework does this already, removed

2022-12-10 02:13 UTC, Andepande commented on wdio/features/AddressFlow.feature
> +    Then I should see a warning message "This address is a token contract address. If you send tokens to this address, you will lose them."
done

2022-12-10 02:18 UTC, Andepande commented on wdio/features/helpers/Gestures.js
> +    await elem.isDisplayed();
Removed, was only there research purposes

2022-12-13 13:39 UTC, Andepande commented on app/components/UI/AssetSearch/AssetOverview/index.js
> +import AssetActionButton from '../../AssetActionButton';
Reverted the commit that made these changes

2022-12-13 13:43 UTC, Andepande commented on wdio/features/screen-objects/WalletMainScreen.js
> +  async tapBurgerButton() {
tapping on the burger icon doesn't always invoke the burger menu so I added another which taps on the surrounding element.

2022-12-13 13:52 UTC, Andepande commented on wdio/features/step-definitions/network-flow.js
> +  await driver.pause(wait);
Previous PR comments requested the wait be a separate const variable

2022-12-13 13:52 UTC, Andepande commented on wdio/features/step-definitions/network-flow.js
>    await driver.pause(wait);
Previous PR comments requested the wait be a separate const variable

2022-12-13 13:53 UTC, Andepande commented on wdio/features/testIDs/Screens/WalletView.testIds.js
> +  'hamburger-menu-button-wallet';
One for the Icon, the other for the surrounding button element. Kept getting inconsistent results with burger icon.

2022-12-13 23:25 UTC, cortisiko approved these changes
looks good. Just some small nit picks. Also run detox to ensure nothing isn't broken.

2022-12-13 23:25 UTC, cortisiko commented on app/components/UI/Navbar/index.js
> +        //testID={'hamburger-menu-button-wallet'}
remove this guy

2022-12-13 23:25 UTC, cortisiko commented on app/components/UI/AccountOverview/index.js
> +import { SEND_BUTTON_ID } from '../../../../wdio/features/testIDs/Screens/WalletView.testIds';
there is a linting issue here. Do you use `SEND_BUTTON_ID` ?

2022-12-13 23:25 UTC, cortisiko commented on app/components/UI/AccountOverview/index.js
> +  Platform,
There is a lint issue here. Is platform ever used?

2022-12-13 23:25 UTC, cortisiko commented on wdio/features/step-definitions/send-flow.steps.js
> +    const wait = 500;
You should probably set this globally. That way when on line 136 you do not need to define `wait` again

2022-12-16 17:44 UTC, Fatxx requested changes
Left some comments

2022-12-16 17:44 UTC, Fatxx commented on app/components/UI/NavbarTitle/index.js
> +            {...generateTestId(Platform, NAVBAR_TITLE_NETWORKS2)}
Can we get a better name for this variable? Using numbers as names is a bad programming practice.

2022-12-16 17:44 UTC, Fatxx commented on wdio/features/helpers/Helper.js
> +class Helper {
This seems redundant, what's the reason behind it?

2022-12-16 17:44 UTC, Fatxx commented on wdio/features/step-definitions/network-flow.js
> +  await Helper.driverTimeout(10000);
Again, I don't see any benefit of having this inside a class method

2022-12-19 13:28 UTC, Fatxx commented on wdio/features/screen-objects/WalletMainScreen.js
> +    await driver.pause(wait);
You created that util but you're not using it here

2022-12-20 07:47 UTC, chrisleewilcox requested changes, later dismissed
Please review changes.

2022-12-20 14:03 UTC, Fatxx approved these changes

2022-12-20 17:08 UTC, merged