Auth refactor (contined)
MetaMask/metamask-mobile pull request #5374
Opened 2022-12-08 23:35 UTC by owencraston

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-12-09 00:36 UTC, owencraston commented on app/components/hooks/DeleteWallet/useDeleteWallet.ts
>        await Engine.resetState();
@sethkfman I added this back since you removed it. Should we bring this call into one of the Authentication methods?

2022-12-09 00:36 UTC, owencraston commented on app/components/hooks/DeleteWallet/useDeleteWallet.ts
> +      await Authentication.newWalletAndKeyChain(`${Date.now()}`, {
@sethkfman why are we calling this method to reset the wallet?

2022-12-09 21:07 UTC, owencraston commented on app/core/Authentication/Authentication.ts
> +    password: string,
we should wipe the sensitive params from memory. Thins like parsedSeed, password

2022-12-09 21:09 UTC, owencraston commented on app/core/Authentication/Authentication.ts
> +  resetVault = async (): Promise<void> => {
Maybe we can call this when we delete the wallet in useDeleteWallet vs `await Authentication.newWalletAndKeyChain(`${Date.now()}`, {`

2022-12-09 21:20 UTC, owencraston commented on app/components/Views/ChoosePassword/index.js
> +        this.keyringControllerPasswordSet = true;
Look into if this is needed

2022-12-09 21:22 UTC, owencraston commented on app/components/Views/Onboarding/index.js
>        this.props.navigation.navigate('HomeNav');
// TODO verify that password set is still needed

2022-12-09 21:24 UTC, owencraston commented on app/components/Views/Onboarding/index.js
>        this.props.navigation.navigate('HomeNav');
look at onPressCreate in ChoosePassword screen to see how this variable is set

2022-12-09 21:30 UTC, owencraston commented on app/components/Views/ChoosePassword/index.js
> +    // const authData = await Authentication.getType();
delete commented code

2022-12-09 21:30 UTC, owencraston commented on app/components/Views/ChoosePassword/index.js
> +        await AsyncStorage.removeItem(NEXT_MAKER_REMINDER);
maybe we can delete this too ?

2022-12-09 21:40 UTC, owencraston commented on app/components/Views/ChoosePassword/index.js
>        await AsyncStorage.removeItem(SEED_PHRASE_HINTS);
Look into consolidating `EXISTING_USER` with the keyring controllers existing vault. 

- Login vault creation is not needed once we remove the encryption lib 
- Initial init of the nav stack. when you kill the app and reload it will either show onboarding or login
- Onboarding/index.js screen. Hides or shows an unlock button
-

2022-12-09 21:46 UTC, owencraston commented on app/core/Authentication/Authentication.ts
> +
Look into adding a method that checks if there is an existing user.

2022-12-12 22:23 UTC, owencraston commented on app/components/Nav/App/index.js
> +        animationRef?.current?.play();
@sethkfman we have to finish the animation after the auth logic has finished to maintain solid UX.

2022-12-12 22:30 UTC, owencraston commented on app/components/Nav/App/index.js
> +    if (prevNavigator.current || !navigator) return;
This ensures we are only running this once. See similar branch IO logic on line [248](https://github.com/MetaMask/metamask-mobile/blob/6056f5ec99bac18a71328542ad75312ce006c868/app/components/Nav/App/index.js#L248)

2022-12-13 20:21 UTC, owencraston commented on app/components/Views/Login/index.js
> +      this.props.navigation.replace('HomeNav');
we are calling replace here vs navigate to prevent users from being able to go back to the previous screen.

2022-12-13 20:22 UTC, owencraston commented on app/components/Nav/App/index.js
> +        navigator.navigate('HomeNav');
todo: check if navigate is okay here or if we need to use replace. Should the user be able to go back?

2022-12-13 20:22 UTC, owencraston commented on app/components/Views/LockScreen/index.js
> +      this.props.navigation.navigate('HomeNav');
todo: check if navigate is okay vs replace. Should we be able to go back?

2022-12-13 20:22 UTC, owencraston commented on app/components/Views/Onboarding/index.js
>        this.props.navigation.navigate('HomeNav');
todo: check if navigate is okay vs replace. Should we be able to go back?

2022-12-13 20:23 UTC, owencraston commented on app/components/Views/Onboarding/index.js
>        this.props.navigation.navigate('HomeNav');
todo: check if navigate is okay vs replace. Should we be able to go back?

2022-12-13 20:31 UTC, owencraston commented on app/components/Nav/App/index.js
> +  const authOnLoadAuthLock = useRef(false);
Is this needed? if not remove. If we do use it, add the `Ref` suffix to the name.

2022-12-13 20:35 UTC, owencraston commented on app/components/Nav/App/index.js
> +        await Authentication.logout(false);
maybe we need to explicit about navigating to the login screen. In case for some reason the screen underneath is not login.

2022-12-13 20:36 UTC, owencraston commented on app/components/Nav/App/index.js
> +        await Authentication.logout(false);
future: we might as well explicitly navigate

2022-12-13 20:38 UTC, owencraston commented on app/components/Nav/App/index.js
> +          'App: Max Attempts Reached',
maybe change this to something more generic about failed logins? Not a big deal though

2022-12-13 20:40 UTC, owencraston commented on app/components/UI/DrawerView/index.js
> +  onPressLogout = async () => {
Change to lock.

2022-12-13 20:41 UTC, owencraston commented on app/core/Authentication/Authentication.ts
> +  logout = async (reset = true): Promise<void> => {
change to lock()

2022-12-13 20:52 UTC, owencraston commented on app/components/Views/ImportFromSeed/index.js
>    async componentDidMount() {
Maybe we should rename this file to ImportFromSRP

2022-12-13 20:53 UTC, owencraston commented on app/components/Views/LockScreen/index.js
> +  logOut = async () => {
Lock()

2022-12-13 20:55 UTC, owencraston commented on app/components/Views/LockScreen/index.js
> +    this.props.navigation.navigate('Login');
use ROUTES object

2022-12-13 21:03 UTC, owencraston commented on app/components/Views/ResetPassword/index.js
> +    try {
future todo: there are a few instances of this method in the app with some slight differences. In the future we should unify these and maybe improve the performance.

2022-12-13 21:15 UTC, owencraston commented on app/components/Views/Settings/SecuritySettings/Sections/LoginOptionsSettings.tsx
> +        const stateValue = Device.isAndroid()
Look into using the Platform.select instead of `Device`

2022-12-13 21:19 UTC, owencraston commented on app/components/Views/Settings/SecuritySettings/Sections/RememberMeOptionSection.tsx
> +        Boolean(authType.type === AUTHENTICATION_TYPE.REMEMBER_ME),
No need for the type cast as Boolean

2022-12-13 21:24 UTC, owencraston commented on app/components/hooks/DeleteWallet/useDeleteWallet.ts
> +      await Authentication.logout();
maybe we need to call navigate to...onboarding?

2022-12-13 21:45 UTC, owencraston commented on app/util/test/testSetup.js
> +// crypto.getRandomValues
triple check what mocks are still needed

2022-12-13 21:45 UTC, owencraston commented on package.json
> +    "polyfill-crypto.getrandomvalues": "^1.0.0",
double check if still needed

2022-12-13 21:51 UTC, owencraston commented on app/components/Views/ChoosePassword/index.js
> +        await AsyncStorage.removeItem(NEXT_MAKER_REMINDER);
I can probably remove this

2022-12-13 21:51 UTC, owencraston commented on app/components/Views/ChoosePassword/index.js
>        await AsyncStorage.removeItem(SEED_PHRASE_HINTS);
for the future

2022-12-13 21:53 UTC, owencraston commented on app/core/Authentication/Authentication.ts
> +
for the future

2022-12-13 21:57 UTC, owencraston commented on app/components/Nav/App/index.js
> +        navigator.navigate('HomeNav');
Move the navigate call into the if statement

2022-12-14 18:59 UTC, owencraston commented on app/core/Authentication/Authentication.ts
> +    password: string,
Looking more into this, it seems we simply cannot control what is stored in memory or not in JS (makes sense since its garbage collected) see stack overflow question with exact same use case: https://security.stackexchange.com/questions/192387/how-to-securely-erase-javascript-parameters-after-use

- by assigning it to a new value you are just creating a new instance, not doing anything with the old pointer

2022-12-14 19:08 UTC, owencraston commented on app/core/Authentication/Authentication.ts
> +  resetVault = async (): Promise<void> => {
I am going to leave this for a future improvement as the scope is growing fast on this PR

2022-12-14 21:03 UTC, owencraston commented on app/components/Views/ChoosePassword/index.js
> +        await AsyncStorage.removeItem(NEXT_MAKER_REMINDER);
Looking here, there are no get or set calls for this storage flag, indicating that it is not needed
<img width="436" alt="Screenshot 2022-12-14 at 1 02 56 PM" src="https://user-images.githubusercontent.com/22918444/207713195-05327b38-5fc2-4557-9089-58d38c6cf86a.png">

2022-12-14 23:08 UTC, owencraston commented on app/core/Authentication/Authentication.ts
> +    password: string,
I went ahead and reset these values anyway as a good first step.

2022-12-14 23:52 UTC, owencraston commented on app/components/Views/LockScreen/index.js
> +    this.props.navigation.navigate('Login');
addressed in [this](https://github.com/MetaMask/metamask-mobile/pull/5374/commits/cf2c46da8a1c4963016eb2ffc562248c856cb043) commit

2022-12-14 23:54 UTC, owencraston commented on app/components/Views/ImportFromSeed/index.js
>    async componentDidMount() {
addressed in [this](https://github.com/MetaMask/metamask-mobile/pull/5374/commits/bef62adec066b2910114e0cc518cce62cc4c6660) commit

2022-12-15 00:26 UTC, owencraston commented on app/components/Nav/App/index.js
> +          navigator.navigate(Routes.ONBOARDING.HOME_NAV);
@Cal-L as it stands now replace is not available on this navigator (idk why). Using `navigator.replace` through an error so I reverted back to using navigate. Based on my tests it seems that it works in the other places I added it.

2022-12-15 00:27 UTC, owencraston commented on app/components/Views/ImportFromSecretRecoveryPhrase/index.js
> +const ImportFromSecretRecoveryPhrase = ({
I renamed this component to better match the UX.

2022-12-15 00:32 UTC, owencraston commented on app/components/Views/Settings/SecuritySettings/Sections/LoginOptionsSettings.tsx
> +        const stateValue = Device.isAndroid()
I wasn't able to get this to work easily so I left it as it. For the sake of speed.

2022-12-15 00:33 UTC, owencraston commented
@Cal-L @sethkfman @gantunesr I believe I have addressed the comments made in our review session. I am looking for another review 🙏 .

2022-12-15 21:09 UTC, Cal-L commented on app/components/Nav/App/index.js
> +          navigator.navigate(Routes.ONBOARDING.HOME_NAV);
NP, were you able to confirm that you're not able to swipe back to navigate back to the login screen though?

2022-12-15 21:35 UTC, owencraston commented on app/components/Nav/App/index.js
> +          navigator.navigate(Routes.ONBOARDING.HOME_NAV);
Confirmed I can't navigate back to the Login screen on Iphone.

2022-12-15 22:07 UTC, Cal-L approved these changes
LGTM

2022-12-20 18:25 UTC, tommasini commented
Hey @owencraston , this PR addresses this [issue](https://github.com/MetaMask/metamask-mobile/issues/5404)?

2022-12-20 18:29 UTC, owencraston commented
@tommasini yes. This will take a while to qa and ship though given the size/importance of the chance.

2023-01-07 00:58 UTC, plasmacorral commented
Experiencing multiple e2e critical test failures that would block this PR if I were anywhere close to complete.

2023-01-09 21:53 UTC, plasmacorral commented
MB#3: While using FACE_ID, the fingerprint icon shows in the password entry box instead of the FACE_ID icon.

Steps:
1. Have biometric auth turned on with a device using FACE_ID
2. fail FACE_ID auth (cover front camera)
3. Tap 'Cancel' to return to Lock page
4. Note fingerprint icon presented in password entry box, instead of FACE_ID icon (as shown in prod v5.12.3 today)

Screenshot of v5.12.3 production lock screen when FACE_ID is active (left), this branch showing Fingerprint icon when FACE_ID is auth method (right):
<div style="display: inline-block"> <img width="190" src="https://user-images.githubusercontent.com/32695229/211415603-42fa7cdd-8ac5-46c5-a8ca-ec60660f86b0.png"><img width="190" src="https://user-images.githubusercontent.com/32695229/211415656-654806ea-1a4f-4149-a7b1-bf78c6a662f5.png"></div>

2023-01-09 21:56 UTC, owencraston commented
MB#1 has been addressed in [this commit](https://github.com/MetaMask/metamask-mobile/pull/5374/commits/c82cfd55d26abd61ca5b791daab325af14ebfaf6) ✅

2023-01-10 00:21 UTC, owencraston commented
MB resolved in [this commit](https://github.com/MetaMask/metamask-mobile/pull/5374/commits/bd9611fca2abf19dfd776247ef1c8b124c924cee).

![IMG_4353](https://user-images.githubusercontent.com/22918444/211433938-dd10c479-c914-47d2-a009-1d4c02ed7cf7.png)

2023-01-11 23:18 UTC, olenapankina requested changes
Tested on
iPhone Xr iOS 16.1.1
Samsung Galaxy M21 Android 12, One UI Core version 4.1
commit b7d4b8cd9f6649d4856e7d6913ae839f3f7fc929

**OP_01:** iOS Incorrect error message 
**Steps to reproduce:**

1. Launch freshly installed application
2. Import SRP
3. Deny system request to use FaceID/TouchID
4. Observe

**Actual result:** '**Error:** Error: The user name or passphrase you entered is not correct.' [5374 OP_01](https://user-images.githubusercontent.com/116747263/211929896-3a4e7a62-e58d-44af-bf75-a136759562dd.PNG)
**Expected result:** prod: 'Error: The user name or passphrase you entered is not correct.'
Would be great to change the error message while we are at it. But the 'error error' message - is a regression.

**OP_02:** When creating a wallet, I'm observing console error: 'The user name or passphrase you entered is not correct.' [5374 OP_02](https://user-images.githubusercontent.com/116747263/211932007-30011ddc-c590-4fc5-b4f2-02fd5b424078.PNG) - presented when biometrics request was disabled

**OP_03:** flashing screen is presented after resetting password. 
**Actual result:** flashing screen is presented after resetting password. on the first try: confirmation pop-up was flashing as well [5374 OP_03.MP4](https://user-images.githubusercontent.com/116747263/211930568-07519e14-d689-4598-a0d8-71b1e378bcf4.MP4)
**Expected result:** the screen is not flashing - prod

**OP_04:** Toggles are not placed in the correct order in Settings
**Actual result:** Unlock with device passcode -> Turn on Remember Me
**Expected result:** Turn on Remember Me -> Unlock with device passcode

**OP_05:** After disabling login with the device PIN user is prompted with device PIN
**Steps to reproduce:**

1. Create new wallet with Biometrics OFF
2. Skip SRP backup
3. Disable 'login with device PIN'
4. Observe

**Actual result iOS:** I'm prompted with device PIN after successfully entering it the first time. After force quitting the application - I'm prompted with device PIN; when accessing settings, etc. Toggle is OFF
**Actual result Android:** After force quitting the application - I'm prompted with device PIN; when accessing settings, etc. Toggle is not displayed in settings right after turning it to OFF
**Expected result:** user is not prompted with device PIN after step 3 until enabled

[5374_OP_05.mov](https://user-images.githubusercontent.com/116747263/211937944-abae0cba-b51b-4df3-8c26-a36728b392d9.mov)

**OP_06:** User is prompted with biometrics after disabling it in settings
**Steps to reproduce:**

1. Launch the app for the first time
2. Import SPR, Biometrics ON
3. Disable Biometrics in settings
4. Force quit the app
5. Observe

**Actual result:** User is constantly prompted with Biometrics, Remember me is turned ON by system, not user
**Expected result:** User is not prompted with Biometrics until enabled

**OP_07:** Biometrics icon is presented in the password field after importing the wallet with Biometrics toggle OFF on the first launch
**Steps to reproduce:**

1. Create new wallet with Biometrics OFF
2. Skip SRP backup
3. Force quit the app
4. Open app
5. Observe

**Actual result:** biometrics icon is presented on the login screen in the password field
**Expected result:** biometrics icon is not presented

2023-01-12 19:54 UTC, olenapankina requested changes
Tested on
commit b7d4b8cd9f6649d4856e7d6913ae839f3f7fc929

**OP_08:** iOS - Incorrect < AUTH name > on the login screen

iPhone Xr iOS 16.1.1, Face ID
**Actual result:** Unlock with Biometrics
**Expected result:** Unlock with Face ID - prod

iPhone 8 Plus, Touch ID
**Actual result:** Unlock with Biometrics
**Expected result:** Unlock with Touch ID

2023-01-12 20:20 UTC, plasmacorral commented
MB_04-Similar to OP_7 but observed on android:

Pixel 5a
Android 13

When I decline biometric auth on importing an SRP when my device has a fingerprint and is set to use PIN to unlock the screen, MMM defaults to authenticate with Device PIN.  In production V5.12.3, this scenario results in Password authentication on MMM.

Production 5.12.3: https://recordit.co/dWDbAKIQTI
Auth refactor branch: https://recordit.co/dufsce4aJX

Steps:
1. Have fingerprint present on device
2. Launch MMM and import an SRP
3. Turn off biometrics when creating password
4. get to wallet view
5. Kill app and relaunch
6. Note that device PIN toggle is presented
7. Biometric fingerprint icon presented in password entry box

2023-01-12 20:41 UTC, plasmacorral commented
MB_05 Biometric fingerprint icon in password entry box does not open fingerprint authentication request

Commit https://github.com/MetaMask/metamask-mobile/commit/b7d4b8cd9f6649d4856e7d6913ae839f3f7fc929
Pixel 5a
Android 13

When I cancel on the initial fingerprint request and am taken to the lock page, I expect to be able to tap the fingerprint icon presented in the password entry box and initiate fingerprint authentication.

Production 5.12.1: https://recordit.co/Caucu5tJMj
Auth refactor branch: https://recordit.co/HjNDkLCFw7

Steps:
1. Import an SRP and use biometric authentication
2. Kill the app and relaunch
3. Cancel at the fingerprint auth prompt
4. At lock page, tap the fingerprint icon within the password entry box
5. Note that auth refactor branch does not currently open the fingerprint auth prompt

2023-01-13 00:58 UTC, owencraston commented
@olenapankina regarding OP 5: I believe I was able to resolve this issue by removing useless loading state in the settings screen. See the following video for demo. 

https://user-images.githubusercontent.com/22918444/212212736-843203d2-fe55-4c67-9047-17f441cc1789.MP4

2023-01-13 01:01 UTC, owencraston commented
@olenapankina regarding OP 1 and 2: I am not seeing the issue mentioned in OP 1. Below is a video of what I see. In my case after the denial we are navigated to the backup flow and the wallet is created with a password. 

https://user-images.githubusercontent.com/22918444/212212944-5d202b3a-d8c7-4a5e-ac04-f3070d3298a9.mov

For OP 2 and the console warning. I don't think this is a major problem since in order for us to catch the denial of the biometrics that error must be logged.

2023-01-13 21:48 UTC, olenapankina commented
@owencraston please note that OP_01 is Import using SRP case, not Create new wallet flow

Tested on
iPhone Xr iOS 16.1.1
Samsung Galaxy M21 Android 12, One UI Core version 4.1
commit 400da0801837efe352b1a127c25aaa20b89c0aed 

**Steps to reproduce:**

1. Launch freshly installed application
2. Create new wallet with biometrics OFF
3. Skip SRP backup - observe video
4. Force quit and relaunch the application
5. Observe Biometrics system request pops up
6. Observe password entry field - **OP_07** 
7. Observe PIN toggle ON - **MB_04**
8. Turn PIN toggle OFF, login with password
9. Tap Protect Wallet from Yellow warning
10. Observe video

**OP_09:** Video is not playing in 'Secure your wallet' flow
**Actual result:** Step3, Step10 - video is not playing 
**Expected result:** video is playing - prod 

**OP_10:** Biometrics system request pop-up when biometrics toggle was turned OFF
**Actual result:** Step5 - biometrics system request pops-up
**Expected result:** no biometrics system request - prod 

![5374_OP_09-10 Actual result.MP4](https://user-images.githubusercontent.com/116747263/212424768-67413eac-9a88-4007-95da-ecfcf46902a4.MP4)
![5374_OP_09-10 Expected result.MP4](https://user-images.githubusercontent.com/116747263/212424848-e7e678e8-aa5b-4531-8c0d-ac51eb9dda02.MP4)

2023-01-13 22:24 UTC, plasmacorral commented
In the video here for OP_05: https://github.com/MetaMask/metamask-mobile/pull/5374#issuecomment-1381172658

I believe there is still an issue in that the device PIN auth is being automatically enabled when biometrics are declined. When the user declines biometrics today in production, they end up with password authentication. 

https://recordit.co/F28UUu4QxK

2023-01-13 23:18 UTC, plasmacorral commented
MB_06: Android - Potential variation on OP_10- Remember me enabled after disabling biometrics from Settings> Security & Privacy

Commit https://github.com/MetaMask/metamask-mobile/commit/b7d4b8cd9f6649d4856e7d6913ae839f3f7fc929
Pixel 5a
Android 13

I attempted to disable biometric authentication from settings and notice that the Remember Me toggle was somehow moved to the ON position without my interaction.  Like OP_10,  I am noticing biometric authentication being requested after I disabled through the toggle in settings. Curiously, it is always requested twice, even when the first request seemingly succeeds. This is to say I have to provide my finger twice to proceed, every time.  I would also note that while in this condition, biometric auth is requested to even open settings>security and privacy.

Steps:

1. Create new wallet with biometrics on
2. Get to wallet view
3. Kill app
4. Unlock with biometrics and get back to wallet view
5. Turn biometrics off in settings>security & Privacy
6. Give the finger, as requested
7. Kill app
8. Give the finger, as requested
9. Give the finger again, as requested
10. Get to wallet view
11.  Go to settings>security & Privacy
12. Give the finger, as requested

2023-01-14 00:47 UTC, plasmacorral commented
MB_07: Android- `Copy to clipboard` CTA is missing in Show private key

Copy to clipboard option for the private key exists in production v5.12.1 on this android 13 device, but not in this branch.  The 'Done' CTA also appears higher on the screen than in production.

Commit https://github.com/MetaMask/metamask-mobile/commit/b7d4b8cd9f6649d4856e7d6913ae839f3f7fc929
Pixel 5a
Android 13

Steps:

1. Create new wallet
2. From wallet view go to settings and reveal private key
3. Note CTA to copy to clipboard is missing

Production on the left below
<div style="display: inline-block"> <img width="190" src="https://user-images.githubusercontent.com/32695229/212442076-14b73bae-f945-467f-9108-9daf6d11de5c.png"><img width="200" src="https://user-images.githubusercontent.com/32695229/212442103-f58c0e64-6e27-42d4-a7e8-ea4802077787.png"></div>

2023-01-14 01:04 UTC, plasmacorral commented
MB_08: Android- `ManualBackupStep1` presented when fingerprint authentication requested for SRP backup

Commit https://github.com/MetaMask/metamask-mobile/commit/b7d4b8cd9f6649d4856e7d6913ae839f3f7fc929
Pixel 5a
Android 13

Steps:

1. Create new wallet with biometric authentication
2. Skip backup prompts
3. Go through Settings>Security & Privacy> Backup Now
4. After you tap `Start` authentication is requested
5. Observe background


Still Screenshot:

<img src="https://user-images.githubusercontent.com/32695229/212442730-cd094ab7-cf90-426b-8dd0-3cd33e94789d.png" width="150"/>


Video of production v5.12.1:
https://recordit.co/e0TTyZFlXr

Video from Commit https://github.com/MetaMask/metamask-mobile/commit/b7d4b8cd9f6649d4856e7d6913ae839f3f7fc929: https://recordit.co/ogL00WI745

2023-01-14 04:00 UTC, plasmacorral commented
MB_09: Android- App returns to Onboarding view instead of Lock screen after Auto lock time exceeded

Commit https://github.com/MetaMask/metamask-mobile/commit/b7d4b8cd9f6649d4856e7d6913ae839f3f7fc929
Pixel 5a
Android 13
Device screen timeout: 15 seconds
MMM auto lock: 5 seconds

When I import an SRP and then multitask, when I return to the app I can see and interact with the onboarding flow instead of Lock screen. When the lockscreen does eventually appear, biometric authentication is not available.

Steps:

1. Import SRP with biometric auth
2. set auto-lock to 5 seconds
3. Switch to settings and set screen timeout to 15 seconds
4. Return to app
5. Swipe up to dismiss at authentication prompt
6. Note a second biometric authentication prompt flashes (this also happens in production)
7. Relaunch app again
8. Note that authentication is showing above onboarding (instead of Lock screen)
9. Provide authentication this time, when prompted
10. Tap get started
11. Provide authentication this time, when prompted
12. Note the Import/Create CTAs presented
13. Then Lock screen is presented
14. Tapping biometric fingerprint icon does NOT launch authentication request

Commit https://github.com/MetaMask/metamask-mobile/commit/b7d4b8cd9f6649d4856e7d6913ae839f3f7fc929: https://recordit.co/XjI3NzN5P4

Production v5.12.1: https://recordit.co/Euk0zmc0Ic

2023-01-16 20:04 UTC, owencraston commented
✅ OP1: I was able to fix the error message issue. It was as simple as extracting the message from the error with `error.message`
![IMG_4438](https://user-images.githubusercontent.com/22918444/212757933-f4f88b5c-5594-4c06-ad13-78cebbdc5cf4.png)

2023-01-16 21:42 UTC, owencraston commented
@olenapankina @plasmacorral the issues are getting hard to manage in this thread so I [created a table in notion](https://www.notion.so/be5d38d5290c4dae8d9db43a1b935fa7?v=450c6074c3854e08b0fd8bb93bfaa1ab) for us to better track the problems. Please update this page as you report new problems.

2023-01-17 01:36 UTC, owencraston commented
## ✅ OP_6 resolved
- fixed by resetting the generic password
https://user-images.githubusercontent.com/22918444/212790575-c6a6576e-735d-4f0d-90e0-918f72cb9aab.MP4

## ✅ OP_5 resolved
- fixed by removing the loading state as mentioned in this [comment](https://github.com/MetaMask/metamask-mobile/pull/5374#issuecomment-1381172658)
- partially resolved with the same fix as OP_6 above
https://user-images.githubusercontent.com/22918444/212790639-597f57e5-bc3a-4103-a04b-c876cf1400d2.MP4

2023-01-17 22:42 UTC, plasmacorral commented
MB_10: Android- Biometric toggle not present when changing password

Commit https://github.com/MetaMask/metamask-mobile/commit/b7d4b8cd9f6649d4856e7d6913ae839f3f7fc929
Pixel 5a
Android 13

Steps to reproduce:

1. Have device setup with biometric authentication present
2. Import SRP with biometric toggle in the default = ON position
3. Request password change in settings
4. Note that biometric toggle is not presented


Production v 5.12.3 on the left, Commit https://github.com/MetaMask/metamask-mobile/commit/b7d4b8cd9f6649d4856e7d6913ae839f3f7fc929 on the right:
`<div style="display: inline-block"> <img width="190" src="https://user-images.githubusercontent.com/32695229/213028186-9c5d0e98-36c4-4b4c-a2c5-7ac2c675c256.png"><img width="185" src="https://user-images.githubusercontent.com/32695229/213028229-45cbcd35-a933-4783-88d8-08177d04f504.png"></div>

2023-01-18 19:53 UTC, olenapankina commented
**Tested on**
iPhone Xr iOS 16.1.1
Samsung Galaxy M21 Android 12, One UI Core version 4.1
commit https://github.com/MetaMask/metamask-mobile/pull/5374/commits/0b39ed6406ae54d3e6c12c208c480c004097e790

**OP_12:** Unlock with device PIN is automatically on in settings when user creates wallet with biometrics OFF

**Steps to reproduce:**

1. Launch freshly installed application
2. Create a wallet with biometrics off
3. Skip SRP backup
4. Go to Settings-Security&Privacy
5. Observe device passcode toggle being on

**Actual result:** device pin is automatically on in settings when user creates wallet with biometrics OFF [5374_OP_12 Actual result.mp4](https://user-images.githubusercontent.com/116747263/213278254-8ba04ba5-f1f7-4a8d-bda1-77e506918ecb.mp4)
**Expected result:** device pin is off in settings and on login screen - prod, 5.12.3 [5374_OP_12 Expected result.mp4](https://user-images.githubusercontent.com/116747263/213278389-18d65c39-0f1d-4c2e-9a9c-97779ed780be.mp4)

**OP_13:** HD key account disappears after changing password

**Steps to reproduce:**

1. Import account from SRP
2. Tap Account icon 
3. Tap Create new account - created account selected
4. Change password in settings
5. Go back to wallet view
6. Observe accounts

**Actual result:** only 1 account exists [5374_OP_13 Actual result.mov](https://user-images.githubusercontent.com/116747263/213280520-c942f500-6d7a-461e-9f1f-9a848fc97188.mov)
**Expected result:** all accounts exist, HD key account selected [5374_OP_13 Expected result.mp4](https://user-images.githubusercontent.com/116747263/213280599-ab82bd9a-2a85-4437-a248-e86109298940.mp4)
**Note**: Works as expected on prod and main commit 61fe46512adff7e9f466754b552c3112fc8db4ee

2023-01-18 23:48 UTC, plasmacorral commented
MB_11: Android- Dismissing fingerprint/device PIN authentication 

When I dismiss the device pin/finger authentication prompt and turn off Device pin toggle that is presented on the lock screen, then authentication toggles no longer being presented in settings.  Even though the toggle is no longer displayed, the device pin authentication is still requested to unlock or even to view Settings>Security&Privacy.

The expectation here would be to see both device PIN and biometric toggles shown in the off position within settings, and no longer be asked for device PIN or fingerprint if the device pin authentication toggle is turned off OR not available to the user.

commit https://github.com/MetaMask/metamask-mobile/commit/0b39ed6406ae54d3e6c12c208c480c004097e790
Pixel 5a
Android 13

Steps:
1.  Import SRP with biometrics present and turned on, land at wallet view
2. In Settings>Security&Privacy turn off biometric authentication toggle
3. Provide fingerprint authentication when prompted
4. In Settings>Security&Privacy  turn ON device PIN authentication toggle
5. provide password when requested
6. tap 'Use PIN' and enter the correct device PIN
7. From wallet view check settings
8. Kill app and relaunch
9.  Authenticate with device PIN
10. land at wallet view and confirm Settings>Security&Privacy still shows device PIN authentication toggle ON
11.  Kill app and relaunch
12.  Dismiss authentication prompt by tapping outside of it or swiping down
13. Enter password and tap Unlock
14. When fingerprint/device pin is requested dismiss it without providing authentication
15. Note error presented "Error: Error: Error: Cancel"
16. Tap to turn 'Unlock with device PIN" toggle at lock screen to OFF
17. Tap unlock
18. Access Settings>Security&Privacy and note that you are prompted for PIN or fingerprint authentication
19. Can dismiss this by swiping down or tapping outside of the area (may ask twice)
20. Note that biometric toggles are not presented
21. Kill app and relaunch
22. Note that biometric authentication is requested even though it is supposed to be off and is absent from setting




In production v5.12.1 I am unable to take the flow above beyond step 15, because production currently shows no unlock with device pin toggle on the lock screen to disable.  At this step, production shows a remember me toggle in the off position.  I am able to login with the password and can see in settings that the remember me enable toggle is in the on position and device PIN has been turned off.  Production no longer asks for device pin or fingerprint.

Video from commit https://github.com/MetaMask/metamask-mobile/commit/0b39ed6406ae54d3e6c12c208c480c004097e790: 
https://recordit.co/8KYRjbhceW

2023-01-19 00:35 UTC, plasmacorral commented
MB_12: IOS (only)- SRP backup demand is not initiated when account has >$.01 USD

When a new wallet is created, if the account is funded or if an account is imported/paired with >$.01 USD then the user is supposed to be required to complete SRP backup.   This is working on Android, but the backup demand is not initiated on iOS 15.

commit https://github.com/MetaMask/metamask-mobile/commit/0b39ed6406ae54d3e6c12c208c480c004097e790
iPhone 13 mini
iOS 15.6.1
 
Steps
1. Create new account
2. Import a private key OR pair with a Keystone having >$.01 USD
3. Note that demand to protect your wallet is not presented

Expectation: User should not be able to proceed without completing SRP backup.

Screenshot below shows immediately after binding to Keystone, iOS on the left and android on the right.
<img src="https://user-images.githubusercontent.com/32695229/213328023-c8b11a31-768f-4ff3-b986-428b2845aae5.png" width="200"/>

2023-01-19 20:04 UTC, olenapankina commented
**Tested on**
iPhone Xr iOS 16.1.1
Samsung Galaxy M21 Android 12, One UI Core version 4.1
commit https://github.com/MetaMask/metamask-mobile/commit/0b39ed6406ae54d3e6c12c208c480c004097e790

**OP_14:** Imported account is not selected after changing password
**Steps to reproduce:**

1. Import account from SRP (1st)
2. Tap Account icon
3. Tap Import an account - imported account selected (2nd)
4. Change password in settings
5. Go back to the wallet view
6. Observe accounts

**Actual result:** 1st account is selected [5374_OP_14 Actual result.mov](https://user-images.githubusercontent.com/116747263/213521929-0ed186b8-9560-4567-a4a5-6479ae2d8f11.mov)
**Expected result:** Imported account (2nd) is selected - prod 5.13.0 [5374_OP_14 Expected result.mp4](https://user-images.githubusercontent.com/116747263/213521842-aa813f2f-99b9-4a41-b3c2-d3212787449e.mp4)

2023-01-19 21:23 UTC, plasmacorral commented
MB_12: Android and IOS- When engaging a toggle but refusing authentication UI should not reflect the change

commit https://github.com/MetaMask/metamask-mobile/commit/0b39ed6406ae54d3e6c12c208c480c004097e790
Pixel 5a with Android 13
&
iPhone 13 mini with iOS 15.6.1

If I tap to turn on or off the biometric or device pin toggles in Settings>Security & Privacy but then refuse the authentication prompts, the toggle does not revert until I exit and return to Security & Privacy.

Expectation: Security & Privacy toggles accurately present.  If a change is started that requires authentication but authentication is not satisfied, that change should be reverted in the UI.

Steps:
1. Be at wallet view with device PIN/passcode authentication active
2. From wallet view access Settings>Security & Privacy
3. Device pin/passcode toggle should be presented ON
4. Tap it to turn off Device pin/passcode authentication
5. Cancel/back/dismiss authentication prompts for PIN and password to return to Security & Privacy
6. Note device pin/passcode toggle shows OFF
7. Navigate back to exit Security & Privacy 
8. Go back in to Security & Privacy and the toggle will reflect ON as expected

Video of commit https://github.com/MetaMask/metamask-mobile/commit/0b39ed6406ae54d3e6c12c208c480c004097e790 on both devices.

2023-01-23 20:46 UTC, olenapankina commented
**Tested on** 
iPhone Xr iOS 16.1.1
Samsung Galaxy M21 Android 12, One UI Core version 4.1
commit https://github.com/MetaMask/metamask-mobile/commit/0b39ed6406ae54d3e6c12c208c480c004097e790 

**OP_05 and OP_06 are not fixed**
**Steps to reproduce:**

1. Launch the app with biometrics/PIN ON
2. Fail Auth request - tap cancel
3. Turn biometrics toggle OFF on login page
4. Enter correct password  
5. Go to Settings-Security&Privacy - observe
6. Relaunch the application - observe

**Actual result:** step 5, step 6 - biometrics/PIN is requested
**Expected result:**  biometrics/PIN is not requested in settings. biometrics/PIN is not requested at login until enabled.

[OP_06 regression.mp4](https://user-images.githubusercontent.com/116747263/214145060-06b4b742-e5c1-42e7-8cc8-c42d0288d7b4.mp4)

2023-01-24 19:51 UTC, plasmacorral commented
Update MB_02: On relaunching app, test expects user to be taken to lock screen and in this branch the user is brought directly into wallet view.

This continues to cause e2e tests to fail, that are otherwise passing in production today.  When these spec files are run individually, they will pass, but when run within the full suite of e2e they fail because wallet view is shown without authentication after the app is refreshed. 

VIDEO: 
This can be observed in e2e/specs/onboarding-wizard-opt-in.spec.js around line [125](https://recordit.co/g7nvN68DuJ). Also shown in e2e/specs/import-seed-phrase.spec.js around line [134](https://recordit.co/4BYKGRm2rB).

EXPECTATION: In both tests above, production builds require authentication prior to wallet view being presented.

2023-01-24 21:06 UTC, plasmacorral commented
MB_13: Biometric icon presented in password entry box while using device pin/passcode authentication in MMM

iPhone Xs
IOS 16
commit https://github.com/MetaMask/metamask-mobile/commit/0b39ed6406ae54d3e6c12c208c480c004097e790

When device pin/passcode authentication is selected, biometric authentication can also be used to unlock MMM.  When actively using device pin/passcode authentication, the biometric icon is presented in the password entry box on the lock screen.  Tapping this biometric icon does actually open the device pin/passcode prompt, but the icon is inaccurate.  

This is an improvement on production, where device pin/passcode is simply turned off when the user taps 'Cancel' at the pin/passcode prompt.  However, the icon presenting face_id is confusing. If there is any iconography to signify pin/passcode that should be used instead, but that does not appear in production builds.

VIDEO:  https://recordit.co/NawHS0Esx7
production v5.13 build 1042 on the Iphone 13 mini running iOS 15 on the left
& 
QA build of the feature branch on Iphone Xs running ios 16 on the right

2023-01-31 20:01 UTC, owencraston commented on android/app/build.gradle
> +		versionCode 1056
must be removed before merging

2023-01-31 20:26 UTC, owencraston commented on app/components/hooks/DeleteWallet/useDeleteWallet.ts
> +        type: AUTHENTICATION_TYPE.UNKNOWN,
this needs to be currentAuthType.

2023-01-31 20:29 UTC, owencraston commented on app/components/Nav/App/index.js
> +        const currentVersion = await getVersion();
doesn't need to be await

2023-01-31 21:20 UTC, gantunesr commented on app/core/Authentication/Authentication.ts
> +  newWalletAndKeyChain = async (
```suggestion
  newWalletAndKeychain = async (
```

2023-01-31 21:21 UTC, gantunesr commented on app/components/Views/ChoosePassword/index.js
> +  'Error: The user name or passphrase you entered is not correct.';
Solved: Error from the keychain

2023-01-31 21:47 UTC, gantunesr reviewed
LGTM

2023-01-31 22:29 UTC, owencraston commented on app/components/Views/Settings/SecuritySettings/index.js
> +const BIOMETRY_CHOICE_STRING = 'biometryChoice';
they are very specific to this file and I think brining them into a shared folder would be putting too much importance on these values.

2023-02-01 22:27 UTC, plasmacorral commented
MB_15 Invalid password error only shows when less submission is less than the 8 character minimum

Commit https://github.com/MetaMask/metamask-mobile/commit/2f0c1657f9836ac3f0b58eac85afde218ea8fc51
iPhone 13 mini with iOS 15
&
Samsung a515f with android 11


In production, the error "Invalid password" shows regardless of the length of password submitted when the password is not correct.  However, in this branch the "Invalid password" error only shows when the incorrect submission is under 8 characters.

In this branch I am able to produce the following errors when submitting an incorrect password that is 8 or more characters:
IOS: "Error: Decrypt failed"
Android: "Error: error:1e000065:Cipher functionsOPENSSL_internal:BAD_DECRYPT"

These errors could be confusing and may not help users understand what further action is needed. 


Steps:
1. Import SRP and establish password of 8 characters
2. Lock wallet
3. Submit password of length =3 and note the expected error
4. Submit a password of length >8 and observe error messages

Screenshot:
![Screenshot 2023-02-01 at 2 27 13 PM](https://user-images.githubusercontent.com/32695229/216177426-51469df1-b029-4ff2-b3fd-481164aeb0e3.png)

Video: https://recordit.co/0s5puCoHGs
Feature branch shown in first ~24 seconds, and beyond that shows production v5.14 build 1055

2023-02-01 23:12 UTC, plasmacorral commented
MB_16 After locking wallet with Remember Me active, remember me is automatically reactivated upon password unlock

Commit https://github.com/MetaMask/metamask-mobile/commit/2f0c1657f9836ac3f0b58eac85afde218ea8fc51
iPhone 13 mini with iOS 15
&
Samsung a515f with Android 11

Steps:
1. Import SRP
2. Enable Remember Me enable toggle in Settings>Security& Privacy
3. kill app and relaunch
4. Turn on Remember Me toggle on lock screen
5. Provide password and tap unlock
6. kill app and relaunch
7. Note that remember me is enabled and authentication is NOT requested before arriving at wallet view
8. Tap drawer>Lock and then confirm
9. Note that you arrive at unlock with Remember Me toggle presented in the off position
10. Provide password and tap unlock
11. Arrive at wallet view
12. kill app and relaunch
13. Note that you arrive back at wallet view without being prompted for authentication

Video of Production V5.14 build 1055: https://recordit.co/rGyAmG2peT
Video of this branch: https://recordit.co/Nz4p3izdRC

Expectation: After lock, Remember me is disabled and remains that way until the user turns the toggle back on at the lock screen.

2023-02-01 23:31 UTC, plasmacorral commented
MB_17 Biometric toggle is not defaulted to ON when biometrics are present

Commit https://github.com/MetaMask/metamask-mobile/commit/2f0c1657f9836ac3f0b58eac85afde218ea8fc51
iPhone 13 mini with iOS 15
&
Pixel 5a with android 13

When conducting a password change while biometrics are present on the device, today in production we will present the biometric toggle defaulted to the ON position.  However, in this branch we are presenting the toggle defaulted to the OFF position.  This is different than production today.

This impacts both password changes, in addition to setting up a new wallet after deleting the existing one.


Steps:
1. Import SRP with biometrics present, but use password authentication 
2. Change password
3. Note that biometric toggle is NOT defaulted to the On position

Production v5.14 build 1055: https://recordit.co/YbmQF3jvxt
This branch: https://recordit.co/k8fscP0oNl

2023-02-02 23:58 UTC, plasmacorral commented
MB_18 App lock timer is not respected

Commit https://github.com/MetaMask/metamask-mobile/commit/2f0c1657f9836ac3f0b58eac85afde218ea8fc51

**Pixel 5a with android 13**
When the screen lock is set to 60 seconds and the app lock remains at the default 30 second setting with the app in the foreground, I expect after 90+ seconds of not touching anything that the device and app should both be locked.  When I unlock the device, I should be subsequently prompted to unlock MMM.  After 2.5 minutes, I can still unlock the phone and access wallet view without having to authenticate.

Steps to reproduce on the Pixel:
1. Have a stopwatch
2. Have device set with fingerprint/PIN to unlock
3. Have Settings>Display screen lock set at 1 minute on the device
4. Have wallet setup with device PIN authentication
5. Have app-lock at the default 30s
6. Be on wallet view and swipe down to refresh
7. At the same time, start the timer
8. After 60ish seconds screen will lock
9. At 2 minutes and 30 seconds tap the screen to wake up
10. Provide fingerprint authentication to unlock the device
11. Note that Wallet view is presented without authentication

Commit https://github.com/MetaMask/metamask-mobile/commit/2f0c1657f9836ac3f0b58eac85afde218ea8fc51s: https://recordit.co/u4bwYlVwQM
Production v5.14 build 1055: https://recordit.co/EZqB3rYP0i



**Samsung a515f**
The scenario here is a bit different, but the result is the same.  Curiously the pixel performs as expected in the scenario below, as you can see in the video.  With the screen lock set at 30 seconds and the app lock at the default 30s, when I tap the power button to lock the screen I can get unlock the phone and return to wallet view without being prompted to authenticate.


Samsung steps:
1. Have a stopwatch
2. Have device set with fingerprint/PIN to unlock
3. Have Settings>Display screen lock set at 30 seconds on the device
4. Have wallet setup with biometric (fingerprint) authentication
5. Have app-lock at the default 30s
6. Tap the device power button to lock the screen
7. At the same time, start the timer
8. tap the screen to wake up and then provide fingerprint authentication after 60ish seconds
9. Note that Wallet view is presented without authentication

Commit https://github.com/MetaMask/metamask-mobile/commit/2f0c1657f9836ac3f0b58eac85afde218ea8fc51s: https://recordit.co/Q52ePQzATJ (samsung device is in the middle position)
Production v5.14 build 1055: https://recordit.co/ht1PBCeHuW


Expectation: When App-lock time is exceeded, authentication should be required to access wallet view.

2023-02-03 19:53 UTC, plasmacorral commented
MB_19: Android 11-When biometrics are deleted from the device, device PIN is demanded and cannot be disabled

Samsung A515f with Android 11
Commit https://github.com/MetaMask/metamask-mobile/commit/2f0c1657f9836ac3f0b58eac85afde218ea8fc51

When I have fingerprint authentication enabled on MMM but then delete the fingerprints on the device, the device demands the device PIN for authentication.  It does this two times, everytime, even when the first fingerprint was successful.  In this state, the device PIN is also requested to even open the Security & Privacy menu.

As you can see in the video with the device on the left, Android 13 simply reverts to password authentication. My iOS device also handles this case by simply reverting to password authentication. This Samsung device with the production build v5.14 build 1055 will also default to password authentication.  In the branch MMM changes to device PIN authentication without the user consent.  The multiple demands for the PIN make using the wallet even slower and more challenging.

In addition to being requested twice, the device PIN toggle is not presented in settings to be able to turn it off and make the app more usable.

On my first attempt to reproduce this, it did not happen.  However, this behavior of asking for authentication twice, and requiring authentication to view Security & Privacy was also mentioned in MB_06 and makes an appearance here as well. 

Steps:
1. Have device configured with biometrics (I had 2 fingers configured on each device at the time)
2. Import SRP/create wallet with biometrics ON
3. kill app and relaunch to confirm biometric authentication works to access wallet view
4. Kill app again
5. Access device settings and delete biometric factors
6. launch app
7. Note that pixel asks for password, Samsung asks for device PIN two times before presenting wallet view.


Commit https://github.com/MetaMask/metamask-mobile/commit/2f0c1657f9836ac3f0b58eac85afde218ea8fc51s: https://recordit.co/FtyjvM9J9h
Production v5.14 build 1055: https://recordit.co/HIaoQLdmNJ
(pixel 5a on the left and Samsung on the right)

2023-02-03 21:15 UTC, plasmacorral commented
A quick testing update from Commit https://github.com/MetaMask/metamask-mobile/commit/2f0c1657f9836ac3f0b58eac85afde218ea8fc51

MB_12- Failed retest
MB_14- Failed retest
& 
MB_11- needs further discussion after retest

2023-02-06 21:33 UTC, olenapankina commented
**Tested on**
iPhone Xr iOS 16.1.1
Samsung Galaxy M21 Android 12, One UI Core version 4.1
commit https://github.com/MetaMask/metamask-mobile/commit/2f0c1657f9836ac3f0b58eac85afde218ea8fc51 

**OP_15:** Error message is shown when user tries to disable Biometrics right after changing the password
**Steps to reproduce:**
1. Change password
2. In the same session, tap on the toggle to disable Biometrics
3. Observe Face_ID request pops up at the same time as the 'Incorrect password' error message

**Actual result:** user is unable to disable Biometrics on a first try. 'Incorrect password' error is being shown when password wasn't entered [5374_OP_15.mp4](https://user-images.githubusercontent.com/116747263/217090498-aaeff897-2a75-43f4-9970-aa04e009119b.mp4)
**Expected result:** after tapping of the toggle to disable Biometrics - enter password screen pops up. After entering correct (new) password - Biometrics are disabled

**OP_16:** iOS-Auto-lock 'Immediately' stopped working after auth failure
**Steps to reproduce:**
1. Launch the app with Face_ID ON and auto-lock set to 'Immediately'
2. Fail biometrics request
3. Login
4. Put the app in the background
5. Launch the application
6. Observe app not being locked

**Actual result:** Auto-lock 'Immediately' stopped working after auth failure [5374_OP_16.mp4](https://user-images.githubusercontent.com/116747263/217092136-93c52c20-0674-48c0-bdb6-8e795e452f3e.mp4)
**Expected result:** Auto-lock is working
Note: not able to reproduce with auto-lock set to 5s

**OP_17:** Welcome screen is in the background when biometrics auth requests fails on the first session
**Steps to reproduce:**

1. Launch freshly installed application
2. Import an account, Biometrics ON
3. Put app in the background
4. Wait 30 seconds (auto-lock)
5. Launch the application
6. Fail Biometrics request
7. Observe

**Actual result:** Welcome screen is in the background with 'Unlock' link [5374_OP_17_Actual result.mp4](https://user-images.githubusercontent.com/116747263/217092348-1c3ad5eb-2d27-4ceb-aab5-df026513898c.mp4)
**Expected result:** loading screen (black with orange diamond) is in the background [5374_OP_17_Expected result.mp4](https://user-images.githubusercontent.com/116747263/217092418-5ad403c1-7e69-46d0-825f-8e1e5ad2c4eb.mp4)

2023-02-10 19:25 UTC, olenapankina commented
**Tested on**
iPhone Xr iOS 16.1.1
commit 75db8290c358b04f4a1dfd3d6a9ecb3f3e234414

**OP_18:** iOS - app is asking for Alphanumeric code on a fresh build after Alphanumeric code was used on the previous instance

**Steps to reproduce:**
1. Set up iPhone with Alphanumeric code and Face_ID
2. Install MetaMask
3. Create or Import wallet with Face_ID ON
4. Disable Face_ID, enable device passcode in Metamask settings
5. Verify you are able to login with Alphanumeric code
6. Delete application from the device
7. Disable Face_ID in Settings
8. Install MetaMask
9. Tap Import SRP/Create a new wallet buttons
10. Observe Alphanumeric code request
11. Observe 'Create a new wallet' broken navigation 

**Actual result:** 1) Alphanumeric code request pops-up on tapping Import SRP/'Create a new wallet' buttons. [5374_OP_18.mp4](https://user-images.githubusercontent.com/116747263/218179509-841dab88-039b-44b4-8cf0-f25c4382cab8.mp4)
2) 'Create a new wallet' page has 'Onboarding' instead of 'Back' button and 'ChoosePassword' instead of 'MATAMASK' - was able to reproduce only with Alphanumeric code issue. [5374_OP_18](https://user-images.githubusercontent.com/116747263/218179617-3e3b27dd-962a-4dfe-97fe-1dd9acbd1ef5.PNG)
**Expected result:** Alphanumeric code is not being asked on freshly installed application with wallet not created.

2023-02-14 19:37 UTC, plasmacorral commented
MB_14 is not passing retest in commit 75db8290c358b04f4a1dfd3d6a9ecb3f3e234414 

This fails retest with a slight variation on the original reproduction steps from the original report, but has the same result that the biometric icon is presented to the user when it should not be. 

Video: [https://recordit.co/ebMslOOOSB](https://recordit.co/ebMslOOOSB) (pixel 5a on left, Samsung A515f on right)

Updated steps:
1. Import SRP with biometric authentication =ON
2. Get to wallet view and then open app drawer
3. Tap lock and then confirm
4. At lock screen note biometric icon is NO LONGER presented
5. Kill app and restart
6. Note that biometric icon is presented in password entry box. Tapping it does NOT open auth request because password auth is still required after lock. Biometric icon should not be presented

2023-02-20 18:32 UTC, olenapankina commented
Tested on
commit 445236d, Test build 1069
iPhone Xr iOS 16.1.1
Samsung Galaxy M21 Android 12, One UI Core version 4.1

**OP_19:** Unable to disable Biometrics after importing account
**Steps to reproduce:**

1. Import an account on a freshly installed build
2. Go to Settings->Security and Privacy
3. Tap on the toggle to disable Biometrics
4. Observe

**Actual result:** Android: no Biometrics request, on relaunch Biometrics are requested [5374_OP_19.mov](https://user-images.githubusercontent.com/116747263/220177888-e1a3f82a-7492-444e-a5fc-6b8b6fe3ea65.mov)
iOS: incorrect password error, user is locked out of the app, login page presented with Biometrics toggle turned ON
**Expected result:** Biometrics are requested, and after success - toggle is turned off. Biometrics toggle is not presented on the login page.
**Note**, this is a floating issue

**OP_20:** Unable to connect to WalletConnect
**Steps to reproduce:**

1. Change network to Goerli
2. Open https://example.walletconnect.org/ in a browser outside of MMM
3. Tap 'Connect to WalletConnect'
4. Observe

**Actual result:** Andoid: error page [5374_OP_20 Actual result.mov](https://user-images.githubusercontent.com/116747263/220178113-edc48469-f15a-4b5e-a74c-cb51a2eaf1f2.mov)
iOS: user is not redirected to MetaMask app, WalletConnect is connected to the previous account
**Expected result:** MetaMask opened, connect modal is presented [5375_OP_20 Expected result.mov](https://user-images.githubusercontent.com/116747263/220178452-c526513e-b465-483a-bbd9-364cda8114f7.mov)

2023-02-21 19:48 UTC, olenapankina commented
**Tested on**
commit https://github.com/MetaMask/metamask-mobile/commit/445236df6b63ad55e73a652a0ac457c97b4ab7da, Test build 1069
Samsung Galaxy M21 Android 12, One UI Core version 4.1

**OP_21:** Android - User can navigate to the lock page with back device button
**Steps to reproduce:**

1. Launch the app with finger/PIN authentication 
2. Login with biometrics
3. Tap side menu
4. Tap on Settings/Support/Request a Feature/View on Etherscan/Activity button
5. Observe lock page in the background [5374_OP_21.png](https://user-images.githubusercontent.com/116747263/220443765-c4fe1f4f-ecf7-4e82-972b-be04b8ae4dab.png)
6. Tap back device button until you're on wallet view -> tap one more time
7. Observe

**Actual result:** User launches on lock page, app is locked [5374_OP_21.mov](https://user-images.githubusercontent.com/116747263/220442912-c74fa574-b615-4889-ad7a-8d5a9d1a891b.mov)
**Expected result:** User launches on home screen, after going back to MetaMask (within auto-lock time) wallet view presented

Unable to reproduce on prod, main build #5882

2023-02-22 20:13 UTC, olenapankina commented
**Tested on**
commit d6cd272 
Samsung Galaxy M21 Android 12, One UI Core version 4.1

**OP_22**: After unblocking the device with metamask in the foreground and Auto-Lock set to Immediately - auth is requested more than once, user launches on a lock screen.
**Steps to reproduce:**

1. Finger and pin auth presented on the device
2. PIN or finger is used to unlock metamask
3. Auto-lock is set to Immediately
4. Lock the phone with MetaMask in the foreground
5. Turn the device screen on
6. Unlock the device with a finger
7. Observe

**Actual result**: auth is requested, after success  - user is on the lock screen. auth is requested 2 more times. after tapping on the finger icon - and proving valid auth user is logged in. [5374_OP_22.mov](https://user-images.githubusercontent.com/116747263/220748005-5931c8af-9a16-48f1-b8ff-922825f21293.mov)
**Expected result**: auth is requested, after success - user is logged in

2023-02-23 23:53 UTC, plasmacorral commented
MB_20: Android- Auth request fails when trying to change from device PIN to biometric auth on the first attempt, every time with error "Invalid Password The password was not correct. Please try again"

commit https://github.com/MetaMask/metamask-mobile/commit/d6cd2720cbfa186b1be01591a3f289d4f1694fb1

Observed on 3 devices: Pixel 5a with Android 13 (left), Pixel 3a with Android 12 (center), and Samsung a515f with Android 11 (right)

video: https://recordit.co/Z1dJNl4Zai

Steps:
1. Have biometric auth present and available on the device, but choose numeric pin, password or pattern for device lock
2. Create a new wallet and do not enable biometric auth in setup flow
3. From wallet view >Settings>Security & Privacy change to app-lock immediate
4. Turn on device PIN authentication
5. provide auth as requested
6. kill app and relaunch
7. Provide pin/password/pattern to unlock
8. From wallet view >Settings>Security & Privacy tap to turn on biometric auth toggle
9. notice that authentication prompt will accept biometrics or device PIN/passcode/pattern
10. Regardless of the valid authentication provided notice the invalid password error
11. On second attempt notice that only MMM app password is requested, when that is provided biometric auth is successfully enabled

2023-02-24 18:56 UTC, owencraston commented
All the core flows seem to be intact after the rebase. We are ready to merge.

https://user-images.githubusercontent.com/22918444/221267209-8d000367-0a28-43f6-b1c5-f5ad659f017a.MP4

2023-02-24 18:56 UTC, olenapankina approved these changes

2023-02-24 19:24 UTC, owencraston commented
Android also looks good after the rebase
https://user-images.githubusercontent.com/22918444/221272550-fd25a987-5b00-453a-9ff7-e9eae79dc0f7.mp4

2023-02-24 22:08 UTC, Cal-L approved these changes
LGTM

2023-02-24 22:44 UTC, merged