Include L1 fee in the Send flow and on the tx detail page for Optimism
MetaMask/metamask-mobile pull request #5376
Opened 2022-12-09 14:59 UTC by dan437

## Description
This PR:
- Includes Optimism's L1 fee in the Send flow, transaction detail page, dapp approval and tx confirmation modals and in all quotes in Swaps (not only in the selected one).

TODOs:
- Once QA is finished, I will merge new code into the swaps-controller, publish it on npm and use it here in package.json. Currently it's pointing to a GitHub commit in the swaps-controller repo for testing purposes.

## Testing
- Switch to the Optimism network
- See correct fees in the Send flow, transaction detail page and in Swaps (including a list of quotes). Try to submit a tx and compare estimated gas fee vs the real one.
- For dapp testing, open e.g. Uniswap in MetaMask app's browser section and try to do a swap with a token that needs an approval and with another one that doesn't. MetaMask's modal windows for approval and tx confirmation will show up with correct estimations. If an approval is needed, an estimated gas fee is higher for a few cents (at this time).

2022-12-12 05:03 UTC, Cal-L reviewed
Left some comments

2022-12-12 13:47 UTC, dan437 commented on app/components/UI/TransactionReview/TransactionReviewEIP1559Update/index.tsx
> +    multiLayerL1FeeTotal,
In the extension we only allow a user to edit gas fees for the L2 network on Optimism after they send a tx, so I believe we don't need to show Optimism's L1 fee in the edit gas modals for now. I will mention it to our product folks, since it could be a nice-to-have improvement in another PR.

2022-12-13 09:00 UTC, dan437 commented on app/components/Views/SendFlow/Confirm/index.js
> +            multiLayerL1FeeTotal={multiLayerL1FeeTotal}
Thanks for instructions how to trigger the `ApproveTransactionReview` component via Uniswap. It was needed there as well, so I've added it.

2022-12-13 16:19 UTC, Cal-L commented on app/components/UI/TransactionReview/TransactionReviewEIP1559Update/index.tsx
> +    multiLayerL1FeeTotal,
Makes sense.

2022-12-13 16:20 UTC, Cal-L commented on app/components/Views/SendFlow/Confirm/index.js
> +            multiLayerL1FeeTotal={multiLayerL1FeeTotal}
Resolving since updated.

2022-12-13 16:20 UTC, Cal-L approved these changes
LGTM

2022-12-20 00:41 UTC, cortisiko requested changes
@dan437 swinging this back your way!

**Issue 1**
I do not think the edit gas modal contains the L1 fees. 

As it stands, the estimated gas is showing a different value on the edit gas modalhttps://www.screencast.com/t/wcy3KX2N  compared to the transaction confirmation screen: https://www.screencast.com/t/WWmbVv1mrlsD 


**Issue 2**

The transaction details view totals look a bit off for a swap transaction. For example: on optimism I wrapped ETH: https://www.screencast.com/t/kNC4UHY40QLb 
When I view the transaction details, the total amount is padded with extra 0's: https://www.screencast.com/t/1SquM6d5s 

**Issue 3**
L1 fees are not respected in Dapp transactions. See my attempt to perform a swap on uniswap: http://recordit.co/yMGK36Idre


**Potential Issue 4**
This might be out of scope but can you confirm whether or not PALM is included in this change? As it stands I noticed on PALM the transaction confirmation view does not include the L1 fee. See here: https://www.screencast.com/t/N8AQ4v0sR

2022-12-20 08:18 UTC, dan437 commented
Thanks for great feedback, @cortisiko!

1. This is a known thing I mentioned here, can be solved as a future improvement: https://github.com/MetaMask/metamask-mobile/pull/5376#discussion_r1045847462 _In the extension we only allow a user to edit gas fees for the L2 network on Optimism after they send a tx, so I believe we don't need to show Optimism's L1 fee in the edit gas modals for now. I will mention it to our product folks, since it could be a nice-to-have improvement in another PR._
2. Agreed, we should have a max number of digits after decimal point, otherwise it can get too long sometimes. I will check with product about details.
3. Great catch, I will add it there as I did for other dapp modal. There is also a gas editing modal, which I described in 1.
4. The PALM network is not included in this change. Someone can add support for it in another PR if needed.

2022-12-20 18:55 UTC, gantunesr reviewed
LGTM

2022-12-20 19:12 UTC, dan437 commented on package.json
> +    "@metamask/swaps-controller": "git+https://github.com/MetaMask/swaps-controller.git#f8127fbdacc71d9f02b3c907844f3170ab9f472d",
Yup, once QA is finished for this PR, I will get the code in the swaps-controller reviewed, merged, published and then I will use it here.

2022-12-21 06:21 UTC, cortisiko approved these changes
This PR is 🌮 🌮 🌮 .

2022-12-21 17:02 UTC, gantunesr approved these changes

2022-12-21 18:27 UTC, merged