Appium/test fixes
MetaMask/metamask-mobile pull request #5398
Opened 2022-12-15 08:02 UTC by chrisleewilcox

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
Added fixes and enhancements.  Adjusted to run on physical device.

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2022-12-19 22:06 UTC, Fatxx commented
This PR has https://github.com/MetaMask/metamask-mobile/pull/5398 as dependency

2022-12-19 22:40 UTC, cortisiko requested changes

2022-12-19 22:40 UTC, cortisiko commented on wdio/features/screen-objects/Onboarding/ImportFromSeedScreen.js
> +    var msg = await driver.getAlertText();
Following ES6 variable declaration: the variable should be either a const or let.

2022-12-19 22:40 UTC, cortisiko commented on wdio/features/screen-objects/Onboarding/ImportFromSeedScreen.js
> +    while(msg === '' || null){
curious, why are you looping through the alert text?

2022-12-19 23:19 UTC, chrisleewilcox commented on wdio/features/screen-objects/Onboarding/ImportFromSeedScreen.js
> +    var msg = await driver.getAlertText();
Changed to `let`.

2022-12-19 23:23 UTC, chrisleewilcox commented on wdio/features/screen-objects/Onboarding/ImportFromSeedScreen.js
> +    while(msg === '' || null){
This is for running test on physical device.  For some reason the device alert text is not retrieved _sometimes_ on physical device so this was for dealing with those situations on physical device.  This does not result in an infinite loop because the automation timeout will kill the step.  This was not a solid solution and will remove.  Probably better to just try/catch and tap to confirm alert.

2022-12-19 23:25 UTC, chrisleewilcox commented on wdio/features/screen-objects/Onboarding/ImportFromSeedScreen.js
> +    var msg = await driver.getAlertText();
See comment below, will just remove.

2022-12-20 00:11 UTC, cortisiko approved these changes
✅ ✅ ✅ ✅

2022-12-20 18:50 UTC, merged