Refactor Approval Update
MetaMask/metamask-mobile pull request #5412
Opened 2022-12-20 11:54 UTC by blackdevelopa

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-01-12 10:55 UTC, tommasini requested changes
Hey mate, great work!

Left a few NIT picks

2023-01-12 10:55 UTC, tommasini commented on app/components/UI/EditGasFee1559/types.ts
> +  dappSuggestedGasPrice?: any;
Could we type these two props?

2023-01-12 10:55 UTC, tommasini commented on app/components/UI/TransactionEditor/index.js
> +          stopUpdateGas: false,
The `stopUpdateGas` state varaible, it's not in the initial state, it's this intended?

2023-01-12 10:55 UTC, tommasini commented on app/components/UI/TransactionReview/index.js
> +    gasError: PropTypes.string,
Could we write a description for these new added props?

2023-01-12 10:59 UTC, blackdevelopa commented on app/components/UI/EditGasFee1559/types.ts
> +  dappSuggestedGasPrice?: any;
Yes and absolutely. Did prior and still got a lint warning message. Will try again and update.

2023-01-17 19:32 UTC, blackdevelopa commented on app/components/UI/TransactionEditor/index.js
> +          stopUpdateGas: false,
https://github.com/MetaMask/metamask-mobile/pull/5412/commits/8a274d4d4f5e1afb2b643449facb088c4bf94396

2023-01-19 15:17 UTC, jpuri commented on app/components/UI/EditGasFee1559/types.ts
>  }
Hi, just curious what motivated renaming to remove `Update` ?

2023-01-19 15:20 UTC, jpuri commented on app/components/UI/UpdateEIP1559Tx/index.tsx
>        primaryCurrency={primaryCurrency}
In my opinion separate PR for renaming would have been easier for reviewing.

2023-01-19 15:25 UTC, jpuri reviewed
Change look good, I would prefer more mobile devs review it to approve.

2023-01-20 16:18 UTC, blackdevelopa commented on app/components/UI/UpdateEIP1559Tx/index.tsx
>        primaryCurrency={primaryCurrency}
Yes. In hindsight, you are right on this.

2023-01-20 16:53 UTC, gantunesr reviewed
I left some suggestions and questions. Nothing major

2023-01-20 16:53 UTC, gantunesr commented on app/core/GasPolling/types.ts
> +  };
I'd suggest to create a new interface for this object

2023-01-20 16:53 UTC, gantunesr commented on app/core/GasPolling/types.ts
> +
Can you change the format of the documentation to,
```suggestion
/**
 * @type UseGasTransactionProps
 *
 * <Definition>
 * @property gasSelected - <Definition>
 * @property onlyGas - <Definition>
 */
export interface UseGasTransactionProps extends TransactionSharedProps {
  gasSelected: string | null;
  onlyGas?: boolean;

```

2023-01-20 16:53 UTC, gantunesr commented on app/util/transactions/index.js
> +    const exchangeRate = contractExchangeRates?.[address];
Is this variable being treating as a optional in the rest of the code to avoid `undefined` errors?

2023-01-20 16:53 UTC, gantunesr commented on app/core/GasPolling/types.ts
>    };
Probably a good idea to define a new interface for this object too (Out of scope for this PR)

2023-01-20 16:53 UTC, gantunesr commented on app/core/GasPolling/types.ts
> +  };
Out of scope for this PR

2023-01-20 18:23 UTC, blackdevelopa commented on app/util/transactions/index.js
> +    const exchangeRate = contractExchangeRates?.[address];
I updated this https://github.com/MetaMask/metamask-mobile/pull/5412/commits/4a3e2ee0108af9b1d7bdc6480086dd99bba8f727

2023-01-20 21:17 UTC, gantunesr approved these changes
LGTM

2023-01-23 10:29 UTC, tommasini approved these changes
LGTM just left pointer few props without type

2023-01-23 10:29 UTC, tommasini commented on app/core/GasPolling/types.ts
> +  suggestedGasPrice?: any;
Here too

2023-01-24 12:58 UTC, blackdevelopa commented on app/core/GasPolling/types.ts
> +  suggestedGasPrice?: any;
Good catch. 🙌🏿

2023-02-17 10:44 UTC, seaona commented
I've noticed that when I perform a Send from inside MetaMask, when clicking Confirm, the app crashes and I see an error saying `undefined is not an object (evaluating gasTransaction.renderableGasFeeMinNative)`
This happens both to EIP1159 transactions and Legacy transactions (i.e. Binance).

https://user-images.githubusercontent.com/54408225/219619955-a78ee72c-8749-4507-91e3-ca7be9d7fcb8.mp4

2023-05-02 10:51 UTC, closed without merging