E2e test/browser flow
MetaMask/metamask-mobile pull request #5460
Opened 2023-01-06 19:48 UTC by SamuelSalas

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-01-09 11:33 UTC, Andepande approved these changes

2023-01-09 23:53 UTC, cortisiko requested changes
@SamuelSalas Left a couple of things for now. Can you run detox to ensure nothing broke?

2023-01-09 23:53 UTC, cortisiko commented on wdio/features/step-definitions/browser-flow.js
> +/* global driver */
rename this file to be `browser-steps.js`

2023-01-09 23:53 UTC, cortisiko commented on wdio/features/BrowserFlow.feature
> +    And I navigate to the browser
Tests are failing because these two steps are missing:

    And I tap No Thanks on the Enable security check screen
    And I tap No thanks on the onboarding welcome tutorial

```suggestion
    And I tap No Thanks on the Enable security check screen
    And I tap No thanks on the onboarding welcome tutorial
    And I navigate to the browser
```

2023-01-10 00:03 UTC, cortisiko commented on wdio/features/BrowserFlow.feature
> +    And I navigate to the browser
oh I see. You have the test actions for the above steps in

`And I navigate to the browser`

this creates a slight confusion since there is a test step for dismissing the onboarding tutorial modal and the security checks modal. Furthermore, the test was failing. At this point, it is unclear why it is failing. Can you run tests on your end to confirm that they are working? 

Lastly, let's keep those crucial steps separated.

2023-01-11 21:19 UTC, chrisleewilcox commented on e2e/specs/wallet-tests.spec.js
> -
Why is this being removed from detox?  Can you confirm this is necessary and if not please revert.

2023-01-11 21:20 UTC, chrisleewilcox commented on wdio/config/android.config.debug.js
> -    deviceName: 'Android 11 - Pixel 4a API 30',
Can you remove your android device config from this PR?  We would all get your device config changes if this was merged.

2023-01-11 21:35 UTC, chrisleewilcox commented on wdio/features/BrowserFlow/SwitchWallet.feature
> +  Scenario: Switching wallet accounts while connected to a dapp.
For clarity can you please update this to switch accounts, not wallets.  Also, can you update this filename to SwitchAccounts.feature?

2023-01-11 21:38 UTC, chrisleewilcox commented on wdio/features/BrowserFlow/OptionMenu.feature
> +  Scenario: Browser options
So having just one scenario that says browser options is not as informative as having a scenario for each of the browser options.  I think this is best broken down into each browser option as scenarios.

2023-01-11 21:38 UTC, chrisleewilcox requested changes
Please review comments.

2023-01-11 22:37 UTC, SamuelSalas commented on e2e/specs/wallet-tests.spec.js
> -
Not sure why this test was remove, i have it present locally. I'll validate this when making my last commit.

2023-01-11 22:37 UTC, SamuelSalas commented on wdio/config/android.config.debug.js
> -    deviceName: 'Android 11 - Pixel 4a API 30',
Of course, I forgot to change this information.

2023-01-12 15:27 UTC, cortisiko requested changes

2023-01-12 15:27 UTC, cortisiko commented on wdio/features/screen-objects/BrowserObject/AddressBarScreen.js
> +  get root() {
Mind shedding some light on what this means? "Root" seems a little vague.

2023-01-12 15:27 UTC, cortisiko commented on wdio/features/screen-objects/BrowserObject/AddressBarScreen.js
> +    if (flag) {
Flag seems a little vague as well. Can we rename it?

2023-01-12 15:27 UTC, cortisiko commented on wdio/features/screen-objects/BrowserObject/BrowserScreen.js
> +  get screen() {
Maybe rename this to "container"

2023-01-12 15:27 UTC, cortisiko commented on wdio/features/screen-objects/BrowserObject/OptionMenuModal.js
> +  get menu() {
Probably rename to container. Or menu container.

2023-01-12 15:27 UTC, cortisiko commented on wdio/features/screen-objects/DrawerViewScreen.js
> +  get browser() {
Perhaps rename to browserContainer or container

2023-01-12 15:59 UTC, SamuelSalas commented on wdio/features/screen-objects/BrowserObject/AddressBarScreen.js
> +  get root() {
I call it root because I based the name on the id from the page. I'll change it to container

2023-01-12 16:48 UTC, cortisiko commented on wdio/features/screen-objects/DrawerViewScreen.js
> +  get browser() {
okay got it!

2023-01-12 20:21 UTC, cortisiko approved these changes
looks good to me @SamuelSalas 🚀 🚀 🚀

2023-01-12 20:27 UTC, chrisleewilcox approved these changes

2023-01-12 22:41 UTC, merged