Fixed failing e2e tests and made minor adjustments
MetaMask/metamask-mobile pull request #5498
Opened 2023-01-13 16:58 UTC by Andepande

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

A number of e2e/appium tests were failing, this PR fixes those failures with some minor adjustments to the running of wdio tests

**Checklist**

* [ ] There is a related GitHub issue
* [x] Tests are included if applicable
* [ ] Any added code is fully documented

2023-01-13 19:56 UTC, SamuelSalas commented on wdio/features/step-definitions/send-flow.steps.js
> +    await driver.pause(timeout);
is there an specific reason for this variable?

2023-01-13 20:24 UTC, cortisiko requested changes
left a couple of thangsss, take a look when you get a chance @Andepande

2023-01-13 20:24 UTC, cortisiko commented on wdio.conf.js
> +  waitforTimeout: 20000,
probably revert this back. I think it was added to deal with Browserstack laggy-ness

2023-01-13 20:24 UTC, cortisiko commented on wdio/features/step-definitions/add-networks.steps.js
>  Given(/^I import wallet using seed phrase "([^"]*)?"/, async (phrase) => {
probably remove this step “Given I imported my wallet with xxx” instead, use the import wallet step in the common.step file: https://github.com/MetaMask/metamask-mobile/blob/main/wdio/features/step-definitions/common-steps.js#L15

2023-01-13 21:10 UTC, chrisleewilcox requested changes

2023-01-13 21:10 UTC, chrisleewilcox commented on wdio/features/NetworkFlow.feature
> +    When I click "Delete" on remove network modal
Should this be flagged as a bug?  It was originally 'Remove' and not it's 'Delete'?  I would confirm with dev/prod that this is expected, otherwise I would write this up as a bug indicating this change was not expected.  I recall I worked on a PR that was to make these controls 'Remove' so I don't think we should revert back.  Also, 'tap' instead of 'click'.

2023-01-15 23:53 UTC, Andepande commented on wdio/features/NetworkFlow.feature
> +    When I click "Delete" on remove network modal
Good Point! I've noticed a few similar changes and wanted find out whether we label them as bugs or were they attributed to changes I wasn't aware of

2023-01-16 00:15 UTC, Andepande commented on wdio/features/step-definitions/send-flow.steps.js
> +    await driver.pause(timeout);
One of the previous PR's Seth requested we put the timeout into a Const and refer to it.

2023-01-16 16:22 UTC, Fatxx requested changes

2023-01-16 16:22 UTC, Fatxx commented on wdio/features/screen-objects/CommonScreen.objects.js
> +class CommonScreen {
Do we need this? Seems empty

2023-01-16 16:22 UTC, Fatxx commented on wdio/features/ExploreWizard.feature
> +@ExploreSkip
Why do we need this tag?

2023-01-16 16:22 UTC, Fatxx commented on wdio/features/ExploreWizard.feature
> +@ExploreStartExplore
Why do we need this tag?

2023-01-16 17:34 UTC, cortisiko requested changes
small feedback

2023-01-16 17:34 UTC, cortisiko commented on wdio/features/testIDs/Screens/WalletView.testIds.js
> +export const MAIN_WALLET_VIEW_VIA_TOKENS_ID = 'tokens';
the name of the testID is slightly confusing. Mind shedding some light on what it is?

2023-01-16 17:34 UTC, cortisiko commented on wdio/features/step-definitions/send-flow.steps.js
> +    await WalletMainScreen.isMainWalletViewVisible();
hmmm this can be WalletScreen.isVisible() because you are checking to see if you are on the wallet screen.

2023-01-16 17:34 UTC, cortisiko commented on wdio/features/step-definitions/send-flow.steps.js
> +    await WalletMainScreen.isMainWalletViewVisible();
Also in the WalletMainScreen class there is a method to check if the wallet screen is visible. 

```
  async isVisible() {
    await WalletMainScreen.isMainWalletViewVisible();
    await expect(this.WalletScreenContainer).toBeDisplayed();
  }
```

maybe use that?

2023-01-16 17:34 UTC, cortisiko commented on wdio/features/NetworkFlow.feature
> +    # Then Add button is disabled
any reason for having this comment here?

2023-01-17 17:31 UTC, Fatxx approved these changes

2023-01-17 17:41 UTC, cortisiko commented on wdio/features/ImportCustomToken.feature
> +        And I tap on Goerli Test Network on Networks list to switch
can we revert the changes made in this file? This feature file was created to be the stepping stone for the Send tokens feature file.

2023-01-17 17:41 UTC, cortisiko commented on wdio/features/NetworkFlow.feature
> +    # Then Add button is disabled
probably remove this comment?

2023-01-17 17:41 UTC, cortisiko commented on wdio/features/NetworkFlow.feature
> +    # Then Add button is disabled
Probably remove this comment

2023-01-18 00:41 UTC, closed without merging