[IMPROVEMENT] Refactor Personal Signature
MetaMask/metamask-mobile pull request #5551
Opened 2023-01-19 17:49 UTC by blackdevelopa

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
Refactor the personal sign code from JavaScript to Typescript

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses NA

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-01-26 15:51 UTC, gantunesr requested changes

2023-01-26 15:51 UTC, gantunesr commented on app/components/UI/PersonalSign/PersonalSign.tsx
> +  });
Move this to a `styles.ts` file

2023-01-26 15:51 UTC, gantunesr commented on app/components/UI/PersonalSign/PersonalSign.tsx
> +  }, [currentPageInformation, selectedAddress]);
Do you think it would be better for this method to have a return type?

2023-01-26 15:52 UTC, gantunesr commented
Great work! left some feedback

2023-01-26 20:17 UTC, blackdevelopa commented on app/components/UI/PersonalSign/PersonalSign.tsx
> +  });
https://github.com/MetaMask/metamask-mobile/pull/5551/commits/48a8a3180ae4d6a6be1b7b3d810b0296d7110082

2023-01-27 02:17 UTC, gantunesr approved these changes
LGTM

2023-01-27 14:00 UTC, merged