[FIX] SRP recover when an error is thrown
MetaMask/metamask-mobile pull request #5608
Opened 2023-01-25 20:42 UTC by tommasini

**Description**
The SRP was not possible to recover when an error was found.

**Proposed solution**
SRP is able to be recovered when an error is found

**How to test it**
* Setup dev environment
* Write this code line `throw new Error('testing')` on the beginning of [wallet/index.tsx](https://github.com/MetaMask/metamask-mobile/blob/e05ef5ee785f171ba994373ebde4128e2dd18d20/app/components/Views/Wallet/index.tsx#L72) 
* Reload the app
* Insert password
* Expected to see the Error boundary screen
* Expected to be able to recover password
* (ONLY ON ANDROID)
* Try to take a screenshot of SRP
* Expected behaviour is that it's not possible

(This screen doesn't have the warning alert of when the screenshot is taken on IOS)

**Screenshots/Recordings**
https://recordit.co/dbQHB41jPb

**Issue**

Progresses #

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-01-26 01:28 UTC, gantunesr requested changes
This is a strange solution to this problem, lets sync on it later

2023-01-30 13:53 UTC, sethkfman commented on app/components/Views/Root/index.js
> -  errorHandler = (error, stackTrace) => {
Why did you remove this log?

2023-01-30 17:11 UTC, tommasini commented on app/components/Views/Root/index.js
> -  errorHandler = (error, stackTrace) => {
ErrorBoundary doesn't have any prop called onError, it was unused code

2023-02-01 18:48 UTC, gantunesr approved these changes
LGTM, just a minor comment

2023-02-01 18:48 UTC, gantunesr commented on app/components/Views/ErrorBoundary/index.js
> +        errorBoundaryView={this.props.view}
```suggestion
        hasNavigation={this.props.view === ROOT}
```

2023-02-01 19:45 UTC, tommasini commented on app/components/Views/ErrorBoundary/index.js
> +        errorBoundaryView={this.props.view}
Done 🚀

2023-02-01 20:27 UTC, gantunesr approved these changes

2023-02-02 23:44 UTC, cortisiko approved these changes
this was QA passed 🌮 🌮

2023-02-02 23:44 UTC, merged