E2e appium request token3
MetaMask/metamask-mobile pull request #5650
Opened 2023-01-31 15:07 UTC by Andepande

**Description**

- E2e test for Request token flow

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [ ] Any added code is fully documented

2023-01-31 19:26 UTC, cortisiko requested changes
left a few comments @Andepande !

2023-01-31 19:26 UTC, cortisiko commented on wdio/screen-objects/RequestTokenScreen.js
> +  async tapBackButtonOnSearch(searchReq) {
the variable `searchReq` is not used. probably remove it as a parameter.

2023-01-31 19:26 UTC, cortisiko commented on wdio/screen-objects/RequestTokenScreen.js
> +  async inputSearchRequestField(searchReq) {
mind spelling out this variable.

2023-01-31 19:26 UTC, cortisiko commented on wdio/step-definitions/request-token.steps.js
> +    await RequestTokenScreen.inputSearchRequestField(seaarchRequest);
typo in `seaarchRequest`

2023-01-31 19:26 UTC, cortisiko commented on wdio/screen-objects/testIDs/Screens/RecieveToken.testIds.js
> +export const REQUEST_AMOUNT_INPUT = 'request-amount-input';
Can you rename this file to `RequestToken.testIDs.js`

2023-01-31 19:26 UTC, cortisiko commented on wdio/screen-objects/RequestTokenScreen.js
> +  get requestCloseButton() {
Create another Screen class for the SendLink screen. The `requestCloseButton`, `closeRequestPaymentQRIcon` && `closePaymentRequest` should be in the SendLink class.

2023-02-01 04:19 UTC, cortisiko approved these changes
Looks good to me. Before you merge:
- Ensure detox is not broken. In particular, the `request-token-flow.spec.js`
-  Get one more dev review

2023-02-01 15:42 UTC, SamuelSalas approved these changes

2023-02-01 16:10 UTC, merged