ens-fix
MetaMask/metamask-mobile pull request #5656
Opened 2023-02-01 10:45 UTC by blackdevelopa

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-02-01 15:42 UTC, tommasini requested changes
It would be nice to have the validation logic covering both scenarios on one util folder, wdyt?

2023-02-01 15:42 UTC, tommasini commented on app/core/DeeplinkManager.js
> +
We have this logic already [here](https://github.com/MetaMask/metamask-mobile/blob/01680ea4df25febd930b2d52289e36f0e33fa19e/app/components/Views/Send/index.js#L270) and we could re-use it here, we should also validate if the address is valid correct

It would be nice to refactor and use the same function in both places

2023-02-01 18:09 UTC, tommasini approved these changes
LGTM!

Just good to have:
Could we have test cases when:
* Address is not valid
* ENS is not valid

2023-02-02 04:14 UTC, jpuri approved these changes
LGTM

2023-02-08 11:15 UTC, jpcloureiro approved these changes
Code looks good to me ✅ 
Left one suggestion

2023-02-08 11:15 UTC, jpcloureiro commented on app/components/Views/Send/index.js
> +    let ensRecipient;
`ensRecipient` is not being used anymore. Is it safe to remove it?

2023-02-08 11:15 UTC, jpcloureiro commented on app/util/address/index.js
> +}
Clean solution 👍

2023-02-08 11:18 UTC, blackdevelopa commented on app/components/Views/Send/index.js
> +    let ensRecipient;
Ah. It's used [here](https://github.com/MetaMask/metamask-mobile/blob/d2250bcc3be237c725f06b19dd51957a113ad90e/app/components/Views/Send/index.js#L284).

2023-02-08 11:38 UTC, blackdevelopa commented on app/components/Views/Send/index.js
> +    let ensRecipient;
I was wrong. Good catch. https://github.com/MetaMask/metamask-mobile/pull/5656/commits/6d64e74a9db950274c5b5780cc090cf48b1463ce

2023-02-08 11:47 UTC, jpcloureiro approved these changes

2023-02-08 11:48 UTC, merged