E2e appium/app launch times
MetaMask/metamask-mobile pull request #5666
Opened 2023-02-01 23:32 UTC by SamuelSalas

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-02-02 16:58 UTC, NicolasMassart commented on wdio/config/android.config.debug.js
> +    deviceName: 'R5CRA0C5ZXW',
Was this expected to be committed?

2023-02-02 17:03 UTC, SamuelSalas commented on wdio/config/android.config.debug.js
> +    deviceName: 'R5CRA0C5ZXW',
Already commit the proper changes, thanks for point this out

2023-02-05 00:12 UTC, chrisleewilcox approved these changes

2023-02-05 23:08 UTC, cortisiko requested changes

2023-02-06 17:01 UTC, SamuelSalas commented on wdio/step-definitions/app-launch-times.steps.js
> +When(/^I log into my wallet$/, async () => {
I dont see a common step for login once the app has been close in the same session

2023-02-06 17:04 UTC, SamuelSalas commented on wdio/step-definitions/app-launch-times.steps.js
> +Given(/^I have imported my wallet for app launch times$/, async () => {
The main reason was to both remove one hard coded driver.pause() and second one is that there while the steps are pretty much similar, i needed to move the wait for splash animation to appear to a different step so i could stop the timer

2023-02-06 17:05 UTC, SamuelSalas commented on wdio/step-definitions/common-steps.js
> +  await ImportFromSeedScreen.setLoginBiometrics('OFF');
Remove

2023-02-06 17:17 UTC, SamuelSalas commented on wdio/step-definitions/app-launch-times.steps.js
> +  await WelcomeScreen.isScreenTitleVisible();
My bad. The waitForSplashAnimationToDisplay() method has a hard coded pause, i created another method that just wait for the splash animation instead. Going to replace it with just the wait for the splash animation.

2023-02-06 17:43 UTC, SamuelSalas commented on wdio/features/AppLaunchTime.feature
> +    And main Wallet Screen is displayed
updated

2023-02-06 17:43 UTC, SamuelSalas commented on wdio/step-definitions/app-launch-times.steps.js
> +Given(/^main Wallet Screen is displayed$/, async () => {
remove

2023-02-06 17:43 UTC, SamuelSalas commented on wdio/step-definitions/app-launch-times.steps.js
> +  startTimer = new Date().getTime();
Update the gherkin for that step definition

2023-02-06 20:39 UTC, cortisiko commented on wdio/step-definitions/app-launch-times.steps.js
> +  startTimer = new Date().getTime();
okay updated.

2023-02-06 20:41 UTC, cortisiko commented on wdio/step-definitions/app-launch-times.steps.js
> +  await WelcomeScreen.isScreenTitleVisible();
trigger the test against Browserstack and see what the test runs look like

2023-02-06 21:29 UTC, SamuelSalas commented on wdio/step-definitions/app-launch-times.steps.js
> +When(/^I log into my wallet$/, async () => {
Got it

2023-02-06 21:29 UTC, SamuelSalas commented on wdio/step-definitions/app-launch-times.steps.js
> +  await WelcomeScreen.isScreenTitleVisible();
Got it

2023-02-08 19:02 UTC, SamuelSalas commented
Browerstack successful runs:
https://app-automate.browserstack.com/dashboard/v2/builds/af352c3cb4fc61986127b52d3b21c37a2213b608/sessions/b4b7f35b875b6dbcbee34304012c7e4ebef4db2e?searchQuery=b4b7f35b875b6dbcbee34304012c7e4ebef4db2e

2023-02-08 19:02 UTC, SamuelSalas commented
https://app-automate.browserstack.com/dashboard/v2/builds/af352c3cb4fc61986127b52d3b21c37a2213b608/sessions/45336fe6a5923b8ba7aa5cd62e840e27098ad893?searchQuery=45336fe6a5923b8ba7aa5cd62e840e27098ad893

2023-02-08 19:06 UTC, SamuelSalas commented
https://app-automate.browserstack.com/dashboard/v2/builds/af352c3cb4fc61986127b52d3b21c37a2213b608/sessions/442db6ff5fc55c5ba10563d147b1cd3f5d8f6082?searchQuery=442db6ff5fc55c5ba10563d147b1cd3f5d8f6082

2023-02-08 21:43 UTC, cortisiko approved these changes
great stuff @SamuelSalas 👏 👏

2023-02-08 21:43 UTC, merged