Appium/add scenario changepassword
MetaMask/metamask-mobile pull request #5672
Opened 2023-02-03 05:42 UTC by chrisleewilcox

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
Added change password scenario.

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-02-03 11:55 UTC, Andepande approved these changes

2023-02-04 22:21 UTC, cortisiko requested changes
PR looks good overall, just left a few comments. I did notice the test was failing for me on Browserstack. I ran it against the pixel 6 running android 12.

2023-02-07 00:11 UTC, chrisleewilcox commented on wdio/screen-objects/ChangePasswordScreens.js
> +  async tapCONFIRM() {
Updated.

2023-02-07 00:12 UTC, chrisleewilcox commented on wdio/screen-objects/ChangePasswordScreens.js
> +  get buttonCONFIRM() {
Updated.

2023-02-07 00:13 UTC, chrisleewilcox commented on app/components/Views/ResetPassword/index.js
> +                    // testID={CONFIRM_PASSWORD_INPUT_BOX_ID}
Updated.

2023-02-07 20:34 UTC, chrisleewilcox commented
Test result on browserstack:
https://app-automate.browserstack.com/dashboard/v2/builds/af352c3cb4fc61986127b52d3b21c37a2213b608/sessions/60b691472713286d50be20b8f33c7fe60e3ebb5c

2023-02-16 03:26 UTC, chrisleewilcox commented
Browserstack ./features/LockResetWallet.feature
https://app-automate.browserstack.com/dashboard/v2/builds/af352c3cb4fc61986127b52d3b21c37a2213b608/sessions/6ceedb26595d573523adf353e9ef95220260402f

2023-02-16 03:31 UTC, chrisleewilcox commented
Browserstack ./features/ChangePassword.feature
https://app-automate.browserstack.com/dashboard/v2/builds/af352c3cb4fc61986127b52d3b21c37a2213b608/sessions/2fece468aff3efe1283de3c52e2ed6cef8c01e20

2023-02-16 03:33 UTC, chrisleewilcox commented
detox
https://app.bitrise.io/build/ec89e75c-b9b4-4ade-9a79-0efc1f6461f9

2023-02-17 00:56 UTC, closed without merging