Fix/6.0.0 regression bugs
MetaMask/metamask-mobile pull request #5765
Opened 2023-02-14 18:18 UTC by Cal-L

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-02-14 18:33 UTC, jpcloureiro requested changes

2023-02-14 18:33 UTC, jpcloureiro commented on app/components/Nav/Main/MainNavigator.js
> +      tabBarLabel: strings('drawer.wallet'),
We can't pass translated strings into `tabBarLabel` since it is used to index `ICON_BY_TAB_BAR_LABEL` const in `TabBar` component

2023-02-14 19:37 UTC, jpcloureiro approved these changes

2023-02-15 03:12 UTC, chrisleewilcox commented
1. PASS
2. PASS
3. BNB education modal not displaying
4. PASS

2023-02-15 20:45 UTC, cortisiko approved these changes

2023-02-15 20:45 UTC, merged