use url-parse instead of native URL api
MetaMask/metamask-mobile pull request #5799
Opened 2023-02-20 21:30 UTC by jpcloureiro

**Description**

In-App browser do not handle special URLs (deeplinks like market://details?...)

Change from native URL API to `url-parse` package. This way the app do not throw an error & the invalid URL is handled by the browser.

**Screenshots/Recordings**

<img width="387" alt="image" src="https://user-images.githubusercontent.com/1649425/220201130-537e458f-e3d0-4ef2-9751-dc1fa3112713.png">

**Issue**

Progresses #5794

2023-02-20 21:46 UTC, Gudahtt commented
We are already using this polyfill: https://github.com/charpeni/react-native-url-polyfill which apparently follows the whatwg standard for `URL`, which does support custom protocols. I'm curious to know which specific scenario is failing that `url-parse` fixes.

2023-02-20 22:31 UTC, jpcloureiro commented
> We are already using this polyfill: https://github.com/charpeni/react-native-url-polyfill which apparently follows the whatwg standard for `URL`, which does support custom protocols. I'm curious to know which specific scenario is failing that `url-parse` fixes.

Invalid URL error handling needs to be implemented before replacing `parse-url` with the native URL API.

In this case (market://details?src=io.metamask. ...) the deeplink gets transformed somewhere into an invalid URL in the form of `null?src=io.metamask`.

`url-parse` being designed to not throw errors (like legacy nodejs url API) keeps the app from crashing

2023-02-20 23:14 UTC, Gudahtt commented
>deeplinks are transformed into an invalid URL

Ahhh I see. I thought you meant that `new URL` was throwing directly. That makes more sense.

2023-02-21 15:57 UTC, andreahaku approved these changes
LGTM

2023-02-21 16:09 UTC, chrisleewilcox commented
@jpcloureiro what is expected if user has coingecko app installed on device?  Will coingecko app open?  Can you confirm this?  Will need this confirmed in development before handing this over to QA.

2023-02-21 16:11 UTC, chrisleewilcox requested changes
Please review my comments about behavior for coingecko app on device.

2023-02-21 17:35 UTC, jpcloureiro commented
@chrisleewilcox 
In 5.14.0, the browser presents the "Something went wrong" screen regardless of having the coingecko app installed or not.

I would say this is the expected behaviour for this PR as well.

2023-02-21 17:41 UTC, chrisleewilcox approved these changes

2023-02-21 17:41 UTC, merged