[Improvement] Send Token E2E test
MetaMask/metamask-mobile pull request #5825
Opened 2023-02-23 13:12 UTC by Andepande

**Description**
- SendToken Flow originating from this [ticket](https://github.com/MetaMask/mobile-planning/issues/546)
- Increased Appium test coverage 
- Minor implementations to improve test runs
- PR based on deprecated PR [5793](https://github.com/MetaMask/metamask-mobile/pull/5793) with resolved comments
**ScreenShots**
Local test run:
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/110056475/220932475-91513496-2d8a-4384-af18-5773abe6ab85.png">

Browserstack test successful runs X3:
1 - https://app-automate.browserstack.com/dashboard/v2/builds/be5310c82607f6abeeb859c3db73cfc6112c2f55/sessions/5c13b2805691db2580f319962941791e4ad89fde
2 - https://app-automate.browserstack.com/dashboard/v2/builds/be5310c82607f6abeeb859c3db73cfc6112c2f55/sessions/e2dae7067d83f8031c2ddad4ac7479105997448a
3- https://app-automate.browserstack.com/dashboard/v2/builds/be5310c82607f6abeeb859c3db73cfc6112c2f55/sessions/a94b38101f748c07620e7777e4ecc2f21ea3a007

Failing tests

**Issue**

Progresses #???

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [ ] Any added code is fully documented

2023-02-23 15:56 UTC, NicolasMassart commented on wdio.conf.js
> +  waitforTimeout: 45000,
It's great if we can reduce timeouts this much. what made this possible?

2023-02-23 15:56 UTC, NicolasMassart commented on wdio/features/SendToken.feature
> +        Then The Token Symbol is displayed
We only tap to focus on token symbol field here, but we don't check the symbol is actually displayed, right?
Doing so would prevent the pause in the next "I tap on the Import button" step.
Am I missing something here?

2023-02-23 15:56 UTC, NicolasMassart commented on wdio/features/SendToken.feature
> +        And the token <TOKEN> being sent is visible
The amount will change for each test if we send tokens from the same address, right?

2023-02-23 15:56 UTC, NicolasMassart commented on wdio/features/SendToken.feature
> +            # | Goerli            | ETH   | 0.0004 | 0xebe6CcB6B55e1d094d9c58980Bc10Fed69932cAb |
Why commenting this case?

2023-02-23 15:56 UTC, NicolasMassart commented on wdio/features/SendToken.feature
> +        And I type amount "<AMOUNT>" into amount input field
this case requires token balance to be >, how do we prevent it to fail?

2023-02-23 15:56 UTC, NicolasMassart commented on wdio/features/SendToken.feature
> +            | AVAX Fuji | 1 USDC | 121212121212121212121 | 0xebe6CcB6B55e1d094d9c58980Bc10Fed69932cAb |
Maybe we could try a more realistic amount? I know it depends on the wallet balance but if we check first, we can find a value that's over the balance and not a hardcoded one?

2023-02-23 15:56 UTC, NicolasMassart commented on wdio/screen-objects/AmountScreen.js
> +        await Gestures.tap(this.amountInputField);
We should check the visibility of the field before tapping in.

2023-02-23 15:56 UTC, NicolasMassart commented on wdio/step-definitions/import-tokens.steps.js
> +const setTimeout = 1500; //added to run on physical device
I know it's not the change you made here, it's just the const, but any way we could prevent the pause (for instance on line 9) with wait for custom token address field to be visible instead?

2023-02-23 16:47 UTC, Andepande commented on wdio/features/SendToken.feature
> +            | AVAX Fuji | 1 USDC | 121212121212121212121 | 0xebe6CcB6B55e1d094d9c58980Bc10Fed69932cAb |
Makes sense, we could check the current value and add 1 maybe

2023-02-23 17:11 UTC, Andepande commented on wdio/step-definitions/import-tokens.steps.js
> +const setTimeout = 1500; //added to run on physical device
So there are some instances where an element would be available in the dom before it can be tapped, but appium would just tap that and move on to the next statement where it would fail.

2023-02-23 17:14 UTC, Andepande commented on wdio/step-definitions/import-tokens.steps.js
> +const setTimeout = 1500; //added to run on physical device
We can try asserting for specific attributes like whether an element is clickable before it taps but I believe when we tried that before it wasn't consistent

2023-02-23 17:16 UTC, Andepande commented on wdio/screen-objects/AmountScreen.js
> +        await Gestures.tap(this.amountInputField);
Implemented in Tap function within the Gestures class

2023-02-23 23:34 UTC, cortisiko commented on wdio/screen-objects/AmountScreen.js
> +        await Gestures.tap(this.amountInputField);
You should probably use `Gestures.waitAndTap`

2023-02-26 22:43 UTC, cortisiko requested changes
left a few comments. We will need to put our wallet keys behind an env variable to prevent loss of funds. We can discuss it tomorrow.

2023-02-26 22:43 UTC, cortisiko commented on wdio/helpers/Gestures.js
> +  static async tapTextContains(text, tapType = 'TAP') {
What do you think about renaming to either `tapByTextContaining` or `tapByStringContainingText`

2023-02-26 22:43 UTC, cortisiko commented on wdio/screen-objects/AmountScreen.js
> +  async isCorrectTokenConfirm(token) {
perhaps rename to `isTokenCorrect`

2023-02-26 22:43 UTC, cortisiko commented on wdio/screen-objects/AmountScreen.js
> +  async enterAmount(text) {
put the test action above the assertions

2023-02-26 22:43 UTC, cortisiko commented on wdio/screen-objects/TokenOverviewScreen.js
> +    async tapBackButton() {
put the test action before the assertion

2023-02-26 22:43 UTC, cortisiko commented on wdio/step-definitions/common-steps.js
> -Then(/^I am on the main wallet view/, async () => {
changing this step might cause other tests to fail. Can we confirm this is not the case?

2023-02-26 22:52 UTC, cortisiko commented
A couple more things: 

- Rename this PR. `[Improvement] Send Token E2E test`
- Fix the listing issues.

2023-02-27 05:56 UTC, DigitalsupportTeam commented
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

2023-02-27 10:25 UTC, Andepande commented on wdio/features/SendToken.feature
> +        And the token <TOKEN> being sent is visible
Yeah, the amount will change each time we send from that account, an idea I thought of was to have a hook that would transfer the amount back after the test has completed.

2023-02-27 10:26 UTC, Andepande commented on wdio/features/SendToken.feature
> +            # | Goerli            | ETH   | 0.0004 | 0xebe6CcB6B55e1d094d9c58980Bc10Fed69932cAb |
Commented for now as there are no funds on the goerli account therefore the test will fail

2023-02-27 10:26 UTC, Andepande commented on wdio/features/SendToken.feature
> +        And I type amount "<AMOUNT>" into amount input field
Maybe a close loop test that would send the funds back?

2023-02-27 10:28 UTC, Andepande commented on wdio/helpers/Gestures.js
> +  static async tapTextContains(text, tapType = 'TAP') {
yeah sure, thought maybe it was too long but I'll change it to that

2023-02-27 10:43 UTC, Andepande commented on wdio.conf.js
> +  waitforTimeout: 45000,
Browserstack had a delay in starting the app, therefore tests would begin before the app, Found some solutions with @SamuelSalas that would dynamically wait for pages to exist/Disappear which enabled the reduction of this

2023-02-27 11:05 UTC, Andepande commented on wdio/features/SendToken.feature
> +        Then The Token Symbol is displayed
true, it was missing the assertion which is now added, I think someone was added the extra pause while running on a physical device as it was failing without that extra pause, but never removed the pause in the PR.

2023-02-27 11:10 UTC, Andepande commented on wdio/step-definitions/common-steps.js
> -Then(/^I am on the main wallet view/, async () => {
That is not the case, it was a duplicate step

2023-02-27 20:58 UTC, SamuelSalas commented on wdio/helpers/Gestures.js
>          await elem.touchAction(Actions.TAP);
Mayber outside of scope, but i see that there are a lot of tap methods that practically do the same. Just with small changes.

2023-02-27 20:58 UTC, SamuelSalas commented on wdio/screen-objects/ChangePasswordScreens.js
> +/* eslint-disable no-undef */
any reason to add this exception?

2023-02-27 21:59 UTC, Andepande commented on wdio/helpers/Gestures.js
>          await elem.touchAction(Actions.TAP);
Yeah there, so getXpathElementByText() taps by text with the exact text, which is good for static text but for some buttons that have dynamic text like on the main wallet view if you want to tap on a specific token  e.g (1 USDC) without knowing the amount, using getXpathElementByTextContains() was more usefull.

2023-02-27 22:00 UTC, Andepande commented on wdio/screen-objects/ChangePasswordScreens.js
> +/* eslint-disable no-undef */
ES-Lint expection for driver.HideKeyboard on line 29

2023-02-28 17:34 UTC, SamuelSalas commented on wdio/helpers/Gestures.js
>          await elem.touchAction(Actions.TAP);
So, if the selectors methods are outside the tap method, the method is going to fail? Like, instead of having the text param, to have a  element param in the taptext methods?

2023-02-28 18:17 UTC, Andepande commented on wdio/helpers/Gestures.js
>          await elem.touchAction(Actions.TAP);
E.g On the main wallet view, the test has to tap on the USDC Token button which contains text "USDC" however there is always a prefix which is dynamic, like "1" or "2" USDC, but therefore if I use tapTextByXpath() to tap on USDC it won't work because you need to account for the prefix. But using getXpathElementByTextContains() would enable you to select the button by declaring the text it contains 'USDC'

2023-02-28 21:10 UTC, SamuelSalas approved these changes

2023-03-01 01:03 UTC, cortisiko approved these changes
🌮 🌮 🌮 🌮

2023-03-01 09:22 UTC, merged