Adding e2e for simpe send flow using default gas
MetaMask/metamask-mobile pull request #5833
Opened 2023-02-24 19:37 UTC by jpuri

Fixes: #5695

Adding e2e for simple send flow using default gas.

The e2e succeeded only after I added some GoreliETH to the account.

2023-02-24 19:38 UTC, jpuri commented on e2e/viewHelper.js
> +};
These helpers will be useful as we plan to write more e2e for send flow.

2023-02-26 21:56 UTC, cortisiko requested changes

2023-02-26 21:56 UTC, cortisiko commented on e2e/specs/send-eth-flow.spec.js
> +describe('Addressbook Tests', () => {
rename the test description

2023-02-26 21:56 UTC, cortisiko commented on e2e/viewHelper.js
> +};
Yup yup, I like this solution.

2023-02-26 21:56 UTC, cortisiko commented on e2e/specs/send-eth-flow.spec.js
> +'use strict';
can you create a subfolder called "Confirmations" in the specs folder, this way we put all the confirmations e2e tests

2023-02-27 04:23 UTC, jpuri commented on e2e/specs/send-eth-flow.spec.js
> +'use strict';
Good Idea I implemented this.

2023-02-27 05:55 UTC, DigitalsupportTeam commented
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

2023-03-01 00:05 UTC, cortisiko approved these changes
looks good to me. We are going to hide the SRP used in the tests behind an env variable. You can track the ticket [here](https://github.com/MetaMask/mobile-planning/issues/672).

2023-03-01 12:31 UTC, merged