Creating reusable address from/to component.
MetaMask/metamask-mobile pull request #5900
Opened 2023-03-06 17:03 UTC by jpuri

Ref: https://github.com/MetaMask/metamask-extension/issues/17246

The PR extracts out a re-usable component to display from/to addresses on send screen, this component will be re-used in following [PR](https://github.com/MetaMask/metamask-mobile/pull/5887):

![Screenshot 2023-03-06 at 10 28 21 PM](https://user-images.githubusercontent.com/2182307/223179860-f75f2ccb-580e-4993-b315-21eaf63da9f1.png)

---------------------------------------
QA Steps:
From / To address section in send screen shoulg continue to work as before for various combinations of addresses / tokens.

2023-03-09 16:24 UTC, blackdevelopa approved these changes

2023-03-14 00:46 UTC, digiwand commented on app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx
how are these passing the lint check? Are we excluding the indent rule from our ci/lint? 🤔 

<img width="1188" alt="Screen Shot 2023-03-13 at 5 41 12 PM" src="https://user-images.githubusercontent.com/20778143/224863269-eb1be42c-2307-4f5e-8bb3-3f9accb0a0e3.png">

2023-03-14 02:18 UTC, digiwand commented on app/components/Views/SendFlow/Confirm/index.js
> -        [, transactionTo] = decodeTransferData('transferFrom', data);
Q: how did we remove this logic to support the collectibles logic and `transferFrom` type? 

I was looking at AccountFromToInfoCard.tsx for a bit and I'm having trouble seeing the full picture

2023-03-14 07:55 UTC, jpuri commented on app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx
> +  }, [identities, ensRecipient]);
Hey @digiwand ; the probabilities of the code running multiple time is too low, but it is logical and correct to add all dependencies in array.

2023-03-14 07:57 UTC, jpuri commented on app/components/Views/SendFlow/Confirm/index.js
> -        [, transactionTo] = decodeTransferData('transferFrom', data);
Interesting thing is this file no longer exists
`import collectiblesTransferInformation from '../../../../util/collectibles-transfer';` but somehow old code was not complaining, as I wrote typescript code it was complained about this and thus I removed it.

2023-03-14 07:59 UTC, jpuri commented on app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx
Not sure these does not complaint for me. I also tried running `yarn run lint` locally.

2023-03-15 08:38 UTC, digiwand requested changes

2023-03-15 08:44 UTC, jpuri commented on app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx
> +      setFromAccountName(fromEns || fromName);
Hey @digiwand : it was not there in confirm page even before.

2023-03-15 18:31 UTC, digiwand commented on app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx
> +      setFromAccountName(fromEns || fromName);
oops, you are right

2023-03-15 18:33 UTC, digiwand approved these changes
LGTM! nice cleanup

2023-03-15 18:33 UTC, digiwand commented on app/components/Views/SendFlow/Confirm/index.js
> -        [, transactionTo] = decodeTransferData('transferFrom', data);
that is interesting

2023-03-21 09:43 UTC, seaona commented
Most of the QA happened [in this PR](https://github.com/MetaMask/metamask-mobile/pull/5887) as it integrates both changes. I've reported the issues there.

As per this PR specifically, I have one question. Do we expect the recipient address to be clickable? This allows the ability of adding the address to the address book.  @bschorchit  @jpuri 

It is done already on [Verify Contract details](https://github.com/MetaMask/MetaMask-planning/issues/179) in Mobile and it is also done on Extension in regular Sends.

This can be addressed in a different PR, as the issue was already there. Let me know if we should create a separate issue for that

https://user-images.githubusercontent.com/54408225/226567569-51f03efb-7f0d-4086-95e7-07184cd252cd.mp4

2023-03-21 17:17 UTC, bschorchit commented
Agree with Jyoti on creating a separate issue for this :)
Nice catch on this detail!

2023-03-21 18:10 UTC, seaona commented
Thank you both @jpuri @bschorchit ! Issue created [here](https://github.com/MetaMask/metamask-mobile/issues/6008)

2023-03-23 18:16 UTC, bschorchit commented
Should this PR be merged? As the reported issues are being handled in the other PR or in the new created ticket? @seaona

2023-03-28 12:57 UTC, seaona commented
Looks good!!
Note some QA worked from this PR happened [here](https://github.com/MetaMask/metamask-mobile/pull/5887)

2023-03-28 13:43 UTC, merged