[Feature] SDK Session Persistence
MetaMask/metamask-mobile pull request #5948
Opened 2023-03-10 08:22 UTC by abretonc7s

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-03-10 08:42 UTC, deeeed commented
I have read the CLA Document and I hereby sign the CLA

2023-03-13 09:32 UTC, andreahaku requested changes
few minor issues

2023-03-13 09:32 UTC, andreahaku commented on app/components/UI/AccountApproval/index.js
> +          <>
unnecessary fragment

2023-03-13 09:32 UTC, andreahaku commented on app/components/Views/SDKSessionsManager/SDKSessionsManager.tsx
> +        <View>
unnecessary `view`

2023-03-13 09:32 UTC, andreahaku commented on app/components/Views/SDKSessionsManager/SDKSessionItem.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
any reason for this?

2023-03-13 09:32 UTC, andreahaku commented on app/components/Views/SDKSessionsManager/SDKSessionsManager.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
any reason for this?

2023-03-13 09:32 UTC, andreahaku commented on app/components/Views/Settings/SecuritySettings/index.js
> +    this.props.navigation.navigate('SDKSessionsManager');
If I'm not wrong, we are using constants for navigation pages strings

2023-03-13 09:32 UTC, andreahaku commented on app/components/Views/Settings/SecuritySettings/index.js
> +      <>
unnecessary fragment

2023-03-13 09:32 UTC, andreahaku commented on app/components/Views/Settings/SecuritySettings/index.js
> +          <View>
this can be a fragment

2023-03-13 09:32 UTC, andreahaku commented on locales/languages/en.json
> +    "action_reconnect_deeplink": "Do you want to reconnect to thris dApp?",
typo `this`

2023-03-13 10:36 UTC, abretonc7s commented on app/components/Views/Settings/SecuritySettings/index.js
> +    this.props.navigation.navigate('SDKSessionsManager');
Doesn't seem to use constants, I copied from other views.

2023-03-13 11:25 UTC, andreahaku approved these changes
LGTM

2023-03-13 15:01 UTC, leotm reviewed
few minor comments

2023-03-14 07:41 UTC, andreahaku commented on app/core/SDKConnect/CommunicationLayer/types/LogggingOptions.ts
> +  // logger?: (_msg: string) => void;
This is a piece of the SDK code that we decided to temporarily embed in the code. We'll take your comments into account on the SDK repo. Thanks

2023-03-14 07:42 UTC, andreahaku commented on app/core/SDKConnect/CommunicationLayer/types/MessageType.ts
> +   * Used for debugging purpose and check channel validity.
This is a piece of the SDK code that we decided to temporarily embed in the code. We'll take your comments into account on the SDK repo. Thanks

2023-03-14 07:42 UTC, andreahaku commented on app/core/SDKConnect/CommunicationLayer/config.ts
> +export const DEFAULT_SESSION_TIMEOUT_MS = 7 * DAY_IN_MS;
This is a piece of the SDK code that we decided to temporarily embed in the code. We'll take your comments into account on the SDK repo. Thanks

2023-03-14 07:42 UTC, andreahaku commented on app/core/SDKConnect/CommunicationLayer/config.ts
> +export const CHANNEL_MAX_WAITING_TIME = 3 * 1000; // 3 seconds
This is a piece of the SDK code that we decided to temporarily embed in the code. We'll take your comments into account on the SDK repo. Thanks

2023-03-14 08:42 UTC, christopherferreira9 commented
QA'd and passed!

2023-03-14 11:47 UTC, abretonc7s commented
> **CLA Signature Action:**
> 
> Thank you for your submission, we really appreciate it. We ask that you read and sign our [Contributor License Agreement](https://metamask.io/cla.html) before we can accept your contribution. You can sign the CLA by just by adding a comment to this pull request with this exact sentence:
> 
> > _**I have read the CLA Document and I hereby sign the CLA**_
> 
> By commenting with the above message you are agreeing to the terms of the CLA. Your account will be recorded as agreeing to our CLA so you don't need to sign it again for future contributions to this repository.
> 
> **0** out of **1** committers have signed the CLA. ❌ @abretonc7s


I have read the CLA Document and I hereby sign the CLA

2023-03-14 14:42 UTC, leotm approved these changes

2023-03-14 18:00 UTC, Cal-L reviewed
Left some comments for now. Continuing to review

2023-03-14 19:48 UTC, Cal-L reviewed
Left some comments for now. Continuing to review

2023-03-14 19:48 UTC, Cal-L commented on app/core/DeeplinkManager.js
> +              console.warn(`DeepLinkManager invalid OTP params`);
Should this be reported to metrics?

2023-03-14 19:48 UTC, Cal-L commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +            const approved = getApprovedHosts()[hostname];
<3 how this isn't hardcoded to selectedAddress anymore. Can we do the same and remove `selectedAddress` from `getAccounts()`?

2023-03-14 19:48 UTC, Cal-L commented on app/core/SDKConnect/CommunicationLayer/Analytics.ts
> +export interface AnaliticsProps {
AnaliticsProps -> AnalyticsProps

2023-03-14 19:48 UTC, Cal-L commented on app/core/SDKConnect/CommunicationLayer/Analytics.ts
> +export const SendAnalytics = async (
What's the reason for sending analytics to a server url vs tracking using mix panel?

2023-03-14 19:48 UTC, Cal-L commented on app/core/SDKConnect/CommunicationLayer/ECIES.ts
> +import { decrypt, encrypt, PrivateKey } from 'eciesjs';
Can we rename `encrypt` to prevent confusion with `encrypt` method in the class. Same with `decrypt`

2023-03-14 19:48 UTC, Cal-L commented on app/core/SDKConnect/CommunicationLayer/ECIES.ts
> +  generateECIES(): void {
Not used. Will there be future changes that requires this?

2023-03-14 19:48 UTC, Cal-L commented on app/core/SDKConnect/CommunicationLayer/ECIES.ts
> +  toString() {
Seems redundant since we can just use `getKeyInfo` directly

2023-03-14 19:48 UTC, Cal-L commented on app/core/SDKConnect/CommunicationLayer/KeyExchange.ts
> +  private sendPublicKey: boolean;
Not used

2023-03-14 19:48 UTC, Cal-L commented on app/core/SDKConnect/CommunicationLayer/KeyExchange.ts
> +  private debug = false;
Not used

2023-03-14 20:18 UTC, Cal-L reviewed
Last comments. Since the communication layer has been included since we're waiting on the latest version to be published, feel free to address the communication layer comments how you see fit.

2023-03-14 20:18 UTC, Cal-L commented on app/core/SDKConnect/CommunicationLayer/types/AutoConnectOptions.ts
> +export interface AutoConnectOptions {
Since all of the type files only deal with exporting one type, it seems overkill to have a file for each one. Unless there's a usage style that's specific to isolating 1 type per file, can we place all of the types in a single file instead?

2023-03-14 20:18 UTC, Cal-L commented on app/core/SDKConnect/SDKConnect.ts
> +  serverUrl: 'https://metamask-sdk-socket.metafi.codefi.network/',
These seem like they could be moved to the app constants file

2023-03-14 20:18 UTC, Cal-L commented on app/reducers/modals/index.js
> +    case 'TOGGLE_SDKLOADING_MODAL':
Can remove all of these once the modals are moved to stack navigator

2023-03-14 20:18 UTC, Cal-L commented on locales/languages/en.json
> +    "donot_rememberme": "Do not remember me on this dApp",
do_not_remember_me

2023-03-14 20:18 UTC, Cal-L commented on package.json
> +    "@metamask/preferences-controller": "^2.1.0",
TODO: Stated in description - reintroduce communication layer once it has been published

2023-03-15 00:13 UTC, abretonc7s commented on app/components/UI/DrawerView/index.js
> +        <Modal
Would they still look like coming from drawer? Wouldn't creating them as a screen make the ui completely different?

2023-03-15 00:13 UTC, abretonc7s commented on app/components/UI/DrawerView/index.js
> +  toggleChannelDisconnectModal = () => {
Good catch, it was initially put there during debug. Forgot to remove.

2023-03-15 00:13 UTC, abretonc7s commented on app/components/UI/DrawerView/index.js
> +  toggleChannelDisconnectModal: () => dispatch(toggleChannelDisconnectModal()),
They are used (except the toggleChannelDisconnectModal)

2023-03-15 00:17 UTC, abretonc7s commented on app/components/UI/DrawerView/index.js
> +  toggleChannelDisconnectModal,
Those have been added in the actions. Not sure what you are referring?

2023-03-15 00:23 UTC, abretonc7s commented on app/components/Nav/App/index.js
> +    SDKConnect.getInstance().init();
Yes I also wanted to avoid a singleton, but kept it for consistency. Another option is to have a provider and access the sdk instance via hooks / provider context.

2023-03-15 01:18 UTC, abretonc7s commented on app/components/UI/AccountApproval/index.js
> +    otps: shuffle(this.props.currentPageInformation.otps || []),
Needed, otherwise the first value is always the answer.

2023-03-15 09:58 UTC, abretonc7s commented on app/components/UI/TransactionHeader/index.js
>      } else title = getHost(currentEnsName || url || origin);
Title not set otherwise, origin isn't matching initial conditions.
Added condition to make sure there is always a valid title.

2023-03-15 10:12 UTC, abretonc7s commented
@Cal-L lot of suggestions, I would say most of them can be combined into categories:
- remove unused code: very good point, I missed them as they were initially used for debugging and js files didn't warn of unused code (let's ban .js ! )
- communication layers issues: ignored for now, some unused properties are left here due to a massive refactoring of the sdk and wanted to maintain them in case anything needs to be rolled-back (and if need comparison to previous code). Will be remove by stage with upcoming versions.
- move code from Drawer to StackNavigator: Done.
- use typography for styling: done except in AccountApproval/index.js which is legacy code that needs a complete ts refactoring. It will be done for next release.

2023-03-15 10:42 UTC, abretonc7s commented on app/components/UI/DrawerView/index.js
> +        <Modal
Done

2023-03-15 10:45 UTC, abretonc7s commented on app/components/Views/SDKSessionsManager/SDKSessionsManager.tsx
> +    setTimeout(() => {
Fixed by moving to screen.

2023-03-15 10:46 UTC, abretonc7s commented on app/components/Views/SDKSessionsManager/SDKSessionsManager.tsx
> +  const renderEmptyResult = () => <Text>{strings('sdk.no_connections')}</Text>;
added typography

2023-03-15 10:54 UTC, abretonc7s commented on app/core/SDKConnect/SDKConnect.ts
> +  serverUrl: 'https://metamask-sdk-socket.metafi.codefi.network/',
It is meant to be completely removed when using the package which will contain the default url.

2023-03-15 10:55 UTC, abretonc7s commented on app/core/SDKConnect/CommunicationLayer/SocketService.ts
> +  private clientsConnected = false;
On the actual sdk they are used with a developerMode for debugging but it has been disabled / removed when copied to wallet.

2023-03-15 10:56 UTC, abretonc7s commented on app/core/SDKConnect/CommunicationLayer/WebRTCService.ts
> +    // this.removeAllListeners();
webrtcservice not used at all currently, can be ignored.

2023-03-15 10:59 UTC, abretonc7s commented on app/core/SDKConnect/CommunicationLayer/types/AutoConnectOptions.ts
> +export interface AutoConnectOptions {
Here I think it is subject to preference. I personally like to separate all my types so I can quickly view what is available in the source tree. Also it is easier to go to a specific file using the IDE and would usually enforce such a rule with a linter. In this case there is no rule for either direction so I would prefer to keep them separate until can be removed from wallet.

2023-03-15 16:40 UTC, Cal-L commented on app/components/UI/AccountApproval/index.js
> +    otps: shuffle(this.props.currentPageInformation.otps || []),
I see. The state is used to lock in the value to prevent re-renders from reshuffling.

2023-03-15 16:55 UTC, Cal-L commented on app/components/UI/TransactionHeader/index.js
>      } else title = getHost(currentEnsName || url || origin);
Since it's a fallback case, could we remove the last else condition then since your case will handle it already?

2023-03-15 17:01 UTC, Cal-L commented on locales/languages/en.json
> +    "donot_rememberme": "Do not remember me on this dApp",
Doesn't seem addressed yet

2023-03-15 17:05 UTC, Cal-L commented on app/components/UI/DrawerView/index.js
> +    /**
Remove any remaining instances of sdk modal toggle properties from all files

2023-03-15 17:09 UTC, Cal-L commented on app/components/Views/SDKFeedbackModal/SDKFeedbackModal.tsx
> +      <SDKFeedback />
Instead of having `SDKFeedback` call `navigation.goBack()`, you need to pass a callback like `onDismiss` to `SDKFeedback`, which calls `sheetRef.current.hide()`. Same for `SDKLoadingModal`

2023-03-16 00:33 UTC, abretonc7s commented on locales/languages/en.json
> +    "donot_rememberme": "Do not remember me on this dApp",
This has been added back into latest commit. UI displays the do not remember me checkbox.

2023-03-16 00:36 UTC, abretonc7s commented on app/components/Views/SDKFeedbackModal/SDKFeedbackModal.tsx
> +      <SDKFeedback />
SDKLoading state is managed outside of the modal, so I cannot add the callback. For this one using redux could make sense instead of forcing a dependency to the navigation when initiating the SDK instance.

2023-03-16 14:28 UTC, abretonc7s commented on app/core/SDKConnect/SDKConnect.ts
> +  serverUrl: 'https://metamask-sdk-socket.metafi.codefi.network/',
moved to AppConstants

2023-03-20 07:59 UTC, abretonc7s commented on app/components/UI/TransactionHeader/index.js
>      } else title = getHost(currentEnsName || url || origin);
I am not sure of the impact of replacing the else since it is one of the ifs that doesn't work as expected in some conditions with the SDK. To prevent unexpected behavior, it is safer to have the fallback after.

2023-03-20 22:52 UTC, Cal-L commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +            const approved = getApprovedHosts()[hostname];
TODO for the future

2023-03-20 22:57 UTC, Cal-L commented on app/components/UI/TransactionHeader/index.js
>      } else title = getHost(currentEnsName || url || origin);
The logic would be exactly the same since the else at the end is essentially a catch all case, which is the same outcome as the fallback. The equivalent logic would be to remove the last else condition and change `title === undefined || title.length === 0` -> `!title` for the fallback condition

2023-03-20 23:04 UTC, Cal-L commented on app/components/Views/SDKFeedbackModal/SDKFeedbackModal.tsx
> +      <SDKFeedback />
Ah ok.

Can you update SDKFeedbackModal to call `sheetRef.current.hide()` instead of `navigation.goBack()`? Once the sheet hides, it'll auto handle go back.

2023-03-21 02:37 UTC, Cal-L reviewed
LGTM

2023-03-22 16:33 UTC, christopherferreira9 commented
QA Passed!

2023-03-22 16:42 UTC, andreahaku approved these changes
LGTM

2023-03-22 16:56 UTC, merged