[IOS] Send Native and ERC-20 tokens
MetaMask/metamask-mobile pull request #6001
Opened 2023-03-20 19:55 UTC by Andepande

**Description**

As part of goal to Increase e2e test coverage for IOS/Android, this PR is:
- Added an e2e test spec for sending ERC-20 Tokens in the app.
- Added/Modified existing testID's and selectors 
- Added relevant code for test purposes.
- Tested locally against IOS simulator.

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [ ] Any added code is fully documented

2023-03-21 00:56 UTC, cortisiko requested changes
I left a few comments. I will continue tomorrow!

2023-03-21 00:56 UTC, cortisiko commented on e2e/pages/Onboarding/ImportWalletView.js
> +    await TestHelpers.replaceTextInField(
any reason for the change?

2023-03-21 12:42 UTC, Andepande commented on e2e/pages/Drawer/Settings/SettingsView.js
> +  static async tapSend() {
Removed

2023-03-21 12:44 UTC, Andepande commented on e2e/pages/Onboarding/ImportWalletView.js
> +    await TestHelpers.replaceTextInField(
instead of typing it just pastes the text into the field, much quicker.

2023-03-21 14:55 UTC, NicolasMassart commented on e2e/pages/ConfirmView.js
> +const CONFIRM_SEND_BUTTON = 'txn-confirm-send-button';
Q: Why is this id not in the test id file shared with app?

2023-03-21 14:55 UTC, NicolasMassart commented on e2e/pages/EnableAutomaticSecurityChecksView.js
> +      ENABLE_AUTOMATIC_SECURITY_CHECK_NO_THANKS_BUTTON,
Q: according to our automation manifesto, I understood that we should name these variables with `_ID` at the end, like `ENABLE_AUTOMATIC_SECURITY_CHECK_NO_THANKS_BUTTON_ID`. Is there any exceptions here? Why?

2023-03-21 14:55 UTC, NicolasMassart commented on e2e/pages/LoginView.js
> +    await TestHelpers.tapByText('UNLOCK');
Q: do we always use the english text for tests or should we use the translation system?

2023-03-21 14:55 UTC, NicolasMassart commented on e2e/specs/send-ERC-token.spec.js
> +
C: I know it's already like that in other tests, but we could start in this one to maybe clarify that these steps are only the initialisation steps and not the test itself. Maybe rename the steps "Import wallet" or something?
Also would it be interesting to have this init done in one function call in the beforeAll so we only focus on the actual test in the test file? it would make it reusable also and reduce code duplication...

2023-03-21 14:55 UTC, NicolasMassart commented on e2e/specs/send-ERC-token.spec.js
> +    await TestHelpers.delay(2000);
Q: can we remove this delay by waiting for the symbol filed to be visible?

2023-03-21 14:55 UTC, NicolasMassart commented on e2e/specs/send-ERC-token.spec.js
> +    await TestHelpers.delay(1000);
Q: can we wait for the next button instead of this delay?

2023-03-21 14:55 UTC, NicolasMassart commented on e2e/specs/send-ERC-token.spec.js
> +    await ConfirmView.tapSendButton();
Q: should we test the tokens were actually sent by verifying the remaining balance?

2023-03-21 14:55 UTC, NicolasMassart commented on e2e/specs/send-ERC-token.spec.js
> +  });
C: This test does exactly the same thing as the previous one. It uses the same screen. The only difference is how you land on the screen. I feel like it would be only required to test that the screen is reached but no need to do the send test again. It would be faster and use less test token.

2023-03-21 15:24 UTC, Andepande commented on e2e/pages/LoginView.js
> +    await TestHelpers.tapByText('UNLOCK');
I believe our current scope for now is in English, but this was just a temporary function, it'll be removed

2023-03-21 16:55 UTC, Andepande commented on e2e/specs/send-ERC-token.spec.js
> +
I agree, going we'll be creating a ticket to refactor our Detox tests.

2023-03-21 17:20 UTC, Andepande commented on e2e/specs/send-ERC-token.spec.js
> +  });
I'm told a bug existed previously which prevented sending tokens from the token overview page

2023-03-21 19:10 UTC, Andepande commented on e2e/specs/send-ERC-token.spec.js
> +    await ConfirmView.tapSendButton();
As discussed difficult to test while consistently while concurrent tests occur.

2023-03-21 19:11 UTC, Andepande commented on e2e/specs/send-ERC-token.spec.js
> +    await TestHelpers.delay(1000);
As discussed, will be covered in next refactor ticket for detox to verify it doesn't impact Bitrise runs.

2023-03-21 19:11 UTC, Andepande commented on e2e/specs/send-ERC-token.spec.js
> +    await TestHelpers.delay(2000);
As discussed, will be covered in next refactor ticket for detox to verify it doesn't impact Bitrise runs.

2023-03-21 19:21 UTC, Andepande commented on e2e/pages/WalletView.js
> +    await TestHelpers.waitAndTap(`asset-${token}`);
Implemented

2023-03-21 22:28 UTC, NicolasMassart reviewed
Great work. Thanks.
Good for me if this test passes on CI.

2023-03-22 12:34 UTC, SamuelSalas approved these changes

2023-03-23 00:49 UTC, cortisiko approved these changes
The code looks good. Just make sure the tests run successfully on detox.

2023-03-27 09:08 UTC, merged