Add toggle to enable/disable multi account balances fetching
MetaMask/metamask-mobile pull request #6026
Opened 2023-03-23 16:43 UTC by Fatxx

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-03-29 21:59 UTC, Cal-L commented on app/components/Views/AccountSelector/AccountSelector.tsx
> +        selectedAddress={selectedAddress}
Shouldn't need to pass `selectedAddress` since `accounts` object should already have `isSelected` boolean nested within it. Check `AccountSelectorList's `renderAccountItem` function.

2023-03-29 21:59 UTC, Cal-L commented on app/components/Views/AccountSelector/AccountSelector.tsx
> +    selectedAddress,
can remove

2023-03-29 21:59 UTC, Cal-L commented on app/components/hooks/useAccounts/useAccounts.ts
> +    isMultiAccountBalancesEnabled,
A cleaner approach would be to update the `mappedAccount` to update the `assets` field instead. For example, if `isMultiAccountBalancesEnabled` is false, the `assets` field would be `undefined` and you can use that to render null in the components. This way, you don't have to pass `isMultiAccountBalancesEnabled` in multiple places.

2023-03-29 21:59 UTC, Cal-L commented on app/components/hooks/useAccounts/useAccounts.types.ts
> +  selectedAddress: string;
Can remove both of these extra fields. Refer to previous comments.

2023-03-29 21:59 UTC, Cal-L commented on app/components/Views/Settings/SecuritySettings/index.js
> +    const { PreferencesController } = Engine.context;
Nit - move deconstructed Engine.context to top of function

2023-03-29 21:59 UTC, Cal-L commented on app/components/Views/AccountPermissions/AccountPermissionsConnected/AccountPermissionsConnected.tsx
> +  selectedAddress,
Can remove these fields. Refer to other comments.

2023-03-29 21:59 UTC, Cal-L commented on app/components/Views/AccountPermissions/AccountPermissions.tsx
> +    isMultiAccountBalancesEnabled,
Can undo all changes on this page. Refer to other comments.

2023-03-29 21:59 UTC, Cal-L commented on app/components/Views/AccountConnect/AccountConnectSingleSelector/AccountConnectSingleSelector.tsx
> +  selectedAddress,
Can remove these fields. Refer to other comments.

2023-03-29 21:59 UTC, Cal-L commented on app/components/Views/AccountConnect/AccountConnectMultiSelector/AccountConnectMultiSelector.tsx
> +  selectedAddress,
Can remove these fields. Refer to other comments.

2023-03-29 21:59 UTC, Cal-L commented on app/components/UI/AccountSelectorList/AccountSelectorList.tsx
> +      isMultiAccountBalancesEnabled,
Can remove these fields. Refer to other comments.

2023-03-29 21:59 UTC, Cal-L commented on app/components/UI/AccountSelectorList/AccountSelectorList.tsx
> +        if (!isMultiAccountBalancesEnabled) {
- for `selectedAddress`, you can use `isSelected`
- For `isMultiAccountBalancesEnabled`, once the other changes are addressed, you should be able to just check for the existence of `assets` and render null if it's undefined

2023-03-29 21:59 UTC, Cal-L commented on app/components/Views/Settings/SecuritySettings/index.js
> +  toggleIsMultiAccountBalancesEnabled = (isMultiAccountBalancesEnabled) => {
It was intended to track analytics via the user profile property in `Analytics.js` file `_setUserProfileProperties` instead

2023-03-29 22:06 UTC, Fatxx commented on app/components/Views/Settings/SecuritySettings/index.js
> +  toggleIsMultiAccountBalancesEnabled = (isMultiAccountBalancesEnabled) => {
@NicolasMassart can you check this one please

2023-03-30 12:50 UTC, NicolasMassart commented on app/components/Views/Settings/SecuritySettings/index.js
> +  toggleIsMultiAccountBalancesEnabled = (isMultiAccountBalancesEnabled) => {
We won't have analytics on the toggle event itself then, so no way to know if users use it a lot or not, is this fine?
We will only have infos on the user profile state with other event.
Or should I keep both?

2023-03-30 13:49 UTC, NicolasMassart commented on app/components/UI/AccountSelectorList/AccountSelectorList.tsx
> +        <Text style={styles.balanceLabel} testID="balance-label">
REQ: something like `{...generateTestId(Platform, `${BALANCE_LABEL_PREFIX}${address}`)}` function should be used to get the right testId prop and also make sure the id is unique. Otherwise it will be the same for all accounts in the list. You can use the address as the key as it's what's used as key on the list.

2023-03-30 16:17 UTC, NicolasMassart commented on app/components/UI/AccountSelectorList/AccountSelectorList.tsx
> +        <Text style={styles.balanceLabel} testID="balance-label">
as discussed I will handle this change and make sure it works for intergration test and e2e

2023-03-31 10:54 UTC, NicolasMassart commented on app/components/UI/AccountSelectorList/AccountSelectorList.tsx
> +        <Text style={styles.balanceLabel} testID="balance-label">
TestIds rework will be a suggestion on the app wide scope in another ticket. So many test Ids are wrong...

2023-03-31 10:55 UTC, NicolasMassart approved these changes
Looks good to me.

2023-03-31 17:27 UTC, Cal-L commented on app/components/Views/Settings/SecuritySettings/index.js
> +  toggleIsMultiAccountBalancesEnabled = (isMultiAccountBalancesEnabled) => {
Yeah let's remove this since we're tracking it in the user profile properties

2023-04-04 21:48 UTC, Cal-L commented on patches/@metamask+assets-controllers+3.0.1.patch
> +--- a/node_modules/@metamask/assets-controllers/dist/AccountTrackerController.js.map
It looks like you included some unrelated changes. Try these steps to regenerate the patch
1. Remove node_modules
2. run `yarn`
3. Apply your changes to node_modules
4. yarn patch-package @metamask/assets-controllers

2023-04-05 15:46 UTC, Fatxx commented on patches/@metamask+assets-controllers+3.0.1.patch
> +--- a/node_modules/@metamask/assets-controllers/dist/AccountTrackerController.js.map
This was copied from the controllers compiled source.

But there is another issue because there were patches already made so I cannot copy directly from the compiled controllers PR since the other patches are not in that branch.

I'll fix this.

2023-04-05 17:51 UTC, NicolasMassart approved these changes, later dismissed
Looks good to me.

2023-04-05 17:51 UTC, NicolasMassart commented on app/components/UI/AccountSelectorList/AccountSelectorList.tsx
> +            (assets && renderAccountBalances(assets, address))}
C: That's what I thought we had no choice to do. Otherwise would mean not using testId at all but not practical.

2023-04-05 18:22 UTC, Cal-L submitted a review, later dismissed
LGTM

2023-05-15 23:35 UTC, cortisiko requested changes, later dismissed
@Fatxx sending this back your way:

1. [Translations](https://www.screencast.com/t/KBa8pMJw66) are missing. 

2. I cannot see analytic events: 

  -  Locally when I enable and disable “batch account balance requests” 
  -  In a preproduction version of the app: I had an iOS version of the QA app > I went ahead and toggled “batch account balance requests” to off, but when I searched [mix panel](https://www.screencast.com/t/wJA7Fa5WkD3) the analytics did not appear.

What wasn't tested:
upgrading the app from a previous version to a version containing this PR. Can we kick off a release build for this branch?

2023-05-31 18:03 UTC, Cal-L reviewed
Left a small comment

2023-06-01 09:34 UTC, NicolasMassart commented
> @Fatxx sending this back your way:
> 
> 1. [Translations](https://www.screencast.com/t/KBa8pMJw66) are missing.
> 2. I cannot see analytic events:
> 
> * Locally when I enable and disable “batch account balance requests”
> * In a preproduction version of the app: I had an iOS version of the QA app > I went ahead and toggled “batch account balance requests” to off, but when I searched [mix panel](https://www.screencast.com/t/wJA7Fa5WkD3) the analytics did not appear.
> 
> What wasn't tested: upgrading the app from a previous version to a version containing this PR. Can we kick off a release build for this branch?

https://github.com/MetaMask/metamask-mobile/issues/5321#issuecomment-1563185509

2023-06-01 14:08 UTC, sethkfman approved these changes
LGTM

2023-06-01 15:42 UTC, Cal-L reviewed
LGTM

2023-06-02 11:27 UTC, merged