fix: linea network order in dropdown and feature toggle removal for linea
MetaMask/metamask-mobile pull request #6072
Opened 2023-03-29 17:29 UTC by VGau

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
- Fix Linea network order issue in network list dropdown
- Remove feature toggle for Linea as the public testnet is already live

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-03-29 18:00 UTC, NicolasMassart reviewed
I think it's fine and just added questions so that I can better understand your decisions on these changes.

2023-03-29 18:23 UTC, VGau commented on app/components/UI/NetworkList/index.js
> +      rpcTarget === new URL(LINEA_TESTNET_RPC_URL).href
It is because RPC type networks rpcUrls are formatted (using `new URL(...)` ) before being added to the `frequentRpcList` array. This formatting adds a trailing `/`  at the end of the rpcUrl. By default rpcUrls don't have trailing `/` in `app/util/networks/customNetworks.tsx`.
When we add a new RPC network manually from the settings, the rpcUrls are formatted before being added to the `frequentRpcList`.
For the Linea network, as it should display by default in the dropdown, it will be added to the `frequentRpcList` when we select it for the first time.
That's why there is this condition:
- We first check that the linea network is not already in the `frequentRpcList` array
- We also check that the `rpcTarget` is the linea network.
This condition will only be true once.

2023-03-29 18:26 UTC, VGau commented on app/components/UI/NetworkList/index.js
> +    rpcList = frequentRpcList.filter(
`Array.includes()`only checks if an element is in the array or not. Here we want to remove the Linea network from the list because the Linea network is already display using the `renderNonInfuraNetwork` function. If we don't filter this array, the linea network will be displayed twice in the network dropdown :)

2023-03-29 18:28 UTC, VGau commented on app/components/UI/NetworkList/index.js
> +      rpcURL.href,
because we only need the formatted rpcUrl  :)

2023-03-29 21:39 UTC, Cal-L commented
Can you confirm if we should also show Linea in the test network section on the networks page in settings?
<img width="336" alt="image" src="https://user-images.githubusercontent.com/10508597/228673877-5f667ea1-07d9-4538-b8b1-0079cdda1d82.png">

2023-03-29 21:40 UTC, Cal-L requested changes
Can you confirm if we should also show Linea in the test network section on the networks page in settings?
<img width="336" alt="image" src="https://user-images.githubusercontent.com/10508597/228673877-5f667ea1-07d9-4538-b8b1-0079cdda1d82.png">

Vid is just outdated. Please ignore.

2023-03-29 23:55 UTC, chrisleewilcox approved these changes
LGTM

2023-03-29 23:57 UTC, chrisleewilcox commented
@Cal-L can confirm Linea is in the Test networks section in Settings > Networks screen...
![image](https://user-images.githubusercontent.com/6626407/228694065-6335f9fc-2c7f-4b50-9f9a-00c75cdc4381.png)

2023-03-30 00:01 UTC, Cal-L reviewed
Looks like video was just outdated. LGTM

2023-03-30 00:01 UTC, Cal-L approved these changes
LGTM

2023-03-30 00:37 UTC, Cal-L commented
Resolved convos. Please bring up any other concerns and we'll address in separate PR.

2023-03-30 00:37 UTC, merged