Use Node environment for e2e tests
MetaMask/metamask-mobile pull request #6088
Opened 2023-03-31 19:26 UTC by Gudahtt

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

The Jest configuration used for Detox e2e tests has been updated to use a Node.js environment rather than React Native presets. This was a requirement for using Ganache as part of e2e tests (it was incompatible with some of the global changes introduced by the React Native environment).

The Jest process doesn't need to execute any React Native code directly as part of the e2e test suite. The only direct reference today was via the `i18n` module, which was accessed to retrieve localized messages. All such references were updated to use the JSON file directly, to avoid importing React Native libraries.

**Issue**

Progresses https://github.com/MetaMask/mobile-planning/issues/765

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

2023-04-03 23:53 UTC, Gudahtt commented
It seems that the [static image imports](https://reactnative.dev/docs/images#static-image-resources) might be causing some trouble; I'll investigate.

2023-04-05 12:52 UTC, Gudahtt commented
The e2e test errors we encountered should now be resolved. They were caused by imports of test IDs in e2e tests that also brought in unrelated lines of code that would only work correctly in a React Native context. The test IDs have been migrated to an alternative constants file instead that just includes string literal constants, no imports.

2023-04-12 11:13 UTC, NicolasMassart requested changes

2023-04-12 11:13 UTC, NicolasMassart commented on app/component-library/components/Cells/Cell/variants/CellSelect/CellSelect.tsx
> +import { CELL_SELECT_TEST_ID } from '../../../../../../constants/test-ids';
REQ: 
- this test id constant is used twice in the component, only one testID prop should be added. [Line 36](https://github.com/MetaMask/metamask-mobile/pull/6088/files#diff-0fd6dbdb0f9e3ae036c54f237f82817f617ee7a57f4d8a33e0c9e34f1432e899R36) `testID={CELL_SELECT_TEST_ID}` could be removed.
- test id is not unique. This item is a select item that will appear in a list in the app. It works here in the integration test isolated context, but will fail in e2e as we won't be able to target a specific item if ids are not unique for each item of the list. A suffix should be used to make this unique like the cell base title or something from the avatar props.

2023-04-12 11:48 UTC, Gudahtt commented on app/component-library/components/Cells/Cell/variants/CellSelect/CellSelect.tsx
> +import { CELL_SELECT_TEST_ID } from '../../../../../../constants/test-ids';
This is a pre-existing problem though right? I'm not introducing this test ID in this PR. I just had to move it in order to avoid React Native style png imports in the Jest test runner process.

2023-04-12 15:49 UTC, NicolasMassart approved these changes
Looks good to me.

2023-04-12 18:06 UTC, Gudahtt commented
I ran the iOS e2e tests on Bitrise here: https://app.bitrise.io/build/c4dfd2cd-7316-4d2d-b37a-7c8cd8a2a15a

Like on `main`, it timed out and the deeplink tests failed. Presumably that is expected for now, until it's fixed on main.

But there was one additional failure, for the test `Browser Tests › should test phishing sites`. I'm investigating that now.

2023-04-12 19:24 UTC, Gudahtt commented
It looks like `main` has the same failure at the moment. This branch passes all tests that are passing on `main`.

2023-04-12 19:25 UTC, merged