Added closed Whats new modal steps for appium
MetaMask/metamask-mobile pull request #6155
Opened 2023-04-10 17:32 UTC by SamuelSalas

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
Move existing code to close what's new content after take a tour for the appium test cases.

**Issue**

Progresses https://github.com/MetaMask/metamask-mobile/issues/6149

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-04-10 22:00 UTC, sethkfman commented on app/components/UI/WhatsNewModal/WhatsNewModal.tsx
> +} from '../../../../wdio/screen-objects/testIDs/Components/WhatsNewModal.testIds';
Why are these ids being moved out of the app folder?

2023-04-10 22:02 UTC, sethkfman commented on wdio/features/Accounts/CreatingWalletAccount.feature
> +    And I close the Whats New modal
I see we are changing this in a lot of feature files. Is there not a standard share setup? The same 3 test steps are shared in every test case.

2023-04-10 23:23 UTC, SamuelSalas commented on app/components/UI/WhatsNewModal/WhatsNewModal.tsx
> +} from '../../../../wdio/screen-objects/testIDs/Components/WhatsNewModal.testIds';
I change the location of the ids to the wdio folder so the same ids could be located in the same file. When running the Appium test scripts, in some occasions the test failed because it didn't find the test-id. Just validate that this behavior does not appear for the whats new modal. I'll make the proper changes.

2023-04-10 23:25 UTC, SamuelSalas commented on wdio/features/Accounts/CreatingWalletAccount.feature
> +    And I close the Whats New modal
I added the extra step to follow the two previous steps for the enable security and onboarding modals. We could have one step for the three, but I think @cortisiko could give a proper answer about this.

2023-04-11 15:16 UTC, cortisiko commented on wdio/features/Accounts/CreatingWalletAccount.feature
> +    And I close the Whats New modal
@sethkfman @SamuelSalas We opted to have our feature files written in an imperative style. The purpose of this is to enable engineers to easily identify which step cause bug(s). I do however agree that we _should_ write the steps in a more high level manner. We will aim to have our tests written in a more declarative style in Q3/Q4.

2023-04-11 15:54 UTC, cortisiko requested changes
one comment

2023-04-11 15:54 UTC, cortisiko commented on app/components/UI/WhatsNewModal/WhatsNewModal.tsx
> +        testID={WHATS_NEW_MODAL_CONTAINER_ID}
seems a bit redundant to have the `TestID` prop as well as the `generateTestID` method. Can you remove the `TestID` prop and have the page object for the what's new modal in detox point to the path of `WHATS_NEW_MODAL_CONTAINER_ID`

2023-04-11 22:28 UTC, SamuelSalas commented on app/components/UI/WhatsNewModal/WhatsNewModal.tsx
> +        testID={WHATS_NEW_MODAL_CONTAINER_ID}
Done.

2023-04-12 00:29 UTC, cortisiko approved these changes
Looks good Sam

2023-04-12 00:33 UTC, merged