Cleanup approve transaction review
MetaMask/metamask-mobile pull request #6213
Opened 2023-04-19 08:49 UTC by jpuri

Fixes: #6159

The task was about extracting out tooltip component from ApproveTransactionReview component but I found that the tooltip was actually not being used anywhere. Thus I delete it from the code.

QA Steps:
- The PR only removes un-used code, a check can be done to ensure that gas tooltip on confirmation pages work as before.

![Screenshot 2023-04-19 at 2 18 32 PM](https://user-images.githubusercontent.com/2182307/233021630-2bf4bc3b-efe2-476d-8f3a-6172374f7460.png)

2023-04-21 08:31 UTC, blackdevelopa commented on app/components/UI/ApproveTransactionReview/index.js
> -  renderQRDetails() {
Hey @jpuri, just checking why this was removed. I can't seem to find where it was moved to. TY

2023-04-21 08:47 UTC, blackdevelopa approved these changes
It seem `isSigningQRObject` isn't passed to the ApproveTransactionReview component and so has no value. So yeah, lgtm. Great find, @jpuri

2023-04-22 11:00 UTC, segun commented on app/components/UI/ApproveTransactionReview/index.js
> -  renderQRDetails() {
+1

2023-04-25 11:04 UTC, gantunesr commented on app/components/UI/ApproveTransactionReview/index.js
> -  renderQRDetails() {
Hi team, I have the same question as @blackdevelopa. As far as I know, that component is used with QR based hardware wallets like keystone

2023-04-25 11:40 UTC, jpuri commented on app/components/UI/ApproveTransactionReview/index.js
> -  renderQRDetails() {
This is dead code, it is not reachable and its safe to get rid of.

2023-04-25 16:08 UTC, segun approved these changes

2023-04-25 16:32 UTC, plasmacorral requested changes
In a spot check I am I encountering an issue with spending approvals when using Keystone. After tapping approve, the button becomes disabled but the QR modal fails to open and present the composed transaction (to be scanned with Keystone).

iPhone 13 mini
iOS 15.6.1

https://recordit.co/FDiMZnGtz5

Steps to reproduce:
1. Import SRP
2. bind with Keystone
3. Be on testnet or change to it (sepolia)
4. Open test dapp
5. deploy collectables contract (patience required here)
6. Add tokens to wallet and transfer tokens (may not be required steps)
7. On test dapp tap Approve tokens
8. Tap Approve
9. Note absence of presented QR

2023-04-26 04:10 UTC, jpuri commented
Hey @gantunesr , @plasmacorral : thanks a lot for helping with this. @plasmacorral : reported that this PR indeed has issue with QR scanning flow. I have updated the PR to remove QR code related cleanup. I will create a separate PR for cleaning that up.

2023-04-28 16:35 UTC, seaona commented
From QA changes look good @jpuri . The tooltip is working as before in the different flows (Send ETH / Send token / Contract Interaction ..) and in different networks


https://user-images.githubusercontent.com/54408225/235204056-74e254b6-2f07-4527-b7ad-29c961270763.mp4

PR can be merged. Whenever I get the Keystone, I can QA the other changes. 

PS Thank you @plasmacorral for doing an initial QA on the QR code part !

2023-04-28 17:34 UTC, plasmacorral commented
Just want to confirm no issues observed with Keystone approval in commit 99fa02b56b931b92e9ab9b5aa2e4f6054f65d1de on the same iphone I previously tested with.

https://recordit.co/wrCPIUufPa

2023-04-28 17:39 UTC, plasmacorral approved these changes

2023-04-29 00:16 UTC, merged