[e2e] Add Ganache seeder for deploying contracts and add simple Send ETH test to Multisig contract
MetaMask/metamask-mobile pull request #6217
Opened 2023-04-19 14:52 UTC by seaona

**Description**
- This PR adds the ability to easily deploly smart contracts on the background using Ganache
- The smart contracts directly available are the ones provided by the `test-dapp` dependency
- As a simple showcast, this PR also adds a simple e2e test where we require a Multisig contract to be deployed on Ganache, for later sending ETH to that account
- At the moment the Multisig contract address is hardcoded on the test. Pending to resolve how to grab variables from the global/background scope into the `.features` file. This can be done in a subsequent PR
- For testing the implementation you can test the confirmations suite, by running `yarn test:wdio:android --suite confirmations`

**Screenshots/Recordings**
/

**Issue**
- Resolves https://github.com/MetaMask/mobile-planning/issues/897

**Checklist**

* [X] There is a related GitHub issue
* [X] Tests are included if applicable
* [X] Any added code is fully documented

2023-04-19 15:13 UTC, jpuri submitted a review, later dismissed

2023-04-20 09:43 UTC, seaona commented on wdio/features/Confirmations/SendEthMultisig.feature
> +  Scenario: Setting up Ganache local network
In the future, this scenario should be injected in state

2023-04-20 09:45 UTC, seaona commented on wdio/features/Confirmations/SendEthMultisig.feature
> +      | 0x4aff835038b16dccdb1670103c4877a8f93e5219 | 1      |
This is the hardcoded address from the Multisig deployed contract on Ganache. In the future, this should be dynamically injected. Pending to figure out how to access to variables from the "world"/testing scope from the `.features` files - if possible

2023-04-20 10:28 UTC, seaona commented on wdio/features/Confirmations/SendEthMultisig.feature
> +      | 0x18b06605539dc02ecd3f7ab314e38eb7c1da5c9b | 1      |
At the moment the Multisig contract address is hardcoded on the test. Pending to resolve how to grab variables from the global/background scope into the .features file. This can be done in a subsequent PR

2023-04-20 10:49 UTC, seaona commented on wdio/features/Confirmations/SendEthMultisig.feature
> +      | 0x18b06605539dc02ecd3f7ab314e38eb7c1da5c9b | 1      |
More on this: `That's not supported. If you want dynamic data you have to handle this in your step definitions.`
https://community.smartbear.com/t5/Cucumber-Open/Dynamic-values-in-feature-file/td-p/214332

2023-05-17 02:28 UTC, chrisleewilcox requested changes
Please review comments.

2023-05-17 02:28 UTC, chrisleewilcox commented on bitrise.yml
> +                yarn test:wdio:android:browserstack:local
@seaona this was intended for local configuration to run test on browserstack on your local system.  If we change this then will the original reference config file be needed?  Should we revert this so to keep bitrise using the same config?

2023-05-17 02:28 UTC, chrisleewilcox commented on wdio/config/android.config.browserstack.local.js
> +  process.env.BROWSERSTACK_TAG_EXPRESSION || '@androidApp'; // pass tag to run tests specific to android
@seaona can you change this to '@smoke'?  We want to keep the default test on bitrise to be smoke test.

2023-05-17 02:28 UTC, chrisleewilcox commented on wdio/features/Confirmations/SendEthEOA.feature
> +  Scenario Outline: Sending ETH to an EOA from inside MetaMask wallet
If not using data table then should be Scenario instead of Scenario Outline.

2023-05-17 02:28 UTC, chrisleewilcox commented on wdio/features/Confirmations/SendEthMultisig.feature
> +
@seaona remove space

2023-05-17 02:28 UTC, chrisleewilcox commented on wdio/features/Confirmations/SendEthMultisig.feature
> +
@seaona remove space

2023-05-17 02:28 UTC, chrisleewilcox commented on wdio/features/Confirmations/SendEthMultisig.feature
> +
@seaona remove space

2023-05-17 02:28 UTC, chrisleewilcox commented on wdio/features/Confirmations/SendEthMultisig.feature
> +    And I enter address "<MultisigAddress>" in the sender's input box
@seaona remove quotes around parameter values

2023-05-17 02:28 UTC, chrisleewilcox commented on wdio/features/Confirmations/SendEthMultisig.feature
> +    When I type amount "<Amount>" into amount input field
@seaona remove quotes around parameter values

2023-05-17 02:28 UTC, chrisleewilcox requested changes
Please review comments.

2023-05-17 07:01 UTC, seaona commented on bitrise.yml
> +                yarn test:wdio:android:browserstack:local
To you first question, the script itself already points to the local config, so no need to change anything else. See package.json:
`"test:wdio:android:browserstack:local": "yarn wdio ./wdio/config/android.config.browserstack.local.js",`

To your second question, using local config is needed in order to connect to the localhost server. MetaMask needs to be able to perform RPC requests to `localhost:8545`, where Ganache is running, and the only straight-forward way to do it is by enabling the local config

2023-05-17 07:02 UTC, seaona commented
> Please review comments.

Thank you @chrisleewilcox !! Will resolve them shortly

2023-05-17 10:39 UTC, seaona commented on wdio/features/Confirmations/SendEthEOA.feature
> +  Scenario Outline: Sending ETH to an EOA from inside MetaMask wallet
thank you @chrisleewilcox  in this case  here I am using a data table - see line 37

2023-05-17 12:07 UTC, seaona commented on wdio/config/android.config.browserstack.local.js
> +  process.env.BROWSERSTACK_TAG_EXPRESSION || '@androidApp'; // pass tag to run tests specific to android
done! thank you @chrisleewilcox

2023-05-17 12:07 UTC, seaona commented on wdio/features/Confirmations/SendEthMultisig.feature
> +
done, thank you!

2023-05-17 12:07 UTC, seaona commented on wdio/features/Confirmations/SendEthMultisig.feature
> +
done, thank you!

2023-05-17 12:07 UTC, seaona commented on wdio/features/Confirmations/SendEthMultisig.feature
> +
done, thank you!

2023-05-17 12:07 UTC, seaona commented on wdio/features/Confirmations/SendEthMultisig.feature
> +
done, thank you!

2023-05-23 15:38 UTC, jpuri approved these changes

2023-05-23 15:39 UTC, seaona commented
> Please review comments.

thank you @chrisleewilcox  I've moved the necessary config to the browserstack config file :+1:

2023-05-23 15:47 UTC, chrisleewilcox approved these changes
LGTM

2023-05-23 15:58 UTC, merged