fix wallet-tests.spec.js
MetaMask/metamask-mobile pull request #6250
Opened 2023-04-22 02:28 UTC by chrisleewilcox

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
Fixed `wallet-tests.spec.js`
- refactored NFT steps
- added ERC-1155 token info to `Accounts.js`

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/6626407/233757232-864054f0-73c1-4de9-9656-9457cb3fbe01.png)

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-04-24 21:54 UTC, cortisiko requested changes
The code looks good, just one comment.

2023-04-24 21:54 UTC, cortisiko commented on wdio/helpers/Accounts.js
> +const ERC_1155_TOKEN = `0xCBBA076Cd4c35432203F71fc5CaeEBA38C25aa2C`;
I don't think having token data mixed with account data is a good idea.  you should probably create a json file that holds token data then in the test read the token data from the json.

2023-04-25 21:50 UTC, chrisleewilcox commented on wdio/helpers/Accounts.js
> +const ERC_1155_TOKEN = `0xCBBA076Cd4c35432203F71fc5CaeEBA38C25aa2C`;
Updated.  Moved collectible data to collectible.json and removed code from Accounts.js.

2023-04-25 23:25 UTC, cortisiko commented on wdio/helpers/Accounts.js
> +const ERC_1155_TOKEN = `0xCBBA076Cd4c35432203F71fc5CaeEBA38C25aa2C`;
Nice, looks good!

2023-04-25 23:26 UTC, cortisiko approved these changes
🌮 🌮 🌮

2023-04-25 23:27 UTC, cortisiko commented
update ticket description to reflect where the 1155 token data is. Once that is done, feel free to merge

2023-04-26 16:32 UTC, merged