Custom Gas Modal Component
MetaMask/metamask-mobile pull request #6287
Opened 2023-04-27 14:06 UTC by blackdevelopa

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-04-28 14:55 UTC, bschorchit commented
Hey @gauthierpetetin, did you remove the `needs-dev-review` and added a `in-progress` for this PR by mistake? We currently use the `needs-dev-review` label for internal processes in the team. cc: @hilvmason

2023-04-28 16:28 UTC, gauthierpetetin commented
Hi @bschorchit , we setup an automation yesterday to update the label of the Github issue every time the corresponding Zenhub issue is moved to a new column (more detail [here](https://github.com/MetaMask/metamask-zaps/tree/main/zaps/github-labels-automation)). In this case the ticket was moved from "needs-dev-review" to "in-progress" column.

However, I don't understand why it impacts your board, because the automation is only meant to work for the MetaMask Mobile board. I'll investigate and come back to you, sorry for that.

2023-04-28 17:38 UTC, gauthierpetetin commented
@bschorchit we've just added an additional filter to make sure the automation only applies to issues with the label "team-mobile-client". It shall not happen again on your board. In case it does, don't hesitate to reach out.

2023-05-01 08:24 UTC, jpuri commented on app/components/UI/CustomGasModal/CustomGasModal.tsx
> +  const { colors } = useAppThemeFromContext() || mockTheme;
`useAppThemeFromContext() || mockTheme` does not looks good. We should rather change `useAppThemeFromContext` to return mockTheme by default or
`const { colors = mockTheme.colors } = useAppThemeFromContext();`

2023-05-01 08:24 UTC, jpuri commented on app/components/UI/CustomGasModal/CustomGasModal.test.tsx
> +});
Above is shallow snapshot matching, is not very useful.

2023-05-01 08:24 UTC, jpuri commented on app/components/Views/SendFlow/Confirm/index.js
>      );
Great cleanup 👏

2023-05-01 08:24 UTC, jpuri commented on app/components/UI/CustomGasModal/CustomGasModal.tsx
> +  };
Above function can also be broken down into 2 functions for legacy and 1559 transactions.

2023-05-01 08:59 UTC, jpuri commented
@blackdevelopa : while testing with legacy transaction from test DAPP I found that it is showing advance options for legacy transaction:

Uploading Screen Recording 2023-05-01 at 2.28.30 PM.mov…

2023-05-03 12:39 UTC, blackdevelopa commented
@jpuri thanks for flagging this. It exists in production and a new issue should be created for it.

> @blackdevelopa : while testing with legacy transaction from test DAPP I found that it is showing advance options for legacy transaction:
> 
>  Screen.Recording.2023-05-01.at.2.28.30.PM.mov

2023-05-03 13:04 UTC, blackdevelopa commented on app/components/UI/CustomGasModal/CustomGasModal.test.tsx
> +});
Added some [here](https://github.com/MetaMask/metamask-mobile/pull/6287/commits/90da478ffa41abb258184d2b450bdd2a24e60b0d)

2023-05-03 13:55 UTC, segun commented on app/components/UI/CustomGasModal/CustomGasModal.test.tsx
> +    const wrapper = render(
Consider using `renderWithProvider` from `app/util/test/renderWithProvider.tsx`

2023-05-03 14:01 UTC, segun reviewed
Just one comment.

2023-05-03 15:09 UTC, blackdevelopa commented on app/components/UI/CustomGasModal/CustomGasModal.test.tsx
> +    const wrapper = render(
Updated. Thank you. https://github.com/MetaMask/metamask-mobile/pull/6287/commits/84c225da3f201dc770b5a03258d498b249b3087e

2023-05-03 15:48 UTC, jpuri commented on app/components/UI/CustomGasModal/CustomGasModal.tsx
> +
Nested components declaration is not good idea.

2023-05-03 15:49 UTC, jpuri requested changes
Hey, can you plz get rid of nested component declaration. PR looks good otherwise.

2023-05-05 13:22 UTC, segun submitted a review, later dismissed

2023-05-16 16:43 UTC, segun submitted a review, later dismissed

2023-05-17 00:28 UTC, jpuri commented on app/components/UI/CustomGasModal/CustomGasModal.tsx
> +  };
Above function can just be constant, its returning static values and really does not needs try/catch block.

2023-05-17 00:29 UTC, jpuri commented on app/components/UI/CustomGasModal/CustomGasModal.tsx
> +  };
Variable names `updateParent`, `stopUpdateGas` are not very intuitive.

2023-05-17 00:31 UTC, jpuri commented on app/components/UI/CustomGasModal/CustomGasModal.tsx
> +  );
is it possible that we keep `closeModal` in this component itself and not in parent ?
Null can be returned if `closeModal` is true.

2023-05-17 00:33 UTC, jpuri commented on app/components/UI/CustomGasModal/CustomGasModal.tsx
> +        )}
We can avoid passing here values which are fetched from selector. Those can be obtained in child components.

2023-05-19 11:58 UTC, blackdevelopa commented on app/components/UI/CustomGasModal/CustomGasModal.tsx
> +        )}
Yeah. Just checked again and don't think there's any value here that can be gotten from selector that is passed.

2023-05-19 11:59 UTC, blackdevelopa commented on app/components/UI/CustomGasModal/CustomGasModal.tsx
> +  };
Yeah. I updated `updateParent` to `updateParentState`. Let me know if this works. I am not sure what a better name for `stopUpdateGas` should be

2023-05-25 17:39 UTC, jpuri commented on app/components/UI/CustomGasModal/CustomGasModal.tsx
> +          closeModal: true,
@blackdevelopa : parent state params may be different for different components. How will that get handled ?

2023-05-25 17:39 UTC, jpuri commented on app/components/UI/CustomGasModal/CustomGasModal.tsx
> +
I am bit confused, below looks like callback of callback.

2023-05-25 17:40 UTC, jpuri reviewed
Changes look good, just some small questions.

2023-07-10 09:10 UTC, blackdevelopa commented on app/components/UI/CustomGasModal/CustomGasModal.tsx
> +
Done. [345c539](https://github.com/MetaMask/metamask-mobile/pull/6287/commits/345c539f781c5139988e8e40405e2e137b226071)

2023-07-10 09:10 UTC, blackdevelopa commented on app/components/UI/CustomGasModal/CustomGasModal.tsx
> +          closeModal: true,
Updated. [fd5e14d](https://github.com/MetaMask/metamask-mobile/pull/6287/commits/fd5e14dbc3fe1f289c142bad77619e5a25e39273)

2023-07-10 14:49 UTC, jpuri approved these changes, later dismissed
Changes look good 👍

2023-07-10 16:52 UTC, segun approved these changes, later dismissed

2023-07-19 08:41 UTC, seaona commented
do you think we could prioritize [this issue](https://github.com/MetaMask/metamask-mobile/issues/5760) soon? It is interfering whenever we test anything related with gas.

cc. @bschorchit @blackdevelopa

2023-07-19 10:05 UTC, seaona commented
From QA everything looks good except a small issue I am seeing with Send ETH using a Deeplink.
Basically I can see how the gas does not have a correct value, after re-calculated, making the transaction fail.
Notice: this only happens with Send ETH and not with Send ERC20 token using a deeplink.


https://github.com/MetaMask/metamask-mobile/assets/54408225/68bcf786-1e13-43c0-91a6-dd710a9bbe57



I've tried on `main` and apparently it's working fine. Do you think something from this PR might have affected that function @blackdevelopa ?

1. Select Sepolia
2. Scan this QR code
3. See how gas is set to >0.00000....1
4. Try to Send the tx
5. Tx fails with `Intrinsic gas too low` error

![image](https://github.com/MetaMask/metamask-mobile/assets/54408225/6eceba57-9a1b-4013-a205-d6d06a427d68)

2023-07-20 09:54 UTC, seaona commented
hi @blackdevelopa ! The issue above seems intermittent and probably not caused by this PR, as we have other reports related to Deeplink gas calculations. For this reason it can be investigated separately.

However I encounter another issue described below.

### Wallet breaks when changing gas priority
Whenever I am sending an ERC20 token, if I edit the gas priority the wallet breaks with the error `Cannot read property 'subst' of undefined`


https://github.com/MetaMask/metamask-mobile/assets/54408225/9f67fad5-4226-4cf3-be39-492aa1e543d8

**Steps**:
1. Import an ERC20 token
2. Click Send
3. Add any amount and recipient
4. Click next
5. Click Edit Gas
6. Change priority Gas
7. Click Save
8. Wallet breaks

2023-07-23 07:30 UTC, seaona commented
I can see the issue fixed @blackdevelopa . This looks good from QA. We need x2 re-approvals

2023-07-24 13:30 UTC, jpuri submitted a review, later dismissed

2023-07-24 13:52 UTC, cryptotavares commented on app/components/UI/CustomGasModal/CustomGasModal.test.tsx
> +const initialState = {
There is a [common background initial state](https://github.com/MetaMask/metamask-mobile/blob/main/app/util/test/initial-background-state.json) for unit tests. If possible we should use that one, as it reduces the unit tests maintenance effort.

2023-07-24 16:05 UTC, blackdevelopa commented on app/components/UI/CustomGasModal/CustomGasModal.test.tsx
> +const initialState = {
Great. Updated [here](https://github.com/MetaMask/metamask-mobile/pull/6287/commits/1217799a6b685ffbc659fd9b4f936c03563c39b4)

2023-07-24 17:11 UTC, jpuri approved these changes

2023-07-26 11:02 UTC, segun approved these changes

2023-07-26 16:47 UTC, blackdevelopa commented
Merging this PR as it is now QA passed

2023-07-26 16:48 UTC, merged