feat(action): github action to add label "release-x.y.z" when PR gets merged
MetaMask/metamask-mobile pull request #6352
Opened 2023-05-08 17:53 UTC by gauthierpetetin

**Description**

This PR introduces a new GitHub action that adds a `release-x.y.z` label to a PR and its linked issues when the PR gets merged.

*Prerequisites*

1. Create a personal access token with "repo" permissions.
- Go to the repository's settings and add the token as a secret named "PERSONAL_ACCESS_TOKEN".
- The personal access token is necessary for creating, adding, and retrieving labels in the linked issues' repositories.

2. Define the next release cut number every time a new release is created (e.g., `6.5`).
- Go to the repository's settings and add the number as a variable named "NEXT_RELEASE_CUT_NUMBER".
- The GitHub action will use this number to create a new label, such as `release-6.5`, which will be added to the PR and linked issues.
- The label helps identify which issues and PRs will be included in the next release.

*Steps to Reproduce*

1. In a first repository, create an issue.
2. In a second repository, create another issue.
3. In one of the two repositories, create a PR.
4. Link both issues to the PR.
5. Merge the PR.

*Acceptance Criteria*

Upon merging the PR, the PR and both issues should have the release-x.y.z label.
This process should work for both public and private repositories.

**Screenshots/Recordings**

https://recordit.co/aJ2gkTF8lk

**Issue**

None

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [x] Any added code is fully documented

2023-05-08 18:31 UTC, wachunei commented
Cool! I enjoyed the recording :D Is this restricted to PRs that are merged to main? Maybe we want to do that, I've seen feature branches that collect tasks:
```
main <-- PR -- feature/branch <-- PR-- feature/branch-task-1
main <-- PR -- feature/branch <-- PR-- feature/branch-task-2
```

and more often we fix bugs in a release branch:
```
release/x.y.z <-- PR -- fix/a-fix-branch
```

Maybe issues related to these edge cases would have manual labeling? What do you think?

2023-05-16 12:18 UTC, gauthierpetetin commented
Hi @wachunei ,
Thanks for the review, I just saw tour message and indeed good catch, we want it to apply only for PRs that are merged to main. I need to change it.

2023-05-17 15:54 UTC, tommasini approved these changes
LGTM! The graphql it's cool ahah

2023-05-17 15:57 UTC, tommasini requested changes
AAAH it's supposed to be just a comment I will request changes to invalidate the approve, when this is done I take a look again 🙏

2023-05-19 06:40 UTC, gauthierpetetin commented on .github/scripts/add_release_label_to_pr_and_linked_issues.ts
> +  const releaseLabelColor = "000000";
Thanks for the review and suggestion @tommasini . Why not, I wonder what people will prefer, I'll ask on [Slack](https://consensys.slack.com/archives/C047WAG4RFT/p1684478296218209).

2023-06-06 06:36 UTC, gauthierpetetin commented on .github/scripts/add_release_label_to_pr_and_linked_issues.ts
> +  const releaseLabelColor = "000000";
I'm resolving this thread after results from poll on [Slack](https://consensys.slack.com/archives/C047WAG4RFT/p1684478296218209).

2023-06-16 13:03 UTC, Gudahtt commented
I can review this PR as well once the conflicts have been addressed

2023-06-20 18:30 UTC, gauthierpetetin commented
Hi @Gudahtt , yes that would be great, I resolved conflicts.

- It shall be very close to the [Extension PR](https://github.com/MetaMask/metamask-extension/pull/19061) you already approved.
- Here, I had to add this [commit](https://github.com/MetaMask/metamask-mobile/pull/6352/commits/bfcf881fdf20c542c7149e62c83f06a5d071000d) to pass the CI.

2023-06-21 19:03 UTC, gauthierpetetin commented on .github/workflows/add-release-label.yml
> +          node-version: '16'
This is now fixed with this [commit](https://github.com/MetaMask/metamask-mobile/pull/6352/commits/38872b1613267eaf9aa07afeaff02062953e8b31).

2023-06-21 19:04 UTC, gauthierpetetin commented on .github/workflows/add-release-label.yml
> +        run: chmod +x ./scripts/get-next-semver-version.sh
This is now fixed with this [commit](https://github.com/MetaMask/metamask-mobile/pull/6352/commits/9c905e19754334cef6f69654bccee435f8471577).

2023-06-21 19:04 UTC, Gudahtt approved these changes
LGTM!

2023-06-21 19:06 UTC, gauthierpetetin commented
@Gudahtt , I see you already did the same changes on Extension side, thanks!

2023-06-21 22:34 UTC, NicolasMassart reviewed
LGTM only if we also create an issue reminding us to extract all this process to a standalone action once we will have validated that it works fine. Right now, it overloads the app repo with deployment CI that will require devs to load unnecessary dev dependencies when they should be handled at the action level. That's what GH actions are for.

2023-06-22 02:39 UTC, sethkfman commented
@SocketSecurity ignore-all

All packages are dev dependencies and do not impact production code

2023-06-22 02:40 UTC, sethkfman approved these changes
LGTM

2023-06-22 02:41 UTC, sethkfman commented
@gauthierpetetin PR looks good. If @tommasini doesn't complete his review we can move it forward tomorrow.

2023-06-22 10:10 UTC, gauthierpetetin commented
Thank you all for the reviews!

@NicolasMassart, good point, I created this [issue](https://github.com/MetaMask/mobile-planning/issues/1057) in our backlog.

2023-06-22 10:52 UTC, tommasini approved these changes
LGTM! Awesome!!

2023-06-22 15:11 UTC, Gudahtt commented
`RELEASE_LABEL_TOKEN` has been added as a repository secret

2023-06-22 16:16 UTC, merged