Fix bug domain not shown on signature
MetaMask/metamask-mobile pull request #6464
Opened 2023-05-25 11:55 UTC by segun

**Description**

This PR fixes a bug where domain URL is not displayed on any signature type.

**Screenshots/Recordings**

**Before**

![](https://user-images.githubusercontent.com/54408225/239191041-0c0ccd72-1ae2-4c4a-9f0c-967a87a7173b.png)

**After**

**Issue**

Fixes: #6429 

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-05-30 14:50 UTC, blackdevelopa submitted a review, later dismissed

2023-06-02 18:30 UTC, digiwand commented on app/components/hooks/useAddressBalance/useAddressBalance.ts
> +      setBalance();
maybe
```suggestion
    if (
      // if asset is undefined, we are fetching the balance of the selected account
      !asset ||
      asset.isETH ||
      asset.tokenId ||
      asset.standard === ERC721 ||
      asset.standard === ERC1155
    ) {
      setBalance();
```
```suggestion
    if (!asset) {
      // if asset is undefined, we are fetching the balance of the selected account
      setBalance();
    } else if (
      asset.isETH ||
      asset.tokenId ||
      asset.standard === ERC721 ||
      asset.standard === ERC1155
    ) {
      setBalance();
```

2023-06-03 00:07 UTC, jpuri submitted a review, later dismissed
Changes look good, @digiwand has made some useful suggestion hrere.

2023-06-06 16:23 UTC, jpuri approved these changes
LGTM except for a small feedback.

2023-06-06 16:23 UTC, jpuri approved these changes
LGTM except for a small feedback.

2023-06-06 17:15 UTC, chrisleewilcox requested changes, later dismissed
@seaona @digiwand @jpuri when a PR is QA Passed then adding a review afterwards puts the PR at risk.  Not sure the reviews were worth it after being QA Passed but I would like this to go through QA again and would advise QA to merge the PR after QA Passed to avoid further changes after it's been QA Passed.

2023-06-06 17:22 UTC, seaona commented
hi @chrisleewilcox correct if there were changes in the PR this resets the x2 reviews as well as the QA approval

2023-06-07 14:23 UTC, digiwand approved these changes

2023-06-07 14:33 UTC, seaona commented
@segun can we resolve the open conversations so PR can be merged?

2023-06-07 15:20 UTC, segun commented on app/components/hooks/useAddressBalance/useAddressBalance.ts
>      } else if (asset?.decimals !== undefined) {
it was used in 2 places earlier, but we merged the 2 if conditions.

2023-06-07 15:21 UTC, merged