Update banner component to show/hide details section
MetaMask/metamask-mobile pull request #6494
Opened 2023-05-30 14:11 UTC by segun

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-05-31 12:55 UTC, blackdevelopa commented on app/component-library/components/Banners/Banner/foundation/BannerBase/BannerBase.tsx
> +          label={isExpanded ? 'Hide details' : 'Show details'}
Can we add `Hide details` to en.json?

2023-05-31 13:04 UTC, holantonela commented
Looks great! we are missing the attribution line:
`[icon] Security advice by Blockaid`

Ref
![image](https://github.com/MetaMask/metamask-mobile/assets/87079938/0d7ec57a-94f0-44ce-ac85-b44ccc47cf29)

Figma
https://www.figma.com/file/Q69vHaA7Or7Rxz4vdzjVHC/Support-for-tx-security-providers-(MVP)?type=design&node-id=5485-37009&t=9XdtRhrk5v6t7Gw7-4

2023-05-31 14:31 UTC, jpuri commented
Changes look good, will be nice to have test coverage also.

2023-05-31 15:35 UTC, georgewrmarshall requested changes
Hey @segun, would it be possible to work with @brianacnguyen to make this component a bit more flexible by adding a `children` prop similar to the extension https://github.com/MetaMask/metamask-extension/blob/develop/ui/components/component-library/banner-base/banner-base.js#L56-L60

2023-05-31 15:35 UTC, georgewrmarshall commented on app/component-library/components/Banners/Banner/foundation/BannerBase/BannerBase.types.ts
> +  details?: string | React.ReactNode;
Instead of adding these props I think it would make the component more flexible if we added a `children` prop. Then anything can be added to the banner, if we continue to keep adding props for specific functions or features we will end up with an [apropcalypse](https://twitter.com/gurlcode/status/1002110517094371328?lang=en)

2023-05-31 18:14 UTC, brianacnguyen commented
This isn't vested by the DS team yet. For future reference, please try not to add additional props to DS Components without communicating with the DS team first. Thanks

2023-05-31 22:19 UTC, brianacnguyen commented
After discussing with the team, the `Banner` component should be updated as such
1/ a `children` prop will be added to BannerBase, this `children` prop will accept `React.ReactNode` as a type and it will go below the `actionButton`
2/ For the specific case of show/hide details, feature developers will need to use `Banner` with the alert variant and the children populated with the details `Accordion`

Please let me know if you want to assign me to make the changes for #1, or please reach out to me if you have any other questions.

2023-06-02 17:50 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/foundation/BannerBase/BannerBase.types.ts
> -  title?: string | React.ReactNode;
keep this

2023-06-02 17:50 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/foundation/BannerBase/BannerBase.types.ts
> +  children?: React.ReactNode;
Add comment describing the prop. Also please update the `md` file with this new prop

2023-06-02 17:50 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/foundation/BannerBase/BannerBase.tsx
> -        {renderTitle()}
keep this

2023-06-02 17:50 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/foundation/BannerBase/BannerBase.tsx
> -  const renderDescription = () =>
keep this

2023-06-02 17:50 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/foundation/BannerBase/BannerBase.tsx
> -  DEFAULT_BANNERBASE_DESCRIPTION_TEXTVARIANT,
keep this

2023-06-02 17:50 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/foundation/BannerBase/BannerBase.tsx
> -  DEFAULT_BANNERBASE_TITLE_TEXTVARIANT,
keep this

2023-06-02 17:50 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/foundation/BannerBase/BannerBase.styles.ts
> +    infoButton: {
remove

2023-06-02 17:50 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/foundation/BannerBase/BannerBase.constants.tsx
> -  title: SAMPLE_BANNERBASE_TITLE,
keep this

2023-06-02 17:50 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/foundation/BannerBase/BannerBase.constants.tsx
> -  description: SAMPLE_BANNERBASE_DESCRIPTION,
keep this

2023-06-02 17:50 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/Banner.types.ts
> +  | BlockaidBannerProps
remove

2023-06-02 17:50 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/Banner.types.ts
> +import { BlockaidBannerProps } from './BlockaidBanner.types';
remove

2023-06-02 17:54 UTC, brianacnguyen requested changes
Please keep the title and description as is, and just add children under the action button. Also please remove the BlockaidBanner from the design system since it does not belong in the design system. Let me know if we need to jump on a call.

2023-06-06 00:44 UTC, brianacnguyen approved these changes, later dismissed
LGTM

2023-06-06 00:44 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/Banner.test.tsx
> +describe('SendFlowAddressFrom', () => {
Banner*

2023-06-07 16:40 UTC, georgewrmarshall reviewed
Hey @segun, Excellent work on the prop type descriptions. Should there be a story for the `children` prop in storybook? I've also added some comments about testing but I'll defer to @brianacnguyen as I am not as familiar with the mobile code base. My review is non-blocking

2023-06-07 16:40 UTC, georgewrmarshall commented on app/component-library/components/Banners/Banner/Banner.test.tsx
> +    expect(wrapper).toMatchSnapshot();
I'm not familiar with mobile unit tests so forgive me if this is the convention but this test seems a little flaky to me? One could just update the snapshot if it fails when `startAccessory` doesn't render? Shouldn't we add a test id to the component we are passing to the `startAccessory` and check if it exists?

2023-06-07 16:40 UTC, georgewrmarshall commented on app/component-library/components/Banners/Banner/Banner.test.tsx
> +    expect(wrapper).toMatchSnapshot();
Same here? Is a snapshot a reliable way to check if the action button exists?

2023-06-07 16:54 UTC, brianacnguyen commented
> Hey @segun, Excellent work on the prop type descriptions. Should there be a story for the `children` prop in storybook? I've also added some comments about testing but I'll defer to @brianacnguyen as I am not as familiar with the mobile code base. My review is non-blocking

No there doesnt need to be a story for the `children` prop

2023-06-07 16:55 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/Banner.test.tsx
> +    expect(wrapper).toMatchSnapshot();
there's always a separate snapshot test. but regardless, yes there should be a check for the startAccessory

2023-06-07 16:57 UTC, brianacnguyen requested changes
Please update tests per @georgewrmarshall 's comment

2023-06-08 20:20 UTC, georgewrmarshall approved these changes, later dismissed
LGTM. Please don't merge until @brianacnguyen has approved

2023-06-14 14:16 UTC, blackdevelopa commented on app/component-library/components/Banners/Banner/foundation/BannerBase/BannerBase.tsx
> +            data-testid="banner-close-button"
I can't seem to find this prop in `ButtonIcon`. Is this omitted somewhere?

2023-06-14 14:20 UTC, blackdevelopa reviewed
LGTM. Left a comment

2023-06-14 15:23 UTC, blackdevelopa commented on app/component-library/components/Banners/Banner/foundation/BannerBase/BannerBase.tsx
> +            data-testid="banner-close-button"
TY.

2023-06-14 15:25 UTC, blackdevelopa submitted a review, later dismissed

2023-06-15 00:06 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/Banner.test.tsx
> +    expect(await wrapper.queryByTestId('banner-close-button')).toBeDefined();
where'd you get this test id?

2023-06-15 09:16 UTC, segun commented on app/component-library/components/Banners/Banner/Banner.test.tsx
> +    expect(await wrapper.queryByTestId('banner-close-button')).toBeDefined();
I added the test id to the close button in this PR.
The close button is just an icon, so can't be checked for existence by text.

2023-06-15 19:08 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/foundation/BannerBase/BannerBase.tsx
> +            data-testid="banner-close-button"
update to testID and extract out the string to const

2023-06-15 19:08 UTC, brianacnguyen commented on app/component-library/components/Banners/Banner/Banner.test.tsx
> +    expect(await wrapper.queryByTestId('banner-close-button')).toBeDefined();
Use const

2023-06-16 08:57 UTC, blackdevelopa approved these changes

2023-06-16 09:46 UTC, jpuri approved these changes

2023-06-16 22:04 UTC, brianacnguyen approved these changes

2023-06-19 10:53 UTC, merged