test: Send ETH with Gas API Down - Introducing Mock Responses
MetaMask/metamask-mobile pull request #6511
Opened 2023-06-01 11:28 UTC by seaona

## Description
This PR adds a testcase for Sending ETH when the Gas API is down. We will validate that the correct gas fallback is displayed.
For achieving this, we introduce the ability to Mock responses on the background, using `mockttp` library.

## Screenshots/Recordings

https://github.com/MetaMask/metamask-mobile/assets/54408225/e9d8a9cc-83fe-43c6-9d0b-3cbf07f7066c

![Screenshot from 2023-06-01 13-21-41](https://github.com/MetaMask/metamask-mobile/assets/54408225/a7cc0d06-caf5-4644-9740-c743372401b7)

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-06-01 11:39 UTC, seaona commented on wdio/step-definitions/common-steps.js
> -Given(/^Ganache server is started$/, async () => {
For some reason this section was added back in another PR - this was moved to the `ganache-steps` file, so it should be removed from here

2023-06-01 11:42 UTC, seaona commented on wdio/step-definitions/mock-steps.js
> +Given(/^Mock server is started with mock Gas API Down$/, async () => {
Here we mock the API response to return a 500, so we then check that we display the Fallback Gas API screen

2023-06-01 13:50 UTC, chrisleewilcox requested changes

2023-06-01 13:50 UTC, chrisleewilcox commented on wdio/features/Confirmations/SendETHGasApiDown.feature
> +      | 0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6 | 1      |
I feel like this can be better understood by breaking this scenario down into more scenarios....

Scenario: Setup Genache Server
Scenario Outline: Enter Send Amount
Scenario: Edit Gas Fees
Scenario: Send Transaction

Can we break it down like that?  No changes in steps just grouping them in scenarios that make the tests and steps more understood.  This will also make it easier to expand and add to this test for each scenarios such as negative test for inputing invalid values for send amount and other things.
@seaona

2023-06-02 10:57 UTC, seaona commented on wdio/features/Confirmations/SendETHGasApiDown.feature
> +      | 0x1FDb169Ef12954F20A15852980e1F0C122BfC1D6 | 1      |
Thank you @chrisleewilcox I've updated the test breaking it down in more Scenarios

2023-06-02 12:49 UTC, chrisleewilcox submitted a review, later dismissed

2023-06-02 13:24 UTC, blackdevelopa approved these changes, later dismissed

2023-06-05 09:32 UTC, naugtur commented
@SocketSecurity ignore-all

Checked the ones where a maintainer changed, but these are very old releases with decent download counts, nothing to worry about.
FS and Net access for dependencies of a http mocking tool makes sense :) 
Some of the stuff is a bit dated, but fine for a dev dependency.

2023-06-05 14:35 UTC, segun submitted a review, later dismissed

2023-06-05 15:34 UTC, NiranjanaBinoy submitted a review, later dismissed

2023-06-05 18:36 UTC, SamuelSalas approved these changes, later dismissed

2023-06-05 19:01 UTC, chrisleewilcox submitted a review, later dismissed

2023-06-07 11:54 UTC, seaona commented on wdio/features/Confirmations/SendEthGasApiDown.feature
> +  Scenario: Display fallback on the Gas Edit screen
Each test must be under the same scenario as we use hooks for starting/stopping the needed servers and pass them on the World object (which is reset on each scenario)

2023-06-07 14:04 UTC, segun approved these changes

2023-06-07 15:27 UTC, NiranjanaBinoy approved these changes

2023-06-07 15:33 UTC, merged