Fixture POC
MetaMask/metamask-mobile pull request #6519
Opened 2023-06-02 09:23 UTC by vinistevam

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

The aim of this PR is to have a stable POC to include the possibility to use fixtures in e2e tests on Appium and Detox (ios/android).

```
# Run on Appium

yarn watch
# On another terminal
yarn start:android:qa 
# Once the build finishes
yarn test:wdio:android --spec ./wdio/features/Onboarding/SkipOnboarding.feature 

## Run on Detox (Not tested)
yarn watch
# On another terminal
yarn test:e2e:ios:debug
# Once the build finishes
yarn test:e2e:ios:debug:single e2e/specs/skip-onboarding.spec.js
```

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-06-08 22:27 UTC, matthewwalsh0 commented on app/components/Nav/App/index.js
> +      const existingUser = await asyncStorageWrapper.getItem(EXISTING_USER);
Rather than replacing every import, could we instead update the library directly by assigning functions, or using a third party library, or even just patching it?

2023-06-08 22:44 UTC, matthewwalsh0 commented on app/components/Views/Root/index.js
> +      await new Promise((resolve) => {
Is it worth encapsulating this in a private `waitForStore` method?

2023-06-08 22:46 UTC, matthewwalsh0 commented on app/images/static-logos.js
> +  'ftn.svg': require('metamask/node_modules/@metamask/contract-metadata/images/ftn.svg'),
Bad merge?

2023-06-08 22:48 UTC, matthewwalsh0 commented on app/store/async-storage-wrapper.js
> +const isTest = process.env.IS_TEST === 'true';
Is it worth putting this in a method somewhere as we do it in multiple places?

2023-06-08 22:53 UTC, matthewwalsh0 commented on app/store/index.js
> +const ReadOnlyNetworkStorage = {
Did we need this in the end? If I understand right, we are overriding three different flows by updating:

- The initial state of the root store.
- The references to `AsyncStorage`.
- The `storage` property in the `persistConfig`.

Are all of these in use and unrelated to each other? Do we have a ballpark figure of which is most prevalent?

2023-06-08 22:58 UTC, matthewwalsh0 commented on app/store/index.js
> +if (isTest) {
Would it be cleaner to put this logic inside a method that we call inline?

The `else` condition is almost identical also so we could remove some duplication.

2023-06-08 23:00 UTC, matthewwalsh0 commented on app/util/test/network-store.js
> +import axios from 'axios';
Is it worth commenting that this is identical to what is in the extension?

We could eventually move it to core to avoid the duplication.

2023-06-08 23:03 UTC, matthewwalsh0 commented on wdio/fixtures/fixture-server.js
Would we want both this server and the builder to exist above the Android tests specifically?

Am I right this has been tested on Android but not yet Detox?

2023-06-08 23:08 UTC, matthewwalsh0 commented on app/store/index.js
> +const ReadOnlyNetworkStorage = {
As discussed, in an ideal world, we'd have a single asynchronous intersection point where all flows ultimately read state from, that we could then override or configure to inject our own logic which would use the state from the server.

In the extension for example, all state ultimately comes from the local store initialised in the background script.

If this doesn't exist in mobile, it'd likely be worth the investment to align any existing flows to use a single mechanism.

2023-06-20 13:42 UTC, vinistevam commented on app/images/static-logos.js
> +  'ftn.svg': require('metamask/node_modules/@metamask/contract-metadata/images/ftn.svg'),
removed, my bad.

2023-06-20 13:47 UTC, vinistevam commented on app/store/index.js
> +const ReadOnlyNetworkStorage = {
After changing the approach to only overwrite the `state.getState()` I run some tests using the original `MigratedStorage` with fixtures and they all passed. I removed `ReadOnlyNetworkStorage` which will simplify the changes to create the persistor and store.

2023-06-20 13:48 UTC, vinistevam commented on app/util/test/network-store.js
> +import axios from 'axios';
It's not 100% identical, but 100% compatible I just had to include some extra functions to cover the Async Storage.

2023-06-26 15:28 UTC, leotm reviewed
thanks again for walking thru this today ^ just a reminder that could be worth adding notes on this to our ReadMe.md (for internal/external contributors)

2023-06-27 07:03 UTC, seaona commented on wdio/config/android.config.debug.js
> +    deviceName: 'Pixel 3 API 33',
I think we can leave this as it was previously, as it depends on each setup

2023-06-27 07:07 UTC, seaona commented on wdio/features/Onboarding/SkipOnboarding.feature
> +    Given State is loaded with fixtures to skip onboarding steps
I am wondering if instead of using fixtures as a "step" in the feature file, we could trigger them on the `hooks` level, like we do with Ganache server, deployment of smarts contracts, mocks, etc. and then use the cucumber tag in the feature file, for indicating that the test uses that particular fixture.

See ganache, mocks, etc implemented in the `hooks` : https://github.com/MetaMask/metamask-mobile/blob/main/wdio.conf.js#L316

See how this is then triggered on a particular test, by using the `tags`: i.e. in this case `@ganache` starts and tears down ganache server, and `@erc721` deploys an NFT conctract, before the test begins.

https://github.com/MetaMask/metamask-mobile/blob/main/wdio/features/Confirmations/SendERC721.feature#L8

2023-07-05 07:22 UTC, vinistevam commented on wdio/features/Onboarding/SkipOnboarding.feature
> +    Given State is loaded with fixtures to skip onboarding steps
That is a great suggestion, thanks :1st_place_medal: ! I pushed the changes to introduce the tag to support loading the state before any step of the scenario.  [here](https://github.com/MetaMask/metamask-mobile/pull/6519/files#diff-f297ad33212595210fbfc7c32d334f7025fe8eee14cc4179d2527c3f4543035fR347)

2023-07-14 08:05 UTC, vinistevam commented
@SocketSecurity ignore koa@2.14.2

2023-07-17 22:20 UTC, cryptotavares commented on app/store/index.js
> +  if (state) store.getState = () => state;
Why can't we just pass the fixture state as preloaded state when creating the redux store? Something like:
```js
  const state = isTest ? await ReadOnlyNetworkStore.getState() : undefined;
  store = createStore(pReducer, state, applyMiddleware(thunk));
```

2023-07-17 22:43 UTC, cryptotavares commented on e2e/init.js
> +  await loadFixture();
Should we load the fixtures in a global before hook? or should we follow the extension approach of starting the server, loading the fixtures and then tearingdown the server per test? (in this way allowing tests to setup their own fixtures)

2023-07-17 22:46 UTC, cryptotavares commented on e2e/init.js
> +    await device.reverseTcpPort(12345);
I know that it is not in this PR scope, but should we add the reverse port for ganache as well? (just as we have for appium)

2023-07-17 22:47 UTC, cryptotavares commented on wdio/fixtures/fixture-builder.js
> +/**
Maybe we could move this files into the e2e directory (where all the detox files are).. as we intend to migrate everyting into detox

2023-07-20 08:03 UTC, vinistevam commented
@SocketSecurity ignore koa@2.14.2

2023-07-21 15:10 UTC, vinistevam commented on e2e/init.js
> +  await loadFixture();
I migrate one of the existing jest tests to use fixtures through the `withFixtures` function. Unfortunately, it's still necessary to load a general fixture because once the flag `IS_TEST` is `true` all the tests are using the fixtures' infrastructure and need it to provide an empty initial state to be backwards compatible with the existent tests.

2023-07-21 15:17 UTC, vinistevam commented on app/store/index.js
> +  if (state) store.getState = () => state;
Depending on the fixtures it takes a long time to create a store with an initial state and then override the `getState` after creating the store. All my attempts to workaround that ended up with the [initializeEngine](https://github.com/MetaMask/metamask-mobile/blob/5a8723529f81b243b414b76abc061f7112a9dcc6/app/core/EngineService/EngineService.ts#L27)  setting an empty state to the controllers.

2023-07-26 17:10 UTC, cryptotavares commented on e2e/init.js
> +  await loadFixture();
Ok it makes sense.. I am just wondering then if we shouldn't reset the state before each test execution? (the idea is to make tests atomic.. no app state leakeage between tests).. Although I am not sure on the impact that that might have on already existing tests.
Let's keep it as is and create a subsequent task to look into it.

2023-07-26 17:12 UTC, cryptotavares commented on e2e/fixtures/fixture-builder.js
> +      ? this.withOnboardingFixture()
The naming seems confusing to me... `withOnboardingFixture` seems to suggest that onboarding will be fixture, and thus the e2e test will bypass it. But, again, the same is true for the extension fixtures code base... So, for consistency reasons let's keep it like this

2023-07-26 17:14 UTC, cryptotavares commented on e2e/fixtures/fixture-helper.js
> +    if (restartDevice) {
Can we add a small explanation or comment to when one would expect to pass the `restartDevice=true`? In which cases do we want to set it to true on e2e tests?

2023-07-27 08:59 UTC, vinistevam commented on e2e/fixtures/fixture-helper.js
> +    if (restartDevice) {
Sure I will include a comment here.
Currently, this is required because the app is launched on `init.js` at the beginning of the process, so once in the test file we load the fixtures a restart of the app is necessary. Ideally, as progressively we start to use fixtures we move the `await device.launchApp();` to the file and use `beforeAll` or `beforeEach` hooks to load the fixtures and launch the app or not using the hooks and rely on `withFixtures` function, depending on the use case.

2023-07-27 09:07 UTC, Andepande submitted a review, later dismissed
LGTM some great work, looking forward to using it

2023-07-27 09:19 UTC, Andepande submitted a review, later dismissed

2023-07-27 22:32 UTC, cortisiko requested changes

2023-07-27 22:32 UTC, cortisiko commented on e2e/viewHelper.js
> +  await LoginView.enterPassword(PASSWORD);
You can import the password from the validAccount object. 

```suggestion
  await LoginView.enterPassword(validAccount.password);
```

2023-07-27 22:32 UTC, cortisiko commented on app/components/Views/RevealPrivateCredential/RevealPrivateCredential.tsx
> +import AsyncStorage from '../../../store/async-storage-wrapper';
Whenever we intend to use fixtures in our tests, is it necessary to include 

`import AsyncStorage from '../../../store/async-storage-wrapper';`

 in all areas of the app code that the test interacts with?

2023-07-27 22:32 UTC, cortisiko commented on package.json
> +    "build:ios:pre-qa": "IS_TEST='true' ./scripts/build.sh ios QA --pre",
any reason why we add this flag to the pre-qa build for both iOS and android?

2023-07-27 22:32 UTC, cortisiko commented on e2e/init.js
>  beforeAll(async () => {
We won't use fixtures for all tests. Instead, we'll enable fixtures at the test level, allowing us to use them selectively. Some tests will remain unchanged, while for others, such as the confirmation tests, we'll utilize fixtures.

2023-07-31 11:13 UTC, vinistevam commented on e2e/fixtures/fixture-builder.js
> +      ? this.withOnboardingFixture()
I was thinking of an option `withoutFixtures` / `noFixtures` but as you mentioned I left it like this for consistency at least for the infrastructure PR.

2023-07-31 11:14 UTC, vinistevam commented on package.json
> +    "build:android:pre-release:bundle:qa": "IS_TEST='true' GENERATE_BUNDLE=true ./scripts/build.sh android QA --pre",
Included in the `.js.env.example`.

2023-07-31 11:22 UTC, vinistevam commented on e2e/specs/delete-wallet.spec.js
> +      await withFixtures({ fixture, restartDevice: true }, async () => {
Yes, because the app is started at `init.js` using the `beforeAll` hook so every time we want to provide fixture to support our test the app needs to reload in order to obtain the new fixture provided specifically to support the test.
One way to avoid it is to start the app using `beforeAll` hook in the test file or using `withFixtures` function with the option `restartDevice` set to `true`. It starts the app if the app is not running.

2023-07-31 11:28 UTC, vinistevam commented on e2e/viewHelper.js
> +  await LoginView.enterPassword(PASSWORD);
I was trying to avoid disruption here because the password on the fixtures account is different from the one in `Accounts.js`.  One thing to use `validAccount.password` for this case again is if I change the password in the fixtures `KeyringController` to match the one in `validAccount.password`.

2023-07-31 11:34 UTC, vinistevam commented on app/components/Views/RevealPrivateCredential/RevealPrivateCredential.tsx
> +import AsyncStorage from '../../../store/async-storage-wrapper';
No, It acts as a wrapper around the AsyncStorage module from the `@react-native-async-storage/async-storage` package. The purpose of this class is to provide a unified interface for storing, retrieving, and removing data using the AsyncStorage module. 

Using the wrapper I can provide the fixtures to async storage in a central place.

2023-07-31 11:38 UTC, vinistevam commented on package.json
> +    "build:ios:pre-qa": "IS_TEST='true' ./scripts/build.sh ios QA --pre",
Sorry for my confusing here. I changed it to `test:e2e:ios:debug` and `test:e2e:android:bitrise:debug`.
I'm not sure if I also should include `IS_TEST='true'` to  `test:e2e:android:debug`. 
The goal here is no need to add environment variables through the Bitrise UI.

2023-07-31 11:46 UTC, vinistevam commented on e2e/init.js
>  beforeAll(async () => {
To clarify here it's just loading an "empty fixture" as the infrastructure of the fixtures relies on the env `IS_TEST` once it's `true` it will try to load the fixtures and by providing this "empty fixture" which to simplify is the same as it was before going through all the onboarding process.

I thought the fixtures were meant to be used on almost all tests, in the example I've created using the fixtures to skip the onboarding process it can be applied to all the tests besides the flows to test specifically the onboarding flows.

2023-07-31 22:05 UTC, cortisiko requested changes

2023-08-01 22:52 UTC, cortisiko approved these changes, later dismissed
PR looks good!

2023-08-15 23:43 UTC, cortisiko approved these changes

2023-08-16 08:35 UTC, matthewwalsh0 approved these changes

2023-08-16 08:41 UTC, vinistevam commented
@SocketSecurity ignore-all

2023-08-16 10:46 UTC, OGPoyraz approved these changes

2023-08-16 11:05 UTC, Andepande approved these changes
LGTM

2023-08-16 11:20 UTC, merged