[Fix] Invalid password error
MetaMask/metamask-mobile pull request #6584
Opened 2023-06-09 19:22 UTC by owencraston

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses https://github.com/MetaMask/mobile-planning/issues/975

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-06-14 19:08 UTC, Andepande requested changes
Issue 1 [Android Specific]
Details
- When user imports from SRP, and updates from build 1127 to 1129, user enters valid password, an 'Invalid Password' validation error occurs on login page 

Steps to Reproduce:

1. Install Apk build 1127 v7.1.0
2. Import account using SRP
3. Navigate to main wallet view and kill app
4. Install Apk build 1129 v7.0.2
5. Open app and type in password

Outcome 

- Invalid Password validation error occurs 

Device: Android 13 Pixel 6,
see here for android, skip to minute 2, error occurs at 2:48 https://recordit.co/m8gfHFhbDz

Issue 2 [IOS specific]
- Vault corruption flow is stuck in a loop. When the user kills and relaunches the app, user is taken through the vault recovery flow again repeatedly.
Device:  IOS 16 iPhone SE

Steps to reproduce:
1. Install v7.1.0 (1127) on IOS device using TestFlight
2. Create wallet and navigate to main wallet view
3. Kill app, and update to v7.0.2 (1129) using TestFlight
4. Relaunch app, input password on login page
5. Go through the vault recovery and navigate to main wallet view 
6. Kill app, then relaunch app

Outcome:
- Vault Recovery Process repeats again

There are two recordings, the first [recording](https://recordit.co/oXAFX5rvrc) which goes through the upgrading from v7.1.0 (1127) to v7.0.2 (1129).
The second [recording](https://recordit.co/Wa5qn3omSL) is a continuation (Recording stopped accidentally), this illustrates the Vault recovery loop when the app is killed on IOS


**Clarification on expected behavior:**
1. After a user who imported their wallet goes through the vault recovery flow, should the protect your wallet modal appear when a user already imported their wallet via SRP?
see recording: http://recordit.co/Mz2zObw2gO
The protect your wallet modal does not appear when a user goes through the vault recovery flow after a new wallet was created: http://recordit.co/DH9cDN0kgE

2. When upgrading the app between versions, the vault recovery flow is triggered. Is this now expected behavior? This seems a bit counterintuitive because we are now prompting all users to recover their wallet once they upgrade between app versions.

2023-06-15 18:00 UTC, sethkfman commented
> When upgrading the app between versions, the vault recovery flow is triggered. Is this now expected behavior? This seems a bit counterintuitive because we are now prompting all users to recover their wallet once they upgrade between app versions.

This is not expected behavior and would be part of the blocking issue. @Andepande @owencraston

2023-06-16 20:56 UTC, sethkfman commented
This probably should go into the next release but is not the root cause of the password issue. @owencraston

2023-07-20 11:32 UTC, owencraston commented on app/components/Views/Login/index.js
> +      throw new Error(VAULT_ERROR);
this is only for manually triggering a vault corruption error so we can go through the recovery flow.

2023-08-29 19:48 UTC, closed without merging