Blockaid banners implementation
MetaMask/metamask-mobile pull request #6585
Opened 2023-06-12 10:05 UTC by segun

**Description**
Implementing the Blockaid Banner and making it configurable, such that we only pass in the attackType and attackDetails as props.

This will allow us to be able to show BlockAid PPOM error/warning messages. 

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-06-23 11:46 UTC, jpuri commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +import FontAwesome5Icon from 'react-native-vector-icons/FontAwesome5';
Ordered imports looks better.

2023-06-23 11:48 UTC, jpuri commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +  };
Above can be extracted into a separate component, that will be better than having a fn like this.

2023-06-23 11:48 UTC, jpuri commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +  }
Above can be extracted into a separate function.

2023-06-23 11:50 UTC, jpuri reviewed
PR looks good, but I added small possible improvements.

2023-07-19 15:35 UTC, jpuri commented on app/components/UI/BlockaidBanner/AttributionLink.tsx
> +import Text from '../../../component-library/components/Texts/Text/Text';
Nit: sort imports

2023-07-19 15:37 UTC, jpuri commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +  }
Instead of switch
```
 description = strings(`attackType_${description}`);
```

2023-07-20 13:58 UTC, blackdevelopa approved these changes, later dismissed
changes look good. Left a couple small nit

2023-07-20 16:18 UTC, blackdevelopa commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +        title={strings('see_details')}
I think this should be `strings('blockaid_banner.see_details')}`

2023-07-20 16:19 UTC, blackdevelopa commented on app/components/UI/BlockaidBanner/__snapshots__/BlockaidBanner.test.tsx.snap
> +        [missing "en.see_details" translation]
I think that should fix this as well

2023-07-20 16:25 UTC, segun commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +        title={strings('see_details')}
oh yes,

2023-07-20 17:01 UTC, blackdevelopa submitted a review, later dismissed

2023-07-20 17:06 UTC, jpuri submitted a review, later dismissed

2023-07-25 07:25 UTC, jpuri commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +    <BannerAlert
`if (flagType === 'benign') return null` can come after line 47.

2023-07-25 07:26 UTC, jpuri submitted a review, later dismissed
Changes look good, just some small feedbacks.

2023-07-25 13:52 UTC, blackdevelopa approved these changes, later dismissed

2023-07-25 20:29 UTC, digiwand reviewed
looking good! minor suggestions

2023-07-25 20:29 UTC, digiwand commented on app/components/UI/BlockaidBanner/BlockaidBanner.test.tsx
> +    expect(wrapper).toMatchSnapshot();
I think we can remove this line since we check the snapshot above with the same setup

```suggestion
```

2023-07-26 14:27 UTC, blackdevelopa submitted a review, later dismissed

2023-07-26 14:56 UTC, digiwand commented on locales/languages/en.json
> +  },
[nit] i think it would be nice to alphabetize these as well

2023-07-27 07:53 UTC, digiwand approved these changes

2023-07-27 07:58 UTC, digiwand requested changes
Style requests

2023-07-27 07:58 UTC, digiwand commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +  });
Style requests:

1. Is it possible to add more padding between the content to match the figma designs? 
2. The icon is aligned to the middle. We are aligning this to the top in the extension. Can we update this?
3. There appears to be additional pixels for the left border. I'm not sure if this was added on purpose
4. Looks like there's an extra space between "Security advice by" and "Blockaid"

2023-07-27 08:03 UTC, digiwand commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +            name={IconName.Security}
```suggestion
            name={IconName.SecurityTick}
```

Does `SecurityTick` work here? `Security` icon is missing the tick

2023-07-28 13:41 UTC, digiwand commented on app/component-library/components/Accordions/Accordion/foundation/AccordionHeader/AccordionHeader.tsx
> +import { DEFAULT_ACCORDION_EXPANDDURATION } from '../../Accordion.constants';
why `DEFAULT_ACCORDION_EXPANDDURATION` and not `DEFAULT_ACCORDION_EXPAND_DURATION`?

2023-07-28 13:45 UTC, digiwand commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +            style={styles.shieldIcon}
[nit] rather than creating synonyms, i think it is better practice to try to preserve naming. "shield icon" appears to be synonymous to "security tick icon"

2023-07-28 13:47 UTC, digiwand commented on locales/languages/en.json
> +    "attribution_link_name": "BlockAid",
```suggestion
    "attribution_link_name": "Blockaid",
```

2023-07-28 13:49 UTC, digiwand requested changes
re: https://github.com/MetaMask/metamask-mobile/pull/6585/files#r1275878904

thanks for updating the padding in between the content. ~As discussed through DM, the icon location add outer padding, and the border is inherited from BannerAlert which can be out of scope of this PR. We should create a follow-up task to update the BannerAlert DS styles~ edit: updated styles are looking good!

blocking because we need to change "BlockAid" → "Blockaid"

2023-07-28 14:02 UTC, segun commented on app/component-library/components/Accordions/Accordion/foundation/AccordionHeader/AccordionHeader.tsx
> +import { DEFAULT_ACCORDION_EXPANDDURATION } from '../../Accordion.constants';
hummmn, any changes to the core component, I was told we have to defer to the DS team. So maybe open a PR for them.

2023-07-28 14:05 UTC, segun commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +            style={styles.shieldIcon}
oh yeah, I've always known it to be shield, took me a while to find it's called SecurityTick. thanks. ;)

2023-07-28 15:50 UTC, brianacnguyen commented on app/component-library/components/Accordions/Accordion/foundation/AccordionHeader/AccordionHeader.tsx
> +import { DEFAULT_ACCORDION_EXPANDDURATION } from '../../Accordion.constants';
`DEFAULT_ACCORDION_EXPAND_DURATION` should be correct. will update this

2023-07-28 16:45 UTC, brianacnguyen requested changes, later dismissed

2023-07-28 18:37 UTC, digiwand commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +  });
oops, sorry my last review comment is outdated. This lgtm! I wonder if we should add padding between the content at the BannerAlert level

2023-07-28 22:33 UTC, digiwand commented on app/components/UI/BlockaidBanner/BlockaidBanner.types.ts
> +export enum AttackType {
[comment] I was conflicted about using "AttackType". My thought is that to maintain consistency, it is safer to refer to the values as "Reason" values since this is the key name provided by the blockaid response.

2023-07-31 15:21 UTC, digiwand commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +  }
@jpuri is adding additional logic to return null if there is no response here https://github.com/MetaMask/metamask-extension/pull/20125/files#diff-fa946d37c83b9bea4c150a4a3244b3e6ede98712afef3cb0098b3a629fee8ec0

which makes me wonder, would it be helpful to pass the entire response to the component rather than break it apart beforehand? else, we will need to perform the !response check for each instance, and break apart the response for each instance that calls BlockaidBanner

2023-07-31 15:22 UTC, digiwand submitted a review, later dismissed
looks like all the comments in-scope were addressed. Nice work! 

todos outside of PR: 
- `DEFAULT_ACCORDION_EXPAND_DURATION` name change ref: https://github.com/MetaMask/metamask-mobile/pull/6585/files#r1277721480
- outer padding should be handled at BannerAlert DS level 
- [optional] add !response check ref: https://github.com/MetaMask/metamask-mobile/pull/6585/files#r1279473889

2023-07-31 23:34 UTC, digiwand commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +  }
@segun 

additionally she is checking for 'Failed' responses. I think we should add the failed check on the mobile side as well to match parity

2023-08-01 12:55 UTC, digiwand commented on app/components/UI/BlockaidBanner/BlockaidBanner.test.tsx
> +  it('should not render if flagtye is benign', async () => {
```suggestion
  it('should not render if flagType is benign', async () => {
```

2023-08-01 12:56 UTC, digiwand commented on app/components/UI/BlockaidBanner/BlockaidBanner.test.tsx
> +  it('should render normal banner alert if flagtye is failed', async () => {
```suggestion
  it('should render normal banner alert if flagType is failed', async () => {
```

2023-08-01 12:57 UTC, digiwand approved these changes, later dismissed

2023-08-03 16:20 UTC, digiwand commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +  return strings('blockaid_banner.deceptive_request_title');
a new title has been provided for failed. will need to be supported here as well

e.g. see https://github.com/MetaMask/metamask-extension/pull/20362 for extension implementation of new title

2023-08-03 16:22 UTC, digiwand commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +  }
[nit] could move before `getTitleDescription` logic to avoid calling `getTitleDescription` unnecessarily

2023-08-03 16:24 UTC, digiwand commented on app/components/UI/BlockaidBanner/BlockaidBanner.tsx
> +      <Accordion
can we move <Accordion> into `renderDetails` to avoid rendering <Accordion> if no details are provided? or add check around the template here?

2023-08-16 15:44 UTC, jpuri approved these changes
LGTM

2023-08-17 10:08 UTC, digiwand approved these changes

2023-08-24 10:16 UTC, merged