fix: patch zero balance when getBalance query times out
MetaMask/metamask-mobile pull request #6717
Opened 2023-06-28 13:26 UTC by NicolasMassart

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

Main token (eth) balance shows zero balance when the getBalance query times out as the store is updated to the 0x0 default value instead of not being updated at all. 

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_

This randomly shows a zero balance making the wallet display frightening zero ETH and show the "Add crypto to get started" button. Button only disapear and balance is ok when a new successful call is done. So you have the wrong state for 10s between two polls.

_2. What is the improvement/solution?_

Return an error instead of 0x0 as a balance when an error actually happen. This requires an update in `patches/@metamask+assets-controllers+5.0.0.patch`

**Issue**

fixes MetaMask/mobile-planning#1079

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

2023-06-28 15:53 UTC, tommasini requested changes
Left a comment! 
I just see a possible edge case, if the get balance fails and we don't have a default value, I can see the app crashing creating a new wallet for example, unless it's handled on other place that I'm not seeing

2023-06-28 15:53 UTC, tommasini commented on patches/@metamask+assets-controllers+5.0.0.patch
> ++            const result = yield (0, controller_utils_1.safelyExecuteWithTimeout)(() => __awaiter(this, void 0, void 0, function* () {
If we are not changing the util function `safelyExecuteWithTimeout` and only initiating the balance without a default '0x0' value, the result variable that has the return of the `safelyExecuteWithTimeout`  is not being used.

2023-06-28 16:32 UTC, NicolasMassart commented on patches/@metamask+assets-controllers+5.0.0.patch
> ++            const result = yield (0, controller_utils_1.safelyExecuteWithTimeout)(() => __awaiter(this, void 0, void 0, function* () {
Sorry I forgot to remove it...

2023-06-28 16:33 UTC, NicolasMassart commented
> I just see a possible edge case, if the get balance fails and we don't have a default value, I can see the app crashing creating a new wallet for example, unless it's handled on other place that I'm not seeing

[Each new account balance state is initialised with 0x0](https://github.com/MetaMask/core/blob/dc9eb67eed23375bdcaa9db2ddfadd995d81f397/packages/assets-controllers/src/AccountTrackerController.ts#L69-L71), so it can not be undefined in state unless the state is broken, but then we have other issues...

2023-06-29 09:37 UTC, tommasini approved these changes, later dismissed
Amazing! LGTM!

2023-06-29 15:42 UTC, NicolasMassart commented
Fix time tracking: 3d

2023-06-29 17:44 UTC, tommasini approved these changes
LGTM!!!!

2023-06-29 17:44 UTC, tommasini submitted a review, later dismissed
LGTM!!!!

2023-06-30 00:49 UTC, chrisleewilcox commented
@NicolasMassart I changed the base branch back to release/7.2.0 but there were merge conflicts with a few files.  I then changed the base branch back to main for now.  At least for this release we'll continue working out of the release branch.  Can you take a look at the merge conflicts against release branch?  I'll retest once the conflicts are resolved.

2023-06-30 16:27 UTC, sethkfman approved these changes
LGTM

2023-06-30 16:49 UTC, merged