Create a performance E2E test for warm starts
MetaMask/metamask-mobile pull request #6865
Opened 2023-07-22 00:29 UTC by SamuelSalas

**Description**
Feature test case created to test the warm start of the app from multiple devices. It sends the app to the background for 30 seconds so the Login screen appears.

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-07-24 13:13 UTC, Andepande submitted a review, later dismissed
LGTM

2023-07-24 22:28 UTC, cortisiko requested changes
code looks good, just left some feedback on your feature file.

2023-07-24 22:28 UTC, cortisiko commented on wdio/features/Performance/WarmStartPerformance.feature
> +  Scenario: Measure cold start launch time after importing a wallet
change from "cold" to "warm"

2023-07-24 22:28 UTC, cortisiko commented on wdio/features/Performance/WarmStartPerformance.feature
> +    When I background the app for 30 seconds
```suggestion
    When I background the app for 30 seconds
    And I relaunch the app
    And the timer starts running
    When I fill my password in the Login screen
    And I log into my wallet
    Then the app should launch within "5" seconds

2023-07-24 22:28 UTC, cortisiko commented on wdio/features/Performance/WarmStartPerformance.feature
> +    And the app should launch within "15000" seconds
This seems a bit excessive. We do need to establish a baseline for the warm starts. My idea was to have the test run on main for a week or so to establish a baseline then we create a ticket to set that baseline.

2023-07-25 15:48 UTC, SamuelSalas commented on wdio/features/Performance/WarmStartPerformance.feature
> +    When I background the app for 30 seconds
Adding the "And I relaunch the app" pretty much would be empty. The Background functionality from Appium already relaunch the app the set time pass

2023-07-25 15:49 UTC, SamuelSalas commented on wdio/features/Performance/WarmStartPerformance.feature
> +    And the app should launch within "15000" seconds
Of course, just set that time to pass the test cases and to use existing steps. I can update or create a new step for this one.

2023-07-26 00:58 UTC, cortisiko commented on wdio/features/Performance/WarmStartPerformance.feature
> +    When I background the app for 30 seconds
Good to know. Without having that context it is hard to tell whether the app has been foregrounded. Following the steps above, backgrounding the app and not specifying the app was foregrounded is a bit confusing. Adding a step to indicate that the app was brought to the foreground would enhance clarity and ease of understanding.

2023-07-26 01:01 UTC, cortisiko commented on wdio/features/Performance/WarmStartPerformance.feature
> +    And the app should launch within "15000" seconds
yup yup. So in this case, do not specify the expected time in milliseconds. Follow what we already did: https://github.com/MetaMask/metamask-mobile/blob/7a7653652ef2f0629b7b284613986a9e9478508f/wdio/features/Performance/AppLaunchTime.feature#L11 

Also let's set the launch time to be 6 seconds as our baseline. We can adjust as needed.

2023-07-26 01:01 UTC, cortisiko commented on wdio/step-definitions/warm-start-performance.steps.js
> +When(/^I background the app for (\d+) seconds$/, async (time) => {
We shouldn't even create a new step file for this. Let's move this step to the app launch times step file.

2023-07-26 01:04 UTC, cortisiko commented
Lets also go ahead and change the name of https://github.com/MetaMask/metamask-mobile/blob/feature/700-performance-test-warm-starts/wdio/features/Performance/AppLaunchTime.feature to `ColdStartLaunchTimes.feature`

2023-07-26 01:25 UTC, cortisiko commented on wdio/step-definitions/warm-start-performance.steps.js
> +When(/^I background the app for (\d+) seconds$/, async (time) => {
This step can live within `app-launch-times.steps.js`

2023-07-26 23:46 UTC, SamuelSalas commented on wdio/features/Performance/WarmStartPerformance.feature
> +    When I background the app for 30 seconds
Done

2023-07-26 23:46 UTC, SamuelSalas commented on wdio/step-definitions/warm-start-performance.steps.js
> +When(/^I background the app for (\d+) seconds$/, async (time) => {
Move to app lunch times step file

2023-07-26 23:47 UTC, SamuelSalas commented on wdio/step-definitions/warm-start-performance.steps.js
> +When(/^I background the app for (\d+) seconds$/, async (time) => {
Move it to app launch times steps file

2023-07-28 02:20 UTC, cortisiko approved these changes
PR looks good to me sam! great work!

2023-07-28 02:21 UTC, merged