refactor: Update controller packages to v44 [WIP]
MetaMask/metamask-mobile pull request #6872
Opened 2023-07-24 13:41 UTC by Gudahtt

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://docs.google.com/document/d/1VJLwTRsUw_5EDq_o8d6sSbXUAYENLurkRitYO45eY5o/edit?usp=sharing)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

TODO

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

Progresses #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-07-25 16:33 UTC, Gudahtt commented
@SocketSecurity ignore @metamask/swappable-obj-proxy@2.1.0

This is our package

2023-07-25 16:37 UTC, Gudahtt commented
This depends upon:

- https://github.com/MetaMask/metamask-mobile/pull/6874
- https://github.com/MetaMask/metamask-mobile/pull/6878
- https://github.com/MetaMask/metamask-mobile/pull/6879
- https://github.com/MetaMask/metamask-mobile/pull/6880
- https://github.com/MetaMask/metamask-mobile/pull/6881
- https://github.com/MetaMask/metamask-mobile/pull/6884

2023-07-27 23:16 UTC, Gudahtt commented on app/core/BackgroundBridge/BackgroundBridge.js
> -    // provider and block tracker proxies - because the network changes
The `NetworkController` method `getProviderAndBlockTracker` now returns a proxied provider and block tracker, so we don't need to proxy them at this layer anymore

2023-07-27 23:20 UTC, Gudahtt commented on package.json
> +    "@metamask/assets-controllers": "~5.0.1",
This is kept at v5.0.1 because v5.1.0 depends upon v7 of the network controller

2023-07-28 00:18 UTC, Gudahtt commented
Successful e2e test run: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/57d8e065-650f-4e01-9fb8-577cb754b96f

2023-07-28 02:26 UTC, cortisiko commented
@Gudahtt Once a successful dev review is done, let's put this PR through QA. I am a bit nervous about only having e2e run against it.

2023-07-28 02:46 UTC, Gudahtt commented
Definitely!

2023-07-28 12:21 UTC, Gudahtt commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +      // TODO: Use network configuration ID to update existing entries
Leaving it in this state is far from ideal. If we used the network configuration ID instead, we could eliminate a lot of this duplicate detection logic.

However, I started going down this path and lost confidence in it. This component is pretty complicated and I didn't understand all of the moving parts well enough. Instead I left it to use the same strategy it did before, because it seemed less likely to break something.

2023-07-28 20:40 UTC, mcmire reviewed
Did a first pass, left some minor comments. I will now check the changelog for v44 and make sure all changes are accounted for.

2023-07-28 20:40 UTC, mcmire commented on app/components/UI/Ramp/components/OrderDetails.tsx
> +  networkConfigurations: any;
Should we use `NetworkState['networkConfigurations']` here?

2023-07-28 20:40 UTC, mcmire commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
>      return networkInformation?.rpcUrl || '';
Nit: This now has a proper name (`networkConfiguration`).

``` suggestion
    const networkConfiguration = Object.values(networkConfigurations).find(
      ({ chainId: id }) => String(id) === String(Networks.mainnet.chainId),
    );
    return networkConfiguration?.rpcUrl || '';
```

2023-07-28 20:40 UTC, mcmire commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +        const networkInformation = Object.values(networkConfigurations).find(
Nit: This now has a proper name (`networkConfiguration`).

2023-07-28 20:40 UTC, mcmire commented on app/components/Views/Settings/NetworksSettings/index.js
> +        const { name } = { name: nickname || rpcUrl };
Nit: This can be simplified to

``` suggestion
        const name = nickname || rpcUrl;
```

2023-07-28 20:40 UTC, mcmire commented on app/core/RPCMethods/wallet_switchEthereumChain.js
> +    const [networkConfigurationId, networkConfiguration] = existingEntry;
It seems like `existingEntry` could be undefined here (if `existingNetworkDefault` is not nullish instead). Do we want to check for that here somehow before destructuring?

2023-07-28 21:48 UTC, mcmire approved these changes, later dismissed
I have double-checked the changes in these packages to ensure that they are covered by these changes. I am not familiar with all of the areas of mobile but the changes here make sense to me.

2023-08-03 16:46 UTC, Gudahtt commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +        const networkInformation = Object.values(networkConfigurations).find(
Done here: 7104b9bd3

2023-08-03 16:47 UTC, Gudahtt commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
>      return networkInformation?.rpcUrl || '';
Done here: 7104b9bd3

2023-08-04 23:50 UTC, Cal-L reviewed
Looks like the `chainId` that's being stored in the network controller for mobile is decimal format. When passed into `NetworkController.upsertNetworkConfiguration`, the app crashes with the error `Value must be a hexadecimal string, starting with "0x"`. It seems like we'll have to update the entire app to use that format but probably doesn't make sense to do it in this PR. We can just convert the decimal chain ID -> hexadecimal before passing it into `upsertNetworkConfiguration` for now.

2023-08-05 01:38 UTC, Cal-L reviewed
Other than the `upsertNetworkConfiguration` chainId issue, everything else including migrations LGTM

2023-08-15 18:17 UTC, Gudahtt commented
Great catch @Cal-L ! This was a problem I was aware of but had forgotten about - hex validation was added to that method despite the fact that we still use decimal string chain IDs in that controller. If we converted it to hex for just that call, it would remain in the wrong format in the configuration and would cause further problems. Instead I have updated `upsertNetworkConfiguration` in a patch to expect a decimal string chain ID, until the v53 update which converts it to hex.

2023-08-15 18:24 UTC, Gudahtt commented on app/components/UI/Ramp/components/OrderDetails.tsx
> +  networkConfigurations: any;
Oops, wrong line. Fixed here instead: 303697265

2023-08-15 19:15 UTC, Gudahtt commented
Updated passing e2e test run here: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/c68e73a6-29b8-45fe-85f8-f9240c2fb938

2023-08-15 21:28 UTC, Cal-L approved these changes, later dismissed
Confirmed the network switch issue is resolved

https://github.com/MetaMask/metamask-mobile/assets/10508597/8621c188-8cce-4709-87c0-6ad01eaf28f2

LGTM

2023-08-16 18:54 UTC, mcmire approved these changes, later dismissed

2023-08-18 13:24 UTC, Gudahtt commented
Rebased to resolve conflicts

2023-08-21 21:42 UTC, cortisiko requested changes
@Gudahtt I found a bug while testing. 

When adding a custom network either by adding it through the popular networks flow, or manually adding a custom network, the network does not automatically switch from mainnet to the custom network by default. 

To reproduce:
Import a wallet or create a wallet
Go to through the add custom network flow (tap on the network picker in the top nav on the wallet view > Add network > custom network tab)
Add a custom network using an RPC URL. Feel free to use gnosis: RPC URL: 

Notice you do not switch from mainnet to the custom network: http://recordit.co/9De0nA7ocy  

Reproducing via the custom network flow:
Import a wallet or create a wallet
Go to through the add custom network flow (tap on the network picker in the top nav on the wallet view > Add network > popular network tab)
Approve to add the network to your network list 
When the network-added modal appears tap the switch to network
Notice you are not taken to the custom network 

See here: http://recordit.co/v5iWMAR6GR 

Expected behavior:
When adding a custom network manually the network should automatically switch from mainnet to the custom network by default. 
 http://recordit.co/pIbty7aWDG 

Similarly, if you were to add a network via the popular networks flow, the network does not automatically update.

2023-08-22 18:11 UTC, Gudahtt commented
The reported bug should hopefully be fixed! Though I haven't validated that yet.

Updated Bitrise e2e smoke test run: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/27637e9f-c16d-4d77-b6ff-b3e8ca57d3a6

Bitrise browserstack test run: https://app.bitrise.io/build/fad7d051-9bb5-4eb9-bf9f-a407cdfed4da

Both passing

2023-08-22 18:31 UTC, cortisiko approved these changes
Fix looks good! Nothing else to report 🌮

2023-08-22 18:41 UTC, merged