Updated ButtonIcon disabled state
MetaMask/metamask-mobile pull request #6892
Opened 2023-07-25 05:16 UTC by brianacnguyen

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/coding_guidelines/CODING_GUIDELINES.md)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
- Update ButtonIcon's disabled state
- Also update ButtonIcon to probably disable

**Screenshots/Recordings**
![Simulator Screen Shot - iPhone 14 Pro - 2023-06-29 at 10 08 19](https://github.com/MetaMask/metamask-mobile/assets/14355083/dfc40bcb-db44-4505-bd35-8a9748d6b949)
![Simulator Screen Shot - iPhone 14 Pro - 2023-06-29 at 10 08 22](https://github.com/MetaMask/metamask-mobile/assets/14355083/98725257-644d-42d9-a95d-0f44aff76c69)

**Issue**

fixes #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-08-04 02:35 UTC, georgewrmarshall commented
Can this be closed in favor of https://github.com/MetaMask/metamask-mobile/pull/6727

2023-08-04 16:03 UTC, brianacnguyen commented
> 

They were originally but I split them out to help get things in faster

2023-08-29 18:00 UTC, tommasini requested changes
Hey @brianacnguyen, left a question!

If possible could you do as well a recording of button icons working on the app, and a small description of the change? <3

2023-08-29 18:04 UTC, brianacnguyen commented on app/component-library/components/Buttons/ButtonIcon/ButtonIcon.tsx
> +  const [pressed, setPressed] = useState(false);
it is being set on `triggerOnPressedIn` and  `triggerOnPressedOut `

2023-08-29 18:06 UTC, tommasini commented on app/component-library/components/Buttons/ButtonIcon/ButtonIcon.tsx
> +  const [pressed, setPressed] = useState(false);
You are right! It's not new lines thought, that make me be confused, thanks!

2023-08-29 18:06 UTC, brianacnguyen commented
> Hey @brianacnguyen, left a question!
> 
> If possible could you do as well a recording of button icons working on the app, and a small description of the change? <3

will add this soon

2023-08-30 16:51 UTC, tommasini approved these changes
LGTM!

2023-08-30 17:02 UTC, merged