Added README to BannerBase
MetaMask/metamask-mobile pull request #6894
Opened 2023-07-25 06:42 UTC by brianacnguyen

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/coding_guidelines/CODING_GUIDELINES.md)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
- Added README to BannerBase

**Screenshots/Recordings**
![Screenshot 2023-07-24 at 11 41 19 PM](https://github.com/MetaMask/metamask-mobile/assets/14355083/d38033a9-323f-42c0-ada6-245f978c888e)

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

fixes #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-07-25 17:14 UTC, georgewrmarshall requested changes
Looking good! Left some suggestions

2023-07-25 17:14 UTC, georgewrmarshall commented on app/component-library/components/Banners/Banner/foundation/BannerBase/README.md
> +BannerBase is a foundational component, which serves as a base for any inline notification.
Can we align the description with the insight reports for figma and extension?

![Screenshot 2023-07-25 at 10 11 00 AM](https://github.com/MetaMask/metamask-mobile/assets/8112138/2b1a5481-b278-4485-9ede-d847873216cd)

![Screenshot 2023-07-25 at 10 09 29 AM](https://github.com/MetaMask/metamask-mobile/assets/8112138/c17a91bf-6e74-4d7a-90bd-bfac9338466e)

<img width="1344" alt="Screenshot 2023-07-25 at 10 10 13 AM" src="https://github.com/MetaMask/metamask-mobile/assets/8112138/e9838c9e-99dd-4825-8f3e-35a33a537b3c">

```suggestion
BannerBase serves as a base for all banner variants. It contains  standard props such as information and related actions.
```

2023-07-25 20:21 UTC, georgewrmarshall approved these changes
LGTM!

2023-07-26 21:52 UTC, Gudahtt approved these changes
LGTM!

2023-07-27 01:29 UTC, merged