Added README to Avatar
MetaMask/metamask-mobile pull request #6895
Opened 2023-07-25 06:55 UTC by brianacnguyen

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/coding_guidelines/CODING_GUIDELINES.md)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add `needs-qa` label when dev review is completed
5. Add `QA Passed` label when QA has signed off

**Description**
Added README to Avatar

**Screenshots/Recordings**
![Screenshot 2023-07-24 at 11 54 11 PM](https://github.com/MetaMask/metamask-mobile/assets/14355083/bfcb9556-538a-48d7-a2c8-e49c289531f3)

**Issue**

fixes #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-07-25 17:26 UTC, georgewrmarshall requested changes
Looking good! Left some small suggestions

2023-07-25 17:26 UTC, georgewrmarshall commented on app/component-library/components/Avatars/Avatar/README.md
> +Avatar is a component that renders any circular graphic, which includes [AvatarAccount](./variants/AvatarAccount/AvatarAccount.tsx), [AvatarFavicon](./variants/AvatarFavicon/AvatarFavicon.tsx), [Avat
Can we consolidate the descriptions for this and design? I couldn't find an insight report with a description for Avatar but the one here and Figma seem pretty similar.

```
The Avatar is a round graphic identity. It unifies AvatarAccount, AvatarToken, AvatarNetwork and AvatarIcon
```

2023-07-25 17:26 UTC, georgewrmarshall commented on app/component-library/components/Avatars/Avatar/README.md
> +| [AvatarAccountType](./AvatarAccount.types.ts#L2)    | Yes                                                     | JazzIcon                                               |
I think this link will break because we need to traverse into the variants folder?
```suggestion
| [AvatarAccountType](./variants/AvatarAccount/AvatarAccount.types.ts)    | Yes                                                     | JazzIcon                                               |
```

2023-07-25 17:26 UTC, georgewrmarshall commented on app/component-library/components/Avatars/Avatar/README.md
> +| [name](./AvatarNetwork.types.ts#L11)                | No                                                      |
Update link to types

2023-07-25 17:26 UTC, georgewrmarshall commented on app/component-library/components/Avatars/Avatar/README.md
> +| [tokenName](./AvatarToken.types.ts#L10)             | No                                                      |
Update link to types

2023-07-25 17:26 UTC, georgewrmarshall commented on app/component-library/components/Avatars/Avatar/README.md
> +| [isHaloEnabled](./AvatarToken.types.ts#L18)         | No                                                      |
Update link to types

2023-07-26 16:57 UTC, brianacnguyen commented on app/component-library/components/Avatars/Avatar/README.md
> +| [AvatarAccountType](./AvatarAccount.types.ts#L2)    | Yes                                                     | JazzIcon                                               |
it does not

2023-07-26 17:52 UTC, georgewrmarshall approved these changes
Approved but left a comment about README links

2023-07-26 17:52 UTC, georgewrmarshall commented on app/component-library/components/Avatars/Avatar/README.md
> +| [AvatarAccountType](./AvatarAccount.types.ts#L2)    | Yes                                                     | JazzIcon                                               |
Oh? I thought we would want the URL to be:
https://github.com/MetaMask/metamask-mobile/blob/main/app/component-library/components/Avatars/Avatar/variants/AvatarAccount/AvatarAccount.types.ts

At the moment it looks like it will navigate here?
https://github.com/MetaMask/metamask-mobile/tree/main/app/component-library/components/Avatars/Avatar/AvatarAccount.types.ts#L2

2023-07-26 19:19 UTC, brianacnguyen commented on app/component-library/components/Avatars/Avatar/README.md
> +| [AvatarAccountType](./AvatarAccount.types.ts#L2)    | Yes                                                     | JazzIcon                                               |
i read that wrong. you're correct and I've updated the link accordingly

2023-07-26 20:08 UTC, georgewrmarshall commented on app/component-library/components/Avatars/Avatar/README.md
> +| [AvatarAccountType](./AvatarAccount.types.ts#L2)    | Yes                                                     | JazzIcon                                               |
Might need to push

2023-07-27 18:05 UTC, leotm reviewed
lgtm except couple 404's spotted

- [app/component-library/components/Avatars/Avatar/README.md](https://github.com/MetaMask/metamask-mobile/blob/ce805b307b3c43df9295e8d23aebd312e77314b5/app/component-library/components/Avatars/Avatar/README.md)
  - [AvatarAccountType](https://github.com/MetaMask/metamask-mobile/blob/ce805b307b3c43df9295e8d23aebd312e77314b5/app/component-library/components/Avatars/Avatar/AvatarAccount.types.ts#L2)
  - [IconName](https://github.com/MetaMask/metamask-mobile/blob/ce805b307b3c43df9295e8d23aebd312e77314b5/app/component-library/components/Avatars/Icons/Icon.types.ts)

2023-07-27 21:43 UTC, georgewrmarshall requested changes
Looks like those links still need updating going to unresolve until they've been updated

2023-08-02 19:17 UTC, georgewrmarshall approved these changes
LGTM 👍

2023-08-02 20:37 UTC, owencraston approved these changes

2023-08-02 20:41 UTC, merged