Fix invalid password error
MetaMask/metamask-mobile pull request #6957
Opened 2023-08-02 17:39 UTC by jpcloureiro

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/coding_guidelines/CODING_GUIDELINES.md)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add the appropiate QA label when dev review is completed
    - `needs-qa`: PR requires manual QA.
    - `No QA/E2E only`: PR does not require any manual QA effort. Prior to merging, ensure that you have successful end-to-end test runs in Bitrise. 
    - `Spot check on release build`: PR does not require feature QA but needs non-automated verification. In the description section, provide test scenarios. Add screenshots, and or recordings of what was tested.
5. Add `QA Passed` label when QA has signed off (Only required if the PR was labeled with `needs-qa`)
6. Add your team's label, i.e. label starting with `team-` (or `external-contributor` label if your not a MetaMask employee)

**Description**

KeyringController did not update redux store state after vault recovery.

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

https://github.com/MetaMask/mobile-planning/issues/1160

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-08-03 07:47 UTC, NicolasMassart approved these changes
Please ask for another approval but for what I read it looks good.

2023-08-03 16:03 UTC, Cal-L commented
Could you provide info for expected behavior on both scenario 1 and 2 + provide videos demonstrating the fix?

2023-08-03 16:11 UTC, Cal-L requested changes
Could you provide info for expected behavior on both scenario 1 and 2 + provide videos demonstrating the fix?

2023-08-03 18:02 UTC, jpcloureiro commented
> > Could you provide info for expected behavior on both scenario 1 and 2 + provide videos demonstrating the fix?
> 
> @jpcloureiro Are the 2 cases listed steps to reproduce or steps to verify the fix? In both scenarios, it states to install the APK/Testflight build but doesn't have the build numbers associated with them

I've updated the description with videos and descriptions on how to replicate the problems and fixes running local development builds.

Steps to reproduce will have build numbers to help QA verify the acceptance criteria

2023-08-03 19:01 UTC, owencraston commented on app/components/Views/ResetPassword/index.js
> -  passwordUnset: () => dispatch(passwordUnset()),
@jpcloureiro why was this not needed anymore?

2023-08-03 19:02 UTC, owencraston commented on app/core/Authentication/Authentication.ts
>        this.store?.dispatch(authSuccess(bioStateMachineId));
we should migrate the `this.store?.dispatch(authSuccess(bioStateMachineId));` to have its own dispatch function

2023-08-04 16:15 UTC, jpcloureiro commented on app/components/Views/ResetPassword/index.js
> -  passwordUnset: () => dispatch(passwordUnset()),
It is dead code

2023-08-04 18:49 UTC, Cal-L commented on app/core/Authentication/Authentication.ts
>        this.store?.dispatch(authSuccess(bioStateMachineId));
+1 that it will be cleaner. Since it isn't related to these fixes, we can handle in future iterations of auth refactors. WDYT?

2023-08-04 18:50 UTC, Cal-L approved these changes
Thanks for the videos. LGTM!

2023-08-14 16:55 UTC, owencraston approved these changes

2023-08-15 14:09 UTC, hesterbruikman commented
Manual test findings:

**1. Upgrade after vault corruption during wallet creation**
Android 11
Samsung Galaxy S10e

1. Install 6.6
2. Create wallet
3. Trigger vault corruption following [these steps](https://github.com/MetaMask/mobile-planning/issues/975#issuecomment-1634454281)
4. Upgrade to 7.4.1 (including PR fix)

Result: Success
Outcome: Reset password
[Recording](https://drive.google.com/file/d/1o25VQjCks2qfg6W7aS2FYuOm-abXpjR5/view?usp=sharing)

**2. Upgrade after vault corruption during wallet import**
Android 11
Samsung Galaxy S10e

1. Install 6.6
2. Create wallet
3. Trigger vault corruption following [these steps](https://github.com/MetaMask/mobile-planning/issues/975#issuecomment-1634454281)
4. Upgrade to 7.4.1 (including PR fix)

Result: Success
Outcome: Back up SRP and set password
[Recording](https://drive.google.com/file/d/1oB9Nd9I0fVY3vgoMgwmy5dLj_M8BUIME/view?usp=sharing)

2023-08-15 19:24 UTC, cortisiko approved these changes
### **Parameters for testing:**

- Imported Wallet Biometrics enabled
- New Wallet Biometrics enabled
- Imported Wallet Biometrics disabled. 
- New Wallet Biometrics disabled. 


### Devices used:
**iOS: iPhone Xr, 11, iPhone SE
Android:  Pixel 3XL, Xiaomi Redmi Note 10, Samsung S8**


### Scenarios I covered:
 Biometrics enabled (FaceID and FingerPrint):

- Updating from v6.6 (1113) to v7.1 (1125) to trigger the bug in the vault corruption flow then updating to the build with the fix [v7.4.1 (1161)]
- Updating from all versions of the app since the vault corruption bug was introduced v7.1 - v7.4 to the build with the fix [v7.4.1 (1161)]


- Updating from v6.6 (1113) to v7.1 (1125) to trigger the bug in the vault corruption flow then updating to the build with the fix [v7.4.1 (1161)] I ensured that I can successfully enter my password. I went ahead and changed my password, killed and relaunch the app then authenticate with password instead of biometrics. 

- Import wallet on v6.6 (1113) then changed password. Updated to v7.1 (1125) to trigger the bug in the vault corruption flow then updated to the build with the fix [v7.4.1 (1161)]. 

I can confirm the invalid password error does not appear. I am able to successfully recover my wallet. 

_____


### No biometrics enabled (NO FaceID and FingerPrint):

- Updating from v6.6 (1113) to v7.1 (1125) to trigger the bug in the vault corruption flow then updating to the build with the fix [v7.4.1 (1161)]
- Updating from all versions of the app since the vault corruption bug was introduced v7.1 - v7.4 to the build with the fix [v7.4.1 (1161)]


- Updating from v6.6 (1113) to v7.1 (1125) to trigger the bug in the vault corruption flow then updating to the build with the fix [v7.4.1 (1161)] I ensured that I can successfully enter my password. I went ahead and changed my password, killed and relaunch the app then authenticate with password instead of biometrics. 

- Import wallet on v6.6 (1113) then changed password. Updated to v7.1 (1125) to trigger the bug in the vault corruption flow then updated to the build with the fix [v7.4.1 (1161)]. 

I can confirm the invalid password error does not appear. I am able to successfully recover my wallet. 

This PR is ✅

2023-08-16 15:00 UTC, merged