940 e2e migrate senderc721 test to detox
MetaMask/metamask-mobile pull request #6983
Opened 2023-08-13 17:00 UTC by sleepytanya

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/coding_guidelines/CODING_GUIDELINES.md)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add the appropiate QA label when dev review is completed
    - `needs-qa`: PR requires manual QA.
    - `No QA/E2E only`: PR does not require any manual QA effort. Prior to merging, ensure that you have successful end-to-end test runs in Bitrise. 
    - `Spot check on release build`: PR does not require feature QA but needs non-automated verification. In the description section, provide test scenarios. Add screenshots, and or recordings of what was tested.
5. Add `QA Passed` label when QA has signed off (Only required if the PR was labeled with `needs-qa`)
6. Add your team's label, i.e. label starting with `team-` (or `external-contributor` label if your not a MetaMask employee)

**Description**

Converted Appium E2E test to Detox.

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-08-14 18:43 UTC, SamuelSalas commented on e2e/helpers.js
> +        // Element not found yet: waithing for 200ms
Change waithing with waiting

2023-08-14 19:05 UTC, SamuelSalas commented on e2e/pages/Drawer/Browser.js
> +      await TestHelpers.tapAtPoint(BROWSER_WEBVIEW_ID, BUTTON_RELATIVE_PONT);
why do you need to import the BUTTON_RELATIVE_PONT constant? Considering that is being used in the same way as in the TestDApp.js file.

2023-08-14 20:25 UTC, chrisleewilcox commented
@sleepytanya test passes for both iOS and android when I run locally.  

I did notice that iOS was failing at first because it kept timing out.  I had to adjust `testTimeout` to `180000` in `/e2e/jest.e2e.config.js` and the test passes.  Not sure why this takes longer to run on iOS.

2023-08-14 20:26 UTC, chrisleewilcox submitted a review, later dismissed
LGTM

2023-08-14 20:51 UTC, sleepytanya commented
@chrisleewilcox probably IOS takes longer time because detox has no access to webview -  i can not conditionally check if web element is presented, so using hardcoded delays.

2023-08-14 21:13 UTC, cortisiko requested changes
I left a few comments. When you get a chance, can you run all the tests in the confirmations folder on your local machine?

2023-08-14 21:13 UTC, cortisiko commented on e2e/pages/Drawer/Browser.js
> +    await TestHelpers.tapByText(CONFIRM_BUTTON_TEXT, 0);
submitting a transaction should be in its own method.

2023-08-14 21:13 UTC, cortisiko commented on e2e/specs/confirmations/send-erc721.spec.js
> +    await Browser.tapConnectButton();
any objections to using https://github.com/MetaMask/metamask-mobile/blob/main/e2e/pages/TestDApp.js#L12 instead of lines 48 and 49?

2023-08-17 20:03 UTC, cortisiko reviewed
@sleepytanya I left a few more comments. Also I didn't have success running the test on iOS. After you address my comments can you confirm that you are able to run the tests on iOS?

2023-08-18 02:13 UTC, sleepytanya commented on e2e/specs/confirmations/send-erc721.spec.js
> +    await Browser.tapConnectButton();
Fixed.

2023-08-18 02:13 UTC, sleepytanya commented on e2e/specs/confirmations/send-erc721.spec.js
> +const CONFIRM_BUTTON_TEXT = root.messages.confirmation_modal.confirm_cta;
Good catch! Fixed.

2023-08-18 02:14 UTC, sleepytanya commented on e2e/specs/confirmations/send-erc721.spec.js
> +      root.transactions.sent_collectible,
Done.

2023-08-18 02:14 UTC, sleepytanya commented on e2e/specs/confirmations/send-erc721.spec.js
> +describe(Regression('Send token tests'), () => {
Done.

2023-08-18 02:14 UTC, sleepytanya commented on e2e/specs/confirmations/send-erc721.spec.js
> +    await TestHelpers.tapByText(CONFIRM_BUTTON_TEXT, 0);
Done.

2023-08-22 18:23 UTC, cortisiko approved these changes
🥇 🥇 🥇  Good work @sleepytanya !

2023-08-22 18:53 UTC, merged