test: Enable cold start tests for iOS against browserstack locally
MetaMask/metamask-mobile pull request #7040
Opened 2023-08-22 20:52 UTC by SamuelSalas

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/coding_guidelines/CODING_GUIDELINES.md)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add the appropiate QA label when dev review is completed
    - `needs-qa`: PR requires manual QA.
    - `No QA/E2E only`: PR does not require any manual QA effort. Prior to merging, ensure that you have successful end-to-end test runs in Bitrise. 
    - `Spot check on release build`: PR does not require feature QA but needs non-automated verification. In the description section, provide test scenarios. Add screenshots, and or recordings of what was tested.
5. Add `QA Passed` label when QA has signed off (Only required if the PR was labeled with `needs-qa`)
6. Add your team's label, i.e. label starting with `team-` (or `external-contributor` label if your not a MetaMask employee)

**Description**
We need to ensure that our app's performance does not drop during releases. The goal of this ticket is to optimize the app's launch and relaunch times to ensure a smooth user experience. You would be measuring the cold launch times of the iOS app. Similar to the Android

**Issue**

fixes #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-08-22 21:25 UTC, cortisiko requested changes
I would say kick off Detox and ensure nothing breaks.

2023-08-22 21:25 UTC, cortisiko commented on app/components/Views/ImportFromSecretRecoveryPhrase/index.js
> +          ANDROID_IMPORT_FROM_SEED_SCREEN_SEED_PHRASE_INPUT_ID,
ehh. You shouldn't change the name of the testID though. In Detox the testID is consistent across platforms. Having the testID named `ANDROID_IMPORT_FROM_SEED_SCREEN_SEED_PHRASE_INPUT_ID` would cause confusion for Detox tests.

2023-08-22 21:25 UTC, cortisiko commented on wdio/screen-objects/testIDs/Screens/WalletSetupScreen.testIds.js
> -export const I_AGREE_BUTTON = 'optin-metrics-i-agree-button-id';
Any reason why we removed this ID?

2023-08-22 21:25 UTC, cortisiko commented on wdio/screen-objects/testIDs/Screens/WalletSetupScreen.testIds.js
> -export const CREATE_PASSWORD_INPUT_FIRST_FIELD =
Any reason why we removed this ID?

2023-08-22 21:25 UTC, cortisiko commented on wdio/screen-objects/testIDs/Screens/WalletSetupScreen.testIds.js
> -export const ANDROID_I_UNDERSTAND_BUTTON_ID = 'skip-backup-text';
Any reason why we removed this ID?

2023-08-22 21:25 UTC, cortisiko commented on wdio/screen-objects/testIDs/Screens/WalletSetupScreen.testIds.js
> -export const SKIP_BACKUP_MODAL = 'skip-backup-modal';
Any reason why we removed this ID?

2023-08-22 21:25 UTC, cortisiko commented on wdio/screen-objects/testIDs/Screens/WalletSetupScreen.testIds.js
> -export const SKIP_ACCOUNT_SECURITY_MODAL = 'skip_backup_warning';
Any reason why we removed this ID?

2023-08-22 21:57 UTC, SamuelSalas commented on app/components/Views/ImportFromSecretRecoveryPhrase/index.js
> +          ANDROID_IMPORT_FROM_SEED_SCREEN_SEED_PHRASE_INPUT_ID,
This selector was one of the elements that needed to have both an ios and an android. I change it to keep consistency with the IOS naming. I can restore the testID and just have the ios as it.

2023-08-22 21:58 UTC, SamuelSalas commented on wdio/screen-objects/testIDs/Screens/WalletSetupScreen.testIds.js
> -export const CREATE_PASSWORD_INPUT_FIRST_FIELD =
Its not being used at the moment. I removed it to make the code more clean. I can restore it.

2023-08-22 21:58 UTC, SamuelSalas commented on wdio/screen-objects/testIDs/Screens/WalletSetupScreen.testIds.js
> -export const I_AGREE_BUTTON = 'optin-metrics-i-agree-button-id';
Its not being used at the moment. I removed it to make the code more clean. I can restore it.

2023-08-22 21:58 UTC, SamuelSalas commented on wdio/screen-objects/testIDs/Screens/WalletSetupScreen.testIds.js
> -export const ANDROID_I_UNDERSTAND_BUTTON_ID = 'skip-backup-text';
Its not being used at the moment. I removed it to make the code more clean. I can restore it.

2023-08-22 21:58 UTC, SamuelSalas commented on wdio/screen-objects/testIDs/Screens/WalletSetupScreen.testIds.js
> -export const SKIP_BACKUP_MODAL = 'skip-backup-modal';
Its not being used at the moment. I removed it to make the code more clean. I can restore it.

2023-08-22 21:59 UTC, SamuelSalas commented on wdio/screen-objects/testIDs/Screens/WalletSetupScreen.testIds.js
> -export const SKIP_ACCOUNT_SECURITY_MODAL = 'skip_backup_warning';
Its not being used at the moment. I removed it to make the code more clean. I can restore it.

2023-08-22 22:19 UTC, cortisiko commented on app/components/Views/ImportFromSecretRecoveryPhrase/index.js
> +          ANDROID_IMPORT_FROM_SEED_SCREEN_SEED_PHRASE_INPUT_ID,
Oh I see. If appium was our main framework I would be in favor of the change but since it is not, just restore it.

2023-08-23 02:06 UTC, SamuelSalas commented on app/components/Views/ImportFromSecretRecoveryPhrase/index.js
> +          ANDROID_IMPORT_FROM_SEED_SCREEN_SEED_PHRASE_INPUT_ID,
Got it

2023-08-23 21:55 UTC, cortisiko approved these changes
Looks good. Thanks @SamuelSalas

2023-08-23 22:28 UTC, merged