test: Swap and Token Details e2e automated tests
MetaMask/metamask-mobile pull request #7074
Opened 2023-08-29 12:50 UTC by davibroc

**Description**
This PR add e2e test coverage for Swap and Token Details page as well testIds in the app to facilitate the execution of the scripts.

Instruction to run the script:

Swap:
`yarn test:e2e:ios:debug:single e2e/specs/swap-token.spec.js`

Token Details:
`yarn test:e2e:ios:debug:single e2e/specs/token-details.spec.js`

https://github.com/MetaMask/metamask-mobile/assets/6626407/54cb934e-09a3-45f6-9084-4e00d0f57306

https://github.com/MetaMask/metamask-mobile/assets/6082863/a5254edf-59a4-49d5-87ae-f1fd6e05a22a

2023-08-29 23:22 UTC, cortisiko requested changes
Great stuff @davibroc ! A couple of things: 

- Can you create a new folder, call it "Swaps" and have your tests live in that folder? 
- Now that we have fixtures implemented feel free to use it to bypass these long test steps! 
-  Run `yarn lint` to fix the linting issues on your PR. 

Also, I left a few comments!

2023-08-29 23:22 UTC, cortisiko commented on e2e/pages/SwapView.js
> +  static async getQuote(quantity, sourceTokenSymbol, destTokenSymbol) {
This method is doing a lot more than getting the swaps quote. Can we have this method only fetch the quotes? 

Can we split this up a bit:
A method for getting to the swaps page.  
A method for selecting tokens
A method for entering the amount you want to swap

2023-08-29 23:22 UTC, cortisiko commented on e2e/pages/SwapView.js
> +    await TestHelpers.checkIfElementByTextIsVisible('Fetching quotes');
import this string from the en.json locales and use it here. The object that contains the string is: `swaps.fetching_quotes`

2023-08-29 23:22 UTC, cortisiko commented on e2e/pages/TokenOverview.js
> +const NO_CHART_DATA = 'No chart data';
import this string from the en.json locales and use it here. The object that contains the string is: `asset_overview.no_chart_data.title`

2023-08-29 23:22 UTC, cortisiko commented on e2e/pages/TokenOverview.js
> +const chartTimePeriod = ['1D', '1W', '1M', '3M', '1Y', '3Y'];
import this string from the en.json locales and use it here. The object that contains the string is: `asset_overview.no_chart_data.chart_time_period_navigation`

2023-08-29 23:22 UTC, cortisiko commented on e2e/specs/swap-token.spec.js
> +    quantity | sourceTokenSymbol | destTokenSymbol
Can you put these values in a json that lives in the resource folder? Then import the json to access each value.

2023-08-29 23:22 UTC, cortisiko commented on e2e/specs/token-details.spec.js
> +    networkName                    | symbol        | swapTo
Can you put these values in a json that lives in the resource folder? Perhaps call it networks.json? Then import the json to access each value.

2023-08-30 14:21 UTC, davibroc commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +                {...generateTestId(Platform, TOKEN_OVERVIEW_RECEIVE_BUTTON)}
Done

2023-08-30 14:41 UTC, davibroc commented on e2e/pages/SwapView.js
> +    await TestHelpers.waitAndTapText('Start swapping');
Done

2023-08-30 14:42 UTC, davibroc commented on e2e/pages/SwapView.js
> +    await TestHelpers.checkIfElementByTextIsVisible('Fetching quotes');
Done

2023-09-01 03:48 UTC, davibroc commented on e2e/helpers.js
> +  static async checkIfElementIsNotVisible(elementId, text) {
checkIfElementWithTextIsNotVisible is already taken so I cannot use.  Please check line 172 where I make sure the element does NOT contain the text.

` expect(element(by.id(elementId))).not.toHaveText(text);`

In other words here I check that the chart doesn't have a quote that is `$0` to address this bug
https://github.com/MetaMask/metamask-mobile/issues/7062

How about checkIfElementNotToHaveText?

2023-09-01 06:25 UTC, davibroc commented on e2e/pages/SwapView.js
> +  static async getQuote(quantity, sourceTokenSymbol, destTokenSymbol) {
Done

2023-09-01 10:44 UTC, davibroc commented on e2e/pages/TokenOverview.js
> +const NO_CHART_DATA = 'No chart data';
Done

2023-09-01 10:45 UTC, davibroc commented on e2e/specs/token-details.spec.js
> +    networkName                    | symbol        | swapTo
I have changed it please look at the new code

2023-09-01 11:04 UTC, davibroc commented on e2e/pages/TokenOverview.js
> +const chartTimePeriod = ['1D', '1W', '1M', '3M', '1Y', '3Y'];
Actually that doesn't map correctly to what's displayed on the screen as we don't have a 7D chart. See below. Not sure it's worth the extra code to map it right. Don't think these label will change much anyway

` "chart_time_period_navigation": {
      "1d": "1D",
      "7d": "7D",
      "1w": "1W",
      "1m": "1M",
      "3m": "3M",
      "1y": "1Y",
      "3y": "3Y"
    }`

2023-09-01 11:07 UTC, davibroc commented on e2e/specs/swap-token.spec.js
> +    quantity | sourceTokenSymbol | destTokenSymbol
Actually on this I would rather keep the code like this. It's much easier to read this way and with just one line of code you can add more pair swaps. What do you think?

2023-09-07 00:35 UTC, cortisiko requested changes
a few more comments. Also run `yarn lint` to fix the lining issues

2023-09-07 00:35 UTC, cortisiko commented on e2e/pages/TokenOverview.js
> +  static async checkIfReceiveButtonVisible() {
```suggestion
  static async isReceiveButtonVisible() {
```

2023-09-07 00:35 UTC, cortisiko commented on e2e/pages/TokenOverview.js
> +  static async checkIfSendButtonVisible() {
```suggestion
  static async isSendButtonVisible() {
```

2023-09-07 00:35 UTC, cortisiko commented on e2e/pages/TokenOverview.js
> +  static async checkIfBuyButtonVisible() {
```suggestion
  static async isBuyButtonVisible() {
```

2023-09-07 00:35 UTC, cortisiko commented on e2e/pages/TokenOverview.js
> +  static async checkIfSwapButtonVisible() {
```suggestion
  static async isSwapButtonVisible() {
```

2023-09-07 00:35 UTC, cortisiko commented on e2e/specs/swaps/token-details.spec.js
> +const Goerli = {
Can you put the network names in a json, call it `networks.json.` Then import the networks in this test

2023-09-07 00:35 UTC, cortisiko commented on e2e/pages/TokenOverview.js
> +const chartTimePeriod = ['1D', '1W', '1M', '3M', '1Y', '3Y'];
Fair, the goal is to avoid hard coding values in the test and use what is already created.  

`chartTimePeriod = [asset_overview.no_chart_data.chart_time_period_navigation.1d, asset_overview.no_chart_data.chart_time_period_navigation.1w, asset_overview.no_chart_data.chart_time_period_navigation.1m]` 

would probably work?

2023-09-07 06:37 UTC, davibroc commented on e2e/pages/TokenOverview.js
> +  static async checkIfSendButtonVisible() {
Done

2023-09-07 06:37 UTC, davibroc commented on e2e/pages/TokenOverview.js
> +  static async checkIfBuyButtonVisible() {
Done

2023-09-07 06:38 UTC, davibroc commented on e2e/pages/TokenOverview.js
> +  static async checkIfSwapButtonVisible() {
done

2023-09-07 07:17 UTC, davibroc commented on e2e/specs/swaps/token-details.spec.js
> +const Goerli = {
Done

2023-09-07 07:35 UTC, davibroc commented on e2e/pages/TokenOverview.js
> +const chartTimePeriod = ['1D', '1W', '1M', '3M', '1Y', '3Y'];
Done

2023-09-07 08:25 UTC, davibroc commented
I have read the CLA Document and I hereby sign the CLA

2023-09-07 14:55 UTC, cortisiko commented on e2e/pages/TokenOverview.js
> +  static async checkChartNotVisible() {
```suggestion
  static async ChartIsNotVisible() {
```

2023-09-07 14:56 UTC, cortisiko commented on e2e/pages/TokenOverview.js
> +  static async checkTokenQuoteIsNotZero() {
```suggestion
  static async TokenQuoteIsNotZero() {
```

2023-09-07 19:17 UTC, chrisleewilcox requested changes
Had to change to await WalletView.tapOnToken(Networks.Goerli.providerConfig.ticker); and it worked.

2023-09-07 19:17 UTC, chrisleewilcox commented on e2e/specs/swaps/token-details.spec.js
> +    await WalletView.tapOnToken(Networks.Goerli.ticker);
await WalletView.tapOnToken(Networks.Goerli.providerConfig.ticker);

2023-09-07 20:32 UTC, chrisleewilcox requested changes
Getting failures when transitioning to the failed tests.  Looks like it was failing to unlock app at the start of the next dataset.  Commenting out the failed scenarios and the tests passes.  Didn't dig too much into the failed scenarios....
![image](https://github.com/MetaMask/metamask-mobile/assets/6626407/fe5d8326-e8e3-421c-b8f5-3b9ce477204f)

2023-09-07 21:26 UTC, cortisiko commented on e2e/fixtures/fixture-builder.js
> +                  rpcUrl:
You specified this in the fixture builder as well as the `swaps-tokens.spec.js`. Is there a reason for the duplication?

2023-09-07 21:27 UTC, cortisiko commented on e2e/specs/swaps/swap-tokens.spec.js
> +        providerConfig: {
can we move this to the `networks.json`

2023-09-08 06:05 UTC, davibroc commented on e2e/pages/TokenOverview.js
> +  static async checkChartNotVisible() {
Done

2023-09-08 06:06 UTC, davibroc commented on e2e/pages/TokenOverview.js
> +  static async checkTokenQuoteIsNotZero() {
Done

2023-09-08 06:07 UTC, davibroc commented on e2e/specs/swaps/token-details.spec.js
> +    await WalletView.tapOnToken(Networks.Goerli.ticker);
Done

2023-09-08 06:10 UTC, davibroc commented on e2e/fixtures/fixture-builder.js
> +                  rpcUrl:
Not really a duplication because this is the frequentRpcList. I did that because I saw Mariona doing the same when he added Localhost but after checking it's not needed so I will remove

2023-09-08 06:15 UTC, davibroc commented on e2e/specs/swaps/swap-tokens.spec.js
> +        providerConfig: {
Done

2023-09-14 17:41 UTC, chrisleewilcox submitted a review, later dismissed
I would say for now we should just comment out or remove the failing scenarios so we can get your PR merged.

2023-09-15 05:28 UTC, Woodpile37 approved these changes

2023-09-20 12:01 UTC, davibroc commented
> a few more comments. Also run `yarn lint` to fix the lining issues

Done

2023-09-20 12:02 UTC, davibroc commented
> a few more comments. Also run `yarn lint` to fix the lining issues

This is done

2023-09-20 12:57 UTC, nikoferro submitted a review, later dismissed
LGTM

2023-09-20 22:15 UTC, cortisiko approved these changes
Good work @davibroc 🥇 🥇 🥇

2023-09-21 07:54 UTC, merged