Olu/blockaid dapp metrics
MetaMask/metamask-mobile pull request #7104
Opened 2023-09-01 10:54 UTC by segun

**Description**

Adding analytics to Blockaid will help us understand and evaluate the performance of this feature.

For users that have the Blockaid feature enabled, on performing a dapp transaction, the following should happen

1. Add a security_alert_response property to Transactions and Signature events, the value of this property should be the [result_type parameter that is returned by Blockaid](https://wobbly-nutmeg-8a5.notion.site/PPOM-Validation-Schema-Attack-Types-555e7f6a5b6c4b6caa9ced59561c8667) (e.g. set_approval_for_all_famring).
2. Add a security_alert_reason property to Transactions and Signature events, the value of this property should be the [reason parameter that is returned by Blockaid](https://wobbly-nutmeg-8a5.notion.site/PPOM-Validation-Schema-Attack-Types-555e7f6a5b6c4b6caa9ced59561c8667). When there's no value for this property (because user has the feature disabled or Blockaid response does not contain a reason value), we should pass it the value not_applicable.
Create ui_customizations list property for transactions and signatures events on mobile - this property should be similar to the one created here on extension [MetaMask/metamask-extension#17688](https://github.com/MetaMask/metamask-extension/pull/17688). This property should be a type list property (more info [here](https://help.mixpanel.com/hc/en-us/articles/115004547063-Properties-Supported-Data-Types#list).
3. Whenever we display a warning to the user as a result of Blockaid flagging a request as malicious, we should add the flagged_as_malicious value to the ui_customizations property in the respective Transactions or Signature events

**Issue**

https://github.com/MetaMask/MetaMask-planning/issues/929

**Checklist**

* [x] There is a related GitHub issue
* [x] Tests are included if applicable
* [x] Any added code is fully documented

2023-09-01 15:19 UTC, jpuri commented on app/util/blockaid/index.ts
> +export const getAdditionalMetricsParams = (
The function name is very generic.

2023-09-01 15:21 UTC, jpuri commented on app/components/Views/Send/index.js
> +      { ...this.getTrackingParams(), ...additionalParams },
Similarly here change can go into `this.getTrackingParams(),`.

2023-09-07 15:46 UTC, jpuri submitted a review, later dismissed
LGTM

2023-09-12 13:32 UTC, segun commented
Once [this](https://github.com/MetaMask/metamask-mobile/pull/7068) is merged, rebase to main

2023-09-13 15:29 UTC, segun commented on app/lib/ppom/ppom.html.js
>  var A = {
Not entirely sure why this file is included in this change. I think yarn lint:fix is reformatting it.

2023-09-14 09:17 UTC, blackdevelopa commented on app/lib/ppom/ppom.html.js
>  var A = {
If we revert the change in this file locally and pushed without running `yarn lint`, would that overwrite this in your PR?

2023-09-14 09:27 UTC, blackdevelopa commented on app/components/UI/PersonalSign/PersonalSign.tsx
>        getAnalyticsParams(),
Should we be passing the expected [props](https://github.com/MetaMask/metamask-mobile/pull/7104/files#diff-9eb780c5c84ee4e372468c43a809dfd448ac21398bcc485ad9a1ac85a68b3d60R17) to `getAnalyticsParams`?

2023-09-14 13:17 UTC, segun commented on app/components/UI/PersonalSign/PersonalSign.tsx
>        getAnalyticsParams(),
This one doesn't take any props. I'm not entirely sure why PersonalSign has a different separate method to do this separate from the rest....but this is analytics forte and that question is beyond the scope of this PR.

2023-09-14 15:18 UTC, jpuri commented on app/components/UI/SignatureRequest/index.js
> +
Just curious: was `SIGN_REQUEST_STARTED` event not captured before ?

2023-09-14 15:19 UTC, jpuri commented on app/components/Views/Send/index.js
> +      ...blockaidParams,
This may break if `blockaidParams` is `undefined`

2023-09-14 15:20 UTC, jpuri commented on app/lib/ppom/ppom.html.js
>  var A = {
Plz revert changes to this file, this is file provided by blockaid team and audited by diligence team and should be preserved exactly as audited.

2023-09-14 15:21 UTC, jpuri commented on app/util/confirmation/signatureUtils.js
> +    }
`if` condition above can be omitted as it is taken care of in `getBlockaidMetricsParams` function.

2023-09-14 15:22 UTC, jpuri requested changes
Please revert changes in `app/lib/ppom/ppom.html.js`

2023-09-18 19:24 UTC, segun commented on app/components/UI/SignatureRequest/index.js
> +
I was curious too, this method exists with the parameters, but all the place the method was called, it was called without the parameters. Honestly not sure why they call with without the parameters.

I need to use the method in this PR and there's [another PR](https://github.com/MetaMask/metamask-mobile/pull/7120) that specified the event values, so I followed the same value naming in that PR to call this method with the proper parameters.

Alternatively, I could leave the method as is and use something else for blockaid stuffs. But I don't think that's optimal.

2023-09-19 05:28 UTC, jpuri approved these changes

2023-09-19 05:30 UTC, jpuri commented on app/components/UI/ApproveTransactionReview/index.js
> +      }
Nit: a way to simplify using may `if` conditions could be `getBlockaidMetricsParams` return empty object if blockaid is not enabled or `transaction.securityAlertResponse` is not defined.

Thus we do not need to check `if (showBlockaidUI())` at many places.

2023-09-20 11:26 UTC, blackdevelopa approved these changes

2023-09-20 13:01 UTC, merged