Feat: Fix the Message Sign issue for ledger devices
MetaMask/metamask-mobile pull request #7172
Opened 2023-09-08 01:08 UTC by dawnseeker8

**Description**

After rebase from `main` branch to `ledger-intergtation-main` branch, the whole ledger message sign including `eth_sign`, `personal_sign`, `eth_signTypedDataV1` to V4 all break, this PR include fix from above operation.

following tasks have been done:
1. add two missing patch files in current branch but exists in `main` branch (`patches/@metamask+signature-controller++@metamask+message-manager+7.0.1.patch`, `patches/@metamask+signature-controller+4.0.1.patch`)
2. add `signMessage` actions and reducer to track the difference stage of sign message flow.
3. modify `LedgerMessageSignModal.tsx` to subscribe the `signMssageStage` in redux store. to perform dismissModal. 
4. refactory the RPCMethodMiddleware relative sign code to use common handle function `handleCommonSignFlow`
5. fix the code errors in MessageSIgn.tsx and PersonalSign.tsx fils for navigation.

**Caution** unit tests for testing reducer and RPCMethodMiddleware.ts will be done in another unit test branch.

2023-09-08 02:52 UTC, stanleyyconsensys requested changes

2023-09-08 02:52 UTC, stanleyyconsensys commented on app/components/UI/LedgerModals/LedgerMessageSignModal.tsx
>      onConfirmationComplete(true, rawSignature);
shall we update onConfirmationComplete, as rawSignature will be undefined anyway

2023-09-08 02:52 UTC, stanleyyconsensys commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +    console.error(e);
console.error may needed to remove?

2023-09-08 02:52 UTC, stanleyyconsensys commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> -          res.result = AppConstants.ETH_SIGN_ERROR;
it look like ur generic method doesnt handle this

why not just have a try catch on the req method, hence to leave everything not change , doesnt it more easy ? as the logic will update in future too

2023-09-08 02:52 UTC, stanleyyconsensys commented on app/components/UI/SignatureRequest/types.ts
> +  metamaskId?: string;
what is the reason to change to optional?

2023-09-08 02:52 UTC, stanleyyconsensys commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +    messageParams: MessageParams,
for the type , you can refer to sign controller

2023-09-08 02:54 UTC, dawnseeker8 commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +    console.error(e);
will remove later.

2023-09-08 02:58 UTC, stanleyyconsensys commented on app/components/UI/LedgerModals/LedgerMessageSignModal.tsx
> +    ) {
when we on unmount, shall we dismiss modal too?

2023-09-08 03:07 UTC, dawnseeker8 commented on app/components/UI/SignatureRequest/types.ts
> +  metamaskId?: string;
The reason is metamaskId is mandatory defined in params in `SignatureController.newUnsign<>Message(messageParam)`, if you look at `RPCMethodMiddleware.ts` file for difference sign method, the params inside signMsgCallback may not include metamaskId, that is why i define it optional, however, the best way is getting the param types directly from @Metamask-SignatureController, but our library version didnt export the type, and i saw you already define a duplicate one in this file, i just directly use it to solve the tsc error.

2023-09-08 03:11 UTC, dawnseeker8 commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +    messageParams: MessageParams,
I check the @Metamask-SignatureController library,  the current version didnt export the types including `MessageParams` and `OriginalRequest` , the only way is upgrade or downgrade library, i saw you already use the `MessageParams` in `SignatureRequest/types.ts`, that is why i directly modify there, and add a `OriginalRequest` type there.

2023-09-08 03:18 UTC, dawnseeker8 commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> -          res.result = AppConstants.ETH_SIGN_ERROR;
Sorry, my mistake to remove the `} else {` probably from copy and parse the code.  anyway, my generic method will  only process the signing bit, so after i add the `} else {` the `eth_sign` will still work, the code will change as following
```Typescript
     if (req.params[1].length === 66 || req.params[1].length === 67) {
          await checkActiveAccountAndChainId({
            hostname,
            address: req.params[0].from,
            checkSelectedAddress: isMMSDK || isWalletConnect,
          });
          const signMessageFunc = SignatureController.newUnsignedMessage({
            data: req.params[1],
            from: req.params[0],
            ...pageMeta,
            origin: hostname,
          });

          res.result = await handleCommonSignFlow(signMessageFunc);
        } else {
          res.result = AppConstants.ETH_SIGN_ERROR;
          throw ethErrors.rpc.invalidParams(AppConstants.ETH_SIGN_ERROR);
        }
      ```

2023-09-08 03:21 UTC, stanleyyconsensys commented on app/components/UI/SignatureRequest/types.ts
> +  metamaskId?: string;
i see, the type for MessageParams original was not used for RPCMethodMiddleware, but for approval request
until we move the sign function as a callback in RPCMethodMiddleware and then you have to define the type to bypass the type error

got it, but if we dont use that way (move the sign function as a callback) on RPCMethodMiddleware , just rmb to roll it back, thx

2023-09-08 03:23 UTC, stanleyyconsensys commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +    messageParams: MessageParams,
they did export , as they import from metamask/message-manager

import type {
  MessageParams,
  MessageParamsMetamask,
  PersonalMessageParams,
  PersonalMessageParamsMetamask,
  TypedMessageParams,
  TypedMessageParamsMetamask,
  AbstractMessageManager,
  AbstractMessage,
  MessageManagerState,
  AbstractMessageParams,
  AbstractMessageParamsMetamask,
  OriginalRequest,
  TypedMessage,
  PersonalMessage,
  Message,
} from '@metamask/message-manager';

2023-09-08 03:24 UTC, dawnseeker8 commented on app/components/UI/LedgerModals/LedgerMessageSignModal.tsx
>      onConfirmationComplete(true, rawSignature);
i see the original code implemented by Zoltan, the rawSignature is optioinal in onConfirmationComplete(), let me test deviices when removing `rawSignature` in that method, see any unexpected behaviour or not.

2023-09-08 05:07 UTC, dawnseeker8 commented on app/components/UI/LedgerModals/LedgerMessageSignModal.tsx
> +    ) {
dismissModal wiill run first before unmounted,  so we dont need to handle dismissModal again here in unmounted callback

2023-09-08 05:16 UTC, stanleyyconsensys commented on app/components/UI/LedgerModals/LedgerMessageSignModal.tsx
>      onConfirmationComplete(true, rawSignature);
onConfirmationComplete is passed by app/util/hardwareWallet/signatureUtils.ts, and since we no longer has rawSignature until keyring signed, hence, i think we dont need it anymore, you can double check

2023-09-08 05:31 UTC, dawnseeker8 commented on app/components/UI/LedgerModals/LedgerMessageSignModal.tsx
>      onConfirmationComplete(true, rawSignature);
i have checked remove rawSignature and change to use `onComfirmationComplete(true)` and it still work as expected, so i have removed the rawSignature in above code.

2023-09-08 08:08 UTC, stanleyyconsensys commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +        store.dispatch(setSignMessageStage(SignMessageStageTypes.REQUEST_SEND));
do you wanna change the reducer name and action name to more general purpose as we discussed? or you prefer stay with explicitly name for sign message

2023-09-08 08:13 UTC, dawnseeker8 commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +        store.dispatch(setSignMessageStage(SignMessageStageTypes.REQUEST_SEND));
last commit is to make a backup of workable version for further change, as i mention in the commit comment, further reducer change will be carried out later.

2023-09-11 04:52 UTC, stanleyyconsensys approved these changes

2023-09-11 06:37 UTC, merged