Update build quote page to use hooks instead of local state
MetaMask/metamask-mobile pull request #7227
Opened 2023-09-14 20:56 UTC by georgeweiler

**Development & PR Process**
1. Follow MetaMask [Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/coding_guidelines/CODING_GUIDELINES.md)
2. Add `release-xx` label to identify the PR slated for a upcoming release (will be used in release discussion)
3. Add `needs-dev-review` label when work is completed
4. Add the appropiate QA label when dev review is completed
    - `needs-qa`: PR requires manual QA.
    - `No QA/E2E only`: PR does not require any manual QA effort. Prior to merging, ensure that you have successful end-to-end test runs in Bitrise. 
    - `Spot check on release build`: PR does not require feature QA but needs non-automated verification. In the description section, provide test scenarios. Add screenshots, and or recordings of what was tested.
5. Add `QA Passed` label when QA has signed off (Only required if the PR was labeled with `needs-qa`)
6. Add your team's label, i.e. label starting with `team-` (or `external-contributor` label if your not a MetaMask employee)

**Description**

_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions,_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

**Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change_

**Issue**

fixes #???

**Checklist**

* [ ] There is a related GitHub issue
* [ ] Tests are included if applicable
* [ ] Any added code is fully documented

2023-09-14 20:57 UTC, georgeweiler commented
I have read the CLA Document and I hereby sign the CLA

2023-09-25 19:26 UTC, wachunei commented on app/components/UI/Ramp/buy/hooks/useCryptoCurrencies.ts
> +  }, [errorCryptoCurrencies, isFetchingCryptoCurrencies, sdkCryptoCurrencies]);
Please add `selectedChainId` to the array as well.

2023-09-25 19:45 UTC, wachunei requested changes
One small no-impact change requested.

2023-09-25 19:45 UTC, wachunei commented on app/components/UI/Ramp/buy/hooks/useCryptoCurrencies.ts
> +  }, [errorCryptoCurrencies, isFetchingCryptoCurrencies, sdkCryptoCurrencies]);
.

2023-09-26 00:38 UTC, georgeweiler commented on app/components/UI/Ramp/buy/hooks/useCryptoCurrencies.ts
> +  }, [errorCryptoCurrencies, isFetchingCryptoCurrencies, sdkCryptoCurrencies]);
fixed https://github.com/MetaMask/metamask-mobile/pull/7227/commits/4cb71a1b41878ecbb92a0002dbe1b9a9da8e84fe

2023-09-26 13:56 UTC, wachunei requested changes

2023-09-26 13:56 UTC, wachunei commented on app/components/UI/Ramp/buy/Views/PaymentMethods/PaymentMethods.test.tsx
> +import { createAmountToBuyNavDetails } from '../BuildQuote/BuildQuote';
Oh we missed this, `createAmountToBuyNavDetails` must be renamed to `createBuildQuoteNavDetails` and imported from index file instead, as before. `AmountToBuyParams` has to be renamed as well.

2023-09-26 13:56 UTC, wachunei commented on app/components/UI/Ramp/buy/Views/PaymentMethods/PaymentMethods.tsx
> +import { createAmountToBuyNavDetails } from '../BuildQuote/BuildQuote';
Same comment from the test file

2023-09-26 13:56 UTC, wachunei commented on app/components/UI/Ramp/buy/hooks/useCryptoCurrencies.ts
> +import { NATIVE_ADDRESS } from '../../../../../constants/on-ramp';
nit: sort imports placing relative imports last
```suggestion
import { useEffect, useMemo } from 'react';
import useSDKMethod from '../../common/hooks/useSDKMethod';
import { useRampSDK } from '../../common/sdk';
import { NATIVE_ADDRESS } from '../../../../../constants/on-ramp';```

2023-09-26 13:56 UTC, wachunei commented on app/components/UI/Ramp/buy/hooks/useFiatCurrencies.ts
> +import { useEffect, useMemo } from 'react';
nit. Same as other hook
```suggestion
import { useEffect, useMemo } from 'react';
import useSDKMethod from '../../common/hooks/useSDKMethod';
import { useRampSDK } from '../../common/sdk';
```

2023-09-26 19:26 UTC, wachunei approved these changes

2023-09-28 14:56 UTC, sethkfman commented on app/components/UI/Ramp/buy/hooks/useCryptoCurrencies.ts
> +  const cryptoCurrencies = useMemo(() => {
Could you add tests for all of the new files in hooks?

2023-09-28 16:58 UTC, wachunei commented on app/components/UI/Ramp/buy/hooks/useCryptoCurrencies.ts
> +  const cryptoCurrencies = useMemo(() => {
Hey @sethkfman, thank you for the review.

We have planned to add hooks' test at the end of the feature development process, since this is pointing to a feature branch https://github.com/MetaMask/metamask-mobile/pull/7037.

However you're raising a very good point, we skipped the views test for this change, we will add them just like the almost all the others views ([Get Started](https://github.com/MetaMask/metamask-mobile/blob/feat/off-ramp-build-quote-view/app/components/UI/Ramp/buy/Views/GetStarted/GetStarted.test.tsx), [Payment Methods](https://github.com/MetaMask/metamask-mobile/blob/feat/off-ramp-build-quote-view/app/components/UI/Ramp/buy/Views/PaymentMethods/PaymentMethods.test.tsx), [Region](https://github.com/MetaMask/metamask-mobile/blob/feat/off-ramp-build-quote-view/app/components/UI/Ramp/buy/Views/Regions/Regions.test.tsx), [Quotes](https://github.com/MetaMask/metamask-mobile/blob/feat/off-ramp-build-quote-view/app/components/UI/Ramp/buy/Views/Quotes/Quotes.test.tsx)) and ask for review again.

2023-09-28 17:15 UTC, georgeweiler commented on app/components/UI/Ramp/buy/hooks/useCryptoCurrencies.ts
> +  const cryptoCurrencies = useMemo(() => {
+1. We are planning to change these hooks to support buy and sell very soon in a future PR that will be pointed at feature branch #7037. It makes more sense to write tests for them only once they are in their "final state".

2023-10-02 22:51 UTC, georgeweiler commented on app/components/UI/Ramp/buy/hooks/useCryptoCurrencies.ts
> +  const cryptoCurrencies = useMemo(() => {
added a test here: https://github.com/MetaMask/metamask-mobile/pull/7227/commits/9a706e89f8e82b58795015e0598ca91292693053

2023-10-03 16:44 UTC, wachunei commented on app/components/UI/Ramp/buy/Views/BuildQuote/BuildQuote.test.tsx
> +    expect(mockNavigate).toHaveBeenCalledWith('Quotes', {
Please change `'Quotes'`  with the Routes const, will help us with the next navigation refactor

2023-10-03 16:46 UTC, wachunei commented on app/components/UI/Ramp/common/Views/Settings/AddActivationKey.tsx
> -
Please dismiss these changes
```git checkout feat/off-ramp -- app/components/UI/Ramp/common/Views/Settings/AddActivationKey.tsx```

2023-10-03 17:06 UTC, georgeweiler commented on app/components/UI/Ramp/common/Views/Settings/AddActivationKey.tsx
> -
https://github.com/MetaMask/metamask-mobile/pull/7227/commits/c0485c73223e61feda3feed3c57bc078efee7813

2023-10-03 19:19 UTC, wachunei approved these changes

2023-10-03 19:37 UTC, merged

2023-11-03 16:09 UTC, MarioAslau reviewed
Looks good!