Feat: add ledger error nonce too low
MetaMask/metamask-mobile pull request #7279
Opened 2023-09-20 19:40 UTC by igorms-cons

## **Description**

The error occurred during a transaction from a Ledger account to a normal account, after we manually decreased the nonce value on the confirmation page.

1. pair ledger with imported SRP (secret recovery phrase) on MMM
2. turn on custom nonce in MMM settings>advanced
3. tap send from wallet view
4. transfer within your accounts
5. on confirmation, reduce nonce value by 2
6. confirm- approve on Ledger

Expected:- Error displays 'Nonce value too low' 

## **FIx**

We need to: 

**`app/components/hooks/useLedgerBluetooth.tsx`**
- Add a new value to LedgerCommunicationErrors.
- Inside the catch block of the processLedgerWorkflow function, add a condition to set the error to the newly created one.

**`app/components/UI/LedgerModals/LedgerConfirmationModal.tsx`**
- Set error details with a dedicated title and subtitle, previously added in local languages.

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained:
  - [ ] What problem this PR is solving.
  - [ ] How this problem was solved.
  - [ ] How reviewers can test my changes.
- [ ] I’ve indicated what issue this PR is linked to: Fixes #???
- [ ] I’ve included tests if applicable.
- [ ] I’ve documented any added code.
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-09-20 19:42 UTC, igorms-cons commented
![Screenshot_2023-09-20-21-26-22-693_io metamask](https://github.com/MetaMask/metamask-mobile/assets/89637087/fd927cfd-e5c7-4065-904a-f7fd5b3eba6e)

2023-09-21 07:47 UTC, igorms-cons commented
I have read the CLA Document and I hereby sign the CLA

2023-09-21 07:49 UTC, Akaryatrh approved these changes

2023-09-21 09:09 UTC, dawnseeker8 approved these changes

2023-09-21 09:36 UTC, stanleyyconsensys requested changes

2023-09-21 09:36 UTC, stanleyyconsensys commented on locales/languages/en.json
> +    "nonce_too_low_nonce": "The set nonce  is too low"
1. remove extra space `nonce  is`
2. update error message key to  from nonce_too_low_nonce to nonce_too_low_error

2023-09-21 09:36 UTC, stanleyyconsensys commented on app/components/UI/LedgerModals/LedgerConfirmationModal.tsx
> +            isRetry={ledgerError !== LedgerCommunicationErrors.NonceTooLow}
do we wanna to take care other exceptions case
e.g not allow to retry when:
- NonceTooLow, 
- any transaction error => UnknownError
- NotSupported

or we can do it in other way, to allow retry in some action
e.g any ledger connect error

2023-09-21 16:01 UTC, igorms-cons commented on app/components/UI/LedgerModals/LedgerConfirmationModal.tsx
> +            isRetryHide={
had to do like that because I got `This comparison appears to be unintentional because the types 'X' and 'Y' have no overlap` with `!==`

2023-09-23 08:44 UTC, stanleyyconsensys approved these changes

2023-09-25 05:01 UTC, merged