refactor: Convert List stories to csf format
MetaMask/metamask-mobile pull request #7414
Opened 2023-10-08 00:42 UTC by brianacnguyen

## **Description**
- Converted List stories to csf format

## **Screenshots/Recordings**
![Simulator Screen Shot - iPhone 14 Pro - 2023-10-07 at 17 37 58](https://github.com/MetaMask/metamask-mobile/assets/14355083/f06130fb-47f9-40a3-971a-50d045d2284f)
![Simulator Screen Shot - iPhone 14 Pro - 2023-10-07 at 17 38 00](https://github.com/MetaMask/metamask-mobile/assets/14355083/5bab67dd-f591-466b-bcd7-83df533fb2e1)
![Simulator Screen Shot - iPhone 14 Pro - 2023-10-07 at 17 38 02](https://github.com/MetaMask/metamask-mobile/assets/14355083/130c5307-81a0-4d57-a0d4-f08673005c0a)

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained:
  - [ ] What problem this PR is solving.
  - [ ] How this problem was solved.
  - [ ] How reviewers can test my changes.
- [ ] I’ve indicated what issue this PR is linked to: Fixes #???
- [ ] I’ve included tests if applicable.
- [ ] I’ve documented any added code.
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-10-24 19:37 UTC, georgewrmarshall approved these changes, later dismissed
LGTM!
- pulled branch checked stories and controls

2023-10-24 19:37 UTC, georgewrmarshall commented on .storybook/main.js
> +    '../app/component-library/components/List/**/*.stories.?(ts|tsx|js|jsx)',
Can we update this folder path so it's less specific and doesn't create merge conflicts every time a story is created?

```
stories: [
    '../app/components/**/*.stories.?(ts|tsx)',
    '../app/component-library/**/*.stories.?(ts|tsx)',
  ],
```

2023-10-24 19:37 UTC, georgewrmarshall commented on app/component-library/components/List/ListItem/ListItem.stories.tsx
> +    },
non-blocking: Could add `children` as a text arg

2023-10-25 17:27 UTC, georgewrmarshall commented on .storybook/main.js
> +    '../app/component-library/components/List/**/*.stories.?(ts|tsx|js|jsx)',
As @brianacnguyen pointed out. Storybook always will create conflicts with the `.storybook/storybook.requires.js` file anyway

2023-10-25 18:37 UTC, brianacnguyen commented on app/component-library/components/List/ListItem/ListItem.stories.tsx
> +    },
> non-blocking: Could add `children` as a text arg

Then it would override a more complicated example, which I think is more beneficial to show imo

2023-10-25 18:38 UTC, georgewrmarshall commented on index.js
> +// AppRegistry.registerComponent(name, () => Sentry.wrap(Root));
Revert the changes to this file

2023-10-25 18:39 UTC, georgewrmarshall requested changes
Remove changes from index.js

2023-10-25 18:45 UTC, brianacnguyen commented on index.js
> +// AppRegistry.registerComponent(name, () => Sentry.wrap(Root));
woops

2023-10-25 18:47 UTC, georgewrmarshall approved these changes

2023-10-25 19:04 UTC, merged