Fix/1273 duplicate contact addresses
MetaMask/metamask-mobile pull request #7482
Opened 2023-10-12 04:28 UTC by frankvonhoven

## **Description**
_Write a short description of the changes included in this pull request, also include relevant motivation and context. Have in mind the following questions:_
_1. What is the reason for the change?_
_2. What is the improvement/solution?_

## **Manual testing steps**

_1. Step1:_
_2. Step2:_
_3. ..._

## **Screenshots/Recordings**

_If applicable, add screenshots and/or recordings to visualize the before and after of your change._

### **Before**

_[screenshot]_

### **After**

_[screenshot]_

## **Related issues**

_Fixes #???_

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained:
  - [ ] What problem this PR is solving.
  - [ ] How this problem was solved.
  - [ ] How reviewers can test my changes.
- [ ] I’ve indicated what issue this PR is linked to: Fixes #???
- [ ] I’ve included tests if applicable.
- [ ] I’ve documented any added code.
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-10-16 21:56 UTC, tommasini requested changes
Hey @frankvonhoven amazing work!

Left some comment, let me know your thoughts!!

Also, it seems that it is some UI issues on the warning on the SendTo screen? Comparatively to the other, at least doesn't seem right the margin between the two warnings for me 
![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/fc85aa22-e233-4711-9635-5de49109b7bf)

2023-10-16 21:56 UTC, tommasini commented on app/components/Views/Settings/Contacts/AmbiguousAddressSheet/AmbiguousAddressSheet.tsx
> +      <View style={styles.container}>
Did you try to use <SheetHeader component here?

2023-10-16 21:56 UTC, tommasini commented on app/components/Views/Settings/Contacts/AmbiguousAddressSheet/AmbiguousAddressSheet.tsx
> +// Third party dependencies.
Can we add a test file with a snapshot of this component?

2023-10-16 21:56 UTC, tommasini commented on app/components/Views/Settings/Contacts/index.js
> +import Routes from '../../../../../app/constants/navigation/Routes';
Since we are adding a new CTA to this component, do you think it could be a good opportunity to refactor it and convert it to typescript? Also convert it into a functional component and add testing to the new CTA?

2023-10-16 21:56 UTC, tommasini commented on app/components/Views/SendFlow/SendTo/index.js
> +    const currentChain = this.props.ambiguousAddressEntries[this.props.chainId];
Could we change `currentChain` for something for example `correntChainAddresses` or something more reliable, I feel that currentChain is not an accurate variable name for this purpose, wdyt?

2023-10-17 19:33 UTC, frankvonhoven commented on app/components/Views/Settings/Contacts/index.js
> +import Routes from '../../../../../app/constants/navigation/Routes';
That could be done, however, I'm not sure if we want to add more development time to this issue since it is a sev1?

2023-10-17 19:37 UTC, frankvonhoven commented on app/components/Views/SendFlow/SendTo/index.js
> +    const currentChain = this.props.ambiguousAddressEntries[this.props.chainId];
`currentChain` means the currently selected chain, I don't think it is possible to know the correct chain id for the ambiguous address. This gets the list of ambiguous addresses by the current chain id... so maybe something like `currentChainAmbiguousAddresses`?

2023-10-17 19:39 UTC, frankvonhoven commented
re: the warning message spacing... I did notice that but didn't know if it would be a real use case, since a user probably wouldn't want to send funds without having any funds. But perhaps I could refactor the warning component to only have a top margin?

2023-10-17 23:43 UTC, cortisiko commented
@frankvonhoven can you test this in dark mode as well? The caution icons look a bit dark and it would be interesting to see if it is visible in dark mode. 


Can you confirm that the translations are in for this feature? Confirm by showing recordings of the translated text for the new this is a ambitious address sheet

2023-10-18 22:31 UTC, frankvonhoven commented
@cortisiko 
* The caution icons in dark mode.
A: Updated screenshots in PR description

* Translations in for this feature
A: Translations completed
  - **Waiting on confirmation for translation integration into `main`**

* Analytic events appearing correctly
  - ![image](https://github.com/MetaMask/metamask-mobile/assets/141057783/61a3e331-9207-4eb4-b9fc-0d7bea7a8148)

2023-10-19 23:14 UTC, frankvonhoven commented
@cortisiko with translations in I checked the modal in German and copied the string 3x to test long translations:
![Screenshot 2023-10-19 at 6 13 46 PM](https://github.com/MetaMask/metamask-mobile/assets/141057783/fc71eafb-da69-4813-a24e-ae08e6a38862)

2023-10-20 18:26 UTC, frankvonhoven commented
@tommasini I fixed the padding for the warning component
![Simulator Screen Shot - iPhone 14 - 2023-10-20 at 13 25 04](https://github.com/MetaMask/metamask-mobile/assets/141057783/4b81a531-5dc6-4b20-8cdf-38c72983ff74)

2023-10-23 18:55 UTC, sethkfman approved these changes
LGTM

2023-10-23 20:38 UTC, tommasini approved these changes
LGTM!

2023-10-23 20:39 UTC, tommasini commented on app/components/Views/SendFlow/SendTo/index.js
> +    const currentChain = this.props.ambiguousAddressEntries[this.props.chainId];
`currentChainAmbiguousAddresses` -> You are right this would be perfect I believe!

2023-10-23 20:40 UTC, tommasini commented on app/components/Views/Settings/Contacts/index.js
> +import Routes from '../../../../../app/constants/navigation/Routes';
I think we have sometime if this is pointed to release 7.11.0, or it will enter on 7.10?

2023-10-23 20:59 UTC, merged