feat: hide alert when navigating to protect wallet
MetaMask/metamask-mobile pull request #7534
Opened 2023-10-18 10:40 UTC by tommasini

**Description**

This PR aims to solve a bug on the backup alert, when navigating to the protect your wallet screen the alert kept being visible.

This PR still needs unit test coverage and recordings to be completed.

## **Manual testing steps**

_1. Step1: Create a new wallet
_2. Step2: Do not protect your wallet pressing (remember later)
_3. Step3: Press protect your wallet on the backup alert
_4. Step4: The protect your wallet should not be there

## **Screenshots/Recordings**
Need recordings

### **Before**

_[screenshot]_

### **After**

_[screenshot]_

## **Related issues**

_Fixes #4400 

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained:
  - [ ] What problem this PR is solving.
  - [ ] How this problem was solved.
  - [ ] How reviewers can test my changes.
- [ ] I’ve indicated what issue this PR is linked to: Fixes #???
- [ ] I’ve included tests if applicable.
- [ ] I’ve documented any added code.
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-01-10 22:29 UTC, plasmacorral commented
Had a chance to take a quick look here and am confident that this addresses the issue reported.  Specifically, tested with the SRP backup demand flow and was pleased with the result.  

Tested commit 55d3aee20d1eab692324a72b31b89aab87ba9956 on Samsung a515f with Android 12.

Manual testing steps for SRP backup demand
1. Create a new wallet
2. Do not protect your wallet pressing (remember later)
3. Import a PK for an account with assets present to trigger backup demand
4. App is unusable for anything but SRP backup
5. Warning is also not presented overtop the SRP backup flow in this condition

2024-01-25 15:15 UTC, jpcloureiro requested changes

2024-01-25 15:15 UTC, jpcloureiro commented on app/components/UI/BackupAlert/BackupAlert.styles.ts
> + * Style sheet function for ModalConfirmation component.
update header comment
```suggestion
 * Style sheet function for BackupAlert component.
```

2024-01-25 15:15 UTC, jpcloureiro commented on app/components/UI/BackupAlert/BackupAlert.styles.ts
> + * @param params.vars Inputs that the style sheet depends on.
We're not using `params.vars` we can remove this line

2024-01-25 15:15 UTC, jpcloureiro commented on app/components/UI/BackupAlert/BackupAlert.tsx
> +  return (
```suggestion
  return shouldNotRenderAlert ? null
  : (
```

2024-01-25 15:15 UTC, jpcloureiro commented on app/components/UI/BackupAlert/BackupAlert.tsx
> +            {/* We need a icon on our component library to use icon component*/}
Is this comment converted into a ticket to create the icon component?

2024-01-25 22:24 UTC, tommasini commented on app/components/UI/BackupAlert/BackupAlert.tsx
> +            {/* We need a icon on our component library to use icon component*/}
It was not!!
[Created](https://github.com/MetaMask/metamask-mobile/issues/8406) and sent to the design systems team!
Amazing call!

2024-01-25 22:25 UTC, tommasini commented on app/components/UI/BackupAlert/BackupAlert.tsx
> +  return (
Addressed!

2024-01-25 22:25 UTC, tommasini commented on app/components/UI/BackupAlert/BackupAlert.styles.ts
> + * @param params.vars Inputs that the style sheet depends on.
Removed!

2024-01-25 22:25 UTC, tommasini commented on app/components/UI/BackupAlert/BackupAlert.styles.ts
> + * Style sheet function for ModalConfirmation component.
Thanks for the review <3

updated!

2024-01-25 22:44 UTC, tommasini commented
Actually there is a new Bell Icon already, will ask for design-qa, updated the final result on the description

2024-01-29 22:14 UTC, yanrong-chen commented
@tommasini Looks good to me for now! Thank you for checking with me. Later we can also update this to use our DS [banner alert](https://www.figma.com/file/HKpPKij9V3TpsyMV1TpV7C/DS-Components?type=design&node-id=5711-16548&mode=design&t=yw3OUBHPHwp8zBOI-0) component

2024-01-30 14:42 UTC, MarioAslau approved these changes
Codewise it looks great Tomas! I dm'd you a couple of questions regarding the context of some choices

2024-02-02 17:00 UTC, jpcloureiro approved these changes
LGTM

2024-02-05 12:27 UTC, merged