Refactor/6887 text comp replacement
MetaMask/metamask-mobile pull request #7565
Opened 2023-10-23 11:54 UTC by Jonathansoufer

## **Description**
This PR replaces old usage of legacy <Text> component with the new one available from our `component-library`. This will bring uniformity to all text elements on our app.

## **Manual testing steps**
- From the main screen, click on any asset available to go to Asset Detail.
- Make sure  you have no balance on the chosen asset [Specific for testing Warning Message Text].
- Review Button's Texts.

## **Screenshots/Recordings**

### **Before**
![Screenshot 2023-10-20 at 14 54 13](https://github.com/MetaMask/metamask-mobile/assets/44679989/75ab745a-1539-43fe-890e-dfc24145e42d)
![Simulator Screen Shot - iPhone 12 Pro - 2023-10-23 at 12 17 49](https://github.com/MetaMask/metamask-mobile/assets/44679989/46085891-262f-42b9-8b65-2eb42b7489c8)

### **After**
![Screenshot 2023-10-20 at 15 07 52](https://github.com/MetaMask/metamask-mobile/assets/44679989/da4bf332-f009-49fc-aa1c-cccf921aede1)
![Simulator Screen Shot - iPhone 12 Pro - 2023-10-23 at 12 27 21](https://github.com/MetaMask/metamask-mobile/assets/44679989/daae33d8-b229-4cc6-bd05-36d989567283)

## **Related issues**

This is **part** of ongoing tasks related to issue #6887

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained:
  - [x] What problem this PR is solving.
  - [x] How this problem was solved.
  - [x] How reviewers can test my changes.
- [x] I’ve indicated what issue this PR is linked to: Fixes #???
- [x] I’ve included tests if applicable.
- [x] I’ve documented any added code.
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)).
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-10-23 21:13 UTC, owencraston commented on app/components/UI/AssetOverview/AssetActionButton/AssetActionButton.tsx
> +          variant={TextVariant.BodyMD}
The default value for variant is already `TextVariant.BodyMD` so I do not think you need to pass those values in here.

2023-10-23 21:18 UTC, owencraston commented on app/components/UI/AssetOverview/AssetActionButton/AssetActionButton.tsx
> +          style={styles.buttonText}
I looked through the styles that are passed here and I think we could clean it up a tad. 
This is how the button styles are defined

```
    buttonText: {
      marginTop: 8,
      marginHorizontal: 3,
      color: colors.primary.default,
      fontSize: 14,
    },
```

I think a better pattern for passing color to the Text component would be to use the `color` prop. That way we can migrate all the Text components to use "valid" [TextColor values](https://github.com/MetaMask/metamask-mobile/blob/664977cf0ce1b2e99cd4bfe10134f7193bdf5697/app/component-library/components/Texts/Text/Text.types.ts#L24-L25). In this case I would remove the color from buttonText and pass it in as `color={TextColor.Primary}`

2023-10-23 21:21 UTC, owencraston commented on app/components/UI/AssetOverview/AssetActionButton/AssetActionButton.tsx
> +          style={styles.buttonText}
I am wondering now is the `TextColor.Inverse` will be the same as `colors.primary.default`. @brianacnguyen is this valid?

2023-10-23 21:32 UTC, owencraston commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +        <Text variant={TextVariant.BodyMD} style={styles.warning}>
Again, I don't think the variant is needed here since it is using the default value.

2023-10-23 21:38 UTC, owencraston commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +        <Text variant={TextVariant.BodyMD} style={styles.warning}>
I am looking at the warning styles and they are defined as follows
```
    warning: {
      ...typography.sBodyMD,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.warning.default,
      backgroundColor: colors.warning.muted,
      padding: 20,
    } as TextStyle,
    warningLinks: {
      ...typography.sBodyMD,
      color: colors.primary.default,
    } as TextStyle,
    ```
This indicates a few things to me. It seems that the style is setting the variant to use `sBodyMD`. In my opinion we should remove this from the styles and just set that as the variant through the props. I also find it very weird that we are using this Text component to render the warning banner and passing the colours in through styles but that is propably out of scope for this change.

2023-10-23 21:38 UTC, owencraston commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +          <Text variant={TextVariant.BodyMD} style={styles.warningLinks}>
same comment as above ^.

2023-10-23 21:41 UTC, owencraston commented on app/components/UI/AssetOverview/Balance/Balance.tsx
> +      <Text variant={TextVariant.BodyMD} style={styles.text}>
text styles are defined as follows

```
    text: {
      ...typography.sBodySM,
      marginVertical: 0,
    } as TextStyle,
```

Given this lets remove that style from the `Balance.styles.ts` file  and pass in `sBodySM` as the variant so we don't override that variant.

2023-10-23 21:41 UTC, owencraston commented on app/components/UI/AssetOverview/Balance/Balance.tsx
> +      <Text variant={TextVariant.BodyMD} style={styles.text}>
same as above.

2023-10-24 10:57 UTC, Jonathansoufer commented on app/components/UI/AssetOverview/AssetActionButton/AssetActionButton.tsx
> +          variant={TextVariant.BodyMD}
Got u. Fixed.

2023-10-24 10:57 UTC, Jonathansoufer commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +          <Text variant={TextVariant.BodyMD} style={styles.warningLinks}>
Fixed already.

2023-10-24 10:57 UTC, Jonathansoufer commented on app/components/UI/AssetOverview/Balance/Balance.tsx
> +      <Text variant={TextVariant.BodyMD} style={styles.text}>
Fixed already.

2023-10-24 11:37 UTC, Jonathansoufer commented on app/components/UI/AssetOverview/AssetActionButton/AssetActionButton.tsx
> +          style={styles.buttonText}
Did some clean up already removing props that are now present on the `TextVariant `. Just for the sake of registering here. Checking `design-tokens` repository I see that `TextColor.Inverse` is set to `#FCFCFC` and `colors.primary.default = #0376C9` thus not being the best replacement. Based on the following from `app/component-library/components/Texts/Text/Text.styles.ts` the best replacement in this case would be `TextColor.Primary`.

```
    case TextColor.Primary:
      textColor = theme.colors.primary.default;
      break;
```

2023-10-24 11:54 UTC, Jonathansoufer commented on app/components/UI/AssetOverview/AssetOverview.tsx
> +        <Text variant={TextVariant.BodyMD} style={styles.warning}>
Removed unnecessary style attrs and added color as direct prop.

2023-10-24 11:58 UTC, Jonathansoufer commented on app/components/UI/AssetOverview/Balance/Balance.tsx
> +      <Text variant={TextVariant.BodyMD} style={styles.text}>
Thanks, but in this case `sBodySM` is the default variant thus there's no need to pass it.

2023-10-24 18:04 UTC, owencraston submitted a review, later dismissed

2023-10-26 08:33 UTC, brianacnguyen requested changes

2023-10-26 08:33 UTC, brianacnguyen commented on app/components/UI/AssetOverview/Balance/Balance.tsx
>  import styleSheet from './Balance.styles';
shouldnt the text variant be BodySM since the Text default is BodyMD?

2023-10-26 14:58 UTC, Jonathansoufer commented on app/components/UI/AssetOverview/Balance/Balance.tsx
>  import styleSheet from './Balance.styles';
You're write. fixed.

2023-10-27 21:55 UTC, owencraston approved these changes

2024-02-01 23:31 UTC, closed without merging