feat: sdk batch rpc calls
MetaMask/metamask-mobile pull request #7628
Opened 2023-10-27 05:23 UTC by abretonc7s

## **Description**

Allow dapp developers to create sequences of RPC method calls that are sent simultaneously and managed by the MM mobile app using the existing RPC queue.

Chained RPC Calls:

Implement the ability for the SDK to handle sequences of RPC method calls.
Address known issues in the RPC queue, especially when one of the methods fails.

## **Related issues**

[Fixes: #
](https://github.com/MetaMask/metamask-sdk/issues/391)

## **Manual testing steps**

1. Use a dapp using metamask/sdk and call the following:
```
    const selectedAddress = provider?.selectedAddress;

    const rpcs: ChainRPC[] = [{
      method: "personal_sign",
      params: ["something to sign 1", selectedAddress],
    },
    {
      method: "personal_sign",
      params: ["hello world", selectedAddress],
    },
    {
      method: "personal_sign",
      params: ["Another one #3", selectedAddress],
    }];

    try {
      const response = await provider?.request({method: 'metamask_batch', params: rpcs}) as any[];
      ...
```

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-10-27 07:11 UTC, omridan159 commented on app/core/SDKConnect/BatchRPCManager.ts
> +  getId(id: string) {
```suggestion
  getRpcStateById(id: string) {
```
WDYT?

2023-10-27 07:15 UTC, omridan159 commented on app/core/SDKConnect/BatchRPCManager.ts
> +}
```suggestion
interface RPCMethod<TParams = any, TResponse = any> {  id: string;
  method: string;
  params: TParams;
  jsonrpc: string;
  response?: TResponse;
}
```
WDYT?

2023-10-27 07:16 UTC, omridan159 commented on app/core/SDKConnect/Connection.ts
> +              Array.isArray(message?.params) &&
```suggestion
              Array.isArray(message.params) &&
```

2023-10-27 07:17 UTC, omridan159 commented on app/core/SDKConnect/Connection.ts
> +              Array.isArray(message?.params) &&
Redundant Null Check

2023-10-27 07:19 UTC, omridan159 commented on app/core/SDKConnect/Connection.ts
> +        if (message.method === 'metamask_batch') {
It might be a good idea to put all the method types in a const

2023-10-27 07:21 UTC, omridan159 requested changes
.

2023-10-27 07:46 UTC, omridan159 submitted a review, later dismissed

2023-10-27 07:49 UTC, omridan159 approved these changes, later dismissed

2023-10-27 07:49 UTC, abretonc7s commented on app/core/SDKConnect/BatchRPCManager.ts
> +}
used unknown

2023-10-27 08:12 UTC, andreahaku submitted a review, later dismissed
LGTM

2023-11-03 10:36 UTC, andreahaku approved these changes
LGTM

2023-11-03 12:47 UTC, merged