WIP:  Feat/offramp analytics
MetaMask/metamask-mobile pull request #7637
Opened 2023-10-27 20:09 UTC by georgeweiler

## **Description**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-10-27 21:11 UTC, wachunei commented
Please mark as Draft until PR is ready for review and all checks are passing 🙏

2023-11-06 15:43 UTC, wachunei requested changes
Changes requested, main changes requested are: use `isBuy`/`isSell` instead of RampType and revert our analytics internal interface to be decoupled of current MMetrics implementation. I did not see any changes related to tests, we must create tests to confirm the off-ramp methods are being called when `isBuy` is false (you can do this by mocking the sdk hook)

Please use the conventional commit on the PR title (eg: `feat(ramp): <description>`, `refactor(ramp): <description>` and **set is as draft** instead of using `WIP` in the title.

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/buy/Views/PaymentMethods/PaymentMethods.tsx
> +        : 'OFFRAMP_CONTINUE_TO_AMOUNT_CLICKED',
use `isBuy` or `isSell` instead.

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/buy/Views/Quotes/Quotes.tsx
> +    if (rampType === RampType.BUY) {
Let's adopt `isBuy`/`isSell` here too.

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/buy/Views/Quotes/Quotes.tsx
> +        if (rampType === RampType.BUY) {
Let's adopt `isBuy`/`isSell` here too.

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/buy/Views/Regions/Regions.tsx
> +    if (rampType === RampType.BUY) {
Let's adopt `isBuy`/`isSell` here.

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/common/Views/NetworkSwitcher/NetworkSwitcher.tsx
> +    if (rampType === RampType.BUY) {
Let's adopt `isBuy`/`isSell` here too.

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/buy/Views/Quotes/Quotes.tsx
> +          if (rampType === RampType.BUY) {
Same comment about `isBuy`/`isSell` 😅 .

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/buy/Views/Quotes/Quotes.tsx
> +        if (rampType === RampType.BUY) {
Same comment about `isBuy`/`isSell` 😅 .

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/buy/Views/Quotes/Quotes.tsx
> +        if (rampType === RampType.BUY) {
Same comment about `isBuy`/`isSell` 😅 .

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/common/Views/OrderDetails.tsx
> +          provider_onramp: (order.data as Order)?.provider.name,
`(order.data as Order)?.provider.name` is being accessed twice, I propose moving it to a variable next to `payload`.

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/common/Views/Settings/AddActivationKey.tsx
> -
Undo this change since is not relevant to the PR

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/common/Views/Settings/Settings.tsx
> +      rampType === RampType.BUY
Let's adopt `isBuy`/`isSell` instead of `RampType` comparison.

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/common/components/ErrorView.tsx
> +    trackEvent(`${isBuy ? 'ON' : 'OFF'}RAMP_ERROR`, {
This is correct but a little bit too complex for the future, let's change it to the approach seen in other files 
```suggestion
    trackEvent(isBuy ? 'ONRAMP_ERROR' : 'OFFRAMP_ERROR', {
```

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/common/components/InfoAlert.tsx
> +      trackEvent(`${isBuy ? 'ON' : 'OFF'}RAMP_EXTERNAL_LINK_CLICKED`, {
Same comment about doing ternary between the whole strings instead, this is correct but maybe too complex

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/common/components/InfoAlert.tsx
> +      trackEvent(`${isBuy ? 'ON' : 'OFF'}RAMP_EXTERNAL_LINK_CLICKED`, {
Same comment about doing ternary between the whole strings instead, this is correct but maybe too complex

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/common/components/InfoAlert.tsx
> +      trackEvent(`${isBuy ? 'ON' : 'OFF'}RAMP_EXTERNAL_LINK_CLICKED`, {
Same comment about doing ternary between the whole strings instead, this is correct but maybe too complex

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/ReceiveRequest/index.js
> +        // ASK PEDRO - do we need an "onSell" method?
Yes, we need `SELL_BUTTON_CLICK` but attached to the Sell button (currently there's only one)

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/common/types/analytics.ts
> +};
We must undo this change. This file must export only two interfaces:
`ScreenLocation` and `AnalyticsEvents`, like before.

MetaMetricsEvents is an object coupled to the current mobile analytics implementation, the `AnalyticsEvents` interface exported here must remain agnostic to the current implementation. 

This means we must not export the smaller interfaces either.

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/index.tsx
> +} from './common/types';
These exports/imports must be removed and use `import { AnalyticsEvents } from './common/types';` instead, you can access the type by using the key string.

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/index.tsx
>      | null
Follow the same pattern as before.

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/index.tsx
> +        `${isBuy ? 'ON' : 'OFF'}RAMP_PURCHASE_FAILED`,
Same comment about doing ternary between the whole strings instead, this is correct but maybe too complex.

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/index.tsx
> +        `${isBuy ? 'ON' : 'OFF'}RAMP_PURCHASE_CANCELLED`,
Same comment about doing ternary between the whole strings instead, this is correct but maybe too complex.

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Ramp/index.tsx
> +        `${isBuy ? 'ON' : 'OFF'}RAMP_PURCHASE_COMPLETED`,
Same comment about doing ternary between the whole strings instead, this is correct but maybe too complex

2023-11-06 15:43 UTC, wachunei commented on app/components/UI/Tokens/index.tsx
> +  // ASK PEDRO - do we need a "goToSell" method?
Not here at the moment, there's no `Sell` button planned to be here at the moment

2023-11-06 15:43 UTC, wachunei commented on app/components/Views/Asset/index.js
> +        // ASK PEDRO - go to
There's no current plan to have a sell button here at the moment, remove comment 🙏

2023-11-06 15:43 UTC, wachunei commented on app/components/Views/SendFlow/SendTo/index.js
> +  // ASK PEDRO - do we need a go to sell
There's no current plan to have a sell button here at the moment, remove comment 🙏

2023-11-06 15:43 UTC, wachunei commented on app/components/Views/WalletActions/WalletActions.tsx
> +          text: 'Buy',
Let's change it to `Sell`

2023-11-08 23:58 UTC, wachunei commented
I'll convert back to draft until CI is passing

2023-11-15 19:54 UTC, wachunei commented on app/components/UI/Ramp/buy/Views/Quotes/Quotes.test.tsx
> +    // test for buy event
Remove this comment, if you want to explicitly note this is for buy, then rename the test, for example: `navigates and tracks event on cancel button press for buy flow`

2023-11-15 19:55 UTC, wachunei commented on app/components/UI/Ramp/buy/Views/Quotes/Quotes.test.tsx
> +    // test for offramp cancel event
Remove this comment, if you think the test needs more context then improve the test description

2023-11-15 19:56 UTC, wachunei commented on app/components/UI/Ramp/buy/Views/Quotes/Quotes.test.tsx
> +    // test for offramp cancel event
Remove this comment, if you think the test needs more context then improve the test description

2023-11-15 20:00 UTC, wachunei commented on app/components/UI/Ramp/common/types/analytics.ts
> +  text?: 'Buy' | 'Buy Native Token';
Any reason why this is optional now? Every button of the ramp flow is either a generic "Buy"  or "Buy Native Token". I think we are missing the "Sell" case?

2023-11-15 20:01 UTC, wachunei commented on app/components/UI/Ramp/index.tsx
> +    // processing fee
remove these comments or add a proper `// TODO: <description>` comment

2023-11-15 20:04 UTC, wachunei commented on app/components/UI/Ramp/index.tsx
> +      ];
refactor to a single branching condition
```suggestion
      return isBuy
        ? ['ONRAMP_PURCHASE_COMPLETED', buyCompletePayload]
        : ['OFFRAMP_PURCHASE_COMPLETED', sellCompletePayload];
```

2023-11-15 20:18 UTC, georgeweiler commented on app/components/UI/Ramp/common/types/analytics.ts
> +  text?: 'Buy' | 'Buy Native Token';
it's for the `*_GET_STARTED_CLICKED` events. Made it optional so I could reuse the interface. Happy to make another one if you need it's needed

2023-11-15 21:28 UTC, wachunei commented on app/components/UI/Ramp/common/types/analytics.ts
> +  text?: 'Buy' | 'Buy Native Token';
I see, it is ok to have the same interface but I'd prefer then to add the 'Get Started' case to the text and keep it required.

2023-11-15 21:44 UTC, lorenzosantos commented
QA'd in simulator--LGTM!

2023-11-15 21:58 UTC, wachunei reviewed
One little change

2023-11-15 21:58 UTC, wachunei commented on app/components/UI/Ramp/common/components/RegionModal.tsx
> +      trackEvent(`RAMP_REGION_SELECTED`, {
Use single quotes
```suggestion
      trackEvent('RAMP_REGION_SELECTED', {
```

2023-11-15 22:01 UTC, wachunei approved these changes
LGTM!

2023-11-15 22:12 UTC, merged