feat: add account type tag label
MetaMask/metamask-mobile pull request #7641
Opened 2023-10-30 07:46 UTC by stanleyyconsensys

## **Description**

Enable account type tag label

- Add account type tag label on the right hand side of the account address to display it's account type
  - when account type is QR, it will show ```QR Hardware```
  - when account type is simple, it will show ```Imported```
- Update existing account type tag label render in some components , to show the label when it is QR or simple
- Add utils method ```getKeyringByAddress``` to get keyring by address for reuse logic purpose
- Add utils method ```isHardwareAccount``` to determined address is hardware account or not
- add utils method ```getLabelTextByAddress```  to return label transaction key base on account type

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-10-31 07:14 UTC, dawnseeker8 commented on app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.test.tsx
>              balance: 200,
we have implemented a `isValidAddress()` check for eth accounts valid or not, in order to make unit tests to simulate the real case in the world, we now replace all invalid address `0x0` and `0x1` to all fake real eth address to make tests more robust tests.

2023-10-31 07:15 UTC, dawnseeker8 commented on app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.test.tsx
> +              '0xe64dD0AB5ad7e8C5F2bf6Ce75C34e187af8b920A',
mock keyringController initial state with valid accounts.

2023-11-06 14:29 UTC, NicolasMassart approved these changes, later dismissed
Nice work!
I only added a few suggestions, but nothing that should prevent this to go through.

2023-11-06 14:29 UTC, NicolasMassart commented on app/components/Views/AccountConnect/AccountConnectSingle/AccountConnectSingle.tsx
> +        tagLabel={tagLabel ? strings(tagLabel) : ''}
Suggestion: for better separation of component responsibility, keep the fallback value handled in the `Cell` component and not in the `tagLabel` prop setting:
```suggestion
        {...(tagLabel && { tagLabel })}
```
Then in the Cell, display empty text, or do whatever, if the `tagLabel` prop is not define.

2023-11-06 14:29 UTC, NicolasMassart commented on app/component-library/components/Pickers/PickerAccount/PickerAccount.styles.ts
> +      fontSize: 10,
Q: can you use a TextVariant here instead of specifying individual text style values?

2023-11-06 14:29 UTC, NicolasMassart commented on app/components/Views/SendFlow/AddressElement/AddressElement.styles.ts
> +      fontSize: 10,
Q: can you use a TextVariant here instead of specifying individual text style values?

2023-11-07 07:06 UTC, dawnseeker8 commented on app/components/Views/AccountConnect/AccountConnectSingle/AccountConnectSingle.tsx
> +        tagLabel={tagLabel ? strings(tagLabel) : ''}
hi, the only thing about here is `Cell` component is wrapper of `CellDisplay`, `CellMultiSelect` and `CellSelect` component,  and all three components will use `CellBase` component, however, i saw all the custom components defined `component-library` didnt contain any locale translation code ( `strings(tagLabel)`), if i do above change, then i need to handle translation in `CellBase` component which may break the pattern.

2023-11-07 08:22 UTC, montelaidev requested changes

2023-11-07 08:22 UTC, montelaidev commented on app/components/UI/DrawerView/index.js
> +    const label = getLabelTextByAddress(this.getKeyringForSelectedAddress());
It looks like the wrong value is being passed into `getLabelTextByAddress`

2023-11-07 10:31 UTC, dawnseeker8 commented on app/component-library/components/Pickers/PickerAccount/PickerAccount.styles.ts
> +      fontSize: 10,
have use TextVariant to control the fontSize, however, the bolder style need to remain here to render a border for account type label.

2023-11-07 10:32 UTC, dawnseeker8 commented on app/components/Views/SendFlow/AddressElement/AddressElement.styles.ts
> +      fontSize: 10,
have use TextVariant to control the fontSize, however, the bolder style need to remain here to render a border for account type label.

2023-11-07 10:35 UTC, stanleyyconsensys commented on app/components/UI/DrawerView/index.js
> +    const label = getLabelTextByAddress(this.getKeyringForSelectedAddress());
right, it should be a address instead, this.props. selectedAddress should be sufficient enough

2023-11-08 10:26 UTC, dawnseeker8 commented on app/components/UI/DrawerView/index.js
> +    const label = getLabelTextByAddress(this.getKeyringForSelectedAddress());
have changed to use `this.props.selectedAddress`

2023-11-09 07:50 UTC, montelaidev approved these changes

2023-11-09 11:24 UTC, merged