fix: 942 invalid QR code warning message on bad QR code
MetaMask/metamask-mobile pull request #7683
Opened 2023-11-03 15:49 UTC by frankvonhoven

## **Description**
When trying to scan an invalid QR code (e.g. not an address) from the home screen, the QR scanner was scanning and then just closing without providing any feedback to the user. This PR adds a warning to the user that they have scanned an invalid QR code.

## **Related issues**

Fixes: [942](https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/gh/metamask/mobile-planning/942)

## **Manual testing steps**

**Steps to test:**
1. On the Main Wallet view tap the Scan Icon on the top right
2. Scan this invalid QR code https://www.screencast.com/t/qhiE60jx on Networks , Ethereum, Polygon, Binance and Avalanche.
3. Should see a popup warning that the QR code is invalid

**Regression test:**
1. Scan a valid QR address code
2. Should go to SendTo flow with address populated

## **Screenshots/Recordings**

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/141057783/1369c8ea-09a3-43ed-b2e6-3dcd3c4a5eb6

### **After**

https://github.com/MetaMask/metamask-mobile/assets/141057783/a432bd4f-ddad-4ca1-ac60-5093f6ed4731

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-11-06 17:21 UTC, jpcloureiro requested changes
Left a suggestion about the Route const to use. 

Otherwise looks good 👍

2023-11-06 17:21 UTC, jpcloureiro commented on app/components/UI/Navbar/index.js
> +      origin: Routes.QR_SCANNER,
Suggestion: use `Routes.WALLET_VIEW` for the `origin` property.

Since it is under `getWalletNavbarOptions` const, I assume this only affect when on Wallet View.

2023-11-06 17:42 UTC, frankvonhoven commented on app/components/UI/Navbar/index.js
> +      origin: Routes.QR_SCANNER,
This is from the home screen. Is that the Wallet View?

2023-11-06 18:26 UTC, jpcloureiro commented on app/components/UI/Navbar/index.js
> +      origin: Routes.QR_SCANNER,
> This is from the home screen. Is that the Wallet View?

Correct, that is the Wallet View

2023-11-06 21:00 UTC, frankvonhoven commented on app/components/UI/Navbar/index.js
> +      origin: Routes.QR_SCANNER,
I think I can make that happen :)

2023-11-06 21:36 UTC, frankvonhoven commented on app/components/UI/Navbar/index.js
> +      origin: Routes.QR_SCANNER,
@jpcloureiro let me know if you can 👍

2023-11-07 10:52 UTC, jpcloureiro approved these changes

2023-11-07 16:26 UTC, merged