test: Approve custom erc20 v2
MetaMask/metamask-mobile pull request #7736
Opened 2023-11-08 23:24 UTC by sleepytanya

## **Description**

## **Related issues**

Fixes: #

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-11-13 15:30 UTC, SamuelSalas approved these changes

2023-11-13 20:58 UTC, SamuelSalas submitted a review, later dismissed

2023-11-14 14:33 UTC, NicolasMassart reviewed
Just make sure the multiline to singleline change has no impact on the other parts of the app as it's only here for testing purpose.
Otherwise, looks good to me.

2023-11-14 14:33 UTC, NicolasMassart commented on app/component-library/components-temp/CustomSpendCap/CustomInput/CustomInput.tsx
> +            multiline={false}
@brianacnguyen for anything about component library: make sure making it single line has not impact other than allowing the "\n" character input in tests to simulate return key

2023-11-14 14:49 UTC, sleepytanya commented on app/component-library/components-temp/CustomSpendCap/CustomInput/CustomInput.tsx
> +            multiline={false}
Multiline issue was discussed [here](https://consensys.slack.com/archives/C02U025CVU4/p1698170013612969).

2023-11-16 18:30 UTC, cortisiko requested changes
Can you kick off a regression test build on bitrise and post the results here? Same with a smoke build? Thanks!

2023-11-16 18:51 UTC, sleepytanya commented
@cortisiko https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/dafa17cc-ca9d-4d65-9ff8-f872d2887102
                   https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/b7f4467f-6baa-497d-8b27-f2f9d737bc0f
   Both pipelines fail at `install node and yarn` step.

2023-11-16 22:01 UTC, cortisiko commented
@sleepytanya can you update your branch with main?

2023-11-16 23:22 UTC, cortisiko requested changes
left one comment. I would say to be on the safe side, build the app and test the keyboard inputs, especially on Android (use BrowserStack to test the different device keyboards. Pixel, Samsung, Xaomi)

2023-11-16 23:22 UTC, cortisiko commented on e2e/pages/modals/ContractApprovalModal.js
> +    await TestHelpers.typeText(
Use `typeTextAndHideKeyboard`

2023-11-17 00:02 UTC, sleepytanya commented
https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/3d2229d7-2a99-4b0e-9794-1f5c6be3b68c - Smoke test passed
https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/50425d06-0c3d-44b3-8630-8d7578424353 - Regression test passed

2023-12-12 00:46 UTC, brianacnguyen commented on app/component-library/components-temp/CustomSpendCap/CustomInput/CustomInput.tsx
> +            multiline={false}
@blackdevelopa gonna tag you here since you were the author of this file

2023-12-12 02:01 UTC, sleepytanya commented on e2e/pages/modals/ContractApprovalModal.js
> +    await TestHelpers.typeText(
@cortisiko Done.

2023-12-12 04:13 UTC, alanaladd21 approved these changes

2023-12-12 04:42 UTC, sleepytanya commented on e2e/pages/modals/ContractApprovalModal.js
> +    await TestHelpers.typeText(
@cortisiko [Browserstack](https://app-automate.browserstack.com/dashboard/v2/builds/6ddb463080312dc8cf1a56c6010e2df3affa1628/sessions/574b25107d68d63e9a3bab9975ed35c9e359a83b) Seems I can't change the device on Browserstack as you requested. Would appreciate some help.

2023-12-12 18:24 UTC, cortisiko commented on e2e/pages/modals/ContractApprovalModal.js
> +    await TestHelpers.typeText(
@sleepytanya Oh, my apologies for the confusion. At this moment in time, we do not have detox running in BrowserStack. What I am asking here is to test the various device keyboards manually to ensure nothing breaks.

2023-12-12 21:43 UTC, sleepytanya commented on e2e/pages/modals/ContractApprovalModal.js
> +    await TestHelpers.typeText(
@cortisiko No worries! That's what I see on browserstack real devices:
<img width="691" alt="Screenshot 2023-12-12 at 4 41 22 PM" src="https://github.com/MetaMask/metamask-mobile/assets/104780023/fedd722f-a04e-4993-bb34-f143be55327c">
(I clicked 'request access' over a month ago)

2023-12-14 00:34 UTC, cortisiko commented on e2e/pages/modals/ContractApprovalModal.js
> +    await TestHelpers.typeText(
noooooooooooo 😢 , can you use the confirmations team alias to log into browserstack @sleepytanya ?

2023-12-14 00:42 UTC, sleepytanya commented on e2e/pages/modals/ContractApprovalModal.js
> +    await TestHelpers.typeText(
@cortisiko I logged in!
<img width="806" alt="Screenshot 2023-12-13 at 7 40 45 PM" src="https://github.com/MetaMask/metamask-mobile/assets/104780023/78c737ef-709b-4bf6-ad10-367ed80ed037">

2023-12-21 21:45 UTC, sleepytanya commented on e2e/pages/modals/ContractApprovalModal.js
> +    await TestHelpers.typeText(
I checked different Xiaomi, Google Pixel, Samsung - keyboard work as expected. Couldn't check Huawei - 'backspace' button doesn't work.

2023-12-21 21:47 UTC, cortisiko approved these changes
✅ ✅ ✅

2023-12-22 22:39 UTC, brianacnguyen approved these changes
Approved based on @blackdevelopa 's approval

2023-12-22 22:39 UTC, merged