Feat/ledger enable
MetaMask/metamask-mobile pull request #7757
Opened 2023-11-10 09:21 UTC by dawnseeker8

## **Description**

This PR will enable ledger hardware wallet support in Metamask mobiles. Following features will be added.

- User can pair with Ledger devices via bluetooth, and user can import their ledger accounts into metamask mobile.
- User can swap token using their ledger account.
- User can do normal web3 transaction using their ledger account. (contract deployment, transfer, authorise etc.)
- Dapp can connect to metamask mobile using ledger account and do normal operation.
- User can do following message signing feature
  - eth_sign
  - personal_sign
  - eth_signTypedDataV4

## **Related issues**

Fixes: https://github.com/MetaMask/metamask-mobile/issues/1237

## **Manual testing steps**

Need a full regression tests to test all ledger relative feature using https://metamask.github.io/test-dapp/

## **Screenshots/Recordings**

For detailed of screenshot, please refer to our internal Figma design. we will only list out some screenshot below:

Scan devices
![Screenshot 2023-11-08 at 12 18 48](https://github.com/MetaMask/metamask-mobile/assets/7315988/2eb3e3eb-2505-43f4-aba1-0de7997b42fb)

Pair with ledger
![Screenshot 2023-11-08 at 12 22 36](https://github.com/MetaMask/metamask-mobile/assets/7315988/c3365778-d9bf-4aca-9b99-3b100fc154a7)

Transfer
![Screenshot 2023-11-08 at 13 14 58](https://github.com/MetaMask/metamask-mobile/assets/7315988/fac0dca2-7311-41c7-aec5-a1193c1962cf)

Sign message:
![Screenshot 2023-11-08 at 13 16 26](https://github.com/MetaMask/metamask-mobile/assets/7315988/23e3d58b-bae3-4fca-bd76-a80eec720653)

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-11-13 16:33 UTC, brianacnguyen requested changes

2023-11-13 16:33 UTC, brianacnguyen commented on app/component-library/components/Cells/Cell/foundation/CellBase/CellBase.styles.ts
> +      height: 25,
please dont change this directly. instead pass the style down to the cell component

2023-11-13 16:33 UTC, brianacnguyen commented on app/component-library/components/Cells/Cell/foundation/CellBase/__snapshots__/CellBase.test.tsx.snap
> +            "lineHeight": 20,
remove

2023-11-13 16:33 UTC, brianacnguyen commented on app/component-library/components/Cells/Cell/variants/CellDisplay/__snapshots__/CellDisplay.test.tsx.snap
>                "color": "#24272A",
remove changes

2023-11-13 16:33 UTC, brianacnguyen commented on app/component-library/components/Cells/Cell/variants/CellMultiSelect/__snapshots__/CellMultiSelect.test.tsx.snap
> +                "lineHeight": 20,
remove changes

2023-11-13 16:33 UTC, brianacnguyen commented on app/component-library/components/Cells/Cell/variants/CellSelect/__snapshots__/CellSelect.test.tsx.snap
> +                "lineHeight": 20,
remove changes

2023-11-13 16:33 UTC, brianacnguyen commented on app/component-library/components/Pickers/PickerAccount/PickerAccount.tsx
> +            variant={TextVariant.BodySMBold}
did this change get approved by @Akatori-Design ?

2023-11-13 16:33 UTC, brianacnguyen commented on app/component-library/components/Tags/Tag/Tag.tsx
> +      <Text style={styles.label} variant={TextVariant.BodySMBold}>
did this change get approved by @Akatori-Design ?

2023-11-14 03:22 UTC, dawnseeker8 commented on app/component-library/components/Cells/Cell/foundation/CellBase/CellBase.styles.ts
> +      height: 25,
Has removed.

2023-11-14 03:29 UTC, dawnseeker8 commented on app/component-library/components/Tags/Tag/Tag.tsx
> +      <Text style={styles.label} variant={TextVariant.BodySMBold}>
the figma design for ledger-feature show the Label of devices should be `bold, font-size:12`. however because the people who create that figma screentshot didnt follow our `design-token`, i will revert this change to use standard one for label.

2023-11-14 03:31 UTC, dawnseeker8 commented on app/component-library/components/Pickers/PickerAccount/PickerAccount.tsx
> +            variant={TextVariant.BodySMBold}
will revert the change.

2023-11-14 04:23 UTC, dawnseeker8 commented on app/component-library/components/Cells/Cell/variants/CellSelect/__snapshots__/CellSelect.test.tsx.snap
> +                "lineHeight": 20,
after remove `LineHeight` in CellBase.Style.ts,  have regenerated the snapshot file, this file has been outdated.

2023-11-14 04:23 UTC, dawnseeker8 commented on app/component-library/components/Cells/Cell/variants/CellDisplay/__snapshots__/CellDisplay.test.tsx.snap
>                "color": "#24272A",
after remove `LineHeight` in CellBase.Style.ts,  have regenerated the snapshot file, this file has been outdated.

2023-11-14 04:23 UTC, dawnseeker8 commented on app/component-library/components/Cells/Cell/foundation/CellBase/__snapshots__/CellBase.test.tsx.snap
> +            "lineHeight": 20,
after remove `LineHeight` in CellBase.Style.ts,  have regenerated the snapshot file, this file has been outdated.

2023-11-14 12:36 UTC, NicolasMassart reviewed
I've reviewed :
- constants
- core/Analytics
- core/Engine.ts
- images
- util/test/testSetup.js
- ios
- package.json

2023-11-14 12:36 UTC, NicolasMassart commented on package.json
> +    "rxjs": "^7.8.1",
Q: what is RXJS used for in this new use case?

2023-11-14 12:57 UTC, dawnseeker8 commented on package.json
> +    "rxjs": "^7.8.1",
`useBluetooth.ts` and `useBluetoothDevices.ts` has use `rxjs`

2023-11-14 13:19 UTC, gantunesr commented on patches/@metamask+keyring-controller+6.1.0.patch
> +index dff777b..bb3aad2 100644
@stanleyyconsensys @dawnseeker8 what are the specific changes to the keyring-controller? This patch seems odd

2023-11-14 15:02 UTC, dawnseeker8 commented on patches/@metamask+keyring-controller+6.1.0.patch
> +index dff777b..bb3aad2 100644
Those strange character look like caused by sourcemap, we will find a way to regenerate the patch without .map files to simplify the patch contents.

2023-11-14 23:38 UTC, brianacnguyen requested changes

2023-11-14 23:38 UTC, brianacnguyen commented on app/component-library/components/Tags/Tag/Tag.styles.ts
> +        height: 22,
why was this changed?

2023-11-15 00:37 UTC, dawnseeker8 commented on app/component-library/components/Tags/Tag/Tag.styles.ts
> +        height: 22,
After discuss with Brian, we design to revert the change, and log a defect for `ledger` tag label `g` being cut off for brian to look at.

2023-11-15 03:09 UTC, dawnseeker8 commented on app/images/etherscan-dark.png
I double check the source code, and didn't find any where use this image, i have removed this image in my last commit.

2023-11-15 03:09 UTC, dawnseeker8 commented on app/images/etherscan-light.png
I double check the source code, and didn't find any where use this image, i have removed this image in my last commit.

2023-11-15 08:50 UTC, dawnseeker8 commented on patches/@metamask+keyring-controller+6.1.0.patch
> +index dff777b..bb3aad2 100644
hi @gantunesr i have checked some of our patches files, such as `@metamask+approval-controller+3.4.0.patch` and `@metamask+signature-controller+4.0.1.patch`, they also have those strange characters for their `.map` source mapping file change. should we still want to tackle `@metamask+keyring-controller+6.1.0.patch` by removing those source map diff?

2023-11-15 09:21 UTC, vivek-consensys commented
Manual Ledger Test Flows:- 

1. Connect to Ledger, import tokens on the Ledger account

https://github.com/MetaMask/metamask-mobile/assets/106310394/13419402-56bb-4699-b0df-4b3e7164b580


2. Disconnect to Ledger


https://github.com/MetaMask/metamask-mobile/assets/106310394/19f6f4b6-8bb3-4f2f-b0d3-dafe1c14ac1a

2023-11-15 09:44 UTC, dawnseeker8 commented on patches/@metamask+keyring-controller+6.1.0.patch
> +index dff777b..bb3aad2 100644
hi, @gantunesr i have manually remove those source file diff in our patch, and also test it was working ok, we can resolve this now. :)

2023-11-15 10:20 UTC, vivek-consensys commented
Manual Ledger Test Flows:-
3. Send transaction from Ledger 

https://github.com/MetaMask/metamask-mobile/assets/106310394/b6d18f66-6e9b-47cf-9c52-357689a48276

2023-11-15 10:36 UTC, vivek-consensys commented
Manual Ledger Test Flows:-
4. Create & Approve Token using MetaMask Test-dApp 

https://github.com/MetaMask/metamask-mobile/assets/106310394/7d11e581-de31-4c57-8de3-7593bdb99f5d

2023-11-17 16:23 UTC, matthewwalsh0 commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +    const isWhiteListedMethod = isWhitelistedRPC(req.method);
As this is stable and generic, this is great if it facilitates what is needed for this first implementation.

But I'd also be very happy to discuss how we can improve the confirmation architecture or signature controller if there is an aspect that is missing to support the Ledger use case.

Forgive me if this isn't relevant but the approval requests as they are know should throw in the backend if the approval is rejected, but equally we have a mechanism called result callbacks that can reject a promise held in the the frontend to notify it of any backend failures.

2023-11-17 16:26 UTC, matthewwalsh0 commented
No issues from the confirmations system perspective, except for potential future improvements to the error flows in case these can be "natively" supported by the `ApprovalController` and `SignatureController`.

Have also forwarded the PR to @jpuri to keep in the loop concerning the frontend confirmation changes.

2023-11-18 23:26 UTC, gantunesr commented on app/components/UI/LedgerModals/Steps/SearchingForDeviceStep.tsx
> +        url: 'https://support.ledger.com/hc/en-us/articles/360009576554-Ethereum-ETH-?docs=true',
Move this url to a constants file (`app/constants/urls.ts`).

2023-11-18 23:26 UTC, gantunesr commented on app/components/UI/Swaps/QuotesView.js
>          Analytics.trackEventWithParameters(
Is there a reason why you removed this event?

2023-11-18 23:26 UTC, gantunesr commented on app/components/Views/LedgerConnect/index.tsx
> +        url: 'https://support.ledger.com/hc/en-us/articles/360009576554-Ethereum-ETH-?docs=true',
Use the constant value here

2023-11-18 23:26 UTC, gantunesr commented on app/components/Views/LedgerConnect/index.tsx
> +export default React.memo(LedgerConnect);
What's this comment? Lets remove it

```suggestion
};

export default React.memo(LedgerConnect);
```

2023-11-18 23:26 UTC, gantunesr commented on app/components/Views/SendFlow/Confirm/index.js
> +      if (!approve) {
nit

```suggestion
    const { navigation } = this.props;
    // Manual cancel from UI or rejected from ledger device.
    try {
      if (!approve) {
```

2023-11-18 23:26 UTC, gantunesr commented on app/components/Views/SendFlow/Confirm/index.js
> +      //Let ledger modal handle the error
Nit
```suggestion
      // Error handling derived to LedgerConfirmationModal component
```

2023-11-18 23:26 UTC, gantunesr commented on app/components/hooks/Ledger/useBluetooth.test.ts
> +describe('useBluetooth', () => {
In a next PR we should improve the testing around the bluetooth hooks

2023-11-18 23:26 UTC, gantunesr commented on app/constants/navigation/Routes.ts
> +    CONNECT_LEDGER: 'LedgerConnectFlow',
Nit
```suggestion
    CONNECT_QR_DEVICE: 'ConnectQRHardwareFlow',
    CONNECT_LEDGER: 'ConnectLedgerFlow',
```

2023-11-18 23:26 UTC, gantunesr commented on app/core/Ledger/Ledger.ts
> +//TODO - Patch EthKeyringController into KeyringController
Is this the same patch in this PR or another one?

2023-11-20 03:51 UTC, dawnseeker8 commented on app/components/UI/Swaps/QuotesView.js
>          Analytics.trackEventWithParameters(
hi, @gantunesr if you look at the code here, we log a `SWAP_STARTED` with empty information first , and then immediately we log a same `SWAP_STARTED` with swap information. if we dont remove that empty line, metric will log twice with one empty information and one not empty information. if you think that line is still needed, i can revert the `removed` code in line 885.

2023-11-20 04:09 UTC, dawnseeker8 commented on app/core/Ledger/Ledger.ts
> +//TODO - Patch EthKeyringController into KeyringController
Stanely has remove the `TODO` comment, current patch in PR is sufficient enought.

2023-11-20 07:25 UTC, dawnseeker8 commented on app/components/UI/LedgerModals/LedgerConfirmationModal.tsx
> +/* eslint-disable @typescript-eslint/no-var-requires */
have been removed!

2023-11-20 07:37 UTC, dawnseeker8 commented on app/components/Views/LedgerConnect/index.tsx
> +        url: 'https://support.ledger.com/hc/en-us/articles/360009576554-Ethereum-ETH-?docs=true',
has changed to use Urls. constant.

2023-11-20 07:38 UTC, dawnseeker8 commented on app/components/UI/LedgerModals/Steps/SearchingForDeviceStep.tsx
> +        url: 'https://support.ledger.com/hc/en-us/articles/360009576554-Ethereum-ETH-?docs=true',
have moved 'https://support.ledger.com/hc/en-us/articles/360009576554-Ethereum-ETH-?docs=true` into urls.ts in constant folder.

2023-11-20 08:17 UTC, dawnseeker8 commented on app/components/UI/LedgerModals/LedgerConfirmationModal.tsx
> +    }
this was very old code from ledger team, currently we can't make this throw statement occur, after talking to Stanley , he suggest we keep this code and aslo add a log here to track whether any users hit this throw, and try to identify how this could happen.

2023-11-20 08:28 UTC, dawnseeker8 commented on app/components/hooks/Ledger/useBluetooth.test.ts
> +describe('useBluetooth', () => {
we will improve this test in next PR, currently for testing this, most difficult part is mock the `@ledgerhq/react-native-hw-transport-ble`, and following code in `useBluetooth.ts`

```
 import('@ledgerhq/react-native-hw-transport-ble').then(
        (BluetoothTransport: any) => {
          subscription = BluetoothTransport.default.observeState({
            next: (e: { available: boolean; type: State }) => {
              if (e.available && e.type === State.PoweredOn && !bluetoothOn) {
                setBluetoothOn(true);
                setBluetoothConnectionError(false);
              }

              if (!e.available && e.type === State.PoweredOff) {
                setBluetoothOn(false);
                setBluetoothConnectionError(true);
              }
            },
          });
        },
      );
      ```

2023-11-20 09:01 UTC, dawnseeker8 commented on app/components/UI/Swaps/QuotesView.js
>          Analytics.trackEventWithParameters(
i have reverted that line 885 in the latest commit.

2023-11-20 09:22 UTC, dawnseeker8 commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> +    const isWhiteListedMethod = isWhitelistedRPC(req.method);
hi, @matthewwalsh0 thank you for suggestion, we will be happy to discuss with you after this PR merged to see any improvement we can do in core SignatureController to improve this step. :)

2023-11-20 12:04 UTC, gantunesr commented on app/components/UI/LedgerModals/LedgerConfirmationModal.tsx
> +    }
Is this a product metric we're interested? If not, it's better to log it into Sentry for dev purposes

2023-11-20 16:16 UTC, NicolasMassart reviewed
It looks good to me for the files I listed as reviewed in my previous comment

2023-11-20 17:46 UTC, gantunesr approved these changes, later dismissed

2023-11-20 23:54 UTC, plasmacorral commented
I have some concerns here after some manual testing on iOS 17.0.3 with iPhone Xs using a Nano X with eth app 1.10.1 and blind signing enabled.

1) Signatures are not being returned to the [test dapp](https://metamask.github.io/test-dapp) on Ledger in this branch, but Keystone works just fine. 
  Keystone successfully using Eth sign and Personal sign on the test dapp: https://recordit.co/ozWHGC0DwX
  Ledger signing attempts: https://recordit.co/PA4g8SH0jI
2) After binding a Keystone address to MMM, user is returned to hardware wallet selection screen.  On successful binding with Keystone, user should be returned to Wallet view with the freshly added Keystone address selected. 
  https://recordit.co/9hnHZDV11s 
3) Was able to pair a Ledger device without clicking anything on the personal security device (PSD).  I selected to pair from MMM and it just happened in this branch.  In testing from 2022 I was required to tap on the PSD to confirm that I wished to pair to MMM.  This is not happening today and could be a security issue: https://recordit.co/ns7WBIWaVF

2023-11-20 23:54 UTC, plasmacorral submitted a review, later dismissed
https://github.com/MetaMask/metamask-mobile/pull/7757#issuecomment-1819992123

2023-11-21 01:03 UTC, brianacnguyen approved these changes, later dismissed

2023-11-21 03:42 UTC, dawnseeker8 commented on app/components/UI/LedgerModals/LedgerConfirmationModal.tsx
> +    }
this is product metric listed in https://docs.google.com/document/d/1sBeYy-pA9cpXdD-jy48CoZTYFusSdWkm2kM5WDClybc/edit#heading=h.mq7tghwjdb93

2023-11-21 03:46 UTC, dawnseeker8 commented
hi, @plasmacorral, 
I have fixed the point 2 issue, now the keyring accounts selected, screen will be redirect to Wallet view.

2023-11-21 10:01 UTC, vivek-consensys commented
> I have some concerns here after some manual testing on iOS 17.0.3 with iPhone Xs using a Nano X with eth app 1.10.1 and blind signing enabled.
> 
> Android device is Pixel 5a with Android 14.
> 
> Tested with a QA build of commit [8778e77](https://github.com/MetaMask/metamask-mobile/commit/8778e7789dc12d7b25985a70e02114f85c724632)
> 
> 1. Signatures are not being returned to the [test dapp](https://metamask.github.io/test-dapp) on Ledger in this branch, but Keystone works just fine. I had no issues conducting a send tx with the test dapp on iOS.  Did not have this issue on Android.  Can confirm this impedes the iOS user's ability to sign a message to login to Opensea, for example.
>    Keystone successfully using Eth sign and Personal sign on the test dapp: https://recordit.co/ozWHGC0DwX
>    Ledger signing attempts on test dapp (eth sign/personal sign): https://recordit.co/PA4g8SH0jI
>    Three attempts to login to Opensea with Ledger + MMM: https://recordit.co/CVmITcwCEq
> 2. After binding a Keystone address to MMM, user is returned to hardware wallet selection screen on both android and iOS.  On successful binding with Keystone, user should be returned to Wallet view with the freshly added Keystone address selected.
>    https://recordit.co/9hnHZDV11s
> 3. ~Was able to pair a Ledger device without clicking anything on the personal security device (PSD).  I selected to pair from MMM and it just happened in this branch without any consent on the Ledger.  In testing from 2022 I was required to tap on the PSD to confirm that I wished to pair to MMM.  Did not have this issue on Android.  This is not happening today with my iOS device and could be a security issue: https://recordit.co/ns7WBIWaVF~. This was only the case because Ledger had been previously paired with iPhone.  Once I forgot the prior bt connection, I was prompted to pair on the Ledger PSD as expected. This was testing error and is not an issue.

Test Flow Screen Recordings:- 

Manual testing using iPhone 13 on iOS 17.1
Tested with a QA build of commit https://app.bitrise.io/build/0dc22016-e6b8-4858-b88f-b11aa53a84c3?tab=artifacts

1. Signing using MetaMask test-dApp

https://github.com/MetaMask/metamask-mobile/assets/106310394/3da9b751-28d3-4f99-93f5-2107e5d0cc7c

2. Signing using OpenSea

https://github.com/MetaMask/metamask-mobile/assets/106310394/8e652a0e-8cc2-4840-bc4e-12b784b51690

3. User returned to wallet view after connecting to Keystone wallet

https://github.com/MetaMask/metamask-mobile/assets/106310394/841e4239-a11a-44ac-a65e-1e6e160677c2

2023-11-22 02:29 UTC, plasmacorral commented
Issue #1 resolved according to videos above, Thank you @vivek-consensys!

I have one last nit that is a correction to an earlier error I made.  For #2 above I made a mistake and missed the fact that in production today after adding or removing hardware, the user is returned to wallet view **_with the accounts drop-down menu presented._**  

As tested today with Pixel 5a on Android 14 and iPhone Xs with iOS 17.0.3 with a QA build of commit bbdee57ae94c0721f5a2321514a2b6524026a4f9.

Here is a grid that includes recordings comparing production results to the branch under test: 
<google-sheets-html-origin><style type="text/css"><!--td {border: 1px solid #cccccc;}br {mso-data-placement:same-cell;}--></style>
  | bbdee57 commit lands | Commit bbdee57 video | Production lands | Production v7.11.0 build 1197
-- | -- | -- | -- | --
Adding Ledger | Wallet View | https://recordit.co/JHt9OwQn1J |   |  
Forgetting Ledger | Hardware selection.  When I tap back arrow I returned to Wallet view with accounts drop-down open | https://recordit.co/7YC1AkeFEG |   |  
Adding Keystone | Wallet View | https://recordit.co/XqIm4TW7d0 | Wallet view with accounts drop-down open | https://recordit.co/eL0dDcYz9e
Forgetting Keystone | Hardware selection.  When I tap back arrow I returned to Wallet view with accounts drop-down open | https://recordit.co/3WKzk0tIR4 | Wallet view with accounts drop-down open | https://recordit.co/odGKM2vowS

2023-11-22 02:32 UTC, plasmacorral commented
I can otherwise report that signing and sending with the test dapp from both Keystone and Ledger (when both present in the wallet) looks good in commit bbdee57ae94c0721f5a2321514a2b6524026a4f9 tested with Pixel 5a on Android 14 and iPhone Xs with iOS 17.0.3 using a QA build

2023-11-22 03:53 UTC, gantunesr commented
[Running E2E](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/871803b2-40c4-4677-b448-981753248c0c)

2023-11-22 13:15 UTC, gantunesr commented
@SocketSecurity ignore-all

2023-11-22 16:39 UTC, dawnseeker8 commented
> Issue #1 resolved according to videos above, Thank you @vivek-consensys!
> 
> I have one last nit that is a correction to an earlier error I made. For two above I made a mistake and missed the fact that in production today after adding or removing hardware, the user is returned to wallet view **_with the accounts drop-down menu presented._**
> 
> As tested today with Pixel 5a on Android 14 and iPhone Xs with iOS 17.0.3 with a QA build of commit [bbdee57](https://github.com/MetaMask/metamask-mobile/commit/bbdee57ae94c0721f5a2321514a2b6524026a4f9).
> 
> Here is a grid that includes recordings comparing production results to the branch under test: <style type="text/css"></style>
> 
>  	[bbdee57](https://github.com/MetaMask/metamask-mobile/commit/bbdee57ae94c0721f5a2321514a2b6524026a4f9) commit lands	Commit [bbdee57](https://github.com/MetaMask/metamask-mobile/commit/bbdee57ae94c0721f5a2321514a2b6524026a4f9) video	Production lands	Production v7.11.0 build 1197
> Adding Ledger	Wallet View	https://recordit.co/JHt9OwQn1J	 	 
> Forgetting Ledger	Hardware selection. When I tap back arrow I returned to Wallet view with accounts drop-down open	https://recordit.co/7YC1AkeFEG	 	 
> Adding Keystone	Wallet View	https://recordit.co/XqIm4TW7d0	Wallet view with accounts drop-down open	https://recordit.co/eL0dDcYz9e
> Forgetting Keystone	Hardware selection. When I tap back arrow I returned to Wallet view with accounts drop-down open	https://recordit.co/3WKzk0tIR4	Wallet view with accounts drop-down open	https://recordit.co/odGKM2vowS

I have changed the code to make `Adding Keystone Wallet View` and `Forgetting Keystone Hardware Selection` behave same as `Production v7.11.0 build 1197` (same as `main` as well), now the screen will direct to `Wallet view with accounts drop-down open`.  for `adding ledger`, i also change the code to direct to `Wallet view with accounts drop-down open` to make behave consistance.

2023-11-23 16:46 UTC, dawnseeker8 commented
attached new e2e tests result [here](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/ce00e5a6-2d9f-44a7-b6d7-b4623a694366)

2023-11-24 02:17 UTC, stanleyyconsensys commented on app/constants/keyringTypes.ts
> +
app/util/importAdditionalAccounts.js using own keyring type text, it should replace by ExtendedKeyringTypes.hd

2023-11-27 05:35 UTC, dawnseeker8 commented on app/constants/keyringTypes.ts
> +
has changed  `importAdditionalAccounts ` based o your comments.

2023-11-29 08:55 UTC, dawnseeker8 commented
This is the latest smoke e2e tests result https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/74ad83d1-aaea-4065-935b-2d6c220e5d0d

2023-11-29 09:02 UTC, dawnseeker8 commented
This is the latest regression e2e tests result: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/4553befb-80f7-4c38-883b-7e9a95d6943a

2023-11-29 12:27 UTC, gantunesr commented on .detoxrc.js
> +  },
Nit: Looks like a space got added in this line

2023-11-29 12:28 UTC, gantunesr commented on .detoxrc.js
> +
Nit: Same here

2023-11-29 12:28 UTC, gantunesr approved these changes

2023-11-29 14:02 UTC, dawnseeker8 commented on .detoxrc.js
> +  },
Already resolved in my last commit to revert the version to match main version.

2023-11-29 14:02 UTC, dawnseeker8 commented on .detoxrc.js
> +
Already resolved in my last commit to revert the version to match main version.

2023-11-29 18:38 UTC, gantunesr approved these changes
I've manually tested the PR and verified the test cases

2023-11-29 21:03 UTC, Akaryatrh commented
I've manually tested the PR and verified the test cases

2023-11-29 21:03 UTC, Akaryatrh approved these changes

2023-11-29 23:19 UTC, georgewrmarshall approved these changes
Approving as @brianacnguyen previously mentioned no updates to component-library folder

2023-11-29 23:20 UTC, merged