test: Move TestIDs from page objects in e2e/pages folder
MetaMask/metamask-mobile pull request #7762
Opened 2023-11-10 17:38 UTC by SamuelSalas

## **Description**
 Relocate the TestIDs from each page object to their corresponding testID file within the testID folder. This task is aimed at transferring the TestIDs from the page objects in the e2e/pages folder.

## **Related issues**

Fixes: #7721

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-11-15 00:39 UTC, chrisleewilcox requested changes
See comment.

2023-11-15 00:39 UTC, chrisleewilcox commented on e2e/pages/ImportTokensView.js
@SamuelSalas update this file that's currently on main.

2023-11-15 01:38 UTC, SamuelSalas commented on e2e/pages/ImportTokensView.js
Done

2023-11-15 22:09 UTC, chrisleewilcox submitted a review, later dismissed
LGTM

2023-11-16 15:06 UTC, chrisleewilcox requested changes, later dismissed
Please see comments.

2023-11-16 15:06 UTC, chrisleewilcox commented on .tool-versions
This change here is not currently in main.  Try to keep PRs limited to only your changes.  Please update this branch with current main and if there are changes from your branch that is not part of the PR and it's not in sync with main then revert those changes.

2023-11-16 15:31 UTC, SamuelSalas commented on .tool-versions
Just remove it.

2023-11-16 18:07 UTC, cortisiko requested changes
I only left one small comment. Also, run the regression pipeline in addition to the smoke pipeline on this PR.

2023-11-16 18:07 UTC, cortisiko commented on e2e/specs/browser/browser-tests.spec.js
> +    await Browser.isWebViewTestDapp();
This is checking the URL bar for the short hand url for the test dapp right? We should rename it to reflect that. First place I assumed we are asserting that the test dapp loads correctly.

2023-11-16 18:55 UTC, SamuelSalas commented
> I only left one small comment. Also, run the regression pipeline in addition to the smoke pipeline on this PR.

2023-11-16 21:59 UTC, cortisiko approved these changes
✅ ✅ ✅

2023-11-16 22:55 UTC, merged