chore: fix typos
MetaMask/metamask-mobile pull request #7764
Opened 2023-11-11 03:47 UTC by shuoer86

2023-11-11 03:51 UTC, shuoer86 commented
I have read the CLA Document and I hereby sign the CLA

2023-11-16 13:33 UTC, leotm approved these changes, later dismissed

2023-11-16 13:33 UTC, leotm commented on app/components/UI/Drawer/index.tsx
> +        // Network switched has occurred
few more to update on this one

<img width="520" alt="Screenshot 2023-11-16 at 1 32 55 pm" src="https://github.com/MetaMask/metamask-mobile/assets/1881059/4a0294cd-009a-44fe-a3ad-4cf645eada0b">

if you fancy in this pr or after

2023-11-16 13:34 UTC, leotm commented
if you could preserve the original PR template too, that would be great

2023-11-16 15:16 UTC, shuoer86 commented
@leotm Thanks for you review.

2023-12-04 19:03 UTC, georgewrmarshall reviewed
This is great! Thank you @shuoer86 🙏   Can we get an mobile engineer that is familiar with the locales keys to ensure the `error_occured` => `error_occurred` key update is valid otherwise LGTM!  Out of curiosity what tool did you use to catch all of these? Thanks for your contribution 🙏

2023-12-04 20:43 UTC, brianacnguyen requested changes

2023-12-05 15:53 UTC, shuoer86 commented
@georgewrmarshall I would like to add code speller workflow in CI if needed

2023-12-26 15:34 UTC, shuoer86 commented
@georgewrmarshall @brianacnguyen @leotm thanks for your reviews again.

2024-01-04 18:30 UTC, georgewrmarshall approved these changes, later dismissed
LGTM! Thanks for your contribution @shuoer86 🙏 
- Searched to confirm no instances of `error_occured` remain ✅ 

![Screenshot 2024-01-04 at 10 29 47 AM](https://github.com/MetaMask/metamask-mobile/assets/8112138/bf190385-1de1-4446-850e-04afb0a82c6c)

2024-01-04 18:43 UTC, brianacnguyen approved these changes, later dismissed

2024-01-12 14:53 UTC, shuoer86 commented
@brianacnguyen Could you help to merge it? Thank you very much.

2024-04-12 16:04 UTC, shuoer86 commented
@georgewrmarshall @brianacnguyen @leotm 

I rebased to resolved the new coming conflict. 

Please help me to review again. Thank you very much!

2024-04-12 21:26 UTC, georgewrmarshall approved these changes
LGTM! Not sure why e2e tests are failing is this to do with open source contributions @leotm?

2024-05-17 11:40 UTC, shuoer86 commented
@georgewrmarshall @brianacnguyen @leotm 
Could you help to merge when approved.

2024-11-14 16:30 UTC, Cal-L approved these changes
LGTM

2025-05-21 00:46 UTC, closed without merging

2025-06-07 15:04 UTC, shuoer86 commented
anyone can help to review and merge?