test: Settings Security And Privacy: Refactor page objects
MetaMask/metamask-mobile pull request #7888
Opened 2023-11-21 01:15 UTC by SamuelSalas

## **Description**
Add Page object model to Security and privacy pages

## **Related issues**

Fixes: #1331

## **Manual testing steps**

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-11-29 00:04 UTC, cortisiko requested changes
left some comments @SamuelSalas

2023-11-29 00:04 UTC, cortisiko commented on e2e/pages/Drawer/Settings/SecurityAndPrivacy/RevealSecretRecoveryPhrase.js
> +  async getContainer() {
we might be creating duplicate work for ourselves. No need for line 38 through 56 since we already have getters for these.

2023-11-29 04:37 UTC, SamuelSalas commented on e2e/specs/quarantine/deeplinks.failing.js
> +    ).toBeTruthy();
No, just updated the assertion.

2023-11-29 04:37 UTC, SamuelSalas commented on e2e/specs/quarantine/deeplinks.failing.js
> +    ).toBeTruthy();
No, just updated the assertion.

2023-11-29 04:56 UTC, SamuelSalas commented on e2e/pages/Drawer/Settings/SecurityAndPrivacy/ChangePasswordView.js
> +  async getTitle() {
The main idea is so the getter are only accessible by the methods on the page object. But with the current implementation, an extra method would be redundant. I'll remove it.

2023-11-29 04:56 UTC, SamuelSalas commented on e2e/specs/settings/delete-wallet.spec.js
> +        await expect(await ChangePasswordView.getTitle()).toBeVisible();
Yes

2023-11-29 04:58 UTC, SamuelSalas commented on e2e/utils/Gestures.js
> +      .atIndex(0)
I added the atIndex because I kept getting a lot of error from the previous swipeByText. That specific method had the extra atIndex. After I added to the new swipe, those errors no longer appear locally.

2023-11-29 04:58 UTC, SamuelSalas commented on e2e/specs/onboarding/onboarding-wizard-opt-in.spec.js
> +        await SecurityAndPrivacy.getMetaMetricsToggle(),
Will change it.

2023-11-29 04:58 UTC, SamuelSalas commented on e2e/specs/quarantine/contract-nickname.failing.js
> +      await SecurityAndPrivacy.getRememberMeToggle(),
Will change it.

2023-11-29 04:58 UTC, SamuelSalas commented on e2e/specs/permission-systems/permission-system-delete-wallet.spec.js
> +            await SecurityAndPrivacyView.getChangePasswordSection(),
will change it

2023-11-29 04:59 UTC, SamuelSalas commented on e2e/specs/quarantine/contract-nickname.failing.js
> +    await expect(
will change it

2023-11-29 04:59 UTC, SamuelSalas commented on e2e/pages/Drawer/Settings/SecurityAndPrivacy/RevealSecretRecoveryPhrase.js
> +  async getContainer() {
Ok, will remove it.

2023-11-30 00:35 UTC, cortisiko requested changes

2023-11-30 00:35 UTC, cortisiko commented on e2e/pages/CommonView.js
> +    return Matchers.getElementByText('OK');
```suggestion
    return Matchers.getElementByLabel('OK');
```

2023-12-01 03:25 UTC, chrisleewilcox commented on app/components/Views/ResetPassword/index.js
> +                    {...generateTestId(Platform, RESET_PASSWORD_INPUT_ID)}
@cortisiko is there where we want to use testID property?

2023-12-01 16:35 UTC, cortisiko commented on app/components/Views/Settings/SecuritySettings/SecuritySettings.test.tsx
> +      getByTestId(SecurityPrivacyViewSelectorsIDs.CHANGE_PASSWORD_CONTAINER),
@SamuelSalas can you set the TestID property instead of using this method? Ideally we want to move away from it

2023-12-01 18:30 UTC, SamuelSalas commented on app/components/Views/ResetPassword/index.js
> +                    testID={RESET_PASSWORD_INPUT_ID}
I decided to remove the input box id and use the same reset password input. The inputs is the same, the only difference is that one appears when confirming a password and the other one when reset. I find it a little bit redundant.

2023-12-01 18:50 UTC, cortisiko commented on app/components/Views/ResetPassword/index.js
> +                    testID={RESET_PASSWORD_INPUT_ID}
ah yeah I see the variable names are redundant. Basically `RESET_PASSWORD_INPUT_ID` is the ID for the enter password input box on [the reset password screen](https://app.screencast.com/ycddvP7RJaiji). 

Whereas RESET_PASSWORD_INPUT_BOX_ID is the create password Input box on the [setup password screen](https://app.screencast.com/rYndUkimBDB4V). 

To avoid confusion here I would say to reuse the same input selectors from https://github.com/MetaMask/metamask-mobile/blob/main/e2e/selectors/Onboarding/ChoosePassword.selectors.js#L4

So `RESET_PASSWORD_INPUT_BOX_ID` becomes `ChoosePasswordSelectorsIDs.NEW_PASSWORD_INPUT_ID `

And 
`RESET_PASSWORD_CONFIRM_INPUT_BOX_ID` becomes `ChoosePasswordSelectorsIDs.CONFIRM_PASSWORD_INPUT_ID`

2023-12-01 19:31 UTC, SamuelSalas commented on app/components/Views/ResetPassword/index.js
> +                    testID={RESET_PASSWORD_INPUT_ID}
done

2023-12-01 19:48 UTC, cortisiko approved these changes, later dismissed
PR looks good. TY @SamuelSalas

2023-12-04 16:32 UTC, cortisiko approved these changes

2023-12-04 17:12 UTC, merged