chore: refactor the DeeplinkManager into smaller parts and add unit tests
MetaMask/metamask-mobile pull request #7925
Opened 2023-11-24 09:18 UTC by omridan159

## **Description**

Refactored the `DeeplinkManager` class into smaller, more manageable components, enhancing code readability and maintainability.
This change simplifies future modifications and debugging. Additionally, comprehensive unit tests were added to ensure each component functions correctly, boosting overall software reliability.

## **Related issues**

Fixes: #

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

https://github.com/MetaMask/metamask-mobile/assets/61094771/147fc998-cf49-448e-a71b-2af8006c9225

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-11-24 09:28 UTC, abretonc7s requested changes
I think we should rename all the handleParseMetamask/Universal/Walle by handleMetamask/Univer/Walle.

It would make it easier to match the filename to the functionality without opening the file

2023-11-24 09:28 UTC, abretonc7s commented on app/core/DeeplinkManager/ParseManager/handleParseWCProtocol.ts
> +export function handleParseWCProtocol({
that files seems to connect to wc, probably would need a more appropriate name

2023-11-24 11:53 UTC, abretonc7s approved these changes

2023-12-04 08:13 UTC, deeeed approved these changes
LGTM

2023-12-04 08:14 UTC, abretonc7s approved these changes
LGTM

2023-12-04 08:15 UTC, abretonc7s submitted a review, later dismissed
LGTM

2023-12-04 17:32 UTC, christopherferreira9 commented
E2E: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/bfad41f3-66ff-48a9-98c5-9bb80027d9ae

2023-12-04 17:45 UTC, christopherferreira9 commented
**Checked for both Android and iOS**

- Multiple sign variants
- SwitchChain
- AddChain
- Session persistence
- WalletConnect
- Deeplink variants from https://metamask.github.io/metamask-deeplinks/#

Only one issue found @omridan159 .
Steps to reproduce:
1. Open https://metamask.github.io/metamask-deeplinks/#
2. Select "Payment request"
3. Enter any details you want with and without chainId (on separate tries)
4. Tap the link 
5. See issue

Video:

https://github.com/MetaMask/metamask-mobile/assets/104831203/fc9e2594-9bc5-42d1-a58a-c24e4184e82d

2023-12-06 09:16 UTC, deeeed approved these changes

2023-12-06 11:22 UTC, andreahaku approved these changes
LGTM

2023-12-06 15:23 UTC, merged