feat: Added SelectButton and SelectValue
MetaMask/metamask-mobile pull request #7938
Opened 2023-11-28 19:00 UTC by brianacnguyen

## **Description**

## **Screenshots/Recordings**
![Simulator Screen Shot - iPhone 14 Pro - 2023-11-28 at 10 57 54](https://github.com/MetaMask/metamask-mobile/assets/14355083/1447424e-9727-494c-8415-0f2d41ba2c82)
![Simulator Screen Shot - iPhone 14 Pro - 2023-11-28 at 10 58 01](https://github.com/MetaMask/metamask-mobile/assets/14355083/8c33d984-ba86-45c6-afce-58acdd2ffeae)

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-11-28 23:03 UTC, georgewrmarshall reviewed
Can we break this PR down further? As of writing this comment it's `1,408` code changes which is on the large side. Also a video rather than long images I think would really improve the PR description and help QA this PR

2023-12-06 21:48 UTC, georgewrmarshall reviewed
Looking good! Left a few suggestions

2023-12-06 21:48 UTC, georgewrmarshall commented on app/component-library/components/Select/SelectButton/README.md
> +Optional content to be displayed in the info section.
```suggestion
Optional content to be displayed in the info section
```

2023-12-06 21:48 UTC, georgewrmarshall commented on app/component-library/components/Select/SelectButton/SelectButton.stories.tsx
> +  ),
If you are just rendering the component without any wrappers or other components can we just use the args object?
```suggestion
  args: {
    iconProps: SAMPLE_SELECTBUTTON_PROPS.iconProps,
  },
```

2023-12-06 21:48 UTC, georgewrmarshall commented on app/component-library/components/Select/SelectButton/SelectButton.test.tsx
> +});
Seems like we are missing some tests here?

2023-12-06 21:48 UTC, georgewrmarshall commented on app/component-library/components/Select/SelectButton/SelectButton.types.ts
> +}
nit: Could add comments here so the heights show up in intellisense

2023-12-06 21:48 UTC, georgewrmarshall commented on app/component-library/components/Select/SelectButton/foundation/SelectButtonBase.tsx
> +export default SelectButtonBase;
This seems to be missing a test file?

2023-12-13 23:57 UTC, brianacnguyen commented on app/component-library/components/Select/SelectButton/foundation/SelectButtonBase.types.ts
> +  caretIconEl?: React.ReactNode;
It doesn't need to be imported?

2023-12-14 00:00 UTC, brianacnguyen commented on app/component-library/components/Select/SelectButton/SelectButton.stories.tsx
> +  ),
no since we don't want the iconProps arg to be changable. This is intentional

2023-12-14 00:01 UTC, brianacnguyen commented on app/component-library/components/Select/SelectButton/SelectButton.types.ts
> +}
true but the size here doesn't equate to a static height but rather min height and vertical padding so not gonna include that

2023-12-15 01:58 UTC, georgewrmarshall approved these changes, later dismissed
LGTM. A few non blocking suggestions

2023-12-15 01:58 UTC, georgewrmarshall commented on app/component-library/components/Select/SelectButton/SelectButton.tsx
> +          size={STARTICON_ICONSIZE_BY_SELECTBUTTONSIZE[size]}
Does this not then make it impossible to override the size even if the intent is to override it via the `iconProps` object? I would suggest allowing for the override if necessary 
```suggestion
          size={STARTICON_ICONSIZE_BY_SELECTBUTTONSIZE[size]}
          {...iconProps}
```

2023-12-18 21:56 UTC, georgewrmarshall commented on app/component-library/components/Select/SelectButton/SelectButton.test.tsx
> +});
It doesn't seem like there is adequate testing coverage for this component?

2023-12-18 21:58 UTC, georgewrmarshall commented on app/component-library/components/Select/SelectButton/foundation/SelectButtonBase.test.tsx
> +  });
Seem to be missing tests here?

2023-12-18 21:58 UTC, georgewrmarshall requested changes
Code looks good however, there doesn't seem to be adequate testing coverage for this component? You are not testing all of the sizes, isDisabled, isDanger props

2023-12-18 23:55 UTC, georgewrmarshall approved these changes
Seeing as other mobile components have very light testing coverage and there are no official testing coverage criteria I can approve but we should discuss in the NY

2023-12-19 04:43 UTC, brianacnguyen commented on app/component-library/components/Select/SelectButton/foundation/SelectButtonBase.test.tsx
> +  });
will add additional tests in another PR

2023-12-19 04:43 UTC, merged