Feat/snaps controllers integration
MetaMask/metamask-mobile pull request #7942
Opened 2023-11-29 03:04 UTC by owencraston

## **Description**

## **Related issues**

Fixes: #

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-12-06 10:10 UTC, FrederikBolding requested changes, later dismissed

2023-12-06 10:10 UTC, FrederikBolding commented on app/core/Permissions/specifications.js
> +  ///: BEGIN:ONLY_INCLUDE_IN(flask)
Seems there are mixed usage of `flask` and `snaps` fences. Should they not all be `snaps`?

2023-12-06 10:10 UTC, FrederikBolding commented on app/util/test/initial-background-state.json
> +    "snapErrors": {},
```suggestion
```

2023-12-06 10:10 UTC, FrederikBolding commented on package.json
> +    "@metamask/slip44": "3.1.0",
Can we not use strict versions for the snaps deps?

2023-12-06 10:10 UTC, FrederikBolding commented on app/core/Snaps/location/location.ts
> +      return new LocalLocation(root, opts);
```suggestion
      assert(allowLocal, new TypeError('Fetching local snaps is disabled.'));
      return new LocalLocation(root, opts);
```

2023-12-06 10:10 UTC, FrederikBolding commented on app/core/Snaps/location/location.ts
> +  const root = new URL(location.toString());
```suggestion
  const allowLocal = opts?.allowLocal ?? false;
  const root = new URL(location.toString());
```

2023-12-06 10:10 UTC, FrederikBolding commented on app/core/Snaps/location/location.ts
> +export function detectSnapLocation(
Maybe this should be more flexible upstream so we don't have to duplicate 🤔

2023-12-06 10:10 UTC, FrederikBolding commented on app/core/Snaps/SnapsMethodMiddleware.ts
> +  createSnapsMethodMiddleware(true, {
We should validate whether the origin is a snap or not instead of just passing `true`

2023-12-06 10:10 UTC, FrederikBolding commented on app/components/Views/Snaps/components/SnapPermissions/SnapPermissions.tsx
> +    const pathMetadata = SNAPS_DERIVATION_PATHS.find(
Please update this to be in line with extension (also we should upstream more of this)

2023-12-06 10:10 UTC, FrederikBolding commented on app/constants/permissions.ts
> +  'endowment:long-running': 'endowment:long-running',
```suggestion
```

2023-12-06 10:10 UTC, FrederikBolding commented on app/core/Permissions/constants.ts
> +  snap_confirm: 'snap_confirm',
```suggestion
  snap_dialog: 'snap_dialog',
```

2023-12-07 01:21 UTC, owencraston commented on app/core/Engine.ts
> +      return state === 'active';
This will return false in the case that the app gets backgrounded or force closed. [RN AppState docs](https://reactnative.dev/docs/appstate).

2023-12-07 01:33 UTC, owencraston commented on app/core/Permissions/specifications.js
> +  ///: BEGIN:ONLY_INCLUDE_IN(flask)
I am going to migrate them all to be snaps

2023-12-07 04:33 UTC, owencraston commented on app/core/Snaps/location/http.ts
> +    const contents = await (
I don't think this is needed anymore. I removed it in my latest commit.

2023-12-07 04:33 UTC, owencraston commented on app/core/Permissions/specifications.js
> +  ///: BEGIN:ONLY_INCLUDE_IN(flask)
Done

2023-12-07 20:38 UTC, owencraston commented on app/core/Engine.ts
> +      process.env.METAMASK_BUILD_TYPE === 'main' ? true : undefined;
The reason I added this was because the expected type of the featureFlag is `true | undefined`?

2023-12-07 20:41 UTC, owencraston commented on app/core/Engine.ts
> +      process.env.METAMASK_BUILD_TYPE === 'main' ? true : undefined;
However I noticed that it was breaking under my current implementation and reverting it to `process.env.METAMASK_BUILD_TYPE === 'main';` seems to work so I will ignore the type error.

2023-12-07 23:36 UTC, owencraston commented on app/core/Engine.ts
> +      closeAllConnections: () =>
I removed the definition and it gave me errors when running a snap. This prop seems to have no default inside the controller and it is expected for execution. I will add it back in for now.

2023-12-08 07:05 UTC, owencraston commented on app/core/Engine.ts
> +            this.controllerMessenger.call(
again, I do not see any usage of `usePhishDetect` on mobile.

2023-12-08 07:06 UTC, owencraston commented on app/core/Snaps/location/location.ts
> +      return new LocalLocation(root, opts);
we can't assert (its a node js paradigm) but we can throw an error so I added that in the latest implementation.

2023-12-08 07:07 UTC, owencraston commented on app/core/Snaps/location/location.ts
> +      return new LocalLocation(root, opts);
<img width="588" alt="Screenshot 2023-12-07 at 11 07 29 PM" src="https://github.com/MetaMask/metamask-mobile/assets/22918444/a5efacf9-7fe7-4fbf-8e34-0e2ed42ff347">

2023-12-08 17:30 UTC, Jonathansoufer approved these changes, later dismissed
LGTM! Left some comments.

2023-12-08 17:30 UTC, Jonathansoufer commented on app/core/Engine.ts
> +      refetchOnAllowlistMiss: requireAllowlist,
if you decide to change allowList to camelCase, then we need to change/replace it throughout the entire file.

2023-12-08 17:30 UTC, Jonathansoufer commented on app/core/Snaps/WebviewExecutionService.ts
> +// eslint-disable-next-line @typescript-eslint/ban-ts-comment
I was thinking the same, but we're apparently in a deadlock situation. My PR was built upon the newest package's versions, but mobile wasn't ready for it, and this PR is what will get mobile ready, although not taking full advantage of the snaps related code migration to snaps main repo. I think we move with this one, and then would be easier for me to test mine.

2023-12-08 18:49 UTC, owencraston commented on app/core/Engine.ts
> +        KeyringTypes.hd,
extension and mobile are using different keyrings. Mobile  using [@metamask/keyring-controller](https://github.com/MetaMask/core/tree/main/packages/keyring-controller) and the extension is using [@metamask/eth-keyring-controller](https://github.com/MetaMask/KeyringController). The @metamask/keyring-controller wraps the @metamask/eth-keyring-controller so a lot of the same methods are available but through different apis.

2023-12-08 18:54 UTC, owencraston commented on app/core/Engine.ts
> +          `SnapController:getPermitted`,
good catch

2023-12-08 19:02 UTC, owencraston commented on app/constants/snaps.ts
> +export const SNAPS_DERIVATION_PATHS: SnapsDerivationPath[] = [
I do not think we can import this at this time but this would be a great map to upstream. Perhaps we could even upstream the lookup functions.

2023-12-11 19:08 UTC, owencraston commented on app/core/Engine.ts
> +import { AppState } from 'react-native';
Note: check if there is an existing util

2023-12-11 19:11 UTC, owencraston commented on app/core/Engine.ts
> +  | LoggingControllerActions
needs to be added back to global actions

2023-12-11 19:13 UTC, owencraston commented on app/core/Engine.ts
> +  | KeyringControllerEvents
needs to be moved back to global actions

2023-12-11 19:17 UTC, owencraston commented on app/core/Engine.ts
> +          // @ts-ignore
add todo

2023-12-11 22:23 UTC, owencraston commented on app/core/Engine.ts
> +          // @ts-ignore
I created an issue for all of the type check related errors that need to be implemented at the package level. Here is the [issue](https://github.com/MetaMask/snaps/issues/2029). cc @andrepimenta

2023-12-11 22:26 UTC, owencraston commented on app/core/Engine.ts
> +import { AppState } from 'react-native';
I could not find a util function in the codebase for this functionality. All components are directly using the AppState class from RN and since its such a simple API I think this is fine.

2023-12-11 22:43 UTC, owencraston commented on app/components/UI/SnapsExecutionWebView/SnapsExecutionWebView.tsx
> +    // localAndroid: 'http://10.0.2.2:3001/mobile-execution-environment',
despite these not being used (testing only) they were causing the sonar lint to fail with security issues so I chose to comment them out in order to preserve this knowledge but also fix the lint.

2023-12-12 04:04 UTC, owencraston commented on app/core/Snaps/location/location.ts
> +export function detectSnapLocation(
the snaps controller accepts this function as a param. The duplication is mostly due to me reimplementing  the NPM class.

2023-12-12 08:59 UTC, FrederikBolding commented on app/core/Engine.ts
> +        'ExecutionService:getRpcRequestHandler',
```suggestion
```

This action does not exist anymore.

2023-12-12 09:00 UTC, FrederikBolding commented on app/core/Engine.ts
> +        requireAllowList,
```suggestion
        requireAllowlist,
```
This is typoed

2023-12-12 21:04 UTC, tommasini reviewed
Engine, RpcMethodMiddleware, EngineService, BackgroundBridge and Engine LGTM!

Cool thing that we use code fencing only for snaps and this way we can create easily other feature to include on the diferent featureSet! 
Awesome work going on 🚀

2023-12-12 23:29 UTC, owencraston commented
[e2e smoke test passed](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/dcaaa896-5313-4c87-9f6e-bff67a06f05e)

2023-12-12 23:33 UTC, gantunesr approved these changes, later dismissed
The overall code looks good to me, there are a lot of improvements to be done but we need to take into consideration that this is the first iteration of the code working and this is a great step into opening the snaps platform in the mobile app to the dev community. Since it is behind code fencing I don't have any reason to not merge it as it is and start working on smaller refactors that can be shipped faster and stop dedicating time into constant rebases.

The comments I left in the PR are suggestion I'd like to see done but I don't mind it being addressed in a follow up PR.

To do in a follow up PR:
  - Address pending comments
  - Add unit tests to all files in `core/Snaps` 
  - The `Engine` is getting too big, this code would be a good candidate to break it down to another file

Great work @owencraston 🎉 🚢

2023-12-12 23:33 UTC, gantunesr commented on app/core/Snaps/WebviewPostMessageStream.ts
> +  }
Would be good to add a more descriptive comment on the reason this method is not doing anything, IIRC it is because we don't want to kill the stream that communicates with the execution environment. We can also remove the console log or also update the message inside

2023-12-12 23:33 UTC, gantunesr commented on app/core/Snaps/WebviewPostMessageStream.ts
> +    //this._targetWindow.onMessage = this._onMessage;
nit
```suggestion
```

2023-12-12 23:33 UTC, gantunesr commented on app/core/Snaps/WebviewPostMessageStream.ts
> +    const data = JSON.parse(message.data);
Should we add a try-catch here in case the data is not compatible with the `parse` method?

2023-12-12 23:33 UTC, gantunesr commented on app/core/Snaps/WebviewExecutionService.ts
> +  #snapDuplexMap: SnapDuplex[];
Just noticed this is declared as an array but then we use it as a object, it should be updated as `#snapDuplexMap: Record<string, SnapDuplex>` or `#snapDuplexMap: Map<string, SnapDuplex>`

2023-12-12 23:33 UTC, gantunesr commented on app/core/Snaps/SnapWebviewPostMessageStream.ts
> +    );
Lets consider removing these logs to not pollute our dashboards. I don't see value on having them

2023-12-12 23:55 UTC, owencraston commented on app/core/Snaps/WebviewPostMessageStream.ts
> +    const data = JSON.parse(message.data);
Unless we plan to perform some logic in this catch, (other than throw) there is no need to wrap this in a try catch since if the parse fails it will throw. Doing this actually triggers a lint rule for the useless catch.
<img width="453" alt="Screenshot 2023-12-12 at 3 55 04 PM" src="https://github.com/MetaMask/metamask-mobile/assets/22918444/c66f15a8-8377-4940-a00d-5f3603383e8e">

2023-12-12 23:55 UTC, Jonathansoufer commented on app/components/Approvals/InstallSnapApproval/InstallSnapApproval.tsx
> +  const getSnapName = (request: any): string => {
I'm pretty sure this request has a type other than `any`. We should try as much as we can to avoid it. Minor stuff, but worth to mention.

2023-12-12 23:58 UTC, gantunesr commented on app/core/Snaps/WebviewPostMessageStream.ts
> +    const data = JSON.parse(message.data);
Yeah, I was leaning into handling it in a better way than just throwing an error.

2023-12-13 00:16 UTC, Jonathansoufer commented on app/components/Views/Snaps/SnapsSettingsList/SnapsSettingsList.tsx
> +const testSnaps = {
Is this kept due this PR being the first big move into mobile snaps and its intended to be removed in future iterations?

2023-12-13 00:25 UTC, Jonathansoufer commented on app/components/Views/Snaps/components/SnapPermissions/SnapPermissions.tsx
> +
I think this file could easily have most of the methods decoupled into another file and imported here, instead of mixing logic and UI that much.

2023-12-13 00:27 UTC, Jonathansoufer commented on app/core/Snaps/SnapBridge.ts
> +  getRPCMethodMiddleware: (args: any) => any;
Too many usage of `any` types here.

2023-12-13 00:31 UTC, Jonathansoufer approved these changes, later dismissed
Excellent work putting all this together @owencraston ! Minor comments of mine, but approved since they can be addressed in a follow up PR.

2023-12-13 00:55 UTC, owencraston commented on app/core/Snaps/location/npm.ts
> +}
🤦

2023-12-13 01:16 UTC, owencraston commented on app/core/Snaps/WebviewPostMessageStream.ts
> +  }
I removed almost all instances of Logger.log().

2023-12-13 01:17 UTC, owencraston commented on app/core/Snaps/location/fetch.ts
> +};
I modified this to throw an error. if this fails we cannot proceed.

2023-12-13 01:17 UTC, owencraston commented on patches/@metamask+post-message-stream+7.0.0.patch
> +  */
👍

2023-12-13 01:19 UTC, owencraston commented on app/core/Snaps/WebviewPostMessageStream.ts
> +    const data = JSON.parse(message.data);
I cant think of the correct behaviour if this parse fails. I don't think we would be able to proceed without the message data.

2023-12-13 01:42 UTC, owencraston commented on app/core/Snaps/WebviewExecutionService.ts
> +  #snapDuplexMap: SnapDuplex[];
I chose a map since it seems to be slightly more applicable here and is slightly more performant.

2023-12-13 01:45 UTC, owencraston commented on app/components/Approvals/InstallSnapApproval/InstallSnapApproval.tsx
> +  const getSnapName = (request: any): string => {
Looking at the return type it is of type `ApprovalRequest<any>` so I will change the typing to match that. As far as moving this to a util, while this is not a bad idea, this method of getting the snap name is only applicable to the approval flow. In other areas of the code we can simple extract this from the snaps controller itself so I do not think this function would be useful outside of this file.

2023-12-13 01:48 UTC, owencraston commented on app/components/Views/Snaps/SnapsSettingsList/SnapsSettingsList.tsx
> +const testSnaps = {
I was thinking of keeping it for testing but since this is main and I do not want to risk it I will remove. Thank you.

2023-12-13 02:02 UTC, owencraston commented on app/components/Views/Snaps/components/SnapPermissions/SnapPermissions.tsx
> +
While I do agree, most of these files functions are specific to the UX of the snaps permissions and if we moved them outside of this file we would no longer be able to wrap them in a useCallback which could lead to a degradation in performance. I think that the coin derivation logic should be extracted into the snaps utils and then we can import it from there in a future pr.

2023-12-13 02:05 UTC, owencraston commented
[e2e regression test passed](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/1fc341b5-bcac-45f5-8ef2-6899737c48bd)

2023-12-13 02:07 UTC, gantunesr approved these changes

2023-12-13 02:09 UTC, owencraston commented on app/core/Snaps/SnapBridge.ts
> +  getRPCMethodMiddleware: (args: any) => any;
Lets address this when we migrate to your new execution env.

2023-12-13 02:31 UTC, merged