Feat: Use new Segment implementation in onboarding steps (Batch 3 of 4)
MetaMask/metamask-mobile pull request #7990
Opened 2023-12-01 23:16 UTC by NicolasMassart

## **Description**

1. What is the reason for the change?
  Implement the New Segment metrics system created in PR #7520 in the onboarding steps.

2. What is the improvement/solution?
  - Initialise MetaMetrics on app start without removing Analytics yet as we still uses it outside of onboarding
  - Replace calls to Analytics with calls to MetaMetrics in all components involved in onboarding screens (see [`OnboardingNav`](https://github.com/MetaMask/metamask-mobile/blob/feat%2F1275_segment_onboarding_impl/app/components/Nav/App/index.js#L122-L175) in `app/components/Nav/App/index.js`)
  - Fix onboarding events queue usage in `app/components/UI/OptinMetrics/index.js`
  - Update Opt-on/Opt-out in onboarding and Security Settings
  - Add TODOs in app/components/Views/Settings/SecuritySettings/Sections/DeleteMetaMetricsData.tsx for Deletion task to come in next batch PR (see issue https://github.com/MetaMask/mobile-planning/issues/1403)
  - Extract Analytics User profil properties in UserProfileMetaData util and inject it in MetaMetrics identify request alongside device metadata
 

## **Related issues**

Fixes https://github.com/MetaMask/mobile-planning/issues/1275

## **Manual testing steps**

### Scenario 1: Onboarding with optin
### Scenario 2: Onboarding with optout

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-12-04 23:24 UTC, tommasini requested changes
Any reason that I'm missing of why we are only getting the instance on the CTA functions instead of on the component level?

2023-12-07 18:09 UTC, NicolasMassart commented on app/components/Views/ChoosePassword/index.js
> +    InteractionManager.runAfterInteractions(async () => {
Good catch. Will do that, thanks @frankvonhoven !

2023-12-08 18:38 UTC, NicolasMassart commented on app/components/Views/ChoosePassword/index.js
> +    InteractionManager.runAfterInteractions(async () => {
I created a `trackAfterInteractions` utility function.

2023-12-08 20:11 UTC, frankvonhoven approved these changes
Looks good 👍 Thanks for making that helper :)

2023-12-08 21:39 UTC, merged