chore: add unit tests to sdk connect handlers
MetaMask/metamask-mobile pull request #8005
Opened 2023-12-05 14:39 UTC by omridan159

## **Description**

 Add unit tests to SDKConnect handlers to make the code more stable and reliable
 
## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-12-06 04:51 UTC, abretonc7s requested changes, later dismissed
Didn't go over all the tests but overall would need to change the cast using as with the using real types in the variables declarations

2023-12-06 04:51 UTC, abretonc7s commented on app/core/SDKConnect/handlers/checkPermissions.test.ts
> +  let connection = {} as unknown as Connection;
probably should use corrct types here

2023-12-06 04:51 UTC, abretonc7s commented on app/core/SDKConnect/handlers/checkPermissions.test.ts
> +  let connection = {} as unknown as Connection;
Just implement as a partial for what is needed for the unit test:
```
let connection: Partial<Connection> = ...
```

2023-12-06 04:51 UTC, abretonc7s commented on app/core/SDKConnect/handlers/checkPermissions.test.ts
> +  } as unknown as typeof Engine;
Did you check on the test files in the codebase, they may have already implemented Engine?

2023-12-06 04:51 UTC, abretonc7s commented on app/core/SDKConnect/handlers/handleConnectionReady.test.ts
> +    } as OriginatorInfo;
let's avoid the as Casting and try to use real types

2023-12-06 08:13 UTC, omridan159 commented on app/core/SDKConnect/handlers/checkPermissions.test.ts
> +  let connection = {} as unknown as Connection;
We can't do that cause then we get:
Type 'Partial<Connection>' is not assignable to type 'Connection'.
When we try to pass it to the `checkPermissions` params...

2023-12-06 08:15 UTC, omridan159 commented on app/core/SDKConnect/handlers/checkPermissions.test.ts
> +  } as unknown as typeof Engine;
I have checked now, and I didn't saw something...

2023-12-06 09:22 UTC, deeeed approved these changes

2023-12-07 11:41 UTC, andreahaku approved these changes
LGTM

2023-12-12 09:03 UTC, merged