test: Batch 4 Remove all instances of strings in TestID property in the app code
MetaMask/metamask-mobile pull request #8014
Opened 2023-12-06 13:09 UTC by SamuelSalas

## **Description**

Replace all string definitions used for testIDs. These files should no longer selector strings in the TestID prop:

- app/components/Views/AccountBackupStep1/index.js
- app/components/Views/AccountBackupStep1B/index.js
- app/components/Views/AddAsset/AddAsset.tsx
- app/components/Views/AddBookmark/index.js
- app/components/Views/AddressQRCode/index.js
- app/components/Views/ChoosePassword/index.js
- app/components/Views/Collectible/index.js

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**
Smoke test run: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/6cb82fee-c55a-4c6b-a5a6-926eba229dd0
Regression test run: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/ef0b5a0b-171b-4819-ad4b-7f598fee427b
Appium test run: https://app.bitrise.io/build/39801a05-be41-4010-9c6c-8ef85b26b732

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-12-07 16:37 UTC, cortisiko requested changes
left a few comments @SamuelSalas

2023-12-07 16:37 UTC, cortisiko commented on app/components/Views/ManualBackupStep3/index.js
> -          confirmTestID={ManualBackUpStep3SelectorsIDs.DONE_BUTTON}
Is there a reason why you remove this ID?

2023-12-07 17:18 UTC, SamuelSalas commented on app/components/Views/ManualBackupStep3/index.js
> -          confirmTestID={ManualBackUpStep3SelectorsIDs.DONE_BUTTON}
Not being used at the moment on Unit or Detox tests.

2023-12-07 17:18 UTC, SamuelSalas commented on app/components/Views/ManualBackupStep2/index.js
> -        confirmTestID={ManualBackUpStep2SelectorsIDs.CONTINUE_BUTTON}
Not being used at the moment on Unit or Detox tests.

2023-12-07 17:18 UTC, SamuelSalas commented on app/components/Views/ManualBackupStep2/index.js
> -          testID={ManualBackUpStep2SelectorsIDs.CONTAINER}
Not being used at the moment on Unit or Detox tests.

2023-12-07 17:19 UTC, SamuelSalas commented on app/components/Views/ManualBackupStep1/index.js
> -        confirmTestID={ManualBackUpStep1SelectorsIDs.CONTINUE_BUTTON}
Not being used at the moment on Unit or Detox tests.

2023-12-07 17:19 UTC, SamuelSalas commented on app/components/Views/ManualBackupStep1/index.js
> -              testID={ManualBackUpStep1SelectorsIDs.VIEW_BUTTON}
Not being used at the moment on Unit or Detox tests.

2023-12-07 17:23 UTC, SamuelSalas commented on e2e/selectors/Onboarding/ManualBackUp.selectors.js
> +export const ManualBackUpSelectorsIDs = {
That makes sense. The reason why I decided to remove a couple of testIDs and move them into just one file was because more than one of the ManualBackUp views. I can restore the testIDs remove, but I'd recommend to change slightly the name to better differentiate between each file more easily.

2023-12-07 18:23 UTC, cortisiko commented on e2e/selectors/Onboarding/ManualBackUp.selectors.js
> +export const ManualBackUpSelectorsIDs = {
Sure that sounds like a good plan to me. To keep things simple, how about renaming to ManualBackUpStepsSelectorsIDs

2023-12-07 18:24 UTC, cortisiko commented on app/components/Views/ManualBackupStep2/index.js
> -          testID={ManualBackUpStep2SelectorsIDs.CONTAINER}
eh, lets restore this guy. There might be use for it in the future.

2023-12-07 18:24 UTC, cortisiko commented on app/components/Views/ManualBackupStep2/index.js
> -        confirmTestID={ManualBackUpStep2SelectorsIDs.CONTINUE_BUTTON}
eh, lets restore this guy. There might be use for it in the future.

2023-12-07 18:24 UTC, cortisiko commented on app/components/Views/ManualBackupStep3/index.js
> -          confirmTestID={ManualBackUpStep3SelectorsIDs.DONE_BUTTON}
eh, lets restore this guy. There might be use for it in the future.

2023-12-08 23:39 UTC, cortisiko approved these changes

2023-12-13 16:19 UTC, merged