Feat: use Segment (batch)
MetaMask/metamask-mobile pull request #8067
Opened 2023-12-11 16:02 UTC by NicolasMassart

## **Description**

## **Related issues**

Fixes https://github.com/MetaMask/mobile-planning/issues/1129

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-01-25 20:13 UTC, worldlyjohn commented on app/core/Analytics/MetaMetrics.ts
> +        proxy: process.env.SEGMENT_PROXY_URL as string,
are we planning to use a separate endpoint for PROD from the rest? (cc @vu1n)

2024-01-29 18:34 UTC, NicolasMassart commented on app/core/Analytics/MetaMetrics.ts
> +        proxy: process.env.SEGMENT_PROXY_URL as string,
Yes if we have one provided. The endpoint is provided by env variable so it can be different depending on the build type.

2024-02-16 19:42 UTC, sethkfman commented on app/core/Analytics/MetaMetrics.constants.ts
> +  'https://proxy.metafi-dev.codefi.network/segment/v1';
This should be updated to the prod URL.

2024-02-19 18:15 UTC, tommasini approved these changes
AMAZING WORK! LGTM! Just left a nit pick that i've found but it's okay to merge it without it!

2024-02-19 18:15 UTC, tommasini commented on app/components/Views/Settings/SecuritySettings/Sections/DeleteMetaMetricsData.tsx
> +        isDataDeletionAvailable() ? (
We could call this function only once and have the variable being used here

2024-02-19 18:15 UTC, tommasini commented on app/components/Views/Settings/SecuritySettings/Sections/DeleteMetaMetricsData.tsx
> +      buttonDisabled={!isDataDeletionAvailable()}
And here

2024-02-19 18:31 UTC, tommasini requested changes
Actually it seems that the unit tests are failing! We will need to address that

2024-02-20 10:41 UTC, tommasini commented on app/components/Nav/App/index.js
> +      await MetaMetrics.getInstance().configure();
No more Logger log with the instance id?

2024-02-20 10:41 UTC, tommasini commented on app/core/Analytics/MetaMetrics.ts
> +        Logger.log(`MetaMetrics configured with ID: ${this.metametricsId}`);
Cool!

2024-02-20 10:43 UTC, tommasini submitted a review, later dismissed
LGTM!

2024-02-20 13:17 UTC, tommasini approved these changes
LGTM!

2024-02-20 14:36 UTC, merged