E2e: Refactor Smoke Tests to Execute Across Multiple Virtual Machines on Bitrise
MetaMask/metamask-mobile pull request #8083
Opened 2023-12-12 22:53 UTC by Andepande

## **Description**
- This PR refactors smoke test execution on Bitrise into parallel runs across multiple virtual machines, optimising test runtime.
- 

## **Related issues**

Fixes: https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/gh/metamask/metamask-mobile/7844

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-12-15 04:20 UTC, cortisiko requested changes
small comments

2023-12-15 04:20 UTC, cortisiko commented on bitrise.yml
> +                echo "TEST_SUITE_TAG value is: $TEST_SUITE_TAG"
You have this in for debugging purposes? If not probably remove

2023-12-15 04:20 UTC, cortisiko commented on bitrise.yml
>                    TEST_SUITE="Smoke"
we no longer use this flag anymore, perhaps remove it

2023-12-15 16:52 UTC, Andepande commented on bitrise.yml
> +                echo "TEST_SUITE_TAG value is: $TEST_SUITE_TAG"
I'll keep in for now as I'm using it to pass the tag type from the bitrise env variable, once I work on condensing the regression I'll refine it some more

2023-12-19 21:28 UTC, sethkfman approved these changes, later dismissed
LGTM

2023-12-21 16:54 UTC, cortisiko approved these changes

2023-12-21 17:56 UTC, merged