fix: fix padding tab, should be 16px
MetaMask/metamask-mobile pull request #8146
Opened 2023-12-18 18:13 UTC by salimtb

## **Description**

Currently segmented controls on wallet view, import token view, network view have no paddings on the side. Need to match designs and have 16px paddings on each side.
On import token view and network view, copies for segments are in all caps. Should be using normal sentence case (e.g. "Custom networks" instead of "CUSTOM NETWORKS"), font "Body-MD-Medium", and color "text/default" & "primary/default".

## **Related issues**

Fixes: [#8060](https://github.com/MetaMask/metamask-mobile/issues/8060) 

## **Manual testing steps**
1. Wallet view: open the app and you are on the default wallet view.
2. Import token view: click on "Import tokens" on the wallet view
3. Network view: click on the network picker on the top of the wallet view, then click "Add Network"

## **Screenshots/Recordings**

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/26223211/de19499d-d888-47f9-a5c3-a37fc769a53d

### **After**

https://github.com/MetaMask/metamask-mobile/assets/26223211/1d84a00b-e24b-46fd-a0ca-0f8ce0ca08bf

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2023-12-18 18:21 UTC, brianacnguyen commented
that looks a lot cleaner! from what I can see from the design link below, do you think you can align the vertical padding, font styles, font colors, and bottom border color of each tab item? 
https://www.figma.com/file/9s1RkDrGQYNhtJrsqvfNJW/MC-(Multichain)-mobile-v0.75?type=design&node-id=9-6412&mode=design&t=bb3vLdTNM6W0VdJp-0

2023-12-18 18:25 UTC, brianacnguyen requested changes
that looks a lot cleaner! from what I can see from the design link below, do you think you can align the vertical padding, font styles, font colors, and bottom border color of each tab item?
https://www.figma.com/file/9s1RkDrGQYNhtJrsqvfNJW/MC-(Multichain)-mobile-v0.75?type=design&node-id=9-6412&mode=design&t=bb3vLdTNM6W0VdJp-0

2023-12-18 20:53 UTC, wachunei commented
<img width="300" src="https://github.com/MetaMask/metamask-mobile/assets/1024246/2f5f4874-d325-4e5e-a4bf-1b4a2a8bdac8" />
<img width="300" src="https://github.com/MetaMask/metamask-mobile/assets/1024246/e7735405-6b4f-44f0-b663-b31c3e35cc8b" />

The app currently shows the scroll view edge to edge, this solution introduces a wrapper that changes this behavior, adding a padding to the main views. I just want to point this out and make sure DS team is ok with this.

2023-12-19 15:04 UTC, salimtb commented
> that looks a lot cleaner! from what I can see from the design link below, do you think you can align the vertical padding, font styles, font colors, and bottom border color of each tab item? https://www.figma.com/file/9s1RkDrGQYNhtJrsqvfNJW/MC-(Multichain)-mobile-v0.75?type=design&node-id=9-6412&mode=design&t=bb3vLdTNM6W0VdJp-0
hey @brianacnguyen 
just added your suggestion in a separated commit, regarding the vertical padding, that's not possible to override this value because it's coming from the library use ( see this link [here](https://github.com/ptomasroos/react-native-scrollable-tab-view/blob/master/DefaultTabBar.js#L103) ) , do you have any suggestion ?

2023-12-19 15:22 UTC, salimtb commented
> that looks a lot cleaner! from what I can see from the design link below, do you think you can align the vertical padding, font styles, font colors, and bottom border color of each tab item? https://www.figma.com/file/9s1RkDrGQYNhtJrsqvfNJW/MC-(Multichain)-mobile-v0.75?type=design&node-id=9-6412&mode=design&t=bb3vLdTNM6W0VdJp-0

@brianacnguyen  done

2023-12-19 16:47 UTC, chrisleewilcox commented on app/components/Views/AddAsset/AddAsset.styles.ts
> +      paddingHorizontal: 16,
Instead of hardcoding pixel values can we have a more responsive value based on screen dimensions?  Like 0.5% of screen width?  May need to reach out to design team for guidance but in general we should avoid hardcoded pixel values.

2023-12-19 16:59 UTC, brianacnguyen commented on app/components/Views/AddAsset/AddAsset.styles.ts
> +      paddingHorizontal: 16,
we're in the process of introducing space tokens, but, for now, we're still using pixel units for spacing

2023-12-19 17:00 UTC, brianacnguyen commented
> <img alt="" width="300" src="https://private-user-images.githubusercontent.com/1024246/291405543-2f5f4874-d325-4e5e-a4bf-1b4a2a8bdac8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDUzMTAsIm5iZiI6MTcwMzAwNTAxMCwicGF0aCI6Ii8xMDI0MjQ2LzI5MTQwNTU0My0yZjVmNDg3NC1kMzI1LTRlNWUtYTRiZi0xYjRhMmE4YmRhYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTY1NjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTM0MzhhMWVjYTA5OWY3OTEwNGZlYTBlNmE4OWUxMGNhZTg4NzBlYTY4ZWRkMTZlZGRmMjMwZWZmYjcwODg5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.enIsFXosAZqdiFOW_vXyfLUZOtHYJ6iOBDbcTxhMQLA"> <img alt="" width="300" src="https://private-user-images.githubusercontent.com/1024246/291405558-e7735405-6b4f-44f0-b663-b31c3e35cc8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDUzMTAsIm5iZiI6MTcwMzAwNTAxMCwicGF0aCI6Ii8xMDI0MjQ2LzI5MTQwNTU1OC1lNzczNTQwNS02YjRmLTQ0ZjAtYjY2My1iMzFjM2UzNWNjOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTlUMTY1NjUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQwODU1NTk4Yzg4NGJkNDY2YWI1NjM0YzNhODljM2E2NGIwYjA5NDJjODI3NWI2OTRjNGQzYTc2YWI4OTg0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ebYTkdXSaO_4v_YFjiBLhQm3fTK3Tjsot4Fud2I9hoE">
> The app currently shows the scroll view edge to edge, this solution introduces a wrapper that changes this behavior, adding a padding to the main views. I just want to point this out and make sure DS team is ok with this.

Thank you for notifying me about this. Can you double check with the designer first to make sure it's what the designer want?
If it isn't what the designer want and the padding is meant to be added to the tabs only, you can move the `View` with the added horizontalPadding to the `renderTabBar` to isolate the paddings to the tab bar only

2023-12-21 18:18 UTC, yanrong-chen commented
Hi @salimtb - Thank you for checking with me. Ideally the goal is to add paddings to tab bar only as @brianacnguyen suggested.

2024-01-03 12:05 UTC, salimtb commented
the changes suggested after the design review are done , i also updated the recorded video
cc @brianacnguyen @yanrong-chen

2024-01-08 16:00 UTC, brianacnguyen commented on app/components/Views/AddAsset/AddAsset.styles.ts
> +      ...fontStyles.normal,
```suggestion
      ...params.theme.typography.sBodyMD
```

2024-01-08 16:01 UTC, brianacnguyen reviewed
Everything looks good! Just 1 last comment regarding text style

2024-01-08 16:01 UTC, brianacnguyen commented on app/components/Views/AddAsset/AddAsset.styles.ts
> +      ...fontStyles.normal,
instead of manually defining all the text styles, just use `params.theme.typography.sBodyMD`

2024-01-08 22:08 UTC, salimtb commented on app/components/Views/AddAsset/AddAsset.styles.ts
> +      ...fontStyles.normal,
with the suggestion that you made , i'm  seeing that `fontWeight` property in `params.theme.typography.sBodyMD` is not one of the accepted values for fontWeight in React Native.
In React Native, the fontWeight property expects one of the following string values: "normal", "bold", "100", "200", "300", "400", "500", "600", "700", "800", "900", or undefined.
that's why my fix was to do:

`
textStyle: {
      textTransform: 'capitalize',
      ...params.theme.typography.sBodyMD,
      fontWeight: '500',
    },
`

2024-01-09 15:22 UTC, brianacnguyen approved these changes

2024-01-09 18:57 UTC, merged