feat: add privacy toggle
MetaMask/metamask-mobile pull request #8234
Opened 2024-01-10 13:31 UTC by salimtb

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-01-10 15:24 UTC, salimtb commented
Figma - https://www.figma.com/file/t4Zc6ZOA9Urw8POrCReEam/Privacy-epic-%26-update-security-and-privacy-in-settings?type=design&node-id=436-132218&mode=design&t=44JW6eob6cTiA6KB-0
Toggle scenarios - Toggle scenarios - https://docs.google.com/presentation/d/16s_2-kViYyQBAI6WMQRuro8qLPq2Oc3whZ1tlIO68bo/edit#slide=id.g25ba5b08687_1_0

2024-01-10 19:36 UTC, Cal-L commented
@salimtb There was a ticket 2 of 3 prior to this iteration. Is it correct to say those changes are also implemented in this PR? When you have the chance, could you also verify that the network verification errors are still being respected when adding network from both custom and dapps? A video would be fine

2024-01-10 21:21 UTC, tommasini requested changes
Awesome work!

Just some comments:
* It seems that comparing it with figma is missing bold on the copy `Settings -> Security and Privacy` part
![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/ac9a41fa-4897-4f44-952d-b6c648b4dae2)
![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/1b75ee22-e3d7-4a04-8fc3-a4ce4080cda1)

* Can we also have a scenario with the recordings of the scenario with warning alerts?
* - When added a chain via Dapp
* - When adding a chain via Custom Network

* It seems that I started the first PR of this Batch and I missed it or it was added to the Figma after, but the banners are missing a cross icon to be able to closed on the right side :( , let me know if you can add it!
Figma:
![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/f725da13-8903-41b9-b2ff-c2f4d989d1c0)

[Recording](https://recordit.co/U7eo17r4qD) from the first batch [PR](https://github.com/MetaMask/metamask-mobile/pull/7701)

* Also it makes sense to add a condition before we check the networks [here](https://github.com/MetaMask/metamask-mobile/blob/616e3b0fbfd52eb3987e88d2975083fac8cbace6/app/core/RPCMethods/wallet_addEthereumChain.js#L237) , we do not want to fetch anything if the toggle is disabled

NIT:
Do you think it would be better extracting the contextual sheet of enabling/disabling the new privacy toggle would be better for easier change/reusability on the future?

2024-01-10 21:28 UTC, tommasini commented
Also wanted to bring a product question, I can see that on the [slide 28](https://docs.google.com/presentation/d/16s_2-kViYyQBAI6WMQRuro8qLPq2Oc3whZ1tlIO68bo/edit#slide=id.g25ba5b08687_1_133) we do show intention to show the warning banners of the network when adding it from our popular list. 
I'm wondering if that should be the case, since we control all the add network flow from the networks on our popular list (all that networks data is hardcoded [here](https://github.com/MetaMask/metamask-mobile/blob/f06356218ccdefb471c8d0d15b38bcffe47cd576/app/util/networks/customNetworks.tsx#L5))

It seems just new noise to the user, let me know your thoughs

cc: @hesterbruikman  @alfeng6

2024-01-11 09:45 UTC, salimtb commented
> @coreyjanssen I'm seeing some copy inconsistency. Can you confirm what copy we want to use?
> 
> @salimtb I'd suggest to wait on confirmation from @coreyjanssen before creating a translations PR.
> 
> ![Frame 1](https://private-user-images.githubusercontent.com/35233054/295860884-4217ac52-7f25-4157-b9b4-8a33374eae80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjU4NDQsIm5iZiI6MTcwNDk2NTU0NCwicGF0aCI6Ii8zNTIzMzA1NC8yOTU4NjA4ODQtNDIxN2FjNTItN2YyNS00MTU3LWI5YjQtOGEzMzM3NGVhZTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA5MzIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYTk2MzMwMGNkMjNiOTczYTk2MGRhZWFiYzZlN2VkMjFlMzMzZDc1MmYxMDIyZDg1N2U2NTFhMDE3YTJmY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zZ_eWfbX3KDzVuBoFqfjLsBICQDXC_myieOUdqiBHWc)

hey @hesterbruikman ,
does the image you shared appear when adding a network from an external dapp or when adding from tab popular ?
because i'm seeing that the title is "Allow this site to add a network" , i'll share another recorded video to include this scenario as well ( add network from external dapp )

2024-01-11 09:54 UTC, hesterbruikman commented
> Also wanted to bring up a product question, I can see that on [slide 28](https://docs.google.com/presentation/d/16s_2-kViYyQBAI6WMQRuro8qLPq2Oc3whZ1tlIO68bo/edit#slide=id.g25ba5b08687_1_133) we do show intention to show the warning banners of the network when adding it from our popular list. I'm wondering if that should be the case, since we control all the add network flow from the networks on our popular list (all that networks data is hardcoded [here](https://github.com/MetaMask/metamask-mobile/blob/f06356218ccdefb471c8d0d15b38bcffe47cd576/app/util/networks/customNetworks.tsx#L5))
> 
> It seems just new noise to the user, let me know your thoughts
> 
> cc: @hesterbruikman @alfeng6

@tommasini Let me see if I understand the logic you're proposing correctly:
- GIVEN User adds Custom Network (manually)
- AND Details of Custom Network Details match those of hardcoded popular network list
- THEN Don't show warning

If so I agree. And we can probably makes this smarter as a next step as well. This would be the sequence of implementation and logic:
- **Warn** - Any Custom Network based on Chain ID verification [CURRENT BATCH]
- **Promote** - Auto-populate Network details based on Chain ID (allows editing) - Current batch - Warn for any Custom Network based on Chain ID verification [TICKET OF INCIDENT 337 [#1347](https://github.com/MetaMask/mobile-planning/issues/1347)] 
- **Optimise for Popular Networks** - Hide warning when Custom Network is added where details match Popular Network details [NO TICKET]
- **Recommend** - Propose Popular Network hardcoded network details when custom is added with same ID of Popular Network list [NO TICKET]

@alfeng6 Wdyt? I do have reservation about my own proposal as a last step. UX improvement, but we should generally avoid making strong recommendations

2024-01-11 10:21 UTC, hesterbruikman commented
> hey @hesterbruikman ,
> does the image you shared appear when adding a network from an external dapp or when adding from tab popular ?
> because i'm seeing that the title is "Allow this site to add a network" , i'll share another recorded video to include this scenario as well ( add network from external dapp )

Good callout @salimtb ! Here's an updated side-by-side. It's the "Does not endorse custom networks or their security" copy that is new to me
![Frame 1](https://github.com/MetaMask/metamask-mobile/assets/35233054/56c2185b-4af3-4e15-9732-0ecceb6eb3ca)

2024-01-11 17:05 UTC, coreyjanssen commented
Good catch @hesterbruikman @salimtb. The copy from the Figma (`MetaMask doesn't verify custom networks, so only approve networks you trust.`) is what we should be using. 

However, would it be possible to modify the title on the **Add from dapp** screen to align with the **Add from settings?** 

`Add network` instead of `Allow this site to add a network?`

2024-01-19 16:25 UTC, alfeng6 commented
@hesterbruikman I agree we should hide the warning when Custom Network is added where details match Popular Network details. I'm wondering for recommendations, which details will be assessed for us to be confident we can recommend a particular network? I know for tokens, if we detect a known contract address, we'll prepopulate the rest of the token details.

2024-01-22 09:43 UTC, hesterbruikman commented
> @hesterbruikman I agree we should hide the warning when Custom Network is added where details match Popular Network details. I'm wondering for recommendations, which details will be assessed for us to be confident we can recommend a particular network? I know for tokens, if we detect a known contract address, we'll prepopulate the rest of the token details.

In my mind this is all based on chainID. For any chainID, we verify network details via chainid.network or equivalent. If chainID matches Popular Network list we suggest you to use network details as recorded for the Popular Networks. Does that make sense?

2024-01-23 00:57 UTC, Cal-L reviewed
Left some comments. Feel free to reach out and we can walk through them

2024-01-23 00:57 UTC, Cal-L commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> -                      onPress={this.addRpcUrl}
Could you elaborate on the change of behavior here? It used to add the network on add but toggling the the CustomNetwork now?

2024-01-23 00:57 UTC, Cal-L commented on app/components/UI/NetworkVerificationInfo/NetworkVerificationInfo.tsx
> +              textVariant: TextVariant.BodyMD,
The Button link variant doesn't have a textVariant property. It shows an error in the IDE

2024-01-23 00:57 UTC, Cal-L commented on app/components/UI/NetworkVerificationInfo/NetworkVerificationInfo.tsx
> +            color={DEFAULT_BUTTONLINK_LABEL_COLOR}
Remove this since the default color is primary already.

2024-01-23 00:57 UTC, Cal-L commented on app/components/UI/NetworkVerificationInfo/NetworkVerificationInfo.styles.ts
> +      fontSize: scaling.scale(18),
Replace font styles with typography from `theme`. You'll have to reference what Figma designs are using

2024-01-23 00:57 UTC, Cal-L commented on app/components/UI/NetworkVerificationInfo/NetworkVerificationInfo.styles.ts
> +      fontSize: scaling.scale(18),
That would mean removing fontStyles, fontSize, lineHeight and replacing those with typography. Look for ...typography in the codebase

2024-01-23 00:57 UTC, Cal-L commented on app/components/UI/NetworkVerificationInfo/NetworkVerificationInfo.styles.ts
> +      ...fontStyles.bold,
Use typography from theme instead

2024-01-23 00:57 UTC, Cal-L commented on app/components/UI/NetworkVerificationInfo/NetworkVerificationInfo.tsx
> +  const useSafeChainsListValidation = useSelector(
While the name is accurate, could we rename this to something like `safeChainsListValidationEnabled`. This would prevent confusion with hook naming conventions.

2024-01-24 15:10 UTC, salimtb commented on locales/languages/en.json
> +    "network_details_check": "Network details check",
hey @Cal-L ,
i just created the [PR](https://github.com/MetaMask/metamask-mobile/pull/8383) , can you pls check if i applied the right label. ?

2024-01-29 14:17 UTC, tommasini requested changes
Amazing work! Loved the recordings!
Let me know your thoughts I left some minor comments!

Also, I'm not sure but, probably with a slow internet, when accepting the safe network feature, I saw a small glitch on the UI (Basically the transition, between the message asking if the user wants to activate the safe network feature and the warnings of the network). 
Wondering if it makes sense to improve that with a loading state! This is not on the designs, but I would love to know your thoughts!

2024-01-29 14:17 UTC, tommasini commented on app/components/UI/NetworkModal/index.tsx
> +    if (!value) PreferencesController.setUseSafeChainsListValidation(value);
Is this condition really needed?

2024-01-29 14:17 UTC, tommasini commented on app/components/UI/NetworkModal/index.tsx
> +    if (!value) PreferencesController.setUseSafeChainsListValidation(value);
```suggestion

```

2024-01-29 14:17 UTC, tommasini commented on app/components/UI/NetworkVerificationInfo/NetworkVerificationInfo.tsx
> +    if (!value) PreferencesController.setUseSafeChainsListValidation(value);
```suggestion

```

2024-01-29 14:17 UTC, tommasini commented on app/components/UI/NetworkVerificationInfo/NetworkVerificationInfo.tsx
> +    if (!value) PreferencesController.setUseSafeChainsListValidation(value);
Also it seems that this function is used on other NetworkModal, would make sense to create an util and create a single unit test for this?
Let me know your thoughts!

2024-01-29 14:20 UTC, tommasini commented on app/components/UI/NetworkModal/index.tsx
>  const createStyles = (colors: ThemeColors) =>
Could we follow the pattern of components and extract the styles for a different file?

2024-01-30 10:01 UTC, salimtb commented
> Amazing work! Loved the recordings! Let me know your thoughts I left some minor comments!
> 
> Also, I'm not sure but, probably with a slow internet, when accepting the safe network feature, I saw a small glitch on the UI (Basically the transition, between the message asking if the user wants to activate the safe network feature and the warnings of the network). Wondering if it makes sense to improve that with a loading state! This is not on the designs, but I would love to know your thoughts!

hey @tommasini ,
it totally makes sense to implement a loader for me , this will give the users a better experience.
but i need product approve for that, there are still other tasks regarding this epic ( avoid scams ), so I'm going to talk to my product owner and the designer and ask if they can introduce it into the [MMASSETS-123](https://consensyssoftware.atlassian.net/browse/MMASSETS-123) task.

2024-01-30 10:03 UTC, tommasini commented
Awesome!!!

2024-01-30 16:35 UTC, tommasini submitted a review, later dismissed
LGTM!

2024-01-31 16:07 UTC, chrisleewilcox commented
Regression tests: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/dd61afc8-ab6b-48a7-9a07-aaeb58c61571

2024-02-01 05:38 UTC, chrisleewilcox requested changes
Hi @salimtb.  Our regression tests is consistently failing on iOS simulator with this branch.  Can you take a look?  The link to the regression test will show the test results.

![image](https://github.com/MetaMask/metamask-mobile/assets/6626407/24898c22-1fea-44c4-853f-61d3c5c234ef)

2024-02-02 10:33 UTC, salimtb commented
> Hi @salimtb. Our regression tests is consistently failing on iOS simulator with this branch. Can you take a look? The link to the regression test will show the test results.
> 
> Regression: https://app.bitrise.io/build/f60f7f47-a8cc-4647-8405-6d9d20627104
> 
> ![image](https://private-user-images.githubusercontent.com/6626407/301397487-24898c22-1fea-44c4-853f-61d3c5c234ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjU0NTEsIm5iZiI6MTcwNjg2NTE1MSwicGF0aCI6Ii82NjI2NDA3LzMwMTM5NzQ4Ny0yNDg5OGMyMi0xZmVhLTQ0YzQtODUzZi02MWQzYzVjMjM0ZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMDkxMjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDBjZTI0Nzg2NjE0MTI2NTBhZWNjYzM3MGQ5MDkxMDllODM5M2YwYjYwZjlhMDFjOTVlNDQ2NmFlZTI1ZTM2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NJCcgezw5RjgubhjZT_lQy4o16-YNfV38dMNyalLMZE)

hey @chrisleewilcox ,
the regression test was fixed , i just pushed a new commit for this.
to give you some clarification , the user flow has changed in the case of custom network ( see the two video below ) , we have an extra step now btw the moment when we feel the form with network informations and the moment when the network is added and the Network educational modal is displayed.
so some changes was required on the regression test and i just pushed them.

**Before**

https://github.com/MetaMask/metamask-mobile/assets/26223211/eb810410-5e3d-479f-a3e8-654f70be2db2

**After** 

https://github.com/MetaMask/metamask-mobile/assets/26223211/11340927-80e1-41eb-ab49-5cd59dfc954e

2024-02-03 17:53 UTC, chrisleewilcox commented
Hi @salimtb 
Thanks for looking into this.  Looks like the test is working on iOS but it's now failing for android device.  Looks like when adding a custom network for android device the approve and switch modal is not showing like it does for iOS.  These are the lines that fail in the tests.  Can you take an look and ensure that when adding a custom network the approve and switch views are shown for android devices?
I tested this locally and it took me awhile to notice this.  The test seems to be good as is and would pass once the fix for showing approve and switch views are shown for android.  Hope all this makes sense and reach out if you have any questions.

https://recordit.co/82bDXlPoXa

2024-02-06 18:07 UTC, chrisleewilcox approved these changes

2024-02-06 18:14 UTC, merged