Test/1452 refactor modal pages batch 2
MetaMask/metamask-mobile pull request #8257
Opened 2024-01-11 22:24 UTC by SamuelSalas

## **Description**
We are aiming to refactor the page objects in the modal folder so that they strictly follow the page object model pattern. This would aide in providing more readable and help standardize the way we create our tests. Because of the amount of files inside of the modal folder, the scope was divided into a batch of 4.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-01-12 00:22 UTC, cortisiko requested changes
left some comments

2024-01-12 00:22 UTC, cortisiko commented on e2e/specs/quarantine/deeplinks.failing.js
> +//const BINANCE_RPC_URL = 'https://bsc-dataseed1.binance.org';
remove comment

2024-01-12 00:22 UTC, cortisiko commented on e2e/specs/quarantine/deeplinks.failing.js
> +    //await NetworkApprovalModal.isNetworkURLVisible(BINANCE_RPC_URL);
remove comment

2024-01-12 00:22 UTC, cortisiko commented on e2e/specs/quarantine/deeplinks.failing.js
> +    //await NetworkApprovalModal.isChainIDVisible('137');
remove comment

2024-01-12 00:22 UTC, cortisiko commented on e2e/pages/modals/NetworkApprovalModal.js
> +  //static async isChainIDVisible(chainID) {
remove comments: line 26-32

2024-02-14 16:37 UTC, SamuelSalas commented
Regression Test run: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/701c4020-c70a-466c-8606-3c1066259c29
Smoke Test run: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/4e18f36a-cf2e-4eeb-bd1b-82b5ee1e55fc
Appium wdio test run: https://app.bitrise.io/build/9d369fcc-d944-48c2-a00f-0352d4961708

2024-02-14 20:40 UTC, cortisiko approved these changes
✅ ✅ ✅ ✅

2024-02-14 21:25 UTC, chrisleewilcox commented
Regression: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/3bedadae-3558-48ac-9f61-197febd26064

2024-02-15 06:48 UTC, Andepande approved these changes
LGTM

2024-02-15 16:49 UTC, merged