fix: update nft metadata on page refresh
MetaMask/metamask-mobile pull request #8348
Opened 2024-01-19 15:13 UTC by sahar-fehri

## **Description**

This PR fixes nft metadata refresh when the user refreshes the page

## **Related issues**

Fixes: https://consensyssoftware.atlassian.net/browse/MMASSETS-105

## **Manual testing steps**

1. Mint an NFT. (I used REMIX)
2. Go to NFT tab and import the NFT
3. You should be able to see the NFT image
4. Update the NFT image
5. Pull down the page to refresh and notice that the image is updated

## **Screenshots/Recordings**

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/10994169/c067c15a-1525-4cfc-98d6-492ec2cca4c8

### **After**

https://github.com/MetaMask/metamask-mobile/assets/10994169/78ca98b2-f071-4a7e-a73a-f9db390cf0ad

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-01-19 16:01 UTC, sahar-fehri commented on app/components/UI/CollectibleContracts/index.js
> -      NftController.removeNft(address, tokenId);
I do not have enough context on why we were doing a removeNft in this function;

2024-01-19 16:02 UTC, sahar-fehri commented on app/components/UI/CollectibleContracts/index.js
> +    (typeof collectible.tokenId === 'string' && !isNaN(collectible.tokenId));
Noticed that this shouldUpdateCollectibleMetadata fct is returning false when the tokenId is "2", i made an update so its handling the case where its a string number

2024-01-22 16:09 UTC, NicolasMassart reviewed
Nice work!
Test follows good testing practices and should provide good coverage of you refresh fixes.
I added some suggestion and questions, I'm curious to know more about reason for the removal of `removeNft`.

2024-01-22 16:09 UTC, NicolasMassart commented on app/components/UI/CollectibleContracts/index.test.tsx
> +      .mockImplementation(async () => undefined);
Could be simplified with:
```suggestion
    const spyOnCollectibles = jest
      .spyOn(allSelectors, 'collectiblesSelector')
      .mockReturnValueOnce(nftItemData)
      .mockReturnValueOnce(nftItemDataUpdated);
    const spyOnContracts = jest
      .spyOn(allSelectors, 'collectibleContractsSelector')
      .mockReturnValue(collectibleData);
    const spyOnAddNft = jest
      .spyOn(Engine.context.NftController, 'addNft')
      .mockImplementation(async () => undefined);
```

And so, with naming the spies, you could be able to clean them up at the end of the test:
```ts
    spyOnCollectibles.mockRestore();
    spyOnContracts.mockRestore();
    spyOnAddNft.mockRestore();
```

2024-01-22 16:42 UTC, chrisleewilcox requested changes
Hi @sahar-fehri looking forward to getting this merged.  Can you also provide recordings of this feature on android emulator?  We have different types of challenges with NFTs displaying properly on iOS and android.

2024-01-22 17:24 UTC, sahar-fehri commented on app/components/UI/CollectibleContracts/index.js
> -      NftController.removeNft(address, tokenId);
Here is how the UI looks like with  "NftController.removeNft(address, tokenId);"
 cc @tommasini  @NicolasMassart 

https://github.com/MetaMask/metamask-mobile/assets/10994169/8f9c4e54-cd21-4223-9014-97ceab1a96e9

2024-01-22 19:06 UTC, sahar-fehri commented
> Hi @sahar-fehri looking forward to getting this merged. Can you also provide recordings of this feature on android emulator? We have different types of challenges with NFTs displaying properly on iOS and android.

Hello @chrisleewilcox i have updated the video for Android in the description above, lemme know if anything 🙏

2024-01-22 19:18 UTC, sahar-fehri commented on app/components/UI/CollectibleContracts/index.test.tsx
> +    const { queryByTestId } = renderWithProvider(<CollectibleContracts />, {
Hello @NicolasMassart , initially i have tried the rerender(); but It was not working

So i switched to renderWithProvider

2024-01-23 06:32 UTC, chrisleewilcox commented
Smoke tests: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/d0d133e2-06db-43a9-b7f6-f48bdd5819f0
Regression tests: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/b91a0fdb-9c95-4a03-847b-7e172d417b2e

2024-01-23 06:33 UTC, chrisleewilcox submitted a review, later dismissed
LGTM

2024-01-23 11:07 UTC, tommasini requested changes

2024-01-23 11:07 UTC, tommasini commented on app/components/UI/CollectibleContracts/index.js
> -      NftController.removeNft(address, tokenId);
Hey Sahar, indeed it seems that it's creating some flakiness on the rendering of the component, good catch!
It should be on the description why there is a `removeNft`, sorry!

The `removeNft` is there because the NFT can be imported without metadata from external APIs. The user has the possibility on `Security & Privacy` on `Settings`, to opt-out from `Display NFT Media` and `IPFS Gateway`

The user will need to be able to still fetch the NFT from the chain directly if either of these options are opt-in, but it wouldn't be fetched part of the NFTMetadata.

For context:

We can upload Nfts from 3 different sources
* External APIs (We use open sea)
* IPFS
* Blockchain

The user on the Settings can opt-out and decide that don't want to import the NFT from IPFS or External APIs, when this happens, multiple things can happen, one for example is:
* An user import an NFT without external APIs
* That NFTMetadata do not have the tokenURI metadata this way
* We do not show the image so, we need to remove the NFT and add it again

With this being said, I believe that if it's removed and you opt-out and opt-in from one of the toggles mentioned above, the metadata will not update.

We can indeed improve this logic, by for example using the services only to update the missing data and do not remove and re update everything!


Let me know your thoughts and how could we improve the flakiness!

2024-01-29 11:33 UTC, sahar-fehri commented on app/components/UI/CollectibleContracts/index.js
> +    (typeof collectible.tokenId === 'string' && !isNaN(collectible.tokenId));
Im really not sure why, in the tests i made it was always returning a string, havent found a case yet where its a number

2024-01-31 11:59 UTC, tommasini submitted a review, later dismissed
LGTM! Just if possible address the minor comment

2024-01-31 11:59 UTC, tommasini commented on app/components/UI/CollectibleContracts/index.js
> +      if (!isRemovingNftInProgress) {
NIT: This can be only one condition

2024-01-31 11:59 UTC, tommasini commented on app/components/UI/CollectibleContracts/index.js
> +      if (!isRemovingNftInProgress) {
`!isRemovingNftInProgress && !isIgnored`

2024-01-31 14:04 UTC, tommasini approved these changes

2024-01-31 14:59 UTC, merged