fix: improve native balance fetch logic on the UX
MetaMask/metamask-mobile pull request #8556
Opened 2024-02-08 17:38 UTC by salimtb

## **Description**

Problem: When we change network or account, the native balance of the ERC-20 tokens is not reset. It shows a wrong value for a couple seconds and then updates.

We should reset the state and show a skeleton text instead of a wrong value.

## **Related issues**

Fixes: #6101 

## **Manual testing steps**

1. Go to any network where you hold native tokens
2. switch to another network when you have 0 balance
3. you can see that the wrong balance was displayed for a short time

## **Screenshots/Recordings**

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/26223211/d96b474f-60fc-4c4a-a43f-fde18c4a4a26

### **After**

https://github.com/MetaMask/metamask-mobile/assets/26223211/462d8c0e-dcf0-4da7-ae2f-7fdba65b9076

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-09 09:20 UTC, salimtb commented on patches/@metamask+assets-controllers+7.0.0.patch
> ++    accountsByChainId: Record<string, {
this patch contains only the state change in core (the addition of the `accountsByChainId` property).
the PR in core also contains other things like the provider change ( with the use of `@metamask/eth-query` ) and the use of the new polling controller ( `StaticIntervalPollingControllerV1` ) which are not yet implemented in the version used in core ( i have to create module mentioned from scratch ).
@tommasini bumped the assets controller version , but my patch is still needed to fix this bug

2024-02-13 17:05 UTC, chrisleewilcox commented
Error on regression tests `./e2e/specs/networks/add-custom-rpc.spec.js`
![image](https://github.com/MetaMask/metamask-mobile/assets/6626407/e8286df6-f059-4406-849f-2c451cfdddd9)

2024-02-13 17:06 UTC, chrisleewilcox requested changes
https://app.bitrise.io/build/10e18cd4-22e2-4688-b017-44cb87f8716c to address test failure.

2024-02-14 13:23 UTC, salimtb commented
> https://app.bitrise.io/build/10e18cd4-22e2-4688-b017-44cb87f8716c to address test failure.

fixed

2024-02-15 21:05 UTC, Cal-L reviewed
Left a comment

2024-02-15 21:05 UTC, Cal-L commented on app/components/Views/Wallet/index.tsx
> +   * Map of accountsByChain to information objects including balances
Seems like there's a typo here. Should it be simply Map of accounts by chainID?

2024-02-15 21:07 UTC, Cal-L commented on scripts/ios/bundle-js-and-sentry-upload.sh
This should disappear once you merge with main. LMK if it doesn't

2024-02-15 21:07 UTC, Cal-L commented on app/components/Views/Settings/SecuritySettings/Sections/RevealPrivateKey/RevealPrivateKey.tsx
> +
Nit - would just remove this

2024-02-16 18:03 UTC, chrisleewilcox approved these changes
LGTM

2024-02-16 18:03 UTC, merged