test: add blacklist URLs to automated tests
MetaMask/metamask-mobile pull request #8558
Opened 2024-02-08 22:21 UTC by chrisleewilcox

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-09 17:24 UTC, cortisiko requested changes
Left a comment

2024-02-09 17:24 UTC, cortisiko commented on e2e/init.js
> +const blacklistURLs =
This shouldn't be in the init file. The init This seems more fitting for a data structure. Can we perhaps store this in a json preferably in the resources folder? Then we can have some logic to get the URL's from the json. 

For example: 

URLs is stored in a json called blacklist.json 

We have a method that goes through the json and stores these urls in an array for consumption by detox's blacklist.

2024-02-14 18:29 UTC, cortisiko requested changes, later dismissed

2024-02-14 18:29 UTC, cortisiko commented on e2e/helpers.js
> +  static getBlacklistURLs() {
it would be ideal if this was in a file other than the helpers.js. The goal is to ultimately extract all functionality in the helpers file. Perhaps place this in a utilities.js file under the utils folder?

2024-02-14 18:29 UTC, cortisiko commented on e2e/resources/blacklistURLs.json
> +  "blacklistURLsString": "/'\\(\".*infura\\.io/*\",\".*cdn\\.branch\\.io/*\",\".*api2\\.branch\\.io/*\",\".*api\\.etherscan\\.io/*\",\".*static\\.metafi\\.codefi\\.network/*\",\".*rpc\\.tenderly\\.co
Seems like tedious work if we were to continue increasing blacklistURLs. Can we create a function that puts blacklistURLs into a regex format reducing the need for  `blacklistURLsString`?

2024-02-14 18:29 UTC, cortisiko commented on e2e/helpers.js
> +    return device.getPlatform() === 'android'
Seems like we are doing the same thing for both iOS and android. The only difference I see here is that on iOS we are programmatically creating the regex's for each entry in `blacklistURLs`. Seems like we can eliminate the need for `blacklistURLsString` and just ``\\("${blacklistURLs.join('","')}"\\)`;`

2024-02-14 18:29 UTC, cortisiko commented on e2e/resources/blacklistURLs.json
> +  "blacklistURLsString": "/'\\(\".*infura\\.io/*\",\".*cdn\\.branch\\.io/*\",\".*api2\\.branch\\.io/*\",\".*api\\.etherscan\\.io/*\",\".*static\\.metafi\\.codefi\\.network/*\",\".*rpc\\.tenderly\\.co
Correcting myself here, it seems as if we can do away with the blackListURL strings and just create the blacklist URLs dynamically similar to what you did in my above comment. 
 `\\("${blacklistURLs.join('","')}"\\)``

2024-02-14 18:42 UTC, SamuelSalas submitted a review, later dismissed
LGTM

2024-02-15 15:09 UTC, SamuelSalas approved these changes

2024-02-15 16:04 UTC, cortisiko approved these changes
✅ ✅

2024-02-15 16:25 UTC, merged