fix: deprecate goerli network
MetaMask/metamask-mobile pull request #8567
Opened 2024-02-12 10:57 UTC by sahar-fehri

## **Description**

Pr to deprecate goerli network. 
- Removes instances of goerli network. (From network dropdown and setting)
- Updates e2e tests to use Sepolia instead.
- Creates a new component (https://www.figma.com/file/KXgbxFucvk3FM5VULGZmzk/Assets%3A-Bug-Fixes?node-id=449%3A2210&mode=dev) for the scenario when a user clicks on a deepling for goerli.

## **Related issues**

Fixes: https://github.com/MetaMask/mobile-planning/issues/1368

## **Manual testing steps**

1. Click on network dropdown list (you should not see Goerli)
2. Click on settings, then network list (you should not see Goerli)
3. Click on a deeplink that is supposed to switch to goerli : https://metamask.app.link/send/0x4701Aa9471d7bfAc765D87dcb1Ea6BB23AD32733@5/approve?address=0x178e3e6c9f547A00E33150F7104427ea02cfc747&uint256=5e8. You should see a modal saying that the network is deprecated.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-15 20:42 UTC, sahar-fehri commented on app/store/migrations/029.js
> +    chainId === '5'
Im not quite sure if i created this migration correctly but please lemme know 🙏

2024-02-15 21:17 UTC, cortisiko requested changes
Left a few comments relating to E2E

2024-02-15 21:17 UTC, cortisiko commented on e2e/specs/swaps/token-details.spec.js
>      await WalletView.tapOnToken(Networks.Goerli.providerConfig.ticker);
Update this to reflect Sepolia

2024-02-15 21:17 UTC, cortisiko commented on e2e/specs/assets/import-nft.spec.js
>  describe(SmokeCore('Import NFT'), () => {
Can you update this test to use fixtures to deploy a 721 contract and then import it into the wallet? 

You can use https://github.com/MetaMask/metamask-extension/blob/develop/test/e2e/tests/nft/import-nft.spec.js as a guide.

2024-02-16 15:16 UTC, cortisiko requested changes

2024-02-16 15:20 UTC, sahar-fehri commented on e2e/specs/assets/import-nft.spec.js
> +  it('should switch to Sepolia network', async () => {
Thanks Curtis 🙏  fixed that 🙏

2024-02-16 16:01 UTC, cortisiko approved these changes, later dismissed
From a testing perspective this PR is ✅

2024-02-16 16:46 UTC, tommasini requested changes
As requested Sahar, I took a look on the migration file, and left some question and outputs how we could handle this on the best way possible!

Let me know any support that you need for we further adopt this migration process, anything just ping me!

2024-02-16 18:32 UTC, sahar-fehri commented on app/store/migrations/029.js
> +    chainId === '5'
Thanks a lot Tomas for the feedback! 🙏  will update this 🙏

2024-02-20 11:03 UTC, tommasini requested changes
Awesome work! I left some comments

2024-02-21 12:13 UTC, sahar-fehri commented on app/core/DeeplinkManager/Handlers/handleEthereumUrl.ts
> +    if (ethUrl.chain_id === getDecimalChainId(CHAIN_IDS.GOERLI)) {
Nice catch! Fixed that 🙏

2024-02-21 12:15 UTC, sahar-fehri commented on app/components/UI/DeprecatedNetworkModal/DeprecatedNetworkModal.tsx
> +    <ReusableModal ref={modalRef} style={styles.screen}>
Thats true, i ve missed that component 🙏  I updated the file, the BottomSheetHeader was not looking like i want so i used the Text instead for the title

2024-02-23 22:31 UTC, Cal-L reviewed
Left some comments

2024-02-23 22:34 UTC, Cal-L reviewed
Have we also tested upgrading with Goerli network selected?

2024-02-26 10:15 UTC, sahar-fehri commented
> Have we also tested upgrading with Goerli network selected?

Hey @Cal-L , i have tested the migration when the user is already on goerli, he will be automatically switched to Sepolia 🙏

2024-02-26 10:15 UTC, sahar-fehri commented on app/components/UI/DeprecatedNetworkModal/DeprecatedNetworkModal.styles.ts
> +      fontSize: 14,
Thnx for pointing this out! fixed this

2024-02-27 04:45 UTC, Cal-L reviewed
Code LGTM, let's resolve the conflict and I'll approve

2024-02-27 04:52 UTC, Cal-L approved these changes, later dismissed
LGTM.

2024-02-27 12:17 UTC, tommasini approved these changes
LGTM

2024-02-27 12:58 UTC, merged