fix: fake native tokens need better UX error handling
MetaMask/metamask-mobile pull request #8572
Opened 2024-02-13 15:00 UTC by salimtb

## **Description**

In response to recent scam incidents we're adding mitigations to help prevent users from adding malicious networks and being shown inaccurate token values.

Implementation of this ticket will:

Show N/A for a native token value, when the native token symbol does not match the chain ID as publicly known
Show a tooltip that when tapped shows a bottom sheet explainer
The explainer directs the user to update their Network details for the network the token balance is requested for
User story

As a user I want to be informed that a token balance might be inaccurate, so that I don't make decisions to transfer or buy assets based on this information
As a user I want to be informed when a custom network might be trying to scam me

## **Related issues**

Fixes: [#1354](https://github.com/MetaMask/mobile-planning/issues/1354)

## **Manual testing steps**

1. Go to edit network page and choose Polygon
2.change the symbol from MATIC to ETH
3. Go to the wallet page

## **Screenshots/Recordings**

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/26223211/14c599fd-a8f8-4d93-8e91-6ac34040ee6b

### **After**

https://github.com/MetaMask/metamask-mobile/assets/26223211/14c599fd-a8f8-4d93-8e91-6ac34040ee6b

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-14 15:34 UTC, salimtb commented
figma : https://www.figma.com/file/T0z1ZJ81y8YlaKzoLGraTt/Verify-and-pre-populate-network-details-(mobile)?node-id=9%3A48702&mode=dev

2024-02-15 20:37 UTC, Cal-L reviewed
Left some comments. Looks like there are failing unit tests as well

2024-02-15 20:37 UTC, Cal-L commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +      ...fontStyles.normal,
use typography from theme instead of fontStyles

2024-02-15 20:37 UTC, Cal-L commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +      ...fontStyles.normal,
Same comment on typography

2024-02-15 20:37 UTC, Cal-L commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +      ...fontStyles.normal,
Same comment for typography

2024-02-15 20:37 UTC, Cal-L commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +
It's typically not good practice having data fetching logic within the component themselves. Could we abstract this into the `useIsOriginalNativeToken` hook instead?

2024-02-15 20:37 UTC, Cal-L commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +      .get('https://chainid.network/chains.json')
Refer to abstracting this out into a constant

2024-02-15 20:37 UTC, Cal-L commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +
You can create a HOC wrapper that exposes the `useIsOriginalNativeToken` hook to this class component

2024-02-15 20:37 UTC, Cal-L commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +                    onPress={() => {
Could we abstract the inline logic into a function + add some comments to explain the functionality?

2024-02-15 20:37 UTC, Cal-L commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +                    onPress={() => {
Same comment regarding abstracting the function + add comments for functionality

2024-02-15 20:37 UTC, Cal-L commented on app/components/UI/Tokens/index.tsx
> +import ButtonSecondary from '../../../../app/component-library/components/Buttons/Button/variants/ButtonSecondary';
Replace ButtonSecondary with `Button` instead. You can then pass in the `variant` prop that indicates if it should be secondary. Ex.

`<Button variant={ButtonVariants.Secondary} />`

2024-02-15 20:37 UTC, Cal-L commented on app/components/UI/Tokens/index.tsx
> +            e.preventDefault();
I've seen this on web before but not so sure on mobile. What default behavior are you preventing here? Same question for stopPropogation. Could we also abstract this into a function + add comments

2024-02-15 20:37 UTC, Cal-L commented on app/components/UI/Tokens/index.tsx
> +          <ButtonSecondary
Replace with Button and pass variant instead

2024-02-15 20:37 UTC, Cal-L commented on app/components/UI/Tokens/index.tsx
> +            {`This network doesn't match its associated chain ID or name. Many popular tokens use the name ${ticker}, making it a target for scams. Scammers may trick you into sending them more valua
Use translated string instead of hardcode

2024-02-15 20:37 UTC, Cal-L commented on app/components/UI/Tokens/styles.ts
> +      ...fontStyles.bold,
Use typography from theme

2024-02-15 20:37 UTC, Cal-L commented on app/components/UI/Tokens/index.tsx
> +      if (asset.isETH) {
Let's add some comments to explain this logic

2024-02-15 20:37 UTC, Cal-L commented on app/components/UI/Tokens/index.tsx
> +      if (asset.isETH) {
Let's add some comments to explain this logic and/or abstract into a function

2024-02-19 16:06 UTC, salimtb commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +
done :)

2024-02-20 17:29 UTC, Cal-L reviewed
Left small comments

2024-02-20 17:29 UTC, Cal-L commented on app/components/UI/Tokens/index.tsx
> +        <SheetHeader title={'This is a potential scam'} />
Is there a translation string for this?

2024-02-20 17:29 UTC, Cal-L commented on app/components/UI/Tokens/styles.ts
> +      ...fontStyles.bold,
Looks like this didn't change?

2024-02-20 17:29 UTC, Cal-L commented on app/components/Views/Settings/NetworksSettings/NetworkSettings/index.js
> +// export default connect(mapStateToProps, mapDispatchToProps)(NetworkSettings);
Remove unused code

2024-02-21 23:12 UTC, Cal-L approved these changes, later dismissed
LGTM

2024-02-23 23:34 UTC, cortisiko requested changes
See my comment above

2024-02-26 09:41 UTC, salimtb commented
> @salimtb We should double-check the logic when it comes to infura supported networks. I noticed that when on mainnet I see the warning next to ETH. See [here](https://app.screencast.com/TxY9jW3qOgcG4). [This](https://app.screencast.com/2vWR8lwArTVcQ) is what the network overview for `mainnet` shows

hello @cortisiko ,
thank you for your comment, the issue has now been resolved.

just to clarify a few things, at the bottom of the name you see a message that suggests using ETH as the name, this must be Ethereum mainnet, so thanks for reporting that, it's now fixed.

you shouldn't also see the red border in the filed name, so I've fixed that too.
the suggested network name came from [here](https://chainid.network/chains.json), you can also see the design [here](https://www.figma.com/file/T0z1ZJ81y8YlaKzoLGraTt/Verify-and-pre-populate-network-details-(mobile)?node-id=9%3A48702&mode=dev)

2024-02-29 20:44 UTC, cortisiko approved these changes
Looks good from a testing perspective

2024-03-01 09:03 UTC, merged

2024-04-18 01:49 UTC, wachunei commented
Hey @salimtb I just realized there were additions to the Ramp folder, to be exact the files:
- `app/components/UI/Ramp/hooks/useIsOriginalNativeTokenSymbol.test.ts`
- `app/components/UI/Ramp/hooks/useIsOriginalNativeTokenSymbol.ts`

These must have been added before our `CODEOWNERS` folders were listed so I was not aware of this change. I want to kindly ask for these two files to be moved to the corresponding code domain since these are not used within our feature.

cc: @Cal-L @cortisiko

2024-04-18 10:53 UTC, salimtb commented
> * app/components/UI/Ramp/hooks/useIsOriginalNativeTokenSymbol.test.ts

hey @wachunei ,
hooks now moved on this [PR](https://github.com/MetaMask/metamask-mobile/pull/9177) , can i have a review pls