feat: migrate Segment utils [split of 8387]
MetaMask/metamask-mobile pull request #8574
Opened 2024-02-13 18:11 UTC by NicolasMassart

## **Description**

>[!NOTE]
> #8387 is too big for review, splitting it into contextual/domain scoped smaller PRs.
> you can refer to #8387 for global view

### This is the part of #8387 related to the utils code of the Segment work.

update metrics utils
- rename trackAfterInteractions to trackOnboarding to match purpose
- update for synchronous getInstance
- fix types
- update exports
- move and update trackErrorAsAnalytics outside of Analyticsv2

## **Related issues**

Related to MetaMask/mobile-planning/issues/1461

## **Manual testing steps**

NA

## **Screenshots/Recordings**

### **Before**

NA

### **After**

NA

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-16 01:11 UTC, Cal-L requested changes
Nice - love how this is split out. For folder structure and naming, I think there's a more scalable way that aligns more with how our current files are setup. The design system components set it up in this manner as well. The final structure + naming would look like so:

<img width="969" alt="image" src="https://github.com/MetaMask/metamask-mobile/assets/10508597/f8fded34-810f-4a89-9432-82baf0776079">


LMK what you think.

2024-02-16 02:20 UTC, Cal-L reviewed
Left some comments

2024-02-16 02:20 UTC, Cal-L commented on app/util/metrics/index.ts
>  export default DeviceAnalyticsMetaData;
Is there a reason why we aren't reexporting TrackOnboarding as well? Could we also consolidate the exports?

2024-02-16 12:28 UTC, NicolasMassart commented on app/util/metrics/index.ts
>  export default DeviceAnalyticsMetaData;
Will update these imports in another PR, trying to reduce conflicts and merge here

2024-02-20 20:43 UTC, Cal-L reviewed
Left a comment

2024-02-20 20:43 UTC, Cal-L commented on app/util/metrics/DeviceAnalyticsMetaData/DeviceAnalyticsMetaData.types.ts
Let's follow the folder structure similar to how Design system team has theirs set up. Your `useMetrics` hook is set up this way as well. Here's an example of how `metrics` directory might look like after the improvement.:

<img width="628" alt="image" src="https://github.com/MetaMask/metamask-mobile/assets/10508597/19dc4acb-f1bc-4549-8579-6a2adefb03b1">

2024-02-28 13:32 UTC, NicolasMassart commented
Closed as this was reworked and split differently in smaller PRs for the migration

2024-02-28 13:32 UTC, closed without merging