feat: Move Security settings from Experimental Settings into Security Settings
MetaMask/metamask-mobile pull request #8635
Opened 2024-02-20 13:42 UTC by segun

## **Description**

We should move security alerts feature out of Settings > Experimental to Settings > Security & Privacy under the Security section below the show private key feature.

## **Related issues**

Fixes: [#1986](https://github.com/MetaMask/MetaMask-planning/issues/1986)

## **Manual testing steps**

1. Start Metamask
2. Open Settings > Experimental and see blockaid settings
3. Checkout this branch
4. Open Metamask
5. Open Settings > Security & Privacy and see blockaid settings under private key settings

## **Screenshots/Recordings**

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/44811/0ed7131a-fcb4-4e57-b697-83496aa73d5b

### **After**

https://github.com/MetaMask/metamask-mobile/assets/44811/d231b87a-61dd-47a0-9840-33f66779aa28

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-20 14:41 UTC, blackdevelopa commented on app/components/Views/Settings/SecuritySettings/Sections/BlockaidSettings.tsx
> +      <View style={styles.switchElement}>
I will to update the styles.

Here's what `switchElement` should be https://github.com/MetaMask/metamask-mobile/blob/2a377e80923c6bcfe0a5fe102700ec2c73190f5f/app/components/Views/Settings/ExperimentalSettings/ExperimentalSettings.styles.ts#L28

2024-02-20 14:43 UTC, blackdevelopa commented on app/components/Views/Settings/SecuritySettings/SecuritySettings.tsx
> +        {isBlockaidFeatureEnabled() && <BlockaidSettings />}
Do we have a figma description of where the toggle should be in this screen?

2024-02-20 14:53 UTC, blackdevelopa commented
Other than this, it looks good to me

2024-02-20 15:13 UTC, segun commented on app/components/Views/Settings/SecuritySettings/Sections/BlockaidSettings.tsx
> +      <View style={styles.switchElement}>
haha, thanks, I was also wondering that it looks weird. but it seems like it looks same way on develop though.

2024-02-20 15:14 UTC, segun commented on app/components/Views/Settings/SecuritySettings/SecuritySettings.tsx
> +        {isBlockaidFeatureEnabled() && <BlockaidSettings />}
No figma, but the issue said `after Reveal Passphrase`

2024-02-20 15:24 UTC, jpuri submitted a review, later dismissed
LGTM

2024-02-20 17:06 UTC, jpuri approved these changes, later dismissed

2024-02-20 17:19 UTC, blackdevelopa approved these changes, later dismissed

2024-02-20 17:23 UTC, digiwand commented on app/components/Views/Settings/SecuritySettings/Sections/BlockaidSettings.tsx
> +        MetaMetricsEvents.SETTINGS_EXPERIMENTAL_SECURITY_ALERTS_ENABLED,
I think we should update the variable names to exclude experimental now that we're moving the settings from experimental to security

2024-02-20 17:26 UTC, digiwand commented on app/components/Views/Settings/SecuritySettings/Sections/BlockaidSettings.tsx
> +          {strings('experimental_settings.security_alerts')}
we should move the translations away from experimental_settings with the changes

2024-02-20 17:30 UTC, digiwand requested changes
for consistency, I think we should update the toggle button to be right-aligned with content on the left 

**current:** 
<img width="278" alt="Screenshot 2024-02-20 at 10 28 31 AM" src="https://github.com/MetaMask/metamask-mobile/assets/20778143/83c69c51-09dd-4617-a299-00dc5b48d37d">

**example of other existing toggle settings:**
<img width="280" alt="Screenshot 2024-02-20 at 10 28 02 AM" src="https://github.com/MetaMask/metamask-mobile/assets/20778143/2079046e-c1a5-4051-bae6-bcc2b00f4ad8">
<img width="278" alt="Screenshot 2024-02-20 at 10 28 15 AM" src="https://github.com/MetaMask/metamask-mobile/assets/20778143/50e35f8a-295d-4fc3-b6f8-d3df74cf5e99">

2024-02-22 12:12 UTC, blackdevelopa commented on locales/languages/en.json
> +    "symbol_required": "Symbol is required.",
Moved from `experimental settings` to `app settings`

2024-02-22 12:12 UTC, blackdevelopa approved these changes

2024-02-22 17:29 UTC, digiwand commented on app/core/Analytics/MetaMetrics.events.ts
>    // Experimental Settings
```suggestion
  // Security Settings
```

2024-02-22 17:29 UTC, digiwand approved these changes

2024-02-23 13:20 UTC, merged