feat: migrate to native primary currency
MetaMask/metamask-mobile pull request #8720
Opened 2024-02-24 14:54 UTC by salimtb

## **Description**

 The primary currency toggle provides unnecessary overhead for every asset feature we build. The Extension team is removing it for Extension and we will do so as well for Mobile.
the default one on mobile will be Native.

## **Related issues**

Fixes: [#1846](https://github.com/MetaMask/MetaMask-planning/issues/1846#top)

## **Manual testing steps**

1. Go the setting page
2. Go to general
3. Primary currency toggle is removed, the default one is Native

## **Screenshots/Recordings**

### **Before**

<img width="478" alt="Screenshot 2024-02-24 at 15 53 46" src="https://github.com/MetaMask/metamask-mobile/assets/26223211/e45108fe-884a-4fcd-8fdb-3788e7448884">

### **After**

<img width="499" alt="Screenshot 2024-02-24 at 15 42 12" src="https://github.com/MetaMask/metamask-mobile/assets/26223211/adb343d1-114b-4bdf-b6c0-444f5832e62f">

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-26 23:44 UTC, cortisiko requested changes
Hey @salimtb a few more test scenarios come to mind:

- Changing your currency conversion from USD to CAD and submit a txn
- Change your currency conversion from USD to DAI, ETC and submit a txn

Does this PR require migrations? If so here is another scenario to test:

- Test with a version of the app where you select Fiat as your primary currency
- Upgrade to the app with this version. Does the app break? try visiting the general view does the app break? Try to submit another txn.

2024-03-04 10:32 UTC, salimtb commented
hey @cortisiko ,
you can find here the list of [requested test](https://drive.google.com/drive/folders/1dGOtdKNTTKnGKWv6Hwr3oXGbGec4UQVA?usp=drive_link)

2024-03-05 21:29 UTC, cortisiko submitted a review, later dismissed
@salimtb, I have reviewed your testing. 

The idea of removing the fiat toggle makes sense to me. I'm concerned that omitting the fiat conversion of the total transaction amount on the confirmation screen could cause user confusion.

see[ this video](:https://drive.google.com/file/d/1h7YpOCXjpbMPWN7LpaPPE67dLk7IreA0/view?usp=share_link) at the 17-19 second mark

2024-03-15 23:08 UTC, cortisiko commented
Thanks for providing testing artifacts @salimtb. Everything looks ✅ from a quality perspective.

2024-03-18 19:09 UTC, Cal-L reviewed
Left some comments

2024-03-18 19:09 UTC, Cal-L commented on app/components/Views/confirmations/components/TransactionReview/TransactionReviewEIP1559Update/index.tsx
> +                    {renderableGasFeeMaxNative} {'\n'}{' '}
May want to re-run the app to confirm this still renders properly

2024-03-18 19:09 UTC, Cal-L commented on app/components/Views/confirmations/components/TransactionReview/TransactionReviewEIP1559Update/index.tsx
> +                      {renderableTotalMaxNative} {'\n'}{' '}
```suggestion
                      {renderableTotalMaxNative} {`\n `}
```

2024-03-18 19:09 UTC, Cal-L commented on app/store/migrations/035.test.ts
> +describe('Migration #30', () => {
```suggestion
describe('Migration #35', () => {
```

2024-03-18 19:09 UTC, Cal-L commented on app/store/migrations/035.test.ts
> +      `Migration 30: Invalid state settings parameter: '${JSON.stringify(
```suggestion
      `Migration 35: Invalid state settings parameter: '${JSON.stringify(
```

2024-03-18 19:09 UTC, Cal-L commented on app/store/migrations/035.test.ts
> +      `Migration 30: Invalid settings state: '${typeof oldState.settings}'`,
```suggestion
      `Migration 35: Invalid settings state: '${typeof oldState.settings}'`,
```

2024-03-18 19:09 UTC, Cal-L commented on app/store/migrations/035.test.ts
> +      `Migration 30: Invalid state: '${typeof oldState}'`,
```suggestion
      `Migration 35: Invalid state: '${typeof oldState}'`,
```

2024-03-18 19:09 UTC, Cal-L commented on app/store/migrations/035.ts
> +  Fiat = 'Fiat',
Can remove Fiat since it isn't used

2024-03-18 19:09 UTC, Cal-L commented on app/store/migrations/035.test.ts
> +        primaryCurrency: 'ETH',
use `PrimaryCurrency.ETH` from `035.ts` instead

2024-03-18 19:09 UTC, Cal-L commented on app/store/migrations/035.ts
> +  if (!state.settings.primaryCurrency) {
Do not need this condition since line 32 already checks for the existence of the property

2024-03-18 19:09 UTC, Cal-L commented on app/store/migrations/035.ts
> +    return state;
Can remove this return since we can just rely on line 47 and 48 to set both primaryCurrent and return the state

2024-03-19 14:37 UTC, Cal-L approved these changes
LGTM!

2024-03-19 14:39 UTC, merged