Svg network mobile
MetaMask/metamask-mobile pull request #8722
Opened 2024-02-26 00:15 UTC by salimtb

## **Description**

hardcode a mapping of chainIDs to currency symbol, once the svg are uploaded we mapped the images to the network name and chainIDs

Acceptance criteria
When the network list is displayed within the Select a network modal, or custom network list, or any similar context, the hardcoded network image avatars should be displayed. This will reduce the often appearing "?" that appears when the network avatar is not present.

## **Related issues**

Fixes: [#1813](https://github.com/MetaMask/MetaMask-planning/issues/1813)

## **Manual testing steps**

Go to the network modal
Add a new network displayed on this [list](https://docs.google.com/spreadsheets/d/16G3SRiQvWXK6hp5duob0aopeKyx2HOAQpz152Fy8VNQ/edit#gid=2080069111)
check if the image is displayed

## **Screenshots/Recordings**

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/26223211/b50efcc2-37dc-43a1-b506-ab6f72e1b00e

### **After**

https://github.com/MetaMask/metamask-mobile/assets/26223211/9f29ceea-45cb-409e-93af-0824d9ea7373

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-26 14:01 UTC, wachunei requested changes

2024-02-26 14:01 UTC, wachunei commented on app/components/UI/Ramp/Views/NetworkSwitcher/NetworkSwitcher.tsx
> +                          ).toString()}
This is not needed, `selectedChainId` is already a base 10 string.

2024-02-26 14:01 UTC, wachunei commented on app/components/UI/Ramp/Views/NetworkSwitcher/NetworkSwitcher.tsx
> +                          ).toString()}
This is not needed, `selectedChainId` is already a base 10 string.

2024-02-26 14:03 UTC, wachunei commented on app/component-library/components/Badges/Badge/Badge.test.tsx
> +      />,
The chainId prop was not part of the test before and it was already defined in `SAMPLE_BADGENETWORK_PROPS`, so probably the chain needed is only in [`BadgeNetwork.constants`](https://github.com/MetaMask/metamask-mobile/pull/8722/files#diff-ff563c4e4aa2e562fa31a3c72c505d881c659a04dabfccaa5a2c33731df3b5b8).

2024-02-29 00:53 UTC, brianacnguyen commented
also please break this PR up. It's HUGE

2024-02-29 01:05 UTC, brianacnguyen requested changes

2024-02-29 01:05 UTC, brianacnguyen commented on app/component-library/components/Networks/Network/Network-icon.tsx
> +export interface NetworkIconProps extends ViewProps {
Put in .type file

2024-02-29 01:05 UTC, brianacnguyen commented on app/component-library/components/Networks/Network/Network-icon.tsx
> +  name?: string;
Comment with description for name

2024-02-29 01:05 UTC, brianacnguyen commented on app/component-library/components/Networks/Network/Network-icon.tsx
> +  onError?: (arg: boolean) => void;
Comment with description for onError

2024-02-29 01:05 UTC, brianacnguyen commented on app/component-library/components/Networks/Network/Network-icon.tsx
> +   * Enum to select between networks chainId.
Optional. Also try to keep the descriptions consistent

2024-02-29 01:05 UTC, brianacnguyen commented on app/component-library/components/Networks/Network/Network-icon.tsx
> +export default NetworkIcon;
Add test and stories

2024-02-29 01:05 UTC, brianacnguyen commented on app/component-library/components/Networks/Network/Network.assets.ts
> +/* eslint-disable import/prefer-default-export */
How is this library going to be maintained?

2024-02-29 01:05 UTC, brianacnguyen commented on app/component-library/components/Networks/Network/Network.types.ts
> +import { NETWORKS_CHAIN_ID_WITH_SVG } from '../../../../constants/network';
Please group imports accordingly

2024-02-29 01:05 UTC, brianacnguyen commented on app/component-library/components/Pickers/PickerNetwork/PickerNetwork.types.ts
> +   * Network chainId.
Keep this consistent

2024-02-29 01:05 UTC, brianacnguyen commented on app/component-library/components/Pickers/PickerNetwork/PickerNetwork.tsx
> +        chainId={convertHexToDecimal(chainId).toString()}
Why is this not part of the original component?

2024-02-29 01:05 UTC, brianacnguyen commented on app/component-library/components/Toast/Toast.tsx
> +            chainId={convertHexToDecimal(chainId).toString()}
same

2024-02-29 01:05 UTC, brianacnguyen commented on app/images/acala-logo.svg
> +<svg width="100%" height="100%" viewBox="0 0 128 128" fill="none" xmlns="http://www.w3.org/2000/svg">
Please optimize SVGs

2024-03-18 09:13 UTC, closed without merging