test: onboarding add custom default ETH Mainnet
MetaMask/metamask-mobile pull request #8723
Opened 2024-02-26 06:32 UTC by chrisleewilcox

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-26 18:58 UTC, chrisleewilcox commented on e2e/pages/Onboarding/DefaultNetworkView.js
Added a view for default network screen

2024-02-26 19:01 UTC, chrisleewilcox commented on e2e/pages/Onboarding/MetaMetricsOptInView.js
Modified existing view to use new selectors in place of the old wdio selector file.

2024-02-26 19:02 UTC, chrisleewilcox commented on e2e/pages/Onboarding/MetaMetricsOptInView.js
> +  }
Rendering of this screen show the here link in different screen positions for iOS and android devices.

2024-02-26 19:03 UTC, chrisleewilcox commented on e2e/selectors/Onboarding/MetaMetricsOptIn.selectors.js
New selector file for MetaMetrics Opt-In screen.

2024-02-26 19:05 UTC, chrisleewilcox commented on e2e/specs/onboarding/add-custom-eth-mainnet.spec.js
> +    await WalletView.isNetworkNameVisible('Ethereum Main Custom');
Was trying to use Assertion class for this but was not working so used existing function in WalletView.  May need to update WalletView to work with Assertions.

2024-02-26 21:36 UTC, cortisiko requested changes
Left some comments on the PR

2024-02-26 21:36 UTC, cortisiko commented on e2e/pages/Onboarding/DefaultNetworkView.js
> +      await TestHelpers.waitAndTapByLabel(
use gestures to tap not TestHelpers

2024-02-26 21:36 UTC, cortisiko commented on e2e/pages/Onboarding/DefaultNetworkView.js
> +      await TestHelpers.waitAndTapByLabel(
use gestures to tap not TestHelpers

2024-02-26 23:15 UTC, chrisleewilcox commented on e2e/selectors/Onboarding/CustomDefaultNetwork.selectors.js
> +  USE_THIS_NETWORK_BUTTON_TEXT: 'Use this network',
I feel this is bad practice.  Doing this is almost like the step will never fail.

2024-03-01 19:11 UTC, cortisiko requested changes

2024-03-01 19:13 UTC, cortisiko commented on e2e/specs/onboarding/add-custom-eth-mainnet.spec.js
> +  validURL: 'https://eth.llamarpc.com',
since this is a network rpc url, put this in the networks.json

2024-03-01 19:16 UTC, cortisiko commented on e2e/specs/onboarding/add-custom-eth-mainnet.spec.js
> +    await WalletView.isNetworkNameVisible('Ethereum Main Custom');
This also relates to the above. https://github.com/MetaMask/metamask-mobile/pull/8723/files#r1509432249

2024-03-01 19:19 UTC, cortisiko commented on e2e/specs/onboarding/add-custom-eth-mainnet.spec.js
> +    await CreatePasswordView.enterPassword(testData.password);
There is a hook that skips all these onboarding steps. https://github.com/MetaMask/metamask-mobile/blob/main/e2e/viewHelper.js#L90

2024-03-01 19:24 UTC, cortisiko commented on e2e/specs/onboarding/add-custom-eth-mainnet.spec.js
> +    await CreatePasswordView.enterPassword(testData.password);
It makes sense what you are doing here but keep in mind there is a hook that skips all these onboarding steps. https://github.com/MetaMask/metamask-mobile/blob/main/e2e/viewHelper.js#L90 

 Don't reinvent the wheel. Use the password from Accounts utils

2024-03-02 19:43 UTC, chrisleewilcox commented on e2e/pages/Onboarding/MetaMetricsOptInView.js
> +  }
I tried using testID but wasn't working no matter what I did.  I'm also handicapped with appium server not working on my local so I can't inspect elements.  I suggest we create an issue for this or maybe an Epic to addres Gestures using coordinates and try to convert to using Matchers.  Not sure it's worth continuing to hold up the PR for this as it works on local and CI.

2024-03-02 19:59 UTC, chrisleewilcox commented on e2e/specs/onboarding/add-custom-eth-mainnet.spec.js
> +  validURL: 'https://eth.llamarpc.com',
Can you provide the network info that is needed to be added as an entry into the networks.json?  I can't even find this rpc url on chainlist.

2024-03-06 17:53 UTC, cortisiko commented on e2e/specs/onboarding/add-custom-eth-mainnet.spec.js
> +  validURL: 'https://eth.llamarpc.com',
This is how you can display the RPC url for mainnet while on chainlist: http://recordit.co/lgIoP1aMhF

2024-03-06 21:19 UTC, cortisiko commented on e2e/pages/Onboarding/MetaMetricsOptInView.js
> +  }
This behavior will change in the coming weeks. Happy to leave tapping by coordinates for now, and we update this test when the behavior changes.

2024-03-07 16:59 UTC, cortisiko commented on e2e/resources/networks.json
> +      "invalidUrl": "https//rpc.mevblocker.io",
The networks in the networks.json file are used when building fixtures with a specific network. The network controller uses the providerconfig object. If you intend to use Ethereum Main Custom within a fixture sometime in the future, you will run into an error because the data in the provider configuration is incorrect. It would be best to store the invalid URL as a string in the test code and perform your assertion on it.

2024-03-08 00:38 UTC, cortisiko approved these changes
Looks Good 👍

2024-03-08 00:50 UTC, merged