Fix/8643 location permission issue
MetaMask/metamask-mobile pull request #8745
Opened 2024-02-27 12:26 UTC by dawnseeker8

## **Description**

This PR is to fix #8643 and #8718 issue

## **Related issues**

Fixes: #8643 
#8718 

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-03-01 21:46 UTC, plasmacorral commented
Android 11
Moto G Play 2021
Testing commit 962b740f1b1461811e220e49453e70589e33cbd5
LNX fw 2.2.3 w/ Eth App 1.10.3

Happy path with location on, works.  

When location is off pairing error presents without actionable instruction for user (related to report in [8643](https://github.com/MetaMask/metamask-mobile/issues/8643))

When bluetooth is off `View settings` goes to app level info rather than device level bluetooth settings (previously reported in [4920](https://github.com/MetaMask/metamask-mobile/issues/4920).

Results for Android 11 device-
Bluetooth on/Location on (Happy path) [recording](https://www.loom.com/share/2ed72611182c424fa7e9048165ad4f01?sid=2f638261-f669-4486-8dba-602248a9e5b3)
1. Access Settings>Applications>MetaMask>Storage & Cache and clear storage (to simulate fresh install)
2. Access Settings>Connected devices> to forget previously paired devices
3. Have Bluetooth enabled
4. Have Location enabled
5. Launch app
6. import SRP
7. Access accounts drop down
8. tap `Add account or hardware wallet`
9. tap `Add hardware wallet`
10. Tap `Ledger`
11. Tap `Only this time` or Ask every time equivalent on Location permission prompt
12. Tap continue once device is found
13. Tap Pair and connect on android
14. Tap connect on android
15. Tap both buttons on Ledger to confirm pairing
16. Confirm Ledger account appears in account list

Bluetooth on/Location off [recording](https://www.loom.com/share/a17ce145ef464a7fa6b94aeb4d26d1d0?sid=cdaf967e-2e8b-4aae-b875-6ed4c1ec2327)
1. Access Settings>Applications>MetaMask>Storage & Cache and clear storage (to simulate fresh install)
2. Access Settings>Connected devices> to forget previously paired devices
3. Have Bluetooth enabled
4. Have Location disabled (OFF)
5. Launch app
6. import SRP
7. Access accounts drop down
8. tap `Add account or hardware wallet`
9. tap `Add hardware wallet`
10. Tap `Ledger`
11. Tap `Only this time` or Ask every time equivalent on Location permission prompt
12. Note generic error with no instruction to enable location

Bluetooth off/Location on [recording](https://www.loom.com/share/a17ce145ef464a7fa6b94aeb4d26d1d0?sid=beacd15d-7b6c-41b3-b3eb-19508f3d3952)
1. Access Settings>Applications>MetaMask>Storage & Cache and clear storage (to simulate fresh install)
2. Access Settings>Connected devices> to forget previously paired devices
3. Have Bluetooth disabled (OFF)
4. Have Location enabled
5. Launch app
6. import SRP
7. Access accounts drop down
8. tap `Add account or hardware wallet`
9. tap `Add hardware wallet`
10. Tap `Ledger`
11. Tap `Only this time` or Ask every time equivalent on Location permission prompt
12. Error presented `Bluetooth is off`
13. Tap `View Settings`
14. takes user to Settings>App info>MetaMask, but instead should be Device bluetooth settings at Settings>Connected Devices

2024-03-12 13:13 UTC, dawnseeker8 commented
This PR will required #8873 to be merged, i will move this ticket to Draft Review before #8873 merged.

2024-03-14 17:32 UTC, sethkfman commented
@dawnseeker8  You have a SonarCloud issue here: https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&pullRequest=8745&id=metamask-mobile&open=AY3qkn5-sSDT4PHPL46h

This will need to be resolved before you can complete the PR.

2024-03-19 08:44 UTC, angelcheung22 commented
Needs to wait until https://github.com/MetaMask/metamask-mobile/pull/8932 being merged first

2024-03-19 18:22 UTC, NicolasMassart reviewed
Hi,
In addition to my inline comments, do you think it could help to have unit/integration tests on these changes? Are they testable?

2024-03-20 03:43 UTC, dawnseeker8 commented on locales/languages/en.json
> +    "ledger_reminder_message_step_five": "4. Nearby devices is enabled",
done the change.

2024-03-20 03:51 UTC, dawnseeker8 commented on app/components/hooks/useBluetoothPermissions.ts
> +      // to make sure User come back to Metamask, the bluetoothPermissionError is undefined, otherwise, `ledgerConfirmationModal.tsx` will have issue on retry.
hi, Nicolas, this is a workaround for the issue jumpping from metamask to phone setting screen to switch permission. bluetoothPermissionError hasn't been set to `undefined` after user enable Nearby devices permission.

2024-03-20 08:55 UTC, dawnseeker8 commented
> @dawnseeker8 You have a SonarCloud issue here: https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&pullRequest=8745&id=metamask-mobile&open=AY3qkn5-sSDT4PHPL46h
> 
> This will need to be resolved before you can complete the PR.

The sonarCloud issue have been fixed successfully with latest code.

2024-03-20 08:57 UTC, dawnseeker8 commented
> Hi, In addition to my inline comments, do you think it could help to have unit/integration tests on these changes? Are they testable?

Because the original code haven't been implemented any unit tests, i didn't do that as well, however, we can improve the unit tests coverage for those files, in other story not in this PR, since this PR is quite important to be merged for the release.

2024-03-20 12:32 UTC, NicolasMassart commented
Testing on Android device (moto edge 30, Android 13), I can't pass the happy path:
I'm stuck at connect ledger part, after I confirm pairing on the ledger, nothing happens on the app side and finally "An error occured" is raised. No logs about the error, see all session logs and recording bellow.

https://github.com/MetaMask/metamask-mobile/assets/4677568/2250de4a-7884-4dac-8b06-c0a16eb6514a

```
 BUNDLE  ./index.js

 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 WARN  Require cycle: app/core/Engine.ts -> app/core/NotificationManager.js -> app/core/Engine.ts

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
 ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package. [...]

2024-03-20 15:11 UTC, dawnseeker8 commented
> Testing on Android device (moto edge 30, Android 13), I can't pass the happy path: I'm stuck at connect ledger part, after I confirm pairing on the ledger, nothing happens on the app side and finally "An error occured" is raised. No logs about the error, see all session logs and recording bellow.
> 
>  screen-20240320-131343.mp4 
> ```
>  BUNDLE  ./index.js
> 
>  WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
>  WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
>  WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
>  WARN  Require cycle: app/core/Engine.ts -> app/core/NotificationManager.js -> app/core/Engine.ts
> 
> Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
>  WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types' package.
>  ERROR  ViewPropTypes will be removed from React Native, along with all other PropTypes. We recommend that you migrate away from PropTypes and switch to a type system like TypeScript. If you need to continue using ViewPropTypes, migrate to the 'deprecated-react-native-prop-types'  [...]

2024-03-20 19:01 UTC, NicolasMassart commented on app/components/hooks/useBluetoothPermissions.ts
> +      // to make sure User come back to Metamask, the bluetoothPermissionError is undefined, otherwise, `ledgerConfirmationModal.tsx` will have issue on retry.
Yes, but it's not clear, sorry. I read it multiple times and can't figure out exactly what it it about...

2024-03-20 23:26 UTC, dawnseeker8 commented
Smoke e2e pass in https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/85bfc211-35c6-4d76-b27f-e48a64a3dbce

2024-03-21 14:31 UTC, dawnseeker8 commented
Move the PR back to draft to implement unit tests for all modified components and hooks.
Will reset it to ready when all unit tests implemented.

2024-03-21 14:45 UTC, dawnseeker8 commented on app/components/hooks/useBluetoothPermissions.ts
> +      // to make sure User come back to Metamask, the bluetoothPermissionError is undefined, otherwise, `ledgerConfirmationModal.tsx` will have issue on retry.
Sorry, this comment is not valid anymore after i split the checkPermission() function into two, one for android and another for iOS in checkPermissions(),  that was workaround for old code during useEffect didnt trigger when switch MM mobile and setting page in android, cause some of the state in component still outdated. you can forget his comment now, i will remove all the comments.

2024-03-21 18:05 UTC, NicolasMassart commented
I found the reason why it was not working on Moto edge!
The device was in "do not disturb" mode so the pairing notification was not displayed!
Maybe that's something we should add in the "looking for device" section, a 5th point with make sure your mobile displays notifications.

2024-03-22 11:15 UTC, NicolasMassart requested changes
Thanks for these improvements!
I added a comment about Enzyme being deprecated though.
If you have any questions about this you can get in touch with @kylanhurt or @Cal-L who are working on this migration.

2024-03-22 11:15 UTC, NicolasMassart commented on app/components/UI/LedgerModals/LedgerConfirmationModal.test.tsx
Using Enzyme is deprecated (your IDE should show it as deprecated), you should rewrite using React Native Testing framework. See this epic for details and example PRs: https://app.zenhub.com/workspaces/metamask-mobile-platform-5f984938ddc0e4001d4b79cb/issues/gh/metamask/mobile-planning/835

2024-03-22 11:15 UTC, NicolasMassart commented on app/components/UI/LedgerModals/LedgerConfirmationModal.test.tsx
> +  it('should render correctly', () => {
I suggest gloably renaming these kind of snapshot tests as it doesn't check if it renders correctly but only if nothing has changed since last snapshot. it can be totally wrong and pass if not changed.
```suggestion
  it('render matches latest snapshot', () => {
```

2024-03-25 02:25 UTC, dawnseeker8 commented on app/components/UI/LedgerModals/LedgerConfirmationModal.test.tsx
have removed the Enzyme in the code, and use react native testing framework directly.

2024-03-25 10:14 UTC, NicolasMassart submitted a review, later dismissed

2024-03-26 00:46 UTC, dawnseeker8 commented
This PR has been move to Draft, i will put `ready for review` again after some unit tests implemented which was required by Nicolas.

2024-03-26 12:40 UTC, dawnseeker8 commented
New Unit tests have been implemented for for following components and current code coverage:

* OpenETHAppStep: 100%
* SearchingForDeviceStep: 100%
* LedgerConfirmationModal: 98.14%
* scan.tsx:  79.16%
* index.tsx:  86.66%

* useBluetoothPermission: 100%
* useBluetooth: 46%,  difficulty on mock native library and observeState for `@ledgerhq/react-native-hw-transport-ble`

All above unit tests have covered all the code change in this PR, plus some extra tests for UI.

Regarding the unit tests for  `useBluetooth` hook, we plan to do it when we start to work on mock in e2e tests.

2024-03-26 16:12 UTC, NicolasMassart reviewed
Some guidelines compliance changes on tests, but otherwise it's a great work.
Adding all these tests was not a small thing and you mastered it!

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/Views/LedgerConnect/index.test.tsx
> +  it('should show error when LedgerCommunicationError AppIsNotInstalled is returned', () => {
```suggestion
  it('displays error on LedgerCommunicationError AppIsNotInstalled', () => {
```

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/Views/LedgerConnect/index.test.tsx
> +  it('should show error when LedgerCommunicationError LedgerIsLocked is returned', () => {
```suggestion
  it('displays error on LedgerCommunicationError LedgerIsLocked', () => {
```

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/Views/LedgerConnect/index.test.tsx
> +  it('should navigate to selectHardwareWallet when default LedgerCommunicationError is returned', () => {
```suggestion
  it('navigates to selectHardwareWallet on default LedgerCommunicationError', () => {
```

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/Views/LedgerConnect/index.test.tsx
> +  it('should show correct permission text when device is android 12+ ', () => {
```suggestion
  it('displays android 12+ permission text on android 12+ device', () => {
```

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/Views/LedgerConnect/index.test.tsx
> +  it('should show correct permission text when device is android 11 ', () => {
```suggestion
  it('displays android 11 permission text on android 11 device', () => {
```

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/Views/LedgerConnect/index.test.tsx
> +  it('should open how to install eth app link when clicked', () => {
```suggestion
  it('opens "how to install eth" on link', () => {
```

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/Views/LedgerConnect/index.test.tsx
> +        url: 'https://support.ledger.com/hc/en-us/articles/360009576554-Ethereum-ETH-?docs=true',
Suggestion: if you move the URL to the url file, also reference it here.

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/Views/LedgerConnect/index.test.tsx
> +  it('should call connectLedger when retry button is pressed', () => {
```suggestion
  it('calls connectLedger on retry button', () => {
```

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/hooks/useBluetoothPermissions.test.ts
> +  it('grants permissions on Android version 12 and above', async () => {
```suggestion
  it('grants permissions on Android 12+', async () => {
```

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/hooks/useBluetoothPermissions.test.ts
> +  it('denies permissions on Android version 12 and above', async () => {
```suggestion
  it('denies permissions on Android 12+', async () => {
```

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/hooks/useBluetoothPermissions.test.ts
> +  it('grants permissions on Android version below 12', async () => {
```suggestion
  it('grants permissions on Android <12', async () => {
```

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/hooks/useBluetoothPermissions.test.ts
> +  it('denies permissions on Android version below 12', async () => {
```suggestion
  it('denies permissions on Android <12', async () => {
```

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/hooks/useBluetoothPermissions.test.ts
> +  it('does not check permissions when app state changes to inactive', async () => {
```suggestion
  it('does not check permissions when app state changes to background', async () => {
```

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/hooks/useBluetoothPermissions.test.ts
> +  it('should still grants permissions when getSystemVersion is null', async () => {
```suggestion
  it('grants permissions when getSystemVersion is null', async () => {
```

2024-03-26 16:12 UTC, NicolasMassart commented on app/components/hooks/useBluetoothPermissions.test.ts
> +  it('should still grants permissions when getSystemVersion return not number', async () => {
```suggestion
  it('grants permissions when getSystemVersion return is not a number', async () => {
```

2024-03-27 05:26 UTC, dawnseeker8 commented on app/components/Views/LedgerConnect/index.test.tsx
> +        url: 'https://support.ledger.com/hc/en-us/articles/360009576554-Ethereum-ETH-?docs=true',
has used LEDGER_SUPPORT_LINK in url.ts const in this test.

2024-03-27 05:31 UTC, dawnseeker8 commented on app/components/UI/LedgerModals/LedgerConfirmationModal.test.tsx
> +    expect(getByTestId(ERROR_STEP)).toBeTruthy();
Add test to check the ledger connection error Title and body.

2024-03-27 11:20 UTC, NicolasMassart submitted a review, later dismissed
Looks good to me.
Thanks again for all the effort you put in following advice and taking account of feedback!

2024-04-02 14:32 UTC, vivek-consensys commented
Tested on Samsung S21 using Android 14.
Bitrise build:- https://app.bitrise.io/build/ce998116-a194-487f-a46d-315a8386cecb?tab=artifacts


https://github.com/MetaMask/metamask-mobile/assets/106310394/3c28e0c6-f51d-4400-a8c3-522a671636d0

2024-04-03 09:40 UTC, NicolasMassart approved these changes
Looks good to me.

2024-04-03 09:53 UTC, dawnseeker8 commented
I have also tested the android 9 with location permission, and all the issue marked by Mike has gone with latest library upgrade.

2024-04-03 09:54 UTC, merged