feat: Accounts controller integration
MetaMask/metamask-mobile pull request #8759
Opened 2024-02-28 00:30 UTC by owencraston

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-02-29 00:30 UTC, owencraston commented
@SocketSecurity ignore npm/@metamask/obs-store@9.0.0

2024-03-07 05:58 UTC, owencraston commented on app/components/Nav/App/index.js
> +  // TODO remove this useEffect before merging
Used for testing but will remove before merging.

2024-03-07 07:16 UTC, owencraston commented on app/core/Engine.ts
> -  | KeyringControllerEvents
this was a duplicate as you can see from line 235 above.

2024-03-15 09:46 UTC, ccharly commented on app/core/Engine.ts
> +                `Attempt to get permission specifications failed because their were ${accounts.length} accounts, but ${internalAccountCount} identities, and the ${keyringTypesWithMissingIdentities} k
```suggestion
                `Attempt to get permission specifications failed because there were ${accounts.length} accounts, but ${internalAccountCount} identities, and the ${keyringTypesWithMissingIdentities} keyrings included accounts with missing identities. Meanwhile, there are ${accountTrackerCount} accounts in the account tracker.`,
```

2024-03-15 09:46 UTC, ccharly commented on app/core/Permissions/specifications.js
> + * `AccountsController` internalAccount objects for all accounts in the
Is it me or the doc line are a bit mixed up? Shouldn't it be "in the current Metamask instance" here?

2024-03-15 09:46 UTC, ccharly commented on app/core/Permissions/specifications.js
> +            internalAccount.address.toLowerCase() ===
Same comment than earlier, maybe use `toChecksumAddress` here?

2024-03-15 09:46 UTC, ccharly commented on app/core/Permissions/specifications.js
> +            internalAccount.address.toLowerCase() ===
Same.

2024-03-15 09:46 UTC, ccharly commented on app/core/Permissions/specifications.js
> +      return accounts.sort((firstAddress, secondAddress) => {
Purely cosmetic small improvement, what about something like this (not tested):

```ts
const [firstAccount, secondAccount] = _.map([firstAddress, secondAddress], (address) => {
    const checksumedAddress = toChecksumAddress(address);
    const internalAccount = internalAccounts.find(
      (internalAccount) =>
        toChecksumAddress(internalAccount.address) === checksumedAddress
    );

    if (!internalAccount) {
        captureKeyringTypesWithMissingIdentities(internalAccounts, accounts);
        throw new Error(`Missing identity for address: "${address}".`);
    }

    return internalAccount;
});
```

This way, we only have conditions for the sort after we verified those "preconditions" (like having an internal account for a given address).

WDYT?

2024-03-15 09:46 UTC, ccharly commented on app/core/Permissions/specifications.js
> +          internalAccount.address.toLowerCase() === address.toLowerCase(),
Same comment for `.toChecksumAddress` here.

2024-03-15 09:46 UTC, ccharly commented on app/core/Permissions/specifications.test.js
> +          const getInternalAccounts = jest.fn().mockImplementationOnce(() => [
What about adding a:
```ts
const baseEoaAccount = {
  type: EthAccountType.Eoa,
  options: {},
  methods: [...Object.values(EthMethod)],
};
```

And use it for every test accounts we add with `...baseEoaAccount,`.

WDYT?

2024-03-15 09:46 UTC, ccharly commented on app/core/Permissions/specifications.js
> +      return accounts.sort((firstAddress, secondAddress) => {
Also, after re-reading some other code, I think than using other names like `accountA` or `accountB`, might be more suitable here (since we're sorting "any" account, and not only the first and second.

2024-03-15 09:46 UTC, ccharly commented on app/store/migrations/033.test.ts
> +describe('Migration #032', () => {
Shouldn't it be `#33`? (Given the filename and looks like other migrations use `#XY` form, without a leading 0)

2024-03-15 09:46 UTC, ccharly commented on app/store/migrations/033.test.ts
> +  describe('createDefaultAccountsController', () => {
Having a newline here would be nice.

2024-03-15 09:46 UTC, ccharly commented on app/core/Permissions/specifications.js
> +      return accounts.sort((firstAddress, secondAddress) => {
And finally. add a comment to explain in which order we sort the accounts. To my understanding, it's ordered by `.lastSelected` (highest `.lastSelected` get sorted in front, right?)

2024-03-15 09:46 UTC, ccharly commented on app/store/migrations/033.ts
> +      new Error(`Migration 32: Invalid root state: '${typeof state}'`),
32 -> 33 (everywhere in this file I guess)

2024-03-15 09:46 UTC, ccharly commented on app/store/migrations/033.ts
> +      account.address.toLowerCase() === selectedAddress.toLowerCase(),
`.toChecksumAddress`? :D

2024-03-15 09:46 UTC, ccharly commented on app/store/migrations/033.ts
> +    state.engine.backgroundState.AccountsController.internalAccounts = {
Couldn't we just use `....internalAccounts.selectedAccount = selectedAccount.id ?? '';` here?

2024-03-15 09:46 UTC, ccharly commented on app/store/migrations/033.test.ts
> +    sha256Spy = jest.spyOn(Aes, 'sha256').mockImplementation((address) => {
Isn't it redundant with what we have in the `testSetup.js` file?

2024-03-15 09:46 UTC, ccharly commented on patches/@metamask+accounts-controller+10.0.0.patch
> ++        // Snaps controller is not instanciated in the production MetaMask Mobile app (Flask only). For this reason we cannot subscriobe to this state change.
```suggestion
+        // Snaps controller is not instantiated in the production MetaMask Mobile app (Flask only). For this reason we cannot subscribe to this state change.
```

I'm not 100% sure for the `instantiated` here, I guess it's UK vs US form here? 🙈

But there was a typo for `subscriobe`!

2024-03-15 16:59 UTC, montelaidev commented
The accounts controller doesn't seem to update the selected account when changing accounts in the accounts picker

2024-03-15 21:25 UTC, owencraston commented on app/core/Engine.ts
> +          initialState.AccountsController?.internalAccounts?.accounts[
yeah good call. I'll add this in the latest commit.

2024-03-15 21:28 UTC, owencraston commented on app/core/Engine.ts
> +                `Attempt to get permission specifications failed because their were ${accounts.length} accounts, but ${internalAccountCount} identities, and the ${keyringTypesWithMissingIdentities} k
good catch

2024-03-15 21:38 UTC, owencraston commented on app/core/Engine.ts
> +                    account.address.toLowerCase() === address.toLowerCase(),
I wrote it this way to match the logic [inside extension](https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/metamask-controller.js#L1140). What is the benefit of computing the `.toLowerCase` outside of the `.some`? or are you suggesting that we use checkSum instead of lowercase?

2024-03-15 21:43 UTC, owencraston commented on app/core/Permissions/specifications.js
> + * `AccountsController` internalAccount objects for all accounts in the
🤦 yes,I guess I lost my train of thought mid sentence. what else is new 🤣 . Fixed in the latest commit.

2024-03-15 22:07 UTC, owencraston commented on app/core/Permissions/specifications.test.js
> +          const getInternalAccounts = jest.fn().mockImplementationOnce(() => [
good idea, especially since this object gets used a lot.

2024-03-15 22:07 UTC, owencraston commented on app/store/migrations/033.test.ts
> +describe('Migration #032', () => {
ah yes, it used to be 32 but I had to change it in a rebase and forgot to modify this. good catch. ❤️

2024-03-15 22:11 UTC, owencraston commented on app/store/migrations/033.test.ts
> +    sha256Spy = jest.spyOn(Aes, 'sha256').mockImplementation((address) => {
Guto and I paired on this and we were having issues getting the test setup to actually work so we added this. I went back and removed it just now and it seems like everything works without it so I will remove. I am not sure what changed but that is a nice win. I will remove it in the latest commit. cc @gantunesr

2024-03-15 22:12 UTC, owencraston commented on app/store/migrations/033.ts
> +      new Error(`Migration 32: Invalid root state: '${typeof state}'`),
rebase issues 🤦

2024-03-15 22:17 UTC, owencraston commented on app/store/migrations/033.ts
> +      account.address.toLowerCase() === selectedAddress.toLowerCase(),
I am following the same pattern set out [in the extension](https://github.com/MetaMask/metamask-extension/blob/b3b5ef664c3b64a0cbc9cb7d418ea77930f52dcc/app/scripts/migrations/105.ts#L116). Perhaps we need to discuss the correct pattern as a group. cc @montelaidev

2024-03-15 22:19 UTC, owencraston commented on app/store/migrations/033.ts
> +    state.engine.backgroundState.AccountsController.internalAccounts = {
yes, addressed in the latest commit.

2024-03-15 22:22 UTC, owencraston commented on patches/@metamask+accounts-controller+10.0.0.patch
> ++        // Snaps controller is not instanciated in the production MetaMask Mobile app (Flask only). For this reason we cannot subscriobe to this state change.
Nope, leave it to a European to be better at english spelling than a Canadian.

2024-03-15 22:26 UTC, owencraston commented on app/core/Permissions/specifications.js
> +      return accounts.sort((firstAddress, secondAddress) => {
I sent you a follow up discussion on slack.

2024-03-15 22:26 UTC, owencraston commented on app/store/migrations/033.ts
> +      new Error(`Migration 32: Invalid root state: '${typeof state}'`),
fixed

2024-03-15 22:44 UTC, owencraston commented on app/core/Engine.ts
> +  setSelectedAddress: (address: string) => {
@montelaidev I added this method and replaced all direct calls to `PreferencesController.setSelectedAddress(address);` in the U.I to address the selected address being out of sync. It seems to working well now.

2024-03-18 09:02 UTC, montelaidev commented on app/core/Permissions/specifications.test.js
> +    methods: [...Object.values(EthMethod)],
We can't really use all the EthMethods now, because they would also contain 4337 methods. The extension would also have to be updated as well.

2024-03-18 19:48 UTC, ccharly commented on app/core/Engine.ts
> +                    account.address.toLowerCase() === address.toLowerCase(),
Having it outside makes it (in theory) a bit faster since we don't need t re-compute the checksum address for `address` during each iterations of the `some` (since `address` do not change here, but `account.address` does change though)

2024-03-18 23:18 UTC, owencraston commented on app/core/Permissions/specifications.test.js
> +    methods: [...Object.values(EthMethod)],
I updated it to explicitly state each eth method.

2024-03-18 23:18 UTC, owencraston commented on app/core/Engine.ts
> +            ?.address ?? '',
updated.

2024-03-18 23:37 UTC, owencraston commented on app/core/Permissions/specifications.js
> +            internalAccount.address.toLowerCase() ===
I computed the lowerCase value outside of the .some for the performance gain but have kept it as lowercase until I get some feedback from @montelaidev on this.

2024-03-19 17:27 UTC, owencraston commented on app/core/Engine.ts
> +                    account.address.toLowerCase() === address.toLowerCase(),
moved it outside of the .some but kept the values lowercase as we discussed on slack.

2024-03-19 17:28 UTC, owencraston commented on app/store/migrations/033.ts
> +      account.address.toLowerCase() === selectedAddress.toLowerCase(),
Kept the values lowercase as per our discussion on slack.

2024-03-19 17:37 UTC, tommasini requested changes
Left a question and a comment <3

2024-03-19 17:37 UTC, tommasini commented on app/store/migrations/036.ts
> +export default async function migrate(state: unknown) {
Right now we introduced async migrations, this state will be a promise, it will needed to be resolved for we have the values:
You can follow this [example](https://github.com/MetaMask/metamask-mobile/pull/8952/files#diff-4765cfe076490c6bc280062ec607c7ae60e9e0fb842e5aa75d6b8c24f0da9ea6R13)

2024-03-19 17:37 UTC, tommasini commented on app/core/Engine.ts
> +  // This should be used instead of directly calling PreferencesController.setSelectedAddress or AccountsController.setSelectedAccount
Are we going with this format further because we do not want to use the listeners on the controllers? 
I don't know if my question makes sense but, why PreferencesController or AccountsControler do not have listener that changes the internal state when one of them change? (And we use only one further on the mobile repo)

2024-03-19 17:49 UTC, owencraston commented on app/core/Engine.ts
> +  // This should be used instead of directly calling PreferencesController.setSelectedAddress or AccountsController.setSelectedAccount
My reasoning here was that listeners have a lot more side effects than directly calling a function. In my eyes this is easier to maintain/reason about than parsing through a massive list of listeners. Also the extension uses the same pattern in conjunction with listeners so they are maintaining both patterns fairly well. this is a valid point though.

2024-03-19 17:50 UTC, owencraston commented on app/store/migrations/036.ts
> +export default async function migrate(state: unknown) {
resolved in the [latest commit](https://github.com/MetaMask/metamask-mobile/pull/8759/commits/e499d81c40ef20ceaf4602cbcd142eef67bad0f4).

2024-03-19 17:52 UTC, tommasini commented on app/core/Engine.ts
> +  // This should be used instead of directly calling PreferencesController.setSelectedAddress or AccountsController.setSelectedAccount
Thanks for the explanation! <3

2024-03-19 17:56 UTC, tommasini requested changes
One last comment 🙏

2024-03-19 17:56 UTC, tommasini commented on app/store/migrations/036.ts
> +        `Migration 35: Invalid root engine state: '${typeof state.engine}'`,
Can we update the migration number on the exception please?  And also if possible can we have this test cases on the migration test file as we have on older migrations?

2024-03-19 17:59 UTC, owencraston commented on app/store/migrations/036.ts
> +        `Migration 35: Invalid root engine state: '${typeof state.engine}'`,
🤦 fixed

2024-03-19 18:24 UTC, tommasini submitted a review, later dismissed
COOOL, awesome work!! LGTM!

2024-03-19 20:08 UTC, owencraston commented
There are no U.I changes that can be QA'd here so I will advocate for this PR to not enter QA but when I eventually migrate all of the U.I to reference the accounts controller in a [subsequent change ](https://github.com/MetaMask/accounts-planning/issues/235)we can QA those. That being said I will leave this decision up to @plasmacorral and @gantunesr

2024-03-19 22:50 UTC, owencraston commented
[QA builds](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/b2e2cfc0-94f9-46f4-9517-ce2f1f5fb3da)

2024-03-20 10:57 UTC, tommasini approved these changes, later dismissed
LGTM

2024-03-20 21:49 UTC, owencraston commented
[New QA builds](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/11117a34-077a-42c4-ba95-0c69f3845c85)

2024-03-21 16:45 UTC, owencraston commented on app/store/migrations/037.ts
> +      methods: [...Object.values(EthMethod)],
true because this wont apply to 4437 accounts.... I set them to this now

```
    methods: [
      EthMethod.PersonalSign,
      EthMethod.Sign,
      EthMethod.SignTransaction,
      EthMethod.SignTypedDataV1,
      EthMethod.SignTypedDataV3,
      EthMethod.SignTypedDataV4,
      EthMethod.PrepareUserOperation,
      EthMethod.PatchUserOperation,
      EthMethod.SignUserOperation,
    ],
```

2024-03-21 17:01 UTC, owencraston commented on app/store/migrations/037.ts
> +  }
We are handling this case above on this [line](https://github.com/MetaMask/metamask-mobile/pull/8759/files#diff-5ab5ef6bbca2dbda1ff1de6c748147b422c97b044b3c9d32a08ed048f0ef30d2R72) by simply creating the default state for the accounts controller. I added a test for this case in [this](https://github.com/MetaMask/metamask-mobile/pull/8759/commits/daadd0c96215fbd8fc35d250ca5cdea0aba8e455) commit.

2024-03-21 17:21 UTC, owencraston commented on app/store/migrations/037.ts
> +  }
I also don't think we should set the selected address in the preferences controller to an empty string since it can have a lot of unintended side effects.

2024-03-21 18:58 UTC, montelaidev commented on app/store/migrations/037.ts
> +  }
After discussion with @owencraston, the identities shouldn't be empty if there is a selectedAddress.

2024-03-21 19:00 UTC, montelaidev commented on app/store/migrations/037.ts
> +      methods: [...Object.values(EthMethod)],
we should exclude 
 ```EthMethod.PrepareUserOperation,
      EthMethod.PatchUserOperation,
      EthMethod.SignUserOperation,```
      
 These are the 4337 methods

2024-03-21 19:04 UTC, montelaidev approved these changes, later dismissed

2024-03-21 21:34 UTC, Cal-L approved these changes
LGTM

2024-03-21 22:06 UTC, merged