feat: preinstalled mobile snaps
MetaMask/metamask-mobile pull request #8827
Opened 2024-03-04 11:30 UTC by Jonathansoufer

## **Description**

This PR is part of the Notifications Project aiming to bring descentralised Notification/Auth to MetaMask. IN THIS PR, we're implementing a way to enable MetaMask mobile to read from FS an embedded snap, so we can embed auth snap into Mobile App by default.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this Snaps page and check the existence of a installed snap in a fresh installation.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-03 12:38 UTC, NicolasMassart commented on app/util/test/testSetup.js
> +  console.log("do nothing since we aren't testing the pre installed snaps"),
Q: we are not testing the snap but could we test the getPreinstalledSnap function or the object? Making the function a util and then use it in app/lib/snaps/preinstalled-snaps.ts could help at least test the function implem.

2024-04-16 17:55 UTC, owencraston commented
I am not sure if we will be able to solve this issue here but when I navigate to the test snap site (https://metamask.github.io/snaps/test-snaps/1.1.0/) it does not show the bip32 snap as installed. I am wondering if this will cause issues in the future where the state of the browser and the local snaps are out of sync and we direct people to the browser to perform certain actions. thoughts?
![Simulator Screenshot - iPhone 13 Pro - 2024-04-16 at 10 52 55](https://github.com/MetaMask/metamask-mobile/assets/22918444/a6a943b0-122c-407f-9cc0-d4a86d379276)

2024-04-16 19:54 UTC, owencraston commented on app/lib/snaps/preinstalled-snaps.ts
> +/* eslint-disable no-console */
any ideas as to how we could make this more dynamic. If we add more pre bundled snaps in the future this code will have to change a lot and it will get very repetitive. I was able to come up with something


```ts
/* eslint-disable no-console */
/* eslint-disable @typescript-eslint/no-var-requires, @typescript-eslint/no-require-imports, import/no-commonjs*/
import { assert } from '@metamask/utils';
import getPreinstalledSnap from '../../util/snaps/getPreinstalledSnap';

// List of pre installed snaps
const snapModules = ['@metamask/bip32-example-snap'];

async function loadSnapAssets(snapName: string) {
  let bundleJs, manifestJson, icon;
  let bundlePath = 'dist/bundle.js';
  let iconPath = 'images/icon.svg';

  try {
    manifestJson = await import(
      `../../../node_modules/${snapName}/snap.manifest.json`
    );
    assert(
      manifestJson,
      new TypeError(`ManifestJson not found for ${snapName}`),
    );

    bundlePath = manifestJson.source.location.npm.filePath;
    bundleJs = await import(`../../../node_modules/${snapName}/${bundlePath}`);
    assert(bundleJs, new TypeError(`BundleJs not found for ${snapName}`));

    iconPath = manifestJson.source.location.npm.iconPath;
    try {
      icon = await import(`../../../node_modules/${snapName}/${iconPath}`);
    } catch (error) {
      console.warn(
        `Icon not found for ${snapName} at ${iconPath}, using default icon.`,
      );
      icon = ''; // what is the default?
    }
  } catch (error) {
    console.error(`Error loading assets for ${snapName}: ${error}`);
    throw error;
  }

  return {
    bundleJs,
    manifestJson,
    icon,
    bundlePath,
    iconPath,
  };
}

export async function loadPreinstalledSnaps() {
  const snapsPromises = snapModules.map(async (snapName) => {
    const { manifestJson, icon, bundleJs, iconPath, bundlePath } =
      await loadSnapAssets(snapName);
    return getPreinstalledSnap(snapName, manifestJson, [
      {
        path: iconPath,
        value: icon,
      },
      {
        path: bundlePath,
        value: JSON.stringify(bundleJs),
      },
    ]);
  });

  const PREINSTALLED_SNAPS = await Promise.all(snapsPromises);
  return PREINSTALLED_SNAPS;
}

const PREINSTALLED_SNAPS = await loadPreinstalledSnaps();

export default PREINSTALLED_SNAPS;

```

The issue is that this requires top level await which I do not think is currently supported on RN (we should verify this). Do you see a way we could implement something like what I have above? One option would be to change the `preinstalledSnaps?: PreinstalledSnap[];` to intake a generator function?

2024-04-16 19:54 UTC, owencraston commented on app/lib/snaps/preinstalled-snaps.ts
> +/* eslint-disable no-console */
I tried using dynamic require here but it did not work with variables.

2024-04-17 21:03 UTC, Jonathansoufer commented
> I am not sure if we will be able to solve this issue here but when I navigate to the test snap site (https://metamask.github.io/snaps/test-snaps/1.1.0/) it does not show the bip32 snap as installed. I am wondering if this will cause issues in the future where the state of the browser and the local snaps are out of sync and we direct people to the browser to perform certain actions. thoughts? ![Simulator Screenshot - iPhone 13 Pro - 2024-04-16 at 10 52 55](https://private-user-images.githubusercontent.com/22918444/322949282-a6a943b0-122c-407f-9cc0-d4a86d379276.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNTkwNTIsIm5iZiI6MTcxMzM1ODc1MiwicGF0aCI6Ii8yMjkxODQ0NC8zMjI5NDkyODItYTZhOTQzYjAtMTIyYy00MDdmLTljYzAtZDRhODZkMzc5Mjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEyNTkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZDkxZjkwMTQxNDBmNTkwNGViMDdhOGE5MGQxZjQxOGRhN2EyNzk3MmVkOTU1MGIwOTk1Yzg1NjI1ZmQ1ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-2ZOBfzkXybbOYab-guHvNN9Nlv4RLV0elZ4UYPZh1Y)

Good catch @owencraston , but I think that wouldn't be a problem since in the first call, that RPC would note the installation and proceed instantly as shown below.

https://github.com/MetaMask/metamask-mobile/assets/44679989/afa92a44-a832-4c3c-aadf-082bcd289610

2024-04-17 21:07 UTC, Jonathansoufer commented on app/lib/snaps/preinstalled-snaps.ts
> +/* eslint-disable no-console */
Indeed dynamic require/imports doesn't work as we want on RN. To achieve what you coded above, we would need to change `preinstalledSnaps` asap and I'm afraid that would impact Notifications' deadlines immensely. So, I came up with a **not so nice** approach but delivers the ability to work with more than just one embedded snap. We can revisit this theme after notifications and try to come up with a better solution as proposed by you.

2024-04-29 15:18 UTC, owencraston submitted a review, later dismissed

2024-04-30 21:07 UTC, legobeat requested changes, later dismissed

2024-04-30 21:07 UTC, legobeat commented on yarn.lock
> +<<<<<<< HEAD
Merge-conflict markers commited in lockfile. If you remove both versions and run `yarn install && yarn deduplicate`, it should do the right thing.

2024-05-01 18:04 UTC, legobeat commented on app/lib/snaps/preinstalled/bip32/index.ts
> +const bundleJs = require('../../../../../node_modules/@metamask/bip32-example-snap/dist/bundle.js');
Is there a reason why these need relative path and can't resolve normally from package names? If so could we leave a comment as to why?
```suggestion
const bundleJs = require('@metamask/bip32-example-snap/dist/bundle.js');
```

(same on line below).

2024-05-01 18:05 UTC, legobeat commented on package.json
> +    "@noble/secp256k1": "^1.7.1",
https://github.com/MetaMask/metamask-mobile/actions/runs/8908666381/job/24464750583?pr=8827

2024-05-02 12:19 UTC, Jonathansoufer commented on package.json
> +    "@noble/secp256k1": "^1.7.1",
Added by mistake. Removed.

2024-05-02 14:02 UTC, Jonathansoufer commented on app/lib/snaps/preinstalled/bip32/index.ts
> +const bundleJs = require('../../../../../node_modules/@metamask/bip32-example-snap/dist/bundle.js');
Fixed.

2024-05-03 12:54 UTC, FrederikBolding commented on package.json
> +    "@metamask/bip32-example-snap": "^2.1.1",
Why are we installing the BIP32 example Snap?

2024-05-03 12:57 UTC, FrederikBolding commented on app/lib/snaps/preinstalled-snaps.ts
> +const PREINSTALLED_SNAPS = Object([
```suggestion
const PREINSTALLED_SNAPS = Object.freeze([
```

2024-05-03 12:57 UTC, FrederikBolding commented on app/lib/snaps/preinstalled-snaps.ts
> +const { name, manifestJson, icon, bundleJs } = bip32;
This entire file can probably just mirror the extension now: https://github.com/MetaMask/metamask-extension/blob/2380a8df87d1dd4a62a9cfafd0bc00ddd77c11c4/app/scripts/snaps/preinstalled-snaps.ts#L1-L8

2024-05-04 18:44 UTC, Jonathansoufer commented on app/lib/snaps/preinstalled-snaps.ts
> +const { name, manifestJson, icon, bundleJs } = bip32;
Cool! I didn't know about the evolution on extention. Changed to mirro this implementation then,.

2024-05-04 18:45 UTC, Jonathansoufer commented on package.json
> +    "@metamask/bip32-example-snap": "^2.1.1",
This was the package we were using as example while we didn't have `@metamask/message-signing-snap`. Removed.

2024-05-06 17:55 UTC, FrederikBolding approved these changes, later dismissed

2024-05-06 22:01 UTC, Jonathansoufer commented on yarn.lock
> +<<<<<<< HEAD
Fixed.

2024-05-06 22:10 UTC, legobeat commented on yarn.lock
> +<<<<<<< HEAD
@Jonathansoufer Still needs a `yarn deduplicate`: https://github.com/MetaMask/metamask-mobile/actions/runs/8976319546/job/24652990789?pr=8827

2024-05-06 22:32 UTC, Jonathansoufer commented on yarn.lock
> +<<<<<<< HEAD
just ran again.

2024-05-07 07:28 UTC, FrederikBolding approved these changes

2024-05-07 17:00 UTC, owencraston approved these changes
Looks good! Great work.

2024-05-07 21:30 UTC, merged