test: 1453 refactor modal pages batch 3
MetaMask/metamask-mobile pull request #8909
Opened 2024-03-12 17:33 UTC by SamuelSalas

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-03-20 06:15 UTC, chrisleewilcox commented on e2e/utils/Matchers.js
> +    return element(by.id(id).and(by.label(label)));
Missing .atIndex(index)

2024-03-22 22:31 UTC, cortisiko requested changes

2024-03-22 22:31 UTC, cortisiko commented on e2e/utils/Matchers.js
> +   * Get element by text.
Elaborate on this more, don't we already have a matcher for getting element by text?

2024-03-22 22:31 UTC, cortisiko commented on e2e/utils/Matchers.js
> +  static async getElementByIDAndLabel(id, label, index = 0) {
I see we will locate an element by combining two locator strategies. I am curious to understand why we have this matcher.

2024-03-22 22:31 UTC, cortisiko commented on e2e/pages/modals/NetworkListModal.js
> +    return Matchers.getElementByIDAndLabel(CellModalSelectorsIDs.SELECT, regex);
Is this problematic for both iOS and Android? 
```
    return Matchers.getElementByIDAndLabel(CellModalSelectorsIDs.SELECT, regex);
```

2024-03-30 01:07 UTC, SamuelSalas commented on e2e/utils/Matchers.js
> +  static async getElementByIDAndLabel(id, label, index = 0) {
While working on the `add-custom-rpc.spec.js`, in ios I found some problem, detox was not able to select the just added custom network. Detox is detecting the network name as "G Gnosis", adding the network icon letter to the beginning of the name. So this strategy is looking for the specific network label with elements that share the same id.

2024-04-17 16:25 UTC, cortisiko commented on e2e/utils/Matchers.js
> +  static async getElementByIDAndLabel(id, label, index = 0) {
Does

> detox was not able to select the just added custom network


 happen on main or only on your branch? If that is the case then we should use the same locator strategy on android re: https://github.com/MetaMask/metamask-mobile/pull/8909#discussion_r1536280411.

 We should hop on a call to chat about this some more.

2024-04-17 16:26 UTC, cortisiko commented
@SamuelSalas I left a follow up comment. Also there are merge conflicts on your PR. Will move it back to dev in progress

2024-04-17 17:43 UTC, SamuelSalas commented on e2e/utils/Matchers.js
> +  static async getElementByIDAndLabel(id, label, index = 0) {
This implementation is not compatible with android because is not detecting the icon letter as part of the custom network, so the regular `getElementByText` works without any issue. The reason why this script is not failing on main is because `checkIfElementHasString` from the helpers.js file. With this current implementation, i have trying to move away from it because is lint is throwing a warning and is not technically supported by detox.
<img width="1282" alt="image" src="https://github.com/MetaMask/metamask-mobile/assets/22276767/4a393428-ea76-4bd5-bd02-00b132c84287">
<img width="767" alt="image" src="https://github.com/MetaMask/metamask-mobile/assets/22276767/048dc1f0-c037-402a-b6d4-9eee490e25f8">

2024-04-18 01:20 UTC, cortisiko commented on e2e/pages/modals/NetworkListModal.js
> +  get testSwitch() {
rename this to be more explicit

2024-04-18 01:20 UTC, cortisiko commented on e2e/pages/modals/NetworkListModal.js
> +  async changeToNetwork(networkName) {
we should only have one method to switch networks. No need to duplicate efforts

2024-04-18 01:20 UTC, cortisiko commented on e2e/pages/modals/NetworkListModal.js
> +  async changeToCustomNetwork(networkName) {
see above comment

2024-04-18 13:23 UTC, SamuelSalas commented on e2e/utils/Matchers.js
> +   * Get element by text.
Resolved

2024-04-18 13:23 UTC, SamuelSalas commented on e2e/pages/modals/NetworkListModal.js
> +  async changeToCustomNetwork(networkName) {
Resolved

2024-04-18 13:24 UTC, SamuelSalas commented on e2e/pages/modals/NetworkListModal.js
> +  async changeToNetwork(networkName) {
Resolved

2024-04-18 19:20 UTC, cortisiko commented on e2e/pages/modals/NetworkListModal.js
> +  get testSwitch() {
@SamuelSalas can you rename to something like: `test net-toggle `or something of that nature? It makes it a bit more explicit. Also rename the selector variable to be more specific as well: `TESTNETTOGGLE` or something of that nature

2024-04-18 19:40 UTC, cortisiko commented on e2e/utils/Matchers.js
> +  static async getElementByIDAndLabel(id, label, index = 0) {
ah great okay, I follow now. The only other comment here is to add a description in the js doc for the above locator strategy. Make clear the purpose and when to use.

2024-04-18 21:20 UTC, cortisiko approved these changes, later dismissed
✅ ✅ ✅

2024-04-24 21:07 UTC, cortisiko approved these changes, later dismissed

2024-04-25 01:56 UTC, SamuelSalas commented
Latest bitrise test run: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/a21ca4f5-9020-47e1-9b2b-97b49d4b5ddd

2024-04-25 14:43 UTC, cortisiko approved these changes

2024-04-25 14:47 UTC, merged