ci: Simplify PR template
MetaMask/metamask-mobile pull request #8918
Opened 2024-03-13 14:15 UTC by Gudahtt

## **Description**

The PR template checklist has been simplified. The changes are as follows:

* The checkbox about using a draft has been replaced by a comment at the top of the template
* The checkboxes about using the template properly have been consolidated into a "I have completed the template" checkbox

This should streamline the process of creating a PR for contributors, while preserving all the same requirements.

## **Related issues**

N/A

## **Manual testing steps**

N/A

## **Screenshots/Recordings**

N/A

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-03-13 18:57 UTC, Gudahtt commented on .github/pull-request-template.md
> +Do not mark it as "Ready for review" until the template has been completely filled out, and PR status checks have passed at least once.
Not sure on exactly what criteria we should suggest here for something being ready for review, but this seemed like a good starting point

2024-03-13 19:24 UTC, Gudahtt commented on .github/pull-request-template.md
> +- [ ] I've completed the PR template to the best of my ability
Alternatively we could omit this, and assume the PR author has properly reviewed and filled out the template.

But having it here as an explicit step might be a useful reminder, especially in cases where a PR sits in draft for a while, with the template partially filled out. This is a good reminder to go back and review.

2024-03-19 08:45 UTC, danjm requested changes
This looks good to me. Were you also going to make a change to put one or more of the checkboxes in a comment?

2024-03-19 11:46 UTC, Gudahtt commented
@danjm Sorry I am not sure what you're referring to

2024-03-19 16:46 UTC, danjm approved these changes
Ignore my last comment, I was misremembering something from a past conversation. This looks good to ship

2024-03-19 18:19 UTC, gauthierpetetin commented on .github/pull-request-template.md
> +Do not mark it as "Ready for review" until the template has been completely filled out, and PR status checks have passed at least once.
I think the initial purpose for placing the **Description** section at the very top was to have the description previewed when PR is posted on Slack.
cc @NicolasMassart as it was initially brought up by you I believe

2024-03-19 18:28 UTC, Gudahtt commented on .github/pull-request-template.md
> +Do not mark it as "Ready for review" until the template has been completely filled out, and PR status checks have passed at least once.
Interesting! I think this comment would be omitted from the preview, but that's a great point, we should test this to make sure

2024-03-19 18:31 UTC, Gudahtt commented on .github/pull-request-template.md
> +Do not mark it as "Ready for review" until the template has been completely filled out, and PR status checks have passed at least once.
I have just tested this by adding a comment to the description of this PR, and sharing it with myself. I also added the text "(this text was added to test PR preview)" to the description to ensure I didn't get a cached copy.

It looks like only rendered content is included in the preview, so this comment will not affect it.

2024-03-19 18:56 UTC, gauthierpetetin commented on .github/pull-request-template.md
> +Do not mark it as "Ready for review" until the template has been completely filled out, and PR status checks have passed at least once.
Ok great, thanks for the test

2024-03-21 14:52 UTC, sethkfman commented on .github/pull-request-template.md
> +- [ ] I've completed the PR template to the best of my ability
Let's leave it for now and we can refine again in a few weeks.

2024-03-21 14:53 UTC, sethkfman approved these changes
LGTM

2024-03-21 17:30 UTC, gauthierpetetin approved these changes

2024-03-21 17:56 UTC, merged