feat: add the 'eth_phishing_detection' logic to the connect accounts flow
MetaMask/metamask-mobile pull request #8920
Opened 2024-03-13 16:49 UTC by omridan159

## **Description**

Add the 'eth_phishing_detection' logic to the connect accounts flow

eth_phishing_detection is a utility for detecting phishing domains targeting Web3 users.
For checking why a given domain was blocked, there is a third-party search tool maintained by ChainPatrol.

Now when user connects to a dapp via SDK that's url is blacklisted in our eth_phishing_detection list, MetaMask mobile app should show a warning to the user before selecting to connect or not. This will allow MetaMask to warn the user while letting user to decide what to do next.

## Screenshots

### WC 

https://github.com/MetaMask/metamask-mobile/assets/61094771/cacef0ac-17f6-4672-b830-450f30d2e4b4

### MM_SDK
https://github.com/MetaMask/metamask-mobile/assets/61094771/58358497-82e1-4783-891e-76d37b6a0bfd

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've clearly explained what problem this PR is solving and how it is solved.
- [x] I've linked related issues
- [x] I've included manual testing steps
- [x] I've included screenshots/recordings if applicable
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [x] I’ve properly set the pull request status:
  - [x] In case it's not yet "ready for review", I've set it to "draft".
  - [x] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-03-14 07:13 UTC, abretonc7s commented on app/core/SDKConnect/Connection/EventListenersHandlers/handleClientsReady.ts
> +            instance.origin !== AppConstants.DEEPLINKS.ORIGIN_QR_CODE
why do we need this new condition?

2024-03-14 07:45 UTC, abretonc7s approved these changes, later dismissed

2024-03-14 09:31 UTC, andreahaku approved these changes, later dismissed
LGTM

2024-03-18 19:07 UTC, christopherferreira9 commented
**WalletConnect example:**

https://github.com/MetaMask/metamask-mobile/assets/104831203/b93b3989-cd56-4054-bf54-221430410236

**MetaMask SDK Example:**

https://github.com/MetaMask/metamask-mobile/assets/104831203/c256252f-9002-4902-b1a7-781e8a1e0adc

Verified that:
- All links work in the modal
- Connection to both WalletConnect and SDK are terminated once the user taps "Back to safety"
- Tested on both iOS and Android

2024-03-19 08:02 UTC, andreahaku approved these changes, later dismissed
LGTM

2024-03-19 08:02 UTC, abretonc7s commented on app/components/Views/AccountConnect/AccountConnect.tsx
> +  const renderPhishingModal = () => (
add useCallback

2024-03-19 08:03 UTC, abretonc7s requested changes
small change to have consistent use of useCallback

2024-03-20 12:37 UTC, abretonc7s approved these changes

2024-03-20 14:22 UTC, christopherferreira9 commented
Looking good for QA.

2024-03-20 14:22 UTC, merged