Feat: notifications UI
MetaMask/metamask-mobile pull request #8961
Opened 2024-03-15 17:41 UTC by Jonathansoufer

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-11 17:13 UTC, brianacnguyen commented
Hi @Jonathansoufer can you link the figma file attached to this?

2024-04-15 04:56 UTC, Cal-L reviewed
Left some comments on a few reviewed files. Since there are some pretty significant changes in this feature, I'd like to request to break this out into smaller scoped PRs. In addition to good practice, this suggested approach is inline with the team's mission in making PRs more reviewable + reducing chances of bugs. It will also result in a quicker turn around time and enable members from all teams to review the different chunks. 
I'd recommend breaking it out in terms of dependencies and testability (unit testable). Here are some examples of how it can be broken out:
- component-library
- onboarding wizard
- boiler plate for actions and reducers
- third party libs
- image assets
- Notification screens (NotificationsView, NotificationsDetails, GasDetails, etc)
- translations
- notifications utils
- Lastly, hooking up all of the business logic so to connect all of the above

2024-04-15 04:56 UTC, Cal-L commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/README.md
> +# [BadgeNotifications](https://metamask-consensys.notion.site/Badge-Notifications-94a679c50cb446f4844dc624b4f74946)
Use Badge notification content

2024-04-15 04:56 UTC, Cal-L commented on app/components/Nav/Main/MainNavigator.js
> +  <Stack.Navigator initialRouteName={'NotificationsOptIn'}>
Put name in Routes constants file. Same with all of the other names

2024-04-15 04:56 UTC, Cal-L commented on app/components/Nav/Main/MainNavigator.js
> +      name="NotificationsOptIn"
Put name in Routes constants file

2024-04-15 04:56 UTC, Cal-L commented on app/components/Nav/Main/MainNavigator.js
> +      name="NotificationsSettings"
Put name in Routes constants file

2024-04-15 04:56 UTC, Cal-L commented on app/components/UI/Navbar/index.js
> +      navigation.navigate('NotificationsView');
use constant from Routes constants file

2024-04-15 04:56 UTC, Cal-L commented on app/components/UI/OnboardingWizard/Step6/index.js
> +  some: {
Let's provide a more unique name for this

2024-04-15 04:56 UTC, Cal-L commented on app/components/UI/OnboardingWizard/Step6/index.js
> +    navigation && navigation.navigate('WalletView');
Use constant from Routes

2024-04-15 04:56 UTC, Cal-L commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.test.tsx
> +import { shallow } from 'enzyme';
Use react testing library instead

2024-04-15 04:56 UTC, Cal-L commented on app/components/UI/OnboardingWizard/Step7/index.test.tsx
> +import { shallow } from 'enzyme';
Use react testing library instead

2024-04-15 04:56 UTC, Cal-L commented on app/components/Views/Notifications/Details/FcmView.tsx
> +      screen: 'SimpleWebview',
Use constant from Routes

2024-04-15 04:56 UTC, Cal-L commented on app/components/Views/Notifications/Details/FcmView.tsx
> +          source={{ uri: notification.data.image.file.url }}
I suspect this may crash the app if url isn't defined. Is there a fallback view in the designs?

2024-04-15 04:56 UTC, Cal-L commented on app/components/Views/Notifications/Details/FcmView.tsx
> +            (notification.data?.link as unknown as { linkText?: string })
Let's abstract this out into a variable since it's a complex condition

2024-04-18 15:03 UTC, brianacnguyen requested changes
Can you add the figma link to the description?

2024-04-30 19:56 UTC, closed without merging