Chore/generate rc commits
MetaMask/metamask-mobile pull request #8963
Opened 2024-03-15 20:45 UTC by sethkfman

## **Description**

This PR includes a script to generate the changes between two branches. It will create a `csv` that is use by QA during release testing. 

## **Related issues**

Fixes:

## **Manual testing steps**

1. Fetch the latest from the repo
2. Run command `./generate-rc-commits vx.x.x release/x.x.x`
3. Look for csv called commits.csv 

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've clearly explained what problem this PR is solving and how it is solved.
- [ ] I've linked related issues
- [ ] I've included manual testing steps
- [ ] I've included screenshots/recordings if applicable
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.
- [ ] I’ve properly set the pull request status:
  - [ ] In case it's not yet "ready for review", I've set it to "draft".
  - [ ] In case it's "ready for review", I've changed it from "draft" to "non-draft".

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-03-15 21:07 UTC, cortisiko requested changes
left a few comments

2024-03-15 21:07 UTC, cortisiko commented on scripts/generate-rc-commits.js
> +  'Extension Platform': [
any reason why we need the extension platform team?

2024-03-15 21:07 UTC, cortisiko commented on scripts/generate-rc-commits.js
> +  'Extension UX': ['David Walsh', 'vthomas13', 'Nidhi Kumari', 'Victor Thomas'],
Perhaps rename to Wallet UX?

2024-03-15 21:07 UTC, cortisiko commented on scripts/generate-rc-commits.js
> +    'Brian Bergeron',
Add mike to this list as well. @plasmacorral

2024-03-15 21:07 UTC, cortisiko commented on scripts/generate-rc-commits.js
> +  SDK: ['abretonc7s'],
@christopherferreira9, @omridan159 @andreahaku as well for the SDK

2024-03-15 21:07 UTC, cortisiko commented on scripts/generate-rc-commits.js
> +};
can we also have a hardware wallet group as well? @vivek-consensys @stanleyyconsensys should be part of this group

2024-03-15 21:07 UTC, cortisiko commented on scripts/generate-rc-commits.js
> +    'Derek Brans',
add @sleepytanya to this list as well.

2024-03-15 21:10 UTC, plasmacorral commented on scripts/generate-rc-commits.js
> +    'Howard Braham',
Howard is not a member of the accounts team

2024-03-15 21:11 UTC, plasmacorral commented on scripts/generate-rc-commits.js
> +    'Brian Bergeron',
I think Brian is on the assets team

2024-03-18 11:28 UTC, jpcloureiro commented
Is there anyone in charge of keeping the `JSON mapping authors to teams` up to date?

2024-03-18 18:31 UTC, sethkfman commented
@jpcloureiro The delivery team will be updating this each time the run an analysis. It flags the unknown members and they can be added to the sheet.

2024-03-21 17:50 UTC, plasmacorral commented on scripts/generate-rc-commits.js
> +  ],
Ok, one more team member to add to accounts, please: Charly Chevalier

2024-03-21 17:54 UTC, plasmacorral submitted a review, later dismissed
looks good to me, Accounts team members are accurate

2024-03-22 12:47 UTC, gantunesr commented
Why certain names show up as their actual names and other as their GH handle? Which one is the correct?

2024-03-27 16:13 UTC, sethkfman commented
@gantunesr It is based on the users git config and what is provided in the commit logs. Eventually we will be modifying the script to use team names.

2024-03-27 16:14 UTC, sethkfman commented
@SocketSecurity ignore npm/simple-git@3.22.0

2024-04-30 14:56 UTC, sethkfman commented
replaced by #9425

2024-04-30 14:56 UTC, closed without merging