feat(ramp): add activation keys labels and DS components
MetaMask/metamask-mobile pull request #9119
Opened 2024-04-03 14:00 UTC by wachunei

> [!Note]
> Supersedes #8549

## **Description**

This PR changes the components used in the Settings views of Buy & Sell and adds a label property to the activation keys (not used in production). 

## **Related issues**

Closes #8549 

## **Manual testing steps**

1. Go to Settings (Development or Ramp UAT build)
2. Go to Buy and Sell Crypto
3. Add Activation Key
4. Edit Activation Key

## **Screenshots/Recordings**

### **Before**

https://github.com/MetaMask/metamask-mobile/assets/1024246/df7b4e39-eee7-4e9d-ba40-503fe7f22486

### **After**

https://github.com/MetaMask/metamask-mobile/assets/1024246/13f68328-5f1f-4efb-bf65-fdec81c694cc

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-09 16:33 UTC, brianacnguyen commented on app/components/UI/Ramp/Views/Settings/ActivationKeyForm.tsx
> +            <Label>{strings('app_settings.fiat_on_ramp.label')}</Label>
loving the use of DS here!

2024-04-09 16:34 UTC, brianacnguyen commented on app/components/UI/Ramp/Views/Settings/ActivationKeyForm.tsx
> +import TextField from '../../../../../component-library/components/Form/TextField';
can you clean up the imports?
- internal =  usually anything within the same folder or similar internal dependencies
- external = anything within this repo
- third party = anything outside

2024-04-09 16:34 UTC, brianacnguyen commented on app/components/UI/Ramp/Views/Settings/ActivationKeys.tsx
> +        <Text variant={TextVariant.BodyMD} color={TextColor.Alternative}>
thank you @wachunei

2024-04-09 16:35 UTC, brianacnguyen requested changes
just a small change requested regarding imports

2024-04-10 16:03 UTC, brianacnguyen approved these changes, later dismissed

2024-04-25 17:52 UTC, bkirb commented
@wachunei LGTM for QA ✅

2024-04-26 10:02 UTC, tommasini approved these changes, later dismissed
LGTM!
Small nit, it makes sense to keep two components under Settings folder on Ramps folder?

2024-05-02 21:34 UTC, wachunei commented
@tommasini @brianacnguyen I had to solve conflicts manually and reviews went stale, would you mind re-approving please 🙏

2024-05-07 16:06 UTC, georgeweiler commented on app/components/UI/Ramp/Views/Settings/ActivationKeyForm.tsx
> +export const creatActivationKeyFormNavDetails =
small typo here

2024-05-07 16:08 UTC, wachunei commented on app/components/UI/Ramp/Views/Settings/ActivationKeyForm.tsx
> +export const creatActivationKeyFormNavDetails =
fixed in 441c05193

2024-05-07 16:37 UTC, georgeweiler submitted a review, later dismissed

2024-05-07 22:34 UTC, georgeweiler approved these changes

2024-05-08 14:54 UTC, merged