feat: setting for showing fiat conversions on testnets
MetaMask/metamask-mobile pull request #9129
Opened 2024-04-04 01:21 UTC by bergeron

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-11 01:58 UTC, bergeron commented on app/components/Views/Settings/AdvancedSettings/FiatOnTestnetsFriction/FiatOnTestnetsFriction.tsx
> +        <Text style={styles.heading}>
I don't want to use the deprecated `<Text>`.  But when i tried to use the new one, I couldn't prevent it from adding too much left padding:

![image](https://github.com/MetaMask/metamask-mobile/assets/3500406/925be710-62a5-4ead-a7b3-e55aaef8b87e)

2024-04-11 02:13 UTC, bergeron commented on app/components/UI/AssetOverview/Balance/Balance.tsx
> +      <Text style={styles.text}>{fiatBalance ? balance : ''}</Text>
Improves the case where there is no fiat value.  It used to show this:
<img width="377" alt="Screenshot 2024-04-10 at 7 12 00 PM" src="https://github.com/MetaMask/metamask-mobile/assets/3500406/2e8f12e2-bbbe-4cb1-bc8a-7cd269a8b829">

But the balance was loaded.  It's just the fiat value that isn't available.  So I made it fallback to the balance:
<img width="378" alt="Screenshot 2024-04-10 at 7 12 49 PM" src="https://github.com/MetaMask/metamask-mobile/assets/3500406/7626a265-9d91-4dff-ae36-c77d16972d2b">

2024-04-16 16:26 UTC, salimtb commented on locales/languages/en.json
> +    "show_fiat_on_testnets_modal_button": "Continue",
you should create a separate PR for all the locales in addition of the changes above and merge it with the label `area-translation` , once it's done you should merge that one.
DM if you want more explanation about this process

2024-04-16 16:28 UTC, salimtb commented
i just triggered the e2e tests on your PR ⬆️

2024-04-17 08:47 UTC, salimtb commented
@bergeron you have to check the failing e2e tests

2024-04-22 21:14 UTC, bergeron commented on locales/languages/en.json
> +    "show_fiat_on_testnets_modal_button": "Continue",
https://github.com/MetaMask/metamask-mobile/pull/9361

2024-04-24 17:28 UTC, darkwing reviewed
Works beautifully but can we increase test coverage to prevent regression?  Speaking from experience, lack of tests hurt on extension for this feature.

2024-04-26 04:02 UTC, bergeron commented
Added basic unit and e2e tests

2024-04-30 20:54 UTC, legobeat commented
I think it would make sense to add a small advisory badge or label in the UI next to the fiat value on testnets that indicates that this is indeed "not real money" to avoid this feature being leveraged as a vector for scams.

2024-05-01 15:28 UTC, bergeron commented
> I think it would make sense to add a small advisory badge or label in the UI next to the fiat value on testnets that indicates that this is indeed "not real money"

I think this is challenging because there are so many places in the UI that show fiat values.  But perhaps the main balance on the home page would be sufficient.

The existing behavior before introducing this setting is that we've always been showing fiat values on testnets, so it's becoming much safer to be off by default.

2024-05-01 15:55 UTC, alfeng6 commented
I like the idea of badges to represent tokens with no monetary value but it should be a separate design effort so that we are intentional about where to put badges.

This current work already improves the security of our app. But the badge work will do even better.

2024-05-03 16:14 UTC, cortisiko requested changes
Left a few comments. Thanks for writing a new e2e test for this flow!

2024-05-03 16:14 UTC, cortisiko commented on e2e/specs/settings/fiat-on-testnets.spec.js
> +import { CONTINUE_BUTTON } from '../../../wdio/screen-objects/testIDs/Components/FiatOnTestnetsModal.testIds';
avoid creating selector strings in the wdio folder. Create the selector strings in e2e/selectors. See example here: https://github.com/MetaMask/metamask-mobile/blob/6da4cf9e20ec46c6a7babcab959b6877aec27f2a/e2e/selectors/Modals/ConnectAccountModal.selectors.js

2024-05-03 16:14 UTC, cortisiko commented on e2e/specs/settings/fiat-on-testnets.spec.js
> +        await TestHelpers.waitAndTap(CONTINUE_BUTTON);
This continue button seems to be related to the new sheet to enable test net fiat balances. I recommend creating a page object for that sheet similar to https://github.com/MetaMask/metamask-mobile/blob/main/e2e/pages/modals/ConnectedAccountsModal.js and put all the elements and actions related to that sheet there.  

Feel free to read up more [here](https://github.com/MetaMask/contributor-docs/blob/main/docs/e2e/mobile-e2e-guidelines.md)

2024-05-03 16:14 UTC, cortisiko commented on e2e/specs/settings/fiat-on-testnets.spec.js
> +import { TOTAL_BALANCE_TEXT } from '../../../wdio/screen-objects/testIDs/Components/Tokens.testIds.js';
Same comment as above.

2024-05-06 22:04 UTC, bergeron commented on e2e/specs/settings/fiat-on-testnets.spec.js
> +import { CONTINUE_BUTTON } from '../../../wdio/screen-objects/testIDs/Components/FiatOnTestnetsModal.testIds';
done in https://github.com/MetaMask/metamask-mobile/pull/9129/commits/f9120b2fb1fc9a3964e55fc8b30521ee03a18cde

2024-05-06 22:04 UTC, bergeron commented on e2e/specs/settings/fiat-on-testnets.spec.js
> +        await TestHelpers.checkIfElementNotToHaveText(TOTAL_BALANCE_TEXT, '$0');
done in https://github.com/MetaMask/metamask-mobile/pull/9129/commits/f9120b2fb1fc9a3964e55fc8b30521ee03a18cde

2024-05-06 22:07 UTC, bergeron commented on e2e/specs/settings/fiat-on-testnets.spec.js
> +        await TestHelpers.waitAndTap(CONTINUE_BUTTON);
done in https://github.com/MetaMask/metamask-mobile/pull/9129/commits/f9120b2fb1fc9a3964e55fc8b30521ee03a18cde

2024-05-06 22:08 UTC, bergeron commented on e2e/specs/settings/fiat-on-testnets.spec.js
> +import { TOTAL_BALANCE_TEXT } from '../../../wdio/screen-objects/testIDs/Components/Tokens.testIds.js';
`TOTAL_BALANCE_TEXT` is an existing selector, I'm just importing it.  I could refactor the tokens page to use the better test patterns, but I'd prefer to keep this PR minimal.

2024-05-09 16:00 UTC, tommasini commented on app/components/Views/Settings/AdvancedSettings/FiatOnTestnetsFriction/FiatOnTestnetsFriction.tsx
> +        <Text style={styles.heading}>
cc: @brianacnguyen Do you know why this behaviour on the new Text component?

2024-05-09 16:04 UTC, tommasini commented on app/components/Views/Settings/AdvancedSettings/FiatOnTestnetsFriction/FiatOnTestnetsFriction.tsx
> +            {...generateTestId(
I believe generateTestId is no longer needed since we no longer use Appium only detox! I believe this could change to the testID property

2024-05-10 19:04 UTC, cortisiko reviewed
@bergeron left a couple of comments

2024-05-10 19:04 UTC, cortisiko commented on e2e/specs/settings/fiat-on-testnets.spec.js
> +        await TabBarComponent.tapSettings();
For some reason, the tests are failing on Android at this step. See bitrise run here: https://app.bitrise.io/build/81cf46a7-f8ab-4704-bad9-9baff4e50335 

For now, I recommend adding a timeout. `TestHelpers.delay(2500) `.

2024-05-14 20:27 UTC, bergeron commented on e2e/specs/settings/fiat-on-testnets.spec.js
> +        await TabBarComponent.tapSettings();
That seems to work.  I think it has to wait for the network switch toast to disappear before clicking the settings button.

2024-05-14 21:24 UTC, bergeron commented
The new e2e test is passing locally on android, so I'm not sure what's happening in bitrise

2024-05-16 21:49 UTC, Cal-L reviewed
Left some comments

2024-05-16 21:49 UTC, Cal-L commented on app/components/Views/Settings/AdvancedSettings/FiatOnTestnetsFriction/FiatOnTestnetsFriction.test.tsx
> +    const wrapper = render(
Can replace this with `renderWithProvider`, which includes the provider

2024-05-16 21:49 UTC, Cal-L commented on app/components/Views/Settings/AdvancedSettings/FiatOnTestnetsFriction/FiatOnTestnetsFriction.tsx
> +              navigation.navigate('Webview', {
Use constants from `Routes.ts`

2024-05-16 21:49 UTC, Cal-L commented on app/components/Views/Settings/AdvancedSettings/FiatOnTestnetsFriction/FiatOnTestnetsFriction.tsx
> +                screen: 'SimpleWebview',
Use constants from Routes.ts

2024-05-16 22:12 UTC, Cal-L approved these changes
LGTM!

2024-05-28 15:05 UTC, cortisiko approved these changes
From an E2E test perspective this looks good.

2024-05-28 15:08 UTC, merged