Add eth stake button
MetaMask/metamask-mobile pull request #9136
Opened 2024-04-04 10:51 UTC by ameliejyc

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-04 14:19 UTC, ameliejyc commented
I have verified that MetaMetrics `trackEvent` is called with the expected params, however is there anything else I need to do to get this new event updated in Segment? I don't see a Segment mobile tracking plan.

2024-04-05 18:03 UTC, georgewrmarshall approved these changes, later dismissed
LGTM! I have once question for DS designers but I imagine it will be a change on the design side

2024-04-05 19:19 UTC, brianacnguyen commented on app/component-library/components/Icons/Icon/Icon.assets.ts
> +  [IconName.Stake]: Stake,
this is not needed. you can use the `plant` icon instead

2024-04-05 19:20 UTC, brianacnguyen commented on app/components/UI/Tokens/index.tsx
> +      <TouchableOpacity
I think we should move towards the `Pressable` component instead of `TouchableOpacity` https://reactnative.dev/docs/pressable

2024-04-05 19:22 UTC, brianacnguyen requested changes
Looks good. Just 1 comment regarding not needing the `Stake` Icon

2024-04-08 08:17 UTC, ameliejyc commented on app/components/UI/Tokens/index.tsx
> +      <TouchableOpacity
I will change this, thanks!

2024-04-08 08:18 UTC, ameliejyc commented on app/component-library/components/Icons/Icon/Icon.assets.ts
> +  [IconName.Stake]: Stake,
Great!

2024-04-08 16:53 UTC, NicolasMassart approved these changes
Tested and code approved.
Nice work!
https://github.com/MetaMask/metamask-mobile/assets/4677568/12cc3873-6b0f-41a6-b360-6e763558fa3a

2024-04-09 16:31 UTC, brianacnguyen approved these changes

2024-04-10 14:38 UTC, merged