feat: Add new privacy policy alert toast
MetaMask/metamask-mobile pull request #9204
Opened 2024-04-11 13:57 UTC by jonybur

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-05-01 09:04 UTC, hesterbruikman commented
@jonybur Same as for Extension, could you remove the Accept button here please? It's not required from a legal point of view and it might create the impression that it is

2024-05-06 17:41 UTC, georgewrmarshall reviewed
Code LGTM! Would be great to upload the most recent recording that removes the approve button and it looks like you may have some linting errors and need to sign the CLA @jonybur 🙏

2024-05-07 16:35 UTC, EtherWizard33 submitted a review, later dismissed

2024-05-07 16:35 UTC, EtherWizard33 commented on app/components/Nav/App/index.js
>  import { colors as importedColors } from '../../../styles/common';
just a nit: any reason the new line at line 52 is added?

2024-05-08 13:19 UTC, jonybur commented
I have read the CLA Document and I hereby sign the CLA

2024-05-08 15:12 UTC, EtherWizard33 commented on app/reducers/legalNotices/index.ts
> +
nit: maybe the 'any' could be typed.

It seems in a few reducers they do it inline like  action: { type: string, payload: number}

Or I have also seen an example in the accounts reducer extending the redux Action type:

export interface iAccountActions extends Action {
  reloadAccounts: boolean;
}

2024-05-08 15:20 UTC, EtherWizard33 reviewed
looks like there is a snapshot test failing, this should create an updated snapshot:

npx jest -u ./app/components/Views/Wallet/index.test.tsx;

2024-05-09 13:31 UTC, EtherWizard33 commented on app/reducers/legalNotices/index.ts
> +export interface iAccountActions extends Action {
NIT: this is just a nit so feel free to use it or not, I noticed it's not used very much currently in the app anyway.
But if it's used it should probably be named LegalNoticesActions, here is an example, the action typing stuff is between line 18 and 28 of this example, the rest I provide just for a bit of context around the example:

https://chat.consensys.io/chat/OnL8kM75dDqArR335YFxW

2024-05-09 15:46 UTC, georgewrmarshall submitted a review, later dismissed
Component library changes LGTM! Approving to unblock. Please still get an approval from @EtherWizard33 🙏

2024-05-09 20:00 UTC, EtherWizard33 commented
> Component library changes LGTM! Approving to unblock. Please still get an approval from @EtherWizard33 🙏

Also needed approval from mobile platform code owners first, EtherWizard33 being a newcomer probably shouldn't be really stamping stuff yet.

2024-05-09 20:06 UTC, EtherWizard33 commented on app/components/Views/Wallet/index.tsx
> +    shouldShowNewPrivacyToast,
is the toast supposed to be rendered only once on first rendering, and if it would render only once, would it affect how it's expected to work?

Without dependencies i logged one showToast, and with I logged 3-4 as can be see in attached images 


| With deps       | Without deps        |
|--------------|--------------|
| <img width="350" alt="Screenshot 2024-04-18 at 3 56 43 PM" src="https://github.com/MetaMask/metamask-mobile/assets/165834542/46b12768-8bba-4a2c-8a64-a0658d0951c8"> |<img width="350" alt="Screenshot 2024-04-18 at 3 56 43 PM" src="https://github.com/MetaMask/metamask-mobile/assets/165834542/8c2483e5-7c3b-409b-9dbd-12a106ca5a78"> |

2024-05-10 03:01 UTC, darkwing submitted a review, later dismissed

2024-05-10 13:14 UTC, EtherWizard33 commented on locales/languages/en.json
> +    "fine_print_1": "We’ll let you know if we decide to use this data for other purposes. You can review our",
Are the translations displaying for you, currently I see this:


| en-US       | en-CA        |
|--------------|--------------|
| <img width="350" alt="Screenshot 2024-04-18 at 3 56 43 PM" src="https://github.com/MetaMask/metamask-mobile/assets/165834542/3ec3a835-3ff9-4e85-82ab-21366127fe98"> |<img width="350" alt="Screenshot 2024-04-18 at 3 56 43 PM" src="https://github.com/MetaMask/metamask-mobile/assets/165834542/5158bbcc-e06c-4808-a03f-bb25d1a927e5"> |

2024-05-10 15:41 UTC, tommasini commented on app/components/Views/Wallet/index.tsx
> +const mapStateToProps = (state: any) => ({
Instead of using this pattern of mapStateToProps and mapDispatchToProps, since we have a functional component what do you think about using the useSelector (That it's already used ) and the useDispatch hooks instead?

2024-05-10 16:11 UTC, jonybur commented on app/components/Views/Wallet/index.tsx
> +const mapStateToProps = (state: any) => ({
Hey @tommasini , this will involve a re-do of large parts of the PR. I would rather not do this, but we can absolutely apply those refactors after merging this PR, given that this must go in ASAP.

2024-05-10 16:35 UTC, jonybur commented on locales/languages/en.json
> +    "fine_print_1": "We’ll let you know if we decide to use this data for other purposes. You can review our",
Fixed!

2024-05-10 16:48 UTC, EtherWizard33 approved these changes, later dismissed
ran it on android and ios and it showed and was hidden as described in the pr description

approving assuming passed CI checks and considering there is an ongoing review from the platform team as well

2024-05-14 16:28 UTC, georgewrmarshall approved these changes, later dismissed

2024-05-14 16:39 UTC, brianacnguyen commented on app/component-library/components/Toast/Toast.types.ts
> +  closeButtonOptions?: ToastCloseButtonOptions;
can you update this to use ButtonProps instead to avoid more unnecessary duplicates

2024-05-14 16:41 UTC, brianacnguyen commented on app/component-library/components/Toast/Toast.types.ts
> +  disableTimeout: boolean;
can you update this with is- or has- 
https://github.com/MetaMask/contributor-docs/blob/main/docs/javascript.md

2024-05-14 16:42 UTC, brianacnguyen requested changes
Requesting a few changes with the DS changes to follow best practices

2024-05-14 19:01 UTC, brianacnguyen approved these changes

2024-05-15 00:31 UTC, tommasini approved these changes
Approving this so it can go in, in 7.23, but I would say that this PR should change:

On wallet/index.tsx
`connect`, `mapStateToProps` and `mapDispatchToProps` for the hooks (useSelector and useDispatch) of redux since it's a functional component and it was already following that pattern

It would be a nice to have the slices of redux tool kit follwing the slice pattern already implemented instead of creating a new action and reducer


BREAKING:

This PR absolutely needs the translations to be ready to cherry pick into 7.23.0

2024-05-15 10:47 UTC, EtherWizard33 approved these changes

2024-05-15 15:58 UTC, merged