Fix/add migration for linea goerli
MetaMask/metamask-mobile pull request #9224
Opened 2024-04-12 15:33 UTC by sahar-fehri

## **Description**

PR to migrate users to linea Sepolia if they are on linea-goerli. And remove linea goerli from default network list because its deprecated.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Build on main
2. Switch to linea-goerli
3. Build on this PR
4. You should be on linea goerli
5. You can add linea goerli  by clicking on the navigation button in the wallet and type in: chainlist.org. Connect your wallet and you can look for the network you want to add then click on "add to metamask" button.
6.You should see deprecation warning for linea goerli

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-12 17:07 UTC, NicolasMassart approved these changes, later dismissed
Looks good to me.

2024-04-12 21:34 UTC, tommasini requested changes
Nit: at migration level doesn't need async state anymore if there is not async operations

2024-04-12 21:34 UTC, tommasini commented on app/store/migrations/038.ts
> +  const state = await stateAsync;
This is not needed anymore, you can add the migration synchronously the coming state is no longer a promise

2024-04-15 18:42 UTC, tommasini approved these changes

2024-04-15 18:42 UTC, merged