chore: add new notifications badge
MetaMask/metamask-mobile pull request #9238
Opened 2024-04-15 13:37 UTC by Jonathansoufer

## **Description**

This PR implements a new badge element to be used within Notifications feature. 

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-16 16:19 UTC, brianacnguyen commented
@Jonathansoufer can you attach the story screenshots/videos?

2024-04-16 16:20 UTC, brianacnguyen commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.styles.ts
> +        borderRadius: 9,
can you attach the figma link to the badge? want to double check on the styles

2024-04-16 16:21 UTC, brianacnguyen commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.tsx
> +import { useComponentSize, useStyles } from '../../../../../hooks';
can you organize this into different imports like other files?

2024-04-16 16:22 UTC, brianacnguyen commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.tsx
> +const BadgeNotifications = ({ style, iconName }: BadgeNotificationsProps) => {
will this ever be rendered without an icon?

2024-04-16 16:23 UTC, brianacnguyen requested changes, later dismissed
Component looks good. Minor changes requested. Thank you for following the standards!

2024-04-16 16:24 UTC, Jonathansoufer commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.styles.ts
> +        borderRadius: 9,
Here it goes the [Figma](https://www.figma.com/file/XcAVSI5z4myb1DtlbIHw7U/ProfileID-(UUID)-mobile?type=design&node-id=911-25369&mode=design&t=sgMlhWtC32iyzhSk-0) with all the artefacts. This PR is just a better organization of [this one](https://github.com/MetaMask/metamask-mobile/pull/8961) requested by @Cal-L in order to make review easier.

2024-04-16 16:55 UTC, Jonathansoufer commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.tsx
> +const BadgeNotifications = ({ style, iconName }: BadgeNotificationsProps) => {
Fixed.

2024-04-16 16:56 UTC, Jonathansoufer commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.tsx
> +import { useComponentSize, useStyles } from '../../../../../hooks';
Just used now the same approach of the other badges.

2024-04-16 19:58 UTC, Cal-L reviewed
Left some comments

2024-04-16 19:58 UTC, Cal-L commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/README.md
> +# [BadgeNotifications](https://metamask-consensys.notion.site/Badge-Notifications-94a679c50cb446f4844dc624b4f74946)
This is currently opening BadgeNetwork, point to BadgeNotifications

2024-04-16 19:58 UTC, Cal-L commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/README.md
> +### `name`
The `name` prop doesn't seem to exist and is not being used on the `BadgeNotifications` component

2024-04-16 19:58 UTC, Cal-L commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.types.ts
> +  name?: string;
This isn't used

2024-04-16 19:58 UTC, Cal-L commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.types.ts
> +   * Optional prop to control the image source of the notifications
The component uses `Icon` under the hood - `IconName` type is an enum, and isn't an `ImageSourcePropType`. We can simplify the description to be `Icon to use`.

2024-04-16 19:58 UTC, Cal-L commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/README.md
> +| [iconNamePropType](https://reactnative.dev/docs/image#imagesource) | Yes                                                     |     |
```suggestion
| [IconName](./Icon.types.ts#L53)   | Yes                                                     |     |
```

2024-04-16 19:58 UTC, Cal-L commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/README.md
> +Optional prop to control the icon source name of the notifications from local source.
Simplify to `Icon to use`

2024-04-16 19:59 UTC, Cal-L reviewed
Apply `Run E2E Smoke` label to run e2e smoke tests after all comments are resolved

2024-04-17 21:24 UTC, Jonathansoufer commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/README.md
> +# [BadgeNotifications](https://metamask-consensys.notion.site/Badge-Notifications-94a679c50cb446f4844dc624b4f74946)
There isn't a BadgeNotifications notion site yet. All I have it a Figma to base my work on. Asked Praise Fabilola to create one, but will remove this link for now so that it not become a blocker.

2024-04-17 21:26 UTC, Jonathansoufer commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/README.md
> +### `name`
Fixed.

2024-04-17 21:27 UTC, Jonathansoufer commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.types.ts
> +  name?: string;
Fixed.

2024-04-17 21:28 UTC, Jonathansoufer commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.types.ts
> +   * Optional prop to control the image source of the notifications
addressed!

2024-04-17 21:34 UTC, Jonathansoufer commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/README.md
> +| [iconNamePropType](https://reactnative.dev/docs/image#imagesource) | Yes                                                     |     |
Fixed.

2024-04-17 21:35 UTC, Jonathansoufer commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/README.md
> +Optional prop to control the icon source name of the notifications from local source.
fixed.

2024-04-18 06:01 UTC, Cal-L commented
E2E failure not related to this branch

2024-04-18 06:02 UTC, Cal-L approved these changes
LGTM

2024-04-18 09:19 UTC, tommasini approved these changes
LGTM

2024-04-18 13:55 UTC, merged