Remove xmldom 0.6.0 for xmldom@^0.x target
MetaMask/metamask-mobile pull request #9264
Opened 2024-04-16 14:00 UTC by NicolasMassart

## **Description**

Remove xmldom 0.6.0 for xmldom@^0.x target

## **Related issues**

fixes MetaMask/metamask-mobile/security/dependabot/110

## **Manual testing steps**

1. `yarn setup` should succeed
2. Smoke e2e should succeed as xmldom is used by Appium

## **Screenshots/Recordings**

<img width="266" alt="image" src="https://github.com/MetaMask/metamask-mobile/assets/4677568/ee41e0f8-0bc8-42c9-aec3-b39520f5a3e1">

### **Before**

NA

### **After**

NA

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-18 02:17 UTC, legobeat submitted a review, later dismissed

2024-04-30 18:18 UTC, sethkfman submitted a review, later dismissed
LGTM

2024-05-01 01:37 UTC, legobeat requested changes
Looks like a merge-conflict resolution in `resolutions` went sideways - LGTM otherwise.

2024-05-01 01:37 UTC, legobeat commented on package.json
> +    "apg-js": "4.2.0",
```suggestion
```
these shouldn't be reintroduced here.

2024-05-01 17:58 UTC, legobeat approved these changes

2024-05-02 01:01 UTC, merged