feat: Update SignatureController v6.1.3
MetaMask/metamask-mobile pull request #9305
Opened 2024-04-18 01:59 UTC by MarioAslau

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-18 17:22 UTC, tommasini requested changes

2024-04-18 17:22 UTC, tommasini commented on app/core/Engine.ts
> +      // @ts-expect-error TODO: Resolve/patch mismatch between base-controller versions. Before: never, never. Now: string, string, which expects 3rd and 4th args to be informed for restrictedControl
Nice work! Could we do a more human readable comment? For example when this ts-expect-error can be removed and how?

It's when we update LoggingController to v^2?
Also I don't understand why ts-expect-error it's needed on this update

Probably because it needs ^1.0.4 logging controller version as peer dependency?
https://github.com/MetaMask/core/blob/%40metamask/signature-controller%406.1.3/packages/signature-controller/package.json

It also needs Approval controller v^4 peer dependency, I believe this is not a blocker since it's not a breaking change on the changelog

2024-04-18 18:34 UTC, MarioAslau commented on app/core/Engine.ts
> +      // @ts-expect-error TODO: Resolve/patch mismatch between base-controller versions. Before: never, never. Now: string, string, which expects 3rd and 4th args to be informed for restrictedControl
Hey Tomas, this comment was copied from the original location of the code, I moved it all into a variable. We could refine the message if needed

2024-04-30 16:23 UTC, tommasini approved these changes, later dismissed

2024-05-03 20:24 UTC, frankvonhoven approved these changes, later dismissed
👍

2024-05-07 17:30 UTC, tommasini approved these changes, later dismissed

2024-05-08 09:53 UTC, tommasini approved these changes

2024-05-08 10:47 UTC, merged