Feature/1634 add account and network on card 1
MetaMask/metamask-mobile pull request #9321
Opened 2024-04-18 20:00 UTC by EtherWizard33

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

<img width="449" alt="Screenshot 2024-04-18 at 3 56 43 PM" src="https://github.com/MetaMask/metamask-mobile/assets/165834542/5fef7b7c-3430-4b5d-8185-4e7413946e4e">

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-18 20:25 UTC, darkwing commented on app/components/UI/Tabs/TabThumbnail/index.js
> +  tab: PropTypes.object,
Can we add the JSDoc comments back down here?

2024-04-18 20:25 UTC, darkwing commented on app/components/UI/Tabs/TabThumbnail/index.js
> +  tab: PropTypes.object,
Also, should any of these be `isRequired`?

2024-04-19 18:34 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/index.js
> +  tab: PropTypes.object,
yes, definitely, to both questions, will take care of it, thanks for pointing it out

2024-04-20 21:05 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/index.js
> +  tab: PropTypes.object,
added the docs and marked all props as required, 
please let me know if it is as expected

2024-04-26 22:05 UTC, darkwing requested changes

2024-04-26 22:05 UTC, darkwing commented on app/components/UI/Tabs/TabThumbnail/index.js
> +            {selectedAccount?.name ?? 'undefined account'} - {networkName}
We need to localize this.

2024-04-26 22:05 UTC, darkwing commented on app/components/UI/Tabs/TabThumbnail/useNetworkInfo.js
> +    [providerConfig],
Are there really 3 possibilities?  Is there another helper for this?  Seems like something we'd use a lot.

2024-04-29 12:10 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/useNetworkInfo.js
> +    [providerConfig],
Yes you are right, found a util and used it

2024-04-29 20:46 UTC, frankvonhoven commented on app/components/UI/Tabs/TabThumbnail/index.js
> +            {selectedAccount?.name ?? 'undefined account'} - {networkName}
Add string in `en.json` to relevant container name and then `strings('your_container.undefined_account')`

2024-05-01 17:39 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/index.js
> +            accessibilityLabel="Close tab"
I have now added the change to make use of the new localizations
will keep an eye on the other pr, 9248, which is expected to add other languages
will mark this as resolve since the localization code in this PR is now present

2024-05-01 17:40 UTC, EtherWizard33 commented
> Can we concert the JavaScript files to typescript files? Also the component file on the new pattern is imported and exported by the index.ts file
> 
> Se usually give the name something like this: componentName.tsx

this is now done

2024-05-02 18:17 UTC, darkwing requested changes
Looking awesome, just a nit!

2024-05-02 18:17 UTC, darkwing commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.tsx
> +            {!isHomepage ? (
We should use the positive case first:

```
isHomepage ? /* ... */ : /* ... */
```

2024-05-02 18:50 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.tsx
> +            {!isHomepage ? (
agreed!

2024-05-06 12:46 UTC, EtherWizard33 commented
> Can we concert the JavaScript files to typescript files? Also the component file on the new pattern is imported and exported by the index.ts file
> 
> Se usually give the name something like this: componentName.tsx

this is done, ready for review

2024-05-06 13:23 UTC, EtherWizard33 commented
> Looking awesome, just a nit!

fixed

2024-05-07 16:14 UTC, darkwing approved these changes, later dismissed

2024-05-07 20:39 UTC, tommasini requested changes
LGTM! Just left some comments to be addressed and we are good to go!

2024-05-07 20:39 UTC, tommasini commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.styles.ts
> +    networkBadge: {
If this isn't needed we can remove it I believe!

2024-05-07 20:39 UTC, tommasini commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.tsx
> +const METAMASK_FOX = require('../../../../images/fox.png');
I believe we can use import instead of require here
```suggestion
import METAMASK_FOX from '../../../../images/fox.png';
```

2024-05-07 20:39 UTC, tommasini commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.tsx
> +/* eslint-disable import/no-commonjs, @typescript-eslint/no-var-requires, @typescript-eslint/no-require-imports */
```suggestion

```

2024-05-07 20:39 UTC, tommasini commented on app/components/UI/Tabs/TabThumbnail/useNetworkInfo.js
> +import { useMemo } from 'react';
All new files should be in typescript

2024-05-07 20:39 UTC, tommasini commented on app/components/UI/Tabs/TabThumbnail/useSelectedAccount.js
> +import { useMemo } from 'react';
All new files should be in typescript

2024-05-08 14:07 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.tsx
> +const METAMASK_FOX = require('../../../../images/fox.png');
thanks, this is now fixed, marking as resolved

2024-05-08 14:07 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.tsx
> +/* eslint-disable import/no-commonjs, @typescript-eslint/no-var-requires, @typescript-eslint/no-require-imports */
thanks, this is now fixed, marking as resolved

2024-05-08 14:14 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/useSelectedAccount.js
> +import { useMemo } from 'react';
this is now fixed, marking as resolved

2024-05-08 15:31 UTC, tommasini commented on app/components/UI/Tabs/TabThumbnail/useSelectedAccount.ts
> +import { useMemo } from 'react';
Can we move this hook to the hooks folder?

And actually this is amazing because it can replace this useMemo on wallet/index: https://github.com/MetaMask/metamask-mobile/blob/d4e8528db2b329b7e7616565f24a259cc212caaa/app/components/Views/Wallet/index.tsx#L151

2024-05-08 15:34 UTC, tommasini commented on app/components/UI/Tabs/TabThumbnail/useNetworkInfo.ts
> +import { useMemo } from 'react';
This is also amazing hook!

Can we move it to the hooks folder?
Also can you replace where the network name is used? (This is a screenshot of all the functional components that have duplicated code)
![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/dbe464b3-8f82-4ba4-82bd-69c11455b3f5)

Can we also do the same for the networkImage source?
![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/dafc7cff-68f2-4802-b33a-c31c0aae1945)

2024-05-08 16:29 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/useNetworkInfo.ts
> +import { useMemo } from 'react';
after discussion, me and Tomas have agreed to address the refactoring of other components in a later PR, part of the options will include extracting two custom hooks one for name and one for image, or using selectors to achieve this, since we will address in a later PR, marking this as resolved for now

2024-05-08 16:29 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/useSelectedAccount.ts
> +import { useMemo } from 'react';
after discussion, me and Tomas have agreed to address the refactoring of other components in a later PR, part of the options will include extracting two custom hooks one for name and one for image, or using selectors to achieve this, since we will address in a later PR, marking this as resolved for now

2024-05-08 16:33 UTC, tommasini commented on app/components/UI/Tabs/TabThumbnail/useSelectedAccount.ts
> +import { useMemo } from 'react';
For history, this could also be a selector instead, that would be better I would say

2024-05-08 16:33 UTC, tommasini commented on app/components/UI/Tabs/TabThumbnail/useNetworkInfo.ts
> +import { useMemo } from 'react';
For history, this could also be a selector instead, that would be better I would say

2024-05-08 16:35 UTC, tommasini commented on app/components/UI/Tabs/TabThumbnail/types.ts
> +export interface TabThumbnailProps {
NIT: The name of this file could follow the pattern as well "TabThumbnail.types.ts"

2024-05-08 16:36 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/useNetworkInfo.ts
> +import { useMemo } from 'react';
the refactoring in this issue or one around this one
https://github.com/MetaMask/mobile-planning/issues/1633

2024-05-08 16:36 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/useSelectedAccount.ts
> +import { useMemo } from 'react';
the refactoring in this issue or one around this one
https://github.com/MetaMask/mobile-planning/issues/1633

2024-05-08 16:44 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/types.ts
> +export interface TabThumbnailProps {
done, thanks, marking as resolved

2024-05-08 16:50 UTC, tommasini approved these changes, later dismissed
LGTM, since we are refactoring the usage of the hooks on a next PR

Let's wait for the E2E test result, if it is green we can merge it!

2024-05-08 17:24 UTC, frankvonhoven commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.styles.ts
> +      alignSelf: 'flex-start',
Could you remove all of these `flex-start`s and see if the UI is affected. `flex-start` is typically the default for these style props ;)

2024-05-08 17:26 UTC, frankvonhoven commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.styles.ts
> +const height = Dimensions.get('window').height / (Device.isIphone5S() ? 4 : 5);
Are we supporting iPhone 5?

2024-05-08 17:27 UTC, frankvonhoven commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.styles.ts
> +      paddingHorizontal: 8,
You can just use `padding: 8`

2024-05-08 17:28 UTC, frankvonhoven commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.styles.ts
> +      overflow: 'hidden',
Are things running on to the next line?

2024-05-08 17:28 UTC, frankvonhoven commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.styles.ts
> +      marginTop: -7,
should this be `marginBottom`?

2024-05-08 17:30 UTC, frankvonhoven commented on app/components/UI/Tabs/TabThumbnail/__snapshots__/TabThumbnail.test.tsx.snap
> +        accessibilityLabel="Close tab"
Should be i18n

2024-05-08 17:33 UTC, frankvonhoven commented on app/components/UI/Tabs/TabThumbnail/useSelectedAccount.ts
> +    () => accounts.find((account: Account) => account.isSelected) ?? undefined,
The default if `accounts.find()` returns `undefined` is `undefined`? Why the coalescing if no default?

2024-05-08 17:44 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.styles.ts
> +      overflow: 'hidden',
I believe it's necessary for ellipsising to work as expected

2024-05-08 19:00 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.styles.ts
> +      paddingHorizontal: 8,
done

2024-05-08 19:03 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.styles.ts
> +      marginTop: -7,
done

2024-05-08 19:07 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.styles.ts
> +const height = Dimensions.get('window').height / (Device.isIphone5S() ? 4 : 5);
I checked with Cal, under the hood it checks the device with, so any device the size of an iphone 5s would have smaller tabs than the rest.

2024-05-08 19:08 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/TabThumbnail.styles.ts
> +      alignSelf: 'flex-start',
done

2024-05-08 19:10 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/useSelectedAccount.ts
> +    () => accounts.find((account: Account) => account.isSelected) ?? undefined,
nice 'find' thanks

2024-05-08 19:27 UTC, darkwing approved these changes, later dismissed

2024-05-08 20:36 UTC, frankvonhoven approved these changes

2024-05-08 21:02 UTC, tommasini approved these changes
The hooks will be refactored to createSelectors on this [issue](https://github.com/MetaMask/mobile-planning/issues/1633)

LGTM!

2024-05-08 22:30 UTC, merged

2024-05-15 12:01 UTC, EtherWizard33 commented on app/components/UI/Tabs/TabThumbnail/useNetworkInfo.ts
> +import { useMemo } from 'react';
in the previous message above, issue 1633 was suggested to include this refactor, we could also include it as part of a smaller issue like this [style change for the footer](https://github.com/MetaMask/mobile-planning/issues/1637)