Feat/notifications screen UI
MetaMask/metamask-mobile pull request #9346
Opened 2024-04-22 15:46 UTC by Jonathansoufer

## **Description**

This PR implements a List screen for Notifications

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-29 14:12 UTC, tommasini commented on app/components/Nav/Main/MainNavigator.js
> +    <Stack.Screen name="NotificationsView" component={NotificationsModeView} />
Can we use the constant instead?
```suggestion
    <Stack.Screen name={Routes.NOTIFICATIONS.VIEW} component={NotificationsModeView} />
```

2024-04-29 14:17 UTC, tommasini commented on locales/languages/en.json
> +    "search_information_not_saved": "Your search information will not be saved.",
Can we submit to main these translations on a different PR? To make sure that the translations are requested before the next release cut?

2024-04-29 14:18 UTC, tommasini reviewed
This PR looks amazing, just left some comment, and if you firstly could submit a new PR for translations and then address the others it would be awesome.
I'm requesting this because translations need some time to be handled by other team and between reviews and changes we have a bigger change that they are handled before the next release cut

2024-04-29 18:57 UTC, Jonathansoufer commented on locales/languages/en.json
> +    "search_information_not_saved": "Your search information will not be saved.",
All changes NOT related to notifications are probably some `linting` since I didn't touched anything but this. Cherry picking the translation just for that wouldn't be necessary in my humble opinion, don't you agree?

2024-05-02 02:49 UTC, legobeat commented on app/components/UI/Notification/Empty/__snapshots__/index.test.tsx.snap
> +    Object {
As of the upgrade to Jest v29, snapshots will need to be regenerated (or, this worked fine for me: `rg -l -g '*.snap' 'Object\s*\{|Array\s*\[' | xargs sed -i -e 's#Object\s*{#{#g' -e 's#Array\s*\[#[#g'`

2024-05-06 12:36 UTC, NicolasMassart requested changes
Nice overall work!
I added some suggestions on tests naming and implementation to match guidelines and good practices that may have CI stability and  security implications.

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/UI/Notification/Row/Content.tsx
> +      : [];
You could safeguard this part by first testing title is defined and then rely on this without the redundant optional chaining.
Returning directly in case of undefined or null title.
Also, the ternary here is not the most readable structure. Try a classic if/else, it sometimes makes it more readable with the exact same efficiency.

Finally, be careful, your regex are vulnerable to redos attack (as indficated by Sonar). This may be changed to more simple regex without backtracking or direct substring manipulation.

Example suggestion for all these changes:
```suggestion
if (!title) return <Text color={TextColor.Alternative} variant={TextVariant.BodySM}>{title}</Text>;

    const lowerTitle = title.toLowerCase();
    let parts;

    if (lowerTitle.includes('sent')) {
      parts = title.split(/(\bto\b)/g);
    } else if (lowerTitle.includes('received')) {
      parts = title.split(/(\bfrom\b)/g);
    } else {
      parts = [];
    }
```

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/UI/Notification/Row/Actions.tsx
> +    }
Remove this dead code and create an issue for adding the deeplink handling if is has to be provided in another PR.

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/UI/Notification/Row/Actions.tsx
> +// import AppConstants from '../../../../core/AppConstants';
See Comment on lines +35 to +41

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/UI/Notification/Row/Actions.test.tsx
> +  it('renders correctly', () => {
Try to avoid this test name as it's not actually testing rendering is correct but only that it hasn't changed since last time.
```suggestion
  it('matches snapshot', () => {
```

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/UI/Notification/Row/Actions.test.tsx
> +  it('renders correctly with LINK only', () => {
```suggestion
  it('matches snapshot with LINK only', () => {
```

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/UI/Notification/Row/Actions.test.tsx
> +  it('Calls Linking.openURL when link CTA is clicked', async () => {
```suggestion
  it('calls Linking.openURL when link CTA is clicked', async () => {
```

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/UI/Notification/Row/Actions.test.tsx
> +  it('renders link title correctly', () => {
```suggestion
  it('renders link title', () => {
```

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/UI/Notification/List/index.tsx
> +      //TODO: details will be implemented on a separete PR
This should be a PR comment instead of a code comment

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/UI/Notification/Empty/index.test.tsx
> +  it('should render correctly', () => {
```suggestion
  it('matches snapshot', () => {
```

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/UI/Notification/Row/Content.test.tsx
> +  it('renders correctly', () => {
```suggestion
  it('matches snapshot', () => {
```

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/UI/Notification/Row/Icon.test.tsx
> +  it('renders correctly with Wallet type', () => {
```suggestion
  it('matches snapshot with Wallet type', () => {
```

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/UI/Notification/Row/Icon.test.tsx
> +  it('renders correctly with Announcement type', () => {
```suggestion
  it('matches snapshot with Announcement type', () => {
```

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/UI/Notification/Row/Root.test.tsx
> +  it('renders correctly', () => {
```suggestion
  it('matches snapshot', () => {
```

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/Views/Notifications/index.test.tsx
> +  it('should render correctly', () => {
```suggestion
  it('matches snapshot', () => {
```

2024-05-06 12:36 UTC, NicolasMassart commented on app/components/Views/Notifications/index.test.tsx
> +  it('should render correctly with no notifications', () => {
```suggestion
  it('matches snapshot without notifications', () => {
```

2024-05-06 14:15 UTC, Jonathansoufer commented on app/components/UI/Notification/Row/Icon.tsx
> +              'https://token.api.cx.metamask.io/assets/nativeCurrencyLogos/ethereum.svg',
Fixed.

2024-05-06 14:17 UTC, Jonathansoufer commented on app/components/UI/Notification/Row/Actions.tsx
> +    }
Fixed.

2024-05-06 14:18 UTC, Jonathansoufer commented on app/components/UI/Notification/Row/Actions.tsx
> +// import AppConstants from '../../../../core/AppConstants';
Fixed.

2024-05-06 14:46 UTC, Jonathansoufer commented on app/components/UI/Notification/Row/Content.tsx
> +      : [];
Good approach, I implemented a mix of it.

2024-05-06 14:46 UTC, Jonathansoufer commented on app/components/UI/Notification/Row/Icon.test.tsx
> +    imageUrl:
Fixed.

2024-05-07 16:45 UTC, NicolasMassart submitted a review, later dismissed

2024-05-07 16:45 UTC, NicolasMassart commented on app/components/UI/Notification/Row/Icon.tsx
> +    if (notificationType.toLowerCase().includes('erc721' || 'erc1155')) {
As indicated by Sonar, this can't work: in JS, the || operator always return the first true item. And because items here are non empty strings, they are always considered as true. So the first one 'erc721' is always returned and the second one 'erc1155' is never considered in the includes. One way to fix that would be to match against `some` on an array (at least one element in the array passes) of notification types like the following:
```suggestion
    const types = ['erc721', 'erc1155'];
    if (types.some(type => notificationType.toLowerCase().includes(type))) {
```
This is not the only way of course. Feel free to adjust.

2024-05-07 21:17 UTC, Jonathansoufer commented on app/components/UI/Notification/Row/Icon.tsx
> +    if (notificationType.toLowerCase().includes('erc721' || 'erc1155')) {
Good catch. Fixed.

2024-05-07 21:22 UTC, Jonathansoufer commented on app/core/Analytics/MetaMetrics.events.ts
> +  ),
These are used to track which tab the user are when selecting notifications list to see, but I moved them out of legacy to the new events list.

2024-05-07 22:30 UTC, Cal-L commented
Regarding PR description

- I can see in current prod that the notification button is behind a feature flag. Does this mean that users shouldn't be able to interact with the changes once it's merged?
- Can you attach a Figma link (useful for reviewers to have a point of reference)?
- Usually a good way to split the description is by sectioning out by the screen/components. Ex:
  - Turn on notifications page -> new page + explanation of functionality
  - Notifications toggle page -> new page + explanation of functionality
      - How each toggle affects the behavior of the app based on toggle state
  - Notifications list page -> new page + explanation of functionality
      - All -> shows all notification types - What are all of the possible notification types?
      - Wallet -> shows wallet based notifications -> What are all of the possible notification types here?
      - Announcements -> shows announcement notifications -> What are all of the possible notification types here?

2024-05-07 22:31 UTC, Cal-L requested changes
Turn on notifications page's Learn more link needs a space to the left of itself

2024-05-07 22:32 UTC, Cal-L requested changes
Turn on notifications page's Learn more link needs a space to the left of itself

2024-05-07 22:33 UTC, Cal-L reviewed
The Notifications toggle page should probably have an X on the top right since it isn't mean to go back. The dismiss behavior should be a slide down (current slides diagonally)

2024-05-07 22:33 UTC, Cal-L requested changes
The Notifications toggle page should probably have an X on the top right since it isn't mean to go back. The dismiss behavior should be a slide down (current slides diagonally)

2024-05-07 22:34 UTC, Cal-L requested changes
Are the sub toggles from the Notifications page functional yet and if so, can we provide videos/description on app behavior when those toggles are on/off

2024-05-07 22:34 UTC, Cal-L requested changes
The Allow notifications toggle should remain off until a user taps Yes (currently, it slides right but back to the left)

2024-05-07 22:35 UTC, Cal-L requested changes
The Notifications list page seems to also have extra padding below the header or is that by design?

2024-05-07 22:35 UTC, Cal-L requested changes
The row items on the notifications list on the Wallet tab seems misaligned vertically. For example, the icon and badge floats more towards the bottom whereas the middle content floats towards the top. Should this all be center aligned? More of a design comment: It'll scale better if we align the icon+badge towards the top with a bit of top padding so that it appears center aligned with wallet notifications. Applying that same approach to other notification types such as announcements, it will balance the row items out. After that, the height of each announcement will only be determined by the body content, which the icon+badge remains fixed against the top.

2024-05-07 22:35 UTC, Cal-L requested changes
Unless by design, the trash icon should either be center aligned vertically or aligned against the top, similar to the icon+badge

2024-05-07 22:35 UTC, Cal-L requested changes
Is the settings icon on the Notifications list page hooked up or is just a placeholder for now?

2024-05-07 23:23 UTC, Jonathansoufer commented
> Is the settings icon on the Notifications list page hooked up or is just a placeholder for now?

Settings was implemented [here](https://github.com/MetaMask/metamask-mobile/pull/9258), and

2024-05-07 23:24 UTC, Jonathansoufer commented
> Turn on notifications page's Learn more link needs a space to the left of itself

This is fixed and merged on main already.

2024-05-07 23:25 UTC, Jonathansoufer commented
> Are the sub toggles from the Notifications page functional yet and if so, can we provide videos/description on app behavior when those toggles are on/off

Not. They'll be calling profile sync, but for now they're just being saved on local storage. This PR just implements UI

2024-05-08 10:07 UTC, Jonathansoufer commented
> The Notifications list page seems to also have extra padding below the header or is that by design?

Fixed.

2024-05-08 10:15 UTC, Jonathansoufer commented
> The row items on the notifications list on the Wallet tab seems misaligned vertically. For example, the icon and badge floats more towards the bottom whereas the middle content floats towards the top. Should this all be center aligned? More of a design comment: It'll scale better if we align the icon+badge towards the top with a bit of top padding so that it appears center aligned with wallet notifications. Applying that same approach to other notification types such as announcements, it will balance the row items out. After that, the height of each announcement will only be determined by the body content, which the icon+badge remains fixed against the top.

Good one! Fixed.

2024-05-08 10:16 UTC, Jonathansoufer commented
> Unless by design, the trash icon should either be center aligned vertically or aligned against the top, similar to the icon+badge

Fixed.

2024-05-08 10:17 UTC, Jonathansoufer commented
> The Allow notifications toggle should remain off until a user taps Yes (currently, it slides right but back to the left)

Fixed.

2024-05-15 04:45 UTC, Cal-L reviewed
Left some comments

2024-05-15 04:45 UTC, Cal-L commented on app/components/UI/Notification/Empty/index.tsx
> +  const styles = createStyles();
If nothing is dynamic in these styles, it doesn't need to be a function. Return `StyleSheet.create` directly instead

2024-05-15 04:45 UTC, Cal-L commented on app/components/UI/Notification/List/index.tsx
> +        // eslint-disable-next-line
Is there a reason why this is ignored by lint?

2024-05-15 04:45 UTC, Cal-L commented on app/components/UI/Notification/List/index.tsx
> +          <ActivityIndicator color={colors.icon.default} size="large" />
@brianacnguyen What color would you suggest for Activity the activity indicator?

2024-05-15 04:45 UTC, Cal-L commented on app/components/UI/Notification/List/styles.ts
> +      fontWeight: '500',
Is fontWeight needed? If so, the typography should be updated instead of fontWeight

2024-05-15 04:45 UTC, Cal-L commented on app/util/notifications/methods/index.ts
>      a.createdAt > b.createdAt ? -1 : b.createdAt > a.createdAt ? 1 : 0,
```suggestion
    b.createdAt - a.createdAt
```

2024-05-15 04:45 UTC, Cal-L commented on app/components/Views/Notifications/index.tsx
> +    <TouchableOpacity onPress={() => navigation.goBack()}>
I'd recommend navigating to the actual page rather than going back. This prevent the risk of double tapping (which can go back twice)

2024-05-15 04:45 UTC, Cal-L commented on app/components/Views/Notifications/index.tsx
> +      if (!isNotificationEnabled) navigation.navigate('WalletView');
What is the scenario where we'd want to automatically navigate to the wallet screen automatically?

2024-05-15 04:45 UTC, Cal-L commented on app/components/Views/Notifications/index.tsx
> +      allNotificationsSorted?.filter((notification) => {
Use for each instead since this isn't actually filtering

2024-05-15 04:45 UTC, Cal-L commented on app/components/Views/Notifications/index.tsx
> +          self.findIndex(
Instead of `findIndex`, It's probably more performant to keep track IDs in an object and return false if the ID already exists in the object

2024-05-15 04:45 UTC, Cal-L commented on app/components/UI/Notification/Row/Actions.tsx
> +      testID="notification-actions-button"
Move into a constants file

2024-05-15 09:24 UTC, Jonathansoufer commented on app/components/UI/Notification/Empty/index.tsx
> +  const styles = createStyles();
Ok. No a problem. Fixed.

2024-05-15 09:32 UTC, Jonathansoufer commented on app/components/UI/Notification/List/index.tsx
> +          <ActivityIndicator color={colors.icon.default} size="large" />
This shouldn't be a blocker, but in any case I changed to follow the pattern used in different place within the app which is `colors.primary.default`

2024-05-15 09:38 UTC, Jonathansoufer commented on app/components/UI/Notification/List/styles.ts
> +      fontWeight: '500',
again, I'm just following existing patterns available and used throughout the app, like [here](https://github.com/MetaMask/metamask-mobile/blob/dcdb03a95203e43d50dbe1dbb4d06226ba77dcd1/app/components/Views/Wallet/index.tsx#L77), [here](https://github.com/MetaMask/metamask-mobile/blob/476532d7f9c8d3699b4c591be744618e74f9136a/app/components/Views/RevealPrivateCredential/RevealPrivateCredential.tsx#L278), and [here](https://github.com/MetaMask/metamask-mobile/blob/f7466da745ad9db800abfe1a4e72639ba8e30598/app/components/Views/AddAsset/AddAsset.tsx#L96). Not an issue IMO.

2024-05-15 09:42 UTC, Jonathansoufer commented on app/components/Views/Notifications/index.tsx
> +      if (!isNotificationEnabled) navigation.navigate('WalletView');
The Scenario is when users tap on bell icon with isNotificationEnabled equals true, they will see a list of notifications but also on the top right corner an settings icon allowing them to go to the settings and disable notifications. If they disable notifications can tap back, we shouldn't show them the notifications list (which will be still available on navigation stack) but bypass it directly to Wallet main page.

2024-05-15 09:46 UTC, Jonathansoufer commented on app/components/Views/Notifications/index.tsx
> +    <TouchableOpacity onPress={() => navigation.goBack()}>
Fixed.

2024-05-15 09:53 UTC, Jonathansoufer commented on app/components/Views/Notifications/index.tsx
> +      allNotificationsSorted?.filter((notification) => {
Refactored.

2024-05-15 10:02 UTC, Jonathansoufer commented on app/components/Views/Notifications/index.tsx
> +          self.findIndex(
Same approach used [here](https://github.com/MetaMask/metamask-mobile/blob/39f43bce87b2f9c686732e62f6fd52ce6b900683/app/components/Views/TransactionsView/index.js#L75), [here](https://github.com/MetaMask/metamask-mobile/blob/39f43bce87b2f9c686732e62f6fd52ce6b900683/app/components/Views/Asset/index.js#L352) before.

2024-05-15 10:32 UTC, Jonathansoufer commented on app/util/notifications/methods/index.ts
>      a.createdAt > b.createdAt ? -1 : b.createdAt > a.createdAt ? 1 : 0,
This wouldn't work since createdAt is Date type, which would throw the "The left-hand side of an arithmetic operation must be of type 'any', 'number', 'bigint' or an enum type" problem. I approached slightly different now mixing your suggestion and handling Date.

2024-05-15 23:34 UTC, Cal-L commented on app/components/Views/Notifications/index.tsx
> +      if (!isNotificationEnabled) navigation.navigate('WalletView');
Is this the cause for the horizontal dismiss animation? Would we be able to have a direct dismiss by passing the condition to the screen that we're tapping back on instead?

2024-05-15 23:37 UTC, Cal-L commented on app/components/UI/Notification/List/styles.ts
> +      fontWeight: '500',
There are many areas in the app that contain less than ideal implementation. Those are areas that we need to refactor. Moving forward, let's remove the need to manage an additional piece of typography unless the actual styles provided in Figma isn't available.

2024-05-16 09:11 UTC, Jonathansoufer commented on app/components/Views/Notifications/index.tsx
> +      if (!isNotificationEnabled) navigation.navigate('WalletView');
Moved logic to Settings.

2024-05-16 21:30 UTC, Cal-L submitted a review, later dismissed
LGTM. Since this feature isn't live yet, it's hard to imagine what the final flow will look like. We can review those future questions in later PRs.

2024-05-20 18:04 UTC, Cal-L approved these changes
LGTM

2024-05-20 18:05 UTC, Cal-L commented
Approved from code perspective, will defer to @Jonathansoufer regarding QA

2024-05-21 09:03 UTC, merged