E2e json rpc coverage tool
MetaMask/metamask-mobile pull request #9356
Opened 2024-04-22 18:50 UTC by tmashuang

## **Description*

json rpc testing with open-rpc-coverage-tool. Method checking, confirmations,, rejects, response, errors, etc.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-22 18:57 UTC, tmashuang commented
I have read the CLA Document and I hereby sign the CLA

2024-04-24 18:25 UTC, shanejonas commented on e2e/specs/window-json-rpc-test/json-rpc-coverage.spec.js
> +                .then((res) => (el.innerHTML = JSON.stringify(res)))
```suggestion
                .then((res) => (el.innerHTML = JSON.stringify({result: res})))
```

2024-04-24 18:25 UTC, shanejonas commented on e2e/specs/window-json-rpc-test/json-rpc-coverage.spec.js
> +                .catch((err) => (el.innerHTML = JSON.stringify(err)));
```suggestion
                .catch((err) => (el.innerHTML = JSON.stringify({error: {code: e.code, message: e.message, data: e.data}})));
```

2024-04-24 18:32 UTC, shanejonas commented on e2e/specs/window-json-rpc-test/json-rpc-coverage.spec.js
> +          return result;
probably also need to JSON.parse here
```suggestion
          return JSON.parse(result);
```

2024-06-05 17:32 UTC, adonesky1 commented on e2e/pages/Settings/NetworksView.js
> +  get   networkContainer() {
```suggestion
  get  networkContainer() {
```

2024-06-05 20:39 UTC, shanejonas commented on index.js
> +LogBox.ignoreAllLogs();
need to revert this part

cc @cortisiko

2024-06-05 22:04 UTC, cortisiko commented
@shanejonas @adonesky1 I take it that we intend on including this as part of our test pipeline? If so, we should add the tests to the smoke pipeline. So that you know, our CI platform (bitrise) operates slightly differently than circleCI. 


Here is a visual representation of what our smoke pipeline looks like on bitrise: 
![Screen Shot 2024-06-05 at 4 35 45 PM](https://github.com/MetaMask/metamask-mobile/assets/12821081/dd44804f-82d6-4b55-bb99-6095667428a5)


Now here are the steps we can do for now just as a proof of concept and iterate in the future:

-  we can duplicate this [workflow](https://github.com/MetaMask/metamask-mobile/blob/main/bitrise.yml#L749%23L815) and call it a different name (ios_rpc_coverage_e2e). then change the test [script](https://github.com/MetaMask/metamask-mobile/blob/main/bitrise.yml#L815) to run your tests: 
- we then can create a separate workflow that we will add in the `run_smoke_e2e_ios_android_stage`
  basically, duplicate  https://github.com/MetaMask/metamask-mobile/blob/main/bitrise.yml#L471, call it whatever you want

- make sure the workflow you created above to the  `run_smoke_e2e_ios_android_stage` : https://github.com/MetaMask/metamask-mobile/blob/main/bitrise.yml#L118
- You can rinse and repeat for Android


Feel free to reach out if anything.

2024-06-05 23:33 UTC, cortisiko requested changes
good stuff @shanejonas I left a few comments.  Sharing https://github.com/MetaMask/contributor-docs/blob/main/docs/e2e/mobile-e2e-guidelines.md#step-2-create-the-networks-page-object in case you want a quick run down on how we create page objects within our tests!

2024-06-05 23:33 UTC, cortisiko commented on e2e/api-specs/json-rpc-coverage.js
> +              const cancelButton = await Matchers.getElementByText('Cancel');
We can use a page object for this. You would need to create the element for the Cancel Button and the user gesture to tap the cancel button. 

You can follow the same steps done with [tapApproveButton](https://github.com/MetaMask/metamask-mobile/blob/e2e-json-rpc-coverage-tool/e2e/pages/modals/NetworkApprovalModal.js#L10).

2024-06-05 23:33 UTC, cortisiko commented on e2e/api-specs/json-rpc-coverage.js
> +              const cancelButton = await Matchers.getElementByText('Cancel');
The SignModal page object have actions for tapping the cancel button.

```suggestion
await SigningModal.tapCancelButton();
```

2024-06-05 23:33 UTC, cortisiko commented on e2e/api-specs/json-rpc-coverage.js
> +              const cancelButton = await Matchers.getElementByText('Cancel');
The SignModal page object have actions for tapping the cancel button.

```suggestion
await SigningModal.tapCancelButton();
```

2024-06-05 23:33 UTC, cortisiko commented on e2e/api-specs/json-rpc-coverage.js
> +              const cancelButton = await Matchers.getElementByText('Cancel');
The ConnectModal page object have actions for tapping the cancel button.
```suggestion
              await ConnectModal.tapCancelButton();
```

2024-06-05 23:33 UTC, cortisiko commented on e2e/api-specs/json-rpc-coverage.js
> +      const webElement = await web.element(by.web.id('json-rpc-response'));
Create an element for this button in the TestDapp page object. Follow the exact steps [here](https://github.com/MetaMask/metamask-mobile/blob/e2e-json-rpc-coverage-tool/e2e/pages/Browser/TestDApp.js#L25) to create the element.

2024-06-05 23:33 UTC, cortisiko commented on e2e/api-specs/json-rpc-coverage.js
> +      await webElement.scrollToView();
Then in the TestDapp page object you can have a method that scrolls to the button. Something like scrollToJsonRPCResultSection()

[here](https://github.com/MetaMask/metamask-mobile/blob/e2e-json-rpc-coverage-tool/e2e/pages/Browser/TestDApp.js#L122) is how we scroll to a webview element

2024-06-06 14:02 UTC, shanejonas commented on e2e/api-specs/json-rpc-coverage.js
> +      await webElement.scrollToView();
This `json-rpc-response` element (or scrolling to it) isnt actually needed since I refactored the existing code that relied on the test-dapp.

2024-06-06 14:02 UTC, shanejonas commented on e2e/api-specs/json-rpc-coverage.js
> +      const webElement = await web.element(by.web.id('json-rpc-response'));
This `json-rpc-response` element isn't actually needed. but going to change it to `tag('body')`

2024-06-07 21:38 UTC, jiexi commented on package.json
> +    "test:api-specs": "detox test -c ios.sim.apiSpecs",
```suggestion
    "test:api-specs": "detox build -c ios.sim.release && detox test -c ios.sim.apiSpecs",
```

2024-06-07 21:40 UTC, jiexi commented on package.json
> +    "test:api-specs": "detox test -c ios.sim.apiSpecs",
getting this error when running things for the first time using just `detox test -c ios.sim.apiSpecs`
```
Failed to find the app binary at:
/Users/jiexi/Projects/metamask-mobile/ios/build/Build/Products/Debug-iphonesimulator/MetaMask.app

```

2024-06-18 16:17 UTC, Cal-L commented
@shanejonas nice work on this! Just curious, were you ever able to get the mock server working?

2024-06-20 15:32 UTC, shanejonas commented
@Cal-L mock server stuff is working now, but an unrelated android e2e suite is failing.

2024-06-21 21:10 UTC, cortisiko commented on bitrise.yml
> +  - push_branch: e2e-json-rpc-coverage-tool
remember to remove this prior to merge.

2024-06-24 20:07 UTC, shanejonas commented
@SocketSecurity ignore npm/json-schema-ref-parser@6.1.0
@SocketSecurity ignore npm/@mantine/hooks@7.8.0
@SocketSecurity ignore npm/@open-rpc/server-js@1.9.3
@SocketSecurity ignore npm/@open-rpc/test-coverage@2.2.2

2024-06-24 20:17 UTC, cortisiko approved these changes, later dismissed
🌮 🌮 🌮  Looks good!

2024-06-25 16:06 UTC, tommasini commented on e2e/api-specs/json-rpc-coverage.js
> +const mockServer = require('@open-rpc/mock-server/build/index').default;
Any reason we can't use import here?

2024-06-25 16:07 UTC, tommasini submitted a review, later dismissed
LGTM

2024-06-26 16:11 UTC, cortisiko approved these changes
LGTM!

2024-06-26 16:12 UTC, shanejonas commented on e2e/api-specs/json-rpc-coverage.js
> +const mockServer = require('@open-rpc/mock-server/build/index').default;
we can change this later i dont think we should block on this

2024-06-26 16:17 UTC, tommasini approved these changes

2024-06-26 16:18 UTC, merged