feat: create basic Name component for simulations
MetaMask/metamask-mobile pull request #9379
Opened 2024-04-23 15:28 UTC by dbrans

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-25 08:40 UTC, OGPoyraz commented on app/component-library/components/Tags/NameTag/NameTag.tsx
> +/* eslint-disable react/prop-types */
Nit: I know that this rule inherited from other components but removing is not breaking linter.

2024-04-25 08:41 UTC, OGPoyraz commented on app/component-library/components/Tags/NameTag/NameTag.styles.ts
> +// Third party dependencies.
Nit: These are also inherited but can we also remove them?

2024-04-25 08:45 UTC, OGPoyraz commented on ios/Podfile.lock
> +  - "react-native-splash-screen (from `../node_modules/@metamask/react-native-splash-screen`)"
Are these changes intended?

2024-04-25 09:14 UTC, OGPoyraz approved these changes, later dismissed

2024-04-25 11:59 UTC, dbrans commented on app/component-library/components/Tags/NameTag/NameTag.tsx
> +/* eslint-disable react/prop-types */
Goktug, without this line I see these errors:

```
app/component-library/components/Tags/NameTag/NameTag.tsx
  13:49  error  'address' is missing in props validation  react/prop-types
  13:58  error  'style' is missing in props validation    react/prop-types

✖ 2 problems (2 errors, 0 warnings)
```

2024-04-25 12:07 UTC, dbrans commented on app/component-library/components/Tags/NameTag/NameTag.tsx
> +/* eslint-disable react/prop-types */
Goktug, without this line I see these errors:

```
app/component-library/components/Tags/NameTag/NameTag.tsx
  13:49  error  'address' is missing in props validation  react/prop-types
  13:58  error  'style' is missing in props validation    react/prop-types

✖ 2 problems (2 errors, 0 warnings)
```

2024-04-25 12:07 UTC, dbrans commented on ios/Podfile.lock
> +  - "react-native-splash-screen (from `../node_modules/@metamask/react-native-splash-screen`)"
Done.

2024-04-25 12:10 UTC, OGPoyraz commented on app/component-library/components/Tags/NameTag/NameTag.tsx
> +/* eslint-disable react/prop-types */
Interesting, I actually tested this before commenting, probably something on my end, sorry for the bother

2024-04-25 12:11 UTC, OGPoyraz submitted a review, later dismissed

2024-04-25 16:14 UTC, brianacnguyen requested changes
Since this is not an official design system component, please put this in the component-temp folder

2024-04-25 16:46 UTC, dbrans commented
> Since this is not an official design system component, please put this in the component-temp folder

Done.

2024-04-26 09:24 UTC, OGPoyraz submitted a review, later dismissed

2024-04-26 13:41 UTC, matthewwalsh0 commented
> @brianacnguyen wrote:
> 
> > Since this is not an official design system component, please put this in the component-temp folder
> 
> Done.

My understanding is the `component-library` is for the reviewed components managed by the design team, that provide the visual building blocks of our components, but that are free of domain and business logic.

Since this component will grow to include more domain and integrated business logic, would it better placed in `app/components/UI`?

2024-04-26 15:47 UTC, dbrans commented
> Since this component will grow to include more domain and integrated business logic, would it better placed in app/components/UI?
Done.

2024-04-26 15:53 UTC, OGPoyraz submitted a review, later dismissed

2024-04-26 17:13 UTC, dbrans commented on app/component-library/components-temp/NameTag/NameTag.tsx
Matt, just wanted to follow up on my rationale for suggesting "NameTag" over "Name" for that component. 

I felt that "NameTag" more accurately captures the visual nature of the component and the fact that it includes both the identifying name and an avatar. "Name" felt a bit too generic and only referenced one aspect.

That said, I'm open to your perspective on this. If you disagree and think "Name" is the way to go, I'm happy to go with that for the sake of moving forward.

Let me know your thoughts!

2024-04-26 17:49 UTC, dbrans commented on app/components/hooks/DisplayName/useDisplayName.ts
> +  UnknownAddress = 'UnknownAddress',
Done.

2024-04-26 17:49 UTC, dbrans commented on app/components/hooks/DisplayName/useDisplayName.ts
> +export interface DisplayName {
Done.

2024-04-26 17:49 UTC, dbrans commented on app/components/hooks/DisplayName/useDisplayName.ts
> +export interface DisplayName {
Hey Matt, thanks for raising this concern. You're right that my PR diverges from the extension's `UseDisplayNameResponse` type. 

I made these changes because I felt that `DisplayName` better matched the convention of `useFoo` returning `Foo`, and an enum seemed clearer than booleans for representing the provenance and nature of the name. But I may have overlooked some considerations.

I'm open to adjusting the types and names to better align with the extension if you think that's best. We can always discuss on video or slack if it's easier.

2024-04-26 18:06 UTC, dbrans commented on app/component-library/components-temp/NameTag/NameTag.tsx
> +        {displayName.name}
Good point, Matt. I can see the argument for handling `toChecksumAddress` in the rendering component since it does affect how the address is displayed.

However, my thinking is that since `toChecksumAddress` changes the actual value of the address rather than just its styling, it might be better to keep it in the `useDisplayName` hook. That way, if we use the hook in multiple places, the displayed address will be consistent across the app.

But I'm open to discussing this further!

2024-04-26 18:06 UTC, dbrans commented on app/components/hooks/DisplayName/useDisplayName.ts
> +  UnknownAddress = 'UnknownAddress',
Done.

2024-04-26 18:06 UTC, dbrans commented on app/component-library/components-temp/NameTag/NameTag.styles.ts
> +  vars: { style: ViewProps['style']; displayNameVariant: DisplayNameVariant };
Done.

2024-04-26 18:06 UTC, dbrans commented on app/components/hooks/DisplayName/useDisplayName.ts
> +export interface DisplayName {
Done.

2024-04-26 18:21 UTC, dbrans commented on app/component-library/components-temp/NameTag/NameTag.types.ts
> +export interface NameTagProperties extends ViewProps {
I see your point about aligning with the extension and future-proofing. Introducing a `NameType` enum could be a good way to prepare for handling different types of addresses down the line.

My only hesitation is that it might be a bit premature to add this abstraction until we have a more concrete need for it. If we end up never implementing names for other things, or if an enum doesn't turn out to be the right abstraction, we could end up with unnecessary complexity in our APIs and components.

What do you think about holding off on the `NameType` enum for now, and revisiting it once we have a clearer picture of how we'll be handling different address types? I'm open to finding the best path forward.

2024-04-26 18:33 UTC, dbrans commented on app/component-library/components/Tags/NameTag/NameTag.styles.ts
> +// Third party dependencies.
Done

2024-04-27 08:36 UTC, matthewwalsh0 commented on app/component-library/components-temp/NameTag/NameTag.tsx
Even if we changed the name in future, I'd vote to do that as an isolated piece of work in both clients.

So for now i'd vote to align and go with `Name` for the sake of consistency while the mobile component is expanded.

2024-04-27 08:39 UTC, matthewwalsh0 commented on app/component-library/components-temp/NameTag/NameTag.types.ts
> +export interface NameTagProperties extends ViewProps {
It's not technically future-proofing as the `NameType` is already present in the `NameController` as a mechanism to generalise the petname support.

Meaning this component has to also support name types not just for the sake of extensibility, but also for compatibility with `NameController` which will almost certainly be used in future.

So this `NameType` would just be a temporary clone of the `NameController` equivalent until that's adopted in future work.

2024-04-27 08:44 UTC, matthewwalsh0 commented on app/components/hooks/DisplayName/useDisplayName.ts
> +export interface DisplayName {
Fair point, I really like the enum, and the name is fine if that's consistent with other mobile hooks.

Just important we try and match the implementation (where feasible) from the extension for the sake of consistency and quick implementation as we add more to it.

2024-04-27 08:51 UTC, matthewwalsh0 commented on app/component-library/components-temp/NameTag/NameTag.tsx
> +        {displayName.name}
I think this highlights another divergence from the extension as the `useDisplayName` hook there doesn't return the address back as the name, it returns `null` which feels more conceptually correct since there is no available name for the given address.

I'd vote to match that behaviour here for consistency, meaning it's then a rendering choice by the `Name` component itself to display the original address as checksummed since the hook has told us there is no better name.

2024-04-28 14:38 UTC, dbrans commented on app/component-library/components-temp/NameTag/NameTag.tsx
> +        {displayName.name}
Sounds good! Done.

2024-04-28 14:38 UTC, dbrans commented on app/component-library/components-temp/NameTag/NameTag.types.ts
> +export interface NameTagProperties extends ViewProps {
Ah I see what you mean! So essentially:

1. Add a `NameType` enum here that mirrors the one in `NameController` 
2. Make `Name` accept a `type` prop and call `useDisplayName` with that type
3. Export an `EthereumAddressName` component that passes `ETHEREUM_ADDRESS` to `Name`

So SimulationDetails, for example, uses `EthereumAddressName`, a specialized Name component, and we can easily add other types later. Sound about right? Totally makes sense to get that infrastructure in place now to avoid hassle down the line.

2024-04-28 15:17 UTC, dbrans commented on app/component-library/components-temp/NameTag/NameTag.tsx
Renamed

2024-04-29 06:35 UTC, OGPoyraz submitted a review, later dismissed

2024-04-29 15:02 UTC, brianacnguyen submitted a review, later dismissed

2024-04-29 16:52 UTC, matthewwalsh0 commented on app/component-library/components-temp/NameTag/NameTag.types.ts
> +export interface NameTagProperties extends ViewProps {
All correct, except point 3.

The `EthereumAddressName` would exist purely inside `Name.ts` as a way to encapsulate the support for the `ETHEREUM_ADDRESS` type.

2024-04-29 16:56 UTC, matthewwalsh0 commented on app/components/UI/Name/Name.types.ts
> +  address: string;
Missed this but this also needs to be the more general `value` so not coupled to Ethereum addresses.

2024-04-30 07:46 UTC, matthewwalsh0 approved these changes

2024-04-30 08:38 UTC, OGPoyraz approved these changes

2024-04-30 08:38 UTC, OGPoyraz commented
@dbrans am merging this in order to unblock other awaiting PRs, hope you don't mind

2024-04-30 08:38 UTC, merged

2024-04-30 09:41 UTC, legobeat commented
> @dbrans am merging this in order to unblock other awaiting PRs, hope you don't mind

@OGPoyraz FYI: #9455