Initial *.metafi and *.metaswap URL migrations
MetaMask/metamask-mobile pull request #9388
Opened 2024-04-24 15:06 UTC by kylanhurt

## **Description**

## **Related issues**

Fixes: https://github.com/orgs/MetaMask/projects/60/views/6?pane=issue&itemId=59223328

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-24 15:08 UTC, kylanhurt commented on app/components/UI/AssetSearch/index.test.tsx
> +            'https://static.api.cx.metamask.io/api/v1/tokenIcons/1/0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f.png',
New image not loading

2024-04-24 15:13 UTC, kylanhurt commented on e2e/fixtures/fixture-builder.js
> +                    'https://static.api.cx.metamask.io/api/v1/tokenIcons/1/0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f.png',
New image not loading

2024-04-24 21:27 UTC, sethkfman commented
@kylanhurt Can you add the new domain in the description to make it easier to tell what should be changed?

2024-04-25 14:52 UTC, sethkfman commented on app/components/UI/AssetSearch/index.test.tsx
> +            'https://static.cx.metamask.io/api/v1/tokenIcons/1/0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f.png',
Is there a reason why `api.` is not included in this URL?

2024-04-25 14:54 UTC, sethkfman submitted a review, later dismissed
LGTM. 1 small clarifying question, then confirm E2E passes and reach out to Ramps and Tx team for review

2024-04-25 16:43 UTC, kylanhurt commented on app/components/UI/AssetSearch/index.test.tsx
> +            'https://static.cx.metamask.io/api/v1/tokenIcons/1/0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f.png',
@sethkfman Per Michael Hahn's comment on Slack. I think it makes sense because some of these are assets rather than API calls.

https://consensys.slack.com/archives/C03MLR70YSK/p1713972239163469?thread_ts=1713878326.946659&cid=C03MLR70YSK

2024-04-25 16:48 UTC, wachunei requested changes
Just a small change request: for all occurrences of `*.metafi-dev.codefi.network/*` the url to used should be `*.dev-api.cx.metamask.io/*` (ie: use `dev-api` instead of `api` for `metafi-dev`). 

I pointed out a case below.

2024-04-25 18:12 UTC, wachunei submitted a review, later dismissed
LGTM

2024-04-25 20:27 UTC, gauthierpetetin commented
Looks good to me.

I'm just curious know if we need to updated these occurences of `.metafi` as well?
- [app/core/AppConstants.ts](https://github.com/MetaMask/metamask-mobile/blob/main/app/core/AppConstants.ts#L187)
- [patches/@metamask+assets-controllers+14.0.0.patch](https://github.com/MetaMask/metamask-mobile/blob/main/patches/%40metamask%2Bassets-controllers%2B14.0.0.patch)
- [patches/@metamask+controller-utils+5.0.2.patch](https://github.com/MetaMask/metamask-mobile/blob/main/patches/%40metamask%2Bcontroller-utils%2B5.0.2.patch)

Abd these occurences of `.metaswap` as well?

- [e2e/resources/blacklistURLs.json](https://github.com/MetaMask/metamask-mobile/blob/main/e2e/resources/blacklistURLs.json#L13)
- [patches/@metamask+assets-controllers+14.0.0.patch](https://github.com/MetaMask/metamask-mobile/blob/main/patches/%40metamask%2Bassets-controllers%2B14.0.0.patch#L3190-L3192)

2024-04-25 21:37 UTC, sethkfman commented
@gauthierpetetin The patch files should eventually be updated by the controller upgrades. 

@desi I just created a [ticket](https://github.com/MetaMask/core/issues/4215) for your team.

2024-04-26 01:18 UTC, gauthierpetetin commented
I understand that the controllers will be upgraded at some point in Mobile but since we don't know yet exactly when that will be the case, can we not keep the [patches](https://github.com/MetaMask/metamask-mobile/pull/9388/commits/e0a7b907cc5f06e078ba255f912d5db2eefc6656) in the meanwhile, such that we can announce API Platform team that we don't use the deprecated urls anymore, as soon as this PR is merged?

2024-05-03 15:21 UTC, sethkfman approved these changes
LGTM

2024-05-06 14:54 UTC, merged