feat: notifications onboarding wizard
MetaMask/metamask-mobile pull request #9392
Opened 2024-04-24 21:30 UTC by Jonathansoufer

## **Description**

This PR is based on [9263](https://github.com/MetaMask/metamask-mobile/pull/9263), reverted due an e2e failure, which is fixed on this PR. 

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-25 08:50 UTC, tommasini reviewed
Amazing job here! ❤️
Just left comments for we convert to typescript the new step 7 component and if possible the one that was converted to functional component to typescript as well. That will help US continue growing the typescript coverage of the app 🙏🏼

2024-04-25 08:50 UTC, tommasini commented on app/components/UI/OnboardingWizard/Step2/index.js
> -class Step2 extends PureComponent {
Love what you did here! If you see the possibility, converting it to typescript would be amazing!

2024-04-25 08:50 UTC, tommasini commented on app/components/UI/OnboardingWizard/Step7/index.js
> +import React, { useEffect, useState } from 'react';
Do you think we could convert this new component to typescript?

2024-04-26 17:09 UTC, Jonathansoufer commented on app/components/UI/OnboardingWizard/Step2/index.js
> -class Step2 extends PureComponent {
Surething!

2024-04-26 17:09 UTC, Jonathansoufer commented on app/components/UI/OnboardingWizard/Step7/index.js
> +import React, { useEffect, useState } from 'react';
Surething!

2024-04-29 15:44 UTC, brianacnguyen submitted a review, later dismissed

2024-04-30 21:04 UTC, legobeat requested changes, later dismissed
Unit tests are failing: https://github.com/MetaMask/metamask-mobile/actions/runs/8900659423/job/24442767307?pr=9392

2024-05-06 11:24 UTC, NicolasMassart commented
On iOS, the tour bubbles are not correctly placed relatively to the point they show, it may even hide the buttons a bit.
|2/6|3/6|4/6|5/6|6/6|
|-|-|-|-|-|
|<img src="https://github.com/MetaMask/metamask-mobile/assets/4677568/d89341bc-e5eb-4b0a-8068-d224523b1517" width="150px" />|<img src="https://github.com/MetaMask/metamask-mobile/assets/4677568/13485b5a-eedf-4725-b60c-9e17ece4a464" width="150px" />|<img src="https://github.com/MetaMask/metamask-mobile/assets/4677568/639ad691-5ae5-4c25-b1b3-ea6639cb49f3" width="150px" />|<img src="https://github.com/MetaMask/metamask-mobile/assets/4677568/0e889a92-dbf4-435e-837e-f4728c6a92d1" width="150px" />|<img src="https://github.com/MetaMask/metamask-mobile/assets/4677568/37f283f7-dfd1-4149-9b8b-78ebf6fdc662" width="150px" />|

2024-05-06 11:31 UTC, NicolasMassart reviewed
On iOS, the tour bubbles are not correctly placed relatively to the point they show, it may even hide the buttons a bit.
|2/6|3/6|4/6|5/6|6/6|
|-|-|-|-|-|
|<img src="https://github.com/MetaMask/metamask-mobile/assets/4677568/d89341bc-e5eb-4b0a-8068-d224523b1517" width="150px" />|<img src="https://github.com/MetaMask/metamask-mobile/assets/4677568/13485b5a-eedf-4725-b60c-9e17ece4a464" width="150px" />|<img src="https://github.com/MetaMask/metamask-mobile/assets/4677568/639ad691-5ae5-4c25-b1b3-ea6639cb49f3" width="150px" />|<img src="https://github.com/MetaMask/metamask-mobile/assets/4677568/0e889a92-dbf4-435e-837e-f4728c6a92d1" width="150px" />|<img src="https://github.com/MetaMask/metamask-mobile/assets/4677568/37f283f7-dfd1-4149-9b8b-78ebf6fdc662" width="150px" />|

2024-05-06 14:02 UTC, Jonathansoufer commented
> On iOS, the tour bubbles are not correctly placed relatively to the point they show, it may even hide the buttons a bit.
> 
> 2/6	3/6	4/6	5/6	6/6
> <img alt="" width="150px" src="https://private-user-images.githubusercontent.com/4677568/328159704-d89341bc-e5eb-4b0a-8068-d224523b1517.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTg5MTUsIm5iZiI6MTcxNDk5ODYxNSwicGF0aCI6Ii80Njc3NTY4LzMyODE1OTcwNC1kODkzNDFiYy1lNWViLTRiMGEtODA2OC1kMjI0NTIzYjE1MTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMTIzMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE0YTM5ZGIyNDE1ZWJiZjNjMjlkMWE0MjhiYWE5YjFkNTAzYmM1YmNhYmRmMjY5YTE2YTcwZDlkNWQ5NTBmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JvzvVt088ojxPHN-4rz80sOIriFeRLOYz37Hfh3Bymc">	<img alt="" width="150px" src="https://private-user-images.githubusercontent.com/4677568/328159797-13485b5a-eedf-4725-b60c-9e17ece4a464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTg5MTUsIm5iZiI6MTcxNDk5ODYxNSwicGF0aCI6Ii80Njc3NTY4LzMyODE1OTc5Ny0xMzQ4NWI1YS1lZWRmLTQ3MjUtYjYwYy05ZTE3ZWNlNGE0NjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMTIzMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2MyOTU0NzY5Y2Q0MGI5ODQzZjllYThlOWM1ZDllZTM0NWYxZThlNTk0NDNmODQ4ZDQ1Yjk4ODhlNTlkZjJiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4Orak9qO3E3KnGibFvxgDXZSBXtmLfoub8X9P4CYu0U">	<img alt="" width="150px" src="https://private-user-images.githubusercontent.com/4677568/328159838-639ad691-5ae5-4c25-b1b3-ea6639cb49f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTg5MTUsIm5iZiI6MTcxNDk5ODYxNSwicGF0aCI6Ii80Njc3NTY4LzMyODE1OTgzOC02MzlhZDY5MS01YWU1LTRjMjUtYjFiMy1lYTY2MzljYjQ5ZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMTIzMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmVhNmEzZmYwN2JkOWRkZTcwZGNjOGUyMjkxMzk5MzhhMDE4ODcxZDAwMDdmZjA1YjM5MzA1ODgwZGEwZTA5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SkCfZXDoZAqAT2re1aNpq-q93gb-PGqGAXPauiAwoZs">	<img alt="" width="150px" src="https://private-user-images.githubusercontent.com/4677568/328159890-0e889a92-dbf4-435e-837e-f4728c6a92d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTg5MTUsIm5iZiI6MTcxNDk5ODYxNSwicGF0aCI6Ii80Njc3NTY4LzMyODE1OTg5MC0wZTg4OWE5Mi1kYmY0LTQzNWUtODM3ZS1mNDcyOGM2YTkyZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMTIzMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWRkMGEyZDNlMmI4ZmI5YjhmZTU2NjMwNDE4M2QyNTYyMjFkMWYwZTQwNTIwYmExOWZlZDI1N2JlODgxZTAzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ReOt9XnNVCysBYmLEEoyn_Fo8OG1IctxY9u1Pka9uKA">	<img alt="" width="150px" src="https://private-user-images.githubusercontent.com/4677568/328159926-37f283f7-dfd1-4149-9b8b-78ebf6fdc662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5OTg5MTUsIm5iZiI6MTcxNDk5ODYxNSwicGF0aCI6Ii80Njc3NTY4LzMyODE1OTkyNi0zN2YyODNmNy1kZmQxLTQxNDktOWI4Yi03OGViZjZmZGM2NjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMTIzMDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzU5MjczNGE1MWU3MTQyZTQ5MjQwNDQxMTNhY2EyMDYyZTY5N2YwMmYwMzlmYjBkNTE5NTdmMGM1YTQ0MTQ5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e3QKyWnGwq-WhlvuxTH6HDBSOzxm-3o8c2hxWE8fiM0">

Addressed! 

https://github.com/MetaMask/metamask-mobile/assets/44679989/8dde36e5-a0f7-4dbd-840c-d870fb4b4117

2024-05-07 08:43 UTC, NicolasMassart reviewed
The Positions look better now even if I steel have a small missalignment for notifications step 3/6 (iOS 17.4 iPhone 13 pro simulator)
<img width="378" alt="image" src="https://github.com/MetaMask/metamask-mobile/assets/4677568/e46d3e84-dbb2-4e4e-97d8-65431e3c13b5">
Is there a Figma I could check to see if it's expected? I haven't found any in the original PR as it's not linked to any issue (it should).

As indicated by Sonar, you will also have ot fix the duplication to pass the gate and merge.
I suggest that you create a common component from all steps by picking the common code parts and then only have the variations on each specific step.

2024-05-07 12:00 UTC, Jonathansoufer commented
> The Positions look better now even if I steel have a small missalignment for notifications step 3/6 (iOS 17.4 iPhone 13 pro simulator) <img alt="image" width="378" src="https://private-user-images.githubusercontent.com/4677568/328452022-e46d3e84-dbb2-4e4e-97d8-65431e3c13b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODM0OTUsIm5iZiI6MTcxNTA4MzE5NSwicGF0aCI6Ii80Njc3NTY4LzMyODQ1MjAyMi1lNDZkM2U4NC1kYmIyLTRlNGUtOTdkOC02NTQzMWUzYzEzYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMTE1OTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjViMmM4ZDQ2ZDQxZGNmOGVlZDI4Mjg3MTI0ZjgwZmE5NTk4YzY3MTMwODdhNWVkMWYwZDRkNmRmOWEyNjhjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.G_YzP6CCafLeAgsPAeg7MDLXnj5AYwqI20iVxD2jd2E"> Is there a Figma I could check to see if it's expected? I haven't found any in the original PR as it's not linked to any issue (it should).
> 
> As indicated by Sonar, you will also have ot fix the duplication to pass the gate and merge. I suggest that you create a common component from all steps by picking the common code parts and then only have the variations on each specific step.

Fixed.

![Screenshot 2024-05-07 at 12 58 11](https://github.com/MetaMask/metamask-mobile/assets/44679989/c8391ca3-2492-4c4f-a32c-305b7bc8cd5a)

2024-05-07 16:33 UTC, NicolasMassart approved these changes
Looks good to me. Nice work!

2024-05-07 16:34 UTC, merged