Add useFirstPartyContractName hook
MetaMask/metamask-mobile pull request #9407
Opened 2024-04-25 12:31 UTC by OGPoyraz

## **Description**

This PR aims to add `useFirstPartyContractNames` hook to be added in to `useDisplayName`

## **Related issues**

Fixes: https://github.com/MetaMask/mobile-planning/issues/1715

## **Manual testing steps**

N/A

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-04-30 08:46 UTC, OGPoyraz commented on app/component-library/hooks/useFirstPartyContractName.test.ts
> +import { CHAIN_IDS } from '@metamask/transaction-controller/dist/constants';
Not a fan of this but I will keep it in order to follow same convention for now.

2024-04-30 08:57 UTC, OGPoyraz commented on app/constants/first-party-contracts.ts
> +    // [CHAIN_IDS.ZKSYNC_ERA]: '0xf504c1fe13d14DF615E66dcd0ABF39e60c697f34',
Added in next patch https://github.com/MetaMask/core/pull/4201/commits/e4b614610d5c3f66803cf41d5f21b7d3fe2fad33

2024-04-30 11:18 UTC, OGPoyraz commented on app/component-library/hooks/useFirstPartyContractName.ts
> +export function useFirstPartyContractNames(
This will be needed in simulation metrics but to prevent back and forth in the PRs I will leave this here.

2024-05-01 15:35 UTC, brianacnguyen commented on app/component-library/hooks/useFirstPartyContractName.test.ts
> +import { CHAIN_IDS } from '@metamask/transaction-controller/dist/constants';
Hello @OGPoyraz the hooks in this folder is reserved for the design system only. can you move these to the components folder?

2024-05-01 15:35 UTC, brianacnguyen requested changes, later dismissed
These files belong in the components folder

2024-05-01 17:16 UTC, matthewwalsh0 commented on app/constants/first-party-contracts.ts
> +import { CHAIN_IDS } from '@metamask/transaction-controller/dist/constants';
Should we be reliant on transaction controller chain IDs, or the local definitions?

There is also `NETWORKS_CHAIN_ID` in `app/constants/network.js`.

2024-05-01 17:16 UTC, matthewwalsh0 commented on app/component-library/hooks/useFirstPartyContractName.ts
Can we also update `useDisplayName` in this PR?

2024-05-01 17:16 UTC, matthewwalsh0 commented on app/component-library/hooks/useFirstPartyContractName.ts
> +  type: NameType;
I missed this in the extension, but since this hook is separate to the `Name` component, we shouldn't need any coupling to `NameType` or `variation` since this hook is only relevant to Ethereum addresses.

Should we just remove the `type` argument and rename `variation` to `chainId` so it's explicit?

2024-05-01 17:16 UTC, matthewwalsh0 commented on package.json
> +    "@metamask/name-controller": "^6.0.1",
We don't want to add a dependency on `NameController` yet.

We have a local definition of `NameType` but we shouldn't need it for this hook since as mentioned in the other comment.

2024-05-02 09:42 UTC, OGPoyraz commented on app/component-library/hooks/useFirstPartyContractName.test.ts
> +import { CHAIN_IDS } from '@metamask/transaction-controller/dist/constants';
Hey @brianacnguyen , you're right I missed this, will fix it.

2024-05-02 11:42 UTC, OGPoyraz commented on app/component-library/hooks/useFirstPartyContractName.ts
Updated now

2024-05-02 11:42 UTC, OGPoyraz commented on app/component-library/hooks/useFirstPartyContractName.ts
> +  type: NameType;
That make sense, changes are done

2024-05-03 16:03 UTC, matthewwalsh0 approved these changes

2024-05-06 06:37 UTC, merged