feat: notifications details screen
MetaMask/metamask-mobile pull request #9473
Opened 2024-04-30 19:55 UTC by Jonathansoufer

## **Description**

This PR implements notification's Details screen

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [x] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [x] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-05 18:40 UTC, tommasini commented on app/components/Views/Notifications/Details/TX.tsx
> +/* eslint-disable react/prop-types */
Is this a notifciation details transaction?

Can we create a folder with a name like `TransactionDetails` under the Notifications Details or just `Transaction` and add respective `.test` and `.types` file?

The same to the Badge.tsx. Header.tsx and Annoucement.tsx components

With this structure created we can snapshot every component, and if any other engineer change anything on our app, let's say for example a component of component-library, we know that this file was impacted.

We try to have a structure per component
* Component.tsx
* Component.test.tsx
* Component.types.ts
* Component.styles.ts

2024-06-05 18:51 UTC, tommasini requested changes
Hey @Jonathansoufer great work! Left some comments!

2024-06-05 18:51 UTC, tommasini commented on app/components/Views/Notifications/Details/useDetails.tsx
> +      // @ts-ignore
Not sure if this is needed, but to ignore any typescript issue that we see that it will handle on the near future we can use ts-expect-error! Please take a look at https://github.com/MetaMask/contributor-docs/blob/main/docs/typescript.md#escape-hatches

2024-06-05 18:51 UTC, tommasini commented on app/components/Views/Notifications/Details/useDetails.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Maybe to avoid eslint disable rules we can turn this into a new component called `NotificationDetailsStatus?` Or `Status` under the Notification Details folder

2024-06-05 18:51 UTC, tommasini commented on app/components/Views/Notifications/Details/index.tsx
> +        // eslint-disable-next-line react-native/no-inline-styles
Please move this to the styles file instead of disabling eslint here

2024-06-05 18:51 UTC, tommasini commented on app/components/Views/Notifications/Details/index.tsx
> +/* eslint-disable react/display-name */
Not sure of why we need this eslint disable here, could you elaborate?

2024-06-05 18:51 UTC, tommasini commented on app/components/Views/Notifications/Details/TX.tsx
> +        // eslint-disable-next-line no-console
Is this console log missing? Can we remove it and the eslint-disable rule?

2024-06-05 18:51 UTC, tommasini commented on app/components/Views/Notifications/Details/Announcements.tsx
> +        // @ts-ignore
Please consider removing ts-ignore here, we should use ts-expect-error instead, but I believe this can be typed and `link` doesn't need the conditional operator since it's being checked on the line above

2024-06-05 19:17 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/index.tsx
> +/* eslint-disable react/display-name */
This is due a various [issues](https://github.com/jsx-eslint/eslint-plugin-react/issues/597), specially when we use `.navigationOptions`

2024-06-05 19:20 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/index.tsx
> +        // eslint-disable-next-line react-native/no-inline-styles
Good catch. Fixed.

2024-06-05 19:26 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/useDetails.tsx
> +      // @ts-ignore
Most of this types will be refactored to be using shared library ones, which we have a PR open on core codebase already. Changed to follow contributors' guidelines.

2024-06-05 19:31 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/useDetails.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Although this could be an optimal approach, this would imply to the same for the other render*. I added all the deps instead. Most likely this screen will face a major refactor due the integration of Notifications' logic into packages/core codebase.

2024-06-06 16:19 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/TX.tsx
> +        // eslint-disable-next-line no-console
Fixed.

2024-06-06 16:32 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/TX.tsx
> +/* eslint-disable react/prop-types */
Cool, I adjusted the structure to follow that pattern, but would rather add the unit tests later in a different PR. Now I'm just making sure they are rendering.

2024-06-10 16:13 UTC, brianacnguyen commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.types.ts
> +  testID: string;
can you add a description here?

2024-06-10 16:13 UTC, brianacnguyen approved these changes, later dismissed
approved with non-blocking change requested

2024-06-10 16:48 UTC, Jonathansoufer commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.types.ts
> +  testID: string;
Sure

2024-06-12 11:59 UTC, tommasini commented on app/components/Views/Notifications/Details/Announcements/index.tsx
> +const PLACEHOLDER_IMG_URI = require('../../../../../images/no-image-placeholder.jpeg');
Any reason we really need to use require here?

2024-06-12 11:59 UTC, tommasini commented on app/components/Views/Notifications/Details/Announcements/index.tsx
> +  navigation: any;
Could we avoid the usage of any here? I believe instead of a prop we can use `useNavigation` hook instead no?

2024-06-12 12:00 UTC, tommasini commented on app/components/Views/Notifications/Details/Announcements/index.tsx
> +  styles: Record<string, any>;
Not fully understanding why we have the styles as a property here

2024-06-12 12:02 UTC, tommasini commented on app/components/Views/Notifications/Details/NetworkFee/index.tsx
> +  // TODO: Present an error screen when there is an error fetching the network fees
Is there an issue for this TODO?

2024-06-12 12:03 UTC, tommasini commented on app/components/Views/Notifications/Details/NetworkFee/index.tsx
> +  styles: any;
The same here, do we need the styles as a property?

2024-06-12 12:39 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/Announcements/index.tsx
> +const PLACEHOLDER_IMG_URI = require('../../../../../images/no-image-placeholder.jpeg');
Anywhere we provide local images to Image components it's preferable to use require instead of import [see here](https://reactnative.dev/docs/images), and this pattern is used throughout the app as we can see [here](https://github.com/MetaMask/metamask-mobile/blob/8f3968cc914b3e18d01a0e7d3092959eb2c6d9d3/app/components/UI/BiometryButton/BiometryButton.tsx), [here](app/components/UI/EnableAutomaticSecurityChecksModal/EnableAutomaticSecurityChecksModal.tsx) or [here](https://github.com/MetaMask/metamask-mobile/blob/9b25acf4a8bd26c69986c55f5c3dbb267639a379/app/components/UI/LedgerModals/Steps/ConfirmationStep.tsx)

2024-06-12 12:47 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/Announcements/index.tsx
> +  navigation: any;
I adjusted the type to avoid any, but speaking about the pattern, we're calling navigation and styles only on the [parent component](https://github.com/MetaMask/metamask-mobile/blob/2508b2403452bd5075ffc6e1118ae805dd63a7b3/app/components/Views/Notifications/Details/index.tsx#L86-L95) and passing it down to avoid instantiate multiple times these elements since they're used on every sub comp on this structure.

2024-06-12 12:47 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/NetworkFee/index.tsx
> +  styles: any;
About the pattern, we're calling navigation and styles only on the [parent component](https://github.com/MetaMask/metamask-mobile/blob/2508b2403452bd5075ffc6e1118ae805dd63a7b3/app/components/Views/Notifications/Details/index.tsx#L86-L95) and passing it down to avoid instantiate multiple times these elements since they're used on every sub comp on this structure.

2024-06-12 12:48 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/OnChain/index.tsx
> +  styles,
About the pattern, we're calling navigation and styles only on the [parent component](https://github.com/MetaMask/metamask-mobile/blob/2508b2403452bd5075ffc6e1118ae805dd63a7b3/app/components/Views/Notifications/Details/index.tsx#L86-L95) and passing it down to avoid instantiate multiple times these elements since they're used on every sub comp on this structure.

2024-06-12 12:54 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/NetworkFee/index.tsx
> +  // TODO: Present an error screen when there is an error fetching the network fees
We do now :) [9953](https://github.com/MetaMask/metamask-mobile/issues/9953)

2024-06-12 13:05 UTC, tommasini approved these changes
LGTM

2024-06-12 13:13 UTC, merged