Refactor the network name util into a selector
MetaMask/metamask-mobile pull request #9638
Opened 2024-05-15 18:33 UTC by EtherWizard33

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-05-16 12:24 UTC, EtherWizard33 commented
test comment

2024-05-16 12:51 UTC, EtherWizard33 commented
Here is a 2 minute overview of the changes:
https://www.loom.com/share/66bfab4800fd4c16b863652424e68d34?sid=70e8ac74-ca71-48e2-9764-c2a4ce660dce

2024-05-16 14:13 UTC, EtherWizard33 commented on app/components/Views/NetworkSelector/__snapshots__/NetworkSelector.test.tsx.snap
> +                                          "backgroundColor": "#FFFFFF",
good point, i will look into it

2024-05-16 18:19 UTC, EtherWizard33 commented on app/components/Views/NetworkSelector/__snapshots__/NetworkSelector.test.tsx.snap
> +                                          "backgroundColor": "#FFFFFF",
for the this component, it looks like it's populating images from networkConfigurations, it went unnoticed because in the app the current wallet didnt have such configs but the test snapshot did, and it revealed that it's not using the same chainId as the current network to get the image, I am reverting the change to the NetworkSelector component and it's snapshot

2024-05-16 18:21 UTC, EtherWizard33 commented on app/components/Views/OnboardingSuccess/DefaultSettings/__snapshots__/index.test.js.snap
> -        >
this snapshot turned changed turned out indeed to be a case of the new selector not being mocked, with the new selector mocked, the snapshot doesnt need to change and the test needs to be adjusted, pushing the change

2024-05-17 00:25 UTC, tommasini commented on app/components/UI/ManageNetworks/ManageNetworks.test.js
> +const mockProviderConfig = 'Ethereum Main Network';
This name doesn't seem accurate, I think what we want it's more
```suggestion
const mockNetworkName = 'Ethereum Main Network';
```

2024-05-17 00:25 UTC, tommasini commented on app/components/UI/ManageNetworks/ManageNetworks.test.js
> +      if (selector === selectNetworkName) return mockProviderConfig;
```suggestion
      if (selector === selectNetworkName) return mockNetworkName;
```

2024-05-17 00:28 UTC, tommasini commented on app/components/UI/Ramp/Views/NetworkSwitcher/__snapshots__/NetworkSwitcher.test.tsx.snap
> +                                                        "backgroundColor": "#FFFFFF",
I think this snapshot was missed

2024-05-17 00:30 UTC, tommasini commented on app/components/Views/OnboardingSuccess/DefaultSettings/index.test.js
> +const mockProviderConfig = 'Ethereum Main Network';
```suggestion
const mockNetworkName = 'Ethereum Main Network';
```

2024-05-17 00:30 UTC, tommasini commented on app/components/Views/OnboardingSuccess/DefaultSettings/index.test.js
> +      if (selector === selectNetworkName) return mockProviderConfig;
```suggestion
      if (selector === selectNetworkName) return mockNetworkName;
```

2024-05-17 00:31 UTC, tommasini commented on app/components/Views/Settings/NetworksSettings/index.js
> -        const image = getNetworkImageSource({ chainId });
I think here we should keep the util function with the chainid from the filteredNetworks no?

2024-05-17 00:33 UTC, tommasini commented on app/components/Views/Settings/SecuritySettings/SecuritySettings.tsx
> -          const image = getNetworkImageSource({ chainId: chainId?.toString() });
I think here as well, if not it will always show the image of ethereum right?

2024-05-17 00:36 UTC, tommasini requested changes
After addressing the conversations, could you record a video of the app impacted screens?

2024-05-17 13:52 UTC, EtherWizard33 commented on app/components/UI/Ramp/Views/NetworkSwitcher/__snapshots__/NetworkSwitcher.test.tsx.snap
> +                                                        "backgroundColor": "#FFFFFF",
thanks, I have updated the snapshot back to what it was before which now passes without changes to snapshots

2024-05-17 14:05 UTC, EtherWizard33 commented on app/components/Views/Settings/NetworksSettings/index.js
> -        const image = getNetworkImageSource({ chainId });
indeed, glad we caught this early, thanks, change is now pushed, marking as resolved

2024-05-17 14:11 UTC, EtherWizard33 commented on app/components/Views/Settings/SecuritySettings/SecuritySettings.tsx
> -          const image = getNetworkImageSource({ chainId: chainId?.toString() });
agreed, thanks, I have now pushed the change and marking as resolved

2024-05-20 15:59 UTC, brianacnguyen reviewed
why are we removing the close option in toast?

2024-05-21 14:15 UTC, EtherWizard33 commented
> why are we removing the close option in toast?

Hi Brian, this PR got merged with too much content which included stuff about the close option which is not part of this PR.
I actually had to [recreated a new PR which is just about selectors](https://github.com/MetaMask/metamask-mobile/pull/9683), and no UI, closing this one.

2024-05-21 14:15 UTC, closed without merging

2024-07-03 11:14 UTC, EtherWizard33 commented
marked as a closed task in github projects