feat: notifications integration sdk
MetaMask/metamask-mobile pull request #9673
Opened 2024-05-17 15:07 UTC by Jonathansoufer

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-05-22 11:19 UTC, tommasini commented on app/actions/notification/index.js
> +import { ACTIONS } from '../../reducers/notification';
Since we are shipping notification it would be cool to refactor this to use the slice pattern with RTK we have some examples on the codebase like this one: https://github.com/MetaMask/metamask-mobile/blob/4f830c83d26501f20310b25294693aea49bb0514/app/core/redux/slices/inpageProvider/index.ts#L1

It would be cool to instead of the action and reducer we have a single file with the slice instead, in typescript, let me know your thoughts!

2024-05-22 19:30 UTC, owencraston commented on app/actions/notification/index.js
> +import { ACTIONS } from '../../reducers/notification';
@tommasini what is the benefit of this slice pattern?

2024-05-22 19:30 UTC, owencraston commented on app/actions/notification/index.js
> +    type: ACTIONS.MODIFY_OR_SHOW_TRANSACTION_NOTIFICATION,
MUCH better 🔥

2024-05-22 19:38 UTC, owencraston commented on app/core/Engine.ts
> +    const metaMetricsController = new MetaMetricsController({
Is this going to replace the file `app/core/Analytics/MetaMetrics.ts`? If so what is the plan to remove this logic from the app?

2024-05-22 19:42 UTC, owencraston commented on app/core/Engine.ts
> +        return type === NETWORK_TYPES.RPC ? rpcUrl : type;
It seems like this type is only used here. Is there a need to have this enum in the future that is not obvious in this PR?

2024-05-22 19:42 UTC, owencraston commented on app/core/Engine.ts
> +        return type === NETWORK_TYPES.RPC ? rpcUrl : type;
Also this type needs to be properly imported into this file.

2024-05-22 19:55 UTC, owencraston commented on app/store/sagas/index.ts
> +    setParticipateInMetaMetrics,
we should probably make sure that this value and the [METRICS_OPT_IN](https://github.com/MetaMask/metamask-mobile/blob/6c5f55c3407b26f42d270c26cff21883ee0a2e31/app/core/Analytics/MetaMetrics.ts#L178) storage value stay in sync

2024-05-22 19:56 UTC, owencraston commented on app/store/sagas/notifications.ts
> +export function* signIn() {
This `function*` syntax is new to me. what does this do?

2024-05-22 19:57 UTC, owencraston commented on app/store/sagas/notifications.ts
> +export function* signIn() {
Ah I see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*#description

2024-05-22 19:59 UTC, owencraston commented on app/store/sagas/sagas.test.ts
> +    const accounts = ['0x000000000', '0x010101010'];
Lets move these addresses into variables in the test. This is small but it will make it easier to integrate the accounts controller. See [this pr](https://github.com/MetaMask/metamask-mobile/pull/9070) for a reference of why.

2024-05-22 20:03 UTC, owencraston commented on app/util/notifications/hooks/useCreateSession.ts
> +function useCreateSession(): {
I really love the hooks that you have created. I strongly encourage you to write some basic hook tests using [renderHook](https://testing-library.com/docs/react-testing-library/api/#renderhook). This goes for all of the hooks in the new hooks folder. [Here](https://github.com/MetaMask/metamask-mobile/blob/6c5f55c3407b26f42d270c26cff21883ee0a2e31/app/components/hooks/AppConfig/useAppConfig.test.tsx#L41) is an example in the codebase.

2024-05-22 20:06 UTC, owencraston commented on app/util/notifications/hooks/useMetametrics.ts
> +export function useEnableMetametrics(): {
Lets strongly type the return values for these hooks. A good example is the [useAppConfig](https://github.com/MetaMask/metamask-mobile/blob/6c5f55c3407b26f42d270c26cff21883ee0a2e31/app/components/hooks/AppConfig/useAppConfig.tsx#L6-L10) hook.

2024-05-22 20:09 UTC, owencraston commented on app/util/notifications/hooks/useProfileSyncing.ts
> +export interface KeyringType {
can we just use the KeyringTypes from `import { KeyringTypes } from '@metamask/keyring-controller';`?

2024-05-22 20:11 UTC, owencraston commented on app/util/notifications/hooks/useProfileSyncing.ts
> +export interface KeyringType {
This type is widley used across the app and will offer more compatibility with the other controllers.

2024-05-22 20:17 UTC, owencraston commented on app/util/notifications/hooks/useProfileSyncing.ts
> +  label: string;
I am pretty sure that the InternalAccount object has the label (defined as name) under the metadata object.

2024-05-22 20:19 UTC, owencraston commented on app/util/notifications/hooks/useMetametrics.ts
> +export function useEnableMetametrics(): {
This goes for the other hooks in this folder too. Let me know if this seems unreasonable to you.

2024-05-22 21:03 UTC, Jonathansoufer commented on app/core/Engine.ts
> +    const metaMetricsController = new MetaMetricsController({
That's an amazing point. At this stage I'm just replicating what is implemented at the extension side and using the "new" MetaMetrics on two NEW redux actions. In further discussion we can check a proper project to migrate all mobile MetaMetrics  "legacy" to the MetaMetricsController.

2024-05-22 21:08 UTC, Jonathansoufer commented on app/core/Engine.ts
> +        return type === NETWORK_TYPES.RPC ? rpcUrl : type;
just fixed properly importing it. It's only used here indeed. removed them.

2024-05-22 21:12 UTC, Jonathansoufer commented on app/core/Engine.ts
> +      environment: process.env.METAMASK_ENVIRONMENT,
Well, this is also implemented [here](https://github.com/MetaMask/metamask-mobile/blob/feat/notifications-integration-sdk/app/core/Engine.ts#L1378) and used everywhere within the app through the call of `const providerConfig = useSelector(selectProviderConfig);`. What do you advice?

2024-05-22 21:19 UTC, Jonathansoufer commented on app/store/sagas/sagas.test.ts
> +    const accounts = ['0x000000000', '0x010101010'];
Excellent point. Changed.

2024-05-22 21:21 UTC, Jonathansoufer commented on app/util/notifications/hooks/useProfileSyncing.ts
> +export interface KeyringType {
yes we can! :)

2024-05-23 14:15 UTC, Jonathansoufer commented on app/util/notifications/hooks/useCreateSession.ts
> +function useCreateSession(): {
I did this already [here](https://github.com/MetaMask/metamask-mobile/blob/6c5f55c3407b26f42d270c26cff21883ee0a2e31/app/util/notifications/hooks/index.test.ts). Is there any other approach you're suggesting?

2024-05-23 14:54 UTC, Jonathansoufer commented on app/util/notifications/hooks/useMetametrics.ts
> +export function useEnableMetametrics(): {
Refactored/adjusted.

2024-05-23 15:10 UTC, Jonathansoufer commented on app/util/notifications/hooks/useProfileSyncing.ts
> +  label: string;
That's a good point. On the extension notification's implementation they are using name and label [here](https://github.com/MetaMask/metamask-extension/blob/a262bb2da20a07f73c4e9102a0104548ef2a5f2f/ui/components/multichain/connect-accounts-modal/connect-account-modal.types.ts). So I don't know if on purpose or by mistake. Meanwhile, I'll put the question to the Notification's team.

2024-05-23 15:39 UTC, Jonathansoufer commented on app/store/sagas/index.ts
> +    setParticipateInMetaMetrics,
addressed.

2024-05-28 21:06 UTC, owencraston commented on app/core/Engine.ts
> +      environment: process.env.METAMASK_ENVIRONMENT,
I was referring to `process.env.METAMASK_ENVIRONMENT`

2024-05-28 21:06 UTC, owencraston commented on app/core/Engine.ts
> +      environment: process.env.METAMASK_ENVIRONMENT,
If its too much trouble than its okay.

2024-05-28 21:19 UTC, owencraston commented on app/util/notifications/hooks/useProfileSyncing.ts
> +  label: string;
I can confirm that the account name (same as label) is already available on the InternalAccounts object. In my opinion we should rely on this object as much as possible for accounts related work. The balance will need to be added but we can get the label from metadata. The type is also available on this interface but it has support for non evm account type so if we want to limit it to only evm we can use `KeyringType`

2024-06-12 15:47 UTC, Cal-L commented on app/util/notifications/hooks/useMetametrics.ts
We already have a `useMetrics` hook. It seems like this can be merged with that instead of creating a new one

2024-06-12 15:47 UTC, Cal-L requested changes
Please write unit tests of all of the new hooks that are created

2024-06-18 23:16 UTC, tommasini commented on app/actions/notification/pushNotifications.ts
> +import notificationsAction from './helpers/constants';
I'm thinking, if we have the time, should we refactor to use the slice pattern instead with redux tool kit?

2024-06-18 23:17 UTC, tommasini commented on app/util/notifications/hooks/useCreateSession.ts
> +          e instanceof Error ? e.message : (JSON.stringify(e ?? '') as any);
why as any?

2024-06-18 23:19 UTC, tommasini commented on app/components/UI/Notification/List/index.tsx
> +    (item: any) => {
Can we type the item?

2024-06-18 23:19 UTC, tommasini commented on app/components/UI/Notification/List/index.tsx
> +    (props: any) => (
Why any?

2024-06-18 23:25 UTC, tommasini requested changes

2024-06-18 23:25 UTC, tommasini commented on app/components/Views/Settings/NotificationsSettings/NotificationOptionToggle/index.tsx
> +  icon?: any;
Why any?

2024-06-18 23:25 UTC, tommasini commented on app/reducers/pushNotifications/index.ts
> +const pushNotificationsReducer = (action: any, state = initialState) => {
The slice pattern with redux tool kit I think it would be better!

2024-06-18 23:25 UTC, tommasini commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
why any?

2024-06-18 23:25 UTC, tommasini commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
Same as above

2024-06-18 23:25 UTC, tommasini commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
Same as above

2024-06-18 23:25 UTC, tommasini commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
Same as above

2024-06-18 23:25 UTC, tommasini commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
same as above

2024-06-18 23:25 UTC, tommasini commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
same as aboce

2024-06-18 23:25 UTC, tommasini commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
same

2024-06-18 23:25 UTC, tommasini commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
I will stop here but could we remove the anys from all this new file?

2024-06-18 23:25 UTC, tommasini commented on app/util/notifications/hooks/useMetametrics.ts
> +  const [error, setError] = useState<string | null>(null);
I'm not sure but, could this be initialised as undefined and typed only as a string?
```suggestion
  const [error, setError] = useState<string>();
```

2024-06-18 23:25 UTC, tommasini commented on app/util/notifications/hooks/useMetametrics.ts
> +      Logger.error(e as any);
Why any here?

2024-06-18 23:25 UTC, tommasini commented on app/util/notifications/hooks/useNotifications.ts
> +    } catch (e: any) {
Could we replace the any?

2024-06-18 23:25 UTC, tommasini commented on app/util/notifications/hooks/useNotifications.ts
> +      return data as unknown as Notification[];
Hmm why do we type the return here? We could type at the name function level as `Notification[]` right?

2024-06-19 10:25 UTC, Jonathansoufer commented on app/components/UI/Notification/List/index.tsx
> +    (item: any) => {
Good catch. Typed.

2024-06-19 10:52 UTC, Jonathansoufer commented on app/reducers/pushNotifications/index.ts
> +const pushNotificationsReducer = (action: any, state = initialState) => {
Unfortunately as stated before, we can't switch patterns at this stage anymore.

2024-06-19 11:09 UTC, Jonathansoufer commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
So all errors WITHIN the app have been handled like that due the typescript rule: `Catch clause variable type annotation must be 'any' or 'unknown' if specified. ts(1196)`. Nevertheless, I think we can take this as an opportunity to improve thanks for your inquire. So, I created a utility to handle errors on try...catch blocks while using typescript. We can extend this util later on to handle additional use cases we may identify.

2024-06-19 11:10 UTC, Jonathansoufer commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
Resolved/Fixed as stated above.

2024-06-19 11:10 UTC, Jonathansoufer commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
Resolved/Fixed as stated above.

2024-06-19 11:10 UTC, Jonathansoufer commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
Resolved/Fixed as stated above.

2024-06-19 11:16 UTC, Jonathansoufer commented on app/util/notifications/hooks/useNotifications.ts
> +    } catch (e: any) {
Yes we can. using the same approach with the new `getErrorMessage` utility. ❤️

2024-06-19 11:16 UTC, Jonathansoufer commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
Resolved/Fixed as stated above.

2024-06-19 11:17 UTC, Jonathansoufer commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
Resolved/Fixed as stated above.

2024-06-19 11:17 UTC, Jonathansoufer commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
Resolved/Fixed as stated above.

2024-06-19 11:17 UTC, Jonathansoufer commented on app/store/sagas/notifications.ts
> +  } catch (error: any) {
Resolved/Fixed as stated above.

2024-06-19 12:59 UTC, Jonathansoufer commented on app/util/notifications/hooks/useMetametrics.ts
> +  const [error, setError] = useState<string | null>(null);
Addressed

2024-06-19 12:59 UTC, Jonathansoufer commented on app/util/notifications/hooks/useMetametrics.ts
> +      Logger.error(e as any);
addressed

2024-06-19 12:59 UTC, Jonathansoufer commented on app/util/notifications/hooks/useNotifications.ts
> +      return data as unknown as Notification[];
addressed

2024-06-19 17:48 UTC, Jonathansoufer commented on app/util/notifications/hooks/useCreateSession.ts
> +          e instanceof Error ? e.message : (JSON.stringify(e ?? '') as any);
fixed.

2024-06-19 18:47 UTC, tommasini commented on app/util/notifications/hooks/useNotifications.ts
> +      return data as unknown as Notification[];
Thanks! Why do we need the `as unknown` is because there is a compatibility error between the data returned by the dispatch and the :Notification[] | undefined return typed function?

2024-06-19 19:06 UTC, Jonathansoufer commented on app/util/notifications/hooks/useNotifications.ts
> +      return data as unknown as Notification[];
we don't. good catch. Fixed.

2024-06-19 19:50 UTC, tommasini commented on app/reducers/pushNotifications/index.ts
> +const pushNotificationsReducer = (action: any, state = initialState) => {
Could we type this `action:any` ?

2024-06-19 20:41 UTC, Cal-L reviewed
Left comments

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/useNotifications.ts
> +  const disableNotifications = useCallback(() => {
`loading` is technically non functional here since it's not actually waiting for anything to finish. This just results in an extra re-render since loading always switches between true and false.

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/useNotifications.ts
> +  const disableNotifications = useCallback(() => {
To make this functional, we should actually be getting the resolved data from this hook via a selector. The final loading state would then be determined by the data that is returned from that selector. One thing to note is that since there's no guarantee that the data will return in a timely manner, we'll have to set loading back to false after a certain amount of time along with a potential timeout error.

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/useNotifications.ts
> +      try {
Refer to the comment about loading being non functional

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/useNotifications.ts
> +    try {
Refer to the comment about loading being non functional

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/useNotifications.ts
> +      const data = dispatch(fetchAndUpdateMetamaskNotificationsRequest());
`data` doesn't return the result of the dispatch. It returns the dispatch action itself

2024-06-19 20:41 UTC, Cal-L commented on app/store/sagas/index.ts
> +  yield notificationsSagas;
I believe you'll have to fork this

2024-06-19 20:41 UTC, Cal-L commented on app/selectors/pushNotifications/index.tsx
> +export const selectAccountsPresence = createSelector(
use `createDeepEqualSelector` since accounts is a non primitive value

2024-06-19 20:41 UTC, Cal-L commented on app/selectors/pushNotifications/index.tsx
> +export const selectNotificationsList = createSelector(
use createDeepEqualSelector since notifications is a non primitive value

2024-06-19 20:41 UTC, Cal-L commented on app/selectors/pushNotifications/index.tsx
> +  selectPushNotificationsState,
use `selectNotificationsList`

2024-06-19 20:41 UTC, Cal-L commented on app/selectors/pushNotifications/index.tsx
> +  selectPushNotificationsState,
You can probably use `getMetamaskNotificationsUnreadCount`

2024-06-19 20:41 UTC, Cal-L commented on app/store/sagas/notifications.ts
> +// function* setSnapNotificationsEnabled() {
Will this code be resolved prior to this PR being merged?

2024-06-19 20:41 UTC, Cal-L commented on app/util/errorHandling/getErrorMessage.ts
Write unit tests

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/types.ts
> +  error: string | undefined;
```suggestion
  error?: string;
```

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/useNotifications.ts
> +    try {
Refer to the comment about loading being non functional

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/useSwitchNotifications.ts
> +        const data = dispatch(checkAccountsPresenceRequest(accounts));
Refer to the comment about loading being non functional

2024-06-19 20:41 UTC, Cal-L commented on app/components/Views/Notifications/Details/index.tsx
> +    }, 5000);
What is the purpose of this timeout?

2024-06-19 20:41 UTC, Cal-L commented on app/components/Views/Notifications/Details/index.tsx
> +  const markAsRead = useCallback(() => {
This doesn't need `useCallback` since both `markNotificationAsRead` and `notification` doesn't change

2024-06-19 20:41 UTC, Cal-L commented on app/components/Views/Notifications/OptIn/index.tsx
> +      mmStorage.saveLocal(STORAGE_IDS.PUSH_NOTIFICATIONS_PROMPT_COUNT, times);
Move this into a side effect (sagas) via dispatching an action instead

2024-06-19 20:41 UTC, Cal-L commented on app/components/Views/Settings/NotificationsSettings/NotificationOptionToggle/index.tsx
> +    await onChange([address], !originalValue);
`onChange` and `listNotifications` seems like it can be combined within the same hook, which exposes both the new notifications data as well as the onChange handler.

2024-06-19 20:41 UTC, Cal-L commented on app/util/notifications/hooks/useSwitchNotifications.ts
> +        const data = dispatch(checkAccountsPresenceRequest(accounts));
This returns the action, not the data

2024-06-19 20:41 UTC, Cal-L commented on app/components/Views/Settings/NotificationsSettings/NotificationOptionToggle/index.tsx
> +      const fetchedData = switchAccountNotifications([address]);
I don't believe this returns the action, not the data

2024-06-19 20:41 UTC, Cal-L commented on app/components/Views/Settings/NotificationsSettings/index.tsx
> +  }, [accounts, addresses, switchAccountNotifications]);
Do not need `accounts` in deps array

2024-06-19 20:41 UTC, Cal-L commented on app/components/Views/Settings/NotificationsSettings/index.tsx
> +  const addresses = accounts.map((account) => account.address);
Put this in a `useCallback` since it will recalculate on every re-render

2024-06-19 20:41 UTC, Cal-L commented on app/components/Views/Settings/NotificationsSettings/index.tsx
> +          disabled={!isMetamaskNotificationsEnabled}
Is this mean to be interactable regardless of `isMetamaskNotificationsEnabled`? Once `isMetamaskNotificationsEnabled` is false, users would not be able to interact with the toggle

2024-06-19 20:41 UTC, Cal-L commented on app/store/sagas/notifications.ts
> +  // setSnapNotificationsEnabledFailure,
Are these still needed?

2024-06-19 20:52 UTC, Jonathansoufer commented on app/util/notifications/hooks/useMetametrics.ts
This will be implemented as a separated PR after Notifications rollout since it required deeper discussions.

2024-06-19 20:53 UTC, Jonathansoufer commented on app/reducers/pushNotifications/index.ts
> +const pushNotificationsReducer = (action: any, state = initialState) => {
Done already.

2024-06-19 20:55 UTC, Jonathansoufer commented on app/components/UI/Notification/List/styles.ts
> +      transform: [{ rotate: '0deg' }],
Exactly, you're absolutely right. This is a "hack" necessary due the type used [here](https://github.com/MetaMask/metamask-mobile/pull/9673/files/b38abf89697babdc914db7f157f1121fc2acac6a#diff-c37182a55c0dd6c73dd94df5d0af0c0b3d2c61150584be571845d54e51b91abcR61)

2024-06-19 21:03 UTC, Jonathansoufer commented on app/components/Views/Settings/NotificationsSettings/index.tsx
> +  }, [accounts, addresses, switchAccountNotifications]);
fixed.

2024-06-19 21:05 UTC, Jonathansoufer commented on app/components/Views/Settings/NotificationsSettings/index.tsx
> +  const addresses = accounts.map((account) => account.address);
Implemented

2024-06-19 21:08 UTC, Jonathansoufer commented on app/components/Views/Settings/NotificationsSettings/index.tsx
> +          disabled={!isMetamaskNotificationsEnabled}
Yes, that was the way to avoid toggle animation happening before resolving `requestPushNotificationsPermission`. It was one request/suggestion made by you actually.

2024-06-19 21:09 UTC, Jonathansoufer commented on app/store/sagas/notifications.ts
> +  // setSnapNotificationsEnabledFailure,
This method is not implemented in current version of NotificationServicesController but was part of the initial "blind" development while controllers weren't ready. Left as comment but can handle differently. Perhaps as an issue?

2024-06-19 21:10 UTC, Jonathansoufer commented on app/components/UI/Notification/List/styles.ts
> +      aspectRatio: undefined,
Same explanation as above. Need to be explicit due the type of TabBarProps<DefaultTabBarProps>

2024-06-19 21:11 UTC, Jonathansoufer commented on app/components/Views/Settings/NotificationsSettings/NotificationOptionToggle/index.tsx
> +  data?: UseSwitchAccountNotificationsData | undefined;
Fixed.

2024-06-19 21:14 UTC, Jonathansoufer commented on app/selectors/pushNotifications/index.tsx
> +export const selectAccountsPresence = createSelector(
Fixed.

2024-06-19 21:18 UTC, Jonathansoufer commented on app/selectors/pushNotifications/index.tsx
> +export const selectNotificationsList = createSelector(
fixed.

2024-06-19 21:22 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/index.tsx
> +    }, 5000);
We wanna mark an Notification automatically as read after 5secs.

2024-06-19 21:23 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/index.tsx
> +  const markAsRead = useCallback(() => {
Good catch. Fixed.

2024-06-19 21:36 UTC, Jonathansoufer commented on app/components/Views/Settings/NotificationsSettings/NotificationOptionToggle/index.tsx
> +      const fetchedData = switchAccountNotifications([address]);
Fixed.

2024-06-19 22:27 UTC, Cal-L requested changes
Please fully fill in the PR description and provide videos/screenshots showing the tested flows.

2024-06-21 07:40 UTC, Cal-L commented on app/components/Views/Settings/NotificationsSettings/index.tsx
> +          disabled={!isMetamaskNotificationsEnabled}
That makes sense for the `value` prop. I was referring to `disabled={!isMetamaskNotificationsEnabled}`, where the value indicates that the toggle would permanently disabled once the value is false. We wouldn't be able to toggle it back on.

2024-06-21 07:40 UTC, Cal-L commented on app/components/Views/Notifications/Details/index.tsx
> +    }, 5000);
What's the reason for not marking it as read immediately after it's viewed? The notification would be marked read regardless of time. This seems like an unnecessary delay?

2024-06-21 07:58 UTC, Cal-L commented on app/components/UI/Notification/List/styles.ts
> +      transform: [{ rotate: '0deg' }],
To fix this, bump to `"@types/react-native": "^0.70.13"` and in yarn.lock, ensure all versions of @types/react-native is resolving to the same version

`"@types/react-native@*", "@types/react-native@^0.70","@types/react-native@^0.70.13":
  version "0.70.13"
  resolved "https://registry.yarnpkg.com/@types/react-native/-/react-native-0.70.13.tgz#a38a1378e68dc25fe5911b09c49b8afffe191316"
  integrity sha512-VnC/ny8Eynk3fvY4cnNKXpo/0zUhA2gO64RX51yzVofblOP6TR6jciga0kIjI4c+2eUyWNGrahmiolNm+QU6Cw==
  dependencies:
    "@types/react" "*"`

2024-06-21 10:16 UTC, Jonathansoufer commented on app/components/UI/Notification/List/styles.ts
> +      transform: [{ rotate: '0deg' }],
Good one! Fixed.

2024-06-21 10:18 UTC, Jonathansoufer commented on app/components/Views/Notifications/Details/index.tsx
> +    }, 5000);
Okay, agreed. removed  the unnecessary delay.

2024-06-28 11:26 UTC, Prithpal-Sooriya commented
I have read the CLA Document and I hereby sign the CLA

2024-07-02 15:43 UTC, brianacnguyen approved these changes, later dismissed

2024-07-11 19:51 UTC, Cal-L reviewed
Left comments

2024-07-11 19:51 UTC, Cal-L commented on app/util/notifications/hooks/useSwitchNotifications.ts
> +        const data = dispatch(checkAccountsPresenceRequest(accounts));
Loading is still non functional ATM and will cause unnecessary re-renders. Same comment applies for other areas with the same previous comment.

2024-07-11 19:51 UTC, Cal-L commented on app/util/notifications/hooks/useNotifications.ts
> +      return data as unknown as Notification[];
This is still being type casted as unknown and the types do not match because dispatch returns only the action creator.

2024-07-11 19:59 UTC, Cal-L commented on ios/Podfile.lock
> +  boost: 7dcd2de282d72e344012f7d6564d024930a6a440
If you update your pod spec repo, pull from main, and re-run yarn setup, does this go away?

2024-07-11 23:19 UTC, Cal-L commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.tsx
> +        name={iconName ?? IconName.Sparkle}
Since this component is a DS component, it probably shouldn't have a hardcoded sparkle icon as a fallback unless that's expected everywhere else. Is that the case or could we move this fallback to where the Badge is consumed?

2024-07-12 08:41 UTC, Jonathansoufer commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.tsx
> +        name={iconName ?? IconName.Sparkle}
That's the case since this comp will be used mainly on Notifications List items.

2024-07-12 09:46 UTC, Jonathansoufer commented on ios/Podfile.lock
> +  boost: 7dcd2de282d72e344012f7d6564d024930a6a440
Rolled back.

2024-07-23 05:17 UTC, brianacnguyen commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.stories.tsx
> +      defaultValue: SAMPLE_BADGENOTIFICATIONS_PROPS.iconName,
Can you remove these changes? These changes are being fixed on in this PR 
https://github.com/MetaMask/metamask-mobile/pull/10307

2024-07-23 05:19 UTC, brianacnguyen commented on app/component-library/components/Badges/Badge/variants/BadgeNotifications/BadgeNotifications.tsx
> +        name={iconName ?? IconName.Sparkle}
can you put the default icon by the props and just use iconName?

2024-07-23 05:20 UTC, brianacnguyen requested changes
Requested changes for BadgeNotifications

2024-07-29 13:53 UTC, closed without merging