feat: adds "data collection for marketing" toggles
MetaMask/metamask-mobile pull request #9687
Opened 2024-05-20 14:52 UTC by jonybur

…ask/metamask-mobile into jb-opt-in-metrics

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-05-21 17:47 UTC, EtherWizard33 reviewed
as an existing wallet, a bottom sheet show up, when I click 'Agree', and go to the marketing setting the switch is off an expected to be on since 'Agree' was clicked.

![agreed-but-marketing-toggle-is-off](https://github.com/MetaMask/metamask-mobile/assets/165834542/d1c692e2-0ae9-45c8-bfc5-e6dd92a992ed)

2024-05-21 20:02 UTC, EtherWizard33 reviewed
I already discussed it with Jony, about the scenario showing one metrics screen + later a bottom sheet, it is that that it is because it's the legacy onboarding, I still wanted to keep a recording of it incase this scenario needs to be viewed/reviewed
<div>
    <a href="https://www.loom.com/share/edd5ae375b8443de9c526592cd6a81c2">
      <p>Simulator - iPad (10th generation) - 21 May 2024 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/edd5ae375b8443de9c526592cd6a81c2">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/edd5ae375b8443de9c526592cd6a81c2-with-play.gif">
    </a>
  </div>

2024-05-22 15:23 UTC, jonybur commented
@eriknson Just confirmed that this will show after the new privacy policy is rolled out, so the legacy onboarding scenario won't be an issue

2024-05-22 15:57 UTC, jonybur commented
@EtherWizard33 The issue with the toast should be fixed now

2024-05-23 15:57 UTC, EtherWizard33 approved these changes, later dismissed
LGTM

2024-05-23 15:59 UTC, darkwing approved these changes, later dismissed
Looks good to me, just one nit!

2024-05-23 15:59 UTC, darkwing commented on app/components/UI/OptinMetrics/index.js
> +        });
Nit: Does `traits` need to be added via `addTraitsToUser` *and* on line 361?

2024-05-23 16:45 UTC, jonybur commented on app/components/UI/OptinMetrics/index.js
> +        });
Yes, these are two different methods. The `addTraitsToUser` affects the segment configuration, and the `trackEvent` pings Segment with the tracking event.

2024-05-23 18:06 UTC, darkwing approved these changes, later dismissed

2024-05-23 19:05 UTC, EtherWizard33 submitted a review, later dismissed

2024-05-24 10:02 UTC, tommasini requested changes
Heyy, good work! Left some comments

2024-05-24 10:02 UTC, tommasini commented on app/actions/security/state.ts
> +  dataCollectionForMarketing: boolean | null;
I think if we do not want to follow the pattern of creating another variable to tell us if the collection modal allowance was already answered, we should document properly that the null represents the modal not being shown to the end user yet! Although I would say I prefer to separate both responsibilities splitter and clear on the codebase

2024-05-24 11:17 UTC, jonybur commented on app/reducers/security/index.ts
> +  dataCollectionForMarketing: null,
Not really. `null` is if the value has not been set yet, which is different from having it to `false`.

2024-05-24 11:17 UTC, jonybur commented on app/actions/security/state.ts
> +  dataCollectionForMarketing: boolean | null;
Added a comment

2024-05-25 17:28 UTC, EtherWizard33 submitted a review, later dismissed

2024-05-25 19:28 UTC, tommasini requested changes
Everything looks good, but spotted an "any" insertion, and we should avoid it at all cost.

Left also some nit picks coments and a comment with a question

2024-05-25 19:28 UTC, tommasini commented on app/components/Views/DataCollectionModal/index.tsx
> +    testID: 'accept-button',
Nit: Can we move this to a constante and rename it so we know this is the accept button of data collection modal component?

Something like `collection-modal-accept-button`? Wdyt?

2024-05-25 19:28 UTC, tommasini commented on app/components/Views/DataCollectionModal/index.tsx
> +          testID="icon-warning"
Nit: Can we move the test id to a constant?

2024-05-25 19:28 UTC, tommasini commented on app/components/Views/ExperienceEnhancerModal/index.tsx
> +    testID: 'cancel-button',
Nit: Can we move the test id to a constant?

2024-05-25 19:28 UTC, tommasini commented on app/components/Views/ExperienceEnhancerModal/index.tsx
> +            testID="link-button"
Nit: Can we move the test id to a constant?

2024-05-25 19:28 UTC, tommasini commented on app/components/Views/ExperienceEnhancerModal/index.tsx
> +    testID: 'accept-button',
Nit: Can we move the test id to a constant?

2024-05-25 19:28 UTC, tommasini commented on app/components/Views/ExperienceEnhancerModal/index.tsx
> +    <BottomSheet ref={bottomSheetRef} testID="bottom-sheet">
Nit: Can we move the test id to a constant?

2024-05-25 19:28 UTC, tommasini commented on app/components/Views/ExperienceEnhancerModal/index.tsx
> +          <Text style={styles.line} testID="bullet1">
Nit: Can we move the test id to a constant?

2024-05-25 19:28 UTC, tommasini commented on app/components/Views/ExperienceEnhancerModal/index.test.tsx
> +    const cancelButton = getByTestId('cancel-button');
Nit: Can we add the constant created here?

2024-05-25 19:28 UTC, tommasini commented on app/components/Views/Settings/SecuritySettings/SecuritySettings.tsx
> +      if (isDataCollectionForMarketingEnabled) {
Just to confirm, if the `isDataCollectionForMarketingEnabled` value is null, we do not want it to be set to false? 
If it's not possible for the variable to be null at this point, would we need the conditition to check if its true?

2024-05-25 19:28 UTC, tommasini commented on app/components/Views/Wallet/index.tsx
> +    (state: any) => state.security.dataCollectionForMarketing,
We shouldn't use any, if possible we should create create the type, or we can say that its an expected error if it will be address soon

Any remove any type safet that we get from using typescript

I believe we have a RootState with the types defined, could you update it to have this new variable? 🙏🏼

2024-05-25 23:41 UTC, EtherWizard33 commented on app/components/Views/Wallet/index.tsx
> +    (state: any) => state.security.dataCollectionForMarketing,
done, marking as resolve

2024-05-25 23:41 UTC, EtherWizard33 commented on app/components/Views/Settings/SecuritySettings/SecuritySettings.tsx
> +      if (isDataCollectionForMarketingEnabled) {
done, marking as resolve

2024-05-25 23:41 UTC, EtherWizard33 commented on app/components/Views/ExperienceEnhancerModal/index.test.tsx
> +    const cancelButton = getByTestId('cancel-button');
done, marking as resolve

2024-05-25 23:41 UTC, EtherWizard33 commented on app/components/Views/ExperienceEnhancerModal/index.tsx
> +    testID: 'cancel-button',
done, marking as resolve

2024-05-25 23:41 UTC, EtherWizard33 commented on app/components/Views/ExperienceEnhancerModal/index.tsx
> +    <BottomSheet ref={bottomSheetRef} testID="bottom-sheet">
done, marking as resolve

2024-05-25 23:42 UTC, EtherWizard33 commented on app/components/Views/ExperienceEnhancerModal/index.tsx
> +            testID="link-button"
done, marking as resolve

2024-05-25 23:42 UTC, EtherWizard33 commented on app/components/Views/ExperienceEnhancerModal/index.tsx
> +          <Text style={styles.line} testID="bullet1">
done, marking as resolve

2024-05-25 23:46 UTC, EtherWizard33 commented on app/components/Views/DataCollectionModal/index.tsx
> +    testID: 'accept-button',
done, marking as resolved

2024-05-25 23:46 UTC, EtherWizard33 commented on app/components/Views/DataCollectionModal/index.tsx
> +          testID="icon-warning"
done, marking as resolve

2024-05-25 23:46 UTC, EtherWizard33 commented on app/components/Views/ExperienceEnhancerModal/index.tsx
> +    testID: 'accept-button',
done, marking as resolved

2024-05-26 09:58 UTC, EtherWizard33 approved these changes, later dismissed

2024-05-27 12:19 UTC, tommasini commented on app/components/Views/ExperienceEnhancerModal/index.tsx
> +    <BottomSheet ref={bottomSheetRef} testID="bottom-sheet">
This still appears to me as hardcoded

2024-05-27 12:24 UTC, tommasini submitted a review, later dismissed
LGTM! Just seem that two hardcoded test ids were missing

2024-05-27 14:31 UTC, cortisiko requested changes, later dismissed
Small feedback @EtherWizard33

2024-05-27 14:31 UTC, cortisiko commented on app/components/Views/DataCollectionModal/index.constants.ts
> +export default {
can the test IDs go into the e2e/selectors folder for this particular modal? this keeps all the testIDs in a centralized location

2024-05-27 14:31 UTC, cortisiko commented on app/components/Views/ExperienceEnhancerModal/index.constants.ts
> +export default {
can the test IDs go into the e2e/selectors folder for this particular modal? this keeps all the testIDs in a centralized location

2024-05-27 17:14 UTC, EtherWizard33 commented on app/components/Views/DataCollectionModal/index.constants.ts
> +export default {
Hey Curtis, yes you are right, this is now done, marking as resolved.

2024-05-27 17:14 UTC, EtherWizard33 commented on app/components/Views/ExperienceEnhancerModal/index.constants.ts
> +export default {
Hey Curtis, yes you are right, this is now done, marking as resolved.

2024-05-28 11:43 UTC, EtherWizard33 approved these changes, later dismissed

2024-06-03 14:47 UTC, EtherWizard33 approved these changes, later dismissed

2024-06-03 16:10 UTC, tommasini commented
Can we update the initial-background-state and fixture-builder files to have this new data?

2024-06-03 16:16 UTC, tommasini commented on app/components/Views/Settings/SecuritySettings/SecuritySettings.tsx
> +      if (isDataCollectionForMarketingEnabled === true) {
```suggestion
      if (isDataCollectionForMarketingEnabled) {
```

2024-06-03 16:35 UTC, tommasini approved these changes
LGTM!

2024-06-03 18:15 UTC, EtherWizard33 approved these changes

2024-06-03 22:11 UTC, salimtb approved these changes

2024-06-04 11:26 UTC, merged

2024-06-04 11:56 UTC, hesterbruikman commented
Removed the auto-added 7.25.0 label as this is planned for a hotfix based off of 7.24.0 (more on Slack). cc @jonybur @darkwing @Cal-L @NicolasMassart