chore: migrate to mm webview npm registry
MetaMask/metamask-mobile pull request #9695
Opened 2024-05-20 23:18 UTC by tommasini

## **Description**

This PR migrates `react-native-webview` to `@metamask/react-native-webview` on the webview upgrade branch branch

This is the [PR](https://github.com/MetaMask/metamask-mobile/pull/7759) of the main webview upgrade branch.

Currently with this error:
![image](https://github.com/MetaMask/metamask-mobile/assets/46944231/92f4678d-dfbe-4651-b758-62f44be2cbaa)

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-05-21 00:54 UTC, legobeat commented
Failing test addressed [here](https://github.com/MetaMask/react-native-animated-fox/pull/5#issuecomment-2121418420).

2024-05-21 15:41 UTC, brianacnguyen approved these changes

2024-05-23 08:51 UTC, legobeat requested changes, later dismissed

2024-05-23 08:51 UTC, legobeat commented on app/components/Base/AnimatedFox.js
> +        style={{ flex: 1 }}
[This is failing lint](https://github.com/MetaMask/metamask-mobile/actions/runs/9200230452/job/25306515600?pr=9695):

```
 /home/runner/work/metamask-mobile/metamask-mobile/app/components/Base/AnimatedFox.js
Error:   60:16  error  Inline style: { flex: 1 }  react-native/no-inline-styles
```

2024-05-23 09:52 UTC, legobeat commented on app/components/Base/AnimatedFox.js
> +        style={{ flex: 1 }}
```suggestion
        // eslint-disable-next-line react-native/no-inline-styles
        style={{ flex: 1 }}
```
I guess the right thing to do is to add a proper style declaration, though.

2024-05-23 12:51 UTC, tommasini commented on app/components/Base/AnimatedFox.js
> +        style={{ flex: 1 }}
Added a new file with the component all refactored: https://github.com/MetaMask/metamask-mobile/pull/9695/commits/070ebc43e366f9633398b7c88fa2257dfb2c3aa7

2024-05-23 17:55 UTC, sethkfman approved these changes
LGTM

2024-05-23 20:17 UTC, legobeat commented
> LGTM

@sethkfman A lot of failing Android E2E tests, though...? https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/895704f8-84bc-4e71-afd1-3348764f2211

2024-05-23 22:05 UTC, tommasini commented
They are failing on the main update branch as well, the last e2e smoke passing was April third: https://github.com/MetaMask/metamask-mobile/pull/7759/commits

So there is 12 commits to review

2024-06-03 11:11 UTC, merged

2024-06-03 11:12 UTC, jpcloureiro commented
We'll continue with the E2E work in #7759 as discussed with @tommasini today

cc @cortisiko @legobeat