chore: remove unnecessary patch imports and change the patch branch name
MetaMask/metamask-mobile pull request #9712
Opened 2024-05-22 09:49 UTC by OGPoyraz

## **Description**

This PR removes unnecessary imports from patch file and renames the patch name. 

## **Related issues**

Fixes:

## **Manual testing steps**

N/A

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-05-22 11:15 UTC, tommasini requested changes
It is intended to be removing this amount of files from the patch?

2024-05-22 11:28 UTC, tommasini commented on patches/@metamask+transaction-controller+13.0.0.patch
> -diff --git a/node_modules/@metamask/transaction-controller/dist/helpers/EtherscanRemoteTransactionSource.d.ts b/node_modules/@metamask/transaction-controller/dist/helpers/EtherscanRemoteTransactionSo
For example here we are removing the .d.ts of the EtherscanRemoteTransactionSource file, was this expected?

2024-05-22 11:43 UTC, tommasini commented on patches/@metamask+transaction-controller+13.0.0.patch
> -diff --git a/node_modules/@metamask/transaction-controller/dist/helpers/EtherscanRemoteTransactionSource.d.ts b/node_modules/@metamask/transaction-controller/dist/helpers/EtherscanRemoteTransactionSo
After talking with @OGPoyraz understood that this is file is not being used on this directory, instead this file is actually leaving on the source folder and this was just not updated

2024-05-22 11:59 UTC, tommasini approved these changes
Amazing cleanup @OGPoyraz This looks awesome!

Just add manual steps testing for the release qa, a video showing a transactions and dapp transaction working, and the core branch that it was used to generate the patch and we are good to merge

2024-05-22 12:07 UTC, OGPoyraz commented
> Amazing cleanup @OGPoyraz This looks awesome!
> 
> Just add manual steps testing for the release qa, a video showing a transactions and dapp transaction working, and the core branch that it was used to generate the patch and we are good to merge

Requested a regression from @sleepytanya

2024-05-22 12:09 UTC, jpuri approved these changes

2024-05-22 12:33 UTC, vinistevam approved these changes

2024-05-23 05:19 UTC, sleepytanya commented
QA build [Bitrise](https://app.bitrise.io/build/38bb3f57-71c6-46a8-b81f-eba4562d83ee?tab=artifacts)

- [x]  Transactions - send native token origin MM
- [x]  Transactions - send native token origin dapp
- [x]  Transactions - send ERC20 token origin MM
- [x]  Transactions - send ERC20 token origin dapp
- [x]  Transactions - send ERC721 token origin MM
- [x]  Transactions - send ERC721 token origin dapp
- [x]  Transactions - speed up transaction
- [x]  Transactions - cancel transaction
- [x]  Speed up cancellation
- [x]  Tokens - import ERC20 token origin MM
- [x]  Tokens - import ERC20 token origin dapp
- [x]  Tokens - import ERC721 token origin MM
- [x]  Tokens - import ERC721 token origin dapp 
- [x]  Tokens - import ERC1155 token origin MM
- [x]  Tokens - import ERC1155 token origin dapp
- [x]  Tokens - ERC1155 transfer origin MM
- [x]  Tokens - ERC1155 batch transfer
- [x]  Tokens - approve ERC1155 token
- [x]  Tokens - approve ERC20 token
- [x]  Tokens - approve ERC721 token
- [x]  ENS - name resolution
- [x]  Gas fee - EIP-1559 gas
- [x]  Gas fee - legacy gas
- [x]  Sign - ETH sign
- [x]  Sign - personal sign
- [x]  Sign - sign in with Ethereum
- [x]  Sign - sign typed with data (v3 and v4)
- [x]  Swap - swap tokens
- [x]  Incoming transactions history
- [x]  Custom nonce
- [x]  Cancel transaction using custom nonce
- [x]  Stuck multiple transactions (cancel / speed up)
- [x]  PPOM

2024-05-23 07:52 UTC, merged