test: import tokens detected
MetaMask/metamask-mobile pull request #9714
Opened 2024-05-22 13:44 UTC by chrisleewilcox

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-05-29 21:53 UTC, cortisiko requested changes, later dismissed
left some early feedback for ya @chrisleewilcox

2024-05-29 21:53 UTC, cortisiko commented on e2e/pages/assets/DetectedTokensView.js
> +import { DetectedTokensSelectorIDs } from '../../selectors/assets/DetectedTokensView.selectors';
How about creating a "wallet" folder and placing this file there? We also want to put all the other wallet-specific files (WalletView.js, ImportTokens, AddCustomTokenView, ConfirmAddAsset, etc.) in that folder. We essentially want all pages related to the wallet view to be in that folder.

2024-05-29 21:53 UTC, cortisiko commented on e2e/selectors/assets/DetectedTokensView.selectors.js
> +import enContent from '../../../locales/languages/en.json';
Same as my previous comment

2024-05-29 21:53 UTC, cortisiko commented on e2e/selectors/WalletView.selectors.js
> +  WALLET_TOKEN_DETECTION_LINKBUTTON: 'wallet-token-detection-link-button',
Add a `_` in between LINK and BUTTON

2024-06-04 15:13 UTC, cortisiko requested changes
ahhh maybe I wasn't as clear in my previous review. You created a new page called DetectedTokensView, since the entry point to this view lives on the wallet it would make sense having a Wallet Folder and all page objects that relates to the wallet folder lives there. For example: DetectedTokens, WalletView, ImportTokens, etc etc

2024-06-04 19:57 UTC, cortisiko commented on e2e/pages/wallet/DetectedTokensView.js
> +    await TestHelpers.tapByText('Import (1)');
don't use test helper here. Use the gesture class. Also what if you set the testID on the button itself rather than selecting by text? https://github.com/MetaMask/metamask-mobile/blob/main/app/components/Views/DetectedTokens/index.tsx#L236

2024-06-05 21:57 UTC, chrisleewilcox commented on e2e/selectors/wallet/DetectedTokensView.selectors.js
> +};
The import button text is dynamic and wasn't able to find a solid way to verify token count if it change.  This is not ideal implementation but we can revisit.

2024-06-05 21:58 UTC, chrisleewilcox commented on e2e/pages/wallet/DetectedTokensView.js
> +    // await Gestures.tapTextBeginingWith('Import');
Need to revisit using RegExp.

2024-06-05 23:51 UTC, chrisleewilcox commented on e2e/utils/Gestures.js
> +  }
We should revisit since button text is dynamic.

2024-06-05 23:53 UTC, chrisleewilcox commented on e2e/utils/Gestures.js
> +  }
Copy paste from ./e2e/helpers.js

2024-06-05 23:57 UTC, chrisleewilcox commented on e2e/specs/assets/token-detection-import-all.spec.js
The token detection link was not showing when using fixtures.  This was working about a week ago.  Forced to go through onboarding without fixtures.

2024-06-06 00:42 UTC, cortisiko commented on e2e/utils/Gestures.js
> +  }
Ah so the waitAndTap and Tap methods are element agnostic, so there isn't a need to have a method that taps by a specific element.  


for example, 

see how we create an element by ID:
https://github.com/MetaMask/metamask-mobile/blob/main/e2e/pages/Settings/SecurityAndPrivacy/SecurityAndPrivacyView.js#L11 

See how we tap: 
 https://github.com/MetaMask/metamask-mobile/blob/main/e2e/pages/Settings/SecurityAndPrivacy/SecurityAndPrivacyView.js#L74

  
and here

See how we create an element by text: https://github.com/MetaMask/metamask-mobile/blob/main/e2e/pages/Settings/Contacts/AddContactView.js#L25 

And how we tap: https://github.com/MetaMask/metamask-mobile/blob/main/e2e/pages/Settings/Contacts/AddContactView.js#L51

2024-06-06 00:42 UTC, cortisiko commented on e2e/pages/wallet/DetectedTokensView.js
> +    // await Gestures.tapTextBeginingWith('Import');
we can remove this comment for now

2024-06-06 15:07 UTC, cortisiko submitted a review, later dismissed
✅

2024-06-06 20:18 UTC, cortisiko approved these changes

2024-06-06 21:45 UTC, merged