chore: fitness quality gate to only allow TS & TSX files in the app directory
MetaMask/metamask-mobile pull request #9723
Opened 2024-05-22 22:21 UTC by sethkfman

## **Description**

This PR adds a fitness function to fail if a non .ts or .tsx file is added to the app/ directory. 

## **Related issues**

Fixes: https://github.com/orgs/MetaMask/projects/60/views/3?pane=issue&itemId=59597337

## **Manual testing steps**

1. Attempt to push a .js or .jsx file  in the app directory
2. See the fitness function fail
3.

## **Screenshots/Recordings**

NA See unit tests

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-05-23 07:52 UTC, legobeat commented on .github/scripts/fitness-functions/rules/index.ts
> +import { preventJavaScriptFileAdditions } from './javascript-additions';
@sethkfman is there supposed to be a `javascript-additions.ts`..?

2024-05-23 07:53 UTC, legobeat commented on .github/scripts/fitness-functions/common/shared.ts
> +            console.log('PATH', path)
Leftover `console.log`?

2024-05-23 07:54 UTC, legobeat requested changes, later dismissed
https://github.com/MetaMask/metamask-mobile/actions/runs/9199173846/job/25303545010?pr=9723

https://github.com/MetaMask/metamask-mobile/pull/9723/files#r1611184948

2024-05-23 18:37 UTC, sethkfman commented on .github/scripts/fitness-functions/rules/index.ts
> +import { preventJavaScriptFileAdditions } from './javascript-additions';
I missed adding them

2024-05-23 23:02 UTC, sethkfman commented
Troubleshooting fitness function issue

2024-05-31 22:27 UTC, Cal-L reviewed
Left some comments

2024-05-31 22:27 UTC, Cal-L commented on ios/MetaMask.xcodeproj/project.pbxproj
> +				OTHER_LDFLAGS = (
Remove unrelated changes

2024-05-31 22:27 UTC, Cal-L commented on .yarnrc
> +ignore-scripts true
Was this accidentally commited?

2024-05-31 22:39 UTC, sethkfman commented on ios/MetaMask.xcodeproj/project.pbxproj
> +				OTHER_LDFLAGS = (
Removed

2024-05-31 22:39 UTC, sethkfman commented on .yarnrc
> +ignore-scripts true
Fixed

2024-05-31 22:40 UTC, sethkfman commented on .github/scripts/fitness-functions/common/shared.ts
> +            console.log('PATH', path)
removed

2024-06-07 19:38 UTC, Cal-L commented on e2e/helpers copy.js
Was this file committed by accident?

2024-06-10 22:04 UTC, sethkfman commented on e2e/helpers copy.js
removed test files

2024-06-10 23:39 UTC, Cal-L approved these changes
LGTM

2024-06-11 03:02 UTC, merged