feat: remove selectIdentities in favour of selectInternalAccounts
MetaMask/metamask-mobile pull request #9724
Opened 2024-05-22 22:22 UTC by owencraston

## **Description**

## **Related issues**

Fixes: https://github.com/MetaMask/accounts-planning/issues/410

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-06 00:28 UTC, owencraston commented
latest qa build: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/8ec789be-e151-4925-9fce-6b56028def06

2024-06-19 23:42 UTC, gantunesr reviewed
Great to see some refactors as part of this work. Most of my comments are nitpicks

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx
> +        }
What would happen if `accountWithMatchingFromAddress` is falsy? do we need a fallback for that case? I see that in the previous logic the value would be set to the falsy value which doesn't seem correct so this is an improvement

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx
> +        }
Similar observation as my previous comment regarding `accountWithMatchingToAddress` being falsy

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/AccountSelectorList/AccountSelector.test.tsx
> +  it('should render correct account names', async () => {
nit

```suggestion
  it('renders correct account names', async () => {
```

According to our [guidelines](https://github.com/MetaMask/contributor-docs/blob/main/docs/e2e-testing.md#guidelines)

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/DrawerView/index.js
> +  selectedCheckSummedAddress = toChecksumHexAddress(
nit: I think checksum is one word

```suggestion
  selectedChecksummedAddress = toChecksumHexAddress(
```

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/DrawerView/index.js
> +      if (keyring.accounts.includes(this.selectedCheckSummedAddress)) {
```suggestion
      if (keyring.accounts.includes(this.selectedChecksummedAddress)) {
```

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/DrawerView/index.js
> +    const label = getLabelTextByAddress(this.selectedCheckSummedAddress);
```suggestion
    const label = getLabelTextByAddress(this.selectedChecksummedAddress);
```

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/DrawerView/index.js
> +      address !== this.selectedCheckSummedAddress ||
```suggestion
      address !== this.selectedChecksummedAddress ||
```

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/DrawerView/index.js
> +        this.selectedCheckSummedAddress,
```suggestion
        this.selectedChecksummedAddress,
```

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/DrawerView/index.js
> +          address: this.selectedCheckSummedAddress,
```suggestion
          address: this.selectedChecksummedAddress,
```

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/DrawerView/index.js
> +      const url = `${blockExplorer}/address/${this.selectedCheckSummedAddress}`;
```suggestion
      const url = `${blockExplorer}/address/${this.selectedChecksummedAddress}`;
```

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/DrawerView/index.js
> +        this.selectedCheckSummedAddress,
```suggestion
        this.selectedChecksummedAddress,
```

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/DrawerView/index.js
> +      message: this.selectedCheckSummedAddress,
```suggestion
      message: this.selectedChecksummedAddress,
```

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/DrawerView/index.js
> +      address: this.selectedCheckSummedAddress,
```suggestion
      address: this.selectedChecksummedAddress,
```

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/DrawerView/index.js
> +      ...accounts[this.selectedCheckSummedAddress],
```suggestion
      ...accounts[this.selectedChecksummedAddress],
```

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/DrawerView/index.js
> +        renderFromWei(accounts[this.selectedCheckSummedAddress].balance)) ||
```suggestion
      (accounts[this.selectedChecksummedAddress] &&
        renderFromWei(accounts[this.selectedChecksummedAddress].balance)) ||
```

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/DrawerView/index.js
> +                    address={this.selectedCheckSummedAddress}
```suggestion
                    address={this.selectedChecksummedAddress}
```

2024-06-19 23:42 UTC, gantunesr commented on app/components/UI/Ramp/components/Account.tsx
> +    );
Do you think we should check if the `address` value exists (given that's optional) before executing the loop? Just to not compare an entire array with `undefined`

2024-06-19 23:42 UTC, gantunesr commented on app/components/Views/Settings/Contacts/ContactForm/index.js
> +        );
Similar to a previous comment, given that address could be `''` we should check it before executing a loop with the `find` method

2024-06-20 17:27 UTC, owencraston commented on yarn.lock
> +  integrity sha512-trzh6NzBnq8yw5e35f8xe8VTYjqM3NE7bohBtvDVf/dtUer3zYTLK1Ka3DG3p7bdtoaOHZucma6FfVKlQ134pQ==
This was leftover from a previous commit that is no longer needed. I will remove.

2024-06-20 20:10 UTC, owencraston commented on yarn.lock
> +  integrity sha512-trzh6NzBnq8yw5e35f8xe8VTYjqM3NE7bohBtvDVf/dtUer3zYTLK1Ka3DG3p7bdtoaOHZucma6FfVKlQ134pQ==
I was wrong, I needed to include these types for the linter so in my latest commit I explicitly included them in `@types/punycode` in the dev dependancies.

2024-06-20 20:11 UTC, owencraston commented on yarn.lock
> +  integrity sha512-trzh6NzBnq8yw5e35f8xe8VTYjqM3NE7bohBtvDVf/dtUer3zYTLK1Ka3DG3p7bdtoaOHZucma6FfVKlQ134pQ==
<img width="1728" alt="Screenshot 2024-06-20 at 4 06 22 PM" src="https://github.com/MetaMask/metamask-mobile/assets/22918444/8282b528-33d3-4dfb-86f3-8e3d51117d76">

2024-06-20 20:16 UTC, owencraston commented on app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx
> +        }
@jpuri it seems like this component would require an account with matching address. What should we do in this case where we cannot find a match?

2024-06-24 20:57 UTC, tommasini commented on app/util/address/index.ts
>    isHexString,
We can use `isHexString` from @metamask/utils: https://github.com/MetaMask/utils/blob/631d1eb641248da441aa78db6e1530d8e4a3e9a6/src/hex.ts#L30

2024-06-24 21:01 UTC, tommasini commented on app/util/address/index.ts
>      const [address, _] = pathname.split('@');
I'm wondering, if we need to have the unusable variable here

2024-06-24 21:11 UTC, tommasini commented on app/components/Views/confirmations/SendFlow/AddressList/AddressList.tsx
> +            address={account.address}
I think with this change we are showing the address on the UI lower cased and we should show on checksummed format

2024-06-24 21:12 UTC, tommasini commented on app/components/Views/confirmations/SendFlow/AddressList/AddressList.tsx
> +            address={account.address}
Forget I see that AddressElement handles it with this [function](https://github.com/MetaMask/metamask-mobile/blob/2384af6f675f82d3abbf13f3b31f6095922c0ac7/app/util/address/index.js#L84)

2024-06-24 21:15 UTC, tommasini commented on app/components/Views/AccountConnect/AccountConnect.tsx
> +      account.address.toLowerCase(),
Wondering if the toLowerCase() here is needed, since AccountsController already handle the addresses in lower case

Although feel free to resolve to conversation if we feel that maybe be safer than sorry, I'm not against the .toLowerCase()!

2024-06-24 21:24 UTC, owencraston commented on app/components/Views/AccountConnect/AccountConnect.tsx
> +      account.address.toLowerCase(),
I dont think this is needed but since we have been having issues related to the lowercase duplicate addresses I figured being explicit is good. This also shows future maintainers that we are doing address comparisons in lowercase and potentially avoids people comparing checksum/lowercase addresses. I am willing to remove it if needed.

2024-06-24 21:26 UTC, owencraston commented on app/components/Views/confirmations/SendFlow/AddressList/AddressList.tsx
> +            address={account.address}
true, I wrapped it in a `toChecksumHexAddress`

2024-06-24 21:27 UTC, owencraston commented on app/util/address/index.ts
>      const [address, _] = pathname.split('@');
I already changed this file a lot and am trying to minimize the refactors so I am partial to keeping this function as is unless we can easily verify that it works.

2024-06-24 22:06 UTC, tommasini approved these changes
LGTM! Awesome work!

2024-06-24 22:06 UTC, tommasini requested changes
Actually it seems E2E are failing :(

2024-06-25 09:54 UTC, jpuri commented on app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx
> +        }
Since from address is address form which transaction is being made, can you suggest situation in which it will be null ?

2024-06-25 10:14 UTC, jpuri reviewed
I reviewed changes in files owned by confirmations team, those look good to me.

2024-06-25 10:16 UTC, jpuri commented on app/components/Views/confirmations/Send/index.js
> +    newTxMeta.transactionFromName = fromAccount.metadata.name;
It might be more handy to write a selector for above piece of code.

2024-06-25 10:18 UTC, jpuri approved these changes, later dismissed

2024-06-25 15:32 UTC, owencraston commented on app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx
> +        }
Based on a discussion with @jpuri the default case here will be to set the name to the fromAddress if we cannot find a matching address. This should not happen in practice but it is a good to not break the app in the case that it does.

2024-06-25 15:35 UTC, owencraston commented on app/components/UI/AccountFromToInfoCard/AccountFromToInfoCard.tsx
> +        }
same as above, we will default to setting the to account name to the toAddress. This should not happen in practice but at least we have a sane default case.

2024-06-25 15:51 UTC, owencraston commented on app/components/UI/AddressCopy/AddressCopy.tsx
> +    if (selectedInternalAccount?.address) {
The reason for these null checks is that this selector can potentially return undefined. While the state should always be there, there are cases that we have seen in previous PRs where the state is temporarily null during an update and can cause race condition errors as the ui holds on to old references. These null checks allow for the UI to not error out while the state updates.

<img width="718" alt="Screenshot 2024-06-25 at 11 48 04 AM" src="https://github.com/MetaMask/metamask-mobile/assets/22918444/b78aa6b9-19f2-4410-86da-021adc9052ed">

2024-06-25 15:58 UTC, owencraston commented on app/components/Views/confirmations/Send/index.js
> +    newTxMeta.transactionFromName = fromAccount.metadata.name;
Since we can get all the information we need from just one `selectInternalAccounts`, I am hesitant to add an extra state call which will cause re renders.

2024-06-25 16:03 UTC, jpuri approved these changes, later dismissed

2024-06-26 10:11 UTC, nikoferro submitted a review, later dismissed
PR looks good from the swap side, approving this so its not blocked from our side. Just keep in mind E2E tests are failing at the moment

2024-07-02 22:52 UTC, tommasini commented on app/components/UI/AddressCopy/AddressCopy.tsx
> +    if (selectedInternalAccount?.address) {
Thanks for the answer!

2024-07-02 22:54 UTC, tommasini commented on app/components/Views/Settings/Contacts/ContactForm/index.js
> +        memo: contact?.memo || '',
```suggestion
        name: contact?.name ?? '',
        memo: contact?.memo ?? '',
```

not sure if it makes sense but this way we allow the name and memo to be 0 and false

2024-07-02 22:55 UTC, tommasini submitted a review, later dismissed
LGTM!

2024-07-03 15:31 UTC, chrisleewilcox submitted a review, later dismissed
@owencraston @MetaMask/accounts-engineers @MetaMask/account-management please always tests with a hardware wallet accounts.  Account naming issues have been tied to a lack of testing with hardware wallets accounts.  Always tests with multiple account types with names changes including hardware wallet accounts.  Provide a recording confirming tests scenarios work with hardware wallet accounts.


Wallet setup to test all scenarios should be...

- multiple derived accounts
- - at least one with edited name
- multiple imported accounts
- - at least one that is ENS
- multiple hardware wallet accounts
- - at least one with edited name

2024-07-03 15:42 UTC, chrisleewilcox commented
Wallet setup to test all scenarios should be...

- multiple derived accounts
- - at least one with edited name
- multiple imported accounts
- -at least one that is ENS
- multiple hardware wallet accounts
- -at least one with edited name

2024-07-03 16:45 UTC, tommasini approved these changes

2024-07-03 21:06 UTC, owencraston commented
These three issues could potentially be fixed by this PR:
- https://github.com/MetaMask/metamask-mobile/issues/10161
- https://github.com/MetaMask/metamask-mobile/issues/10155
- https://github.com/MetaMask/metamask-mobile/issues/10079

2024-07-03 21:07 UTC, plasmacorral commented
### Accounts Tested:
3 HD accounts (ENS)
2 imported accounts (ENS)
4 QR accounts (custom label)
1 Ledger account

### Devices tested:
- Samsung a515f running Android 12 with security 1/1/2024
- Pixel 5a running Android 14 with security Apr 5, 2024
- iPhone 13 mini running iOS 15.6.1
- iPhone Xs running iOS 17.4.1

### Hardware wallets tested:
LNX running 2.2.3 with Eth App 1.10.4
Keystone v3 with fw1.5.2

### Successful tests:

- Migration from QA build of v7.24.3 to QA build of commit 263856bdeac793469ca7edd8041ff4620d39a2be
  - Accounts and Names persisted 
- Adding accounts
  - HD
  - Imported
  - Ledger
  - QR
- Remove account/Forget device
  - Ledger
  - QR
  - Imported
- Send and confirm screens in send flow
   - Imported and HD accounts display the ENS name in both the account list and send flows **_when they are the sender_**
- Dapp connect accounts shows correct names
- Lock/unlock


### Observations:

**1. Send Flow:**
- `Send to` and `Confirm` screens do not display the ENS name of the recipient address, even when it is shown in the account list.

**2. ENS Names on Hardware Addresses:**
- Ledger and QR accounts that resolve to an ENS address do not have their account names updated in the account list. This issue is also present in production and is not introduced by this PR. I will follow up with a fresh production issue report.

**3. ENS Name Mismatch (Related to Issue 2):**
- For Ledger or QR accounts, if the address resolves to an ENS name and is the sender, the ENS name is shown in the `Send to` and `Confirm` screens, causing a mismatch with the account list where the account name is not updated.

**4. ENS Resolution Delay:**
- When switching between accounts with ENS names, the non-ENS account name is sometimes displayed before the ENS name is resolved. This may be a production issue that I am just noticing today.

2024-07-03 21:58 UTC, owencraston commented
@plasmacorral I went back to version 7.21.0 which was long before any accounts controller changes were added and noticed that the ens resolution in the send flow has been broken for some time. 


https://github.com/MetaMask/metamask-mobile/assets/22918444/c9349672-7202-4d12-9d31-3fc8103eb287

2024-07-03 22:45 UTC, owencraston commented
Tests regarding [[Bug] Hardware wallet account name not reflecting on signing transaction screen #10079](https://github.com/MetaMask/metamask-mobile/issues/10079)

- I have confirmed that this PR addresses this bug

Steps: 
Connect QR/Ledger device on Metamask Mobile
Go to test dapp
Connect using hd wallet
Personal sign using hd wallet
Verify the sign transaction page displays
Expected: Hardware wallet account name to reflect with account list from homepage
Actual: Hardware wallet account name to reflect with account list from homepage

Video

https://github.com/MetaMask/metamask-mobile/assets/22918444/a7c44417-8816-464a-8d4c-e11db1168c36

2024-07-03 22:58 UTC, plasmacorral commented
> These three issues could potentially be fixed by this PR:
> 
> * [[Bug]: All confirmations modals are showing wrong account name #10161](https://github.com/MetaMask/metamask-mobile/issues/10161)
> * [[Bug]: Send to screen showing wrong account names #10155](https://github.com/MetaMask/metamask-mobile/issues/10155)
> * [[Bug] Hardware wallet account name not reflecting on signing transaction screen #10079](https://github.com/MetaMask/metamask-mobile/issues/10079)

These issues are resolved in this PR, and my observations above were also able to be observed in production v7.24.3 and 7.24.4.

2024-07-03 23:31 UTC, SamuelSalas approved these changes
LGTM

2024-07-03 23:33 UTC, merged