fix: display the DApp URL in connect screen for MetaMask IOS-SDK
MetaMask/metamask-mobile pull request #9755
Opened 2024-05-27 11:35 UTC by omridan159

Display the DApp URL in connect screen for MetaMask IOS-SDK

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

https://github.com/MetaMask/metamask-mobile/assets/61094771/4da53e62-d80f-4b09-957b-a19f2775e824

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-05-29 07:10 UTC, abretonc7s requested changes
see comments

2024-05-29 07:10 UTC, abretonc7s commented on app/core/DeeplinkManager/ParseManager/extractURLParams.ts
> +  account?: string; // This is the format => "address@chainId"
should we call this context? Since this is not just an account

2024-05-29 07:10 UTC, abretonc7s commented on app/core/SDKConnect/SDKDeeplinkProtocol/DeeplinkProtocolService.test.ts
> +      // @ts-ignore
why ts-ignore? Can we avoid?

2024-05-29 07:10 UTC, abretonc7s commented on app/core/SDKConnect/SDKDeeplinkProtocol/DeeplinkProtocolService.ts
> +import getDefaultBridgeParams from '../AndroidSDK/getDefaultBridgeParams';
ideally we start to migrate away from default export so 
```
import { getDefaultBridgeParams } 
```
above would be better as we go

2024-05-29 07:10 UTC, abretonc7s commented on app/core/SDKConnect/SDKDeeplinkProtocol/DeeplinkProtocolService.ts
> +        ...connectedAddresses.filter((address) => address !== selectedAddress),
does this work if the addresses have different case? Probably should force lowercase before testing

2024-05-29 07:10 UTC, abretonc7s commented on app/core/SDKConnect/SDKDeeplinkProtocol/DeeplinkProtocolService.ts
> +    const account = params.account.split('@');
this code probably throws an uncatched error if the format is invalid. should have validation first

2024-05-29 07:10 UTC, abretonc7s commented on app/core/SDKConnect/SDKDeeplinkProtocol/DeeplinkProtocolService.ts
> +                    'The selected account or chain has changed. Please try again.',
i18n

2024-05-30 08:17 UTC, elefantel approved these changes, later dismissed
Looks goodd

2024-05-30 15:04 UTC, elefantel approved these changes, later dismissed

2024-05-31 08:51 UTC, andreahaku submitted a review, later dismissed
LGTM

2024-06-03 10:15 UTC, abretonc7s approved these changes

2024-06-04 15:45 UTC, christopherferreira9 commented
Icon and dapp url is fixed.

https://github.com/MetaMask/metamask-mobile/assets/104831203/18818d2b-0f71-4686-be48-9f291e506c9d

2024-06-04 17:54 UTC, merged