chore: Update accounts controller v14
MetaMask/metamask-mobile pull request #9779
Opened 2024-05-29 12:32 UTC by tommasini

## **Description**

This PR updates accounts controller to v^14.

This PR still have typescript issues to solve.

This PR is dependent on the snaps controller update [PR](https://github.com/MetaMask/metamask-mobile/pull/9718)
This PR is dependent on the keyring controller update [PR](https://github.com/MetaMask/metamask-mobile/pull/9570)
## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-05 20:17 UTC, owencraston commented on app/util/test/accountsControllerTestUtils.ts
> -export const MOCK_ACCOUNTS_CONTROLLER_STATE: AccountsControllerState = {
Nitpick: I want to keep these type explicit in case there is an update in the data type that we expect form the package we can find the issue very easily before it fails on CI.

2024-06-05 21:13 UTC, owencraston commented
we should also bump the version of the [keyring-api](https://github.com/MetaMask/keyring-api/releases). I think we will need [a minimum of 6.1.1](https://github.com/MetaMask/core/pull/4262/files#diff-11700fa807e8d925b649057d40f964047063e26926ce62fc5f09210de947dbffR47). This update introduces an extra field on the InternalAccount type of importTime. This will allow us to 100% migrate off of preferences controller.

2024-06-05 21:23 UTC, tommasini commented on app/util/test/accountsControllerTestUtils.ts
> -export const MOCK_ACCOUNTS_CONTROLLER_STATE: AccountsControllerState = {
Reverted <3

2024-06-05 21:25 UTC, owencraston commented on package.json
> +    "@metamask/keyring-api": "^6.0.0",
I believe version 14 of the accounts controller is using `^6.1.1`

2024-06-05 22:22 UTC, tommasini commented on package.json
> +    "@metamask/keyring-api": "^6.0.0",
Tried to bump because it was not a major version change, but it seems it is ^6.0.0: https://github.com/MetaMask/core/blob/3227bd51bc4eca0531a53f4be6468404e6a5f032/packages/accounts-controller/package.json#L47

2024-06-05 22:22 UTC, tommasini commented on app/store/migrations/036.ts
> +        importTime: 123,
Addressed! You are super right! Thanks for the catch!

2024-06-05 22:29 UTC, owencraston approved these changes, later dismissed

2024-06-06 01:06 UTC, montelaidev requested changes
We will need to create a new migration to add `importTime` to existing users that have already migrated past `036`. 

An alternative would be to call `updateAccounts` on the accounts controller and it will populate the value.

2024-06-06 01:53 UTC, legobeat requested changes, later dismissed

2024-06-06 01:53 UTC, legobeat commented on yarn.lock
> +"@metamask/accounts-controller@^14.0.0":
v11 is still used by `@metamask/assets-controllers`.

I guess this also needs to be coupled with an update of `@metamask/assets-controllers` to either v29 or v30?

```
$ nvs -p @metamask/accounts-controller @metamask/assets-controllers | tail
26.0.0  2024-03-04T18:44:07.058Z        >=16.0.0        ^11.0.0
27.0.0  2024-03-12T19:47:40.443Z        >=16.0.0        ^12.0.0
27.0.1  2024-03-13T11:26:43.777Z        >=16.0.0        ^12.0.0
27.1.0  2024-03-19T08:49:30.180Z        >=16.0.0        ^12.0.0
27.2.0  2024-03-19T18:15:55.457Z        >=16.0.0        ^12.0.0
28.0.0  2024-04-17T15:00:35.910Z        >=16.0.0        ^13.0.0
29.0.0  2024-05-01T13:38:25.311Z        >=16.0.0        ^14.0.0
30.0.0  2024-05-29T20:08:33.688Z        >=16.0.0        ^14.0.0
31.0.0  2024-05-31T18:08:03.582Z        >=16.0.0        ^15.0.0
32.0.0  2024-05-31T19:50:52.965Z        ^18.18 || >=20  ^16.0.0
```

2024-06-06 03:01 UTC, montelaidev commented
> We will need to create a new migration to add `importTime` to existing users that have already migrated past `036`.
> 
> An alternative would be to call `updateAccounts` on the accounts controller and it will populate the value.

Also, i think the importTime from the identity in the preferences controller should be used if its available

2024-06-06 15:24 UTC, tommasini commented on yarn.lock
> +"@metamask/accounts-controller@^14.0.0":
But since it's a dependency of assets controller and not a peer dependency, is this a blocker?

Assets controllers will still be using the accounts controller v11, do you think it should be added as a peer dependency instead?

2024-06-06 15:26 UTC, tommasini commented
> Also, i think the importTime from the identity in the preferences controller should be used if its available

Ah read that right now, will update the migration with it

2024-06-06 22:55 UTC, legobeat commented on yarn.lock
> +"@metamask/accounts-controller@^14.0.0":
The dependency is only referenced in `TokenDetectionController` Looking here:
https://github.com/MetaMask/core/blob/main/packages/assets-controllers/src/TokenDetectionController.ts

The actual code of the dependency is not actually used - it's just pulled in for types and interacting with an externally provided `AccountsController`.

So unless we have them matched here, we will have an `assets-controller` implementet towards and expecting an `accounts-controller@11` but actually getting `accounts-controller@14`.

If it has been verified that there are no compatibility issues with mixing v11/v14.

(

So yes, I do think it should be in `peerDependencies`. At which point the `dependencies` entry can be removed, as the expected types will be provided through the `peerDependencies`.

2024-06-07 12:16 UTC, tommasini commented on yarn.lock
> +"@metamask/accounts-controller@^14.0.0":
Thanks for this answer and thanks for validating that there are no compatibility issues!
With this being said I'm WIP on the [assets controllers v30 update ](https://github.com/MetaMask/metamask-mobile/pull/9832)as we speak and that [version](https://github.com/MetaMask/core/blob/6f563ffb714db410666ec518e76e1806581367c8/packages/assets-controllers/package.json#L91) already have accounts-controller as a peer dependency

2024-06-07 15:02 UTC, montelaidev commented on app/store/migrations/043.test.ts
> +      ).toBeDefined();
We can use `expect.any(Number)` here

2024-06-07 17:04 UTC, tommasini commented on app/store/migrations/043.test.ts
> +      expect(true).toBeFalsy();
Was a workaround that I've found to the test fail if the engine is not defined and to deal with the lint and typescript issues to check if the engine object was defined inside of newState, since it can be undefined. It will never happen!

2024-06-10 11:22 UTC, tommasini commented on app/store/migrations/043.ts
> +        Object.keys(preferencesControllerState.identities).forEach(
I'm wondering if there is any reason for the identities to be empty objects and if we should take this into account and write a fallback if it isn't, it seems safer but at the same time, it seems dead code if it's not possible such scenario

2024-06-10 17:32 UTC, tommasini commented on app/store/migrations/043.ts
> +        Object.keys(preferencesControllerState.identities).forEach(
This outdated because the 043 file represents other migration but this is still present on 044.ts file

2024-06-12 09:16 UTC, montelaidev commented on app/store/migrations/044.test.ts
> +    Object.keys(
```suggestion
    const newState: Pick<RootState, 'engine'> = migration(oldState) as Pick<
      RootState,
      'engine'
    >;
```

I think we can just use pick instead of partial and then we don't need to this ```
if (!newState.engine) {
      expect(true).toBeFalsy();
      return;
    }
```

2024-06-12 09:18 UTC, montelaidev commented on app/store/migrations/043.ts
> +        Object.keys(preferencesControllerState.identities).forEach(
Yes we should still check because its possible for the user to reset their vault via forget password after running migration 036. In this case the identities should be an empty object.

2024-06-13 21:13 UTC, tommasini commented on app/store/migrations/044.test.ts
> +    Object.keys(
You are right!  Thanks for the knowledge!

2024-06-14 07:52 UTC, tommasini commented on app/store/migrations/044.test.ts
> +    Object.keys(
addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/9779/commits/febbb833db08dd5cdbe2906df9919742657d5e0e)

2024-06-14 07:52 UTC, tommasini commented on app/store/migrations/043.ts
> +        Object.keys(preferencesControllerState.identities).forEach(
addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/9779/commits/febbb833db08dd5cdbe2906df9919742657d5e0e)

2024-06-20 15:33 UTC, montelaidev submitted a review, later dismissed

2024-06-20 18:47 UTC, owencraston submitted a review, later dismissed

2024-06-20 20:44 UTC, Cal-L submitted a review, later dismissed
LGTM

2024-06-20 22:53 UTC, tommasini commented on yarn.lock
> +"@metamask/accounts-controller@^14.0.0":
I can merge this PR into the assets controllers one: https://github.com/MetaMask/metamask-mobile/pull/9832
Or I can merge both on the same day, resolving by changing on the assets controllers one the migration for number 48*
I would like to keep those separate for now to make life easier for the reviewers on the assets controllers one

2024-06-21 00:04 UTC, tommasini commented on yarn.lock
> +"@metamask/accounts-controller@^14.0.0":
Pointed https://github.com/MetaMask/metamask-mobile/pull/9832 to this branch so we can proceed with easier reviews and at the same time keep this ones that we already have! Thanks for the suggestions Lego!

2024-06-21 16:19 UTC, wachunei approved these changes

2024-06-21 17:00 UTC, infiniteflower approved these changes

2024-06-21 18:07 UTC, jpuri approved these changes

2024-06-21 18:14 UTC, sleepytanya approved these changes

2024-06-21 18:26 UTC, sethkfman approved these changes
LGTM

2024-06-21 18:26 UTC, merged