Update Basic Functionality settings description.json
MetaMask/metamask-mobile pull request #9781
Opened 2024-05-29 12:55 UTC by hesterbruikman

Adds copy to explain:
- What happens when toggle is enabled/disabled
- Basics of internet services and exposing IP addresses (we’re not doing anything out of the ordinary)
- IP address use by us is temporary and limited
- We never sell user data

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-05-29 22:34 UTC, EtherWizard33 commented on app/components/UI/BasicFunctionality/BasicFunctionality.tsx
> +        <Text color={TextColor.Info} onPress={handleLink}>
This code would throw an error on the load of the screen since handleLink is not defined, see video:
[Video 1: fix: Update Basic Functionality settings description.json #9781 - Watch Video](https://www.loom.com/share/65bc11f13cd64f46b4e7b139826841b9)

2024-05-29 22:55 UTC, EtherWizard33 requested changes
This second video is to complement the first one added as a first comment, inline, at line 42 of app/components/UI/BasicFunctionality/BasicFunctionality.tsx

[Video2 : fix: Update Basic Functionality settings description.json #9781 - Watch Video](https://www.loom.com/share/ee1c6a7bbfeb48dc9e0a55343945765a)

2024-05-30 13:55 UTC, jonybur approved these changes, later dismissed

2024-05-30 14:00 UTC, hesterbruikman commented on app/components/UI/BasicFunctionality/BasicFunctionality.tsx
> +        <Text color={TextColor.Info} onPress={handleLink}>
@EtherWizard33 looks like you resolved handling of the link. Ty! Can we resolve this conversation and merge?

2024-05-30 14:22 UTC, EtherWizard33 approved these changes

2024-05-30 16:02 UTC, sethkfman approved these changes
LGTM

2024-05-30 16:59 UTC, merged