feat:  Log the validity of the keyringController in the top 3 Migrations that appear in Sentry
MetaMask/metamask-mobile pull request #9785
Opened 2024-05-29 15:08 UTC by MarioAslau

…migrations that have been reporting errors

## **Description**

As part of the Vault Corruption Tactics: https://www.notion.so/metamask-consensys/Vault-Corruption-98cdfc486e75419fa3e53b7bfe244060

We have to increase our logging around possible areas that could be leading to Vault Corruption, to gather more information.

Add Sentry logs to log the validity of the keyringController in the top 3 Migrations that appear in Sentry, with the highest number of issues.

Issue: https://github.com/MetaMask/mobile-planning/issues/1712

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-10 09:27 UTC, tommasini requested changes

2024-06-10 09:27 UTC, tommasini commented on app/store/migrations/035.ts
> +  // @ts-expect-error We are not returning state not to stop the flow of Vault recovery
This comment seems informative, why the ts-expect-error?

2024-06-10 09:27 UTC, tommasini commented on app/store/migrations/036.test.ts
> +      console.log('OLD STATE:', oldState)
Could you remove the Console.log ?

2024-06-10 09:27 UTC, tommasini commented on app/store/migrations/036.test.ts
> +      console.log(newState)
Here as well?

2024-06-10 09:27 UTC, tommasini commented on app/store/migrations/036.ts
> +  console.log("STATE:", state)
Here as well

2024-06-10 09:27 UTC, tommasini commented on app/store/migrations/036.ts
> +  // @ts-expect-error We are not returning state not to stop the flow of Vault recovery
Hmm what's exactly the typescript error here?

2024-06-10 09:27 UTC, tommasini commented on app/store/migrations/036.ts
> +        // @ts-expect-error We are not returning state not to stop the flow of Vault recovery
And here? What's exactly the typescript error?

2024-06-10 09:27 UTC, tommasini commented on app/store/migrations/037.ts
> +  // @ts-expect-error We are not returning state not to stop the flow of Vault recovery
Here as well probably it's not need the TS expect error

2024-06-10 12:05 UTC, MarioAslau commented on app/store/migrations/037.ts
> +  // @ts-expect-error We are not returning state not to stop the flow of Vault recovery
<img width="650" alt="Screenshot 2024-06-10 at 15 04 37" src="https://github.com/MetaMask/metamask-mobile/assets/15312578/2c6b8be8-8a0a-41ca-a0e8-6451aaa172f4">
it's the same everywhere

2024-06-18 17:58 UTC, tommasini commented on app/store/migrations/036.test.ts
> +            KeyringController: { vault: {} },
On the version before this was introduced we had [Keyring contorller v8](https://github.com/MetaMask/metamask-mobile/blob/04fa71b1730497adfb288ceea655bc07633eed82/package.json#L153)

And at that version the [Keyring Controller already was extending from base controller v2](https://github.com/MetaMask/core/blob/01fb17da36e8a7b9b27f7cff4c200eb6bd6b004d/packages/keyring-controller/src/KeyringController.ts#L240),
Does that mean that the data will be inside of a metadata property?

2024-06-18 20:11 UTC, tommasini commented on app/store/migrations/036.test.ts
> +            KeyringController: { vault: {} },
Hmm this doesn't seem to be truth, we save on the storage without the metadata property will pass this PR

2024-06-18 20:11 UTC, tommasini approved these changes

2024-06-19 18:38 UTC, merged