feat: add semi-transparent overlay to QRScanner
MetaMask/metamask-mobile pull request #9813
Opened 2024-05-31 11:58 UTC by mirceanis

## **Description**

This PR is part of a set of changes intended to redesign the QRScanner experience (see https://github.com/MetaMask/MetaMask-planning/issues/2384)

## **Related issues**

Fixes: https://github.com/MetaMask/MetaMask-planning/issues/2566

## **Manual testing steps**

1. Go to the home screen and press the scan button
2. The QR scanning camera now has a semi-transparent overlay surrounding the frame

## **Screenshots/Recordings**

### **Before**
![before](https://github.com/MetaMask/metamask-mobile/assets/965762/7585995b-479e-4d2a-8cfe-d813ad647cfb)

### **After**

![after](https://github.com/MetaMask/metamask-mobile/assets/965762/5ced578c-7e96-45e4-8d58-c50a29336f15)

## **Pre-merge author checklist**

- [X] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [X] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-05-31 11:58 UTC, mirceanis commented
I have read the CLA Document and I hereby sign the CLA

2024-05-31 13:53 UTC, jonybur requested changes

2024-05-31 13:53 UTC, jonybur commented on app/components/Views/QRScanner/styles.ts
> +      margin: -4,
Let's try to avoid negative margins

2024-05-31 14:17 UTC, mirceanis commented on app/components/Views/QRScanner/styles.ts
> +      margin: -4,
I don't know how else to overlap the frame with the overlay elements. Any suggestions?

2024-06-04 15:02 UTC, mirceanis commented on app/styles/common.ts
> +  overlayText: 'rgba(20, 22, 24, 1.0)',
not sure if this is the right way to introduce colors @jonybur

2024-06-04 15:02 UTC, mirceanis commented on app/components/Views/QRScanner/styles.ts
> -      opacity: 0.5,
removing this opacity fixes https://github.com/MetaMask/MetaMask-planning/issues/2569
we already have the frame asset

2024-06-24 14:41 UTC, mirceanis commented
changes were cherry picked in https://github.com/MetaMask/metamask-mobile/pull/10061

2024-06-24 14:41 UTC, closed without merging