fix: add migration for linea goerli
MetaMask/metamask-mobile pull request #9826
Opened 2024-06-03 08:27 UTC by salimtb

## **Description**

PR to migrate users to linea Sepolia if they are on linea-goerli. And remove linea goerli from default network list because its deprecated.

## **Related issues**

Fixes:

## **Manual testing steps**

1. Build on main
2. Switch to linea-goerli
3. Build on this PR
4. You should be on linea sepolia instead of linea goerli
5. You can add linea goerli  by clicking on the navigation button in the wallet and type in: chainlist.org. Connect your wallet and you can look for the network you want to add then click on "add to metamask" button. (I used this RPc url https://59140.rpc.thirdweb.com to add linea goerli)
6.You should see deprecation warning for linea goerli. And you should be able to see any previous transactions you did.

## **Screenshots/Recordings**

### **Before**

Linea goerli appears on the default network list.
I make few transactions on both linea goerli and linea sepolia.

https://github.com/MetaMask/metamask-mobile/assets/10994169/c0e621ce-9cd3-47e8-b653-cc19f1413796

### **After**

I add manually linea goerli and i can see transactions i already did.

https://github.com/MetaMask/metamask-mobile/assets/10994169/db6c910b-4ba7-4559-8850-33472a883ff6

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-07 16:09 UTC, tommasini requested changes
Awesome work! Left some comments and questions!

2024-06-07 16:09 UTC, tommasini commented on app/components/Views/Settings/NetworksSettings/__snapshots__/index.test.tsx.snap
> -                          <View>
I'm not understanding why this snapshot needed to be updated, I can see that the linea goerli was seleceted, but I dont't understand why since it was not the linea goerli chain id selected on the mock Data, and neither we changed anything related to this component, do you know why it was needed to update this snapshot?

2024-06-07 16:09 UTC, tommasini commented on app/store/migrations/043.ts
> +  if (!isObject(state)) {
Can we use the function [ensureValidState](https://github.com/MetaMask/metamask-mobile/blob/220d7176dfdd4d317c13eaf802910c5b789d7577/app/store/migrations/util/index.tsx#L11) instead of checking for state, state.engine and state.engine.backgroundState?

2024-06-07 16:09 UTC, tommasini commented on app/store/migrations/043.ts
> +        `Migration 43: Invalid NetworkController state error: '${typeof networkControllerState}'`,
Could we had a FATAL error to this exception?
```suggestion
        `FATAL ERROR: Migration 43: Invalid NetworkController state error: '${typeof networkControllerState}'`,
```

2024-06-07 16:09 UTC, tommasini commented on app/store/migrations/043.ts
> +        `Migration 43: NetworkController providerConfig chainId not found: '${JSON.stringify(
Here as well since if there is not chainId found we are on a really weird state!
```suggestion
        `FATAL ERROR: Migration 43: NetworkController providerConfig chainId not found: '${JSON.stringify(
```

2024-06-07 16:09 UTC, tommasini commented on app/store/migrations/043.ts
> +
Since we are casting we are assuming that providerConfig is defined, but it would be cool if we validate it here as well before we validate the chainId!

2024-06-07 16:09 UTC, tommasini commented on app/store/migrations/043.ts
> +      ticker: 'LineaETH',
Can we use a constant from this [file](https://github.com/MetaMask/metamask-mobile/blob/52bc89c7b7e4aefe0157b475d0fa58080c702a33/app/constants/network.js#L62) instead if that makes sense for you?

2024-06-07 16:09 UTC, tommasini commented on app/store/migrations/043.ts
> +  return state;
I believe the object [networkConfigurations](https://github.com/MetaMask/core/blob/f31ff0fef78c2be0d84eedae689cc69b3eeaba08/packages/network-controller/src/NetworkController.ts#L332) of Network Controller also needs to have sepolia data when sepolia data is selected on the provider config, although, I'm not 100% sure, do you know if it is?

2024-06-07 16:38 UTC, salimtb commented on app/store/migrations/043.ts
> +  return state;
yes, if the provider configuration is set to use Sepolia data, then the networkConfigurations object within the Network Controller will indeed include Sepolia data.

2024-06-07 16:41 UTC, salimtb commented on app/store/migrations/043.ts
> +
done :)

2024-06-07 16:55 UTC, salimtb commented on app/components/Views/Settings/NetworksSettings/__snapshots__/index.test.tsx.snap
> -                          <View>
this line has been changed because the list of testsnetwork has been updated , and linea goerli has been deleted ( check the line 724 of this file to understand )

2024-06-10 11:49 UTC, tommasini commented on app/store/migrations/043.ts
> +  return state;
The controller will handle that or we will need to add it on this migrations as well?

2024-06-10 12:27 UTC, tommasini approved these changes
LGTM

2024-06-10 13:03 UTC, merged