Enable transaction simulations for transactions
MetaMask/metamask-mobile pull request #9828
Opened 2024-06-03 09:51 UTC by OGPoyraz

## **Description**

This PR introduces transaction simulation for the transactions.

For the detail of the patch please visit: https://github.com/MetaMask/core/pull/4348

## **Related issues**

Fixes: https://github.com/MetaMask/mobile-planning/issues/1719

## **Manual testing steps**

See recording

## **Screenshots/Recordings**

https://github.com/MetaMask/metamask-mobile/assets/7644512/fbc5e60e-7c3d-4649-94b8-635807b2ece9

### **Before**

### **After**

## **Pre-merge author checklist**

- [x] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [x] I've completed the PR template to the best of my ability
- [x] I’ve included tests if applicable
- [x] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [x] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-03 10:12 UTC, OGPoyraz commented on app/core/Engine.ts
> +      isSimulationEnabled: () => true,
This is temporary for testing purpose.

2024-06-03 20:57 UTC, matthewwalsh0 commented on app/components/UI/Name/Name.tsx
> +export function shortenAddress(address = '') {
As in the extension, should we put this and the constants in a util somewhere so it's not coupled to `Name` and can have its own unit tests?

2024-06-03 20:57 UTC, matthewwalsh0 commented on app/components/Views/confirmations/SendFlow/Confirm/index.js
> +                enableMetrics={false}
Do we not want metrics for transfer transactions?

2024-06-03 20:57 UTC, matthewwalsh0 commented on app/selectors/confirmTransaction.ts
> +export const selectCurrentTransactionId = (state: RootState) =>
Do we need to export this?

Could we instead just use the below `selectCurrentTransactionMetadata` and not make a simulation data specific selector, as that would mean we'd need selectors for every future metadata property also?

2024-06-04 05:18 UTC, sleepytanya commented
Physical Samsung S24+, Android 14. [Bitrise build](https://app.bitrise.io/build/12a21b74-2cb0-449a-93e9-210eb844b599?tab=artifacts).

Simulations conducted on the Sepolia network perform as anticipated. For some reason the balance on Sepolia is always shown as 0 but that doesn't prevent the user to send tokens. `$NaN` is displayed within the simulation section next to the currency name: 


https://github.com/MetaMask/metamask-mobile/assets/104780023/00d6aa59-be68-4210-8e53-aa310fa3828e




When operating on the mainnet, the application experiences a significant slowdown, with transactions taking minutes to proceed. Confirmation screen for the swap displays a message 'You need *** more *token_name* to proceed...' while account has enough assets to pay for the transaction. Sometimes swap simulation work but it takes minutes for them to appear:

https://github.com/MetaMask/metamask-mobile/assets/104780023/95c5d8bc-04ca-4c98-90a4-fc9ed3b51138

 Simple Send on mainnet is also extremely slow but simulations work:

https://github.com/MetaMask/metamask-mobile/assets/104780023/84b7d521-f7d8-494f-a2da-6ec54d910850



I don't see simulations working for the test dapp - is it expected?

2024-06-04 05:36 UTC, OGPoyraz commented
@sleepytanya concerns about the fiat values:
- 0 value on balance: I think you need to enable Advanced => Show conversion on test networks
- NaN value is the same reason as above, you need to enable the conversion on test networks. Since this `NaN US$` looks ugly I've already created a task to handle it separately (https://github.com/orgs/MetaMask/projects/78/views/1?pane=issue&itemId=65817155) but we didn't had a chance to estimate it yet.

I think there is overall a performance issue on your device somehow, I've never experienced such degradation on simulator/phyiscal device (could be seen from the video I recorded). But I will build and check it one more time.

2024-06-04 05:45 UTC, OGPoyraz commented on app/core/Engine.ts
> +      isSimulationEnabled: () => true,
> Could we use an ENV for this or will this be the final ticket?

I am thinking to add ENV for this, preference and the what's new PR. But to make it easy to test it for QA, I didn't add this up yet.

> Did we want to also add E2E tests before enabling?

This has separate ticket that I am currently working on https://github.com/MetaMask/mobile-planning/issues/1725

> We can also reference the preference once that is merged?

Exactly, I will first merge the pref go with ENV then update this.

2024-06-04 05:47 UTC, OGPoyraz commented on app/components/Views/confirmations/SendFlow/Confirm/index.js
> +                enableMetrics={false}
Good catch, a forgotten one.

2024-06-04 06:12 UTC, OGPoyraz commented on app/selectors/confirmTransaction.ts
> +export const selectCurrentTransactionId = (state: RootState) =>
Done https://github.com/MetaMask/metamask-mobile/pull/9828/commits/533fb74b4eb79c9e5d02d811e74e1596604a3cf2

2024-06-06 10:07 UTC, OGPoyraz commented on app/core/Engine.ts
> +      isSimulationEnabled: () => true,
Update: toggle is merged, this is now referencing preferences controller state, but still hidden behind env var.

2024-06-11 10:20 UTC, matthewwalsh0 approved these changes, later dismissed

2024-06-11 10:43 UTC, vinistevam approved these changes, later dismissed

2024-06-11 16:24 UTC, Cal-L requested changes
Add `MM_TRANSACTION_SIMULATIONS_ENABLED` to `bitrisel.yml`. You can reference how `MM_NOTIFICATIONS_UI_ENABLED` is set

2024-06-12 16:00 UTC, Cal-L approved these changes
LGTM

2024-06-13 08:14 UTC, merged