chore Update controller utils to v^10 and assets controllers utils to v^30
MetaMask/metamask-mobile pull request #9832
Opened 2024-06-03 21:06 UTC by tommasini

## **Description**
Still need to re do the patch of assets controllers utils and re check each breaking change

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-20 09:47 UTC, tommasini commented on app/store/migrations/029.ts
> +        //@ts-expect-error Assets Controllers version on the version this migration was applied, this property existed
Not sure if this would be the best way to handle this typescript issue, open to feedback

2024-06-20 09:47 UTC, tommasini commented on app/store/migrations/031.ts
> +            //@ts-expect-error Assets Controllers version on the version this migration was applied, this property existed
Not sure if this would be the best way to handle this typescript issue, open to feedback

2024-06-20 09:47 UTC, tommasini commented on app/store/migrations/031.ts
> +          //@ts-expect-error Assets Controllers version on the version this migration was applied, this property existed
Not sure if this would be the best way to handle this typescript issue, open to feedback

2024-06-20 22:56 UTC, tommasini commented on app/store/migrations/047.ts
Yes, will ask now for reviews on this one once the e2e passes, just to make the life of the reviewers easier! Thanks for pointing this out!

2024-06-20 23:54 UTC, cortisiko requested changes
small feedback

2024-06-20 23:54 UTC, cortisiko commented on e2e/fixtures/fixture-builder.js
> +    merge(this.fixture.state.engine.backgroundState.KeyringController, data);
```suggestion
const keyringData = {

  keyrings: [
    {
      type: 'HD Key Tree',
      accounts: ['0x37cc5ef6bfe753aeaf81f945efe88134b238face'],
    },
    { type: 'QR Hardware Wallet Device', accounts: [] },
  ],
  vault: '{"cipher":"T+MXWPPwXOh8RLxpryUuoFCObwXqNQdwak7FafAoVeXOehhpuuUDbjWiHkeVs9slsy/uzG8z+4Va+qyz4dlRnd/Gvc/2RbHTAb/LG1ECk1rvLZW23JPGkBBVAu36FNGCTtT+xrF4gRzXPfIBVAAgg40YuLJWkcfVty6vGcHr3R3/9gpsqs3etrF5tF4tHYWPEhzhhx6HN6Tr4ts3G9sqgyEhyxTLCboAYWp4lsq2iTEl1vQ6T/UyBRNhfDj8RyQMF6hwkJ0TIq2V+aAYkr5NJguBBSi0YKPFI/SGLrin9/+d66gcOSFhIH0GhUbez3Yf54852mMtvOH8Vj7JZc664ukOvEdJIpvCw1CbtA9TItyVApkjQypLtE+IdV3sT5sy+v0mK7Xc054p6+YGiV8kTiTG5CdlI4HkKvCOlP9axwXP0aRwc4ffsvp5fKbnAVMf9+otqmOmlA5nCKdx4FOefTkr/jjhMlTGV8qUAJ2c6Soi5X02fMcrhAfdUtFxtUqHovOh3KzOe25XhjxZ6KCuix8OZZiGtbNDu3xJezPc3vzkTFwF75ubYozLDvw8HzwI+D5Ifn0S3q4/hiequ6NGiR3Dd0BIhWODSvFzbaD7BKdbgXhbJ9+3FXFF9Xkp74msFp6o7nLsx02ywv/pmUNqQhwtVBfoYhcFwqZZQlOPKcH8otguhSvZ7dPgt7VtUuf8gR23eAV4ffVsYK0Hll+5n0nZztpLX4jyFZiV/kSaBp+D2NZM2dnQbsWULKOkjo/1EpNBIjlzjXRBg5Ui3GgT3JXUDx/2GmJXceacrbMcos3HC2yfxwUTXC+yda4IrBx/81eYb7sIjEVNxDuoBxNdRLKoxwmAJztxoQLF3gRexS45QKoFZZ0kuQ9MqLyY6HDK","iv":"3271713c2b35a7c246a2a9b263365c3d","keyMetadata":{"algorithm":"PBKDF2","params":{"iterations":5000}},"lib":"original","salt":"l4e+sn/jdsaofDWIB/cuGQ=="}'
};

    merge(this.fixture.state.engine.backgroundState.KeyringController, keyringData);

2024-06-20 23:54 UTC, cortisiko commented on e2e/fixtures/fixture-builder.js
> +    merge(this.fixture.state.engine.backgroundState.KeyringController, data);
I think having the test data for the controller in the fixture definition makes sense oppose to keeping it in the test.

2024-06-20 23:54 UTC, cortisiko commented on e2e/specs/wallet/request-token-flow.spec.js
> +    const fixture = new FixtureBuilder()
Now you can just build the fixture with the keyring controller.     

`const fixture = new FixtureBuilder().withKeyringController().build();`

2024-06-20 23:56 UTC, tommasini commented on e2e/fixtures/fixture-builder.js
> +    merge(this.fixture.state.engine.backgroundState.KeyringController, data);
Doing it right now! THanks for the review!

2024-06-20 23:57 UTC, tommasini commented on e2e/specs/wallet/request-token-flow.spec.js
> +    const fixture = new FixtureBuilder()
Addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/9832/commits/9bd8fe3daa8eeae8e7c0222131975745f9783bc1)

2024-06-20 23:57 UTC, tommasini commented on e2e/fixtures/fixture-builder.js
> +    merge(this.fixture.state.engine.backgroundState.KeyringController, data);
Addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/9832/commits/9bd8fe3daa8eeae8e7c0222131975745f9783bc1)

2024-06-21 00:04 UTC, cortisiko approved these changes
🌮 🌮 🌮

2024-06-21 01:54 UTC, jpuri commented on app/components/Views/confirmations/SendFlow/Amount/index.js
> +      : null;
NIT: 
```
const exchangeRate = contractExchangeRates?.[selectedAsset.address]?.price ?? null;
```

2024-06-21 01:55 UTC, jpuri approved these changes
I reviewed the changes in files owned by confirmation team, look great 👍

2024-06-21 09:26 UTC, vinistevam commented on app/components/UI/TransactionElement/utils.js
> +    : contractExchangeRates?.[safeToChecksumAddress(destinationToken.address)]
Isn't it necessary to use optional chaining here too?

2024-06-21 09:26 UTC, vinistevam approved these changes
All great on the confirmations side! :+1:  Amazing PR :fist_oncoming:

2024-06-21 10:08 UTC, NicolasMassart commented on e2e/fixtures/fixture-builder.js
> +  withKeyringController() {
Q: why is this needed?

2024-06-21 10:08 UTC, NicolasMassart commented on app/components/Views/confirmations/SendFlow/Amount/index.js
> +      : null;
I would not say it's a nit... very important change and can be applied in many places (most ternary ops) in this PR.

2024-06-21 10:13 UTC, tommasini commented on app/components/Views/confirmations/SendFlow/Amount/index.js
> +      : null;
Addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/9832/commits/16a0c69b83e6210a85acc90dc95757ae8fdc0fa2)

2024-06-21 10:14 UTC, tommasini commented on app/components/UI/TransactionElement/utils.js
> +    : contractExchangeRates?.[safeToChecksumAddress(destinationToken.address)]
Addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/9832/commits/16a0c69b83e6210a85acc90dc95757ae8fdc0fa2)

2024-06-21 10:14 UTC, tommasini commented on app/components/UI/Swaps/index.js
> -    dispatch(setSwapsHasOnboarded(hasOnboarded)),
It was not being used, found it as dead code!

2024-06-21 10:16 UTC, tommasini commented on e2e/fixtures/fixture-builder.js
> +  withKeyringController() {
This new keyring controller data is needed, because the older account being used had funds (NFTs) in it while we were trying to test an unprotected account flow! That was being blocked by the mandatory protect your wallet modal, making the e2e tests fail!

It's possible to find more [details on this thread](https://consensys.slack.com/archives/C04GLB755TK/p1718897526808119)

2024-06-21 10:24 UTC, NicolasMassart commented on app/components/UI/Swaps/index.js
> -    dispatch(setSwapsHasOnboarded(hasOnboarded)),
Thanks for the cleaning!

2024-06-21 10:28 UTC, tommasini commented on app/components/Views/confirmations/SendFlow/Amount/index.js
> +      : null;
@NicolasMassart Can you help me flag those places? Some of them really need to return undefined instead of null! But maybe we can change all of the places

2024-06-21 10:52 UTC, tommasini commented on app/store/migrations/029.ts
> +        //@ts-expect-error Assets Controllers version on the version this migration was applied, this property existed
At the time of that migrations assets controllers version had those properties, so those users will have that property on their phone storage, the migration was casted and that where it's wrong, we shouldn't cast migrations because the structure and property names change over time

2024-06-21 10:54 UTC, tommasini commented on app/store/migrations/029.ts
> +        //@ts-expect-error Assets Controllers version on the version this migration was applied, this property existed
Copy improved on this [commit](https://github.com/MetaMask/metamask-mobile/pull/9832/commits/d2f49e5b5d2c65b7129f0ddff0be948393d1323f)

2024-06-21 10:54 UTC, tommasini commented on app/store/migrations/031.ts
> +          //@ts-expect-error Assets Controllers version on the version this migration was applied, this property existed
Copy improved on this [commit](https://github.com/MetaMask/metamask-mobile/pull/9832/commits/d2f49e5b5d2c65b7129f0ddff0be948393d1323f)

2024-06-21 10:54 UTC, tommasini commented on app/store/migrations/031.ts
> +            //@ts-expect-error Assets Controllers version on the version this migration was applied, this property existed
Copy improved on this [commit](https://github.com/MetaMask/metamask-mobile/pull/9832/commits/d2f49e5b5d2c65b7129f0ddff0be948393d1323f)

2024-06-21 11:39 UTC, NicolasMassart approved these changes
Looks good to me.

2024-06-21 12:48 UTC, nikoferro approved these changes

2024-06-21 14:54 UTC, wachunei commented on app/components/UI/Ramp/hooks/useBalance.ts
> +        ? tokenExchangeRates?.[assetAddress]?.price
Since we are checking for `tokenExchangeRates`,`assetAddress` and `assetAddress in tokenExchangeRates` then we should just need `tokenExchangeRates[assetAddress].price`.

2024-06-21 14:56 UTC, tommasini commented on app/components/UI/Ramp/hooks/useBalance.ts
> +        ? tokenExchangeRates?.[assetAddress]?.price
You are right @wachunei , addressed on this [commit](https://github.com/MetaMask/metamask-mobile/pull/9832/commits/e6ae06781836b37375a43c6844ceb86cf7698f2f)

2024-06-21 14:58 UTC, wachunei approved these changes
Ramp changes LGTM

2024-06-21 15:45 UTC, merged