fix: create nft auto detection modal and remove nft polling logic
MetaMask/metamask-mobile pull request #9857
Opened 2024-06-05 13:31 UTC by sahar-fehri

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-17 20:53 UTC, cortisiko requested changes
Alright, @sahar-fehri, I left some feedback. Furthermore here are the bugs that I  noticed: 

- With the orangefox the below 1155 contracts are not auto imported
https://opensea.io/assets/ethereum/0xd07dc4262BCDbf85190C01c996b4C06a461d2430/77675
 https://opensea.io/assets/ethereum/0x3778541C3ABb6668eCB3eCC407388837a4457d5D/1 

  in addition to this ENS NFT: https://opensea.io/assets/ethereum/0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85/52013207599245702848910397253902912447697817810483152369346578845112926213225 


- There is a bug when you try to manually import an NFT. 
 For example, you can try using the orangefox test account, go to polygon and  try to import this NFT: contract address: 0x79161C741379c1bCC815FD73D37B91cD8E159B6c and TokenID: 72

2024-06-17 20:53 UTC, cortisiko commented on e2e/specs/assets/nft-detection-modal.spec.js
> +'use strict';
I would also add another test where NFT auto-detection is off by default, and in the not detection modal, I would tap Allow. Then I would verify that the NFts are appearing correctly. The wallet that we uses the default fixture has 2 NFTs (721 and 1155) on mainnet

2024-06-17 20:53 UTC, cortisiko commented on e2e/specs/assets/nft-detection-modal.spec.js
> +          .withGanacheNetwork()
Furthermore, perhaps this is a bug or not but with token detection off, when you start on mainnet, the NFT detection bottom sheet does not appear but if you switch between a custom network back to mainnet the detection sheet appears. If this is not a bug then you would need to adjust the test steps: start on ganache, switch to mainnet to trigger the bottom sheet

2024-06-18 13:06 UTC, sahar-fehri commented
> Alright, @sahar-fehri, I left some feedback. Furthermore here are the bugs that I noticed:
> 
> * With the orangefox the below 1155 contracts are not auto imported
>   https://opensea.io/assets/ethereum/0xd07dc4262BCDbf85190C01c996b4C06a461d2430/77675
>   https://opensea.io/assets/ethereum/0x3778541C3ABb6668eCB3eCC407388837a4457d5D/1
>   in addition to this ENS NFT: https://opensea.io/assets/ethereum/0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85/52013207599245702848910397253902912447697817810483152369346578845112926213225
> * There is a bug when you try to manually import an NFT.
>   For example, you can try using the orangefox test account, go to polygon and  try to import this NFT: contract address: 0x79161C741379c1bCC815FD73D37B91cD8E159B6c and TokenID: 72

Hey @cortisiko ! Thanks for the feedback! 
Regarding this NFT that is not showing up https://opensea.io/assets/ethereum/0xd07dc4262BCDbf85190C01c996b4C06a461d2430/77675
I'm checking with the team on this, it does not show because its marked as spam, im checking why it's the case.

For this one https://opensea.io/assets/ethereum/0x3778541C3ABb6668eCB3eCC407388837a4457d5D/1
Im actually able to see it being detected and added to state (screenshot)
<img width="429" alt="Screenshot 2024-06-18 at 15 00 43" src="https://github.com/MetaMask/metamask-mobile/assets/10994169/ba7afbc6-5325-411b-a4a6-c685fcb506f4">

For the ENS NFT: https://opensea.io/assets/ethereum/0x57f1887a8BF19b14fC0dF6Fd9B2acc9Af147eA85/52013207599245702848910397253902912447697817810483152369346578845112926213225
That NFT does not look like it is owned by orangeFox account. When i call [ownerOf](https://etherscan.io/address/0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85#readContract) function on the contract for this tokenId `52013207599245702848910397253902912447697817810483152369346578845112926213225` i get this address [0x378f19ddbF56ecd512C364FbA1F271A3F571C12f](https://etherscan.io/address/0x378f19ddbF56ecd512C364FbA1F271A3F571C12f) as being the current owner of that NFT.

Please lemme know if i missed something! 🙏 


For the bug on polygon mainnet after adding contract address: 0x79161C741379c1bCC815FD73D37B91cD8E159B6c and TokenID: 72; What was the behavior you experienced?

I was able to add the NFT when i import manually (screenshot) 
<img width="425" alt="Screenshot 2024-06-18 at 15 06 23" src="https://github.com/MetaMask/metamask-mobile/assets/10994169/54c90171-a578-4d06-977d-7dd04010586f">

2024-06-18 15:45 UTC, brianacnguyen approved these changes, later dismissed

2024-06-18 16:41 UTC, sahar-fehri commented on e2e/specs/assets/nft-detection-modal.spec.js
> +          .withGanacheNetwork()
I have updated the test to start on ganache and the switch to mainnet 🙏 
The new modal should only appear on mainnet because as you mentioned NFT detection today is only on mainnet and it should appear when the NFT detection toggle is off.

I was not able to reproduce the behavior you described: 
`when you start on mainnet, the NFT detection bottom sheet does not appear but if you switch between a custom network back to mainnet the detection sheet appears.`

If you have a video to provide that could help me reproduce, but if you start on mainnet and the NFT detection toggle is OFF, then you should see the modal. If it is ON, then it is expected to not see the modal unless you turn the toggle off.

2024-06-18 17:25 UTC, sahar-fehri commented
> ## [<img alt="https://bitrise.io/" height="20" src="https://camo.githubusercontent.com/bcc47f08b749f2842135461d97104f27dde8bdf31c261c0d97680bd89dd5b177/68747470733a2f2f6173736574732d676c6f62616c2e776562736974652d66696c65732e636f6d2f3564623335646530323462623938336166316234653135312f3565366639636363336531323964666438613230356534655f426974726973652532304c6f676f2532302d253230456767706c616e7425323042672e706e67">](https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/69eb2a84-9704-44eb-bce4-7090135bfa8d) **Bitrise**
> ❌❌❌ `pr_smoke_e2e_pipeline` failed on Bitrise! ❌❌❌
> 
> Commit hash: [98d1813](https://github.com/MetaMask/metamask-mobile/commit/98d18138884ee0a0e83d2267f83050c9c323c6f8) Build link: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/69eb2a84-9704-44eb-bce4-7090135bfa8d
> 
> Note
> 
> * You can kick off another `pr_smoke_e2e_pipeline` on Bitrise by removing and re-applying the `Run Smoke E2E` label on the pull request

e2e failing because of the new privacy policy toast, This [PR](https://github.com/MetaMask/metamask-mobile/pull/10021) addresses that

2024-06-18 17:57 UTC, sahar-fehri commented on e2e/specs/assets/nft-detection-modal.spec.js
> +'use strict';
I added a test for that. 🙏

2024-06-19 00:19 UTC, cortisiko commented
hey @sahar-fehri thanks for clarifying my questions. To follow up here:

> For the bug on polygon mainnet after adding contract address: 0x79161C741379c1bCC815FD73D37B91cD8E159B6c and TokenID: 72; What was the behavior you experienced?
> 
> I was able to add the NFT when i import manually (screenshot)


I am no longer experiencing the import bug. However, when I kill and relaunch the app after importing the NFT, that same NFT disappears from my wallet.


https://github.com/MetaMask/metamask-mobile/assets/12821081/2eff1c85-57f9-4620-88d9-2dd7994d5565


> Hey @cortisiko ! Thanks for the feedback!
> Regarding this NFT that is not showing up https://opensea.io/assets/ethereum/0xd07dc4262BCDbf85190C01c996b4C06a461d2430/77675
> I'm checking with the team on this, it does not show because its marked as spam, im checking why it's the case.


I came across the same [issue](https://app.screencast.com/CZXKcrPETFmdp) using a different account.

2024-06-19 00:46 UTC, cortisiko requested changes

2024-06-19 00:46 UTC, cortisiko commented on e2e/specs/assets/nft-detection-modal.spec.js
> +        await TestHelpers.checkIfElementByTextIsVisible(
Use the assertions class for this. You can do `Assertions.checkIfTextIsDisplayed('string')`

2024-06-19 00:46 UTC, cortisiko commented on e2e/specs/assets/nft-detection-modal.spec.js
> +          enContent.wallet.nfts_autodetection_desc,
ahh, so similar to how you would create a testID selector object, you would do the same for String selectors. See here for example: https://github.com/MetaMask/metamask-mobile/blob/feat/call-nft-detection-on-components/e2e/selectors/Common.selectors.js#L23

2024-06-19 00:46 UTC, cortisiko commented on e2e/specs/assets/nft-detection-modal.spec.js
> +        await TestHelpers.checkIfElementByTextIsVisible(
https://github.com/MetaMask/metamask-mobile/blob/feat/call-nft-detection-on-components/e2e/specs/confirmations/send-erc721.spec.js#L61

2024-06-19 00:46 UTC, cortisiko commented on e2e/specs/assets/nft-detection-modal.spec.js
> +        const tesNFTOnMainnet = "collectible-Life's A Joke #2875-2875";
Consider declaring this variable at the beginning of the test.

2024-06-19 00:46 UTC, cortisiko commented on e2e/specs/assets/nft-detection-modal.spec.js
> +        await TestHelpers.checkIfVisible(tesNFTOnMainnet);
Use the assertions class for this. You can do `Assertions.checkIfTextIsDisplayed(tesNFTOnMainnet)`

2024-06-19 00:46 UTC, cortisiko commented on e2e/specs/assets/nft-detection-modal.spec.js
> +        await TestHelpers.checkIfNotVisible(
Use the assertions class for this. You can do `Assertions.checkIfTextIsNotDisplayed('string')`

2024-06-19 00:46 UTC, cortisiko commented on e2e/specs/assets/nft-detection-modal.spec.js
> +          .withGanacheNetwork()
Okay great, thanks for updating! Regarding the issue I described, seems more like an edge case. I can no longer reproduce the issue.

2024-06-19 07:25 UTC, sahar-fehri commented on e2e/specs/assets/nft-detection-modal.spec.js
> +        await TestHelpers.checkIfElementByTextIsVisible(
Fixed 🙏

2024-06-19 07:47 UTC, sahar-fehri commented
> e across the same [issue](https://app.screencast.com/CZXKcrPETFmdp) using a different account.

Hey @cortisiko ! I was not able to reproduce the behavior in the video. The NFT is displayed correctly after relaunching app.
Also i checked the [issue](https://app.screencast.com/CZXKcrPETFmdp) you mentioned, i see that our API is only returning one NFT for that account ( the LifesAJokeNFT). [Opensea](https://opensea.io/0x76cf1CdD1fcC252442b50D6e97207228aA4aefC3) also is only returning one NFT for that account.

I also checked the ownership on the contract:
contract: 0xB66a603f4cFe17e3D27B87a8BfCaD319856518B8
tokenId: 100059584189867566852894599154934721552567499366058460268305346163854916190212

The account 0x76cf1CdD1fcC252442b50D6e97207228aA4aefC3 does not hold that NFT

<img width="947" alt="Screenshot 2024-06-19 at 09 46 46" src="https://github.com/MetaMask/metamask-mobile/assets/10994169/c984a874-8f1e-47fa-bc43-27c1491d8cf8">

2024-06-19 10:24 UTC, tommasini requested changes
Heyy, awesome work! Left some comments!

2024-06-19 10:24 UTC, tommasini commented on app/components/UI/CollectibleDetectionModal/index.tsx
> +    void (async () => {
Please solve lint issue

2024-06-19 10:24 UTC, tommasini commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.tsx
> +  const walletImage = require('../../../images/wallet-alpha.png'); // eslint-disable-line
Should we do the require outside or directly on the prop of the image instead? it seems out of context do a require here but probably it's personal, feel free to change it or not!

2024-06-19 10:24 UTC, tommasini commented on app/components/Views/Wallet/index.tsx
> +          Engine.context as any;
Do we still need this `as any`? If it's not too much outside of the scope it would be cool to remove it

2024-06-19 10:24 UTC, tommasini commented on app/components/Views/Wallet/index.tsx
> -        NftDetectionController.detectNfts();
If we do not detect the NFTs it will not automatically add if the user adds an nft? Thinking out loud, not sure now how the detect works on the controller level

2024-06-19 10:24 UTC, tommasini commented on app/components/Views/Wallet/index.tsx
> +        const { NftDetectionController } = Engine.context as any;
Can we try not use any?

2024-06-19 10:24 UTC, tommasini commented on app/core/Engine.ts
> +        useNftDetection: true, // set this to true to enable nft detection by default to new users
I imagine this was a product decision, could you share the thread via DM where this was discussed?

2024-06-19 11:00 UTC, sahar-fehri commented on app/component-library/components/Toast/Toast.tsx
> +            //size={AvatarSize.Md}
Removed!

2024-06-19 11:15 UTC, sahar-fehri commented on app/components/Views/Wallet/index.tsx
> -        NftDetectionController.detectNfts();
This `useEffect` will be triggered when the user is on the wallet component. I have removed calling `detectNft()` here because instead i want to only call `detectNfts()` when the user clicks on the NFT tab. (now triggered inside `onChangeTab`)

2024-06-19 11:20 UTC, sahar-fehri commented on app/core/Engine.ts
> +        useNftDetection: true, // set this to true to enable nft detection by default to new users
Yes it was. I cannot find a thread regarding this but it is something that we have discussed internally to be done as part of the removal of the 3 mins polling logic;
cc @alfeng6 🙏

2024-06-19 11:22 UTC, sahar-fehri commented on app/components/UI/CollectibleDetectionModal/index.tsx
> +    void (async () => {
Sorry i did notice that the pipeline is failing with a lint issue here, did i miss something?

2024-06-19 11:34 UTC, sahar-fehri commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.tsx
> +  const walletImage = require('../../../images/wallet-alpha.png'); // eslint-disable-line
I have pushed that require up before the function declaration!

2024-06-19 14:02 UTC, tommasini commented on app/components/UI/CollectibleDetectionModal/index.tsx
> +    void (async () => {
It was flagged hmmm will resolve this

2024-06-19 14:15 UTC, tommasini commented on app/components/Views/Wallet/index.tsx
> -        NftDetectionController.detectNfts();
Awesome thanks!

2024-06-19 14:17 UTC, tommasini commented on patches/@metamask+assets-controllers+26.0.0.patch
>    * Controller that passively polls on a set interval for NFT auto detection
I'm working on the update of Assets controllers to v30 could you update this branch on core with this change? 
Branch: `patch/mobile-assets-controllers-v30'`

2024-06-20 17:48 UTC, brianacnguyen submitted a review, later dismissed

2024-06-21 00:23 UTC, cortisiko commented
After discussing with Sahar, we notice the bug I reported [here](https://github.com/MetaMask/metamask-mobile/pull/9857#issuecomment-2177291176) exists on main. A [ticket](https://github.com/MetaMask/metamask-mobile/issues/10057) was created.

2024-06-21 18:10 UTC, cortisiko submitted a review, later dismissed
this is ✅ from an e2e perspective.

2024-06-24 13:17 UTC, NicolasMassart commented on app/components/UI/CollectibleContracts/index.test.tsx
> +  it('Should show spinner if nfts are still being fetched', async () => {
Follow contribution guidelines for test naming please.
```suggestion
  it('Should show spinner if nfts are still being fetched', async () => {
```

2024-06-24 13:17 UTC, NicolasMassart commented on app/components/UI/CollectibleContracts/index.test.tsx
> +  it('Should not show spinner if nfts are not still being fetched', async () => {
```suggestion
  it('Does not show spinner if nfts are not still being fetched', async () => {
```

2024-06-24 13:17 UTC, NicolasMassart commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.test.tsx
> +  it('should call setUseNftDetection and setDisplayNftMedia when clicking on allow button with nftDisplayMedia initially off', () => {
```suggestion
  it('calls setUseNftDetection and setDisplayNftMedia when clicking on allow button with nftDisplayMedia initially off', () => {
```

2024-06-24 13:17 UTC, NicolasMassart commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.test.tsx
> +  it('should call setDisplayNftMedia when clicking on allow button if displayNftMedia if on', () => {
```suggestion
  it('calls setDisplayNftMedia when clicking on allow button if displayNftMedia if on', () => {
```

2024-06-24 13:17 UTC, NicolasMassart commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.test.tsx
> +  it('should not call setUseNftDetection nor setDisplayNftMedia when clicking on not right now button', () => {
```suggestion
  it('Does not call setUseNftDetection nor setDisplayNftMedia when clicking on not right now button', () => {
```

2024-06-24 13:17 UTC, NicolasMassart commented on app/components/Views/Wallet/index.tsx
> +    if (!useNftDetection && isOnMainnet && !isNFTAutoDetectionModalOpened) {
Q: i'm not sure to understand properly here: it seems to me that the modal will show every time we go on the wallet mainnet if we haven't allowed nft detection.
Is this right? If so, I would advise not to do that as it's going to be very annoying...
It may be ok in the security settings, even I fi would consider as a user that I should be able to cancel modal and never see it again. But on the wallet, it's dangerous.
that why I doubt I understood this properly and need you to confirm please.

2024-06-24 13:17 UTC, NicolasMassart commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.tsx
> +        trackEvent(MetaMetricsEvents.NFT_AUTO_DETECTION_MODAL_DISABLE, {
Q: here you don't set anything for the user not to have this modal after cancel each time they land on the app?

2024-06-24 13:17 UTC, NicolasMassart commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.test.tsx
> +  it('should render correctly', () => {
```suggestion
  it('render matches snapshot', () => {
```

2024-06-24 13:33 UTC, sahar-fehri commented on app/components/Views/Wallet/index.tsx
> +    if (!useNftDetection && isOnMainnet && !isNFTAutoDetectionModalOpened) {
Hey @NicolasMassart  👋 , It won't show everytime. The modal will appear only once, and the user will not see it again.
The user can should to dismiss or allow the NFT autodetection, but regardless, the modal will appear only once.
The check for `isNFTAutoDetectionModalOpened` should prevent that

2024-06-24 13:35 UTC, sahar-fehri commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.tsx
> +        trackEvent(MetaMetricsEvents.NFT_AUTO_DETECTION_MODAL_DISABLE, {
If i understood your question correctly, you are asking why im not setting anything when the user cancels so the modal does not appear again?
If so, The dispatch here https://github.com/MetaMask/metamask-mobile/pull/9857/files#diff-6cf3f4e9a74706082cca6f2c08153710158e6a971d42c6f7179ce4721e70bacaR292 should prevent the modal from appearing again. Regardless if the user clicks on cancel or allow

2024-06-24 13:49 UTC, NicolasMassart commented on app/components/Views/Wallet/index.tsx
> +    if (!useNftDetection && isOnMainnet && !isNFTAutoDetectionModalOpened) {
I think the name "isNFTAutoDetectionModalOpened" is what confused me. Something like "isNFTAutoDetectionModalViewed" would be clearer for me. "opened" it's not clear if it's just checking if it's currently already open or not or if it opened once before. I thought it was a value to make sure you don't open two at the same time.
I would advise for something that indicates the user actually already viewed it once.

2024-06-24 13:53 UTC, NicolasMassart commented on patches/@metamask+assets-controllers+30.0.0.patch
I'm not sure how to review a big patch like this.
Is there a PR with your changes on the source code on the core repos I could check?
This "compiled" code is not meant to be read by humans.

2024-06-24 14:01 UTC, sahar-fehri commented on patches/@metamask+assets-controllers+30.0.0.patch
Yes! this is the core PR https://github.com/MetaMask/core/pull/4281 🙏 
Note: This patch keeps NFTDetection controller extending the polling controller while the PR makes it extend BaseController but it makes sure the polling is not triggered anymore in the client code.
It will be fully updated in newer versions of assets-controllers

2024-06-24 14:02 UTC, sahar-fehri commented on app/components/Views/Wallet/index.tsx
> +    if (!useNftDetection && isOnMainnet && !isNFTAutoDetectionModalOpened) {
Yes, totally, apologies for the confusion will update the naming to `isNFTAutoDetectionModalViewed` 🙏

2024-06-24 17:01 UTC, bergeron submitted a review, later dismissed
tested all the scenarios successfully.  new user, existing user, the modal, sending requests when clicking the nft tab, verifying http requests are respecting cache

2024-06-25 08:05 UTC, sahar-fehri commented on patches/@metamask+assets-controllers+30.0.0.patch
> +       }
Removed this to remove triggering the start of the polling when users enable the NFT auto detection toggle

2024-06-25 08:06 UTC, sahar-fehri commented on patches/@metamask+assets-controllers+30.0.0.patch
> ++    return nftApiResponse;
The function getOwnerNfts no longer loops through all user NFTs and return them, but only fetches for a specific cursor.

2024-06-25 08:09 UTC, sahar-fehri commented on patches/@metamask+assets-controllers+30.0.0.patch
> ++    const updateKey = `${chainId}:${userAddress}`;
Added this to avoid having two ongoing NFT fetching at the same time.

2024-06-25 08:10 UTC, sahar-fehri commented on patches/@metamask+assets-controllers+30.0.0.patch
> ++        const addNftPromises = apiNfts.map(async (nft) => {
Now detectNfts function fetches the first page of user NFTs and saves it to state so it is available to display instead of waiting to fetch all user NFTs before saving to state.

2024-06-25 08:16 UTC, NicolasMassart submitted a review, later dismissed
Looks good to me.
Thanks a lot for all your effort making this review clear and solid!

2024-06-25 08:36 UTC, tommasini requested changes

2024-06-25 08:36 UTC, tommasini commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.test.tsx
> +const renderComponent = (state: any = {}) =>
Most likely this any can be typed 
We shouldn't use any anymore, it stricts all the type safety we need

2024-06-25 08:36 UTC, tommasini commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.tsx
> +/* eslint-disable @typescript-eslint/no-require-imports */
If we use the require inside the image component so we still need all this disables?

2024-06-25 08:36 UTC, tommasini commented on app/components/Views/Wallet/index.tsx
> +}: // eslint-disable-next-line @typescript-eslint/no-explicit-any
We shouldn't use any anymore, could you please type instead?

2024-06-25 08:36 UTC, tommasini commented on app/components/Views/Wallet/index.tsx
> +    (state: any) => state.security.isNFTAutoDetectionModalViewed,
Same, please use RootState type instead of any

2024-06-25 08:36 UTC, tommasini commented on e2e/selectors/Modals/NftDetectionModal.selectors.js
> +// eslint-disable-next-line import/prefer-default-export
I think we can remove this disable

2024-06-25 09:19 UTC, sahar-fehri commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.test.tsx
> +const renderComponent = (state: any = {}) =>
I thought in a test file its okay to keep the any, otherwise it will complain for missing properties that may not be relevant to the test, what do you think?

2024-06-25 10:10 UTC, tommasini commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.test.tsx
> +const renderComponent = (state: any = {}) =>
I think we can use Partial (https://www.typescriptlang.org/docs/handbook/utility-types.html)#partialtype if we just want some of the properties 🙏🏼

2024-06-25 10:24 UTC, sahar-fehri commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.test.tsx
> +const renderComponent = (state: any = {}) =>
Updated, we might want to circle back at some point in the future to the rest of test files to cleanup the "any" 🙏

2024-06-25 10:36 UTC, sahar-fehri commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.tsx
> +/* eslint-disable @typescript-eslint/no-require-imports */
After discussion this we decided to keep the disable since it would be needed if we move the require inside the <Image>

2024-06-25 10:37 UTC, tommasini commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.test.tsx
> +const renderComponent = (state: any = {}) =>
Definitely! We need to improve the Typescript coverage of the mobile app in general and set quality gates!
Step by step we reach there! These small efforts helps! Thank you a lot for addressing it!

2024-06-25 10:41 UTC, tommasini commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.test.tsx
> +    const { toJSON } = renderComponent(initialState as Partial<RootState>);
Interesting, do we need to cast this here? Just curious

2024-06-25 10:42 UTC, tommasini approved these changes, later dismissed
LGTM! Feel free to resolve the comments, or if you do any changes regarding them ping me to re approve it!
There is a lint issue on CollectibleDetectionModal

2024-06-25 10:45 UTC, sahar-fehri commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.test.tsx
> +    const { toJSON } = renderComponent(initialState as Partial<RootState>);
I added the cast because otherwise it would say something about `missing properties  AccountTrackerController, AddressBookController, AssetsContractController,,,, and 22 more.`

2024-06-25 10:48 UTC, tommasini commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.test.tsx
> +    const { toJSON } = renderComponent(initialState as Partial<RootState>);
What if where you initialise the initial state you say that is `Partial<RootState>`, would still need to cast this everywhere?

```
const initialState: Partial<RootState> = {
  engine: {
    backgroundState: {
      PreferencesController: {
        displayNftMedia: true,
      },
    },
  },
};
```

2024-06-25 11:16 UTC, sahar-fehri commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.test.tsx
> +    const { toJSON } = renderComponent(initialState as Partial<RootState>);
Yes, `Partial<RootState>` will only make optional the first level of the type properties. Would work perfectly with simple objects but since the state is nested, it would still ask for missing state properties.

I wanted to avoid creating a new type for it, but i guess we can create a "deep partial" type, to avoid having to add any properties not necessarily relevant to the test.

2024-06-25 11:21 UTC, tommasini commented on app/components/Views/NFTAutoDetectionModal/NFTAutoDetectionModal.test.tsx
> +    const { toJSON } = renderComponent(initialState as Partial<RootState>);
Thanks!! I was not aware it was only the first level of depth! Thanks for sharing that knowledge!

With this being said I will resolve this conversation since it's a test file, and will leave up to your decision!

2024-06-25 11:21 UTC, tommasini approved these changes, later dismissed

2024-06-25 15:26 UTC, cortisiko approved these changes
🌮 🌮 🌮 🌮 🌮 🌮

2024-06-25 22:16 UTC, tommasini approved these changes

2024-06-26 18:09 UTC, merged