feat: Feat/9492 add legacy middleware
MetaMask/metamask-mobile pull request #9885
Opened 2024-06-06 09:24 UTC by Cal-L

## **Description**

This PR is a carries over the changes from extension - https://github.com/MetaMask/metamask-extension/pull/24472 where new new middlewares are added and permission middleware reordered within the JSON rpc engine stack. The following changes are:
- New middleware for handling unsupported RPC methods. The only unsupported method at the moment is `eth_signTransaction`
- New middleware for handling legacy RPC methods. The only legacy RPC method where we need to preserve legacy logic is `eth_accounts`
- Moved permission middleware ahead of RPCMethodMiddleware aka user/wallet facing middleware

## **Related issues**

Fixes: #9492 

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-06 09:27 UTC, Cal-L commented on app/core/RPCMethods/utils.ts
Tests are captured in `createLegacyMethodMiddleware`, which utilizes these functions

2024-06-06 09:28 UTC, Cal-L commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> -      eth_signTransaction: async () => {
Now handled by `createUnsupportedMethodMiddleware`

2024-06-06 09:28 UTC, Cal-L commented on app/core/RPCMethods/RPCMethodMiddleware.ts
> -      eth_accounts: getEthAccounts,
Now handled by `createLegacyMethodMiddleware`

2024-06-07 12:08 UTC, tommasini submitted a review, later dismissed
This is awesome! LGTM! Just left one nit pick and one thought!

2024-06-07 12:08 UTC, tommasini commented on app/core/RPCMethods/createUnsupportedMethodMiddleware/index.ts
> +    if ((UNSUPPORTED_RPC_METHODS as Set<string>).has(req.method)) {
Would this make it more type safety? For me it's okay to go like this, just wondering 
It also increases the burden of adding new unsupported rpc methods in two places (The set constant and the type here)

```suggestion
    if ((UNSUPPORTED_RPC_METHODS as Set<'eth_signTransaction'>).has(req.method)) {
```

2024-06-10 23:23 UTC, rekmarks requested changes
This looks good! Just one minor issue: I'm confused by a comment and would like to clarify that first before approving.

2024-06-10 23:23 UTC, rekmarks commented on app/core/RPCMethods/createUnsupportedMethodMiddleware/index.ts
> +    if ((UNSUPPORTED_RPC_METHODS as Set<string>).has(req.method)) {
The problem is that `UNSUPPORTED_RPC_METHODS` is of type `Set<'eth_signTransaction'>` while `req.method` is `string`. The code is good as-is.

2024-06-10 23:23 UTC, rekmarks commented on app/core/RPCMethods/utils.ts
> +  if (missingHookNames.length > 0) {
We should keep it; it's better to be explicit. `.length > 0` unambiguously communicates that we're looking for non-empty arrays. We should avoid relying on JavaScript's boolean coercion logic when possible.

2024-06-10 23:23 UTC, rekmarks commented on app/core/RPCMethods/utils.ts
> +  if (extraneousHookNames.length > 0) {
See above.

2024-06-10 23:23 UTC, rekmarks commented on app/core/RPCMethods/utils.ts
> +            // @ts-expect-error JsonRpcId (number | string | void) doesn't match PS middleware's id, which is (string | number | null)
PS = permission system?

```suggestion
            // @ts-expect-error JsonRpcId (number | string | void) doesn't match the permission middleware's id, which is (string | number | null)
```

2024-06-10 23:25 UTC, rekmarks approved these changes

2024-06-10 23:25 UTC, Cal-L commented on app/core/RPCMethods/utils.ts
> +            // @ts-expect-error JsonRpcId (number | string | void) doesn't match PS middleware's id, which is (string | number | null)
Updated

2024-06-11 00:16 UTC, Cal-L commented
Test passed on one of the latest commit with functional changes

2024-06-11 00:36 UTC, tommasini approved these changes

2024-06-11 11:10 UTC, christopherferreira9 commented
This is currently breaking the SDKs. We're investigating internally what's causing the issue.

2024-06-12 09:20 UTC, abretonc7s approved these changes
LGTM

2024-06-12 09:25 UTC, christopherferreira9 commented
> This is currently breaking the SDKs. We're investigating internally what's causing the issue.
> 
>  Screen.Recording.2024-06-11.at.11.58.37.mov



> This is currently breaking the SDKs. We're investigating internally what's causing the issue.
> 
>  Screen.Recording.2024-06-11.at.11.58.37.mov

After verifying that the issue was not present on main I've re-checked with a clean build from both the SDk side and wallet and it is working properly. I've sorry for the wrong warning. All good from our side.

2024-06-12 16:28 UTC, merged