test: 1454 refactor modal pages batch 4
MetaMask/metamask-mobile pull request #9915
Opened 2024-06-10 12:08 UTC by SamuelSalas

## **Description**

We are aiming to refactor the page objects in the modal folder so that they strictly follow the page object model pattern. This would aide in providing more readable and help standardize the way we create our tests. Because of the amount of files inside of the modal folder, the scope was divided into a batch of 4.

Files inside the scope for this batch:

SigningModal.js
SkipAccountSecurityModal.js
TermsOfUseModal.js
WalletActionsModal.js
WhatsNewModal.js

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-10 16:26 UTC, brianacnguyen approved these changes, later dismissed
Checked in with @cortisiko regarding testID changes. approved

2024-06-10 16:28 UTC, cortisiko requested changes
Before I review this, can you post test results from appium? thanks

2024-06-10 18:52 UTC, SamuelSalas commented
@cortisiko Appium test run:
/wdio/features/Performance/WarmStartPerformance.feature: Failed because it was not able to find element ("//*[@text='CONNECT']"). Most likely a scroll is missing
/wdio/features/Performance/ColdStartLaunchTimes.feature: 
[0-24] The Launch time is: 16274
[0-24] Error in "1: Then the app should launch within "14" seconds"
Error: expect(received).toBeLessThan(expected)
Expected: < 14000
Received:   16274

2024-06-10 18:53 UTC, SamuelSalas commented
Detox test: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/e36a4091-c27e-4e04-ada8-e5b0704c1711

2024-06-11 19:32 UTC, Cal-L commented on e2e/viewHelper.js
> -  await TermsOfUseModal.isDisplayed();
Is this style of Assertion recommended moving forward?

2024-06-11 19:33 UTC, Cal-L commented
> Detox test: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/e36a4091-c27e-4e04-ada8-e5b0704c1711

Tests are failing

2024-06-13 16:49 UTC, SamuelSalas commented
Regression test passed: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/3f1ad255-2273-4fe2-930c-1644bbdf3a40
Smoke test passed: https://app.bitrise.io/app/be69d4368ee7e86d/pipelines/6dca24ea-3893-4678-8919-f02d7707ee7e
Performance test failed: https://app.bitrise.io/build/3d494380-28cd-48d5-a547-c5899d417db7

Cold performance test because the actual time is bigger than the expected time. I'll create an issue where it can be investigated why the increase of this time.
Warm performance test is failing because of some steps are missing. I'll create an issue where this can be resolved.

cc: @chrisleewilcox @cortisiko @Cal-L

2024-06-13 16:50 UTC, SamuelSalas commented on e2e/viewHelper.js
> -  await TermsOfUseModal.isDisplayed();
Yes, we have been using this implementation so far

2024-06-13 17:01 UTC, SamuelSalas commented on e2e/viewHelper.js
> -  await TermsOfUseModal.isDisplayed();
If there's a better approach, i think the team would have any issue to integrate it.

2024-06-13 18:00 UTC, chrisleewilcox approved these changes
LGTM

2024-06-13 20:32 UTC, Cal-L commented on e2e/viewHelper.js
> -  await TermsOfUseModal.isDisplayed();
Sounds good

2024-06-13 20:34 UTC, Cal-L commented
> Cold performance test because the actual time is bigger than the expected time. I'll create an issue where it can be investigated why the increase of this time.
> Warm performance test is failing because of some steps are missing. I'll create an issue where this can be resolved.

@SamuelSalas  Could  you provide some insight on why the refactor would result in slower tests? This tells me that we should not rely on these performance tests since the times are easily affected by test changes and not actual loading times.

2024-06-14 15:16 UTC, cortisiko approved these changes
✅ ✅

2024-06-14 17:45 UTC, merged