test: add e2e checking the enhance experience bottom sheet is showing when expected, dismiss and confirm it's dimissed
MetaMask/metamask-mobile pull request #9955
Opened 2024-06-12 15:13 UTC by jonybur

## **Description**

## **Related issues**

Fixes:

## **Manual testing steps**

1. Go to this page...
2.
3.

## **Screenshots/Recordings**

### **Before**

### **After**

## **Pre-merge author checklist**

- [ ] I’ve followed [MetaMask Contributor Docs](https://github.com/MetaMask/contributor-docs) and [MetaMask Mobile Coding Standards](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/CODING_GUIDELINES.md).
- [ ] I've completed the PR template to the best of my ability
- [ ] I’ve included tests if applicable
- [ ] I’ve documented my code using [JSDoc](https://jsdoc.app/) format if applicable
- [ ] I’ve applied the right labels on the PR (see [labeling guidelines](https://github.com/MetaMask/metamask-mobile/blob/main/.github/guidelines/LABELING_GUIDELINES.md)). Not required for external contributors.

## **Pre-merge reviewer checklist**

- [ ] I've manually tested the PR (e.g. pull and build branch, run the app, test code being changed).
- [ ] I confirm that this PR addresses all acceptance criteria described in the ticket it closes and includes the necessary testing evidence such as recordings and or screenshots.

2024-06-12 15:24 UTC, NicolasMassart submitted a review, later dismissed
Looks good to me: this cherry pick matches the original commit.

2024-06-12 19:07 UTC, sethkfman approved these changes, later dismissed
LGTM

2024-06-13 05:35 UTC, cortisiko requested changes

2024-06-18 03:33 UTC, cortisiko submitted a review, later dismissed

2024-06-18 07:37 UTC, cortisiko commented
closing in favor of https://github.com/MetaMask/metamask-mobile/pull/10021

2024-06-18 07:37 UTC, closed without merging